### ISSUE TITLE
Redux-form warnings are not displayed

### ISSUE THREAD

**Issue by djhi** [marmelab/react-admin#1000]
We currently use the [`TextField`](http://www.material-ui.com/#/components/text-field) from MUI to wrap all the inputs and its `errorText` prop to show *errors*.

However, we don't display the *warnings*. It should be as simple as getting the warnings from props and adjust the styles if any.

Original issue from SO: https://stackoverflow.com/questions/46036622/does-redux-form-field-warnings-work-in-admin-on-rest-inputs

**Comment by djhi** [comment]
We switched to final-form which does not support warnings by default.
As there is not much demand about this, let's close it

**Comment by kopax** [comment]
Hello, just to say that I was also looking for the same feature and found this. hopefully, this can still be done with a little verbosity.
