### ISSUE TITLE
Documentation: Unable to change version 

### ISSUE THREAD

**Issue by arimet** [marmelab/react-admin#10015]
**What you were expecting:**
Change the documentation version via the selector

**What happened instead:**
The selector no longer opens when the documentation is below 4.14.

**Steps to reproduce:**
Go in this page: https://marmelab.com/react-admin/doc/4.14/Authentication.html
Change documentation version to 4.13
Once this is done, you can no longer change the version.

**Related code:**

There is an error in the console that talks about `ra-doc-exec`.
`ra-doc-exec.js:323 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at ra-doc-exec.js:323:5`

**Comment by djhi** [comment]
Fixed by #10016
