### ISSUE TITLE
TabbedForm has Error: Maximum update depth exceeded.

### ISSUE THREAD

**Issue by Stonek79** [marmelab/react-admin#10032]
I have a TabbedForm component like this:

```
return (
        <Create>
            <TabbedForm
                tabs={
                    <TabbedFormTabs variant="scrollable" scrollButtons="auto" />
                }
                onSubmit={(e) => {
                    console.log(e)
                }}
            >
                <TabbedForm.Tab label="Tab 1">
                    <Box>
                        <TextInput source="field1_1" label="Field 1.1" />
                        <TextInput source="field1_2" label="Field 1.2" />
                        <TextInput source="field1_3" label="Field 1.3" />
                        <TextInput source="field1_4" label="Field 1.4" />
                        <TextInput source="field1_5" label="Field 1.5" />
                    </Box>
                </TabbedForm.Tab>
                <TabbedForm.Tab label="Tab 2">
                    <Box>
                        <TextInput source="field2_1" label="Field 2.1" />
                        <TextInput source="field2_2" label="Field 2.2" />
                        <TextInput source="field2_3" label="Field 2.3" />
                        <TextInput source="field2_4" label="Field 2.4" />
                        <TextInput source="field2_5" label="Field 2.5" />
                    </Box>
                </TabbedForm.Tab>
                <TabbedForm.Tab label="Tab 3">
                    <Box>
                        <TextInput source="field3_1" label="Field 3.1" />
                        <TextInput source="field3_2" label="Field 3.2" />
                        <TextInput source="field3_3" label="Field 3.3" />
                        <TextInput source="field3_4" label="Field 3.4" />
                        <TextInput source="field3_5" label="Field 3.5" />
                    </Box>
                </TabbedForm.Tab>
                <TabbedForm.Tab label="Tab 4">
                    <Box>
                        <TextInput source="field4_1" label="Field 4.1" />
                        <TextInput source="field4_2" label="Field 4.2" />
                        <TextInput source="field4_3" label="Field 4.3" />
                        <TextInput source="field4_4" label="Field 4.4" />
                        <TextInput source="field4_5" label="Field 4.5" />
                    </Box>
                </TabbedForm.Tab>
                <TabbedForm.Tab label="Tab 5">
                    <Box>
                        <TextInput source="field5_1" label="Field 5.1" />
                        <TextInput source="field5_2" label="Field 5.2" />
                        <TextInput source="field5_3" label="Field 5.3" />
                        <TextInput source="field5_4" label="Field 5.4" />
                        <TextInput source="field5_5" label="Field 5.5" />
                    </Box>
                </TabbedForm.Tab>
            </TabbedForm>
        </Create>
    )
```

**Information:**
When i use less then 24 inputs there is no error. 
But if you use more than 24 inputs, this error always appears, and it does not matter how many tabs and how many inputs are in each tab if there are more than 24 in total.

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable): 4.14
* React version: 18
* Browser: all (latest)
* Stack trace (in case of a JS error):
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at throwIfInfiniteUpdateLoopDetected (react-dom.development.js:26793:11)
    at getRootForUpdatedFiber (react-dom.development.js:7627:3)
    at enqueueConcurrentHookUpdate (react-dom.development.js:7518:10)
    at dispatchSetState (react-dom.development.js:13073:16)
    at Object.next (useFormState.ts:83:7)
    at Object.next (createSubject.ts:22:33)
    at createFormControl.ts:1165:23

**Comment by fzaninotto** [comment]
Thanks for your report. Can you please provide a link to a reproduction? You can fork the simple example StackBlitz:

- https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v5)
- https://stackblitz.com/github/marmelab/react-admin/tree/4.x/examples/simple (v4)

**Comment by oleksiisurnin** [comment]
I am experiencing an issue after upgrading from version 4 to version 5.0.5. I am using the TabbedForm component along with numerous inputs. The setup worked correctly before the upgrade, but now it is causing problems.

**Comment by fzaninotto** [comment]
@oleksiisurnin Please open a new issue and follow the issue template. We need a reproduction to be able to consider bug reports.

**Comment by Stonek79** [comment]
> Thanks for your report. Can you please provide a link to a reproduction? You can fork the simple example StackBlitz:
> 
> * https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v5)
> * https://stackblitz.com/github/marmelab/react-admin/tree/4.x/examples/simple (v4)

Thanks for feedback! 
I can't reproduce the same error with your examples, component works correct. 
Perhaps the error is related to the fact that I am using a component in a nextjs project. Have u any templates with NextJS to try it there?

**Comment by adguernier** [comment]
I'm afraid we do not provide a template for NextJS. But NextJS provides a [sandbox](https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template) in which you can add react-admin and try to reproduce the issue you're facing.

**Comment by adguernier** [comment]
Related to #10068

**Comment by djhi** [comment]
Closed as duplicate
