### ISSUE TITLE
DataInput with parse function: date.toISOString is not a function

### ISSUE THREAD

**Issue by ibraym** [marmelab/react-admin#10030]
**What you were expecting:**
I just tried to use the DateInput and save the date timestamp instead of Date object. According to documentation, [parsing-the-datetime-as-an-iso-string](https://marmelab.com/react-admin/DateInput.html#parsing-the-datetime-as-an-iso-string), The parse function takes a Date object as input and using toISOString() we can save the date as ISOString into the form state. I used Date getTime() to get the timestamp.

**What happened instead:**
The passed object to parse function is not a Date object so the code in the documentation returns date.toISOString is not a function.

**Steps to reproduce:**
```
import React from 'react';
import {
    SavedQueriesList, DateInput, FilterContext, FilterForm, FilterButton,
    ReferenceArrayInput, SelectArrayInput, SelectInput,
} from 'react-admin';
import { EventType, EventStatus } from '../types';

const eventInlineFilters = [
    <DateInput
        source='created_date__gte'
        variant='filled'
        parse={(date: Date) => (date ? date.toISOString() : null)}
    />,
];

const EventFilterSidebar = (): JSX.Element => (
    <>
        <SavedQueriesList />
        <FilterContext.Provider value={eventInlineFilters}>
            <FilterForm />
            <FilterButton />
        </FilterContext.Provider>
    </>
);
```

**Environment**

* React-admin:  5.0.3
* React version:  18.3.1
* Browser: Microsoft Edge
* Stack trace (in case of a JS error):

date.toISOString is not a function
TypeError: date.toISOString is not a function
    at Object.parse [as current] (http://localhost:3000/static/js/bundle.js:10969:30)
    at http://localhost:3000/static/js/bundle.js:128532:24
    at Object.current (http://localhost:3000/static/js/bundle.js:124591:38)
    at http://localhost:3000/static/js/bundle.js:128532:24
    at handleChange (http://localhost:3000/static/js/bundle.js:37823:7)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:164111:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:164155:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:164212:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:164226:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:168369:7)

**Comment by ibraym** [comment]
Using the following code, I can confirm that the object passed to parse function is a string and not a Date object

```
<DateInput
        source='created_date__gte'
        variant='filled'
        parse={(date: Date) => (date ? console.log(typeof(date)) : null)}
    />,
```

**Comment by ibraym** [comment]
It is resolved by using the following parse function
`parse={(date: Date) => (date ? new Date(date).getTime() : null)}`

**Comment by fzaninotto** [comment]
I'm not sure I understand your problem, and it seems you have fixed it, so I'm closing the issue. Feel free to comment if you think something needs fixing in the react-admin code or doc.

**Comment by npbassett** [comment]
@fzaninotto the documentation related to [parsing dates from DateInput](https://marmelab.com/react-admin/DateInput.html#parsing-the-datetime-as-an-iso-string) states that the parse function is given a `Date` object. The documentation provides the following example:
```
<DateInput
    source="published"
    parse={(date: Date) => (date ? date.toISOString() : null)}
/>
```
However, using the provided example code produces the error `date.toISOString is not a function` because the parse function is given a `string` not a `Date`. The documentation should be updated to reflect this.

**Comment by fzaninotto** [comment]
This piece of documentation if for the Enterprise version of DateInput. Are you using the open-source of the Enterprise version?
