### ISSUE TITLE
Current page of list view should not be silently preserved

### ISSUE THREAD

**Issue by lukecyca** [marmelab/react-admin#10058]
**What you were expecting:**
When opening a new browser window, navigating to the application, and then to a List, I expect to see the first page.

**What happened instead:**
Instead, I get whatever page I was previously looking at in a previous session.

**Steps to reproduce:**

1. https://marmelab.com/react-admin-demo/
2. Click "Invoices"
3. Click page 2
4. Close the browser window, open a new one, and navigate to https://marmelab.com/react-admin-demo/
5. Click "Invoices"

You see page 2 instead of page 1.

What's worse, is that it's not immediately clear because there is no indication on the screen (or in the URL) that you are on page 2. The only indication is "below the fold" and you need to scroll down to see it.

**Other information:**

In my opinion, clicking the "Invoices" link in the left-side navigation should always return you to the first page of the list view. This is standard behaviour (try paging through the list of issues in GitHub, and then click the "Issues" link at the top of the page, for example).

If the user is on a non-default page (that is, a page other than the first) then the URI should always reflect this (it should be in a query string, for example).

Certainly, opening a brand new browser window and navigating to the list view should always go to the first page.

**Environment**

* React-admin version: I am using 4.8.0, but the issue is also present in whatever version is currently running on [the demo](https://marmelab.com/react-admin-demo/)
* Browser: Chrome 126.0.6478.127

**Comment by djhi** [comment]
That's actually a feature :) See https://marmelab.com/react-admin/List.html#storekey
