### ISSUE TITLE
Cli does not show anything

### ISSUE THREAD

**Issue by An88ton** [marmelab/react-admin#10065]
I use react-admin of version 5.0.5 and Windows 11, when I run "npm init react-admin test-admin" as described in the tutorial, cli does not show any options, but when I press Ctrl+C it shows current step.
![image](https://github.com/user-attachments/assets/23c41d51-b06d-4854-a462-2bf160639820)
![image](https://github.com/user-attachments/assets/da41c58a-2306-4a58-a231-69f2905d2415)

**Comment by fzaninotto** [comment]
The CLI isn't tested on Windows, so I guess the problem comes from there. 

Do you manage to run other `create-` packages, e.g. for Next.js, Vite, or Remix?

**Comment by slax57** [comment]
I just tested on my Windows machine (running Windows 10), with both PowerShell and CMD, and everything worked first try. The CLI was rendered along with all the options.

**Versions:**
create-react-admin@5.1.1
node v18.18.2
npm 9.8.1

What are your versions of node and npm?
Can you try with the latest version of create-react-admin?

**Comment by fzaninotto** [comment]
No news for some time, closing.
