### ISSUE TITLE
Documentation search is broken on versions < latest (v5.05)

### ISSUE THREAD

**Issue by sa3dany** [marmelab/react-admin#10089]
**What you were expecting:**
Search to be working for all available React Admin versions

**What happened instead:**
Search is non-functional (always no results returned for any search query) for versions below the laters version (v5.05)

**Steps to reproduce:**
1. Visit [https://marmelab.com/react-admin/doc/4.16/Readme.html](https://marmelab.com/react-admin/doc/4.16/Readme.html)
2. Open the search dialog (by clicking the search input or using the shortcut key)
3. Enter any input
    <img width="500" alt="image" src="https://github.com/user-attachments/assets/274dfa75-ce39-41e2-89b0-a79fad13099f">

**Environment**

* Browser: Safari 17.5 and Brave 1.68.128 (Chromium 127.0.6533.73)

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback. We are aware that the search engine only works for the latest version. 

Configuring the search engine for multiple versions isn't straightforward (or maybe possible for a statically generated site like our docs). We made the choice not to do it.
