### ISSUE TITLE
Nested ArrayInput saves all values to undefined

### ISSUE THREAD

**Issue by oleksiisurnin** [marmelab/react-admin#10090]
**Description:**
When using nested ArrayInput components in a form, the second array saves all values to undefined. The issue can be observed in the console output, where the formData structure shows the nested array values as undefined.

**Code Example:**
```
<ArrayInput source="array_in_array">
    <SimpleFormIterator inline>
        <ArrayInput>
            <SimpleFormIterator inline>
                <TextInput source='name' />
                <FormDataConsumer>
                    {({ formData }) => {
                        console.log(formData);

                        return null;
                    }}
                </FormDataConsumer>
            </SimpleFormIterator>
        </ArrayInput>
    </SimpleFormIterator>
</ArrayInput>
</SimpleForm>
```

**Observed Behavior:**
The formData structure in the console log shows that the second array's values are all saved under undefined.

**Expected Behavior:**
The nested array should correctly save its values and be represented properly in the formData structure.

**Screenshot:**
![image](https://github.com/user-attachments/assets/057d81b5-258a-44ba-8acd-ddd743a2413f)

**Steps to Reproduce:**
1. Use the provided code in a form.
2. Fill in the nested array fields.
3. Observe the console output for the formData structure.

**Environment:**
- React-admin version: 5.0.5
- React version: 18
- Browser: All

**Additional Context:**
This bug makes it difficult to use nested arrays in forms, as the data is not saved correctly. Any help or guidance on resolving this issue would be greatly appreciated.

repo: https://github.com/oleksiisurnin/react-admin-nested-array-input-bug

**Comment by djhi** [comment]
This use case is not supported, you'll have to create your own input
