### ISSUE TITLE
Incorrect index display in PrevNextButtons component on pagination navigation

### ISSUE THREAD

**Issue by Odacchi** [marmelab/react-admin#10136]
**What you were expecting:**

When navigating to the show page from the second page or later in a paginated list, the `PrevNextButtons` component should display the correct index considering the current page number.

**What happened instead:**

The `PrevNextButtons` component does not display the correct index when navigating to the show page from the second page or later. The current page number is not considered in the index calculation.

**Steps to reproduce:**

1. Navigate to the [official react-admin demo site](https://marmelab.com/react-admin-demo/#/orders).
2. Go to the second page.
3. Click on an order to navigate to the show page.
4. Observe that the `PrevNextButtons` component displays an incorrect index.

**Related code:**

This issue can be reproduced on the official react-admin demo site: https://marmelab.com/react-admin-demo/#/orders

**Other information:**

Here is a video capture illustrating the issue:

[Video Capture: Incorrect index display on second page](https://github.com/user-attachments/assets/e0b2e26a-873e-47e9-94dc-a16e929ce9ac)

Our team has also reproduced this issue using react-admin v5.1.1 (React v18.3) and v4.11.x (React v18.2). The issue occurs on Chrome version 127.0.6533.89.

Additionally, it seems that the index value returned by the `usePrevNextController` hook used inside `PrevNextButtons` is already incorrect. The `PrevNextButtons` component appears to simply display `index + 1`.

**Environment**

* React-admin version: 5.1.1, 4.11.x
* Last version that did not exhibit the issue (if applicable):
* React version: 18.3, 18.2
* Browser: Chrome 127.0.6533.89
* Stack trace (in case of a JS error): N/A (No error is thrown)

**Comment by djhi** [comment]
Reproduced, thanks!
