### ISSUE TITLE
ArrayInput + SimpleFormIterator no working correctly inside the TranslatableInputs component in React Admin 5.1

### ISSUE THREAD

**Issue by dany-loveevents** [marmelab/react-admin#10130]
**What you were expecting:**
I have a form in my project, that is a combination of ArrayInput + SimpleFormIterator inside TranslatableInputs component.

**What happened instead:**
In React Admin 4.x it works correctly, however in 5.1 it does not load the actual values ​​of the items and the Delete button does not remove value of the items prop.

**Steps to reproduce:**
This is the code example to reproduce the issue. 

```jsx
const OrderEdit = () => (
  <Edit>
    <SimpleForm>
      <TextInput source="customer"/>
      <TranslatableInputs locales={['en', 'fr']}>
        <ArrayInput source="items">
          <SimpleFormIterator>
            <TextInput source="name"/>
          </SimpleFormIterator>
        </ArrayInput>
      </TranslatableInputs>
    </SimpleForm>
  </Edit>
);
```
Suppose we have `order`  who has many `items`, each `item` with its respective `translations`.

```
{
    orders: [
        {
            id: 1,
            customer: 'Customer 1',
            items: [
                {
                    name: {
                        en: 'Item 1',
                        fr: 'Objet 1',
                    },
                },
                {
                    name: {
                        en: 'Item 2',
                        fr: 'Objet 2',
                    },
                },
            ],
        },
        {
            id: 2,
            customer: 'Customer 2',
            items: [
                {
                    name: {
                        en: 'Item 1',
                        fr: 'Objet 1',
                    },
                },
            ],
        },
        {
            id: 3,
            customer: 'Customer 3',
        },
    ],
}
```

**Related code:**

* Sandboxes v4 and v5 code example.
  - https://stackblitz.com/edit/github-bfjhmp?file=src%2Forders%2FOrderEdit.tsx (Edit v5) [KO]
  - https://stackblitz.com/edit/github-bfjhmp?file=src%2Fdata.tsx (Data V5)
  - https://stackblitz.com/edit/github-zv6u4m?file=src%2Forders%2FOrderEdit.tsx (Edit v4) [OK]
  - https://stackblitz.com/edit/github-zv6u4m?file=src%2Fdata.tsx (Data v4)

**Other information:**

[Issue in stackoverflow](https://stackoverflow.com/questions/78833503/arrayinput-simpleformiterator-no-working-correctly-inside-the-translatableinpu)

**Environment**

* React-admin version: 5.1.1
* Last version that did not exhibit the issue (if applicable): 4.16.18
* React version: ^18.3.1
* Browser: Chrome

**Comment by dany-loveevents** [comment]
Hi @slax57

Thanks for your reply.

I hadn't tried this solution before, I see that it works fine in v5, I've tried it in v4 but it doesn't work.

On the other hand, I was already using it in v4 as I describe in the example code. I'm trying to upgrade to v5 and I've encountered this problem.

If I try to change the way this view is displayed, the end user would stop liking it.

Could you guys look into it anyway?

**Comment by slax57** [comment]
If you really want to keep the existing UI, I still believe the data model should be updated accordingly.

I.e. replace 

```js
      items: [
        {
          name: {
            en: 'Item 1',
            fr: 'Objet 1',
          },
        },
        {
          name: {
            en: 'Item 2',
            fr: 'Objet 2',
          },
        },
      ],
```

by

```js
      items: {
        en: [{ name: 'Item 1' }, { name: 'Item 2' }],
        fr: [{ name: 'Objet 1' }, { name: 'Objet 2' }],
      },
```

If you can't perform this change in your back-end, you can leverage the [lifecycle callbacks](https://marmelab.com/react-admin/withLifecycleCallbacks.html) to do it in the front-end.

Now, since `<TranslatableInputs>` was never really designed to support an `<ArrayInput>` as child, you will also need to override the `SourceContext` to get it to work:

```tsx
import {
  Edit,
  SimpleForm,
  TextInput,
  TranslatableInputs,
  ArrayInput,
  SimpleFormIterator,
  useSourceContext,
  SourceContextProvider,
} from 'react-admin';

const SourceContextOverrider = ({ children }) => {
  const originalContext = useSourceContext();
  // Override getSource:
  // Turn 'items.0.name.en' into items.en.0.name'
  const getSource = (source: string) => {
    const originalSource = originalContext.getSource(source);
    const splits = originalSource.split('.');
    const newSource = [splits[0], splits[3], splits[1], splits[2]].join('.');
    console.log({ originalSource, newSource });
    return newSource;
  };
  const newContext = {
    getSource,
    getLabel: originalContext.getLabel,
  };
  return (
    <SourceContextProvider value={newContext}>{children}</SourceContextProvider>
  );
};

export const OrderEdit = () => (
  <Edit>
    <SimpleForm>
      <TextInput source="customer" />
      <TranslatableInputs locales={['en', 'fr']}>
        <ArrayInput source="items">
          <SimpleFormIterator>
            <SourceContextOverrider>
              <TextInput source="name" />
            </SourceContextOverrider>
          </SimpleFormIterator>
        </ArrayInput>
      </TranslatableInputs>
    </SimpleForm>
  </Edit>
);
```

With all that changes, it should work as expected while keeping the same UI as before.

You can test it live in this [Stackblitz](https://stackblitz.com/edit/github-bfjhmp-waks5h?file=src%2Forders%2FOrderEdit.tsx) (use **Order # 2** which has the correct data model).

I'm not sure this is a use-case we want to support (since it works correctly when the data model and the UI match, as per my [initial answer](https://github.com/marmelab/react-admin/issues/10130#issuecomment-2284046566)), and given I have provided a user-land solution, I'm closing this issue.

**Comment by dany-loveevents** [comment]
Fortunately, the first implementation of the backend was built to work with the format you propose, since I already used it in read admin 4.

I only had to implement the SourceContextOverrider and add it after upgrading to react admin 5.

However, it would be nice to have this if someone else needs it in the future.

Thanks for your time
