### ISSUE TITLE
Delete with 500 response does not call onError callback

### ISSUE THREAD

**Issue by papiliond** [marmelab/react-admin#10141]
React Admin version: <=5.1.1
API Platform version(s) affected: <=4.0.1

Description
I am using the `<DeleteButton />` provided by react-admin to delete a record. This API call makes my server return a 500 response, which should trigger an error notification on the frontend. Instead, I am redirected to the list page and the ra.notification.deleted is displayed.

The mutationMode is "pessimistic". I debugged the useDeleteWithConfirmController.tsx hook and i can confirm that the onSuccess method is called immediately after the deletion confirmation modal is confirmed. The onError is not called at all. 

How to reproduce
0. Make sure that calling DELETE on your api returns 500 status response. UPDATE: It happens with 4** errors, too.
2. Go to an "Edit" page and hit "Delete".
3. You will be redirected to the list page with a success notification at the bottom.

**Comment by slax57** [comment]
Thank you for your report.

I have tweaked the simple demo to reject with a 500 Error when attempting to delete a Post, and also switched to pessimistic mode, but couldn't reproduce your issue.

You can find the Stackblitz I used here: https://stackblitz.com/edit/github-vnfs54?file=src%2FdataProvider.tsx

Can you please fork it to try to reproduce your issue in there?
Thanks

**Comment by papiliond** [comment]
Closing as it was an issue in our custom httpClient.

```
const fetchHydra = async (url, options = {}) => {
  try {
    const result = await baseFetchHydra(url, {
      ...options,
      headers: getHeaders
    });

    return result;
  } catch (error) {
    if (error?.response?.status === 503) {
      setTimeout(() => {
        window.location.reload();
      }, 0);
    } else {
     // Here I had to rethrow the error.
      throw error;
    }
  }

  return null;
};
```

**Comment by papiliond** [comment]
Closing as it was an issue in our custom httpClient.

```
const fetchHydra = async (url, options = {}) => {
  try {
    const result = await baseFetchHydra(url, {
      ...options,
      headers: getHeaders
    });

    return result;
  } catch (error) {
    if (error?.response?.status === 503) {
      setTimeout(() => {
        window.location.reload();
      }, 0);
    } else {
     // Here I had to rethrow the error.
      throw error;
    }
  }

  return null;
};
```

**Comment by slax57** [comment]
Glad you could find the issue.
Thanks for the feedback.
