### ISSUE TITLE
Datagrid rows do not appear as clickable, although they are

### ISSUE THREAD

**Issue by Aikain** [marmelab/react-admin#10155]
**What you were expecting:**
When you mouse over a row in the Datagrid, the cursor should appear as a pointer if the row is clickable.

**What happened instead:**
If no rowClick is defined for the Datagrid, it will not show up as clickable, even though it is actually clickable. With version 5, rows are clickable by default if show or edit views are defined.

**Steps to reproduce:**
1) Go to stackblitz example
2) Find post "Minima ea vero omnis odit officiis aut" (or any else with comments)
3) Go to comments-tab
4) Hover rows

**Related code:**
https://stackblitz.com/edit/github-jsuk6e?file=src%2Fposts%2FPostShow.tsx

The only change from the original example is in the PostShow.tsx file, where I duplicated the comment list and added another `rowClick='show'`.

**Environment**

* React-admin version: 5.1.2
* Last version that did not exhibit the issue (if applicable): -
* React version: 18.3.1
* Browser: Google Chrome 127.0.6533.120
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Reproduced, thanks!
