### ISSUE TITLE
Material UI v6 support

### ISSUE THREAD

**Issue by olesmarola** [marmelab/react-admin#10167]
**What you were expecting:**
Material UI v6 package installed successfully

**What happened instead:**
error when try to install

**Steps to reproduce:**
```
npm i --save-dev @mui/material@6.0.0
```

**Other information:**

**Environment**

* React-admin version: 5.1.2
* Last version that did not exhibit the issue (if applicable): -
* React version: 18.3.1
* Browser: -
* Stack trace (in case of a JS error): -

**Comment by fzaninotto** [comment]
Material-ui V6 is a major version and has some breaking changes with material-ui v5. Unless we can support both versions, supporting material-ui v6 will require a major version bump for react-admin, which isn't planned before at least a year (we've just released react-admin v5). Besides, the MUI team plans on releasing v7 before the end of this year. This means we'll probably skip this release and wait for v7.

**Comment by olesmarola** [comment]
@fzaninotto Got you! Thanks for the info.

**Comment by oliviertassinari** [comment]
It might be possible to support both at the same time, MUI X pulled it off. Same here: https://github.com/KevinVandy/material-react-table/issues/1231#issuecomment-2322983508

**Comment by KevinVandy** [comment]
Material React Table is going to be shipping as a new V3, just so that other minor breaking changes can be made, but it probably could have been kept on V2.

**Comment by djhi** [comment]
Isn't it requiring at least v6? https://github.com/KevinVandy/material-react-table/blob/v3/packages/material-react-table/package.json#L110-L111

**Comment by KevinVandy** [comment]
> Isn't it requiring at least v6? https://github.com/KevinVandy/material-react-table/blob/v3/packages/material-react-table/package.json#L110-L111

Yep

**Comment by rinarakaki** [comment]
MUI v7 is surely not gonna happen before the end of this year and not even close based on their [roadmap](https://github.com/mui/material-ui/milestone/48). Please move forward to MUI v6. It makes adopting MUI v7 easier in the end.

**Comment by fzaninotto** [comment]
MUI V6 support was added in https://github.com/marmelab/react-admin/pull/10439, released in react-admin v5.5.

**Comment by cristisp** [comment]
Is there any plan to support MUI V7? It now provides support for tailwind, could be interesting to see how it would work with React Admin

**Comment by djhi** [comment]
Yes, we'll look into it

**Comment by cristisp** [comment]
Awesome! Could you create a new issue/PR to keep track of progress/conclusions on this?

**Comment by djhi** [comment]
Just tested it, it looks good: #10639
