### ISSUE TITLE
TabbedForm.Tab validation error issue

### ISSUE THREAD

**Issue by olesmarola** [marmelab/react-admin#10178]
**What you were expecting:**
The tab color changes to red if any validation error in the tab on the submit button.

**What happened instead:**
The tab color is left the same as without error.

**Steps to reproduce:**
1. install  "react-hook-form": "^7.53.0".
2. Add CustomToolbar to the TabbedForm and at least 1 input tab that is not active by default.
3. Click on the submit without touching any input.

**Related code:**
```
const CustomToolbar = props => <Toolbar {...props}>
    <SaveButton alwaysEnable />
</Toolbar>;
```

**Other information:**
https://share.cleanshot.com/ksGPlSY0

**Environment**

* React-admin version: 5.1.2
* Last version that did not exhibit the issue (if applicable): 5.1.2 without react-hook-form 7.53.0
* React version: 18.3.1
* Browser: any

**Comment by slax57** [comment]
Thanks for reporting this issue.
It is already fixed by the following PR: https://github.com/marmelab/react-admin/pull/10168
It will be released in the next patch version of React Admin.
