### ISSUE TITLE
ReferenceField style overrides don't allow to change link text colour.

### ISSUE THREAD

**Issue by victor-pluta** [marmelab/react-admin#10174]
**What you were expecting:**

```
<ReferenceField source="SomeSource" reference="SomeRef" record={record} key="some-link"
        sx={{
            [`& .RaReferenceField-link`]: {
                backgroundColor: '#fff',
                color: '#fff',
        },
                               
    }}
>
```

When using the above ReferenceFiled i would expect the children of that componenet to have a white background and a white text colour, e.g. components such as `<TextField />` 

**What happened instead:**
the children only have a white background colour and the text colour is still using the global theme

**Steps to reproduce:**
Add a reference field, add children of TextField, attempt to change the childrens link text colour, while having a global theme

**Environment**

* React-admin version: 4.16.18
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 18.3.1
* Browser: Chrome
* Stack trace (in case of a JS error): N/A

**Comment by slax57** [comment]
The `.RaReferenceField-link` class is applied to the link (`<a>` element), but the text element inside it (`<span>`) has some extra attributes set by MUI.

To target the text element (`<span>`) you need to add an extra CSS selector `.MuiTypography-root`.

```tsx
      <ReferenceField
        source="post_id"
        reference="posts"
        sx={{
          [`& .RaReferenceField-link .MuiTypography-root`]: {
            backgroundColor: '#fff',
            color: 'red',
          },
        }}
      >
        <TextField source="title" />
      </ReferenceField>
```
