### ISSUE TITLE
The contents of the 'sortLabel' tooltip are reversed in descending and ascending order.

### ISSUE THREAD

**Issue by atsfour** [marmelab/react-admin#10182]
**What you were expecting:**

he display content should match the `order` of the `ListSortContext`.

**What happened instead:**

Displayed as “descending” when in ascending order and “ascending” when in descending order

**Steps to reproduce:**

Using DataGrid to display a List, it will probably always be

**Related code:**

Perhaps the ternary operator processing on this line is reversed

https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx#L34

**Other information:**

**Environment**

* React-admin version: 4.16.19
* Last version that did not exhibit the issue (if applicable):
* React version: 18.3.1
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I don't see any bug. For me the label explains what the action will do "sort by label ascending" means what the *future* sort order will be). 

Or am I misunderstanding your report? If so, please provide a detailed repro based on the simple example stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by atsfour** [comment]
> For me the label explains what the action will do "sort by label ascending" means what the future sort order will be

I understand!
“Sort by label ascending” to mean “Change the sort to ascending order by label” and not “Sorting in ascending order by label”.
I had misunderstood the meaning of the English.

This issue is now resolved.
Thank you for the explanation!
