### ISSUE TITLE
useNotify not being called by dataprovider or from within React Query instance

### ISSUE THREAD

**Issue by sebpowell** [marmelab/react-admin#10180]
I have written a custom data provider as per the documentation found here: https://marmelab.com/react-admin/DataProviderWriting.html

Here is a simplified example of my code.

```ts
// api.service.ts
class ApiService {
  private async post(
    props: ApiServiceRequest<Request>,
  ) {

    try {
      await axios.post("https://")
    } catch (error) {
      throw new HttpError(message, status)
    }
  }
}
```

```ts
// dataprovider.ts
const dataProvider: DataProvider = {
 create: async (resource, params): Promise<CreateResult> => {
    const { data: payload } = params

    const { data: returnedData } = await apiService.post({
      endpoint: resource,
      data: payload,
    })

    return { data: returnedData }
  }
}
```

I am then making an API call inside a component like so:

```ts
// component.tsx
const [post, { isLoading }] = useCreate()

post(
  "/path",
  { data },
  {
    onSuccess: () => {
      refresh()
    },
  },
)
```

My API is returning a 406 error. The documentation states the following regarding error handling (see https://marmelab.com/react-admin/DataProviderWriting.html 'Error Format'):

```
"Besides, react-admin displays the error message on screen in a temporary notification." 
```

I would therefore expect to see a toast notification show up, but nothing shows. I can, however, get one to show if I add an `onError` callback like so:

```ts
const [post, { isLoading }] = useCreate()

post(
  "/path",
  { data },
  {
    onSuccess: () => {
      refresh()
    },
    // Adding this shows a message as expected.
    onError: (e) => {
      notify(e.message, { type: 'error' })
    },
  },
)
```

But ideally, I don't want to have to do this in every component, and according to the documentation (?) I shouldn't have to.

I then tried configuring the React Query instance to handle this globally, like so:

```ts
const useCustomQueryClient = () => {
  const notify = useNotify()

  return new QueryClient({
    defaultOptions: {
      mutations: {
        onError: (error: unknown) => {
          console.log(error)
          notify("Test", { type: 'error' })
        },
      },
    },
  })
}
```

This doesn't work either – I see the `console.log`, but the notification doesn't show up. 

The fact the error shows up when `useNotify` is called within the component suggests to me the errors are bubbling up properly from within the data provider (as is the fact that I am seeing the console.log I added to my React Query instance). 

The issue therefore, seems to be that `useNotify` isn't able to display messages when called from within the React Query instance, and a notification isn't automatically created by the data provider on error. 

As mentioned above, the documentation appears to imply that this will take place, so unsure whether this is a bug, or whether I've simply not understood what the expected behaviour is.

I am using React-Admin 4.16.10. 

Any help / advice would be gratefully received, thank you in advance.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
