### ISSUE TITLE
Values of InputFields are not displayed in edit form if shouldUnregister is set

### ISSUE THREAD

**Issue by AlexDroll** [marmelab/react-admin#10194]
**What you were expecting:**
In an EditForm with an ArrayInput all input fields show the given record values. This also holds for conditionally rendered field values if the condition is fullfilled and the `shouldUnregister` property is set to `true`.

**What happened instead:**
Having the following complex EditForm.
There is an ArrayInput. 
One field of the array elements is only conditionally rendered depending on the value of another. Then the value of the conditionally rendered input field is not displayed (even though the field itself is rendered). This only happens if the `shouldUnregister` property is set to true for the conditionally rendered input field.

We just upgraded from react-admin@4.16.20 (where everything worked) to react-admin@5.1.3 where the bug occurs. In both cases we use react-hook-form@7.53.0 

<img src="https://github.com/user-attachments/assets/22aea8d2-c897-4420-bb20-ee5689a87b5a" width="300">

**Steps to reproduce:**
Open [this code sandbox](https://stackblitz.com/edit/github-ijv3mw?file=src%2Fcomments%2FCommentEdit.tsx). 
Go to the comments records and open one of the comments. The value in the field "Bar" is not shown even though we would expect to see "world" there. If the "shouldUnregister" property is removed in the `CommentEdit.tsx` (line 166) the value is displayed correctly. However, then we would lose the unregister functionality of the field.

Hint: Starting from the provided example code sandbox for v5 we only changed the `data.tsx` and `CommendEdit.tsx` to provide the example.

**Environment**

* React-admin version: 5.1.3
* Last version that did not exhibit the issue (if applicable): 4.16.20
* React version: 18.3.1
* Browser: Chrome, Firefox

**Comment by AlexDroll** [comment]
Do you have an update on the issue? Or do you have a timeline when working on it?
Thanks!

**Comment by djhi** [comment]
No but feel free to lend a hand

**Comment by slax57** [comment]
We may have found a solution (see https://github.com/marmelab/react-admin/pull/10271) that seems to fix this particular issue.
However, we also had to warn against this usage in the docs, as react-[hook-form themselves](https://react-hook-form.com/docs/usecontroller#props) do so:

> shouldUnregister
> Note: this prop should be avoided when using with useFieldArray as unregister function gets called after input unmount/remount and reorder.

The most durable solution might be to use the [`transform`](https://marmelab.com/react-admin/Edit.html#transform) prop instead to manually clean the submitted values.

**Comment by slax57** [comment]
In the end we reverted the change to `useAugmentedForm`, because it may have undesired side-effects. Besides, this seems to be a react-hook-form issue/limitation, so we don't believe we should try to fix it in react-admin.
Instead, the doc now encourages to use the [transform](https://marmelab.com/react-admin/Edit.html#transform) prop instead.
