### ISSUE TITLE
[Demo] Input fields are broken after switching themes

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#10219]
**What you were expecting:**

The inputs should not be broken after switching themes

**What happened instead:**
<img width="712" alt="Screenshot 2024-09-17 at 6 05 29 PM" src="https://github.com/user-attachments/assets/a7c72953-aa31-4d50-a76f-417714475bfe">

**Steps to reproduce:**

Go to
https://marmelab.com/react-admin-demo/#/customers/247

Switch theme from **soft** to **default*, or switch theme from **default** to **soft** will trigger the bug.

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v5)
  - https://stackblitz.com/github/marmelab/react-admin/tree/4.x/examples/simple (v4)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: latest demo
* Last version that did not exhibit the issue (if applicable): N/A
* React version:
* Browser: Safari 17.5
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for the report. This is an issue we've been aware of for quite some time, and I believe the root cause is in MUI itself, as we haven't been able to find the cause in our code. 

Can you try and reproduce it with pure MUI, without react-admin?
