### ISSUE TITLE
Dataprovider for Supabase GQL (pg_graphql): ra-data-graphql-simple

### ISSUE THREAD

**Issue by maxschridde1494** [marmelab/react-admin#10210]
I recently decided to test out [supabase](https://supabase.com/) for a quick microservice my team was spinning out. We use `react-admin` for a lot of custom dashboards so I decided to run with `vite`, `react-admin` and `cloudflare pages` on the front end. The combo of `supabase` and `react-admin` proved to be a dangerous one--fast, flexible, powerful. I also wanted to try out the auto generated `supabase` GQL interface (via [pg_graphql](https://supabase.github.io/pg_graphql/)). I noticed there is a REST `supabase` dataprovider in [ra-supabase](https://github.com/marmelab/ra-supabase), but couldn't find a GQL dataprovider so I went ahead and wrote one ([repo here](https://github.com/maxschridde1494/ra-data-graphql-supabase)). 

My question is whether I should create a PR here for a new `ra-data-graphql-supabase` pkg OR just get it listed under the community dataproviders? I wrote it with the intention of a PR. With this in mind, I followed the contributions guide. I forked `ra-data-graphql-simple`, modified it to support `supabase`, enhanced / wrote more verbose test coverage, and have the linters running. I have one outstanding issue regarding the dynamic generation of introspectionResults via the `pg_graphql` introspection schema, but I expect to knock that out tomorrow. Thoughts?

**Comment by djhi** [comment]
Hi, thank you for contributing a new dataProvider! The preferred approach is to publish it yourself and make a PR to add to the community providers.

**Comment by maxschridde1494** [comment]
Thanks for the response @djhi. So this is a PR on documentation or somewhere else?
