### ISSUE TITLE
The correct usage of `Auth0` with `react-admin`

### ISSUE THREAD

**Issue by sheriff-rango** [marmelab/react-admin#10235]
I am building Admin Dashboard using `react-admin`.  
Now I would like to add signup/login via `Auth0`.  

`App.js`  

    import React from "react";
    import { Admin, resolveBrowserLocale } from "react-admin";
    import authProvider from "./providers/auth/authProvider";
    import dataProvider from "./providers/data/dataProvider";

    const App = () => {

	    return (
		    <Admin
			locale={resolveBrowserLocale()}
    	        dataProvider={dataProvider}
	    		authProvider={authProvider}
    		>
			    ........
    		</Admin>
    	);
    };
    export default App;

`authProviders.js`

    import { Auth0Client } from "@auth0/auth0-spa-js";
    import { Auth0Constants } from "../../config";
    import { Auth0AuthProvider } from "ra-auth-auth0";

    const auth0 = new Auth0Client({
    	domain: Auth0Constants.domain,
    	clientId: Auth0Constants.clientId,
    	cacheLocation: "localstorage",
    });
    const authProvider = Auth0AuthProvider(auth0, {
    	loginRedirectUri: window.location.origin,
    });

    export default authProvider;

`index.js`

    import React from "react";
    import ReactDOM from "react-dom/client"; // Update this import
    import "./index.css";
    import App from "./App";
    import * as serviceWorker from "./serviceWorker";
    import { Auth0Provider } from "@auth0/auth0-react";
    import { Auth0Constants } from "./config";

    // Create a root element
    const root = ReactDOM.createRoot(document.getElementById("root"));

    // Render your app using the createRoot method
    root.render(
	    <React.StrictMode>
	    	<Auth0Provider
	    		domain={Auth0Constants.domain}
	    		clientId={Auth0Constants.clientId}
	    		authorizationParams={{
	    			redirect_uri: window.location.origin,
		    	}}
		    >
			    <App />
    		</Auth0Provider>
	    </React.StrictMode>
    );

    serviceWorker.unregister();

But when I accesss the `localhost:3000`, it keeps reloading...
I am not sure what is the problem.
Is there anyone who will help me with this stuff?

Thanks in advance.

**Comment by erwanMarmelab** [comment]
Hello @sheriff-rango,

At first, I'm really not sure you need to wrap your app in an `<Auth0Provider>`. Could you please remove it and feedback us if it works?

You can check the [react-admin's demo with Auth0](https://github.com/marmelab/ra-auth-auth0/tree/main/packages/demo-react-admin) to better understand. 
Moreover, in this example we don't wrap the `<App>` in a `<Auth0Provider>` (cf [App.tsx#L35](https://github.com/marmelab/ra-auth-auth0/blob/main/packages/demo-react-admin/src/App.tsx#L35))

Best regards,

**Comment by erwanMarmelab** [comment]
https://dev.to/master_shifu/the-correct-usage-of-auth0-with-react-admin-349d

**Comment by fzaninotto** [comment]
Please open an issue in the `ra-auth-auth0` repository. 

https://github.com/marmelab/ra-auth-auth0

**Comment by kollucharan** [comment]
> I am building Admin Dashboard using `react-admin`. Now I would like to add signup/login via `Auth0`.
> 
> `App.js`
> 
> ```
> import React from "react";
> import { Admin, resolveBrowserLocale } from "react-admin";
> import authProvider from "./providers/auth/authProvider";
> import dataProvider from "./providers/data/dataProvider";
> 
> const App = () => {
> 
>     return (
> 	    <Admin
> 		locale={resolveBrowserLocale()}
> 	        dataProvider={dataProvider}
>     		authProvider={authProvider}
> 		>
> 		    ........
> 		</Admin>
> 	);
> };
> export default App;
> ```
> 
> `authProviders.js`
> 
> ```
> import { Auth0Client } from "@auth0/auth0-spa-js";
> import { Auth0Constants } from "../../config";
> import { Auth0AuthProvider } from "ra-auth-auth0";
> 
> const auth0 = new Auth0Client({
> 	domain: Auth0Constants.domain,
> 	clientId: Auth0Constants.clientId,
> 	cacheLocation: "localstorage",
> });
> const authProvider = Auth0AuthProvider(auth0, {
> 	loginRedirectUri: window.location.origin,
> });
> 
> export default authProvider;
> ```
> 
> `index.js`
> 
> ```
> import React from "react";
> import ReactDOM from "react-dom/client"; // Update this import
> import "./index.css";
> import App from "./App";
> import * as serviceWorker from "./serviceWorker";
> import { Auth0Provider } from "@auth0/auth0-react";
> import { Auth0Constants } from "./config";
> 
> // Create a root element
> const root = ReactDOM.createRoot(document.getElementById("root"));
> 
> // Render your app using the createRoot method
> root.render(
>     <React.StrictMode>
>     	<Auth0Provider
>     		domain={Auth0Constants.domain}
>     		clientId={Auth0Constants.clientId}
>     		authorizationParams={{
>     			redirect_uri: window.location.origin,
> 	    	}}
> 	    >
> 		    <App />
> 		</Auth0Provider>
>     </React.StrictMode>
> );
> 
> serviceWorker.unregister();
> ```
> 
> But when I accesss the `localhost:3000`, it keeps reloading... I am not sure what is the problem. Is there anyone who will help me with this stuff?
> 
> Thanks in advance.

is the issue resolved if yes can you help me in setting up auth0 in my react admin application?

**Comment by fzaninotto** [comment]
@kollucharan React-admin issues are only for bugs. For support, how tos and troubleshooting, please use the community Discord at https://discord.gg/GeZF9sqh3N/.
