### ISSUE TITLE
`useRecordSelection` definition change missing from migration guide

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#10243]
Since version 5.0.0 of react-admin `useRecordSelection` hook definition has changed (#9742) but it has not been documented in the migration guide.

To be fair, this hook is not fully documented, just referenced in the docs, but I believe it is needed to be mentioned in the migration guide.

At least I found the hard way, I have to update its usage while migrating a project from version 4 to 5.

**Comment by fzaninotto** [comment]
The issue you linked to doesn't concern `useRecordContext`. Are you referring to the fact that the return type has changed?

**Comment by WiXSL** [comment]
I'm referring to the `useRecordSelection` hook.

In v4:

```jsx
const a = useRecordSelection('my_resource');
```

In v5:

```jsx
const a = useRecordSelection({ resource: 'my_resource'});
```

**Comment by fzaninotto** [comment]
My bad, you're right!

This change should figure in the upgrade guide. I'm marking it as a documentation issue. 

Would you mind opening a PR to add the mention in the upgrade guide?
