### ISSUE TITLE
<AutocompleteArrayInput onCreate /> undefined value en enter

### ISSUE THREAD

**Issue by bgeffrault** [marmelab/react-admin#10274]
**What you were expecting:**

After I enter a value in an `<AutocompleteArrayInput>` with a `onCreate` prop. When I press Enter on my keyboard the onCreate handler is called with the value.

**What happened instead:**

The value is `undefined` is not registered.

**Steps to reproduce:**

Type texte inside the component, instead of clicking in "Create" button press "Enter" button on the keyboard.
  
**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v5)
  - https://stackblitz.com/github/marmelab/react-admin/tree/4.x/examples/simple (v4)
* A link to a GitHub repo with the minimal codebase to reproduce the issue
https://stackblitz.com/edit/github-cezwmt?file=src%2Fposts%2FPostCreate.tsx,node_modules%2Fra-ui-materialui%2Fdist%2Fcjs%2Finput%2FAutocompleteInput.d.ts
https://github.com/user-attachments/assets/8cf251a0-3f3d-4175-8e53-2a0d18f2a64e

```tsx
  const [createdChoices, setCreatedChoices] = React.useState<any[]>([]);

  const handleOnCreate = async (presetValue?: string) => {
    let newValue: string | null = presetValue ?? null;
    if (!newValue) {
      return;
    }
    const entityToCreate = {
      name: newValue,
    };
    setCreatedChoices((prev) => [...prev, entityToCreate]);
    return entityToCreate;
  };
<AutocompleteArrayInput
          source="role"
          choices={createdChoices}
          onCreate={handleOnCreate}
        />

```
**Other information:**

https://github.com/user-attachments/assets/5b32e49f-b125-4ac3-a26c-e3d1cd3a4af1

**Environment**

* React-admin version: ^5.2.3
* Last version that did not exhibit the issue (if applicable):
* React version: ^18.3.1
* Browser: Version 128.0.6613.113 (Official Build) (arm64)
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Thank you for submitting this issue.

I may we wrong, but I don't think `<AutocompleteArrayInput>` was ever supposed to create new entries when you hit enter. You actually need to select the 'Create xxxx' choice (it's not just a hint, it's an actual list item).

It also works if you hit the Down key and then Enter.

@fzaninotto or @djhi can you confirm  `<AutocompleteArrayInput>` is not supposed to work that way?
@bgeffrault did you come across a doc page (from either react-admin or MUI) saying otherwise?

Thanks.

**Comment by fzaninotto** [comment]
Yep, @slax57 is right. The effect of the Enter key is selection.

**Comment by slax57** [comment]
So I guess we can close this issue. @bgeffrault feel free to reopen if you found a doc page saying otherwise.

**Comment by djhi** [comment]
It's actually possible by leveraging MUI [`onChange` event](https://mui.com/material-ui/api/autocomplete/#autocomplete-prop-onChange) as it provide a `reason`. When `reason` is `createOption` we can trigger the creation.
