### ISSUE TITLE
Bulk Select conflicts with individual EDIT

### ISSUE THREAD

**Issue by alexrosabr** [marmelab/react-admin#10275]
**What you were expecting:**
Choose a filter, select N items, individually edit one of them and change the filtered field. After the SAVE the LIST should have N-1 selected items.

**What happened instead:**
After the save the header still reads "N items selected" and posts.selectedIds still contains the ID of the changed item

**Steps to reproduce:**
1. Open "simple" demo
2. Filter by "Commentable"
3. Select 3 posts, header shows "3 items selected"
4. Edit one of them
5. Remove the "Commentable" flag and SAVE
6. After the save, the header should read "2 items selected" and posts.selectedIds should have only 2 ids

![Image](https://github.com/user-attachments/assets/96b8d8ca-cd23-44b4-800f-84656d8bb1a4)

** The bug happens in then "simple" demo:
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v5)

**Environment**

* React-admin version: master
* React version: any
* Browser: any

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback.

What you describe is the normal behavior of react-admin. What you are expecting, in our opinion, would be a bug ;)

To say it differently, row selection and filters aren't linked one way or another. Row selection is designed to allow bulk actions. You selected an item, then updated it. We cannot guess why you did it. 

So I'm going to close this issue. Feel free to bring more details to the discussion.
