### ISSUE TITLE
Magic link login

### ISSUE THREAD

**Issue by jason-curtis** [marmelab/react-admin#10289]
**Is your feature request related to a problem? Please describe.**
I'd like to allow my users to login without having to have a password specific to my site

**Describe the solution you'd like**
A common pattern for this is the OTP email / magic link email.

**Describe alternatives you've considered**
Currently I'm able to use a custom login page implementation to achieve this.

**Additional context**
N/A

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by jason-curtis** [comment]
> As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

This is a feature request!

**Comment by slax57** [comment]
@jason-curtis React Admin should already have all the building blocks needed to implement a magic link login.
Depending on the service you are using, it may already be supported by one of the [authProviders](https://marmelab.com/react-admin/AuthProviderList.html).
If it is not already, then you will need to implement it yourself in the authProvider of your choice.
That's where you may need support from the community, in case you're unclear on how to proceed.
But in any case, implementing magic link login shouldn't require any change in react-admin, hence the closing of this feature request.
