### ISSUE TITLE
Resource name is not translated when there is no results found with filters

### ISSUE THREAD

**Issue by thibault-barrat** [marmelab/react-admin#10287]
**What you were expecting:**
When filtering a list and there are no results, a message is displayed: `No {$ressource} found using the current filters.`. The resource name should be translated.

**What happened instead:**
The resource name is not translated.

**Steps to reproduce:**
Set a translation for a resource and filter the list in order to obtain no results.

**Related code:**
https://stackblitz.com/edit/github-adhnve?file=src%2Fi18n%2Fen.ts
On the comments resource, filter it to get no results, we should see `No comments found using the current filters.` instead of `No post_comments found using the current filters.`

**Environment**

* React-admin version: v5

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report!
