### ISSUE TITLE
Filter's required validator is ignored if filter value was never set

### ISSUE THREAD

**Issue by dolfinus** [marmelab/react-admin#10286]
I have a REST API endpoint objects, which has mandatory query params `since` (datetime) and `search_query` (text with minimal length). If I call this endpoint without any of these query params set, it will return an error.

I've added a component `RunGrid` using `List` + `Datagrid` under the hood. `List` has 2 filters with `required()` validator.

![Image](https://github.com/user-attachments/assets/f8ecf63c-2397-4537-a029-2ec2bc52d210)
![Image](https://github.com/user-attachments/assets/683bc456-1c20-4c6a-8fc4-c3629cb8851b)

**What you were expecting:**

If any required filter does not pass validation, `getList` query should not be send. Only then user set all required filters, ReactAdmin should call API endpoint with these filters.

**What happened instead:**

When I open page with `RunGrid` component, ReactAdmin calls `getList` method of DataProvider even then both required filters have no values, resulting an error notification being shown to user.

![Image](https://github.com/user-attachments/assets/b229fe0b-0d4f-4062-add1-032ab7b18a96)

But when I fill up **both** filters and then **manually** remove entered values, then validation is performed as expected, and no requests are send.

![Image](https://github.com/user-attachments/assets/81f06378-7b69-4a2f-b830-230894eabae2)

**Steps to reproduce:**

- Start an application with the following code, go to `Runs` page.
- Filter is not being set, but there are no validation errors (no red frame around input fields), and `getList` is called with empty filters list (unexpected).
- Fill up `since`, and press Refresh button. The error remains (unexpected).
- Fill up `search_query`. `getList` is now called with both filters set (expected).
- Click on `X` button in search input, and then click `Refresh` button in the menu. `getList` will not be called (expected).
- Enter something in search input, click `Delete` button in the calendar input - `getList` still not called (expected).
- Click `CLEAR FILTERS`. Both filters will be reset, input fields have no validation errors, `getList` is called with empty fields again (unexpected).

**Related code:**
```tsx
import { ReactElement } from "react";
import {
    List,
    TopToolbar,
    SelectColumnsButton,
    SearchInput,
    required,
    minLength,
    DatagridConfigurable,
    DateField,
    DateTimeInput,
    ChipField,
    DataProvider,
    GetListParams,
    QueryFunctionContext,
    StoreContextProvider,
    Admin,
    Resource,
} from "react-admin";



const dataProvider: DataProvider = {
    // @ts-ignore
    getList: (
        resource: string,
        params: GetListParams & QueryFunctionContext,
    ) => {
        if (params.filter && params.filter.since && params.filter.search_query) {
            if (params.filter.search_query == "test") {
                return  Promise.resolve({
                    data: [
                        {
                            id: 123,
                            started_at: '2024-01-01T00:00:00',
                            status: 'SUCCESSFUL',
                        },
                    ],
                    total: 1,
                })
            } else {
                return  Promise.resolve({
                    data: [],
                    total: 0,
                })
            }
        }
        return Promise.reject(new Error("Since and search_query fields are mandatory"))
    },
}

const RunGridActions = () => (
    <TopToolbar>
        <SelectColumnsButton />
    </TopToolbar>
);

const runFilters = [
    <DateTimeInput
        source="since"
        alwaysOn
        validate={required()}
        resource="runs"
    />,
    <SearchInput
        source="search_query"
        alwaysOn
        validate={[required(), minLength(3)]}
        resource="runs"
    />,
];

const RunGrid = (): ReactElement => {
    return (
        <List actions={<RunGridActions />} filters={runFilters}>
            <DatagridConfigurable bulkActionButtons={false}>
                <DateField source="started_at" showTime={true} />
                <ChipField source="status" />
            </DatagridConfigurable>
        </List>
    );
};

const App = () => {
    return (
        <Admin
            title=""
            dataProvider={dataProvider}
            disableTelemetry
        >
            <Resource name="runs" list={RunGrid} />
        </Admin>
    );
};
export default App;
```

**Other information:**

If there are required filters, when validation should be performed before any dataProvider interaction.

**Environment**

* React-admin version: 5.3.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18.3.1
* Browser: Mozilla Firefox 132.0b7, Chrome 130.0.6723.58
* Stack trace (in case of a JS error):

**Comment by erwanMarmelab** [comment]
Hello  @dolfinus,

The "validate" prop of react-admin's inputs is designed to work with forms, not filters. Your use case is outside the scope of this property. If you want to do it, please create your own list component.

Cheers,

**Comment by dolfinus** [comment]
> The "validate" prop of react-admin's inputs is designed to work with forms, not filters

That's unfortunate.

> If you want to do it, please create your own list component.

Could you give any examples? Like, can I reuse `SearchInput` & `DateTimeInput` in this component, or should I implement my own?

**Comment by erwanMarmelab** [comment]
> Could you give any examples? Like, can I reuse `SearchInput` & `DateTimeInput` in this component, or should I implement my own?

My bad, the best way to do it is to use a custom `filterForm`. We can find some examples in [the documentation](https://marmelab.com/react-admin/FilteringTutorial.html#building-a-custom-filter).
