### ISSUE TITLE
Dead link in Authentication docs

### ISSUE THREAD

**Issue by justin-hackin** [marmelab/react-admin#10294]
At the end of [this page](https://marmelab.com/react-admin/Authentication.html) there is a dead link:  [Authorization](https://marmelab.com/react-admin/Authorization.md)

**Comment by djhi** [comment]
Indeed, the page is still named `Permissions.html`. Thanks!

**Comment by 5AIPAVAN** [comment]
so shall i change the file name of Permissions.md file to Authorization.md?
i think that solves this issue

**Comment by slax57** [comment]
@5AIPAVAN yes please, a PR is welcome! 🙂 
No need for assignment, just open a PR saying it closes this issue in its description 😉 
Thanks!
