### ISSUE TITLE
SimpleFormIteratorItem always requires a resource be passed

### ISSUE THREAD

**Issue by Dmytro-Uchkin** [marmelab/react-admin#10307]
**What you were expecting:**

When creating a [custom page](https://marmelab.com/react-admin/Admin.html#adding-custom-pages) with a custom `Form` I expect to use SimpleFormIterator without specifying resource context.

**What happened instead:**

When creating a custom page with custom `Form` without specifying resource I get an error using `SimpleFormIterator`. The issue is related to the internal `SimpleFormIteratorItem` component which runs a check for resource existens without it being used. Thus I am forced to wrap my custom page into `ResourceContextProvider` with no existing resource name.

```
export const SimpleFormIteratorItem = React.forwardRef(
  ...

  if (!resource) {
      throw new Error(
          'SimpleFormIteratorItem must be used in a ResourceContextProvider or be passed a resource prop.'
      );
  }
```

**Steps to reproduce:**

1. Create an application with a custom route and add a customer page without any resource ([following documentation](https://marmelab.com/react-admin/Admin.html#adding-custom-pages))
2. Add a `From` component to your page with code like:
```
const defaultValues = {
  children: [
    {}
  ],
};

...

  <Form
    defaultValues={defaultValues}
    id="some-id"
    onSubmit={(values) => {}}
  >
    <ArrayInput source="children" label="Children">
      <SimpleFormIterator>
        <DateInput
          source="birthdayTimestamp"
          label="Birthday"
        />
      </SimpleFormIterator>
    </ArrayInput>
  </Form>
```

3. Get `SimpleFormIteratorItem must be used in a ResourceContextProvider or be passed a resource prop.` error

**Related code:**
 
1. Open https://codesandbox.io/p/github/marmelab/react-admin-sandbox/csb-k2y695/draft/nostalgic-swartz
2. Proceed to /#/custom-route-page route
3. Press + button

**Other information:**

**Environment**

* React-admin version: 5.3.0
* Last version that did not exhibit the issue (if applicable): -
* React version: 18
* Browser: Chrome 128
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for your report. 

React-admin Inputs (including `ArrayInput`) are designed to be used in forms allowing to edit a record (e.g., inside `<Edit>` or `<Create>`). Therefore, they expect a `ResourceContext`, and the error you're facing is normal. 

In your case, you seem to be using react-admin's inputs for another use case, which isn't in our target. 

So I'm closing this report as we won't fix it.
