### ISSUE TITLE
<DateInput> masking incorrect: allows 6 characters for year

### ISSUE THREAD

**Issue by justin-hackin** [marmelab/react-admin#10305]
**What you were expecting:**
I should be able to type out all the date properties without leaving the keyboard in a <DateInput> by typing 8 numbers.

**What happened instead:**
The year portion accepts 6 numbers before proceeding to month (default config) 

**Steps to reproduce:**
Blog admin demo -> post -> miscellaneous -> Published at
Type "20000101"

**Comment by fzaninotto** [comment]
That's not a bug, but a native browser feature. 20024 is a valid JavaScript year. 

I suggest you add a `maxValue` validator if you don't want to accept dates that far in the future.

**Comment by justin-hackin** [comment]
Technically, 6 digit years might be permissiable. In practice, who's going to use a year that's > 9999 though?  From a UX perspective, when you have a masked input with only 4 characters in the current input (not left-padded) or in the placeholder, the user expects to be able to type out the full date uninterrupted. If you really want to have a 6-digit date support, I think it makes more sense to have the year at the end so that when the user finishes typing the year, they will just tab instead of causing unexpected numbers in the year.

**Comment by fzaninotto** [comment]
I understand your concerns, but you are actually ranting against the `<input type="date">`, which is what react-admin uses in this case. I suggest you open an issue in the tracker of your browser. As for react-admin, we rely on these standards and won't reinvent the wheel.

**Comment by justin-hackin** [comment]
Oh wow, it was hard to believe but yes indeed, this is how Chrome's native date input works 🤦‍♂️ Firefox works as I expected. Placeholders are read to screen readers so I suspect it's a minor annoyance that screen reader users have learned to work around with the tab key.
