### ISSUE TITLE
5.2.2 -> 5.3.0 nested <ReferenceField link={false}><ReferenceField> generated link is flaky & invalid / used "parent.id" and not child.id

### ISSUE THREAD

**Issue by fkowal** [marmelab/react-admin#10301]
Given:
```
<Resource name="comments" representation="id" show={...} />
<Resource name="posts" representation="id" />
<Resource name="authors" representation="name" />

<List> <- comments
  <Datagrid>
    <ReferenceField source="post_id" reference="posts" link={false}> <-- false here is important
       <ReferenceField source="author_id" reference="author" link="show" />
    </ReferenceField>
  </Datagrid>
</List>
```
With such data / relation between `{ comment: {id: 'commentid', post: {id: "postid", author: {id: "authorid", name: "Shakespear"}} }`

On version 5.2.2
i would get `<Link to="#/author/authorid/show">Shakespear</Link>`

On version 5.3.0
During the first render (ie. refresh page) (when the resources are still being fetches async
i get `<Link to="#/author/postid/show">Shakespear</Link>` this link is broken

when i click the comment row
then go back (browser back) to comment list
the `<Link to="#/author/authorid/show">Shakespear</Link>` is valid (the same as in 5.2.2)
And this must be somehow related to all the resources now being (in cache)

I understand that a working demo would be best, but when i tried to replicate this in stackblitz & fake-rest-dataprovider
I can't get the same result

So pls let me know if i can't help to provide more context.

ps. adding a 3'rd "self" reference fixed the link issue (on first render), but that's ... just sad

```
<ReferenceField source="post_id" reference="posts" link={false}>
   <ReferenceField source="author_id" reference="author" link={false}> <-----
       <ReferenceField source="id" reference="author" link="show"> <----
    </ReferenceField>
</ReferenceField>
```

**Comment by fkowal** [comment]
using
```
<ReferenceField source="post_id" reference="posts" link={false}> <-- false here is important
    <ReferenceField source="author_id" reference="author" link={(record, reference) => `/${reference}/${record.id}/show` />
</ReferenceField>
```

also works

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue, preferably a sandbox forked from 
  - https://codesandbox.io/p/github/marmelab/react-admin-sandbox/main (v5)
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v5)
  - https://stackblitz.com/github/marmelab/react-admin/tree/4.x/examples/simple (v4)

**Comment by fkowal** [comment]
@djhi pls have a look at the MR https://github.com/marmelab/react-admin/pull/10304

i don't know how to setup a test
that would reflect async record update that would express the issue

but i hope the fix will be apparent when comparing to the `useEffect` before 5.3.0 https://github.com/marmelab/react-admin/commit/10a1c76f19bb5096f64f95cfb09d0a77a383455e

**Comment by fzaninotto** [comment]
I have managed to reproduce the bug by simulating a slow first load on a single ReferenceField (no need for to nested ones). 

I have published the test and a fix in a PR.
