### ISSUE TITLE
DateInput and DateTimeInput not updating value in UI

### ISSUE THREAD

**Issue by dricholm** [marmelab/react-admin#10320]
**What you were expecting:**
On our site we have a custom filter component with `DateInput` / `DateTimeInput` which has a default value set. e.g. filter from date starting a week before. There is also a clear filter button which would reset the filter after being changed. This worked fine, however now we're in the process of upgrading to react-admin v5.
On v5 clicking the clear filter won't update the text inside `DateInput` / `DateTimeInput`. It does reset the value inside the form, so the problem only lies in the component and specifically the input element's value.

**What happened instead:**
The value shown in the input can only be changed manually through the native input UI.
However this "stuck" value only happens after a value is set manually. If I have a default value set, and programmatically set it with a button for example it will work. Once I set it manually it will never update the UI.

**Steps to reproduce:**
Managed to reproduce it in a forked Sandbox, the problem doesn't specifically happen in our above mentioned custom filter component, but in the included edit forms as well.

- Open any post edit page
- Open the miscellaneous tab
- Check the published at / with time inputs
- Click on the buttons below those inputs:
  - Set: it will update the above input to a specific value
  - Reset: will reset the value
- Now manually set a value using the `DateInput` / `DateTimeInput`
- Click on the buttons again
- Now none of the buttons have effect on the input UI itself, although they still update the value inside react-hook-form

Notice the differences between the value in the input and using `useWatch()`.

![Image](https://github.com/user-attachments/assets/70e27522-d16c-4378-8f04-e746f4189b05)

**Related code:**
https://codesandbox.io/p/github/marmelab/react-admin-sandbox/csb-rwcm2m/draft/affectionate-hypatia

**Other information:**
Tested with some other inputs, but those seemed to work as expected.
From what I see the date inputs don't have the `value` as controlled.

**Environment**

* React-admin version: 5.3.1
* Last version that did not exhibit the issue (if applicable): Upgrading from 4.15.3, didn't test versions in-between
* React version: 18.3.1
* Browser: Chrome latest version
* Stack trace (in case of a JS error): -

**Comment by slax57** [comment]
Reproduced, thanks!
FTR, the issue is still there with react-admin 5.3.2.
