### ISSUE TITLE
Version 5 documentation about react-query devtools not up to date

### ISSUE THREAD

**Issue by dricholm** [marmelab/react-admin#10342]
This is purely a documentation issue, those can also be opened here, right?

**What you were expecting:**
The [documentation about react-query devtools](https://marmelab.com/react-admin/DataProviders.html#enabling-query-logs) to be updated to the latest version.
It is no longer bundled with the react-query package but needs to be installed separately so the import is different as well.

**What happened instead:**
The section is still using react-query v3 instructions.

**Steps to reproduce:**
Copying the code in the docs shows errors since devtools is no longer exported from the package.

**Other information:**
The link to react-query docs is to v5, so it can be followed to get it working.

**Environment**

* React-admin version: 5.3.3
* Last version that did not exhibit the issue (if applicable): 4.x.x
* React version: -
* Browser: -
* Stack trace (in case of a JS error): -

**Comment by slax57** [comment]
Indeed, nice catch!
Would you like to open a PR to solve this documentation issue ?
Thanks

**Comment by dricholm** [comment]
> Indeed, nice catch! Would you like to open a PR to solve this documentation issue ? Thanks

Sure. For doc updates which branch should I target?

**Comment by fzaninotto** [comment]
`master` is OK.

**Comment by fzaninotto** [comment]
Fixed by #10346
