### ISSUE TITLE
SimpleFormIteratorContextValue: Missing parameters for the Add function type

### ISSUE THREAD

**Issue by Aikain** [marmelab/react-admin#10355]
**What you were expecting:**
```tsx
const { add } = useSimpleFormIterator();
```
Add type should be something like `(item?: any) => void`

**What happened instead:**
Add type is `() => void` and got typescript error:

```
error TS2554: Expected 0 arguments, but got 1.

    add(defaultValue);
```

**Related code:**
It would seem that the `useSimpleFormIterator`-hook is typed from the [`SimpleFormIteratorContextValue`-type](https://github.com/marmelab/react-admin/blob/v5.3.4/packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorContext.ts#L14), where no parameters are defined for the add function.

[The implementation of the add function](https://github.com/marmelab/react-admin/blob/v5.3.4/packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx#L96) seems to have a parameter.

**Comment by slax57** [comment]
I confirm the issue and the expected behavior. The TS type should be `(item?: any) => void` instead.
Thanks for reporting it!
Would you like to open a PR to fix this issue?

**Comment by Aikain** [comment]
I'll do a PR later today.
