### ISSUE TITLE
Incorrect type for queryOptions in ReferenceArrayField

### ISSUE THREAD

**Issue by dricholm** [marmelab/react-admin#10379]
**What you were expecting:**
Passing the `queryOptions` prop to `ReferenceArrayField` should not require the `queryKey` property.

**What happened instead:**
Typescript error:

```
Property 'queryKey' is missing in type '{}' but required in type 'UseQueryOptions<RaRecord<Identifier>[], Error, RaRecord<Identifier>[], QueryKey>'.ts(2741)
```

**Steps to reproduce:**
Have a `ReferenceArrayField` component and specify `queryOptions` without `queryKey` for it.

**Related code:**

```ts
<ReferenceArrayField
  queryOptions={{ }}
  reference='resourceName'
  source='referenceIds'>
```

**Other information:**

The component passes `queyOptions` to `useReferenceArrayFieldController`, which uses the correct type by omitting the "forbidden" fields:

```ts
queryOptions?: Omit<
  UseQueryOptions<ReferenceRecordType[]>,
  'queryFn' | 'queryKey'
>;
```

**Environment**

* React-admin version: 5.3.3
* Last version that did not exhibit the issue (if applicable): Unsure, I believe the prop was added ~1 year ago to the component
* React version: 18.3.1
* Browser: Chrome
* Stack trace (in case of a JS error): -

**Comment by fzaninotto** [comment]
Well spotted. Would you like to open a PR to fix it?

**Comment by dricholm** [comment]
> Well spotted. Would you like to open a PR to fix it?

Sure, I can open one probably sometime this week.
