### ISSUE TITLE
Access control redirects don't respect basename when react-admin included inside a route

### ISSUE THREAD

**Issue by zemccartney** [marmelab/react-admin#10380]
**What you were expecting:**

- A `false` result from my auth provider's `canAccess` to redirect me to the built-in access denied view

**What happened instead:**

- a route not found error, as surfaced by react router, due to the redirect not accounting for the admin living at a custom path

**Steps to reproduce:**

Given:

- an application with an existing router via react-router
- a react-admin application

1. Set the react-admin application as a route in the existing router 

```js

import Admin from "./Admin";

const router = createBrowserRouter([
  {
    path: "/",
    element: <div>Hello World</div>,
  },
  {
    path: "/admin/*",
    element: <Admin />,
  },
]);
```
2. Pass `basename="/admin"` prop to react-admin's `Admin` element
3. Register a couple of resources
4. Restrict access to one of the resources entirely in `authProvider.canAccess`

```js
canAccess: async ({ resource }) => {
        if (resource === 'users') {
            return false;
        }

        return true;
    },
```

5. Manually navigate to the users list page (change browser's address bar), `/admin/users`

You'll land on `/access-denied`, not `/admin/access-denied` and see react-router's built-in 404 view

The same issue applies to the auth error redirect, too. For example, if you modify `canAccess` as follows:

```js
canAccess: async ({ resource }) => {
        if (resource === 'users') {
            throw new Error('boom');
        }

        return true;
    },
```

You eventually land on the same react-router 404 view, but at path `/authentication-error`. This redirect took a few seconds whereas the false access control result redirected instantly; seems tangential, even irrelevant, but noting for completeness, in case an unexpected behavior.

**Related code:**

Minimal example repo: https://github.com/zemccartney/ra-route-redir-repro/tree/main

**Other information:**

**Environment**

* React-admin version: 5.4.0
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 18.3.1
* Browser: Chrome 131
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
Thanks for the report! A fix is incoming.
