### ISSUE TITLE
FileInput onChange prop return more than one event type

### ISSUE THREAD

**Issue by tnoct** [marmelab/react-admin#10401]
**What you were expecting:**
- In Edit form when we select a file and then File Input onChange prop should return one type of change event value. i should show a `SyntheticBaseEvent` or a `File` object.

**What happened instead:**
Its showing first A `SyntheticBaseEvent` object and rightafter it shows `File` Object that we selected.

**Steps to reproduce:**

* Preferably, a sandbox forked for reproducing the code.
  - https://stackblitz.com/edit/github-uaewfaxm?file=src%2Fposts.tsx

```
<Edit title={<PostTitle />}>
    <SimpleForm>
      <TextInput source="id" disabled />
      <ReferenceInput source="userId" reference="users" />
      <TextInput source="title" />
      <TextInput source="body" multiline rows={5} />
      <FileInput source="attachments" onChange={(file) => console.log(file)}>
        <FileField source="src" title="title" />
      </FileInput>
    </SimpleForm>
  </Edit>
```

**Other information:**

**Environment**

* React-admin version: `^5.4.0`
* Last version that did not exhibit the issue (if applicable): `4.12.0 does not have this issue`
* React version: `^18.3.1`
* Browser: `chorme`

Here us the screen shot : 
![Image](https://github.com/user-attachments/assets/3c0e651c-0ab8-4685-b12e-f5bd735a5b8a)

**Comment by slax57** [comment]
Reproduced, thanks!

**Comment by tnoct** [comment]
thnx for fixing it. @slax57  🙂

**Comment by tnoct** [comment]
Between just wanted to know when the minor will be release so that i can schedule with my production release.
