### ISSUE TITLE
FilterLiveForm context usage and sanitization

### ISSUE THREAD

**Issue by dricholm** [marmelab/react-admin#10400]
**Is your feature request related to a problem? Please describe.**
I tried out the new `FilterLiveForm` component which works pretty good. I ran into two minor problems with it:

1. It requires a ListContext to be used. In my use case it's used as a filter for a custom list/request which then uses `useList`.
1. It sets empty values as empty strings in the filter, tried with `DateInput` (enterprise edition with MUI) and `SelectInput`. Even tried with adding `parse` for the inputs but no change.

**Describe the solution you'd like**
My suggestions for the solutions:

1. Since only filters are used `ListFilterContext` could be used instead of `ListContext` which reduces dependency of the component.
1. Maybe adding a `sanitizeEmptyValues` prop to the component, similar to the one on `SimpleForm`. Or potentially adding something like a transform function, which is called with the `values` in `onSubmit` to set the final filters.

**Describe alternatives you've considered**
First I had a similar custom implementation, but since the use-case is very similar I went with copying the component's code and modifying it for custom use. But since these changes would be very minor and could come in handy for other users I think they could be considered in the main repo.

**Additional context**
-

**Comment by fzaninotto** [comment]
The fact that it requires a ListContext is by design. You can use the output of `useList` as a `ListContext` value. 

As for the problem with empty values, can you please provide a reproduction?

**Comment by dricholm** [comment]
> The fact that it requires a ListContext is by design. You can use the output of `useList` as a `ListContext` value.
> 
> As for the problem with empty values, can you please provide a reproduction?

Thanks for the quick response!
Started working on reproducing it in unit tests and while looking deeper in the code found out point number 2 is fixed because `setFilters()` inside `useList()` has the following: `setFilterValues(removeEmpty(filters))`. So the `removeEmpty()` does prevent empty values from being set on the filters.
Unfortunately in my use case I don't have the `useList` available at the filters yet. As my structure broken down minimally looks like this:

```tsx
const Parent = () => {
  const [filterValues, setFilters] = useState(DEFAULT_VALUES);
  const listFilter = useMemo<ListFilterContextValue>(
    () => ({
      displayedFilters: undefined,
      filterValues,
      hideFilter: () => undefined,
      resource: 'someStatistics',
      setFilters: filters => {
        setFilters(removeEmpty(filters) as InviteStatFilter); // Adding removeEmpty solves my second problem
      },
      showFilter: () => undefined,
    }),
    [filterValues],
  );

  return (
    <FilterListContext.Provider value={filterListContext}>
      <FilterLiveForm>
        {/* with some inputs */}
      </FilterLiveForm>
      <ListComponent />
    </FilterListContext.Provider>
  );
);

const ListComponent = () => {
  const { filterValues } = useFilterListContext();
  const queryResult = useQuery(); // react-query with filterValues to filter larger data on the backend returning aggregated statistics
  const listContext = useList();

  return (
    <ListContextProvider value={listContext}>
      <Datagrid>
        {/* fields which shows the aggregated data and doesn't have any filtering, only showing and sorting the list */}
      </Datagrid>
    </ListContextProvider>
  );
};
```

You mentioned using the full list context by design, but is there any advantage to having `FilterLiveForm` be dependent on `ListContext` instead of its `ListFilterContext` subset? I would be interested to know more about it.
My suggestion was because `ListFilterContext` only uses two properties (`filterValues` and `setFilters`) of the context which are in the `ListFilterContext` and `ListContextProvider` automatically sets `ListFilterContext` in its direct children. I may not see the overall picture of course, but to me it looks like reducing the dependency would make the component easier to use in certain areas where a full list is not necessary.

**Comment by fzaninotto** [comment]
`FilterListContext` is a speed optimization, and considered a private API. We never intended to support partial list contexts. Use a regular `ListContext` instead.

**Comment by dricholm** [comment]
> `FilterListContext` is a speed optimization, and considered a private API. We never intended to support partial list contexts. Use a regular `ListContext` instead.

I'll have to do that then, thanks for the help.

But if it's a speed optimization, wouldn't it be better for `FilterLiveForm` to use that instead? Would improve performance by not re-rendering in unrelated list context changes, e.g. changing sort. If I understand it correctly.
Both are in the `ra-core` package so it even stays private as you mentioned.

We can close the issue otherwise.

**Comment by slax57** [comment]
@dricholm It seems you are right!
When implementing the `FilterLiveForm`, I chose to use the `ListContext` rather than the `ListFilterContext` because some unit tests were only providing the first and not the latter.
But looking closer at it, I realize that's because those tests are using `ListContext.Provider` instead of `ListContextProvider`, which _does_ also set a `ListFilterContext`.
So, I believe you are right, `FilterLiveForm` could be improved to only use the `ListFilterContext`. And those tests need to be fixed to use `ListContextProvider` instead.
I'll add this idea to our backlog, but with low priority though.

If you'd like to open a PR yourself to make this change, we would gladly welcome it 🙂 .
Thanks.

**Comment by dricholm** [comment]
@slax57 Thank you for the response and in-depth explanation!
I'll probably work on it in the near future if I find time, but not a high priority at the moment.
