### ISSUE TITLE
Show Tab Form Validation For Inputs Not Direct Children Of <FormTab>

### ISSUE THREAD

**Issue by alauper** [marmelab/react-admin#1385]
https://stackoverflow.com/q/48199337/782151

**What you were expecting:**
When an unfocused tab has a validation error, the tab header should appear red.

**What happened instead:**
When an unfocused tab has a validation error, the tab header does not give any indication of the error.  

**Steps to reproduce:**
This issue is specific to subcomponents.  If all the components are defined at the Create/Edit level, then the tab turns red as expected.  But if there are nested components, then the tab does not.

This code works.

```
export const CampaignPmpCreate = (props) => (
  <Create {...props}>
    <TabbedForm>
      <FormTab label="settings">
        <Field component={TextInput} name="name" label="Name" validate={required} {...props} />
        <SettingsTab />
      </FormTab>
      <FormTab label="deals">
        <DealsTab />
      </FormTab>
    </TabbedForm>
   </Create>
);
```

By moving the field into a subcomponent, the validation indicator does not work.
```
export const CampaignPmpCreate = (props) => (
  <Create {...props}>
    <TabbedForm>
      <FormTab label="settings">
        <SettingsTab />
      </FormTab>
      <FormTab label="deals">
        <DealsTab />
      </FormTab>
    </TabbedForm>
  </Create>
);


export const SettingsTab = (props) => (
  <div>
    <Field component={TextInput} name="name" label="Name" validate={required} {...props} />
  </div>
);
```

**Environment**
admin-on-rest: 1.3.3
React: 15.6.2
Browser: Safari/Chrome

**Comment by fzaninotto** [comment]
We detect errors in a form and highlight the relevant tab(s), but only if inputs are direct children of the `FormTab` element.

Detecting errors deeper in the hierarchy requires significant refactoring. Marking this as an enhancement.

**Comment by alauper** [comment]
Ok, that makes sense.  

In my use cases, create and edit contain the exact same form fields so I always partial those out for DRY.  Just an FYI, because I know your help docs assume the opposite is common.

**Comment by lucianomlima** [comment]
Maybe can be possible using React.Fragment instead of div.

**Comment by alauper** [comment]
This is fixed in the latest version of react-admin where the snack bar notifies the user there are validation errors, including ones on a different tab.

**Comment by helenatxu** [comment]
Hello, I'm stuck with this issue and I can't change my current react-admin version (react-admin@^2.9.3) without breaking many dependencies on my project.

Is there a way I can "pass" the validation to my custom component or mark my custom fields as invalid so the tabs are properly marked in red when they have an invalid field?

**Comment by djhi** [comment]
Please ask questions on StackOverflow as explained in the contributing guide.

**Comment by helenatxu** [comment]
Done 

https://stackoverflow.com/questions/58135210/show-tab-form-validation-for-inputs-not-direct-children-of-formtab
