### ISSUE TITLE
a lot of wasted render cycles according to react-addons-perf

### ISSUE THREAD

**Issue by zifnab87** [marmelab/react-admin#1496]
I used https://reactjs.org/docs/perf.html#printwasted at the start of my admin-on-rest based application and after a short navigation of 10 or so steps. I printed the results of wasted render cycles that state wasn't even changed and it seems that there is a lot of room for improvement. Any thoughts on this?

![image](https://user-images.githubusercontent.com/526062/35886722-af58b666-0b9a-11e8-99e2-c8bbb4a06e20.png)

Thanks!

Admin-on-rest version: 1.3.4
react-addons-perf": "^15.4.2

**Comment by djhi** [comment]
We'll look into it

**Comment by fzaninotto** [comment]
`react-addons-perf` was discontinued and does not handle React 16 (cf https://reactjs.org/docs/perf.html#printwasted). 

We do regular profiling sessions using the Chrome DevTools, and fix the most obvious rerenders.
