### ISSUE TITLE
AppBarMobile is missing from the documentation - is there a way to override it?

### ISSUE THREAD

**Issue by zifnab87** [marmelab/react-admin#1500]
We needed to override the default AppBarMobile (https://github.com/marmelab/admin-on-rest/search?utf8=%E2%9C%93&q=AppBarMobile&type=) since it seems that it appears on top of our custom AppBar when in mobile. I assume that this component is internally used .. how is it connected with the rest of the application so it can be overriden?

Thank you

**Comment by djhi** [comment]
It can't be overridden currently, unless you create your own versions of all the CRUD views (List, Create, Show, Edit, Delete).

The workaround would be to hide your custom AppBar on mobile.

**Comment by zifnab87** [comment]
Good to know! what I did is I used hacky z-index to enforce my custom AppBar to be on top of the Mobile one to work for both cases (mobile and desktop)

**Comment by fzaninotto** [comment]
Fixed by #2155 (by deprecating it)
