### ISSUE TITLE
Allow use of List, Create, Edit, Show and Delete components in custom routes.

### ISSUE THREAD

**Issue by santaclauze** [marmelab/react-admin#1522]
As discussed in my previous issue #1445 and later #1462, it would be great to be able to use the mains components `List`, `Create`, `Edit`, `Show` and `Delete` in the `customRoutes`.

I found myself in this situation where in certain cases, we create a form related to a `resource` but the case does not fit the CRUD schema or the CRUD has already been exhausted.

For example, I may create multiple forms related to one `resource` at different parts of my software or I may want to use the actions provided by `admin-in-rest` to create pages that load data from multiple `resources` whic will lead me to go through a `customRoutes`.

**Comment by Ryanthegiantlion** [comment]
Not sure if this fits your exact use case, but to use the edit component in a custom route i just had to add the resource as a prop explicitly:

```
<Edit  {...this.props} resource="users">
```

As long as the resource component gets the resource name and id (which it gets [via the route](https://github.com/marmelab/admin-on-rest/blob/2136094c1700452ab6b2ba5b758bbf307f3fd98b/src/mui/detail/Edit.js#L151), so your route path needs to be something like `/users/:id/ResetPassword`) it should handle things from there.

**Comment by fzaninotto** [comment]
Nothing prevents you from using them in custom routes, provided you pass the right props.

Feel free to reopen if you have a more specific problem.

**Comment by ksbulgakov** [comment]
Hi!

I had the same question and found an example : https://marmelab.com/react-admin/CustomApp.html

<Route exact path="/posts" render={(routeProps) => <PostList hasCreate resource="posts" basePath={routeProps.match.url} {...routeProps} />} />

Also if you can customise basePath prop (for instance if at first you render List and then you want row to render Show on click)
