### ISSUE TITLE
error admin-on-rest > react-router-dom > react@^15" doesn't satisfy found match of "react@16.2.0"

### ISSUE THREAD

**Issue by FDiskas** [marmelab/react-admin#1566]
admin-on-rest: v1.4.0
react: 16.2.0
`yarn check`

**Comment by fzaninotto** [comment]
I think that means we should upgrade react-router in master.

But you'll have other warnings with react 16.2. Normally, it's a peer dependency so it should not cause any harm other than these warnings.

**Comment by FDiskas** [comment]
I think that react-router-dom should be used and react-router is an dependency of that 
https://github.com/ReactTraining/react-router/blob/ecc9a73230f574cba138929cd8ef829592609006/packages/react-router-dom/package.json#L47
:checkered_flag:

**Comment by Adebeer** [comment]
It'll be nice to remove these warnings - I normally pin these errors down by doing a npm list --depth=2
From what I can see, the react@^15 warnings are coming indirectly from material-ui@0.19.4 - which still references react 15 dependencies.

I'm getting the following peer dep warnings:
npm ERR! peer dep missing: react@^15, required by react-router@4.1.2
npm ERR! peer dep missing: react@^15, required by react-router-dom@4.1.2
npm ERR! peer dep missing: react@^15, required by react-router@4.1.2

**Comment by mhyassin** [comment]
If we update to react-router-dom 4.2.2 it'll fix the dependencies warnings

**Comment by fzaninotto** [comment]
Moved to [marmelab/admin-on-rest#3](https://github.com/marmelab/admin-on-rest/issues/3)
