### ISSUE TITLE
Pass 'total' property to ReferenceInput children

### ISSUE THREAD

**Issue by alex-knyazev** [marmelab/react-admin#1585]
I want to use pagination in my custom children of ReferenceInput, but I haven't 'total' property there. 
Now in children of ReferenceInput I have 'choices' property and method 'setPagination'. To realize paginationh, I need to know 'total' property, like in List component

**Comment by afilp** [comment]
@AlexandrKnyazev1395 This puzzles me too, could a (temporary) solution be to increase the page number, fetch and check if the length of choices is zero? If yes, then do not show the "next page" link. Just a thought, but I agree with you that we need the total.

What kind of custom children are you using to achieve the paginated results? A custom-made select box with "previous/next" links?

**Comment by AlexandrKnyazev1395** [comment]
@afilp I use Modal-form with List inside. Every ite, of list is text +  radioButton. And in this modal I also have filter and pagination

**Comment by afilp** [comment]
Thanks

**Comment by djhi** [comment]
Fixed by #1912
