### ISSUE TITLE
'Not found' when logging out

### ISSUE THREAD

**Issue by asliwinski** [marmelab/react-admin#1644]
**What you were expecting:**
To be redirected to login page without errors after pressing Logout button

**What happened instead:**
'Not found' appears for a fraction of second before the redirection, as soon as the promise from `authClient` is returned.

**Steps to reproduce:**
- Clone and install the [minimal example app](https://github.com/asliwinski/aor-bug) (it's just a few steps of the tutorial + the basic `authClient`)
- Replace the `node_modules/admin-on-rest/lib/sideEffect/saga/auth.js` with the `auth.js` from `src` of the repo (2 breakpoints added to catch the error):
```
case USER_LOGOUT: {
    debugger;
    yield call(authClient, AUTH_LOGOUT);
    debugger;
    yield put(push('/login'));
    break;
}
```
- run the app, open the console and log out. When it hits the first breakpoint resume script execution to see the error. (Just when I'm testing it right now it went OK at the first attempt and failed at second, which suggests some kind of a race condition).

**Before:**

![image](https://user-images.githubusercontent.com/14044823/37370809-9dcd4a40-270d-11e8-998a-5ea9676a6448.png)

**After:**

![image](https://user-images.githubusercontent.com/14044823/37370828-af4f3cf6-270d-11e8-8e43-b1ac8141f134.png)

**Environment**

* Admin-on-rest version: 1.4.0
* React version: 16.2.0

**Comment by fzaninotto** [comment]
I can't reproduce this on `next`.

**Comment by asliwinski** [comment]
True, it only happens with the current release (1.4.0).

**Comment by fzaninotto** [comment]
Reproduced and confirmed in `master`

**Comment by fzaninotto** [comment]
Moved to [marmelab/admin-on-rest#1](https://github.com/marmelab/admin-on-rest/issues/1).
