### ISSUE TITLE
Regression in v2, hasDelete was removed, so we cannot disable delete on resource

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#1757]
in the v2 the existence of DeleteButton is checked by hasEdit
https://github.com/marmelab/react-admin/blob/ffe14db899be478a89b60bb567f496093aa3aa49/packages/ra-ui-materialui/src/detail/ShowActions.js#L57

instead of using hasDelete as in v1
https://github.com/marmelab/admin-on-rest/blob/master/src/mui/detail/ShowActions.js#L15

it seems that delete was removed on Resource, making it so that is now impossible easily disable deleting some resources

ie. i had some Resources's which could be not deleted, so i set Delete to null to disable appearing of DeleteButton's in List and Show

**Comment by fzaninotto** [comment]
This is addressed in the Upgrade guide: you have to customize the toolbar to remove the edit button.

https://github.com/marmelab/react-admin/blob/master/UPGRADE.md#removed-the-delete-view-in-resource
