### ISSUE TITLE
Missing confirmation dialog on Delete/bulkDelete

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#1758]
there seems to be missing some sort of confirmation for delete action

in the v1 there was custom page with confirmation

in the new version it would be nice to have same or at least to have modal dialog to confirm the delete action

same for bulk actions

all these are potentionally destructive actions, so it's better for user to confirm it 
(could be optionally disablable?)

((and no, weird undo button in notification is not replacement for confirmation))

**Comment by fzaninotto** [comment]
There is no confirmation dialog. It has been replaced by the "undo" feature, which serves the same purpose but provides a better user experience. See rationale in #1589.

And if you want to add  confirmation dialog, you can still create your own `<Delete>` button with a dialog built in.

**Comment by adylevy** [comment]
You can use this gist for delete with confirmation modal - 
https://gist.github.com/adylevy/759900e7c50f9ccebe9f037bc5e32506
