### ISSUE TITLE
ON CRUD_GET_LIST_FAILURE - Trying to refresh view infinite times

### ISSUE THREAD

**Issue by dmakevic** [marmelab/react-admin#1765]
**What you were expecting:**

Display message about failure and stop trying to infinite refresh list until the browser becomes frozen.

**What happened instead:**
After RA/CRUD_GET_LIST_FAILURE dispatches RA/REFRESH_VIEW

meta: onFailure refresh: true
Try to request API endpoint to get data. The browser becomes frozen and get response from API HTTP  status Code 429: Too Many Requests.

Steps to reproduce:
It's just enough to change  <Resource> name prop that is not mapped to API endpoint for that resource.

**Environment**

React-admin version: current master branch
React version: 16.3.2

![selection_009](https://user-images.githubusercontent.com/16756332/39086532-287b7236-4593-11e8-8baa-42721ca30c21.png)

**Comment by fzaninotto** [comment]
Confirmed, that's a serious bug
