### ISSUE TITLE
FormDataConsumer with ReferenceInput: The prop `resource` is marked as required in `ReferenceInput`

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#1766]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
`FormDataConsumer` to work with `ReferenceInput`  

**What happened instead:**
I get the following error:
Warning: Failed prop type: The prop `resource` is marked as required in `ReferenceInput`, but its value is `undefined`.

**Related code:**

```
      <FormDataConsumer>
        {(formData, ...rest) =>
          formData.cat_id && (
            <ReferenceInput label="CATEGORY" source="subCat_id" reference="subCategories" allowEmpty
                            perPage={100}
                            sort={{field: 'name', order: 'ASC'}}
                            fullWidth
                            {...rest}
            >
              <SelectInput optionText="name" />
            </ReferenceInput>
          )}
      </FormDataConsumer>

```

**Environment**

* React-admin version: v2.0.0.RC1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by afilp** [comment]
@fzaninotto @djhi 

The bug is now fixed, thanks a lot.

I believe there is also another related bug, in terms of not updating the ReferenceInput when a `filter` exists and the `formData` changes.

I submitted it as a different bug:
https://github.com/marmelab/react-admin/issues/1772

**Comment by tjgragg** [comment]
I see this same error with ReferenceArrayInput. Not sure it's related, or a new issue should be opened?

**Comment by fzaninotto** [comment]
please open a new issue

**Comment by mrlaseptima** [comment]
i have same error . are you sure this bug fixed?

**Comment by fzaninotto** [comment]
@mrlaseptima please provide a codesandbox reproducing the issue if you think it's not fixed.

**Comment by deftbrain** [comment]
> I see this same error with ReferenceArrayInput. Not sure it's related, or a new issue should be opened?

If it might help somebody... I've got the same error but when I checked my code thoroughly, I realized that I didn't pass the `...rest` props to the `ReferenceArrayInput` component.
