### ISSUE TITLE
List: All columns at the right side of scrollbar are hidden, no way to show them

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#1784]
**What you were expecting:**
In List: Horizontal scrollbar to show all columns in the table (Datagrid), when horizontal scrollbar applies.

**What happened instead:**
All columns at the right part of the scrollbar are hidden, with no way to show them:
![image](https://user-images.githubusercontent.com/7850073/39267198-d2ee4e48-48d4-11e8-9d26-a0af6914cdce.png)

**Steps to reproduce:**
Just use many columns (fields) in a typical List.

**Environment**

* React-admin version: ^2.0.0-beta3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by afilp** [comment]
I found a "trick":

Changed the <Card> component of <List> to `<Card className={classes.card}>`

and changed its style to be `overflow: 'visible'`. This is just a hack though, as more things need to be done.

**Comment by fzaninotto** [comment]
Confirmed, this bug happens both on desktop and on mobile devices.

**Comment by fzaninotto** [comment]
It's a regression caused by #1721
