### ISSUE TITLE
ArrayInput, custom components and sources issue

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/react-admin#1788]
### Issue Description

I am displaying an `<ArrayInput />` containing a custom input such as:

``` js
<ArrayInput label="Paragraph Templates" source="message_template">
    <SimpleFormIterator>
        <ParagraphTemplateInput />
    </SimpleFormIterator>
</ArrayInput>
```

My `<ParagraphTemplateInput />` contains two editable fields such as:

``` js
export const ParagraphTemplateInput = (props) => (
    <Fragment>
        <TextInput source="type" label="Type" />
        <RichTextInput source="value" label="Content" />
    </Fragment>
);

export default addField(ParagraphTemplateInput);
```
However, the fields in my custom component are not pre-filled by Redux form state. After further investigation, I noticed that the `props.source` was similar to `message_template[0].undefined`. Indeed, I didn't mention any `source` to the `SimpleFormIterator` child.

We should allow to not specify any `source` in `SimpleFormIterator` children in such cases, right? 

### How to circumvent the issue?

As a side-note, I circumvent the issue using an empty `source` name, such as:

``` js
<ArrayInput label="Paragraph Templates" source="message_template">
    <SimpleFormIterator>
        <ParagraphTemplateInput source="" />
    </SimpleFormIterator>
</ArrayInput>
```
And then, in my custom component:

``` js
<TextInput source={`${props.source}type`} label="Type" />
```

**Comment by fzaninotto** [comment]
I think the doc for composite input isn't good. I believe that in your snippet, you should inject the props you receive from the parent to the child inputs.

```js
export const ParagraphTemplateInput = (props) => (
    <Fragment>
        <TextInput {...props} source="type" label="Type" />
        <RichTextInput {...props} source="value" label="Content" />
    </Fragment>
);
```

 Also, you should not add `addField`, as the children (`TextInput` and `RichTextInput`) already have `addField`)

**Comment by Kmaschta** [comment]
No answer here for a while.

Does this issue still affects newer versions of react admin?
Might you provide a CodeSandbox in order to reproduce quickly? You can fork this one if it helps: https://codesandbox.io/s/349ovjmlx5

**Comment by Kmaschta** [comment]
Closing from no answer from more than a year.
Feel free to re-open or link this issue if needed.
