### ISSUE TITLE
Resource can not Resolve 

### ISSUE THREAD

**Issue by findcoo** [marmelab/react-admin#1796]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**

```javascript
import { Admin, Resource } from 'react-admin'
```

**What happened instead:**

Resource can not resolve

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Bump, please provide details helping to reproduce the bug.

**Comment by fzaninotto** [comment]
No news for some time, closing.
