### ISSUE TITLE
What is your stance on semicolons?

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#1801]
What is your stance on semicolons? I've stopped using them since last year. I'm inclined to remove them all in one big commit for this react-admin app I'm building, but then again I could also just allow them and have Atom not show warnings on every line (change .eslintrc).

Just a thought from your side on this subject could help me decide.

**What you were expecting:**
No semicolons in code.

**What happened instead:**
Semicolon in code.

**Other information:**
https://standardjs.com/
> No semicolons – It's fine. Really!

**Environment**

* React-admin version: master

**Comment by fzaninotto** [comment]
We're using prettier. No need to remove semicolons.

**Comment by christiaanwesterbeek** [comment]
Indeed. Thanks. I've adhered to the .eslintrc file of react-admin (copy-paste), installed `prettier`, `eslint-config-prettier` and `eslint-plugin-prettier`. And afterwards running `./node_modules/.bin/eslint ./src/**/*.js --fix ` fixed all my own files (inserted semicolons for me where needed and some more stuff). All the linting errors and warnings are now gone.
