### ISSUE TITLE
The `record` of the newly created item is not updated properly for its buttons, on the redirected `List`

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#1804]
**What you were expecting:**

Record of a newly created item to be updated in List, so that custom buttons can use the extra values created on server. (If we do a refresh, this problem goes, but the use would not know this and should not have to do this)

**What happened instead:**

The newly created item's record has only the fields that were used in the `Create` form, not the extra ones created by the server (and retrieved in List).

**Steps to reproduce:**

On `Create`, we send this payload to server:
![image](https://user-images.githubusercontent.com/7850073/39668080-da84c718-50cc-11e8-8b40-321729e10b73.png)

And the server creates some extra data (fields) for the item:

![image](https://user-images.githubusercontent.com/7850073/39668087-fe165b10-50cc-11e8-9f3d-a3c5c7168d43.png)

These fields are also present in `List` and show fine when viewing the List.

The only problem is when we create a new record and get redirected to the list. The record propagating to the item's button still has the form values (not the ones that the server has created).

![image](https://user-images.githubusercontent.com/7850073/39668115-91a39bb8-50cd-11e8-8082-4fa5d99a26e1.png)

Compare that with the record of the other buttons (one per list item), which were already in the list:

![image](https://user-images.githubusercontent.com/7850073/39668121-bccc15a4-50cd-11e8-9cc6-ede265cf4035.png)

As you can see, the `record` of the newly created item that the 'button' receives is not updated properly when on the redirected `List` view. This has implications in the data used by the button when clicked, etc.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: ^2.0.0-RC3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by afilp** [comment]
I believe that the problem is here on buttons (I copied this logic for my custom button):

```
const enhance = shouldUpdate(
    (props, nextProps) =>
        props.translate !== nextProps.translate ||
        (props.record &&
            nextProps.record &&
            props.record.id !== nextProps.record.id) ||
        props.basePath !== nextProps.basePath ||
        (props.record == null && nextProps.record != null)
);
```

In my case, I had to also add the following:

```
(props.record.id !== nextProps.record.id || props.record.eCode !== nextProps.record.eCode)
```

Otherwise the button's record does not update with the server-side new fields.

**Comment by fzaninotto** [comment]
Yes, definitely, you should remove the `shouldUpdate` decoration, which is here for optimization purposes on the Edit and Show buttons. Don't copy/paste code that you don't understand.

By the way, this is a "How to" questions, it should be asked on StackOverflow and not here, as explained in the Issue template.
