### ISSUE TITLE
Export CSV feature

### ISSUE THREAD

**Issue by Aurelyn10** [marmelab/react-admin#1816]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(http://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.
I would like to have Export CSV button on any list page, like as angular version of this admin ( ng-admin)
Thank you.

**Comment by djhi** [comment]
Thank you for this feature request. We won't include this in the core. It's doable using custom actions in user land.

**Comment by fzaninotto** [comment]
It's also a duplicate of #94
