### ISSUE TITLE
can't build react-admin, not compatible with node 10.0

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#1817]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**

I want to build react-admin.
I have node 10.0

**What happened instead:**

I have a error message saying upath 1.04 is not compatible with node 10.0

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

If we upgrade upath to 1.05, that works

**Environment**
node 10.0
* React-admin version: 1.0.rc3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
The problem lies in [upath](https://github.com/anodynos/upath/pull/15), which was fixed a couple weeks ago. Removing the `yarn.lock` and running `yarn` again should fix the problem.

**Comment by JacquesBonet** [comment]
Don't understand your logic.

In a previous PR, you asked me to commit the yarn.lock, file containing juste thee neccessary update: https://github.com/marmelab/react-admin/pull/1780

Here, you suggest to remove he yarn.lock. I do that, now I have  a yarn.lock with 318 difference than the yarn.lock on the repository:

![image](https://user-images.githubusercontent.com/173393/39917499-060188a0-550e-11e8-9f13-ce69366338a1.png)

I have some difficulties to follow your logic: two weeks ago, we have to deliver yarn.lock, this week we have to remove yarn.lock.
