### ISSUE TITLE
AutocompleteInput not working inside SimpleFormIterator and ReferenceInput

### ISSUE THREAD

**Issue by zavadpe** [marmelab/react-admin#1821]
**What you were expecting:**
`AutoCompleteInput` can be used for reference selection inside `SimpleFormIterator` and `ReferenceInput`.

**What happened instead:**
AutoCompleteInput doesn't suggest relevant references at the top when user inputs matching text.
For example user inputs "Sporting" (there's a place with a name Sporting Center) but this place is not suggested at the top. It seems that places are not filtered at all.

<img width="1003" alt="autocomplete_scrshot" src="https://user-images.githubusercontent.com/6029270/39928064-9e562770-5534-11e8-804a-250a3aa5af9f.png">

**Related code:**
Displaying items inside the list of references
```
<FormTab label="resources.tabs.list">
  <ArrayInput source="items">
    <SimpleFormIterator>
      <ReferenceInput label="resources.places" source="id" reference="places" >
        <AutocompleteInput optionText="title.en" />
      </ReferenceInput>
    </SimpleFormIterator>
  </ArrayInput>
</FormTab>
```
List model:
```
{
  ...
  items: [
    { id: <ID>}
  ]
}
```
Place model:
```
{
  id: <ID>,
  title: {
    en: <EN TITLE>
  }
}
```

**Environment**

* React-admin version: 2.0.0-RC3
* React version: 16.3.2
* Browser: any

**Comment by nitoygo** [comment]
I hope this issue is not being ignored, even if possibly invalid.

I also encountered similar issue.

**Comment by nitoygo** [comment]
Could this possible be related to https://github.com/marmelab/react-admin/issues/1887 ?

**Comment by Stoakes** [comment]
Hi,

I am also encountering this issue, but I would say, that `Autocomplete` component doesn't work at all (ie the bug is not related to ReferenceInput or SimpleForm).

After some debug, I found that `Autocomplete.handleSuggestionsFetchRequested` method is bugged: it doesn't update the suggestion list. I'm working on a fix and will share it when ready.

The Material-ui [autosuggest example](https://github.com/mui-org/material-ui/blob/master/docs/src/pages/demos/autocomplete/IntegrationAutosuggest.js) helped me in discovering it.

**Comment by djhi** [comment]
It's the API responsability to filter the items when using a [`ReferenceInput`](https://marmelab.com/react-admin/Inputs.html#referenceinput):

> This component fetches the possible values in the reference resource (using the GET_LIST REST method).

Are you sure you return filtered items ?

**Comment by zavadpe** [comment]
@djhi: You were right, after thorough debugging I found mismatch between my filtering API calls which I didn't notice before. Thanks for pointing this out! This issue can be closed.
