### ISSUE TITLE
Custom Reducer State is Emptied on User Logout

### ISSUE THREAD

**Issue by jdemangeon** [marmelab/react-admin#1826]
**What you were expecting:**

Actually, it's possible to declare custom reducers on `<Admin />` thanks to its "customReducers" props. This way, we can add new standalone functionnalities to our apps that don't rely on React-Admin at all.

**What happened instead:**

On "USER_LOGOUT" auth action (when the user click on logout), the [resettableAppReducer](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/CoreAdmin.js#L43) set the global redux state to undefined, which results in global state reset (including custom reducers ones).

```
const resettableAppReducer = (state, action) =>
        appReducer(action.type !== USER_LOGOUT ? state : undefined, action);
```

Since custom reducers are standalone, we should not empty them on user logout. It's the developer responsability to handle this case the way he wants. 

Then, we should only clear the React-Admin specific reducer states on user logout.

**Environment**

* React-admin version: last
* React version: all
* Browser: all

**Comment by JacquesBonet** [comment]
I think your problem  is related to this issue: https://github.com/marmelab/react-admin/issues/1870

**Comment by djhi** [comment]
I disagree. Custom reducers are a way to **extend** the react-admin state. The `appReducer` is responsible for react-admin state only and it should be cleared on logout, extensions included. That's what will be expected most of the time, imo.

If you want to have an application with only a part using react-admin, you should follow the [custom app](https://marmelab.com/react-admin/CustomApp.html) route, have your own store with your own reducers and the `appReducer will only take care of react-admin state.

**Comment by jdemangeon** [comment]
OK, we'll separate our custom reducer in another "sub-app". It should be good to talk about it in documentation.

Thanks @djhi

**Comment by djhi** [comment]
Can you elaborate about what is missing in the documentation ?

**Comment by fzaninotto** [comment]
putting the reducer in another sub app separates the two stores, and makes that the second app doesn't have access to the first store. It's not a good solution.

I'm reopening the issue.

I don't think there is a simple solution, as the `USER_LOGOUT` should reset only the react-admin part of the store, but if the user combines it with other reducers, we won't know where the react-admin state is...

**Comment by djhi** [comment]
Why two stores ? Following the custom app documentation, you only get one store with a subset of its state for react-admin, right ?

**Comment by fzaninotto** [comment]
two stores is what @jdemangeon understood. But it's not feasible.

**Comment by djhi** [comment]
My understanding is that they wanted features not using react-admin at all.

> This way, we can add new standalone functionnalities to our apps that don't rely on React-Admin at all.

If that's correct, a custom store should do the trick

**Comment by fzaninotto** [comment]
no, because when they compose react-admin's reducers with their own, the auth saga empties the *entire* store on logout, including the part that is not react-admin.

**Comment by djhi** [comment]
I believe the auth saga does [nothing](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/sideEffect/auth.js#L72).

This is the part responsible for clearing the state: https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/CoreAdmin.js#L43.

So:
1. Following the custom app route means you can simply not include this resettable reducer
2. You can have a store of your own and apply the resettable reducer only on the raect-admin state

Am I missing something ?

**Comment by fzaninotto** [comment]
you're right, a custom app allows that. @jdemangeon you do need a custom app anyway, since you have your own pages, right?

**Comment by jdemangeon** [comment]
Right, I'll try to makes my own store along react-admin. Thanks for the help! :+1:
