### ISSUE TITLE
Validation in a custom Input makes the browser crash

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/react-admin#1850]
When using validation in a custom component, React Admin crashes. For instance:

``` js
import React from "react";
import { TextInput, required } from "react-admin";

export const CustomInput = () => (
  <TextInput validate={required()} label="Custom" source="custom" />
);
```

As soon as we remove the `validate={required()}` part, it works correctly.

Here is the related CodeSandbox: https://codesandbox.io/s/m3n38j758. Adding a `validate={required()}` in the `<CustomInput />` component makes the browser crash.

Is it a misuse of custom components? If so, perhaps should we prevent the freeze and add a warning message in the console?

**Comment by fzaninotto** [comment]
This is a known issue with redux-form, that is already documented in https://marmelab.com/react-admin/CreateEdit.html#validation:

> Tip: Make sure to define validation functions or array of functions in a variable, instead of defining them directly in JSX. This can result in a new function or array at every render, and trigger infinite rerender.

```jsx
const validateStock = [required(), number(), minValue(0)];

export const ProductEdit = ({ ...props }) => (
    <Edit {...props}>
        <SimpleForm defaultValue={{ stock: 0 }}>
            ...
            {/* do this */}
            <NumberInput source="stock" validate={validateStock} />
            {/* don't do that */}
            <NumberInput source="stock" validate={[required(), number(), minValue(0)]} />
            ...
        </SimpleForm>
    </Edit>
);
```
