### ISSUE TITLE
AutocompleteInput with ReferenceInput shows 1 item more in its list (the latest selected value)

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#1854]
**What you were expecting:**
`AutocompleteInput` with `ReferenceInput` in List `filters` should not keep the previously selected value in the list (which is not related to the characters being pressed).

![image](https://user-images.githubusercontent.com/7850073/40462800-48637a62-5f1a-11e8-921b-a6b6c6f9ae5d.png)

**What happened instead:**

The previous value that I had selected ("ΚΑΝ1-....") is still in the list. Note that the "possible values" in REDUX are only 2, not 3, which is correct based on the query:

![image](https://user-images.githubusercontent.com/7850073/40462835-6d4d0974-5f1a-11e8-9435-0ddb090f342e.png)

**Related code:**
```
<ReferenceInput 
                      source="id"
                      reference="assets"
                      sort={{field: 'aCode', order: 'ASC'}}
                      perPage={1000}
                      filterToQuery={searchText => ({aCode: {"like": `.*${searchText}.*`, "options": "i"}})}
      >
        <AutocompleteInput optionText="aCode" />
      </ReferenceInput>
```

**Environment**

* React-admin version: v2.0.0

**Comment by fzaninotto** [comment]
That's... a feature. The idea is that, when you open the suggestion list of an autocomplete input with a value, even before you erase the current string and start typing, the current value should be in the suggestion list. My experience is that not having them in the list is worse than having them.

The related code is here: https://github.com/marmelab/react-admin/blob/7cf040d0b8ad842a238df99984249f068aaeefd0/packages/ra-core/src/reducer/admin/references/possibleValues.js#L41-L45

**Comment by afilp** [comment]
Thanks.
