### ISSUE TITLE
AutocompleteInput does not support the 'normalize' prop

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#1855]
**What you were expecting:**
`AutocompleteInput` to support (respect) the 'normalize' prop.

**What happened instead:**
Nothing happens with `AutocompleteInput` text while i am typing (no normalization).

**Steps to reproduce:**
<AutocompleteInput optionText="name" normalize={englishToGreekUpper}/>

* React-admin version:  v2.0

**Comment by djhi** [comment]
Where does this prop come from ?

**Comment by fzaninotto** [comment]
I believe you're referring to the [redux-form `normalize` prop](https://redux-form.com/7.3.0/docs/api/field.md/#-code-normalize-value-previousvalue-allvalues-previousallvalues-gt-nextvalue-code-optional-)

**Comment by fzaninotto** [comment]
`normalize` is for updating the input *value* (i.e. what you select). What you *type* isn't the value, it's just a filter for helping selecting one of the options.

So I think it's normal that `normalize` doesn't affect what you type, don't you think?

**Comment by afilp** [comment]
It is not that important, still it may have a use case for international keyboards or special cases.

In my case, I have created a function for all inputs that normalizes my Greek letters to English letters, so that the user always adds English serial numbers even if the keyboard is switched to Greek.

I thought I could use the same idea when **filtering** with the `AutocompleteInput` input.

It is **not** high priority, other issues are more important to be resolved (like the dual horizontal scrollbars issue when many columns exist). 

Thanks!

**Comment by fzaninotto** [comment]
So I confirm that `normalize` isn't supposed to do what you ask here. That requires an enhanced Autocomplete input, that we probably won't implement in core. I suggest you write you own custom Autocomplet input for that purpose.
