### ISSUE TITLE
Problems with 2 `ReferenceInput` filters referencing its own resource

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#1856]
**What you were expecting:**
2 `ReferenceInput` filters referencing its own resource to work properly in the UI:

1. When I add one of them just have this one shown, not both
2. When I add other filters, a "ghost" extra filter should not appear

**What happened instead:**
1. Both of them appear when adding one of them
2. A "ghost" extra filter appears when adding a 3rd filter (with a different `reference`)

**Steps to reproduce:**

I have these 3 filters:
![image](https://user-images.githubusercontent.com/7850073/40480859-639cadb0-5f58-11e8-986a-7d539f9e5734.png)

When I add either `DeptName` or `DeptCode` I get **both** of them (note: they both have the same `reference="departments"`, which is **also** the current `resource` of the page:

![image](https://user-images.githubusercontent.com/7850073/40480873-6c765148-5f58-11e8-9dd3-a36d6b03643e.png)

Then, when adding a 3rd filter (with other reference)...

![image](https://user-images.githubusercontent.com/7850073/40481009-b9fa88bc-5f58-11e8-8137-772dc920cff3.png)

...I get an extra `deptName` "filter" field, like being a "ghost":

![image](https://user-images.githubusercontent.com/7850073/40481106-08ba9ef6-5f59-11e8-8713-089a41ccd033.png)

**Related code:**

```jsx
    <ReferenceInput label="DeptCode" source="id" reference="departments" allowEmpty
                    sort={{field: 'code', order: 'ASC'}}
                    perPage={1000}
                    filterToQuery={searchText => ({code: {"like": `.*${searchText}.*`, "options": "i"}})}
    >
      <AutocompleteInput optionText="code" />
    </ReferenceInput>

    <ReferenceInput label="DeptName" source="id" reference="departments" allowEmpty
                    sort={{field: 'name', order: 'ASC'}}
                    perPage={1000}
                    filterToQuery={searchText => ({name: {"like": `.*${searchText}.*`, "options": "i"}})}
    >
      <AutocompleteInput optionText="name" />
    </ReferenceInput>

    <ReferenceInput label="Area" source="area_id" reference="areas" allowEmpty
                    sort={{field: 'name', order: 'ASC'}}
                    perPage={1000}
                    filterToQuery={searchText => ({name: {"like": `.*${searchText}.*`, "options": "i"}})}
    >
      <AutocompleteInput optionText="name" />
    </ReferenceInput>

```

**Other information:**

**Environment**

* React-admin version: v2.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
You can't have 2 `ReferenceInput` filters with the same `source` (which is the case in your example: both `DeptCode` and `DeptName` share the same `id` source). That's a hard limitation due to the fact that we use the `source` as field identifier. 

The solution is to have only one such `ReferenceInput`, that I'd name `Dept`, and implement a search on both the `code` and `name` fields server-side.

**Comment by afilp** [comment]
@fzaninotto Thanks. 

You mean that I would need to have 2 extra fields in the UI that would be used to select values and send them through a single field, named Dept? Sorry for having difficulty to understand this. If your team ever finds time, I think it would be a good idea to show this as an example in the Docs. Thx again.

**Comment by fzaninotto** [comment]
No, I mean that you should have only 1 field accepting either code or name, and a server-side route accepting both, and sending back the dept. 

That's better UI, too.
