### ISSUE TITLE
Relay graphql Dataprovider

### ISSUE THREAD

**Issue by nyejon** [marmelab/react-admin#1859]
Hi, I have a backend that uses GraphQL and Relay (Developed with Graphene)

Has anyone started development of a data provider that can connect to relay? (Since the specification is relatively fixed)

I have looked at the other options such as GraphCool or the simple GraphQL client, but would like to stick with Relay if possible.

**Comment by djhi** [comment]
Not aware of any

**Comment by fzaninotto** [comment]
Me neither, I advise using Twitter or StackOverflow for asking the question.

**Comment by Bilaltariq98** [comment]
Hi, I've noticed its been a couple years since this was first asked, I've not found anything on Stack about this - anyone dug into this further? 

I'm starting to think it might not be an option due to the fixed specification / type generation aspect of relay.
