### ISSUE TITLE
Best way to submit translations

### ISSUE THREAD

**Issue by koresar** [marmelab/react-admin#1872]
What's the best way to submit translations?

1) Create PR and add package like this one: https://github.com/marmelab/react-admin/tree/master/packages/ra-language-french
2) Create and publish separately, like people do in https://github.com/marmelab/react-admin/blob/master/docs/Translation.md

I would prefer way number 1. It's less for me to maintain. Also, I'm not using react-admin. Just want to contribute translations while I have a free minute. :)

**Comment by djhi** [comment]
We only keep packages of languages we can maintain (English and French) in this repository.
All other languages should be published separately.
