### ISSUE TITLE
Question on how to Install the demo

### ISSUE THREAD

**Issue by CHOMNANP** [marmelab/react-admin#1886]
I got some issue after setting the project.
I've follow the step bellow.

- glt clone https://github.com/marmelab/react-admin.git
- cd react-admin
- make install
- make run-demo

I've got the error

react-scripts start 
sh: react-scripts: command not found
error Command failed with exit code 127.
make: *** [run-demo] Error 1

**Comment by fzaninotto** [comment]
I can't replicate the error. 

Which platform are you using (MacOS, Windows, Linux)? Which OS? Which version of Node.js?

**Comment by fzaninotto** [comment]
No news for some time, closing.
