### ISSUE TITLE
Add custom item in ReferenceArrayInput

### ISSUE THREAD

**Issue by alihesari** [marmelab/react-admin#1893]
This component fetches the possible values in the reference resource. If I want to select All values, I need a `Select All` item. Values in the reference resource don't have `Select All` item and I don't want add `Select All` item in the reference resource json to display it in ReferenceArrayInput list.
So in my opinion, you add a new feature to display Select All item or any custom item in ReferenceArrayInput list. 
```
<ReferenceArrayInput source="tag_ids" reference="tags" customItems={[ {'selectAll': 'select All'}, {'Key': 'Value'}]}>
    <SelectArrayInput optionText="name" />
</ReferenceArrayInput>
```

**Comment by fzaninotto** [comment]
-1 for your solution: it's not the job of the `<ReferenceArrayInput>` to provide that feature, but of its child. Think about the case where the `<SelectArrayInput>` is replaced by a double list with a buttons to select/deselect an item. A "select all" option wouldn't make sense in that case.

![image](https://user-images.githubusercontent.com/99944/41160808-02de0b10-6b31-11e8-97a6-770f9dc06a1d.png)

So if the enhancement needs to be done, it's by a `allowSelectAll` prop in the `SelectArrayInput`` component.

**Comment by alihesari** [comment]
@fzaninotto Yes, you are right. Thank you for the explanation.

**Comment by DanStorm** [comment]
Any progress on this enhancement or is a work around possible? A method to 'Select All/ Deselect All'  for ReferenceArrayInput:SelectArrayInput is very important functionality for our app. Thanks!

**Comment by fzaninotto** [comment]
The core team won't work on this feature for the near future, as we don't need it. Feel free to open a Pull Request for it.

**Comment by jdemangeon** [comment]
According the previous message and the activity on this issue, I closing it.
