### ISSUE TITLE
Disable prop perPage so it displays all records in ReferenceInput, List

### ISSUE THREAD

**Issue by esoulution** [marmelab/react-admin#1894]
`perPage={false}`

**Comment by afilp** [comment]
@fzaninotto Is it possible that the UI of the results be another LIST component (in a modal form maybe), that will allow for pagination and filtering there? If this is something for "userland" (not sure about it) could your team please provide this in the examples? I find it very useful when the results are many (for example 3000 items).

**Comment by fzaninotto** [comment]
you can pass a large value for the `perPage` to avoid limits. We'll keep compulsory limits in the component to avoid hotting the API with a potentially heavy request.
