### ISSUE TITLE
Layout doesn't render correctly

### ISSUE THREAD

**Issue by samanmohamadi** [marmelab/react-admin#1897]
The admin layout doen't render conrrectly in production
this a screenshot of my admin panel:
![screenshot from 2018-06-11 09-38-52](https://user-images.githubusercontent.com/11535254/41213709-489a5b36-6d5c-11e8-8f1e-cd5d530fb858.png)
it seems that some thing is wrong with JSS.

**Environment**

* React-admin version: v2.0.2
* Browser: Chromium & Firefox
* Stack trace (in case of a JS error): No Error

**Comment by fzaninotto** [comment]
The [demo](https://marmelab.com/react-admin-demo/) doesn't show this behavior. Can you provide a way to reproduce the problem? The best way would be to fork [this codesandbox](https://codesandbox.io/s/pw74xww3p0).

**Comment by samanmohamadi** [comment]
Its Strange but I found that using icon cause this issue.
```
import UserIcon from '@material-ui/icons/People'; 
....
<Resource name="user"
                  icon={UserIcon}  // <-- removing this fix the issue
                  list={UserList}
        />
```

**Comment by fzaninotto** [comment]
Again, I can't reproduce that. Can you try and tweak the codesandbox to prove that the problem is in react-admin, rather than in your own code?

**Comment by samanmohamadi** [comment]
this situation only occurs in production.
If it helps, I can share the code with you or give you the access to the admin panel in production.

**Comment by fzaninotto** [comment]
There is a high chance that it's not a bug with react-admin but in your code (since I can't reproduce it). So please try and reproduce it based on the provided codesandbox, i.e. do the work of isolating the bug.

If you can prove that there is a bug in react-admin, we'll look into fixing it.

**Comment by samanmohamadi** [comment]
Yes, I think it's not a react-admin issue, I removed all icon and it's working for now.
so I close this issue till I can investigate about it.
thanks
