### ISSUE TITLE
DateInput does not override browsers' date picker

### ISSUE THREAD

**Issue by marquesgabriel** [marmelab/react-admin#1914]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
I'm trying to use the DateInput component as shown in the tutorial  (material ui date picker, etc)

**What happened instead:**
The pickers show on browsers (Firefox and Chrome) are native input type="date"

**Steps to reproduce:**
Create a Create or Edit Component and inside it's SimpleForm write a DateInput

**Related code:**
```
<DateInput label="Data" source="data" options={{
        mode: 'landscape',
        hintText: 'Escolha uma data',
        okLabel: 'OK',
        cancelLabel: 'Cancelar',
        locale: 'pt'
}}/>
<DateInput label="Data Simples" source="dataSimples"/>
```

**Environment**

* React-admin version: 2.0.2
* React version: 16.4.0
* Browsers:
Firefox Nightly 61.0a1
Firefox 60.0.2
Chrome 67.0.3396.87

**Comment by djhi** [comment]
Material-ui 1.0 doesn't provide a real date picker anymore. They fall back to the platform default one. We do not want to maintain our own datepicker but you can use https://github.com/vascofg/react-admin-date-inputs which is mentioned in our [Ecosystem](https://marmelab.com/react-admin/Ecosystem.html) documentation. They rely on https://material-ui-pickers.firebaseapp.com/demo/datepicker.
