### ISSUE TITLE
Dynamic filtering of reference many fields from list views

### ISSUE THREAD

**Issue by ben-eb** [marmelab/react-admin#1917]
**Is your feature request related to a problem? Please describe.**

Hello,

I'm having some trouble implementing a filter for localisations in my app. I'd like to display a top level filter box with locales and have that value propagate down to the get many reference calls. I have the following data structure:

```js
const ContentPage = [{
  id: 1
}];

const Localisation = [{
  id: 1,
  key: 'name',
  value: 'Hello',
  locale: 'en-GB',
  object: 1
}, {
  id: 2,
  key: 'name',
  value: 'Bonjour',
  locale: 'fr-FR',
  object: 1
}];
```

And my `List` code looks like this:

```js
import React from 'react';
import {
  List,
  Datagrid,
  EditButton,
  ReferenceField,
  TextField,
  SingleFieldList,
  Filter,
  SelectInput
} from 'react-admin';

const localisationFilter = { key: 'name' };
const filterDefaults = { locale: 'en-GB' };

const Translation = props => (
  <Filter {...props}>
    <SelectInput
      source="locale"
      choices={[
        { id: 'en-GB', name: 'English (UK)' },
        { id: 'fr-FR', name: 'French' },
      ]}
      alwaysOn
      allowEmpty={false}
    />
  </Filter>
);

const ContentPageList = props => (
  <List
    title="Content Pages"
    filters={<Translation />}
    filterDefaultValues={filterDefaults}
    {...props}
  >
    <Datagrid>
      <ReferenceManyField
        filter={localisationFilter}
        label="Page Name"
        reference="Localisation"
        target="object"
      >
        <SingleFieldList>
          <TextField source="value" />
        </SingleFieldList>
      </ReferenceManyField>
      <EditButton />
    </Datagrid>
  </List>
);

export default ContentPageList;
```

When I list the items from `ContentPage` I should see one value, `Hello` or `Bonjour` depending on the current locale. The problem is that the `localisationFilter` on the `ReferenceManyField` does not take into account this locale from the `List`. I had a quick look through the source code and it doesn't seem that this filter is passed down through `Datagrid`, so I think I'm trying to do something that isn't supported!

**Describe the solution you'd like**

I'd like some way for the filter parameter to be propagated through to the `ReferenceManyField`. Perhaps some kind of boolean on the field itself?

```jsx
<ReferenceManyField
  useListFilter={true}
  filter={localisationFilter}
  label="Page Name"
  reference="Localisation"
  target="object"
>
  <SingleFieldList>
    <TextField source="value" />
  </SingleFieldList>
</ReferenceManyField>
```

Though I am open to alternate proposals for the behaviour!

**Describe alternatives you've considered**

A hacky solution to this would be to expose some global variable with the current locale and merge the `localisationFilter` with this value. Alternately this might be a good area to use the React context API.

**Additional context**

I should expect to see one of the two translations in this screenshot but instead I am receiving both:

<img width="866" alt="screen shot 2018-06-15 at 17 01 48" src="https://user-images.githubusercontent.com/1282980/41477941-d317f2aa-70bd-11e8-8441-c6864e9cdf33.png">

**Comment by djhi** [comment]
The `List` filters are stored in the redux state so you should be able to create a custom field component encapsulating a `ReferenceManyField` component and passing it the `List` filters.

I'll close this issue as I'm sure this is achievable without any changes to the core and invite you to post your question on StackOverflow for further discussion.

**Comment by ben-eb** [comment]
@djhi Thanks, I'll give this a go! 👍
