### ISSUE TITLE
optimist update && payload vs requestPayload

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#1918]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
react-admin provide optimist update. That meen we dont wait the server response to update the ui

If I check the code, I see 

```    if (type === CRUD_UPDATE_OPTIMISTIC) {
        const updatedRecord = { ...previousState[payload.id], ...payload.data }
        return addRecords([updatedRecord], previousState)
    }
```

I think the code is wrong because payload contains the response of the request, but we dont have the guaranties this request is finished because its an optimist update

I think its better to replace payload by requestPayload

```   if (type === CRUD_UPDATE_OPTIMISTIC) {
        const updatedRecord = { ...previousState[requestPayload.id], ...requestPayload.data }
        return addRecords([updatedRecord], previousState)
    }
```

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
At this point, the `action.payload` **is** the request payload. We copy it in `action.requestPayload` only when the response is [received](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/sideEffect/fetch.js#L48) or when the request [fails](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/sideEffect/fetch.js#L62). This allows custom sagas which want to handle responses to have access to the original request payload

**Comment by JacquesBonet** [comment]
Breakpoint on data.js

![image](https://user-images.githubusercontent.com/173393/41511652-86764590-727b-11e8-94ea-e7b211b668d8.png)

We see payload contents is empty

![image](https://user-images.githubusercontent.com/173393/41511664-bc9c0506-727b-11e8-922a-0733304c543b.png)

requestPayload contents is not empty

**Comment by djhi** [comment]
We see payload contents is empty

> We see payload contents is empty

Not empty, your screenshot show it has a `data` property as returned by your dataProvider

**Comment by djhi** [comment]
As for supporting the `PATCH` http verb, this is the job of your dataProvider

**Comment by JacquesBonet** [comment]
```
const updatedRecord = { ...previousState[payload.id], ...payload.data }
return addRecords([updatedRecord], previousState)
```
This is only used here

---> my update don't execute this code

```
    if (type === CRUD_UPDATE_OPTIMISTIC) {
        const updatedRecord = { ...previousState[payload.id], ...payload.data }
        return addRecords([updatedRecord], previousState)
    }
```

We see payload contents is empty

Not empty, your screenshot show it has a data property as returned by your dataProvider.

----> your right, payload is not empty, but data inside payload is empty. So I can't use payload to get the data.

--- > my http update (patch) doesn't return data, just http code, so dataProvider doesn't return data

---> in case http update returned data, I'm not sure data will be available because its an optimist update

The data should be the only thing needed to update our store as it contains the full record, id included

---> in my case no because my update is a patch so my data don't contains all data but contains only  the data which are updated

**Comment by djhi** [comment]
> your right, payload is not empty, but data inside payload is empty. So I can't use payload to get the data.
> my http update (patch) doesn't return data, just http code, so dataProvider doesn't return data

Then something is wrong in your dataProvider. See the documentation

> in my case no because my update is a patch so my data don't contains all data but contains only the data which are updated

That's the job of your dataProvider.

**Comment by JacquesBonet** [comment]
As for supporting the PATCH http verb, this is the job of your dataProvider

----> Its the job of the reducer too, in order to update the store with the updated data.

Its what is done here:

```
    if (type === CRUD_UPDATE_OPTIMISTIC) {
        const updatedRecord = { ...previousState[payload.id], ...payload.data }
        return addRecords([updatedRecord], previousState)
    }
```

and what is not done when in react-admin we have in data.js:

```
        case UPDATE: 
        case GET_ONE:
        case CREATE:
            return addRecords([payload.data], previousState)
```

**Comment by JacquesBonet** [comment]
Thks Djhi for your reply.

We don't follow exactly the react-admin recommendation, so there is mismatch.
