### ISSUE TITLE
update && optimist update

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#1919]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

I made a crudUpdate()

I see the reducer code in admin/resource/data.js is executed before my dataprovider code

```
    const convertHTTPResponseToREST = (response, type, resource, params) => {
...

        switch (type) {
            case UPDATE:
                 // my update code executed after reducer code
```

Thats seem quite strange. The update code execute like an optimist update 

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
It is an optimistic update indeed and it's a feature. We assume that in most case, the operation will succeeds and if it doesn't we revert the state change. We probably should document this better though

**Comment by djhi** [comment]
You can find more infos about this feature in the [documentation](https://marmelab.com/react-admin/Actions.html#optimistic-rendering-and-undo)

**Comment by JacquesBonet** [comment]
Ok thks djhi.

One question:

If my update is an optimist update, why if I put a breakpoint on data.js file,

```
    if (type === CRUD_UPDATE_OPTIMISTIC) {
        const updatedRecord = { ...previousState[payload.id], ...payload.data }  // <---- breakpoint here
        return addRecords([updatedRecord], previousState)
    }
```

I never stop on this breakpoint?

**Comment by djhi** [comment]
> I see the reducer code in admin/resource/data.js is executed before my dataprovider code

Which reducer are you talking about then ?

**Comment by JacquesBonet** [comment]
The reducer in data.js

**Comment by JacquesBonet** [comment]
But I think my dataprovider code is not executed, because my http patch return no body.
