### ISSUE TITLE
MenuItemLink leftIcon=<img..>

### ISSUE THREAD

**Issue by DeepSnowNeeL** [marmelab/react-admin#1926]
**What you were expecting:**
No error in console

**What happened instead:**
```
Warning: React does not recognize the `titleAccess` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `titleaccess` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in img (at Menu.js:11)
    in span (created by MenuItemLink)
```
**Steps to reproduce:**
Use a MenuItemLink with 
`<MenuItemLink leftIcon={<img src="/img/icons/chart.png" />} ... />`

I just found while writing this that leftIcon is intended to be used with material-ui icons, maybe you could support custom icons as well ?
Or at least specify it in the docs at https://marmelab.com/react-admin/Admin.html#menu

Thanks !

**Comment by christiaanwesterbeek** [comment]
I had something similar with a <div> within a `SimpleForm`.

**Comment by fzaninotto** [comment]
Sorry, we only support `<SvgIcon>` elements as `leftIcon`. I'll document it.

You'll have to write your own version of `<MenuItemLink>` to use an image instead.
