### ISSUE TITLE
RA-getMuiTheme/createMuiTheme not working to customize theme

### ISSUE THREAD

**Issue by berge616** [marmelab/react-admin#1928]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
Custom theme props would be applied

**What happened instead:**
The custom theme is not applied

**Steps to reproduce:**
declare a custom theme 

**Related code:**

```
App.js

import { createMuiTheme } from '@material-ui/core/styles';
import blue from '@material-ui/core/colors/blue';

const App = () => (

  <Admin
    theme={createMuiTheme({
      palette: {
        primary1Color: blue,
      },
      appBar: {
        height: 50,
      },
    })}
```

**Other information:**

I am trying to apply a custom theme to my RA project. The documentation states pass the theme to `getMuiTheme`, however, this seems to have been replaced by createMuiTheme in Material 1.x. I tried with createMuiTheme and my custom theme does not appear

**Environment**

* React-admin version:2.0.3
* Last version that did not exhibit the issue (if applicable):
* React version:16.4.1
* Browser:chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
The theme injection works [as described in the documentation](https://marmelab.com/react-admin/Admin.html#theme) - I've just tested it.

You're just not using the right syntax for the mui theme (there is no more `primary1Color` or `appBar` key), see https://material-ui.com/customization/default-theme/ for the theme syntax.
