### ISSUE TITLE
Document how to add a button to create a record related to the current one

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#1930]
e.g. "create comment" in post

**Comment by thecassion** [comment]
I want to have this features . How do you intend to do that @fzaninotto ?

**Comment by djhi** [comment]
Well, as the issue title says, we're going to document it because it's doable without introducing any new feature. It's just React after all :)

**Comment by thecassion** [comment]
@djhi how do you handle that with #react-admin ?

**Comment by thecassion** [comment]
Hi @djhi I've post a question about that on [stackoverflow](https://stackoverflow.com/questions/51025768/using-react-admin-how-to-create-a-comment-from-a-post) . Your help would be good for me and after I project to write an article about that on medium. Thanks

**Comment by djhi** [comment]
I'm working on an article which will be published on Marmelab's blog. Stay tuned
