### ISSUE TITLE
ReferenceError: Buffer is not defined ... in ra-core util fetch.js (running ra on Windows)

### ISSUE THREAD

**Issue by alexicum** [marmelab/react-admin#1935]
First steps from Tutorial (posts list) returns error:

"ReferenceError: Buffer is not defined
    at isValidObject (webpack-internal:///./node_modules/ra-core/lib/util/fetch.js:77:20)
    at Object.flattenObject (webpack-internal:///./node_modules/ra-core/lib/util/fetch.js:87:9)
...
"

**Environment**
* mozilla-neutrino + react preset 
* React-admin version: 2.0.3
* Windows 10

**Solved by:**
`global.Buffer = global.Buffer || require('buffer').Buffer;`

**Comment by devhero** [comment]
My environment was not Windows but MacOs, so I think it should be investigated.
