### ISSUE TITLE
RA is all messed up when deployed to s3 bucket

### ISSUE THREAD

**Issue by berge616** [marmelab/react-admin#1941]
My RA project renders fine when deploying locally, however, when I copy my build directory to an S3 bucket for deployment, it renders all messed up. Sometimes it works, but most of the time it renders like the below image. If this should go in stack exchange just let me know- However, it worked fine in both environments with AOR

**Environment**

* React-admin version:2.0.3
* Last version that did not exhibit the issue (if applicable):
* React version:16.4.1
* Browser:Chrome/Safari
* Stack trace (in case of a JS error):

<img width="1414" alt="screen shot 2018-06-21 at 9 51 29 am" src="https://user-images.githubusercontent.com/1350815/41723473-2d7b16da-7539-11e8-86de-201ddb996865.png">

**Comment by fzaninotto** [comment]
Yes, please publish this on StackOverflow.

P.S. We're using S3+CloudFront, too, without ever noticing what you describe.

**Comment by berge616** [comment]
Seems this is an issue with the production build. Here is the issue:
https://github.com/marmelab/react-admin/issues/1782
