### ISSUE TITLE
AutocompleteInput does not function properly

### ISSUE THREAD

**Issue by berge616** [marmelab/react-admin#1943]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
I would expect autocompleteInput to render matching search results on the fly when I enter something in the text field

**What happened instead:**
The list of options does not change and is incorrect

**Related code:**

-->

```
<AutocompleteInput source="exercise" label="Exercise"
                           choices={exerciseListSorted}
                           validate={[required()]}
                           style={{width: '300px'}}/>

export const exerciseListSorted = [
  {id: 0, name: 'Arm Circles'},
  {id: 1, name: 'Around-the-World Lunges'},
  {id: 2, name: 'Bicep Curls'},
  {id: 3, name: 'Cycle'},
  {id: 4, name: 'Bulgarian Split Squat Jumps'},
  {id: 5, name: 'Bulgarian Split Squats'},
...continues on

```

**Other information:**
<img width="330" alt="screen shot 2018-06-21 at 12 40 18 pm" src="https://user-images.githubusercontent.com/1350815/41733050-bc7bca8e-7550-11e8-8c01-e567e0922786.png">

Highlighting does appear to work if I type something that is already visible
<img width="312" alt="screen shot 2018-06-21 at 12 49 36 pm" src="https://user-images.githubusercontent.com/1350815/41733370-a63b25f2-7551-11e8-9e10-0fc72dd56363.png">

I have also tried using the exact code in the documentation to no avail:
```
<AutocompleteInput source="category" choices={[
    { id: 'programming', name: 'Programming' },
    { id: 'lifestyle', name: 'Lifestyle' },
    { id: 'photography', name: 'Photography' },
]} />
```
It highlights but the list does not change when you enter in the text box
**Environment**

* React-admin version:2.0.3
* Last version that did not exhibit the issue (if applicable):
* React version:16.4.1
* Browser:
* Stack trace (in case of a JS error):

**Comment by berge616** [comment]
Any thoughts on this? Is it a confirmed issue? And ideas on workarounds?
Thanks!

**Comment by fzaninotto** [comment]
Yes, it's a confirmed issue, I'm working on a fix.
