### ISSUE TITLE
Helpful req.query parser for developers using react-admin in conjuction with their own API

### ISSUE THREAD

**Issue by carlcorsini** [marmelab/react-admin#1944]
I was having trouble getting the filter component to work when trying to filter through my data. My backend could not recognize the query string and I built a nice parser and example for those who want to use react-admin with their own hand written backend.

I believe my parser could have a place in the docs for those who want to get react-admin working with their own API. 

I tried using different dataProviders and looked across the web for solutions to my problem to no avail.

I am using the postgrestClient from 'aor-postgrest-client' as my dataProvider.
My backend is written in JavaScript with a postgres database using Knex.

here is the parser:

const queryParser = query => {
  query.q = query.q ? query.q.split(/(?<=[*])(.*)(?=[*])/)[1] : ''
  query.orderParam = query.order.split('.')[0] || ''
  query.orderDirection = query.order.split('.')[1] || ''
  return query
}

The main function of this parser will turn this string: 

'?filter=%7B%22q%22%3A%22c%22%7D&order=DESC&page=1&perPage=10&sort=blind'

Into this JavaScript object:

{ order: 'blind.desc',
  q: 'c',
  orderParam: 'blind',
  orderDirection: 'desc' }

![screen shot 2018-06-21 at 3 54 35 pm](https://user-images.githubusercontent.com/28901454/41749832-7dc8c450-756d-11e8-9546-aaa4b70077ec.png)

![screen shot 2018-06-21 at 3 46 33 pm](https://user-images.githubusercontent.com/28901454/41749268-4f8e6e94-756a-11e8-8ed8-2b6dd1624044.png)

![screen shot 2018-06-21 at 3 45 14 pm](https://user-images.githubusercontent.com/28901454/41749235-2410d194-756a-11e8-8a09-046acbc4aede.png)

**Comment by djhi** [comment]
Hi @carlcorsini and thanks for taking the time to share what you did on your backend :) However, `react-admin` is and will stay backend agnostic. You're free to use REST, GraphQL or whatever you like. We don't want to include backend recipes in our documentation.
