### ISSUE TITLE
The problem with Category List -> Products transition in the demo application

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#1951]
In the demo application: https://marmelab.com/react-admin-demo/
when navigating from the list: Category List -> Products (any line)

In the browser: Chrome 67.0.3396.87 there is a pop-up message: "Cannot read property 'toLowerCase' of null",
In the browser: Firefox 56.0.2 go to the Products page does not happen.

**Comment by fzaninotto** [comment]
Confirmed

**Comment by fzaninotto** [comment]
This seems to be caused by a missing `sort` query parameter in the link, which makes FakeRest fail (https://github.com/marmelab/FakeRest/blob/29df939d0ecbcd4dcd0fd12639a7e81630f4ca91/src/Collection.js#L100)
