### ISSUE TITLE
LongTextInput is not auto expandable textarea

### ISSUE THREAD

**Issue by atomxsk8** [marmelab/react-admin#1956]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
`<LongTextInput>` display correct

**What happened instead:**
if `<LongTextInput>` in `<TabbedForm>` have data, it not auto expandable textarea 

<img width="1029" alt="screen shot 2561-06-26 at 17 01 38 copy" src="https://user-images.githubusercontent.com/15246539/41904660-28948db2-7963-11e8-9e37-19fbde6561d4.png">

if `<LongTextInput>` in `<TabbedForm>` no data, 

<img width="1001" alt="screen shot 2561-06-26 at 17 06 36 copy" src="https://user-images.githubusercontent.com/15246539/41904847-a0afdac2-7963-11e8-9433-10823bcb7b4a.png">

**Steps to reproduce:**
1. git clone https://github.com/marmelab/react-admin.git && cd react-admin
2. make install && make run-demo
3. Login demo/demo
4. Go to Customers menu and click edit some customer
5. Go to tab Address

**Related code:**

```
<FormTab label="resources.customers.tabs.address">
                <LongTextInput
                    source="address"
                    formClassName={classes.address}
                />
                <TextInput source="zipcode" formClassName={classes.zipcode} />
                <TextInput source="city" formClassName={classes.city} />
</FormTab>
```

**Other information:**

**Environment**

* React-admin version: 2.0.3
* Last version that did not exhibit the issue (if applicable): v2.0.0-RC4
* React version: 16.3.2
* Browser: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by berge616** [comment]
I also saw this issue. I made the following workaround:
```<TextInput multiline rows={'10'} fullWidth source="notes"/>```

**Comment by fzaninotto** [comment]
Confirmed. This is a recent regression, since [the online demo](https://marmelab.com/react-admin-demo) doesn't show the problem. Perhaps a material-ui regression?

**Comment by fzaninotto** [comment]
Nope, it also shows in `master`

**Comment by fzaninotto** [comment]
It's a regression since 2.0.2, using `git bisect` to locate the culprit commit

**Comment by fzaninotto** [comment]
I believe this is a material-ui bug.
