### ISSUE TITLE
CrudUpdate OnFailure Refresh

### ISSUE THREAD

**Issue by L-Luciano** [marmelab/react-admin#1964]
**Is your feature request related to a problem? Please describe.**
When I edit a resource, if my server validate my data and there is an error, I loose my modification because there is a refresh data.
I valid the data in server side because we use yaml data.

I try to deactivate the undoable to stay on the edit page but the refresh is still doing.

**Describe the solution you'd like**
I would like to specify in the action crudUpdate the value for the refresh data.

`onFailure: {
            notification: {
                body: 'ra.notification.http_error',
                level: 'warning',
            },
            refresh: true,
        },`

**Describe alternatives you've considered**
Is it possible to override the crudUpdate actions to specify our behavior ?

**Comment by fzaninotto** [comment]
Now I'm wondering why we do a refresh on failure in the first place...
