### ISSUE TITLE
how to install master version 

### ISSUE THREAD

**Issue by vhellow** [marmelab/react-admin#1971]
It seems that installing master version with yarn or npm fails because missing version number in package.json. Is there any another way to do this besides manually cloning?

```
npm install git+https://github.com/marmelab/react-admin.git
npm ERR! Can't install git+https://github.com/marmelab/react-admin.git#9424612ed836cf0b6687e47ee9cda330168dec00: Missing package version
```

```
$ yarn add git+https://git@github.com/marmelab/react-admin.git
yarn add v1.7.0
[1/5] Resolving packages...
error Can't add "react-admin-lerna": invalid package version undefined.
```

**Comment by djhi** [comment]
That's not possible. This is a monorepo containing many packages so it can't be installed from a git url

**Comment by vhellow** [comment]
alright thanks for explanation.

**Comment by christiaanwesterbeek** [comment]
That probably answers this one as well: https://stackoverflow.com/questions/50913643/how-to-install-the-next-branch-of-react-admi n. I still like to figure out how to use `next` before it becomes a release.
