### ISSUE TITLE
Datagrid ignores "styles" prop

### ISSUE THREAD

**Issue by vsarang** [marmelab/react-admin#1974]
**What you were expecting:**
I was expecting the styles passed to the Datagrid to change how it looked. [This functionality is listed in the official docs.](https://marmelab.com/react-admin/List.html#custom-grid-style)

**What happened instead:**
The Datagrid looks the same regardless of the `styles` that are passed to it.

**Steps to reproduce:**
1. Create a Datagrid element
2. Pass it some styles
3. View the rendered output

**Related code:**
https://codesandbox.io/s/3q907mmr3q
In this example `PostsList.js:109` has been edited to make the table black, but it seems to have no effect.

```jsx
<Datagrid styles={{ table: { backgroundColor: 'black' } }}>
  { ... }
</Datagrid>
```

**Environment**

* React-admin version: 2.0.3
* React version: 16.2.0
* Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by fzaninotto** [comment]
The documentation is outdated. You should use `withStyles` to customize the datagrid styles.

Marking this as a documentation bug.
