### ISSUE TITLE
Invalid link in the documentation "Using a Custom Layout" 

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#1975]
Use the default layout ->
https://github.com/marmelab/react-admin/blob/master/src/mui/layout/Layout.js

**Comment by cmandesign** [comment]
this issue still exists. 
https://screenshots.firefox.com/wWJf75LYVuksV4z1/marmelab.com

**Comment by fzaninotto** [comment]
Weird, hte fix from #1976 seems to have been lost in a rebase. Reopening.
