### ISSUE TITLE
editbutton on referencemanyfield link to the parent resouce

### ISSUE THREAD

**Issue by data-server** [marmelab/react-admin#1986]
**Other information:** editbutton on referencemanyfield link to the parent resouce

**Environment**

* React-admin version: > 2.0.3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
I can't reproduce this issue. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/p3nq3lyjzq)
* A sample application via GitHub

**Comment by ashim-k-saha** [comment]
I also have the same problem. 

- CodeSandbox [https://codesandbox.io/s/5z2jkxrrlx](https://codesandbox.io/s/5z2jkxrrlx)

```jsx
export const CommentEdit = props => (
    <Edit {...props}>
        <SimpleForm>
            <DisabledInput source="id" />
            <ReferenceField
                source="post_id"
                reference="posts"
                perPage={15}
                sort={{ field: 'title', order: 'ASC' }}
            >
                <TextField source="title" />
            </ReferenceField>
            <TextInput source="author.name" validate={minLength(10)} />
            <DateInput source="created_at" />
            <LongTextInput source="body" validate={minLength(10)} />
        </SimpleForm>
    </Edit>
);
```

When `<ReferenceField>` is used inside `<Edit>`, the link is `BASE_URL/#/comments/1` inplace of `BASE_URL/#/posts/1`. In cas of `<Show>` it is working as expected.

**Comment by djhi** [comment]
I can reproduce @ashim-k-saha's bug but not @data-server's one.

**Comment by djhi** [comment]
@data-server Please provide a codesandbox which reproduces the issue

**Comment by djhi** [comment]
Official ETA is the 13/07. However, as this is a critical issue, I'll see if we can release it sooner. Ping @fzaninotto

**Comment by fzaninotto** [comment]
I've just published v2.1.1

**Comment by antonioparisi** [comment]
@fzaninotto I can still experience the issue using 2.1.1

**Comment by antonioparisi** [comment]
looks like it overrides the `ReferenceArrayField`'s ID object and uses the parent one by default.

**Comment by djhi** [comment]
Would you setting up a codesandbox with a reproduction ?

**Comment by fzaninotto** [comment]
bump

**Comment by strarsis** [comment]
This issue still exists... When I use an `<EditButton />` or a `<DeleteButton />` inside a `<ReferenceManyField`,
both buttons don't redirect back to the parent resource edit page, but rather to the referenced resource list page.

**Comment by WiXSL** [comment]
Please, if you find a bug, open a new issue following the issue template

**Comment by strarsis** [comment]
@WiXSL: Currently I have to use a `redirect` in the `Form` of those referenced pages and the approach described here:
https://marmelab.com/blog/2018/07/09/react-admin-tutorials-form-for-related-records.html#:~:text=today%20%7D%7D%20//%20Spoiler%20alert!-,redirect%3D%22show%22,-%3E%0A%20%20%20%20%20%20%20%20//%20...%0A%20%20%20%20%20%20%3C/SimpleForm%3E%0A%20%20%20%20%3C/Create%3E%0A%20%20)%3B%0A%7D%3B
This guide is a bit dated for web-related things (mid-2018), this issue is more recent, so this is indeed still an ongoing issue.
I will prepare a new issue.
