### ISSUE TITLE
edit page , the form do not render values

### ISSUE THREAD

**Issue by data-server** [marmelab/react-admin#1992]
**Other information:** edit page , the form do not render values

**Environment**

* React-admin version: v2.1.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/p3nq3lyjzq)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
This works on unit tests and on the demo (https://marmelab.com/react-admin-demo/#/customers/118), so there must be something particular with your code. Please give (way) more details to let us determine if there is a bug.

**Comment by data-server** [comment]
yes , something wrong with my node modules , sorry about that .
