### ISSUE TITLE
When you sequentially navigate between Create forms of different resources, the set of Redux state values: form -> record-form -> values not cleared.

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#2021]
When you sequentially navigate between Create forms of different resources, the set of Redux state values: form -> record-form -> values, not cleared. As a result, the set contains fields from different resources.

* React-admin version: 2.1.2
* React version: 16.3.2
* Browser: Chrome (64-bit) 67.0.3396.99

**Comment by aksaha2311** [comment]
Currently I am also facing the same problem.

**Comment by ronfogel** [comment]
also facing it, can cause serious issues if it saves entities with data from different entities

**Comment by ronfogel** [comment]
@fzaninotto this needs immediate attention

**Comment by djhi** [comment]
Confirmed. It is a side effect of #1997

**Comment by ronfogel** [comment]
@djhi @fzaninotto this bug is introduced back in 2.2.0

**Comment by fzaninotto** [comment]
Should be re-fixed by #2186

**Comment by coltonTB** [comment]
Thanks for fixing this. That's a very serious issue that was causing data corruption in my system. I hope things like this are tracked more closely in the future!
