### ISSUE TITLE
run demo on Windows

### ISSUE THREAD

**Issue by maicss** [marmelab/react-admin#2030]
env:
```
Windows 10;
node: 10.5
yarn 1.7
react-admin: 2.1.2
```
use **Powershell**

steps: 
- clone
- cd react-admin
- yarn
- cd ./example/demo
- `(set REACT_APP_DATA_PROVIDER=rest) ; (yarn start)`

result: 
```
Failed to compile
./src/fakeServer/graphql.js
Module not found: Can't resolve 'data-generator' in 'E:\code\work\react-admin\examples\demo\src\fakeServer'
```

I tried use absolute path, bu it seems so many package use this way...

How do I run this demo right? 

PS: with ubuntu 18.04, it works fine.

**Comment by fzaninotto** [comment]
We don't have Windows, so if you're interested in running the project on that platform, feel free to modify our `makefile` and open a PR. But we won't support it, so I'm closing this issue.

**Comment by djhi** [comment]
@maicss 
Have you tried by installing the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) ?

**Comment by djhi** [comment]
You get this error because running `yarn` is not enough. You have to build every projects before running the demo. You can find the commands to do so inside the makefile

**Comment by djhi** [comment]
We decided to make it easier to work on this project on all platforms. We will convert all our makefile commands as package scripts and keep our precious makefile for people who can run it.

In the mean time, the easiest way (not the quickest though) is to install the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and run `sudo apt install make`. You can then use all our makefile commands.

I reopen this issue until we make the migration to package scripts
