### ISSUE TITLE
Themes don't apply to Fields

### ISSUE THREAD

**Issue by vascofg** [marmelab/react-admin#2031]
Themes don't seem to be applied to Fields, only inputs.
When overriding the theme's `palette` no difference occurs in e.g. TextFields. (Their labels are changed)

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/p3nq3lyjzq)
* A sample application via GitHub

**Comment by vascofg** [comment]
Please check the example:
https://k0w6l94p3.codesandbox.io/#/posts/1/show

As you can see, Fields aren't themed. Also Tab titles don't seem to change color either.

**Comment by djhi** [comment]
Confirmed. We should use the `Typography` component instead of `span` for fields. However, the tab component on the material-ui demo page is behaving the same way. See https://material-ui.com/demos/tabs/ and switch to dark theme using the button in the page header
