### ISSUE TITLE
refreshView does not work in IE

### ISSUE THREAD

**Issue by daniel-molkentin** [marmelab/react-admin#2044]
A connected refreshView does not refresh in IE but in Chrome it does.

**What you were expecting:**
List should refresh.

**What happened instead:**
Information where not refreshed.

**Steps to reproduce:**
Connect the refreshViewAction, change Data and trigger a refreshView from the props.

**Environment**

* React-admin version: 2.1.2
* React version: 16.3.2
* Browser: IE 11.165

**Comment by daniel-molkentin** [comment]
Update:

The Refresh-Button seems to show this behavior too. But only if it is included by setting the actions prop manually. If it is included automatically without setting actions prop, it works in IE.

**Comment by djhi** [comment]
I didn't manage to reproduce your issue on Browserstack which has IE `11.15.16299.0`.

Can you share the code you use in both cases?

**Comment by daniel-molkentin** [comment]
Tried to reproduce the behavior mentioned in my update and I can't. It does not work in both cases now. I am confused. But the IE obviously caches request in my case. Is it neccessary that the API does provide some Header against Caching?

**Comment by daniel-molkentin** [comment]
Thanks for your help either.

**Comment by daniel-molkentin** [comment]
I fixed it by setting the "Cache-Control: no-cache" HTTP-Header. Thanks!

**Comment by sebitoelcheater** [comment]
I had a similar issue with Google Chrome. Resolved with "Cache-Control: no-store".
[https://webmasters.stackexchange.com/questions/103243/why-is-chrome-caching-my-login-page](source)
