### ISSUE TITLE
Tab labels are not displayed in Firefox

### ISSUE THREAD

**Issue by daniel-molkentin** [marmelab/react-admin#2051]
In Firefox Tabs are working but do not show any labels.

**What you were expecting:**
Labels should appear like in IE or Chrome.

**What happened instead:**
Labels are drawn with white color. That could be disabled by disabling the CSS "color: inherit". Maybe Firefox has some strange behavior here.

**Steps to reproduce:**
Add TabbedForm or TabbedShowLayout to React-Admin an try to view the labels of the tabs.

**Environment**

React-admin version: 2.1.2
React version: 16.3.2
Browser: Firefox-Version: 61.0.1 (64-bit)

**Comment by djhi** [comment]
Can't reproduce with same firefox version. Did you customize the theme ?

**Comment by daniel-molkentin** [comment]
No, I did no customization of the theme. I tried on a different machine now and it is working there in the same Firefox version. I'll try to investigate this further. Sorry for the inconvenience.
