### ISSUE TITLE
form.record-form.values state not getting updated when navigating to edit page

### ISSUE THREAD

**Issue by PiotrJozefow** [marmelab/react-admin#2053]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**

From the list of records, I should navigate to `/records/1`, save updates, be redirected to list of records, be able to enter another record at `/records/2` and make updates there.

**What happened instead:**

When I am updating `/records/1`, and then I enter `/records/2`, make changes and hit save button my dataProvider receives incorrect `data` which is previously updated record 1. `previousData` object is correct.

I inspected app with React DevTools and after hitting save State on record 1 and navigating to edit page of record 2, the object for record 1 remains in `form.record-form.values`. `form.record-form.initial` is correct and it has currently visited record 2.

It could be solved by hitting refresh button which triggers `@@redux-form/RESET` action which updates `form.record-form.values` redux state to correct record 2 value.

**Steps to reproduce:**

Enter edit page for one record, save changes. Edit a different record on the list and save some changes. Inspect third `params` parameter in `dataProvider` function where `params.data` comes from previously edited record and `previousData` comes from currently edited record.

**Related code:**

```
export const dataProvider = async (type, resource, params) => {
  console.log(params.id, params.data, params.previousData)
  // params.id doesn't match params.data.id here.
  ...
```

dataProvider is directly injected into Admin:
```
import { Admin } from 'react-admin';
...

export const App = () => (
  <Admin
    dataProvider={dataProvider}
    authProvider={authProvider}
    loginPage={Login}
    history={history}
    title="XYZ"
  >
    <Resource
      name={paths.users}
      list={UserList}
      show={UserShow}
      edit={UserEdit}
      icon={UserIcon}
    />
```

Edit page:
```
import React from 'react';
import { Edit, SimpleForm, LongTextInput, TextField } from 'react-admin';

export const UserEdit = props => (
  <Edit title="User Profile" {...props}>
    <SimpleForm>
      <TextField label="Id" source="id" />
      <TextField source="firstname" />
      ...
```

**Other information:**

**Environment**

* React-admin version: 2.1.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
@djhi does #2037 fix this?

**Comment by djhi** [comment]
Yes

**Comment by lazjramos** [comment]
Hi, we are using the version 2.9.2 and still we have the same problem. I looked in SimpleForm.js in the master branch and still it has the line: "destroyOnUnmount: false,".

Please, can you tell me what must we have to do?
