### ISSUE TITLE
onDrop is not working for FileInput

### ISSUE THREAD

**Issue by ashim-k-saha** [marmelab/react-admin#2083]
**What you were expecting:**

> The `FileInput` component accepts all react-dropzone properties

According to documentation, `FileInput` should take `onDrop` props of react-dropzone.

**What happened instead:**
But `onDrop` is not working as expected. Maybe due to [this](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/FileInput.js#L175).

**Related code:**
```jsx
  <FileInput
    onDrop={this.onDrop}
    source="files"
    label="Files"
    accept="application/pdf, image/jpeg, image/png"
  >
    <FileField  source="src" title="title" />
  </FileInput>
```

**Environment**

* React-admin version: 2.1.2
* Last version that did not exhibit the issue (if applicable): NA
* React version: 16.3.2
* Browser: Google Chrome

**Comment by djhi** [comment]
See https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/FileInput.js#L182

Pass your `onDrop` inside the `options` prop. I'll keep the issue open as we need to update the documentation accordingly
