### ISSUE TITLE
Navigational buttons using Link component don't highlight when tabbing

### ISSUE THREAD

**Issue by cbaker118** [marmelab/react-admin#2085]
**What you were expecting:**
Using tab to navigate through the UI each button in the Actions component (add filter, create, refresh, etc) should highlight in order, showing the user what button they've just tabbed to.

**What happened instead:**
Tabbing shows highlighting on Add Filter, nothing on create, and then highlighting on refresh.

**Steps to reproduce:**
Load up the demo app's list view and tab until Add Filter is highlighted.  Tab once more to see that Create does not get highlighting.  Tab a final time to see that Refresh does get highlighting. 

**Other information:**
This seems to be an issue for any button in react-admin/packages/ra-ui-materialui/src/button/
that uses a '@material-ui/core/Button' and passes in component={Link} including ListButton, EditButton, and CreateButton, to name a few. 

**Environment**

* React-admin version: 2.2.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.4.1
* Browser: Chrome Version 67.0.3396.79 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
confirmed on `master`, but already fixed on `next`, where the buttons highlight in order.

![kapture 2018-07-27 at 12 11 11](https://user-images.githubusercontent.com/99944/43315430-3b77b3d2-9196-11e8-9863-c631933a11ca.gif)

**Comment by cbaker118** [comment]
Making all buttons use a handleClick function which does a window.location.hash = (whatever was being set as the to attribute prev) seems to fix it.  Might be a ham handed approach but it cuts out the use of the Link component, is now tab selectable, and still works with back & forward browser buttons etc.

**Comment by cbaker118** [comment]
Thanks!
