### ISSUE TITLE
Nested routes in tabs

### ISSUE THREAD

**Issue by MROFerreiro** [marmelab/react-admin#2086]
**Is your feature request related to a problem? Please describe.**
Taking the demo as example, I want to have a `<TabbedShowLayout>` that shows data of **User** and has a tab **Reviews** that is responsible for managing the reviews related to that user. In this tab user should be able to do CRUD operations of Reviews associated to the User and have it presented in the route. 

**Describe the solution you'd like**
For example for list the reviews associated to an user the route would be `app/user/userId/reviews` and for creating a new review of that user the route would be `app/user/userId/reviews/create`. The problem I'm having is about similar but doing the above would make the framework more flexible. In theory tab could have any content it wanted transitioning between different content and have that be shown in route permitting navigation inside tab components.

**Describe alternatives you've considered**
From my research I tried to use a `<Route>` from react-router inside a tab and a `<Link>` to change the current route (it could be any of CRUD Buttons too), but since [`<Tabs>` receives the current location pathname](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/TabbedShowLayout.js#L98) if the routes changes to a nested route of tab, that route will never be available because it doesn't exists, it only existed when route was `app/user/userId/reviews` because it was inside the `<Tab>` component for that tab. Making `<Route>` outside `<Tab>` but inside `<TabbedShowLayout>` will make a new tab with the route name, not really nesting it.

**Comment by fzaninotto** [comment]
We don't support this use case, but you can do it in userland, e.g. by writing your own custom `TabbedShowLayout` implementation.

**Comment by aam1r** [comment]
I understand that this is still not supported. Bumping it to show interest in this from my end as well 🙂

**Comment by rajadsms** [comment]
@fzaninotto @marmelab-bot 
Happy New Year in advance
Is nested tab with {syncWithLocation=true} support by React admin?
Or do we have any alternative for that?
Please let us know.
