### ISSUE TITLE
Extra <p> inserted on each save

### ISSUE THREAD

**Issue by ikushlianski** [marmelab/react-admin#2091]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
Expected no extra <p> markup to be inserted on each save.

**What happened instead:**
Each time I save the vacancy with RichTextInput as one of the fields an extra <p> tag appears between one <p> and <ul> that follows it.

**Steps to reproduce:**

1. Type some usual text and then write a list of 2-3 items on the next paragraph. 
Thus you will have something like this:
`<p>We are looking for a skilled and passionate <strong>Embedded Linux Developer</strong>, who is ready to join one of our IoT-focused teams:</p><ul><li>the one is on a mission to transform modern ways of mobility and energy consumption. You will be involved in the development of applications for cloud connected devices and smart electric vehicle chargers on an embedded Linux platform running on an ARM processor;</li><li>another one is at the heart of next-gen automotive solution enabling smarter logistics and advanced telematics for one of the world's leaders in self-driving cars market;</li><li>alternatively, you could pioneer with us in productizing wearable devices which lie at the intersection of IoT, Social data management, Big Data integration and advanced analytics;</li></ul>`
2. Save the post. Enter the edit component again and you will see an extra paragraph inserted between first `<p>` and the `<ul>`
3. Add some text to the 1st item on the list and do not remove the extra paragraph (for reproducing).
4. Save and open the edit component again. You will see a second empty paragraph being added. And so on and so forth.

If one does not touch the list (does not add or remove something from it) the number of empty paragraphs does not increase. The same single empty `<p>` remains after each save. Trying to remove that empty `<p>` is fruitless: it reappears when you next enter the edit component.

**Environment**

* React-admin version: ^2.1.1
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.4.1
* Browser: Chrome, Opera

**Comment by lihop** [comment]
This is related to https://github.com/marmelab/aor-rich-text-input/issues/11.

In https://github.com/marmelab/react-admin/commit/b65e697a5fc55d03e2de48df89a2aeaff029c126#diff-c8090629b5a5ba95a6f9c5154882be18R40 quill was upgraded from v1.1.9 to v1.3.6, meaning that we can now set the `matchVisual` option to `false` in the [clipboard configuration](https://github.com/quilljs/quill/blob/1.3.6/docs/docs/modules/clipboard.md#matchvisual).

I can confirm that this resolves the issue, but it changes the clipboard behaviour so we might want to reset the config after the clipboard has been used to set the content on form load.

https://github.com/marmelab/react-admin/blob/2d169154cb04c4c05899cfa534f437e4b9d776ef/packages/ra-input-rich-text/src/index.js#L31-L42
