### ISSUE TITLE
Create state not clearing after Save.

### ISSUE THREAD

**Issue by tjgragg** [marmelab/react-admin#2092]
In List view, click Create (with redirect='list'), fill out form and click Save
After redirect, click Create.

Expected Result:
Form should be blank.

Actual Result:
All fields are filled in with the values from the previously created item.

Even after navigating to other Lists, selecting Create, and navigating back to the original list and selecting Create, the form fields are all pre-populated with the last item I created.

**Comment by tjgragg** [comment]
The same behavior happens when I go to Create, fill out form, click back to List, then go to Form again.  The state never gets cleared and the form still contains all the values previously entered.

Should the form reset if the component unmounts?

**Comment by djhi** [comment]
Fixed by #2082
