### ISSUE TITLE
Exception on     resettableAppReducer(state, action)

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#2096]
The code of resettableAppReducer is 

```
const resettableAppReducer = (state, action) =>
      appReducer(action.type !== USER_LOGOUT ? state : undefined, action)
```

So if ```action.type === USER_LOGOUT```

```appReducer( undefined, action)``` is call

Unfortunatly, ```appReducer``` is a redux reducer, it check its first argument in a switch

```
export default (previousState, { type, payload }) => {
    switch (type) {
}
```

**An exception is throw**

Will be better to write something like that:

```    const resettableAppReducer = (state, action) => {
        if (action.type !== USER_LOGOUT)
            return appReducer(state, action)
        else
            return state
    }```

**Comment by djhi** [comment]
The first argument is `previousState`, not the action, and we set it `undefined` to reset the store as the reducer will return its initial state when passed an `undefined` state.

The second parameter is the action, which is always defined.

Instead of providing a solution, can you please describe the problem you have, adding the exact error and stack trace, or, even better, provide a codesandbox showing the issue?

**Comment by JacquesBonet** [comment]
Yes you right

Here the exception stack

```
../../packages/ra-core/lib/reducer/admin/resource/list/ids.js.exports.default
/home/jacquesbonet/Documents/software/ticatag/ticatag-front/packages/ra-core/lib/reducer/admin/resource/list/ids.js:46
  43 | exports.default = function () {
  44 |     var previousState = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];
  45 |     var _ref = arguments[1];
> 46 |     var type = _ref.type,
  47 |         payload = _ref.payload;
  48 | 
  49 |     switch (type) {
View compiled
../../packages/ra-core/lib/reducer/admin/resource/list/index.js.exports.default
/home/jacquesbonet/Documents/software/ticatag/ticatag-front/packages/ra-core/lib/reducer/admin/resource/list/index.js:29
  26 | 
  27 | exports.default = function (resource) {
  28 |     return (0, _redux.combineReducers)({
> 29 |         ids: (0, _ids2.default)(resource),
  30 |         params: (0, _params2.default)(resource),
  31 |         selectedIds: _selectedIds2.default,
  32 |         total: (0, _total2.default)(resource)
View compiled
../../packages/ra-core/lib/reducer/admin/resource/index.js.exports.default
/home/jacquesbonet/Documents/software/ticatag/ticatag-front/packages/ra-core/lib/reducer/admin/resource/index.js:38
  35 | var resourceState = {
  36 |     props: action.payload,
  37 |     data: (0, _data2.default)(undefined, action),
> 38 |     list: (0, _list2.default)(undefined, action)
  39 | };
  40 | var _newState = (0, _extends6.default)({}, previousState, (0, _defineProperty3.default)({}, action.payload.name, resourceState));
  41 | 
```

**Comment by djhi** [comment]
Would you mind setting up a codesandbox? I can't reproduce this issue neither on the demo nor on any of the examples

**Comment by JacquesBonet** [comment]
I have the problem with the demo and tutorial.

No with simple example.

**Comment by JacquesBonet** [comment]
Don't know how to do the  test with sandbox

If I check the code in ```ra-core/src/reducer/admin/resource/index.js```

we have the code

```
    if (action.type === REGISTER_RESOURCE) {
        const resourceState = {
            props: action.payload,
            data: data(undefined, action),
            list: list(undefined, action),
        }
        const newState = {
            ...previousState,
            [action.payload.name]: resourceState,
        }

        return newState
    }
```

I have ```action.type === REGISTER_RESOURCE```

so  ```list(undefined, action)``` is executed

Now if I check ```list``` function code we have

```export default resource =>
    combineReducers({
        ids: ids(resource),
        params: params(resource),
        selectedIds,
        total: total(resource),
    })
```

resource is undefined, so ```ids(undefined)``` is executed

ids function code is :


```
export default (previousState = [], { type, payload }) => {
    switch (type) {
        case CRUD_GET_LIST_SUCCESS:
            return addRecordIds(payload.data.map(({ id }) => id), [])
        case CRUD_GET_MANY_SUCCESS:
        case CRUD_GET_MANY_REFERENCE_SUCCESS:
            return addRecordIds(
                payload.data.map(({ id }) => id).filter(id => previousState.indexOf(id) !== -1),
                previousState
            )
...
```
so ```type``` is undefined because only one parameter passed to ids function.
When  "switch" instruction is executed, an exception is throw.

**Comment by JacquesBonet** [comment]
I corrected the problem with the folowing code in /home/jacquesbonet/Documents/software/ticatag/ticatag-front/packages/ra-core/src/reducer/admin/resource/list/index.js :

import { combineReducers } from 'redux'
import ids from './ids'
import params from './params'
import selectedIds from './selectedIds'
import total from './total'

```
export default (resource, action) =>
    combineReducers({
        ids: ids(resource, action),
        params: params(resource, action),
        selectedIds,
        total: total(resource, action),
    })
```

**Comment by djhi** [comment]
That's not the same code as in [`master`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/reducer/admin/resource/list/index.js). Where did you get that?

**Comment by JacquesBonet** [comment]
I'm on master.

I make a new git clone on master.

Now I  have good code for list/index.js.

```
import { combineReducers } from 'redux'
import ids from './ids'
import params from './params'
import selectedIds from './selectedIds'
import total from './total'

export default combineReducers({
    ids,
    params,
    selectedIds,
    total,
})
```

Others files didn't change

Don't understand why I get code of next branch for this file, and only for this file.

All its fine now.


Thks a lot djhi

**Comment by djhi** [comment]
Your code above looks like an old version of ours before we refactored the `list` reducers from reducer factories to simple reducers. Aren't you using the official `react-admin` package?

**Comment by djhi** [comment]
`master` has not been backported to `next` yet but it will soon
