### ISSUE TITLE
Autocomplete list is cut off by content area

### ISSUE THREAD

**Issue by esoulution** [marmelab/react-admin#2097]
![bug_autocomplete](https://user-images.githubusercontent.com/136239/43367193-033b7a22-9352-11e8-90ed-49e5e0701a6b.png)

**Environment**

* React-admin version: 2.1.4
* React version: 16.3.0
* Browser: Google Chrome 68.0.3440.75

**Comment by fzaninotto** [comment]
IMHO it's a react-autosuggest bug, I'm not sure we should fix it ourselves

**Comment by fzaninotto** [comment]
I had to revert #2123, so I'm reopening this one.
