### ISSUE TITLE
Filters TextInput source doesn't respect dot value city.name and gets converted to city[name]

### ISSUE THREAD

**Issue by diimpp** [marmelab/react-admin#2102]
Hi,

**What you were expecting:**

```js
 <Filter {...props}>
  <TextInput label='City' source='city.name' alwaysOn />
</Filter>
```
expected result request parameter is `city.name=value`

**What happened instead:**
I've got  result request parameter `city[name]=value` instead

* React-admin version: 2.0.3
* React version: 16.4.1
* Browser: firefox-59.0.3

Maybe it's not much as bug as *desired* behaviour, but how do I avoid it?

**Comment by diimpp** [comment]
After some research,

it looks like intended behaviour of `redux-form`, which can be solved by providing custom `onSubmit` handler to `FilterForm`.

https://stackoverflow.com/questions/47536618/is-there-any-way-to-have-redux-form-ignore-dots-in-a-field-name
https://github.com/erikras/redux-form/issues/2806

**Comment by zzdjk6** [comment]
Another way to hack around this problem:

In the Filter component, we could you another symbol like "->" insteand of "." (dot):

```tsx
<TextInput source="city->name" />
```
and then in the `dataProvider`, we could transfer it back:

```ts
// Add all filter params to query.
Object.keys(params.filter || {}).forEach((key) => {
  if (key.includes("->")) {
    // Hack around dot issue for filters: https://github.com/marmelab/react-admin/issues/2102
    queryParams[`${key.replace("->", ".")}`] = params.filter[key];
  } else {
    queryParams[`${key}`] = params.filter[key];
  }
});
```
