### ISSUE TITLE
BulkAction with subMenu

### ISSUE THREAD

**Issue by L-Luciano** [marmelab/react-admin#2104]
**Is your feature request related to a problem? Please describe.**
Hi,

I would like to put a subMenu in my bulk actions. I explain : If I need to enable/disable my selectedRows, 

**Describe the solution you'd like**
I would like to put a menu "enable" with a sub menu "On", "Off" instead of add 2 menu "enable on", "enable off"

**Comment by djhi** [comment]
Hi, and thanks for your question! 

This is achievable in userland using material-ui components and by not using the default `BulkActions` component.

I'm closing this issue and invite you to ask how to do it on [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
