### ISSUE TITLE
Add Field counterpart for SelectArrayInput, e.g. SelectArrayField

### ISSUE THREAD

**Issue by diimpp** [marmelab/react-admin#2109]
I'm able to render multiple select input with integer values and labels mappings this way
> <SelectArrayInput {...props} source='days' choices={weekdays}/>

but I don't find `SelectArrayField` to render those values afterwards.

**Comment by diimpp** [comment]
And I cannot make it work with something like
```js
const DayField = ({ record = {} }) => <span>{get(record)}</span>;
<ArrayField source='days'>
    <DayField />
</ArrayField>
```

**Comment by fzaninotto** [comment]
Use `ArrayField` or a custom component, es explained in the documentation

https://marmelab.com/react-admin/Fields.html#arrayfield
