### ISSUE TITLE
AutocompleteInput don't update suggestions afrer first event ocurr

### ISSUE THREAD

**Issue by nikun** [marmelab/react-admin#2121]
**What you were expecting:**
Reload the suggestions every time the input value change

**What happened instead:**
The suggestions are only updated on the first use, then when event ocurrs (focus,click,etc) the suggestions never update again

**Steps to reproduce:**
1. type some val in the AutocompleteInput
2. focus on other control
3. focus on AutocompleteInput
4. type the same val

**Other information:**

![selection_053](https://user-images.githubusercontent.com/1055045/43539348-07f98c20-959b-11e8-95c2-55e224568ee0.png)
![selection_054](https://user-images.githubusercontent.com/1055045/43539354-0bb41e52-959b-11e8-9553-7d9609f22a9d.png)

**Environment**
* React-admin version: 2.1.5
* React version: 16.4.1
* Browser: Chromium Version 68.0.3440.75

**Comment by djhi** [comment]
Can't reproduce on the simple example. Can you setup a codesandbox?

**Comment by lihop** [comment]
@djhi to be clear here is a comparison of the expected and actual behaviour:

**Expected**

![expected](https://user-images.githubusercontent.com/3696783/43611921-ea559cc8-96d4-11e8-8016-63077ec5f81a.gif)

**Actual**
![actual](https://user-images.githubusercontent.com/3696783/43611951-fb88c678-96d4-11e8-8240-0d22f6b467ef.gif)

codesandbox here: https://380k0r05rp.codesandbox.io/#/posts/create
failing unit test here: https://github.com/vinmasvn/react-admin/commit/0a7be401fdca17daac7822589b43e791dc9c09f1

I fixed the issue in this commit https://github.com/vinmasvn/react-admin/commit/6080316cde2c5d38b83e61cceb87cc3e23ddf611 but I don't think it's ready for a PR.

The main issue around the `prevSuggestions`. The `handleSuggestionsFetchRequested()` function is always called after `updateFilter()` and sets the `suggestions` state to `prevSuggestions` if it is truthy. Initially `prevSuggestions` is falsy so the component works initially, but it is set when the input is blurred so thereafter the suggestions never appear to update.

Another smaller issue is that `previousFilterValue` is not reset when the input is blurred meaning if you were to type a character, blur, refocus, and type the same character the filter would not update:
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/AutocompleteInput.js#L391-L404
