### ISSUE TITLE
Incorrect documentation for export button feature

### ISSUE THREAD

**Issue by stultusstudio** [marmelab/react-admin#2133]
**What you were expecting:**

The export button to create a single CSV.

**What happened instead:**

The export button creates a csv for every entry. This is because downloadCSV() is called within the map function within the documentation.

**Steps to reproduce:**

Implement the "simple" exporter as specified in the documentation here: https://marmelab.com/react-admin/List.html#exporter

Then click Export.

This will proceed to download multiple csv files like this:

![image](https://user-images.githubusercontent.com/20275787/43701846-0e9d0274-999b-11e8-88c6-241fdf1711e6.png)

**Related code:**

The code below is included in the documentation for the newly released export feature.

https://marmelab.com/react-admin/List.html#exporter

```
const exporter = (data) => data.map(post => {
    const { postForExport, backlinks, author } = post; // omit backlinks and author
    postForExport.author_name = post.author.name; // add a field
    const csv = convertToCSV({
        data: postForExport,
        fields: ['id', 'title', 'author_name', 'body'] // order fields in the export
    });
    downloadCSV(csv, 'posts'); // download as 'posts.csv` file
})
```

**Environment**

* React-admin version: 2.2.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Sorry, I wanted to publish a PR but I inadvertendly published to master instead... See ec6169e for the changeset.
