### ISSUE TITLE
NumberInput accepts letters on Firefox and Safari

### ISSUE THREAD

**Issue by acidburnt** [marmelab/react-admin#2135]
**What you were expecting:**
NumberInput component should not accept letter input.

**What happened instead:**
On Firefox (61.0) and Safari you are able input letters and special characters to the NumberInput field.

**Steps to reproduce:**
https://monosnap.com/file/2qxRUmvJ6hFhfhebCd33XrnyIW78Q2
it was recorded on https://marmelab.com/admin-on-rest-demo/#/products/19
sorry for the quality but I think you can see what's going on

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 2.1.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.2
* Browser: Firefox(61) and Safari
* Stack trace (in case of a JS error):

**Comment by kleberapsilva** [comment]
IE to

**Comment by fzaninotto** [comment]
It makes sense: `1e10` is a valid number.

It's up to you to add the `number` validator to avoid non-number inputs.
