### ISSUE TITLE
Custom value field in AutocompleteInput inside ReferenceInput

### ISSUE THREAD

**Issue by tomasgvivo** [marmelab/react-admin#2139]
When using AutocompleteInput inside ReferenceInput, is it possible to define which field from the reference entity use as the AutocompleteInput value?

Example:
```
<ReferenceInput source="country_code" label="Country" reference="Country" perPage={5}>
  <AutocompleteInput optionText="name" />
</ReferenceInput>
```

Where Country:

id | name | code
--- | --- | ---
1 | Aruba | aw
2 | Afghanistan | af
3 | Angola | ao

I want to save country.code of the selected country into country_code.

**Comment by djhi** [comment]
Duplicate of #2130
