### ISSUE TITLE
Reference filter value : true / false as 1 / 0 in query string ?

### ISSUE THREAD

**Issue by esoulution** [marmelab/react-admin#2149]
```
<ReferenceInput label="Users" source="user_id" reference="users" perPage={100} 
 sort={{ field: "username", order: "ASC" }} filter={{ is_active: true }}>
        <SelectInput optionText="username" />
</ReferenceInput>
```
API request

> GET /api/users?_end=100&_order=ASC&_sort=username&_start=0&is_active=true

should it be better **is_active=1** ?

**Comment by djhi** [comment]
It depends. That's the job of your dataprovider to translate the parameters into what your API expects.
