### ISSUE TITLE
BooleanInput within ArrayInput and SimpleFormIterator with defaultValue clears entire form

### ISSUE THREAD

**Issue by tjgragg** [marmelab/react-admin#2150]
This took me several hours to figure out what was going on, but it turns out, if you have a 
```
<SimpleForm>
  <TextInput label="someText"/>
  <ArrayInput>
    <BooleanInput label="someLabel" defaultValue={true}/>
  </ArrayInput>
</SimpleForm>
```
Enter some text in the TextInput field, not click the Add button.
The form gets cleared.
https://codesandbox.io/s/kkyqop24w7

If you remove defaultValue, the issue goes away.

**Comment by djhi** [comment]
This has been fixed in `2.2.0`. See https://codesandbox.io/s/q715xwwn09. I also fixed the references to material-ui packages
