### ISSUE TITLE
Increase total after CRUD_CREATE

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#2153]
I have this Resource that only has a `list` prop and no `create` prop. The List component has a button that opens a Create Dialog. That Dialog is a custom component that is essentially a copy of everything that Create is. Except that Card is now Dialog. No route change happens upon opening or closing of the Dialog. 

After the records is created, I can see the `ids` and `data` prop being updated on the Datagrid, but the `total` prop is not. That prevents the Datagrid to update and show the newly created record.

(One quirk. When the list starts empty, the behaviour is as how I described. When the list already contained a record, the lists updates just fine after the creation Dialog)

Demonstration here: https://codesandbox.io/s/9zwjyq1znp

**Describe the solution you'd like**
In the admin resource reducer where the total is changed, can you also act on the CRUD_CREATE action? This is my feature request.

```javascript
import {
    CRUD_GET_ONE_SUCCESS,
    CRUD_GET_LIST_SUCCESS,
    CRUD_DELETE_OPTIMISTIC,
    CRUD_DELETE_MANY_OPTIMISTIC,
} from '../../../../actions/dataActions';

export default (previousState = 0, { type, payload }) => {
    if (type === CRUD_GET_ONE_SUCCESS) {
        return previousState == 0 ? 1 : previousState;
    }
    if (type === CRUD_GET_LIST_SUCCESS) {
        return payload.total;
    }
    // vvv
    if (type === CRUD_CREATE) {
        return previousState + 1;
    }
    // ^^^
    if (type === CRUD_DELETE_OPTIMISTIC) {
        return previousState - 1;
    }
    if (type === CRUD_DELETE_MANY_OPTIMISTIC) {
        return previousState - payload.ids.length;
    }
    return previousState;
};
```

This would cause the Datagrid to update, because:
https://github.com/marmelab/react-admin/blob/6be6aa1f80d4e53f0f861f010f3242af68203e6c/packages/ra-core/src/controller/ListController.js#L115-L128

**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by christiaanwesterbeek** [comment]
> This would cause the Datagrid to update, because:

This statement I made was false. I misread the condition in `shouldComponentUpdate`. Just a change of `ids` should be enough for the list component to update.

Nonetheless, the sandbox shows that it doesn't happen when there are no records in the list to start with. The feature request I proposed may not solve this problem.

To conclude.
1. I got a bug that I need to solve :) And 2. you can do with this feature request whatever you like. It seems to make sense to me, but it may not even solve my problem (in the sandbox).

**Comment by djhi** [comment]
Thanks for reporting, this looks like a bug to me

**Comment by djhi** [comment]
Actually not really a bug. The optimistic `CRUD_DELETE_OPTIMISTIC` and `CRUD_DELETE_MANY_OPTIMISTIC` actions do not update the `total` themselves but triggers a refresh of the view (the `List`) once they have been dispatched for real and succeeded, which updates the `total`.

In your case, you can also dispatch a `refreshView` action after the matching `CRUD_CREATE_SUCCESS` has been dispatched. This can be achieved with a custom `crudCreate` action creator using the `onSuccess` meta:

```js
import { crudCreate } from 'react-admin';

export const myCrudCreate = (resource, data, basePath, redirectTo) => {
    const action = crudCreate(resource, data, basePath, redirectTo);
    action.meta.refresh = true;

    return action;
}
```
Feel free to reopen if needed.
