### ISSUE TITLE
Filters not working while object given as source

### ISSUE THREAD

**Issue by sofalse** [marmelab/react-admin#2170]
**What you were expecting:**

I expected <Filter> component to work as it should — pass the proper key and value into API query.

**What happened instead:**

<img width="302" alt="screen shot 2018-08-16 at 14 10 29" src="https://user-images.githubusercontent.com/17087206/44209427-c0022380-a163-11e8-99fb-66e042df4e14.png">

[object Object] is being sent (it is a string).

**Steps to reproduce:**

**Related code:**

```js
// in the <List> :
<List title="Users" {...props} bulkActions={false} filters={<UserFilters />}>
    <Datagrid>
        (...)
        <BooleanField source="email.active" label="Email active" />
        (...)
    </Datagrid>
</List>

// in the <Filter>:
<Filter {...props}>
    (...)
    <BooleanInput source="email.active" label="Email active" />
    (...)
</Filter>
```

**Other information:**

Of course everything is wrapped in functional components, just skipped that code in here because I find it obvious.
**Environment**

* React-admin version: 2.1.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
This is the job of your `dataProvider` to translate those object filters into the format expected by your API. If you have troubles implementing your custom `dataProvider`, please ask for help on StackOverflow
