### ISSUE TITLE
CreateController breaks flow of 'redirect' prop

### ISSUE THREAD

**Issue by stixistyson** [marmelab/react-admin#2176]
**Is your feature request related to a problem? Please describe.**
When you pass a redirect prop from RA-UI-MaterialUI/detail/Create, it dies in the RA-Core/CreateController and is set based on an internal function.

**Describe the solution you'd like**
Only set default if you haven't passed the prop.

**Describe alternatives you've considered**
_**Even better! - Solution!**_

replace CreateController.defaultRedirectRoute to:
```js
    defaultRedirectRoute() {
        if (this.props.redirect) return this.props.redirect;
        const { hasShow, hasEdit } = this.props;
        if (hasEdit) return 'edit';
        if (hasShow) return 'show';
        return 'list';
    }
```
or
```js
    defaultRedirectRoute() {
        const { hasShow, hasEdit, redirect } = this.props;
        if (redirect) return redirect;
        if (hasEdit) return 'edit';
        if (hasShow) return 'show';
        return 'list';
    }
```

**Comment by djhi** [comment]
Hi, thanks for taking time to analyze this. This is not correct though:

See https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/Create.js#L71

Here we either apply the `redirect` from the `CreateView` children, or the one passed by the `CreateController` (https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/Create.js#L140)

**Comment by djhi** [comment]
Can you please explain your issue instead?

**Comment by stixistyson** [comment]
Ok, so with the information you have listed, I am seeing another way to get this to work without recreating the files in react-admin's library. 

I am using react-admin through api-platform/admin and after previously passing desired props though the same method to their 'List' form, I was frustrated that the create form broke the passing of the 'redirect' prop. Being their create form does show the children, I will try this solution. If it works, I am satisfied.

Apparently my issue was placing the prop in the element that uses the value, instead of where it is generated from.

**Comment by djhi** [comment]
Can we close this then ?

**Comment by stixistyson** [comment]
Yes, It is working.
