### ISSUE TITLE
Show / SimpleShowLayout Does not Render Fields When in a Grid

### ISSUE THREAD

**Issue by jayfar** [marmelab/react-admin#2185]
**What you were expecting:**
When using material UI Grid in an _Edit_ or _Create_ page, the field contents displayed perfect. I expected the Grid to work the same way on a _Show_ page.

**What happened instead:**
When using the same Grid on a _Show_ page, the fields did not display.

**Steps to reproduce:**
Modify the demo/example https://marmelab.com/react-admin/Show.html#the-simpleshowlayout-component to include a Material UI Grid that wraps the fields.

**Related code:**
```
import Grid from '@material-ui/core/Grid';

export const PostShowx = (props) => (
    <Show {...props}>
        <SimpleShowLayout>
			<Grid container >
				<Grid item xs={6}>
					<TextField source="title" />
				</Grid>
				<Grid item xs={6}>
					<TextField source="name" />
				</Grid>
			</Grid>
            <RichTextField source="body" />
        </SimpleShowLayout>
    </Show>
);
```
Even a simple html table seems to not render the TextFields:
```
export const PostShow = (props) => (
    <Show {...props}>
        <SimpleShowLayout>
			<table>
				<tr>
					<td>
						<TextField source="title" />
					</td>
					<td>			
					       <TextField source="name" />
					</td>
				</tr>
			</table>
            <RichTextField source="body" />
        </SimpleShowLayout>
    </Show>
);
```
Note: It works just fine on an Edit page:
```
export const PostEdit = (props) => (
    <Edit title={<PostTitle />} {...props}>
        <SimpleForm>
            <DisabledInput source="id" />
			<Grid container >
				<Grid item xs={6}>
					<ReferenceInput label="User" source="userId" reference="users">
						<SelectInput optionText="name" />
					</ReferenceInput>
				</Grid>
				<Grid item xs={6}>
					<TextInput source="title" />
				</Grid>
			</Grid>
            <LongTextInput source="body" />
        </SimpleForm>
    </Edit>
);
```

**Environment**

* React-admin version: 2.2.0
* React version: 16.4.1
* Browser: Tried on both Firefox and Chrome

**Comment by djhi** [comment]
It won't work because the `SimpleShowLayout` expects its children to be fields and the `SimpleForm` expect its children to be inputs. You'll have to implement your own layout and form components to have a grid

**Comment by djhi** [comment]
This could probably be fixed using the context API. The layout component might provide a context setting the `record` (and other required props such as `basePath` and `resource`) and we could provide a `withRecord` HOC consuming this context and passing the required props to the fields components.

This would allow for a lot easier customization path. I event think this should be the default but for backward compatibility sake, we should not make it mandatory in `2.X` version. @fzaninotto, thoughts ?

**Comment by fzaninotto** [comment]
In a form, we inject not only the `record`, but also the `input`, the `basePath`, and the `resource`. In a list, we inject not only the `record`, but also the `basePath` and the `resource`. So the context should provide more than just the `record`.

I'm not fond of the idea, because it's even more magic than the props injection that we do. Besides, it makes custom components harder to write, as they need to grab the `record` from a ContextProvider instead of props.

I think @jayfar's need can be achieved in userland using a custom layout. `<SimpleShowLayout>` only works if you pass fields as children.

**Comment by djhi** [comment]
>  Besides, it makes custom components harder to write, as they need to grab the `record` from a ContextProvider instead of props.

We can ease that by providing an HOC ;)

**Comment by jessemlay** [comment]
Has anyone created such a HOC, that I could see a example of. We are having this issue and some direction would be appreciated.

**Comment by rafaltrojanowski** [comment]
I'm experiencing the same problem. Would be really cool to have it supported out of the box because in case of many attributes the list will be very long so UX is not so great.

**Comment by ronco95** [comment]
i've solved this issue just pass the code as a const and use the record for call the data
```
const Forma = ({ record }) => (
  <span>
    <Grid container>
      <Grid xs={12} sm={2}>
        postazione: <br/> {record.postazione}
        </Grid>
        <Grid xs={12} sm={2}>
        riga: <br/> {record.riga}
        </Grid>
        <Grid xs={12} sm={2}>
        commessa: <br/> {record.commessa}
      </Grid>
    </Grid>
  </span>
);
```
and 

```
<SimpleShowLayout>

      <Forma />
    </SimpleShowLayout>
```
