### ISSUE TITLE
Dateinput broken in react-admin demo

### ISSUE THREAD

**Issue by kleberapsilva** [marmelab/react-admin#2201]
Dateinput broken in react-admin demo

![dateinput](https://user-images.githubusercontent.com/11722264/44486515-2d152d80-a62a-11e8-8f03-beec54cb2309.gif)

React-admin version: 2.2.0
Last version that did not exhibit the issue (if applicable): unknown
React version: 16.4.2
Browser: Chrome 68.0.3440.106

**Comment by djhi** [comment]
Can't reproduce this issue on the demo.

**Comment by kleberapsilva** [comment]
I'm Brazilian, is it a country problem?

**Comment by djhi** [comment]
It might be and this is not an issue we will address in react-admin. Material-ui did not port their DatePicker on v1. You'll probably have to create a custom input for date/time, using any of the libraries for material-ui v1: https://material-ui.com/discover-more/related-projects/#material-ui-specific-projects

If you do, please open source them and we will gladly include them in our Ecosystem documentation page :)

**Comment by mexitalian** [comment]
Oi @kleberapsilva :)
I'm in México and was having a similar issue, the input date was jumping back a day.
To fix it, you can override the date parser used, [explained here](https://github.com/vascofg/react-admin-date-inputs#provideroptions-prop).

```
import MomentUtils from 'material-ui-pickers/utils/moment-utils';

<DateInput
  source="date_of_birth"
  label="DOB"
  options={{
    format: 'MM/DD/YYYY',
    disableFuture: true
  }}
  providerOptions={{ utils: MomentUtils }}
/>
```
