### ISSUE TITLE
Remove `stage-0` preset in `.babelrc`

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#2210]
Babel is [deprecating `stage-` presets](https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets) and it makes sense.

React-admin uses the `stage-0` preset. We should replace it with the features we actually use.

**Comment by Kmaschta** [comment]
What about just using babel-preset-env ?

**Comment by fzaninotto** [comment]
Fixed by #2218
