### ISSUE TITLE
When you replace List default actions with a custom list, Bulk Actions are no longer displayed

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#2224]
When you replace List default actions with a custom list actions (as described in the documentation), Bulk Actions are no longer displayed.

* React-admin version:  2.2.2
* React version: 16.3.2
* Browser: Chrome 68.0.3440.106

**Comment by Kmaschta** [comment]
Please, can you provide a codesandbox including the issue in a reproducible way, so that we can debug it?

**Comment by MaxAlex666** [comment]
Yes, the example lacks the following code from the ListActions:

`const PostActions = ({
    basePath,
    currentSort,
    displayedFilters,
    exporter,
    filters,
    filterValues,
    resource,
    showFilter,

    bulkActions,
    selectedIds,
    onUnselectItems,
}) => (
    <CardActions>
      {bulkActions && React.cloneElement(bulkActions, {
        basePath,
        filterValues,
        resource,
        selectedIds,
        onUnselectItems,
      })}
    ...`

So works.
