### ISSUE TITLE
ReferenctInput tag gets stuck on progress spinner.

### ISSUE THREAD

**Issue by curtisolson** [marmelab/react-admin#2244]
**What you were expecting:**
ReferenceInput calls a resource, but that resource API does not include a Content Range header in the response. I would like to get an error instead of the progress bar. As far as I could tell, no error condition was flagged in the code. 

**What happened instead:**
Progress bar never completed even though I was able to see data in the Dev Tools.

If this isn't a bug, I created a question with answer in stackoverflow to help someone else debug it. 

**Other information:**
[https://stackoverflow.com/questions/52083078/referenceinput-field-shows-progress-bar-but-never-resolves/52083079#52083079](https://stackoverflow.com/questions/52083078/referenceinput-field-shows-progress-bar-but-never-resolves/52083079#52083079)

**Comment by djhi** [comment]
Thanks for reporting this issue! It is very similar to #854 though so I'm closing it in favor of the old one. You may comment on #854 to explain your use case. Feel free to reopen if you disagree.

**Comment by curtisolson** [comment]
It's the same. I'll add some comments there. Sorry for the dupe.
