### ISSUE TITLE
AutocompleteInput should allow the specification of a suggestion size limit

### ISSUE THREAD

**Issue by vascofg** [marmelab/react-admin#2250]
Currently when AutocompleteInput receives a large number of options it displays all of them. (see pic):

![image](https://user-images.githubusercontent.com/634441/44853551-29069280-ac5e-11e8-8304-aad96957fe56.png)

This behavior should be customizable by prop, something like
```jsx
  <AutocompleteInput suggestionLimit={5} />
```

**Comment by fzaninotto** [comment]
Marking this as a "good first issue" as the implementation should be straight forward, according to https://github.com/moroshko/react-autosuggest/pull/132

**Comment by mohinderps** [comment]
But I do have a question on getting started. Now I want to make changes in packages/ra-ui-materialui. After I make the change, I build it using the "build" script from package.json, which will put all the build files in the lib folder. Now how do I proceed from there onwards ?

**Comment by fzaninotto** [comment]
You do not need to `build` for development ; just run `make run` and you can test your changes against the simple example.

**Comment by mohinderps** [comment]
Okay, Got it!

**Comment by mohinderps** [comment]
With the current behaviour of AutocompleteInput, all of the suggestions are shown at once. And when the number of matches against the input turns 1, only the the suggestions are set to the corresponding suggestion. How will suggestion Limit work in this case ?

**Comment by fzaninotto** [comment]
Fixed by #3326
