### ISSUE TITLE
AutocompleteInput suggestions appear outside of screen (to the right) when inside ArrayInput

### ISSUE THREAD

**Issue by vascofg** [marmelab/react-admin#2256]
### Bug report

**Steps to reproduce:**

Please check this sandbox: https://0mny4j7zon.codesandbox.io/#/comments

- Click edit in a comment
- If you click "Add" on the post array, AutocompleteInput loads and shows the suggestions
- Navigate away, e.g. click "Show" on top
- Go back to edit the same comment
- If you click "Add" on the post array now, suggestion appear way to the right outside the screen
- If you try to scroll using the horizontal scroll bar the suggestions jump to the correct location

**Comment by djhi** [comment]
It should be fixed with #2240 which will be released in `2.2.3`

**Comment by vascofg** [comment]
OK thanks, I missed that issue!

**Comment by vascofg** [comment]
@djhi issue seems to still be present in `2.2.3`

**Comment by vascofg** [comment]
**Correction:** The suggestions actually appear but way to the right (check horizontal scroll bar).
When you click said scroll bar, the suggestions suddenly jump to the correct location.

**Comment by fzaninotto** [comment]
Could you join a screencast, and more details about your browser and system?

**Comment by vascofg** [comment]
Absolutely, how can we schedule that?

**Comment by djhi** [comment]
I think @fzaninotto meant a video recording of the issue

**Comment by vascofg** [comment]
Oh ok, I'll send something on Monday.

**Comment by vascofg** [comment]
@fzaninotto @djhi here it is.

![peek 2018-09-03 10-29](https://user-images.githubusercontent.com/634441/44979229-720f5d00-af64-11e8-8b1e-1887c06af9e1.gif)

**Comment by vascofg** [comment]
Issue is still present in 2.4.0
Any idea where one can start debugging this?

**Comment by audunhalland** [comment]
I can no longer reproduce this issue in 2.8.5. I think it can be closed.
