### ISSUE TITLE
ReferenceArrayInput throws error after fetching data selected by a ReferenceInput

### ISSUE THREAD

**Issue by bernd-protofy** [marmelab/react-admin#2271]
**What you were expecting:**
I select a id from a ReferenceInput (SelectInput) and with the selected id fetch data for a ReferenceArrayInput with a SelectArrayInput (with a chipfield)

**What happened instead:**
I select a id from a ReferenceInput (SelectInput) and the loading indicator is shown.
The following error is shown in the console.
index.js:2178 uncaught at handleFetch TypeError: Cannot read property 'error' of null
    at ./node_modules/ra-core/lib/reducer/admin/references/possibleValues.js.exports.default

**Related code:**
```
<Create {...props} >
    <TabbedForm>
      <FormTab>
        <ReferenceInput
          source="estateId"
          reference="estates"
        >
          <SelectInput optionText="name" />
         </ReferenceInput>
        <FormDataConsumer>
          {({ formData, ...rest }) =>
            formData.estateId && (

              <ReferenceArrayInput
                reference={`estates/${formData.estateId}/livingUnits`}
                source="livingUnitIds"
                {...rest}
              >
                <SelectArrayInput>
                  <ChipField source="name" />
                </SelectArrayInput>
                  
              </ReferenceArrayInput>
            )
          }
        </FormDataConsumer>
      </FormTab>
</Create>
```

**Other information:**
The api calls are both working and do not throw any error.

In the first ReferenceInput call the needed data for the ReferenceArrayInput is already fetched as a subarray. Is it easier to use these information and how?

**Environment**

* React-admin version:
    "react-admin": "^2.2.2",
* React version:
    "react": "16.3.2",
    "react-dom": "16.3.3",
* Browser:
 alll
* Stack trace (in case of a JS error):
at ./node_modules/ra-core/lib/reducer/admin/references/possibleValues.js.exports.default (http://localhost:3000/static/js/bundle.js:73285:129)
    at combination (http://localhost:3000/static/js/bundle.js:141149:29)
    at combination (http://localhost:3000/static/js/bundle.js:141149:29)
    at combination (http://localhost:3000/static/js/bundle.js:141149:29)
    at resettableAppReducer (http://localhost:3000/static/js/bundle.js:66741:16)
    at dispatch (http://localhost:3000/static/js/bundle.js:141385:22)
    at http://localhost:3000/static/js/bundle.js:123474:18
    at http://localhost:3000/static/js/bundle.js:139326:22
    at dispatch (http://localhost:3000/static/js/bundle.js:140940:18)
    at http://localhost:3000/static/js/bundle.js:140830:12
    at http://localhost:3000/static/js/bundle.js:139853:52
    at exec (http://localhost:3000/static/js/bundle.js:140493:5)
    at flush (http://localhost:3000/static/js/bundle.js:140534:5)
    at asap (http://localhost:3000/static/js/bundle.js:140507:5)
    at runPutEffect (http://localhost:3000/static/js/bundle.js:139850:69)
    at runEffect (http://localhost:3000/static/js/bundle.js:139799:307)
    at next (http://localhost:3000/static/js/bundle.js:139679:9)
    at currCb (http://localhost:3000/static/js/bundle.js:139752:7)
    at http://localhost:3000/static/js/bundle.js:139815:14
__stack_frame_overlay_proxy_console__ @ index.js:2178
log @ utils.js:225
logError @ proc.js:210
(anonymous) @ proc.js:493
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:451
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
checkEffectEnd @ proc.js:612
chCbAtKey @ proc.js:627
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
(anonymous) @ bindActionCreators.js:3
fetchOptions @ ReferenceArrayInputController.js:292
fetchReferencesAndOptions @ ReferenceArrayInputController.js:205
componentDidMount @ ReferenceArrayInputController.js:168
commitLifeCycles @ react-dom.development.js:9784
commitAllLifeCycles @ react-dom.development.js:11455
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:11594
completeRoot @ react-dom.development.js:12502
performWorkOnRoot @ react-dom.development.js:12452
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
interactiveUpdates @ react-dom.development.js:12597
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259

**Comment by bernd-protofy** [comment]
The problem is the nested resource. When i'm switching reference={`estates/${formData.estateId}/livingUnits`} to a different endpoint for testing, the ReferenceArrayInput will be filled. 
Does anybody has tried normalizr with react admin? https://github.com/paularmstrong/normalizr

**Comment by djhi** [comment]
Do you have a resource named `estates/${formData.estateId}/livingUnits`? It does not look like a resource name. You probably want to reference the `livingUnits` resource with a filter `{ estateId: formData.estateId }` which you can add to the `ReferenceArrayInput`

**Comment by bernd-protofy** [comment]
Hi Gildas, react admin does not support nested resource, so no - i don't have it. 
But, i get all the information i need with the ReferenceInput on the estates resource. here is the simplified response:
````
{
  "id": 5,
  "name": "test",
  "livingUnits": [
    {
      "id": 1,
      "name": "all"
    },
    {
      "id": 2,
      "name": "1."
    }
  ]
}
````
how can i access the livingunits information to fill the ReferenceArrayInput choices?
