### ISSUE TITLE
graphql readme is outdated

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#2274]
**What you were expecting:**

Readme copy/paste working out of the box :-)

**What happened instead:**

createNetworkInterface is not available on react-apollo@2
![image](https://user-images.githubusercontent.com/551837/44999263-1e306280-afbc-11e8-874f-e602851402e8.png)

I didn't go very deep in this issue but this issue https://github.com/apollographql/apollo-client/issues/2458  consolidated my idea that the readme was obsolete.

By the way I would argue that `react-apollo` should be added to the dependencies to install because configuring API URI is a must

**Comment by djhi** [comment]
Closed by #2275

**Comment by gl4ssiest** [comment]
createNetworkInterface still on [readme.md](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql#customize-the-apollo-client) leading to confusion about graphql connections.
