### ISSUE TITLE
ReferenceInput fetches the referenced record with GET_MANY and a filter on a single ID instead of GET_ONE

### ISSUE THREAD

**Issue by bernd-protofy** [marmelab/react-admin#2287]
**What you were expecting:**
The documentation for ReferenceInput says:
"This component fetches the possible values in the reference resource (using the GET_LIST REST method) and the referenced record (using the GET_ONE REST method)"

**What happened instead:**
The referenced record is using the GET_MAY REST method with a filter on a single ID.

**Steps to reproduce:**
Use a ReferenceInput and log the used REST methods

**Environment**

* React-admin version: 2.2.4
* React version: 16.3.2

**Comment by djhi** [comment]
We should update the documentation. It uses `GET_MANY` to optimize the calls made to the API when multiple `ReferenceInput` are used for the same resource (for example, when used inside an `ArrayInput`)

**Comment by fzaninotto** [comment]
The call made by `ReferenceInput` should not depend on whether it's inside an `ArrayInput` or not. So it has to be a `GET_MANY`.

**Comment by jtomaszewski** [comment]
> The call made by ReferenceInput should not depend on whether it's inside an ArrayInput or not. So it has to be a GET_MANY.

How about we make that customizable? In our case, we do not really provide `GET_MANY` for most of the resource clients, as we don't really need that. (We use only `GET_ONE` for now.) To add `GET_MANY` everywhere, that'd involve quite a bit of backend work on our side.

Could we have a prop `referenceLoadType: "GET_ONE" | "GET_MANY" = "GET_MANY"`, that would be passed down to `useReference` hook inside of the `ReferenceInput` internals? This would solve the problem for us.

What do you think? I could submit a PR for that.
