### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by Mrebai** [marmelab/react-admin#2293]
the pagination displays only the current page and does not show next or prev options i get only
 (Rows per page:  1-3 of 3)

when i try to change the page manually from the URL it changes to the requested page but i get this message in the pagination part : The page number 2 is out of boundaries. Try the previous page.

update : it seems this problems accursed only if i set perPage 5 or higher. pagination works fine if i set items per page between 1 and 4.

    "ra-data-graphql-simple": "^2.2.3",
    "react": "^16.4.2",
    "react-admin": "^2.3.0",

**Comment by Mrebai** [comment]
somehow it worked by passing a perPage prop in List component

**Comment by Mrebai** [comment]
seems like i'm receiving the wrong count meta from my database that's what causes the problem

**Comment by microlion116** [comment]
I am having a problem like that.
