### ISSUE TITLE
<DateInput> - Calendar popup not working on Safari and other bugs

### ISSUE THREAD

**Issue by raghuk** [marmelab/react-admin#2296]
**What you were expecting:**
_DateInput_ not working as expected. There are couple of issues in different browsers.
- Calendar pop-up should appear/displayed on Safari
- When I use keyboard and try to deleted _yyyy_ in _dd/mm/yyyy_, it should only deleted _year_.

**What happened instead:**
- There is no Calendar pop-up on Safari
- When I use keyboard and try to deleted _yyyy_ in _dd/mm/yyyy_, it reset's entire date input on Chrome and Firefox.

**Related code:**
```
<DateInput label="Birth Date" source="birth_date" />
```

**Screenshot:**
![error](https://user-images.githubusercontent.com/762942/45272827-295c2480-b4cd-11e8-84df-6620bc2753c9.png)

**Environment**
* react-admin version: 2.3.0
* Safari: 11.1.2
* Chrome: 69.0

**Comment by fzaninotto** [comment]
Material-ui relies on browsers native `<input type="date" />` implementations, so do we. Unfortunately, [Safari doesn't respect the spec](https://caniuse.com/#feat=input-datetime) so date inputs fallback to test inputs in Safari. This is not a react-admin bug.

The second problem is a genuine bug, though.
