### ISSUE TITLE
record-form is null when I saved  (redirect is "edit")

### ISSUE THREAD

**Issue by miyunim** [marmelab/react-admin#2298]
```
<SimpleForm redirect="edit">
...
</SimpleForm>
```

**Issue**

When I clicked "save", there is no data in my edit page form
and I checked in reduxDevTools

![line_p2018910_134743](https://user-images.githubusercontent.com/447006/45276942-23336b80-b500-11e8-8b86-fc686e207bcc.png)

**Environment**

* React-admin version: 2.2.3
* Last version that did not exhibit the issue (if applicable): 2.0.2
* React version: 16.4.0
* Browser: Chrome
* Stack trace (in case of a JS error): None

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/vvw21793w0)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
is this in a Create or in an Edit view?

**Comment by miyunim** [comment]
@fzaninotto // it was in a Edit view, I'm writing a sample.

**Comment by miyunim** [comment]
@djhi 
I wrote a sample, you can see the problem there.
It happens when I save without edit anything but if I edited then it works well.
Please check my sample.

- Follow This: comments list-> show page -> edit page -> just save -> blank
- CodeSandbox: https://codesandbox.io/s/6lnz4ll3ok

**Comment by fzaninotto** [comment]
Probably fixed by #2322
