### ISSUE TITLE
BulkActionToolbar not available in 2.3.0

### ISSUE THREAD

**Issue by vascofg** [marmelab/react-admin#2301]
2.3.0 changelog states that `BulkActions` have been replaced by `BulkActionToolbar`.
However this component is not exported by the react-admin module.

**Comment by djhi** [comment]
It's a typo, the component is named `BulkActionsToolbar` (note the plural `Actions`)

**Comment by djhi** [comment]
I updated the changelogg

**Comment by vascofg** [comment]
Is BulkActionsToolbar really supposed to replace bulkActions? Or is bulkActionButtons the approach now?
[List documentation](https://github.com/marmelab/react-admin/blob/master/docs/List.md) has no reference of this prop. Also, [Actions documentation](https://github.com/marmelab/react-admin/blob/master/docs/Actions.md#list-bulk-actions) link is broken.

**Comment by fzaninotto** [comment]
The `bulkActionButtons` prop is the way to go, as explained in the List documentation. Internally, it uses the `<BulkActionsToolbar>` component.
