### ISSUE TITLE
adding onDrop option break the image preview 

### ISSUE THREAD

**Issue by Mrebai** [marmelab/react-admin#2305]
if i add an image input the image preview works perfectly : 
```
 <ImageInput source="images" label="Pictures" accept="image/*">
          <ImageField source="src" title="title" />
  </ImageInput>
```

however when i add an onDrop option the image preview breaks. I assume that happens because it overrides the default on Drop behavior the shows the image. 
```
     <ImageInput source="images" label="Pictures" accept="image/*" options={{ onDrop: () => 
       console.log('dropped') }}>
          <ImageField source="src" title="title" />
      </ImageInput>
```

i hope there is a work around it.

**Comment by jdemangeon** [comment]
Since there's no news on this issue since more than 2 years. I closing it. 

Feel free to open another with a codesandbox example.
