### ISSUE TITLE
Scrollable tabs on TabbedShowLayout

### ISSUE THREAD

**Issue by MROFerreiro** [marmelab/react-admin#2317]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want the possibility to scroll on `<Tabs>` of `<TabbedShowLayout>`, when using mobile devices and there are many tabs, some become out of view and is not possible to scroll horizontally to see the hidden ones.

**Additional context**
Material-Ui `<Tabs>` component receives  prop called scrollable that enables horizontal scrolling `<TabbedShowLayout>` could receive the same prop.

**Comment by in19farkt** [comment]
I have this problem on the desktop.

**Comment by alauper** [comment]
I have this problem on TabbedForm.   Will you be supporting the TabbedShowLayout option [here](https://github.com/marmelab/react-admin/pull/2740) with the TabbedForm component?

**Comment by MROFerreiro** [comment]
Fixed in #2740 issue can be closed.

**Comment by Kmaschta** [comment]
Fixed by https://github.com/marmelab/react-admin/pull/2740
