### ISSUE TITLE
Delete button cannot be hidden/conditionally displayed in Edit toolbar 

### ISSUE THREAD

**Issue by kctrlv** [marmelab/react-admin#2319]
**What you were expecting:**
Being able to override the DeleteButton showing in the toolbar based on permissions. 

**What happened instead:**
The DeleteButton is hardcoded into the toolbar after the span, there is no way to remove or conditionally display it.

**Steps to reproduce:**
Spin up any edit page that has a resource ID and note that the DeleteButton is on the lower right. Attempting to make your own custom toolbar with conditional logic to display the buttons will not override the hardcoded DeleteButton that comes with it.

**Related code:**
Toolbar.js Lines 94-100

**Comment by kctrlv** [comment]
Potential fix: move the lines that deal with the DeleteButton logic (94-101) to the same section above that conditionally displays SaveButton (Children.count(children) === 0). This way it will still show on the default toolbar but will let a user override it with their custom buttons.  

P.S. Thank you for all your hard efforts on this project.

**Comment by fzaninotto** [comment]
I don't understand why you're saying that you can't create a custom Toolbar without DeleteButton. I don't understand your potential fix either.

**Comment by kctrlv** [comment]
@fzaninotto #2340 fixes the issue, thank you.
