### ISSUE TITLE
Link to related issue on release notes

### ISSUE THREAD

**Issue by jheiska** [marmelab/react-admin#2320]
Concerning the documentation of react-admin: It would be awesome to have a link to the related issue on release notes. This would be especially useful for the fixes, but for new features as well. 
The one-sentence descriptions rarely give a good picture of the update if you haven't been struggling with the same problem or waiting for a specific feature.

**Comment by fzaninotto** [comment]
Concerning the new features, we're already doing more than that: each new release gets a blog post explaining the new features, together with screenshots and before/after comparisons. I've just forgotten to link these blog posts in the Changelog and release notes on GitHub, and I've just fixed it.

As for bugs, I agree with you, we should link the original issue in the changelog, I'll remember this for the future.

Thanks for the heads up!

**Comment by fzaninotto** [comment]
Oh, and I forgot: all the pull requests of a given release (which reference issues when it's a bug fix) can be seen in the related **milestone** on GitHub. See https://github.com/marmelab/react-admin/milestones?state=closed

**Comment by jheiska** [comment]
Thanks for the swift reply. I have somehow managed to miss the blog...
