### ISSUE TITLE
React Router not functional inside TabbedShowLayout

### ISSUE THREAD

**Issue by mknapik** [marmelab/react-admin#2326]
React Router v4 allows to handle routing at any level of application component tree.
Using `TabbedShowLayout` does not allow to continue using nested routes inside a `Tab`.
Preferably, I'd like it to work as in [one of React Router examples](https://reacttraining.com/react-router/web/example/recursive-paths).

**Steps to reproduce:**

* Go to https://nqz43r8l0.codesandbox.io/#/posts/100/show
* Click [Details](https://nqz43r8l0.codesandbox.io/#/posts/100/show/details)
* Click [hello](https://nqz43r8l0.codesandbox.io/#/posts/100/show/details/hello)

**What you were expecting:**

The section with text `Hello!` to appear inside the `Details` tab.

**What happened instead:**

No tab is selected.

**Related code:**

https://codesandbox.io/s/nqz43r8l0

**Other information:**

[It seems the value to determine which tab is selected is taken directly from location.path](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/TabbedShowLayout.js#L92). Navigation assumes the `TabbedShowLayout` and `Tab` is the very last bit of URL.
Possible solution might require usage the tab name/number as tab identifier instead of the full path.

*Edit:*
I found [a working example of material and React Router](https://stackoverflow.com/a/51229652/862426) and modified it to present what could look like: 
* https://codesandbox.io/s/l32r87rkjl
* https://l32r87rkjl.codesandbox.io/tab3/b
So `location.pathname` is only part of the story, it causes the issue with not highlighting a tab header.
I think the issue might be `exact` prop passed to each tab content `Route`.

**Environment**

* React-admin version: `2.3.1`
* React version: `16.3`
* Browser: Chrome

**Comment by mknapik** [comment]
Would you accept a PR with a solution?

**Comment by djhi** [comment]
It's hacktoberfest ! Yes, please :)

**Comment by vunb** [comment]
It's not working!

**Comment by jdemangeon** [comment]
Hello @mknapik ! Thanks for your issue. Would you always like to create a PR?

@vunb feel free to open a PR to address to this issue ;) All help is welcome

**Comment by fzaninotto** [comment]
It seems this feature attracts no interest from the community. Since the core team doesn't need it, I'm closing this issue. 

If someone wants to revive this, feel free to submit a PR.
