### ISSUE TITLE
Children within a FormDataConsumer not receiving css classes

### ISSUE THREAD

**Issue by nickgieschen** [marmelab/react-admin#2328]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
I expect children of a FormDataConsumer to layout like any other element

**What happened instead:**
When the element is rendered, it is missing a FormInput-input-189 css class. The omission of this class results in a different layout from the other elements.

**Steps to reproduce:**
```
<Edit title="Foo" {...props}>
        <SimpleForm redirect={redirect}>
            <TextInput source="name"/>
            <SelectInput source="type" choices={[
                {id: 'text', name: 'Text'},
                {id: 'select', name: 'Select'},
                {id: 'checkboxList', name: 'Checkbox List'},
                {id: 'radioButtonList', name: 'Radio Button List'},
            ]}/>
            <FormDataConsumer>
                {({formData, ...rest}) =>
                    <TextInput source="name"/>
                }
            </FormDataConsumer>
            <TextInput source="name"/>
        </SimpleForm>
    </Edit>
```

**Comment by fzaninotto** [comment]
True, and it's the same problem as in #2331.

Consider it a limitation of the `<SimpleForm>` form layout, which tries to be too smart by inspecting its children and injecting styles only in certain situations. You'll need to manually style the child of the <`FormDataConsumer>`. Sorry for the inconvenience, but there is no way to make the `<SimpleForm>` layout work fine in all situations. And if this feels a burden, you can still write your own Form layout component to use as `<Edit>` child!

**Comment by aserrallerios** [comment]
Even when using manual styles in components included inside a `FormDataConsumer` I cannot get the outer `div` affected by them, only the inner. So this will never draw the two inputs in the same row:

```
const editStyles = {
    left: { display: 'inline-block' },
    right: { display: 'inline-block', marginLeft: 32 },
};

....

<SelectInput
    source="a
    formClassName={classes.left}
/>
<FormDataConsumer>
    {({ formData, ...rest }) => 
                    <NumberInput
                        source="b"
                        validate={[number(), minValue(1)]}
                        {...rest}
                        style={editStyles.right}
                    />
    }
</FormDataConsumer>
```

How can I achieve this?

**Comment by djhi** [comment]
@aserrallerios As explained in the issue template, please use StackOverflow to ask how-to questions

**Comment by stormmuller** [comment]
For anyone else coming to this issue, try this:

Change this
```
<FormDataConsumer>
    {({formData, ...rest}) =>
        <TextInput source="name"/>
    }
</FormDataConsumer>
```

To this
```
<FormDataConsumer>
    {({formData, className, ...rest}) =>
        <TextInput source="name" className={className}/>
    }
</FormDataConsumer>
```

as @fzaninotto mentioned, `<SimpleForm/>` will inject styles into it's children. Because `<FormDataConsumer/>` is the direct child it will receive the styles and you need to pass it on to the `<InputText/>`
