### ISSUE TITLE
React.Fragment treated as top level input

### ISSUE THREAD

**Issue by nickgieschen** [marmelab/react-admin#2331]
**What you were expecting:**
I expect React.Fragment to be invisible. That is, if I wrap two inputs in a React.Fragment they should be layed out as siblings to the other inputs.

**What happened instead:**
When a React.Fragment is encountered, it is treated as a top level input. The components I have wrapped in React.Fragment are treated as children of the top level input instead of being top level inputs themselves.

**Steps to reproduce:**
```
<SimpleForm>
            <TextInput source="name"/>
            <React.Fragment>
                <TextInput source="name"/>
                <TextInput source="name"/>
            </React.Fragment>
            {([
                <TextInput source="name"/>,
                <TextInput source="name"/>
            ])}
</SimpleForm>
```
All 5 TextInputs should be siblings. However, the React.Fragment is rendered as an input with its two child TextInputs as children.

* React-admin version: 2.2.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.5.0
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
This is how React works, I don't see what we can do in react-admin to overcome this. 

To avoid problems like that, we avoid as much as possible inspecting children in a component. `<SimpleForm>` is an exception (it maps over its children to add a `<div>`). If it doesn't fit your need, you can always use your own form layout component.

I'm closing this issue as I think it's outside of the react-admin scope.
