### ISSUE TITLE
Selected Item doesn't disappear in a specific situation

### ISSUE THREAD

**Issue by muticansel** [marmelab/react-admin#2333]
Hi,

I tried that in the [](https://marmelab.com/react-admin-demo/#/customers) demo too. And there is a bug I think. That's the situation;

In customer list, first, I select a record and then enter the Edit page. When I delete the record in the Edit page, it goes to the list page but "1 item selected" warning on top of the page doesn't disapper. 

Did you notice that before?

![selected item1](https://user-images.githubusercontent.com/32303129/45736453-b1d87480-bbf3-11e8-8d9d-31fbda8270ed.PNG)
![selected item2](https://user-images.githubusercontent.com/32303129/45736454-b1d87480-bbf3-11e8-94f5-aa3c163f1cb1.PNG)
![selected item3](https://user-images.githubusercontent.com/32303129/45736455-b1d87480-bbf3-11e8-96e2-9d25132bf69b.PNG)

**Comment by djhi** [comment]
Confirmed, that's a bug indeed, especially when the previously selected item is the one deleted
