### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by kikill95** [marmelab/react-admin#2343]
**What you were expecting:**
Working material inputs

**What happened instead:**
Material inputs don't work - they do not show labels, errors, etc.

**Steps to reproduce:**
Create custom input following the docs: https://marmelab.com/react-admin/Inputs.html#writing-your-own-input-component

**Other information:**
Documentation about custom work with material inputs is old, when I changed code to this, everything works as expected:
```javascript
<TextField
      helperText={label}
      label={label}
      {...input}
      {...custom}
    />
```

**Environment**

* React-admin version: 2.3.0
* Last version that did not exhibit the issue (if applicable): -
* React version: 16.5.0
* Browser: -
* Stack trace (in case of a JS error): -

**Comment by fzaninotto** [comment]
Feel free to do!

**Comment by fzaninotto** [comment]
Fixed by mistake on `master`, reopening.
