### ISSUE TITLE
Allow Admin component to run in a sub route

### ISSUE THREAD

**Issue by kundk-ckret** [marmelab/react-admin#2344]
Allow the <Admin> component to run under a sub route.
If you register a reessource "posts" at the moment, it expects the route to be /posts.

It would be nice to set a route prefix at the admin component to allow routes like "/administration/posts"

So maybe something like <Admin urlPrefix="/administration"> ?

**Comment by fzaninotto** [comment]
I think it's already possible by using your own `history` component, see https://github.com/marmelab/react-admin/pull/1849#issuecomment-397307264.

Feel free to reopen if something in the react-admin code prevents you from doing that.
