### ISSUE TITLE
Bulk-Deleting items while viewing the last page of a List breaks pagination

### ISSUE THREAD

**Issue by nicholasnelson** [marmelab/react-admin#2350]
**What you were expecting:**
Bulk-deleting items causing the total number of pages to drop below the current page of list should display a sensible warning and offer the user the option to navigate to another page of the list. Even better would be to have the List automatically switch to the last page with data.

**What happened instead:**
Bulk-deleting enough items to empty the current page gives the error: 

> The page number 2 is out of boundaries. Try the previous page.

The pagination controls disappear, meaning it is not possible to navigate to the first page. The only fix I've been able to find is to refresh the page with the browser control (not the RA control).

**Steps to reproduce:**
This can be reproduced on the demo page:
https://marmelab.com/react-admin-demo/#/categories?filter=%7B%7D&order=ASC&page=2&perPage=10&sort=name

1. Browse to page 2 of categories
2. Select all 3 items with the bulk actions checkboxes
3. Click Delete in the bulk actions toolbar

**Other information:**
Note that this is not an issue when deleting items individually.

This issue also causes issues using List within a different resource. In my project, I'm using List nested in a ReferenceManyField to take advantage of bulk actions for related records. This works well, except in certain navigation flows users can end up on page '5' of a 2 page list of referenced items. The error message adequately explains the issue, but the pagination controls are missing.

**Environment**

* React-admin version: 2.3.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.5.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by MaxAlex666** [comment]
I received this behavior when deleting a single record (not bulk), the last one on the page.

**Comment by fzaninotto** [comment]
Right, thanks for reporting. We should not show a message without giving the user the directions to get back to a working state, we should catch the error and put the user to a working state.
