### ISSUE TITLE
Send null as id using a custom exporter with fetchRelatedRecord and nullable ids

### ISSUE THREAD

**Issue by Luwangel** [marmelab/react-admin#2353]
We have a list of ids and we want to use `fetchRelatedRecords` method in a custom Exporter. Theses ids could be null.

``` js
const data = [1, 2, 3, null, null, 1, 7, null];
```

**What you were expecting:**

The api request should be:

> `http://example.com/react-admin/table?id[]=1&id[]=2&id[]=3&id[]=7`

**What happened instead:**

The api request is:

> `http://example.com/react-admin/table?id[]=null&id[]=1&id[]=2&id[]=3&id[]=7`

**Steps to reproduce:**

Pre-Conditions:
- Have a table containing foreign nullable keys

For example `user_category_id` is a foreign nullable key:

``` js
{
    users: [
        {
            id: 1,
            name: "Logan Schowalter",
            role: "admin",
            user_category_id: null
        },
        {
            id: 2,
            name: "Breanna Gibson",
            role: "user",
            user_category_id: 1
        },
    ],
    user_categories: [
        {
            id: 1,
            label: "premium"
        },
    ]
}
```

Steps:

1. Create a custom export of `users` list
2. Use `fetchRelatedRecords` to retrieve `user_category` label

**Related code:**

https://codesandbox.io/s/p1k5vol6x

**Environment**

* React-admin version: 2.3.x
* React version: 16.4.x

**Comment by fzaninotto** [comment]
Fixed by #2354
