### ISSUE TITLE
'Back' button clears TabbedForm with 3 or more Tabs

### ISSUE THREAD

**Issue by kctrlv** [marmelab/react-admin#2356]
On an Edit page with a TabbedForm, with FormTabs 'A', 'B', and 'C', when viewing 'B', then 'C', and pressing the Back button, user will find that the inputs on 'B' and 'A' have been cleared.

**What you were expecting:**
Manually navigating to B, then C, and pressing the back button would not clear the inputs on B and A.

**What happened instead:**
Manually navigating to B, then C, and pressing the back button returns you to the previous tabs B, then A, but their input has been cleared.

**Steps to reproduce:**
In the demo application below, navigate to a Post Edit page, then click Body tab -> Miscellaneous tab
Click 'Back' on the browser and notice that the previous tabs are showing as cleared

**Related code:**
* CodeSandbox (https://codesandbox.io/s/wn5k6kqo2k)

**Environment**

* React-admin version: 2.3.2

**Comment by fzaninotto** [comment]
Confirmed and reproduced on `next` as well as on `master`.

**Comment by fzaninotto** [comment]
@djhi I think it's related to the `formMiddleware`. When clicking on tabs, the `location` does have a `skipFormReset` state set to `true`, but when using the back button, it doesn't. We'll need to fallback to analyzing the URL shape instead of relying on location state.

**Comment by djhi** [comment]
Can't reproduce it on `next` anymore
