### ISSUE TITLE
Page number out of boundaries

### ISSUE THREAD

**Issue by vdieulesaint** [marmelab/react-admin#2366]
react-admin : 2.3.2

Steps to reproduce :
1. Go to https://marmelab.com/react-admin-demo/#/customers
2. Change "Rows per page" to 10
3. Select Page "90"
4. Change "Rows per page" to 25

You will get "The page number 90 is out of boundaries"

Playing with pagination size should also reset the page number.

**Comment by fzaninotto** [comment]
Duplicate of #2350
