### ISSUE TITLE
Replace papaparse by something lighter

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#2374]
React-admin bundles the `papaparse` library for converting JSON to CSV. But 90% of the `papaparse` code is used to convert CSV to JSON. Unless we implement import, we should replace papaparse by a lighter library.

**Comment by djhi** [comment]
I think we should first decide whether all admins need the export function. IMO, this should be put in a separate package (`ra-export-to-csv` ?)

**Comment by fzaninotto** [comment]
I think it's a fairly standard requirement. Besides, the JSON to CSV conversion function is really small, so the impact on bundle size isn't really significant (once we get rid of papaparse).

**Comment by fzaninotto** [comment]
Fixed by #3324
