### ISSUE TITLE
Add a footer to the admin

### ISSUE THREAD

**Issue by jcornide** [marmelab/react-admin#2378]
It would be good to have footer area where to put some basic information and links that might be helpful for the admin users. 

If you could include it the same way you could include it with the appBar it would be great

**Comment by geeofree** [comment]
:wave: Hola! Would love to work on this!

**Comment by fzaninotto** [comment]
@geeofree it's yours!

**Comment by geeofree** [comment]
Hey :wave: sorry for the late reception :sweat: was busy for awhile but am starting to pick up on development with this today, I'd like to know what kind of initial information should be on the footer?  

Would having something like *Powered by [react-admin](https://marmelab.com/react-admin/) v2.3.3* be okay?

**Comment by fzaninotto** [comment]
I think no footer should be the default. We don't want to bother developers with a mention that every single team would have to remove.

**Comment by jcornide** [comment]
> I think no footer should be the default. We don't want to bother developers with a mention that every single team would have to remove.

Agree, just and empty footer and example on the documentation on how to add it would be great!

**Comment by tjgragg** [comment]
Any updates on this feature?

**Comment by waynebloss** [comment]
The following adds a fixed footer. You can also make `position` relative or absolute.

```jsx
<React.Fragment>
  <Admin authProvider={authProvider} dataProvider={jsonDataProvider}>
    <Resource {...Comments} />
    <Resource {...Posts} />
    <Resource {...Users} />
  </Admin>
  <div style={{
    position: 'fixed', right: 0, bottom: 0, left: 0, zIndex: 100,
    padding: 6,
    backgroundColor: '#efefef',
    textAlign: 'center',
  }}><strong>HELLO</strong></div>
</React.Fragment>
```

**Comment by fzaninotto** [comment]
@waynebloss Thanks for the post. Indeed, it is so easy to do that we shouldn't worry about including it in react-admin. The only thing that it would provide is the support for theme, which can be achieved otherwise. 

So tis enhancement is downgraded to very low priority, and we might even close it in the future.

**Comment by fzaninotto** [comment]
Yep, let's close it. Footer design is a rabbit hole that we'd better not go down to. since it's achievable in userland, react-admin doesn't need to be changed.

**Comment by tjgragg** [comment]
It's easy to do if you don't need to make an API call and have the footer use react-admin's redux Provider, which is what I would really like to do.

**Comment by fzaninotto** [comment]
That you can do with a custom layout.

**Comment by tjgragg** [comment]
Maybe I was doing it wrong, but it seems like using a custom layout forces someone to create every piece yourself. Is there a way to use custom layout and have “MyAppBar” and “MySidebar” and “MyMenu” and “MyNotification” still be the default, standard react-admin components? 
(reference: https://marmelab.com/react-admin/Theming.html#using-a-custom-layout)

**Comment by fzaninotto** [comment]
Since default AppBar, Sidebar, Menu and Notification components are exported, you can totally reuse them in your own layout. The documentatoin is probably incomplete about it. Would you mind updating it once you've understood how to reuse layout components?
