### ISSUE TITLE
Add breadcrumb 

### ISSUE THREAD

**Issue by jcornide** [marmelab/react-admin#2380]
A breadcrumb that would indicate the current path could improve usability, i.e. if I am in 
/products/1/show
breadcrumb should be
Dashboard (home link) > Products (products link) > Product 1

**Comment by fzaninotto** [comment]
This can be done in userland pretty easily:

```jsx
export const FooList = ({ history, ...rest }) => {
    const breadcrumbPath = [
        { url: "/foos", title: "Foos", isActive: false }
    ];
    return (
        <React.Fragment>
            <Breadcrumb path={breadcrumbPath} />
            <List {...rest}>
                <Datagrid>
                       ...
                </Datagrid>
            </List>
        </React.Fragment>
    );
}
```

So closing as nothing must be changed in core to allow this.

**Comment by gabrieltong** [comment]
@fzaninotto I have the same problem, I want to show the product name,  like
`Dashboard (home link) > Products (products link) > Product Name`

**Comment by lalitjain98** [comment]
where is this Breadcrumb component defined? Is it a custom react component?

**Comment by fzaninotto** [comment]
It's a custom component, but you can easily write some MUI code directly with https://material-ui.com/components/breadcrumbs/#breadcrumbs

**Comment by RWOverdijk** [comment]
For the people scooting across this in the future, we use https://www.npmjs.com/package/react-router-breadcrumbs-hoc

It works quite well.

**Comment by cordial** [comment]
> For the people scooting across this in the future, we use https://www.npmjs.com/package/react-router-breadcrumbs-hoc
> 
> It works quite well.

Sorry, can you expand on this by any chance? How does it fit inside react-admin and does it just magically know about the resource routes or do you have to hardcode them in path array as above (if im understanding the above correctly)?

**Comment by fzaninotto** [comment]
If you're looking for a powerful and customizable Breadcrumb component for react-admin, check out [the `ra-navigation` package](https://marmelab.com/ra-enterprise/modules/ra-navigation), part of [React Admin Enterprise Edition](https://marmelab.com/ra-enterprise). 

![ra-vanigation](https://marmelab.com/ra-enterprise/modules/assets/ra-multilevelmenu-categories.gif)
