### ISSUE TITLE
Miss of normalization of dates in "alwaysOn" filters

### ISSUE THREAD

**Issue by JulienMattiussi** [marmelab/react-admin#2389]
**The situation**

I have an admin page list, with filters including a date permanent one :
```
<DateInput
    source="from_date"
    label="From"
    normalize={startOfDay}
    alwaysOn
/>
```

It is using a normalize fonction **startOfDay** supposed to give date in this ISO format :
`2018-10-04T00:00:00.009Z`

My filter have a default value set (forced in ISO format) :
`filterDefaultValues={{from_date: startOfYesterday().toISOString()}}`

**Actions leading to the issue**

When loading page :
- The default date appears in input. (OK)
- Datas are called filtered with input value. (OK)

When changing date in filter
- The new date is set in input. (OK)
- Datas are called filtered with input value. (OK)

When changing page and coming back
- Filter field keeps the precedent modified input (OK)
- Data is supposed to be filtered with actual input value (**KO**)

**Instead**

I get an error from my data provider :
![image](https://user-images.githubusercontent.com/39904906/46477746-a5573d00-c7eb-11e8-9678-cc310c667063.png)

When checking, I see that the date filter in GET request hasn't been well formated : 
```
{
    "error":"invalid input syntax for type timestamp: \"Tue Oct 03 2017 00:00:00 GMT 0200 (heure d’été d’Europe centrale)\""
}
```
The date value must be in normalized format (ISOString) but is in "text format" instead
And so my API rejected it.

When checking react status in navigator, I see that normalize function haven't applied to my date component in this case.
Component value is `Tue Oct 03 2017 00:00:00 GMT 0200 (heure d’été d’Europe centrale)`
When setting value manually in input, it changes in react component to `2018-10-04T21:59:59.999Z`, which is what is expected too when loading the list page.

**My Environnement**

* React-admin version:2.3.1
* React version:16.4.2
* Browser: Chrome Version 69.0.3497.100 (Build officiel) (64 bits)

**Comment by djhi** [comment]
Fixed in v3
