### ISSUE TITLE
ReferenceManyField: expose the total record number to child

### ISSUE THREAD

**Issue by aserrallerios** [marmelab/react-admin#2394]
I'd like to create a Field inside a List that shows the number of records related to an entity. I've almost got it working, but the ReferenceManyField component only exposes the `data` object to its child, not the total number records returned from the data source.

Probably related to this is that it would be great to have full pagination capabilities combining ReferenceManyField with another component (I don't know if there's any way right now to reverse lookup a BIG list of records other than just use a huge `perPage`).

**Comment by fzaninotto** [comment]
Fixed by #2487
