### ISSUE TITLE
There is no way do not show delete button for the Toolbar in v.2.3.3

### ISSUE THREAD

**Issue by AChuyan** [marmelab/react-admin#2396]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
Ability to hide delete button for the Toolbar component.
**What happened instead:**
It's impossible.

**Steps to reproduce:**
Try to remove or hide 'delete' button for Edit view.

**Related code:**
Toolbar.js:80
        record && typeof record.id !== 'undefined' && React.createElement(DeleteButton, {
            basePath: basePath,
            record: record,
            resource: resource
        })

* CodeSandbox (https://codesandbox.io/s/olr88y53xy)
* A sample application via GitHub
-->

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 2.3.3
* Last version that did not exhibit the issue (if applicable): 2.0.3
* React version: 16.3.1
* Browser: any
* Stack trace (in case of a JS error): Toolbar component misbehavior

**Comment by kctrlv** [comment]
@AChuyan 

I submitted a similar issue a while back and it looks like the fix is set to be released in the next major version: 

https://github.com/marmelab/react-admin/issues/2319

**Comment by fzaninotto** [comment]
indeed, it's a duplicate.
