### ISSUE TITLE
Update graphql-ast-types dependecy for ra-data-graphql-simple

### ISSUE THREAD

**Issue by ak-il** [marmelab/react-admin#2398]
Looking at `ra-data-graphql-simple`'s dependencies I found [it has a dependency for graphql-ast-types](https://github.com/marmelab/react-admin/blob/634662ae9ee562725c646c822752bc19ccd6b501/packages/ra-data-graphql-simple/package.json#L34) which is a repository (`Kmaschta/graphql-ast-types`) that doesn't exist in github.  
After searching I found there is https://github.com/imranolas/graphql-ast-types which I suppose is the same repository with the name changed. It's also [published to npm](https://www.npmjs.com/package/graphql-ast-types) meaning you don't have to use a git repository as the dependency anymore.  
I'd like to use this package's implementation of `buildQuery` but I can't since I'm working offline so I'm waiting for this fix.  
Thanks!

**Comment by ak-il** [comment]
[It's also used in ra-data-graphcool.](https://github.com/marmelab/react-admin/blob/634662ae9ee562725c646c822752bc19ccd6b501/packages/ra-data-graphcool/package.json#L35)

**Comment by ak-il** [comment]
As I said I have no access to the internet so when I install dependencies it downloads them from our local repository. Then I can't install dependencies which refer to git repositories such as on GitHub.

**Comment by Kmaschta** [comment]
I just sent a ping to the library author on the related issue we opened.
I'll just publish a npm package as a workaround to fix that situation, but I don't want it to be a permanent solution.

**Comment by Kmaschta** [comment]
For those who have the same issue, I published a temporary clone of this package: [`graphql-ast-types-browser`](https://www.npmjs.com/package/graphql-ast-types-browser)
