### ISSUE TITLE
Cannot override SnackBar style in Notification Component

### ISSUE THREAD

**Issue by bulby97** [marmelab/react-admin#2400]
Since Notification component is using Snackbar, that would be great to customize SnackBar style for example.

**What you were expecting:**
I want to customize `anchorOriginBottomCenter` css property from SnackBar : 
`<Notification classes={{ root: ..., anchorOriginBottomCenter: classes.anchorPosition }}`

**What happened instead:**
`<Notification />` ignore classes 

**Steps to reproduce:**
Create a notification component, try to modify SnackBar through the css api https://material-ui.com/api/snackbar/#css-api

**Comment by djhi** [comment]
Indeed, thanks for reporting. This looks like a good first issue! See https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/Notification.js

**Comment by fargito** [comment]
Shouldn't this be closed ? ;)
