### ISSUE TITLE
After creating a new record the system fail to fetch the new record

### ISSUE THREAD

**Issue by aldomonteiro** [marmelab/react-admin#2402]
**What you were expecting:**
Create a new record and the system state remains correct.

**What happened instead:**
After create a new record, using the ra-data-simple-rest, the system fails when fetching the new record even though the backend is returning the data in the expected format. The spinner keeps spinning and after some time a message "Failed to fetch" is raised.

It is pretty like the issue #159, closed a lot time ago.

**Steps to reproduce:**
- I created a simple CRUD entity using the dataProvider ra-data-simple-rest. All the operations are working, i.e., the system creates, updates and reads the records. However, after create a new record, the system cannot process the data returned. The backend is returning the data with an ID and the additional data as expected by the dataProvider. Following the backend return using curl after a POST request:

```
curl -i -d "id=16&toppig=Topping" https://localhost:8080/toppings
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
Access-Control-Allow-Headers: Authorization,Origin,X-Requested-With,Content-Type,Accept,application/json,Content-Range
Access-Control-Expose-Headers: Content-Range
Content-Type: application/json; charset=utf-8
Content-Length: 58
ETag: W/"3a-7nkVpG2qZL+X/ZPE94iVIT7d9r4"
Date: Mon, 08 Oct 2018 23:48:03 GMT
Connection: keep-alive

{
  "data": {
    "id": 16,
    "topping": "Topping"
  }
}
```
However, apparently, the system does not recognize this return and makes a new `GET` call to the backend with `undefined` parameter, instead of the returned `id`.

**Related code:**

App.js:

```
...
import simpleRestProvider from 'ra-data-simple-rest';

// Addim Custom Header
// https://marmelab.com/react-admin/DataProviders.html#adding-custom-headers
const httpClient = (url, options = {}) => {
  if (!options.headers) {
    options.headers = new Headers({ Accept: 'application/json' });
  }
  const token = localStorage.getItem('token');
  options.headers.set('Authorization', `Bearer ${token}`);
  return fetchUtils.fetchJson(url, options);
}
const dataProvider = simpleRestProvider("https://localhost:8080", httpClient);

const App = () => (
  <Admin
    customReducers={{ pagesReducer }}
    dashboard={Dashboard}
    loginPage={CustomLogin}
    authProvider={authProvider}
    dataProvider={dataProvider}
    customRoutes={customRoutes}
  >
    <Resource
      name="toppings"
      list={ToppingList}
      edit={ToppingEdit}
      create={ToppingCreate}
      icon={ToppingIcon}
    />
...
```

**Environment**

* React-admin version: 2.3.3
* "ra-data-simple-rest": "^2.3.3"

**Comment by djhi** [comment]
Your API does not have to wrap the data inside a `data` property. Just return the new resource data as the response body directly. Putting it inside `data` for react-admin will be done by the provider

**Comment by aldomonteiro** [comment]
Gildas, perfect, you are right. I am sorry to open an issue instead of asking it on SO, I was pretty sure my code was right, so, I didn't see other option than open it.

Thanks a lot.
