### ISSUE TITLE
no scrollbar with AutocompleteInput

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2407]
Hello,
thank you for your project.
An annoying bug exists with `AutocompleteInput`. There is no scrollbar and it takes the entire length of the screen. This is most visible when there is a lot of data.

```
<ReferenceInput
   label="Institut"
   source="main_institute"
   reference="institutes"
   perPage={250}
>
   <AutocompleteInput optionText="name" />
</ReferenceInput>
```

![image 2](https://user-images.githubusercontent.com/9990521/46678995-3fe9be80-cbe6-11e8-8d0a-3731090a3e77.png)

**Environment**

* React-admin version: 2.3.3
* React version: 16.5.2
* Browser: chrome 69

**Comment by kctrlv** [comment]
In 'admin-on-rest' one could achieve this functionality by passing `menuProps: { maxHeight: 280 }` to the options prop on `AutocompleteInput` to get a scrollbar to appear. I have not figured out how to do this in the current version, or if it is possible via the props, yet. My interim solution is requesting a small set of items in these components but I would love to get the scrollbar back in there.

**Comment by marek-kramski** [comment]
One solution(hack actually) is to override this on themes like that:
```
MuiPaper: {
      elevation2: {
        '& ul[role=listbox]': {
           maxHeight: '250px',
           overflowY: 'auto',
        }
      }
    }
```
