### ISSUE TITLE
Disabled BooleanInput

### ISSUE THREAD

**Issue by yangjiamu** [marmelab/react-admin#2422]
I can make the BooleanInput disabled, is there a way to make BooleanInput disabled?

**Comment by yangjiamu** [comment]
I have solved this problem by use options attributes.

**Comment by christiaanwesterbeek** [comment]
For anyone who stumbles upon this issue. Do `<BooleanInput options={{ disabled: true }} />` instead of `<BooleanInput disabled />`

**Comment by bwaldvogel** [comment]
Has this been changed again? `<BooleanInput disabled={true} />` works for me while `<BooleanInput options={{ disabled: true }} />` doesn’t in react-admin `3.10.4`.
