### ISSUE TITLE
<DeleteButton undoable={false} /> in List does not refresh List

### ISSUE THREAD

**Issue by wuxudong** [marmelab/react-admin#2425]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**

In List with `<DeleteButton undoable={false} />`, after user click delete, request sent to server, and item deleted from list.

**What happened instead:**

user click delete, request sent to server, but item still remains in the list.

![record](https://user-images.githubusercontent.com/1391101/46866639-cc011d80-ce54-11e8-9952-b17ed503bf9d.gif)

**Steps to reproduce:**

add <DeleteButton undoable={false} /> in /examples/simple/src/posts/PostList -> PostListActionToolbar section.

```
                    <PostListActionToolbar>
                        <EditButton />
                        <ShowButton />
                        <DeleteButton undoable={false} />
                    </PostListActionToolbar>

```

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: master branch
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by BartoGabriel** [comment]
I add an example online:
https://03w7o6j530.codesandbox.io/#/users

Code
https://codesandbox.io/s/03w7o6j530

**Comment by trsteel88** [comment]
I'm having the same issue.

**Comment by normanzb** [comment]
setting `undoable={false}` in edit view causes the same issue, seems the `refreshView` only fired in `undo`: https://github.com/marmelab/react-admin/blob/29fc75e19b917bb37952dcbeb881b840f2a07b38/packages/ra-core/src/sideEffect/undo.ts#L41
