### ISSUE TITLE
FormDataConsumer is not working with custom form name

### ISSUE THREAD

**Issue by ashim-k-saha** [marmelab/react-admin#2429]
**What you were expecting:**
`FormDataConsumer` should provide form data object with custom from name or where form name is not `record-form`.

**What happened instead:**
Returns an empty object.

**Steps to reproduce:**
Give custom form name inside `TabbedForm`

**Related code:**

```jsx
class VoucherCreate extends Component {
  render() {
    return (
      <Create title="Voucher" {...this.props}>
        <TabbedForm form="my-custom-form-name">
          <FormTab label="Details">
            <TextInput source="voucher_no" />
            <ReferenceInput
              source="student_id"
              reference="students"
              perPage={5}
            >
              <AutocompleteInput optionText="name" />
            </ReferenceInput>
            <FormDataConsumer>
              {({formData, ...rest}) =>{
                console.log(formData); // Should print the form data
              }
            </FormDataConsumer>
          </FormTab>
        </TabbedForm>
      </Create>
    );
  }
}
```

**Environment**

* React-admin version: 2.3.4
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.3.2
* Browser: Chrome

**Comment by fzaninotto** [comment]
Thanks for the report. That's feasible using [redux-form's `FormName` component](https://redux-form.com/7.4.2/docs/api/formname.md/#-code-formname-code-).
