### ISSUE TITLE
export doesn't work properly

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2440]
Hello,
I need to use the export feature but it doesn't work properly.
When I export, I have[object Object] as a variable in my csv file. 
Also, If I use the ReferenceField field in my list, it does not match when exporting and copies the id.
I tested with demo (https://marmelab.com/react-admin-demo/#/commands?filter=%7B%22status%22%3A%22delivered%22%7D&order=DESC&page=1&perPage=25&sort=date) and same problem.

```
insert short code snippets here
id,reference,date,customer_id,basket,total_ex_taxes,delivery_fees,tax_rate,taxes,total,status,returned
--
573,UWYZ1K,2018-10-16T08:25:38.899Z,654,[object   Object],38.37,6.83,0.2,9.04,54.24,delivered,false
```

I didn't find that this problem has already been reported.

**Environment**

* React-admin version: 2.3.4
* React version: 16.5.2
* Browser: chrome 70

Thanks you for your help :wink:

**Comment by fzaninotto** [comment]
You need to write an `exporter` function, as explained in the documentation.

https://marmelab.com/react-admin/List.html#exporter
