### ISSUE TITLE
Ability to add extensions

### ISSUE THREAD

**Issue by BartoGabriel** [marmelab/react-admin#2446]
Currently in our company we are developing and using React-Admin. We are very happy to use it and consider it an excellent framework.

When using it in a large project, we had to develop new components and add new functionalities.
For example:
- Adaptation of react-select.
- Address Input with a map.
- Images input with carousel, drag and drop, ect.
- Save the creation forms in the local storage in case the user leaves and returns to the screen (such as Gitlab problems)
- Ect.

I think it would be good, that there is the possibility of adding extensions. More than anything, add documentation with some standard for the creation of extensions (for example, how to include the language).
And also, have somewhere the list of available extensions. So that developers can provide specific components and share them among the community, since some are very specific and not worth being at the base of the project.

**Comment by fzaninotto** [comment]
It's just React™. So your extensions are React components, that you can publish as standalone packages. Then, just open a PR to add a link to that package in the Ecosystem documentation, and you're done.

Bonus: Add the `react-admin` tag to your GitHub repository to facilitate discoverability. And prefix the package name with `ra-`, it will help when searching on npm.

**Comment by fzaninotto** [comment]
PS: Thanks for the heads up. I'm looking forward to your contributions to the ecosystem!

**Comment by BartoGabriel** [comment]
@fzaninotto  Thank you very much for all the help.

@afilp Sorry, but these weeks I was very busy, and I still could not upload those extensions.
But if I could create an example that I think can be very useful, regarding your comment.

I think the problem of the forms are 2:

**- Edition** 
When the user is editing an entity and the user navigates to another screen, he never learns that his changes were not saved. I think this is really bad. What I came up with is to make use of the Promp component of react-router.
Example:
![video1](https://user-images.githubusercontent.com/5618170/47817048-6c9b7c80-dd33-11e8-81e2-fc90d3600a44.gif)


**- Creation** 
When an entity is really big, and there are many fields. I think it's good for the user to navigate through the application and that those changes persist in memory (As GitLab does with the new issues, if it is not canceled it is saved), these changes should remain in memory until you save or cancel. For this I use local storage.
Example:
![video2](https://user-images.githubusercontent.com/5618170/47817095-8ccb3b80-dd33-11e8-99db-20ef1812ac76.gif)

Complete Example:
https://v6rx8l7l13.codesandbox.io/#/users

Source code:
https://codesandbox.io/s/v6rx8l7l13
