### ISSUE TITLE
date input gte filter isn't accurate.

### ISSUE THREAD

**Issue by JMD1986** [marmelab/react-admin#2447]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**

when implementing a filter for dates with the gte option and selecting a date all dates created after the date should populate the datagrid.

**What happened instead:**

when selecting the GTE option and choosing a date all days created afterwards populate the gride as well as dates created one day before the selected date.

**Steps to reproduce:**

create your inputs as so
  <DateInput
         source="date_hire_lte"
fields as so
         <DateField source="date_hire" />

then select a date within the previously mentioned range.

**Related code:**

```
create your inputs as so
  <DateInput
         source="date_hire_gte"
fields as so
         <DateField source="date_hire" />
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
This is entirely dependent on your backend, react-admin does nothing special with `_gte` or `_lte` filters.

**Comment by JMD1986** [comment]
is there more documentation on using lte or gte filters in react admin?
