### ISSUE TITLE
Export Button fetchRelatedRecords

### ISSUE THREAD

**Issue by Masoodt** [marmelab/react-admin#2449]
In last update fetchRelatedRecords is using Javascript Set to make ids unique, but to converting it back to Array it has got a .slice() , so it's causing an error, because Set has no slice function
here is my suggested code: ExportButton.js
//old Code:
 var ids =  new Set(sanitizedData).slice();
// new Code
 var ids =  Array.from(new Set(sanitizedData))

**Comment by fzaninotto** [comment]
Confirmed, TypeScript compiles `[...new Set(foo)]` to `(new Set(foo)).slice()`, which fails. It's weird because with modern ES, without transpilation, it works:

```
> const b = new Set([1, 2, 2, 3])
undefined
> b
Set { 1, 2, 3 }
> [...b]
[ 1, 2, 3 ]
> b.slice()
TypeError: b.slice is not a function
```
