### ISSUE TITLE
row double click for Grid component

### ISSUE THREAD

**Issue by vedmalex** [marmelab/react-admin#2453]
Hi!
Cool feature of react-admin 2.4 rowClick for Datagrid
Is you've mentioned in [<Datagrid> rowClick](https://marmelab.com/blog/2018/10/18/react-admin-2-4.html#code-classlanguage-textltdatagridgtcode-code-classlanguage-textrowclickcode)
> Be careful though: if the row contains an <EmailField> or a <ReferenceField>, the link created by these fields won't be clickable - the click to the edit view takes precedence.

Why no implement rowDblClick and use onDoubleClick event?

in mobile mode we can use different events, double click just fine for desktop.

**Comment by michalpierzchlewicz** [comment]
Same here. Love the feature - the only problem is with not being able to click links inside rows - e.g. reference fields or custom buttons. Being able to save some extra space by not having to use the edit button is great!

**Comment by fzaninotto** [comment]
We can do better and make single click on references work out of the box.
