### ISSUE TITLE
Show component doesn't always fetch data from server

### ISSUE THREAD

**Issue by adrianDY** [marmelab/react-admin#2460]
**What you were expecting:**
Whenever you open a URL that renders the `<Show>`component, am API GET request will pull in information from the server

**What happened instead:**
When transitioning from `<List>` view to `<Show>` view in the app, I see an API GET request for ```http://myserver.com/1234``` but when I transition to the `<Show>` view by hitting the "back" button in Chrome or by directly inputting the URL the request is not initiated. Refreshing the page also doesn't seem to send out this request

**Steps to reproduce:**
Go to a `<Show>` view, and transition to an external page: http://www.google.com and then hit the back button after the page loads. 

**Other information:**
Using simpleRestProvider

**Environment**

* React-admin version: 2.4.0
* React version: 16.5.2
* Browser: Chrome

**Comment by fzaninotto** [comment]
I can't replicate this on the simple example with Chrome. I believe this must be an issue with your `dataProvider`. So I'm closing this issue, feel free to reopen it if you can provide a CodeSandbox that reproduces the problem.
