### ISSUE TITLE
Can't use SimpleList whitin edit form

### ISSUE THREAD

**Issue by vedmalex** [marmelab/react-admin#2462]
i've use with Responsive component for xsmall size SimpleList
as for react-admin 2.1 it is works fine but for 2.4 it is broken
i've reproduced the sample scenario for that bug

the same applied for show and edit-form

just select any post with comments and go to the comment it wil not display any, while for 2.1 for the original sample it is working

[sample project](https://codesandbox.io/s/qk3rz6mj5w)

**Comment by despatates** [comment]
I experimented the same issue with `<SimpleList />` when set as child of `<ReferenceManyField />` (was working before v2.2.0).
No `total` or `isLoading` props are provided by `ReferenceManyField`, so no result is displayed.

Your fix should fix this use case too.

**Comment by fzaninotto** [comment]
Confirmed and reproduced

**Comment by fzaninotto** [comment]
Incidentally, this is the type of regression that a strong set of types would prevent...
