### ISSUE TITLE
TableFormIterator: Iterate form fields as table

### ISSUE THREAD

**Issue by mkg20001** [marmelab/react-admin#2479]
**Is your feature request related to a problem? Please describe.**
I wanted to build a simple table that has got input fields and tried using `source="items[0].id"`, etc. That didn't work as I had to use a FormIterator. This table-like iterator could be reusable.

**Describe the solution you'd like**
A table-like FormIterator
Current (non-working) implementation looks like this:
![screenshot non-working implementation](https://user-images.githubusercontent.com/7735145/47576146-0c2bca00-d944-11e8-889a-60c7cef99192.png)
While the code is there, the fields don't really save the values because of the above mentioned problems

**Describe alternatives you've considered**
Iterating over the items as array and returning `source="items[i].id"` inputs.

**Additional context**
As I need this anyways I could implement it and create a PR. But it would be cool if somebody else could add more features to this implementation such as allowing to sort the table.

**Comment by mkg20001** [comment]
This would be the current non-working code

```js
export class ItemTableCreate extends React.Component {
  dynField (i, prop) {
    const {record} = this.props
    const {items} = record
    const item = items[i]

    return {
      label: false,
      value: item[prop],
      handleChange: newValue => {
        item[prop] = newValue
        this.setState({ record })
      },
      source: `items[${i}].id`
    }
  }

  render () {
    const {record} = this.props

    if (!record) {
      return (<div />)
    }

    const items = record.items || (record.items = [])

    if (!items.length) {
      items.push({id: 'never displayed', total: 0, allowUsed: false})
    }

    const itemsReact = items.map((item, i) => (
      <TableRow>
        <TableCell>
          {i ? (
            <IconButton color='secondary' onClick={() => { delete items[i]; this.setState({ record }) }}>
              <DeleteIcon />
            </IconButton>
          ) : (
            <IconButton color='primary' onClick={() => { items.unshift({}); this.setState({ record }) }}>
              <AddIcon />
            </IconButton>
          )}
        </TableCell>
        <TableCell><TextInput className='label-shrink' {...this.dynField(i, 'id')} {...this.props} /></TableCell>
        <TableCell><NumberInput className='label-shrink' {...this.dynField(i, 'total')} /></TableCell>
        <TableCell><BooleanInput {...this.dynField(i, 'allowUsed')} /></TableCell>
      </TableRow>
    ))

    return (
      <Table>
        <TableHead>
          <TableRow>
            <TableCell />
            <TableCell>Artikelbezeichnung</TableCell>
            <TableCell>Menge</TableCell>
            <TableCell>Gebraucht erlauben</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {itemsReact}
        </TableBody>
      </Table>
    )
  }
}
```

**Comment by fzaninotto** [comment]
I assume you're looking for an editable datagrid. Take a look at the work started in #1923.
