### ISSUE TITLE
TabbedDatagrid: Extract from example and turn into offical component?

### ISSUE THREAD

**Issue by mkg20001** [marmelab/react-admin#2480]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
The code from https://github.com/marmelab/react-admin/blob/master/examples/demo/src/commands/CommandList.js could be reused to create a TabbedDatagrid component

**Describe alternatives you've considered**
Copy-and-pasting the code, but that could be improved by having it be an offical component

**Comment by fzaninotto** [comment]
We won't add that component to the core of react-admin. That would be one more component to maintain, and we already have a lot. Besides, this component is probably not used in most of the admins. 

But this can be a userland component - feel free to copy it, republish is as a standalone package, and add it to the Ecosystem doc.
