### ISSUE TITLE
ReferenceManyField keeps showing loading component after data fetched successfully

### ISSUE THREAD

**Issue by pak-zuhlke** [marmelab/react-admin#2484]
**What you were expecting:**
Show values with ReferenceManyField in List

**What happened instead:**
The field keeps showing the loading bar. But after clicking to other page and the came back, loading is gone and the field works properly.

I noticed in the network tab the query for fetching the reference data return successfully and in Redux dev tool "RA/FETCH_END" is created and loading for <Admin/> becomes 0.

**Steps to reproduce:**
Add `<ReferenceManyField/>` to a `<List/>`.
Add `<Resource/>` for the reference resource under `<Admin/>`

```jsx
 <List {...props}>
    <Datagrid rowClick="edit">
      <ReferenceManyField
        label="Contacts"
        reference="contacts"
        target="companies"
      >
        <SingleFieldList>
          <ChipField source="name" />
        </SingleFieldList>
      </ReferenceManyField>
    </Datagrid>
  </List>
```

**Environment**

* React-admin version:
* React version: 16.6.0
* Browser: Chrome latest
* Stack trace (in case of a JS error): no

**Comment by fzaninotto** [comment]
I can't reproduce this bug in the simple example on the `master` branch. Can you please provide a CodeSandbox showing your issue?

**Comment by vedmalex** [comment]
@pak-zuhlke 
actually this means that your component didn't mouted to the props of the component in which is is shown. I have the same problem but i verified it with fakejson-dataprovider it is works without promises so the data is loaded before component is mounted.
i fix it by proper component mount...

**Comment by pak-zuhlke** [comment]
Thanks for the help guys! The cause of the issue was that I forgot to add <Resources> on contacts

**Comment by Mohamed-Hamed** [comment]
> @pak-zuhlke
> actually this means that your component didn't mouted to the props of the component in which is is shown. I have the same problem but i verified it with fakejson-dataprovider it is works without promises so the data is loaded before component is mounted.
> i fix it by proper component mount...

What do you mean by proper component mount?
I have the same problem but in TabbedShowLayout
ReferenceManyField doesn't show results unless I navigate to another Tab and go back again to previous tab.
