### ISSUE TITLE
What's up with TypeScript?

### ISSUE THREAD

**Issue by cyberhck** [marmelab/react-admin#2504]
This is a general question rather than a support question.

I see tslint and tsconfig.json files and some javascript files, I was wondering what's going on there, is react-admin slowly migrating? If it's in the process of gradual migration, I'd love to help out, it'd make so much sense for me, please let me know more on this.

If it IS accepting PRs and converting to TypeScript please let me know I'll try to send some PRs as I just stumbled onto this project and I just love it :)

I can't send huge PRs, which you won't love anyways, but I can do little at a time in my free time.

**Comment by djhi** [comment]
Exactly, we are slowly trying to add TS definitions and we would love some help! I plan to work on `ra-core` tomorrow.

**Comment by cyberhck** [comment]
I'm sorry I wasn't clear, I was trying to ask are we planning to move to TypeScript? As in we convert `.js` files into `.ts` or `.tsx` files? Because if that's the case, I'm super interested, I'd love to help out.

Adding type definition is messy, we have to work hard, and keeping it in sync with project is really difficult.

Let me know if actually moving to typescript is something you are interested in, I'd be interested :)

**Comment by fzaninotto** [comment]
Again, yes, we are moving to TypeScript, i.e. converting .js files to .ts and .tsx. I've explained that in the 2.4 release announcement:

https://marmelab.com/blog/2018/10/18/react-admin-2-4.html#bootstrap-typescript-migration

@djhi will start working on ra-core tomorrow, we need to start by the "leaves" of the type tree. 

Once that's over, we'd love a helping hand on that migration. Feel free to open a Work In Progress (WIP) PR mentioning the directory / files you're migrating, to avoid that two people work on the same subject.

As a side note, you should subscribe to the marmelab blog updates to hear about big news like TypeScript migration ;)

**Comment by cyberhck** [comment]
thanks, I didn't understand at first.

I'd really love to help.

Can we maybe create a milestone and add individual issues with files there? That'd make it really easy to keep track of who's working on what.

I'll try to see if I can migrate something as soon as I've some time.

**Comment by ajhool** [comment]
A while ago I converted 90% of the files in the next branch to Typescript as a rough draft (some of the types aren't exactly correct), but I'd be happy to provide the results to somebody if they thought it would be helpful. I didn't think marmelab would ever officially support it so I was using my own fork

**Comment by Vadorequest** [comment]
Discussion regarding TS has moved to https://github.com/marmelab/react-admin/issues/1617#issuecomment-595874113
