### ISSUE TITLE
Datagrid's last column doesn't line up / has wrong padding

### ISSUE THREAD

**Issue by aliang** [marmelab/react-admin#2506]
**What you were expecting:**
Header of last column of Datagrid should line up with data in column

**What happened instead:**
Header of last column has no padding, but cells in the table have 12px padding, thus making the cells not line up

**Steps to reproduce:**
None in particular, but you need to resize your browser window and/or switch the view in the CodeSandbox to be wide enough to show the Tags column. It won't show up in the narrow Responsive view because the last column is hidden.

**Related code:**
https://codesandbox.io/s/9o0jo2myqo

**Other information:**
![image](https://user-images.githubusercontent.com/162961/48104079-c80fb380-e1e6-11e8-97e0-7777207cd84e.png)

**Environment**

* React-admin version: 2.4.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.1
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi and thanks for reporting. If you look at the dev console, you'll see that the last column has the same padding as the others, only its width changes and it's set automatically by material-ui. I'm afraid there is nothing we can do about that

**Comment by aliang** [comment]
Thanks for the quick response.

I think we might be talking about a different comparison. It sounds like you're comparing the last column with the other columns, but I am comparing the last column's header with the last column's data rows.

- In the last column, the `th` padding is `0`, but the `tr` padding is `0 12px`.
- In the other columns, the `th` and `tr` padding are both `0 12px`.

I think the fix might be in https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/Datagrid.js. I haven't had a chance to test it yet, but I think that `styles.headerCell` needs the same padding style that is in `styles.rowCell`:
```
'&:last-child': {
    padding: '0 12px',
}
```

**Comment by aliang** [comment]
Also here are a couple more screenshots that might clarify things.

Styles and padding for `th`:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/162961/48116038-a845b300-e219-11e8-9e5e-c9e7494c6b98.png">

Styles and padding for `td`:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/162961/48116079-cc08f900-e219-11e8-86b0-40e2858f5531.png">

**Comment by fzaninotto** [comment]
Fixed by #2522
