### ISSUE TITLE
AutocompleteArrayInput has no fullWidth option

### ISSUE THREAD

**Issue by szi** [marmelab/react-admin#2510]
**What you were expecting:**
I was hoping for the fullWidth option to work similar to all the other Input fields.

An additional related issue: when adding more chips to the AutocompleteArrayInput field, it keeps growing horizontally indefinitely, but expected behavior would be wrapping.

**What happened instead:**
The field stays small, despite the fullWidth option.
Additionally, it does not wrap when more chips are added.

**Steps to reproduce:**
Sample code:
``` 
<ReferenceArrayInput fullWidth label="Filter by Data Series" source="filter_data_series" reference="data_series"  filterToQuery={searchText => ({ search: searchText })} allowEmpty>
    <AutocompleteArrayInput fullWidth optionText="label" />
  </ReferenceArrayInput>
```

**Environment**

* React-admin version: 2.4.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.6.1
* Browser: Chrome V68

**Comment by oksuz** [comment]
Can you try with `options` prop ? like this `options={{ fullWidth: true }}`

**Comment by oksuz** [comment]
Hello, you should add following prop to your `ReferenceArrayInput` component

`options={{ fullWidth:true }}`

**Comment by szi** [comment]
Thanks, that worked! A bit weird though that for some elements (like a SelectArrayInput within a ReferenceArrayInput) the plain `fullWidth` syntax works, but some others (like a AutocompleteArrayInput within a ReferenceArrayInput) need the full `options={{ fullWidth:true }}` syntax.

**Comment by afilp** [comment]
@oksuz I think that the point of @szi is valid. It is a little confusing when to use which. 

Do you think that this is clarified and I missed it somewhere?

From what I found, I need to use both, otherwise it does not work properly. I need to add `fullWidth` at `<ReferenceInput />` and then `options={{fullWidth: true}}` at its `<AutocompleteInput />`.

**Comment by aliang** [comment]
I never got any combination of `fullWidth` and `options={{ fullWidth: true }}` to work with `ReferenceArrayInput` and `AutocompleteArrayInput` (the one with chips). If I have some time I will try to isolate and debug it in a codepen.
