### ISSUE TITLE
Outdated readme: GraphQL Demo is down

### ISSUE THREAD

**Issue by tomsender** [marmelab/react-admin#2514]
Hi,

According to "ra-data-graphcool" readme, a version of the react-admin demo using this data provider is available at https://react-admin-graphql.now.sh/.
Unfortunately, I get 404 error code.

Readme page:
https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphcool

**Comment by fzaninotto** [comment]
ping @djhi should we remove that link?

**Comment by djhi** [comment]
Yes, I deployed it on my now.sh account and probably deleted it. Until we deploy it again, it should be removed
