### ISSUE TITLE
rowClick propagation event

### ISSUE THREAD

**Issue by BartoGabriel** [marmelab/react-admin#2515]
When the rowClick property of the datagrid is used and the DeleteButton is added it does not work as expected. After deleting the record, the application goes to the view set in the rowClick.
When you touch some of the buttons inside the datagrid the rowClick event should not be executed

Example: https://codesandbox.io/s/qx714kwy44

**Comment by fzaninotto** [comment]
Bug confirmed. 

Unfortunately, it can only be fixed by adding an `event.stopPropagation` to all buttons.

**Comment by fzaninotto** [comment]
I accidentally pushed to master, which closed that bug. I reverted the commit, and will open a PR soon.
