### ISSUE TITLE
Race condition when linking to another resource

### ISSUE THREAD

**Issue by alanpoulain** [marmelab/react-admin#2517]
**What you were expecting:**
Only one request with pagination and filters set correctly (like when reloading the page).

**What happened instead:**
Two requests are made:
- one with the default props of the `List` component and the URL parameters (coming from `componentDidMount`):
`/products?_end=10&_sort=id&_start=0&is_published=true&author=4`
(it should always be this one)
- one with the URL parameters (coming from `componentWillReceiveProps`):
`/products?_end=NaN&_sort=id&_start=NaN&author=4`

The result depends on the last answered request.

**Steps to reproduce:**
- A resource with a `filterDefaultValues` in its `List`.
- Another resource linking to the first without all the default pagination and filters set.
- Click on the link/button.
- See the two requests.

**Related code:**

Product:
```jsx
<List
  {...props}
  filterDefaultValues={{ is_published: true }}
>
```
LinkProduct:
```jsx
<Button
  component={Link}
  to={{
    pathname: '/products',
    search: stringify({
      sort: 'id',
      filter: `{"author": "${record.id}"}`
    })
  }}
>
```

**Other information:**
The only way to make it work correctly is to give all the default parameters to the `Link` component:
```jsx
<Button
  component={Link}
  to={{
    pathname: '/products',
    search: stringify({
      sort: 'id',
      order: 'DESC',
      page: 1,
      perPage: 10,
      filter: `{"is_published": true, "author": "${record.id}"}`
    })
  }}
>
```
Because of:
https://github.com/marmelab/react-admin/blob/31e388204165a8e8d7886a68a9a5ab4bfe279771/packages/ra-core/src/controller/ListController.js#L102-L112
it will not update the data and only one request will be made.

**Environment**

* React-admin version: 2.4.1
* Last version that did not exhibit the issue (if applicable): /
* React version: 16.6.0
* Browser: Chromium 70.0.3538.77
* Stack trace (in case of a JS error): /

**Comment by fzaninotto** [comment]
React-admin expects you to set all the parameters if you create a link to a filtered list. 

what you're asking is an enhancement to support links with partial parameters. I'm not sure we want to support that, as it adds complexity to the react-admin code and you can develop your feature otherwise. 

So I'm closing this issue. However, if you find a simple way to patch react-admin to support that, feel free to open a PR!
