### ISSUE TITLE
Using the permanent filter with multiple <List> components

### ISSUE THREAD

**Issue by Ryyval** [marmelab/react-admin#2519]
I've got three different lists rendering in a parent component that creates a tab for each list, this is to emulate an inbox, outbox, and trash.

Works just fine, until I set individual Permanent Filters on each list. It looks like all of the lists will filter based on which list set their 'filter' prop last, instead of what I set them to individually. For example, setting the first one to **Inbox** and the second one to **Outbox** and the third one to **Trash** will have all of the lists filter by **Trash** as the message type.

Here's the components being used within the FullWidthTabs component.

```
export const MessagesList = (props, resource) => (
   <FullWidthTabs>
      <List
         bulkActions={false}
         actions={<InboxListActions />}
         tabname="Inbox"
         {...props}
         filter={{ type: 'Inbox' }}
      >
         <MessagesGrid />
      </List>

      <List
         bulkActions={false}
         actions={<OutboxListActions />}
         tabname="Outbox"
         {...props}
         filter={{ type: 'Outbox' }}
      >
         <Datagrid style={tabStyle}>

            <DateField label="Date Sent" source="date" />

            <TextField label="Sent to" source="email" />

            <TextField source="subject" />


            <TextField style={contentPreviewStyle} source="content" />

            <ShowButton resource={resource} label="OPEN" />

            <DeleteButton resource={resource} label="Move To Trash" />
         </Datagrid>
      </List>

      <List
         bulkActions={false}
         actions={<DirectListActions />}
         tabname="Trash"
         {...props}
         filter={{ type: 'Trash' }}
      >
         <Datagrid style={tabStyle}>

            <DateField label="Date Recieved" source="date" />

            <TextField label="From" source="email" />

            <TextField source="subject" />


            <TextField style={contentPreviewStyle} source="content" />

            <ShowButton resource={resource} label="OPEN" />

            <DeleteButton resource={resource} label="DELETE" />
         </Datagrid>
      </List>
   </FullWidthTabs>
);
```
The API endpoint is an array named messages, as defined below:

```
var messageBoxes = ['Inbox', 'Outbox', 'Trash'];
// Fake 20 inbox messages
   for (let i = 0; i < 50; i++) {
      data.messages.push({
         id: i,
         confirmed: faker.random.boolean(),
         date: faker.date.past(),
         subject:
            faker.name.jobDescriptor() +
            ' ' +
            faker.name.jobArea() +
            ' ' +
            faker.name.jobType(),
         content: faker.lorem.paragraph(),

         email:
            faker.internet.email() +
            ' - ' +
            faker.name.firstName() +
            ' ' +
            faker.name.lastName(),
         type: messageBoxes[Math.floor(Math.random() * messageBoxes.length)]
      });
   }
```
In this scenario, **all of the lists have their permanent filter set to 'Trash' instead of what I individually set them to.**

Looking at the source code for List.jsx, I can see that 'filter' is in const sanitizeRestProps

Is this some sort of global filter for all lists on the current view, instead of them all having their own permanent filters?

I need help understanding just what's going on here if possible.

Here is the StackOverflow question as well: https://stackoverflow.com/questions/53211993/how-does-the-permanent-filter-work-when-theres-multiple-list-components-in-reac

**Comment by fzaninotto** [comment]
Good, you posted your question on StackOverflow. This issue tracker is not for support questions.

**Comment by christiaanwesterbeek** [comment]
Unfortunately the SO question was removed. I have a use case with multiple lists on the same page as well. The url change because of filtering on one list is causing filtering on the other list by a search term that is unrelated. Here's my SO question for it: https://stackoverflow.com/questions/59883643/how-to-not-change-the-url-on-list-filtering-with-react-admin

**Comment by christiaanwesterbeek** [comment]
Added a +50 points bounty to the [question](https://stackoverflow.com/questions/59883643/how-to-not-change-the-url-on-list-filtering-with-react-admin) on SO if you're interested.
