### ISSUE TITLE
The header in column grid disappears

### ISSUE THREAD

**Issue by anuraram1234** [marmelab/react-admin#2531]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**

See the image below,the header disappears

**What happened instead:**

![image](https://user-images.githubusercontent.com/44415680/48430478-49ee6800-e724-11e8-9459-599c6fabdf4b.png)

**Steps to reproduce:**
The Data grid

**Related code:**

```
< DNDReferField/>
```

```
 const DNDReferField = ({ record,...props }) =>
        prodActivePermissions.includes(localStorage.getItem("okta-role-storage")) && record &&  record.prodActive
            ?       
            <ReferenceField
            label="Linked Notifications"
            source="notificationId"
            reference="notifications"  linkType = "show" record={record} {...props}
            addLabel>
            <TextField source="name" label="Notification" addLabel={true}/>
          </ReferenceField> : <ReferenceField
            label="Linked Notifications"
            source="notificationId"
            reference="notifications" record={record} {...props}
            addLabel>
            <TextField source="name" label="Notification" addLabel={true} />
          </ReferenceField>;
```

**Other information:**
the column header comes blank

**Environment**

* React-admin version:2.3.3
* React version:16.5.2
* Browser:Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Do you see some warnings or errors in the console?

**Comment by fzaninotto** [comment]
Sorry, now i know. Your custom field does not have a label. Fix it with 

```
< DNDReferField label="Linked Notifications"/>
```

**Comment by anuraram12345** [comment]
Thanks.it works
