### ISSUE TITLE
bug unknow element with edition

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2533]
Hello,
I encounter a bug when I want to edit content. I click on the "edit" button and I have this popup at the bottom. If I refresh the page, all the fields disappear even though they appeared long before.
However, the API sends me the information (I checked in the console).
I think it's a bug related to react-admin.

![capture d ecran 2018-11-14 a 10 40 22](https://user-images.githubusercontent.com/9990521/48474338-a2903480-e7fa-11e8-9f61-d365eddca258.png)

**Environment**

* React-admin version: 2.4.2
* React version: 16.6.3
* Browser: 70

Thanks for your help!

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/vvw21793w0)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
No news for some time, closing. If you can provide a way to reproduce the bug, we'll reopen the issue.
