### ISSUE TITLE
AppBar Toolbar customization using children

### ISSUE THREAD

**Issue by alanpoulain** [marmelab/react-admin#2534]
**Is your feature request related to a problem? Please describe.**
If you want to add elements to the `Toolbar` of the `AppBar`, you need to copy all the `AppBar` into your custom one.

**Describe the solution you'd like**
Why not allowing children to be passed to the `Toolbar`? Maybe between `Typography` and `LoadingIndicator`.

**Describe alternatives you've considered**
It could also be a render prop for the `Toolbar`.

**Additional context**
Example:
```js
import React from 'react'
import { AppBar } from 'react-admin'

export default props =>
  <AppBar {...props}>
    <!-- Toolbar components here -->
  </AppBar>
```

**Comment by fzaninotto** [comment]
Fixed by #2777
