### ISSUE TITLE
Resources are unregistered on language switch

### ISSUE THREAD

**Issue by jorendemaeyer1996** [marmelab/react-admin#2537]
**What you were expecting:**
A multilanguage react-admin setup with our own [store and the admin components](https://marmelab.com/react-admin/CustomApp.html). provided with our own language provider (A combination of react-admin & react-intl [based on this issue](https://github.com/marmelab/react-admin/issues/1099?fbclid=IwAR3fpJ6vxgTWYpVhnPIQZzuqFMA5uTajWpYhSLwYB6PPmB0RklOBXKyVxBk)).

**What happened instead:**
On initial pageload the translations are loaded & working, but when i try to change the locale the messages & locale are loaded but the resources are unregistered.

**Steps to reproduce:**
1) Including React-Admin In Another Redux Application
2) Add the custom language provider
3) Switch languages and the resources are unregistered

**Related code:**
i18nProvider
https://gist.github.com/jorendemaeyer1996/4dd11399b37822ce531539a434b54047

App.js
https://gist.github.com/jorendemaeyer1996/97e7c5e8e34ac6335f5231ed16983de2

LanguageProvider.js
https://gist.github.com/jorendemaeyer1996/6701e619162192bf16e1b897023bd21f

createAdminStore.js
https://gist.github.com/jorendemaeyer1996/c5b5abe46b3a9aaf8770e97b041b7808

**Other information:**
On initial page load:
<img width="1680" alt="screenshot 2018-11-15 at 12 40 02" src="https://user-images.githubusercontent.com/16215602/48550668-b8bdf380-e8d3-11e8-9d41-6ba5a3d74489.png">

After the language switch:
<img width="1680" alt="screenshot 2018-11-15 at 12 40 34" src="https://user-images.githubusercontent.com/16215602/48550679-c1162e80-e8d3-11e8-9e04-3d0ef647c16f.png">

When i removed the store setup and let the Admin component take care of it everything works just fine.

**Environment**

* React-admin version: 2.4.0
* React version: 16.4.0
* Browser: chrome

**Comment by fzaninotto** [comment]
Sorry, we don't provide support for custom apps not using the default translation provider. Try asking your question on StackOverflow.
