### ISSUE TITLE
AutocompleteInput's tooltip's initial x-position is incorrectly calculated when added via ArrayInput/SimpleFormIterator

### ISSUE THREAD

**Issue by kctrlv** [marmelab/react-admin#2541]
Within an Edit page, when adding a new ReferenceInput/AutocompleteInput into an ArrayInput/SimpleFormIterator component, the hidden tooltip that gets created has an incorrectly calculated x-position parameter in its `transform: translate3d` property. When a user clicks the new field, the tooltip is not showing up properly, until they scroll the page. 

**Steps to reproduce:**
Please use the modified demo app @ https://codesandbox.io/s/jk89y91vw 
1. Go to CommentEdit 
2. Add a new Post to the array
3. Do not scroll the window.
4. Click into the new field (autocompleteinput). 
5. Notice that the tooltip (suggestions list) is incorrectly positioned somewhere off the screen.
6. Scroll the window, and notice that it appears where it should be. 
7. Go back to step 2 to repeat, but first inspect another AutocompleteInput's tooltip (suggestions list) that is already correctly positioned. When you add the new one, you can find the new element's `transform: translate3d(xposition)` was incorrectly calculated. Once you scroll the page, it auto-corrects.
 

* React-admin version: 2.4.1

![screen shot 2018-11-15 at 3 18 08 pm](https://user-images.githubusercontent.com/18424060/48585980-a2bc2d00-e8eb-11e8-96ea-f0f9c929d770.png)

The screenshot above is the inspection of the AutocompleteInput fields that were added in the Array. The first element was already on the page with the correct x-position value (79px). The second was just added and has an incorrect position, until the user scrolls the page.

**Comment by marquesgabriel** [comment]
i'm experiencing the same issue. Did you find any way to solve this?

**Comment by marquesgabriel** [comment]
The new version (2.5.1) corrected this

**Comment by fzaninotto** [comment]
Fixed by #2607
