### ISSUE TITLE
Allow 'sortable' to change dynamically (support it in 'shouldUpdate')

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#2543]
**Is your feature request related to a problem? Please describe.**
I tried to make `sortable` depended on a filter (`groupMode`, which renders a custom `Datagrid` with grouping of items, etc.), so that fields are not sortable when this filter is `true`.

See code:

```
<OurFieldElement
              fieldData={fieldData}
              key={fieldData.key}
              label={fieldData.label}
              source={fieldData.key}
              sortable={!props.filterValues.groupMode}
            />
```

This does not work out-of-the-box due to this code in `DatagridHeaderCell`:

```
    shouldUpdate(
        (props, nextProps) =>
            props.isSorting !== nextProps.isSorting ||
            (nextProps.isSorting &&
                props.currentSort.order !== nextProps.currentSort.order)
    ),
```

So, I tried to change this to include the `sortable` prop, but it does not work for some reason:

```
shouldUpdate(
    (props, nextProps) =>
      props.isSorting !== nextProps.isSorting ||
      (nextProps.isSorting &&
        props.currentSort.order !== nextProps.currentSort.order)
    || props.sortable !== nextProps.sortable
  )
```

**Describe the solution you'd like**
The `sortable` prop to be able to change dynamically.

**Describe alternatives you've considered**
Well, I had to take the `shouldUpdate` out... It is not the best solution though.

**Additional context**

**Comment by Kunnu01** [comment]
How can I reproduce it?
