### ISSUE TITLE
Conditional render of FormTab inside TabbedForm

### ISSUE THREAD

**Issue by FieryCod** [marmelab/react-admin#2548]
**What you were expecting:**

When I create the Conditional component which takes the predicate and renders the content accordingly.

```
import React from 'react'
import PropTypes from 'prop-types'

export const Conditional = ({ predicate, render, ...props }) => {
  console.log(predicate(props))
  return predicate(props) ? render(props) : null
}

Conditional.propTypes = {
  predicate: PropTypes.func.isRequired,
  render: PropTypes.func.isRequired,
}
```

When I create an `Edit` which uses the `Conditional` like so:
```  
  <Edit>
    <TabbedForm validate={validate}>
      <Conditional
        predicate={props => !!props.record && props.record.isEnabled}
        render={(
          props => (
            <FormTab label="Documents" {...props}>
              <DocumentsTab />
            </FormTab>)
        )}
      />
    </TabbedForm>
  </Edit>
```

Then if the predicate returns true the Tab should be rerendered.

**What happened instead:**

Given that I'm using these two components and
given that the `console.log` is there.

Then the statement prints like follows:
```
false
true
false
true
```
The last is true so the `TabbedForm` should be rerendered with the `Tab` from the `render` of `Conditional`.
 Instead, the Tab is not rendered.

**Environment**

* React-admin version: 2.4.2
* React version: 16.5.2
* Browser: Version 69.0.3497.92 (Official Build) (64-bit)

**Comment by fzaninotto** [comment]
`<TabbedForm>` expects `<FormTab>` components as children. If you want to create a tabbed form with conditional components, write your own form component.
