### ISSUE TITLE
Reorder nodes with ra-tree

### ISSUE THREAD

**Issue by despatates** [marmelab/react-admin#2550]
**Is your feature request related to a problem? Please describe.**
With the current `ra-tree` component, it's not possible to order nodes.

**Describe the solution you'd like**
I thought to a new dropzone like `RootDropTarget` that will be inserted before or after each tree node. The `dropTargetSpecs` would be the same as the associated node, but with a different order value.

I took a look at the code, nodes don't seem to have order property for now.

Do you plan to implement this behavior?
If no, can you tell me if this way is correct? Any advice about implementation?

**Describe alternatives you've considered**
I looked for an independent treeview component handling nodes ordering, but no one is enough customizable to use material-ui components.

**Comment by djhi** [comment]
> Do you plan to implement this behavior?

Not in the foreseeable future

> If no, can you tell me if this way is correct? Any advice about implementation?

It would work but I'm not sure it's the right way to do it. If you have many nodes, the tree will become very hard to read. Besides, I've seen `react-beautiful-dnd` has release a [new version](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v10.0.0) allowing to work with trees. I discarded this package at the time as it was not possible to handle trees. We will probably rewrite the `ra-tree` package with it as soon as possible (no ETA though). Feel free to give it a try!

**Comment by despatates** [comment]
I tried `react-beautiful-dnd` with the tree behavior, I succeeded to plug it with react-admin.
It was perfectly matching my use case, reordering/moving nodes.

I don't have code to provide, it was just a quick test. This feature has been unprioritized in my project.

**Comment by fzaninotto** [comment]
The new ra-tree in 2.9 allows for that if I'm not mistaken.
