### ISSUE TITLE
ReferenceArrayInput with AutocompleteArrayInput with filter is being overriden by free-text(q) search

### ISSUE THREAD

**Issue by zifnab87** [marmelab/react-admin#2559]
**What you were expecting:**
I expect in `AutocompleteArrayInput` the filter to be respected when I type something

**What happened instead:**
What happens is that results are matching only based on what I type and filter={} is not applied!
(filter should be combined with q:" " like search

**Steps to reproduce:**
Edit a Post, go to miscellaneous -> Tags . Click next to existing tags - you will see only the published tags as expected from `filter={{published: true}}`, try typing 'Tech' and you will see 'Technology' that is not published

**Related code:**
https://codesandbox.io/s/6jpkx6ro73

**Environment**

* React-admin version: 2.4.3

**Comment by fancyaction** [comment]
I experienced same issue.
