### ISSUE TITLE
[Feature Request] Creating resources using Material UI Steppers

### ISSUE THREAD

**Issue by hamidfzm** [marmelab/react-admin#2561]
Material UI has a component called [Stepper](https://material-ui.com/demos/steppers/). Steppers convey progress through numbered steps. I suggest we implement a feature to create resources using MUI steppers and tabs.

![Sample.gif](https://user-images.githubusercontent.com/5591800/48967101-f23be080-eff0-11e8-97cb-822fdebcc623.gif)

**Comment by fzaninotto** [comment]
What do you mean, create resource ? That would be a feature for developers, not users?

**Comment by hamidfzm** [comment]
React admin already has a tabbed form component. Why not implement another type of form called (for example) StepperForm which users create resources by step something like wizard.

**Comment by djhi** [comment]
This is really nice idea for an addon! We won't add it to the core though. Feel free to give it a try and reference your addon in our documentation
