### ISSUE TITLE
Add pagination to SelectInput, AutocompleteInput, etc.

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#2565]
**Is your feature request related to a problem? Please describe.**
Let's say that we have the `departments` resource, with around 2000 items and we want to use it as a filter for the `employees` List (so that the end-user can filter this list for a specific department only). 

The solutions we now have are **good but not ideal**:
- `<SelectInput />` is not very helpful because we would need to fetch all 2000 items in order for the end-user to choose one from. This is **quite heavy for the server/db** and also **bad for the UI** (showing a long list of 2000 items inside a floating combo box).

- `<AutocompleteInput />` comes to the rescue, as it restricts the number of results being sent from the server based on a `filterToQuery` and `like` logic. But this is not ideal because it assumes that the user really knows what to search for (i.e. the user knows the proper wording of the department, etc.). This is not ideal because the user **cannot browse the list** to see what the options are before selecting. 

**Describe the solution you'd like**
I'd like to have **pagination** at the **end of the floating combo** that appears showing the suggestions. This pagination should be fixed at the bottom of the combo, without being affected by its scrolling.

**Describe alternatives you've considered**
Showing a modal `<Dialog />` with a full `List` and `Datagrid` where the user can have pagination and filtering there and then do the selection by pressing a special button called **"Select"** that is at the end of each item (row).

This requires more effort from us though. On the contrary, a solution like the suggested (if implemented) would just require the use of a single prop: `pagination = {true}` (not sure if this is the only requirement though).

Note: If you think that the alternative I mentioned is the only solution, it would be nice to have an example showing this, which all users could copy/paste for their projects.

Thanks!

**Comment by fzaninotto** [comment]
I understand that your use case is too specific for ` SelectInput` and `AutocompleteInput`, so you'll need another component for that. I suggest you try and implement it, and if it's general enough that it can be reused outside of your project, please open a PR. 

As for us, we don't want to work on adding new features to autocomplete or select inputs - these are already dependencies, and adding feature / maintaining these features is worth an entire open-source project. As far as I know, there is no open-source package providing what you ask (I looked at Select2, downshift).
