### ISSUE TITLE
Resource Filter

### ISSUE THREAD

**Issue by tomtom16** [marmelab/react-admin#2567]
**Describe the solution you'd like**
It would be nice if above the explorer tree (resource tree) an input box would be added. It should act like a filter for the resources. When you start typing in this field, the resources should dynamically adapt to your entered search term. (Only those, who match the search term should be visible)

**Describe alternatives you've considered**
No alternatives

**Additional context**

<img width="289" alt="screen shot 2018-11-25 at 21 19 48" src="https://user-images.githubusercontent.com/23172948/48984115-ed158900-f0f7-11e8-9d52-2c601fc7fff1.png">

It could look like the attached image.

**Comment by fzaninotto** [comment]
Hi @tomtom16  Nice idea!

This can be achieved in userland with a [custom menu](https://marmelab.com/react-admin/Theming.html#using-a-custom-menu). And it's only useful for a small number of users (when they have many resources), so we won't implement it in core.

thanks for the suggestion anyway !
