### ISSUE TITLE
Add Torrent Tracker Lists

### ISSUE THREAD

**Issue by guy16510** [marmelab/react-admin#2576]
**Is your feature request related to a problem? Please describe.**
Hello I was looking for the option of adding either 'custom' torrent trackers, or just making the default addTorrent function on line 235, make an additional callback after added.

**Describe the solution you'd like**
So I have the payload of what the UI makes adding these via the webGui. Was hoping we could work together on it. Happy to shoot a PR if you can provide a little guidance. On where to add an additional post would be needed to the "core.set_torrent_trackers".

**Describe alternatives you've considered**
Was hoping to use your API instead of creating some sort of hacky web driver, and automate the GUI piece.

**Additional context**
Hopefully its clear enough above, but happy to create screenshots of adding trackers manually.

**Comment by djhi** [comment]
I have no idea what you are talking about

**Comment by psanatov** [comment]
wtf

**Comment by djhi** [comment]
?

**Comment by fzaninotto** [comment]
a search for `core.set_torrent_trackers` leads to https://forum.deluge-torrent.org/viewtopic.php?t=44387
