### ISSUE TITLE
material-ui-chip-input 1.0.0-beta.9 is breaking webpack compilation

### ISSUE THREAD

**Issue by rickydunlop** [marmelab/react-admin#2578]
**What you were expecting:**
Compiling files with webpack to produce a successful build

**What happened instead:**
I get this error 
```bash
Failed to compile.

./node_modules/material-ui-chip-input/lib/ChipInput.js
Module not found: Can't resolve '@material-ui/core/FilledInput/FilledInput' in '<path>/node_modules/material-ui-chip-input/lib'
```

**Other information:**
This appears related to the latest beta release of [material-ui-chip-input](https://github.com/TeamWertarbyte/material-ui-chip-input/commit/fbf8499c4f3f6f4f5c6fd0ca324778dc00f7c40a) which adds FilledInput and OutlinedInput which are not present in @material-ui/core 1.x

**Environment**

* React-admin version: 2.4.3
* React version: 16.6.3

I think the quick fix would be to pin material-ui-chip-input to 1.0.0-beta.8 or else update @material-ui/core to 3.x

**Comment by fzaninotto** [comment]
Bug confirmed, fix incoming..

**Comment by rocinante42** [comment]
woah, just waiting the new release solving this one.

**Comment by hanzlahabib** [comment]
is this issue fixed? because i don't see any solution. 
i am still facing this problem
i tried downgrading material-ui-chip to beta.8 and also tried updating material ui to latest version, and also tried downgrading material ui to v3 but it didn't worked, 
if this issue is fixed please point me to solution it will be very help full
thank you :)

**Comment by Kmaschta** [comment]
@hanzlahabib This issue was closed one year ago. What version of React Admin do you use?
This should not happen in the latest 2.x version.
If you have an issue with it on the v3-alpha, please open a new issue with a way to reproduce it.

**Comment by vgb0332** [comment]
Not gonna lie. The issue is not fixed. Tried every sort of version combination between react-admin and material-ui-chip-input but throwing compiling errors

**Comment by hanzlahabib** [comment]
Thank you for replying
Jazak Allah :)
