### ISSUE TITLE
Background image not covering entire page if custom image used for Login page

### ISSUE THREAD

**Issue by esoulution** [marmelab/react-admin#2597]
Background position is set to `auto` instead of `cover` if custom image used for Login page

```
	<Login
		loginForm={<MyLoginForm />}
		backgroundImage='https://source.unsplash.com/1600x900/?traffic,road'
		{...props}
	/>
```

**Fix:**

In Login.js replace
`this.containerRef.current.style.background = `url(${backgroundImage})`;`
with
`this.containerRef.current.style.backgroundImage = `url(${backgroundImage})`;`

**Environment**

* React-admin version: 2.5.0

**Comment by esoulution** [comment]
Fixed in 2.5.1

**Comment by fzaninotto** [comment]
yep, sorry for the temporary regression.

**Comment by antoniorrm** [comment]
not work in project.

**Comment by fzaninotto** [comment]
@antoniorrm As it works on master, we can't reproduce your problem. Please provide a link to a CodeSandbox reproducing the issue.
