### ISSUE TITLE
Multiple sort fields

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [marmelab/react-admin#2602]
**Is your feature request related to a problem? Please describe.**
Sometimes I need my initial sort like `sort` prop of `List` to include 2 fields. Thus I can sort on a date and some flag, say most important flagged things come first. 

**Describe the solution you'd like**
It could be nice if `react-admin` supports multiple sort items down to `dataProvider`. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fzaninotto** [comment]
We won't support it in the core. I suggest you write your own `Datagrid` to support that.

**Comment by christiaanwesterbeek** [comment]
I solved it with
`<List sort={{ field: 'year,name', order: 'DESC,ASC' }} />`

and adding something to your dataProvider that can handle it. The way it should handle the sort parameters though depends on how your API expects to receive them in the query. This is an extract from my dataProvider implementation concerning sort.

```
const convertRESTRequestToHTTP = (type, resource, params = {}) => {
    // ...
    switch (type) {
        case GET_LIST:
        case GET_MANY_REFERENCE: {
            const { page, perPage } = params.pagination || {};
            const { field, order } = params.sort || {};
            // ...
            const query = {};
            if (field) {
                const fieldParts = field.split(',');
                const orderParts = order.split(',');
                query.order = fieldParts
                    .map(
                        (field, index) =>
                            `${field}.${orderParts[index].toLowerCase()}`
                    )
                    .join(',');
            }
            // ...
```

It's not foolproof (order may be missing), but I'm the only one using this dataProvider so I should be safe for a while.

**Comment by alanpoulain** [comment]
I think this feature could be really useful and the code would not be much more complex.
Why not having this functionality in the core instead of relying on some hacks like the previous message?

**Comment by DKavaliou-by** [comment]
> We won't support it in the core. I suggest you write your own `Datagrid` to support that.

Could you provide any kind of motivation underthehood?

**Comment by christiaanwesterbeek** [comment]
It's not just DataGrid. In fact I've never used the multi column sorting in a DataGrid. I'm using that mainly in useGetList.

```
useGetList('some-resource', {
    sort: {
        field: 'title,sequence', order: 'ASC,ASC'
    },
    meta: {
        columns: ['id', 'title', 'sequence'],
    },
})
```

PS: Never mind the [columns meta](https://github.com/raphiniert-com/ra-data-postgrest/pull/41). I'm using it for [column filtering in Postgrest](https://postgrest.org/en/stable/api.html#vertical-filtering-columns).
