### ISSUE TITLE
SelectItem non scalar `id` value.

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [marmelab/react-admin#2604]
**Is your feature request related to a problem? Please describe.**
When using `SelectItem` `optionValue` should be able to be more complex than just scalar value. Say depending on selection I need to make more complex `filter query` say; 
```
    <SelectInput source="status" alwaysOn choices={[
      { id: { $regex: '^Waiting' }, name: 'Waiting' },
      { id: 'Completed', name: 'Completed' },
      { id: 'Waiting for parts purchase', name: 'Waiting for parts purchase' },
    ]} />
```

**Describe the solution you'd like**
Adding new non-mandatory field to `choices` with name `value`. If supplied it should be used for filter querying, if not `id` should be used.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fzaninotto** [comment]
Hi Dragomir-Ivanov, and thanks for your suggestion. Your use case seems to be very specific, and it seems that you're trying to put logic in the view that should lie in the data provider. 

So I'm sorry, we won't implement this in core; I suggest you write a custom `SelectInput` for your use case.
