### ISSUE TITLE
`SelectInput native={true}` doesn't propagete down to native `material-ui Select` 

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [marmelab/react-admin#2610]
**Is your feature request related to a problem? Please describe.**
`SelectInput native={true}` doesn't propagete down to native `material-ui Select`.

**Describe the solution you'd like**
It should work. Especially on mobile devices.

**Describe alternatives you've considered**
None

**Additional context**
It goes almost there. Down to the enclosing `Select` `div`.
@fzaninotto If you don't turn me down on this, will try to fix it. I promise :)

**Comment by Dragomir-Ivanov** [comment]
Just to mention my progress:
I got it using native `<select>` element with:
```
    <SelectInput source="status" alwaysOn choices={[
      { id: '{"$regex":"^Waiting"}', name: 'Waiting' },
      { id: 'Completed', name: 'Completed' },
      { id: 'Waiting for parts purchase', name: 'Waiting for parts purchase' },
    ]} parse={parseValue} format={formatValue} SelectProps={{ native: true }} />
```
However it doesn't show any menu, because `MenuItem`/choices are contained in `<li>` instead of `<option>`. A patch to `ra-ui-materialui/src/input/SelectInput.js` will be needed to propagate `component` prop down to `MenuItem`.

**Comment by fzaninotto** [comment]
From what I see, material-ui doesn't allow to use the same code for both native and non-native selects (because native select takes `input` while html select takes `MenuItem`). We won't support it in react-admin, so I suggest you open a PR on material-ui instead.

**Comment by fzaninotto** [comment]
exactly :+1:
