### ISSUE TITLE
enable reducers within `TestContext` component

### ISSUE THREAD

**Issue by peter-mouland** [marmelab/react-admin#2612]
**Is your feature request related to a problem? Please describe.**
While writing tests around our react-admin system, we found that we were not able to assert statements which rely on form actions being dispatched.

Rather than relying on the internals, and implementation details of our components, we'd prefer to test our forms as users would interact with them.  This means (simulating) clicking buttons and then asserting correct actions have been dispatched.  Currently, because reducers aren't integrated within `TestContext`, anything that happens after a dispatch (e.g. form submissions) won't be fired.

**Describe the solution you'd like**
I would like to be able use real reducers when using `TestContext`.

To prevent this from being a breaking change (i.e. once setup, actions will be dispatched and peoples tests may start breaking if they didn't expect this to happen e.g. dispatch an action may update state or unmount components), I propose adding a `enableReducers` flag.  This flag would swap the static state currently returned buy the store within `TestContext` with working reducers.

**Describe alternatives you've considered**
Alternatively, we could use the real react-admin `Admin` component within our tests, but this feels like is expects, and would require, a lot more boilerplate to get working.

The other alternative would be to test the internals of our components.  but I'd prefer not to as this doesn't ensure all aspects are plumbed together properly.

**Additional context**
I expect this would feel, for some people, less like unit tests and more like integration tests.  While this is true I do not see a downside to enabling people to perform more integration-like tests earlier on. 

This is the proposed code:
```js

const TestContext = ({ store, enableReducers, children }) => {
    const storeWithDefaults = enableReducers
        ? createStore(combineReducers(defaultReducers), merge(defaultStore, store))
        : createStore(() => merge(defaultStore, store));
    
    return (
        <Provider store={storeWithDefaults}>
            <TranslationProvider>{children}</TranslationProvider>
        </Provider>
    );
};
```

**Comment by fzaninotto** [comment]
Fixed by #2614
