### ISSUE TITLE
return the store when using TestContext

### ISSUE THREAD

**Issue by peter-mouland** [marmelab/react-admin#2613]
**Is your feature request related to a problem? Please describe.**
When trying to write tests using TestContext we would like to assert on certain actions being dispatched.

**Describe the solution you'd like**
I propose, using renderProps, to return the created `store` from `TestContext` to enable developers to spy on the store.dispatch method.

**Describe alternatives you've considered**
the alternative would be to unit test `mapDispatch` method directly, outside the context of the components.  This would be brittle and allow mistakes to creep in.  I feel it would be better to test the component completely plumbed in.

**Additional context**
This would be a non-breaking change and the renderProp option would be opt-in.

he is an example of the proposed code:

```js
const TestContext = ({ store, enableReducers, children }) => {
    const storeWithDefault = createStore(() => merge(store, defaultStore));

    const showChildren = () => (typeof children === 'function' ? children({ store: storeWithDefault }) : children);

    return (
        <Provider store={storeWithDefault}>
            <TranslationProvider>{showChildren()}</TranslationProvider>
        </Provider>
    );
};
```

**Comment by fzaninotto** [comment]
Fixed by #2614
