### ISSUE TITLE
Resource is missing from AUTH_CHECK

### ISSUE THREAD

**Issue by trsteel88** [marmelab/react-admin#2617]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
params.resource to contain the resource the user is accessing when AUTH_CHECK is fired.

**What happened instead:**
params.resource is undefined

The documentation says that AUTH_CHECK will be given the resource. However, this is coming back as undefined. Code below

```javascript
import { AUTH_LOGIN, AUTH_LOGOUT, AUTH_ERROR, AUTH_CHECK, AUTH_GET_PERMISSIONS } from 'react-admin';
import decodeJwt from 'jwt-decode';

const login_uri = `${process.env.REACT_APP_API_BASE_URL}/auth/login`;

export default (type, params) => {
    switch (type) {
        case AUTH_LOGIN:
            const { username, password } = params;
            const request = new Request(`${login_uri}`, {
                method: 'POST',
                body: JSON.stringify({ username, password }),
                headers: new Headers({ 'Content-Type': 'application/json' }),
            });

            return fetch(request)
                .then(response => {
                    if (response.status < 200 || response.status >= 300) {
                        throw new Error(response.statusText);
                    }

                    return response.json();
                })
                .then(({ token }) => {
                    localStorage.setItem('token', token);
                });

        case AUTH_LOGOUT:
            localStorage.removeItem('token');

            return Promise.resolve();

        case AUTH_ERROR:
            if (403 === params.status) {
                localStorage.removeItem('token');

                // redirect to /

                return Promise.reject();
            }

            localStorage.removeItem('token');

            return Promise.reject();

        case AUTH_GET_PERMISSIONS:
            const decodedToken = decodeJwt(localStorage.getItem('token'));

            return Promise.resolve(decodedToken.roles && decodedToken.roles.length > 0 ? decodedToken.roles : []);

        case AUTH_CHECK:
            const { resource } = params;
            
            console.log(resource);

            return localStorage.getItem('token') ? Promise.resolve() : Promise.reject();
    }

    return Promise.reject('Unknown method');
}
```

**Comment by fzaninotto** [comment]
Confirmed, this regression was introduced one year ago in #1301.

**Comment by RudyLu** [comment]
Is there any simple workaround for this?
What I need to do is let the general listing, say `posts/list` open to general user, but restrict the access to `posts/create`.

**Comment by gscarpino** [comment]
We plan to check the permissions on the different actions in the dataProvider until it is solved

**Comment by aam1r** [comment]
> We plan to check the permissions on the different actions in the dataProvider until it is solved

That's a neat idea. Do you have a quick example for this? Is there something in the `props`?

**Comment by gscarpino** [comment]
> > We plan to check the permissions on the different actions in the dataProvider until it is solved
> 
> That's a neat idea. Do you have a quick example for this? Is there something in the `props`?

In you dataProvider:

```
export default (type, resource, params) => {

    //...

    if(!userHasPermissions(type, resource)){
        throw new Error('Not authorized!');
    }

    //...

}
```

We check local permissions in  'userHasPermissions'

**Comment by fzaninotto** [comment]
We've definitely removed the ability to check authentication for a given resource in the documentation. The auth_check is for authentication only.
