### ISSUE TITLE
AUTH_CHECK on bulkAction

### ISSUE THREAD

**Issue by L-Luciano** [marmelab/react-admin#2621]
When my token expired, I can click on delete button in List. 
The Optimistic Rendering display the message whereas my token is expired. the request is sent and the API send a error.

**Describe the solution you'd like**
Is it possible to call the AUTH_CHECK from AuthProvider on click event to avoid to call api whereas the token is expired ?

Do I have to call redux myself on event click ? (How can I do it in deleteBulkAction ?)

**Comment by fzaninotto** [comment]
Hi @L-Luciano,

And thanks for your suggestion.

Me made a drastic choice with optimistic rendering, and what you describe is one of the drawbacks - that we accept. Normally, the API error should be caught by your authProvider so the user is redirected to the login page (see https://marmelab.com/react-admin/Authentication.html#catching-authentication-errors-on-the-api). So the user experience is, overall, acceptable in this corner case, while it's greatly improved in the general case by optimistic rendering.

So we won't add more AUTH_CHECK calls in the core. Feel free to use custom buttons to dispatch the actions yourself, though.
