### ISSUE TITLE
TabbedForm.js and TabbedShowLayout.js non use API Tabs from '@material-ui/core/Tabs'

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#2629]
**Is your feature request related to a problem? Please describe.**
TabbedForm.js and TabbedShowLayout.js non use API Tabs from '@material-ui/core/Tabs'

**Describe the solution you'd like**
I want to use Props from [https://material-ui.com/api/tabs/](https://material-ui.com/api/tabs/)

**Describe alternatives you've considered**

> TabbedForm.js
```
...
return (React.createElement("form", __assign({ className: classnames('tabbed-form', className), key: version }, sanitizeRestProps(rest)),
            React.createElement(Tabs
            // The location pathname will contain the page path including the current tab path
            // so we can use it as a way to determine the current tab
            , { 
                // The location pathname will contain the page path including the current tab path
                // so we can use it as a way to determine the current tab
                

                value: tabsValue, ...sanitizeRestProps(rest) }, Children.map(children, function (tab, index) {
                //value: tabsValue, indicatorColor: "primary" }, Children.map(children, function (tab, index) {
                
				
				if (!tab)
                    return null;
                // Builds the full tab tab which is the concatenation of the last matched route in the
                // TabbedShowLayout hierarchy (ex: '/posts/create', '/posts/12', , '/posts/12/show')
                // and the tab path.
                // This will be used as the Tab's value
                var tabPath = getTabFullPath(tab, index, match.url);
                return React.cloneElement(tab, {
                    context: 'header',
                    value: tabPath,
                    className: tabsWithErrors.includes(tab.props.label) &&
                        location.pathname !== tabPath
                        ? classes.errorTabButton
                        : null,
                });
            })),
...
```

> TabbedShowLayout.js
```
TabbedShowLayout.prototype.render = function () {
    ...
            React.createElement(Tabs
            // The location pathname will contain the page path including the current tab path
            // so we can use it as a way to determine the current tab
            , { 
                // The location pathname will contain the page path including the current tab path
                // so we can use it as a way to determine the current tab
                
				
				value: location.pathname, ...sanitizeRestProps(rest) }, Children.map(children, function (tab, index) {
				//value: location.pathname, indicatorColor: "primary" }, Children.map(children, function (tab, index) {
                
				
...
    return TabbedShowLayout;
```

**Additional context**
```
const UserTabbedEditLayout = (props) => {
    const {record} = props;
    return (
        <TabbedForm 
            {...props}
            centered
            toolbar={<EditToolbar />}
        >
           ...
        </TabbedForm>
    )
};
```
before:
![screenshot-localhost-3000-2018 12 06-09-06-30](https://user-images.githubusercontent.com/28799755/49566041-61db9500-f93a-11e8-9c62-4f2f502a5862.png)

after:
![screenshot-localhost-3000-2018 12 06-09-34-16](https://user-images.githubusercontent.com/28799755/49566053-6a33d000-f93a-11e8-9e06-7e3089923872.png)

however, Chrome 71 issues a Warning:

> Warning: Failed prop type: Invalid prop `centered` of type `string` supplied to `Tabs`, expected `boolean`.
>     in Tabs (created by WithStyles(Tabs))
>     in WithStyles(Tabs) (created by TabbedShowLayout)
>     in div (created by TabbedShowLayout)
>     in TabbedShowLayout (created by Context.Consumer)
>     in translate(TabbedShowLayout) (created by Route)
>     in Route (created by withRouter(translate(TabbedShowLayout)))
>     in withRouter(translate(TabbedShowLayout)) (at User/index.js:119)
>     in UserTabbedShowLayout (at User/index.js:153)
>     in div (created by Paper)
>     in Paper (created by WithStyles(Paper))
>     in WithStyles(Paper) (created by Card)
>     in Card (created by WithStyles(Card))
>     in WithStyles(Card) (created by ShowView)
>     in div (created by ShowView)
>     in ShowView (created by ShowController)
>     in ShowController (created by Context.Consumer)
>     in translate(ShowController) (created by Connect(translate(ShowController)))
>     in Connect(translate(ShowController)) (created by Show)
>     in Show (created by WithStyles(Show))
>     in WithStyles(Show) (at User/index.js:152)
>     in UserShow (created by WithPermissions)
>     in WithPermissions (created by Connect(WithPermissions))
>     in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
>     in getContext(Connect(WithPermissions)) (created by Route)
>     in Route (created by Resource)
>     in Switch (created by Resource)
>     in Resource (created by Connect(Resource))
>     in Connect(Resource) (at App.js:68)
>     in Route (created by RoutesWithLayout)
>     in Switch (created by RoutesWithLayout)
>     in RoutesWithLayout (created by Route)
>     in div (created by Layout)
>     in main (created by Layout)
>     in div (created by Layout)
>     in div (created by Layout)
>     in Layout (created by WithStyles(Layout))
>     in WithStyles(Layout) (created by Route)
>     in Route (created by withRouter(WithStyles(Layout)))
>     in withRouter(WithStyles(Layout)) (created by Connect(withRouter(WithStyles(Layout))))
>     in Connect(withRouter(WithStyles(Layout))) (created by LayoutWithTheme)
>     in MuiThemeProvider (created by LayoutWithTheme)
>     in LayoutWithTheme (at Layout/index.js:101)
>     in MyLayout (created by Route)
>     in Route (created by CoreAdminRouter)
>     in Switch (created by CoreAdminRouter)
>     in div (created by CoreAdminRouter)
>     in CoreAdminRouter (created by Connect(CoreAdminRouter))
>     in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
>     in getContext(Connect(CoreAdminRouter)) (created by Route)
>     in Route (created by CoreAdmin)
>     in Switch (created by CoreAdmin)
>     in Router (created by ConnectedRouter)
>     in ConnectedRouter (created by CoreAdmin)
>     in TranslationProviderView (created by Connect(TranslationProviderView))
>     in Connect(TranslationProviderView) (created by CoreAdmin)
>     in Provider (created by CoreAdmin)
>     in CoreAdmin (created by withContext(CoreAdmin))
>     in withContext(CoreAdmin) (at App.js:50)
>     in App (at src/index.js:7)

**Comment by fzaninotto** [comment]
I don't understand your point. The components you describe do use mui Tabs:

https://github.com/marmelab/react-admin/blob/d81aede2d579334d98ceb40d9986efa0b2fcf43e/packages/ra-ui-materialui/src/form/TabbedForm.js#L14

Is it possible that you're trying to use new props of the mui Tab component (un mui 3.0), while react-admin is only compatible with mui 1.0?,

**Comment by wmwart** [comment]
Yes, I used the mui 3.x.x documentation, however, the mui 1.x.x version also defines the properties that I need (e.g. centred).
But it does not matter, because in the TabbedForm.js and TabbedShowLayout.js code hardcoded  properties only :
> value: tabsValue, indicatorColor:"primary"

**Comment by fzaninotto** [comment]
That means you can't use TabbedForm for your use case, and that you'll have to replace it by your own component. It should be quite straightforward.

Additional properties of Tabbedform are already passed down to the `<form>` element. We don't want to complexify the API of the react-admin components by letting developers pass all kinds of options to all kinds of elements in the JSX. Instead, we promote the ability to replace any component that doesn't fit your need by another component of your own. 

The only change we could accept is to support passing a custom `tabs` prop to `TabbedForm`, to be used instead of mui's `<Tabs>` (just like we allow overriding `<DatagridBody>` in `<Datagrid>`). If you feel like adding this ability, please open a PR against the `next` branch of react-admin.
