### ISSUE TITLE
window.devToolsExtension is deprecated and will be removed in next version of Redux DevTools

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#2632]
**Is your feature request related to a problem? Please describe.**

After the recent update to the Redux Devtools Extension, I am getting a warning in the console:

VM1998:1 `window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__`, and will be removed in next version of Redux DevTools

**Describe the solution you'd like**

Probably just use the other reference to the function.

**Describe alternatives you've considered**

Alternatively let end-developers shim it themselves by assigning `window.devToolsExtension = window.__REDUX_DEVTOOLS_EXTENSION__` in their index file?

**Additional context**

In Chrome.

**Comment by waynebloss** [comment]
I got rid of the warning in my project by simply putting the re-assignment in my `index.js` file:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

window.devToolsExtension = window.__REDUX_DEVTOOLS_EXTENSION__;

ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by phacks** [comment]
This was also bugging me, so I went ahead and suggested a PR. Tell me what you think!
