### ISSUE TITLE
permanentFilter issue in updating new values

### ISSUE THREAD

**Issue by cmandesign** [marmelab/react-admin#2636]
When I update the permanentFilter props in List, I see that my functions are working with the previous state every time. 
I've used a debugging tool to see what happens in the core and here is where I found the misplacing of data, in the ListController.js. 
As you can see in the below picture, there is a line that wrote 
`const permanentFilter = this.props.filter`
as I have seen in the debugger, the props have not been updated in this time and the value of permanentFilter is always the previous state.

![image](https://user-images.githubusercontent.com/16540068/49696596-47ffb380-fbc1-11e8-919d-ea2ec74edf68.png)

**Comment by fzaninotto** [comment]
Can you test with the latest react-admin version? I think it was fixed by #2831

**Comment by fzaninotto** [comment]
No news for some time, closing.
