### ISSUE TITLE
DatagridBody is not exported from react-admin

### ISSUE THREAD

**Issue by hamidfzm** [marmelab/react-admin#2637]
**What you were expecting:**
importing following statement:
```js
import {DatagridBody as RaDatagridBody} from 'react-admin';
```

**What happened instead:**
Got following error:
```bash
Failed to compile.

./src/resources/Transaction/list/DatagridBody.js
Attempted import error: 'DatagridBody' is not exported from 'react-admin' (imported as 'RaDatagridBody').
```

**Steps to reproduce:**
Just import it :)

**Other information:**
As documented in https://marmelab.com/react-admin/List.html#the-datagrid-component, we can import datagrid body from react admin but it's not possible.

**Environment**

* React-admin version: 2.5.1

**Comment by dalyr95** [comment]
Getting this issue as well. 
```
import { DatagridBody } from 'react-admin';
console.log(DatagridBody);
```
is `undefined`

Exporting 'react-admin' the key is missing
```
DashboardMenuItem: (...)
Datagrid: (...)
DateField: (...)
DateInput: (...)
DateTimeInput: (...)
DeleteButton: (...)
DisabledInput: (...)
```
React Admin version "2.5.1"
