### ISSUE TITLE
Empty List Invite

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#2639]
If there is no result, and if there is no active filter, and if the resource has a Create page, the List page should display a special content inviting the user to create their first element.

![localhost_8080_](https://user-images.githubusercontent.com/99944/49718468-77163380-fc5a-11e8-8695-6775dae0c290.png)

Inspirations:

- http://emptystat.es/
- https://uxplanet.org/empty-state-mobile-app-nice-to-have-essential-f11c29f01f3
- https://twitter.com/steveschoger/status/1058398981888376832

**Comment by m4theushw** [comment]
@fzaninotto What about this?

![empty-state](https://user-images.githubusercontent.com/42154031/69566595-319b6500-0f96-11ea-95a7-f3aa6a1f64c1.png)

**Comment by fzaninotto** [comment]
The first thing about that invite is that it should take the whole content space - filters and export have no meaning here.

Besides, the Create button should use the Filled variant instead of the Standard variant, because it becomes the main action. And I think the Create button should move to the center of the page. 

The invite text should be highly configurable (because it may make sense to create some resources, but it may not make sense for others).

We should not say "no results found". In this case, we know there are no results at all. Also, I'm not fond of "be the first to"... 

Suggestions for the invite text: 

> No $[name} yet.
> Do you want to add one?
> [Create]
