### ISSUE TITLE
Ability to add custom links to reference fields

### ISSUE THREAD

**Issue by dankram** [marmelab/react-admin#2643]
I'd like to supply a custom link to a reference field.

Use case:
If I have a movie that references a company. Normally when I click on the company name it will go to either the edit or show for that company. Instead what I'd like to do is when I click on the company name it should go back to the movie list page with that company name as a filter on the list.

I don't see another way to do this other than copy and rewrite the ReferenceField component.

**Comment by fzaninotto** [comment]
Hi @dankram, and thanks for your suggestion. 

You'll have to write a custom component for that, react-admin won't provide one in core. It would be too difficult to standardize - and writing your own component for that will only take a few lines.
