### ISSUE TITLE
Allow passing `replace={true}` to FormTabs Link.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#2651]
Hello, I will make a pull request for this feature if you approve. It should be trivial.

**Is your feature request related to a problem? Please describe.**
I want react-router to replace the history entry instead of creating a new one every time you change tabs in TabbedForm. That way the user can quickly use the back button to go back to the list view.

**Describe the solution you'd like**
At the very least, I'd like to be able to have `FormTab` pass `replace={true}` to its `MuiTab/Link` element. It turns out that `<FormTab replace>` *does* do this, but that same `replace={true}` property gets passed down to every input element as well, resulting in:

> Warning: Received `true` for a non-boolean attribute `replace`.
> If you want to write it to the DOM, pass a string instead: replace="true" or replace={value.toString()}.

**Describe alternatives you've considered**
I tried passing `replace="true"` since `react-router-dom`s code for `Link` does a simple truthy test, but they actually guarded the type with `PropTypes`, so that produces:

> Warning: Failed prop type: Invalid prop `replace` of type `string` supplied to `Link`, expected `boolean`.

Despite the warnings, everything works the way I want it to regardless of how I pass the prop. So one other alternative is that I could just ignore this warning. It also builds just fine. It's a bit annoying to have the error during development though.

**Additional context**
This is easy to fix in `FormTab`, just sanitize the `replace` prop and pass it to `MuiTab`.

**Comment by fzaninotto** [comment]
Fixed by #2654
