### ISSUE TITLE
react-admin demo not working for IE11

### ISSUE THREAD

**Issue by activist** [marmelab/react-admin#2653]
What you were expecting:
That the react-admin demo should work with IE11

What happened instead:
Hangs at loader page. Console error is "Object does not support assign method.."

Steps to reproduce:
Go to https://marmelab.com/react-admin-demo/ using IE 11. Page won't open.

**Comment by phacks** [comment]
Pushed a PR that fixed the problem in my local IE11 setup (CRA 2.0 needs to include polyfills for IE now) 🙂
