### ISSUE TITLE
Cannot remove a filter with a compound name

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2657]
Hello,
I have an error in the console when I delete a filter.
I noticed that this problem only occurs on pages with links to references.
I couldn't reproduce the bug on the demo page.
The filter works correctly despite the error in the console.
This bug is not similar to #650

```
<Filter {...props}>
  <TextInput source="name" label="name" />
</Filter>
```

**Environment**

* React-admin version: 2.5.1
* React version: 16.6.3
* Browser: Chrome
* Stack trace (in case of a JS error):
![capture d ecran 2018-12-12 a 17 06 24](https://user-images.githubusercontent.com/9990521/49925942-acb95780-feba-11e8-9f3c-f430fdcc4e26.png)

**Comment by fzaninotto** [comment]
I can't reproduce it on master. 

I suggest you fork the codesandbox to show that the error comes from react-admin and not your code.

**Comment by nacimgoura** [comment]
I understood how to reproduce the bug.

With this, the bug occurs and the filter works correctly :
```
<ReferenceInput
      label="Unité"
      source="units.id"
      reference="units"
      perPage={100}
    >
      <AutocompleteInput optionText="code" />
</ReferenceInput>
```

But by replacing the `units.id' source with `unit` the filter still works and can be deleted :
```
<ReferenceInput
      label="Unité"
      source="units"
      reference="units"
      perPage={100}
    >
      <AutocompleteInput optionText="code" />
</ReferenceInput>
```

I don't understand the problem.
