### ISSUE TITLE
Not working with react-redux 6.0.0

### ISSUE THREAD

**Issue by martisekpetr** [marmelab/react-admin#2665]
**What you were expecting:**
After upgrade to `react-redux 6.0.0` my app using react-admin should be still working.

**What happened instead:**
Getting `Uncaught Error: Could not find "store" in the context of "Connect(Menu)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Menu) in connect options.`

**Other information:**
Seems to be a direct manifestation of an error outlined in "Breaking changes" section of https://github.com/reduxjs/react-redux/releases/tag/v6.0.0 
I would guess the problem lies in the use of now deprecated `react-router-redux` library.

**Environment**

* React-admin version: 2.5.2
* React version: 16.4

**Comment by djhi** [comment]
It won't happen any time soon for the same reason we haven't upgraded to the latest MUI. See @fzaninotto answers on this issue: https://github.com/marmelab/react-admin/issues/2399

**Comment by fzaninotto** [comment]
Also, react-admin has its own requirements in terms of dependency versions. If you upgrade a dependency to a major release despite react-admin capping the version, don't expect it to work.

**Comment by NitaAlexandr** [comment]
Hi,

So I am working with react-admin v2.6.0 and ... what is the best/safest version of react-redux to use with it?

Thank you.

**Comment by djhi** [comment]
See https://github.com/marmelab/react-admin/blob/master/packages/ra-core/package.json#L56

**Comment by NitaAlexandr** [comment]
@diji God bless you and thank you :D
