### ISSUE TITLE
Resource without "list" prop does not appear in the admin menu

### ISSUE THREAD

**Issue by pw054** [marmelab/react-admin#2671]
I'm attempting to add a configuration page (as shown in the sample), to change some server properties, not to CRUD a list of records on a table. Therefore, I'm not using the `list` prop for that resource.

I'm using one `Resource` for "Configuration, with `create` and `edit` props defined, and pointing to two components called `ConfigurationCreate` and `ConfigurationEdit`.

I have followed the guide for `Create` and `Edit` components as documented in CreateEdit.md.

**App.js:**
```
// in src/App.js
import React from 'react';
import { Admin, Resource } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

import { PostCreate, PostEdit } from './posts';

const App = () => (
    <Admin dataProvider={jsonServerProvider('http://jsonplaceholder.typicode.com')}>
        <Resource name="posts" create={PostCreate} edit={PostEdit} />
    </Admin>
);

export default App;
```

**posts.js:**
```
// in src/posts.js
import React from 'react';
import { Create, Edit, SimpleForm, DisabledInput, TextInput, DateInput, LongTextInput, ReferenceManyField, Datagrid, TextField, DateField, EditButton } from 'react-admin';
import RichTextInput from 'ra-input-rich-text';

export const PostCreate = (props) => (
    <Create {...props}>
        <SimpleForm>
            <TextInput source="title" />
            <TextInput source="teaser" options={{ multiLine: true }} />
            <RichTextInput source="body" />
            <DateInput label="Publication date" source="published_at" defaultValue={new Date()} />
        </SimpleForm>
    </Create>
);

export const PostEdit = (props) => (
    <Edit title={<PostTitle />} {...props}>
        <SimpleForm>
            <DisabledInput label="Id" source="id" />
            <TextInput source="title" validate={required()} />
            <LongTextInput source="teaser" validate={required()} />
            <RichTextInput source="body" validate={required()} />
            <DateInput label="Publication date" source="published_at" />
            <ReferenceManyField label="Comments" reference="comments" target="post_id">
                <Datagrid>
                    <TextField source="body" />
                    <DateField source="created_at" />
                    <EditButton />
                </Datagrid>
            </ReferenceManyField>
        </SimpleForm>
    </Edit>
);
```

**What you were expecting:**
The resource item should appear in the admin menu, and direct to a form with configuration options.

**What happened instead:**
The resource item does not appear in the admin menu.

**Steps to reproduce:**
Use the provided source code above, following the CreateEdit.md file included in `react-admin`.

**Other information:**
* Sample code also available here: https://codesandbox.io/s/l4k345r53z

**Environment**

* React-admin version: 2.5.2
* React version: 16.6.3
* Browser: Chrome 70.0.3538

**Comment by Kmaschta** [comment]
It seems to be intentional to not show, in the menu, the resources that don't have list.

https://github.com/marmelab/react-admin/blob/ca8b70a0fb6b40ce2210192cf0440a694171ea4c/packages/ra-ui-materialui/src/layout/Menu.js#L48-L53

But I didn't find a reason on the documentation. I'll let the maintainers bear with that decision to document or change this behavior.

**Comment by djhi** [comment]
Yes, the menu item does not appear if there are not List component. If you want a menu item linking to the create or edit page, you'll have to create a [custom menu](https://marmelab.com/react-admin/Theming.html#using-a-custom-menu).

**Comment by djhi** [comment]
PS: This should be made clearer in the documentation indeed
