### ISSUE TITLE
react-admin show view is not showing anything

### ISSUE THREAD

**Issue by Taymindis** [marmelab/react-admin#2672]
I am referring the tutorial below to create show component, but it is not working.

https://marmelab.com/react-admin/Show.html#the-showguesser-component

**Comment by djhi** [comment]
Can you please be more specific about what is not working ?

**Comment by Taymindis** [comment]
It it blank page , but list component is working fine.

**Comment by Taymindis** [comment]
Hi Kmaschta, 

I just change 2 line, then it just show me the blank page. What response format is show attribute accepted?

From your side is work if wrap it all together, but what I need just a show layout only.

References;
https://codesandbox.io/s/lxw015lq07

**Comment by Kmaschta** [comment]
Your Resource need to have a `list` prop to be displayed first.

https://codesandbox.io/s/y3797684pv

Indeed, the example doesn't show the list prop for brevity, but you need one.
Also, the documentation and the code isn't really explicit about this mandatory list prop, but we're working on it.

So, if you just put a show prop, it's normal that it's list isn't displayed.

**Comment by djhi** [comment]
As we are not dealing with a bug of react-admin, please ask your question on StackOverflow as specified in our guidelines.
