### ISSUE TITLE
Default value not displayed with BooleanInput

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2681]
Hello,
when I set the default value true, it is well managed in my filter but the displayed value is always equal to false.

```
<BooleanInput
  source="account.active"
  label="active"
  defaultValue={true}
/>
```

![capture d ecran 2018-12-19 a 17 06 11](https://user-images.githubusercontent.com/9990521/50232128-8743b680-03b0-11e9-942a-dec915643b91.png)

I think it's a bug. Same problem with `NullableBooleanInput`.

**Other information:**

**Environment**

* React-admin version: 2.5.2
* React version: 16.6.3
* Browser: Chrome

**Comment by Kmaschta** [comment]
It does work for me: https://codesandbox.io/s/0q6583162p
Look at the Post Creation form, the "commentable" boolean input.

Do you have a bit more context ? Which version of Material UI do you use?

**Comment by fzaninotto** [comment]
@Kmaschta it seems to be in the context of a Filter form

**Comment by nacimgoura** [comment]
Yes I also tested on the sandbox and it works.
In fact the default value does not work when the source is an object, for example  `account.active`.

**Comment by Kmaschta** [comment]
Interesting clue: it seems to be working on RA 2.3: https://codesandbox.io/s/l5wknxqmwq (see the Post List filters)
I'm trying to figure out how to make RA 2.5 work on CodeSandbox.

**Comment by Kmaschta** [comment]
OK ! I managed to get RA 2.5 working with CodeSandbox thanks to François.

Here it is, on the PostList, there is a BooleanInput as a filter with `defaultValue` is true: https://codesandbox.io/s/y0xx53yy0v

![image](https://user-images.githubusercontent.com/1819833/50236364-77c96b00-03ba-11e9-9718-0b3e961c251c.png)

And it seems to be working.
Do you know what can be different from your codebase?

**Comment by djhi** [comment]
I can't reproduce this issue anymore on V3. Feel free to reopen if I'm wrong

**Comment by osseonews** [comment]
"the default value does not work with BooleanInput and NullableBooleanInput when the source is an object,
for example accounts.commented." Still have this bug. Default Value does not work with objects. On version 3.19.4
