### ISSUE TITLE
resource tag options.label is not working

### ISSUE THREAD

**Issue by Taymindis** [marmelab/react-admin#2683]
<Resource name="posts" options={{ label: 'All' }}  {...posts} />,   

Is it not working? what happened?? I am using 
    "react-admin": "^2.5.2",

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/vvw21793w0)
* A sample application via GitHub

**Comment by Taymindis** [comment]
I have make the change on index.js:50 

add 
        options={{ label:'Posting' }}

It doesn't change the label, doesn't take effect

**Comment by fzaninotto** [comment]
Reproduced and confirmed, thanks for the CodeSandbox.

**Comment by fzaninotto** [comment]
I looked at the code, and in fact there is no bug. The `Resource` `options.label` is used as a menu label *unless you use i18n to translate the resource name*, which is exactly the case in the CodeSandbox you provided. Just remove the `resources.post.name` key in the `i18n/en.js` file, and the menu takes the label all right.
