### ISSUE TITLE
AutocompleteInput auto select the option before i click from suggestion list 

### ISSUE THREAD

**Issue by zohaib055** [marmelab/react-admin#2688]
I'm using AutocompleteInput to pick value from categories if search the word "ag" it auto fills the  input with word "Agent" instead of showing suggestion list

**What should happen**

it should show the suggestions if i type "ag" or something other instead of pre populating the suggestion into input

**Comment by afilp** [comment]
@djhi Are you sure that this is closed due to the commit that you referenced? The commit seems irrelevant to the issue.

**Comment by lijoantony** [comment]
Related to #2641 
This workaround https://github.com/marmelab/react-admin/issues/2641#issuecomment-456188219 helps.
