### ISSUE TITLE
Prop style in SimpleShowLayout doesn't works

### ISSUE THREAD

**Issue by AdriaRios** [marmelab/react-admin#2697]
**What you were expecting:**
If I provide a `style` prop to `SimpleShowLayout`. Styles should be applied. Following the docu:
https://marmelab.com/react-admin/Show.html

**What happened instead:**
If I provide a `style` prop to `SimpleShowLayout`. Styles aren't applied

**Steps to reproduce:**
Check that, and confirm that does not works:

```
<SimpleShowLayout style={{backgroundColor: 'hotpink'}}>
      ....
</SimpleShowLayout>
```

**Environment**

* React-admin version: 2.5.2
* React version:16.5.2
* Browser: Chrome

**Comment by fzaninotto** [comment]
The doc is outdated. `style` isn't supported anymore, you need to pass a `className` to override the styles. I'm going to update the doc accordingly.
