### ISSUE TITLE
Date timezone problem in cypress

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#2702]
In cypress project, in create.js file, there is the following comparison:

        const currentDate = new Date();
        const currentDateString = currentDate.toISOString().slice(0, 10);
        cy.get(CreatePage.elements.input('published_at')).should(el =>
            expect(el).to.have.value(currentDateString)
        );

"The timezone is always zero UTC offset" for the method toISOString() , so when hours its between 0:00 and 0:59, there is one day missmatch in the comparison.

**Comment by fzaninotto** [comment]
Yes, we're aware about this one and we chose to live with it. Dealing with timezones is a PITA (especially when the continuous integration server and the developer servers are in different timezones). Feel free to open a PR if you have a robust fix.
