### ISSUE TITLE
Make install error

### ISSUE THREAD

**Issue by bahman2216** [marmelab/react-admin#2705]
Im using linux mint 19 and install fresh react-admin, But got below error:

```
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
Makefile:7: recipe for target 'install' failed
make: *** [install] Error 
```

**Comment by fzaninotto** [comment]
Can't reproduce the issue. I think it's a problem with your `yarn` version, see https://github.com/yarnpkg/yarn/issues/2821.

**Comment by bahman2216** [comment]
Yes you right, Thanks to save my time.
