### ISSUE TITLE
CRUD request will never fire when browser tab is switched away before "undo" notification goes away

### ISSUE THREAD

**Issue by normanzb** [marmelab/react-admin#2721]
**What you were expecting:**
With undoable is enabled in edit view, the request of edit should be fired after 6 secs even when the tab is inactive (.

**What happened instead:**
The request of edit never gets fired unless the tab is active.

**Steps to reproduce:**

1. Enable undoable for  `<Edit />`
2. In Edit view, change the and submit the data,
3. Switch to the other browser tab, make browser tab of react-admin tool inactive

The request of edit should be fired after 6 secs even when the tab is inactive.

**Other information:**
The "undo" feature seems relies on the event of disappearance of notification message to fire the crud request.
However the hiding of notification message seems rely on something to do with `requestanimationframe`.
So if you switch away the tab immediately after data editing, the request for actually updating the data will never be fired.

**Environment**

* React-admin version: 2.5.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.4.2
* Browser: Chrome 70.0.3538.110
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
related to #1857
