### ISSUE TITLE
HttpError

### ISSUE THREAD

**Issue by vasylpb** [marmelab/react-admin#2723]
Hi! In my AuthProvider file in case AUTH_ERROR i get status error, but i need also check headers response, when i get information about expired token. Can you add in HttpError class parameter 'headers',  which will provide the necessary information ?
https://www.blinkingcaret.com/2018/05/30/refresh-tokens-in-asp-net-core-web-api/

**Comment by fzaninotto** [comment]
Hi @vasylpb, and thanks for your suggestion!

We don't need this feature ourselves so we won't implement it. But feel free to implement it in a fork and send us a PR to have it merged to the core.

**Comment by davidhenley** [comment]
@vasylpb @fzaninotto are you still open for a PR? 

This should be easy to add headers or a bool to check the WWW-Authenticate response header for RFC 6750 Token Expired

**Comment by fzaninotto** [comment]
Sure, we're always open for a PR.
