### ISSUE TITLE
Factoring SanitizeRestProps

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#2727]
There is 31 sanitizeRestProps functions defined.

I think these 31 functions could be categorized, to reduce there numbers. for exemple : by actions, inputs, layout, ... 

Advantages:

- increase the consistencies of the contents of theses functions
- implements these functions in a dedicated js files, enhancing the visibility of the code

Jacques

**Comment by fzaninotto** [comment]
Please use the Issue template to describe the actual problem you have. If you did, you'd see that there is no actual problem with `sanitizeRestProps`.
