### ISSUE TITLE
Ability to trigger filter search explicitly with a button

### ISSUE THREAD

**Issue by hatim-oss** [marmelab/react-admin#2729]
I am trying to build a simple search functionality for a resource using filters. The search works fine using `<SearchInput>`  but it reacts to every keypress. Such unnecessary searches (where the user is typing and is not done with the query) can cause performance degradation at the back end

It should be possible to trigger search explicitly (ie a search Button) that does the same thing that searchInput `onChange` is currently doing.

**Comment by fzaninotto** [comment]
As we can't support all types of interactions, we chose not to support that it in the core. However, you can write a custom `Filter` component to support this behavior. 

As a side note, the current `Filter` component doesn't send one request every keystroke: it uses a debounce filter.

**Comment by ngocketit** [comment]
I also have a need for this. @hatim-oss Have you found any workaround yet? @fzaninotto Does that mean reimplementing the `FilterForm` as well?

**Comment by ngocketit** [comment]
I find that without a possibility to do the search only when you press enter is annoying. In our case, we have very huge dataset of millions of records and we don't want to show the list with any items until somebody provides the search keyword and presses enter. Now, every time one is typing something, it'll make a request to server and it could be very costly this way for a huge dataset. I tried to implement a custom `Filter` that supports search on enter only but it looks like it's very hackish (I had to copy & paste code from the core and modify accordingly). It'd be very beneficial if the framework can support this. Otherwise, I think it won't scale. @fzaninotto What do you think?

**Comment by fzaninotto** [comment]
@ngocketit I disagree. React-admin provides one way to do filtering and allows you to pass your own Filter component if the default doesn't fit you. We can't handle all use cases (and we don't want to, because we have limited resources to spend in this project). 

But I'm sure your use case is common enough that you can release your custom filter as a standalone package and have your own set of contributors. I encourage you to do it!

**Comment by ngocketit** [comment]
@fzaninotto I think the default filter is already very good that we don't want to drop it completely, but only add the possibility to do the filter only on enter. However, I think it's pretty weird to have a separate project just for adding that possibility on the already existing filter, not to mention that I'll need to keep it in sync with any potential changes upstream.

**Comment by ccdredzik** [comment]
Wow. I guess my Elasticsearch will go fsck itself with the amount of requests. Bravo to whoever thought this is a good idea.

**Comment by mohamedshahid** [comment]
@fzaninotto or anyone now we have any idea how set a apply button on filters so filter query get's call only when press the apply button

**Comment by patriksimurka** [comment]
@ngocketit Could you share the code of the custom filter please?

**Comment by akmennon** [comment]
I've made a custom filter if anyone needs it.

`import { Field } from 'react-final-form';
import TextField from '@mui/material/TextField';

const SearchInput = (prop) => {
    const [value,setValue] = useState('')

    return (
        <span>
            <Field name="Query">
            {props => (
                <div>
                <TextField
                    name={props.input.name}
                    value={value}
                    onChange={(ev)=>{ev.persist();setValue(ev.target.value)}}
                    onKeyPress={(e)=>{e.persist();
                        if(e.key==='Enter'){
                            props.input.onChange(value)
                        }
                        else{
                            return null
                        }
                    }}
                />
                </div>
            )}
            </Field>
        </span>
    )
}`

The above is the component, make changes as needed for the ui. Then, the filter which should be used for the list would be as below.

`const MyFilter = (props) => (
    <Filter {...props}>
        <SearchInput source="Query" alwaysOn />
    </Filter>
);`

**Comment by djhi** [comment]
https://marmelab.com/react-admin/List.html#building-a-custom-filter

**Comment by patriksimurka** [comment]
In the meantime I made one similar to the default RA one, the only real difference being user must click on "filter" or press enter to trigger search. Here it is, maybe it helps someone: 

```
import {Box, FormControl, Menu, MenuItem} from '@material-ui/core'
import {makeStyles} from '@material-ui/core/styles'
import CancelOutlinedIcon from '@material-ui/icons/CancelOutlined'
import lodashGet from 'lodash/get'
import {useCallback, useState} from 'react'
import {Button, useListContext} from 'react-admin'
import {Form} from 'react-final-form'

const useStyles = makeStyles({
  customFilter: {
    display: 'flex',
    marginRight: 10,
    marginTop: 'auto',
  },
  cancelIcon: {
    '&:hover': {
      transform: 'scale(1.3)',
    },
    marginRight: 10,
    marginBottom: -20,
  },
})

export const CustomFilter = ({children: filters, context}) => {
  const {filterValues, setFilters, hideFilter, displayedFilters, showFilter} = useListContext()
  const classes = useStyles()
  const [anchorEl, setAnchorEl] = useState(null)
  const open = !!anchorEl

  const hiddenFilters = filters.filter(
    (filterElement) =>
      !filterElement.props?.alwaysOn &&
      !displayedFilters?.[filterElement.props?.source] &&
      typeof lodashGet(filterValues, filterElement.props?.source) === 'undefined',
  )

  const onSubmit = useCallback(
    (values) => {
      if (Object.keys(values).length > 0) {
        setFilters(values, '')
      } else {
        setFilters({}, [])
      }
    },
    [setFilters],
  )

  const handleClick = useCallback((event) => {
    setAnchorEl(event.currentTarget)
  }, [])

  const handleClose = useCallback(
    (key) => {
      setAnchorEl(null)
      showFilter(key, '')
    },
    [showFilter],
  )

  const onCancelIconClick = useCallback(
    (key) => {
      hideFilter(key)
    },
    [hideFilter],
  )

  const CancelIcon = () => {
    return <CancelOutlinedIcon className={classes.cancelIcon} />
  }

  const renderForm = () => (
    <div>
      <Form onSubmit={onSubmit} initialValues={filterValues}>
        {({handleSubmit}) => (
          <form id="filter-form" onSubmit={handleSubmit}>
            <Box display="flex" flexWrap="wrap" mb={1}>
              {filters.map(
                (filterElement) =>
                  (filterElement.props?.alwaysOn || displayedFilters?.[filterElement.props?.source]) && (
                    <Box className={classes.customFilter} key={filterElement.key}>
                      {!filterElement.props?.alwaysOn && (
                        <Box
                          onClick={() => {
                            onCancelIconClick(filterElement.props?.source)
                          }}
                        >
                          <CancelIcon />
                        </Box>
                      )}
                      {filterElement}
                    </Box>
                  ),
              )}
            </Box>
          </form>
        )}
      </Form>
    </div>
  )

  const renderButton = () => (
    <FormControl variant="filled">
      <Button label="Pridaj filter" onClick={handleClick} disabled={hiddenFilters.length === 0} />
      <Menu open={open} anchorEl={anchorEl} onClose={() => handleClose(null)}>
        {hiddenFilters.map((filterElement) => (
          <MenuItem
            key={filterElement.props?.source}
            value={filterElement.props?.source}
            onClick={() => handleClose(filterElement.props?.source)}
          >
            {filterElement.props?.label}
          </MenuItem>
        ))}
      </Menu>
    </FormControl>
  )

  return context === 'button' ? renderButton() : renderForm()
}
```

**Comment by patriksimurka** [comment]
In the meantime I made one similar to the default RA one, the only real difference being user must click on "filter" or press enter to trigger search. Here it is, maybe it helps someone: 

```
import {Box, FormControl, Menu, MenuItem} from '@material-ui/core'
import {makeStyles} from '@material-ui/core/styles'
import CancelOutlinedIcon from '@material-ui/icons/CancelOutlined'
import lodashGet from 'lodash/get'
import {useCallback, useState} from 'react'
import {Button, useListContext} from 'react-admin'
import {Form} from 'react-final-form'

const useStyles = makeStyles({
  customFilter: {
    display: 'flex',
    marginRight: 10,
    marginTop: 'auto',
  },
  cancelIcon: {
    '&:hover': {
      transform: 'scale(1.3)',
    },
    marginRight: 10,
    marginBottom: -20,
  },
})

export const CustomFilter = ({children: filters, context}) => {
  const {filterValues, setFilters, hideFilter, displayedFilters, showFilter} = useListContext()
  const classes = useStyles()
  const [anchorEl, setAnchorEl] = useState(null)
  const open = !!anchorEl

  const hiddenFilters = filters.filter(
    (filterElement) =>
      !filterElement.props?.alwaysOn &&
      !displayedFilters?.[filterElement.props?.source] &&
      typeof lodashGet(filterValues, filterElement.props?.source) === 'undefined',
  )

  const onSubmit = useCallback(
    (values) => {
      if (Object.keys(values).length > 0) {
        setFilters(values, '')
      } else {
        setFilters({}, [])
      }
    },
    [setFilters],
  )

  const handleClick = useCallback((event) => {
    setAnchorEl(event.currentTarget)
  }, [])

  const handleClose = useCallback(
    (key) => {
      setAnchorEl(null)
      showFilter(key, '')
    },
    [showFilter],
  )

  const onCancelIconClick = useCallback(
    (key) => {
      hideFilter(key)
    },
    [hideFilter],
  )

  const CancelIcon = () => {
    return <CancelOutlinedIcon className={classes.cancelIcon} />
  }

  const renderForm = () => (
    <div>
      <Form onSubmit={onSubmit} initialValues={filterValues}>
        {({handleSubmit}) => (
          <form id="filter-form" onSubmit={handleSubmit}>
            <Box display="flex" flexWrap="wrap" mb={1}>
              {filters.map(
                (filterElement) =>
                  (filterElement.props?.alwaysOn || displayedFilters?.[filterElement.props?.source]) && (
                    <Box className={classes.customFilter} key={filterElement.key}>
                      {!filterElement.props?.alwaysOn && (
                        <Box
                          onClick={() => {
                            onCancelIconClick(filterElement.props?.source)
                          }}
                        >
                          <CancelIcon />
                        </Box>
                      )}
                      {filterElement}
                    </Box>
                  ),
              )}
            </Box>
          </form>
        )}
      </Form>
    </div>
  )

  const renderButton = () => (
    <FormControl variant="filled">
      <Button label="Pridaj filter" onClick={handleClick} disabled={hiddenFilters.length === 0} />
      <Menu open={open} anchorEl={anchorEl} onClose={() => handleClose(null)}>
        {hiddenFilters.map((filterElement) => (
          <MenuItem
            key={filterElement.props?.source}
            value={filterElement.props?.source}
            onClick={() => handleClose(filterElement.props?.source)}
          >
            {filterElement.props?.label}
          </MenuItem>
        ))}
      </Menu>
    </FormControl>
  )

  return context === 'button' ? renderButton() : renderForm()
}
```

**Comment by jeanpimentel** [comment]
A huge workaround just to add a simple [submit] button. It doesn't make sense.

**Comment by sebastianbuechler** [comment]
> As we can't support all types of interactions, we chose not to support that it in the core. However, you can write a custom `Filter` component to support this behavior.
> 
> As a side note, the current `Filter` component doesn't send one request every keystroke: it uses a debounce filter.

Is the debounce duration customizable?

**Comment by dk-civictech** [comment]
https://marmelab.com/react-admin/FilteringTutorial.html#building-a-custom-filter

**Comment by klen** [comment]
another search filter component which one works by enter key or blur event:

```js
import SearchIcon from "@mui/icons-material/Search"
import { InputAdornment } from "@mui/material"
import clsx from "clsx"
import debounce from "lodash/debounce"
import { useTranslate } from "ra-core"
import { useState } from "react"
import { ResettableTextField, SearchInputProps, useInput, useResourceContext } from "react-admin"

export function SearchFilter({ source, className, ...props }: SearchInputProps) {
  const translate = useTranslate()
  const { field } = useInput({ source, ...props })
  const [searchValue, setSearchValue] = useState(field.value || "")
  const resource = useResourceContext()

  const onBlur = () => field.onChange(searchValue)
  const label = translate(`resources.${resource}.fields.${source}`)

  return (
    <ResettableTextField
      resettable
      ref={field.ref}
      value={searchValue}
      onBlur={debounce(onBlur, 500)}
      onChange={(e) => setSearchValue(e.target?.value || e)}
      onKeyUp={(e) => {
        if (e.key === "Enter") field.onChange(searchValue)
      }}
      placeholder={label}
      {...props}
      className={clsx("ra-input", `ra-input-${source}`, className)}
      InputProps={{
        endAdornment: (
          <InputAdornment position="end">
            <SearchIcon color="disabled" />
          </InputAdornment>
        ),
      }}
    />
  )
}

```
