### ISSUE TITLE
Cannot add default value to a compound field

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2734]
Hello, 
I encountered a bug. It is not possible to assign a default value to a filter that has a compound name (More precisely, the value is not displayed in the input but is well applied). Also, the filter does not appear when you return to the page but it is still active.

**Related code:**
```js
<Filter {...props}>
    <TextInput
      source="like_unit.title"
      defaultValue="Qui tempore rerum et voluptates"
    />
</Filter>
```
* CodeSandbox (https://codesandbox.io/s/k3lq8j87v5): show PostList.js

**Environment**

* React-admin version: 2.5.3
* React version: 16.7.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Reproduced and confirmed, thanks for the sandbox.

**Comment by bitlab-code** [comment]
News about the fix?
Thanks.
