### ISSUE TITLE
Dynamic TabbedForm isn't supported

### ISSUE THREAD

**Issue by Davideconsonni94** [marmelab/react-admin#2735]
If I try to modify the TabbedForm once instantiated, inserting a new FormTab using FormDataConsumer does not render the new tab correctly, but inserting all the elements of the tab not inserted on the current tab. 
the source code is:

```
> <TabbedForm>
> <FormDataConsumer>
> { ({formData}) => formData && 
>   <FormTab label = "myformtab"></FormTab>
> }
> <FormDataConsumer>
> </TabbedForm>
```

**Comment by Davideconsonni94** [comment]
<TabbedForm>
            <FormDataConsumer>
                {({ formData }) => formData && formData.promoType && formData.promoType.includes("AGGREGATE") &&
                    <FormTab label="Multiprodotto">
                        <FormDataConsumer>
                            {({ formData }) => formData &&
                                <FormMultiProdotto formData={formData} />
                            }
                        </FormDataConsumer>
                    </FormTab>
                }
            </FormDataConsumer>


        </TabbedForm>

**Comment by Davideconsonni94** [comment]
`
<TabbedForm>
            <FormDataConsumer>
                {({ formData }) => formData && formData.promoType && formData.promoType.includes("AGGREGATE") &&
                    <FormTab label="Multiprodotto">
                        <FormDataConsumer>
                            {({ formData }) => formData &&
                                <FormMultiProdotto formData={formData} />
                            }
                        </FormDataConsumer>
                    </FormTab>
                }
            </FormDataConsumer>


        </TabbedForm>`

**Comment by Davideconsonni94** [comment]
`
            <FormDataConsumer>
                {({ formData }) => formData && formData.promoType && formData.promoType.includes("AGGREGATE") &&
                    <FormTab label="Multiprodotto">
                        <FormDataConsumer>
                            {({ formData }) => formData &&
                                <FormMultiProdotto formData={formData} />
                            }
                        </FormDataConsumer>
                    </FormTab>
                }
            </FormDataConsumer>


        </TabbedForm>`

**Comment by fzaninotto** [comment]
You should definitely use the Issue template so that we have a chance to understand what you're trying to achieve, what errors you have, and what platform you use. 

From what I understand, what you are trying to achieve isn't supported by `TabbedForm`. Try writing your own Form component for use inside Edit.
