### ISSUE TITLE
Choose the default order value for sorting

### ISSUE THREAD

**Issue by frankPairs** [marmelab/react-admin#2736]
**Is your feature request related to a problem? Please describe.**
I need to be able to sort descending by default. The problem is ra-core automatically assign the ASC value to sort.order when the sort.field changes.

**Describe the solution you'd like**
I would like to be able to to define this default value. For example, I want to assign DESC value to sort.order when sort.field changes.

**Comment by fzaninotto** [comment]
The default value is set in the [queryReducer](https://github.com/marmelab/react-admin/blob/d147689d9b4a0e21aacc62114ebdabbb6f63eb80/packages/ra-core/src/reducer/admin/resource/list/queryReducer.js#L30). To override it, a user should extend `ListController` and override the `changeParams` method to use their own `queryReducer`... Or write an entirely new `ListController`. Not easy.

I agree that this could be made easier. But I'm not sure this is a common need.

Can you explain your use case a bit more? Which type of data should be ordered DESC by default ?

**Comment by frankPairs** [comment]
@fzaninotto thanks for the quick response.

Yes, I saw that this value is setted in the queryReducer.

The use case is:

I have a list of users with a created at and updated at values. 

By default, I have the list ordered by **updated at** DESC via List sort property because we want to show the latests updated users.

When  the user clicks to order by created at, now the library is ordering by **created at** ASC so we are showing the first created users. 

We want to continue showing the latest users.

Yeah, it is not maybe a common need but I think that would be nice to keep the default order setted in the List sort property also when the sort.field changes.

**Comment by fzaninotto** [comment]
I guess we could change the queryReducer to accept not only a field, but also a direction. That way, it's up to the List (and you can override the DatagridHeaderCell for that) to decide in which direction the sort should go.

I'm marking this as an enhancement. As we don't need it ourselves, we won't implement it in the near future. Feel free to open a PR to add this feature though.

**Comment by fzaninotto** [comment]
Fixed by #4518
