### ISSUE TITLE
SelectField not getting displayed

### ISSUE THREAD

**Issue by NBALAJI95** [marmelab/react-admin#2737]
SelectField alone is not getting rendered. Tried consoling. Got the output below.
Kindly fix this bug. 

{$$typeof: Symbol(react.element), type: ƒ, key: "network", ref: null, props: {…}, …}
$$typeof: Symbol(react.element)
key: "network"
props: {source: "network", choices: Array(3), addLabel: true}
ref: null
type: ƒ ShouldUpdate()
defaultProps: {addLabel: true}
displayName: "pure(translate(SelectField))"
arguments: (...)
caller: (...)
length: 0
name: "ShouldUpdate"
prototype: Component {shouldComponentUpdate: ƒ, render: ƒ, constructor: ƒ}
__proto__: ƒ Component(props, context, updater)
[[FunctionLocation]]: shouldUpdate.js:58
[[Scopes]]: Scopes[5]
_owner: FiberNode {tag: 0, key: null, elementType: ƒ, type: ƒ, stateNode: null, …}
_store: {validated: false}
_self: null
_source: {fileName: "C:\Users\*****\Desktop\Admin\bug-fix\admin\src\TPUsers.js", lineNumber: 50}
__proto__: Object

**Comment by fzaninotto** [comment]
Can you please update your issue to use the issue template?

**Comment by createdbyken** [comment]
This is indeed right. selectInput does work.
