### ISSUE TITLE
How to debug the failed to fetch error in reach-admin app

### ISSUE THREAD

**Issue by gillijay** [marmelab/react-admin#2743]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(http://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.

https://stackoverflow.com/questions/54064757/how-to-debug-failed-to-fetch-in-react-admin-app

**Comment by fzaninotto** [comment]
So you've obviously read the issue template, but for any reason you chose to ignore it. As expected, we'll also ignore your question.
