### ISSUE TITLE
[v2.5.3] datagrid doesn't support the expand prop

### ISSUE THREAD

**Issue by shawnchen1980** [marmelab/react-admin#2745]
I just npm installed the package. Its version is v2.5.3. The **_expand_** prop of **_Datagrid_** doesn't work. So I checked the source code and found this:

```
 render() {
        const {
            basePath,
            body,
            children,
            classes,
            className,
            currentSort,
            data,
            hasBulkActions,
            hover,
            ids,
            isLoading,
            onSelect,
            onToggleItem,
            resource,
            rowClick,
            rowStyle,
            selectedIds,
            setSort,
            total,
            version,
            ...rest
        } = this.props;
```
There is no **_expand_** there.  So the npm's version is not updated yet to support expandable grid row?

**Comment by djhi** [comment]
That's because it's in the version [`2.6`](https://github.com/marmelab/react-admin/releases/tag/v2.6.0) which has been published two days ago. See https://www.npmjs.com/package/react-admin
