### ISSUE TITLE
add default .env file at examples\demo

### ISSUE THREAD

**Issue by reutopiaer** [marmelab/react-admin#2755]
**Is your feature request related to a problem? Please describe.**
``` js
//  Unhandled Rejection (Error): Unknow dataProvider type undefined
this.restoreFetch = await fakeServerFactory(
           process.env.REACT_APP_DATA_PROVIDER
);
```
**Describe the solution you'd like**
process.env.REACT_APP_DATA_PROVIDER is undefind by default
add default .env file to set REACT_APP_DATA_PROVIDER(rest or graphql)
**Describe alternatives you've considered**
set default type at src/fakeServer/index.js
``` js
export default (type = 'rest') => {
    switch (type) {
        case 'rest':
            return import('./rest').then(factory => factory.default());

        case 'graphql':
            return import('./graphql').then(factory => factory.default());

        default:
            throw new Error(`Unknow dataProvider type ${type}`);
    }
};
```

**Additional context**

**Comment by djhi** [comment]
You should use either the makefile commands or the yarn commands, both at the project root
