### ISSUE TITLE
Graphql version breaks webpack bundeling

### ISSUE THREAD

**Issue by dsinai14** [marmelab/react-admin#2761]
See the following issue:
When using graphql 0.13.2 as a dependency, it breaks the webpack bundeling and throw an error, for example when running with the new create-react-app.

An upgrasde to  graphql@^14.0.2 should solve this problem

[Runtime Error "require is not defined" when bundling with webpack](https://github.com/graphql/graphiql/issues/721)

**Comment by djhi** [comment]
Fixed by #2993
