### ISSUE TITLE
Support row expansion on DataGrid row-click

### ISSUE THREAD

**Issue by kdabir** [marmelab/react-admin#2765]
**Is your feature request related to a problem? Please describe.**
Currently, `rowClick` supports `show|edit` as possible action on click of `DataGrid` row.

**Describe the solution you'd like**
Please consider supporting additional option value `expand` which is will expand the row.

`<Datagrid rowClick="expand" expand={<GroupExpansion/>}>`
	
**Additional context**
Row Expansion was a feature introduced in 2.6.

**Comment by fzaninotto** [comment]
It turns out we do need it now ;)

**Comment by fzaninotto** [comment]
Fixed by #2820
