### ISSUE TITLE
Add the availability to populate the choices of an AutocompleteInput from cached items

### ISSUE THREAD

**Issue by sorcer1** [marmelab/react-admin#2766]
Hello,

The AutocompleteInput  decorate with ReferenceInput  is very very good when the choices are less than 100 items.
But when it's needed to populate it with a very large array, it will be usefull to call it's own function to populate it and use session/local storage for better performances.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. In the case you describe, I don't see the interest of the user to have thousands of results at each keystroke. And if the possible records come from another resource, you should use AutocompleteInput as a child of ReferenceInput.

If you can't do that, then you probably have a very specific need, and you'll have to develop a custom component to replace AutocompleteInput. We won't do it in core, as I believe it's a corner case. but if your component is reusable, please publish it as a standalone package!
