### ISSUE TITLE
The list of related resource records is updated only after closing the Create form.

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#2770]
I use the form Create a child resource with the button <SaveButton redirect = {false}>
to create multiple entries without closing the form.

Values ​​in state: references -> oneToMany -> childRes@parentRes -> ids / total
updated only! after exiting the Create form.

React-admin version: 2.6.1
React version: 16.5.2
Browser: Chrome 71.0.3578.98

**Comment by fzaninotto** [comment]
Hi @MaxAlex666,

I don't understand your issue. Can you please create a CodeSandbox and explain the step-by-step scenario to reproduce the issue? And please use the issue template: we wrote it to have as much details as possible to understand and fix bugs.

**Comment by fzaninotto** [comment]
No news for some time, closing.
