### ISSUE TITLE
Enable Print feature

### ISSUE THREAD

**Issue by shahingazi** [marmelab/react-admin#2772]
It would be really good if it can print all order list or specific order from the list.

**Comment by fzaninotto** [comment]
what's an order list?

**Comment by shahingazi** [comment]
![image](https://user-images.githubusercontent.com/6483131/51316817-126aa780-1a56-11e9-8bfb-84ffdb859f07.png)

![image](https://user-images.githubusercontent.com/6483131/51316901-578ed980-1a56-11e9-90d8-f10b2be06af3.png)

so admin can print out order list, a specific order, invoice, purchase order so on. Any list or item could possible to print by using the print feature.

**Comment by shahingazi** [comment]
forgot to say thank you for your reply :)

**Comment by fzaninotto** [comment]
There are three ways you could address that need:

- The button may open a new window on a custom route with no app bar or sidebar. If that' so, I'ts outside the perimeter of react-admin, and you'll have to develop that route on your own.
- the button may trigger a `window.print`. this is so simple that I don't see the purpose of adding a button for that in the library.
- You might want custom styles for the print media. Material ui already handles this, and any modification in the print style should be done in the material-ui project - unless the styles come from react-admin, in which case I invite you to open a specific PR.

So all in all, I don't see the point of adding anything special in react-admin to support the Print feature.

**Comment by strarsis** [comment]
Some feature proposal here: Adding a default print stylesheet to react-admin that hides navigation UI elements, reduces background colors, improves text/readability for printing.

**Comment by fzaninotto** [comment]
Nice idea, feel free to open a PR for it!
