### ISSUE TITLE
ra-data-graphql-simple UPDATE_MANY incorrect build variable {data}

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#2776]
**What you were expecting:**
When creating the BulkArchiveButton, I expected correct execution mutation

**What happened instead:**
UPDATE_MANY a few times causes the execution of the UPDATE
the required ID argument is not passed to the {data} parameter

**Steps to reproduce:**
try to update any resource through the CustomBulkActionButton

**Other information:**
Wrote the BulkArchiveButton as in the example in the documentation:

```
class BulkArchiveButton extends Component {
    handleArchive = () => {
        const {  basePath, resource, selectedIds, startUndoable } = this.props;
        startUndoable(
            crudUpdateMany(resource, selectedIds, { isArchved: true }, basePath)
        );
    };
    render() {
        const { className, classes, filterValues } = this.props;
        return (
            <Button 
                size="small"
                variant="outlined"
                label="raExt.action.archive"
                onClick={this.handleArchive}
                className={`${classes.button} ${classes.archiveButton} ${className}`}
            >
                <ArchiveIcon />
            </Button>
        );
    }
}
```

This is the request this button sends:
![default](https://user-images.githubusercontent.com/28799755/51303684-25c24680-1a47-11e9-933c-4ff4420a2b27.PNG)

That's what gets a response:
![default](https://user-images.githubusercontent.com/28799755/51303716-425e7e80-1a47-11e9-9f2a-4e2b13d85e06.PNG)

To solve the problem fixed 

> C:\...\ui-react-admin\node_modules\ra-data-graphql-simple\esm\index.js

```
...
               if (fetchType === UPDATE_MANY) {
                var ids = params.ids, otherParams_2 = __rest(params, ["ids"]);
                return Promise.all(params.ids.map(function (id) {
                    
                 //return defaultDataProvider(UPDATE, resource, __assign({ id: id }, otherParams_2));
                    return defaultDataProvider(UPDATE, resource, {data:__assign({ id: id }, otherParams_2.data)});

                })).then(function (results) {
                    var data = results.reduce(function (acc, _a) {
                        var data = _a.data;
                        return acc.concat([data.id]);
                    }, []);
                    return { data: data };
                });
            }
...
```
Please, fix for next release.
**Environment**

* React-admin version: 2.6.0

**Comment by fzaninotto** [comment]
ping @djhi

**Comment by djhi** [comment]
Can you make a PR to fix this ?
