### ISSUE TITLE
[FR] Support changing the params passed to actions

### ISSUE THREAD

**Issue by ngocketit** [marmelab/react-admin#2779]
Hi,

First of all, thank you for the work, it's amazing to use! I have one use case where I use DynamoDB for the database and the primary key consists of a hash key (type) and sort key (id). Now, when I want to get one item to show on the show/edit form, it's passing only the sort key (id), which makes it difficult to query the item on DynamoDB. Of course I can use something like global secondary index for that but I think it'd be more flexible to allow changing the `params` which is passed to `GET_ONE` (and the others) so that we can have a more flexible way of querying the item (in my case, I'd need both hash key & sort key). Thanks!

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback, we appreciate!

We won't do what you ask, because there is already a way to do that: modify your data provider to create a composite id for every resource (concatenating type and id).

That sort of mapping logic lives in the data provider, so there is nothing to change in react-admin.

**Comment by ngocketit** [comment]
Thanks for your comment! I actually tried and it won't work in my case as I'm using AWS Appsync. I can concatenate the `id` and `type` as the new id and send that to Appsync but there is no way in VTL to split that string back to `id` and `type`. This is only one example but I can see that it's not very flexible.

**Comment by fzaninotto** [comment]
To troubleshoot your app, I suggest you head to StackOverflow. We don't provide support via github issues.
