### ISSUE TITLE
DataGrid Proptype mitake?

### ISSUE THREAD

**Issue by santaclauze** [marmelab/react-admin#2793]
react-admin 2.6.0

It seems that the Props types of Datagrid has a mistake.

```
Datagrid.propTypes = {
...
    currentSort: PropTypes.shape({
        sort: PropTypes.string,
        order: PropTypes.string,
    }).isRequired,
...
}
```

However if I log `this.props`, I have currentSort: {**_field_**: "id", order: "DESC"}. See how it contains **_field_** and not **_sort_**.

In some resources I also get a warning: `Warning: Failed prop type: The prop `currentSort` is marked as required in `Datagrid`, but its value is undefined.`

I suggest a PR with :
```
Datagrid.propTypes = {
...
    currentSort: PropTypes.shape({
        field: PropTypes.string,
        order: PropTypes.string,
    }).isRequired,
...
}
...
Datagrid.defaultProps = {
  currentSort: {},
};

```

**Comment by djhi** [comment]
Thanks for reporting! Can you make a PR fixing the proptypes names, removing the `isRequired` on it but leaving the default as it is?

**Comment by santaclauze** [comment]
rdy. Closing
