### ISSUE TITLE
Translation ra.action.confirm not available

### ISSUE THREAD

**Issue by despatates** [marmelab/react-admin#2800]
**What you were expecting:**

I want to use translated token `ra.action.confirm` as button label.

**What happened instead:**

Translation of token `ra.action.confirm` is not available in `ra-language-english` nor `ra-language-french`.

![image](https://user-images.githubusercontent.com/3403829/51547527-cd37e280-1e66-11e9-85cd-833452e367f2.png)

**Steps to reproduce:**

```jsx
<Button onClick={this.handleClickConfirm}>
        {translate('ra.action.confirm', { _: 'ra.action.confirm' })}
</Button>
```

**Related code:**

When I look into available tokens
```jsx
import french from 'ra-language-french';
console.log(french);
```
I see that `confirm` key is not in the `action` list.

![image](https://user-images.githubusercontent.com/3403829/51547240-2c492780-1e66-11e9-95ff-5e862efddb41.png)

Maybe is this because `confirm` is a reserved keyword in JS ? 
But what about `delete` and `export`? They are reserved keywords too and they are available.

**Other information:**

**Environment**

* React-admin version: v2.6.1
* Last version that did not exhibit the issue (if applicable): unknown
* React version: 16.7.0
* Browser: Chrome 71.0.3578.98
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
I think you haven't updated the language packages to their last version. Can you check and confirm?

**Comment by despatates** [comment]
Confirmed.
The version was correct in `package.json` but not in `node_modules`.
Deleting file `package-lock.json` and running `npm install` to generate a new one solved the problem.

Thanks for your help!
