### ISSUE TITLE
Responsive doesn't work well for IE

### ISSUE THREAD

**Issue by guoyibj** [marmelab/react-admin#2803]
Bug: Comment doesn't word wrap for IE in mobile mode.
code: examples/demo/src/reviews/index.js

Snapshot in Chrome:
<img width="402" alt="chrome" src="https://user-images.githubusercontent.com/35130561/51588069-f0719900-1f1d-11e9-8b7b-63a83561a9d2.png">

Snapshot in IE:
![ie](https://user-images.githubusercontent.com/35130561/51588081-fa939780-1f1d-11e9-95e7-c7417ecf0e13.png)

**Comment by fzaninotto** [comment]
Hi,

And thanks for your feedback. I suggest you open an issue in the marmelab/react-admin-demo repository - this isn't an issue with react-admin.

**Comment by guoyibj** [comment]
I open an issue in the marmelab/react-admin-demo repository: 
https://github.com/marmelab/react-admin-demo/issues/4
