### ISSUE TITLE
Edit component inside datagrid expansion explicitly requires location property

### ISSUE THREAD

**Issue by kdabir** [marmelab/react-admin#2804]
When placed an `Edit` component inside Datagrid's `expand` as per the example

```
const MyExpansion = props => (
    <Edit {...props} title=" " >
...
```

```
<Datagrid rowStyle={rowStyle} expand={<MyExpansion/>}>
...
```
I get the following error:

```
Uncaught Error: <Edit> component is not properly configured, some essential props are missing.
Be sure to pass the props from the parent. Example:

const MyEdit = props => (
    <Edit {...props}></Edit>
);

The missing props are: location
    at checkMinimumRequiredProps.js:28
```

This goes away if I add `location` prop as follows:
```
<Edit {...props} title=" "  location={props.location}>
```

The documentation does not mention this, so either this is a bug or docs should be updated (about having to pass location object explicitly).

**Environment**

* React-admin version: ^2.6.2
* Last version that did not exhibit the issue (if applicable): ^2.6.0
* React version: ^16.7.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for the bug report. It's a mistake in EditController, I don't think that `location` is required.
