### ISSUE TITLE
duplicated nested field with Edit

### ISSUE THREAD

**Issue by gv-beemining** [marmelab/react-admin#2807]
**What you were expecting:**

Im trying to  Edit  the current record  with nested values  for example:
```

{ id: '77',
  value: { user: 'aaa', password: 'bbb' } }
```

**What happened instead:**

I am actually getting a duplicated object with the values character by character like this:

```
{
  "0": "{",
  "1": "\"",
  "2": "u",
  "3": "s",
  "4": "e",
  "5": "r",
  "6": "\"",
  "7": ":",
  "8": "\"",
  "9": "a",
  "10": "a",
  "11": "a",
  "12": "\"",
  "13": ",",
  "14": "\"",
  "15": "p",
  "16": "a",
  "17": "s",
  "18": "s",
  "19": "w",
  "20": "o",
  "21": "r",
  "22": "d",
  "23": "\"",
  "24": ":",
  "25": "\"",
  "26": "b",
  "27": "b",
  "28": "b",
  "29": "\"",
  "30": "}",
  "user": "aaa",
  "password": "bbb"
}

```
**Steps to reproduce:**

Create a record with a nested object and in the edit form the fields

    <TextInput source="value.user"/> 
    <TextInput source="value.password" /> 

if i reload the "Edit page" the response is normal as expected 
```

 {id: '77',
  value: { user: 'aaa', password: 'bbb' } }
```

**Related code:**

```
insert short code snippets here
```
Request before reloading the edit page (duplicated object)

![error1](https://user-images.githubusercontent.com/42183215/51689540-a5b35800-1fd5-11e9-956e-603a6d48f49f.png)

Request after realoading the edit page (everything ok)

![error2](https://user-images.githubusercontent.com/42183215/51689551-ac41cf80-1fd5-11e9-96f1-3ea6c0d23637.png)

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/vvw21793w0)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
I tried to replicate your issue but I couldn't (see https://codesandbox.io/s/4zx2z5z5w4). Maybe you use an outdated version of react-admin? We'd know if you filled the issue template.
