### ISSUE TITLE
Docs mention Admin.messages prop that doesn't seem to work.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#2808]
**What you were expecting:**
Based on [mention of a messages prop](https://marmelab.com/react-admin/Admin.html#internationalization), I expected to be able to pass a `messages` object prop to the `Admin` component and then be able to use the `showNotification` action without receiving warnings about missing translations.

I'm guessing that things have changed and the docs haven't been updated.

**What happened instead:**
Instead, I had to implement `i18nProvider`.

**Steps to reproduce:**
`<Admin messages={{en: { mymessages: { hello: 'Hi!' } } }} > ... </Admin>`
...
`showNotification('mymessages.hello');`

**Environment**

* React-admin version: 2.6.1
* React version: 16.7.0

**Comment by waynebloss** [comment]
I'm guessing that doc was left there as a note for people looking for that property from a previous version.

Implementing the `i18nProvider` is no big deal, I just thought maybe `messages` was a shortcut for merging some custom messages into the default provider. So, I'll just close this silly issue. Thanks!

**Comment by fzaninotto** [comment]
You're right, the documentation is misleading and we should fix it.
