### ISSUE TITLE
ra-data-graphql-simple getResponseParser doesn't exclude apollo __typename property

### ISSUE THREAD

**Issue by alberto-coolshop** [marmelab/react-admin#2840]
**What you were expecting:**

I have a GraphQL schema which has been created accordingly to ra-data-graphql-simple,
I have the following schema:
```
    type Attribute {
        id: ID!
        type: String!
        code: String!
        group: ID!
        perMarket: Boolean
        options: [AttributeOption]
    }
    type AttributeOption {
        key: String!
        value: String
    }
```
I have only the parent type Attribute registered as a Resource in react-admin:
```
<Resource
          name="Attribute"
          list={AttributeList}
          edit={AttributeEdit}
          create={AttributeCreate}
       />
```
When I edit an Attribute from AttributeEdit component I should be able to perform an updateAttribute mutation.

**What happened instead:**

When it comes to query for nested types we have the unwanted property __typename, but necessary for Apollo InMemory Cache.
That property, when it comes for nested types, not mapped as Resources, is persisted on the reduxstore into the form property: 
![image](https://user-images.githubusercontent.com/13332592/52068983-25b16300-257e-11e9-9310-2bc99fa2be5f.png)

In this way the updateAttribute query comes with an error:
 *Field "__typename" is not defined by type AttributeOptionInput at value[0]*

**Related code:**

I think that __typename property is not correctly omitted by the following peace of code:
https://github.com/marmelab/react-admin/blob/e882ea3602074796115e2878b5c518e01f856490/packages/ra-data-graphql-simple/src/getResponseParser.js#L5-L54

As suggested by this comment:
https://github.com/marmelab/react-admin/blob/e882ea3602074796115e2878b5c518e01f856490/packages/ra-data-graphql-simple/src/getResponseParser.js#L18-L19

If the sub-type is not found in the registered resource list is returned "as-is" without property escaping.

**Other information:**

Any suggestion on how to fix this?

**Environment**

* React-admin version: 2.6.1
* ra-data-graphql-simple: 2.6.0
* ra-data-graphql 2.6.0
* Last version that did not exhibit the issue (if applicable): n.a.
* React version: 16.7.0
* Browser: Chrome
* Stack trace (in case of a JS error): network error 400

**Comment by terkiterje** [comment]
I got this as well, and I navigated around it by just overriding the buildQuery and removing the __typename:

```javascript
const myBuildQuery = introspection => (fetchType, resource, params) => {
  const builtQuery = buildQuery(introspection)(fetchType, resource, params);
  if (resource === 'Attribute' && fetchType === 'UPDATE') {
    return {
      // Use the default query variables and parseResponse
      ...builtQuery,
      variables: {
        ...builtQuery.variables,
        // avoid errors due to __typename being included in embedded schema
        weekdays: builtQuery.variables.options.map(option => ({
          ...option,
          __typename: undefined
        }))
      }
    };
  }

  return builtQuery;
};
```

and then just use that in the buildGraphQLProvider like so

```javascript
    buildGraphQLProvider({
      // ...
      buildQuery: myBuildQuery
    })
```

**Comment by djhi** [comment]
@alberto-coolshop, Thanks for reporting. I would gladly accept a PR fixing this.

**Comment by alberto-coolshop** [comment]
@djhi I would gladly help, but I have problems running the test suite.

running `make test`:

```
MacBookPro-Alberto:react-admin alberto$ make test
Transpiling ra-core files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-ui-materialui files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling react-admin files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-data-fakerest files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-data-json-server files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-data-simple-rest files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-data-graphql files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-data-graphcool files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-data-graphql-simple files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-input-rich-text files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-realtime files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-tree-core files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling ra-tree-ui-materialui files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Transpiling data-generator files...
$ rimraf ./lib && tsc
$ rimraf ./esm && tsc --outDir esm --module es2015
Running unit tests...
Error: Cannot find module './_baseGetTag'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/alberto/Documents/www/react-admin/node_modules/lodash/isPlainObject.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
make: *** [test-unit] Error 1
```

looks like a lodash dependency mismatch...

**Comment by izziaraffaele** [comment]
Since react-admin uses its own cache system and queries to the graphql API are always done with a `fetchPolicy` of `network-only`, why we don't just remove the `__typename` field from all queries and mutation by simply disabling it on the apollo client `InMemoryCache` instance?

**Comment by djhi** [comment]
I think this was fixed by #3168. Please comment and I'll reopen if it didn't

**Comment by yonahforst** [comment]
@djhi  - I just encountered this issue  on react-admin 4.2.4 with ra-data-graphql-simple 4.2.1

**Comment by DmytroUchkinSturupSoft** [comment]
A possible solution that helped in my case:

Using Apollo client Link [removeTypenameFromVariables](https://www.apollographql.com/docs/react/api/link/apollo-link-remove-typename/#overview) will remove __typename recursively from your request data object.

```
const graphQlClient = new ApolloClient({
  link: authLink.concat(removeTypenameLink).concat(httpLink),
  cache: new InMemoryCache({})
});
```
