### ISSUE TITLE
SimpleFormIterator disable remove button for specific elements

### ISSUE THREAD

**Issue by travisMichael** [marmelab/react-admin#2843]
**Is your feature request related to a problem? Please describe.**

Currently, the SimpleFormIterator has a 'disableRemove' boolean property that disables the remove button for each element in the array when it is set to true. Thus, the remove button is either disabled for all of the elements or none of the elements. It would be nice to conditionally disable the remove button for each element.

**Describe the solution you'd like**
An appropriate solution would be making the disableRemove property a function that takes the current record as input and outputs a boolean value that signifies if the remove button should be disabled.

**Describe alternatives you've considered**

**Additional context**

**Comment by fzaninotto** [comment]
Nice enhancement idea! The core team won't implement it (because we don't need it for our own projects), but we'd gladly accept a PR adding and documenting this feature.
