### ISSUE TITLE
AutocompleteInput does not pass disabled prop to react-autosuggest

### ISSUE THREAD

**Issue by mattiloh** [marmelab/react-admin#2848]
**What you were expecting:**

Passing the `disabled` prop to `<AutocompleteInput>` should disable the input, as described here: https://github.com/moroshko/react-autosuggest/issues/420#issuecomment-321902642

```jsx
<AutocompleteInput optionText="name" disabled />
```

**What happened instead:**
The field is not disabled as expected and it can still be changed. The `disabled` value seems not to be passed down to `react-autosuggest`.

**Related code:**

I disabled the `<AutocompleteInput>` in `src/comments/CommentCreate.js` in this CodeSandbox: https://codesandbox.io/s/0pq25pr9r0

**Other information:**
I checked the code of `<AutocompleteInput>` and it looks like it should be easy to fix. We just need to pass `disabled` to `inputProps` here: https://github.com/marmelab/react-admin/blob/ec4fae29eb75fd3c38a9125d23490b00aeeb2e99/packages/ra-ui-materialui/src/input/AutocompleteInput.js#L454-L467

It looks like a low hanging fruit. So if you don't mind, I will open a PR to fix it.

**Environment**

* React-admin version: `2.6.1`
* React version: `16.7.0`
* Browser: `Chrome 71.0.3578.98`

**P.S.**
Thanks for this great framework. We started using it a couple of days ago and it's really powerful – and still pleasant to work with. Very well done 👍

**Comment by fzaninotto** [comment]
did you try setting `options={{ disabled: true }}`? That should work.

**Comment by JulienMattiussi** [comment]
I got the same issue.
And @fzaninotto's solution worked fine for me.
`options={{ disabled: true }}`

**Comment by mattiloh** [comment]
Great, thanks for your help! I can confirm that it works.
