### ISSUE TITLE
Access to store, dispatch or actions that don't need dispatch.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#2856]
**Is your feature request related to a problem? Please describe.**
I don't want to do the Redux connect boilerplate dance just to use `showNotification` from a custom route or other component.

**Describe the solution you'd like**
I would like to be able to directly access the Redux store, its dispatch method or be provided with functions such as `showNotification` that can be called directly (without dispatch).

**Describe alternatives you've considered**
I think the only alternative is to connect my components. Perhaps one workaround would be to have a module in my code that can connect any component with these often-used methods.

**Additional context**
React-admin is so deeply nested with HoCs that whenever I look at React devtools, the content components that I actually need to look at are all the way right inside a pyramid of doom. IMO, not only are they complicated to debug but HoCs often just make things more complicated than they need to be. This is a problem in general with HoCs in React - having to wrap a component just to get access to one little feature is a very bad design on the part of the React and Redux team... they are trying to hard to make everything "functional" and I generally welcome any means of avoiding them.

I understand this is a very opinionated feature request, so no problem if you disagree and just close it - you won't get any argument from me. As of now, I will be looking into my workaround idea.

**Comment by waynebloss** [comment]
My workaround that only addresses the convenience factor (less boilerplate to get to these actions):

```js
import {
  refreshView,
  showNotification,
} from 'react-admin';
import { connect } from 'react-redux';

const defaultMapDispatch = {
  refreshView,
  showNotification,
  showError(err) {
    console.error(err);
    return showNotification(err.message ? err.message : err, 'error');
  },
};
/** Connect with common actions.
 * @param {React.ComponentType} ViewComponent
 * @param {()=>any} [mapState]
 * @param {object | Function} [mapDispatch]
 */
export function connectCommon(ViewComponent, mapState, mapDispatch) {
  return connect(mapState, mapDispatch || defaultMapDispatch)(ViewComponent);
}
```

It's not a huge deal to have to do this, however less nesting of components in HoCs is highly desirable to me for the purposes of debugging and understanding what is happening at runtime and generally just keeping thing simple... So, I'll just leave this issue open in case you want to consider one of the changes I suggested. Thanks.

**Comment by fzaninotto** [comment]
The react-admin core won't address that particular need. we promote one way of dispatching actions, and that's what React-redux advocates: using connect.

React Hooks may change that in the future, but in the meantime, any other methods of dispatching actions will have to live in userland.

**Comment by djhi** [comment]
React hooks are out and material-ui will soon release a version using them. I think there are now good solutions to address those issues but it will take some time to upgrade
