### ISSUE TITLE
Admin menu prop deprecated but it's the only one that works.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#2871]
**What you were expecting:**
The docs say that `<Admin menu={prop} />` is deprecated and it says to use a custom layout. The custom layout example shown below says to use the `Layout menu` prop instead. So, I expected that to work.

```
import { Layout } from 'react-admin';
...
const MyLayout = (props) => <Layout
    {...props}
    appBar={MyAppBar}
    menu={MyMenu}
    notification={MyNotification}
/>;
```

**What happened instead:**
However, it does not work. I copied code directly from `examples/demo` in this repo and even that demo still uses the `Admin menu` prop. When I tried to pass `Layout menu` instead of `Admin menu`, the default sidebar menu was still displayed.

Using `Admin menu` is the only thing that works.

**Steps to reproduce:**
Run the `examples/demo` code and try passing `menu` to the `Layout` component instead of the `Admin` component.

**Related code:**

Demo code as of commit `5cabddcab53bda4b109981f538d217e013dc7b4a`.

**Environment**

* React-admin version: 2.7.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.1
* Browser: Chrome 72
* Stack trace (in case of a JS error): none

**Comment by fzaninotto** [comment]
Bug confirmed, thanks for the report.

**Comment by fzaninotto** [comment]
As seen in #3084, it actually works. 

Maybe the cause of your problem (and I did the same mistake when reproducing the issue) is that the props must be cloned *before* setting a custom menu:

```jsx
// works
const CustomLayout = props => (
    <Layout {...props} appBar={AppBar} sidebar={CustomSidebar} menu={Menu} />
);

// does not work
const CustomLayout = props => (
    <Layout appBar={AppBar} sidebar={CustomSidebar} menu={Menu} {...props} />
);
```

But this is the way JSX works, nothing related to react-admin. the documentation uses the right syntax.

**Comment by waynebloss** [comment]
@fzaninotto Thanks.

At some point the [example code had it wrong](https://github.com/marmelab/react-admin/blob/8a0c324ca4ff345a1f15200115dd1b3ae1030b5f/examples/demo/src/layout/Layout.js) and I must have copied that without putting too much thought into it. Looks like that's fixed now.
