### ISSUE TITLE
AutocompleteArrayInput poor render performance on large list

### ISSUE THREAD

**Issue by StoraH** [marmelab/react-admin#2875]
I've a large list (over 1000 items) and get a lagging experience when rendering all the suggestions.
Would be great if it were possible to be able to limit the suggestion list in AutocompleteArrayInput.

`<AutocompleteArrayInput suggestionsLimit={5} ... />`

Solution first suggested over at react-autosuggest
https://github.com/moroshko/react-autosuggest/issues/292#issuecomment-261177321

The current workaround to handle large amount of choices in AutocompleteArrayInput won't work in my use case sadly
`<AutocompleteArrayInput shouldRenderSuggestions={(val) => { return val.trim().length > 2 }} />`
Explained here: https://marmelab.com/react-admin/Inputs.html#autocompletearrayinput

**Comment by fzaninotto** [comment]
duplicate of #2250
