### ISSUE TITLE
AutocompeteArrayInput do not allow to customize ChipInput

### ISSUE THREAD

**Issue by Madebymaurice** [marmelab/react-admin#2876]
Hello,
I'm using the `AutocompleteArrayInput` with `ReferenceArrayInput` component for having a autocompletion in search input and a chipInput as a selection, with the right props, we should first type in the input a word, then select what we want, and type again and select again.

There is 2 problems : 
- when I type the first time, I can see what I'm typing but the second time, even if the search works we can't see what we type
- then there some props in the original component [`ChipInput`](https://github.com/TeamWertarbyte/material-ui-chip-input) used in `AutocompeteArrayInput` there is a props for not allow Duplicate, which is by default on the `ChipInput` and do not work on the `AutocompeteArrayInput` component.
I also try to pass so props of react-autosuggest [](https://github.com/moroshko/react-autosuggest#should-render-suggestions-prop) by they do not work

```
<ReferenceArrayInput label="Tags" reference="tags" source="tags">
    <AutocompleteArrayInput />
</ReferenceArrayInput>
```

**Other information:**

![autocompletearrayinput](https://user-images.githubusercontent.com/36452057/52705581-87f96300-2f83-11e9-962d-c8f2738e37a9.gif)

**Environment**

* React-admin version: 2.6.2
* React version: 16.7
* Browser: Chrome
* Stack trace (in case of a JS error):

Thanks for your help

EDIT
After updating to the last version of react-admin one problem is then solve, the one who still persist is the access of props of the original composant `ChipInput`

**Comment by Kmaschta** [comment]
Glad to hear that the first bug was fixed in the newer versions!

About all the props not passed to the `AutocompeteArrayInput` a workaround would be to write your own input and pass the props yourself in.
Also, PR are welcome this is a common usage.

**Comment by Kunnu01** [comment]
It doesn't work even if the `allowsDuplicate=false` is directly passed to the `ChipInput` component. One of the solutions can be passing the `allowsDuplicate` prop to `AutocompleteArrayInput` and filtering the suggestions depending on it.
Should this be implemented? @Kmaschta @fzaninotto

**Comment by Madebymaurice** [comment]
Sorry, for the answer late, we finally decide to use another component.

Thanks for the response

**Comment by jdemangeon** [comment]
According to the previous answer, I closing the issue.
