### ISSUE TITLE
Full react-admin powered front-end… should I give this a try ?

### ISSUE THREAD

**Issue by Benew** [marmelab/react-admin#2877]
Hi !

I was building a dashboard view using a custom route and a `List`. I found the necessary doc in the Custom App doc.

But the `List` component is bound to the current route, location etc.

As I will show multiple lists I guess I may use `ListController` instead, with a custom view.

That lead me to an idea... Why not use react-admin to build both my app's admin and front-end views ? I would be able to use the same dataProvider, authProvider, custom actions etc.

@djhi @fzaninotto Do you guys think it'd be good idea to try using ra components (List, Edit, ListController...) and leverage the power of ra to build a fully customized production app ?

Call me crazy ! ;)

**Comment by fzaninotto** [comment]
We do build frontend (user-facing) apps using react-admin - nothing forbids it, except maybe the UI which is quite constrained by material design.

I suggest we continue the discussion on stackOverflow, this tracker is only for bugs / feature requests.

**Comment by djhi** [comment]
![Fly you fools](https://media.giphy.com/media/fbbL8ApME14pG/giphy.gif)

Just kidding, you can :) Obviously you'll be tied to MUI or have to re-implement a lot of UI components.

**Comment by Benew** [comment]
@fzaninotto @djhi thanks for your super-quick reply. And sorry for the spam. Here is an SO question: 

https://stackoverflow.com/questions/54669435/full-react-admin-powered-front-end
