### ISSUE TITLE
Is there a documentation on how to contribute in an efficient manner ?

### ISSUE THREAD

**Issue by Benew** [marmelab/react-admin#2880]
I'd like to contribute to `react-admin`. I created an application with `create-react-app` and I'd like to hack into `react-admin`, `ra-core`, `ra-ui-materialui` packages.

The [contributing](https://github.com/marmelab/react-admin#contributing) quick guide supposedly helps with that but it's not really working for me.

This is the guide I followed, below. 

```bash
# in myapp
# install react-admin from GitHub in another directory
$ cd ..
$ git clone git@github.com:marmelab/react-admin.git && cd react-admin && make install
# replace your node_modules/react-admin by a symbolic link to the github checkout
$ cd ../myapp
$ npm link ../react-admin/packages/react-admin
# go back to the checkout, and replace the version of react by the one in your app
$ cd ../react-admin
$ npm link ../myapp/node_modules/react
$ make watch
# in another terminal, go back to your app, and start it as usual
$ cd ../myapp
$ npm run
```

Problem is, no `watch` recipe in the `Makefile` of `react-admin`. There is a script in `packages/react-admin/package.json` though. 
Running `cd react-admin/packages/react-admin && npm run watch` works.
My app reloads if I modify the `react-admin` package.

But working on the `react-admin` package only doesn't help. As I said, I'd like to work on both `ra-core` and `ra-ui-materialui`, having a watcher rebuild the whole lib, and still having my app reload automatically.

The documentation seems very thin on that specific aspect and I think improving it might make more people able to contribute.

**Comment by fzaninotto** [comment]
Right, this guide is outdated and the dock is lacking, we should improve that.

What we do:

- we develop on all packages and watch the changes on the `simple` app using `make run`
- we add as much unit and integration tests as possible
- when we're satisfied with the changes, we build the packages with `make build`
- we can then test in the context of the (more complex) `demo` app

**Comment by djhi** [comment]
Thank you for this question.

The guide is indeed obsolete. You won't be able to work on the react-admin packages in CRA with hot reloading, etc. Indeed, it requires some webpack voodoo.

Until we find the time to properly document this, I suggest you take a look at the wrongly named `simple` example which uses a custom webpack configuration for this purpose.

**Comment by Benew** [comment]
Thanks guys, will do!
