### ISSUE TITLE
CheckboxGroupInput Options property not overwriting materials ui checkbox props.

### ISSUE THREAD

**Issue by vtretyv** [marmelab/react-admin#2883]
**What you were expecting:**

I would expect the CheckboxGroupInput to apply my "labelPosition" or "onCheck" that I pass to it in the "options" prop.
**What happened instead:**
I am attempting to use react-admin's input component: CheckboxGroupInput (https://marmelab.com/react-admin/Inputs.html#checkboxgroupinput). I wanted to overwrite the "labelPosition" to be left instead of right, however when I attempted to set this property it did not change the label position. I also wanted to overwrite the onCheck callback with my own custom callback, but ran into the same issue.
I was able to set the "checked" or "disabled" property to true in the options object, but it did not apply "labelPosition" or "onCheck" that I gave it.

Attempt to modify the "labelPosition" or "onCheck" in the CheckboxGroupInput.
**Steps to reproduce:**

Attempt to pass your own "labelPosition" or "onCheck" in the CheckboxGroupInput options prop.
**Related code:**

```
const NameField = ({ record }) => <div><div>{record.name}</div>
</div>;
class PartnersCreate extends React.Component {
    render(){
        return(
            <Create {...this.props}>
                <SimpleForm redirect="list">
                    <TextInput label="Partner Name" source="name" />
                    <ReferenceInput
                        source="catalogs"
                        reference="catalogs"
                        label="Catalog"
                    >
                        <SelectInput optionText="title" label="Catalog" />
                    </ReferenceInput>
                    <BooleanInput source="checkout" label="Checkout" />
                    <FormDataConsumer>
                    {({ formData, ...rest }) => formData.checkout &&
                    <div>
                        <CheckboxGroupInput
                            source="checked" 
                            label="Products" 
                            choices={products} 
                            optionText={<NameField />} 
                            optionValue="name" 
                            options={{labelPosition:'left'}}

                        /> 
                    
                        <DiscountPercentageInput />
                        <div>
                            <TextInput source="discountMessage" label="Discount Message" />
                        </div>
                        <div>
                            <NumberInput source="commission" label="Commission Percentage" />
                        </div>
                    </div>
                    }
                    </FormDataConsumer>

                </SimpleForm>
            </Create>
        )
    }
}
export default PartnersCreate;
```

**Other information:**

I recently added the checkout check in <FormDataConsumer>, and the behavior was the same for CheckboxGroupInput outside of this recently added change.
**Environment**

* React-admin version: 2.0.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.1
* Browser: Latest Chrome
* Stack trace (in case of a JS error):

**Comment by sagarbakhtar** [comment]
I think the issue here is not with the code, but with documentation.
Example code in [docs](https://marmelab.com/react-admin/Inputs.html#checkboxgroupinput) of `options` props shows and links to the latest documentation of Material UI’s `<Checkbox>` component, instead, it should link to the [version](https://v1-5-0.material-ui.com/api/checkbox/) (1.5.1) used by react-admin.

Please correct me if am wrong.
