### ISSUE TITLE
Create button redirect with more data in url querystring

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#2885]
Hi Thanks for this great tool. Helped me a lot!

Sometimes when I redirect my users to create page, I want to pass some parameters to that page, with url querystrings.

Using CreateButton, I think it would be ideal to pass an object of key value pairs, and have CreateButton add it to url. I know I can invoke an action to add the parameter to form, but I would very much like it in the url, since they can share it, and I don't want to lose the parameters.

What do you guys think?

**Comment by developerium** [comment]
I can make a pull request if you think it's a cool feature

**Comment by djhi** [comment]
Do you mean this: https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record ?

**Comment by developerium** [comment]
Yes this is also a good idea, thanks

**Comment by djhi** [comment]
Oh you meant to handle this automatically on the `CreateButton`? If so, yes, a PR would be nice :+1:

**Comment by developerium** [comment]
I made a pull request [#2892](https://github.com/marmelab/react-admin/pull/2892)

**Comment by red1** [comment]
Can we expect this branch to be merged ?

**Comment by developerium** [comment]
@red1 I don't think it is going to be merged with the approach I took on my branch, but feel free to use the code from my branch and use it
