### ISSUE TITLE
Documentation on how to use env files

### ISSUE THREAD

**Issue by Benew** [marmelab/react-admin#2888]
I see in the examples' `.gitignore` files:

```
.env.local
.env.development.local
.env.test.local
.env.production.local
```

I know this is not really related to `react-admin` but if you're used to use these, could you provide a sample on how to / why load env variables from them, depending on the environment ?

**Comment by djhi** [comment]
We don't use those. At least not directly. It is indeed not related to react-admin at all. Please use StackOverflow
