### ISSUE TITLE
Add query support

### ISSUE THREAD

**Issue by attilanyers** [marmelab/react-admin#2890]
**Is your feature request related to a problem? Please describe.**
It would be great if react-admin could not only display pure Resources but result of queries too.

**Describe the solution you'd like**
1. I would like to specify the input parameter set of the query using the existing input components
2. Execute the query when I click on the query button
3. Show the result of the query as a (special) Resource.

**Describe alternatives you've considered**
The input query & result set could be represented as a (special) Resource, and we need a button which executes the query and 'redirects' to the result set

**Comment by fzaninotto** [comment]
Use the data provider to map resources to something else than simple REST resources (e.g. compound resources, queries, etc). 

Or, write your own component that fetches the data provider, as explained in the documentation

https://marmelab.com/react-admin/Actions.html#using-a-data-provider-instead-of-fetch
