### ISSUE TITLE
can't see values set by filterDefaultValues in redux store

### ISSUE THREAD

**Issue by ncolboc** [marmelab/react-admin#2894]
Hello,

I have a custom page with a <List /> component inside and some filters (always on) associated with it.
I currently use filterDefaultValues to initialize some filters.
beside this List on the same page, I developed a component that need to be aware of the current filter values selected.
my component is connect to redux, so it can retrieve values from the store and be aware if theses values have changed.
but I remarked that filterDefaultValues object are not set in the redux store first time even if filters components are correctly set in UI.
any update of these filters after correctly fill the redux form. only first time is not set

So, currently I can't retrieve initiale values of these filters when page is loaded.

**Comment by fzaninotto** [comment]
Hi @ncolboc, and thanks for your report. 

This use case is not supported by react-admin's `Filter` component, and we don't want to support it. It's too rare, and would force a greater complexity in an already complex component.

You'll have to write your own Filter component to handle this case.
