### ISSUE TITLE
Change conditional formatting in "list" mode like "show" (ShowController, ShowView)

### ISSUE THREAD

**Issue by mnlbox** [marmelab/react-admin#2900]
**Is your feature request related to a problem? Please describe.**
Now when we want to conditional formatting for `show` mode we can use `ShowController` and `ShowView` like below: (code from docs: https://marmelab.com/react-admin/Fields.html#hiding-a-field-based-on-the-value-of-another)
```
import { ShowController, ShowView, SimpleShowLayout, TextField } from 'react-admin';

const UserShow = props => (
    <ShowController {...props}>
        {controllerProps =>
            <ShowView {...props} {...controllerProps}>
                <SimpleShowLayout>
                    <TextField source="username" />
                    {controllerProps.record && controllerProps.record.hasEmail &&
                        <TextField source="email" />
                    }
                </SimpleShowLayout>
            </ShowView>
        }
    </ShowController>
);
```

But for `list` mode we have not same feature. Please add same component for add conditional formatting to `list` and `DataGrid`. Thanks

**Comment by mnlbox** [comment]
Maybe we need something called for example: `ListController` and `ListView` :thinking:

**Comment by djhi** [comment]
They exist :)

- [ListController](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/ListController.js)

- [ListView](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/List.js#L99)

**Comment by mnlbox** [comment]
Thanks @djhi for rapid response.
And how we can use it?
Any docs available?

**Comment by djhi** [comment]
My pleasure :) No, unfortunately, this is a part we haven't documented yet. You'll have to read the code

**Comment by mnlbox** [comment]
@djhi So please reopen this issue as a feature request for this documentation. Thanks

**Comment by fzaninotto** [comment]
It doesn't make sense to condition the columns of a datagrid to one record, as the grid has many records, and you'll end up with a table with variable number of columns.

I feel that you're trying to do a special list layout that is very specific to your use case, so you should create your own alternative to Datagrid.
