### ISSUE TITLE
[Refactor] Move non ui component into ra-core: ReferenceField, ReferenceArrayField and make material-ui version

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#2902]
# Move non ui component into ra-core

We are currently working on https://www.npmjs.com/package/@bootstrap-styled/ra-ui , 

Following the logic of `ra-core`, it is used in conjunction of `ra-ui-materialui`.

The adapter that set the whole is `react-admin`.

Because of this, it is simple to create UI package to override the materialui default choice. 

https://www.npmjs.com/package/@bootstrap-styled/react-admin

Side node: This force us to lock the version number we use of ra-core until we follow your changes.

Some components in `ra-ui-materialui` still have some code that could be stored in `ra-core` and would benefits to any UI package, for example:

https://github.com/marmelab/react-admin/blob/v2.7.1/packages/ra-ui-materialui/src/field/ReferenceField.js

It only use two imports from `material-ui`.

```js
import { withStyles } from '@material-ui/core/styles';
import Progress from '@material-ui/core/LinearProgress';
```

https://github.com/marmelab/react-admin/blob/v2.7.1/packages/ra-ui-materialui/src/field/ReferenceArrayField.js#L22

Also:

```js
import LinearProgress from '@material-ui/core/LinearProgress';
import { withStyles } from '@material-ui/core/styles';
```

Moving components to the core would reduce the amount of duplicate code for react-admin UI compatibles packages (like for `ListController` and `ListView`).

Now I wonder, are you interested to permit third-party UI package?

If you do, we would be motivated to test and maintain this logic.

**Comment by djhi** [comment]
Those two components actually uses controllers for `ra-core` already and do not have much logic. We believe it is enough but maybe you can elaborate about what would need to be moved?

**Comment by djhi** [comment]
Btw, we are interested in third party UI packages! Please send us more feedbacks about it!

**Comment by kopax** [comment]
It can be tested, so far nothing great compared to what materialui does, it's a convenience for our process, but we will still try to make it look good.

About my suggestion, I would recommend to use the props strategy. Using default props to set the default component to be used would work. The class will become abstract (like `CoreAdmin`), and the one use will still be an import from `ra-ui-materialui`. It will just pass the `LinearProgress`, `Link` components and the styles.

**Comment by djhi** [comment]
Have you read my first answer ? Those two components don't have much logic so I think the current controllers are enough

**Comment by kopax** [comment]
I misread it sorry, sure and noted with thanks.
