### ISSUE TITLE
RFC: Easier Save Action Customization

### ISSUE THREAD

**Issue by djhi** [marmelab/react-admin#2905]
## API

```jsx
const handleSave = (values: any, redirect: RedirectionSideEffect) => {
    // I can override the redirect
    // I can override/add/remove data
    // I can return a custom action, it will be dispatched for me

    return myCustomAction(values, redirect);
}


const CreatePost = props => (
    <Create onSave={handleSave}>
        ....
    </Create>
);
```

If I return an action, it will be dispatched for me, avoiding the redux connect boilerplate.
If I don't return anything, nothing will be done for me. I may dispatch myself and/or do something else.

## Use cases

- I need to override the form values before sending them to my dataProvider. The [current way](https://marmelab.com/react-admin/Actions.html#altering-the-form-values-before-submitting) to do it is way too verbose and complicated.
- I need to change the redirect depending on the form values
- I need to close a dialog/drawer which contain my Create/Edit component once it is saved

## Details on current solution

Today, you have to first implement a custom connected button which already implies a lot of boilerplate, for example (and this does not even includes the code needed for a custom redux action):

```jsx
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { crudCreate, SaveButton, Toolbar } from 'react-admin';

// A custom action creator which modifies the values before calling the default crudCreate action creator
const saveWithNote = (values, basePath, redirectTo) =>
    crudCreate('posts', { ...values, average_note: 10 }, basePath, redirectTo);

class SaveWithNoteButtonView extends Component {
    handleClick = () => {
        const { basePath, handleSubmit, redirect, saveWithNote } = this.props;

        return handleSubmit(values => {
            saveWithNote(values, basePath, redirect);
        });
    };

    render() {
        const { handleSubmitWithRedirect, saveWithNote, ...props } = this.props;

        return (
            <SaveButton
                handleSubmitWithRedirect={this.handleClick}
                {...props}
            />
        );
    }
}

const SaveWithNoteButton = connect(
    undefined,
    { saveWithNote }
)(SaveWithNoteButtonView);
```

Then, you have to create a custom toolbar to use it:

```jsx
const PostCreateToolbar = props => (
    <Toolbar {...props}>
        <SaveButton
            label="post.action.save_and_show"
            redirect="show"
            submitOnEnter={true}
        />
        <SaveWithNoteButton
            label="post.action.save_with_average_note"
            redirect="show"
            submitOnEnter={false}
            variant="flat"
        />
    </Toolbar>
);
```

And finally, you have to pass this custom toolbar to the `SimpleForm` through the `toolbar` prop.

**Comment by djhi** [comment]
After further investigation, the use case addressed by the documentation is when you need to have two different buttons, one for the default save and another. This RFC does not make it easier.

Besides, for overriding the default case, it should be done at the `dataProvider` level or by implementing a custom Create or Edit controller which are not that complicated

**Comment by jjgumucio** [comment]
@djhi Hi!
How can I create this custom Create or Edit controllers? 
There is no documentation for that, or at least I haven't found it.

Can you give me some clues on the process?
My use case is: I need to overwrite the save action to add/process record data before saving/calling the data provider.

Thanks for all of this great software!

**Comment by fzaninotto** [comment]
@jjgumucio Please use StackOverflow for "how to" questions.

**Comment by gypsicoder** [comment]
@fzaninotto  It would be better if there are examples shown in the repo.
