### ISSUE TITLE
The page still loaded when the auth_check failed(return a reject promise)

### ISSUE THREAD

**Issue by keeneagle** [marmelab/react-admin#2907]
The page still be loaded when the auth_check failed(return a reject promise), then switched to login page. 
I checked the code(below is the user_check snippet code of the auth.ts file), since the **yield** 
didn't wait until the the AUTH_LOGOUT executed finished, so it does not block the original page loading, even we return the reject promise in the AUTH_CHECK. 

```js
    case USER_CHECK: {
                try {
                    yield call(authProvider, AUTH_CHECK, payload);
                } catch (error) {
                    **yield call(authProvider, AUTH_LOGOUT);**
                    yield put(
                        replace({
                            pathname: (error && error.redirectTo) || '/login',
                            state: { nextPathname: meta.pathName },
                        })
                    );
                }
                break;
            }
```

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. 

What you describe is a feature that we implemented on purpose. We optimistically render the page before getting a response from the `authProvider` to show feedback to the user faster when they're connected. The drawback, that we accept, is that we display the *UI* (but not the *data*) briefly when the user loses authentication.

So we won't fix this.

**Comment by awesome-manuel** [comment]
This also means you always get a "failed login" notification when you access the page for the first time and are not logged in.
