### ISSUE TITLE
Demo does no run on Windows 10

### ISSUE THREAD

**Issue by noobling** [marmelab/react-admin#2908]
**What you were expecting:**

For the demo app to run in my Windows environment

**What happened instead:**

Same error in this post `data-generator` not found https://github.com/marmelab/react-admin/issues/2030

**Steps to reproduce:**

Use Windows 10 Pro version 1809
* Clone the repo `git clone https://github.com/marmelab/react-admin.git`
* `> cd react-admin`
* `make install`
* `make run-demo`

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):
```
Failed to compile
./src/fakeServer/graphql.js
Module not found: Can't resolve 'data-generator' in 'C:\Users\david\Documents\react-admin\examples\demo\src\fakeServer'
```

**Comment by fzaninotto** [comment]
Thanks for your report. As none of the core team developers use a windows computer, we'll need help from the community to solve this one.

**Comment by mingjyesheng-ioteye** [comment]
The error is not on Windows 10 alone.
Same issue on MAC OS Majave too.

**Comment by noobling** [comment]
I think it just isn't pulling in/building the required packages.

**Comment by SyedFarhan** [comment]
Having this issue on macOS High Sierra. Manually linked data-generator and started getting a similar error for `ra-core` not being found. So as @noobling stated, its not pulling required packages.

**Comment by fzaninotto** [comment]
I can reproduce on a fresh install on Linux, too.

**Comment by fzaninotto** [comment]
I traced back the problem to https://github.com/marmelab/react-admin/commit/e20fb141b002a52c87c3d87983dd5e2eb1133545#diff-b9cfc7f2cdf78a7f4b91a753d10865a2. I removed the automated build from the `make run-demo` target. That means that developers must now run `make build` before calling `make run-demo`. I'll update the documentation accordingly.
