### ISSUE TITLE
Export function always exports first page regardless of page being displayed

### ISSUE THREAD

**Issue by andrewdenton** [marmelab/react-admin#2915]
**What you were expecting:**
Export should export the currently displayed page

**What happened instead:**
Export always exports the first page regardless of which page is being displayed

**Steps to reproduce:**
Go to the demo site 
https://marmelab.com/react-admin-demo/#/customers

Click Export. Then go to the second page and click Export. The contents of both export files will be the same (i.e. the first page of customers).

**Comment by djhi** [comment]
Explained in the documentation:

> Among the default list actions, react-admin includes an <ExportButton>. This button is disabled when there is no record in the current <List>.

> By default, clicking this button will:

> 1. Call the dataProvider with the current sort and filter (but without pagination),
> 2. Transform the result into a CSV string,
> 3. Download the CSV file.

**Comment by djhi** [comment]
PS: About the demo, if you open the CSV file, you'll find **all** customers, not just the first page

**Comment by kctrlv** [comment]
@andrewdenton 

We have a usecase where we want to use the Export button as 'wisywig', to display exactly what's on the list page. This was almost possible, as you could pass filters and sort to it, however I ran into the same issue you did where I couldn't pass the 'page' and therefore the request was always triggered with a page of 0. 

I tried to pass state into the dataProvider but after a lot of fiddling I came up with a different solution: I listen to 'RA/CRUD_CHANGE_LIST_PARAMS' in a saga and save the current page, then read it in the request code before it makes the call with page 0. I too would have preferred if I could pass 'page' as a prop into the ExportButton, but this will do the trick for now.
