### ISSUE TITLE
UrlField link is faulty when using IP

### ISSUE THREAD

**Issue by jheiska** [marmelab/react-admin#2917]
**What you were expecting:**
Using UrlField and fetching IP from the resource, the link points to the correct IP

**What happened instead:**
When running on http://localhost:3001 and using IP 10.10.10.10 the link becomes http://localhost:3001/10.10.10.10

**Steps to reproduce:**
Use UrlField with a resource that has an IP address.

**Comment by djhi** [comment]
This field simply wrap the record value within an anchor tag. It expects an url as the record value. It's your job to make sure the value is an url.

**Comment by djhi** [comment]
PS: In your case, you probably need a custom `IpField` component

**Comment by Kmaschta** [comment]
To be more precise, in HTML when you write a link as `<a href="1.1.1.1">` it will redirect to `{HOST}/1.1.1.1` because you have to specify a protocol in your link, like `http://1.1.1.1`

**Comment by jheiska** [comment]
Thanks for the quick reply! I haven't done much http programming so I completely forgot that you need to specify the protocol for <a href="">. Resolved this by using FuncionField to put the link together.
