### ISSUE TITLE
Rename appLayout to layout in <Admin>

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#2918]
The current prop name for the layout in `<Admin>` isn't intuitive.

**Comment by yuriydobryanskyyempeek** [comment]
I think you can add an "alias" prop - so both are accepted. And mark appLayout as deprecated till next major version bump.

**Comment by Kmaschta** [comment]
You're right! PR are welcome :)

**Comment by fzaninotto** [comment]
fixed by #3055
