### ISSUE TITLE
Allow primaryText to be a component in MenuItemLink

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#2920]
**What you were expecting:**

`primaryText` in `MenuItemLink` to allow a react component (object)

**What happened instead:**

```
VM380406:1 Warning: Failed prop type: Invalid prop `primaryText` of type `object` supplied to `MenuItemLink`, expected `string`.
    in MenuItemLink (created by WithStyles(MenuItemLink))
```

**Steps to reproduce:**

We need to have an accordion in the menu, so we used the code below. That code shows the warning because `react-admin` allows only string for `primaryText`

**Related code:**

```
<MenuItemLink
                    // The 'to' prop is not used for navigation
                    // It is used for showing the link as 'selected' or not, as we use 'preventDefault' at 'onClick'
                    to="/services/"
                    primaryText={
                      <Fragment>
                        <span style={{flex: 1}}> Feedback </span>
                        {this.state.showFeedback
                          ? <ExpandLess />
                          : <ExpandMore />
                        }
                      </Fragment>
                    }
                    title="Feedback"
                    onClick={this.handleFeedback}
                    leftIcon={<StarIcon />}
                  />
```

**Other information:**

**Environment**

* React-admin version: ^2.5.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Marked this as an enhancement. Note that if the `primaryText` can be an element, we'd better rename the property `children`.

Feel free to submit a PR about it.

As for having an accordion menu, take a look at the implementation we did on the demo:

[examples/demo/src/layout/Menu.js](https://github.com/marmelab/react-admin/blob/b2f1a6dc743c676f64578956a728ca1f9ea3aa28/examples/demo/src/layout/Menu.js)
