### ISSUE TITLE
Disable fetching new related records in ReferenceManyField

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#2931]
Hi guys

I have a `ReferenceManyField` which I know I data won't change, and I would like it to not fetch related data every time the component mounts.

Since in `ReferenceManyFieldController`, has

`componentDidMount() {
        this.fetchReferences();
    }`

I like to suggest, adding a boolean field, to not fetch references. Later I can use pagination to get fresh data if I need it.

What do you guys think about this?

**Comment by fzaninotto** [comment]
Hi @developerium, 

Nice idea for a custom ReferenceMAnyField component.

We won't implement that in the core ReferenceManyFieldController, though, as the same reasoning can be applied to all the components that fetch. It's just not the way react-admin was designed.

**Comment by developerium** [comment]
ok cool
