### ISSUE TITLE
Exporting CSV file doesn't include the permanent filter

### ISSUE THREAD

**Issue by jheiska** [marmelab/react-admin#2933]
**What you were expecting:**
Exported CSV file to take into account the permanent filter of the List component.

**What happened instead:**
CSV file includes all entries, regardless of the permanent filter.

**Steps to reproduce:**
Create a List component with a permanent filter. For example 
`<List {...props} filter={{id: 1}} >`
Download CSV file by using the export button.

**Environment**

* React-admin version: 2.7.0
* React version: 16.4.1
* Browser: Chrome

I know I can probably achieve this by creating a custom exporter function. If this is intended behavior, it should be mentioned in the documentation.

**Comment by fzaninotto** [comment]
Confirmed, that's a bug. The List doesn't even pass the `filter` prop to the `ListActions` component.

**Comment by kopax** [comment]
Without going in depth directly, and just to confirm, if we pass `filter` to the `ListActions`, it should work?
