### ISSUE TITLE
[Feature] Ability to have list fetch from redux store

### ISSUE THREAD

**Issue by tml123** [marmelab/react-admin#2935]
First, thanks for the REALLY GREAT product.  

I'd like to figure out a way to incorporate reads from the store rather than from the server after initial data load for a particular resource.

**Is your feature request related to a problem? Please describe.**
I'd like the ability to have `ListController` only request data once from the server and then subsequently read from the store on the client for future requests. 

**Describe the solution you'd like**
Provide some ability to provide `List` or `ListController` with a `prop` that tells the component to make requests from the store after initial load.  Currently, the `ListController` calls `updateData` each time on `componentDidMount`, which calls the `dataProvider`.  This dispatches `GET_LIST` which reads from the server.  Rather, it would be nice to be able to read from the client only.

**Describe alternatives you've considered**
I've considered copy and pasting most of the `List`, `ListController` and `ListView` components to support such a behavior.  I've also considered how one might write a `customSaga` to only read from the store or perhaps try to incorporate a reducer.  The problem that I've found is that `ListController` has `mapDispatchToProps` bound to the `react-admin` implementation of `crudGetList` and so it dispatches and API call each time.  I haven't seen what the best way is to accomplish this.

**Comment by fzaninotto** [comment]
Hi @tml123, and thank you!

Your question is somewhat related to issue #2931, and the answer is the same: we've designed the react-admin controllers to be optimistic, but not offline. Handling both behaviors would require a lot of work, configuration, and documentation; that's not a path we want to take.

But the good news is, you can write your own ListController to implement the exact behavior you're describing! If you don't know how to to it, I suggest you ask the question on StackOverflow.

**Comment by tml123** [comment]
Thanks @fzaninotto for the super quick response.  I had been digging through the source and wasn't sure if writing a custom `ListController` was the right approach, but since you mentioned that, I think that is the way I'll go.  Thanks again!
