### ISSUE TITLE
ra-data-graphql-simple - introspection runs without error but no resources found in react-admin

### ISSUE THREAD

**Issue by gregbelyea71** [marmelab/react-admin#2938]
**What you were expecting:**
changed my schema on Apollo Server over to match what was expected, i have done this before with Apollo Server, React-Admin, and ra-data-graphql-simple... and had it work no problem.. my dependencies in my admin project are as follows..  

"graphql": "^14.1.1",
"prop-types": "^15.7.1",
"ra-data-graphql-simple": "^2.7.1",
"ra-data-json-server": "^2.7.1",
"ra-data-simple-rest": "^2.7.1",
"react": "^16.8.1",
"react-admin": "^2.7.1",
"react-dom": "^16.8.1",
"react-scripts": "2.1.5"

**What happened instead:**
Introspection appears to go fine, no errors.. except the introspection query seems to only come back with types, i don't see any information about the queries.. i copied what was being sent from react-admin out of developer tools and ran it in Graphiql and it's not even asking for info on the queries..

This worked out of the box the last time once i made sure my schema was laid out the way .. i'm not sure where to start to debug this..

I used the react code right out of the example to same as before as well...

`buildGraphQLProvider({ clientOptions: { uri: 'http://localhost:4000' }})
            .then(dataProvider => this.setState({ dataProvider }));`

`<Admin dataProvider={dataProvider}>
       <Resource name="Country" options={{ label: 'Countries' }} list={ListGuesser}/>
 </Admin>`

My schema is drop dead simple as i just needed to get this talking back and forth before i move on... and add functionality..

`export default

# Type definitions define the "shape" of your data and specify
# which ways the data can be fetched from the GraphQL server.

"""
A type that describes the Country
"""
type Country {
    id: ID!
    name: String
    abbr2: String
    abbr3: String
    provStates: [ProvincesAndStates]
}

input SectionFilter {
    q: String
    id: ID
    name: String
  }

"""
The Query type is the root of all GraphQL queries.
"""
type Query {
    Country(id: Int!): Country
    allCountries(page: Int, perPage: Int, sortField: String, sortOrder: String, filter: SectionFilter): [Country]
}
type Mutation {
  createCountry(
    name: String!
    abbr2: String!
    abbr3: String!
  ): Country  
}
`

i have the latest version of Apollo Server running graphql/sequelize but that is probably neither here not there since introspection is what appears to not be working..

Is there any problems that have arisen because of versions?  I am just going to go back and run my older project and have a look at that introspection query that is sent, as the code is pretty much identical..

**Comment by gregbelyea71** [comment]
ok, after hammering away on this...  it seems it was because i had a nested object in my country type... province not surprisingly... However i had nested objects in my first attempt that worked no problem.. You have them in your example here on the front page as well Posts --> Comments.  I am using the sample code to fire up react-admin and as long as no nesting it works...   I can run the nested query in GraphiQL no problem... what is it that the dataProvider would hate about nesting? The error when i put it back in is...  maximum call stack size exceeded

**Comment by OoDeLally** [comment]
@gregbelyea71 Did you find a workaround?
I have the same problem. My entities are as follow:
```
# Provokes `Maximum call stack size exceeded` upon introspection 
User =(field: bookmarks)=> Bookmark[] =(resolveField: book)=> Book =(resolveField: author)=> User
```
Funnily, it works if the entity is standalone, but not when it's inside an array. 
```
# Works
User =(field: bookmark)=> Bookmark =(resolveField: book)=> Book =(resolveField: author)=> User
```
