### ISSUE TITLE
Multiple redirect to login in case multiple requests to api presents on the page

### ISSUE THREAD

**Issue by fxzhukov** [marmelab/react-admin#2939]
**What you were expecting:**

When user is unauthorized and more than one request to api presents on the page, he should be redirected to login page only once

**What happened instead:**

When user is unauthorized and more than one request to API presents on the page, user will be redirected to login page multiple times (after first successful login, user will be again redirected to login form, and it will happens multiple times. Number of times exactly match the number of requests to API on the page)

**Related code:**

I believe that this happens because of this saga:
```
return function* watchAuthActions() {
        yield all([
            takeEvery(action => action.meta && action.meta.auth, handleAuth),
            takeEvery(FETCH_ERROR, handleAuth),
        ]);
    };
```

**Proposed solution:**

May be it is better to use `takeLatest` instead of `takeEvery` for authentication errors. If you are fine with this solution, I can create a PR

**Environment**

* React-admin version: 2.7.1
* React version: 16.6

**Comment by Kmaschta** [comment]
Thank you for the investigation!
PR are always welcome.

This issue would be perfect with an easy-to-reproduce CodeSandbox, you can fork this one: https://codesandbox.io/s/349ovjmlx5

**Comment by fxzhukov** [comment]
@Kmaschta, @fzaninotto PR created - take a look, please
