### ISSUE TITLE
Document how to change JSS insertion point.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#2940]
**Is your feature request related to a problem? Please describe.**
I know that the JSS insertion point can be changed, but I'm not sure how. React-admin is using an older version of material-ui and the techniques described in their latest docs don't work here. I also tried running `jss.setup` myself.

I don't even see how React-Admin is initializing JSS at all. It's a direct dependency of `ra-ui-materialui` but nothing in that package even imports `jss` or `react-jss`. I can't find the words `jss` anywhere in your packages.

**Describe the solution you'd like**
I'd like a support document describing how to do it. Or, just give the answer here if possible and that can serve as the documentation for now...

**Describe alternatives you've considered**
Continuing to try and figure it out myself. So far I've spent over an hour trying the wrong solutions. I might get lucky.

**Additional context**
I really don't want to have to write `!important` next to every rule in every stylesheet! Thanks.

**Comment by oliviertassinari** [comment]
Related to https://github.com/mui-org/material-ui/issues/7944#issuecomment-468042637

**Comment by waynebloss** [comment]
@oliviertassinari No more quick comebacks eh? I know, it's embarrassing getting murdered by words...

Maybe next time if you ask nicely I'll show you 15 years worth of monetary contributions to various open source foundations made by my company. That's what your pal was desperately asking for with his ads right?

Thanks for banning me because I'd never use MUI on purpose and I'd hate to accidentally contribute. Honestly, I think it would be great if [some](https://github.com/oliviertassinari) [users](https://github.com/kof) didn't contribute anything. Work harder on that, ok?

**Comment by oliviertassinari** [comment]
@waynebloss I don't know how banned you, it's surely wasn't me.

**Comment by waynebloss** [comment]
@oliviertassinari I could care less about the banning. You have no foundation to look at my life for 5 seconds and say I don't contribute. I had a beef with the other guy and I said some things against him, not sure why you were white knighting but ok.

Water, bridge. Let's move one.

**Comment by waynebloss** [comment]
Anywhoo - well I haven't found a way to change the JSS insert point after working on this for 3 hours.

I think I wasted half of that trying things that weren't meant for v1.5.1 of MUI before I made this issue.

I'm going to have to pull apart all these packages later and see what's going on. Will update this issue with the answer if and when I can find it.

**Comment by oliviertassinari** [comment]
The solutions shared in https://material-ui.com/customization/css-in-js/#css-injection-order should be working with v1.5.1. Here is a live demo: https://codesandbox.io/s/yw93kl7y0j.

**Comment by oliviertassinari** [comment]
@waynebloss You might like this one… https://twitter.com/olivtassinari/status/1098541740846399488

**Comment by waynebloss** [comment]
OK, I gave up on MUI docs after none of the solutions listed here worked - https://material-ui.com/css-in-js/advanced/

Now I see what's going on, those are for MUI 4.

**Comment by oliviertassinari** [comment]
> https://material-ui.com/css-in-js/

Yes, this section is for v4, it won't help.

**Comment by waynebloss** [comment]
Very good thanks. Glad we could get this resolved with minimum bloodshed!

The proper contraption to setup the insertion point is finally in place and we know where the exact documentation is.

@fzaninotto Perhaps just a link to that page should be added to the docs. I'm actually fine with searching issues to learn things; I do it all the time. Up to you. If you want me to decide where in the docs this should go and how much to say about it - I can certainly do that. Just let me know, thanks!

@oliviertassinari I actually don't see any of those ads on the Vue page. Doh!

**Comment by waynebloss** [comment]
Also, extra thanks to @oliviertassinari for finding the solution even after sparring verbally with me.

To sum up this minor drama for any interested readers:

- I got offended that JSS put ads in their NPM post install hooks for their package. To me that's like a big slap in the face. So I opened and issue and rudely told them about my feelings.
- They got mad and banned me. So, I was not withholding any of my opinions about JSS in a different issue on material-ui.
- Then I guess that some MUI people got offended at my negative attitude towards JSS.
- Now we're here. No big deal. Sorry for the drama!!

**Comment by kof** [comment]
The big drama is that people like you are big damage to our community. You didn't care to look up that the postinstall hint was already removed a long time before you opened that issue, it was already heavily discussed. You didn't care to ask why we added it in the first place. You didn't care that many other very popular projects do that as well, for example, preact, and 99,999999% of people don't get offended by this.  You are using my time and my mental health to express your damaged and hostile attitude towards open source and essentially to other people work, where many people like me invest their PERSONAL time.

If I would be a maintainer in this organization, I would ban you here as well after what you did there https://github.com/cssinjs/jss/issues/1013

**Comment by djhi** [comment]
@waynebloss. We won't tolerate this behavior and language here. This will be the only warning before ban.

**Comment by fzaninotto** [comment]
I'm closing this issue as it's a material-ui issue IMO. Thanks @oliviertassinari for chiming it and staying cool.
