### ISSUE TITLE
Problem with import of most recent version of `react-headroom` (2.2.5)

### ISSUE THREAD

**Issue by te-online** [marmelab/react-admin#2941]
**What you were expecting:**
Compiling an empty project runs fine (set-up after tutorial)

**What happened instead:**
Compiling throws error
``` Console
./node_modules/ra-ui-materialui/esm/layout/Headroom.js
Module not found: Can't resolve 'react-headroom' in '[redacted]/test-admin/node_modules/ra-ui-materialui/esm/layout'
```

**Steps to reproduce:**
Follow tutorial

**Other information:**
Installing a fixed dependency to `react-headroom@2.2.4` in the `package.json` of the project and reinstalling packages fixes the error. 
There must a problem with importing the *just* released version 2.2.5 of `react-headroom`.  

**Environment**

* React-admin version: 2.7.2
* React version: 16.8.2

**Comment by djhi** [comment]
Thanks for reporting!

**Comment by fzaninotto** [comment]
React-headroom just release a fix in version 2.2.6. Can you confirm it solves the issue?

**Comment by kopax** [comment]
I can confirm it does solve the issue I have been through this.

**Comment by te-online** [comment]
Yes, it works. Thank you! 😊
