### ISSUE TITLE
Login Page should redirect to the app if the user is already logged

### ISSUE THREAD

**Issue by dharmesh7980** [marmelab/react-admin#2953]
**Is your feature request related to a problem? Please describe.**
When the user go to the login page if they are already logged, the login form is still displayed.

**Describe the solution you'd like**
I would like the redirect the user to the dashboard by default if they are already logged.

**Additional context**
In order to reproduce on the demo, here is the process to follow:

1. First login in react-admin https://marmelab.com/react-admin-demo/#/login
2. After successful login again visit https://marmelab.com/react-admin-demo/#/login

User sees the login page, but the they would be redirected to the dashboard for example.

**Comment by dharmesh7980** [comment]
First login in react-admin
https://marmelab.com/react-admin-demo/#/login

after successful login again visit https://marmelab.com/react-admin-demo/#/login , still user access login page it should not be happened,

**Comment by Kmaschta** [comment]
I rephrased your whole issue, because it was really hard to understand. Let me know if it's what you asked for.

The next time, please follow the issue templates.

**Comment by macscripter** [comment]
any update?

**Comment by djhi** [comment]
Not sure we want that in the core and this is achievable in user land. I'll wait for more comments from the core team

**Comment by fzaninotto** [comment]
I agree, this is achievable in userland using a `<Redirect>` in `<Login>`. Closing.
