### ISSUE TITLE
Show custom notification after logout in USER_CHECK

### ISSUE THREAD

**Issue by bitshadow** [marmelab/react-admin#2967]
**Is your feature request related to a problem? Please describe.**
When user check fails user should be allowed to show custom notification. Currently when auth token expires we want to show a user message with custom message. This behaviour works well in case of `USER_LOGIN` however it is missing in `USER_CHECK`.

https://github.com/marmelab/react-admin/blob/ed361d34f3d35634f53a0caf08bbd1467c18d8be/packages/ra-core/src/sideEffect/auth.ts#L64

**Describe the solution you'd like**
User should be allowed to set custom notification which will appear after logout.

**Comment by m4theushw** [comment]
Should not this issue be closed as the PR proposed is already merged?

**Comment by Kmaschta** [comment]
Totally. Thanks for the ping!
