### ISSUE TITLE
[ra-data-graphql-simple] Http 401 error is not redirecting to login page

### ISSUE THREAD

**Issue by ballad89** [marmelab/react-admin#2983]
**What you were expecting:**

I expected to be redirected to the login page when the graphql endpoint returns http 401 or 403

**What happened instead:**

It displays the error message, but continues and tries to parse the null data returned

**Steps to reproduce:**

- Have the graphql endpoint return 401 for a query, with an error message and null data

**Related code:**

**Other information:**

**Environment**

* React-admin version: "^2.7.3"
"ra-data-graphql-simple": "^2.7.1",
* React version: "^16.8.4"
* Browser: Google Chrome
* Stack trace (in case of a JS error):
Below is what gets printed to console.log
```js
index.js:83 POST http://localhost:3001/graphql 401 (Unauthorized)
index.js:1446 Warning: Missing translation for key: "GraphQL error: LOGIN_USER
GraphQL error: LOGIN_USER
GraphQL error: Non-nullable field was null."
index.js:1446 Warning: Missing translation for key: "GraphQL error: LOGIN_USER
GraphQL error: LOGIN_USER
GraphQL error: Non-nullable field was null."
```

**Comment by fzaninotto** [comment]
As explained in the documentation, it's your responsibility to handle 401 or 403 errors in the authProvider: https://marmelab.com/react-admin/Authentication.html#catching-authentication-errors-on-the-api

This is not related to the data provider.

**Comment by ballad89** [comment]
Maybe I did not explain clearly, I am saying the default behaviour explained below does not work for graphql
![image](https://user-images.githubusercontent.com/4387126/54317122-01b85700-45eb-11e9-9ab1-ebacdf347ffd.png)

**Comment by fzaninotto** [comment]
You're right, the Authentication documentation is misleading. I'm reopening this issue and marking it as a documentation bug.

**Comment by ballad89** [comment]
the reason I felt it is a bug is because the graphql package does not catch and throw the correct error as the other packages do. It assumes it always succeeds
https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql/src/index.js#L100

**Comment by fzaninotto** [comment]
I mistakenly pushed the fix to master. Reverting and reopening the issue.

**Comment by ballad89** [comment]
Are you referring to the documentation fix or my immediate comment above ?

**Comment by fzaninotto** [comment]
ah, you're referring to the `fetchJson` utility and its control of the HTTP status?

https://github.com/marmelab/react-admin/blob/f1ea409cf67fd285fbf94b9ba241fb29947ff5f4/packages/ra-core/src/util/fetch.ts#L42-L50

In that case, it's true that the graphql data provider doesn't do anything special about it - because it relies on Apollo, not fetch. But Apollo client also returns a failed Promise in case of 401 or 403, I believe you can check for that type of error in the authProvider as usual?

**Comment by ballad89** [comment]
Yes, that is what I was referring to. I already tried what you suggested, but by the time it gets the authprovider it no longer has a `status` and is not in the format expected by the auth provider, because my guess is that the documentation was written with `fetchJson` as the first class implementation, so whatever I tried at the authprovider did not redirect me to the login screen

**Comment by fzaninotto** [comment]
It will never have a `status` because the graphql data provider doesn't use `fetchJson` but Apollo. My knowledge of Apollo Link isn't good enough to help you on this one, but I believe you can add a Link Middleware to turn HTTP errors into meaningful exceptions.

**Comment by ballad89** [comment]
According to the documentation of implementing a dataprovider, it says
```
Error Format
When the API backend returns an error, the Data Provider should `throw` an `Error` object.
This object should contain a `status` property with the HTTP response code (404, 500, etc.).
React-admin inspects this error code, and uses it for authentication (in case of 401 or 403 errors).
Besides, react-admin displays the error `message` on screen in a temporary notification.
```
https://github.com/marmelab/react-admin/blob/master/docs/DataProviders.md#error-format

So according to that documentation the dataprovider should catch the errors and throw the appropriate `Error`. At the moment, it doesn't. It assumes it always succeeds

I already tried what you suggested in multiple permutations, but it does not work, because it is either too early or too late in the stack
```js
return new ApolloClient({
    link: ApolloLink.from([
      onError(({ operation, response, graphQLErrors, networkError }) => {
        console.log('resp', response)
        response.data = null
        response.errors = null
        if (graphQLErrors) {
          response.errors = response.errors.map((e) => {
            switch (e.message) {
              case 'LOGIN_USER':
                return {...e, status: 401}
              default:
                return e
            }
          })
        }
        if (networkError) {
          // logoutUser()
          console.log('networkError', networkError)
        }


      }),
      requestLink,
      withClientState({
        cache
      }),
      new createUploadLink({
        uri: `${uri}`
      })
    ]),
    cache
  })
```

**Comment by fzaninotto** [comment]
Right, @djhi what do you think. Should ra-data-graphql provide HTTP error handling and throw HTTP errors? 

I'm not sure that assuming the GraphQL APPI returns a 403 isn't a strong assertion for GraphQL, which is not linked to HTTP.

**Comment by djhi** [comment]
I think the code @ballad89 posted shows that we shouldn't assume the GraphQL API will return a 403.

> It assumes it always succeeds

No it assumes the client will throw an error if anything went wrong and that error will bubble up to the authProvider if it does have a status field with value `403` ou `401`.

> I believe you can add a Link Middleware to turn HTTP errors into meaningful exceptions

I think this is indeed the way to go if you can't modify your API to actually throw the correct error. I won't be able to help you further on this either. I suggest you ask on StackOverflow

**Comment by maebert** [comment]
@ballad89 Did you ever figure out how to throw the appropriate error with a custom Apollo client?

**Comment by ballad89** [comment]
@maebert No, unfortunately none of the suggestions above worked, so I parked it for now

**Comment by maebert** [comment]
@ballad89 I worked around it by supplying a `schema.json` to `buildGraphQLProvider` - that way the introspection query gets skipped, and the data provider gets build and resolves its Promise (regardless of whether it can actually talk to your graphql endpoint).

**Comment by djhi** [comment]
See https://github.com/marmelab/react-admin/pull/3604#discussion_r317957663

**Comment by aymanbagabas** [comment]
> See [#3604 (comment)](https://github.com/marmelab/react-admin/pull/3604#discussion_r317957663)

I see that however, I have a `null` check in `render()` checking `this.state.dataProvider` which doesn't get set if Apollo returns an error. My workaround was to return a function that throws an error with the status code since react-admin expects a function for dataProvider.

```
    const httpLink = createHttpLink(options);
    const errorLink = onError(({ networkError }) => {
      if (networkError.statusCode < 200 || networkError.statusCode >= 300) {
        networkError.status = networkError.statusCode;
        this.setState({
          dataProvider: function() {
            throw networkError;
          },
        });
      }
    });
```

If I remove the null check the app fails since dataProvider is null.

**Comment by diorgeneseugenio** [comment]
Any news about this problem? I'm with this same problem.

![image](https://user-images.githubusercontent.com/20167342/124184227-a2b6ce80-da8f-11eb-9e2c-9ba92b744349.png)
