### ISSUE TITLE
graphql-demo does not work since v2.4.0

### ISSUE THREAD

**Issue by cyrill62** [marmelab/react-admin#2990]
**What you were expecting:**

Try the demo with a GraphQL backend.

```sh
make run-graphql-demo
```

**What happened instead:**

Once you build & run the graphql-demo, at the first page load the graphql-js lib does not load properly.

At line : `/* WEBPACK VAR INJECTION */}.call(this, require("./../../process/browser.js")))`

**Steps to reproduce:**

```sh
git checkout v2.7.3
make install
make build
make run-graphql-demo
```

**Environment**

* React-admin version: 2.4.0 to 2.8.0
* Last version that did not exhibit the issue (if applicable): 2.3.4
* React version: 16.3.2
* NodeJS version : 10.15.3
* Browser: Firefox - Chrome
* Stack trace (in case of a JS error):
```js
ReferenceError: require is not defined 8.chunk.js:10937:1
```

**Comment by djhi** [comment]
Thans for reporting.
