### ISSUE TITLE
AutocompleteInput throws an error if resource[optionText] isn't a string

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#2991]
Hi guys

I noticed in [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/AutocompleteInput.js#L181), if the result field from api response is null, (usually when first input is put in page), then `suggestionLabel.toString()` will throw an error saying null doesn't have method `toString`.

What do you think about this? Should we put a default filter to avoid being null, or convert to string differently?

**Comment by djhi** [comment]
> if the result field from api response is null, (usually when first input is put in page)

I don't understand this.

> Should we put a default filter to avoid being null

Why are you referring the filter ?

**Comment by developerium** [comment]
This is the code I'm using to get around the error
```
<ReferenceInput
    {...props}
    source={source}
    reference="User"
    filterToQuery={searchText => ({ name: searchText, is_employee: 1 })}
  >
    <AutocompleteInput optionText={item => (item.name ? item.name : '')} />
  </ReferenceInput>

```
In the autocomplete, for the optionText prop, if I just gave `optionText="name" `, and api gave a response, in which even one row has `name=null` , this [line](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/AutocompleteInput.js#L181) will throw an error.

Because it is trying to run `.toString` on null .

**Comment by Kmaschta** [comment]
We surely can improve this error message, but we'll not be able to do much.
If the data we need to display the item isn't preset, we can at best remove it from the result list.

**Comment by developerium** [comment]
Yes I agree, some missing data should not crash the app.
What is the best way to handle this? Maybe I can contribute if you put me in the right direction

**Comment by fzaninotto** [comment]
I think the fix is as easy as adding an empty string (`''`) as third parameter to the `get()` call line 183 of AutocompleteInput:

https://github.com/marmelab/react-admin/blob/af8f2da75bd18e1f3009a568e49594d95f652f53/packages/ra-ui-materialui/src/input/AutocompleteInput.js#L176-L189

`Lodash.get()` uses the third parameter as a default value.

**Comment by Kmaschta** [comment]
IMO it's a better idea to filter the erroneous results and display an error in the console.

@developerium It's up to you! PR are welcome :)

**Comment by developerium** [comment]
@fzaninotto I agree, will you put this in your next release or should I make a pull request? since it's a minor change?

**Comment by fzaninotto** [comment]
you can make a pull request against master for that.
