### ISSUE TITLE
Datagrid Row expansion not working

### ISSUE THREAD

**Issue by zohaib055** [marmelab/react-admin#3003]
Row expansion not working here is the code

```javascript
 <List {...props} bulkActions={false} filters={<Filters />}  perPage={100}>
        <Datagrid rexpand={<Details />}>
            <TextField source="name" />
            <TextField source="email" />
            <TextField source="phone" />
        </Datagrid>
    </List>
```

**Comment by fzaninotto** [comment]
It's working in the demo, see https://marmelab.com/react-admin-demo/#/invoices. There is probably something wrong with your react-admin version, browser, Details component, etc, but we'll never know since you didn't use the issue template.

**Comment by zohaib055** [comment]
> It's working in the demo, see https://marmelab.com/react-admin-demo/#/invoices. There is probably something wrong with your react-admin version, browser, Details component, etc, but we'll never know since you didn't use the issue template.

yes i have seen the demo mine react-admin version is  2.8.1

**Comment by fzaninotto** [comment]
again, please follow the issue template. Your issue doesn't provide enough details to allow us to reproduce your problem.

**Comment by zohaib055** [comment]
Thanks for following the issue has been fixed have restarted the server
