### ISSUE TITLE
Unused prop debounce in Filter

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#3012]
Hi guys

I think [this](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/Filter.js#L96) `debounce` property is not used at all.

Instead List accepts debounce and actually uses it [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/ListController.tsx#L179).

**Comment by fzaninotto** [comment]
Indeed, thanks for the report. Would you mind removing this prop in a PR?

**Comment by developerium** [comment]
From the master branch or the next?

**Comment by fzaninotto** [comment]
It's a bug fix, it can go against master.

**Comment by developerium** [comment]
Had to make sure :+1:

**Comment by fzaninotto** [comment]
I invite you to leave your issue open until we merge the PR. And by the way, GitHub will close it automatically if the PR descriptino contains "Closes #[issue number]".

**Comment by fzaninotto** [comment]
Fixed by #3015
