### ISSUE TITLE
Tutorial ends with error "You should not use <Link> outside a <Router>"

### ISSUE THREAD

**Issue by dzoudzou** [marmelab/react-admin#3018]
Tutorial ends with an error.
`You should not use <Link> outside a <Router>`

**Comment by eligao** [comment]
I just noticed the bug only appears on desktop view:
![image](https://user-images.githubusercontent.com/2323992/54530453-c7213680-49bd-11e9-81f8-330733e4671d.png)
On a phone or when the window is small enough, this page renders as a mobile view and doesn't suffer from this bug.
![14nl4pw6k4 codesandbox io_(iPhone 6_7_8)](https://user-images.githubusercontent.com/2323992/54530530-fd5eb600-49bd-11e9-8100-79b81c8e0492.png)

**Comment by MiMo42** [comment]
Same here with my project.
`yarn upgrade`
grabs the v4.4.0 release of react-router as a dependency for react-admin.
Dependency hell...

I had to change the react-router dependency NOT to use the version 4.4.0 of react-router.
Using react-router 4.4.0 my app sends lots of warnings about deprecated require statements to the console and also ends with `You should not use <Link> outside a <Router>` error.

The release tagged as "Latest release" (it's the 4.3.1) of react-router does work.

**Comment by fzaninotto** [comment]
what's the "Tutorial ends with an error."? Can you please provide a sample project triggering the issue?

Also, since it seems to be a regression on the react-router side, did any of the commenter here open an issue in the react-router repository?

**Comment by vaiulian** [comment]
Been having this issue all morning.

so this weekend it seems react-router and react-router-dom changed versions:

https://github.com/ReactTraining/react-router/issues/6630

"You should not use react-router-dom version 4.3.1 with react-router 4.4.0."

i managed to bypass this issue using this https://github.com/ReactTraining/react-router/issues/6630#issuecomment-473512044

**Comment by vaiulian** [comment]
There is also an issue with the history@4.8.0 - deprecating 

`var createHistory = require('history/createMemoryHistory');`

Instead, use:

`var createHistory = require("history").createMemoryHistory;`

https://github.com/ReactTraining/history/releases

So my big "FIX" is something like 

 ` "resolutions": {
    "react-router": "4.2.0",
    "react-router-dom": "4.2.0",
    "history": "4.7.2"
  },` for react-admin@2.7.0

Still some changes to react-admin core needs to be done.

**Comment by nagad814** [comment]
Please fix this breaking change; I am getting ready for a demo. Would probably downgrade or try working around.

**Comment by eligao** [comment]
> what's the "Tutorial ends with an error."? Can you please provide a sample project triggering the issue?
> 
> Also, since it seems to be a regression on the react-router side, did any of the commenter here open an issue in the react-router repository?

Check out my example (https://codesandbox.io/s/14nl4pw6k4) from my issue #3019

**Comment by fzaninotto** [comment]
The react-router team seems to have fixed the problem on their side.

https://github.com/ReactTraining/react-router/issues/6630

Can you please remove your node_modules, run `yarn` again and check if it fixes the bug?

**Comment by MiMo42** [comment]
@fzaninotto 
Yes, this fixed the bug for me. 
Thanks!

**Comment by MiMo42** [comment]
@vaiulian 
I added Issue #3028 for the warnings due to deprecated requires of history@4.8.0
