### ISSUE TITLE
[Feature request] restore ability to inject custom <Link /> used by the core/ui.

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#3025]
**Is your feature request related to a problem? Please describe.**

We found the `<Link />` to be not sufficient for lifecycle reason. This is why we have created our own, and use our own within an application.

React admin is using `<Link />` from [react-router-dom](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom) package.
We'd like to use [<`Link` />](https://github.com/yeutech-lab/react-router-dom-utils#link) from [`@yeutech-lab/react-router-dom-utils`](https://www.npmjs.com/package/@yeutech-lab/react-router-dom-utils)

**Describe the solution you'd like**

Perhaps normalizing the import within react-admin. This means doing something similar of what have beeing done for the translation system.

As an example, the translation system is configured within 2 sources, it provides an adapter for react-admin sources. In other words, it creates all it needs for react-admin libs to do a translation without having to import polyglot on top of each sources.

This helped us do [react-admin-intl](https://github.com/yeutech-lab/react-admin-intl) to tweak the translation system for [react-intl](https://github.com/yahoo/react-intl).

This could be done as follow `ra-core/src/Link.js`:

```jsx
import { Link as DefaultLink } from 'react-router-dom';

function Link({ tag: Tag, ...rest }) {
  return <Tag {...rest} />;
}

Link.defaultProps = {
  tag: DefaultLink,
};

export default Link;
```

Imports within react-admin libs **should not** be `import { Link } from 'react-admin'`, in fact, if we do like this, we won't be able to override the Link component using `webpack.resolve.alias`, for instance:

```jsx
import { Link as DefaultLink } from 'ra-core';
import { Link } from '@yeutech-lab/react-router-dom-utils';

export default (props) => <DefaultLink tag={Link} {...props} />;
```

This can be hooked using `webpack.resolve.alias['ra-core/lib/Link.js']` quite easily, but core libs must use that link for the alias to work, we can't hook a replacement for the whole `react-router-dom` (it will be bad)

**Describe alternatives you've considered**

Using `webpack.resolve.alias['react-router-dom']`, but that is risky as it will tweak the whole webpack for our link component, this is probably not the best option.

If there are better options, we are interested to know them.

Of course, there is a last option, to use a custom lib that will use those custom link, what I criticise is the amount of code to maintain with the present strategy for a simple replacement. 

Historically, admin-on-rest was using an adapter for all Link within it's source code, it is now deprecated.

**Additional context**

Our `<Link />` provide lifecycle event before and after triggering the page change, allowing us to play animation and preload views that use react-loadable.

For example, these lifecycles are necessary to animate a loading progress indicator.

**Comment by fzaninotto** [comment]
I must be missing something, I don't see how your proposal would work:

```js
import { Link as DefaultLink } from 'react-router-dom';

function Link({ tag: Tag, ...rest }) {
  return <Tag {...rest} />;
}

Link.defaultProps = {
  tag: DefaultLink,
};

export default Link;
```

Even though this allows you to use a custom link by setting the `tag` prop, you'd have to override all react-admin components that currently use react-router-dom `Link` to pass them this `tag` prop by hand. How is that different from overriding these components to call your own `Link` instead?

Also, our custom `Link` is deprecated. A quick search shows that it's only used once in the codebase, in `SimpleList`. The rest of the imports are from 'react-router-dom'. So we don't do any `import { Link } from 'react-admin'`. I don't see how we could move to an import from `ra-core`.

You're asking for a deep dependency injection container, and this is not a path we want to take as it introduces a lot of complexity (cf Angular). Besides, you can use your custom `Link` by overriding components with links by your own components calling your own `Link`.

**Comment by kopax** [comment]
@fzaninotto you misunderstood my purposition, this is what I would do:

1. create `src/Link.js` in `ra-core`
2. Edit all import within `ra-core` and `ra-ui-materialui` to use `import Link from 'ra-core/lib/Link'`

This will not be breaking for any of users because it will keep using the `<Link />` from `react-router-dom` by default.

The necessity of `tag` **is different**, if later you decide to add features in `react-admin` links, then we could rely on it for our code base. 

If we don't, the file could just contain `export { default as Link } from 'react-router-dom/Link';'

In every case, using `import Link from 'react-router-dom/Link` would not require to import the whole lib, and would not oblige us to use an alias to replace the whole `react-router-dom` lib to do that.

This will not only help us to hook our `<Link />` without rewriting a bunch of component, it will also reduce the bundle size, and it is quite safe.

Right now the import used is `import { Link } from 'react-router-dom'`, we could at least change that?

**Comment by fzaninotto** [comment]
I still don't understand. How is it different to use a component from `ra-core` rather than `react-router-dom`?

**Comment by kopax** [comment]
When you use the entry point of react-router-dom, you will import the whole lib. The interest is to permit the usage of webpack.alias to replace that quickly without editing the whole source code. It is a strategy used by some lib author such as react-styleguidist for overriding the default component easily.

**Comment by fzaninotto** [comment]
Well, I'm -1 for that. What you ask for react-router, anyone can ask for other dependencies, like `react-redux` or `redux-form`. It doesn't make sense to alias and reexport every function imported from an external package just to support fine grained overriding as you ask. Again, we won't implement a dependency injection container, with or without webpack.alias.

I really advise you to build your own components based on your own Link implementation.

**Comment by kopax** [comment]
I guess that's not too much work either. Thanks anyway.
