### ISSUE TITLE
ra-core: Warnings due to deprecated requires referencing history@4.8.0 package

### ISSUE THREAD

**Issue by MiMo42** [marmelab/react-admin#3028]
At least ra-core package performs deprecated require calls.

See release notes for v4.8.0  of history package:
https://github.com/ReactTraining/history/releases

Accordingly we get warnings in the console:
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.

**Steps to reproduce:**
Perform 
`yarn upgrade`
to get the latest packages and load page.

**Environment**

* React-admin version: 2.8.2

**Comment by germanattanasio** [comment]
Hi @fzaninotto, I had this issue which I was able to fix by updating the library.
Thanks for all your hard work with react-admin! It's truly inspiring 🙌
