### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by tusmenko** [marmelab/react-admin#3035]
**What you were expecting:**

**What happened instead:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
?

**Comment by tusmenko** [comment]
Should I open new one, on you'll reopen this one?

**Comment by fzaninotto** [comment]
Please open a new one, notifications for this issue are still labeled with the original (short) title.

**Comment by tusmenko** [comment]
Ok, done!
