### ISSUE TITLE
Can't apply filters on fields with tree (nested) path.

### ISSUE THREAD

**Issue by tusmenko** [marmelab/react-admin#3037]
**What you were expecting:**

Defining Filter object for List, when you add a field with a source like "parent.child" I expect to have them filtering by values on that path, accessible same way as In Edit view components.

**What happened instead:**

Corresponding field successfully rendering, but putting there any value filters-off all rows.

**Steps to reproduce:**

Add any filtration field in your Filter object with source like "user.gender". 
Putting any expected (gender) value to this filter input will filter-off all rows, including expected to be shown.  

**Related code:**

I've added option to PostList filters to enable filtration by backlinks.backlinks.url value.
 <TextInput label="Backlink URL" source="backlinks.backlinks.url" alwaysOn />

Example:
https://codesandbox.io/s/wqm1jrq7lw

After entering any value from example data (like "http://example.com/bar/baz.html") will clear all data grid.

**Environment**

* React-admin version: 2.8.2
* React version: 16.8.4
* Browser: Chrome

**Comment by djhi** [comment]
I fixed the filter with path issue in #4347. However, your example uses backlinks which contains an array of objects. I'm not sure the dataProvider which use https://github.com/marmelab/FakeRest can handle this kind of filters.

With #4347, this is the filter sent to the API:
```json
{
    "backlinks":{"url":"http://example.com/foo/bar.html"}
}
```

I believe this is correct but it must be handled properly by the API.
