### ISSUE TITLE
Deleting item from Edit view shows "response.data is undefined"

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3041]
**What you were expecting:**
The confirmation dialog closes with a notification like "Element deleted" after the item was deleted.

**What happened instead:**
- The item is deleted successfully. HTTP status code is 200.
- React-admin shows a notification with "response.data is undefined".
- The confirmation dialog only closes if the user clicks somewhere outside the dialog.

**Steps to reproduce:**
1. Open the `List` view for a resource.
2. Select an item and open the `Edit` view.
3. From the `Edit` view choose "Delete" and confirm.

![image](https://user-images.githubusercontent.com/18437455/54825006-c681ec00-4cac-11e9-85e1-87d52488ff24.png)

![image](https://user-images.githubusercontent.com/18437455/54825016-ceda2700-4cac-11e9-9638-bcb932385953.png)

**Environment**
* React-admin version: 2.8.2
* React version: 16.8.4
* Browser: Firefox 66.0

**Comment by kopax** [comment]
You must write a proper `dataProvider` that can work with react-admin. This includes requirements for request/response body format.

In this case, I believe your `delete` response should be adapted so `response.data` is not undefined.

For instance, this is how `convertHTTPResponseToRest`  convert and return my `default` response case:

    return json ? { data: parseData(data) || json } : { data: {} };

**Comment by straurob** [comment]
> You must write a proper [`dataProvider`](https://marmelab.com/react-admin/CreateEdit.html#the-create-and-edit-components) that can work with react-admin. This includes requirements for request/response body format.

I forgot to mention that this behavior does not occur when deleting the item directly from the `List` view. So my guess was that this might be related to the confirmation dialog.

**Comment by kopax** [comment]
Could you try to add return logging in your `convertHTTPResponseToRest` function and compare those two case?

**Comment by fzaninotto** [comment]
No news for some time, closing.
