### ISSUE TITLE
Layout using Flex grid and not allowing subcomponent to shrink to available space

### ISSUE THREAD

**Issue by red1** [marmelab/react-admin#3048]
**What you were expecting:**
Subcomponents in a display inline-flex mode, should shrink to the available component width
**What happened instead:**
Subcomponents are not shrinking causing an horizontal scroll of the whole admin panel

**Reference:**
Please refer to : 
https://dfmcphee.com/flex-items-and-min-width-0/
By default, flex items won’t shrink below their minimum content size, you need to force it with a min-width:0
https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored

**Environment**
* React-admin version:
```
"dependencies": {
    "chartist": "^0.11.0",
    "prop-types": "^15.7.2",
    "ra-data-json-server": "^2.8.0",
    "ra-input-rich-text": "^2.7.3",
    "ra-ui-materialui": "^2.8.1",
    "react": "^16.8.4",
    "react-admin": "^2.8.1",
    "react-beautiful-dnd": "^10.1.0",
    "react-chartist": "^0.13.3",
    "react-dom": "^16.8.4",
    "react-scripts": "2.1.8"
...
```
* Browser: all

**Comment by red1** [comment]
I submitted the PR3045 for fixing this

**Comment by Luwangel** [comment]
I cannot reproduce. See the comment in the related PR #3045.
