### ISSUE TITLE
The Save button on the Edit page does not work if the list page is outside a <Layout> 

### ISSUE THREAD

**Issue by shawnchen1980** [marmelab/react-admin#3049]
**What you were expecting:**

I want to show some pages about a certain resource without the head bar and side bar. So I defined a custom layout like follows:
```
// in src/Layout.js
import React from "react";
import { Layout } from "react-admin";
import { withRouter } from "react-router-dom";
import MyAppBar from "./components/AppBar";


const MyLayout = props => {
  
  let result;
  if (
    props.location.pathname === "/signup/" ||
    props.location.pathname === "/MyResource"
  )
    result = props.children;
  else
    result = (
      <Layout
        {...props}
        appBar={MyAppBar}
       
      />
    );
   return result;
};

export default withRouter(MyLayout);

//in app.js
import layout from "./Layout";
...
<Admin
          loginPage={Login}
          history={history}
          appLayout={layout}
          customRoutes={customRoutes}
          authProvider={auth}
...
        >
```
**What happened instead:**

I generate the edit and list pages with guessers. I tried to edit some values, press the save button. The page jumps to the list view, but the actual fetch action is not carried out until I click again into the item just edited.

Only the list view is not attached with the Layout component. When I pressed the save button, I saw the "RA/CRUD_UPDATE_OPTIMISTIC" action but without the "RA/STOP_OPTIMISTIC_MODE" as normally I would see. Is this an intended behavior?

**Comment by fzaninotto** [comment]
There is no bug in react-admin. 

Your problem is probably because your layout doesn't contain the Notification component. It's this component that completes the optimistic save. 

Try adding a Notification component, or using undoable="false" in the Edit component.

**Comment by andrei22b** [comment]
> There is no bug in react-admin.
> 
> Your problem is probably because your layout doesn't contain the Notification component. It's this component that completes the optimistic save.
> 
> Try adding a Notification component, or using undoable="false" in the Edit component.

Thank you! Save me alot of time! Was not getting the **update** action from the **Save button**
