### ISSUE TITLE
missing 'x-total-count' but it exists in the response header

### ISSUE THREAD

**Issue by kdong007** [marmelab/react-admin#3050]
**What you were expecting:**
no more complains about 'x-total-count'

**What happened instead:**
missing 'x-total-count'

**Steps to reproduce:**
on client side
```jsx
 <Admin dataProvider={jsonServerProvider("http://localhost:8000")}>
             //...
            </Admin>
```

on server side
```js
app.get("/company", async (req, res) => {
   // ...
    const total = await Company.count();
    res.set("x-total-count", total);
    res.send(data);
});

```

**Other information:**
tracked down to convertDataRequestToHTTP
the only header in the response is `content-type application/json; charset=utf-8`
all other headers got removed?

**Environment**

* React-admin version: 2.8.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.4
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by JBaczuk** [comment]
If it helps anyone, as the warning suggests, I had to add:

`res.header('Access-Control-Expose-Headers', 'X-Total-Count')`

in my express app to the response.
