### ISSUE TITLE
TypeError: state.i18n is undefined

### ISSUE THREAD

**Issue by dexterns88** [marmelab/react-admin#3051]
**What you were expecting:**
To set up and work.

**What happened instead:**
Get error in console state.i18n is undefined

**Related code:**
`import PropTypes from 'prop-types'
import React, { Component } from 'react'
import { Admin, Resource } from 'react-admin';
import englishMessages from 'ra-language-english';
import jsonServerProvider from 'ra-data-json-server';
import createHistory from 'history/createBrowserHistory';

const historyAdmin = createHistory();

const messages = {
  en: englishMessages,
}

const dataProvider = jsonServerProvider('http://jsonplaceholder.typicode.com');

const i18nProvider = () => messages['en']

class Administration extends Component {
  constructor () {
    super()
  }

  render() {
    return {
      < Admin
        i18nProvider={i18nProvider}
        history={historyAdmin}
        dataProvider={dataProvider}
        title="My Admin"
      >...</ Admin>
    }
  }
}`

**Environment**

* React-admin version: 2.8.2
* React version: 16.8.2

* Stack trace (in case of a JS error):
TypeError: state.i18n is undefined

**Comment by dimgrav** [comment]
@dexterns88 how did you solve this?
