### ISSUE TITLE
In Tree-component, every node adds a nested Ripple-effect on hover which kills performance

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#3062]
**What you were expecting:**

In ra-tree-ui-materialui, nested nodes don't create additional ripple effects

**What happened instead:**

Every nested nodes gets darker and creates an additional ripple effects which uses a lot of performance

**Steps to reproduce:**

Create a nested tree with ra-tree-ui-materialui and expand it. hover over one entry

**Related code:**

-

**Other information:**

the problem is visible even on the screencast: https://github.com/marmelab/react-admin/tree/4cf148571b9ec80493bca6979b2825ab2dd5e603/packages/ra-tree-ui-materialui 

**Environment**

* React-admin version: ^2.8.3
* Last version that did not exhibit the issue (if applicable): -
* React version: 16.8.*
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Yes, that's not the only performance issue by the way... That why this package is labelled `lab` in our documentation and should probably not be used in production yet. We have plan to improve it but I don't know when we'll have time to address it.

**Comment by macrozone** [comment]
@djhi if you accept PRs, i might to add some improvements on it

**Comment by djhi** [comment]
Please do ! :heart_eyes:

**Comment by hacktisch** [comment]
PR fix: https://github.com/marmelab/react-admin/pull/3427

**Comment by fzaninotto** [comment]
This will be fixed by #3379

**Comment by fzaninotto** [comment]
Fixed by #3771
