### ISSUE TITLE
Provide RichTextInput with classes and className handling for customization.

### ISSUE THREAD

**Issue by tusmenko** [marmelab/react-admin#3070]
**Is your feature request related to a problem? Please describe.**
I found no way to set RichTextInput's height to be not dependent on text size, moreover - no way to customize any styles of RichTextInput's.

**Describe the solution you'd like**
I'd like to implement classes and className props handling to pass them to corresponding blocks.

**Additional context**
I've already implemented it on localhost, but have no access to create a branch for pull request)

**Comment by djhi** [comment]
> I've already implemented it on localhost, but have no access to create a branch for pull request

I don't get this. Can you explain?

**Comment by Kmaschta** [comment]
In order to submit a pull request, you have to fork the repository, push a new branch on your repo and submit a PR to this repository from your branch.

Here is a detailed explanation: https://help.github.com/en/articles/creating-a-pull-request

**Comment by fzaninotto** [comment]
RichtextInput use Quill, and you can customize Quill by setting `options` in `<RichtextInput>`. Can you explain what you tried to achieve exactly and why you couldn't do it in Quill?

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by abumalick** [comment]
@fzaninotto I had the problem, I didn't find how to add css to Quill options directly.
So to simply add a minimum height to the editor we must use css.

I would like to be able to do this for example:
```
<StyledRichTextInput
        source="content"
        css={{'.ql-editor': {minHeight: 300}}}
        fullWidth
      />
```

For this, my proposition is to add the className passed to the RightTextInput here: https://github.com/marmelab/react-admin/blob/master/packages/ra-input-rich-text/src/index.js#L96

Would you accept a PR for this?

**Comment by andreasradloff** [comment]
I would also be interested in this. Quill editor in itself set a height of 100% but the wrapper created by the RichTextInput does not have any min height. It can not be styled using the guide in the ra-admin docs, classes are not set correctly.

**Comment by RoastVeg** [comment]
Please reopen this issue. I am also unable set a `min-height` to class `ql-editor`, as it appears Quill does not support it via its own options and instead expects you to supply the CSS yourself.

**Comment by RoastVeg** [comment]
As a follow up to this (and for the benefit of anyone else who wants to adjust the rich text CSS from within react-admin), you can use `variant` instead, which attaches itself to the inner `ql-container`. It does not allow you to modify classes in the toolbar, but it solves the `min-height` issue.

I would still suggest adding `className` (and possibly `formClassName`) to this Component - `className` is implied by the Documentation as being common to all Input components, and yet is strangely omitted in this.
