### ISSUE TITLE
Tutorial CORS errors when using DuckDuckGo Privacy Essentials extension 

### ISSUE THREAD

**Issue by handreistoicescu** [marmelab/react-admin#3071]
Lost a whole day trying to follow the tutorial and having a CORS error in the console:

`Access to fetch at 'http://jsonplaceholder.typicode.com/users?_end=10&_order=DESC&_sort=id&_start=0' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

I read tons of bug reports related to CORS here, all answered in the lines of "you don't understand CORS, go to StackOverflow, n00b".

Finally found that a very popular browser extension, namely DuckDuckGo Privacy Essentials, was causing the problem. I disabled it and all the problems were gone.

Is there anything to be done about that? And, if not, maybe adding a line in the tutorial mentioning the problems with that extension?

**Comment by djhi** [comment]
Sorry about that but we can't possibly track this kind of things. There a just too many extensions for too many browsers.

**Comment by handreistoicescu** [comment]
Of course there are, but DuckDuckGo Privacy Essentials is one of the more popular. Putting a notice about that in the docs would help reduce the number of CORS user issues and greatly improve the tutorial.
