### ISSUE TITLE
ra-input-rich-text breaks when using special characters 

### ISSUE THREAD

**Issue by JakobRobijns** [marmelab/react-admin#3073]
**What you were expecting:**

I wanted to use  RichTextInput from 'ra-input-rich-text' like normal use. 

**What happened instead:**

When trying to insert some Spanish content text _("ARTÍCULO 1.- El presente reglamento es de observancia obligatoria")_, and make the "ARTÍCULO" bold (or another action), it keeps creating paragrafs.
After searching why, it's the 'Í' that breaks it. (It's a variant of the normal 'I' used in Spanish.

Edit: It's not only the 'I', other characters also break it.

**Steps to reproduce:**

-Create an react-admin application and use RichTextInput from 'ra-input-rich-text'.
-Try inserting content with the letter 'Í'.
-Make it bold/italic/...

**Related code:**

`
import RichTextInput from 'ra-input-rich-text';
`
`            <RichTextInput source="description" />
`

**Other information:**

[GIF of the bug](https://i.imgur.com/DJvbvOS.gif)

**Environment**

* React-admin version:  2.8.4
* Last version that did not exhibit the issue (if applicable): /
* React version: 16.8.5
* Browser: Firefox & Chrome
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment]
We are using the latest version of `quill@1.3.6` for this rich text component.
Mind you check that this bug is related to their code or to our implementation of the rich text?

Thanks

**Comment by JakobRobijns** [comment]
@fzaninotto Tnx. I also tried it on other quill plugins (React-Quill Demo - https://codepen.io/alexkrolick/pen/xgyOXQ)  & (https://github.com/zenoamaro/react-quill) And I can't reproduce it.

**Comment by roychoo** [comment]
@JakobRobijns @fzaninotto i think this is due to the integration of Quill,
mainly 2 issues i think,

1. after conversion of text to delta, quill seems to add p tag for sentences that has special characters
2. due to that, and the way that it is checking whether it is required to update the component, it goes into an infinite loop of adding p tags.

i have made a fix but i am not sure if that is the best way.
