### ISSUE TITLE
How to use react-admin with the latest version of material-ui?

### ISSUE THREAD

**Issue by dgkmurthy** [marmelab/react-admin#3075]
We would like to use mix of custom components along with react-admin based on the latest version of Material-UI.  

As I understand the current version of react-admin is using material-ui 1.4.  

How to use react-admin with the latest version of Material-UI such as v3.9.3 or later?

**Comment by djhi** [comment]
Duplicate of #2399

**Comment by fzaninotto** [comment]
see #3102
