### ISSUE TITLE
Error: Invariant failed: You should not use <Route> outside a <Router>

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#3078]
When installing react-admin and including dependency `"react-router-dom": "5.0.0"` to package.json, an error occurs when using `customRoutes`.

> Warning: Missing translation for key: "Error: Invariant failed: You should not use <Route> outside a <Router>"

Here's the show case. https://codesandbox.io/s/n0wq5lxkp

I just burned a few hours to narrow down the react-admin app only to find out that even the bare minimum revealed the same error. I only needed to remove dependency `"react-router-dom": "5.0.0"` from package.json to fix the error.

**Comment by christiaanwesterbeek** [comment]
I'm closing this issue immediately. If somebody else has the same problem in the future, a search engine and this issue will be their friend.

**Comment by daominhsangvn** [comment]
Hi, how can i get rid of this ? I having similar issue when trying to add a custom route.

**Comment by christiaanwesterbeek** [comment]
@daominhsangvn 

Check your `package.json` at the `dependecies` or `devDependencies` section. Do you see `"react-router-dom": ...` in there? If so, remove that line, call `yarn` (which is shorthand for yarn `install` or `npm install` if you use npm) and re-run your app.

**Comment by talentAN** [comment]
> When installing react-admin and including dependency `"react-router-dom": "5.0.0"` to package.json, an error occurs when using `customRoutes`.
> 
> > Error: Invariant failed: You should not use `<Route>` outside a `<Router>`
> 
> Here's the show case. https://codesandbox.io/s/n0wq5lxkp
> 
> I just burned a few hours to narrow down the react-admin app only to find out that even the bare minimum revealed the same error. I only needed to remove dependency `"react-router-dom": "5.0.0"` from package.json to fix the error.

Besides, do remember:
1. remove your lock file like (yarn.lock or npm.lock) and node_modules;
2.  run the yarn install or npm insall;
3.  recompile your codes, it will totaly work~ .

**Comment by zhangriyueming** [comment]
@christiaanwesterbeek @talentAN ,
But after did that, wouldn't it cause errors like `Cannot resolve module `react-router-dom`.`?

**Comment by mbchoa** [comment]
@christiaanwesterbeek @NiMaGangFour 

How are you both using the `Route` component without having the `react-router-dom` depdendency? Am I missing something here?

**Comment by christiaanwesterbeek** [comment]
Because react-admin itself has a `react-router-dom` dependency. Are you using react-admin? If so, your own app should depend on react-admin. react-admin depends on `react-router-dom`.

**Comment by macscripter** [comment]
> Because react-admin itself has a `react-router-dom` dependency. Are you using react-admin? If so, your own app should depend on react-admin. react-admin depends on `react-router-dom`.

Whay did you assume that everyone has react-router-dom dependency? In my case I don't have it and this message is probably related to a different issue I have in my code

**Comment by kopax** [comment]
@christiaanwesterbeek if in your source, you are importing `react-router-dom`, then it should appear in your `package.json`, other way around is to let react-admin expose `react-router-dom itself. This is due to dependency management, that expect to have valid import listed within the package.json.

**Comment by cucumberslice** [comment]
I would not recommend deleting react-router-dom from the package.json. unless you are not using it at all. its wiser to 
import { BrowserRouter, Link} from 'react-router-dom
and wrap Link inside of BrowserRouter
<BrowserRouter>
       <Link to="/" className="item">Cats</Link>
</BrowserRouter>

**Comment by jeyadharanigithub** [comment]
import React, { Component } from "react";
import { BrowserRouter, Switch, Route } from "react-router-dom";
import SearchComponent from "./search";
import LoginForm from "./loginform";

class App extends Component {
  render() {
    return (
      <React.Fragment>
        <BrowserRouter>
          <div>
            <Route path="/search" component={SearchComponent} />
            <Route path="/loginform" component={LoginForm} />
          </div>
        </BrowserRouter>
      </React.Fragment>
    );
  }
}

export default App;

**Comment by warren922** [comment]
I fix it by:

checking the version in `react-admin` by  
`yarn list react-router-dom`  

then, change your version of `react-router-dom` to the same as `react-admin` one by editing your `package.json`

type `yarn install`

DONE!!!

**Comment by vishnukgcherupuzha** [comment]
The error is correct. You need to wrap the Switch with BrowserRouter or other alternatives like HashRouter, MemoryRouter. This is because BrowserRouter and alternatives are the common low-level interface for all router components and they make use of the HTML 5 history API, and you need this to navigate back and forth between your routes.

Try doing this rather

import { BrowserRouter, Switch, Route } from 'react-router-dom';
And then wrap everything like this

<BrowserRouter>
 <Switch>
  //your routes here
 </Switch>
</BrowserRouter>

**Comment by vishnukgcherupuzha** [comment]
The error is correct. You need to wrap the Switch with BrowserRouter or other alternatives like HashRouter, MemoryRouter. This is because BrowserRouter and alternatives are the common low-level interface for all router components and they make use of the HTML 5 history API, and you need this to navigate back and forth between your routes.

Try doing this rather

import { BrowserRouter, Switch, Route } from 'react-router-dom';
And then wrap everything like this

<BrowserRouter>
 <Switch>
  //your routes here
 </Switch>
</BrowserRouter>

**Comment by vishnukgcherupuzha** [comment]
The error is correct. You need to wrap the Switch with BrowserRouter or other alternatives like HashRouter, MemoryRouter. This is because BrowserRouter and alternatives are the common low-level interface for all router components and they make use of the HTML 5 history API, and you need this to navigate back and forth between your routes.

Try doing this rather

import { BrowserRouter, Switch, Route } from 'react-router-dom';
And then wrap everything like this

`<BrowserRouter>
 <Switch>
  //your routes here
 </Switch>
</BrowserRouter>`

**Comment by anil-mirge** [comment]
This could also happen specifically when you have not import BrowserRouter from 'react-router-dom' inside of your index.js file. Ideally, you wrap your root component (<App>) inside of BrowserRouter inside of index.js file in your react project like so --

import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import App from './App';
ReactDOM.render(
   <BrowserRouter>
        <App />
   </BrowserRouter>, document.getElementById('root'));

**Comment by anil-mirge** [comment]
This could also happen specifically when you have not imported the BrowserRouter class from 'react-router-dom' inside of your index.js file. Ideally, you wrap your root component (<App>) inside of BrowserRouter inside of index.js file in your react project like so --

import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import App from './App';
ReactDOM.render(
   <BrowserRouter>
        <App />
   </BrowserRouter>,  document.getElementById('root'));

**Comment by anil-mirge** [comment]
This could also happen specifically when you have not imported the BrowserRouter class from 'react-router-dom' inside of your index.js file. Ideally, you wrap your root component (<App>) inside of BrowserRouter inside of index.js file in your react project like so --

import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import App from './App';
ReactDOM.render(
   <BrowserRouter><App /></BrowserRouter>, document.getElementById('root'));

**Comment by anil-mirge** [comment]
This could also happen specifically when you have not imported the BrowserRouter class from 'react-router-dom' inside of your index.js file. Ideally, you wrap your root component () inside of BrowserRouter inside of index.js file in your react project like so --
ReactDOM.render(
   <BrowserRouter>
        <App />
   </BrowserRouter>, document.getElementById('root'));

**Comment by anil-mirge** [comment]
This could also happen specifically when you have not imported the BrowserRouter class from 'react-router-dom' inside of your index.js file. Ideally, you wrap your root component (<App>) inside of BrowserRouter inside of index.js file in your react project like so --

`import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import App from './App';

ReactDOM.render(
   <BrowserRouter>
        <App />
   </BrowserRouter>, document.getElementById('root'));`

**Comment by anil-mirge** [comment]
This could also happen specifically when you have not imported the BrowserRouter class from 'react-router-dom' inside of your index.js file. Ideally, you wrap your root component (<App>) inside of BrowserRouter inside of index.js file in your react project like so --

**Comment by anil-mirge** [comment]
ReactDOM.render(`<BrowserRouter><App/></BrowserRouter>`, document.getElementById('root'));

**Comment by kimkablitz** [comment]
For me react-router and react-router-dom just dont work the same way, check your packages version and compatibility.

**Comment by xtfs** [comment]
Reinforcing what @kimkablitz wrote.
DO NOT use both (react-router and react-router-dom)  choose one.
I particular prefer react-router-dom because I use Link component.

**Comment by josias-r** [comment]
This error could be caused, when you use npm link somepackage to locally link a package w/ react-router-dom installed too.

Possible fix (w/ reat-app-rewired):

const path = require("path");
const { override, addWebpackAlias } = require("customize-cra");

module.exports = override(
  addWebpackAlias({
    react: path.resolve("./node_modules/react"),
    "react-router": path.resolve("./node_modules/react-router"),
    "react-router-dom": path.resolve("./node_modules/react-router-dom"),
  }),
);

**Comment by ramteen85** [comment]
> I'm closing this issue immediately. If somebody else has the same problem in the future, a search engine and this issue will be their friend.

dick.
to be fair i used a search engine just to read your useless crap.
Im sure some of the rest of us did too. the least you could do is not be selfish and try be helpful.
if not stay out of it and let someone else answer the question!

**Comment by kambleaa007** [comment]
i dont have devDependencies

**Comment by timotgl** [comment]
> I fix it by:
> 
> checking the version in `react-admin` by
> `yarn list react-router-dom`
> 
> then, change your version of `react-router-dom` to the same as `react-admin` one by editing your `package.json`
> 
> type `yarn install`
> 
> DONE!!!

This was the only thing that worked for me as well. Had to change `"react-router-dom": "5.1.2"` in `package.json`.

**Comment by thakurprakhar** [comment]
I am not using react-admin in my project (as per package.json) only react-dom and my code looks something like this:
`import { BrowserRouter, Link } from "react-router-dom";
<BrowserRouter>
        <Link to="/mypage">
        <li className=""><span>Home</span></li>
        </Link>
</BrowserRouter>`

And yet i keep getting the error: "Uncaught Error: Invariant failed" any suggestions?

**Comment by nghiatle** [comment]
> This could also happen specifically when you have not imported the BrowserRouter class from 'react-router-dom' inside of your index.js file. Ideally, you wrap your root component `<App>` inside of BrowserRouter inside of index.js file in your react project like so --
> 
> import React from 'react';
> import ReactDOM from 'react-dom';
> import { BrowserRouter } from 'react-router-dom';
> import './index.css';
> import App from './App';
> 
> ReactDOM.render(`<BrowserRouter><App/></BrowserRouter>`, document.getElementById('root'));

it worked

**Comment by aniketmarwade** [comment]
go to index.js and wrap your <App /> in Browse router like this <BrowserRouter><App/></BrowserRouter> and import import {BrowserRouter} from 'react-router-dom';


before that make sure you've installed 'react-router-dom'

**Comment by asura02** [comment]
For those who get Switch issue after December 2021 :-
Alternate solution :
1). Uninstall Previous Version-
npm uninstall react-router-dom
2). Install Older version-
npm install react-router-dom@5.0.0

**Comment by IChowdhury01** [comment]
What worked for me:
Find all instances of importing withRouter, BrowserRouter, or Route.
Make sure you're importing from react-router-dom and not react-router.
Remove react-router from package.json
