### ISSUE TITLE
AutocompleteInput-container-338

### ISSUE THREAD

**Issue by anuraram12345** [marmelab/react-admin#3079]
**Is your feature request related to a problem? Please describe.**
I am not able to give helperText in AutoComplete

**Describe the solution you'd like**
i need helper text option in AutoComplete

**Describe alternatives you've considered**
onChange option ,I want to change the html value

**Additional context**

**Comment by fzaninotto** [comment]
Hi, you've already posted your question as #3072, and we've already answered there. Please stop opening duplicate issues or you'll be banned from this repository. There will be no other warning.
