### ISSUE TITLE
Add custom action for CreateButton

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3101]
**Describe the solution you'd like**
Similar to the mechanism how to overwrite the default actions for the `List` component I'd like to specifically override the action of the `CreateButton` only.

**Describe alternatives you've considered**
The description of [how to replace the default actions](https://marmelab.com/react-admin/List.html#actions) for the `List` component would probably work. However it seems as if I then needed to "re-implement" all the other actions like export, refresh, etc.

**Comment by djhi** [comment]
> However it seems as if I then needed to "re-implement" all the other actions like export, refresh, etc.

Can you explain ?

**Comment by straurob** [comment]
> Can you explain ?

The example on https://marmelab.com/react-admin/List.html#actions is:

```
const PostActions = ({
    bulkActions,
    basePath,
    currentSort,
    displayedFilters,
    exporter,
    filters,
    filterValues,
    onUnselectItems,
    resource,
    selectedIds,
    showFilter,
    total
}) => (
    <CardActions>
        {bulkActions && React.cloneElement(bulkActions, {
            basePath,
            filterValues,
            resource,
            selectedIds,
            onUnselectItems,
        })}
        {filters && React.cloneElement(filters, {
            resource,
            showFilter,
            displayedFilters,
            filterValues,
            context: 'button',
        }) }
        <CreateButton basePath={basePath} />
        <ExportButton
            disabled={total === 0}
            resource={resource}
            sort={currentSort}
            filter={filterValues}
            exporter={exporter}
        />
        <RefreshButton />
        {/* Add your custom actions */}
        <Button color="primary" onClick={customAction}>Custom Action</Button>
    </CardActions>
);
```
From that example it looks like you need to define all those properties for filtering, selectedIds, resources, etc. Maybe my understanding is wrong but my idea is to implement a "custom behavior" for e.g. only the CreateButton.

**Comment by djhi** [comment]
Can you explain the solution you'd like ?

**Comment by straurob** [comment]
Sorry for the confusion. I'm still quite unexperienced with React. My use case is the following:

**Status Quo**
Here is an example of one of my `List` components. This provides the default button to create a new item which redirects the user to the `Create` view.

```
export const CountryList = props => (
  <List
    sort={{ field: "name", order: "ASC" }}
    filters={<CountryListFilter />}
    {...props}
  >
    <Datagrid>
      <TextField source="name" />
      <TextField source="iso3" />
      <EditButton />
    </Datagrid>
  </List>
);
```

**Desired Behavior**
Instead of an empty `Create` form I'd like to provide dynamic default values. If the user clicks on the "Create" button in the `List` view I'd like the following to happen:
- The application issues a custom GET request to an external server.
- The response data from that request is used to populate the `Create` form.

My idea was that I can somehow "overload" the default functionality of the create button.

**Comment by fzaninotto** [comment]
So you need to create a custom CreateButton for that, and replace the react-admin one in PostActions without yours. The current method allows for complete customization of the list actions at the cost of a bit of   code, and we don't want to add new options that would require new learning (and more complexity in the default PostActions implementation).

So we won't implement what you ask, but thanks for the suggestion!
