### ISSUE TITLE
FileInput onChange event that handles both file addition and removal

### ISSUE THREAD

**Issue by UltimateForm** [marmelab/react-admin#3103]
**Is your feature request related to a problem? Please describe.**
My poblem is that it is kind of clunky to manage files under FileInput.  Currently there is the onDrop prop passed through options prop, which I can't use because it blocks FileInput's onDrop listeners, I could use onChange (also passed through options) but this one only triggers when files are added through click and file explorer, when file is dropped it does not trigger. I can find ways to work around this with blocking the onDrop functions but setting the form manually through redux-form's change but I prefer a more natural reactadmin-like approach. **Also, I'm using the FileInput as ImageInput with the multiple files**

**Describe the solution you'd like**
I'd like an implementation that allowed me to know when a file was removed or added and I've noticed that FileInput.js has the onRemove and onDrop functions which it could use to call this new better (imo) onChange event

**Comment by tunglt1810** [comment]
I think solution for you in some article like this
https://medium.com/@650egor/simple-drag-and-drop-file-upload-in-react-2cb409d88929

**Comment by WiXSL** [comment]
This has been implemented along ago in #4140 and #4637. Plus the addition of #7003 in `next` should do it.
So I'm closing this issue.
