### ISSUE TITLE
Displaying "ra.*" instead of labels

### ISSUE THREAD

**Issue by RafeSacks** [marmelab/react-admin#3105]
Instead of labels being rendered I now see "ra.page.list", "ra.action.create", etc (see image):
![Screen Shot 2019-04-06 at 10 57 08 AM](https://user-images.githubusercontent.com/25697588/55673300-1b039a80-585b-11e9-9340-ed6996e38aec.png)

I'm not sure exactly when this started but I did just update to the latest react-admin and dropped my version of material-ui-core from 3.x to ^1.4.0.

**Comment by RafeSacks** [comment]
I updated a few dependencies, removed node_modules and the lock file and reinstalled and now it is fine. I don't know exactly what it was but I wanted to leave this issue in case anyone else ever sees this as I couldn't find mention when searching myself.

Here is the git diff of my packages.json file in case it helps:

    -    "react-admin": "^2.8.3",
    +    "react-admin": "^2.8.5",
    -    "react-scripts": "^2.1.5"
    +    "react-scripts": "^2.1.8",

**Comment by TheHyphen** [comment]
I have this exact issue now. I'll try your dependencies and see if it works for me.

**Comment by TheHyphen** [comment]
Just removing `yarn.lock` and running the build again worked for me too. Cheers!

**Comment by mithoska** [comment]
This happened to me as well, thanks for the howto! It worked for me too!

**Comment by JBaczuk** [comment]
I've got this problem, but removing the package-lock.json and running `npm install` again didn't fix it for me.

```
  "dependencies": {
    "base-64": "^0.1.0",
    "crypto-js": "^3.1.9-1",
    "ra-data-simple-rest": "^2.8.4",
    "ra-input-rich-text": "^2.8.3",
    "react": "^16.8.6",
    "react-admin": "^2.8.5",
    "react-dom": "^16.8.6",
    "react-scripts": "^2.1.8"
  },
```
