### ISSUE TITLE
Handle Nested arrays (array of arrays)

### ISSUE THREAD

**Issue by mithoska** [marmelab/react-admin#3107]
I have to create a form in react-admin that should deal with array of arrays.

I mean I have to choose from an array (this is simple so far) in Create and Edit view and depending on that array I have to reach another subarray.

So in code It's like this what I've done:

             <FormTab label="Jellemzok">
                 <ReferenceInput label="Tipus" source="type" reference="categories" validate={ required() } >
                     <AutocompleteInput optionText="name" />
                 </ReferenceInput>
                 <TextInput source="categories" validate={ required() } />
                 <AutocompleteArrayInput source="categories" choices={choices} optionText="name" optionValue="id" validate={ required() } allowEmpty={false} /> - this AutocompleteArrayInput should depend on my type choice - which currently I have no idea how to do.
                 <TextInput source="data_1" validate={ required() } /> - here depending on my type choice I have to provide different labels
                 <TextInput source="data_2" label="Kiegeszito adat" />
                 <TextInput source="data_3" />
                 <TextInput source="data_4" label="Kiegeszito adat"/>
                 <TextInput source="data_5" />
                 <TextInput source="data_6" label="Kiegeszito adat" />

I haven't found any evidence this exists in react-admin, hence the feature request.

react-admin version: 2.8.5

**Comment by djhi** [comment]
Hi and thanks for your question. This is achievable using the [`FormDataConsumer`](https://marmelab.com/react-admin/Inputs.html#linking-two-inputs). If you need help to use it, please ask a question on [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).
