### ISSUE TITLE
Allow different record cache strategy.

### ISSUE THREAD

**Issue by bamorim** [marmelab/react-admin#3110]
First, I'd like to use this opportunity to thank you for this excellent work! It has enabled us to deploy a full-fledged admin in less than one hour and also allowed us to move further when new features arrived. Thank you!

**Is your feature request related to a problem? Please describe.**
Here, we have some APIs that we want to include extra detail on the show action. That being said, our GET_LIST and GET_MANY_REFERENCE returns less information than our GET_ONE.
If I have a field that may be self-referencing and I'm using ReferenceField, what happens is that the show page loads and gets the resource with all the details. Then, the ReferenceField wants to load, then it sends a GET_MANY_REFERENCE essentially replacing the data with the one with lesser data.

**Describe the solution you'd like**
I'd like if subsequent requests would only "merge" instead of replacing the resource. 

So [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/reducer/admin/resource/data.ts#L79-L85) I'd instead "merge" `newRecordsById[id]` and `oldRecords[id]` instead of getting one or the other.

**Describe alternatives you've considered**
Instead of making this the default, maybe we could provide a merge function in a per-resource base and the default would do just that `const defaultMerge = (new, old) => new || old` but I'd be able to do something like `const myMerge = (new, old) => deepMerge(old || {}, new || {})`

What do you guys think?

**Comment by fzaninotto** [comment]
Thanks for your suggestion.

Sharing resources between pages is a strong architectural choice that allows many optimization (including optimistic rendering). This implies that the resources returned by the data provider are the same for the GET_LIST and GET_ONE verbs.

Any other behavior of the dataProvider isn't supported, as it may impact several parts of the code that assume resources are shared.

I'm sorry but we won't make that optional. Feel free to implement your own reducers and sagas without cache if you need it, but we won't add that to the core.
