### ISSUE TITLE
Upgrade to react-redux v7

### ISSUE THREAD

**Issue by komik966** [marmelab/react-admin#3114]
Yesterday was released new react-redux: https://github.com/reduxjs/react-redux/releases/tag/v7.0.1
It may be worth upgrading because convenient hook `useRedux` was implemented.
I think this upgrade should be scheduled for v3 of react-admin (BC break).

**Comment by djhi** [comment]
> React-Redux version 7 resolves the performance issues that were reported with version 6, and lays the groundwork for us to design and ship a public useRedux()-type Hooks API in a later 7.x release.

It does not yet provide `useRedux`
