### ISSUE TITLE
Scrollable tabs on TabForm

### ISSUE THREAD

**Issue by alauper** [marmelab/react-admin#3116]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want the possibility to scroll on <Tabs> of <TabbedForm>, when using mobile devices and there are many tabs, some become out of view and is not possible to scroll horizontally to see the hidden ones.

**Additional context**
Material-Ui <Tabs> component receives prop called scrollable that enables horizontal scrolling <TabbedForm> could receive the same prop.

This is similar to https://github.com/marmelab/react-admin/issues/2317 but for TabbedForm.

**Comment by fzaninotto** [comment]
Duplicate of #2317

**Comment by fzaninotto** [comment]
oops, sorry, I read too fast

**Comment by fzaninotto** [comment]
Fixed by #3288
