### ISSUE TITLE
[Feature Request] Fetch default values for SimpleForm from an API

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3117]
**Is your feature request related to a problem? Please describe.**
The `SimpleForm` component allows setting the `defaultValue` property for the component's default values. However this seems to be working only with "constant" values, e.g.

```
const myDefaultValues = {
  name: "John Doe",
  city: "New York"
};

<SimpleForm defaultValue={myDefaultValues}>
  <TextInput source="name" />
  <TextInput source="city" />
</SimpleForm>
```

**Describe the solution you'd like**
I'd like to have a feature which allows me to provide the default values from an API call. Please consider the following code snippet as an example in "pseudo-code" instead of a real working example.

```
function getDefaultValues() {
  axios.get("/somepath").then(response => {
    return {
      name: response.data.name,
      city: response.data.city
    }
  });
};

<SimpleForm defaultValue={myDefaultValues}>
  <TextInput source="name" />
  <TextInput source="city" />
</SimpleForm>
```

**Describe alternatives you've considered**
I tried to wrap the `SimpleForm` in a custom `Create` component but as far as I can tell this would require that I need write a lot of boilerplate code for handling the form, the save function, etc.

Additionally I read this in the [documentation](https://marmelab.com/react-admin/CreateEdit.html#the-create-and-edit-components):

> `<Create>` accepts a `record` prop, to initialize the form based on an value object.

But this seems to behave similar to the `defaultValue` property.

**Comment by komik966** [comment]
I had similar case: `update resource form` where first input is AutocompleteInput which after change populates `update resource form` with values from selected item.

Combining initializeForm action (https://github.com/marmelab/react-admin/blob/8f0922f913d58709617c12b952fe2a618ffcb8a8/packages/ra-core/src/actions/formActions.ts#L1) and api query utilities https://marmelab.com/react-admin/Actions.html gave desired effect but i think there might be better, simpler way.

**Comment by fzaninotto** [comment]
Hi, and thanks for bringing this subject.

SimpleForm aims to cover the most common use cases. For more specific cases like yours, you'll have to build your own form component based on Redux-form, using the Query API to fetch the default values from your data provider.

In other terms, this is not something we'll implement in the core. But if you do implement it, feel free to package it as an extension to react-admin, and open a PR to mention your extension in the Ecosystem page of the documentation.
