### ISSUE TITLE
[Feature] Versioning support for resources

### ISSUE THREAD

**Issue by capJavert** [marmelab/react-admin#3122]
### The problem
We are working with react-admin for better part of last year. Using the core functionalities and also extending to fit our specific needs. Our application backend has support for resource versions. 
As far as we know react-admin resources do not support versions. What we would like is to extended resource to support fetching and saving data through versions. 

### The feature
What we would like (example is article):
* if we have base article resource endpoint like: 
`GET /api/articles/:id` which fetches default/active article version
* then article should also support endpoint like:
`GET /api/articles/:id/versions/:version_id` which would fetch dedicated version of the article
* Also List of article component would have be able to fetch his versions from endpoint like:
`GET /api/articles/:id/versions` which should not override article resources in the redux state. (mental note: think about how and where it would be saved)
* As far as we know of this should be implemented inside `ListController`/`EditController`components
* We think that as most of the resource business logic is contained in those components we should extend those to support versions
* Also we think that as versions may not be needed for all users of react-admin that `Resource` component could have `boolean` prop that defines if versions are active or not for that resource. 
* Like this versions feature would not affect users that not use it and others would be able to turn it on per resource.

### So far..
What we implemented as a workaround so for is:
* custom loading logic (we use data provider instance to do custom API call and save versions to EditComponent state)
* we implemented HOC component to handle aditional saving logic
* we implemented custom route that handles version param and also renders EditComponent
* we implemented custom List component with Datagrid to show available versions 
* we use hidden field inside EditForm to pass params to UPDATE data provider call
* we have aditional logic inside our data provider to call versions endpoint if data object that is passed contains version_id from hidden form field

### What we expect from this thread:
* Do you have any plans for supporting this kind of feature inside v3.0 of react admin?
* Would you integrate this kind of feature inside ra-core and other react-admin packages if we worked on it and provided PR of that feature

Let us know,
thanks!

**Comment by djhi** [comment]
> Do you have any plans for supporting this kind of feature inside v3.0 of react admin?

No

> Would you integrate this kind of feature inside ra-core and other react-admin packages if we worked on it and provided PR of that feature

This is a very specific use case and as such, we won't integrate it the official packages. Besides, it seems it can be implemented in user land. Maybe you can create an addon for this and it to our ecosystem documentation ?

**Comment by capJavert** [comment]
> This is a very specific use case and as such, we won't integrate it the official packages. Besides, it seems it can be implemented in user land.

I don't think, personally, that this is specific feature. Also implementation would be such that it could be opt in for any user of react-admin. Maybe we can work on this little bit more and see if we can find some common ground about integrating this?

> Maybe you can create an addon for this and it to our ecosystem documentation ?

What do you mean by addon? Can you provide an example of some addon for react admin that is coming from community?

**Comment by djhi** [comment]
> I don't think, personally, that this is specific feature.

Keyword here is `personally`. Anyway, let's wait for @fzaninotto

> What do you mean by addon? Can you provide an example of some addon for react admin that is coming from community?

Sure: https://marmelab.com/react-admin/Ecosystem.html

**Comment by djhi** [comment]
Just to clarify, you could package your components (including a custom `Resource`) into a separate package

**Comment by capJavert** [comment]
Sure I get that, just that controller components hold lot of logic inside them. Because of that we would like to integrate this into the existing controllers. 

This would help us by allowing that we do not need to maintain separate Controller components (inside our own package) during react-admin updates.
We like how current controllers are implemented and how much features they cover but they do not provide much of configurability (I get if they are developed like that on purpose)

Maybe ideal solution is just to provide some additional configurability to your Controller components and that will allow us to make separate package and integrate it without much hassle.

Again we are open for much more detailed communication about implementation.

Would also like to here what @fzaninotto has to say 👍
Thanks!

**Comment by djhi** [comment]
Thanks for taking the time to explain your use case by the way :)

> Maybe ideal solution is just to provide some additional configurability to your Controller components and that will allow us to make separate package and integrate it without much hassle.

Would you mind to explore how we could allow that and maybe open a PR so we can discuss it further ?

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

I think the right way to model your business case is to have the latest version in the `articles` resource, and to have another resource called `article_versions`. That way, you just need REST endpoints on both resources to implement all the functionality you described.

As your implementation would be highly tied to a specific modeling of versioning APIs, and that there are other ways to model such things, I agree with @djhi: this kind of functionality belongs in an external package rather than the core. 

Unless the core forbids you to do it, which I don't think.
