### ISSUE TITLE
Query component does not update

### ISSUE THREAD

**Issue by RafeSacks** [marmelab/react-admin#3126]
**Background:**
The simple user story for background here is that I wanted to select a customer from a list and then display a list of locations associated with the customer to pick from. The first reference (customer) is sorted out by a `ReferenceInput` which then triggers a `FormDataConsumer` which renders a custom component which uses a `Query` to look up the customer data and then pass the locations list of ids to a nested `Query` to get the locations for use in a SelectInput. _(Let me know if it would be helpful to see the code implementing the pattern above.)_

**What you were expecting:**
When changing customers I expected the locations `SelectInput` to be re-rendered with the new customer's locations as choices

**What happened instead:**
When setting a customer the first time it all worked fine. When changing the customer after that initial time all the machinery fired off but the data in the Query was from the initial customer.

**Related code:**
I fixed the issue by implementing `componentDidUpdate`. I copied the react-admin `Query` component and replaced `componentDidMount` with all of the code here:

```
  queryAndSetState = () => {
    const { dataProvider, type, resource, payload, options } = this.props;
    dataProvider(type, resource, payload, options)
      .then(({ data, total }) => {
        this.setState({
          data,
          total,
          loading: false
        });
      })
      .catch(error => {
        this.setState({
          error,
          loading: false
        });
      });
  };

  componentDidMount = () => this.queryAndSetState();

  componentDidUpdate = prevProps => {
    // This should be enough to ensure we update when we want and avoid an infinte loop
    //   JSON pattern should work here since we already rely on it for the
    //   simple types used for query objects. We could also compare using
    //   ids only but more parsing would be needed.
    if ( JSON.stringify(prevProps.payload) === JSON.stringify(this.props.payload) ) {
      return;
    }

    this.queryAndSetState(prevProps);
  };
```

**Environment**
* React-admin version: `^2.8.5`
* React version: `^16.8.6`

**Comment by Kmaschta** [comment]
I agree, the `<Query>` component run a request at mount and never run any additional request, even in a case of a re-render / update / force update.

It would be great to provide a way to fetch the query again, either by re-render the component or with a children prop.

**Comment by RafeSacks** [comment]
> It would be great to provide a way to fetch the query again, either by re-render the component

The code I posted fixes the issue (assuming someone with more experience reviews it and agrees on the details). `componentDidUpdate` only runs after the component is re-rendered. Basically the loop is:

1. Component is re-rendered by React.
2. `componentDidUpdate` runs and funds the payload has changed, state is updated.
3. `setState` causes React re-render the component which reruns client-code children with updated data
4. `componentDidUpdate` runs again but exits due to the payload test (blocks infinite loop)

...Based on what I've read this is how React is supposed to do it (render 2 times) and `componentDidUpdate` is the recommended place to query external sources and update state.

**Comment by Kmaschta** [comment]
Thank you for the proposal, please open a PR so we'll be able to discuss about the code on it!

**Comment by ricardovf** [comment]
Need this too.

**Comment by RafeSacks** [comment]
Did you see my reply at the Merged link? I found an issue that will be considered a bug when someone else hits it.

**Comment by fzaninotto** [comment]
I have read it but not understood it. If there is a bug, please open a GitHub issue using the issue template, and allowing us to reproduce the bug.

**Comment by RafeSacks** [comment]
It isn't so much a bug as a pattern that needs to be included. Since querying is asynchronous it is possible that a component will be unmounted before control returns, creating a race that will cause an error. Check out the trashable react, a package that solves, and explains the core issue. I've used this in my implementation and it did the trick:
Explained: https://github.com/hjylewis/trashable#trashable-put_litter_in_its_place
HOC Package: https://www.npmjs.com/package/trashable-react
