### ISSUE TITLE
Support helperText in a BooleanInput

### ISSUE THREAD

**Issue by kctrlv** [marmelab/react-admin#3127]
**What you were expecting:**
I would like to be able to set a helperText in this input. I can do this in other inputs, such as
`<TextInput helperText='abc123' />` and 
`<RadioButtonGroupInput meta={ { helperText: 'abc123' } } />`
but currently there is no way to set it for a BooleanInput. 

**Other information:**
The reason is that FormHelperText is not included in the `BooleanInput.js` file. If it were, it would probably be as simple as copying lines 161-164 from `RadioButtonGroupInput.js`

**Comment by fzaninotto** [comment]
Hi, nice idea for an enhancement. Feel free to submit a PR about it.

**Comment by fzaninotto** [comment]
Fixed by #3339
