### ISSUE TITLE
Ability to pin or star records

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#3129]
**Is your feature request related to a problem? Please describe.**
As a user, I often view or edit the same record. I would like a way to find them easily

**Describe the solution you'd like**
I'm thinking about adding the ability to pin or star a record.

**Describe alternatives you've considered**
![image](https://media.giphy.com/media/8zr5dnZSDldNC/giphy.gif)

**Additional context**
In my case, I would like to pin/star where there is a checkbox (replace the checkbox with a star) since I don't use the checkbox

![image](https://user-images.githubusercontent.com/551837/56188518-02973b00-6026-11e9-9d52-9b555d839210.png)

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. This would be a nice addition, however we won't implement it in core as we don't think it belongs to 80% of use cases. I advise you to develop a standalone package for it, and publish it on npm. Then, we'll link to it in the Ecosystem documentation.
