### ISSUE TITLE
'record' prop in Toolbar does not get the values of 'ArrayInput' when they are changed

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#3143]
**What you were expecting:**
Toolbar `record` prop to have the changes of the `ArrayInput` values

This is what the REDUX state has:
![image](https://user-images.githubusercontent.com/7850073/56416380-52316d00-6299-11e9-8557-53b980e0d0f7.png)

**What happened instead:**
In Toolbar's `record`, the values are still empty:
![image](https://user-images.githubusercontent.com/7850073/56416438-89a01980-6299-11e9-9925-6c1d903f2427.png)

**Steps to reproduce:**

**Related code:**

```
<SimpleForm
      {...props}
      redirect={false}
      toolbar={<OurToolbar
        disableDelete
        showFormValues
        style={{clear: 'both'}}
      />}
    >
      <ArrayInput
        source="values.roles"
        label="Roles"
      >
        <SimpleFormIterator>
          <TextInput
            source="roleName"
            label="Role Name"
          />
          <BooleanInput
            label="Guests"
            source="guests"
          />
          <BooleanInput
            label="Appointments"
            source="appointments"
          />
          <BooleanInput
            label="Internet plans"
            source="internetPlans"
          />
          <BooleanInput
            label="Feedback"
            source="feedback"
          />
...etc...
```

**Other information:**

**Environment**

* React-admin version:  "react-admin": "^2.8.2",
* Last version that did not exhibit the issue (if applicable):
* React version:     "react": "^16.8.4",
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
That's a feature: The `record` prop contains the (unchanged) data from the dataProvider. The changes from the user inputs are stored in the redux-form. If you need those changes, you need to connect to the redux form.
