### ISSUE TITLE
AutocompleteInput shows current value as first suggestion

### ISSUE THREAD

**Issue by rgaino** [marmelab/react-admin#3148]
**What you were expecting:**
AutocompleteInput shows only the suggestions that match the criteria.

**What happened instead:**
Auto completeInput shows the previously selected value on top of the suggestion list, regardless if it matches the search criteria.

**Steps to reproduce:**
[On the demo](https://marmelab.com/react-admin-demo/#/), click on any order in `Pending orders`, then type something on the `Customer` field. You get the correct suggestions, so select one. Now go back and start typing another name. The input shows the previous selected suggestion on top of the suggestion list, regardless if it matches if the new text. 

**Related code:**
Behaviour is reproduced on the demo, no need for custom code.

**Other information:**
Is this really the expected behaviour?

**Comment by fzaninotto** [comment]
Fixed by #3031
