### ISSUE TITLE
[Feature request] Prevent default redirect behavior on rowClick

### ISSUE THREAD

**Issue by tunglt1810** [marmelab/react-admin#3155]
The first words, thanks for your awesome project.

My feature request related to a rowClick event on Datagrid. I have some custom action when click an item on a row. Sometime, i pick a row as a template data for a create form. But after rowClick event execute, default redirect event occurs too. So that my form have been reset and destroy.

I think if we want to prevent this default behavior just return nothing in rowClick event hanlder.

![image](https://user-images.githubusercontent.com/19906349/56559293-5fb56280-65cb-11e9-8e44-2dbe34c22451.png)

**Comment by fzaninotto** [comment]
I don't understand, what's the value of rowClick in your datagrid?

**Comment by tunglt1810** [comment]
> I don't understand, what's the value of rowClick in your datagrid?

This is my rowClick function
![image](https://user-images.githubusercontent.com/19906349/56569589-7667b380-65e3-11e9-932f-7888b999466d.png)

It return nothing, but there some actions occur
![image](https://user-images.githubusercontent.com/19906349/56569705-b4fd6e00-65e3-11e9-9af8-cbad93df1cdf.png)

**Comment by fzaninotto** [comment]
Understood, this is a normal use case. I'm tagging this as a feature request, don't hesitate to open a PR to implement it.
