### ISSUE TITLE
ArrayField sortable={false} console warnings

### ISSUE THREAD

**Issue by blamze** [marmelab/react-admin#3157]
Description:
Adding sortable={false} in ArrayField component prints react warrnings in console (**but it disables sorting**)

console error
_Warning: Received `false` for a non-boolean attribute `sortable`.
If you want to write it to the DOM, pass a string instead: sortable="false" or sortable={value.toString()}.
If you used to conditionally omit it with sortable={condition && value}, pass sortable={condition ? value : undefined} instead._

Actually, in all cases if you put it like 
`  <ArrayField source="categories" sortable}> `
or  
`  <ArrayField source="categories" sortable={true}> ` 
it says it want non-boolean , but if you provide string   - it says it wants boolean
 (_Warning: Failed prop type: Invalid prop `sortable` of type `string` supplied to `EnhancedArrayField`, expected `boolean`._)

**What you were expecting:**
Clean console

**What happened instead:**
http://prntscr.com/nfr89v

**Steps to reproduce:**
```jsx
<ArrayField source="categories" sortable={false}>
  <SingleFieldList>
     <ChipField source="title" />
  </SingleFieldList>
</ArrayField>
```

**Environment**
   "react": "16.8.6",
    "react-admin": "2.8.6",

**Comment by JasonasIgn** [comment]
Having this as well

**Comment by iamsimakov** [comment]
hey guys, I use ArrayField with Datagrid:
```
<ArrayField source="jobs">
  <Datagrid>
    <TextField source="status" />
    <TextField source="error" />
    <DateField source="updated_at" showTime />
  </Datagrid>
</ArrayField>
```
and now I see error on click column header:
```
Datagrid.js:162 Uncaught TypeError: _this.props.setSort is not a function
    at Datagrid._this.updateSort (Datagrid.js:162)
```

is this related with topic issue?

**Comment by fzaninotto** [comment]
Reproduced and confirmed.
