### ISSUE TITLE
[ChipField] allow to customize label

### ISSUE THREAD

**Issue by cherniavskii** [marmelab/react-admin#3162]
**Is your feature request related to a problem? Please describe.**
It's hard to customize `ChipField` label, e.g. use `firstName` + `lastName` instead of single field value.
Currently, it's possible to create custom component using `Chip` from `material-ui`, style it (add margins, like `ChipField` does).
We can make it way easier 🚀 

**Describe the solution you'd like**
Add `formatLabel` function prop. It will accept `record` as argument and return label.

```jsx
<ChipField formatLabel={record => `${record.firstName} ${record.lastName}`} />
```

**Describe alternatives you've considered**
There's an alternative, described above, but it's an overkill for such basic use case.

**Additional context**
I'd like to hear from you guys what do you think about that.
And, of course, I can submit a PR.

**Comment by cherniavskii** [comment]
**Current solution**:
```jsx
import React from 'react';
import PropTypes from 'prop-types';
import Chip from '@material-ui/core/Chip';
import withStyles from '@material-ui/core/styles/withStyles';

const styles = {
  root: {
    margin: 4,
  },
};

function CitizenChipField({ classes, record, onClick }) {
  const {
    firstName, lastName,
  } = record;
  return (
    <Chip className={classes.root} label={`${firstName} ${lastName}`} onClick={onClick} />
  );
}

CitizenChipField.propTypes = {
  classes: PropTypes.shape({}).isRequired,
  record: PropTypes.shape({}),
  onClick: PropTypes.func.isRequired,
};

CitizenChipField.defaultProps = {
  record: {},
};

export default withStyles(styles)(CitizenChipField);
```

**Proposed solution**:
```jsx
<ChipField formatLabel={record => `${record.firstName} ${record.lastName}`} />
```

**Comment by Kmaschta** [comment]
This might be useful for other fields too.
Instead of adding a new `formatLabel` prop, what about accepting a function as a label ?

Like:

```jsx
<ChipField label={record => `${record.firstName} ${record.lastName}`} />
```

**Comment by cherniavskii** [comment]
@Kmaschta given that in most parts of react-admin `label` is a string (and often path to translation value), it may be confusing.

**Comment by fzaninotto** [comment]
As explained in #3169, this is really easy enough to do in userland, so we won't implement it.
