### ISSUE TITLE
[Feature Request] Support custom PrimaryKey as an option

### ISSUE THREAD

**Issue by mnlbox** [marmelab/react-admin#3172]
**Is your feature request related to a problem? Please describe.**
I want use React-Admin with an exist database and can't modify all primary key's to `id`. Also it's difficult to create custom data provider and check all resource name with `switch / case` or `if / else` to override primarykey.

**Describe the solution you'd like**
I like to set **primaryKey** as a new option like this: (look at `primaryKey: "title"`)
```
<Resource name="posts" options={{ label: 'Posts', primaryKey: "title" }} list={PostList} />
```
With a new option like `options.primaryKey` we can set custom primary key more simpler than approach present in:
https://github.com/marmelab/react-admin/blob/a156c8fbe583477565901019a75caf8b928e0c5e/docs/FAQ.md#can-i-have-custom-identifiersprimary-keys-for-my-resources

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

We said several times in the past that we don't want to do that. It's a strong design decision, but it allows us to develop complex features with much better confidence.

The place to map the react-admin data structure (which requires an id primary key) and your data structure is the data provider. Creating a custom data provider is much less painful than to have to deal with passing the primary key name along in your components.

**Comment by mnlbox** [comment]
@fzaninotto based on your design decision so anyone need to use a customized version of dataProvider because also data provider can't pass parameter to React-Admin. Because of this limitation we forced to use many messy hack to customize React-Admin for example in Hasura community we forced to implement Postgres schema support with passing schema name with a `.` separator to `name` attribute in `<Resource />` component.
You can see result here: https://github.com/hasura/graphql-engine/pull/2068

Also as I talking with @praveenweb we forced to pass some other setting with similar hack (pass through `name` attribute value) I f you decide this approach it's better to first provide some customization approach and more customization docs.

With this design decision approach anyone forced to create a custom fork of existing data provider and re invent wheel. (For example you can see that many people want to customize primary key based on your approach all of that people forced to Fork existing data provider)

I think this approach increase messy forks and many recurring task but in the end it's up to you man :wink:

**Comment by fzaninotto** [comment]
> data provider can't pass parameter to React-Admin

Can you be more specific? What kind of data do you need to pass, and for what use case? 

Also, why fork a data provider ? You can just decorate an existing one with a function that does the FK translation.

**Comment by mnlbox** [comment]
@fzaninotto let's talking with code.
For example this is my admin panel:
```
<Admin
  title="Online Exam"
  dataProvider={hasuraDataProvider('http://localhost:12003', headers)}
  dashboard={Dashboard}>

  <Resource name="online_exam.difficulty" icon={ModeIcon} list={DifficultyList} show={DifficultyShow} create={DifficultyCreate} edit={DifficultyEdit} options={{ label: 'Difficulty' }}/>
  <Resource name="online_exam.subject" icon={ModeIcon} list={SubjectList} show={SubjectShow} create={SubjectCreate} edit={SubjectEdit} options={{ label: 'Subject' }}/>

</Admin>
```
If any `params` attribute available for `<Resource />` component that just pass value to `dataProvider` function data provider developers able to customize react-admin more simpler. For example for above `promaryKey` example we can use syntax like this:
```
<Resource name="online_exam.difficulty" icon={ModeIcon} list={DifficultyList} show={DifficultyShow} create={DifficultyCreate} edit={DifficultyEdit} options={{ label: 'Difficulty' }} customAttribute= {{ primaryKey: "title" }} />
```
As another example as you seen above we forced to pass `schema` name in `name` parameter as a messy hack. (as you see above in `name="online_exam.difficulty"` we forced to pass with a irreverent `name` parameter and use a `.` separator hack) If we can pass `customAttribute` to data provider through `Resource` component then we can pass this more cleaner like this:
```
<Resource name="difficulty" icon={ModeIcon} list={DifficultyList} show={DifficultyShow} create={DifficultyCreate} edit={DifficultyEdit} options={{ label: 'Difficulty' }} customAttribute= {{ schema: "online_exam" }} />
```
And access this attribute value in data provider function like this:
```
const convertHTTPResponse = (response, type, resource, params, customAttribute) => {

// customAttribute.primaryKey available here
// customAttribute.schema available here

}
```

**Comment by mnlbox** [comment]
> Also, why fork a data provider ? You can just decorate an existing one with a function that does the FK translation.

Can you explain this? Or provide some example or how to guide about this?

**Comment by djhi** [comment]
There is one in the documentation: https://marmelab.com/react-admin/DataProviders.html#decorating-your-data-provider-example-of-file-upload

**Comment by mnlbox** [comment]
@djhi Thanks for your attention.
Your [provided url](https://marmelab.com/react-admin/DataProviders.html#decorating-your-data-provider-example-of-file-upload) use `requestHandler => (type, resource, params)` but [FAQ guide use](https://github.com/marmelab/react-admin/blob/a156c8fbe583477565901019a75caf8b928e0c5e/docs/FAQ.md#can-i-have-custom-identifiersprimary-keys-for-my-resources) `(response, type, resource, params)` for customize primaryKey.
Can you explain this? :thinking: 
I think something is missing in docs. :thinking:

**Comment by fzaninotto** [comment]
The dataProvider has a signature `(type, resource, params) => Promise`. Internally, it can use a function to transform the response into the format expected by react-admin. This function has the signature `(response, type, resource, params) => Promise`. Please read the example data provider in the data providers documentation.

As for passing attributes and schema in the Resource, let me reiterate: this is not the way Resource was designed. Resource describes your UI, not your API. If you want to pass extra attributes to your data provider, then just use a factory function, something like:

```js
const MyDataProvider = (url, routes) => (type, resource, params) => {
   const apiRoute = url + (resource in routes) ? routes[resource].apiRoute : resource;
   // etc.
}

```

**Comment by mnlbox** [comment]
@fzaninotto So based on your guide and [this url](https://github.com/marmelab/react-admin/blob/a156c8fbe583477565901019a75caf8b928e0c5e/docs/FAQ.md#can-i-have-custom-identifiersprimary-keys-for-my-resources) we can change primaryKey just with fork and create a custom data provider and can't use decoration approach [like this](https://marmelab.com/react-admin/DataProviders.html#decorating-your-data-provider-example-of-file-upload)

Yes?
But I want a way to just customized existing data provider. I don't want create one data provider for each project based on database schema design :disappointed:

**Comment by fzaninotto** [comment]
You can use decoration, because the data provider is a simple function. If that function uses another function internally, it should not be a problem.

> But I want a way to just customized existing data provider. I don't want create / fork / fully customize one data provider for each project based on database schema design. 

I don't understand the difference, and anyway it's not react-admin's job to do that. The logic of mapping your resources to your API is your responsibility, and the data provider is the place to put that logic. How you organize your data provider depends on your style guidelines.

I'm closing this discussion as it looks more and more like a support request. that kind of discussion is better done on StackOverflow.
