### ISSUE TITLE
RejectButton is coded as AcceptButton

### ISSUE THREAD

**Issue by ericwb** [marmelab/react-admin#3178]
**What you were expecting:**
I would expect the code in [RejectButton.js](https://github.com/marmelab/react-admin/blob/master/examples/demo/src/reviews/RejectButton.js) to define a class called RejectButton.

**What happened instead:**
Take a look at [RejectButton.js](https://github.com/marmelab/react-admin/blob/master/examples/demo/src/reviews/RejectButton.js) and you'll notice the code defines a class named AcceptButton.  Seems a little confusing, because there is actual code for rejection and it's using the thumbs down icon.

**Steps to reproduce:**
Code inspection of [RejectButton.js](https://github.com/marmelab/react-admin/blob/master/examples/demo/src/reviews/RejectButton.js)

**Related code:**
N/A

**Other information:**
n/a

**Environment**

* React-admin version: master
* Last version that did not exhibit the issue (if applicable): n/a
* React version: n/a
* Browser: n/a
* Stack trace (in case of a JS error): n/a

**Comment by djhi** [comment]
Thanks for reporting. It looks like a bad copy/paste. Would you mind opening a PR to fix it ?

**Comment by ericwb** [comment]
Sure, will do

**Comment by fargito** [comment]
This issue should be closed, since a PR fixed it
