### ISSUE TITLE
Resource 'options.label' do not change the resource name in the title

### ISSUE THREAD

**Issue by Rakiah** [marmelab/react-admin#3179]
The documentation states nothing about changing the Title displayed for a resource, it by default uses name only

**Comment by Kmaschta** [comment]
Reproduced with the 2.9.3.

![image](https://user-images.githubusercontent.com/1819833/59326663-85b3d500-8ce7-11e9-8557-0d8dae443080.png)

**Comment by Kmaschta** [comment]
You can change the title of the resource list view with the [`title` prop of the `<List>` component](https://marmelab.com/react-admin/List.html#page-title) or by [changing the translations](https://marmelab.com/react-admin/Translation.html).
