### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by avciaytac** [marmelab/react-admin#3180]
Hi,
I need to install in Windows but i can not setup build.ps1 reason of security (Not Admin at PC) Do you have any other solution? 
Also I dont have yarn. When I tried to change package.json yarn to npm, still had some problem with yarn anyway.

Thank you.

**Comment by fzaninotto** [comment]
Please use StackOverflow for support questions.

**Comment by avciaytac** [comment]
https://stackoverflow.com/questions/55920167/need-support-for-install-react-admin-in-windows
