### ISSUE TITLE
Infinite fetch requests when using ReferenceField within TreeView

### ISSUE THREAD

**Issue by galbenyosef** [marmelab/react-admin#3189]
Hello ,
I'm fetching a reference field from 'locales' resource within TreeView:
How to reproduce:
```
export const LocaledTreeList = (props) => {
  return (
  <List {...props}>
    <Tree allowDropOnRoot enableDragAndDrop>
      <NodeView>
        <ArrayField source="locales">
          <Datagrid>
            <ReferenceField label="Locale" source="localeId" reference="locales" >
              <TextField source="name" />
            </ReferenceField>
            <TextField source="value" />
          </Datagrid>
        </ArrayField>
      </NodeView>
    </Tree>
  </List>)
}
```

the object that is being used to render a treeview list: 
```
[
  {
    "_id": "5ccc147c5fd4371bf0cb35ac",
    "locales": [
      {
        "localeId": "5cb61b12f7418a1e08b02ad1",
        "value": "Softi"
      }
    ]
  },
  {
    "_id": "5ccd780141108b3748c52962",
    "locales": [
      {
        "localeId": "5cb61b12f7418a1e08b02ad1",
        "value": "tsya"
      }
    ],
    "parent_id": "5ccc147c5fd4371bf0cb35ac",
  }
]
```
a 'locale' model:

```
const LocalesSchema = new Schema({
    name: String,
    symbol: String,
}, { versionKey:false })
```

The reference field and TreeView renders as expected and now displaying correct information, which means, the expected result is fine.
But now, infinite refresh actions happens because of infinite fetch requests are being sent to the server, which make it impossible to work with, because each fetch re-renders (infinitely),

server is getting requests infinitely:
```
GET /locales?filter=%7B%22id%22%3A%5B%225cb61b12f7418a1e08b02ad1%22%5D%7D 304 3.362 ms - -
GET /locales?filter=%7B%22id%22%3A%5B%225cb61b12f7418a1e08b02ad1%22%5D%7D 304 3.808 ms - -
GET /locales?filter=%7B%22id%22%3A%5B%225cb61b12f7418a1e08b02ad1%22%5D%7D 304 3.221 ms - -
GET /locales?filter=%7B%22id%22%3A%5B%225cb61b12f7418a1e08b02ad1%22%5D%7D 304 3.575 ms - -
GET /locales?filter=%7B%22id%22%3A%5B%225cb61b12f7418a1e08b02ad1%22%5D%7D 304 2.958 ms - -
```

Replacing ReferenceField will fix this infinite loop, but I must use it.

**What I'm expecting**
Expecting render one time after fetch.

**What happened instead:**
Infinite fetch requests.

**Steps to reproduce:**
As shown above

**No errors in stacktrace**

**Environment**
   "ra-data-simple-rest": "^2.9.0",
    "ra-tree-ui-materialui": "^2.8.5",
    "react": "^16.8.6",
    "react-admin": "^2.9.0",
    "react-dom": "^16.8.6",
    "react-scripts": "2.1.8"
chrome Version 73.0.3683.103

**Comment by fzaninotto** [comment]
Can you provider a CodeSandbox demonstrating the issue?

**Comment by galbenyosef** [comment]
I'm not sure, could anyone maybe provide working demonstration of ReferenceField within Tree ?
if it works well to one, ill do anything I can to solve this,I suspect it has nothing to do with my code but something in the package, also, I have nothing more to add because everything is explained in the issue, thanks in advanced,

**Comment by fzaninotto** [comment]
the issue template links to a CodeSandbox that already uses the Tree for tags. Please start from there and try and reproduce your issue.

**Comment by galbenyosef** [comment]
https://19z92435l.codesandbox.io/#/myCustomTreeList

or 

https://codesandbox.io/embed/19z92435l

and Tags tab, just as you guided me,
hopefully it will be clearer now, thanks,

**Comment by DaniilVysotskiy** [comment]
Same happens with `ReferenceArrayField` component - infinite fetching loops.

**Comment by djhi** [comment]
Closing this issue as we deprecated the tree package
