### ISSUE TITLE
Unexpected logout behavior

### ISSUE THREAD

**Issue by calebfaruki** [marmelab/react-admin#3197]
**What you were expecting:**

When the GraphQL server eventually responds with a `socket hang up` error, the `FETCH_ERROR` action is dispatched, the user should remain logged in.

**What happened instead:**

When a GraphQL query hangs and the server eventually responds with a `socket hang up` error, the `FETCH_ERROR` action is dispatched, initiating logout behavior once you navigate to another page.

**Steps to reproduce:**

1. Modify an existing GraphQL query on the server to not respond at all.
2. In `react-admin`, navigate the application as normal until the server closes the connection for said query.
3. When the socket hangs up, navigate to any page.

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Other information:**

**Environment**

* React-admin version: 2.8.5
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.8.6
* Browser: Chrome
* Stack trace (in case of a JS error): N/A

**Comment by MhdSyrwan** [comment]
For some reason, react-admin tries to call "AUTH_ERROR" on "FETCH_ERROR". In your auth provider, you need to make sure that the error is an AUTH_ERROR otherwise, just return Promise.resolve()

**Comment by fzaninotto** [comment]
Yep, that's not a react-admin bug, just changes you need to make in your dataProvider and authProvider.
