### ISSUE TITLE
FormTab not marked as error tab when the error is in input field using complex record path as source

### ISSUE THREAD

**Issue by iskrenantonov** [marmelab/react-admin#3200]
**What you were expecting:**
When there is an error in a tab - the tab should be marked as error tab and be colored in red.

**What happened instead:**
When the error is in input field which uses complex record path as source the tab is not marked as errored tab and not colored in red when looses focus

**Steps to reproduce:**
[![Edit simple](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wnmm51pxn?fontsize=14)
1.Edit some post.
2.In the form there is a TEST TAB. It has 2 fields using complex record path as source. They are required but empty.
3.The tab should be colored in red but it isn't.

**Related code:**
[![Edit simple](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wnmm51pxn?fontsize=14)

**Other information:**

**Environment**

* React-admin version: 2.9.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.6
* Browser: Opera
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
This is a limitation of the `<FormTab>` component that we can't fix in core. The solution is to fix it in user land, by subscribing to the form state, and manually assigning fields to tabs. Then, in a custom FormTab component, use this information to display the form title in red.
