### ISSUE TITLE
[ra-input-rich-text] validation doesn't rerun on input change

### ISSUE THREAD

**Issue by cherniavskii** [marmelab/react-admin#3206]
**What you were expecting:**

I expect no validation error when required rich text input has content

**What happened instead:**

Validation error persists, even when input is not empty anymore

**Steps to reproduce:**

1. Run simple example
2. Go to PostCreate.js
3. Add `validate={[required()]}` to `RichTextInput`
4. Try to edit rich text input

**Other information:**

![Screen-Recording-2019-05-09-at-15 47 35](https://user-images.githubusercontent.com/13808724/57459190-03ad3800-7273-11e9-8ebf-797eb84d5549.gif)

Looking at source code, there's `shouldComponentUpdate` method:

https://github.com/marmelab/react-admin/blob/cd560cb9ba6f78efd098449e5e3febcf26418f25/packages/ra-input-rich-text/src/index.js#L61-L63

But when it executes, both values are the same, therefore component doesn't rerender:

![Screenshot 2019-05-09 at 15 59 14](https://user-images.githubusercontent.com/13808724/57459492-a36ac600-7273-11e9-88d1-d9964e5ace44.png)

**Environment**

* React-admin version: 2.9.0
* ra-input-rich-text version: 2.8.6
* Last version that did not exhibit the issue (if applicable): N/A
* React version: N/A
* Browser: N/A
* Stack trace (in case of a JS error): N/A

**Comment by cherniavskii** [comment]
Looks like `this.props.input.value` should be used instead of `this.lastValueChange`.

**Comment by fzaninotto** [comment]
Confirmed and reproduced
