### ISSUE TITLE
[ra-input-rich-text] validation message shows up when field isn't touched

### ISSUE THREAD

**Issue by cherniavskii** [marmelab/react-admin#3207]
**What you were expecting:**

I expect no validation message, when input wasn't touched yet (same as regular input)

**What happened instead:**

Validation message is visible when field is untouched.

**Steps to reproduce:**

1. Run simple example
2. Go to PostCreate.js
3. Add `validate={[required()]}` to `RichTextInput`

**Other information:**

![Screenshot 2019-05-09 at 16 06 18](https://user-images.githubusercontent.com/13808724/57459975-8d113a00-7274-11e9-8c16-ade3e150febc.png)

There's no check if field is touched (like in other inputs).
I'll submit a PR

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Reopening since the PR was reverted

**Comment by fzaninotto** [comment]
Fixed by #3223
