### ISSUE TITLE
RichTextInput inside ArrayInput deletion issue

### ISSUE THREAD

**Issue by cherniavskii** [marmelab/react-admin#3220]
When using `RichTextInput` inside `ArrayInput`, deletion of single element doesn't work as expected.

**What you were expecting:**

Clicking Remove button removes element from array

**What happened instead:**

Clicking Remove button removes element from array and adds new empty item instead

**Steps to reproduce:**

Minimal example: https://codesandbox.io/s/zr7r9pn52p

1. Open post edit view.
2. Click Remove button on the last backlink item

**Related code:**

```jsx
<ArrayInput source="backlinks">
  <SimpleFormIterator>
    <RichTextInput source="url" />
  </SimpleFormIterator>
</ArrayInput>
```

**Other information:**

![mpjnt-ucdx1](https://user-images.githubusercontent.com/13808724/57706762-a6e0c180-7666-11e9-8eac-196a065ccabb.gif)

**Environment**

* React-admin version: 2.9.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by cherniavskii** [comment]
So, what's going on:

First of all, `text-change` event handle never gets removed, since it's reference is never stored:

https://github.com/marmelab/react-admin/blob/bcea168c4c3953b0f19de73aec99f5fa19aa3037/packages/ra-input-rich-text/src/index.js#L58

Second of all, after removing redux-form field, `RichTextInput` gets updated with empty string value.
This invokes `componentDidUpdate`, then `this.quill.setContents`:

https://github.com/marmelab/react-admin/blob/bcea168c4c3953b0f19de73aec99f5fa19aa3037/packages/ra-input-rich-text/src/index.js#L65-L69

After that, `onTextChange` is invoked, and finally `this.props.input.onChange`, which writes empty string as last array field in redux-form:
https://github.com/marmelab/react-admin/blob/bcea168c4c3953b0f19de73aec99f5fa19aa3037/packages/ra-input-rich-text/src/index.js#L82-L86

Then new array item appears with empty `RichTextInput`.

## Proposed solution

#3221 fixes wrong debouncing handling.
But doesn't solve problem completely, because of `TransitionGroup` in `SimpleFormIterator`.
It has timeout set to **500**ms (same as `RichTextInput` debounce timeout), so `RichTextInput` unmounts **after** debounced callback is fired.

Setting `timeout` to **450**ms in `SimpleFormIterator` resolves the issue completely.

My suggestion is first add `timeout` prop to `SimpleFormIterator`. Having timeout configurable, it'll be possible to demonstrate, that changing it's value may solve the problem.

That being said, #3221 is crucial for fixing this issue.

**Comment by Kmaschta** [comment]
I fixed the import error in your codesandbox : https://codesandbox.io/s/rlmq71qyj4

**Comment by cherniavskii** [comment]
@Kmaschta thanks!

**Comment by cherniavskii** [comment]
Workaround in user land if #3223 and #3226 got merged:

```diff
<ArrayInput source="backlinks">
-  <SimpleFormIterator>
+  <SimpleFormIterator TransitionProps={{ timeout: 400 }}>
    <RichTextInput source="url" />
  </SimpleFormIterator>
</ArrayInput>
```

**Comment by fzaninotto** [comment]
Cannot reproduce anymore on master (v3.16), it was probably solved by a previous PR.
