### ISSUE TITLE
Add complete Oauth (social login via Facebook/Instagram) example

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/react-admin#3222]
Complete Oauth (social login via Facebook/Instagram?) example will be extremely welcome!

_Originally posted by @deksden in https://github.com/marmelab/react-admin/issues/2957#issuecomment-490185524_

**Comment by Nilegfx** [comment]
any updates regarding this issue?

**Comment by Kmaschta** [comment]
I recently implemented an OpenID Connect authentication strategy with a react admin for a private project.

It's on my todo list to write such a thing! But it's unlikely that I'll publish something like that before the V3 release.
