### ISSUE TITLE
Unable to implement a forgot-password page

### ISSUE THREAD

**Issue by whnunlife** [marmelab/react-admin#3224]
**What you were expecting:**
Using the customRoutes.js, I was under the impression I could add a /forgot-password page.

**What happened instead:**
If the user is on the /login page and clicks on /forgot-password, the user is redirected back to the login page.

**Steps to reproduce:**
https://codesandbox.io/embed/z8zq9mzp

The goal here is trying to allow a url path (/forgot-password) that should be able to be hit without requiring user auth. I do have the authProvider and implemented a custom login page.

I wonder, if it would make sense to add another prop to the customRoutes, that allows the bypassing of the auth check. Which appears to be redirecting the user back to the /login page.

**Comment by cherniavskii** [comment]
@whnunlife here's working example: https://codesandbox.io/s/2j3w15k51j

What I did is basically following docs here: https://marmelab.com/react-admin/Admin.html#customroutes

**Comment by fzaninotto** [comment]
I'm closing this issue as it's more a "how-to" discussion - @cherniavskii's comment shows that the feature works fine in react-admin. Please use StackOverflow if you need more guidance - the answers are searchable there, and can be used by other developers.

**Comment by whnunlife** [comment]
Thanks @cherniavskii and @fzaninotto
