### ISSUE TITLE
Default 404 page should forward to login when unauthenticated

### ISSUE THREAD

**Issue by tusmenko** [marmelab/react-admin#3230]
**What you were expecting:**
When I'm setting up `authProvider` in `Admin` I'm expecting to not allow unauthenticated user to see internal app structure, ( especially the **Menu**), i.e not allow to get further than **Login** page. Even if I go via unexisting path, default 404 page should forward me to login, but not show the Layout.

**What happened instead:**
If user enters random url path, he is forwarded to default **404** page, and shows **Menu**, even user is unauthenticated.
This can be roughly fixed by implementing own **NotFound** page, wrapped in `<Authenticated> `HOC and pass it in `catchAll` prop, so it will forward you to Login page in this case.
This forces me to duplicate default  RA’s **NotFound** page code, if I want to keep page the same, or implement it from scratch, even if I’m OK with default.
In rare case, If you want to show **404** page for unauthenticated user for unexisting path (via `catchAll`), but hide the **Menu** in Layout - you have no option to set this as with `Route` in `customRoutes` with `noLayout` prop.

**Steps to reproduce:**
Setup Application with Auth.
Go to any unexisting url like "www.your-ra-app.com/unexistingurl" before Logging. 
See NotFount page with all Layout visible.

**Related code:**
Reproduced on default sandbox code:
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Environment**

* React-admin version: 2.8.6
* React version: 16.8.6
* Browser: Chrome

**Comment by Kmaschta** [comment]
Would be great for the v3!

**Comment by fzaninotto** [comment]
Fixed by #3243
