### ISSUE TITLE
Nothing listed in the list after change the row count per page

### ISSUE THREAD

**Issue by keeneagle** [marmelab/react-admin#3234]
Description:
- There's 17 clients created
- Change "Rows per page" to 5
- Select Page "4"
- Change "Rows per page" to 25

Sometimes the list is displayed empty, see below snapshot:
![image](https://user-images.githubusercontent.com/38956189/57831842-cdc70100-77e8-11e9-98e5-d5763ee20682.png)

From the network, we can see below 4 requests, the #3 one seems the cause of empty list problem, it had a wrong range.

https://test.com:3001/api/resources?filter={}&range=[0,4]&sort=["client_name","ASC"]
https://test.com:3001/api/resources?filter={}&range=[15,19]&sort=["client_name","ASC"]
**https://test.com:3001/api/resources?filter={}&range=[75,99]&sort=["client_name","ASC"]**
https://test.com:3001/api/resources?filter={}&range=[0,24]&sort=["client_name","ASC"]

Here's the Redux action snapshot: 
![image](https://user-images.githubusercontent.com/38956189/57832825-24cdd580-77eb-11e9-93b9-7a2492ffde55.png)

The left highlighted actions are all the actions when click "25" in the "Rows per page". The highlighted "RA/CRUD_GET_LIST_SUCCESS" result shows why the page displayed empty.

The first "RA/CRUD_GET_LIST_SUCCESS" got the good result:
![image](https://user-images.githubusercontent.com/38956189/57833605-ed602880-77ec-11e9-9b00-6d50d60c330e.png)

**Comment by fzaninotto** [comment]
Confirmed and reproduced. In the list controller, the function that handles a change of perPage should also reset the page to 1. Otherwise it doesn't make sense.

**Comment by keeneagle** [comment]
Right, it should also reset the page to 1. Thanks.
