### ISSUE TITLE
Customizing The Login and Logout Components by following documentation does not work

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#3237]
**What you were expecting:**

Copy/Paste of example code  to work

**What happened instead:**

Go to https://marmelab.com/react-admin/Authentication.html#customizing-the-login-and-logout-components

See the `{...sanitizeRestProps(rest)}` code. This will not work, as there is no `sanitizeRestProps` function in the example.

**Other information:**

**Environment**

* React-admin version:  2.9.1

**Comment by fzan** [comment]
i agree this is an error in the example.

I would ask moreover, if i found an error on your advanced blog post/tutorial, this is the correct place to report?
thanks

**Comment by Kmaschta** [comment]
@fzan I'm not sure, prefer to post a comment directly on the blog post. We'll receive a mail from Disqus
