### ISSUE TITLE
ArrayInput does not like primitive values

### ISSUE THREAD

**Issue by Veikedo** [marmelab/react-admin#3249]
**What happened instead:**

**Steps to reproduce:**
I have this form 
```
<ArrayInput source='configuration.xpathexpressions' label='XPath expressions'>
  <SimpleFormIterator>
    <TextInput label='XPath expression' />
  </SimpleFormIterator>
</ArrayInput>
```

Note - I don't have source prop in `TextInput`. 
And here what I see in the browser

![image](https://user-images.githubusercontent.com/5779339/58015701-961bca00-7b04-11e9-8e2e-06f3365a99b8.png)

The problem is with this line:
https://github.com/marmelab/react-admin/blob/5d2a88df4ed31d1f61aa0fee5519ee637354bedb/packages/ra-ui-materialui/src/form/SimpleFormIterator.js#L102

If we make it just `fields.push();` everything would work as expected, even for complex objects (ie with fields with `source` props)

**CodeSandbox**

https://codesandbox.io/s/simple-cwjuz

Here is the form with array input: https://cwjuz.codesandbox.io/#/tags/5

**Other information:**
A question on this topic https://stackoverflow.com/questions/51468966/react-admin-array-input-with-array-of-strings-numbers

**Environment**

* React-admin version: ^2.9.1
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.8.6

**Comment by Veikedo** [comment]
Create PR https://github.com/marmelab/react-admin/pull/3250

**Comment by mleczakm** [comment]
Are there any easy way to override this method ( `_this.addField` in `SimpleFormIterator`) in current implementation?

**Comment by taitems** [comment]
I'm hitting this issue now. Is there any interest in firing up the PR again, or a suitable workaround? I just want to have an array of URLs.
