### ISSUE TITLE
[RFC] Guesser with custom rules and fieldTypes

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#3256]
Current Situation:
Guesser can not always guess perfectly and it can only guess for elements in `ra-ui-materialui` package.
As more and more dataProviders, inputs, fields, and UI showing up in the ecosystem, the record value format and UI rendering varies a lot. Current Guesser cannot accommodate that.

Solution:
We suggest some customization on guessers.
These customization to List/Show/Edit Guessers includes:
1. Allow user to skip some keys in the record JSON
2. Allow user to add custom inference rule functions
3. As a follow up to 2, allow user to add custom field types

From user’s perspective
Before the change:
`<Resource name=”user” list={ListGuesser} />`

They can still write in the old way after the change
After the change:
`<Resource name=”user” list={p => <ListGuesser ...p skipfields=fieldsToSkip inferRules=[...myInferRules, ...defaultListInferRules, ...otherRules] fieldTypes={...myFieldTypes, ...defaultListFieldTypes, ...otherTypes} />} />`

This change will involve separating all if statements in `inferElementFromValues.js` to individual functions and export an array of functions in defaultInferRules. `inferElementFromValues.js` will run against a list of inferRules and return the element by the first matching rule. 
This change will also need to export list/show/edit FieldTypes from `ra-ui-materialui`.

The benefit of the proposed change is we may have `ra-inference-*` packages coming up in the community for specific dataProvider or specific inputs and fields. These inference packages only needs to export `inferRules` and `fieldTypes`. This can make the prototyping a lot easier.

**Comment by djhi** [comment]
Hi and thanks for your suggestion. The guessers are meant to be used to bootstrap your development only. We don't want to add so many props nor do we want to maintain this complexity. However, this is something completely doable in userland. Feel free to create a package for advanced guessers. We'll gladly include it in our documentation.

We might export our inference helper functions if it helps though.

**Comment by djhi** [comment]
Feel free to open a new issue if you need us to export more of our helpers related to inference

**Comment by djhi** [comment]
Can you be more specific ? Which helpers do you need ? Would you mind opening a pull request and we'll try to help!
