### ISSUE TITLE
Export objects to CSV

### ISSUE THREAD

**Issue by fargito** [marmelab/react-admin#3278]
**What you were expecting:**
When I click on the 'export to csv' button, the dowloaded file should not display [object Object] in any field

**Steps to reproduce:**
* Open the demo app
* Go to 'posts'
* Click the 'export' button
* In the dowloaded file, in the 'backlinks' column, there are [object Object] items

**Comment by fzaninotto** [comment]
Thanks for your report. 

In the general case, I don't think JSON is acceptable in a CSV. On the other hand, `[object Object]` forces the developer to design a well-crafted CSV format. So it's an acceptable default IMO.

Now I agree that the simple example should have a custom exporter. I'll mark that as a bug, but just for the demo app.

**Comment by fargito** [comment]
Ok perfect, I'll create a custom exporter for the demo app
