### ISSUE TITLE
Docs about MenuItemLink appear two times but with diferent code

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3295]
https://marmelab.com/react-admin/Admin.html#menu --> Correct
https://marmelab.com/react-admin/Theming.html#using-a-custom-menu -->Outdated

**Comment by djhi** [comment]
I see that the second example is wrong as it does not imports the `Responsive` component correctly. Can you explain why you think it is outdated though?

**Comment by WiXSL** [comment]
It is outdated because it lacks the use of the resource icon prop "leftIcon={createElement(resource.icon)}".

**Comment by fzaninotto** [comment]
Fixed by #3316
