### ISSUE TITLE
After creating an item, it is automatically navigating to the update route, expected to navigate to the list route

### ISSUE THREAD

**Issue by dmajumder4292** [marmelab/react-admin#3299]
When I create a new item is one of the tables, once the creation is successfull it navigates to the update route, for example, if my create item url is [localhost:3000/wallet/add](localhost:3000/wallet/add), then after creation, it is getting navigated to [localhost:3000/wallet/hjbsadh4hb5mn5tmfs](localhost:3000/wallet/hjbsadh4hb5mn5tmfs), here 'hjbsadh4hb5mn5tmfs' is assumed as the id of the newly created item, what I want to achieve is that after the creation is successful, it should navigate back to the list which shows all the items including the new one.

I'm not sure which part of the code will be relevant in this case, please let me know, if I have to share some code.

**Comment by djhi** [comment]
This is documented [here](https://marmelab.com/react-admin/CreateEdit.html#redirection-after-submission).
