### ISSUE TITLE
Issues with DELETE_MANY operation

### ISSUE THREAD

**Issue by dmajumder4292** [marmelab/react-admin#3300]
When I try to execute the DELETE_MANY operation, the DB is updated however there is an error/warning in the console "**Missing translation for key: "Not Found"**". Please check if this a bug or am I doing a mistake

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
No news for some time, closing.
