### ISSUE TITLE
form.record-form.values problem when navigate to edit page

### ISSUE THREAD

**Issue by lazjramos** [marmelab/react-admin#3302]
**What you were expecting:**
From the list of items, I should navigate to /items/1, save updates, be redirected to list of items, be able to enter another record at /items/2, see the values related to the /items/2 and make updates there.

**What happened instead:**
Occurs exactly the same sayed in the issue #[2053](https://github.com/marmelab/react-admin/issues/2053). In that case the developers talked that this will be fixed in the futures milestones but in the SimpleForm.js file still exists the code line:
destroyOnUnmount: false
In the options of the redux-form instance.
In other words: if you save the item1 information when you edit the item2 you will see the same information that item1. The edit form values was not updated

**Related code:**
      <Edit {...editProps} id={id} title={`Edit ${this.props.resourceTitle} #${id}`} className={styles.adminForm}>
        <SimpleForm className={styles.centeredForm}>
          <DisabledInput label="Id" source="id"/>
          {filteredInputs.map(({source, label, type, defaultValue}) => {
            return type === 'DECIMAL' || type === 'INTEGER' || type === 'BIGINT' ?
              <NumberInput key={source} source={source} label={label} defaultValue={defaultValue}/> :
              type === 'STRING' ? 
                <TextInput key={source} source={source} label={label} defaultValue={defaultValue}/> :
                type === 'DATE' ?
                  <DateInput key={source} source={source} label={label} defaultValue={defaultValue} parse={dateParser} format={dateFormatter}/> :
                  type === 'EXCELDATE' ?
                    <DateInput key={source} source={source} label={label} defaultValue={defaultValue} parse={excelDateParser} format={excelDateFormatter}/> :
                    type === 'BOOLEAN' ?
                      <BooleanInput key={source} source={source} label={label} defaultValue={defaultValue}/> : null
          })}
        </SimpleForm>
      </Edit>

**Environment**
React-Admin v2.9.2

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

PS: I did not manage to reproduce this on the codesandbox

**Comment by lazjramos** [comment]
Hi djhi. Thanks for quick response. I would like to share some pieces of code of the app and also share with you a video where you can see what happens when we use SimpleForm component. 
Please, let me know if you need something else. Also tell me if we must do this in another way.

Greetings !!!!
https://github.com/lazjramos/react-admin-trouble

**Comment by lazjramos** [comment]
Hi. It wasn't a bug, it was a mistake from the developer who programmed the app. The mistake is in the key of the rendered fields, its is always the same value.

Thanks for your attention
Greetings!

**Comment by lazjramos** [comment]
Hi guys, after many test the issue continues, it's very weird

**Comment by fzaninotto** [comment]
Please fork the react-admin codesandbox to try and reproduce your issue. That way you can isolate the problem and help us run your code (the CodeSandbox ships with a client-side dataProvider). 

To troubleshoot your code, please use StackOverflow.
