### ISSUE TITLE
What is reference attribute?

### ISSUE THREAD

**Issue by HyunSangWon** [marmelab/react-admin#3303]
Hi i'm junior developer
Thank you for your understanding that I'm not good at English ..
The photo below is a react-admin api picture.
![api](https://user-images.githubusercontent.com/34639434/58843362-19185500-86ad-11e9-93af-2ce405124283.PNG)

I have a two question.
frist, What does reference attribute in the <ReferenceInput> tag mean?

seconde, Is the reference attribute mean a Resource tag name?

**Comment by djhi** [comment]
Yes, it is a resource name specified on a `Resource` element. Here we're displaying an autocomplete input where you can type a post title. As we wrapped it inside a ReferenceInput, react-admin knows it has to request the posts resources and look for those havng a title matching what the users typed.

**Comment by djhi** [comment]
This is explained in the [tutorial](https://marmelab.com/react-admin/Tutorial.html#handling-relationships)

**Comment by HyunSangWon** [comment]
thank you~ ! !
