### ISSUE TITLE
DOM not updated if AUTH_GET_PERMISSIONS takes too long

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/react-admin#3307]
**What you were expecting:**

A simple conditional render as [documented here](https://marmelab.com/react-admin/Authorization.html#restricting-access-to-fields-and-inputs).

**What happened instead:**

The condition seems to work but the DOM isn't being updated.

**Steps to reproduce:**

I have the same issue with any List. See code snippet below.

**Related code:**

This is the List I've been testing this on:

```tsx
import * as React from 'react';
import { Datagrid, DeleteButton, EditButton, List, ShowButton, TextField } from 'react-admin';
import { LocaleFilter } from './LocaleFilter';

export const LocaleList = ({ permissions, ...props }: any) => {
  const scope = permissions === 'admin' ? <TextField source='scope' /> : null;

  console.log(permissions, { shouldShowScope });
  // null, {shouldShowScope: null}
  // null, {shouldShowScope: null}
  // 'admin', {shouldShowScope: Element}

  return (
    <List {...props} filters={<LocaleFilter />}>
      <Datagrid>
        {scope}
        <TextField source='locale' />
        <ShowButton label='' />
        <EditButton label='' />
        <DeleteButton label='' redirect={false}/>
      </Datagrid>
    </List>
  );
};
```

Like commented inline, this logs three times. `null`, `null` and finally 'admin'. So it does work, but for some reason it's just not being re-rendered on the page and the "scope" field never shows up.

**Other information:**

I've implemented my own authProvider and I've removed all other fluff to keep the example as simpel as possible:

```ts
if (type === AUTH_GET_PERMISSIONS) {
  return new Promise(resolve => setTimeout(() => resolve('admin'), 1000));
}
```

If the promise resolves fast enough, it works as expected. So if I change 1000 to 0 or 1 it does work. But if I take too long, it doesn't.

This is relevant because I use firebase to store and fetch the role of the user, which takes longer than 1 ms.

**I can work around it** by not rendering anything until I get what I expect:

```ts
  if (permissions === null) {
    return null;
  }
```

But this hides the underlying issue, rather than solving it.

**Environment**

* React-admin version: 2.9.1
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.8.6
* Browser: Chrome 74.0.3729.169
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
This is probably due to the overzealous optimization in ListController: the `shouldComponentUpdate` ignores changes in `permissions` (considering you pass `permissions` to the `List` component.

The fact that it works if the `authProvider` is fast is incidental - in fact, it works if the `authProvider` replies before the `dataProvider`, as the latter modifies several props that `shouldComponentUpdate` watches.

It's indeed a bug.

**Comment by fzaninotto** [comment]
Pushed to master by default, reverted in 3a23a677
