### ISSUE TITLE
Strange error after running fetchJson with 'no-cors' mode

### ISSUE THREAD

**Issue by gotthardp** [marmelab/react-admin#3314]
**What you were expecting:**
I am using the JSON Server Data Provider (`ra-data-json-server`) to download data. I have a custom `httpClient` where I set custom `fetchJson` options. Adding the `mode: 'no-cors'` option causes a strange error to appear (see bellow). Is it a bug or just my ignorace?

**What happened instead:**
The data to be shown are always correctly downloaded from the JSON server (200 OK, correct payload). However, `No results found` is displayed instead with an error notification (red box bellow the page) stating either:
 * `response is undefined` when run in my browser, or
 * `Unexpected frame by generating stack.` when run in sandbox

**Steps to reproduce:**
Add `mode: 'no-cors'` to `fetchJson` options simply by uncommenting the line indicated bellow.

**Related code:**
See https://codesandbox.io/s/vigilant-haze-zgtgm?fontsize=14

```js
import React from 'react';
import { render } from 'react-dom';
import { fetchUtils, Admin, Resource, ListGuesser } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const httpClient = (url, options = {}) => {
    // options.mode = 'no-cors'; /* <----- ADDING THIS LINE CAUSES THE PROBLEM */
    return fetchUtils.fetchJson(url, options);
}
const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com', httpClient);

render(
    <Admin dataProvider={dataProvider}>
        <Resource name="posts" list={ListGuesser}/>
    </Admin>,
    document.getElementById('root')
);
```

**Environment**
I should have the latest environment.

* React-admin version: 2.9.2
* React version: 16.8.6
* Browser: Firefox Quantum 67.0.1

**Comment by fzaninotto** [comment]
CORS are compulsory if the API runs in another domain that the frontend. It's your browser that blocks the request if you don't enable CORS, not react-admin.

By the way, as explained in the issue template, please use StackOverflow for troubleshooting rather than the GitHub issues.
