### ISSUE TITLE
Docs - Using Custom Iterators missing imports...

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3325]
https://marmelab.com/react-admin/List.html#using-a-custom-iterator

The first code sample for the "src/comments.js" file is missing some imports:

```
import Avatar from '@material-ui/core/Avatar';
import PersonIcon from '@material-ui/core/Avatar';
import {List, TextField, DateField, ReferenceField, EditButton} from "react-admin";
```

**Comment by ashneg** [comment]
Hey @WiXSL , can you assign it to me

**Comment by WiXSL** [comment]
I don't have write access permissions.

**Comment by fzaninotto** [comment]
@ashneg you don't need to have the issue assigned to you to propose a PR for it ;)

**Comment by ashneg** [comment]
@fzaninotto just being shure nobody's working on it :-)
