### ISSUE TITLE
Support intersection of permanent filter and regular filters

### ISSUE THREAD

**Issue by ericwb** [marmelab/react-admin#3332]
**Is your feature request related to a problem? Please describe.**
So according to the docs
```
The user cannot override the permanent filters set by way of filter.
```

That makes sense and I understand the value of this prevention.  However, it would be very nice to do filtering of the permanent filter itself.  I don't believe this would go against the current motivation to prevent overrides.  It wouldn't be overriding technically, it would be further filtering of a default permanent filter.

**Describe the solution you'd like**
I have a table of "requests" with a "user_id" field.  The permanent filter on the <List> is set to only show a subset of the total number of users.  However, a person may still want to filter this list further using an optional filter specified in the "filters" option of <List>.  

I may see requests for 10 users in my datagrid.  But I may want to temporarily filter all the requests by the 1 or 2 users I'm interested in.  So I really want an intersection of the 1-2 user names I want to filter and the 10 users that are being permanently filtered.

Hope this is clear.

**Describe alternatives you've considered**
The alternative is to do this all on the backend.  That'll involve more work for me to be sure.

**Additional context**
Can provide if needed.

**Comment by djhi** [comment]
Also in the documentation (actually just before):

> The actual filter parameter sent to the REST client is the result of the combination of the user filters (the ones set through the filters component form), and the permanent filter

If you need default filter values (set but overridable by users), use `alwaysOn` filters ([doc](https://marmelab.com/react-admin/List.html#filters)) and `filterDefaultValues` ([doc](https://marmelab.com/react-admin/List.html#filter-default-values))

**Comment by ericwb** [comment]
Yeah, but using an `alwaysOn` filter with `filterDefaultValues` also won't work for me.

**Comment by ericwb** [comment]
I do want a permanent filter of user IDs.  But I want a person to be able to choose a subset of the user IDs to filter.  The given suggestion simply provides a default that a person can override however they want.  In other words, nothing permanent.
