### ISSUE TITLE
Possibility to change and disable defaultCacheDuration for data stored in admins Redux store

### ISSUE THREAD

**Issue by michalpierzchlewicz** [marmelab/react-admin#3337]
**Is your feature request related to a problem?**
Yes. The problem showed up when I wanted to keep data in resources auto-updating using events from WebSocket. If an update event came after defaultCacheDuration (10 min) and I would try to update the state (described below), it would remove all other records from the Redux store. What is missing is the possibility of controlling the defaultCacheDuration. Description of my situation:
1. I have a resource `clients` for which I have a List view.
2. I'm listening on `clients` resource for update events to my data from my API through WebSockets. When I receive a new event, I dispatch the following event:
```javascript
props.dispatch({
  type: UPDATE,
  payload: {
    data: {
      id: client._id,
      ...client
     }
  },
  meta: {
    resource: constants.resources.clients,
    fetchResponse: UPDATE,
    fetchStatus: FETCH_END
  }
})
```
3. If I go to this view and wait for longer than 10 min (longer than `const defaultCacheDuration = 10 * 60 * 1000;`) and after that time I will receive the update event from my API, the event that I disaptch will cause all the "old" data to be removed because their 'fetchedAt' values are older than defaultCacheDuration.

**Describe the solution you'd like**
Possibility to change the defaultCacheDuration and maybe as well disable it completely. What I'm trying to achieve is instead of removing old data from the cache I would like to keep it automatically up to date.

**Comment by michalpierzchlewicz** [comment]
A related issue that was closed: #2886

**Comment by djhi** [comment]
I think this is now possible with [Application cache](https://marmelab.com/react-admin/Caching.html). @fzaninotto ?

**Comment by fzaninotto** [comment]
No, we still evict outdated (>10min) records from the `data` reducer. Application cache is a different mechanism.

**Comment by WiXSL** [comment]
This has been implemented in `next` branch since the data fetching is managed by `react-query`.
You would be able to make a call to any react-admin's data related hook passing a [`cacheTime`](https://react-query.tanstack.com/reference/useQuery#:~:text=cacheTime%3A%20number%20%7C%20Infinity) option to the internal `react-query` `useQuery` call.

So since this has been address, I'm closing this issue.
