### ISSUE TITLE
How to disable 'loginPage' ? 

### ISSUE THREAD

**Issue by vnnw** [marmelab/react-admin#3342]
I found that the document says it is possible to disable loginPage by passing false to this prop at here: https://marmelab.com/react-admin/Admin.html#loginpage .

But when I tried to writes lines like below and run 'yarn build', there will be error:

```
class App extends Component {
  render() {
    return (
    <Admin
      dataProvider={dataProvider}
      authProvider={authProvider}
      loginPage=false
    >
      <Resource name="posts" list={PostList} edit={PostEdit} create={PostCreate} icon={PostIcon}/>
    </Admin>
    );
  }
}
``` 
So what is the right way to disable loginPage? I can't find the answer after searching this repo and the internet.

**Comment by Kmaschta** [comment]
What's the error? Also, are you able to reproduce the issue on a CodeSandbox? (check the link in the bug template)

**Comment by vnnw** [comment]
> What's the error? Also, are you able to reproduce the issue on a CodeSandbox? (check the link in the bug template)

Here is the error snapshot:

![image](https://user-images.githubusercontent.com/4979571/59690795-91862680-9214-11e9-83b9-2a181a61d7f6.png)

**Comment by djhi** [comment]
wrap your `false` with accolades: `{false}`
