### ISSUE TITLE
Add tooltip on Menu entry when shrunk

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#3343]
The shrunk menu isn't really usable unless there are only a hand full of icons. Having the menu label appear on hover is a must have.

**Comment by Arlevoy** [comment]
Hi! Would love to try to help on this matter but I'm not sure to understand perfectly what is expected here. Would you be able to provide us with an example pls? Thanks 👍

**Comment by djhi** [comment]
Hey :) Thanks for asking. This should be done on the `next` branch which uses mui v4.
When the side menu is shrinked, every icon should be wrapped inside a tooltip element which would display the label. See https://material-ui.com/components/tooltips/

**Comment by fzaninotto** [comment]
Fixed by #3390
