### ISSUE TITLE
Middle click on Datagrid row

### ISSUE THREAD

**Issue by geoaxis** [marmelab/react-admin#3347]
I would like to have the ability to middle click in data grid row and open in a new tab.

I have considered adding a button, but that is not as convenient as it is to click the middle button anywhere in the row.

Ideally, the solution could be to add something that captures any generic event on the row.

**Comment by fzaninotto** [comment]
Hi @geoaxis, and thanks for your suggestion.

This is something you can achieve in user land by creating your own `DatagridRow` component, injecting it into `DatagridBody`, and then `Datagrid`, as explained in [the Datagrid documentation](https://marmelab.com/react-admin/List.html#body-element). 

This is also not a common need IMO, so we won't add that ability to the core.

**Comment by louiszuckerman** [comment]
I ran into this as well and the conversation in this issue was a huge help.

Here's some code that implements the approach described above.  This works for me with react-admin 3.1.2.

```
import {
  Datagrid,
  DatagridBody,
  DatagridRow,
} from 'react-admin'
import { linkToRecord } from 'ra-core'

// ...

const handleRowMiddleClick = (basePath, id) => e => {
  e.preventDefault()
  const recordPath = linkToRecord(basePath, id)
  window.open(`#${recordPath}`)
}

const MyDatagridRow = props => <DatagridRow onAuxClick={handleRowMiddleClick(props.basePath, props.id)} {...props} />

const MyDatagridBody = props => <DatagridBody row={<MyDatagridRow />} {...props} />

<Datagrid body={<MyDatagridBody />}>

```

Thanks!

**Comment by nicgirault** [comment]
Our users are frustrated not being able to CTRL+click to open in a new tab as it is a common practice on the web. I would expect react-admin to provide a native way to deal with this. I am surprised to see so little activity on this issue. @fzaninotto are you sure it's not a common need?

**Comment by geoaxis** [comment]
But it is possible to use the framework to do so with custom code. See example above. I am sure there are many other things that need not be in default widgets (but some people need them)

**Comment by djhi** [comment]
@nicgirault The CTRL + click will work on EditButton or ShowButton but not on the row itself

**Comment by fzaninotto** [comment]
if someone wants to submit a PR using the code mentioned above by @louiszuckerman, we can merge it.

**Comment by WiXSL** [comment]
Something like this: #6051
