### ISSUE TITLE
Making default theme RTL won't apply to some components

### ISSUE THREAD

**Issue by mohas** [marmelab/react-admin#3348]
**What you were expecting:**
for all the components to flip when I specify RTL in theme and `dir="rtl"` on body tag

**What happened instead:**
setting rtl on theme does absolutely nothing.
![ra-rtl](https://user-images.githubusercontent.com/1816728/59797013-f8c6d800-92f3-11e9-9673-1b2c00a52825.PNG)
As you can see many components are not RTL, icons are not flipped, paddings are not flipped, there is `text-align: left;` defined on the body.
I made list and edit components rtl using a jssProvider like:

    const jss = create({ plugins: [...jssPreset().plugins, rtl()] });

    function RTL(props) {
      return (
        <JssProvider jss={jss}>
          {props.children}
        </JssProvider>
      );
    }

Then use it with list and edit and create components:

    <RTL>
      <List {...props} ...

**Steps to reproduce:**

1-Create an RTL theme:

    const theme = {
      direction: 'rtl',
      typography: {
        fontFamily: 'IranSans'
      },
      isRtl: true
    };
    const themeWithDirection = createMuiTheme({...defaultTheme, ...theme});

2-Pass it to Admin component:

    <Admin locale="fa" i18nProvider={i18nProvider} theme={theme} ...

There is very little badly written documentation and answers regarding these issues, so any help is appreciated, thanks.

**Environment**

* React-admin version: 2.9.3
* React version: 16.6.3
* Browser: any

**Comment by mohas** [comment]
I've made further inspections on next, back buttons and why their icons won't flip, turns out material-ui `TablePaginationActions` is doing a correct job regarding theme direction:

    return _react.default.createElement("div", other, _react.default.createElement(_IconButton.default, (0, _extends2.default)({
            onClick: this.handleBackButtonClick,
            disabled: page === 0
          }, backIconButtonProps), theme.direction === 'rtl' ? _ref : _ref2), _react.default.createElement(_IconButton.default, (0, _extends2.default)({
            onClick: this.handleNextButtonClick,
            disabled: page >= Math.ceil(count / rowsPerPage) - 1
          }, nextIconButtonProps), theme.direction === 'rtl' ? _ref3 : _ref4));

but `PaginationActions` in react-admin does not regard theme direction when making action buttons, so my guess is the same problem lies everywhere in react-admin components so how can I introduce theme prop into those components?

**Comment by mohas** [comment]
I made a gist to show how to fix it, can I make this into a pull request?
[PaginationActions](https://gist.github.com/mohas/563edd5af4a499f155b927082b47e290)

**Comment by djhi** [comment]
Hi, thanks for reporting the issue. It's very difficult to spot any changes in a gist. Please open a pull request and we'll do our best to review it and iterate with you.

**Comment by fzaninotto** [comment]
Thanks for the bug report. Please note that we don't have the need or the ability to test admins with RTL turned on. We'll need help from the community to fix that one, so PRs are welcome.

**Comment by jdemangeon** [comment]
Fixed by #4496
