### ISSUE TITLE
Docs: Dead Link.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3355]
[https://marmelab.com/react-admin/Actions.html#list-bulk-actions](https://marmelab.com/react-admin/Actions.html#list-bulk-actions)

"You can find a complete example of a custom Bulk Action button in the List documentation, in the **Bulk Action Buttons** section." <--- Here

**Comment by bmuthoga** [comment]
Raised a PR for this [here](https://github.com/marmelab/react-admin/pull/3361)
