### ISSUE TITLE
When canceling an operation, the DeleteButton button raises the rowClick event

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#3359]
When canceling an operation, the DeleteButton button raises the rowClick event.
This question has already been raised, but previous changes have not solved the problem!

```jsx
<List {...props} >
  <Datagrid rowClick="edit" >
    ...
    <DeleteButton undoable={false} />
  </Datagrid>
</List>
```

Solves the problem:

```js
class DeleteWithConfirmButton extends Component {
    ...
    handleDialogClose = e => {
        this.setState({ isOpen: false })
        e.stopPropagation()                 // Solves the problem  
    }
```

* React-admin version:  2.9.3
* React version: 16.8.6
* Browser: Chrome 75.0.3770.100

**Comment by Kmaschta** [comment]
Do you have a link to the previous issue?

**Comment by MaxAlex666** [comment]
https://github.com/marmelab/react-admin/issues/3358

**Comment by MaxAlex666** [comment]
Here is another similar question:
https://stackoverflow.com/questions/56694919/is-it-possible-to-control-the-path-for-the-cancel-button-on-react-admins-delete
