### ISSUE TITLE
Highlight all invalid inputs, whether they've been touched or not, when and only when the user clicks save.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#3367]
**Is your feature request related to a problem? Please describe.**
I'd like a way to highlight all invalid inputs, whether they've been touched or not, when and only when the user clicks save.

**Describe the solution you'd like**
Highlight all invalid inputs, whether they've been touched or not, when and only when the user clicks save.

**Describe alternatives you've considered**
Telling users to get used to it.

**Additional context**
[My StackOverflow question which I'm almost positive will go unanswered](https://stackoverflow.com/questions/56762047/how-to-highlight-all-inputs-that-failed-validation-in-react-admin-whether-theyv)

**Comment by djhi** [comment]
It's not possible currently unless you're willing to rewrite all inputs as they include the logic checking for the `touched` and `error` props injected by redux-form. I'm not sure we can/should make it configurable but I'll keep this issue as an enhancement until we decide

**Comment by jdemangeon** [comment]
This issue is over a year old now. In addition, we no longer use redux-form. So, I'm closing it.
Feel free to open an RFC if you need advanced form capabilities on the new react-admin version.
