### ISSUE TITLE
callback never called onSuccess or onError using withDataProvider

### ISSUE THREAD

**Issue by tusmenko** [marmelab/react-admin#3369]
**What you were expecting:**

As mentioned in **Handling Side Effects** block of **Querying the API**:
> React-admin can handle the following side effects:  
> - ...
> - callback: Execute an arbitrary function. The value should be the function to execute. React-admin will call the function with an object as parameter ({ requestPayload, payload, error }). The payload contains the decoded response body when it’s successful. When it’s failed, the response body is passed in the error.

**What happened instead:**
Function passed to `callback` never called, as for common, so for undoable actions.

**Steps to reproduce:**
Go to sandbox example
On Posts tab click the custom Status switcher
-> Switch toggles it's value.
-> No console log entries added with callback `() => console.log("I wand to be called onSuccess!")` passed to callback in src/posts/StatusSwitch.js:79

**Related code:**
https://codesandbox.io/s/simple-0x7un

```
dataProvider(
      UPDATE,
      resource,
      {
        id: record.id,
        data: updatedRecord
      },
      {
        undoable: false,
        onSuccess: {
          notification: { body: `${label} has changed` },
          callback: () => {
            console.log("I wand to be called onSuccess!");
          }
        },
        onError: {
          notification: {
            body: `Error: ${label} has not changed`,
            level: "warning"
          },
          callback: () => {
            console.log("I wand to be called onError!");
          }
        }
      }
    );
```

**Other information:**

**Environment**

* React-admin version: 2.9.2 
* React version: 16.8.6
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for the report and the codesandox. This is indeed a bug

**Comment by djhi** [comment]
Actually, you don't need this callback as the `dataProvider` call returns a promise. 

```js
dataProvider(
      UPDATE,
      resource,
      {
        id: record.id,
        data: updatedRecord
      },
      {
        undoable: false,
        onSuccess: {
          notification: { body: `${label} has changed` },
        },
        onError: {
          notification: {
            body: `Error: ${label} has not changed`,
            level: "warning"
          }
        }
      }
    ).then(() => {
        console.log("I wand to be called onSuccess!");
    }).catch(error => {
        console.log("I wand to be called onError!");
    });
```

However, this should be explained in the documentation. I'll keep this issue open
