### ISSUE TITLE
TextInput inside a Grid: its label is NOT translated 

### ISSUE THREAD

**Issue by nhuttrung** [marmelab/react-admin#3373]
**What you were expecting:**

I want to put TextInput in a Grid to make two columns layout Edit form
And I expect that the TextInput's label should get translated as described in https://marmelab.com/react-admin/Translation.html

**What happened instead:**
TextInput's label is not translated. It simply “humanizes” field name, e.g field name `username` will has label of `Username` instead of `My Custom Label` (i18n message)

**Steps to reproduce:**

* Follow https://marmelab.com/react-admin/Translation.html to create i18n messages and setup `i18nProvider`
* Follow https://marmelab.com/react-admin/Tutorial.html to create a Edit form

```jsx
// File en.js
import englishMessages from "ra-language-english";

export default {
  ...englishMessages,
  resources: {
    users: {
      fields: {
        username: "My Custom Label",
        email: "EMail",
        website: "Web Site"
      }
    }
  }
};

// File users.js
export const UserEdit = props => (
  <Edit {...props}>
    <SimpleForm>
      <DisabledInput source="id" />
      {/* OK: TextInput's label is translated */}
      <TextInput source="username" />

      <Grid container spacing={8}>
        <Grid item xs={12} sm={6}>
          {/* Issue: TextInput's label is NOT translated */}
          <TextInput source="username" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);
```
* Working code describing the issue: https://codesandbox.io/s/react-admin-f38gy
Click on a row to open the Edit form. Check the label of TextInput.

**Other information:**

**Environment**

* React-admin version: 2.9.3
* React version: 16.8.6

**Comment by Kmaschta** [comment]
Reproduced, thanks for the issue!
But I'm not sure it's a bug or that it's just not designed to be used like that.

As a [explained in the documentation](https://marmelab.com/react-admin/Translation.html#translating-your-own-components), you might be able to use the `label` prop to force React Admin to translate it.

```jsx
// File users.js
export const UserEdit = props => (
  <Edit {...props}>
    <SimpleForm>
      <DisabledInput source="id" />
      {/* OK: TextInput's label is translated */}
      <TextInput source="username" />

      <Grid container spacing={8}>
        <Grid item xs={12} sm={6}>
          {/* The workaround is to repeat the translation path in the label */}
          <TextInput source="username" label="resources.users.fields.username" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);
```

But I don't know why it's translated by default as root by not in depth.

**Comment by djhi** [comment]
Not really a bug. `SimpleForm` does not handle anything but inputs and fields. If you want to wrap our inputs inside other components such as the Grid, you'll have to implement your own form.

**Comment by fzaninotto** [comment]
Yep, it's a limitation of SimpleForm in version 2. React-admin v3 may lift this limitation, but until then we won't fix it.
