### ISSUE TITLE
handleSubmitWithRedirect not working has excepted

### ISSUE THREAD

**Issue by stevenLT** [marmelab/react-admin#3376]
Hi everyone

Thank you very much for your work ! I love working with.

I am faced with a problem. The handleSubmitWithRedirect props does not seem to work as expected on my code. When clicking to save, the function that must be executed before the submit is executed. But that does not go further. There is no redirection or send to the server or errors on console.

I think I missed something.

Thanks for your help.

**What you were expecting:**

handleSubmitWithRedirect should perform the function transmitted during submission and perform a redirection. 

**What happened instead:**

The function is well executed but there is no redirection and no POST is sent to the server.

**Steps to reproduce:**

See Related code below. I based myself on https://marmelab.com/react-admin/Actions.html#altering-the-form-values-before-submitting

**Related code:**

**Environment**

* React-admin version: ^2.9.2
* Last version that did not exhibit the issue (if applicable): 
* React version: ^16.8.6
* Browser: Chrome
* Stack trace (in case of a JS error): no JS error

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by stevenLT** [comment]
Thank you for your reply. I just implemented my piece of code that was a problem in the sandbox. It seems to work! Which means that my worries probably do not come from that ... I do not have a lot of idea of ​​where the problem may come from.

Link to sandbox: https://codesandbox.io/s/simple-8qnny
File implemented in: src/posts
Action used on UI: Save button on the right on post ceate

I use react-redux to record the state of a variable. Could it come from the fact that there are several blinds? Mine + react-admin store?

Thanks for your help

**Comment by stevenLT** [comment]
Hi, 

I'm closing this issue, the problem came from the way so I set up react-redux on the project. I followed this part of the documentation https://marmelab.com/react-admin/CustomApp.html and my problem corrected itself.

I did not understand how react-admin managed to use a react-redux. I begin to understand even if it still seems a little magical.

Thanks for all
