### ISSUE TITLE
Document how to have a full width SelectArrayInput in Filter

### ISSUE THREAD

**Issue by vnnw** [marmelab/react-admin#3381]
I use SelectArrayInput in the Filters of a List, but the width is very small, and cannot be adjusted with options={{ fullWidth: true }}.

**What you were expecting:**
The width of SelectArrayInput should equal to SelectInput's.

**What happened instead:**
![image](https://user-images.githubusercontent.com/4979571/60645508-6e41b500-9e6b-11e9-8852-ac8a6d8ab8d7.png)

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by vnnw** [comment]
> Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:
> 
> * CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
> * A sample application via GitHub

Thanks for the reply.

I modified the codes as below in UserList.js, and added Name filter, the interface then looks ugly. 

![image](https://user-images.githubusercontent.com/4979571/60660528-8aa11a00-9e8a-11e9-8439-d81527934a00.png)


```
const UserFilter = ({ permissions, ...props }) => (
    <Filter {...props}>
        <SearchInput source="q" alwaysOn />
       /* <TextInput source="name"/> */
        <SelectArrayInput source="name" 
            choices={[
                { id: '1', name: 'A' },
                { id: '2', name: 'B' },
            ]}
         />
        {permissions === 'admin' ? <TextInput source="role" /> : null}
    </Filter>
);

```

**Comment by djhi** [comment]
For reference: https://codesandbox.io/s/simple-vhors

**Comment by vnnw** [comment]
> For reference: https://codesandbox.io/s/simple-vhors

Thank you for the effort.
I noticed that you added "fullWidth" into the code. But the look doesn't change at all.
Did you notice that "Name" dropdown selector in the snapshot below looks kind of clumsy?
I think its width should be  the same as that of "Role".

![image](https://user-images.githubusercontent.com/4979571/60673229-e4fda300-9ea9-11e9-93a8-fd027db2eae6.png)

**Comment by djhi** [comment]
Yes, I added `fullWidth` to try fixing it quickly but it did not work. I also noticed the issue which is why I added the `bug` label

**Comment by djhi** [comment]
PS: next time, please create a codesandbox instead of posting code :)

**Comment by m4theushw** [comment]
The `fullWidth` will have no effect unless you add a width to the `SelectArrayInput`. Please check the `PostFilter` component on this [codesandbox](https://codesandbox.io/s/simple-e3g7n) I created.

**Comment by fzaninotto** [comment]
It seems that the underlying element (mui Select) [doesn't support the `fullWidth` prop](https://v1.material-ui.com/api/select/). Trying to pass `fullWidth` to `inputProps` doesn't work either, as mui renders a hidden input... So the only way is to pass a custom style through `className`.

This is a mui limitation that we can't overcome, so the issue is only a documentation one - we should remove the mention about `fullWidth` in the `SelectArrayInput` documentation.

**Comment by vnnw** [comment]
> The `fullWidth` will have no effect unless you add a width to the `SelectArrayInput`. Please check the `PostFilter` component on this [codesandbox](https://codesandbox.io/s/simple-e3g7n) I created.

Thanks. It works fine.
