### ISSUE TITLE
AppBar customization

### ISSUE THREAD

**Issue by hffmnn** [marmelab/react-admin#3383]
**Is your feature request related to a problem? Please describe.**
I wanted to show an AppBar without a loading indicator or reload button, because for me that is reimplementing existing browser functionality. Setting `appBar={MyAppBar}` to a custom app bar does not remove that control.

**Describe the solution you'd like**
When providing a custom layout do not insert any hardcoded children but use the one specified in the layout.

Alternatively, make the `AppBar` (packages/ra-ui-materialui/src/layout/AppBar.js) somehow configurable

**Describe alternatives you've considered**
My existing solution copies the existing `AppBar`, makes the necessary changes and uses that as a container for the layout.

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by hffmnn** [comment]
Hi @djhi and thanks for the quick response.

I prepared one CodeSandbox at https://codesandbox.io/s/simple-uw85j

There you can see the "problem": In MyAppBar does not have any children, still the Loading Indicatore/Reload button is visible. Same for authentication and the menu.

**Comment by djhi** [comment]
You have to create your own `AppBar` component. Using the existing one like you did will result in the current behavior. You can use the original `AppBar` as a starting point: https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/AppBar.js

**Comment by hffmnn** [comment]
Ok, so doing it exactly as described above is the correct way.

>My existing solution copies the existing `AppBar`, makes the necessary changes and uses that as a container for the layout.
