### ISSUE TITLE
custom datagrid dosent work when we use and edit button 

### ISSUE THREAD

**Issue by mrlaseptima** [marmelab/react-admin#3384]
custom Datagrid (MyDatagrid in document)  dosent work when we use and edit button or something like that because in custom Datagrid use this : 
``` {React.Children.map(children, field => (
            <TableCell key={`${id}-${field.props.source}`}>
                {React.cloneElement(field, {
                    record,
                    basePath,
                    resource,
                })}
            </TableCell>
        ))}
```
and error on field.props.source in key prop is this :
"Cannot read property 'source' of undefined"

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
No news for some time, closing.
