### ISSUE TITLE
Documentation aside example issue + fix

### ISSUE THREAD

**Issue by firepol** [marmelab/react-admin#3387]
Hi in the Documentation > chapter 6. Lists > [aside component](https://marmelab.com/react-admin/List.html#aside-component), you wrote a code to calculate the sum, which is not working.

This gave me issues, see my [stackoverflow question](https://stackoverflow.com/questions/56878628/display-total-of-grid-column-values-in-react-admin)

The issue:
```
Total views: {ids.map(id => data[id]).reduce((sum, post) => sum + post.views)}
```

The fix:
```
Total views: {ids.map(id => data[id]).reduce((sum, post) => sum + post.views, 0)}
```

**Comment by djhi** [comment]
Thanks for reporting/ Can you make a pull request to fix it ?
