### ISSUE TITLE
Cannot read property 'touched' of undefined

### ISSUE THREAD

**Issue by mrlaseptima** [marmelab/react-admin#3399]
after add RichTextInput i have this error : 
![image](https://user-images.githubusercontent.com/24463719/60954049-94f06780-a313-11e9-89cb-59ab7c2473bd.png)
its my code : 

```
<RichTextInput
	toolbar={[["bold", "italic", "underline", "link"]]}
	source="summary"
	validation={{ required: true }}
/>
```

**Environment**

* React-admin version: ^2.9.4
* Last version that did not exhibit the issue (if applicable): 
* React version: ^16.8.6
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by FlipperDev** [comment]
Hi, got the same problem ! I updated all the packages and react-admin :

`{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "jsonwebtoken": "^8.5.1",
    "prop-types": "^15.7.2",
    "ra-data-json-server": "^2.9.0",
    "ra-language-english": "^2.9.3",
    "ra-language-french": "^2.8.5",
    "react": "^16.8.6",
    "react-admin": "^2.9.4",
    "react-dom": "^16.8.6",
    "react-number-format": "^4.0.8",
    "react-scripts": "3.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "ra-input-rich-text": "^2.9.3"
  }
}
`

For the informations you are waiting for, its easy to reproduce with a really simple app. Just add a resource and a "Create" page for the resource. Add the input with a source and boom, error happend.

**Comment by Kmaschta** [comment]
We'll consider this issue as resolved, then. Feel free to re-open if the issue persists with fresh dependencies.

Try to provide a CodeSandbox with a reproduced issue.

**Comment by chungchi300** [comment]
Your code works fine, the similar error occur when the rich text input is included with bracklet


```
import {RichTextInput} from 'ra-input-rich-text';

```

**Comment by chungchi300** [comment]
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple?fontsize=14

the problematic example

**Comment by pjw9195** [comment]
i have same problem
in my case, 
import {RichTextInput} from 'ra-input-rich-text'; 
to 
import RichTextInput from 'ra-input-rich-text'

i solved
