### ISSUE TITLE
Filters are preserved when going back to a list page (even though URI has no filters)

### ISSUE THREAD

**Issue by michal-samluk** [marmelab/react-admin#3400]
Scenario:
1. Click in the menu on "Users" resource `/users`. List is being displayed. 
2. Use some filter (e.g. search by email). Filters are added to URI. 
3. Navigate to another page, e.g. "Blog Posts" `/posts` 
4. Click "Users" in the sidebar menu again and navigate to `/users`

Current Behavior: 
Filters will be selected, but URI will not have the filtering params. 

Expected behavior: 
1. Clicking Users should use default filters. In this case: (no filters).
OR 
2. Keep the filters in URI. 

I am not sure if this is a bug or feature. I want to achieve behavior no. 1.

**Comment by fzaninotto** [comment]
This is a feature - we've built it that way so that users find a similar state of the application whatever the navigation (just like on mobile apps). If you want to achieve use case number one, change the menu link to include an empty filter request parameter.
