### ISSUE TITLE
Issue with page reloads on production builds 

### ISSUE THREAD

**Issue by joernh** [marmelab/react-admin#3403]
**What you were expecting:**

When being logged in to react admin, I expect react-admin to keep its session after reloading or re-navigating to the webpage without the UI breaking as described below.

**What happened instead:**

This happens only on **production builds**. When running the page in dev mode via `yarn start`, everything works fine on reloads.

After reloading a react admin page using the browser's reload button, the elements in the navigation bar turn red, the navigation disappears and any further actions lead to breaking the page completely. Logging out and logging in again, fixes the issue without any further reloads. 

**Steps to reproduce:**

1. Create a production build via `yarn build`
2. Load the react-admin page from a web server
3. Log in to react-admin
4. Click the browser's reload button or navigate to react-admin from another browser window
5. -> UI breaks

**Related code:**

I think the issue is related on how a current session is being restored. Please find my authProvider below which is basically just a modified version of the example provider from the docs page.
 
```
import {AUTH_LOGIN, AUTH_CHECK, AUTH_LOGOUT, AUTH_ERROR} from 'react-admin';
import {API_URL} from './Constants';

export default (type, params) => {
  if (type === AUTH_LOGIN) {
    const {username, password} = params;
    const request = new Request(`${API_URL}/session`, {
      method: 'POST',
      body: JSON.stringify({email: username, password}),
      headers: new Headers({'Content-Type': 'application/json'}),
    });
    return fetch(request)
      .then(response => {
        if (response.status < 200 || response.status >= 300) {
          throw new Error(response.statusText);
        }
        return response.json();
      })
      .then(({token}) => {
        localStorage.setItem('token', token);
      });
  } else if (type === AUTH_CHECK) {
    return localStorage.getItem('token')
      ? Promise.resolve()
      : Promise.reject({redirectTo: '/login'});
  } else if (type === AUTH_LOGOUT) {
    return localStorage.removeItem('token');
  } else if (type === AUTH_ERROR) {
    const status = params.status;
    if (status === 401 || status === 403) {
      localStorage.removeItem('token');
      return Promise.reject();
    }
    return Promise.resolve();
  }
  return Promise.resolve();
};
```

**Other information:**

Expected layout:
<img width="1112" alt="Screenshot 2019-07-11 at 09 42 44" src="https://user-images.githubusercontent.com/36643/61031659-4220b980-a3c0-11e9-80d0-edc5342f36db.png">

Layout after reloading:
<img width="1110" alt="Screenshot 2019-07-11 at 09 32 58" src="https://user-images.githubusercontent.com/36643/61031626-33d29d80-a3c0-11e9-9386-dcdf5ff91a5f.png">

**Environment**

* React-admin version: 2.9.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.4
* Browser: Safari 12.1.1, Chrome 75
* Stack trace (in case of a JS error): No console output available

**Comment by fzaninotto** [comment]
I can't reproduce it in the demo (https://marmelab.com/react-admin-demo/), which is a production build. Can you please use the react-admin CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) to reproduce your problem?

**Comment by joernh** [comment]
It turned out that the resource icons caused the issue. After upgrading to the latest @material-ui/icons package everything is working as expected now. Still weird how this affected production builds only and only after reloading the page.

```
-    "@material-ui/core": "^3.9.2",
-    "@material-ui/icons": "^3.0.2",
+    "@material-ui/core": "^4.2.0",
+    "@material-ui/icons": "^4.2.1",
```

**Comment by Kmaschta** [comment]
Certainly related to #1782

When your local version of MUI conflicts with the React Admin one, JSS does weird stuff with class minification.
