### ISSUE TITLE
Add a <ReferenceArrayInput> in demo + write E2E tests

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/react-admin#3416]
Currently, there is no E2E tests on `<ReferenceArrayInput>` and that can lead to [many bugs and/or regressions](https://github.com/marmelab/react-admin/issues?utf8=%E2%9C%93&q=is%3Aissue+%22referencearrayinput%22)

I would add an example of `<ReferenceArrayField>` and `<ReferenceArrayInput>` on the demo example and write some E2E tests on it.

**Comment by fzaninotto** [comment]
I'm closing this one as it points one missing test among many...
