### ISSUE TITLE
Autocomplete: Dropdown does not stay underneath input

### ISSUE THREAD

**Issue by ConstantineKononenko** [marmelab/react-admin#3418]
Hello.

**What you were expecting:**
That the dropdown stays underneath and won't scroll with the page.

**What happened instead:**
The dropdown is scrolling with the page.

**Steps to reproduce:**
Works in demo app:
https://marmelab.com/react-admin-demo/#/reviews?filter=%7B%7D&order=DESC&page=1&perPage=25&sort=date

- Add filter -> Customer -> click on it
- Scroll down

![autocomplete-dropdown](https://user-images.githubusercontent.com/46819108/61271900-77f1e380-a7ae-11e9-8382-9063b0ce4bf0.gif)

**Comment by fzaninotto** [comment]
Thanks for the report. I could reproduce the issue.

**Comment by m4theushw** [comment]
I couldn't reproduce this bug. The demo from the `next` branch is working correctly. @fzaninotto did you test this way?

![autocomplete](https://user-images.githubusercontent.com/42154031/62586171-e0eee780-b892-11e9-88ec-1d7848fa600e.gif)

**Comment by fzaninotto** [comment]
Fixed by #3683
