### ISSUE TITLE
react-admin-postgrest-client

### ISSUE THREAD

**Issue by Wellers0n** [marmelab/react-admin#3420]
if you are using postgres and react-admin I got you cover with: https://www.npmjs.com/package/react-admin-postgrest-client
https://github.com/wellers0n/react-admin-postgrest-client

**Comment by djhi** [comment]
Nice! Can you open a pull request to add it in our ecosystem documentation page ? Issues are for tracking issues :wink:

**Comment by Wellers0n** [comment]
#3423
