### ISSUE TITLE
[3.0.0-alpha.0 upgrade] can't resolve react-testing-library

### ISSUE THREAD

**Issue by MohammedFaragallah** [marmelab/react-admin#3431]
Thank you very much for this alpha release i think it will be very helpful

after upgrading 
react-admin => 3.0.0-alpha.0
@material-ui/core => 4.2.1
@material-ui/icons => 4.2.1

i got this error

_ra-core/esm/util/renderWithRedux.js
Module not found: Can't resolve 'react-testing-library'_

i tried to install it but i got another error 

_Error: 🚨  react-testing-library has moved to @testing-library/react. Please uninstall react-testing-library and install @testing-library/react instead, or use an older version of react-testing-library. Learn more about this change here: https://github.com/testing-library/dom-testing-library/issues/260 Thanks! :)_

**Comment by smeng9** [comment]
I yarn add the react-testing-library@6.1.2 as a temporary solution

**Comment by djhi** [comment]
We should probably extract those test utilities in a separate package installable as a dev dependency

**Comment by fzaninotto** [comment]
We already used `react-testing-library` in `master`. the difference is that we now export `renderWithRedux`, which depends on `react-testing-library`. So this package must be in `dependencies` rather than `devDependencies` in `next`. I'm marking this a s a bug.

**Comment by fzaninotto** [comment]
Fixed by #3442

**Comment by fzaninotto** [comment]
This was published in version 3.0 on November 20, 2019. https://github.com/marmelab/react-admin/releases/tag/v3.0.0
