### ISSUE TITLE
multiline text inputs are styled as plain text inputs

### ISSUE THREAD

**Issue by esistgut** [marmelab/react-admin#3433]
![Screenshot from 2019-07-21 15-04-53](https://user-images.githubusercontent.com/869693/61591639-3b1c5700-abc9-11e9-90ac-17253e3d0b2b.png)

Please note: this is happening with both `<LongTextInput />` (deprecated) and `<TextInput multiline />`

**Comment by djhi** [comment]
I don't get the issue. What did you expect? If expecting to see multiple lines right away, use the `rows` prop (see material-ui documentation)

**Comment by esistgut** [comment]
Ok, sorry, on the previous version this was not required to see multiple lines, my bad.

**Comment by fzaninotto** [comment]
If it was not required, it's a regression. We should either mention it in the upgrade guide, or remove the regression. I'm reopening this issue.

**Comment by fzaninotto** [comment]
Fixed by #3450
