### ISSUE TITLE
list table header height not consistent on bulkActionButtons={false}

### ISSUE THREAD

**Issue by esistgut** [marmelab/react-admin#3435]
Without `bulkActionButtons={false}`:
![Screenshot from 2019-07-21 15-24-33](https://user-images.githubusercontent.com/869693/61591864-e9290080-abcb-11e9-9687-8df96512b064.png)

With `bulkActionButtons={false}`:
![Screenshot from 2019-07-21 15-24-14](https://user-images.githubusercontent.com/869693/61591867-efb77800-abcb-11e9-9346-5bc099def2c8.png)

On previous versions it remained consistent:
![Screenshot from 2019-07-21 15-27-49](https://user-images.githubusercontent.com/869693/61591919-648ab200-abcc-11e9-99db-6d6b9da19095.png)

**Comment by esistgut** [comment]
The issue report was initially focused on the header only but as you can see from the previous screenshot something is wrong about the height on the actual rows too. This is visible on the demo too: https://github.com/marmelab/react-admin/issues/3437#issuecomment-513581357

**Comment by djhi** [comment]
Thanks a lot for testing this :+1:

**Comment by fzaninotto** [comment]
Fixed by #3480
