### ISSUE TITLE
[3.0.0-alpha.0] Can't provide custom redux store

### ISSUE THREAD

**Issue by johannesfritsch** [marmelab/react-admin#3445]
**What you were expecting:**
I can provide a store through react-redux' Provider and am not forced to provide a dataProvider on the `<Admin>` component.

**What happened instead:**
When I skip the dataProvider I get the error "Missing dataProvider prop.". If I pass the dataProvider too (which I don't need according to the docs and a quick look at CoreAdmin.tsx) multiple stores are created: The one I wrapped `<Admin>` in and another one that <Admin> created.

**Steps to reproduce:**
Wrap `<Admin>` inside a `<Provider>` with a store. We simply followed these steps: https://github.com/marmelab/react-admin/blob/next/docs/CustomApp.md

**Related code:**
```
<Provider store={this.store}>
        <Admin layout={Layout} theme={Theme} title="Mall-X" history={history} authProvider={authProvider} loginPage={Login}>
          ...
        </Admin>
      </Provider>
```

**Other information:**
I had a look into CoreAdmin.tsx. I think you have to provide the `CoreAdmin.contextType` there in order to consume the context.store. As the context is empty during initialization the member variable this.reduxIsAlreadyInitialized is never set to true. That's why render wraps the renderCore into another `<Provider>` with a store from local `createAdminStore(...)`.

**Environment**

* React-admin version: 3.0.0-alpha.0
* Last version that did not exhibit the issue (if applicable): Latest v2 afaik
* React version: 16.8.1
* Browser: Latest Chrome
* Stack trace (in case of a JS error): No stack trace

**Comment by Pomazan-Bogdan** [comment]
TypeError: Cannot read property 'store' of undefined
App
src/App.js:27
  24 | 
  25 | const App = () => (
  26 |     <div>    
> 27 |         <Provider>
  28 |             store={this.store}
  29 |             dataProvider={hasuraDataProvider(hasuraUrl, headers)}
  30 |             authProvider={authProvider}

**Comment by djhi** [comment]
Thanks for reporting this :+1:
