### ISSUE TITLE
Datagrid: Can't set expand and optional checkboxes at the same time

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3470]
I need to use a Datagrid with expand attribute and also be able to show checkboxes only in cells that meet some criteria.

The Docs explain how to achieve the latter here:
[https://marmelab.com/react-admin/List.html#body-element](https://marmelab.com/react-admin/List.html#body-element)

But if you do this and set the "expand" attribute to a Datagrid, It renders incorrectly.
You can't have both characteristics.

**Comment by fzaninotto** [comment]
Please follow the issue template and provide sample code, an example of what you get, and whet you expect instead. Even better, please add a link to a CodeSandbox allowing us to reproduce the problem.

**Comment by WiXSL** [comment]
Ok.
Check out the "PostList" component here:
[https://codesandbox.io/s/tutorial-3mgjq?fontsize=14](url)

It has a Datagrid component with expand and a custom body:

`<Datagrid rowClick="expand" expand={<PostShow />} body={<MyDatagridBody />}>`

And it renders incorrectly. You can't expand the rows and the "select all" checkbox is miss-aligned with the rest of the rows.

**Comment by WiXSL** [comment]
Well, now i see where the problem is.
The code of the custom DatagridRow doesn't  have the resolution of the expand attribute. I took the code from the Docs. Which now this will be a Docs problem report instead of a react-admin one.

**Comment by Kmaschta** [comment]
I'm not sure to understand the issue. On your CodeSandbox, everything seems aligned to me.

![image](https://user-images.githubusercontent.com/1819833/62201336-7f58e580-b387-11e9-95a1-018a864c4c1d.png)

Do you have a screenshot?
Also, we really need the information that were asked by the template : what is your React Admin version and browser?

**Comment by WiXSL** [comment]
@Kmaschta, you are seeing now the code with the solution I've found, which is overriding the entire DatagridRow prop plus the ExpandRowButton component and adding the "getHasCheckBox".
I couldn't clarify that I did that yesterday.

`<DatagridBody
    {...props}
    row={<MyDatagridRow getHasCheckBox={rec => !rec.selected} />}
  />`

**Comment by fzaninotto** [comment]
What exactly is this `getHasCheckBox` prop you're talking about? Can you please clarify which component sets it and which component uses it?

**Comment by WiXSL** [comment]
`getHasCheckBox` is a function that I pass as a prop to my custom DatagridRow component  that receives the record of the row and resolves if it will show a `CheckBox` component or not.

https://codesandbox.io/s/tutorial-qyfmn :

**Posts**: Using the Docs (v2) code override (https://marmelab.com/react-admin/List.html#body-element)

**Users**: Using A complete override of DatagridRow component.

**Comment by WiXSL** [comment]
#3964

**Comment by fzaninotto** [comment]
Fixed by #3964
