### ISSUE TITLE
AutocompleteArrayInput not accepting props

### ISSUE THREAD

**Issue by Kunnu01** [marmelab/react-admin#3477]
**What you were expecting:**
On passing prop `fullWidth` in `options` of `AutocompleteArrayInput` component, ChipInput to have full wdth. I guess no props are accessible by `AutocompleteArrayInput`.

**What happened instead:**
passing `fullWidth` didn't work.

**Related code:**
```
<AutoCompleteArrayInput options={{
    fullWidth: true
}} />
```
**Steps to reproduce**
1- Open up any post
2- Go to `MISCELLANEOUS`
3- ChipInput doesn't has full width

**CodeSandbox**
https://codesandbox.io/embed/simple-jkp47

**Additional Information**
Even after sending `options` prop, `AutocompleteArrayInput` got `options: { }` (empty object) when checked using `console log`.

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment]
Confirmed, thanks for the report
