### ISSUE TITLE
UrlField open link in new tab

### ISSUE THREAD

**Issue by gespispace** [marmelab/react-admin#3487]
Hi
**Is your feature request related to a problem? Please describe.**
I need open link always in new tab, don't use center button in mouse.

**Describe the solution you'd like**
onClick for urlField open new tab. maybe it will be some sort of property 'openNewTab' or desription in docs forwarding props in component UrlFiled becose i understanded forwarding props working only looked in source file and upon seeing sanitizeRestProps

**Describe alternatives you've considered**
i try user target='_blank' with rel="noopener noreferrer" and it work, but i think it is not correct solution.

**Comment by Kmaschta** [comment]
The [`<URLField>` is just a plain `<a>` tag](https://github.com/marmelab/react-admin/blob/1b6967f3367b13a6675de7047bd9385dc36a8db5/packages/ra-ui-materialui/src/field/UrlField.tsx#L7-L17) so, using `target` and `rel` is the correct usage for that component if you want it to open your link in a new tab.

**Comment by gespispace** [comment]
@Kmaschta 
Thanks you. Well, but what about add in docs comment about forwarding props in <a> tag?

**Comment by Kmaschta** [comment]
That's a great idea! Any PR on that matter is welcome :)
