### ISSUE TITLE
Documentation error in Menu example

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#3496]
The "menu" component does not receive prop "resources":
https://marmelab.com/react-admin/Admin.html#menu

const Menu = ({ resources, onMenuClick, logout }) => (
    <div>
     ...

* React-admin version: 2.9.5
* React version: 16.8.6
* Browser: Chrome 75.0.3770.142

**Comment by Kmaschta** [comment]
Thanks for opening the issue!

You're right, in fact the Menu is connected to the redux store:

https://github.com/marmelab/react-admin/blob/a508029a6eb0d6632b376c29b54705374f3bae66/packages/ra-ui-materialui/src/layout/Menu.js#L87

**Comment by fatahn** [comment]
Hi @MaxAlex666 I thought the Menu should have the resources prop because we are injecting it through redux.

**Comment by fzaninotto** [comment]
This was fixed in #3643, six months ago
