### ISSUE TITLE
[RFC] Deprecate DisabledInput

### ISSUE THREAD

**Issue by djhi** [marmelab/react-admin#3518]
Following the review from @Kmaschta in #3515, we think the `DisabledInput` should be deprecated/removed.

1. We can make almost any of the existing inputs disabled by setting either their `disabled` or `readonly` prop.

2. We are binding a TextInput to the record value but are just not passing the event handlers. This results in an unresponsive text input, which is weird and probably confusing for people using screen readers as nothing indicates this input is readonly/disabled

**Comment by fzaninotto** [comment]
I agree. We should even remove it completely from 3.0 instead of deprecating it.

**Comment by djhi** [comment]
Do you mean we should remove all other deprecated components (LongTextInput for example)?

**Comment by fzaninotto** [comment]
Fixed by #3549

**Comment by Kunnu01** [comment]
@djhi @fzaninotto Does the `LongTextInput` needs to be removed? Should I work on it?

**Comment by ouonet** [comment]
in https://react-admin.com/docs/en/tutorial.html, the example still use DisabledInput and LongTextInput . that causes confusion  for beginner.

**Comment by fzaninotto** [comment]
@ouonet You've read the wrong documentation. react-admin.com is not owned by the core team, and contains **outdated** documentation. The correct documentation, hosted at https://marmelab.com/react-admin/Tutorial.html, does not contain `<DisabledInput>` or `<LongTextInput>`. Please update your bookmarks.
