### ISSUE TITLE
Reimplement AutocompleteInput and AutocompleteArrayInput using downshift

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/react-admin#3519]
The V3 Roadmap (#3194) include a rewrite of `<AutocompleteInput>` and `<AutocompleteArrayInput>` using  `downshift`.

Here is the current PR implementation: #3031 

This issue purpose is to list all problems the new implementation should fix:

- #2961 The suggestion list is wrongly placed when a second search as few results
- #2428 The suggestion list appears again after a suggestion is selected
- #3098 The `<AutocompleteInput>` doesn't work in a `<ReferenceInput>`
- #3148 The selected value is always the first suggested item (even if it shouldn't)

**Comment by fzaninotto** [comment]
Fixed by #3031 and #3667
