### ISSUE TITLE
<ReferenceArrayField> sends improper `ids` array in `payload` parameter

### ISSUE THREAD

**Issue by Sheraff** [marmelab/react-admin#3530]
Hello Marmelab team, I started using react-admin about a week ago and trying to connect a custom API to your frontend. I have an issue with `<ReferenceArrayField>` where 
1. if I land on the view where it's declared (or refresh it), everything goes well: GET_ONE gets the info for the `<Edit>` view, and GET_MANY fetches related data for the `<ReferenceArrayField>`
2. if I navigate to said view (click from preceding `<List>` view), the GET_MANY request is sent with a `payload` argument with an empty `ids` array

After investigating, I found that the issue stems from the fact that when navigating from the `<List>` view to the `<Edit>` view, react-admin first tries to display the the `<Edit>` view with the bits of data it obtained from the List's GET_LIST request. In my case: 
- GET_LIST (from `<List>` view) didn't return an array of relationships related to the item (but GET_ONE does). 
- Thus GET_MANY is called with an empty `ids` array, and loads infinitely,
- the GET_ONE (from `<Edit>` view) request yields (with an array or relationships) but react-admin never ends up using it.

This seems counter intuitive / a bug / a feature request. It seems reasonnable that GET_LIST wouldn't return an array of relationships (bigger cost on database when we're already fetching a list) and that GET_ONE would (fetching a single item, with all its details).

The ways to bypass this issue seem to be
1. tweaking our custom API to return relationships on its GET_LIST endpoint
2. upgrading to 3.0-alpha

If I were to go with solution 2. could you give me an idea of how the project is going for version 3.0 stable ? 

Thank you very much, and thanks for reading me this far ;)

-----

For more info on how the issue manifests itself, keep reading.

Here are the main components involved here:
- `App.js` with `<Admin>` declaring resources (the destructured objects contain `name`, `List`, `Edit`...)
```javascript
const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource {...Courses} />
        <Resource {...Sessions} />
    </Admin>
)
```

- `<Edit>` view for the *Courses* resource, containing the `<ReferenceArrayField>` that seems to be causing me trouble
```javascript
export const CourseEdit = props => {
    return (
        <Edit {...props}>
            <SimpleForm>
                <LongTextInput source="title"/>

                <ReferenceArrayField label="Sessions" reference="sessions" source="relationships.sessions">
                    <Datagrid>
                        <TextField source="id" />
                        <TextField source="slug" />
                        <Logger>
                    </Datagrid>
                </ReferenceArrayField>

            </SimpleForm>
        </Edit>
    )
}
```

- `<Logger>`: small utility component to see what props were received:
```javascript
export const Logger = ({resource, record}) => {
	console.log(`Logger component: ${resource}`, record)
	return <></>
}
```

Now as I described above, there are two paths that can be taken to this `<Edit>` view, and that lead to different outcomes.

1. Landing directly (refreshing) on Courses Edit page results in proper "sessions" list:
    - GET_ONE request queried @ courses/5?include=sessions
    - GET_MANY for sessions, {ids: [9, 10]} *=> falls back to `Promise.all` with array of GET_ONE*
        - GET_ONE request queried @ sessions/9
        - GET_ONE request queried @ sessions/10
    - Logger component: sessions, {id: 9}
    - Logger component: sessions, {id: 10}
![Screen Shot 2019-08-14 at 14 46 45](https://user-images.githubusercontent.com/1325721/63026884-3a1ad480-beac-11e9-9c01-afe2a4179eda.png)

2. Landing on Courses List, then navigating to Courses Edit page results in infinitely loading "sessions" list:
    - GET_LIST request queried @ courses?include=sessions&page=1&per_page=10&sort=id&sortOrder=DESC
    - *navigating (user interaction)*
    - GET_ONE request queried @ courses/5?include=sessions
    - GET_MANY for sessions, {ids: []}
![Screen Shot 2019-08-14 at 14 45 33](https://user-images.githubusercontent.com/1325721/63026864-35562080-beac-11e9-9c5d-1a848655c267.png)

As you can see, in the case where we come from the `<List>` view for Courses, the GET_MANY request doesn't receive the proper parameters. But if you look at the `<ReferenceArrayField>` declaration above, and the JSON samples below, it seems the behavior (empty `ids` array) is a bug.

- Sample result after a GET_ONE request **and** `dataProvider` processing of result for /courses: 
```json
{
    "data": {
        "id": 5,
        "title": "Le soir, en rentrant, il la quittait, il.",
        "sessions": [
            {
                "id": 9,
                "slug": "je-mimaginais-quelquefois-quun-hasard-vous"
            },
            {
                "id": 10,
                "slug": "sur-la-fosse-entre-les-dents-une-dame-prs"
            }
        ],
        "relationships": {
            "sessions": [9, 10]
        }
    }
}
```

- Code for GET_MANY bridge in `dataProvider`: 
```javascript
case GET_MANY: {
    return Promise.all(
        payload.ids.map(id => {
            const { url, options } = convertDataRequestToHTTP(GET_ONE, resource, { id, ...payload })
            return httpClient(url, options)
                .then(response => {
                    const { data } = convertHTTPResponse(response, GET_ONE, resource, payload)
                    return data
                })
        })
    ).then(responses => ({ data: responses }))
}
```

- Sample result after a GET_MANY request **and** `dataProvider` procesing for /sessions:
```json
{
    "data": [
        {
            "id": 9,
            "slug": "je-mimaginais-quelquefois-quun-hasard-vous"
        },
        {
            "id": 10,
            "slug": "sur-la-fosse-entre-les-dents-une-dame-prs"
        }
    ]
}
```

- Sample result after a GET_LIST request **and** `dataProvider` procesing for /courses (**note how there isn't a relationships array here**):
```json
{
    "data": [
        {
            "id": 5,
            "title": "Le soir, en rentrant, il la quittait, il.",
            "sessions": [
                {
                    "id": 9,
                    "slug": "je-mimaginais-quelquefois-quun-hasard-vous"
                },
                {
                    "id": 10,
                    "slug": "sur-la-fosse-entre-les-dents-une-dame-prs"
                }
            ]
        }
    ],
    "total": 1
}
```

**Environment**

* React-admin version: 2.9.5
* React version: 16.8.6
* Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by djhi** [comment]
Thanks for the very detailed issue. This is indeed a limitation of react-admin: we expect that all routes for a given resource (GET_LIST, GET_ONE, etc.) will return resources with the same shape. I'm not sure we already addressed it in v3.

About the GET_ONE vs GET_MANY: this is because we *accumulate* GET_ONE calls into one GET_MANY. This is useful inside a List if it has a `ReferenceField` as it avoid making many GET_ONE requests (for each row).

> If I were to go with solution 2. could you give me an idea of how the project is going for version 3.0 stable ?

I don't really understand the question. You can check the [upgrade guide](https://github.com/marmelab/react-admin/blob/next/UPGRADE.md) as we try to keep it up to date with every PR introducing breaking changes.

**Comment by fzaninotto** [comment]
This is indeed a react-admin limitation. Your dataProvider should return the same shape in `GET_LIST` and `GET_ONE` (and if your API doesn't have this constraint, the `dataProvider` is the right place to transform the `GET_LIST` payload before returning it).

React-admin v3 has the same limitation, and I don't understand how it could do otherwise without deeply changing the react-admin internals.

But this is a recurrent gotcha, so I feel that we should do a better job at documenting the limitation. So I'm marking this as a documentation bug.
