### ISSUE TITLE
BooleanInput: onChange handler not called (3.0.0-alpha.2)

### ISSUE THREAD

**Issue by BowlingX** [marmelab/react-admin#3541]
**Issue**
The `<BooleanInput />` component is currently not responding to any change on toggling. 

**Related code:**
https://github.com/marmelab/react-admin/blob/next/packages/ra-ui-materialui/src/input/BooleanInput.tsx#L62

The `onChange` handler is overwritten directly with the `input`'s builld in `onChange`, which yields to a wrong result.

Version: `3.0.0-alpha.2`
React: `16.9`
Browser: latest `Chrome`

**Comment by djhi** [comment]
We extract the `onChange` from the input props at https://github.com/marmelab/react-admin/blob/next/packages/ra-ui-materialui/src/input/BooleanInput.tsx#L31, so it shouldn't be injected.

Besides, this input seems to work pretty well in the simple example on the `next` branch

**Comment by BowlingX** [comment]
Great ok :). Then it's only broken in the current alpha release, sorry I checked only the source that was bundled inside the NPM Package. I guess we can close the issue as already fixed :).

**Comment by alrik** [comment]
I experienced the exact same issue on alpha.2. @djhi Awesome, this is already fixed :tada: Is there an ETA for the next alpha release?
