### ISSUE TITLE
Add "row" property to CheckboxGroupInput and pass it to FormGroup

### ISSUE THREAD

**Issue by jedrzejowski** [marmelab/react-admin#3547]
While having many choices with long text, control starts to be unreadable:
![Screenshot_20190820_122831](https://user-images.githubusercontent.com/15786714/63340907-599c7c00-c348-11e9-9030-6def2aa03488.png)

Perfect solution would be to be place check boxes in column.

I have made some research and discovered that CheckboxGroupInput is using [FormGroup](https://material-ui.com/api/form-group/), here:
[packages/ra-ui-materialui/src/input/CheckboxGroupInput.js#L195](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/CheckboxGroupInput.js#L195)
As u can see property row is passed to FormGroup without possibility to alter it.
MUI documentation states that row property define how item would be displayed, in row(true) or in column(false).

Please, add "row" property to CheckboxGroupInput and pass it to FormGroup.

My temporary solution:
I have edited `node_modules/ra-ui-materialui/esm/input/CheckboxGroupInput.js` and changed file responsible for this property and added it to git.
But this solution is just bad.

**Comment by fzaninotto** [comment]
Fixed by #3561
