### ISSUE TITLE
Incorrect Links in 2.9.6 Release.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3567]
Links to pull request say "gihub" in the url instead of "github" for version  2.9.6.

[https://github.com/marmelab/react-admin/releases](https://github.com/marmelab/react-admin/releases)

Also in the ChangeLog:
[https://github.com/marmelab/react-admin/blob/master/CHANGELOG.md](https://github.com/marmelab/react-admin/blob/master/CHANGELOG.md)

**Comment by fzaninotto** [comment]
Thanks for reporting this! It's now fixed.
