### ISSUE TITLE
upgrading to 3.0.0-alpha.3 breaks compilation

### ISSUE THREAD

**Issue by esistgut** [marmelab/react-admin#3597]
On my current project this:

```
-    "ra-core": "^3.0.0-alpha.2",
-    "ra-data-graphql-simple": "^3.0.0-alpha.1",
+    "ra-core": "^3.0.0-alpha.3",
+    "ra-data-graphql-simple": "^3.0.0-alpha.3",
-    "react-admin": "^3.0.0-alpha.2",
+    "react-admin": "^3.0.0-alpha.3",
```
results in this error:
```
Failed to compile.

./node_modules/ra-ui-materialui/esm/layout/DeviceTestWrapper.js
Module not found: Can't resolve 'css-mediaquery' in '/myproject/node_modules/ra-ui-materialui/esm/layout'
```

**Comment by djhi** [comment]
Sounds like an issue with your material-ui version. Try removing your node_modules and reinstall or upgrade it manually to its latest version. We might have to fix our dependencies versions though

**Comment by esistgut** [comment]
I tried to upgrade every other package in my `package.json`, `@material-ui/core` was already at version 4.3.3, I removed `package-lock.json` and the `node_modules` directory and performed a fresh `npm i`, the error persists.

**Comment by djhi** [comment]
This is indeed an issue on our side. The `css-mediaquery` is used in `DeviceTestWrapper` which we provide to help users to test their components. However, this module is in the dev dependencies...

Workaround until we publish another alpha, install it yourself:

`npm install css-mediaquery`

**Comment by fzaninotto** [comment]
Fixed by #3603

**Comment by denisesenguel** [comment]
FYI this bug seems to be back. After upgrading to `4.1.4` the issue re-appeared for me and I had to manually install `css-mediaquery` as described above

**Comment by fzaninotto** [comment]
@denisesenguel Which is the latest version that didn't have the bug for you?

**Comment by denisesenguel** [comment]
@fzaninotto I was on `4.0.3` before

**Comment by fzaninotto** [comment]
OK, it must be due to the move from `tsup` to `tsc`, reintroduced in #7818. I'll reopen this issue and push a fix.
