### ISSUE TITLE
Payload passed to dataProvider doesn't contain File from ImageInput [3.0.0-alpha only]

### ISSUE THREAD

**Issue by Sheraff** [marmelab/react-admin#3607]
I'm making a react-admin app and I'd like to be able to handle file uploads. I have read the appropriate documentation on [decorating-your-data-provider-example-of-file-upload](https://marmelab.com/react-admin/DataProviders.html#decorating-your-data-provider-example-of-file-upload) and I already have a custom `dataProvider`.

The problem is that said **`dataProvider` never receives any info about files passed to `<ImageInput>`**.

Here's a simplified view of the app's structure:

```javascript
import { fetchUtils } from 'react-admin';

const jsonServerProvider = (apiUrl, httpClient = fetchUtils.fetchJson) => {
	return (type, resource, payload) => {
		console.log('making API request', type, resource, payload)

		const options = { // ... }
		const url = `${apiUrl}/${resource}/...`;
		
		return httpClient(url, options)
	}
}

const dataProvider = jsonServerProvider(`${domain}/api/v1`);

const App = () => (
	<Admin dataProvider={dataProvider} >
		<Resource {...MediaLibraries} />
	</Admin>
);
```

And `MediaLibraries` contains a `create` key to the following component:

```javascript
const MediaLibrarieCreate = props => (
	<Create {...props}>
		<SimpleForm defaultValue={defaultValue}>
			<TextInput source="title" />
			<ImageInput source="file" accept="image/*" >
				<ImageField source="url" title="title"/>
			</ImageInput>
		</SimpleForm>
	</Create>
);
```
Now this has an issue addressed in a separate issue (https://github.com/marmelab/react-admin/issues/3606) but the problem here is that this **`<Create>` component doesn't send the `File` payload to the `dataProvider`**.

I can observe that the `File` is passed to the `<ImageInput>` with an extra component:

```javascript
const Test = props => {
	console.log(props)
	return <ImageField title="title" {...props}/>
}

// ...

<ImageInput source="file" accept="image/*">
	<Test source="url"/>
</ImageInput>
```
Which logs the following:
```
{
	className: "ImageInput-preview-213"
	record: {
		rawFile: File
			lastModified: 1566296107287
			lastModifiedDate: Tue Aug 20 2019 12:15:07 GMT+0200 (Central European Summer Time) {}
			name: "493ca08cec56142508776cab706c07ca.jpg"
			preview: "blob:http://localhost:3002/c99da6a6-a506-4c25-b8f2-62b3c4f9c966"
			size: 58380
			type: "image/jpeg"
			webkitRelativePath: ""
			__proto__: File
		}
		url: "blob:http://localhost:3002/c99da6a6-a506-4c25-b8f2-62b3c4f9c966"
	}
	source: "url"
```

But when I click "Save" on the `<Create>` form, the dataProvider doesn't receive any File object. Here's what the `console.log` from the `jsonServerProvider` (shown above) logs:
```
making API request
CREATE
mediaLibraries
{
	data: 
		title: "test CREATE image"
}
```

Whereas I'm expecting the `payload` argument to contain some sort of `file.url`. 

This is only an issue in react-admin v3. I have implemented this in v2 without any issues.

---
- macOS 10.14.6
- Chrome 76.0.3809.100
- react-admin 3.0.0-alpha.2

**Comment by fzaninotto** [comment]
OK, so the solution is: upgrade to alpha.3. Thanks for the bug report!

**Comment by Sheraff** [comment]
I just tested. This is fixed indeed. Though the <FileInput> won't open a dialog when clicked. It still works when dropping a file on it though ;)
