### ISSUE TITLE
Modularize the GraphQL data loader implementations

### ISSUE THREAD

**Issue by dantman** [marmelab/react-admin#3611]
**Is your feature request related to a problem? Please describe.**
Currently the only two GraphQL implementations are `ra-data-graphcool` and `ra-data-graphql-simple`.

Both of these are pretty similar with small differences like `skip`/`page`, `first`/`perPage`, and `orderBy`/`sortOrder`.

And while these two libraries do allow you to override the patterns for how things are named (e.g. change `allPosts` to `Posts`). You cannot easily adapt them to other GraphQL API patterns.

For example if, instead of an API where there are `allPosts(): [Post]` and `_allPostsMeta(): { total }` I had an API where pagination was done using `allPosts() { items: [Post], totalCount }`. But the other 90% of the API structure was the same as `ra-data-graphql-simple`, I would have to copy most of the library (around 650 lines of code) just to make a small modification to it. `ra-data-graphql` may abstract some things, but it still takes a significant amount of code to actually implement a GraphQL data connector for react-admin.

It also feels redundant because looking at `ra-data-graphcool` and `ra-data-graphql-simple`, it feels like I see a lot of duplication in the code between the two.

**Describe the solution you'd like**
I would prefer it if much of the common patterns in the graphql data libraries were separated out into modules/packages/utilities that make it easier to handle GraphQL APIs that are slightly different. Especially for things where `ra-data-graphcool` and `ra-data-graphql-simple` have duplicate code. Like how `buildCreateUpdateVariables` in both libraries is 100% the same, and the first 54 lines of `buildGetListVariables` is basically the same.

**Describe alternatives you've considered**
I considered copying the library to change the code. But it's over 650 lines of code and the portion changed is really small, so there is a significant amount of code that would not be changes but not keep up with changes to the library.

I also considered importing `ra-data-graphql-simple` and essentially wrapping portions of it. But there are significant portions of the code that look like you cannot make small modifications to it without duplicating a significant amount of code.

**Comment by djhi** [comment]
Hi @dantman. This is something I wanted to do for a long time but I wanted to get more feedbacks from people building other implementations. We don't have enough of them yet. So thanks!

Some of the duplicated code should probably be moved inside `rat-data-graphql` and might be refactored to allow easier usage. I'd gladly review any pull requests doing that.

Feel free to open one and I'll do my best to assist. Thanks!

**Comment by fzaninotto** [comment]
This enhancement request hasn't gained enough interest to get a PR from the community. As we canot keep all feature requests open, I'm closing it.

If you feel like working on this feature, we'd love a PR!
