### ISSUE TITLE
[alpha.3] defaultValue no longer working

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3627]
Seems like after rewrite to final-form

the defaultValue on SimpleForm and TabbedForm no longer works

and initialValues is not defined as prop, nor mentioned in docs

**Comment by djhi** [comment]
Right.. I wonder how we should handle this as final-form does not support `defaultValue`.

I think we should retrieve both `initialValues` and `defaultValue`, then:
- use only `initialValues` if both are defined, with a warning about `defaultValue` being deprecated and that it will be overridden by `initialValues`
- pass `defaultValue` as `initialValues` to `final-form` if `defaultValue` was the only one defined

**Comment by fzaninotto** [comment]
Fixed by #3756
