### ISSUE TITLE
[alpha.3] problems with permissions in List

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3629]
aka using example from docs to hide buttons in grid

Seems like in v3 is some problem with permissions or rerendering

Showcase from the simple example: 
https://codesandbox.io/s/simple-7zyys

![Aug-30-2019 15-00-16](https://user-images.githubusercontent.com/488136/64022790-3c7d5f80-cb37-11e9-95f1-eb0b6a239a87.gif)

as you can see the buttons are showed only for admin, but if you go away from page, and return, the button's are now gone

Steps to reproduce:
1) open example, you will se buttons if you are admin
2) go to another page
3) go back, you will now see the buttons are gone even if you are admin

**Comment by djhi** [comment]
Thanks for reporting and the reproduction sandbox!

**Comment by djhi** [comment]
I think this is actually the same issue as #3631

**Comment by fzaninotto** [comment]
Fixed by #3635
