### ISSUE TITLE
Support React Element as optionText in AutocompleteInput

### ISSUE THREAD

**Issue by yelworc** [marmelab/react-admin#3630]
**Is your feature request related to a problem? Please describe.**
I'd like to apply some simple custom formatting to the choices displayed in an `AutocompleteInput` (so the available values are presented the same way as in other places, e.g. in a list view).

**Describe the solution you'd like**
Other input elements (e.g. `SelectInput`) allow passing a React Element as the `optionText` prop, which enables flexible customization of the way the values are rendered. `AutocompleteInput` only accepts a string (choice field name) or a function returning a string in that prop.

**Additional context**
I'm guessing it currently only works with plain strings is because there is already some formatting applied to the autocompleted choices (highlighting of the matching substring). A custom element passed as `optionText` would have to implement that itself, if desired.

I checked the reimplemented `AutocompleteInput` in the latest v3 branch, but this particular aspect seems to be unchanged so far.

**Comment by fzaninotto** [comment]
Fixed by #3683
