### ISSUE TITLE
Search/Filter is not working with firebase provider

### ISSUE THREAD

**Issue by AngularMast** [marmelab/react-admin#3633]
**What you were expecting:**

Add a search bar by my specific fields.

**What happened instead:**

No search bar and some redux hot loading console errors.

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox you can fork this one: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
const SearchFilter = props => (
  <Filter {...props}>
    <TextField label="Search" source="name" alwaysOn />
  </Filter>
)

export const SearchList = props => (
  <List {...props} filters={<SearchFilter />}>
    <Datagrid>
      <TextField source="name" />
      <TextField source="avgRating" />
      <TextField source="numReviews" />
      <EditButton label="" />
      <DeleteButton label="" redirect={false} />
    </Datagrid>
  </List>
)
```

**Other information:**

<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions. 
    in Provider (created by CoreAdminBase)
    in CoreAdminBase (created by withContext(CoreAdminBase))
    in withContext(CoreAdminBase) (at Admin.js:19)
    in AdminView (at App.js:222)
    in Router.Consumer (created by Route)
    in Route (at App.js:219)
    in App (at src/​index.js:10)
**Environment**
macOS Mojave
* React-admin version:2.9.5
* Last version that did not exhibit the issue (if applicable):
* React version:16.9.0
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
I can't reproduce the problem with another provider. 

This seems to be related to the Firebase `dataProvider`, that is not maintained in this repository. I encourage you to open an issue in https://github.com/aymendhaya/ra-data-firebase-client (if that's what you used).

**Comment by dmytropaduchak** [comment]
ERROR in ./node_modules/ra-data-firebase-client/dist/index.es.js 2:0-29
Module not found: Error: Can't resolve 'sort-by' in './node_modules/ra-data-firebase-client/dist'
