### ISSUE TITLE
Add linkText to UrlField

### ISSUE THREAD

**Issue by jheiska** [marmelab/react-admin#3639]
Sometimes URL:s can be quite long. For a more readable outcome (especially in the list view!) it would be nice if you could have an option to add a text for the link. For example

`<UrlField source="superlongurl" linkText="Click me!" />`
would translate to
`<a href="http://thefetchedsuperlongurlfromthesourcerecord">Click me!</a>`

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. I'm not convinced by your idea, because in a list, all records will show a "click me" link. Besides, it's a one liner that you can achieve in userland:

```jsx
const UrlField = ({ record, source }) => <a href={record[source]}>Click me!</a>;
```

So I'm going to close this feature request.

**Comment by alextaymx** [comment]
Hi there, the Custom url field seems to clash with the rowClick="edit" in datagrid, it wont redirect to the url but instead to the edit page

**Comment by cydergoth** [comment]
i have a use case for this feature where the the datagrid is a list of field name: field value. For each field value which is a URL, we need to use the Field Name as the URL text.

**Comment by cydergoth** [comment]
I used :
```
import { Link, TextField } from 'react-admin';

const NamedUrl = (props) => (<span><Link to={get(props.record, props.source)}><TextField source={props.label_source}/><LaunchIcon/></Link></span>)

NamedUrl.propTypes = {
    label: PropTypes.string,
    record: PropTypes.object,
    source: PropTypes.string.isRequired,
    label_source: PropTypes.string.isRequired,
};

Then:

```
  case 'url': return (<NamedUrl source={props.source} label_source="definition.name"/>);
```
