### ISSUE TITLE
Field margin is too small on ShowView

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#3641]
In v3, the ShowView and TabbedShowView layouts feels too packed. This is a regression due to the Form look and feel rework. 

![image](https://user-images.githubusercontent.com/99944/64133810-268ec980-cdd9-11e9-92d3-06acde756075.png)

**Comment by fboechats** [comment]
@fzaninotto Hello, I was taking a look at this and the problem is that in this version there's no top part where should be a Edit button, should we add that or just adapt to work without that upper part??

**Comment by fzaninotto** [comment]
The Toolbar lives outside of the main Card in v3. This is by design.

**Comment by fboechats** [comment]
So we should just adapt the padding to this new layout??

**Comment by fboechats** [comment]
So we should just adapt the padding to this new layout??

**Comment by fzaninotto** [comment]
@fboechats I'm not sure I understand your question. I've opened a PR to improve the default margins of Show views and solve this problem.

**Comment by fzaninotto** [comment]
Fixed by #3648
