### ISSUE TITLE
Login: Possible Security Risk with DOM warning

### ISSUE THREAD

**Issue by UltimateForm** [marmelab/react-admin#3650]
**What you were expecting:**
No warning, password is not raw-presented anywhere

**What happened instead:**
Warning log:
`[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input aria-invalid=​"false" class=​"jss726 jss729" name=​"password" type=​"password" value=​"etc_123">​`

(note: etc_123 was the password i inserted)

tested with demo and codesandbox (https://codesandbox.io/s/simple-1hrmf)

**Steps to reproduce:**
Log in, have browser save credentials, logout, and when the input field for login is auto-filled the log occurs with raw password

On code sandbox i had to open the webpage window on a new tab for the warning to occur as expected

**Related code:**
https://codesandbox.io/s/simple-1hrmf

**Other information:**
this is probably related to this:
https://bugs.chromium.org/p/chromium/issues/detail?id=889780
 
But it's probably fixable on your side if you set the autocomplete attribute to "current-password"

**Environment**
* React-admin version:2.9.6
* React version: 16.9.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
I can't reproduce the issue on your CodeSandbox. Which version of Chrome are you running?

**Comment by UltimateForm** [comment]
Hi, on codesandbox you have to open the webpage on a new tab of the browser for it to occur. It seems like the browser does not autofills those fields on the embeded window when credentials are saved. Either way the log also occurs the demo you have at examples.
![image](https://user-images.githubusercontent.com/24314735/64731578-693b5a80-d4d9-11e9-9eba-570182b366c8.png)

I'm using chrome version  77.0.3865.75 (64bits)

**Comment by Kmaschta** [comment]
I tested with: Chrome, Chromium, and Firefox and I have not this warning anytime on the demo nor on the CodeSandbox.

Do you see anything we are missing?

**Comment by UltimateForm** [comment]
i have no idea, over here the warning keeps appearing:
![image](https://user-images.githubusercontent.com/24314735/66303827-cfa67380-e8f3-11e9-9b27-829d6b17a0b7.png)
