### ISSUE TITLE
[alpha.4][v3] Cannot save empty item in SelectInput with allowEmpty

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3660]
SelectInput cannot be cleared when using allowEmpty

![Sep-09-2019 14-44-08](https://user-images.githubusercontent.com/488136/64531832-9be62700-d310-11e9-8b10-85484c216b0b.gif)

Reproduction sandbox:
https://codesandbox.io/s/simple-yd6sm

Reproduction steps:
1) open sandbox or some other form with select input with allowEmpty
2) try to change saved and select value to empty value
3) it will stay same

(it stays the same in PUT request)

**Comment by djhi** [comment]
Reproduced. Thanks!

**Comment by fzaninotto** [comment]
Fixed by #3758
