### ISSUE TITLE
Expand or collapse all nodes in Tree/NodeView 

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3678]
**Is your feature request related to a problem? Please describe.**
Using the `Tree` component from the [ra-tree-ui-materialui](https://github.com/marmelab/react-admin/tree/master/packages/ra-tree-ui-materialui) package generally works fine. The default view however is with all nodes collapsed.

**Describe the solution you'd like**
When configuring the component I'd like to see a new property like e.g. `showExpanded` which would show the tree view with all its nodes.

As an alternative, a "switch" could be made available which toogles the tree between showing all nodes collapsed or expanded.

**Comment by jdemangeon** [comment]
@djhi does this issue always up to date?

**Comment by djhi** [comment]
As we decided to not implement it in the v3, I think you can close it.

**Comment by jdemangeon** [comment]
Thanks!

**Comment by djhi** [comment]
As said before, we won't work on a tree component in the OSS version. We do have one as an enterprise package though, which is not built with MUI for now. See https://marmelab.com/ra-enterprise/modules/ra-tree
