### ISSUE TITLE
Apply filters to all elements in a tree

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3679]
**Is your feature request related to a problem? Please describe.**
It is cumbersome to find "relevant" nodes if there a lot of items in a `Tree` component (using the [ra-tree-ui-materialui](https://github.com/marmelab/react-admin/tree/master/packages/ra-tree-ui-materialui) package).

**Describe the solution you'd like**
I'd like to define a filter which filters all nodes including sub-nodes.

**Describe alternatives you've considered**
I tried to use the "standard" way of defining a filter for the surrounding `List` view but it seems as if this filter only applies to the top-level nodes.

**Comment by fzaninotto** [comment]
The tree packages were removed from the core in 3.0.
