### ISSUE TITLE
Issue with the Content-Type header for GET requests

### ISSUE THREAD

**Issue by clement-escolano** [marmelab/react-admin#3687]
**What you were expecting:**

When React-Admin fetches the list of items for a specific model with `fetchUtils.fetchJson`, the GET request should not have a `Content-Type` header.

**What happened instead:**

A `Content-Type` header with the value `application/json` is added to the request.

**Steps to reproduce:**

Create a sample react-admin application and go to the list of items for an entity.
Check the HTTP headers of the request.

**Related code:**

I am sorry I cannot provide a sample right now but any React-Admin application using `fetchUtils.fetchJson` for your HTTP requests should show the issue. The related code adding this header for `fetchUtils.fetchJson` is:

https://github.com/marmelab/react-admin/blob/893add6e7c98be3a68f55fb42c9f8fbd7879d3d9/packages/ra-core/src/util/fetch.ts#L16-L21

**Other information:**

As per the [Mozilla documentation of the header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type), the `Content-Type` header in a request indicate the type of the body, which is relevant for `PUT` or `POST` requests but not `GET` requests.

I am particularly affected by this issue because a firewall in my company is blocking these requests. As it is not required for `GET` requests, I think it can be removed.

I am willing to work on a PR to fix this if this is OK for you.

**Environment**

* React-admin version: 2.9.6
* Last version that did not exhibit the issue (if applicable): None
* React version: 16.4.1
* Browser: All

**Comment by fzaninotto** [comment]
Sure, feel free to open a PR for it. Thanks for the report!
