### ISSUE TITLE
Set ReferenceInput to "null" completely

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3690]
In my `Create` view I have defined a `ReferenceInput` like this:

```xml
      <ReferenceInput
        source="category.id"
        reference="category"
        allowEmpty
        emptyValue={null}
        sort={{ field: "name", order: "ASC" }}>
        <SelectInput optionText="name" />
      </ReferenceInput>
```

It fetches and displays the referenced "categories" correctly. When saving the record I observed the following behavior.

**Saving with a valid value from the reference**
So if I select any valid value in the `SelectInput` the JSON payload looks like this:
```json
{
  "id": 1,
  "version": 8,
  "type": "K",
  "category": {
    "id": 598,
    "name": "New name"
  }
}
```

My problem is that the `category` is optional, i.e. I added `allowEmpty`. In this case the JSON looks like this:
```json
{
  "id": 1,
  "version": 8,
  "type": "K",
  "category": {
    "id": null,
    "name": ""
  }
}
```

But actually this is not what I require. My request should look like this:

```json
{
  "id": 1,
  "version": 8,
  "type": "K",
  "category": null
}
```

Could we add a property to the `ReferenceInput` like `nullable`?

**Comment by fzaninotto** [comment]
As the `source` is `category.id`, react-admin only changes that field - not the surrounding `category` field. To do what you want, you'll need some transform logic before submission via redux-form. 

As it's not a react-admin bug, I'm closing this issue.
