### ISSUE TITLE
tab label not change to red while one of it's input  with source='post.title'(the source like x.y) is invalid

### ISSUE THREAD

**Issue by atares0223** [marmelab/react-admin#3695]
**What you were expecting:**
tab label change to red while one of it's input with source='post.title'  is invalid. 
**What happened instead:**
tab label not change to red, once click save, you don't know where is invalid for a TabbedForm.
**Steps to reproduce:**
create a TabbedForm with FormTabs.
create some tabs.
have one input with source='post.title' and required. 
switch to other tab , the tab have 'post.title' is not showing warning red label.
`<TextInput source="post.title" validate={required()}/>`
![image](https://user-images.githubusercontent.com/16397455/65012439-ec313a80-d949-11e9-83c4-79904c3adb77.png)
![image](https://user-images.githubusercontent.com/16397455/65012502-23075080-d94a-11e9-8629-98c2bc68b022.png)

**Related code:**
https://codesandbox.io/s/simple-ttj4i?fontsize=14

**Environment:**

React-admin version: 2.9.1 and v3 alpha
React version: 16.8.6
Browser: Chrome

**Comment by djhi** [comment]
Please follow the issue template

**Comment by atares0223** [comment]
@djhi please help me figure it out.  it not surpport complex source for a input.

**Comment by djhi** [comment]
Your codesandbox does not use the version of react-admin you specified in the issue template: it is based on the v3 alpha and not on `v2.9.1`.

Besides, using `v2.9.6`, I cannot reproduce the issue.

Please either provide a codesandbox with the version of react-admin you are actually using or correct your issue description

**Comment by atares0223** [comment]
@djhi  thanks for help , my dev version is v2.9.1 and the codesandbox is v2.9.6. it's both not working.
I think I don't make myself clearly, the  codesandbox can reproduce the issue.
steps in the  codesandbox:
1. go to post edit page.
2. make sure that the 'post.title' is empty so that is will trigger a invalid required warnning under the input.
3. switch to other tabs except SUMMARY.
4.it should trigger a event that make the label of the **SUMMARY** tab to **red 'SUMMARY'** , but it's not. since the source is changed from 'title'->'**post.title**'  (a format like **x.y**)

**Comment by djhi** [comment]
Try upgrading to `2.9.6`

**Comment by djhi** [comment]
I cannot reproduce your issue on the official codesandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)

**Comment by atares0223** [comment]
@djhi  sorry ,but I can reproduce the issue through 
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
steps:
1. go to one of Post Edit View and makes the title to empty.you can see the 'Post.title' is required warning.
![image](https://user-images.githubusercontent.com/16397455/65135226-211bbb00-da38-11e9-8cf8-d9c83fa40e37.png)
2.switch to BODY tab. so you can see the SUMMARY tab is red.
![image](https://user-images.githubusercontent.com/16397455/65135371-64762980-da38-11e9-9851-b34aec6f38df.png)
3. change source the **title** input  from source='title' to source='post.title' .
![image](https://user-images.githubusercontent.com/16397455/65135578-c33ba300-da38-11e9-9bc6-7c0907da6d5c.png)
4. do the step 1 again, you can see the 'Post.title' is required warning.
![image](https://user-images.githubusercontent.com/16397455/65135659-e403f880-da38-11e9-9925-4365ec1c4631.png)
5.do the step 2 again (switch to BODY tab),  and now the SUMMARY tab is **not red**!!
![image](https://user-images.githubusercontent.com/16397455/65135760-0e55b600-da39-11e9-9d12-059a09257b57.png)

**Comment by djhi** [comment]
Sorry, I read your description too quickly apparently. Confirmed

**Comment by atares0223** [comment]
cool , @djhi ,thanks.

**Comment by atares0223** [comment]
Hi @djhi , I had reinstalled react-admin at version of ^2.9.7. but this bug is still existed, what version can I use or waiting for 3.00 version release?

**Comment by fzaninotto** [comment]
The introduction of FormGroups in 3.12 (#5712) finally solves this properly.
