### ISSUE TITLE
Filters with a drop-down list are saved after going to another page

### ISSUE THREAD

**Issue by Manviel** [marmelab/react-admin#3717]
**What you were expecting:**
After going to another page, the selected filters should be reset

**What happened instead:**
After going to another page, the selected filters remain and filter the content

**Steps to reproduce:**
- select the Сustomers resource in the drop-down sidebar list
- click on Add filter button and choose Segments
- choose any option in the list
- after that, select Segments resource in the drop-down sidebar list
- return to Сustomers resource page

**Environment**
https://marmelab.com/react-admin-demo

**Comment by fzaninotto** [comment]
That's not a bug, that's a feature!

**Comment by Manviel** [comment]
Ok, but can you offer me a solution to my problem?

**Comment by fzaninotto** [comment]
Or, write a custom menu in which the menu items link to a list with empty filters.
