### ISSUE TITLE
[v3] Filter does reload whole app on Enter

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3731]
Filter does not stop enter from submiting the whole form to browser as GET to current url

in v2 there was no form but only div so it did not happen

repro in basic simple example: https://codesandbox.io/s/simple-wsknw

could be probably fixed by onSubmit={e => e.preventDefault()} on < form >

steps to reproduce:

1) click to search
2) write to search something and press enter before it auto-submits
3) you will get normal browser form submit to GET
4) the whole app reloads and seems like filtering failed (well, it failed)

![Sep-24-2019 16-21-35](https://user-images.githubusercontent.com/488136/65520429-d55d8b80-dee7-11e9-82f5-6d6825f0e545.gif)

**Comment by natrim** [comment]
btw one more thing on filter, when the form autosubmits the input loses focus which can get annoying sometimes

**Comment by djhi** [comment]
Thanks for the report!

**Comment by fzaninotto** [comment]
Fixed by #3732
