### ISSUE TITLE
[v3] Regression - BooleanInput - cannot change by clicking on label

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3734]
BooleanInput cannot be toggled by click the label
(worked in v2)

![Sep-25-2019 10-37-31](https://user-images.githubusercontent.com/488136/65584161-c1199d00-df80-11e9-93ad-75d01a38414e.gif)

repro: https://codesandbox.io/s/simple-wsknw

Step to reproduce:
1) open edit post and go to miscellanous
2) try to toggle checkbox by clicking on label
3) does not work in v3

**Comment by djhi** [comment]
Reproduced. Thanks for reporting!

**Comment by fzaninotto** [comment]
Fixed by #3736
