### ISSUE TITLE
Changing filter in `ReferenceArrayInput` does change the filter added to the `GET_LIST` action.

### ISSUE THREAD

**Issue by FaizuddinEverest** [marmelab/react-admin#3739]
**What you were expecting:**

Updating filter in `ReferenceArrayInput` should update the filter added in the `GET_LIST` API call.

**What happened instead:**

Updating filter in `ReferenceArrayInput` does not update filter in the API call. Uses the stale filter.

**Steps to reproduce:**

https://codesandbox.io/s/simple-cop17?fontsize=14

Try to create a Post `/posts/create` which has a `ReferenceArrayInput` for searching a user. You can see in the browser console action logger that the `filter` in the `GET_LIST` call is one form change old.
![image](https://user-images.githubusercontent.com/47523926/65655636-82481d80-e03a-11e9-8aa0-b6750b01ed60.png)

See in the screenshot above - the user input for email does not match the filter in the action.

**Other information:**

I believe this is happening because the `fetchOptions` in the line [203](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx#L203) in `ReferenceArrayInputController` is called without passing the `nextProps` as argument which means the `defaultFilter` in line [262](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx#L262) is still the old filter.

**Environment**

* React-admin version: ^2.9.5
* Last version that did not exhibit the issue (if applicable):
* React version:^16.8.6
* Browser:Chrome
* Stack trace (in case of a JS error):

**Comment by FaizuddinEverest** [comment]
This works in `ReferenceInputController` because:
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/ReferenceInputController.tsx#L252

The `filterFromProps` is being extended by the current `filter` and in `ReferenceArrayInputController` it's the other way.

**Comment by TheHyphen** [comment]
I went ahead and made a PR here with the small change, https://github.com/marmelab/react-admin/pull/3740

Please let me know if this is good enough.
