### ISSUE TITLE
Adding a custom logout button results in error: withRef is removed

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3774]
**What you were expecting:**
I expected the app to compile and run without any errors. It should display a custom logout button.

**What happened instead:**
When opening the application I get the following error message.
`
withRef is removed. To access the wrapped instance, use a ref on the connected component`

<img width="1022" alt="grafik" src="https://user-images.githubusercontent.com/18437455/66207939-53721d00-e6b4-11e9-8611-457b96c21157.png">

**Steps to reproduce:**
I followed the description on how to use a custom logout button from [this documentation](https://marmelab.com/react-admin/Authentication.html#customizing-the-login-and-logout-components).

I found some hints that one should add the following property:

```
{
  forwardRef: true
}
```

But I cannot find where this should happen.

**Environment**

* React-admin version: 2.9.6
* Browser: Firefox 69.0.2

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
which version of material-ui are you using?

**Comment by straurob** [comment]
> which version of material-ui are you using?

That's `@material-ui/core@4.5.0` and `@material-ui/icons@4.4.3`

**Comment by djhi** [comment]
react-admin v2 is not compatible with material-ui v4. You might use the v3 though if you don't mind some warnings.

**Comment by djhi** [comment]
To use mui v4, you can try our latest beta

**Comment by straurob** [comment]
> react-admin v2 is not compatible with material-ui v4. You might use mui v3 though if you don't mind some warnings.

Thanks for the information. I downgraded to the following packages but I still see the error mentioned above.

`@material-ui/core@3.9.3`
`@material-ui/icons@3.0.2`

Maybe the reason is some incompatibility with `react-redux@7.1.1`?

**Comment by kopax** [comment]
@straurob you should use the same version of `dependencies` fixed by `react-admin` packages.

**Comment by straurob** [comment]
Thanks, using the explicit version of `react-redux@5.0.7` works.

**Comment by kopax** [comment]
This is because you can't use two stateful packages in your project (like `react-redux`).

In v3, you will have those stateful package set as `peerDependencies` in `ra-core`, `ra-ui-materialui`, etc.. and you will be able to manage the version by your own. (except if you use `react-admin` which will keep fixing those deps for you)

See https://github.com/marmelab/react-admin/pull/3763
