### ISSUE TITLE
 If there is the same id in my data, but the other data is different, how can I display it all?

### ISSUE THREAD

**Issue by 97thjingba** [marmelab/react-admin#3786]
**What you were expecting:**
When I need to write the same id, the DataGrid can still be displayed.
**What happened instead:**
When I expect the same data with the same id, the data will be displayed only one
**Environment**

- ra-data-json-server: ^2.1.1,
- react: ^16.4.1
- react-admin: 2.9.5

{
	"id": "2aa7dce4-e00d-462e-b025-68a351a82103",
	"created_at": "2019-09-30T10:13:43.840000+00:00"
},
{		
	"id": "1d620502-45a4-458b-a291-e1327c4f66b5",
        "created_at": "2019-09-30T10:13:24.722000+00:00"
},

My data is roughly the same

By the way ...I just want to use this id

**Comment by djhi** [comment]
I don't get the issue at all. Would you mind adding some examples ?

**Comment by Kmaschta** [comment]
Having a unique `id` field for each record of the same resource is a strong design choice.
You can't expect React Admin to function properly with not unique `id` field.

A workaround might be to generate this `id` field in a custom data provider based on a hash / concatenation of multiple field values, for example.
