### ISSUE TITLE
ra-data-graphql reports every error aus AUTH_ERROR

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#3799]
**What you were expecting:**

only real auth errors are handled as AUTH_ERROR. the other errors should be reported as a suitable error

**What happened instead:**

every error is reported as AUTH_ERROR. If your authprovider logs you out on AUTH_ERROR, it gets really annoying.

**Steps to reproduce:**

- use a data provider that uses ra-data-graphql
- have your graphql backend throw an error on some query or mutation
- log the `type` argument in your authprovier, you will see its an `AUTH_ERROR`

**Related code:**
- sorry, i have none at this point

**Other information:**

there is a related PR: https://github.com/marmelab/react-admin/pull/3604

i tried that out, but it does not solve the issue (or maybe there was something other wrong)

**Environment**

* React-admin version: 2.9.6
* Last version that did not exhibit the issue (if applicable): none
* React version: 16.10.0
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by melvynhills** [comment]
You should parse the error object passed as the 2nd parameter to the auth provider function and check the status code. Then you should only log out your users on 401 and 403.

**Comment by djhi** [comment]
Closing as @melvynhills actually answered it. Thanks!

**Comment by macrozone** [comment]
thank you guys for the information, this should solve the problem for the moment.

In my opinion, it should be the dataprovider's responsibility to parse the error and decided whether to pass it to the auth-provider, so that an AUTH_ERROR would really be an  authentification error
