### ISSUE TITLE
[3.0.0-beta.0] Filter Component: Error when overriding CSS classes `button` and `form` 

### ISSUE THREAD

**Issue by MiMo42** [marmelab/react-admin#3800]
**What you were expecting:**
It should be possible to override form and button CSS styles of Filter component without errors.
See documentation: https://github.com/marmelab/react-admin/blob/next/docs/Theming.md

**What happened instead:**
Runtime errors: 
```
Material-UI: the key `form` provided to the classes prop is not implemented in undefined.
You can only override one of the following: root. 
    in FilterButton (at Filter.js:36)
    in Filter (at Filter.tsx:81)
```
and
```
Material-UI: the key `button` provided to the classes prop is not implemented in undefined.
You can only override one of the following: root. 
    in FilterButton (at Filter.js:36)
    in Filter (at Filter.tsx:81)
```

**Steps to reproduce:**
Override CSS styles like documented.

**Related code:**
https://stuzk.csb.app/posts
See material-ui errors in console

**Environment**

* React-admin version: 3.0.0-beta.0
* React version: 16.9
* Browser: Chrome

**Comment by fzaninotto** [comment]
Fixed by #3817
