### ISSUE TITLE
Allow ReferenceInput to accept more than one child

### ISSUE THREAD

**Issue by sebitoelcheater** [marmelab/react-admin#3801]
**Is your feature request related to a problem? Please describe.**
ReferenceInput only accepts a single child.

**Describe the solution you'd like**
ReferenceInput should accept multiple children. For example, when selecting a product from a list of products, the user should be able to filter by more than one field, say product_name and maker.

**Describe alternatives you've considered**
Allow ReferenceInput to accept more than one Input. (for example, AutocompleteInput for name and another AutocompleteInput for maker).

**Additional context**

**Comment by Kmaschta** [comment]
It seems like a good idea, but it will be difficult to implement I guess.
The core team doesn't have that need, so, this suggestion may be closed.

Any PR is welcome!

**Comment by djhi** [comment]
One way to handle this is to create a custom Input wrapping the multiple inputs you need.
