### ISSUE TITLE
"sort" property is ignored in ReferenceInput

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#3803]
**Code:**

```
const PostFilter = (props) => (
  <Filter {...props}>
      <TextInput label="Search" source="title" alwaysOn />
      <ReferenceInput
        source="userId"
        reference="users"
        sort={{ field: 'name', order: 'ASC' }}
        alwaysOn
        >
          <SelectInput optionText="name"  />
      </ReferenceInput>
  </Filter>
);
```

This code was taken from the Tutorial (I've added sort and alwaysOn)

Expected that select input option is sorted by name; however default sort is used:
sort: {field:"id", order:"DESC"}

**Environment**

* React-admin version: 3.0.0-beta.0
* Last version that did not exhibit the issue (if applicable): not tested in previous buiilds
* React version: 16.9
* Browser: Chrome

**Comment by Kmaschta** [comment]
So, it is a documentation issue or a bug?

**Comment by djhi** [comment]
Duplicate of #3642
