### ISSUE TITLE
Enhance <AutocompleteArrayInput />

### ISSUE THREAD

**Issue by samz-github** [marmelab/react-admin#3807]
**Situation**
 After I have selected an item from dropdown list from a choice array(like \<ReferenceArrayInput /\>), this selected item still in dropdown list.  It can easily makes duplicated selection in next select, and cause abnormal issue(like when click blank, no drop down list appear ). 

**Describe the solution you'd like**
Once an item have been selected from dropdown list, it should be removed from dropdown list.

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
This is fixed in 3.0

**Comment by samz-github** [comment]
@fzaninotto Awesome!
