### ISSUE TITLE
defaultI18nProvider not exported

### ISSUE THREAD

**Issue by thclark** [marmelab/react-admin#3819]
**What you were expecting:**
I'm following the instructions in [CustomApp.md](https://github.com/marmelab/react-admin/blob/next/docs/CustomApp.md) for creating a store. I was expecting everything to go smoothly, but...

**What happened instead:**
I got `Attempted import error: 'defaultI18nProvider' is not exported from 'react-admin'.`

**Steps to reproduce:**
With Release 3.0.0-beta-0 installed...
```
import { defaultI18nProvider } from "react-admin";
```

**Other information:**
I think that import is no longer necessary and should have been removed as part of [this commit](748b4dedb0345d773683da39b26fd23b6a5d2012)

**Environment**

* React-admin version: 3.0.0-beta-0

**Comment by djhi** [comment]
Thanks!

**Comment by thclark** [comment]
Actually, there's a paragraph in the preamble of htat page that should probably be adjusted to match too:
"React-admin requires that the redux state contains at least 3 reducers: admin, i18n and router. "

(sorry, I'd link to the line, but github renders markdown instead of allowing us to crossreference it like code).

**Comment by djhi** [comment]
Good catch :) Thanks again!

**Comment by fzaninotto** [comment]
Fixed by #3820
