### ISSUE TITLE
Datagrid: Passing a function to rowClick prop may throw an error.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3822]
[https://codesandbox.io/s/tutorial-nn423](https://codesandbox.io/s/tutorial-nn423)

In the above sample, click on any row (body) of the PostList to expand it.
You see in the console the following error logged:

`VM8520:37 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `stopPropagation` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.`

This is reproducible with versions 2.9.7 and 3.0.0.beta0 of react-admin

**Comment by fzaninotto** [comment]
Thanks, bug reproduced and confirmed.

**Comment by WiXSL** [comment]
Thanks!
