### ISSUE TITLE
how to use with Gatsby or within any other app?

### ISSUE THREAD

**Issue by BernardA** [marmelab/react-admin#3824]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(http://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.
I understand you pointing to  StackOverflow, but this seems too much of a general question, so I am trying here.

I may have a mind set that does not fit with your set up. Normally I would expect `admin` to be an additional route -  and sub-routes -  within an app and by consequence a domain, like `www.mywebsite.com/admin`.

As such I was expecting to be able to use `react-admin` within a Gatsby web app I am building but that should apply for any web app, of course. 

In Gatsby it would be on additional route which would be set up as a page:
`/src/pages/admin.js` and any component thereof under `/src/components/`.

But, based upon what I read in your docs,  it would seem that a separate domain is required for `react-admin`.

What am I missing?

**Comment by fzaninotto** [comment]
Maybe a good read of the documentation?

https://marmelab.com/react-admin/CustomApp.html
