### ISSUE TITLE
Unable to render Routes in CustomApp example

### ISSUE THREAD

**Issue by thclark** [marmelab/react-admin#3837]
**What you were expecting:**
I was expecting a UsersList component to show, when accesssing the `/#/users/` endpoint in the Custom App tutorial.

**What happened instead:**
I get an error:
```
Error: <List> component is not properly configured, some essential props are missing.
Be sure to pass the props from the parent. Example:

const MyList = props => (
    <List {...props}></List>
);

The missing props are: basePath
```

The stack trace also whinges about missing required props `hasCreate`, `hasEdit`, `hasShow`, `hasList`

**Steps to reproduce:**
I've created a standalone working example, which follows `docs/CustomApp.md` as closely as possible whilst updating to v3.

Incidentally, this example (once this issue gets fixed) could be used to update [CustomApp.md](https://github.com/marmelab/react-admin/blob/master/docs/CustomApp.md) for v3.

`index.js` file and `createAdminStore.js` files are in [this sandbox](https://codesandbox.io/s/simple-vtk9k)

Navigate in the sandbox to `/#/users` endpoint and you'll see the error. Note: Codesandbox halts at the first error, so you only see the missing props.

**Environment**

* React-admin version: 3.0.0.beta-0
* Last version that did not exhibit the issue (if applicable): 
* React version: 16.10
* Browser:
* Stack trace (in case of a JS error):

** Proposed solution **
The following List component fixes the issue:
```
const UsersList = props => {
  console.log('LIST PROPS', props)
  return (
    <List
      {...props}
      basePath={props.path}
      hasCreate={false}
      hasList
      hasEdit={false}
      hasShow={false}
    >
      <Datagrid rowClick="edit">
        <TextField source="id" />
        <EmailField source="email" />
      </Datagrid>
    </List>
  )
}
```
Why 'basePath' is required in List, I don't know... it doesn't seem to be used at all from my quick search. I also suggest that the `has*` props be given sensible defaults.

**Comment by fzaninotto** [comment]
Confirmed. The CustomApp documentation should mention that the component requires a basePath.

**Comment by thclark** [comment]
Should the basePath be anything other than `{props.path}`?

**Comment by fzaninotto** [comment]
```diff
- <Route exact path="/posts" hasCreate render={(routeProps) => <PostList resource="posts" {...routeProps} />} /
+ <Route exact path="/posts" hasCreate render={(routeProps) => <PostList resource="posts" basePath={routeProps.match.url} {...routeProps} />} /
```

**Comment by dgkm** [comment]
@thclark Is this sandbox link is working correctly [https://codesandbox.io/s/simple-vtk9k](url)?
