### ISSUE TITLE
The react-admin 3.0.0-beta demo doesn't work

### ISSUE THREAD

**Issue by zhouhao27** [marmelab/react-admin#3842]
**What you were expecting:**

**What happened instead:**

The demo doesn't work. It shows:

> Module not found: Can't resolve 'ra-core' in '/Users/user/Documents/react-admin/examples/demo/src/dataProvider'

**Steps to reproduce:**

1. Clone the repository
2. Switch to next branch
3. `yarn` in examples/demo
4. `yarn start`

**Related code:**

* Preferably, a CodeSandbox you can fork this one: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.0.0-beta.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Have you build all the packages first ?

**Comment by zhouhao27** [comment]
After I upgrade to 3.0.0-beta.2, I got an error again:

> ./node_modules/ra-core/esm/util/renderWithRedux.js
Module not found: Can't resolve '@testing-library/react' in '/Users/abc/Documents/React/demo/node_modules/ra-core/esm/util'

The steps:

1. Copy demo folder out to ~/Desktop
2. `cd demo`
3. `yarn `
4. `yarn start`

**Comment by fzaninotto** [comment]
@zhouhao27 it was fixed in #3851
