### ISSUE TITLE
Link to dataProvider for django (updated for v3) in the ecosystem

### ISSUE THREAD

**Issue by thclark** [marmelab/react-admin#3843]
**Is your feature request related to a problem? Please describe.**
This is less of a "feature request" and more of a "feature donation"! An updated dataProvider for django.

**Describe the solution you'd like**
RA v3 uses different kind of dataProvider to v2. I use django DRF, so refactored the provider linked in your 'Ecosystem' docs to the v3 format and have made it available [in this gist](https://gist.github.com/thclark/722ea2bae42db05c38a5c583ba976c52)

You're welcome to link to it directly from your EcoSystem page. I've also raised an issue [here](https://github.com/synaptic-cl/ra-data-drf/issues/5) so if the original package provider wants to bring it into their repo directly they can... in which event, no need to link to me too.

**Comment by djhi** [comment]
Would you mind openning a pull request to update the ecosystem page ?

**Comment by thclark** [comment]
Sorry Gildas, I've had to move away from RA. I've spent a lot of time (entire week) trying to make it work but haven't got anywhere, so I can't afford to justify more effort in.

So I've just flung that up on a gist to help others move through more quickly.

**Comment by fzaninotto** [comment]
Thanks. I hope the people interested in a Django dataProvider for v3 will find this issue.
