### ISSUE TITLE
Inconsistency when sending Get vs Put requests from react-admin

### ISSUE THREAD

**Issue by oi-eddyoj** [marmelab/react-admin#3845]
Here is a sample get request that react-admin is sending:
http://localhost:8000/projects/ad1fed08-c52d-11e9-aa8c-2a2ae2dbcce4/ 

Here is a sample put request:
http://localhost:8000/projects/ad1fed08-c52d-11e9-aa8c-2a2ae2dbcce4

Note the trailing slash, which is a horrible inconsistency to have to deal with. The url is redirected in Django and therefore the PUT request is lost and the update fails.

Resolution: Consistently append a slash from the client for all urls.

**Comment by fzaninotto** [comment]
I understand you’re using a Django Data Provider. It is not edited in this organization. I invite you to open the issue in the repository of your data provider.

**Comment by oi-eddyoj** [comment]
Yes, blame Django for the inconsistencies of react-admin. Makes sense. We're talking about reinventing Django instead of adding a '/' to a PUT request in react-admin. Surely this is a simple resolution?

**Comment by djhi** [comment]
Please read carefully. @fzaninotto said the Django **Data Provider** which we don't provide.
