### ISSUE TITLE
Include @material-ui/pickers in built-in dependencies

### ISSUE THREAD

**Issue by nitoygo** [marmelab/react-admin#3847]
I'd like to use material-ui pickers without using the DateInputs for more flexibility.

Is it possible that react-admin itself would include @material-ui/pickers in built-in dependencies?

Having to install it manually may seem redundant as react-admin already includes material-ui core/icons

Thoughts?
Thank you.

**Comment by djhi** [comment]
Thanks for the suggestion. However, we don't use those pickers for our `DateInput` component so we won't include this package.

**Comment by nitoygo** [comment]
Thanks for the reply.
By the way, will react-admin use material ui v4 soon?

**Comment by djhi** [comment]
Yes the V3 is using it. You can try it already. See the releases page
