### ISSUE TITLE
<SimpleForm >should add custom styles by pass  props 'className' to it like the  <SimpleShowLayout>

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#3856]
**Is your feature request related to a problem? Please describe.**
SimpleShowLayout can pass props 'className ', if i want to custom the  style of  the field display .for example ,i want to display flex.
```
const styles = {
  showForm: {
    display: 'flex',
    alignContent: 'flex-start',
    flexWrap: 'wrap',
  },
};
  <SimpleShowLayout className={classes.showForm}>
```
yes,  SimpleShowLayout have this feature for  show page.unfortunately the SimpleForm did not have this feature when i use in the edit page.
**Describe the solution you'd like**
we can see  SimpleShowLayout  
```
export var SimpleShowLayout = function (_a) {
    var basePath = _a.basePath, className = _a.className, children = _a.children, record = _a.record, resource = _a.resource, version = _a.version, rest = __rest(_a, ["basePath", "className", "children", "record", "resource", "version"]);
    return (React.createElement(CardContentInner, __assign({ className: className, key: version }, sanitizeRestProps(rest)), Children.map(children, function (field) {
        return field && isValidElement(field) ? (React.createElement("div", { key: field.props.source, className: classnames("ra-field ra-field-" + field.props.source, field.props.className) }, field.props.addLabel ? (React.createElement(Labeled, { record: record, resource: resource, basePath: basePath, label: field.props.label, source: field.props.source, disabled: false }, field)) : typeof field.type === 'string' ? (field) : (cloneElement(field, {
            record: record,
            resource: resource,
            basePath: basePath,
        })))) : null;
    })));
};
SimpleShowLayout.propTypes = {
    basePath: PropTypes.string,
    className: PropTypes.string,
    children: PropTypes.node,
    record: PropTypes.object,
    resource: PropTypes.string,
    version: PropTypes.number,
};
export default SimpleShowLayout;
```
‘className’ can pass to custom styles.
But, in SimpleForm
```
      <form
            className={classnames('simple-form', className)}
            {...sanitizeRestProps(rest)}
        >
            <CardContentInner key={version}>
                {Children.map(children, input => (
                    <FormInput
                        basePath={basePath}
                        input={input}
                        record={record}
                        resource={resource}
                        variant={variant}
                        margin={margin}
                    />
                ))}
            </CardContentInner>
            {toolbar &&
                React.cloneElement(toolbar, {
                    basePath,
                    handleSubmitWithRedirect,
                    handleSubmit,
                    invalid,
                    pristine,
                    record,
                    redirect: defaultRedirect,
                    resource,
                    saving,
                    submitOnEnter,
                    undoable,
                })}
        </form>
``` 
 the className is pass to the 'form'  not pass to  'CardContentInner',but  ,we always want custom styles for CardContentInner, because the field is contains by 'CardContentInner' not  'form'
**Describe alternatives you've considered**
In react-admin2.0 the SimpleForm do not have this feature.
now the 3.0 i hope can add this feature just add more one props can finish it.

**Comment by fzaninotto** [comment]
We won't implement what you ask in 3.0 - it would be a breaking change, and it's too late for that. 

It's a convention in react-admin to pass the extra props to the root element. The fact that the root element isn't the same in `SimpleShowLayout` and `SimpleForm` explains the different in behavior.

What we could do, however, is to allow to switch the `CardContentInner` with a custom component - just like the `List` component allows replacing the `Card` component by setting the `component` prop  in v3. 

https://github.com/marmelab/react-admin/blob/d9c5e1b0e58009f5bf3e8d1f7f2898b3adac52bb/examples/simple/src/comments/CommentList.js#L207-L222

I'll mark this issue as an enhancement. If someone from the community wants to work on a PR for it, we'll merge it, but the core team won't work on it unless we need it. If it receives no attention from the community for a few months, we'll close it.

**Comment by Luwangel** [comment]
Hi,

This enhancement didn't receive attention from the community.

So I'm closing it to allow us to focus on the other tasks. That doesn't mean you can't implement it if you want.

Have a good day,
Adrien
