### ISSUE TITLE
Bulk selected message not disappear after click single Delete Button.

### ISSUE THREAD

**Issue by atares0223** [marmelab/react-admin#3862]
**What you were expecting:**
Bulk selected message would disappear after click single Delete Button.
![image](https://user-images.githubusercontent.com/16397455/67351851-0aa9d780-f581-11e9-9d0d-684b90edcd7f.png)

1.In a List page, select one record.
2.click single Delete Button related to the selected one.
3. the seleted items message should disapear since no one is selected now.
**What happened instead:**
1.In a List page, select one record.
2.click single Delete Button related to the selected one.
3. the seleted items message still showing '1 item selected'

**Steps to reproduce:**

1.In a List page, select one record.
2.click single Delete Button related to the selected one.
**Related code:**

codesandbox  (Post List page):
https://codesandbox.io/s/react-admin-advanced-recipes-create-a-record-related-to-the-current-one-kxc7j?fontsize=14
* Preferably, a CodeSandbox you can fork this one: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
const PostList = withStyles(styles)(({ classes, ...props }) => (
  <List {...props} sort={{ field: 'published_at', order: 'DESC' }}>
    <Datagrid>
      <TextField source="id" />
      <TextField source="title" cellClassName={classes.title} />
      <EditButton />
      <DeleteButton />
    </Datagrid>
  </List>
));

```

**Other information:**

**Environment**

* React-admin version:2.9.7
* Last version that did not exhibit the issue (if applicable):
* React version:16.3.2
* Browser:chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I can't reproduce the bug in the codesandbox you provided. Can you try again and write a more detailed scenario if you manage to reproduce the bug?

**Comment by atares0223** [comment]
@fzaninotto  , sorry , I forgot to add  undoable={false} to <DeleteButton/>
it should be ` <DeleteButton undoable={false}/>`
please help to check it again with https://codesandbox.io/s/react-admin-advanced-recipes-create-a-record-related-to-the-current-one-kxc7j?fontsize=14

**Comment by Kmaschta** [comment]
Confirmed! Thanks for the report.

**Comment by fzaninotto** [comment]
And the problem also exists in 3.0

**Comment by atares0223** [comment]
cool, thanks guys.
