### ISSUE TITLE
React-admin 3.0.0-beta3 demo Theme config not working correctly.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3863]
Got to:
[https://codesandbox.io/s/react-admin-demo-300-o7wfl](https://codesandbox.io/s/react-admin-demo-300-o7wfl)

![chrome-capture](https://user-images.githubusercontent.com/8268610/67358201-05736b00-f536-11e9-8aa2-2cefaf5f580e.gif)

**Comment by fzaninotto** [comment]
Reproduced and confirmed. Thanks for the report.

**Comment by fzaninotto** [comment]
Fixed by #3867
