### ISSUE TITLE
React-admin 3.0.0: Can't set resettable prop in SearchInput Component

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3869]
Setting `resettable` prop to a `SearchInput` component doesn't have any effect.
The component always show the search icon on the end.

I set it to every `Filter` of this demo:
[https://codesandbox.io/s/react-admin-demo-300-0sygp](https://codesandbox.io/s/react-admin-demo-300-0sygp)

**Comment by djhi** [comment]
Thanks for reporting!

**Comment by fzaninotto** [comment]
Fixed by #4107
