### ISSUE TITLE
Cannot read property 'stopPropagation' of undefined when confirming record deletion

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#3873]
I am using react admin 3.0.0-beta.3 with dataProvider =  jsonServerProvider('http://jsonplaceholder.typicode.com'); 3.0.0-beta.3

I have a sample edit form for posts per react-admin tutorial (https://github.com/marmelab/react-admin/blob/next/docs/Tutorial.md) and added "undoable={false}" to edit form. This setting triggers confirmation prompt. When I click "confirm", I get an error "Cannot read property 'stopPropagation' of undefined". I also notice that the browser is javascript files. 

Attached screenprint shows files reloaded after I clicked confirm and the error message.
![image](https://user-images.githubusercontent.com/48455289/67511141-e4a53580-f65b-11e9-97b8-442f97aa4d33.png)

Source Code is attached.

[react-admin-app-3x.zip](https://github.com/marmelab/react-admin/files/3768781/react-admin-app-3x.zip)

**Comment by vnnw** [comment]
Same here.

**Comment by djhi** [comment]
Thanks for the report!

**Comment by fzaninotto** [comment]
fixed by #3889
