### ISSUE TITLE
Search field loses its value when a column is sorted

### ISSUE THREAD

**Issue by m4theushw** [marmelab/react-admin#3876]
**What you were expecting:**
The value of the search field should be kept when sorting.

**What happened instead:**
The search field loses its value when a column is sorted.

**Steps to reproduce:**
Open this [sandbox](https://codesandbox.io/s/nifty-austin-mfscr)
Type something into the search field
Click the "Title" column to sort

![search](https://user-images.githubusercontent.com/42154031/67540746-e9e69c80-f6bc-11e9-9fd2-704b2018669d.gif)

**Environment**

* React-admin version: 3.0.0-beta.3
* Last version that did not exhibit the issue: https://marmelab.com/react-admin-demo
* React version: 16.8.6
* Browser: Google Chrome 77.0.3865.120

**Comment by djhi** [comment]
Thanks for the report!

**Comment by fzaninotto** [comment]
Fixed by #3887
