### ISSUE TITLE
Stylesheet class names conflict with production build (issue with JSS minification)

### ISSUE THREAD

**Issue by straurob** [marmelab/react-admin#3879]
This issue is a follow-up to #1782.

I'm experiencing a very similar behavior when using the `ra-tree-ui-materialui` package.

Running the app locally in development mode is fine. As soon as I deploy it to a Docker container the app gets minified. This causes the following behavior:

- Upon the first call there seems to be only one "layer". The user cannot control anything in the tree component or in the sidebar.
- Manually accessing the URL https://hostname/# triggers a refresh and afterwards, the tree works fine.

**Package versions**
Please note that I must stick to `react-admin@2.9.6` using the "old" `ra-tree-core` component for compatibility reasons. That's why I added some packages with a fixed version.

```
"@material-ui/core": "1.5.1"
"@material-ui/icons": "1.1.1"
"ra-tree-ui-materialui": "2.9.3"
"react-admin": "2.9.6"
"react-dnd": "^5.0.0"
"react-redux": "5.0.7"

```

**Code Sandbox**
https://codesandbox.io/s/determined-germain-39sck

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18437455/67560502-50020c80-f71b-11e9-9239-03c7508ad756.png)

![grafik](https://user-images.githubusercontent.com/18437455/67560515-555f5700-f71b-11e9-9be9-89f6297f0607.png)

**Comment by fzaninotto** [comment]
whenever you're using different versions of react-admin and on of the other packages, you're effectively duplicating it. Try using the same version.

```diff
"ra-tree-ui-materialui": "2.9.3"
-"react-admin": "2.9.6"
+"react-admin": "2.9.3"
```

Or using a more flexible version number to let npm deduplicate the package.
