### ISSUE TITLE
Hiding field deletes form values

### ISSUE THREAD

**Issue by tdeo** [marmelab/react-admin#3882]
**What you were expecting:**
When upgrading to version 3 beta, I expected the forms to keep values even when fields are mounted / unmounted.

**What happened instead:**
If a form field is unmounted, the value of the field is removed from the form state. This is especially a problem in dynamic field and when displaying part of a form inside a modal. 

**Steps to reproduce:**
Set up a field displayed based on another value as the doc mention (https://github.com/marmelab/react-admin/blob/next/docs/Inputs.md#linking-two-inputs), then when the condition changes and the field gets unmounted / remounted, it doesn't have a value anymore.

**Related code:**
https://codesandbox.io/s/vibrant-tereshkova-q6i27
Pick a user, enable the email toggle, the original email is present.
After disabling / enabling the toggle again, the email address is gone from the field:

**Other information:**
It looks like this is due to some internals of react-final-form, I didn't have time to investigate though.

It would be nice to figure a workaround, I'll update the issue if I can figure something out.

![Oct-25-2019 15-55-45](https://user-images.githubusercontent.com/6230277/67577012-f2cc8200-f73f-11e9-9edc-242e1990d0ae.gif)

**Environment**

* React-admin version: 3.0.0-beta.3
* Last version that did not exhibit the issue (if applicable): 2
* React version: 16.8.6
* Browser: Chrome
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
Reproduced and confirmed, thanks for the CodeSandbox. I suspect this is a react-final-form bug, would you mind opening an issue in their bug tracker?

**Comment by tdeo** [comment]
It doesn't seem to be reproducible with final-form only: https://codesandbox.io/s/kind-jang-0gyjg

**Comment by fzaninotto** [comment]
Thanks. Your last example is simpler than what we do in react-admin (you should use the same subscriptions and use a FormSpy), but I appreciate the effort. I'll dig further to try and understand what react-admin does wrong here.

**Comment by tdeo** [comment]
@fzaninotto I actually was trying out with the simple example and realized it's the `destroyOnUnregister` prop of `<Form>` in SimpleForm.js that causes the issue

**Comment by fzaninotto** [comment]
Exactly, so I think #3884 should fix the problem. I'm going to test that patch more thoroughly.

**Comment by fzaninotto** [comment]
Fixed by #3884

**Comment by tdeo** [comment]
👍 Thanks
