### ISSUE TITLE
Sort by a filed will cause Filter losing its value in version 3.0.0-beta.3

### ISSUE THREAD

**Issue by vnnw** [marmelab/react-admin#3899]
**What you were expecting:**
When in a ListView, I add a filter which using ReferenceInput and SelectInput, then click a field to sort the result set, the selected filter value should be kept. 

**What happened instead:**
When I add a filter, then click a field to sort to refresh result set, the selected filter will disappear. 

E.g. 
the filtering request url is 

http://localhost:8000/api/tables/?database=1&ordering=-last_modified_at&page=1&page_size=10

when I clicked any field, the url get changed into
 
http://localhost:8000/api/tables/?ordering=-name&page=1&page_size=10

the "database=1" part is lost, Filter form becomes blanked too.

**Comment by fzaninotto** [comment]
Already fixed by #3887
