### ISSUE TITLE
ra-tree-ui-materialui with v3.0.0-beta.X?

### ISSUE THREAD

**Issue by js-chris** [marmelab/react-admin#3902]
Hi,

is it or will it be possible to use ra-tree-ui-materialui with v3.0.0-beta.X? Is it already testable or should I wait? Do have plans to include it? 

Thanks in advance
Chris

**Comment by djhi** [comment]
It won't work on the v3 because they use different versions of material-ui.

We do plan to migrate it on the v3. As it is an addon, it can be done after v3 is out though
