### ISSUE TITLE
ImageInput doesn't work for create

### ISSUE THREAD

**Issue by zhouhao27** [marmelab/react-admin#3906]
**What you were expecting:**

**What happened instead:**

Got error message when using `ImputInput` for `create`. The error message is:

> Sign_in_error

But it works for `edit`.

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox you can fork this one: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

Here is the code doesn't work:

```
export const ArticleCreate = props => (
  <Create {...props}>
    <SimpleForm>
      <TextInput source="title" />      
        <ImageInput source="image" label="Related Image" accept="image/*" >
        <ImageField source="src" title="title" />
      </ImageInput> 
    </SimpleForm>
  </Create>
);
```

Here is the code works:

```
export const ArticleEdit = props => (
  <Edit {...props}>
    <SimpleForm>
      <DisabledInput source="id" />
      <TextInput source="title" />      
       <ImageInput source="image" label="Related Image" accept="image/*" >
        <ImageField source="src" title="title" />
      </ImageInput> 
    </SimpleForm>
  </Edit>
);

```

**Other information:**

**Environment**

* React-admin version: 2.9.8
* Last version that did not exhibit the issue (if applicable):
* React version: 16.9.0
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by zhouhao27** [comment]
Here is my [example code](https://codesandbox.io/s/immutable-cherry-6mtp2). The user name is `demo@mail.com`, password is `password`.

**Comment by zhouhao27** [comment]
I think the reason is in the dataProvider.
