### ISSUE TITLE
3.0.0-beta.4: Typescript compiler missing symbols error when updating from beta.3 to beta.4

### ISSUE THREAD

**Issue by MiMo42** [marmelab/react-admin#3913]
**What you were expecting:**
Being able to compile without compiler complain about missing symbols

**What happened instead:**
Massive compiler errors, because no ra-ui-materialui symbols are found.

**Steps to reproduce:**
A *.tsx file that imports symbols of ra-ui-materialui from react-admin

**Related code:**
```
import {
  List
} from "react-admin"
```
-> Compiler does not find symbol 'List'

**Other information:**
Directly importing from ra-ui-materialui works.
Symbols from ra-core *are* found.
Symbols of ra-ui-materialui *are* found if imported in *.js files.

* React-admin version:
3.0.0-beta.4
* Last version that did not exhibit the issue (if applicable):
3.0.0-beta.3
* React version:
16.11.0
* Browser:
Chrome

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report. I'll republish a new beta shortly to fix the issue.

**Comment by fzaninotto** [comment]
Done: https://github.com/marmelab/react-admin/releases/tag/v3.0.0-beta.5

Sorry for the trouble. We need to improve our testing bench for types.

**Comment by MiMo42** [comment]
Oh, that was fast :-)
Fixed.
Thank you!
