### ISSUE TITLE
Wrong Error Messages From dataProvider ra-data-simple-rest

### ISSUE THREAD

**Issue by francoisruty** [marmelab/react-admin#3919]
The simple rest data provider.

I tried to connect it with an ExpressJS REST API.

Issue 1: The data provider complained that the API did not returned an answer with Content-Range header for LIST call, even though the response header was there.
The issue was that the api returned {data: [....]} instead of just [...]. So now I don't have a problem anymore. 
So basically, if the API returns, for a LIST call, the wrong format (= not a json array but something else), the data provider complains about the Content-Range header, which is totally unrelated.

Issue2: For a get call, I returned {data: {id: ...}}, and the dataProvider complained with this:
The response to 'GET_ONE' must be like { data: { id: 123, ... } }, but the received data does not have an 'id' key. The dataProvider is probably wrong for 'GET_ONE'
This is weird because this is exactly what my API returned.
I figured out the issue was probably the same than issue 1, so I modified my API so that it returns directly {id ....} instead of {data: {id: ...}}, and now the problem is gone.
So in that case, the error message is just plain wrong, it tells you the response should have format A while in reality it should have format B.

**Environment**

* React-admin version: 2.9.8
* React version: 16.11.0
* Browser: chrome osX

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by fzaninotto** [comment]
1. I don't see how react-admin can complain about missing content-range header while the problem lies in the response format. The code testing these conditions is clearly separated. So we'll need you to provide a reproducible test case to prove the bug.  
2. You may confuse the format returned by your API and the format returned by the dataProvider. Apart from testing the content-range header, the simple rest provider never throws any warning about your API format. Any warning concerning a mising data key is from react-admin, and should never happen if you use one of the bundled data providers (like simple rest), which are heavily tested. So once again, please provide a failing test case.

**Comment by francoisruty** [comment]
[fruty_react-admin2.zip](https://github.com/marmelab/react-admin/files/3809274/fruty_react-admin2.zip)


Hello, please find attached a zip file with source code and docker-compose.yml to easily reproduce the issue 2. For issue 1, it seems to happen randomly so must be some caching problem on my side, let's forget about it for now
I'm using the simple rest dataprovider out of the box btw

Once you unzipped the folder:
cd fruty_react-admin
docker-compose up -d
docker-compose run front /bin/sh
cd /home/app
npm install
exit
docker-compose run back /bin/sh
cd /home/app
npm install
exit
docker-compose exec postgres /bin/bash
psql --username=fruty
\i /init/init.sql
\q
exit

docker-compose up -d
Now go to:

http://0.0.0.0:3000/#/items
and click on one of the items to edit it, to trigger a GET call

In the console, you will see:
The response to 'GET_ONE' must be like { data: { id: 123, ... } }, but the received data does not have an 'id' key. The dataProvider is probably wrong for 'GET_ONE'

Now go to back/server.js, line 52, and replace:
      res.json({data: results.rows[0]});
by 
      res.json(results.rows[0]);

Now it works.
So the error message tells the format should be:
{ data: { id: 123, ... } }
while the format should be { id: 123, ... }
Now maybe the error message talks about the request and not the payload, but then it would be nice to precise so

**Comment by fzaninotto** [comment]
So I downloaded your app and tested it, and my conclusion is that everything works as expected. 

You're using the `ra-data-simple-rest` data provider, which expects the API for a single resource to return an object (like https://jsonplaceholder.typicode.com/todos/1). This data provider transforms the response from the API to a format that react-admin understands, and that format is an object with a `data` key.

       API
        ⬇️        { id: 1, title: 'foo' } 
    dataProvider
        ⬇️        { data: { id: 1, title: 'foo' } }
     react-admin
    
The error message is about the value received by react-admin from the dataProvider, and it's correct. So I see no bug here, but a misunderstanding on your side. I'm closing this issue.

**Comment by 3agpot** [comment]
Francois, upon checking the documentation, I confirmed that you're correct - it's the misunderstanding on the user's side. However, being a user and facing the exact same problem and getting confused in the exact same way, I can perhaps assume that the documentation can be a bit clear even though I don't have an exact suggestion as to what improvements to make. I usually don't like criticizing without being constructive, but I'm pretty new to react-admin, and perhaps I will come back here in several months and offer an improvement to the documentation. BTW, is it here on github and open for conributions?
Thanks for such a great framework BTW!

**Comment by slax57** [comment]
@3agpot Thank you for your positive feedback :slightly_smiling_face: 
The docs you would want to improve are in two locations:
- For react-admin in general (ends up on the website): https://github.com/marmelab/react-admin/tree/master/docs
- For ra-data-simple-rest (ends up on npm package page): https://github.com/marmelab/react-admin/blob/master/packages/ra-data-simple-rest/README.md

We gladly accept PRs :slightly_smiling_face: . Just make sure to read the [contribution guidelines](https://github.com/marmelab/react-admin#contributing) first.
