### ISSUE TITLE
Add custom option to support move the pagination/actions of <List> component from right to left

### ISSUE THREAD

**Issue by samz-github** [marmelab/react-admin#3931]
**Is your feature request related to a problem? Please describe.**
In my practical case, I have a <List> component with dozens of fields. And the actions and pagination view still in right side. It's not convient as I have to move my scollbar to find the pagination button or actions button, and then click it.

**Describe the solution you'd like**
Add custom option to support move the pagination/actions of <List> component from right to left.

**Comment by djhi** [comment]
This is achievable by providing your own actions and pagination components with custom styles. If you need help to do it, please ask on StackOverflow

**Comment by samz-github** [comment]
@djhi , please don't close  it, I want it can be achieved on  officail component but not my own component.

**Comment by fzaninotto** [comment]
@samz-github It's good that you want it, but it's not enough to have someone implement it for you. You see, this is an open-source project, not a free development workshop. The core team decides what we want to see in the core (usually, not much), and what people can implement in userland (usually, most features). The rationale is that the bigger it gets, the harder react-admin is to learn. We want it to be a compact and easy to use library, not a replacement for React.

**Comment by samz-github** [comment]
@fzaninotto got your point, I think there may/will be also other people encounter such situation which have a List component with dozens of fields.  It will be make list component more adaptive for real need if we have this custom option.  Nevertherless, and this is decided by you and I just give a advice.
