### ISSUE TITLE
<AutocompleteInput>do not support  to be empty

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#3933]
**What you were expecting:**
allow empty of  the AutocompleteInput 

**What happened instead:**
AutocompleteInput after select one value ,even you clear the input ,  always save  the last selected choice .

**Steps to reproduce:**
1. [https://codesandbox.io/s/simple-ucjul](url)
2.enter to create comment page 
3.choose one item of posts,
4.clear your input and  leave 
5.you can see the input will load the value selected last time
**Related code:**
```
    <ReferenceInput {...props} defaultValue={newPostId}>
                <AutocompleteInput optionText="title" allowEmpty />
            </ReferenceInput>
```
In document we can see following :
> `allowEmpty` | Optional | `boolean` | `false` | If `false` and the searchText typed did not match any suggestion, the searchText will revert to the current value when the field is blurred. If `true` and the `searchText` is set to `''` then the field will set the input value to `null`. |
but after selected one  when the field is blurred. the input never became empty.
**Environment**

* React-admin version: next

**Comment by MiMo42** [comment]
Yes. see #3920
The empty item is missing as soon as a suggestion has been selected.

**Comment by Kmaschta** [comment]
Closing as duplicated as #3920
