### ISSUE TITLE
<AutocompleteArrayInput /> interaction not friendly when select multiple  value

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#3939]
**Is your feature request related to a problem? Please describe.**
When use AutocompleteArrayInput to select values.when cursor focus the input ，the suggestion result list will display. When cursor blur the input will disappear. Well, it good ,no any problem.

But if you have selected one value, the cursor will focus the input, Even if click the input the suggestions did not display(because the input have focused) .It will make users mistakenly think this is a bug (click input no suggestion ). Normally user after select one value ,will not  want to input anything to fetch suggestion.they always use mouse to click the input to select from the  suggestion.Users should remove the cursor from input and re-enter the cursor focus to choose next value or what they can do is must input some word  .(well ,it not a friendly interaction to teach user how to do).

**Describe the solution you'd like**
I did not have a good idea to solute it .i just know the user ' habit.
Solution1 : after user selected  one value ,do not  make cursor focus in input .even  let user click to  re-enter blur input ,also won't let the user feel bad.
Solution2 : after user selected  one value ,if user click the input ,render the suggestions  and let the user choose.

**Reproduce**
see [https://codesandbox.io/s/simple-ucjul](https://codesandbox.io/s/simple-ucjul)
1.comment create page 
2.see category  field

**Comment by Kmaschta** [comment]
Agree, we can improve the usage experience of this component.
Any idea on this matter is welcome.

**Comment by MoonSeeing** [comment]
@Kmaschta  thanks

**Comment by fzaninotto** [comment]
Fixed by #3949
