### ISSUE TITLE
[v3] beta.5 - ReferenceArrayInput ignoring custom label

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3942]
ReferenceArrayInput seems to ignore custom labels

repo:
https://codesandbox.io/s/simple-i0xmz

steps to reproduce:
1) edit comment
2) you will see custom label while loading data for ReferenceArrayInput
3) after load it reverts to one generated from source, ignoring custom one

![Nov-06-2019 12-22-32](https://user-images.githubusercontent.com/488136/68294444-7cf5de00-0090-11ea-8ad3-8a9d8b92d90a.gif)

**Comment by Kmaschta** [comment]
Confirmed, thanks for reporting!

**Comment by fzaninotto** [comment]
Fixed by #3944
