### ISSUE TITLE
[v3] beta.5 - ReferenceArrayInput - removing wrong item

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3943]
ReferenceArrayInput removes wrong item if clicked on remove icon

repo:
https://codesandbox.io/s/simple-i0xmz

steps to reproduce:
1) edit comment
2) you will see  ReferenceArrayInput
3) add some items
4) try to remove first item
5) it instead removes last item

![Nov-06-2019 13-51-02](https://user-images.githubusercontent.com/488136/68299793-ad437980-009c-11ea-9184-bc25d1c5762d.gif)

**Comment by Kmaschta** [comment]
Confirmed! Thanks for reporting it

**Comment by fzaninotto** [comment]
fixed by #3950
