### ISSUE TITLE
incompatible with parcel / redux-saga issue

### ISSUE THREAD

**Issue by MarkLyck** [marmelab/react-admin#3945]
**What you were expecting:**
node module to work with major bundlers like parcel-bundler

**What happened instead:**
error `Uncaught TypeError: (0 , _reduxSaga2.default) is not a function` happens when using parcel-bundler

**Steps to reproduce:**
set up react-admin app with parcel-bundler that initializes the redux store in react-admin

**Related code:**
seems to happen from  `createAdminStore.js:62`
https://github.com/marmelab/react-admin/blob/5f33113494c25291ddb98c2b931284ed47a1b8d2/packages/ra-core/src/createAdminStore.ts#L70

**Other information:**
The error itself and why it happens is described in better detail in this ticket: https://github.com/redux-saga/redux-saga/issues/1346

**Environment**
"parcel-bundler": "^1.12.4",
"react-admin": "2.8.5",
* Browser: ANY

* Stack trace (in case of a JS error):
```
utils.js:225 uncaught at  at  
 at  
 TypeError: (0 , n.default) is not a function
    at http://localhost:3000/src.c8a83f2b.js:1280:1722
    at http://localhost:3000/src.c8a83f2b.js:1280:1415
    at Object.next (http://localhost:3000/src.c8a83f2b.js:1280:1520)
    at K (http://localhost:3000/src.c8a83f2b.js:1218:4337)
    at E (http://localhost:3000/src.c8a83f2b.js:1218:4062)
    at F (http://localhost:3000/src.c8a83f2b.js:1218:7973)
    at P (http://localhost:3000/src.c8a83f2b.js:1218:6802)
    at http://localhost:3000/src.c8a83f2b.js:1218:8536
    at Array.forEach (<anonymous>)
    at W (http://localhost:3000/src.c8a83f2b.js:1218:8509)
  | j | @ | utils.js:225
-- | -- | -- | --
  | S | @ | proc.js:210
  | M | @ | proc.js:349
  | i | @ | proc.js:79
  | F | @ | proc.js:563
  | P | @ | proc.js:435
  | (anonymous) | @ | proc.js:644
  | W | @ | proc.js:643
  | P | @ | proc.js:435
  | K | @ | proc.js:315
  | E | @ | proc.js:270
  | c | @ | runSaga.js:49
  | s | @ | createAdminStore.js:62 <<<<<<<<< latest point of failure in react-admin
  | c.render | @ | CoreAdmin.js:78
  | so | @ | react-dom.production.min.js:181
  | co | @ | react-dom.production.min.js:180
  | Bo | @ | react-dom.production.min.js:261
  | Qu | @ | react-dom.production.min.js:230
  | Bu | @ | react-dom.production.min.js:229
  | Fu | @ | react-dom.production.min.js:223
  | (anonymous) | @ | react-dom.production.min.js:121
  | exports.unstable_runWithPriority | @ | scheduler.production.min.js:18
  | ia | @ | react-dom.production.min.js:120
  | sa | @ | react-dom.production.min.js:121
  | ca | @ | react-dom.production.min.js:120
  | Nu | @ | react-dom.production.min.js:214
  | enqueueSetState | @ | react-dom.production.min.js:133
  | h.setState | @ | react.production.min.js:13
  | (anonymous) | @ | admin.js:93
```

**Comment by Kmaschta** [comment]
The core team don't use parcel, and we'll have hard time reproducing the issue.
But it would be a nice enhancement, any help on the matter is welcome!

**Comment by fzaninotto** [comment]
I'll close this one as it's a problem with redux-saga or parcel - there is nothing we can do in react-admin to solve it.

**Comment by christopherbauer** [comment]
I had a similar issue except it was just a basic react app - I was forced to disable hoisting in order to get it to work. Not sure if you need more information than that or if it's even helpful, but hopefully some weary traveller stumbles across this thread in their time of need and sees the promised command:

`"build": "parcel build --no-scope-hoist --detailed-report",`
