### ISSUE TITLE
save event not working in SimpleForm & TabbedForm

### ISSUE THREAD

**Issue by gvillo** [marmelab/react-admin#3947]
**What you were expecting:**
I would like to handle save logic (in fact, just handle values -move some props to an obj because API expects data in that way- before posting), so I went to docs (https://marmelab.com/react-admin/CreateEdit.html, selecting v3.0-beta), and I added a handleSave func, to a <TabbedForm save={handleSave}>, but unfortunately it's not firing handleSave method.

**What happened instead:**
It's not reaching save func at all

**Steps to reproduce:**
Just attach save func to a SimpleForm or TabbedForm.

**Related code:**
I've forked your code sandbox in order to reproduce it, tags/TagEdit.js file
https://codesandbox.io/s/react-admin-v3-simple-save-issue-nxssx

**Other information:**
I've developed a workaround, instead of listening to save event, I am creating a new SaveButton and handling click event. That works good.

I may implemented save func in a wrong way, it would be better to clarify that in the doc, there is no example how to use it.   

**Environment**

* React-admin version: v3.0.0-beta.5
* Last version that did not exhibit the issue (if applicable):
* React version: v16.11.0
* Browser: Google Chrome v78.0.3904.87
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment]
Confirmed, thanks!

**Comment by fzaninotto** [comment]
You can't override the `save` prop for a SimpleForm used inside `Edit`, because `Edit` overrides that prop. 

As for how to modify data before submission, this is the job of the underlying form framework (react-final-form), so I advise you to check their docs. Maybe [mutators](https://final-form.org/docs/react-final-form/types/FormProps#mutators) is what you're looking for.

**Comment by gvillo** [comment]
Thank you for your quick reply @fzaninotto, I couldn't find a way to use mutators in a SimpleForm or TabbedForm neither, maybe because on those react-admin forms has the following piece of code `mutators={{ ...arrayMutators }}`.

I will take a look how to modify data before submission in a clever way using react-admin.

Thank you very much!

**Comment by mkhoussid** [comment]
> Thank you for your quick reply @fzaninotto, I couldn't find a way to use mutators in a SimpleForm or TabbedForm neither, maybe because on those react-admin forms has the following piece of code `mutators={{ ...arrayMutators }}`.
> 
> I will take a look how to modify data before submission in a clever way using react-admin.
> 
> Thank you very much!

Have you managed to figure it out? I'm also struggling with mutating form data before submission. I tried injecting the `mutators` prop into `SimpleForm .. />`, which did not work.

**Comment by mkhoussid** [comment]
For anyone else curious,

https://marmelab.com/react-admin/doc/3.1/CreateEdit.html#altering-the-form-values-before-submitting

**Comment by fzaninotto** [comment]
Or better https://marmelab.com/react-admin/CreateEdit.html#using-onsave-to-alter-the-form-submission-behavior
