### ISSUE TITLE
How to fix below warning from console? react-admin ^2.9.8

### ISSUE THREAD

**Issue by JoeLeeWu** [marmelab/react-admin#3952]
- Warning: componentWillMount has been renamed, and is not recommended for use.
Please update the following components: ConnectedRouter, CoreAdminRouter, Notification, Resource, Route, Router, Switch, WithPermissions

- Warning: componentWillReceiveProps has been renamed, and is not recommended for use.
Please update the following components: Connect(CoreAdminRouter), Connect(CustomLayout), Connect(Notification), Connect(Resource), Connect(TranslationProviderView), Connect(WithPermissions), Connect(WithStyles(WithTheme(WithWidth(AppBar)))), Connect(WithStyles(WithTheme(WithWidth(Sidebar)))), Connect(translate(UnconnectedEditController)), Connect(withRouter(WithStyles(Layout))), CoreAdminRouter, LayoutWithTheme, Notification, Provider, Route, Router, Switch, UnconnectedEditController, WithPermissions

- Warning: componentWillUpdate has been renamed, and is not recommended for use.
Please update the following components: Connect(CoreAdminRouter), Connect(CustomLayout), Connect(Notification), Connect(Resource), Connect(TranslationProviderView), Connect(WithPermissions), Connect(WithStyles(WithTheme(WithWidth(AppBar)))), Connect(WithStyles(WithTheme(WithWidth(Sidebar)))), Connect(translate(UnconnectedEditController)), Connect(withRouter(WithStyles(Layout)))

- Warning: componentWillMount has been renamed, and is not recommended for use.
Please update the following components: Sidebar

- Warning: componentWillReceiveProps has been renamed, and is not recommended for use.
Please update the following components: Connect(WithStyles(LoadingIndicator)), Headroom

- Warning: componentWillUpdate has been renamed, and is not recommended for use.
Please update the following components: Connect(WithStyles(LoadingIndicator))

- Warning: componentWillMount has been renamed, and is not recommended for use.
Please update the following components: Form(WithStyles(TabbedForm))

- Warning: componentWillReceiveProps has been renamed, and is not recommended for use.
Please update the following components: Connect(ConnectedField), Connect(DefaultValueView), Connect(Form(WithStyles(TabbedForm))), Connect(FormDataConsumerView), Connect(UnconnectedReferenceInputController), Connect(translate(ReduxForm)), Field, Form(WithStyles(TabbedForm)), ImageInput, UnconnectedReferenceInputController

- Warning: componentWillUpdate has been renamed, and is not recommended for use.
Please update the following components: Connect(ConnectedField), Connect(DefaultValueView), Connect(Form(WithStyles(TabbedForm))), Connect(FormDataConsumerView), Connect(UnconnectedReferenceInputController), Connect(translate(ReduxForm))

- Warning: componentWillReceiveProps has been renamed, and is not recommended for use.
Please update the following components: Connect(WithStyles(SaveButton)), Connect(translate(WithStyles(DeleteWithUndoButton)))

- Warning: componentWillUpdate has been renamed, and is not recommended for use.
Please update the following components: Connect(WithStyles(SaveButton)), Connect(translate(WithStyles(DeleteWithUndoButton)))

- Warning: componentWillReceiveProps has been renamed, and is not recommended for use. 
Please update the following components: Connect(translate(RefreshButton))

- Warning: componentWillUpdate has been renamed, and is not recommended for use. 
Please update the following components: Connect(translate(RefreshButton))

**Comment by fzaninotto** [comment]
Downgrade React, or upgrade react-admin to 3.0.0.
