### ISSUE TITLE
[v3] RadioButtonGroupInput - label is different size than other labels

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3955]
RadioButtonGroupInput's label size is different from other's label's ie. CheckboxGroupInput

![label](https://user-images.githubusercontent.com/488136/68481514-b452bf00-0237-11ea-9f95-53376f471b55.png)

repo: https://codesandbox.io/s/simple-i0xmz

steps:
1) edit post
2) see the difference

**Comment by Kmaschta** [comment]
Nice catch :+1:

**Comment by fzaninotto** [comment]
Fixed by #3974
