### ISSUE TITLE
[v3] Multiple notifications displayed instead of one on dataProvider error.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#3976]
1.- Create a new Post record.

2.- Click "Save"  button multiple times.

3.- Go back to the List.

https://codesandbox.io/s/tutorial-rr0qd

![chrome-capture (5)](https://user-images.githubusercontent.com/8268610/68723829-915a3f00-0598-11ea-8fc6-10772fd46e9e.gif)

**Comment by fzaninotto** [comment]
I don't understand your issue. React-admin shows one notification each time the submission fails. If you submit it 5 times, and the server returns an error 5 times, it's normal that you see 5 notifications.

**Comment by llioor** [comment]
What about js debounce or takeLatest() saga?

**Comment by fzaninotto** [comment]
@llioor I don't understand that comment.

**Comment by WiXSL** [comment]
> I don't understand your issue. React-admin shows one notification each time the submission fails. If you submit it 5 times, and the server returns an error 5 times, it's normal that you see 5 notifications.

Of course,
But i think the form should not be sent again until the first request is completed.
Precisely to avoid multiple errors, since if for an sent id an error is returned, all subsequent requests will return an error.
In addition to being a performance problem, calls are made to the server unnecessarily.
It also shows an annoying and confusing amount of messages to the detriment of the user's experience.

**Comment by fzaninotto** [comment]
The SaveButton already has a double submit prevention system. If th form is saving, a user can't resubmit it until the server has responded. 

So the problem you describe only occurs if:
- the dataProvider returns an error
- the user waits for the initial error message to resubmit, and repeats that cycle again and again

We won't address that use case in the core - it' too minor IMHO. 

What you're asking for is a Circuit Breaker system, and I think it should be done at the data provider level - or you can write your own SaveButton for that.

**Comment by WiXSL** [comment]
Ok.
