### ISSUE TITLE
ra-data-graphql-simple: delete resource not working

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#3978]
**What you were expecting:**
Pending resource deletion

**What happened instead:**
ra-data-graphql-simple Error

**Steps to reproduce:**
Use the ra-data-graphql-simple dataProvider and try to delete the resource

**Related code:**
```
errors: [{,…}]
0: {,…}
locations: [{line: 2, column: 3}]
0: {line: 2, column: 3}
message: "Field "removeGasMeter" of type "GasMeter" must have a selection of subfields. Did you mean "removeGasMeter { ... }"?"
```

generated request:
```
query: "mutation removeGasMeter($id: ID!) {↵  removeGasMeter(id: $id)↵}↵"
variables: {id: "ck2k2kfok008z0768fguqxpfc"}
```

error in request: fields for returned type are not passed.

 [Is there a mistake in the documentation?](https://github.com/marmelab/react-admin/tree/next/packages/ra-data-graphql-simple) 
```
return (
            <Admin dataProvider={dataProvider}>
                <Resource name="Post" list={PostList} edit={PostEdit} create={PostCreate} remove={Delete} />
            </Admin>
        );
```

```
Failed to compile
./src/App.js
Attempted import error: 'Delete' is not exported from 'react-admin'.
```

What is `Delete`? Why did the mutation name deleteResource -> removeResource change? In the documentation below it is specified deleteResource:
```
type Mutation {
  createPost(
    title: String!
    views: Int!
    user_id: ID!
  ): Post
  updatePost(
    id: ID!
    title: String!
    views: Int!
    user_id: ID!
  ): Post
  deletePost(id: ID!): Post
}
```
 Or is this provider still raw? Or there will be no support for this provider?

**Environment**

* React-admin version: : "3.0.0-beta.6",
* ra-data-graphql-simple: "3.0.0-beta.6",
* React version: "16.11.0",
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
The readme of that package is, indeed, outdated. I fixed it in 7339e375213300207709a25eafaef199e0c81218. 

As for the simple graphql data provider, it seems that it's indeed broken (tested with `make run-graphql-demo`).

**Comment by wmwart** [comment]
@fzaninotto , thanks for the quick response! 
What's the name of the delete mutation, `deleteResource($id: ID)`?

**Comment by wmwart** [comment]
@fzaninotto, i apologize. The problem was on my side. I did not trace customBuildQuery. Removal works.

**Comment by fzaninotto** [comment]
OK then, closing the bug.
