### ISSUE TITLE
react-admin 3.0 <AutocompleteArrayInput> suggestion list and Input are not aligned

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#3985]
**What you were expecting:**
In <AutocompleteArrayInput />  suggestion list and Input should be aligned like <AutocompleteInput>.
AutocompleteArrayInput why Leave a blank and not alignment with Input.(right alignment )
but AutocompleteInput do alignment with Input (left alignment).
it is a little weird.
s this design a special purpose？

**Steps to reproduce:**
1. [https://codesandbox.io/s/simple-ucjul](url)
2.enter to create comment page 
3.click the field 'Category',

**Related picture:**
<img width="516" alt="WeChatbd607c85d3d209e77626bde563bc6a18" src="https://user-images.githubusercontent.com/19420622/68845255-1e6ed680-0706-11ea-99d0-81d3af962391.png">

**Environment**

* React-admin version:3.0.0-beta.6

**Comment by fzaninotto** [comment]
Thanks for the report. 

That's a feature: it's aligned with the cursor in the text field. It's especially useful once you have more than one item selected, as the selection list will show closer to the place where the user clicked.

**Comment by MoonSeeing** [comment]
@fzaninotto  got it . it makes sense.
