### ISSUE TITLE
ra-tree-ui-materialui doesn't fetch data

### ISSUE THREAD

**Issue by Sklico** [marmelab/react-admin#3990]
**What you were expecting:**

I try the example which is in README (https://github.com/marmelab/react-admin/tree/master/packages/ra-tree-ui-materialui), so I expect similar behaviour.

**What happened instead:**

Unfortunately, there is no attempt to fetch data for tree like e.g. in classic List component. I don't see any request to my API in Network. I don't know what is wrong, cause there is no other information in README and when I try replace that tree by List component, it works right. I try the exactly same code like in README. I don't know, if it's a bug, or it's right behaviour and I don't find anything about this problem on stackoverflow. If it's not a bug, can you explain me, how to fetch my data for Tree Component.

Thanks for any advice or solution. 

**Environment**

* React-admin version: 2.9.0
* ra-tree-ui-materialui version: 2.9.8
* React version: 16.11.0
* Browser:

**Comment by djhi** [comment]
Sorry about that, this package readme has not been updated properly. Please follow the readme of the `ra-tree-core`: https://github.com/marmelab/react-admin/tree/master/packages/ra-tree-core.

It looks like you're not handling the new dataProvider verbs

**Comment by Sklico** [comment]
Hi, thanks a lot for explanation. You're absolutely right, I didn't even know that there are some new dataProvider verbs. I tried it like it's in ra-tree-core readme and it works now. Thanks again :) We can close it here.
