### ISSUE TITLE
Should Update Documment

### ISSUE THREAD

**Issue by Vn-ChemGio** [marmelab/react-admin#3991]
Hello, In a few day ago, I''m reading Reat-admin Documentation, and I think you should add something to doc
ex:
In docummentation SelectField, I had been find "how to set default value for it", but not found in documentation
But in Github, i found props defaultValue
so Can you add props to documentation for any body ....
Thanks :D

**Comment by fzaninotto** [comment]
The `defaultValue` prop is documented in the Inputs documentation. Check the beginning of the following page: https://marmelab.com/react-admin/Inputs.html.
