### ISSUE TITLE
Advanced Tutorials for React-admin v3.0

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#3997]
Good afternoon, dear development team. Thanks for the great tool!

In my React-admin v2 project, I actively used materials from the advanced tutorial. Now I want to try React-admin v3.0. However, changing the libraries (redux-form -> final-form) makes the transition less obvious to me.

Do you plan to adapt articles from the advanced Tutorials for the new version of React-admin?

Thanks!

**Comment by djhi** [comment]
Hi! Glad they were useful to you :) Yes, we do plan to adapt them. Can't give you any ETA though

**Comment by wmwart** [comment]
Great news!
@djhi, please tell me the link to the CodeSandbox with ra-data-graphql-simple.

**Comment by djhi** [comment]
> please tell me the link to the CodeSandbox with ra-data-graphql-simple.

I have no idea what you are referring to. Besides, please note that this package is just an example implementation of a GQL dialect and there are many of them. It might not be a good fit for your project.

**Comment by fzaninotto** [comment]
Writing more tutorials is something we always have in mind, no need for an issue to track the progress on that task. So I'm closing this issue.
