### ISSUE TITLE
Notification on custom login page appear at wrong place

### ISSUE THREAD

**Issue by sharon-xz** [marmelab/react-admin#4009]
On my login page, when username/pw is wrong, the error notification saying "Invalid username/password" does not show up, but if the next time the login is successful, the previously failed login error messages would show up after the login. 

**What you were expecting:**
When username/pw is wrong, the error notification saying "Invalid username/password" should show up on the login page.

**What happened instead:**
The error notification does not show up and user stays on login page. Then if I enter correct username/password (without refreshing), login is successful and I will be redirected to the content, now the error notification saying "Invalid username/password" from the previous failed attempt would show up.

**Related code:**
I use a custom login page, very similar to the example in the document. 

```
//in MyLoginpage.js
const MyLoginPage = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const login = useLogin();
    const notify = useNotify();
    const username = "";
    const rememberme = "false";
    const sessionid = "";
    const submit = (e) => {
        e.preventDefault();
        login({username, email, password, rememberme, sessionid})
            .catch(() => notify('Invalid email or password', 'warning'));
    };
    const classes = useStyles();

    return (
        <form onSubmit={submit}>
            <input name="email" type="email" value={email} onChange={e => setEmail(e.target.value)} />
            <input name="password" type="password" value={password} onChange={e => setPassword(e.target.value)} />
            <Button type="submit" color="primary">
                Sign In
            </Button>
        </form>
    );
};

//in authProvider.js
export default {
    login: ({username, email, password, rememberme, sessionid}) => {
        const request = new Request('test.test.test', {
            method: 'POST',
            body: JSON.stringify({username, email, password, rememberme, sessionid}),
            headers: new Headers({'Content-Type': 'application/json'}),
        });
        return fetch(request)
            .then(response => {
                if (response.status < 200 || response.status >= 300) {
                    throw new Error(response.statusText);
                }
                return response.json();
            })
            .then(({token}) => {
                localStorage.setItem('token', token);
                push("/list");
                return Promise.resolve();
            });
    },
    logout: () => {
        localStorage.removeItem('token');
        return Promise.resolve();
    },
    checkError: (error) => {
        const status = error.status;
        if (status === 401 || status === 403) {
            localStorage.removeItem('token');
            return Promise.reject();
        }
        return Promise.resolve();
    },
    checkAuth: () => localStorage.getItem('token')
        ? Promise.resolve()
        : Promise.reject(),
    getPermissions: params => Promise.resolve(),

}
```

**Environment**

* React-admin version: 3.0.0-beta.6
* Last version that did not exhibit the issue (if applicable):
* React version: 16.11.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
As it works on the default Login page, it's not a react-admin bug. To troubleshoot your own code, please use StackOverflow rather than our GitHub issue tracker, as explained in the Issue template.

**Comment by gvillo** [comment]
Hey @sharon-xz check my issue #4491 and my PR #4492. it will solve your issue.

**Comment by sharon-xz** [comment]
> Hey @sharon-xz check my issue #4491 and my PR #4492. it will solve your issue.

Yes, missing Notification is the problem. Thanks for fixing, @gvillo !
