### ISSUE TITLE
In <ReferenceInput> with <AutocompleteInput> the required indicator * disappears

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#4011]
**What you were expecting:**
InputLabel with indicator * when validate={requiredValidete}

**What happened instead:**
Required indicator * disappears

**Steps to reproduce:**
1) Add required validation for the `<ReferenceInput>` with `<AutocompleteInput>`
2) Refresh page

**Related code:**
```
const validateType = [required()];

...
 <SimpleForm>
                <ReferenceInput source="controller" reference="Controller" allowEmpty validate={validateType} >
                    <AutocompleteInput optionText="name" />
                </ReferenceInput>     
 </SimpleForm>
...
```
![lQJRAD2lPN](https://user-images.githubusercontent.com/28799755/69222466-99167680-0b8a-11ea-95c9-d5a6fe8b6c53.gif)

for [# 3849](https://github.com/marmelab/react-admin/issues/3849)

* React-admin version: 3.0.0-beta.6

**Comment by wmwart** [comment]
In addition, as you can see, the default width for AutocompleteInput is different from the rest of the inputs

**Comment by fzaninotto** [comment]
Confirmed and reproduced, thanks for the report.

**Comment by wmwart** [comment]
@djhi , to fix the default width create a separate issue?

**Comment by fzaninotto** [comment]
Sorry, I forgot about the width. Yes, please create a new Github issue to track that bug.
