### ISSUE TITLE
Implement Typescript

### ISSUE THREAD

**Issue by llioor** [marmelab/react-admin#4014]
I opened thread here: https://stackoverflow.com/questions/58958243/implement-typescript-with-react-admin for search optimizations.

I did: create-react-app with --typescript flag

Then install react admin version 3.0

and I got this in console:
```
Could not find a declaration file for module 'react-admin'. 
'.../node_modules/react-admin/lib/index.js' implicitly has an 'any' type.
Try `npm install @types/react-admin` if it exists or add a new declaration (.d.ts)
 file containing `declare module 'react-admin';`
```

Any advice please or a guide please?

**Comment by bicstone** [comment]
@llioor 
SEE https://github.com/marmelab/react-admin/issues/3194#issuecomment-495664607

**Comment by fzaninotto** [comment]
TypeScript types is an ongoing effort. No need for a Github issue to track it.

**Comment by llioor** [comment]
Can we get a guide? What is the error I got?

**Comment by fzaninotto** [comment]
This error shows up because you’ve configured typescript to work only with typescript modules, and react-admin only publishes a JS module. If you still want to use react-admin, you’ll need to alter your TS configuration. Refer to the TS doc for a guide on how to do that.

**Comment by mehrad77** [comment]
How can we help to imlementing TypeScript? it's essential for us.

**Comment by fzaninotto** [comment]
Convert JS files from the ra-ui-matreial-ui package into TSX files and open a PR.

**Comment by Vadorequest** [comment]
Discussion regarding TS has moved to https://github.com/marmelab/react-admin/issues/1617#issuecomment-595874113
