### ISSUE TITLE
Optimistic rendering is not refreshing records after update

### ISSUE THREAD

**Issue by m4theushw** [marmelab/react-admin#4016]
**What you were expecting:**
After updating a record the list should be refreshed and all items be displayed.

**What happened instead:**
The list is displaying only the item I updated.

![react-admin](https://user-images.githubusercontent.com/42154031/69282431-14971880-0bc9-11ea-96a9-3281c3ecc760.gif)

**Steps to reproduce:**
Open the codesandbox below and click the button "Open In New Window"
Click in a post to edit
Click the browser's refresh button
Save the post

**Related code:**
[https://codesandbox.io/s/simple-xtv0e](https://codesandbox.io/s/simple-xtv0e)

**Other information:**
I found that the `getList` call to refresh records is being made while `admin.ui.optimistic` is true. This causes the data provider to cancel the request. This bug only occurs when an edit page is accessed directly or the user refreshes the page, not when you click the Edit button from a listing.

```js
// in ra-core/src/dataProvider/useDataProvider.ts

if (isOptimistic) {
    // in optimistic mode, all fetch actions are canceled,
    // so the admin uses the store without synchronization
    return Promise.resolve();
}
```

**Environment**

* React-admin version: 3.0.0
* Last version that did not exhibit the issue (if applicable): 2.9.9
* React version: 16.9.0
* Browser: Google Chrome 78.0.3904.108

**Comment by djhi** [comment]
Reproduced. Thanks for the report
