### ISSUE TITLE
ra-tree-ui read.me 404

### ISSUE THREAD

**Issue by vgb0332** [marmelab/react-admin#4017]
Hi, following  https://github.com/marmelab/react-admin/tree/master/packages/ra-tree-core. leads 404 page for some reason. I am wondering if this is under rebuilding phase?

**Comment by djhi** [comment]
See https://github.com/marmelab/react-admin/pull/3836. We removed it from v3 until we have time to rewrite it. If you still use v2.x, you can find the documentation using the release page and exploring the source

**Comment by fzaninotto** [comment]
I'm reopening this as we have links in the 2.x documentation that point to it. We must update them.

**Comment by vgb0332** [comment]
Im currently using 2.9x react admin and i waa able to find some doc about the tree on lab section from the development blog. But it was written at 2.3x version or so.

**Comment by fzaninotto** [comment]
Fixed by #4018
