### ISSUE TITLE
Pass extra props to dataprovider methods (from InputReference or Grid) 

### ISSUE THREAD

**Issue by Abenezer** [marmelab/react-admin#4032]
i am trying to implement odata dataprovider and properties other than filter and sort (like $expand and $select) are important.  

**Describe the solution you'd like**
just pass all props from components to data provider methods (not just filter, sort, page) 
`<ReferenceInput expand="xxx" label="yyy" source="pId" reference="zzz" validate={[required()]}>`

**Describe alternatives you've considered**
modified the source

**Comment by fzaninotto** [comment]
This has already been required multiple times (e.g. #3767), and we have always said that it's not in the react-admin data model. You don't need embeds with react-admin, and even less now that we have http/2. See the other related issues for details.

**Comment by Abenezer** [comment]
oh, am not saying to let react-admin do it automatically. i just want a way to pass those props to the custom dataProvider i'am writing.  (currently you can only pass sort, filter and page params right?)

**Comment by Abenezer** [comment]
ok, i found people are just passing custom props inside filter props 
<ReferenceInput filter={{customProp:xx}} it works but it seems hacky solution. if this is ok can you add it to docs. thanks
