### ISSUE TITLE
Form resets when using custom TabbedForm toolbar

### ISSUE THREAD

**Issue by whnunlife** [marmelab/react-admin#4033]
**What you were expecting:**
When using a TabbedForm with a custom toolbar, the redux form is resetting the form state when I try to programmatically change the URL to the next tab.

The expectation here is at the bottom of the tabbed form, instead of showing a "Save" button, I'm replacing that element with a "Next" button and the onClick function is using react-router-dom to navigate to the next tab.

**What happened instead:**
When updating the route, even though it's the valid route to show the specific tab, the form and all values that have been entered on any other tabs have been reset.

**Steps to reproduce:**
To re-create this issue, click the link below then navigate to the `Create Post`. Fill out a field on the first selected tab, then using the button near the bottom `Next`, notice that after clicking on it, the redux form for the form values is lost and if you click on the first tab in the header, the values you entered are lost.

**Related code:**
[Codesandbox Example](https://codesandbox.io/s/react-admin-history-push-mil18)

```
return (
    <Toolbar {...props}>
      <Button
        variant="contained"
        color="primary"
        onClick={() => {
          props.history.push(nextUrl);
        }}
      >
        Next
      </Button>
    </Toolbar>
  );
```

**Other information:**
When looking at the redux toolbar, clicking on any of the navigation tabs, I see it's calling `@@router/LOCATION_CHANGE` with a payload for the next tab. I assumed I could just call history.push and update the tab in the URL since it always works if I refresh the page.

**Environment**

* React-admin version: 2.9.8
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.8.6
* Browser: Chrome 78.0.3904.97
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
Please follow the issue template and give us a way to easily reproduce the bug.

**Comment by whnunlife** [comment]
Thanks @fzaninotto, I updated the initial post with the provided template and added a working example.

**Comment by fzaninotto** [comment]
Thanks for the report.

The `TabbedForm` doesn't support this usage. I invite you to write your own Form component for your use case.
