### ISSUE TITLE
Disable the `{filter: {q: ""}}` created by default from ReferenceInput

### ISSUE THREAD

**Issue by TMiguelT** [marmelab/react-admin#4036]
**Is your feature request related to a problem? Please describe.**
By default, a `<ReferenceInput>` component generates a `GET_LIST` request, with the params set to `{filter: {q: ""}}`, aka an empty filter for the column `q`.

This is a strange behaviour, because backends may actually try to interpret this filter, even though it has no value. For example, `flask-rest-jsonapi` tries to filter by a column called `q`, which doesn't exist. Similarly, discussion in #2615 shows this problem in a different backend.

**Describe the solution you'd like**
By default, a `<ReferenceInput>` should not add any parameters to the `GET_LIST` request. Instead, users should be required to implement a `filterToQuery` function, where they can add their own filter if needed.

In terms of the actual code, I think the only thing we'd need to do is change the default prop value of `filterToQuery` to a no-op: https://github.com/marmelab/react-admin/blob/0b08e998931f35469b1bfb33874f3e97cc23e3ac/packages/ra-ui-materialui/src/input/ReferenceInput.tsx#L162

**Describe alternatives you've considered**
Currently this default behaviour can be disabled by adding a no-op `filterToQuery`, e.g.:
```js
<ReferenceInput
    filterToQuery={() => {}}
>
```

I'd be happy to write a PR if this would be acceptable.

**Comment by fzaninotto** [comment]
Thanks, reproduced and confirmed. I'll post a fix.
