### ISSUE TITLE
Allow for custom label in NullableBooleanInput

### ISSUE THREAD

**Issue by dryhten** [marmelab/react-admin#4041]
**Is your feature request related to a problem? Please describe.**
Right now [NullableBooleanInput](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/NullableBooleanInput.tsx#L95) doesn't support custom label for null value. It just shows as blank.

**Describe the solution you'd like**
 It would be nice if we can override the default labels for true, false and null (e.g. via props).

**Comment by bicstone** [comment]
FYI: 3.0.1 support custom label using domain translations
https://codesandbox.io/s/simple-0iyef?hidenavigation=1&module=%2Fsrc%2Fi18n%2Fen.js

**Comment by dryhten** [comment]
Cool, it looks exactly like what I need. However I didn't get to test it, I tried upgrading my project to `react-admin` 3.0.1 but couldn't get `NullableBooleanField` to work again (it kept complaining it gets undefined instead of 'true'/'false'/'' even though `BooleanField` worked just fine with the same source). I didn't spend time debugging but I might in the future. Feel free to close this issue (I would personally document how to change the menu items somewhere).
