### ISSUE TITLE
Request a access push for this repo

### ISSUE THREAD

**Issue by Vn-ChemGio** [marmelab/react-admin#4043]
Hello, 
First time, thank you by provider this repositories
When reading project, I had been re-write (clone) a login template, to example/demo page for this repositories
So, can you access me to  push it to this repositories
Thanks

![image](https://user-images.githubusercontent.com/25608423/69556562-7d223300-0fd7-11ea-8304-f28e3f9938bf.png)

**Comment by fzaninotto** [comment]
Hi, the usual way to contribute is to open a pull request - and you don't need special rights for that.

If you're willing to contribute the login page looking like the screenshot above, we won't accept it - material admin isn't the name of this project, and we don't offer login via Google.
