### ISSUE TITLE
ra-realtime alternative

### ISSUE THREAD

**Issue by esistgut** [marmelab/react-admin#4044]
react-admin 2 had the ra-realtime package for realtime updates, this has been deprecated and removed https://github.com/marmelab/react-admin/pull/3908

@fzaninotto commented about an alternative right way to do this using a global EventListener, can we get an example?

**Comment by fzaninotto** [comment]
Realtime support wasn't ready for prime time in v3. Until it is, please ask the community for help. And if you want to speed up the reimplementation of ra-realtime by supporting us financially, please get in touch.

**Comment by bayareacoder** [comment]
@fzaninotto Can you elaborate why ra-realtime wasn't ready for prime-time? 
We modified the older code from v2 to work with v3's object-based data provider and it seems to work using the realtime saga approach. Planning to use it for a real-time dashboard page fed via web sockets.
What is the reason you would move to the 'global event listener' approach instead? 
Thanks.

**Comment by djhi** [comment]
> Can you elaborate why ra-realtime wasn't ready for prime-time?

We just did not have the time to migrate it.

> What is the reason you would move to a 'global EventListener and to interact with it from the dataProvider' approach instead? Thanks.

Because react and redux have evolved, we are moving away from redux-saga and using hooks instead.

> We modified the older code from v2 to work with v3's object-based data provider and it seems to work using the realtime saga approach. Planning to use it for a real-time dashboard page fed via web sockets.

Nice :)

**Comment by bayareacoder** [comment]
Thanks for reply. The more fundamental issue I think is the lack of granularity of rendering the data updates. If you have a List view and only 1 cell in 1 record updates, it's still going to update the whole list, and will do that every time with every update. Any suggestion how we could go about improving that in react-admin to update only changed records, or even cells within those records in a List view? Obviously we could throttle the updates of the whole page by changing the 'realtimeObserverChannel' in ra-realtime to act in less than realtime but that defeats the purpose.
