### ISSUE TITLE
Data provider for strapi-3.0.0 beta version

### ISSUE THREAD

**Issue by yogesh-dalvi** [marmelab/react-admin#4046]
As mentioned in this reference [https://github.com/nazirov91/ra-strapi-rest](https://github.com/nazirov91/ra-strapi-rest), **data provider** for strapi's **alpha** version is provided.
How to use this data provider for strapi's **beta** version as using this data provider requires us to add a **Content-Range** header in the strapi's controller's plugin which is not provided in the **beta** version.

**Comment by fzaninotto** [comment]
This data provider isn't maintained by the react-admin core team. Please open issues concerning it in their repo.

**Comment by devalexandre** [comment]
why the react-admin team does not participate in the development of this provider, strapi is a great cms
