### ISSUE TITLE
'onDrop' does not fire in <ImageInput> options (react-admin 3.0.1)

### ISSUE THREAD

**Issue by JoeLeeWu** [marmelab/react-admin#4068]
**What you were expecting:**
'onDrop' fires in <ImageInput> options

**What happened instead:**
'onDrop' does not fire in <ImageInput> options

**Steps to reproduce:**
Define a function called 'callback'
Add 'options={{onDrop:callback}}' in <ImageInput>

**Related code:**
```
const callback = () => { console.log("callback"); }

<ImageInput source="pictures" label="Related pictures" accept="image/*" options={{onDrop:callback}}>
       <ImageField source="src" title="title" />
</ImageInput>
```

**Environment**

* React-admin version: 3.0.1
* React version: 16.9.0
* Browser: Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by djhi** [comment]
Please follow the issue template.

**Comment by JoeLeeWu** [comment]
Updated comment

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by JoeLeeWu** [comment]
https://codesandbox.io/s/simple-2qzpd?fontsize=14&hidenavigation=1&theme=dark
src->posts->PostEdit.js
<ImageInput>

**Comment by djhi** [comment]
We override the `onDrop` option without calling back the original supplied by the user. Marking this as an enhancement. In the mean time, you may use the `onChange` event which is called after a file is dropped or when a file is removed.

Thanks for the report :+1:

**Comment by JoeLeeWu** [comment]
https://codesandbox.io/s/simple-2qzpd?fontsize=14&hidenavigation=1&theme=dark
src->posts->PostEdit.js
<ImageInput>

changed options 'onDrop' to 'onChange', still no work.

**Comment by djhi** [comment]
Sorry, that's not an option, you can pass it as a prop directly

**Comment by fzaninotto** [comment]
If you need a custom behavior, instead of using `<FileInput>`, you can always use react-dropzone directly. We won't support a custom `onDrop` callback in the core.

**Comment by brownieboy** [comment]
> https://codesandbox.io/s/simple-2qzpd?fontsize=14&hidenavigation=1&theme=dark
> src->posts->PostEdit.js
> `<ImageInput>`
> 
> changed options 'onDrop' to 'onChange', still no work.



> Sorry, that's not an option, you can pass it as a prop directly

Adding onChange as a prop directly did not work for me.   It does trigger as an option though, but unlike onDrop, it only works if I click on the image loader and load it from the file dialog.   It doesn't trigger when I drop it from the Finder.   This is on Mac OS X Mojave.

**Comment by brownieboy** [comment]
I worked around this by dropping the ImageField component and just using an ordinary img tag.  I then use an onDrop callback to set the src of that img tag to the preview property of fileObj parameter that's passed to the callback.

```JavaScript
const ImageForm = props => {
  const [previewPath, setPreviewPath] = useState("");

  const handleImageChange = fileObj => {
    setPreviewPath(fileObj[0].preview);
  };

  return (
    <SimpleForm {...props}>
      <ImageInput
        source="pictures"
        label="Image"
        accept="image/*"
        options={{ onDrop: handleImageChange }}
      />
      {previewPath && previewPath !== "" ? (
        <img
          src={previewPath}
          title="preview"
          alt="preview"
          style={styles.imagePreview}
        />
      ) : null}
    </SimpleForm>
  );
};
```

Note: the img tag has to go outside of the ImageInput component or it won't work.
