### ISSUE TITLE
TextInput (resettable)in Filter when input  will become longer(width) 

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#4069]
**What you were expecting:**
TextInput (resettable) should not change the width in the Filter

**What happened instead:**
set TextInput resettable , when i input something the input width will longger

**Steps to reproduce:**
see [https://codesandbox.io/s/simple-mk9bm](https://codesandbox.io/s/simple-mk9bm)
1.enter to post list
2 .see the Title of  Filter ,type some word into it.
**Related code:**
```
  <Filter {...props}>
    <TextInput source="title" resettable alwaysOn />
  </Filter>
```
**Environment**

* React-admin version:3.0.1

**Comment by djhi** [comment]
Reproduced. Thanks for the report
