### ISSUE TITLE
The dataProvider returned an empty response for 'delete'. (react admin 3.0.1)

### ISSUE THREAD

**Issue by JoeLeeWu** [marmelab/react-admin#4070]
When deleting a resource, "The dataProvider returned an empty response for 'delete'." happens.
In dataProvider, though I hard code the response for DELETE action, the warning still happens. 
```
delete: (resource, params) =>{
        httpClient(`${apiUrl}/${resource}/${params.id}`, {
            method: 'DELETE',
        }).then(({ json }) => ({ data: {result: "deleted"} }))
    },
```

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
Perhaps you miss a `return`?

```diff
delete: (resource, params) =>{
-       httpClient(`${apiUrl}/${resource}/${params.id}`, {
+       return httpClient(`${apiUrl}/${resource}/${params.id}`, {
            method: 'DELETE',
        }).then(({ json }) => ({ data: {result: "deleted"} }))
    },
```

**Comment by fzaninotto** [comment]
No news for some time, closing.
