### ISSUE TITLE
Filter is not being applied when using useListController and ListView

### ISSUE THREAD

**Issue by Nohac** [marmelab/react-admin#4083]
**What you were expecting:**
I expect the `filter` prop to work as it does when using `List`.

**What happened instead:**
The filter is not being applied at all.

**Related code:**
https://codesandbox.io/s/simple-v9n85

I modified the `PostList.js` file to use `ListView` and `useListController`. Passing the filter directly to `useListController` works, but this is not always the best option, and it's not as clear as passing it to the `ListView`. I assume it doesn't work because `useListController` does the request, and not when it's passed to the `ListView` itself.

```js
const PostList = props => {
  ...
  const listController = useListController({
    ...props,
    // filter: { title: "Omnis voluptate enim similique est possimus" }
  });
  return (
    <ListView
      {...listController}
      bulkActionButtons={<PostListBulkActions />}
      filters={<PostFilter />}
      filter={{ title: "Omnis voluptate enim similique est possimus" }}
      sort={{ field: "published_at", order: "DESC" }}
      exporter={exporter}
    >
    ...
    </ListView>
  )
...
```

**Other information:**

**Environment**
* codesandbox.io

**Comment by fzaninotto** [comment]
Exactly, the request is done by `useListController` and it needs the `filter`, so what you ask isn't possible with react-admin. If you want a different separation of responsibilities, you'll have to write your own controller hook and ListView component.
