### ISSUE TITLE
[V3.0] ReferenceInput not work on create, with Redux enabled

### ISSUE THREAD

**Issue by jmayoranotandil** [marmelab/react-admin#4087]
**What you were expecting:**
I expect ReferenceInput shows data like React-admin 2.9

**What happened instead:**
Field is loading infinitely

<img width="405" alt="Screen Shot 2019-11-29 at 2 06 36 PM" src="https://user-images.githubusercontent.com/1682903/69883129-8f3ef280-12b1-11ea-8ff6-78804ea1333a.png">

**Steps to reproduce:**
1 - Enable Redux Provider
```
 <Provider
            store={createAdminStore({
                authProvider,
                dataProvider,
                history,
            })}
        >
         <Admin ..... />
</Provider>
```

2 - Add a ReferenceField on Create Component:
```
<Create>
                <SimpleForm>
                    <ReferenceInput
                        source="bankId"
                        reference="banks"
                        validate={required()}
                        onChange={this.handleSelect}
                    >
                        <SelectInput optionText="name"/>
                    </ReferenceInput>
.
.
.
```

**Other information:**

- I'm upgrading from V2.9 to V3.0.1, and that was working in 2.9
- In Edit Component (with previous data loaded) that works OK
- If I remove Redux, the bank field load correctly, but other problemas are generated

**Comment by fzaninotto** [comment]
I don't thinks there is a bug in react-admin. `ReferenceInput` works correctly with `<Admin>` when not used inside Redux. The fact that "other problemas are generated", as you wrote, lets me think the error is on your side - maybe in your `createAdminStore` code. I suggest you troubleshoot your code on stackOverflow. 

If you manage to show that there is a bug in react-admin and not in your code, feel free to comment here and I'll reopen the issue.
