### ISSUE TITLE
BooleanInput does not display default value correctly for filters

### ISSUE THREAD

**Issue by akedemos** [marmelab/react-admin#4091]
**What you were expecting:**

When looking at the filters of a list view, any default filters that are supplied should be indicated in by the filter. When setting a default value for a boolean e.g `filterDefaultValues={{ commentable: true }}` then the BooleanInput should display a value of true also.

**What happened instead:**

The BooleanInput appears to be set to false, the filter is correctly applied however.

**Steps to reproduce:**

Set the default value in the List view and create a filter

```
    <List
      {...props}
      bulkActionButtons={<PostListBulkActions />}
      filters={<PostFilter />}
      filterDefaultValues={{ commentable: true }} // default to true
      sort={{ field: "published_at", order: "DESC" }}
      exporter={exporter}
    >
```

and then add a filter to PostFilters

`<BooleanInput source="commentable"  alwaysOn/>`

**Related code:**

Codesandbox: https://codesandbox.io/s/simple-9lf55?fontsize=14&hidenavigation=1&theme=dark

**Other information:**

**Environment**

* React-admin version:
3.02
* Last version that did not exhibit the issue (if applicable):
2.x (Seemed to work fine before upgrade)
* React version:
16.12.0
* Browser:
Chrome

**Comment by fzaninotto** [comment]
Reproduced and confirmed, thanks for the report.
