### ISSUE TITLE
<AutocompleteInput /> fullwidth property not working

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#4093]
**What you were expecting:**
Fullwidth `<AutocompleteInput />`

**What happened instead:**
For `<AutocompleteInput />` without `<ReferenceInput />`, after setting the `fullWidth` property, the width becomes smaller.
For `<AutocompleteInput />` without `<ReferenceInput />`, after setting the `options={{ fullWidth: true}}` property, the width does not change.
For `<AutocompleteInput />` with `<ReferenceInput options={{fullWidth: true}} />`, after setting the `fullWidth` property, the width does not change:
```
.makeStyles-input-236 {
    width: 256px;
}
``` 
cancels
```
.MuiFormControl-fullWidth {
    width: 100%;
}
```
For `<AutocompleteInput />` with `<ReferenceInput />`, after setting the `fullWidth` property, the width does not change. `MuiFormControl-fullWidth` missing.

* React-admin version: 3.0.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Confirmed and reproduced, thanks for the report.

**Comment by dkocich** [comment]
i could not make it wider in "react-admin": "4.8.4" this way; should that fix still be working?

**Comment by fzaninotto** [comment]
@dkocich Please open a new issue with a repro if you think there is a bug.

**Comment by dkocich** [comment]
I found out today that the issue was on my side. It works ok using fullwidth property. Thanks for reminder
