### ISSUE TITLE
Customize data provider without having to re-write simple-rest-provider

### ISSUE THREAD

**Issue by rodrigo-picanco** [marmelab/react-admin#4100]
**Is your feature request related to a problem? Please describe.**
Well, since this is my first issue on the repo, first of all, thank you all for this well rounded and so usefull projetct! I always found myself having issues to write a custom data provider cause I was expected to map every single action in react-admin. 

**Describe the solution you'd like**
I was wondering if I could pass a map of customizations and fallback the rest of the common simple rest provider api. 

**Describe alternatives you've considered**
The main creation could look like: 

```js
const types = {
  UPDATE: {
    request: ({ resource, params, apiUrl }) => {
      return {
        url: `${apiUrl}/${resource}/${params.userId}`,
        options: {
          method: 'PATCH',
          body: JSON.stringify({ name: params.data.name })
        }
      }
    },
    success: async ({ httpClient, response }) => {
      const { json } = response
      const userResponse = await httpClient(`/users/${json.id}`)

      return { data: userResponse.json }
    }
  }
}

const usersDataProvider = customDataProviderFactory(types)
```

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. We won't provide this because in react-admin v3, dataProviders are objects. So you can easily override only one method, as explained in the documentation:

https://marmelab.com/react-admin/DataProviders.html
