### ISSUE TITLE
refresh token mechanism

### ISSUE THREAD

**Issue by rlembo-vulog** [marmelab/react-admin#4110]
just to know and avoid digging to much. Is there any refresh token mechanism in auth provider to get a new token when a 401 arise ?

**Comment by djhi** [comment]
No and we don't plan to include one. This is the job of your authProvider

**Comment by DvoeglazovIlya** [comment]
Maybe it help:
https://marmelab.com/blog/2020/07/02/manage-your-jwt-react-admin-authentication-in-memory.html

https://github.com/marmelab/ra-in-memory-jwt/tree/master/demo
