### ISSUE TITLE
'onRemove' does not fire in <FileInput> options

### ISSUE THREAD

**Issue by oleg-andreyev** [marmelab/react-admin#4118]
**What you were expecting:**
'onRemove' fires in options

**What happened instead:**
'onRemove' does not fire in options

**Steps to reproduce:**
Define a function called 'callback'
Add 'options={{onRemove:callback}}' in

**Related code:**
```
const callback = () => { console.log("callback"); }

<ImageInput source="pictures" label="Related pictures" accept="image/*" options={{onRemove:callback}}>
       <ImageField source="src" title="title" />
</ImageInput>
```

**Environment**

* React-admin version: 3.3.x
* Last version that did not exhibit the issue (if applicable): -
* React version: 16.13.1
* Browser: any
* Stack trace (in case of a JS error): -

**Comment by oleg-andreyev** [comment]
Probably it's more like a feature, but IMO events like onDrop and onRemove are must have

Example:
- Using API Platform which is using react-admin 2.x
- While create new Object, I want to upload image immediately on drop to avoid sending N images (HQ) when sending POST also I need to upload image to server in order to detect EXIF/GPS and build MAP with Point from image coords. 

#4068

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by oleg-andreyev** [comment]
@Kmaschta https://codesandbox.io/s/relaxed-snow-fr1vm?fontsize=14&hidenavigation=1&theme=dark

- Go to PostCreate.js ~ 112
- You'll see onDrop and onRemove handlers
- Go to Post Create screen
- Try to upload any image

AR:
- No logs `ImageInput onDrop` or `ImageInput onRemove`

ER:
- onDrop and onRemove are called.
