### ISSUE TITLE
Missing document for useInput

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#4120]
As explained in the doc, I use `addField` to create custom components: https://marmelab.com/react-admin/Inputs.html#writing-your-own-input-component

However, this generate a deprecation warning: `FormField is deprecated, use the useInput hook instead.`.

So I'm looking for `useInput` doc but there is no doc. This piece of doc would be appreciated. It's not really a pain to look in the source code but I feel out of the track which is quite worrying!

**Comment by djhi** [comment]
Thanks for reporting

**Comment by sclausen** [comment]
I don't think `useInput` is exported by `react-admin`, but by `ra-core`, or am I wrong?

**Comment by fzaninotto** [comment]
`react-admin` re-exports all the exports from `ra-core`. We recommend that you always import from `react-admin`, as the `ra-core` API may be changed in a non compatible way in a minor release (with a backward compatible change in `react-admin` to avoid breakage).
