### ISSUE TITLE
RA3 ReferenceArrayInput & AutocompleteArrayInput + parse/format issue + possible solution 

### ISSUE THREAD

**Issue by Bnaya** [marmelab/react-admin#4125]
Sorry i don't have a minimal repro. i'm really not sure how to write one that will show the issue.

Background:
I'm trying to make ReferenceArrayInput + AutocompleteArrayInput to give my array of objects `[{id: 1}, {id: 2}]` and not array of ids `[1, 2]` 

I've tried to set parse and format on `ReferenceArrayInput` & `AutocompleteArrayInput`, one by one, or on both  and i got very wired behaviours. 

code:
```
      initialValue={[]}
      parse={(list: Array<number> = []) => {
        console.log('parse AutocompleteArrayInput', list);
        return list.map(id => {
          return { id };
        });
      }}
      format={(list: Array<{ id: number }> = []) => {
        console.log('format AutocompleteArrayInput', list);
        return list.map(i => i.id);
      }}
```

After some debugging, i've figured that ReferenceArrayInput does not pass `parse` & `format` to the useInput call
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/ReferenceArrayInput.js#L106-L113

*But* ReferenceArrayInput & AutocompleteArrayInput pointing to the same final form field and seems that both of them updating the value of that field. that makes them ""fight""

My local fix is, i've copied `ReferenceArrayInput` into my project, and made it access and pass the parse & format props, and to not pass them to `AutocompleteArrayInput`

**Environment**

* React-admin version: `3.0.3`

**Comment by Kmaschta** [comment]
Thanks for reporting!

It's the ReferenceArrayInput that should pass parse and format to its `useInput` (just like ReferenceInput does)

I created a PR for that fix.

**Comment by Bnaya** [comment]
Thanks!!

**Comment by humbertowoody** [comment]
Hi @Bnaya ! Your code works perfectly for `ReferenceArrayInput` with the latest version of react-admin. However, I can't seem to get it working on an `ReferenceArrayField`. Does the same logic applies? Thanks in advance!

**Comment by Bnaya** [comment]
TBH i'm not sure - i haven't use much fields
But i can imagine how similar issue might be
anyhow, Fields are much more simple and when i want customisation i simply use FunctionField
