### ISSUE TITLE
what is point of blob sending to request in upload file 

### ISSUE THREAD

**Issue by moeinrahimi** [marmelab/react-admin#4126]
I can see react-admin sends blob in the request when using ImageUpload component, as you know blob can be used in the current session of the opened tab, a server can not handle blob and turn it into a file.

**Comment by fzaninotto** [comment]
@moeinrahimi Transferring a file to the server is the `dataProvider`'s job, and react-admin is agnostic in that matter. Feel free to push multipart data with XMLHTTPRequest or use a CDN to store your images - nothing in react-admin prevents you from doing so.

**Comment by sclausen** [comment]
Is there any usecase the file/image upload components work out of the box?
Is there any example displaying the preview image, if the response is now the base64 encoded string, not a file object?
