### ISSUE TITLE
the list view has way too much responsibility .. separate data loading  

### ISSUE THREAD

**Issue by Abenezer** [marmelab/react-admin#4127]
sometimes we would want to load the data ourway (maybe using custom sagas) but still want the awesome filtering, pagination functionalities of the list using it as client side 

Have the list accept data prop and move the data loading component one level up so we can use List with or without automatic data loading (when using as client site mode) just like Grid
```
<DataProvider>
<List>
</List>
</DataProvider>
```

**Comment by fzaninotto** [comment]
Hi @Abenezer,

the separation of responsibilities you mention already exists - see `useListcontroller` to understand how it mixes several hooks that you can reuse individually. 

As for loading data without the data hooks, this won't be supported by react-admin.
