### ISSUE TITLE
ReferenceField link prop documentation is incorrect

### ISSUE THREAD

**Issue by jfedick** [marmelab/react-admin#4129]
**What you were expecting:**

When using a ReferenceField, you should be able to add a `link` prop and set it to either `show`, `edit` or `{false}`.

**What happened instead:**

ReferenceField ignores the `link` prop entirely and just routes the click to the `show`.

**Other information:**

This is just an error in the documentation as the prop is actually called `linkTo` instead of `link`. You can see what I mean here- https://github.com/marmelab/react-admin/pull/490

**Comment by Kmaschta** [comment]
What version of react admin do you use?

This prop `linkType` was renamed in v3 to be `link`.
In my knowledge, it was never called `linkTo`.

Do you have any way to reproduce the issue? It works on my end.

**Comment by jfedick** [comment]
Ah! We use version 2.9.8. I apologize, I meant `linkType` instead of `linkType`. Thanks for the clarification.

**Comment by Kmaschta** [comment]
I'm curious, where did you find linkTo ? Can we improve the documentation on that matter ?
