### ISSUE TITLE
Allow to customize the Pagination component

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/react-admin#4131]
**Is your feature request related to a problem? Please describe.**
In order to change the color (primary or secondary) of the pagination buttons, in the datagrid, we have to clone the whole components `Pagination` and `PaginationActions`.

**Describe the solution you'd like**

1. In the `PaginationActions` component, allow to overwrite the button props
2. In the `Pagination` component, do not use directly the PaginationAction component, but pass it as a default prop `actions = <PaginateActions />`

**Describe alternatives you've considered**
Today, in order to customize the pagination, we're forced to clone these components entirely.

**Comment by fzaninotto** [comment]
Fixed by #4132
