### ISSUE TITLE
material Design Variant not Working on Input fields

### ISSUE THREAD

**Issue by virendrasi** [marmelab/react-admin#4135]
**What you were expecting:**

Adding the Variant attribute on SimpleForm or InputField must changes the UI.
**What happened instead:**

The UI is not changed it remains same underline.
**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by virendrasi** [comment]
Yes The isssue is reproducable in the above URL too, I just modified the Input field in PostEdit and added the variant = outlined , but the output of Input is same.
![image](https://user-images.githubusercontent.com/10473936/70552596-ad54fe80-1b9f-11ea-9ed1-065dedcaac8d.png)

**Comment by virendrasi** [comment]
In material UI the Outlined Input looks different.

![image](https://user-images.githubusercontent.com/10473936/70552748-f3aa5d80-1b9f-11ea-91ad-23dff071f5bb.png)

**Comment by Kmaschta** [comment]
You're right, I tried with the following option  and it doesn't work.

```jsx
<TextInput {...props} options={{ variant: 'outlined' }} />
```

As a workaround, you can set the prop variant to the SimpleForm or the TabbedForm that wraps the textfield.
