### ISSUE TITLE
ReferenceInput with AutocompleteInput can not match the choice according to my input

### ISSUE THREAD

**Issue by HolyZheng** [marmelab/react-admin#4141]
**What you were expecting:**
when I input something words , it will filter out the matched items

**What happened instead:**
when I input something words , it just highlight the same words
![iamge](https://raw.githubusercontent.com/HolyZheng/holyZheng-blog/master/images/image-2019-12-02-20-49-07-696.png)

**Steps to reproduce:**
just click and input

**Related code:**
```JS
<Filter {...props}>
        <ReferenceInput label="企业名称" source="companyId" reference="company" alwaysOn>
            <AutocompleteInput optionText="name" optionValue="id" />
        </ReferenceInput>
 </Filter>
```

**Environment**

* React-admin version:  2.9.4
* React version:  16.8.6
* Browser: chrome
* Stack trace (in case of a JS error): no error

**Comment by fzaninotto** [comment]
Could you please provide a codesandbox demonstrating the issue, preferably with content in English so that we can understand it?
