### ISSUE TITLE
ComponentPropType not exported from 'ra-core'

### ISSUE THREAD

**Issue by LordKriegan** [marmelab/react-admin#4145]
I upgraded from 2.9.8 to 3.03 and when I ran the code, I got the following error:
./node_modules/ra-ui-materialui/esm/layout/Layout.js
Attempted import error: 'ComponentPropType' is not exported from 'ra-core'.

Apparently Layout.js is trying to import something from ra-core, but it no longer exists there.

**Comment by fzaninotto** [comment]
I can't reproduce the problem. Would you mind joining a CodeSandbox demonstrating the issue?

Also, could you check your `yarn.lock` to see if  you don't have a duplicated dependency on `ra-core` (e.g. by not upgrading a secondary react-admin package like `ra-language-english`)?

**Comment by LordKriegan** [comment]
OMG *facepalm* idk why i didnt think of deleting the lock file. i just ended up sticking with 2.9.8 and figuring out how to write the old style dataproviders. im not sure whether my boss will want to stick with this version or upgrade :/ but thanks for the idea.

**Comment by radove** [comment]
I had a similar issue and the resolution was to ensure all RA packages were upgraded too. In my case, it was ra-data-json-server.
