### ISSUE TITLE
[Suggestion] Publish canary/nightly version 

### ISSUE THREAD

**Issue by Bnaya** [marmelab/react-admin#4146]
The title is kinda self explanatorily 😅
I basically sometimes want have the option to quickly use something merged to master before the next release.

**Comment by codeser** [comment]
I think it's very easy to change to the Material-ui dark mode. I can show you how on here if that's what you're looking for?

**Comment by fzaninotto** [comment]
We release bug fix versions every week. If you need to be even more on the cutting edge, then you have to release your own packages, or use `npm link`.

In fact, I even think we do too many releases: for developers, in can be intimidating.
