### ISSUE TITLE
Can't I return a form custom error anymore with “Altering the Form Values before Submitting”?

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#4148]
[this question on the stackoverflow.com](https://stackoverflow.com/questions/59299706/cant-i-return-a-form-custom-error-anymore-with-altering-the-form-values-before)

Please help with the question as it prevents me from switching from version 2 to version 3.

React-admin version 2 used redux-form. Together with the documentation "Altering the Form Values before Submitting" i created a custom button that returns a form error from a custom function, or does a save.

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { crudCreate, SaveButton, Toolbar } from 'react-admin';
import { SubmissionError } from 'redux-form';

const myValidate = (values) => {
    const errors = {};
    if (values.files < 1) errors.files = 'resources.Order.errors.files';

    return errors;
};

// A custom action creator which modifies the values before calling the default crudCreate action creator
const saveWithNote = (values, basePath, redirectTo) =>
    crudCreate('posts', { ...values, average_note: 10 }, basePath, redirectTo);

class SaveWithNoteButtonView extends Component {
    handleClick = () => {
        const { basePath, handleSubmit, redirect, saveWithNote } = this.props;

        return handleSubmit(values => {

            return new Promise((resolve, reject) => {
                const errors = myValidate(values);
                if (errors) { 
                    reject(new SubmissionError(errors))
                } else {
                    resolve( saveWithNote(values, basePath, redirect) );
                };
            }
            });

        });
    };

    render() {
        const { handleSubmitWithRedirect, saveWithNote, ...props } = this.props;

        return (
            <SaveButton
                handleSubmitWithRedirect={this.handleClick}
                {...props}
            />
        );
    }
}

const SaveWithNoteButton = connect(
    undefined,
    { saveWithNote }
)(SaveWithNoteButtonView);
```

Now in React-admin version 3 "Altering the Form Values before Submitting" Can't I do this anymore? This code does not work:(

```
import React, { useCallback } from 'react';
import ProcessIcon from '@material-ui/icons/HeadsetMic';
import { useForm, useFormState  } from 'react-final-form';
import { SaveButton } from 'react-admin';

const validateProcess = (values) => {
    const errors = {};

    if (values.files < 1) errors.files = ['resources.Order.errors.files'];

    return errors
};

const SaveWithProcessButton = ({ handleSubmitWithRedirect, ...props }) => {
    const form = useForm();
    const formState = useFormState();

    const handleClick = useCallback(() => {

        return new Promise((resolve, reject) => {
            const errors = validateProcess(formState.values);
            if (errors) { 
                reject(errors) 
            } else {
                form.change('status', "DRAFT");
                resolve( handleSubmitWithRedirect('show') );
            };

        });
    }, [form]);

    return <SaveButton {...props} handleSubmitWithRedirect={handleClick} label="ra.action.process" icon={<ProcessIcon />} />;
};

export default SaveWithProcessButton;
```

**Comment by fzaninotto** [comment]
I think the documentaton is outdated. Would you mind trying to add the following line after the `form.change` line?

```js
form.resetFieldState('status');
```

**Comment by fzaninotto** [comment]
Oh, and what 'does not work'? Is it the display of errors or the update of fields before submission?

**Comment by wmwart** [comment]
@fzaninotto, thank you for responding so quickly.
But my task is that the code does not reach the form submission.
If you noticed then validateProcess now always returns an error. I want the files field to be highlighted in red with an error message at this moment and Nofification to be displayed as if the validate property in SimpleForm worked.

**Comment by fzaninotto** [comment]
well, it does work on the simple example (see [PostCreate](https://github.com/marmelab/react-admin/blob/e434745ff8431fc6ad3c37bbce3802304cf3d352/examples/simple/src/posts/PostCreate.js#L25-L63)), so I believe the problem is on your side. 

As this issue tracker is only for bugs and not for troubleshooting, please use StackOverflow to ask for help.

**Comment by wmwart** [comment]
In a simple simple example, you cleverly circumvented this problem and wrote in the end:

> Note: This technique will not trigger a form validation pass.

That is, now there is no way to display an error in the form at the time of clicking on the custom button?

**Comment by fzaninotto** [comment]
I really don't know, I think it's a react-final-form question.
