### ISSUE TITLE
Release 3.0.4 dependency not updated.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4154]
File version for `packages/ra-data-simple-rest/package.json` hasn't been changed.
I don't know if this is right.

**Comment by Kmaschta** [comment]
None of the files of this package was changed between the 3.0.3 and the 3.0.4:
https://github.com/marmelab/react-admin/compare/v3.0.3...v3.0.4

There is no need to upgrade this package. Am I missing something?

**Comment by WiXSL** [comment]
Ok, could be, I thought it was some sort of  convention you have maintaining the packages.json files that way since from release 3.0.2 to 3.0.3 that file was updated but the package wasn't change.
But I think I was wrong.
