### ISSUE TITLE
ra-data-graphql-simple sending wrong pagination (seems zero-based)

### ISSUE THREAD

**Issue by EricTousignant** [marmelab/react-admin#4155]
**What you were expecting:**
I'm expecting the page number in the request to be the number of the actual page (as displayed)

**What happened instead:**
The page number sent through the request seems to be zero-based.

**Steps to reproduce:**
To reproduce, we need a graphql endpoint and define a resource.

**Related code:**
Basically, it seems we are sending the page number - 1 in ra-data-graphql-simple: 
[ra-data-graphql-simple/src/buildVariables.js:180](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql-simple/src/buildVariables.js#L180) & [251](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql-simple/src/buildVariables.js#L251)

**Other information:**
Is this the intended behavior? The only references I could find were about Apollo discussing offset-based pagination, but if we were sending zero-based value for this purpose, shouldn't it be using offset as the key, instead of page?

**Environment**

* React-admin version: 3.0.3
* React version: 16.12
* ra-data-graphql-simple version: 3.0.2

**Comment by Kmaschta** [comment]
It seems confusing to me too... Perhaps the package ra-data-graphql-simple was designed with a zero-based GraphQL endpoint, and that's the end of the story.
Not sure if we have to change it on our own, paging @fzaninotto and @djhi one this one.

In the meantime, a workaround would be to wrap this data provider to fix the offset.

**Comment by EricTousignant** [comment]
@Kmaschta, could you give me a quick nudge in the right direction for wrapping the dataProvider to fix only this argument? Thanks.

**Comment by Kmaschta** [comment]
I would be something like that (I've not tested):

```js
import simpleGraphqlProvider from 'ra-data-graphql-simple';

export const dataProvider = {
    ...simpleGraphqlProvider,
    getList: async (resource, params) => {
        const result = await simpleGraphqlProvider.getList(
            resource,
            { ...params, page: params.page + 1 }
        );

       return { ...result, page: result.page - 1 };
    },
}:
```

**Comment by EricTousignant** [comment]
I ended up decorating the dataProvider as explained [here](https://marmelab.com/react-admin/doc/2.8/DataProviders.html#decorating-your-data-provider-example-of-file-upload).

The issue I have now is that it seems to break the filters. The pages are incrementing with each request. So it stops working pretty quickly. I have the feeling there is something broken somewhere in the pagination between react-admin and ra-data-graphql-simple, but I can't seem to figure it out.

**Comment by berenddeboer** [comment]
Using same package, not seeing that.

**Comment by berenddeboer** [comment]
My bad, it is indeed zero based. This is actually convenient for my calculations.

**Comment by fzaninotto** [comment]
Why is it wrong? That's a design choice, and it works well with json-graphql-server.
