### ISSUE TITLE
Misleading of react-admin doc of <DateTimeInput> 

### ISSUE THREAD

**Issue by JoeLeeWu** [marmelab/react-admin#4160]
For [vascofg/react-admin-date-inputs.](https://github.com/vascofg/react-admin-date-inputs) is not updated anymore, and it is not suitable for new version react admin, please fix the react-admin doc of <DateTimeInput> part.
Thanks.

**Comment by fzaninotto** [comment]
Why is it not suitable? Is there a bug when you use it?

**Comment by Kmaschta** [comment]
Feel free to open a PR to remove this library from the documentation

**Comment by JoeLeeWu** [comment]
When using this library, It failed to compile for the wrong dependency of it.
I looked into the source code and found it is importing 'material-ui-pickers/utils/MuiPickersUtilsProvider' which is located at the wrong path.
And I can not solve the problem. 
'Can't resolve 'material-ui-pickers/utils/MuiPickersUtilsProvider' shows in the console.

**Comment by fzaninotto** [comment]
Well, you need to open an issue in their repo. We can't keep track of all third-party packages.

**Comment by JoeLeeWu** [comment]
But your doc tells me to use a library which is not valid anymore if I want to use material-ui styled <DateTimeInput>
`Tip: For a material-ui styled <DateTimeInput> component, check out vascofg/react-admin-date-inputs.`

**Comment by kell18** [comment]
Same here

**Comment by WiXSL** [comment]
They just updated the library two days ago.
https://github.com/vascofg/react-admin-date-inputs/pull/40
