### ISSUE TITLE
Console warning when using alwaysOn SelectInput in Filter component

### ISSUE THREAD

**Issue by MiMo42** [marmelab/react-admin#4161]
**What you were expecting:**
No console warnings

**What happened instead:**
Console warning:
`Warning: React does not recognize the `alwaysOn` prop on a DOM element.`
It hit me after set alwaysOn prop on a SelectInput within a Filter component.

**Steps to reproduce:**
- Open modified ra simple example at https://codesandbox.io/s/simple-kld3t
- Switch to Comments
- See Warning in console

**Related code:**
https://codesandbox.io/s/simple-kld3t

**Other information:**
As in #4133 alwaysOn prop is not sanitized.

**Environment**

* React-admin version: 3.0.4 
* React version: 16.12.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Reproduced and confirmed, thanks for the report.

**Comment by marina9568** [comment]
The same issue with SelectArrayInput.
