### ISSUE TITLE
Add documentation snippet to upgrade redux-saga from 0.16 to 1.0 in v2 to v3 upgrade doc

### ISSUE THREAD

**Issue by mbchoa** [marmelab/react-admin#4166]
There's no mention of upgrading the `redux-saga` package in the the [UPGRADE.md](https://github.com/marmelab/react-admin/blob/master/UPGRADE.md) doc.

I encountered the following error when trying to spin up my local React app. 

![Screen Shot 2019-12-13 at 5 14 11 PM](https://user-images.githubusercontent.com/1431853/70841061-115c0a80-1dcc-11ea-9f58-9e169c183d8f.png)

It would be helpful if this could be mentioned in the [Increased version requirement for key dependencies](https://github.com/marmelab/react-admin/blob/master/UPGRADE.md#increased-version-requirement-for-key-dependencies) section of the doc.

**Comment by fzaninotto** [comment]
Thanks for the report, will be fixed soon.
