### ISSUE TITLE
Column headers for Datagrid in ReferenceManyField don't update sort indicator

### ISSUE THREAD

**Issue by dinodeSimon** [marmelab/react-admin#4178]
**What you were expecting:**
When using a ReferenceManyField with a Datagrid child a user can re-sort the columns by clicking on the column headers. The field being used for sort and the sort order should be indicated by an arrow next to the column header. 

**What happened instead:**
The field with the initial sort has the indicator next to it but sorting on any other column doesn't update the sort field or oder indicator. The data is sorted correctly as expected. This feature used to work with RA 2.9

**Steps to reproduce:**
Go to https://marmelab.com/react-admin-demo/#/customers
Sort by "Orders" to bring a customer with multiple orders to the top of the list
Select a customer with multiple orders
Click on the "Orders" tab
Click on the column headers to sort by that column in ascending or descending order
The columns will sort correctly but the indicator won't be updated

**Other information:**
![2019-12-17 12 40 30](https://user-images.githubusercontent.com/45355318/70957537-854b2b00-20ca-11ea-8991-120a1ffca012.gif)

**Environment**

* React-admin version: 3.0.4
* Last version that did not exhibit the issue (if applicable): 2.9.x

**Comment by Kmaschta** [comment]
Reproduced, thanks!
