### ISSUE TITLE
AutocompleteInput does not display choices

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#4183]
**What you were expecting:**
I expected to enter a search string in the <AutocompleteInput/> and get autocomplete choices

**What happened instead:**
The query returned a list of autocomplete options, but they were not displayed.
Rather, they appear for a moment when I remove the focus from the field, then disappear.

**Related code:**
```
const TaskCreate = ({...props }) => {
  
    const controllerProps = useCreateController(props);

    return (
        <CreateView
            {...props}
            {...controllerProps}
        >
            <SimpleForm  >
            <ReferenceInput source="maintainableItem" reference="Object"  fullWidth >
                <AutocompleteInput />
            </ReferenceInput> 
            </SimpleForm>
        </CreateView>
    );
};

export default TaskCreate;
```

**Other information:**
that's what the react-admin does right after the page loads:
![Аннотация 2019-12-18 151207](https://user-images.githubusercontent.com/28799755/71085618-fcef8780-21a8-11ea-9523-3a360c2e7793.jpg)

response:
![Аннотация 2019-12-18 151517](https://user-images.githubusercontent.com/28799755/71085747-3f18c900-21a9-11ea-8086-c001049151f3.jpg)

then i enter the search text:
![Аннотация 2019-12-18 1515174](https://user-images.githubusercontent.com/28799755/71085865-81daa100-21a9-11ea-8bf4-13ab2b9fe9c3.jpg)

response:
![Аннотация 2019-12-18 15151а74](https://user-images.githubusercontent.com/28799755/71085906-9cad1580-21a9-11ea-8db6-ed6a75b74dcf.jpg)

but nothing is displayed on the screen until I click on an empty spot:
![wfUqa2CtL2](https://user-images.githubusercontent.com/28799755/71086005-cc5c1d80-21a9-11ea-82a0-767d809b9abe.gif)

after a moment, the autocomplete options disappear and the first 25 entries are displayed

**Environment**

* React-admin version: 3.1.0

**Comment by wmwart** [comment]
Empirically, I have identified the problem. It was hard to guess.

If the optionText property (default "name") does not contain a search string ({filter: { q: "d2he"}}), then the options are not displayed !!!

How so? The {filter: { q: "d2he"}} does not have to return objects with the "name" field that contains the search string.
For example, my backend allows me to search by id, but I do not want to return the id to the AutocompleteInput option, I want to display the name, and I can not do this.

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by wmwart** [comment]
@Kmaschta, comment above

**Comment by wmwart** [comment]
I think it has something to do with [4092](https://github.com/marmelab/react-admin/issues/4092)

**Comment by dinodeSimon** [comment]
@wmwart not sure if this is what you are after but something like this should allow you to select items from the AutocompleteInput without it trying to filter the results returned from the api based on the text displayed

`<AutocompleteInput matchSuggestion={() => true}/>`

**Comment by wmwart** [comment]
Oh! Thanks, it really helped! But what does it do? How did you guess to use this? The documentation says nothing about my use case.

**Comment by fzaninotto** [comment]
The AutocompleteInput does filtering on the client-side, and the ReferenceInput does filtering in the server side. Even though the AutocompleteInput does receive options, the ReferenceInput won't display them if the `optionText` does not match the typed string. 

That's what `matchSuggestion` is for. It's a function which check whether a choice matches a filter. It must return a boolean.  

```ts
(filter: string, suggestion: any) => boolean
```

It's documented in the properties of the `AutocompleteInput`: https://marmelab.com/react-admin/Inputs.html#autocompleteinput.
