### ISSUE TITLE
ReferenceError: getPermissionsWithoutProvider is not defined

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#4184]
Because `getPermissionsWithoutProvider` is initialized with a var, it can't be placed below `useGetPermissions`.

Either, change `getPermissionsWithoutProvider` to function OR move it before `useGetPermissions`

**Environment**

* React-admin version: 3.0.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: Chrome
* Stack trace (in case of a JS error): `ReferenceError: getPermissionsWithoutProvider is not defined`

**Comment by fzaninotto** [comment]
Thanks for the report
