### ISSUE TITLE
Custom routes not working when rendering something of the resources (3.1.0)

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#4196]
**What you were expecting:**
A custom route to be able to render the List of a resource

**What happened instead:**
> A client error occurred and your request couldn't be completed.

> Error: An error occurred while selecting the store state: Cannot read property 'list' of undefined.

**Steps to reproduce:**
See the related code. Change path="/posts" to path="/foo" and the error is gone and the posts list is rendered.

**Related code:**
https://codesandbox.io/s/custom-route-not-working-4iyg5

```
import posts from "./posts";

const customRoutes = [
  <Route
    exact
    path="/posts"
    render={props => React.createElement(posts.list, props)}
  />
];

render(
  <Admin
    authProvider={authProvider}
    dataProvider={dataProvider}
    i18nProvider={i18nProvider}
    title="Example Admin"
    customRoutes={customRoutes}
  >
    <Resource name="posts" {...posts} />
  </Admin>,
  document.getElementById("root")
);
```

**Other information:**
On codesandbox you do not actually get the specific error, that I'm seeing here, but that seems cross-origin related, so you can ignore what codesandbox is saying. This is what I'm seeing locally:

> Error: An error occurred while selecting the store state: Cannot read property 'list' of undefined.

A peek at redux state shows me that state.admin.resources is an empty object {} when my function component at /posts is running.

I think somehow the resources are not defined in the redux store quite yet, when a ListController by a customRouted component is trying to read from state.admin.resources.posts.list or something.

**Environment**

* React-admin version: 3.1.0
* Last version that did not exhibit the issue (if applicable): 2.9.x
* React version: 16.12.0
* Browser: Chrome
* Stack trace (in case of a JS error):

> Uncaught Error: An error occurred while selecting the store state: Cannot read property 'list' of undefined.
>     at useSelectorWithStoreAndSubscription (useSelector.js:39)
>     at useSelector (useSelector.js:104)
>     at useListParams (useListParams.js:81)
>     at useListController (useListController.js:54)
>     at List (List.js:80)
>     at renderWithHooks (react-dom.development.js:16260)
>     at mountIndeterminateComponent (react-dom.development.js:18794)
>     at beginWork$1 (react-dom.development.js:20162)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:336)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
>     at invokeGuardedCallback (react-dom.development.js:440)
>     at beginWork$$1 (react-dom.development.js:25780)
>     at performUnitOfWork (react-dom.development.js:24695)
>     at workLoopSync (react-dom.development.js:24671)
>     at performSyncWorkOnRoot (react-dom.development.js:24270)
>     at scheduleUpdateOnFiber (react-dom.development.js:23698)
>     at updateContainer (react-dom.development.js:27103)
>     at react-dom.development.js:27528
>     at unbatchedUpdates (react-dom.development.js:24433)
>     at legacyRenderSubtreeIntoContainer (react-dom.development.js:27527)
>     at Object.render (react-dom.development.js:27608)
>     at Module../src/index.js (index.js:265)
>     ...(bootstrap stuff)

**Comment by wuichen** [comment]
im having the same error as well. heres my code that triggered the same error. i have followed the tutorial of placing admin under another app. 
<img width="1440" alt="Screen Shot 2019-12-22 at 2 32 36 AM" src="https://user-images.githubusercontent.com/6353587/71312233-5edb1600-2463-11ea-8027-a08ef583ba84.png">

<img width="602" alt="Screen Shot 2019-12-22 at 2 31 34 AM" src="https://user-images.githubusercontent.com/6353587/71312215-38b57600-2463-11ea-9070-e283066fd255.png">
<img width="604" alt="Screen Shot 2019-12-22 at 2 31 13 AM" src="https://user-images.githubusercontent.com/6353587/71312216-38b57600-2463-11ea-8c20-4c0dec00e233.png">

**Comment by i25878427** [comment]
I am handling a similar issue too when trying to use custom routers.
Here are the errors I am having-

![Screen Shot 2019-12-26 at 12 03 55](https://user-images.githubusercontent.com/6019339/71471408-15c6f100-27d8-11ea-898e-bf8fb4c7cd5d.png)
![Screen Shot 2019-12-26 at 12 03 46](https://user-images.githubusercontent.com/6019339/71471411-18294b00-27d8-11ea-99b0-dbb24f71c217.png)
![Screen Shot 2019-12-26 at 12 06 39](https://user-images.githubusercontent.com/6019339/71471461-33945600-27d8-11ea-8d1f-80ff9aee4ac4.png)

**Comment by christiaanwesterbeek** [comment]
I'm halfway upgrading quite a large app from 2.x to 3.1.1. It's a lot of work, but I'm not sure if I should follow through right now, since I know I'll endup not being able to release it due to this problem I described in this issue.

I wonder if I should bail the upgrade now and do it again after a fix for this problem is released or plan for a timely fix (or workaround) and follow through with my current upgrade.

Unfortunately I do not have the resources to investigate the problem myself. @fzaninotto Can you provide some feedback on this issue? Based on it I can decide when to upgrade.

**Comment by djhi** [comment]
Reproduced. I'll look into it
