### ISSUE TITLE
FileInput doesn't accept xlsx files

### ISSUE THREAD

**Issue by vgb0332** [marmelab/react-admin#4205]
**What you were expecting:**
FileInput should accept excel files

**What happened instead:**
No preview or File data is delivered at all.

**Steps to reproduce:**
Simple FileInput example with accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" attribute.

**Related code:**
```
            <FileInput source="csvFile" label="Upload file (.csv)" type="files" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
                <FileField source="src" title="title" />
            </FileInput>
```

**Other information:**
Strange thing is that it accepts csv files but not xlsx files..

**Environment**

* React-admin version: 2.0.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.1
* Browser: Window Chrome
* Stack trace (in case of a JS error):

**Comment by ThieryMichel** [comment]
I can upload xlsx file with the mimetype application/vnd.openxmlformats-officedocument.spreadsheetml.sheet with your code snippet.
Do note that the accept props check the file mimeType. If for whatever reason, your file has no mimetype or another one, he will get rejected and the file input will remains empty.
