### ISSUE TITLE
Invalid value for prop `translate` on <div> tag.

### ISSUE THREAD

**Issue by michelerota** [marmelab/react-admin#4207]
**What you were expecting:**
I expect the browser to not trigger a warning in the console.

**What happened instead:**
The browser throws a warning in the console with the message "Invalid value for prop `translate` on \<div\> tag." when using \<ShowView/\> instead of \<Show/\>. To remove the warning I give an empty "translate" prop to the ShowView component.

**Steps to reproduce:**
```export const MyShow = props => (
    <ShowController {...props}>
        {controllerProps =>
            <ShowView {...props} {...controllerProps}>
                <SimpleShowLayout>
                    <TextField source="myfield"/>
                </SimpleShowLayout>
            </ShowView>
        }
    </ShowController>
);
```

This does not trigger the error:
```export const MyShow = props => (
    <ShowController {...props}>
        {controllerProps =>
            <ShowView {...props} {...controllerProps} translate="">
                <SimpleShowLayout>
                    <TextField source="myfield"/>
                </SimpleShowLayout>
            </ShowView>
        }
    </ShowController>
);
```

**Environment**

* React-admin version: 3.1.1
* React version: 16.12
* Browser: Chrome 79.0.3945.88
* Stack trace (in case of a JS error):
in div (created by ShowView)
    in ShowView (at anagrafica.js:60)
    in ShowController (at anagrafica.js:58)
    in MyShow (created by WithPermissions)
    in WithPermissions (created by Context.Consumer)
    in Route (created by ResourceRoutes)
    in Switch (created by ResourceRoutes)
    in ResourceRoutes (created by Resource)
    in Resource (at App.js:46)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Context.Consumer)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Context.Consumer)
    in withRouter(WithStyles(Layout)) (created by ConnectFunction)
    in ConnectFunction (created by LayoutWithTheme)
    in ThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (created by Context.Consumer)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Context.Consumer)
    in Route (created by AdminUI)
    in Switch (created by AdminUI)
    in AdminUI (created by Admin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by AdminContext)
    in TranslationProvider (created by AdminContext)
    in Provider (created by AdminContext)
    in AdminContext (created by Admin)
    in Admin (at App.js:38)
    in App (at src/index.js:7)

**Comment by ThieryMichel** [comment]
Happens only with ShowController component not useShowController hook.
