### ISSUE TITLE
Translate defaultProps not working as before for class component

### ISSUE THREAD

**Issue by Madebymaurice** [marmelab/react-admin#4208]
**What you were expecting:**
We are actually update react-admin to version 3 but we facing an issue with `translate`
We mostly use class component in numbers of files, we use a file called `component.js` for the component and `index.js` for all the encapsuled stuff.

**What happened instead:**
But with the new version of react-admin, the `translate` defaultProps (f => f) is used by default so all the translation is lost. The only trick that we find is to put the `translate` props as Required in our `propTypes`.
But the side effect is that we use jest for testing, and all the tests failed because the `translate` function is now needed. So we need to put in all tests the props `translate: jest.fn()`
In the documentation for the upgrade to version 3 it's specified that we could use the `translate` as before even if it's deprecated.

Do you have any idea for solve the problem without pass on all our tests and component ?

**Related code:**

```
// component.js
class MyComponent extends Component {
static propTypes = {
...propTypes,
translate: func,
}
static defaultProps = {
...defaultProps,
translate: f => f,
}
export default MyComponent

// index.js
import {translate} from 'react-admin';
import MyComponent from './component';

export default translate(MyComponent);
```

**Environment**

* React-admin version: 3.1
* Last version that did not exhibit the issue (if applicable): 2.9
* React version: 16.8
* Browser: Firefox or Chrome
* Stack trace (in case of a JS error):

**Comment by ThieryMichel** [comment]
Thanks for the issue we will look into it.
