### ISSUE TITLE
Warning: React does not recognize the `basePath` prop on a DOM element.

### ISSUE THREAD

**Issue by manisuec** [marmelab/react-admin#4209]
Expected Behaviour: No warning of prop when Grid component is used inside SimpleForm component.

Current Behaviour: Getting below warning.

```
2.chunk.js:363015 Warning: React does not recognize the `basePath` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `basepath` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at boqitemcreate.js:129)
    in div (created by FormInput)
```

Code: 
```
<SimpleForm toolbar={<BoQCreateToolbar />} redirect={redirect}>
					<Grid container spacing={1} style={{ width: 'auto' }}>
						<Grid item xs={4}>
```
**Environment**

* React-admin version: 3.1.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: Chrome/Opera
* Stack trace (in case of a JS error):

**Comment by ThieryMichel** [comment]
Seems like it come from boqitemcreate.js:129 where FormInput is probably called.
Can you post its code here.
Thanks in advance.

**Comment by fzaninotto** [comment]
SimpleForm expects Input or Field components as children (as [explained in the documentation](https://marmelab.com/react-admin/CreateEdit.html#the-simpleform-component)). So it's normal that you see warnings if you pass anything else. 

for your use case, you need a custom form component.

**Comment by waynebloss** [comment]
Here's an quick workaround that works by throwing away any props normally passed to an input:

```jsx
export const NonInput = React.memo(function NonInput({ children }) {
  return children;
});
```

I use it in my `<SimpleForm>` to add notes and other non-input items to my forms:

```jsx
      <TextField source="otherField" />
      <NonInput>
        <Typography color="error">
          Important note that is always visible and has it's own layout outside of any field!!
        </Typography>
      </NonInput>
```

**Comment by nathan815** [comment]
@waynebloss  Have you found any way to wrap inputs in a FormGroup while avoiding the above error?

i.e.

```
<TabbedForm>
...
<FormTab label="Section name">
    <FormGroup row fullWidth>
        <NumberInput source="distanceInches" label="Distance" helperText="Inches" className={classes.toleranceInput} />
        <NumberInput source="distanceToleranceInches" label="+/- Tolerance" helperText="Inches" className={classes.toleranceInput} />
    </FormGroup>

</FormTab>
</TabbedForm>
```

I get this error for both the FormGroup and FormLabel.

**Comment by wayheyha** [comment]
> SimpleForm expects Input or Field components as children (as [explained in the documentation](https://marmelab.com/react-admin/CreateEdit.html#the-simpleform-component)). So it's normal that you see warnings if you pass anything else.
> 
> for your use case, you need a custom form component.

Hello fzaninotto,

do you guys don't see a reason for form elements to be nested inside a grid?
It is a real pain to make good forms because we can't use grids in the simpleform component. Most of the stuff happening in an admin dashboard is forms.
This would have been a cool feature but instead i guess i will just waste many hours and find out how i writ a custom form. 

Cheers,
Chris

**Comment by WiXSL** [comment]
@wayheyha,  Maybe the [SimpleForm's `component`](https://marmelab.com/react-admin/CreateEdit.html#simpleform-component) prop could help you

**Comment by fzaninotto** [comment]
Hello @wayheyha,

That's a cool feature indeed. In fact, it's already possible with SimpleShowLayout in `next`. If you feel like adding the same abililty for SimpleForm, please open a PR on the `next` branch.

**Comment by wayheyha** [comment]
Hello @fzaninotto,

please excuse my harshness in tone earlier, that was unmannered. From a newbie's perspective this problem was hard to understand and it was a false accusation that you were careless . The problem was easy to handle with the right understanding of what is going on.

For everybody with the same problem the sollution is to just not pass the basePath-parameter to the Grid-Component, e.g. like this:

export const SanitizedGrid = ({basePath, ...props}) => {
    return (
        <Grid {...props} />
    );
};
