### ISSUE TITLE
Issue do display "Save" button on iPhone only for portrait device orientation.

### ISSUE THREAD

**Issue by oz-messapps** [marmelab/react-admin#4211]
The button "Save" disappered when you try to see the Edit form on real devices the pic is below
https://storage.www.wrike.com/filemeta/oriented/F123105297.A2426874 ,
but pretty nice in the browser emulator the toolbar with "Save" button on the bottom of the display!

In other cases everything is ok, even desktop or mobile but in landscape orientation.

**What you were expecting:**

My expectation that on real devices behaviour will be the same as emulated.

Thanks for advance.

**What happened instead:**

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by ThieryMichel** [comment]
Cannot access the image: I got a 403 error.
From what I can see in landscape, the toolbar can be at the bottom of the page on bigger phone screen (more than 600px).
Currently you can only change that behavior by rewriting the Toolbar component to change [the width detection value](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/form/Toolbar.js#L74-L75).

**Comment by ThieryMichel** [comment]
My mistake we use material-ui breakpoint to detect screen size.
We fix the toolbar on the xs breakpoint (600px)
And you can change the material-ui breakpoint in the theme.
see https://material-ui.com/customization/default-theme/?expand-path=$.breakpoints.
Closing the issue.

**Comment by oz-messapps** [comment]
Hi Thiery, 

Thanks for your answer, I'll check it after updates, hope after that it will be ok.
