### ISSUE TITLE
DateTimeInput converts to empty Object in ra-data-graphql-simple provider 

### ISSUE THREAD

**Issue by filozof6** [marmelab/react-admin#4218]
**What you were expecting:**
Dateinput should return the correct datetime string

**What happened instead:**
Variables that are connected to this input are {} in graphql mutation

**Steps to reproduce:**
Install ra-data-graphql-simple use any form that contains DateTimeInput and submit, network inspect the graphql request

* React-admin version:"^3.1.1"
* Last version that did not exhibit the issue (if applicable):
* React version: "^16.12.0"
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by ThieryMichel** [comment]
Thanks for the issue.
