### ISSUE TITLE
add successMessage to override deleted too

### ISSUE THREAD

**Issue by sfenig** [marmelab/react-admin#4219]
**Is your feature request related to a problem? Please describe.**
successMessage is a simple solution to notification overrides for create and edit, but doesn't exist for delete
**Describe the solution you'd like**
A way to override delete success message.  I guess it would have to be in Edit to pass through to delete for the default toolbar case

**Describe alternatives you've considered**
considered fixing it through translations, but we really don't have a need for translations at this point.  This is the only thing driving that, and doesn't seem like the right solution.

**Additional context**

**Comment by ThieryMichel** [comment]
Added as a possible enhancement.
For now, you could change the delete notification by adding your own custom DeleteButton. You can then pass the notification you like to the useDelete hook.

**Comment by fzaninotto** [comment]
Fixed by #5310
