### ISSUE TITLE
add successMessage to override "element deleted"

### ISSUE THREAD

**Issue by pfenig** [marmelab/react-admin#4220]
**Is your feature request related to a problem? Please describe.**
successMessage is a simple solution to notification overrides for create and edit, but doesn't exist for delete
**Describe the solution you'd like**
A way to override delete success message.  I guess it would have to be in Edit to pass through to delete for the default toolbar case

**Describe alternatives you've considered**
considered fixing it through translations, but we really don't have a need for translations at this point.  This is the only thing driving that, and doesn't seem like the right solution.

**Comment by ThieryMichel** [comment]
duplicate of #4219
