### ISSUE TITLE
[Documentation] WithPermissions not in doc and not in upgrade.md

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#4232]
**What you were expecting:**

I am reading https://github.com/marmelab/react-admin/blob/master/UPGRADE.md and there is nothing about `WithPermissions` being changed in v3.

It use to exist in v2: https://github.com/marmelab/react-admin/blob/v2.6.4/docs/Authorization.md#restricting-access-to-content-in-custom-menu

It is still present in v3, but without any documentation API to it.

Should it still be used or should we installed rewrite where we used it and use new hook?

**What happened instead:**

`authProvider.getPermissions` was always returning undefined permissions even if the response from the API was a success with an array of many permissions

https://stackoverflow.com/questions/59408349/upgrade-react-admin-v2-to-v3-permissions-is-always-empty-and-context-is-not-con/59559307#59559307

* React-admin version: 3.1.0
* Last version that did not exhibit the issue (if applicable): 2.6.4

**Comment by ThieryMichel** [comment]
Actually, this is a bug, WithPermissions should still works as before.

**Comment by ThieryMichel** [comment]
Seems like this issue depends on the implementation of your authProvider.
The WithPermissions hook still work and return the value resolved by `authProvider.getPermissions` .
Do note that permissions will be undefined until the promise resolve.
Please post your `authProvider.getPermissions` implementation.

**Comment by fzaninotto** [comment]
WithPermissions is still there (so we don't need to ask for upgrades). It's kept to avoid a breaking change, and also because the core uses it (in Resource.tsx). Cosider it an internal component in 3.0.

The right way to check permissions in userland in 3.0 is to use the `useAuthenticated` and `usePermissions` hooks.
