### ISSUE TITLE
Query params change after saving resource

### ISSUE THREAD

**Issue by go1dfish** [marmelab/react-admin#4234]
**What you were expecting:**
In my setup I have a side dialog to create a resource, so that the list is always displayed. If I change the query params (e.g. rows per page), then create a resource and save, the query params should still be there.

**What happened instead:**
The query params were removed.

**Steps to reproduce: / Related code:**
I have an example here: https://codesandbox.io/s/react-admin-bug1-v0zex

1. View posts
2. Change rows per page to 25. Note query params.
3. Click "Add Station"
4. Fill in form and save
5. All query params are removed

**Environment**

* React-admin version: 3.1.1
* React version: 16.12.0

**Comment by ThieryMichel** [comment]
Thanks for the issue

**Comment by fzaninotto** [comment]
This is not a bug: the query params aren't displayed in the List url after redirection, but they are kept in the Redux store and do apply. In your test scenario, even though the url doesn't show perPage=25 after save, the list pagination does have a perPage of 25.

**Comment by go1dfish** [comment]
I realize the problem was in my app I was refreshing the data based off the query params. When I instead grabbed those values from the redux store it worked. Thanks for looking into it!
