### ISSUE TITLE
material-ui-pickers v3.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4235]
For anyone who is interesting, I made a version of material-ui-pickers compatible with react-admin v3.
https://github.com/vascofg/react-admin-date-inputs/issues/42

You can try it directly in your package.json with:

`"react-admin-date-inputs": "WiXSL/react-admin-date-inputs#mui-pickers-v3",`

And send me feedback if you want.

**Comment by fzaninotto** [comment]
Please open a Pr to add it to the ecosystem doc!

**Comment by WiXSL** [comment]
Ok.
