### ISSUE TITLE
[RFC] useResource

### ISSUE THREAD

**Issue by CarsonF** [marmelab/react-admin#4243]
**Is your feature request related to a problem? Please describe.**
I see a handful of props passed around to controllers/views describing the resource configuration. `basePath`, `resource`, `hasCreate`, etc. They are passed through multiple layers.

**Describe the solution you'd like**
Putting these in a context would allow them to not have to be passed around. This seems like a good solution as the values are all determined in one place and read only.
```ts
export interface ResourceContextType<Options = object> {
    basePath: string;
    name: string; // or resource
    options: Options;
    hasList: boolean;
    hasEdit: boolean;
    hasShow: boolean;
    hasCreate: boolean;
}

// Context, Provider, Hook omitted
```
Usage:
```ts
const { basePath, name, hasCreate } = useResource();
```

The `Provider` would be used right inside of `Resource`.

---

I'm not sure what's considered a BC break here, but I think we could still pass those props to the controllers/views during a transition period. They would be ignored in our components since we would pull the values from the context/hook.

**Comment by fzaninotto** [comment]
`basePath` does not come from the Resource defined by the user, and the other props aren't passed down much. In fact, the only data passed around a lot is `basePath`, so perhaps a `useBasePath` is a better idea?

That being said, I'm not fond of multiplicating the contexts. I think it obfuscates part of the API of components. 

But that's just my 2c.

**Comment by CarsonF** [comment]
Actually `basePath` could be pulled from `useRouteMatch()`
```ts
const basePath = useRouteMatch()?.path ?? '';
```

----

> That being said, I'm not fond of multiplicating the contexts. I think it obfuscates part of the API of components.

I think context hooks are a much easier way to access and handle this information. 
When we are declaring resources what we mean is: "Here's my resource and here's what it can do. Anything down the tree can use this info IF it helps them."
This sounds much nicer than "here's all these props that I need to pass around even though I don't directly use them".

Think about all the places we handle `hasList`:
- useCreateController
- useEditController
- useListController
- useShowController
- CreateActions
- Edit
- EditActions
- Show
- ShowActions
- List

All of those places (depending on what they are) have:
- The TypeScript definition
- The PropType definition
- The need to sanitize the prop out

~10 places * ~3 ways to handle * 7 resource props = 210 usages
All of those could go away by using a context instead.

What happens if we want to add something else like `hasPreview` and how many places this new property needs to be handled? With a context it's just defining the property and and setting the value. 2 places plus where-ever it's actually needed.

In my mind, this information is no different than `location`, `history`, `theme` - all of which have contexts/hooks. Even `react-router` is now favoring context hooks instead of prop injection and most of those use-cases are only one level deep.

Sorry if this comes off strong I don't mean it to be. Thanks for reading and considering ❤️

**Comment by fzaninotto** [comment]
useRouteMatch will yield a different value when inside a Show or Edit component, so the context should be initialized within Resource. 

Your explanation is pretty convincing. The only drawback is that, as we need to keep backwards compatibility in the 3.x branch, we'll need to keep the PropTypes and sanitization anyway.

If we decide to proceed with this one, I will really start to benefit the codebase in 4.0, when we remove the `hasList`-like injected props.

**Comment by CarsonF** [comment]
> useRouteMatch will yield a different value when inside a Show or Edit component, so the context should be initialized within Resource.

Ah of course. Good catch.


> Your explanation is pretty convincing. The only drawback is that, as we need to keep backwards compatibility in the 3.x branch, we'll need to keep the PropTypes and sanitization anyway.
> 
> If we decide to proceed with this one, I will really start to benefit the codebase in 4.0, when we remove the `hasList`-like injected props.

Unfortunately yes. But by adding the context now we can give a deprecation notice and an upgrade path.

This is the concern I had in the OP though. Are we expecting users to be able to customize these values at the controller level?
```tsx
<Resource name="users" list={UserList} create={UserCreate} />

const UserList = props => (
  <List
    {...props}
    // overrides what resource defines (and potentially what's stored in context)
    hasCreate={false}
  />
);
```
It's one thing to handle & ignore hasCreate prop in `List` and just use the value from context. It's another to accept it over what's given in context.

---

Another option could be to provide users an ability to opt-in to the new props/context. By opting in we could skip passing all props that can be accessed via a hook (resource, auth, routing, permissions).
This is a bit more **forward** but also more **holistic**. With the React community and you guys moving towards context & hooks over render props. This would allow a smooth and at-will upgrade path for users and allow us to drop all of those props in v4.

Perhaps:
```tsx
<Admin
  noContextProps={true} // opt in globally
>
  <Resource name="users" />
  <Resource
    name="users"
    noContextProps={false} // override per resource
/>
</Admin>
```
`noContextProps` would be false by default and the option would just be dropped or accepted & ignored in v4.

Thoughts?

**Comment by fzaninotto** [comment]
Having the ability to override `hasXXX` at the controller level was never requested, and I don't see a use case for it. As for opt in/opt out, I think we'd rather follow the react-router path: still inject the props in children, but children should ignore them and use the context instead. 

I don't want to add deprecation warnings now as we just asked users to follow a steep upgrade path for 3.0.

**Comment by CarsonF** [comment]
Ok sounds good. I'll start implementing.

**Comment by fzaninotto** [comment]
useResource has been implemented in `master` under another name, see https://github.com/marmelab/react-admin/blob/eb3c1acbf4ecc81793b8e790e11a6f84f9bdbc1b/packages/ra-core/src/core/useResourceDefinition.ts
