### ISSUE TITLE
Do not reload data after cache timeout.

### ISSUE THREAD

**Issue by WangLarry** [marmelab/react-admin#4245]
**What you were expecting:**

After cache timeout, LIST Page should reload data from provider.

**What happened instead:**

After cache timeout, then click one item of list page,  some items in LIST Page disappear 

**Steps to reproduce:**

Open reviews list page of Demo project in react-admin  examples folder, then after ten minutes(or change  'defaultCacheDuration' value in util/getFetchedAt.ts)  without click anything, click one item in list, the problem happened:  some  items disappear .

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: V3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by ThieryMichel** [comment]
Nice catch.
