### ISSUE TITLE
SelectArrayInput - validation text is not red wen used with ReferenceArrayInput

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#4248]
validation text/label on SelectArrayInput is not red wen used with ReferenceArrayInput

RA version: 3.1.1

![2020-01-06  9 14 43](https://user-images.githubusercontent.com/488136/71804975-483cdd80-3065-11ea-8390-5aaea1193e40.png)

repo to reproduce:
https://codesandbox.io/s/jolly-edison-fh1c6

steps to reproduce:
1) edit posts
2) go to misc.
3) remove tags to make it empty
4) you will see the validation error and label is not red, unlike the SelectArrayInput under it

![Jan-06-2020 09-12-14](https://user-images.githubusercontent.com/488136/71804984-4c68fb00-3065-11ea-87c9-1e1331273d43.gif)

**Comment by djhi** [comment]
Reproduced. Thanks!
