### ISSUE TITLE
Components exported twice

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4253]
Some components are exported twice, as default and as not default, I don't no if it's the idea.

- ArrayInput
- DatagridCell
- DateInput
- DateTimeInput
- FileField
- ImageField
- Labeled
- LoadingIndicator
- ReferenceArrayField
- ReferenceInput
- TextInput

- List, Edit, Show (exports its `useStyles` hooks)

**Comment by fzaninotto** [comment]
It's a relic of the time when we used HOCs. Now we shouldn't export them twice. Could you open A PR to remove the named exports?

**Comment by WiXSL** [comment]
Done!

**Comment by AleksandarFaraj** [comment]
I see other issues with Material UI icons. 

This component does a full include to '@material-ui/icons';
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/field/ReferenceField.js

It causes a build time.

**Comment by fzaninotto** [comment]
@AleksandarFaraj I'm surprised by what you say, as the material-ui documentation explains that both usages are supported:

![image](https://user-images.githubusercontent.com/99944/71877744-3b35f200-312a-11ea-8f12-9bfef7c7f3fa.png)

https://material-ui.com/components/icons/#usage

Can you double check that this is the cause of your slow build? There might be something wrong with your build settings.

**Comment by AleksandarFaraj** [comment]
I double checked, check the logs here.

I tried running parcel, and CRA. Parcel without any particular configs and CRA with option 2. No major differences.

https://github.com/AleksandarFaraj/rabug

Parcel is setup to run with logging, Line 6909-12439 are @material-ui/icons builds. Takes approx 40 seconds for this part to execute. https://github.com/AleksandarFaraj/rabug/blob/master/out.txt



![X](https://user-images.githubusercontent.com/4523129/71929512-0feaeb80-319a-11ea-857d-60433168c243.png)

**Comment by fzaninotto** [comment]
@AleksandarFaraj Thanks for the link and explanation. Would you like to open a PR to fix the issue with the icon import?

**Comment by WiXSL** [comment]
If this is true, there is a lot of usages of `@material-ui/core` than can be refactored.
I don't know if that's ok, I can PR those changes.
