### ISSUE TITLE
Remove the link to LoicMahieu/aor-tinymce-input (or explicit that it's broken on v3)

### ISSUE THREAD

**Issue by Rowern** [marmelab/react-admin#4264]
**Is your feature request related to a problem? Please describe.**
The linked package doesn't work anymore with v3.

**Describe the solution you'd like**
We created this simple component to use TinyMCE.
If you think it is good enough we can create a package for it (or maybe put it inside the doc).

It does rely on the lodash debounce otherwise the change are too frequent and the input becomes laggy as hell.

```js
import React, { useState } from 'react';
import { useForm } from 'react-final-form';
import { Editor } from '@tinymce/tinymce-react';
import * as _ from 'lodash';

const TinyMCEInput = ({ source, ...props }: { source: string }) => {
  const form = useForm();
  const firstInit = _.get(form.getState().initialValues, source, '');
  const [init] = useState(firstInit);

  const debouncedOnChange = _.debounce(text => {
    form.change(source, text);
  }, 500);
  return (
    <Editor
      init={{
        plugins: ['autoresize', 'lists link '],
        menubar: false,
        statusbar: false,
        toolbar:
          'undo redo | bold italic underline strikethrough | forecolor | link | removeformat ',
      }}
      initialValue={init}
      onEditorChange={content => {
        debouncedOnChange(content);
      }}
    />
  );
};

export default TinyMCEInput;
```

It might be a really bad way to do it, if you have any suggestion I'm all ears.

PS: Your tool is incredible! Thanks to the dev team!

**Comment by Luwangel** [comment]
Hi, thanks :) We worked a lot to release this v3 and we're glad you enjoy it.

I'll update the documentation by removing your package from the 3.x versions.

If you want help to upgrade your module, you could post your questions it inside the [React Admin channel on StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

Regards,
Adrien
