### ISSUE TITLE
optimistic rendering causing unexpected permissions redirect behaviour in v3.0 

### ISSUE THREAD

**Issue by pdiniz13** [marmelab/react-admin#4271]
This is the same issue as the one reported https://github.com/marmelab/react-admin/issues/4006

ISSUE DETAILS:
What you were expecting:
When an authProvider is supplied, Resources should be rendered only after the checkAuth function resolves.

What happened instead:
Resources are optimistically rendered before checkAuth resolves and then if the promise is rejected, the user is redirected to the login page
This would be a security hole as users get a peek before being kicked out. Agreed, in cases of dataProviders backed by authenticated API's, this would be less of an issue, but it still feels wrong.

Steps to reproduce:
see attached gif

Related code:
The following authProvider demonstrates the behaviour

export default {
    login: ({ username }) => {
        localStorage.setItem('username', username);
        // accept all username/password combinations
        return Promise.resolve();
    },
    logout: () => {
        localStorage.removeItem('username');
        return Promise.resolve();
    },
    checkError: () => Promise.resolve(),
    checkAuth: async () => {
        // added fake delay to simulate behaviour clearly
        await new Promise(resolve => setTimeout(resolve, 10000));
        return localStorage.getItem('username')
            ? Promise.resolve()
            : Promise.reject();
    },
    getPermissions: () => Promise.reject('Unknown method'),
};

The previous issue was closed because this wasn't really a security concern. But this is actually causing another problem, this extra requests that are getting fired are actually failing and trying to redirect the user. The extra redirect attempts are actually resetting the value of nextPathname.

**Comment by Luwangel** [comment]
Hi, and thanks for reporting this issue.

It seems that someone else already reported it. To make things easier for everyone, we prefer to centralize the discussions in only one thread.

So I'll close this issue and invite you to speak about your problem directly on the original issue: https://github.com/marmelab/react-admin/issues/4006.
