### ISSUE TITLE
classes not passed from AutocompleteInput to AutocompleteSuggestionList

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#4280]
**What you were expecting:**
I want to be able to configure the className of the Paper that the suggestions are placed in in AutocompleteSuggestionList.

**What happened instead:**
The classes props is not passed to AutocompleteSuggestionList.

**Steps to reproduce:**
I haven't created a Sandbox yet, but I got to this conclusion after looking at the sourcecode 

https://github.com/marmelab/react-admin/blob/f7ab33314b9d8252cbf23adf98379903c7b7e60e/packages/ra-ui-materialui/src/input/AutocompleteInput.tsx#L381-L392

and here's the reason that I expected a classes object to be passed to AutocompleteSuggestionList

https://github.com/marmelab/react-admin/blob/f7ab33314b9d8252cbf23adf98379903c7b7e60e/packages/ra-ui-materialui/src/input/AutocompleteSuggestionList.tsx#L51

**Related code:**
^^^

**Other information:**

**Environment**

* React-admin version: 3.1.2
* Last version that did not exhibit the issue (if applicable): 2.x
* React version: 16.12.0
* Browser: Chrome
* Stack trace (in case of a JS error): -

**Comment by Sklico** [comment]
Actually className or classes, or anything else could be passed to AutocompleteSuggestions through suggestionsContainerProps like that:

`<AutocompleteInput optionText="title" options={{suggestionsContainerProps: { className: classes.container }}} />`

I don't know if it's the right solution, but it works for me.

**Comment by jdemangeon** [comment]
Hello @christiaanwesterbeek! Did @Sklico response help you?

**Comment by mercurjl** [comment]
Is there something similar for the TextInput? I'm trying to style specific TextInputs based on a piece of state and I would like to use `classes` like material-ui traditionally would but it doesnt seem to work. 

Also the docs never talk about a plain `options` prop nor what can be passed down with it for AutocompleteInput or any other input unless I'm not looking in the right place

**Comment by djhi** [comment]
@mercurjl You should be able to pass a `classes` prop to almost any of react-admin components. Please open another issue with a codesandox showing what you tried. 

As for the documentation, if you think something is missing, please help us to make it better by submiting a pull request ?

**Comment by fzaninotto** [comment]
Fixed by #5393
