### ISSUE TITLE
react-admin not sorting 

### ISSUE THREAD

**Issue by Ongeziwe-Mbana** [marmelab/react-admin#4290]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(http://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.
![image](https://user-images.githubusercontent.com/44267829/72418216-14f40000-3783-11ea-8d61-bd181c18f444.png)
![image](https://user-images.githubusercontent.com/44267829/72418241-23421c00-3783-11ea-9c44-72abc9aba4a9.png)
I need to sort by email address but it's not sorting below is a code snippet: 
`import React, { Component } from 'react';
import { connect } from 'react-redux';
import { List, Datagrid, TextField, ShowButton } from 'react-admin';

class AdminList extends Component {
    constructor (props) {
        super(props);
    }

    render() {
        return(
            <List perPage={10000} {...this.props} bulkActions={false}>
                <Datagrid>      
                    <TextField label="Email Address" source="emailAddress" />
                    <ShowButton />
                </Datagrid>
            </List>
        );
    }
}

function mapStateToProps(state) {
    return {};
}

export default connect(mapStateToProps)(AdminList);`

**Comment by djhi** [comment]
This is most probably an issue with your API. If you disagree, please share a codesandbox showing the issue. Use https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple as your template

**Comment by fzaninotto** [comment]
No news for some time, closing.
