### ISSUE TITLE
Passing "dense={false}" to a custom Menu does not affect the dashboard MenuItem

### ISSUE THREAD

**Issue by guilleironhack** [marmelab/react-admin#4296]
**What you were expecting:**
When creating a custom `Menu` with prop `dense={false}`, I expect all the menu elements not to have the dense properties

**What happened instead:**
The dense prop is not passed to the `DashboardMenuItem` and therefore it's not affected

**Steps to reproduce:**
 - Add a `Dashboard` to an app
 - Create a custom `Menu` with `dense={false}`
 - Add the custom `Menu` to the `Layout`
 

**Related code:**
https://codesandbox.io/s/mystifying-stallman-e8brq

**Other information:**

**Environment**

* React-admin version: v3.1.2
* React version: 16.9.0
* Browser: Chrome 79.0.3945.117

**Comment by djhi** [comment]
Reproduced on the codesandbox. Thanks! This is weird though, it should have been fixed by #4241

**Comment by djhi** [comment]
Just noticed that #4241 was merged on `next` so this is fixed but will only be available in `3.2.0`
