### ISSUE TITLE
React Admin Notification third param as seconds has no effect. 

### ISSUE THREAD

**Issue by heyaj19** [marmelab/react-admin#4298]
**What you were expecting:**
The notification to stay as long as the number of seconds added in the third param
**What happened instead:**
The notification still uses the default timer and auto hides
**Steps to reproduce:**
I imported 
import { useNotify,useSafeSetState} from "react-admin";
const notify=useNotify();
notify("An email has been sent to you. Please check your SPAM for the email.",'info',500000);

**Related code:**
const notify=useNotify();
notify("An email has been sent to you. Please check your SPAM for the email.",'info',500000);

The code box on the post page has a test notification button 

https://codesandbox.io/s/great-hill-hm4zk

```
const notify=useNotify();
notify("An email has been sent to you. Please check your SPAM for the email.",'info',500000);

```

**Environment**
Dev
* React-admin version:3.1.2
* Last version that did not exhibit the issue (if applicable):
* React version:16.12.0
* Browser: Firefox/Chrome
* Stack trace (in case of a JS error):

**Comment by heyaj19** [comment]
Also created a sandbox on the Post page

https://codesandbox.io/s/great-hill-hm4zk

**Comment by djhi** [comment]
Where have you seen that `notify` accept a duration as its third argument ? [Documentation](https://marmelab.com/react-admin/Actions.html#handling-side-effects-in-usedataprovider) explain it accept an option object as the third argument, which are options sent to the `translate` function.

Marking this as a documentation issue to clarify the hook usage and an enhancement request to allow customizing the notification duration as this is not possible currently.

**Comment by fzaninotto** [comment]
Note that the implementation of the enhancement is very easy: add the `autoHideDuration` param expected by the `notificationActions` action creator to the `useNotify` arguments. I'm marking it as a "good first issue".
