### ISSUE TITLE
NullableBooleanInput doesn't seem to work

### ISSUE THREAD

**Issue by dryhten** [marmelab/react-admin#4299]
**What you were expecting:**
`NullableBooleanInput` to show Yes/No if the value in source is true/false.

**What happened instead:**
It doesn't show anything, it complains about having `undefined` instead of true/false:
```
Material-UI: you have provided an out-of-range value `undefined` for the select (name="active") component.
Consider providing a value that matches one of the available options or ''.
The available values are ``, `false`, `true`.
```

**Steps to reproduce:**
Go here https://codesandbox.io/s/fervent-violet-4mhkw
Click on one user, check console message. Also check that `BooleanInput` is showing correct value.

**Comment by dryhten** [comment]
Btw if anyone else is experience this issue you can go around it if you create your own `NullableBooleanInput` component like so
```
const MyNullableBooleanInput = ({ source, label, record }) => {
  const getStringFromBoolean = value => {
    if (value === true) return "true";
    if (value === false) return "false";
    return "";
  };

  const value = getStringFromBoolean(record[source]);
  const options = {
    SelectProps: {
      value
    }
  };
  return (
    <NullableBooleanInput label={label} source={source} options={options} />
  );
};
```

Full example here https://codesandbox.io/s/affectionate-ardinghelli-j28uv

Notice that null doesn't work either. Doing this change in `ra-ui-materialui/src/input/NullableBooleanInput.tsx` 

```
<MenuItem value=" ">{translate('ra.boolean.null')}</MenuItem>
``` 

And then updating the `getStringFromBoolean` to return `" "` at the end seems to do the trick.

**Comment by fzaninotto** [comment]
Confirmed and reproduced, thanks or the report.

**Comment by fzaninotto** [comment]
weird, it works on the simple example but not on your CodeSandbox...

**Comment by fzaninotto** [comment]
Nevermind, I found the issue

**Comment by dryhten** [comment]
If it makes any difference I tracked it down to https://github.com/marmelab/react-admin/commit/739849025ee57fdc2095817291c085d1772c52fa

But the `useInput` hook was not straightforward to read so stopped investigating :)
