### ISSUE TITLE
Default App loading view does not center vertically on screen.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4302]
To solve it I use the `loader-container` css class from the demo.
```jsx
<Admin
     loading={() => <Loading className="loader-container"/>}
     ...
>
```
Sandbox: https://codesandbox.io/s/mystifying-dirac-lo5m1
Note: You have to enlarge the sandbox frame in order to see it.

![Screenshot of mystifying-dirac-lo5m1 - CodeSandbox](https://user-images.githubusercontent.com/8268610/72530915-26a2d980-384f-11ea-9a75-3bee02899666.jpg)

Using version 3.1.2.

**Comment by djhi** [comment]
Confirmed. Thanks

**Comment by manishsundriyal** [comment]
@fzaninotto @djhi Can I work on this?

**Comment by djhi** [comment]
@manishsundriyal Please do ! :)

**Comment by manishsundriyal** [comment]
@djhi Please review and merge https://github.com/marmelab/react-admin/pull/4686
