### ISSUE TITLE
Not synchronize data in redux

### ISSUE THREAD

**Issue by WangLarry** [marmelab/react-admin#4310]
**What you were expecting:**

When  submit  form to update data, which will use "useMutation" , then through DataProvider.
Data in "resources" key of redux can be changed successfully. But it do not update data inside "customQuery" .

**What happened instead:**

Should synchronize data inside  two key or reload "Custom Query".

**Steps to reproduce:**

Trace in  redux devtools.

**Environment**

* React-admin version: V3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by WangLarry** [comment]
I can't see any logic about  synchronize 'resources' and 'customQueries'  in code.

**Comment by WangLarry** [comment]
I custom layout and mix some material-ui code, so it is not easy to put into codesandbox.

Basic idea:  total window is split to two part , in left pane I  create tree list using 'useGetList(which cache data in 'customQueries' key of redux), right pane is Create or Edit component.  When submitting form in right pane, it will update 'resources' data. But left pane do not refresh.

Trace in redux devtools, can not any update 'customQueries' actions.

**Comment by djhi** [comment]
We need a codesandbox or a github repository which reproduce the issue.

**Comment by WangLarry** [comment]
Use 'useListControler' function instead of 'useGetList', it is OK!

useGetList save data in 'customQueries',  which do not synchronize data in 'resources'.

![excalidraw-20201181182 (2)](https://user-images.githubusercontent.com/5869244/72658660-de222200-39ee-11ea-88ca-63aabe9c19c8.png)

**Comment by fzaninotto** [comment]
You can [Customize the Redux action](https://marmelab.com/react-admin/Actions.html#customizing-the-redux-action) dispatched by a dataProvider hook. Choose any of the actions used internally by react-admin (e.g. `CRUD_GET_LIST`) to have the regular Redux store updated upon action success.
