### ISSUE TITLE
Demo code sandbox provided in react-admin landing page has error 

### ISSUE THREAD

**Issue by alixdeschamps** [marmelab/react-admin#4323]
**What you were expecting:**
This link https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple in the react-admin landing page to provide a sandbox without errors

**What happened instead:**
The code sandbox prints the error "Failed to read the 'localStorage' property from 'Window': Access is denied for this document."

**Steps to reproduce:**
The landing page https://marmelab.com/react-admin/ provides a link to a code sandbox https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple . 

This link is a clickable image under "Get started in minutes" 
![Screenshot from 2020-01-20 10-56-12](https://user-images.githubusercontent.com/9588479/72717117-c0ca9080-3b73-11ea-9114-f562583cfe53.jpg)

The code sandbox prints the error "Failed to read the 'localStorage' property from 'Window': Access is denied for this document."
![Screenshot from 2020-01-20 10-59-12](https://user-images.githubusercontent.com/9588479/72717232-ebb4e480-3b73-11ea-968f-128a4b666287.png)

Other information:
Both code sandbox console and chrome console mention an error during service worker registration 
![Screenshot from 2020-01-20 11-10-30](https://user-images.githubusercontent.com/9588479/72718078-83ff9900-3b75-11ea-8d1e-2a9b916b24f7.png)

**Environment**
Chrome Version 79.0.3945.117 (Official Build) (64-bit)
Ubuntu 18.04.3 LTS

**Comment by fzaninotto** [comment]
Are you using incognito mode/private browsing?

**Comment by fzaninotto** [comment]
Also, a simple search on StackOverflow shows that you may have too conservative privacy settings in Chrome.

https://stackoverflow.com/a/44069936/1333479

**Comment by alixdeschamps** [comment]
Ha yeah, that was the problem. Thanks!
