### ISSUE TITLE
Documentation: FAQ refers to aor-dependent-input

### ISSUE THREAD

**Issue by elsni** [marmelab/react-admin#4324]
aor-dependent-input does not seem to work with the current version of react-admin and leads into an error:

> Module not found: Can't resolve 'admin-on-rest/lib/mui/form/FormField' in '<my local project path>\node_modules\aor-dependent-input\lib'

The problem: aor-dependent-input is mentioned on the FAQ page https://marmelab.com/react-admin/FAQ.html. What can be used instead  aor-dependent-input?

**Comment by djhi** [comment]
See https://github.com/marmelab/react-admin/blob/2.x/UPGRADE.md#aor-dependent-input-was-removed. Marking this as a documentation issue as we should update the FAQ

**Comment by djhi** [comment]
You should also read the documentation: https://marmelab.com/react-admin/Inputs.html#linking-two-inputs
