### ISSUE TITLE
Example code in documentation does not work

### ISSUE THREAD

**Issue by elsni** [marmelab/react-admin#4329]
On this documentation Page
https://marmelab.com/react-admin/CreateEdit.html#customizing-the-form-layout
The Example code in subsection "formClassName" does not work: makeStyles() is undefined.

**Comment by fzaninotto** [comment]
I pushed the fix to master by mistake. I've reverted 3355f1d5 in c32471d4, and I'm reopening this issue to propose the fix in a PR instead.
