### ISSUE TITLE
Extending data providers in react-admin v3 with typescript

### ISSUE THREAD

**Issue by g3n35i5** [marmelab/react-admin#4340]
I'm not sure if this is a bug or a wrong implementation on my part. I have already described the problem in detail on  [stackoverflow](https://stackoverflow.com/questions/59855908).
For this reason I will give only a shortened description here.

**What you were expecting:**
I want to extend the simple rest provider with my own update method.

**What happened instead:**
I get the following error:
`Property 'update' does not exist on type '(apiUrl: any, httpClient?: ((url: any, options?: Options | undefined) => Promise<{ status: number; headers: Headers; body: string; json: any; }>) | undefined) => DataProvider'.  TS2339`

**Steps to reproduce:**
I followed the steps as explained in the  [documentation](https://marmelab.com/react-admin/DataProviders.html#extending-a-data-provider-example-of-file-upload)

**Environment**

* React-admin version: 3.1.2
* React version: 16.12.0
* Browser: Chromium
* Stack trace (in case of a JS error):
```
Property 'update' does not exist on type '(apiUrl: any, httpClient?: ((url: any, options?: Options | undefined) => Promise<{ status: number; headers: Headers; body: string; json: any; }>) | undefined) => DataProvider'.  TS2339

   6 |         if (resource !== 'posts' || !params.data.pictures) {
   7 |             // fallback to the default implementation
>  8 |             return dataProvider.update(resource, params);
     |                                 ^
   9 |         }
  10 |         /**
  11 |          * For posts update only, convert uploaded image in base 64 and attach it to
```

**Comment by fzaninotto** [comment]
This is not  bug, check the documentation or wait for someone to give you a hand on StackOverflow.

**Comment by g3n35i5** [comment]
@fzaninotto First of all, thank you for your answer. Could you briefly explain to me why it is not a bug (or faulty or incomplete documentation) if I took the code from the documentation without any changes and it does not work?

**Comment by fzaninotto** [comment]
Sorry, you're right, the documentation is wrong. I'll mark it as a documentation bug.

**Comment by g3n35i5** [comment]
Great, thank you very much!
