### ISSUE TITLE
Multiple validation errors per field

### ISSUE THREAD

**Issue by archfz** [marmelab/react-admin#4348]
**Is your feature request related to a problem? Please describe.**
There are many cases where multiple validations exists for one field. There is currently only 
one way to display multiple errors for a single field: combining all the error translations into one translation.

```js
const errorTranslation: ValidationErrorMessageWithArgs = {
      message: 'validation.multiple_errors',
      args: {
        0: translate('validation.error1'),
        1: translate('validation.error2'),
        // ...
      },
    };

// Translation
{
  "validation": {"multiple_errors": "${0}${1}${2}${3}"}
}
```

Doing this is cumbersome and it also has the issue of not being able to display these errors as separate since they all render in the same tag. Since HTML is not currently supported for translation strings they cannot be displayed separately in any good way.

**Describe the solution you'd like**
`validate` and `validateAsync` for forms should allow to pass for each field array of string or array of ValidationErrorMessageWithArgs. The validation errors should render in separate html tags for better display and styling.

**Describe alternatives you've considered**
The alternative solution is described above but it's far from convenient.

**Additional context**
Version: 3.0.1

**Comment by fzaninotto** [comment]
Thanks for your suggestion. I think you should open this issue in the react-final-form tracker, as we rely on this library for form manipulation (and validation).
