### ISSUE TITLE
Tooltip not displaying properly

### ISSUE THREAD

**Issue by liviozanol** [marmelab/react-admin#4349]
**What you were expecting:**
Material-ui Tooltip should work with RA elements.

**What happened instead:**
Material-ui tooltip used enclosing some RA elements don't display properly. After a first mouseclick on the element the tooltip is displayed correctly.

**Steps to reproduce:**
Tried with a arrayinput and with a editbutton. I don't know the oter ones...

**Related code:**
The Edit Button from the tag list have a Tooltip:
https://codesandbox.io/s/objective-pasteur-b6dpv

**Comment by fzaninotto** [comment]
Confirmed, thanks for the issue.

The console shows the following warning:

> Warning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(Tooltip)`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://material-ui.com/r/caveat-with-refs-guide

For some reason, many material-ui components require that children do `forwardRef`. I don't know why, and it's cumbersome.

**Comment by wmwart** [comment]
Yes, I noticed that too. This happened with the Tooltip polse update material-ui ^ 4.8.3. I have to wrap my elements in an extra <div />

**Comment by fzaninotto** [comment]
@wmwart can you perhaps open an issue in the material-ui Issue tracker? It seems like a regression on their side.

**Comment by liviozanol** [comment]
> Yes, I noticed that too. This happened with the Tooltip after update material-ui ^ 4.8.3. I have to wrap my elements in an extra `<div />`

Perfect workaround!

**Comment by fzaninotto** [comment]
I'm reconsidering this. It's not a bug, it's the way the MUI `Tooltip` component works. [Their documentation says](https://material-ui.com/components/tooltips/#custom-child-element):

![image](https://user-images.githubusercontent.com/99944/75039385-d99ecc80-54b8-11ea-89d8-b6eff38a457a.png)

So it's your job to wrap the child of tooltip with a div or a fowardRef.

**Comment by NikitaVlaznev** [comment]
Here is my solution:
```

import Tooltip from '@material-ui/core/Tooltip';

const TooltipWrapper = React.forwardRef(({children, ...props}, ref) => (
    <div ref={ref}>{React.cloneElement(children, props)}</div>
));

const MyTooltip = ({children, ...props}) => (
    <Tooltip {...props}>
        <TooltipWrapper>{children}</TooltipWrapper>
    </Tooltip>
);

const Component = () => (
    <MyTooltip title="Some description" aria-label="add">
        <TextInput source="someField" />
    </MyTooltip>
)
```
