### ISSUE TITLE
General errors for form validation

### ISSUE THREAD

**Issue by archfz** [marmelab/react-admin#4350]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a general error area for a form that could contain error messages that are not related to a specific field but rather to the record or combination of the fields.

**Describe the solution you'd like**
Maybe the validation callback could support returning error messages for the empty string key or '_' and this would be recognized and displayed above/below the form.

```js
{'_': 'validation.verify_account'}
```

**Describe alternatives you've considered**
The alternative currently is to save these messages in a state value and render them manually besides the form. It would be nice to have support out of the box.

**Comment by fzaninotto** [comment]
Yep, marking this as an enhancement request

**Comment by fzaninotto** [comment]
Note: react-final-form does support global form errors, see https://final-form.org/docs/react-final-form/types/FormProps#validate

**Comment by fzaninotto** [comment]
This is now supported by react-hook form (https://github.com/react-hook-form/react-hook-form/pull/9758). We just need react-admin to have a special UI for displaying errors with the `root` path.

**Comment by fzaninotto** [comment]
We don't need this feature in our own projects, so the core team won't implement it. Besides, version 3 is in maintenance mode and will not receive new features. 

If you need this feature for one of your projects, please consider upgrading to the latest version of react-admin, or hiring a member of the core team to do it in your project.
