### ISSUE TITLE
Module error in demo app

### ISSUE THREAD

**Issue by willyyang** [marmelab/react-admin#4355]
**What you were expecting:**
using `node 12.12.0`, `yarn 1.7.0`

running `yarn run-demo`. Expected to work without issues.

**What happened instead:**
Seeing following error:
```
react-admin/node_modules/react-app-polyfill/node_modules/core-js/modules/es.string.pad-end.js
Module not found: Can't resolve '../internals/webkit-string-pad-bug'
```

**Comment by fzaninotto** [comment]
Can't reproduce on master with node v12.14.1 and yarn 1.21.1. This is probably a problem in your setup.

Also, `yarn run-demo` isn't something we document. To run the demo, use the `make` commands:

```sh
make install
make build
make run-demo
```
