### ISSUE TITLE
Unable to access custom routes with resource permissions when not authenticated

### ISSUE THREAD

**Issue by zeppelin** [marmelab/react-admin#4357]
**What you were expecting:**
A custom route, like `/forgot-password` should be accessible without permissions.

**What happened instead:**
Redirects to `/login` when not authenticated.

**Steps to reproduce:**
When `<Resource>`s are declared as
```tsx
<Admin customRoutes={[✂️]}>
  {(permissions) => [
    <Resource />
  ]}
</Admin>
```
`getPermissions()` [gets executed](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRouter.tsx#L43-L45), which will, when it rejects, [call `logout()`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRouter.tsx#L78), making it impossible to tell React Admin to not to [redirect to the loginUrl](https://github.com/marmelab/react-admin/blob/89ac783fd9f961401d1c2e8d4ca4965053ed1d21/packages/ra-core/src/auth/useLogout.ts#L48) but stay on the custom route.

This is not the case when permissions are not exposed to the `<Resource>`s as [`initializeResources()` isn't called](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRouter.tsx#L43-L45), so this works [as advertised](https://marmelab.com/react-admin/Authorization.html):

```tsx
<Admin customRoutes={[✂️]}>
  <Resource />
</Admin>
```

**Related code:**
See above.

**Other information:**
This, apparently, wasn't the case with 2.x, so I decided not to reopen #3224.

**Environment**

* React-admin version: `3.0.3`
* Last version that did not exhibit the issue (if applicable): `2.???`
* React version: `16.12.0`
* Browser: Not browser-specific

**Comment by zeppelin** [comment]
Hm, I think I might have missed something, so I'll reopen when I can figure out what's off...

**Comment by RWOverdijk** [comment]
@zeppelin Did you figure this out? We're not able to create custom routes that don't require permission checks.

**Comment by Kmaschta** [comment]
@zeppelin Feel free to open a new issue, your feedback would be much appreciated :)

**Comment by zeppelin** [comment]
@RWOverdijk @Kmaschta thank you, I did figure it out!

**Comment by Kmaschta** [comment]
@zeppelin Nice!
Would you mind share with us what you figured, so that next readers might be helped a bit :)

**Comment by RWOverdijk** [comment]
Hahahaha, @zeppelin I wasn't just asking because I was curious :p I was asking because I'd like to know how you did it. You know, to help other people.

How did you solve it?

**Comment by zeppelin** [comment]
@RWOverdijk I was missing something. Returned wrong values from auth provider, as I recall...

**Comment by RWOverdijk** [comment]
That's not very helpful 😄 But thanks anyway!

**Comment by RWOverdijk** [comment]
![image](https://user-images.githubusercontent.com/781745/78886332-4b79a800-7a5e-11ea-859a-a6b0196239cf.png)

**Comment by zeppelin** [comment]
@RWOverdijk I honestly can't recall what was it exactly. It had to do with screwing up something in the auth provider, not at the route definitions.
