### ISSUE TITLE
Demo src/Layout/Login.tsx has an issue with useLocation type from react-router-dom

### ISSUE THREAD

**Issue by francoisruty** [marmelab/react-admin#4368]
**What you were expecting:**

I expect the demo app to work (let me log in)

**What happened instead:**

I have a typescript compilation error because examples/demo/src/Layout/Login.tsx makes a typed call to useLocation, but we don't have type for this function, so typescript compilation crashes

**Steps to reproduce:**

Build the demo app, start it and try to log in

**Related code:**

examples/demo/src/Layout/Login.tsx
line 87

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.1.3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

Here is my package.json:

{
  "name": "test-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.3.3",
    "@material-ui/icons": "^4.2.1",
    "prop-types": "^15.7.2",
    "ra-data-json-server": "^3.1.3",
    "ra-data-simple-rest": "3.1.0",
    "react": "^16.11.0",
    "react-admin": "^3.1.3",
    "react-dom": "^16.11.0",
    "react-redux": "^7.1.0",
    "react-router": "^5.1.0",
    "react-router-dom": "^5.1.0",
    "redux-saga": "^1.0.0",
    "react-scripts": "3.0.0"
  },
  "devDependencies": {
    "@types/classnames": "^2.2.9",
    "@types/jest": "^24.0.23",
    "@types/node": "^12.12.14",
    "@types/react": "^16.9.13",
    "@types/react-dom": "^16.9.4",
    "@types/react-router-dom": "^5.1.3",
    "@types/react-router": "^5.1.4",
    "source-map-explorer": "^2.0.0",
    "typescript": "^3.7.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by fzaninotto** [comment]
I can't reproduce the error on master. Besides, you haven't pasted the TypeScript error. 

Please give us more details by following the issue template.

**Comment by JulienMattiussi** [comment]
Unfortunatedly, without reproducing it and without some new informations, this issue is closed.
Feel free create an issue with detailled error and reproduction cases if you have it.
