### ISSUE TITLE
<ReferenenceArrayField> <ReferenceManyField> in shows sends an array of objects which contains ids to the get many instead of an array of ids.

### ISSUE THREAD

**Issue by Jasonsdeli** [marmelab/react-admin#4369]
I use a graphql backend. I control the whole backend and can formulate all the data in such a way the the ra-data-graphql-simple parses it and reads it fine. Which includes making the filters and pagination just plug in.  

It seems the ids query is different between List `<ReferenceField>` and the Show `<ReferenceManyField>,<ReferenceArrayField>`

When <ReferenceField> grabs a group of stores in this case. It passes a filter that looks like this 
filter: {ids: ["5b33cd58f0cabc140067de63", "5ba29a857f12561300102ac0", "5ba29cd57f12561300102b25"]}
Which I then parse on the backed and query the resulting ids and return them back as expected.  the show field looks like this. 
```
<ReferenceField source="storeId" reference="JssStore" link="show" label="Store">
                <TextField source="description" />
</ReferenceField>
```

When I do a similar call that pulls multiple in a reference-many or reference-array to the same JssStore using some thing like this in a show to show multiple stores a person maybe part of by id. 
`<ReferenceArrayField source="JssStore" reference="JssStore"><TextField source="description" /></ReferenceArrayField>`
the filter passed to it looks like this. 
filter: {ids: [{id: "5b33cd58f0cabc140067de63"},{id: "5ba29a857f12561300102ac0"}]}}

Which of course does not match what I expected. I would expect they would be the same since they are doing the same thing. Is this expected and i just misunderstand the documentation. I am wondering since id vs ids was not covered in the expected schema on graphql-simple and had to be inferred by the queries passed. Do i some how need to take both ways into account or is it a bug. 

**Environment**

* React-admin version: 3.13
* React version: 16.12
* Browser: only tried chrome based
* Stack trace (in case of a JS error):

**Comment by Jasonsdeli** [comment]
Seems to be in the difference in the way get_many and get_many_reference is built. Seems like in graphql simple should take into account if it is not a custom id reference. Again maybe i miss understand the difference between referencearrayfield and referencemanyfield. 

`case GET_MANY:
            return {
                filter: { ids: preparedParams.ids },
            };
        case GET_MANY_REFERENCE: {
            const parts = preparedParams.target.split('.');
            let variables = buildGetListVariables(introspectionResults)(
                resource,
                aorFetchType,
                preparedParams,
                queryType
            );
            variables.filter[`${parts[0]}Id`] = preparedParams.id;
            return variables;
        }`

**Comment by Jasonsdeli** [comment]
Going to move forward with creating my own copy of Reference Array Field that pull the ids from data like this to data the reference many does expect. 
`"JssStore": [
          {
            "id": "5b33c72b218c4f140098f77a"
          },
          {
            "id": "5ba29a797f12561300102aba"
          },
          {
            "id": "5ba29d397f12561300102b33"
          }
        ]
`

**Comment by otroboe** [comment]
I'm in the same situation. What's disturbing me is when I come from a DataGrid (click on row, load the form), it's not working, but when I reload the page, it's working.

**Comment by l3v1k** [comment]
Support for nested keys is Reference fields/inputs is needed, there are many cases when rest api returns array of reference objects instead of array of reference ids. Case with ReferenceArrayField can be solved using own field which will map objects to ids array and modify record then pass to underlying ReferenceArrayField, but case with ReferenceArrayInput with AutocompleteInput is harder to solve, because it fetches records and passes to options, so there must be one more wrapper over Autocomplete and so on.
