### ISSUE TITLE
ReferenceInput fails to display choices when multiple instances reference different resources on the same form

### ISSUE THREAD

**Issue by 09wattry** [marmelab/react-admin#4378]
**What you were expecting:**
Using ra-data-graphql-simple and apollo-boost to create a DataProvider, multiple ```<ReferenceInput>``` components populating and displaying on a single form.

**What happened instead:**
Only one  ```<ReferenceInput>``` displays it's data the second appears empty on click.

**Steps to reproduce:**
1) Setup default project
2) Add ra-data-graphql-simple and respective packages into the project.
3) Setup an Apollo client and create an instance of the DataProvider.
4) Make sure you have at least 3 data resources.
5) Create custom List and Create components.
6) In the Create component, ensure you reference two separate resources using ```<ReferenceInput>``` components.

**Related code:**

App setup
```jsx
import React, { useState, useEffect } from 'react';
import { Admin, Resource } from 'react-admin';
import { InvoiceList, InvoiceEdit, InvoiceCreate } from './invoices';
import { StatusList, StatusEdit, StatusCreate } from './statuses';
import { DebtorsList } from './debtors';
import { Book, Person } from '@material-ui/icons';

import buildGraphQLProvider from 'ra-data-graphql-simple';
import { ApolloClient, ApolloLink, InMemoryCache, HttpLink } from "apollo-boost";

const httpLink = new HttpLink({ uri: "https://my-secure-graphqlserver.com/graphql"});
const authLink = new ApolloLink((operation, forward) => {
  operation.setContext({
    headers: {
      'x-api-key': "mySuperSecret"
    }
  });

  return forward(operation);
});

const apolloClient = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache()
});

function App() {
  const [dataProvider, setDataProvider] = useState(null);

  useEffect(() => {
    (async () => {
      const dataProvider = await buildGraphQLProvider({
        client: apolloClient
      });

      setDataProvider(() => {
        return dataProvider;
      });
    })()
  }, []);

  if (!dataProvider) {
      return <div>Loading</div>;
  }

  return (
    <Admin dataProvider={dataProvider}>
      <Resource
        name="Invoice"
        list={InvoiceList}
        edit={InvoiceEdit}
        create={InvoiceCreate}
        icon={Book}/>
      <Resource 
        name="Debtor"
        list={DebtorsList}
        icon={Person}
      />
      <Resource name="Status" />
    </Admin>
  );
}
```

invoice.js
```jsx
export const InvoiceCreate = props => {
  return (
    <Create {...props}>
      <SimpleForm>
        <ReferenceInput label="Company" name="debtorId" source="id" reference="Debtor">
          <SelectInput optionText="name"/>
        </ReferenceInput>
        <TextInput source="price"/>
        <TextInput source="description" multiline/>
        <ReferenceInput label="Status" name="status" source="id" reference="Status">
          <SelectInput optionText="description"/>
        </ReferenceInput>
      </SimpleForm>
    </Create>
  );
}
```

**Other information:**
issue [#2309](https://github.com/marmelab/react-admin/issues/2309) is similar except it was referencing the same resource and I am referencing different resources. There is no error being logged or shown to screen. If I comment out on the second ReferenceInput then the first works as expected. I tried to reproduce this issue with the rest API in the tutorial and the bug did not occur. 

<img src="https://media.giphy.com/media/H4JlUZXuEq2rUGIOGA/giphy.gif" />

**Environment**

* React-admin version: 3.1.3
* "apollo-boost": ^0.4.7"
* "graphql": "14.6.0
 * "ra-data-graphql": "^3.0.2",
 * "ra-data-graphql-simple": "^3.1.2",
* React version: 16.12.0
* Browser: Chrome Version 79.0.3945.130 (Official Build) (64-bit) & Firefox Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by fzaninotto** [comment]
I don't understand what your video is supposed to show. If there is no company returned by your API, it's normal that the dropdown shows no choice. Besides, without all the code for your example, it's impossible to reproduce. 

Can you please fork the react-admin CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and tweak it so that it shows the bug you're mentioning?

**Comment by JulienMattiussi** [comment]
Unfortunatedly, without reproducing it and without some new informations, this issue is closed.
Feel free create an issue with detailled error and reproduction cases if you have it.
