### ISSUE TITLE
when expand button click, drop all like checkbox check all button

### ISSUE THREAD

**Issue by kimsuel** [marmelab/react-admin#4383]
First of all, sorry for my english.
Like the checkbox button, can the expand button expand all when the button is clicked?
I need to expand all when I click just one button.
I tried to make this feature but it doesn't work.
please answer about my question. Thank you.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

This is not something the core team needs, so we won't implement it ourselves. However, if someone contributes a PR for it, it'll be merged. 

So I'm turning this issue to an enhancement request and closing it, as we don't want to fill the issue tracker with wishes.
