### ISSUE TITLE
AppBar should not use secondary color

### ISSUE THREAD

**Issue by hotgen** [marmelab/react-admin#4396]
Currently `AppBar` uses secondary color as backgroud: 

`<MuiAppBar className={className} color="secondary" {...rest}>`

Material Design suggests:

> A secondary color provides more ways to accent and distinguish your product. Having a secondary color is optional, and should be applied sparingly to accent select parts of your UI.
> 
> Secondary colors are best for:
> 
> Floating action buttons
> Selection controls, like sliders and switches
> Highlighting selected text
> Progress bars
> Links and headlines

So I think `AppBar` should use primary color by default.

**Comment by fzaninotto** [comment]
We won't change the AppBar color in a minor release, as it would be a breaking change. However, we can easily make the AppBar color configurable via an additional prop. 

So I'm turning this into an enhancement request. Feel free to submit a PR for it!

**Comment by fzaninotto** [comment]
Fixed by #4479
