### ISSUE TITLE
UrlField should use Mui Link

### ISSUE THREAD

**Issue by hotgen** [marmelab/react-admin#4397]
Currently: UrlField -> a
Probably better: UrlField -> Link (from @material-ui/core)

https://material-ui.com/components/links/

**Comment by fzaninotto** [comment]
Why is it better? Can you explain the problem you have?

**Comment by djhi** [comment]
I think it would indeed be better regarding Typography and theming

**Comment by fzaninotto** [comment]
If anyone wants to tackle this one, please do. Without any involvement by the community, we'll close this issue in a couple months.

**Comment by fzaninotto** [comment]
Fixed by #4568
