### ISSUE TITLE
validation ist called on create before applying given record template?

### ISSUE THREAD

**Issue by elsni** [marmelab/react-admin#4400]
I was expecting that validation function on a TabbedForm is called on save.

But It is also called when a new empty form es rendered.
I prepopulated the record using the 2nd example (with Link) from here:
https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record

Problem: the structures are not applied. I use  a nested json as record template.
```
const emptyErlaubnisschein  = {
            "status": {},
            "vorbereitung": {
                "benachrichtigen": {},
                "enthaelt": {},
                "freimessen": {
                    "messungen": []
                }
            }
}
```
The validation breaks because i.e. vorbereitung.freimessen.messungen is undefined.

I use this code for the create button in ````ListActions````
```
export const CreateErlaubnisscheinButton = () => (
    <Button
        component={Link}
        to={{
            pathname: '/Erlaubnisscheine/create',
            state: { record: emptyErlaubnisschein }
        }}
    >
        <><IconAdd /><div>Neuen Erlaubnisschein erstellen</div></>
    </Button>
);


```

**Comment by fzaninotto** [comment]
Could you please follow the issue template and provide your react-admin version, as well as a link to a CodeSandbox reproducing the issue?

**Comment by fzaninotto** [comment]
No news for some time, closing.
