### ISSUE TITLE
Migration to latest version forces to rewrite the whole app which is not mentioned in upgrade guide

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#4401]
Hi, guys thanks for your effort on the latest version.

**Is your feature request related to a problem? Please describe.**
I was following [this upgrade guide](https://github.com/marmelab/react-admin/blob/next/UPGRADE.md) to migrate to the latest version. What frustrates me is the number of changes that are forced as side effect of moving from class-based components to function-based.

For example, I accessed locale directly from redux (mapStateToProps) in multiple places in my app, which are class-based component, but as a result of moving to `useLocale`, I have to refactor all of these places.

**Describe the solution you'd like**
I was expecting to see a warning or notice of some kind in the upgrade guide, to warn me about possibility of rewriting the whole app! It would've saved me a lot of time!

At [i18nProvider Signature Changed](https://github.com/marmelab/react-admin/blob/next/UPGRADE.md#i18nprovider-signature-changed) seems like a good place to warn about this issue.

All the best

**Comment by fzaninotto** [comment]
You don't have to rewrite the whole app. All the new hooks have a corresponding HOC with the same signature as in 2.x.
