### ISSUE TITLE
Notification error from server doesn't work correct

### ISSUE THREAD

**Issue by pavel-nano** [marmelab/react-admin#4402]
I have a problem with show notification.
The notification red block doesn't show or fasters hide.
I made a video with my problem https://yadi.sk/i/ILyky68X3h509Q

The problem in "react-admin": "3.0.0".

**Comment by fzaninotto** [comment]
Please follow the issue template.

**Comment by fnowacki** [comment]
I have the same problem, when form is invalid, notification disappear too fast.

**Comment by fzaninotto** [comment]
Again, please follow the issue template and provide sufficient code (or a Codesandbox) to reproduce the problem. We can't find bugs with so few details.

**Comment by fzaninotto** [comment]
No news for some time, closing.
