### ISSUE TITLE
RichTextInput: Wrong background color on light themes

### ISSUE THREAD

**Issue by jpsfs** [marmelab/react-admin#4404]
Hi,

When using the latest version of ra-input-rich-text (3.2.1) I've found an issue regarding the editor's background color:

![image](https://user-images.githubusercontent.com/1041209/74106942-1f779e80-4b63-11ea-8979-4aa994cbfea4.png)

When using the previous version (3.2.0), the problem didn't appear.

![image](https://user-images.githubusercontent.com/1041209/74106955-551c8780-4b63-11ea-9087-a0bd1d431591.png)

The problem seems related with the latest commit on this package, when adding support for theming:

![image](https://user-images.githubusercontent.com/1041209/74107012-bb090f00-4b63-11ea-8068-987621c7a5be.png)

My text is indeed black, but the background of the rich text input shouldn't have the same color as the text. Not sure what's the correct variable to use though.

**Versions:** 
react-admin: 3.2.1
ra-input-rich-text: 3.2.1

**Comment by JulienMattiussi** [comment]
You are write, it was a mistake
It will be fixed soon
Thanks
