### ISSUE TITLE
Camelcase in source props of <Input> components changes json attribute when creating form.

### ISSUE THREAD

**Issue by kayuapi** [marmelab/react-admin#4405]
Hi, I am not sure whether I should report this under bug or make it a proposed feature...

**What you were expecting:**

When doing a create operation on database, I expected that the source props of <Input> components determine the json attribute. For example, 
```javascript
<FormTab label="resources.choices.tabs.details" path="details">
    <NumberInput 
      source="priceRange"
    />
</FormTab>
```
I was expecting a json like this {priceRange: ...} to pass to backend when saving the form.

**What happened instead:**

the above produces a json like this {price_range: ...} when passed to the backend.

Thank you.

**Comment by djhi** [comment]
This is most probably done by your dataProvider. The react-admin components do not transform the source.

**Comment by kayuapi** [comment]
> This is most probably done by your dataProvider. The react-admin components do not transform the source.

I see, I thought I was specifying the attributes of the json I'm going to submit to the backend through the source, and react-admin transforms it from camelCase to snake_case, which is not what I wanted.

**Comment by djhi** [comment]
You are specifying them but it looks like your dataProvider is changing them. Please provide a codesandbox showing the issue or ask the question on Stackoverflow.

**Comment by kayuapi** [comment]
> You are specifying them but it looks like your dataProvider is changing them. Please provide a codesandbox showing the issue or ask the question on Stackoverflow.

Yup, it's the data provider... thanks!
