### ISSUE TITLE
Refactoring components to typescript

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#4406]
Hi guys
I would like to contribute to refactoring components to typescript, but I don't know where to start and I didn't want to work on something that someone else is already working on (ra-ui-matreial-ui ?).

Can you direct me to where I can start?

**Comment by fzaninotto** [comment]
See the discussion on #4403: we need help migrating the demo to TypeScript.

**Comment by developerium** [comment]
Awsome!
