### ISSUE TITLE
Clone button on SimpleFormIterator

### ISSUE THREAD

**Issue by robertleeplummerjr** [marmelab/react-admin#4408]
**Is your feature request related to a problem? Please describe.**
We have a need for having a clone button in the `SimpleFormIterator`, it would be super simple to add it within this component, and would demonstrate how easy and well build react-admin is.

**Describe the solution you'd like**
A small button that would clone the record clicked into the record below it, and have form data be added automatically.

**Describe alternatives you've considered**
I've tried extending and wrapping, but the UI is broken and I cannot extend the wrapped class, as it has been translated.

**Additional context**
This seems like something that a lot of projects could benefit from.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. We won't add this feature to the react-admin core - which we want to keep small. You can achieve what you describe it in user land, by implementing your custom form iterator. 

And if you think it's a common need, I encourage you to publish it as an open-source package that can plug to react-admin!

**Comment by chunich** [comment]
Was hoping for the same thing as well since `<CloneButton />` exists for the resource but not for the subsequent form-element-entry.
