### ISSUE TITLE
Cannot upload the file through the custom data provider (example of file upload)

### ISSUE THREAD

**Issue by thtan89** [marmelab/react-admin#4414]
I was following this example of the code to do the file upload but it always returned the error message "The submitted data was not a file. Check the encoding type on the form."

https://marmelab.com/react-admin/DataProviders.html

Extending a Data Provider (Example of File Upload)

![Screen Shot 2020-02-12 at 10 57 05 AM](https://user-images.githubusercontent.com/51570658/74299052-7c06d380-4d86-11ea-980a-cbb87db5954e.png)

I m using ra-data-drf provider & Django REST Framework API.
https://github.com/synaptic-cl/ra-data-drf

And use ImageInput to upload the file.

Here is the following code i m using:

```
//in WorkRequest.js
<ImageInput source="attachment" label="Attachment" accept="image/*">
   <ImageField source="src" title="title" />
</ImageInput>

//in addUploadFeature.js
const convertFileToBase64 = file => new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file.rawFile);

    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
});

const addUploadFeature = requestHandler => (type, resource, params) => {
    if (type === 'CREATE' && resource === 'WorkRequest') {
        // notice that following condition can be true only when `<ImageInput source="pictures" />` component has parameter `multiple={true}`
        // if parameter `multiple` is false, then data.pictures is not an array, but single object
        if (params.data.attachment && params.data.attachment.length) {
            // only freshly dropped pictures are instance of File
            const formerPictures = params.data.attachment.filter(p => !(p.rawFile instanceof File));
            const newPictures = params.data.attachment.filter(p => p.rawFile instanceof File);

            return Promise.all(newPictures.map(convertFileToBase64))
                .then(base64Pictures => base64Pictures.map((picture64, index) => ({
                    src: picture64,
                    title: `${newPictures[index].title}`,
                })))
                .then(transformedNewPictures => requestHandler(type, resource, {
                    ...params,
                    data: {
                        ...params.data,
                        attachment: [...transformedNewPictures, ...formerPictures],
                    },
                }));
        }
    }
    // for other request types and resources, fall back to the default request handler
    return requestHandler(type, resource, params);
};

export default addUploadFeature;

// in dataProvider.js
import { fetchUtils } from 'react-admin';
import drfProvider from 'ra-data-drf';
import addUploadFeature from './addUploadFeature';

const token = localStorage.getItem('token');
const Token = 'Token ' + token
const httpClient = (url, options = {}) => {
    if (!options.headers) {
        options.headers = new Headers({ Authorization: Token });
    }
    return fetchUtils.fetchJson(url, options);
}

const dataProvider = drfProvider('http://localhost:8000', httpClient)
const uploadCapableDataProvider = addUploadFeature(dataProvider);

export default uploadCapableDataProvider;
```

**Other information:**
The addUploadFeature function has this problem if console.log the function:

![Screen Shot 2020-02-12 at 3 08 40 PM](https://user-images.githubusercontent.com/51570658/74311086-9aca9180-4da9-11ea-916e-497d5c53d791.png)

**Environment**

* React-admin version: "react-admin": "^2.9.6",
* Last version that did not exhibit the issue (if applicable):
* React version: "react": "^16.10.2",
* Browser: https://marmelab.com/react-admin/DataProviders.html
* Stack trace (in case of a JS error):

Please rectify the issue, thank you.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by ENGR-MANSOOR** [comment]
> I was following this example of the code to do the file upload but it always returned the error message "The submitted data was not a file. Check the encoding type on the form."
> 
> https://marmelab.com/react-admin/DataProviders.html
> 
> Extending a Data Provider (Example of File Upload)
> 
> ![Screen Shot 2020-02-12 at 10 57 05 AM](https://user-images.githubusercontent.com/51570658/74299052-7c06d380-4d86-11ea-980a-cbb87db5954e.png)
> 
> I m using ra-data-drf provider & Django REST Framework API. https://github.com/synaptic-cl/ra-data-drf
> 
> And use ImageInput to upload the file.
> 
> Here is the following code i m using:
> 
> ```
> //in WorkRequest.js
> <ImageInput source="attachment" label="Attachment" accept="image/*">
>    <ImageField source="src" title="title" />
> </ImageInput>
> 
> //in addUploadFeature.js
> const convertFileToBase64 = file => new Promise((resolve, reject) => {
>     const reader = new FileReader();
>     reader.readAsDataURL(file.rawFile);
> 
>     reader.onload = () => resolve(reader.result);
>     reader.onerror = reject;
> });
> 
> const addUploadFeature = requestHandler => (type, resource, params) => {
>     if (type === 'CREATE' && resource === 'WorkRequest') {
>         // notice that following condition can be true only when `<ImageInput source="pictures" />` component has parameter `multiple={true}`
>         // if parameter `multiple` is false, then data.pictures is not an array, but single object
>         if (params.data.attachment && params.data.attachment.length) {
>             // only freshly dropped pictures are instance of File
>             const formerPictures = params.data.attachment.filter(p => !(p.rawFile instanceof File));
>             const newPictures = params.data.attachment.filter(p => p.rawFile instanceof File);
> 
>             return Promise.all(newPictures.map(convertFileToBase64))
>                 .then(base64Pictures => base64Pictures.map((picture64, index) => ({
>                     src: picture64,
>                     title: `${newPictures[index].title}`,
>                 })))
>                 .then(transformedNewPictures => requestHandler(type, resource, {
>                     ...params,
>                     data: {
>                         ...params.data,
>                         attachment: [...transformedNewPictures, ...formerPictures],
>                     },
>                 }));
>         }
>     }
>     // for other request types and resources, fall back to the default request handler
>     return requestHandler(type, resource, params);
> };
> 
> export default addUploadFeature;
> 
> // in dataProvider.js
> import { fetchUtils } from 'react-admin';
> import drfProvider from 'ra-data-drf';
> import addUploadFeature from './addUploadFeature';
> 
> const token = localStorage.getItem('token');
> const Token = 'Token ' + token
> const httpClient = (url, options = {}) => {
>     if (!options.headers) {
>         options.headers = new Headers({ Authorization: Token });
>     }
>     return fetchUtils.fetchJson(url, options);
> }
> 
> const dataProvider = drfProvider('http://localhost:8000', httpClient)
> const uploadCapableDataProvider = addUploadFeature(dataProvider);
> 
> export default uploadCapableDataProvider;
> ```
> 
> **Other information:** The addUploadFeature function has this problem if console.log the function:
> 
> ![Screen Shot 2020-02-12 at 3 08 40 PM](https://user-images.githubusercontent.com/51570658/74311086-9aca9180-4da9-11ea-916e-497d5c53d791.png)
> 
> **Environment**
> 
> * React-admin version: "react-admin": "^2.9.6",
> * Last version that did not exhibit the issue (if applicable):
> * React version: "react": "^16.10.2",
> * Browser: https://marmelab.com/react-admin/DataProviders.html
> * Stack trace (in case of a JS error):
> 
> Please rectify the issue, thank you.

Did u fix ur issue, can u please guide us??

**Comment by neps-in** [comment]
> Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).
> 
> This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.
> 
> So I'm closing this issue, and inviting you to ask your question at:
> 
> http://stackoverflow.com/questions/tagged/react-admin
> 
> And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

You guys don't want to give the answer out, because you guys are making money from it in the form of consulting. It would be actually self killing process, if there is no open documentation. For every question i see the same stupid advice.  Highly demotivating to use this framework.

**Comment by slax57** [comment]
@neps-in 
There **is** open documentation: https://marmelab.com/react-admin/DataProviders.html#handling-file-uploads

And there **are** ways you can get help for your react-admin questions:

- Community support: [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin)
- Community support: [Discord](https://discord.gg/B4G7AEQ3jm)
- Professional support: [React-Admin Enterprise Edition Support](https://marmelab.com/ra-enterprise/#support)

We simply made the choice to reserve Github Issues for bugs and feature requests only.

Also, I hope you'll come to understand that offering a paid support alternative is, also, a way for us to keep the react-admin project sustainable. If it weren't for those fine folks that bought a React Admin Enterprise subscription at some point, we wouldn't be able to have a full-time team working on maintaining and evolving this framework, and maybe the project would even be discontinued by now.

React-admin still lives thanks to people supporting it and contributing to it. We are grateful for them, and so should you.
