### ISSUE TITLE
make TabbedForm responsive

### ISSUE THREAD

**Issue by elsni** [marmelab/react-admin#4417]
TabbedForm is not responsive.  It makes me scroll sideways on small screens.
It would be better if tabbed form morps into an accordeon menu if screen is too small to display all tabs.
By accordion menu I mean that the tabs are displayed below each other instead of next to each other and that they use the whole screen width each.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. We won't implement this in react-admin. You can use the `useMediaQuery` hook to implement that in user land.
