### ISSUE TITLE
Boolean Input should support disabled property

### ISSUE THREAD

**Issue by mchaffotte** [marmelab/react-admin#4424]
**What you were expecting:**
Adding disabled property in BooleanInput component must disable it.

**What happened instead:**
But this option is ignored 

**Steps to reproduce:**
add this piece of code in your form: `<BooleanInput disabled />`

**Environment**

* React-admin version: 3

**Comment by fzaninotto** [comment]
It works if you pass `disabled` in the `options`: `<BooleanInput options={{ disabled: true }} />`. This is explained in the documentation:

![image](https://user-images.githubusercontent.com/99944/74815954-76673b80-52fa-11ea-9a50-a8ba07ed564a.png)

However, I agree that it's counterintuitive as it's working in `TextInput`. I'm turning this issue to an enhancement request.

**Comment by fzaninotto** [comment]
Fixed by #4443
