### ISSUE TITLE
Pagination is not working after browser history back

### ISSUE THREAD

**Issue by spoehner** [marmelab/react-admin#4428]
**What you were expecting:**
URL of pagination being
/#/resource?filter=%7B%7D&order=ASC&page=3&perPage=25&sort=id

**What happened instead:**
/#/resource/5?filter=%7B%7D&order=ASC&page=3&perPage=25&sort=id

**Steps to reproduce:**
1. Click "edit" on a List component
2. Navigate back using the browser button / mouse gesture / history.back()
3. Click any page or next button in pagination

**Related code:**
Nothing special with my List component:

```jsx
<List {...props}
    title="some resource"
    sort={{ field: "id", order: "ASC" }}
    perPage={25}
    filters={<Filters/>}
>
```

**Environment**
Google Chrome 80

* React-admin version: 3.1.3
* Last version that did not exhibit the issue (if applicable): unknown
* React version: 16.12.0
* Browser: Google Chrome 80
* Stack trace (in case of a JS error): no JS error

**Comment by fzaninotto** [comment]
I can't reproduce the bug you describe on master. Could you please fork the react-admin CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and tweak it so that it reproduces your problem?

**Comment by Limuyang1013** [comment]
meet same problem
