### ISSUE TITLE
Translation bug for translate("...", {smart_count: 5})

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#4438]
Not correctly using the smart-count parameter of the poliglot library.
If I understand correctly, then it is used to determine the singular or plural (bulk_actions: "1 selected ||||% {smart_count} selected"). If you use it to display the counter, then unexpected values arise related to localization.

In particular, for the Russian language: 
`translation("ra.action.bulk_actions", {smart_count: 5})
==> "1 выбрано"
`

**What happened instead:**

**Steps to reproduce:**
1. [Open codesandbox](https://codesandbox.io/s/immutable-wildflower-9m46y)
2. Select >4 rows

 propose a solution below.

I think such changes should be made for all translations where the text is used `%{smart_count}`

**Environment**

* React-admin version: 3.2.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for your report. 

I''m not sure I understand what you mean by

> I think such changes should be made for all translations where the text is used %{smart_count}

We're using polyglot as explained [in their doc](https://airbnb.io/polyglot.js/#pluralization), and it seems to work as advertised:

```js
import Polyglot from 'polyglot.js'

var polyglot = new Polyglot({locale: "cz"});
polyglot.extend({
  "num_foxes": "Mám %{smart_count} lišku |||| Mám %{smart_count} lišky |||| Mám %{smart_count} lišek"
})

document.getElementById("app").innerHTML = polyglot.t('num_foxes', { smart_count:5 });
// Mám 5 lišky
```

If this doesn't work for Russian, it's probably because of a bug in the Russian i18nProvider (which is not maintained here). 

So I'm closing this bug as it'q not related to the code we maintain. Feel free to add more details if you can prove that there is a bug in react-admin itself.

**Comment by wmwart** [comment]
@fzaninotto, error exactly with React-admin.
I already provided a codesandbox. Is this also not enough now?
We look at the same de documentation but read it differently. It is under your link that it says:

> Polyglot provides a very basic pattern for providing pluralization based on a single string that contains all plural forms for a given phrase. Because various languages have different nominal forms for zero, one, and multiple, and because the noun can be before or after the count, we have to be overly explicit about the possible phrases.
...
> In English (and German, Spanish, Italian, and a few others) there are only two plural forms: singular and not-singular.
> 
> Some languages get a bit more complicated. In Czech, there are three separate forms: 1, 2 through 4, and 5 and up. Russian is even crazier.
...

> polyglot.t() will choose the appropriate phrase based on the provided smart_count option, whose value is a number.

It follows that smart_count is a reserved special option that Poliglot,js needs in order to be able to select singular or plural from the transmitted string.
The fact that in your language this parameter correctly displays the number is a pleasant coincidence. However, there are a number of languages, including Russian, where this parameter displays what the library needs to correctly parse the string for translation.

The library uses interpolation to substitute values (the documentation section is slightly higher):

> Polyglot.t() also provides interpolation. Pass an object with key-value pairs of interpolation arguments as the second parameter.
> 
> polyglot.extend({
>   "hello_name": "Hola, %{name}."
> });
> 
> polyglot.t("hello_name", {name: "DeNiro"});
> => "Hola, DeNiro."

Now I understand what I mean?

**Comment by fzaninotto** [comment]
No, I still don't understand. Again, see the copied example from the Polyglot doc:

```js
var polyglot = new Polyglot({locale: "cz"});
polyglot.extend({
  "num_foxes": "Mám %{smart_count} lišku |||| Mám %{smart_count} lišky |||| Mám %{smart_count} lišek"
})
```

They are using `smart_count` in interpolation. In a language with more than 2 plurals. This is exactly what we do.

**Comment by wmwart** [comment]
Oh. look my codesandbox. All that is not forbidden is allowed. The example you give works. But it does not work as you expect (the counter shows) in all languages that Polyglot.js (end React-admin) provides. They indicate this in their documentation. There are a number of languages for which the line from the example will not show what is expected. The same thing happened with the counter of selected lines in the react admin for the Russian language. Other languages will face the same bug. Here are the source codes for the polyglot.js where these languages are indicated:
```
var russianPluralGroups = function (n) {
  var lastTwo = n % 100;
  var end = lastTwo % 10;
  if (lastTwo !== 11 && end === 1) {
    return 0;
  }
  if (2 <= end && end <= 4 && !(lastTwo >= 12 && lastTwo <= 14)) {
    return 1;
  }
  return 2;
};

var defaultPluralRules = {
  // Mapping from pluralization group plural logic.
  pluralTypes: {
    arabic: function (n) {
      // http://www.arabeyes.org/Plural_Forms
      if (n < 3) { return n; }
      var lastTwo = n % 100;
      if (lastTwo >= 3 && lastTwo <= 10) return 3;
      return lastTwo >= 11 ? 4 : 5;
    },
    bosnian_serbian: russianPluralGroups,
    chinese: function () { return 0; },
    croatian: russianPluralGroups,
    french: function (n) { return n > 1 ? 1 : 0; },
    german: function (n) { return n !== 1 ? 1 : 0; },
    russian: russianPluralGroups,
    lithuanian: function (n) {
      if (n % 10 === 1 && n % 100 !== 11) { return 0; }
      return n % 10 >= 2 && n % 10 <= 9 && (n % 100 < 11 || n % 100 > 19) ? 1 : 2;
    },
    czech: function (n) {
      if (n === 1) { return 0; }
      return (n >= 2 && n <= 4) ? 1 : 2;
    },
    polish: function (n) {
      if (n === 1) { return 0; }
      var end = n % 10;
      return 2 <= end && end <= 4 && (n % 100 < 10 || n % 100 >= 20) ? 1 : 2;
    },
    icelandic: function (n) { return (n % 10 !== 1 || n % 100 === 11) ? 1 : 0; },
    slovenian: function (n) {
      var lastTwo = n % 100;
      if (lastTwo === 1) {
        return 0;
      }
      if (lastTwo === 2) {
        return 1;
      }
      if (lastTwo === 3 || lastTwo === 4) {
        return 2;
      }
      return 3;
    }
  },
```

**Comment by wmwart** [comment]
github

**Comment by fzaninotto** [comment]
OK, so you are basically saying that the polyglot doc is wrong and that we should not use `smart_count` in interpolation?

If so, could you please open an issue on the Polyglot repo so that they acknowledge and fix the doc issue? That would confirm the problem. then, we'll fix it on the react-admin side.

**Comment by wmwart** [comment]
Good news, agreed)

**Comment by wmwart** [comment]
Here are some similar issues:
[https://github.com/airbnb/polyglot.js/issues/59](https://github.com/airbnb/polyglot.js/issues/59)
[https://github.com/airbnb/polyglot.js/issues/9](https://github.com/airbnb/polyglot.js/issues/9)
my issue:
[https://github.com/airbnb/polyglot.js/issues/142](https://github.com/airbnb/polyglot.js/issues/142)

**Comment by wmwart** [comment]
@fzaninotto, [confirmation from Poliglot.js](https://github.com/airbnb/polyglot.js/issues/142)
this is not a mistake Poliglot.js, this is a feature for russianPluralGroups().

> To fix you issue, I suggest to add same 3rd option:
> "выбран только 1 |||| %{smart_count} выбрано |||| %{smart_count} выбрано"

need to fix ra-language-russian)

**Comment by fzaninotto** [comment]
Thanks for taking the time to investigate this issue. I'm glad it's not a react-admin bug.
