### ISSUE TITLE
List view with delete button doesn't refresh list if API request fails

### ISSUE THREAD

**Issue by dinodeSimon** [marmelab/react-admin#4445]
**What you were expecting:**
With an undoable delete button on a list view if the delete API request fails the item which failed to be deleted should be added back to the list

**What happened instead:**
The item is pre-emptively removed from the list but when the API request fails an error notification is shown but the item isn't added back to the list. Pressing the reload list button brings it back. 

**Steps to reproduce:** and **Related code:**
https://codesandbox.io/s/icy-cache-77giw

This forked code sandbox has the data provider modified so that rejects delete requests to posts
```
if (name === "delete" && resource === "posts") {
      return Promise.reject("deletion error");
    }
```
It also has 2 delete buttons added to the posts list view. 
```
<DeleteButton label={"Undoable Delete"} />
<DeleteButton label={"Regular Delete"} undoable={false} />
```
Pressing the "Regular Delete" button shows the error notification and the item remains on the list as expected.
Pressing the "Undoable Delete" button removes the item from the list, then sends the API request which is rejected, the error notification is displayed but the item isn't added back to the list so the user is confused about what happened.

**Environment**

* React-admin version: 3.2.3
* Last version that did not exhibit the issue (if applicable): N/A

**Comment by djhi** [comment]
Reproduced. Thanks for the report

**Comment by djhi** [comment]
Can't reproduce anymore
