### ISSUE TITLE
ReferenceField with UUID

### ISSUE THREAD

**Issue by xero88** [marmelab/react-admin#4449]
I'm trying to use **ReferenceField with UUID** 

```
<ReferenceField source="customer" reference="customers">
  <TextField source="id" />
</ReferenceField>
```

In the API, customer field is an UUID (_fac9062f-2e20-41c6-a74a-d2d8871025a3_) : 

```
[
    {
        "id": "12a36bc8-85a7-46a5-9df5-15389eeffd96",
        "amount": 125.55,
        "customer": "fac9062f-2e20-41c6-a74a-d2d8871025a3"
    }
]
```
I looked in the console and instead of calling something like that : 

http://localhost:3000/customers?id=in.(fac9062f-2e20-41c6-a74a-d2d8871025a3)

It's calling something like that : 

http://localhost:3000/customers?id=in.(0=%5B&1=%22&10=-&11=2&12=e&13=2&14=0&15=-&16=4&17=1&18=c&19=6&2=f&20=-&21=a&22=7&23=4&24=a&25=-&26=d&27=2&28=d&29=8&3=a&30=8&31=7&32=1&33=0&34=2&35=5&36=a&37=3&38=%22&39=%5D&4=c&5=9&6=0&7=6&8=2&9=f)

# Note 

By the way, i'm using postgrest data provider, I don't know if this is correlated.

**Comment by djhi** [comment]
It looks like a bug in the postgrest data provider. You should open an issue on their repository
