### ISSUE TITLE
Not really a feature request but more of a support request through the community. I was wondering if we can start a Slack, Discord channel ?

### ISSUE THREAD

**Issue by heyaj19** [marmelab/react-admin#4451]
**Is your feature request related to a problem? Please describe.**
The big issue is stackoverflow responses take a long time. If we have a channel to ask questions to people who are active in the community we may have a better chance of faster replies?
**Describe the solution you'd like**
Slack, DIscord or anything like that. You can have multiple channels like questions, types of apis it works with etc?

**Describe alternatives you've considered**
Stackoverflow - not worth it

**Comment by fzaninotto** [comment]
Thanks for your suggestion. We've considered it in the past, and I still don't think it's a good solution.

1. A chat isn't searchable 
2. If there are not enough community contributions on StackOverflow, why would there be more on a chat?
3. Unanswered questions on a chat feel even more frustrating than on a forum-like site like stackoverflow
4. There are no ways to encourage people to do support in a chat (stackOverflow gamification does that).

So we still won't open a chat support.
