### ISSUE TITLE
A way to update the Admin data store without using dataProvider

### ISSUE THREAD

**Issue by heyaj19** [marmelab/react-admin#4452]
**Is your feature request related to a problem? Please describe.**
Using websockets to send data from my server to front end. I  want to make changes to the admin store from the data received from the websocket without having to force a fetch request.

**Describe the solution you'd like**
A solution would be to make available certain actions to update the admin store based on resource. Based on the request type
* Update - resource name, id, and data
* Insert - id/ids, data, count -- could be one could be multiple. This gets added to the current count. Top or Bottom - add to the tope of the store or bottom
*Delete -  id/ids, data, count -- could be one could be multiple. This gets subtracted from the current count.

**Describe alternatives you've considered**
Current solution initiate a fetch request on socket received using the useDataProvider hook.

**Comment by djhi** [comment]
We are still using redux so you should be able to dispatch actions yourself to update the stores. See https://github.com/marmelab/react-admin/tree/master/packages/ra-core/src/actions. This was done before with a saga in the `ra-realtime` addon package which has not been upgraded for v3 yet.
