### ISSUE TITLE
Make refreshView call in useDataProvider.performUndoableQuery optional

### ISSUE THREAD

**Issue by robert-armstrong** [marmelab/react-admin#4453]
**Is your feature request related to a problem? Please describe.**
I have stateful buttons and tag widgets on entities in list views. These controls use optimistic rendering which eventually triggers a full refresh [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useDataProvider.ts#L270) after the client change and server update. The refreshView call seems unnecessary for my use case and also causes the vertical scroll to jump. 

**Describe the solution you'd like**
A flag to disable the refreshView call. Perhaps like this:

```
{
            undoable: true,
            disableRefresh: true
            .....
}
```

**Describe alternatives you've considered**
I have a workaround by making my own dispatch call, but it currently has no error handling and I'd prefer to directly call useMutation.

**Additional context**
Looking for guidance on whether or not this makes sense and potential direction on how to implement. I can possibly offer a PR. Somewhat related, I'd also like to optimistically render and issue the server update simultaneously with no undo or notification. Notify would only occur on an error.

**Comment by fzaninotto** [comment]
This is somehow fixed by #4386. We don't do a full refresh anymore - just replaying the requests that were delayed while in optimistic mode. Besides, you can disable refetching using the new Application Cache feature.
