### ISSUE TITLE
List sort order flipped?

### ISSUE THREAD

**Issue by vysinsky** [marmelab/react-admin#4463]
**What you were expecting:**

When I set default `sort` for list as `{{ field: 'order', order: 'ASC' }}`. It will sort in ascendent order (e.g. from 1 to 4)

**What happened instead:**

It sorts in descendent order instead (e.g. from 4 to 1)

**Steps to reproduce:**

* have an field `order` that is number
* set `List` sort property to `{{ field: 'order', order: 'ASC' }}`
* reload page without any sorting

**Related code:**

This is my PagesList
```
import React from 'react'
import { Datagrid, List, TextField, NumberField } from 'react-admin'
import TruncateRichTextField from '../fields/TruncateRichTextField'

export const PagesList = (props: any) => (
  <List {...props} sort={{ field: 'order', order: 'ASC' }}>
    <Datagrid rowClick="edit">
      <NumberField source="order" />
      <TextField source="title" />
      <TextField source="slug" />
      <TruncateRichTextField source="content" />
    </Datagrid>
  </List>
)
```

This is the result: 
![image](https://user-images.githubusercontent.com/3693578/75613623-30974800-5b30-11ea-846b-eac03e2d9e60.png)

I would really expect `ASC` should go from 1 to 4 :-)

**Other information:**

- I am using `ra-data-firestore-client` 0.1.14

**Environment**

* React-admin version: 3.2.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.0
* Browser: Brave Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
The bug does not appear on the react-admin simple example. It's likely in th edata providr you're using. We do not maintain the `ra-data-firestore-client` in this repository. Please open an issue in their repository.
