### ISSUE TITLE
Changing the value to null and setting filter on a ReferenceArrayInput does not filter choices properly

### ISSUE THREAD

**Issue by FaizuddinEverest** [marmelab/react-admin#4466]
**What you were expecting:**

Changing the value of a `ReferenceArrayInput` from, let's say `1`, to `null` and changing the `filter` prop to not include `1` in the results should also remove `1` from choices.

**What happened instead:**

The choices still show `1` and it does not go away until you select a different choice. If you select `1`, the `1` never goes away.

**Steps to reproduce:**

I've provided a CodeSandbox link.
To reproduce the error:

1. Go to comments create page
2. Select a value for Post from the ReferenceArrayInput that I've added. Make sure the value is not `2` or `3` as those are used in the filter. I've shown the current value and filter right below this control.
3. Now, click on the "Add Filter" button next to the control which sets the value to `null` and the filter value to `{id: [2, 3]}`.
4. The value should now be `null` and filter should now be `{id: [2, 3]}`.
5. Click on the control to see the choices now. There will be three choices when there are only supposed to be two. The third one apart from 2 and 3 will be the one you selected before adding the filter.
6. Click on the value that you chose before adding the filter. Now, it's as if the value is selected and it does not matter that the results of the filtered choices do not include that value.

* Here's the sandbox link:
https://5kikk.csb.app/#/comments/create
https://codesandbox.io/s/sparkling-currying-5kikk

Here's a couple of screen captures of the bug:

When selecting an "invalid" choice:

![invalid](https://user-images.githubusercontent.com/47523926/75676892-39af2300-5cb0-11ea-8261-a7bd44b16319.gif)

When selecting a "valid" choice:

![valid](https://user-images.githubusercontent.com/47523926/75676899-3f0c6d80-5cb0-11ea-96d6-b28d9292b740.gif)

**Environment**

* React-admin version: 3.2.3
* Last version that did not exhibit the issue (if applicable): ~
* React version: 16.9.0
* Browser: Chrome
* Stack trace (in case of a JS error): ~

**Comment by JulienMattiussi** [comment]
I reproduced your issue.
Thanks for noticed it to us.
I tagged it as bug

**Comment by JulienMattiussi** [comment]
Here is a possible workaround based on your example : 
https://codesandbox.io/s/inspiring-murdock-3cyq0
