### ISSUE TITLE
How to display custom message on blank list

### ISSUE THREAD

**Issue by Eth3rnit3** [marmelab/react-admin#4472]
Hi, i search a way to add a custom message or image on list component when it empty.

Actually, is it possible to do this ?

Thank for answers

**Comment by fzaninotto** [comment]
Yes, it's possible: https://marmelab.com/react-admin/List.html#empty-page

**Comment by Eth3rnit3** [comment]
Thank you very much for your answer, I apologize for my lack of attention...

**Comment by sarcastic-verma** [comment]
> Thank you very much for your answer, I apologize for my lack of attention...

+1, had the same doubt. xD
