### ISSUE TITLE
Next Right Now Admin - Seek help/guidance for a Next.js (SSR) + GraphQL OSS boilerplate

### ISSUE THREAD

**Issue by Vadorequest** [marmelab/react-admin#4475]
I’m working on an OSS React Admin backoffice using Next.js and deployed on Zeit platform. 
See https://github.com/UnlyEd/next-right-now-admin/pulls

**The ultimate goal is to generate a whole backoffice automatically, by using GraphQL schema introspection.** 
Alternatively, (if “dynamically generated” backoffice doesn’t work out), the goal is to make a reusable boilerplate compatible with GraphQL (using GraphCMS as example).

- I could use some help from developers with experience in React Admin and/or API Platform Admin.
I’m currently stuck with API Platform Admin on https://github.com/api-platform/admin/issues/281
- I could use some guidance regarding GraphCMS localised fields
  - GraphCMS has built-in Localisation, for instance, the field "label" is accessible through `title` and `titleEN` (EN is default, and used as fallback if not specified), but also through `titleFR`. When using a list, it works fine.
```tsx
export const ProductList = (props): JSX.Element => {
  return (
    <List {...props}>
      <Datagrid rowClick="edit">
        {/*<TextField source="id" />*/}
        <TextField source="title" />
        {/*<ArrayField source="images"><SingleFieldList><ChipField source="id" /></SingleFieldList></ArrayField>*/}
        {/*<ReferenceArrayField source="imagesIds" reference="images"><TextField source="id" /></ReferenceArrayField>*/}
        <TextField source="customer.id" />
        <TextField source="price" />
        <TextField source="description" />
        <DateField source="updatedAt" />
      </Datagrid>
    </List>
  );
};
```
  - But, when editing a record using the Edit form, it doesn't work and fails because the field `title` isn't valid, `titleEN` should be used.
```tsx
export const ProductEdit = (props): JSX.Element => {
  return (
    <Edit {...props}>
      <SimpleForm>
        <TextInput source="status" />
        <DateInput source="updatedAt" />
        <DateInput source="createdAt" />
        <TextInput source="id" />
        {/*<ArrayInput source="images"><SimpleFormIterator><TextInput source="id" /></SimpleFormIterator></ArrayInput>*/}
        {/*<ReferenceArrayInput source="imagesIds" reference="images"><TextInput source="id" /></ReferenceArrayInput>*/}
        <TextInput source="customer.id" />
        <TextInput source="customer.id" />
        <TextInput source="price" />
        <TextInput source="title" />
        <TextInput source="description" />
      </SimpleForm>
    </Edit>
  );
};
```
  - You can see the live demo at https://nrn-admin.unly.now.sh/ and test for yourself. Any hint about how to resolve this?
- I could also use some guidance regarding assets-related stuff (CRUD operations). GraphCMS has a built-in assets system, based on https://www.filestack.com/. I've commented out the related fields because it made the whole app crash.

If you have some experience with either those tools and have time to share your feedback, that’d be awesome.

This OSS boilerplate is based on https://github.com/UnlyEd/next-right-now and benefits from quite a lot of automation (CI/CD deployments pipeline, TypeScript, E2E testing, built-in API (serverless), etc.). I believe it would be a great addition to both react-admin and api-platform/admin.

> I did not open a SO question, because I do not believe SO would be great for that kind of things

Related:
- https://github.com/api-platform/admin/issues/160
- https://github.com/marmelab/react-admin/issues/3751
- https://github.com/api-platform/admin/issues/282

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
