### ISSUE TITLE
Optimistic rendering on Lists with different permanentFilters

### ISSUE THREAD

**Issue by js-chris** [marmelab/react-admin#4486]
Hi,

I am having an issue with lists in different tabPanels. Every tabPanel loads a list from the same resource but with a different permanentFilter.

When I switch from one tab to another, I can see the list with the data loaded in the first place, then it loads and shows the new data recommended by my permanentFilter.

Is that really your intention that data of a previous request is shown in an optimistic request, even if a different permanentFilter is used?

And if, what do you recommend to "disable" this behaviour? Ist their a built in function in react-admin to reset the redux store?

Thanks in advance
Chris

**Environment**
* React-admin version: 3.31.4

**Comment by fzaninotto** [comment]
Yes, it's the intend behavior. The idea is that when a user changes *filter*, they usually don't want to see the list getting empty then getting filled again. 

The user expectation is different when using *tabs*, so I understand that implementing tab using filters doesn't work from a UX point of view. 

To disable this behavior, a change is necessary in `useListController` : the `ids` and `total` returned by the hook should not default to the previous results (changes line 209 and 224). I believe we can add an option for that, so I'm marking this as an enhancement. Feel free to open a PR for it.

**Comment by js-chris** [comment]
Hi,

thanks, an option would be great :)

Chris

**Comment by jdemangeon** [comment]
Hi @js-chris! Feel free to send an RFC, we will give it a lot of attention ;)
