### ISSUE TITLE
Data Refresh After component render in UseQuery of react-admin

### ISSUE THREAD

**Issue by onlineverh** [marmelab/react-admin#4489]
i ask my question  on stackoverflow this link : [https://stackoverflow.com/questions/60575129/data-refresh-after-component-render-in-usequery-of-react-admin]
but i dont receive answer plz help me 
i use useQuery for showing list item, i need to Button for Refresh my requests how i can use useRefresh for this work?

this is my Code:
```
const {data,total,loading,error} = useQuery({
  type: 'GET_LIST',
  resource: 'requests',
  payload: {
    pagination: { page: page, perPage: perPage },
    sort: { field: 'createdAt', order: 'DESC' },
    filter: {restaurants_id:restaurants_id,createdAt:date}
  }
});
```

**Comment by fzaninotto** [comment]
As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin) - NOT this issue tracker.

So I'm closing this issue.

**Comment by onlineverh** [comment]
Dear in StackoverFlow i dont receive answer
how i receive my answer?

thanks and regards

**Comment by fzaninotto** [comment]
This is an open-source project. If you absolutely need an answer, consider hiring a contractor (I recommend marmelab.com).
