### ISSUE TITLE
I wish applying the HideOnScroll component could be selectable

### ISSUE THREAD

**Issue by anthonyminyungi** [marmelab/react-admin#4493]
**Is your feature request related to a problem? Please describe.**

I think to give the more customizability to users, the `HideOnScroll` component should be selectable via props.
I'm very bothered by this.

**Describe the solution you'd like**

https://github.com/marmelab/react-admin/blob/3d16941b7c8fdfcd534f49f27a105164ab6fff6b/packages/ra-ui-materialui/src/layout/AppBar.js#L50-L70
This is the code that you guys published.

As I said on the top, How about this way?

src/layout/AppBar.js
```js
const AppBar = props => {
    const {
        children,
        classes: classesOverride,
        className,
        logo,
        logout,
        open,
        title,
        userMenu,
        hideOnScroll, // prop for selective
        ...rest
    } = props;
    const classes = useStyles(props);
    const dispatch = useDispatch();
    const isXSmall = useMediaQuery(theme => theme.breakpoints.down('xs'));


    return (
        <HideOnScroll hide={hideOnScroll}> // pass through prop to target component.
            <MuiAppBar className={className} color="secondary" {...rest}>
                <Toolbar
```

src/layout/HideOnScroll.tsx
```ts
function HideOnScroll(props: Props) {
    const { children, hide } = props;
    const trigger = useScrollTrigger();
    return (
        <Slide appear={!hide} direction="down" in={!trigger}>
            {children}
        </Slide>
    );
}
```

Usage
```js
  <AppBar hideOnScroll={/*true or false*/} {...props}>
    ...
  </AppBar>
```
**Describe alternatives you've considered**

Please consider my issue seriously. I hope this would be reflected. 🙏 

**Additional context**

**Comment by djhi** [comment]
Thank you for your suggestion. We are aware our components can't please everyone. This is why we ensured the `<Appbar />` component, as many others, can be replaced.

You can find instructions to do this in our documentation, specifically this page:
https://marmelab.com/react-admin/Theming.html#replacing-the-appbar

**Comment by anderswestberg** [comment]
Change the AppBars container prop to a simple div instead of the default HideOnScroll:

container={MyDiv}

const MyDiv = (props: any) => {
    return <div>{props.children}</div>
}

**Comment by anderswestberg** [comment]
The code in my comment doesn't show properly, here is another try:
`const MyDiv = (props: any) => {
    return <div>{props.children}</div>
}`

**Comment by djhi** [comment]
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/AppBar.tsx#L68

**Comment by djhi** [comment]
btw, you can find instructions about this specific case in the documentation. See https://marmelab.com/react-admin/Theming.html#replacing-the-appbar
