### ISSUE TITLE
[RFC] Change function components defaultProps for params default values.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4495]
React is deprecating the use of defaultProps on function components in favor or ES6 params default values.
I don't know what you think.

https://github.com/facebook/react/pull/16210
https://github.com/reactjs/rfcs/pull/107
https://twitter.com/dan_abramov/status/1133878326358171650
https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components

**Comment by JulienMattiussi** [comment]
Not fan myself because that means you'll have to deconstruct (and sometimes reconstruct) your props each type you want to use default values.

After
```
const Foo = ({foo = 1, ...rest}) => {
  const props = { foo, ...rest };
  return (
     <>
        <FirstComponent foo={foo} />
        <SecondComponent {...props} />
     </>
  );
}
```
Before

```
const Foo  = props => {
  return (
     <>
        <FirstComponent foo={props.foo} />
        <SecondComponent {...props} />
     </>
  );
}

Foo.defaultProps = {
   foo: 1
};

```

**Comment by fzaninotto** [comment]
defaultProps can be inspected by the parent, while params default values can't. 

This change will break some of the things we do in react-admin. I'm not in a hurry to jump in...

**Comment by jdemangeon** [comment]
Sorry @WiXSL but this RFC can break so many things in react-admin that it seems risky to apply it as is. Do you have another proposition? 

In other case, we'll consider closing this RFC (@JulienMattiussi @fzaninotto are you OK?)

**Comment by WiXSL** [comment]
Ok, I don't have nothing else, just throwing the idea.
It's ok, you can close it.
