### ISSUE TITLE
Router doesn't work with resources whose name contains a double colon

### ISSUE THREAD

**Issue by srosset81** [marmelab/react-admin#4504]
**What you were expecting:**
I want to use react-admin with a [Linked Data Platform](https://www.w3.org/TR/ldp/) backend. Linked Data Platform use web semantic standards and in particular ontologies. Class types are defined using the ontology keyword (eg. `pair`) and the class, separated by a double colon (:)

I was expecting it would be possible to use resource names with a double colon like this:
```js
function App() {
  return (
    <Admin dataProvider={myDataProvider()}>
      <Resource name="pair:Project" list={ProjectList} edit={ProjectEdit} create={ProjectCreate} icon={ProjectIcon} />
      <Resource name="pair:Organization" list={OrganizationList} edit={OrganizationEdit} create={OrganizationCreate} icon={OrganizationIcon} />
    </Admin>
  );
}
```

**What happened instead:**
The first resource (`pair:Project`) is always displayed. It's not possible to navigate to the other resource.

**Steps to reproduce:**
- Click on "pair:Projects" : you see the projects
- Click on "pair:Organization": the URL changes to http://localhost:3000/#/pair:Organization but you still see the projects.
- If you invert `pair:Organization` and `pair:Project`, then you will always see the organizations.

**Other information:**
I guess the router doesn't understand double colons and considers http://localhost:3000/#/pair:Organization and http://localhost:3000/#/pair:Project are the same route.

**Environment**
* React-admin version: 3.2.4
* React version: 16.13.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
That's a limitation of react-router. We fon't fix it in core as you can fix it in userland: don't use a double colon in the resource name, and do the translation between the resource name and the API path in the dataProvider.
