### ISSUE TITLE
ra-input-rich-text - Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

### ISSUE THREAD

**Issue by Vadorequest** [marmelab/react-admin#4512]
I'm trying to use the `ra-input-rich-text` component.

First things first, it's not SSR compatible, it crashes the whole app when imported, I had to use `require` instead of `import`. But that's not the main problem.

```tsx
import React from 'react';
import { Edit, SimpleForm, TextField, TextInput } from 'react-admin';

const CustomerEdit = (props): JSX.Element => {
  const RichTextInput = require('ra-input-rich-text'); // Not SSR compatible

  console.log('customerEdit props', props);
  return (
    <Edit {...props}>
      <SimpleForm
        redirect={false}
      >
        <TextField source="ref" label={'Reference (#)'} />
        <TextInput source="labelEN" label={'Label (EN)'} />
        <TextInput source="labelFR" label={'Label (FR)'} />
        <RichTextInput source="terms.html" label={'Terms'} />
        {/*<TextInput source="terms.html" label={'Terms'} />*/}
      </SimpleForm>
    </Edit>
  );
};

export default CustomerEdit;

```

`<RichTextInput source="terms.html" label={'Terms'} />` crashes the app with
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
>
>Check the render method of `CustomerEdit`.
>
>    in div (created by FormInput)

If I use a `TextInput` instead, it works fine:

![image](https://user-images.githubusercontent.com/3807458/76442787-baad9f00-63c1-11ea-96bd-25925878f180.png)

Here is what my data looks like:
![image](https://user-images.githubusercontent.com/3807458/76443193-5808d300-63c2-11ea-9b20-9ffff95745cd.png)

I don't understand the bug, `terms.html` isn't an object, it's a string. 
Maybe this component doesn't support nested field name using `source`?

**Steps to reproduce:**
Use a `RichTextInput` component with a HTML value that is nested, like `terms.html`

**Related code:**
https://github.com/UnlyEd/next-right-now-admin/pull/19

**Environment**

* React-admin version: 3.2.4
* React version: 16.12

**Comment by fzaninotto** [comment]
I can't reproduce the error on the simple example. The problem is likely on your side. 

Please fork [the simple example codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple), which contains a working RichRextInput in the Post edit page, Body tab. Try and reproduce your issue there, and paste the link to your codesandbox when you're done.

**Comment by Vadorequest** [comment]
I'll try to do that. How did you try to reproduce it? Did you use a nested field that contains HTML, similar to `terms.html`?

**Comment by fzaninotto** [comment]
I used the simple example, without modification.

**Comment by Vadorequest** [comment]
Won't take time to provide a repro. Closing.
