### ISSUE TITLE
[Update documentation] ra-data-simple-rest dialect sends Valid JSON in URL params

### ISSUE THREAD

**Issue by eightyfive** [marmelab/react-admin#4520]
You should update the documentation of [`ra-data-simple-rest` dialect](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-simple-rest#rest-dialect) to reflect that the library does indeed send valid JSON in URL params.

Example:
```
GET http://my.api.url/posts?sort=['title','ASC']&range=[0, 24]&filter={title:'bar'}
```

Needs to be:
```
GET http://my.api.url/posts?sort=["title","ASC"]&range=[0, 24]&filter={"title":"bar"}
```

Thanks a lot for the library.

**Comment by fzaninotto** [comment]
Thanks for reporting this!
