### ISSUE TITLE
[docs] Missing segments array in FormWithRedirect code example

### ISSUE THREAD

**Issue by ValentinnDimitroff** [marmelab/react-admin#4522]
While experimenting with v.3 new features I have attempted to just copy code from the docs to play around with but I noticed missing part which took me a few minutes searching in the repo to get things working. 

This is the  page ->[Custom Form Component part](https://marmelab.com/react-admin/CreateEdit.html#custom-form-component)

When you copy and execute an error an error appears because the `segments ` array is missing and I think it would be nice to have it in the snippets itself. Shall I make a pull request with the edit?

**Comment by JulienMattiussi** [comment]
We would'be happy if you can do so and help us to have a better doc.
