### ISSUE TITLE
Custom undo timeout

### ISSUE THREAD

**Issue by archfz** [marmelab/react-admin#4533]
It would be nice to be able to customize the undo timeout for edits and deletes. Specifically what I would need this for is browsers tests in which I do not want to wait always 4 seconds for all edit and delete operations, since I want to assert that the request is being made.

Possibly have a react context based RA configuration that could be used by the undo logic to send to the Notification as the autohide duration.

**Comment by JulienMattiussi** [comment]
I'm not convainced that having a specific behaviour in tests diferents from the normal usage wanted behaviour is a good idea. IMO, it's a big risk to have unconsistent tests at the end.

By the way, if your probleme is the times taken by those tests, you can speend them up just by adding a neutral click  on the page after the submission. It will skip the undoing time instantly.

**Comment by archfz** [comment]
@JulienMattiussi even if not for tests it would be nice to have it configurable. I did not know about the click skipping the undo.

**Comment by fzaninotto** [comment]
You can already use your own controller to relace the edit controller, where you call the notify() side effect with a custom timeout. It's a bit of work, but it's possible. 

As for tests, as Julien said, you should dispatch a click in the page to dismiss the notification and trigger the end of the undo period.
