### ISSUE TITLE
Documentation - Add exemples for conditional data manipulation in List, Edit, Show and Create views

### ISSUE THREAD

**Issue by Vadorequest** [marmelab/react-admin#4534]
The official documentation lacks some examples regarding how to conditionally show information in the CRUD views.

For instance, the `ShowController ` is mentioned in a [SO answer](https://stackoverflow.com/a/51068735/2391795) (by one of the core team members I believe) but it's not mentioned in https://marmelab.com/react-admin/Show.html 

I believe this is a very common question for most people and it should be part of the official documentation.

See related SO questions:
- https://stackoverflow.com/questions/60695739/react-admin-chipfield-conditional-color-in-list-view
- https://stackoverflow.com/questions/50992548/how-do-you-conditionally-show-fields-in-show-component-in-react-admin

**Comment by fzaninotto** [comment]
<ShowController> and <ListController> are deprecated in 3.0. Developers should use the hooks counterpart, useShowController, and useListController.

So this issue underlines a more global problem: ra-core hooks aren't documented.

**Comment by Vadorequest** [comment]
Exactly, I couldn't find any official example at https://marmelab.com/react-admin/List.html

I spent a lot of time looking at the ra-core and ra-material-ui packages (too much time, to be honest). The only SO answer from a RA dev I could find on the matter is not using the `useShowController`, so it's likely outdated. And I've seen no deprecation warning when using `ShowController`. The method could use `@deprecated Use useShowController instead for v3`, for instance, or a link or something.

I also opened another SO question, which is (IMHO) related to missing documentation too (because that's very basic and should be covered by the official doc):
https://stackoverflow.com/questions/60695739/react-admin-chipfield-conditional-color-in-list-view/60746700?noredirect=1#comment107480140_60746700

**Comment by Vadorequest** [comment]
Here is how I do it right now for my `ProductEdit.tsx`:

```tsx
import React from 'react';
import { Edit, EditController, ImageField, NumberInput, SimpleForm, TextInput } from 'react-admin';
import { EditControllerProps } from '../../types/admin/EditControllerProps';
import { EditProps } from '../../types/admin/EditProps';
import { Product } from '../../types/data/Product';

const ProductEdit = (props: EditProps): JSX.Element => {
  console.debug('productEdit.props', props);
  return (
    <EditController {...props}>
      {(controllerProps: EditControllerProps) => {
        const { record, loading }: EditControllerProps & { record: Product } = controllerProps;

        if (!loading) {
          console.debug('productEdit.controllerProps:', controllerProps, 'record:', record);
          return (
            <Edit {...props}>
              {/* XXX Using custom toolbar breaks updates because props get injected to the DOM instead of being passed down to children, somehow*/}
              {/*<SimpleForm toolbar={<ProductEditToolbar />}>*/}
              <SimpleForm
                redirect={false}
              >
                <ImageField source="images" src="url" title="Image" />
                <TextInput source="titleEN" label={'Title (EN)'} />
                <TextInput source="titleFR" label={'Title (FR)'} />
                <TextInput source="descriptionEN" label={'Description (EN)'} multiline={true} />
                <TextInput source="descriptionFR" label={'Description (FR)'} multiline={true} />
                <NumberInput source="price" />
              </SimpleForm>
            </Edit>
          );
        } else {
          return null;
        }
      }}
    </EditController>
  );
};

export default ProductEdit;

```

Would you mind either show me how you would recommend doing this, using `useShowController`, or link some documentation/examples about how to do it properly? Thank you.

On another note, I guess using a tool like StoryBook could be a great way to show all your component with live and documented examples. It'd be more developer-friendly and reusable. Similar to what you did with your article series at https://marmelab.com/react-admin/AdvancedTutorials.html, but better (and it could be kept up to date, unlike those that are probably also outdated)
