### ISSUE TITLE
Filter not displayed with a compound source

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#4539]
Hello, I have a problems when I use the compound names (e.g. `element.title`) as `source` in filter inputs since I updated react-admin.
The input doesn't display and I have no errors in the console.

**Steps to reproduce:**
Add compound name in source for input filter

* Sandbox
https://codesandbox.io/s/modest-rgb-ehvhd

**Environment**

* React-admin version: 3.3.1
* Last version that did not exhibit the issue (if applicable): 2.9.8
* React version: 16.13.0
* Browser: Chrome
* Stack trace (in case of a JS error): No stack trace

**Comment by JulienMattiussi** [comment]
I reproduced your issue.
Thanks for reported it.
We are still looking for the cause.
