### ISSUE TITLE
handleCheck saga never called causing no redirect

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#4549]
I am recreating the issue as I am not sure if that's a bug and a previous issue created for this just disappeared =/

## Description

During an upgrade from `react-admin` v2 to v3.3.0, I encounter issue to get redirected to `/login` after rewriting the `authProvider`

- react-admin [documentation](https://marmelab.com/react-admin/Authentication.html) | [github](https://github.com/marmelab/react-admin)

My `authProvider.js` contains the following methods:

```jsx
export default function createAuthProvider(urls, client, options) {
  return {
    login: (params) =>  {
      return fetchLoginBatch(params, urls, client, options);
    },
    logout: (params) => params.jwt ? fetchLogout(makeRequestLogout(urls.logout, params.jwt), options) : Promise.resolve(),
    checkError: (error) => {
      const { status } = error;
      if (status === 401 || status === 403) {
        return Promise.reject();
      }
      return Promise.resolve();
    },
    checkAuth: (params) => params.jwt ? Promise.resolve() : Promise.resolve(),
    getPermissions: (params) => params.jwt ? Promise.resolve(params.jwt.authorities) : Promise.resolve(),
    refreshJwt: (params) => params.jwt ? fetchRefreshJwt(makeRefreshJwtRequest(client.accessTokenUri, {
      grant_type: 'refresh_token',
      refresh_token: params.jwt.refresh_token,
    }, client), options) : Promise.resolve()
  };
}
```

It is as described in [documentation](https://marmelab.com/react-admin/Authentication.html) and [example](https://github.com/marmelab/react-admin/blob/master/examples/simple/src/authProvider.js)

## Expected 

I expect to be redirected to `/login`.

## Result

Instead, I stay on the page, `checkAuth` is well called and the `jwt` is `null`, 

[![enter image description here][1]][1]

## Possible fix

It is offered to change the redirect using an argument to rejected promise:

```jsx
    checkAuth: () => localStorage.getItem('token')
        ? Promise.resolve()
        : Promise.reject({ redirectTo: '/no-access' }),
```

But adding `Promise.reject({ redirectTo: '/login' })` doesn't help even if the code run.

I have tried to add some logging in `ra-core/lib/sideEffect/auth.js`:

```
console.log('auth');

exports.handleCheck = function (authProvider) {
    console.log('handleCheck', authProvider);

    return function (action) {
        console.log('action', action);

        var payload, meta, error_1, redirectTo, errorMessage;

        console.log('redirectTo', redirectTo, 'meta', meta);
```

`handleCheck` is called but never `action`, it seems that the saga is ignored somehow.

I also have tried to do (by mistake):

```jsx
{
  getPermissions: (params) => params.jwt ? Promise.resolve(params.jwt.authorities) : Promise.resolve({ redirectTo: '/login' }),
}
```

It work a bit better, it trigger the redirect to `/login`, but then I have an issue with `permissions` being an object `{ redirectTo: '/login' }` instead of being my **`Array`** of permissions  causing the rest of my userland code to fail,

Is this expected? According to the documentation, it should be `permissions`.

## Question

- Saga are configured within `<Admin />`, why isn't it triggered as it should?

- What should I check next to see why the redirection is failing? 

How does the `ra-core` code follow?

Thanks for advice and time

  [1]: https://i.stack.imgur.com/jJHuZ.png

**Comment by kopax** [comment]
Continue on SO

**Comment by DanielSanchez94** [comment]
HI, LET US KNOW IF I FOUND ANY SOLUTION. I HAVE THE SAME PROBLEM.

REGARDS
