### ISSUE TITLE
Right menu isnt working correctly in react-admin documentation

### ISSUE THREAD

**Issue by Cetger** [marmelab/react-admin#4558]
Hi, when i read the documentation of react-admin ı cant see all links in right menu even i am in bottom of page. 
![Screenshot from 2020-03-20 02-24-53](https://user-images.githubusercontent.com/31896026/77123957-9a7d8000-6a52-11ea-8866-337355c9141a.png)

It is my screenshot. I'm using ubuntu 18.04 and Chromium 80.0.3987.87

**Comment by JulienMattiussi** [comment]
You're right, it happens when scroll height isn't efficient on certain pages.
I'm just writing a fix on this.
Thanks for reporting this.
