### ISSUE TITLE
SimpleForm save prop cannot be overridden when SimpleForm is child of <Create>

### ISSUE THREAD

**Issue by francoisruty** [marmelab/react-admin#4563]
**What you were expecting:**

I expected to be able to override the save function of the SimpleForm component with the save prop, in all circumstances.

**What happened instead:**

When the SimpleForm is a child of a <Create>, the function I pass to SimpleForm via its save prop is not triggered when the form "Save" button is clicked, the function triggered is the one provided by <Create>
When SimpleForm is used in a standalone fashion (outside of a Create or Edit component), the save prop works properly

As a workaround, right now I use this SimpleForm wrapper:
const SimpleFormWrapper = props => {
  const {save, submit, ...rest} = props;
  return (
    <SimpleForm save={submit} {...rest} />
  )
}

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by JulienMattiussi** [comment]
It's the wanted behavior that controllers give the save fonction to SimpleForm.
The save prop is provided by the Create or Edit component depending on the case.

By the way, to override the default `save`, you have 2 way

### in your `SaveButton` by using the prop `onSave`

This will allow you to have many custom save functions on the same SimpleForm
https://marmelab.com/react-admin/CreateEdit.html#using-onsave-to-alter-the-form-submission-behavior

### Wrapping your SimpleForm to override the default save

```js
const WrappedSimpleForm = ({save, ...rest}) => {
   const mySave = () => { ...};
   return (<SimpleForm save={mySave} {...rest} />);
}

<Create>
    <WrappedSimpleForm />
</Create>
```

**Comment by francoisruty** [comment]
I finally went for the wrapping option, could we update the doc to mention this behavior? I can propose a PR

**Comment by ravi-pandit14** [comment]
how to get `<Edit><SimpleForm>` updated data on save click?
