### ISSUE TITLE
Add the GET_COUNT data fetch action

### ISSUE THREAD

**Issue by oklas** [marmelab/react-admin#4566]
GraphQL implementation is based on the assumption that count requests has same input type as list requests. Also all the list requests must has same input type. Else we need to make multiple count query fields - separated query per each list request. Ans one more count field with different filter type.

All this tasks may be solved in custom dataProvider when resource will has **count fetch action**. But without information about count fields and its data in introspection the data provider implementation gains meaningless complexity and instability.

To solve the problem I have to suggest to add **`GET_COUNT`** to the [dataFetchActions.ts](https://github.com/marmelab/react-admin/blob/v3.3.1/packages/ra-core/src/core/dataFetchActions.ts) and also to query types list at [ra-data-graphql/src/constants.js](https://github.com/marmelab/react-admin/blob/v3.3.1/packages/ra-data-graphql/src/constants.js#13)

This will significantly simplify implementation of the dataProvider and increase customization level at all.

**Comment by JulienMattiussi** [comment]
Sorry, but I don't really understand your needs.
Can you provide some code samples to illustrate what you have and what you want ?

**Comment by oklas** [comment]
The required definition of an `introspection` looks like this:

```js
const introspection = {
  operationNames: {
      [GET_COUNT]: resource => `count${pluralize(resource.name)}`,
      [GET_LIST]: resource => `all${pluralize(resource.name)}`,
      ...
  }
}
```

then [introspectionResults](https://github.com/marmelab/react-admin/blob/v3.3.1/packages/ra-data-graphql-simple/src/buildGqlQuery.js#L161) implementation will be like this:

```js
    const { sortField, sortOrder, ...metaVariables } = variables;
    const apolloArgs = buildApolloArgs(queryType, variables);
    const args = buildArgs(queryType, variables);
    const fields = buildFields(introspectionResults)(resource.type.fields);

    if (
        aorFetchType === GET_LIST ||
        aorFetchType === GET_MANY ||
        aorFetchType === GET_MANY_REFERENCE
    ) {
        //    vvvvvvvvv
        const countType = resource[GET_COUNT]
        //    ^^^^^^^^^
        const argsForCount = buildArgsCount(countType, variablesForCount);
        const apolloArgsForCount = buildApolloArgsCount(countType, variablesForCount);

        return gqlTypes.document([
            gqlTypes.operationDefinition(
                'query',
                gqlTypes.selectionSet([
                    gqlTypes.field(
                        gqlTypes.name(queryType.name),
                        gqlTypes.name('items'),
                        args,
                        null,
                        gqlTypes.selectionSet(fields)
                    ),
                    gqlTypes.field(
                        gqlTypes.name(countType.name),
                        gqlTypes.name('total'),
                        argsForCount,
                        null,
                        null,
                    ),
                ]),
                gqlTypes.name(queryType.name),
                [...apolloArgs, ...apolloArgsForCount]
            ),
        ]);
```

We must have access to graphql type and definition of `count` operation in introspection `resource`. It is `countType` in above code. Otherwise we are unable to create request.

Introspection resources is building in `ra-data-graphql` at [this place](https://github.com/marmelab/react-admin/blob/v3.3.1/packages/ra-data-graphql/src/introspection.js#L67). So it is not enough to add count name into `operationNames` but also `react-admin` need to know `GET_COUNT` and do same processing which already implemented. The constant for `count` operation is required to be exported from `ra-core` in the file  [dataFetchActions.ts](https://github.com/marmelab/react-admin/blob/v3.3.1/packages/ra-core/src/core/dataFetchActions.ts). And will be processed as request in `ra-data-graphql`.

Suggested modification of [ra-data-graphql/src/constants.js](https://github.com/marmelab/react-admin/blob/v3.3.1/packages/ra-data-graphql/src/constants.js#L13) is like this:

```js
- export const QUERY_TYPES = [GET_LIST, GET_MANY, GET_MANY_REFERENCE, GET_ONE];
+ export const QUERY_TYPES = [GET_COUNT, GET_LIST, GET_MANY, GET_MANY_REFERENCE, GET_ONE];
```

Otherwise it will be required to provide multiple `count` operations per each list operation. The only difference between all the `count` operations will be a types and amount of arguments.

**Comment by fzaninotto** [comment]
I don't understand either. Can you please explain not the change you need in the code, but the actual problem you're having in your application, in clear and simple words, and with examples?

**Comment by oklas** [comment]
The application has server side and client side like every web application. Examples of client side is exactly same as in react-admin documentation.

Server side provides a graphql interface. But it not match the default graphql provider. To integrate with server a custom provider is developing.

The default GraphQL provider implementation is based on the assumption that count (meta) requests has same input type as list requests. Also all the list requests must has same input type. And the meta request must have same input type. 

The graphql interface provided by server side match all the required features to make react-admin worked. But not match the assumption that a **count request**  and **all list requests** has same arguments and same input types.

That is the reason to use flexibility to have custom provider and implement simple custom provider instead of multiple duplications existing requests or create additional slightly different requests on the server side.

There could be no problem if the queries were called one at a time. But react-admin designed to call two request at time. For example `list`+`count` or list `reference`+`count`. (here count is meta request)

Current design do not allow implement the data provider because there is no way to determine type and args meta request because to build meta request used types not from meta request itself but from main request at [this line](https://github.com/marmelab/react-admin/blob/v3.3.1/packages/ra-data-graphql-simple/src/buildGqlQuery.js#L170).

This make it not possible to implement simple data provider and make it necessary provide multiple count operations per each list operation. The only difference between all the count operations will be a types and amount of arguments.

To solve this problem I suggests to add `GET_COUNT` fetch action.

**Comment by oklas** [comment]
Current doc requres:

```js
allPosts(filter: PostFilter): [Post]
_allPostsMeta(filter: PostFilter): ListMetadata
```

Agruments may has different types:

```js
allPosts(filter: PostFilterList): [Post]
_allPostsCount(filter: PostFilterCount): ListMetadata
```

**Comment by djhi** [comment]
`ra-data-graphql-simple` is an **example** implementation of a graphql dialect. If you don't want to rely on a meta query to fetch the count, you'll have to build your own provider.

**Comment by RWOverdijk** [comment]
I don't know if closed issues get looked at when commented on, but I do have an additional question about ra-data-graphql-simple.

Why does meta need the same inputs as allposts? I don't understand how page, perPage, sortField and sortOrder make a difference in the count. Shouldn't the count be the same without those?

I do understand that writing a custom provider gives more flexibility, I'm not unwilling to do that 😄 I am just curious why they're the same arguments if they don't change the outcome.

```graphql
  allPosts(page: Int, perPage: Int, sortField: String, sortOrder: String, filter: PostFilter): [Post]
  _allPostsMeta(filter: PostFilter): ListMetadata # <--- shouldn't this be enough?
```
