### ISSUE TITLE
addLabel not working in FormDataConsumer

### ISSUE THREAD

**Issue by deepnees** [marmelab/react-admin#4571]
**What you were expecting:**
addLabel should work with FormDataConsumer.

**What happened instead:**
I have using outlined inputs with labels on my project. And FormDataConsumer ignores addLabel prop.

**Steps to reproduce:**
Example usage in CommentCreate component:
https://codesandbox.io/s/staging-sunset-cthz9

**Possible Solution:**
I have created FormGroup componet and covered formData with FormGroup 

```
formData.post_id !== "" && (
            <FormGroup>
              <DateInput
                source="created_at"
                defaultValue={now}
                addLabel={true}
              />
              <TextInput
                source="body"
                fullWidth={true}
                multiline={true}
                addLabel={true}
              />
            </FormGroup>
          )`
```
**FormGroup Component:**

```
import React, { Children } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import { makeStyles } from '@material-ui/core/styles';

import { FormInput } from 'react-admin';

const useStyles = makeStyles(theme => ({
    input: { maxWidth: theme.spacing(64), minWidth: theme.spacing(48) },
}));

export const FormGroup = ({ children, classes: classesOverride, ...rest }) => {
    const classes = useStyles({ classes: classesOverride });
    return (
        <div className={classnames('ra-form-gruop', classes)}>
            {Children.map(children, input => (
                <FormInput input={input} {...rest} />
            ))}
        </div>
    );
};

FormGroup.propTypes = {
    className: PropTypes.string,
    classes: PropTypes.object,
};

FormGroup.displayName = 'FormGroup';

export default FormGroup;
```

**Environment**

* React-admin version: 3.0+
* React version: 16.3.0
* Browser: Any
* Stack trace (in case of a JS error): No error

**Comment by fzaninotto** [comment]
The documentation is misleading. `addLabel` only works when a component is used as child of `<SimpleForm>`, `<FormTab>`, `<SimpleShowLayout>`, or `<Tab>`. In other cases, you have to decorate the field with `<Labeled>` yourself.
