### ISSUE TITLE
Console warning when using alwaysOn SelectArrayInput in Filter component

### ISSUE THREAD

**Issue by marina9568** [marmelab/react-admin#4576]
**What you were expecting:**
No console warnings

**What happened instead:**
Console warning:
`Warning: React does not recognize the "alwaysOn" prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase "alwayson" instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Steps to reproduce:**
`<Filter {...props}>
        <SelectArrayInput source="groups" alwaysOn choices={...} />
</Filter>`

**Other information:**
The same as #4161 

**Environment**
* React-admin version: 3.2.3
* React version: 16.12.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Fixed by #4561
