### ISSUE TITLE
Fix custom layout documentation

### ISSUE THREAD

**Issue by g3n35i5** [marmelab/react-admin#4578]
In order to add a custom icon to the app toolbar, the [documentation](https://marmelab.com/react-admin/Theming.html#using-a-custom-layout) says
```typescript
const MyUserMenu = props => (<UserMenu {...props} icon={MyCustomIcon} />);
```
but it should be
```typescript
const MyUserMenu = props => (<UserMenu {...props} icon={<MyCustomIcon/>} />);
```

**Comment by fzaninotto** [comment]
Good catch. Could you please make a PR to fix this?

**Comment by g3n35i5** [comment]
Sure, here you go #4581
