### ISSUE TITLE
useAuthState() hook creates a 'could not find react-redux context value' error

### ISSUE THREAD

**Issue by dvasdekis** [marmelab/react-admin#4585]
**What you were expecting:**
useAuthState() hook allows me to display different application states depending on if someone is logged in or not

**What happened instead:**
Using the hook, no matter what circumstances I try and call it under, produces an error: `could not find react-redux context value; please ensure the component is wrapped in a <Provider>`

**Steps to reproduce:**
Try and implement the hook! See the related code example, where it is an implementation of the example from the tutorial. The app doesn't even load.

**Related code:**
https://codesandbox.io/s/github/dvasdekis/react-admin-hook-provider-error/tree/master/examples/simple

**Environment**

* React-admin version: latest (3.3.3)
* Last version that did not exhibit the issue (if applicable): N/A
* React version: "^16.9.0"
* Browser: Chrome
* Stack trace (in case of a JS error): [See CodeSandbox example](https://codesandbox.io/s/github/dvasdekis/react-admin-hook-provider-error/tree/master/examples/simple)

**Comment by fzaninotto** [comment]
`useAuthState()` must be used *inside* a react-admin app, not *around* it.

**Comment by dvasdekis** [comment]
Is there an example I can see where this has been used correctly? I have searched widely, and can't find anything.

**Comment by kopax** [comment]
@dvasdekis try to add `const { loading, authenticated } = useAuthState();` into a route, it will work.

There's no way it work around react-admin, because react-admin is not initialized, it didn't even run and there's nothing you can do about it. What you are doing right now is similar to :

```jsx
console.log(a);
var a = 'initialized';
```

**Comment by dvasdekis** [comment]
@kopax thank you for your explanation Dimitri. I understand what you mean from a theoretical level, but now the [implementation I think you've suggested](https://marmelab.com/react-admin/CustomApp.html) is getting quite complex for me, as my background is backend/data, and my basic javascript knowledge is not up to task of managing a Redux store! 

I was hoping to use React-Admin as a simple template on top of my GraphQL backend for prototyping purposes, but I am hitting [an authentication stumble](https://github.com/benwinding/react-admin-firebase/issues/93) that is stopping me from using it. Managing Redux state is complicated even for the guy who makes the Firebase Auth module for React-Admin! :)

Please take this as a gentle request for an easier way to set this up without getting drowned in the complexities of Redux. Thank you for all the great work you've put into React-Admin so far! :)

**Comment by dvasdekis** [comment]
Hi folks, I managed to get the integration working here: https://github.com/dvasdekis/react-admin-hasura-firebase
I avoided the use of this hook by setting the data provider up as a .then-able from the definition of the auth provider. Code here: https://github.com/dvasdekis/react-admin-hasura-firebase/blob/master/src/App.js
