### ISSUE TITLE
React-Admin customize URL for extranet use case

### ISSUE THREAD

**Issue by francoisruty** [marmelab/react-admin#4586]
**Is your feature request related to a problem? Please describe.**

My problem is that I'm setting up a backoffice, and I need some people from the outside to be able to edit particular resources.
So I use a configured nginx in front of react-admin to authorize outside access only for particular URL patterns.
However, I don't want outside people to use a URL that contains the database id of the object.

**Describe the solution you'd like**

I would like a solution to have the URL use another column than the id column of the resource.

**Describe alternatives you've considered**

Currently my workaround is that my API returns under the "id" key another column, which contains an uuid. Then I propagate this change to all my other backend endpoints that are used by ReferenceField and such, so that they are aware that the id used by the Show and Edit components is not really the id but an uuid.

I think it would be cleaner to have a way to customize the URLs (but maybe that's possible already and I'm not aware of it!

**Additional context**

**Comment by fzaninotto** [comment]
React-admin requires that your resources have an "id" field. What you choose to put in this id field is entirely up to you. If the underlying record doesn't have and id field, or if your id field isn't public, map the id field with another field in your dataProvider.
