### ISSUE TITLE
Datagrid header cells lose their styles when dynamically changing theme

### ISSUE THREAD

**Issue by djhi** [marmelab/react-admin#4587]
**What you were expecting:**
The styles of the header cells should be kept when changing theme

**What happened instead:**
They disappear :ghost: 

**Related code:**
https://codesandbox.io/s/hopeful-leaf-05ybg

1. Open devtool and use the DOM selector to highlight a datagrid header cell (see the css class `.RaDatagrid-headerCell-XXX` applied and its CSS content in the devtool styles part)
![image](https://user-images.githubusercontent.com/1122076/77769550-4c650f80-7044-11ea-937a-f8b8701c75d5.png)

2. Use the user menu to toggle darkmode
3. Check the element in the devtool. The css class is still applied on the element but its CSS content is not here anymore.
![image](https://user-images.githubusercontent.com/1122076/77769497-38b9a900-7044-11ea-8406-fbd54ab3acbd.png)

**Environment**

* React-admin version: 3.3.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.9.0
* Browser: FF, Chrome

**Comment by jayanth-2** [comment]
@djhi I couldn't reproduce it. It's working fine.
![Screenshot from 2020-12-17 19-41-04](https://user-images.githubusercontent.com/49862074/102571184-fb83d280-410e-11eb-9b84-e82fff55b8ea.png)
![Screenshot from 2020-12-17 19-40-47](https://user-images.githubusercontent.com/49862074/102571188-fe7ec300-410e-11eb-8990-4a38c9c0e089.png)

**Comment by djhi** [comment]
Yes I think it has been fixed
