### ISSUE TITLE
App cannot run after upgraded to 3.3.3

### ISSUE THREAD

**Issue by Godman-quake** [marmelab/react-admin#4588]
It seemed <Admin> and other components cannot work normally after upgraded to 3.3.3.
But if I downgrade to 3.3.1, everything is OK!
Please check it, thanks!

**Comment by djhi** [comment]
Please follow the issue template. We use 3.3.3 on several projects without any issues

**Comment by Godman-quake** [comment]
Hi, djhi!
The error is like this (output to the browser's console over and over, and at last my computer crashed!):
[getList-error]-- TypeError: a is null DataProvider.js:40:14
    P http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    x http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    get http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    a http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    ac http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    bs http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    unstable_runWithPriority http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Va http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    ms http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Zc http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Ya http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    unstable_runWithPriority http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Va http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Ya http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Ha http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Gc http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    enqueueSetState http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    setState http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    unlisten http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    r http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    notifyListeners http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    notifyListeners http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    P http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    push http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    confirmTransitionTo http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    push http://192.168.0.101/static/js/2.5423f534.chunk.js:2
    Hs http://192.168.0.101/static/js/2.5423f534.chunk.js:2

**Comment by Godman-quake** [comment]
And this is my getList method in DataProvider:
getList: (resource, params) => {
    try {
      ......
      const url = `${apiUrl}/${resource}?${stringify(query)}`;
      const validUntil = new Date();
      validUntil.setTime(validUntil.getTime() + 30 * 60 * 1000);
      return httpClient(url).then(({ headers, json }) => {
        return {
          data: json.data,
          total: json.count,
          validUntil,
        }
      })
    } catch (err) {
      console.log(`[getList-error]-- ${err}`)
      return Promise.reject(err);
    }
  },

**Comment by Godman-quake** [comment]
It can run on 3.3.1 with no errors, and the backend is the same.

**Comment by fzaninotto** [comment]
Please put yourself in our shoes: there is no way we can tell if the problem is on your side or on the react-admin side with poorly formatted, incomplete code. 

So either you follow the issue template, and provide a link to a minimal CodeSandbox based on the simple example that reproduces the issue, or we'll just consider this as a "how to/troubleshoot" issue, and close it.

**Comment by kopax** [comment]
Just a guess, it looks like a minification error, perhaps a `core-js`. Can you disable minification to get a proper error. Also check with `npm ls core-js` and `npm ls | grep core-js` and compare the version with the one that you had in your old `package-lock.json` or `yarn.lock` (or just the old project). Hope it help.

**Comment by Godman-quake** [comment]
Thanks to fzaninotto, and thanks to kopax too.
Now I have an idea: git clone the official simple example and run it with 3.3.3 on my computer, let's see what will happen!

**Comment by Godman-quake** [comment]
OK, I got the example, ran `npm i --save react-admin`, the react-admin's version is 3.3.3 now.
I ran it in the development mode, and no errors displayed. But the page is not correct, it seemed the i18nProvider and dataProvider are not working, because the posts' list is empty and the UI's title and content are not be translated.

**Comment by Godman-quake** [comment]
Maybe it's my environment's problem?
But I can run it on 3.3.1 with no errors.

**Comment by fzaninotto** [comment]
It's probably a problem with your environment. Alternately, try to fork the react-admin simple example codesandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by Godman-quake** [comment]
OK, fzaninotto, thank you again! I will have a try, and it's the time to close this issue.
