### ISSUE TITLE
More sophisticated ReferenceInput by using List/Datagrid

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#4593]
**Is your feature request related to a problem? Please describe.**

If you need to select references, the SelectInput and MultiSelectInput are very limited. As a developer, you have to figure out, how your users will select the right references (should i show a user email? or firstname, lastname?). So it would be best ist the user could filter the data as he/she wishes. Building such a component would surely be a lot of work... or isn't it? We already have such a component: It's the List-Component of that referenced Resource!

**Describe the solution you'd like**

I once built a admin solution my self  (far not as polished as react-admin!) and my solution was quite simple:

- The input field would show the selected reference by a field (id or whatever) to indicate that something is selected
- Instead of beeing editable, this input field would have a button next to it (i used a magnifier-icon for that)
- clicking on that button would mount the <List />-Component in a Modal.
- This Modal would show the normal `<List />` of that resource, but intead of the normal actions (Edit for example), it would have a "Pick" button (or a checkbox in case of multi-select)
- Clicking on that Pick button would set the referenced value to this item (e.g. ist does just `onChange(newId)`)
- In my case i did not implement the multi-select-case, but it could work very similarly

Consider a `User` Entity which has a foreign reference `Company`.
The API could look like this:

```
export const UserEdit = props => (
  <Edit {...props}>
    <SimpleForm variant="outlined">
      <TextInput disabled source="id" />
      <TextInput source="email" />
      <ReferenceListInput source="company.id"> // would take the same args as <List />
         <Datagrid>
           <TextField source="id" />
           <TextField source="companyName" />
           <TextField source="street" />
           <PickButton /> // or maybe this is automatically added
         </Datagrid>
     </ReferenceListInput>
    </SimpleForm>
  </Edit>
);

```

**Describe alternatives you've considered**

I think this is doable in user-space, but i think it would be worth investigating if we could provide a built-in-component for that

**Comment by fzaninotto** [comment]
Nice idea. We won't implement that in core, feel free to write your own package for it, and please add a link to it in the Ecosystem docs!

**Comment by macrozone** [comment]
![Download (1)](https://user-images.githubusercontent.com/1972353/77862945-07e19b80-721f-11ea-8c45-862f468b43ec.png)

okey, will try someting...
