### ISSUE TITLE
AutocompleteInput  search for click  not display 

### ISSUE THREAD

**Issue by curisegong** [marmelab/react-admin#4594]
AutocompleteInput  search for click  not display 
when i input something then it show the options which contains my input
but when i click someone ,the component does not show
but when second i  input something and click someone ,this time is show my first click
my react-admin version is 2.9
what should i do

**Comment by fzaninotto** [comment]
Please use the issue template.

**Comment by jdemangeon** [comment]
This issue seems to be abandoned. Please open another one using template.
