### ISSUE TITLE
Empty view shows after coming back from detail view

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#4601]
1. Open the url `/#/posts/1` on the simple example on  a new window
2. Click on the Save button
3. The user is redirected to the List view, which shows the Empty component... but it shouldn't.

Tested in v3.3.3

**Comment by ekrenzin** [comment]
I encountered this issue. I used a custom toolbar and custom save button to first save with a dataprovider, then redirect with an href. My workaround is not ideal because it removes the option to undo the save, but we found it more desirable than an empty list page for a couple of seconds.
