### ISSUE TITLE
Client side pagination

### ISSUE THREAD

**Issue by Odonno** [marmelab/react-admin#4603]
**Is your feature request related to a problem? Please describe.**

When working with `List` component, you need to create a data provider by using `getList` function and so a backend side pagination mechanism.
That works great but sometimes you want a faster/simpler mechanism by loading the entire list at once and then apply client-side pagination. Of course, it can be applied to a small and not a large list of items.

**Describe the solution you'd like**

Add a property `clientSidePagination` on the `List` component in order to call a `getAll` function instead of the `getList` function of the data provider.
It should be transparent for the user and the developer and it is still compliant with the `validUntil` frontend caching mechanism.

**Describe alternatives you've considered**

Making my own caching mechanism that is built on top of `getList` function. It works but it is really ugly since I discovered that the new frontend caching mechanism is way better and is simple stupid to implement.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

We won't implement that feature in core, as we don't think it replies to a common enough requirement. But if you happen to develop it, please bundle it as an open-source package and open a PR in the Ecosystem documentation to link to it!

**Comment by webdevNYC** [comment]
Hi there,

Since this issue is from 2 years ago,  I wonder if anyone else got an easy solution for this request?  A workaround that would not take too much time coding?    Please let me know if you have any suggestions on how to do a getAll once, when it loads, and control the pagination and filter on the client-side.

**Comment by fzaninotto** [comment]
React-admin provides [the `useList` hook](https://marmelab.com/react-admin/useList.html), which allows to paginate, sort and filter any array of records. It should do the trick for your need.
