### ISSUE TITLE
Tree View on version 3 >

### ISSUE THREAD

**Issue by vgb0332** [marmelab/react-admin#4609]
I'm wondering if tree-view-material-ui has been updated for version 3!

**Comment by fzaninotto** [comment]
No, not yet. Feel free to work on your own custom package for that feature.

**Comment by macrozone** [comment]
@vgb0332 https://github.com/marmelab/react-admin/pull/3379 worked on that, but it staled, maybe you can help there?

**Comment by vgb0332** [comment]
> @vgb0332 #3379 worked on that, but it staled, maybe you can help there?
I would love to try! The thing is that I already made my own using Components from @material-ui/core without drag and drop feature which I prob can add, but I'm not sure if the codes will fit react-admin standards. Nevertheless, I'll try to refactor my codes for #3379 . 

It looks like the following at the moment.
![image](https://user-images.githubusercontent.com/23355692/78908625-531c6980-7abd-11ea-91d7-64a2c97994d6.png)
