### ISSUE TITLE
upgrading to V3.3.3 breaks multiple custom exporters

### ISSUE THREAD

**Issue by yitzgold** [marmelab/react-admin#4615]
**What you were expecting:**
in a ListView in custom actions, I can add 2 custom ExportButtons with the "exporter" property being a custom function

**What happened instead:**
it's ignoring my custom exporter, and using the default export instead, in V3.0.2 this worked fine

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
const Actions = props => {
    const { basePath, currentSort, filterValues, resource, total } = props;
    return (
      <Toolbar>
        <ExportButton
          label="donation export"
          disabled={total === 0}
          resource={resource}
          sort={currentSort}
          filter={{ ...filterValues, campaign_id }}
          exporter={donationExporter}
          maxResults={5000}
        />
          <ExportButton
            label="ticket export"
            disabled={total === 0}
            resource={resource}
            sort={currentSort}
            filter={{ campaign_id }}
            exporter={ticketExporter}
            maxResults={5000}
          />
      </Toolbar>
    );
  };

<ListView
      ........................
        actions={<Actions />}
      >
```

**Other information:**
this line is possibly the issue
https://github.com/marmelab/react-admin/commit/bb1b0be82417d865eadedd60b631d47765d4440e#diff-6756f5fe2842556d7a12d21454d38df8L139
the exporter prop was removed

**Environment**

* React-admin version: 3.3.3
* Last version that did not exhibit the issue (if applicable): 3.0.2
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
The fact that you could override the `exporter` at the button level was never an intended (or documented) feature. Yet, it's simple enough to add, so let's consider this a bug.

**Comment by yitzgold** [comment]
Thank you!
