### ISSUE TITLE
Get permissions in data provider

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/react-admin#4619]
**Is your feature request related to a problem? Please describe.**

I'm using firebase and would like to add default criteria to my queries in the data provider to restrict access to some resources (as firestore otherwise gives me an error saying I have insufficient permissions). To do this, I need access to the permissions.

**Describe the solution you'd like**

A reference to the permissions would be very useful as I can set some default query values (such as where owner = user)

**Describe alternatives you've considered**

Using globals and maintaining it in auth events. This quickly became very messy.

**Comment by fzaninotto** [comment]
Hi, and thanks for your request. 

This is something we've already considered in the past, and chose specifically not to address. This would add significant complexity to the code for a small number of use cases, and there are alternative solutions (like using globals or sessionStorage, as you're doing) in userland.

**Comment by RWOverdijk** [comment]
Well that's disappointing. Isn't the permission stuff maintained _somewhere_? How hard can it be to get access? I don't mind getting my hands dirty, but advising to use globals is just morally wrong haha

**Comment by fzaninotto** [comment]
The permission stuff is maintained in the authProvider, made accessible by the AuthContext.

**Comment by RWOverdijk** [comment]
Okay so then I should be able to ask the authprovider. I can construct my data provider with the authprovider. That sounds reasonable. Thanks!
