### ISSUE TITLE
Validate uniqueness of an input value

### ISSUE THREAD

**Issue by OoDeLally** [marmelab/react-admin#4625]
All of my users must have a unique nickname.
My DB has a `unique` index on the nickname field.
Therefore creating a new user fails if the chosen nickname is already taken.
However it would be nice to know that in advance in the UI, as part of the field's validation process.

**Describe the solution you'd like**
```
<TextInput source="nickname" unique={true} />
```
The validator could use the `allUsers` query with `{ nickname: "foo" }` as filter and `limit: 1`, so we do not need any extra query type.

The issue with such feature is that it requires an asynchronous validation, and as far as I saw in the source code, all the validation chain is synchronous. This implies big refactoring.

**Describe alternatives you've considered**
Currently the only way is to fail at the form submit time.

**Comment by fzaninotto** [comment]
You can use react-final-form's `asyncValidation` prop on `<SimpleForm>` and `<TabbedForm>`. You can also write your own custom form using react-final-form to handle this.

**Comment by OoDeLally** [comment]
Thanks!
I haven't found a `asyncValidation`, the prop on `SimpleForm` is called `validate`, isn't it?
I've managed to use it.

```ts
const validate = async (...args: any[]) => {
  return 'my custom error'
};
...
<SimpleForm validate={validate}>
  ...
</SimpleForm>
```


However, it doesn't seem to show the reported message, but rather something like that:
![image](https://user-images.githubusercontent.com/1717629/78257162-c50f1480-74f9-11ea-81d0-dc565b3f1573.png)

**Comment by fzaninotto** [comment]
most props that you pass to SimpleForm are passed to react-final-form. refer to their documentation for more details about `asyncValidation`

**Comment by OoDeLally** [comment]
I haven't found anything about `asyncValidation` in React Final Form. Am I looking at the right thing?
https://final-form.org/docs/react-final-form/types/FormProps

**Comment by fzaninotto** [comment]
Sorry, `asyncValidate` was a redux-form prop. The solution is to use a `validate` function that returns a Promise (see https://final-form.org/docs/react-final-form/types/FormProps#2-asynchronous-with-a-promise). 

Note that you should ask these questions in the react-final-form bug tracker. We don't provide support for third-party packages.

**Comment by OoDeLally** [comment]
Thank you.
Could you provide a working example?
I haven't got past this issue https://github.com/marmelab/react-admin/issues/4625#issuecomment-607863391
Basically, since the async validation is doc-wise, I see no way to re-dispatch the error to the specific field that cause the problem. Also, I haven't found the way to simply get the message returned from the server, rather than having a generic `This form is not valid. Please check for errors`.
