### ISSUE TITLE
RadioButtonGroupInputItem not checked when parsing input value

### ISSUE THREAD

**Issue by AdrienAgnel** [marmelab/react-admin#4626]
Hello, thanks a lot for react-admin, I use it a lot ! I'm having a slight issue with Radio Buttons:

**What you were expecting:**
The RadioButtonGroupInputItem should be checked after click on a RadioButtonGroupInput with a `parse` props.

When using a parsed input as described [in the doc](https://marmelab.com/react-admin/Inputs.html#transforming-input-value-tofrom-record), the value stored in react-final-form seems to be the parsed value, thus I would expect the RadioButtonGroupInputItem value to be parsed before being passed through useField hook in the RadioButtonGroupInputItem component [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/RadioButtonGroupInputItem.tsx#L26), because otherwise the `checked` props passed to the underlying Radio remains `false`.

**What happened instead:**
The RadioButtonGroupInputItem remains not checked on click.

**Steps to reproduce:**
- define a custom List Filter
- use a RadioButtonGroupInput with a parse function, like:

```
<RadioButtonGroupInput options={{classes: radioButtonGroupClasses}} label='' source='filling_level' choices={[
    { id: 0, name: 'Empty' },
    { id: 50, name: 'Half' },
    { id: 100, name: 'Full' }
]} parse={v => v / 100 } alwaysOn />
```

=> no Radio button should get checked on click (except 'Empty')

**Related code:**

Here is how my List's custom Filter is defined:
```
<Filter {...filterProps} >
      <TextInput label='Recherche' source='q' alwaysOn />
      <RadioButtonGroupInput options={{classes: radioButtonGroupClasses}} label='' source='employee' choices={[
        { id: `${employeeId}`, name: 'My files' },
        { id: 'all', name: 'All files' }
      ]} parse={v => v === 'all' ? '' : v} alwaysOn />
</Filter>
```

**Other information:**
- The form is actually a custom Filter in a List component
- I was upgrading from react-admin v2 to react-admin v3 and fixing some upgrade related bugs in my application. The RadioButtonGroupInput used to work with empty string values, but this does not seem to be possible any more. Certainly due to the behavior of react-final-form converting '' to undefined, mentioned in the spec of the parse function (again) of the FieldProps [here](https://final-form.org/docs/react-final-form/types/FieldProps#parse).
- I had to parse the input in order to keep sending an empty string to my API while using another value in my RadioButtonGroupInput
- I locally tried to pass the `parse` props from the RadioButtonGroupInput to the RadioButtonGroupInputItem component and it seemed to solve the issue, but not sure it's the right thing to do...

**Environment**

* React-admin version: 3.3.3
* Last version that did not exhibit the issue (if applicable): 2.9 (with empty string and no parse function)
* React version: 16.9.0
* Browser: Google Chrome Version 80.0.3987.149
* Stack trace (in case of a JS error): None

**Comment by fzaninotto** [comment]
I believe this is a react-final-form limitation: checkboxes and radio buttons don't support parse and format.

See https://github.com/final-form/react-final-form/blob/f3c1aea93b520c0620f1b8090f5966e0da94a798/src/useField.js#L213

**Comment by AdrienAgnel** [comment]
Thanks ! I'm going to dig on react-final-form side and submit an issue if this looks like a bug.

**Comment by tsonev7** [comment]
@AdrienAgnel , do you have new info on the issue? :)

**Comment by AdrienAgnel** [comment]
@tsonev7 no news about that, sorry, I opened an issue in react final form repo : https://github.com/final-form/react-final-form/issues/772 but got no answer and did not take the time to go further :/
