### ISSUE TITLE
Documentation about setting resources dynamically is outdated

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4629]
Current: 
https://marmelab.com/react-admin/doc/3.3/Admin.html#declaring-resources-at-runtime

New:
#3907

I'll see if I find some time to do this, no warranties.

**Comment by Kmaschta** [comment]
That would be awesome :)

**Comment by fzaninotto** [comment]
I don't understand, we don't enforce the usage of `<AdminUI>`, and the previous way still works... Can you be more specific?

**Comment by WiXSL** [comment]
Of course, I don't say to remove the current way to do it but to add documentation about your solution here #3907 for cases where for example (quoting):

`... even if <Admin> accepts a function as child, this function can't execute hooks. So it's impossible, for instance, to have a dynamic list of resources based on a call to the dataProvider (since the dataProvider is only defined after the Admin component renders).
Many people use the Custom App approach just because of that, and they have to rewrite too much code.`

**Comment by fzaninotto** [comment]
Understood. A PR is welcome!
