### ISSUE TITLE
[DOCS]: Modifing input when another one changes example breaks the layout.

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4631]
The following docs example has the problem that inputs inside `OrderOrigin` component are shown as one, in the same row.

https://marmelab.com/react-admin/Inputs.html

**Would you need to update an input when another one changes**, use the `useForm` hook from `react-final-form`. For example, a country input that resets a city input on change.

```jsx
import React, { Fragment } from 'react';
import { useForm } from 'react-final-form';

const OrderOrigin = ({ formData, ...rest }) => {
    const form = useForm();

    return (
        <Fragment>
            <SelectInput
                source="country"
                choices={countries}
                onChange={value => form.change('city', null)}
                {...rest}
            />
            <SelectInput
                source="city"
                choices={getCitiesFor(formData.country)}
                {...rest}
            />
        </Fragment>
    );
};

const OrderEdit = (props) => (
    <Edit {...props}>
        <SimpleForm>
            <FormDataConsumer>
                {formDataProps => (
                    <OrderOrigin {...formDataProps} />
                )}
            </FormDataConsumer>
        </SimpleForm>
    </Edit>
);
```

**Comment by JulienMattiussi** [comment]
You're right as when you put many inputs inside a single FormDataConsumer, they are displayed in a row because of style applying on Parent component.

I think FormDataConsumer is not needed in this example using useForm.
Will check it.

**Comment by Kmaschta** [comment]
@JulienMattiussi Still on this one?

**Comment by jdemangeon** [comment]
@JulienMattiussi @Kmaschta Is there any news on that?

**Comment by fzaninotto** [comment]
I pushed cd856c8 to `master` by mistake. I reverted it in 84eff69ca.
