### ISSUE TITLE
warning: Cannot update a component (`ArrayInput`) while rendering a different component (`SelectInput`)

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#4632]
**What you were expecting:**
The following code should work without warnings.
```js
<ArrayInput source="tabs" resource={props.resource}
basePath={props.basePath} record={props.record}>
            <SimpleFormIterator labelSource="tabName" basePath={props.basePath} >
              <SelectInput source="template" label="Page tempate"
                choices={[{ id: 'tableau', name: 'Tableau Report' }]}
                initialValue="tableau"
              />
            </SimpleFormIterator>
          </ArrayInput>
```

**What happened instead:**
Received warning on chrome console.
```
Warning: Cannot update a component (`ArrayInput`) while rendering a different component (`SelectInput`). To locate the bad setState() call inside `SelectInput`, follow the stack trace as described in https://fb.me/setstate-in-render
    in SelectInput (at reportEdit.jsx:65)
    in div (created by FormInput)
    in FormInput (created by SimpleFormIterator)
    in section (created by SimpleFormIterator)
    in li (created by SimpleFormIterator)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SimpleFormIterator)
    in TransitionGroup (created by SimpleFormIterator)
    in ul (created by SimpleFormIterator)
    in SimpleFormIterator (at reportEdit.jsx:63)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by Arr
```

**Steps to reproduce:**
Create edit form with ```ArrayInput -> SimpleFormIterator ->SelectInput ``` and view console log

**Related code:**
It looks like the issue is with react 16.13.1 and final-form/react-final-form. https://github.com/final-form/react-final-form/issues/751

It appears the issue has been fixed react-final-form to 6.4.0. Please update to use react-final-form 6.4

**Environment**

* React-admin version:  3.3.3
* React version: 16.13.1
* Browser: Chrome 80.0.3987.122
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
The dependency on react-final-form is ^6.3.3. Nothing prevents you from upgrading this dependency on your side, so we don't need to do anything in react-admin.

**Comment by fzaninotto** [comment]
Also see #4572
