### ISSUE TITLE
Attempted import error: 'DisabledInput' is not exported from 'react-admin'.

### ISSUE THREAD

**Issue by Banyc** [marmelab/react-admin#4642]
**What you were expecting:**

'DisabledInput' should be exported from 'react-admin'.

**What happened instead:**

'DisabledInput' is not exported from 'react-admin'. And there came the error 
```
Failed to compile.

./src/people.js
Attempted import error: 'DisabledInput' is not exported from 'react-admin'.
```

**Steps to reproduce:**

Simply follow the instructions from <https://react-admin.com/docs/en/tutorial.html> but use `npm` rather than `yarn` in the entire procedure.

**Related code:**

in src/people.js

```javascript
// in src/people.js
import React from 'react';
// import { List, Datagrid, TextField } from 'react-admin';
import { List, Edit, Create, Datagrid, ReferenceField, TextField, EditButton, DisabledInput, LongTextInput, ReferenceInput, SelectInput, SimpleForm, TextInput } from 'react-admin';

export const PostList = (props) => (
    <List {...props}>
        <Datagrid>
            <TextField source="id" />
            <TextField source="name" />
            <TextField source="gender" />
            <TextField source="number" />
            <TextField source="health" />
        </Datagrid>
    </List>
);

const PostTitle = ({ record }) => {
    return <span>Post {record ? `"${record.name}"` : ''}</span>;
};

export const PostEdit = (props) => (
    <Edit title={<PostTitle />} {...props}>
        <SimpleForm>
            <DisabledInput source="id" />
            {/* <ReferenceInput label="User" source="userId" reference="users">
                <SelectInput optionText="name" />
            </ReferenceInput> */}
            <TextInput source="name" />
            <LongTextInput source="gender" />
        </SimpleForm>
    </Edit>
);

export const PostCreate = (props) => (
    <Create {...props}>
        <SimpleForm>
            {/* <ReferenceInput label="User" source="userId" reference="users">
                <SelectInput optionText="name" />
            </ReferenceInput> */}
            <TextInput source="name" />
            <LongTextInput source="gender" />
        </SimpleForm>
    </Create>
);
```

in src/App.js

```javascript
// in src/App.js
import React from 'react';
import { Admin, Resource } from 'react-admin';
// import jsonServerProvider from 'ra-data-json-server';
import fakeDataProvider from 'ra-data-fakerest';
// import { PostList } from './people';
import { PostList, PostEdit, PostCreate } from './people';

// const dataProvider = jsonServerProvider('http://jsonplaceholder.typicode.com');

const dataProvider = fakeDataProvider({
  people: [
      { id: 0, name: 'Alice', gender: 'female', number: '13131313', health: 'good'},
      { id: 1, name: 'Bob', gender: 'male', number: '181915915', health: 'good'  },
  ],
  comments: [
      { id: 0, post_id: 0, author: 'John Doe', body: 'Sensational!' },
      { id: 1, post_id: 0, author: 'Jane Doe', body: 'I agree' },
  ],
})

const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="people" list={PostList} edit={PostEdit} create={PostCreate}/>
    </Admin>
);

export default App;
```

**Other information:**

After I commented out `<DisabledInput source="id" />`, a new error occurred

```
Attempted import error: 'LongTextInput' is not exported from 'react-admin'.
```

**Environment**

* React-admin version: `^3.4.0`
* Last version that did not exhibit the issue (if applicable): This is the first time I use it
* React version: `^16.13.1`
* Browser: `chrome`
* Stack trace (in case of a JS error): It only shows "Failed to compile." The process seems to be still running

**Comment by djhi** [comment]
You've read the wrong documentation. react-admin.com is not owned by the core team, and contains **outdated** documentation. The correct documentation, hosted at https://marmelab.com/react-admin/Tutorial.html, does not contain `<DisabledInput>` or `<LongTextInput>`. Please update your bookmarks.

**Comment by pramit-marattha** [comment]
`Instead of DisabledInput component use <TextInput disabled source="id">`

![image](https://user-images.githubusercontent.com/37651620/101245046-4a566300-3732-11eb-9fa9-c1aff4382255.png)

**Comment by dylanh724** [comment]
> You've read the wrong documentation. react-admin.com is not owned by the core team, and contains **outdated** documentation. The correct documentation, hosted at https://marmelab.com/react-admin/Tutorial.html, does not contain `<DisabledInput>` or `<LongTextInput>`. Please update your bookmarks.

What to use in place of LongTextInput? I ran into this issue in 2021, as those docs are at the TOP of Google with no direction indicating it's not officially owned (that's at least not painstakingly obvious).

**Comment by AnettB** [comment]
> > You've read the wrong documentation. react-admin.com is not owned by the core team, and contains **outdated** documentation. The correct documentation, hosted at https://marmelab.com/react-admin/Tutorial.html, does not contain `<DisabledInput>` or `<LongTextInput>`. Please update your bookmarks.
> 
> What to use in place of LongTextInput? I ran into this issue in 2021, as those docs are at the TOP of Google with no direction indicating it's not officially owned (that's at least not painstakingly obvious).

Try TextInput
