### ISSUE TITLE
Docs searches always end up in version 3.1

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4643]
![screenshot 1](https://user-images.githubusercontent.com/8268610/78573872-9ba6ff00-77ff-11ea-9cd0-2a7270fcc6f7.jpg)
![screenshot2](https://user-images.githubusercontent.com/8268610/78573882-9f3a8600-77ff-11ea-8304-0533019c9415.jpg)

**Comment by fzaninotto** [comment]
Reproduced, thanks. I think we need more configuration on the search engine.

**Comment by jdemangeon** [comment]
Thanks @WiXSL for your feedback, a PR is on its way to correct our search indexing.

**Comment by fzaninotto** [comment]
Refs https://github.com/algolia/docsearch-configs/pull/1851

**Comment by jdemangeon** [comment]
Algolia PR is merged  and crawler as already indexed latest version pages :+1:

https://github.com/algolia/docsearch-configs/pull/1851

**Comment by WiXSL** [comment]
Thanks!
