### ISSUE TITLE
Comma in NumberInput not accepted with Firefox 74

### ISSUE THREAD

**Issue by kiad** [marmelab/react-admin#4646]
**What you were expecting:**
I expected to be able to type a percentage like "65,34", with a comma

**What happened instead:**
Once I type the comma, the whole input is erased.

**Steps to reproduce:**
I have set-up a small example : https://codesandbox.io/s/frosty-allen-xm38z with a "progress" field in the post element.
The progress field follow [the documentation example of parse/format](https://marmelab.com/react-admin/Inputs.html#transforming-input-value-tofrom-record) : it comes as 0-1.0 from the API, but is displayed and typed as 0-100 (which I have been doing for months without any issues).

**Other information:**
I noticed this issue since Firefox 74.0. Works well on Safari or Chrome.

**Environment**

* React-admin version: 3.4.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: Firefox 74.0

**Comment by Kmaschta** [comment]
This is related to how Firefox manages input type number, because it better handles langs.

I updated the documentation to better handle this case, thanks for the issue

**Comment by kiad** [comment]
Thank you. I tried in the Codesansbox to add the parseFloat but it still does not all to add a comma, and not a point anymore (point works previously).

**Comment by Kmaschta** [comment]
Firefox switches between a dot and a comma depending on the language defined on the HTML tag. (eg. a dot if `lang="en"` or a comma if `lang="fr"`)

You can overwrite the input languages by passing the following prop:

```jsx
<NumberInput source="progress" options={{ inputProps: { lang: "fr" } }} />
```

**Comment by kiad** [comment]
Thanks a lot, it works indeed (I've been reading [this](https://www.ctrl.blog/entry/html5-input-number-localization.html) in the meantime).
