### ISSUE TITLE
Round issues with NumberInput & parse/format

### ISSUE THREAD

**Issue by kiad** [marmelab/react-admin#4647]
**What you were expecting:**
I expect to be able to type a percentage like "70,50" with a configuration like [the documentation example of parse/format](https://marmelab.com/react-admin/Inputs.html#transforming-input-value-tofrom-record) : the number field comes as 0-1.0 from the API, but is displayed and typed as 0-100.

**What happened instead:**
Once I type the 7, it instantly display 7.0000000001 
I can't type 70 straight...

**Steps to reproduce:**
I have set-up a small example : https://codesandbox.io/s/frosty-allen-xm38z with a "progress" field in the post element.

**Other information:**
I have the same issue on Firefox, Safari, Chrome, though at first I thought it came from Firefox 74 (noticed this issue at the same time I noticed the comma issue...). I had no issue until early march.

If I try to round the value in format(), it prevents to type any point or comma, I don't see how I can fix this at this level as it is called at each character typed.

**Environment**

* React-admin version: 3.4.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: Firefox 74.0

PS : thanks a lot for your work on React-admin ! We're using it since last july, happy with it.

**Comment by Kmaschta** [comment]
In JavaScript, `0.07 * 100 = 7.000000000000001`, and there is nothing we can do about that!
Perhaps this is not the better example we can find. :p

![image](https://user-images.githubusercontent.com/1819833/78648841-e044a000-78bc-11ea-8237-e090e8b9fee9.png)

**Comment by kiad** [comment]
Thank you for the anwser. I understand there are some weird behaviours with floats :) What I don't understand is that it's been working for me during months, I've type dozens of times 70 percent (which in our case happens often...). I don't get what has changed recently and now it's really impossible to type a percentage in an input :/
I can't fix that in format/parse, unless there's a way not to call them at every character ?
Only solution I see is to convert from 0-1.0 to 0-100 and vice versa in the data provider directly (and round server-side), I'll try it.

**Comment by fzaninotto** [comment]
The right solution is to use integers, not floats, when you need precise calculations in JavaScript. 

https://stackoverflow.com/questions/2876536/precise-financial-calculation-in-javascript-what-are-the-gotchas/45551353#45551353

**Comment by kiad** [comment]
I see, thank you! And sorry for the non-related issues then...

**Comment by lortiz-daitan** [comment]
@kiad you can round the value to remove these decimal issues.
You can multiply and divided by 100 to add 2 decimal places in the result: `Math.round((value) * 100) /100` or to use `_.round(value, 2)` from lodash.

So, in the input, you can round the "0-100 value" with 2 dcimal places; and in the onChange, you can convert to 0-1, rounding with 4 decimal places
```
<input
  type="number"
  value={_.round(value * 100, 2) || undefined}
  onChange={(e) => setValue(_.round(e.currentTarget.value / 100, 4))}
/>
```
