### ISSUE TITLE
TextField with null value outputs "null" (as string)

### ISSUE THREAD

**Issue by danejorgensen** [marmelab/react-admin#4648]
**What you were expecting:**
If a TextField value is null, it should not render a value

**What happened instead:**
The null value gets converted into a string and is rendered as "null"

**Steps to reproduce:**
```
const record = { title: null };
const { queryByText } = render(
  <TextField record={record} source="title" />
 );
```

I think these changes are related to the addition of the emptyText property.   It looks like emptyText used to have a default value of '', but now it does not.

https://github.com/marmelab/react-admin/blob/054fd1c6d80a38b613e8d93c8e0aedecc98cad05/packages/ra-ui-materialui/src/field/TextField.tsx#L14

**Environment**

* React-admin version: 3.4.0
* Last version that did not exhibit the issue (if applicable):
* React version: latest
* Browser: chrome latest
* Stack trace (in case of a JS error):

**Comment by jdemangeon** [comment]
Thanks for the issue, it's a regression.
It is now fixed in #4661
