### ISSUE TITLE
ra-data-fakerest adds new items to ReferenceInput onChange

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#4664]
CodeSnadBox:
https://codesandbox.io/s/react-admin-referenceinput-example-x290t?file=/src/index.js

**Steps to reproduce:**

1.- Go to Posts and Edit any record 
     (NOTE: `Title` will change since it has the same source, I don't know if this is intended behaviour).

2.- Type number one (1) on Post input

3.- Click on `Title` ReferenceInput

You get duplicate items and a console error.

PS: This doesn't happen using `ra-data-json-server` as data provider in the same example.

**Environment**
react-admin version: 3.4.0
react version: 16.13.1
ra-data-fakerest: v3.2.2
Browser: Chrome v81

**Comment by jdemangeon** [comment]
I'm able to reproduce, thanks for the issue! :+1:

**Comment by manishsundriyal** [comment]
Just to confirm. Is this the issue?
<img width="715" alt="Screenshot 2020-04-18 at 11 54 28 PM" src="https://user-images.githubusercontent.com/24211507/79655562-37f1de00-81d0-11ea-80c7-5fdfd9518853.png">

**Comment by WiXSL** [comment]
Yes, that is the error i'm describing.

**Comment by manishsundriyal** [comment]
@WiXSL Thanks for such a quick confirmation. I will fix it.

**Comment by jdemangeon** [comment]
Hello @manishsundriyal ! 

Did you have time to fix the issue? Or have you an opened PR I can link to this issue?

**Comment by jdemangeon** [comment]
Changing the current record id from `<Edit />` is not a common use case and should not involve more time on debug.
I'm closing the issue.
