### ISSUE TITLE
Add data-provider to support any graphql schema with configuration

### ISSUE THREAD

**Issue by spetrunin** [marmelab/react-admin#4668]
**Is your feature request related to a problem? Please describe.**
I'm trying to use ra-data-graphql-simple provider, but it is too restricted about schema

what are the most inconvenient restrictions:

1. You have to define Meta query which strictly starts with an underscore
```graphql
type Query {
    allContacts: [Contact!]!
    _allContactsMeta: ListMetadata
}
```
languages like Go uses Capital letter to specify exported functions, so with such implementation in most of graphql go implementations you will be not flexible in code structuring cause all resolvers will be in the same folder

2. instead of single query you have 2 whenever it could be combined into return object like:
```graphql
type Query {
    allContacts: ContactsResponse!
}

type ContactsResponse {
  Contacts: [Contact!]!
  ListMetaData:   ListMetaData!
}
```
3. By convention, mutations accept a list of fields instead of single input
```graphql
type Mutation {
  updatePost(
    id: ID!
    title: String!
    views: Int!
    user_id: ID!
  ): Post
```
Whenever up to date approach is to use a corresponding input type like:
```graphql
input PostInput {
    title: String!
    views: Int!
    user_id: ID!
}

type Mutation {
  updatePost(
    id: ID!
    fields: PostInput!
  ): Post
}
```
4. ra-data-graphql-simple lacks of documentation
so it is hard to adopt it

**Describe the solution you'd like**
1) It would be good to have a configurable graphql-data-source to be able to tailor it to existing graphql apis

2) Make ra-data-graphql-simple more flexible in terms of configuration

**Additional context**
I'm ready to update ra-data-graphql-simple to be more flexible, but lack of knowledge hot it works will appreciate any help

**Comment by djhi** [comment]
Hi and thanks for the detailled issue. There are so many ways to build a graphql api that we can't possibly handle them all (Hasura, Prisma, your very own,etc.).

The two current graphql dataproviders are merely examples showing how to create your own and use the `ra-data-graphql` package which provides the primitives needed to do so.

Please take a look at this package and its documentation. It should be what you are looking for.

**Comment by fzaninotto** [comment]
Agreed, this is just like asking "please support any REST flavor". It's your responsibility as a developer to write that adapter part.
