### ISSUE TITLE
ra-data-graphql uses deprecated export graphql.introspectionQuery

### ISSUE THREAD

**Issue by ryanberckmans** [marmelab/react-admin#4670]
ra-data-graphql uses [introspectionQuery](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql/src/introspection.js#L1) from graphql-js. This export was removed here graphql/graphql-js@6b550192e0ce3b458abaec92e4c65d36eeafb7d0. It was renamed to `getIntrospectionQuery`.

Currently `yarn add ra-data-graphql` or `yarn add ra-data-graphql-simple` requires `yarn add graphql@14.5.8 --tilde` or it will fail compilation with:

```bash
./node_modules/ra-data-graphql/esm/introspection.js
Attempted import error: 'introspectionQuery' is not exported from 'graphql'.
```

**Comment by djhi** [comment]
Thanks for the report. Would you mind submitting a pull request to fix it?

**Comment by jdemangeon** [comment]
PR Merged! Thanks!  :+1:

**Comment by myhubproject** [comment]
export 'introspectionQuery' (imported as 'introspectionQuery') was not found in 'graphql'

**Comment by fzaninotto** [comment]
@myhubproject If you found a bug, please open a new issue by following the issue template
