### ISSUE TITLE
Side menu scroll with data 

### ISSUE THREAD

**Issue by ravi-pandit14** [marmelab/react-admin#4684]
**What I Want**
I want to fixed side menu it should not scrolling with my data.

**Description**
I have installed react-admin in my react web App project but i am facing side menu scrolling issue. Side menu is scrolling with data. 

**Steps to reproduce:**
I have following the same example that is providing by react-admin and in this example issue can be reproduce on dashboard.
If we will scroll the dashboard then side menu is also scrolling.
**Link to reproduce**:
 [Link](https://marmelab.com/react-admin-demo/#/)

**Environment**

* React-admin version: ^3.3.1
* React version:^16.13.0
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for the request. It's a good idea indeed.

**Comment by ravi-pandit14** [comment]
@djhi Any update for this issue??

**Comment by djhi** [comment]
No. Feel free to open a pull request if you have time to work on this. It's not a priority for us

**Comment by nitishmittal1990** [comment]
@djhi I will take up this issue.

**Comment by emericspiroux** [comment]
Hi ! 

It can be cool if side menu doesn't scroll with content when scrolling X too !

Can  #4753 PR be implemented with ? @WiXSL Thank you very much for your PR ! 👍

**Comment by JochenFerchland** [comment]
Anything new to this request?
