### ISSUE TITLE
ReferenceInput Cannot read property 'getList' of undefined

### ISSUE THREAD

**Issue by williamwxz** [marmelab/react-admin#4687]
**What you were expecting:**

By following [React Admin CustomApp](https://marmelab.com/react-admin/CustomApp.html)
**What happened instead:**

When using ReferenceInput, it will never call dataProvider.getMany(). 
However, if I just change ReferenceInput to ReferenceArrayInput, it works, it will call dataProvider.getMany()! But I don't want it to be an array. 

**Steps to reproduce:**

**Related code:**

`<Route exact path={"/" + ROUTES.CAMPAIGN_ENDPOINT + "/create"}
                                render={({ staticContext, ...routeProps }) => <CampaignCreate resource={ROUTES.CAMPAIGN_ENDPOINT} basePath={routeProps.match.url} {...routeProps} />} />`

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
export function CampaignCreate(props) {
    return (
        <Create
            hasList={true}
            hasEdit={false}
            hasShow={false}
            hasCreate={true}
            {...props}>
            <SimpleForm>
                {/* If I change to  ReferenceArrayInput, it works*/}
                <ReferenceArrayInput label="Product to be promoted"
                    source="asin" reference="products" required={true} allowEmpty={true}
                >
                    <SelectInput optionText="name" />
                </ReferenceArrayInput>
                <NumberInput label="Discounted Price" source="discounted_price" required={true} step="0.01" />
                <SelectInput source="coupon_column" choices={ALPHA} defaultValue="0" />
                <FileInput source="file" label="CSV files" accept="text/csv" required={true}>
                    <FileField source="src" title="title" />
                </FileInput>
            </SimpleForm>
        </Create>
    );
}
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by sfenig** [comment]
@fzaninotto FWIW, this is failing for me too.  Works as array.  I'm using a custom DataProviderContext to set DataProvider.  Wondering if  this is an issue that referenceInput is not using hooks and so can't find the dataProvider.

**Comment by sfenig** [comment]
> @fzaninotto FWIW, this is failing for me too. Works as array. I'm using a custom DataProviderContext to set DataProvider. Wondering if this is an issue that referenceInput is not using hooks and so can't find the dataProvider.

For anyone else that stumbles on to this one.  Maybe reference input is not the right approach.  Using useQuery to populate the choices did the job for me:

```
import React from 'react';
import { SelectInput, useQuery, Loading, Error } from 'react-admin';
export default props => {
  const { data, loading, error } = useQuery({
    type: 'getList',
    resource: props.resource,
    payload: {
      pagination: { page: 1, perPage: 100 },
      sort: { field: 'id', order: 'DESC' },
      filter: {},
    },
  });
  if (loading) return <Loading />;
  if (error) return <Error />;
  if (!data) return null;

  return <SelectInput choices={data} {...props} />;
};
```

**Comment by fzaninotto** [comment]
`useReferenceInputController` currently doesn't use the dataProvider hooks. There is already an issue to track that legacy code migration task: #4531
