### ISSUE TITLE
Need a demo for local MySQL as data provider

### ISSUE THREAD

**Issue by Banyc** [marmelab/react-admin#4689]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when DataProvider cooperates with MySQL. I believe an official demo is needed to give the best practice.

**Describe the solution you'd like**

To provide a demo of MySQL as a data source for the react-admin project.

**Comment by Banyc** [comment]
According to the description on <https://marmelab.com/react-admin/DataProviders.html>,

> Tip: In version 1, react-admin was called admin-on-rest (AOR), and developers shared Data Providers for even more backends. Due to breaking changes in v2, these providers are no longer working. Fortunately, Data Providers aren’t complex pieces of code, and using legacy Data Provider with a recent react-admin version requires minimal changes. If you are a maintainer of one of these projects, we would warmly welcome an upgrade.

> DynamoDb: abiglobalhealth/aor-dynamodb-client
> Epilogue: dunghuynh/aor-epilogue-client
> Parse Server: leperone/aor-parseserver-client
> Xmysql: soaserele/aor-xmysql

It seems that React-admin is no longer supported for MySQL.

**Comment by fzaninotto** [comment]
React-admin requires an HTTP API to work with. MySQL isn't an HTTP server, it's a Database. To use MySQL with react-admin, you need to setup an API. xmysql is one utility offering an API based on a SQL schema - among others. 

React-admin doesn't support any database directly. It supports every database, provided there is an API in front of it. 

As for "I need a demo", I understand your need, but it's not our job to provide examples for every possible backend. I invite you to ask your question on StackOverflow.

**Comment by Ben888GitHub** [comment]
> React-admin requires an HTTP API to work with. MySQL isn't an HTTP server, it's a Database. To use MySQL with react-admin, you need to setup an API. xmysql is one utility offering an API based on a SQL schema - among others.
> 
> React-admin doesn't support any database directly. It supports every database, provided there is an API in front of it.
> 
> As for "I need a demo", I understand your need, but it's not our job to provide examples for every possible backend. I invite you to ask your question on StackOverflow.

That means, we need to have sth like nodejs backend to make it work?

**Comment by fzaninotto** [comment]
yes.
