### ISSUE TITLE
Multi-language content editing

### ISSUE THREAD

**Issue by TheMisir** [marmelab/react-admin#4690]
**Is your feature request related to a problem? Please describe.**
I wanted to use react-admin as admin interface because I couldn't maintain our own internal admin interface library. In "products" section we have some fields which translated to different languages.

```json
{
  "id": "4857",
  "sku": "sku_example",
  "price": 13.99,
  "translations": [
    {
      "languageId": "en",
      "name": "coffee",
    },
    {
      "languageId": "ru",
      "name": "кофе"
    }
  ]
}
```

Is there any exiting components that able to used for editing this kind of contents?

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/29130291/79452289-f6f3a100-7ff8-11ea-9427-49fcbedab519.png)

I'm currently adding tabs to edit/create tab but if there are other ways to achieve that that might be cool too.

**Comment by fzaninotto** [comment]
No, there is no such content, you'll have to develop it yourself.
