### ISSUE TITLE
Ability to alter FileInput with onDrop event.

### ISSUE THREAD

**Issue by oleg-andreyev** [marmelab/react-admin#4695]
**A bit of context**
All images have EXIF data and the most interesting is an `Orientation` attribute when Image is rotated using any software (Window Preview, Mac Finder and etc.) it does not modify `Orientation`, when User will try to drag-n-drop image into FileInput, "preview" will be rotated in the original position.
![image](https://user-images.githubusercontent.com/1244112/79502517-62109800-8038-11ea-9773-4abaaff479cb.png) while in Finder it looks like 
![image](https://user-images.githubusercontent.com/1244112/79502588-7f456680-8038-11ea-9380-7aef67904fc5.png)

**Proposal**
- Move the "onDrop" event before we trigger "onChange" in FileInput to allow alter images
- Allow "onDrop" return `Promise API` because manipulating `File Blob` requires `FileReader API` 

**Code may look like**
```js
const onDrop = (newFiles, rejectedFiles, event) => {
    const updatedFiles = multiple ? [...files, ...newFiles] : [...newFiles];

    const emitChange = (updatedFiles) => {
        if (multiple) {
            onChange(updatedFiles);
        } else {
            onChange(updatedFiles[0]);
        }
    }

    if (options.onDrop) {
        const result = options.onDrop(newFiles, rejectedFiles, event);
        if (result instanceof Promise) {
            result.then((files) => {
                emitChange(files);
            })
        } else {
            [newFiles, rejectedFiles] = result;
            emitChange(newFiles);
        }
    }
};

```

P.S. It's possible to do it right now, but it requires emitting the `change` event for second time.

**Comment by djhi** [comment]
Interesting. Thanks for bringing that up. Would you like to work on a PR for that ?

**Comment by fzaninotto** [comment]
This enhancement request hasn't gained enough interest to get a PR from the community. As we canot keep all feature requests open, I'm closing it. 

If you feel like working on this feature, we'd love a PR!
