### ISSUE TITLE
Edit view resets itself after a fixed amount of time

### ISSUE THREAD

**Issue by esistgut** [marmelab/react-admin#4698]
**What you were expecting:**
The edit forms should not wipe the modified data and replace it with the original one.

**What happened instead:**
After a fixed amount of time (I suspect this one https://github.com/marmelab/react-admin/blob/fa62eaa42e11fed3fd9fc820d4aa47ec3fab790e/packages/ra-core/src/util/getFetchedAt.ts#L4 ) the form is resetted.

**Steps to reproduce:**
Edit a field on the demo, like the `Reference` field in https://marmelab.com/react-admin-demo/#/products/0/details
Leave the window open without saving for about 10 minutes.

**Comment by fzaninotto** [comment]
Good catch! it's an important bug. We should not refresh the view if a form is tainted.

**Comment by fzaninotto** [comment]
as the `useRefreshWhenVisible` hook isn't connected to any other part of the app, I believe the solution is to have FormWithRedirect set a global flag to true when tainted, then reset it upon leave. `useRefreshWhenVisible` should not trigger if this flag is true.
