### ISSUE TITLE
Provide a way to reset admin.loading to 0

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#4704]
**Is your feature request related to a problem? Please describe.**

After upgrading the `dataProvider` for v3, I am having issue with the refresh button losing is state.

The cause to this may be because of  a failing request, I have two kind of failing request in my application :

1. I must press the login button twice in order to get to the authentication pass. This because I must fail one request in order to get the cookie from the server, then renew the request with the cookie. My old login provider normally did take care of that and with the new `dataProvider` and v3,  it seems that `ra-core` is catching the error and abort the authentication. I believe this can be a reason why I have `admin.loading > 0` after loading, causing the application loader to be spinning  infinitly on the dashboard .
2. Another cause could be the `401` expired token causing the redirect to login without resetting the `admin.loading` on login page redirection. 

So far, it happen when either: 

- The first failed login request fail (if the cookie is already there, then the bug is not there)
- The `401` cause redirect to login and the `loading` state is not reset

![image](https://user-images.githubusercontent.com/1866564/79693854-5ce85e80-826d-11ea-83b8-ae24d3005bb4.png)

**Describe the solution you'd like**

So far, I must, of course, find a way to prevent having to click twice on the login button, but also find a way to fix the application button refresh/loading indicator.  

Currently, we are forced to refresh our app after login in order to get the refresh button available.

I have tried to use `clearState` upon login screen redirection but that doesn't reset the loading to 0.

This ticket is a request to add a `resetLoading()` action into `react-admin`.

I know it's a XY problem, but that will be a small addition and give us more fined control over this button (currently we have none and that's also good unless it can break in some people apps)

**Describe alternatives you've considered**

Nothing yet

**Comment by djhi** [comment]
Thanks for the detailed issue. I'm afraid a `resetLoading` action would be a poor solution for your issue and I'd rather like to figure out exactly why it is happening and how we could possibly prevent it.

It would be really great if you could try to reproduce the issue in a codesandbox

**Comment by fzaninotto** [comment]
You can still dispatch a `FETCH_END` action manually to stop the loading state. We won't implement a `resetLoading` action as it's just ignoring the core problem and fixing only the side effect.

**Comment by kopax** [comment]
@djhi I have no clue about the exact problem, just that the call should happen within react admin and for some reasons it doesn't. I haven't touch anything, it's a bar react admin app but with a lot of resources. 

@fzaninotto I completely agree. Calling `FETCH_END` will decrement the `loading` value by one, I can read the state and call this as many times as I need, this can solve the issue and it's "kind of" ok solution for the moment. 

I'll add more information when I'll find the real cause. Thanks again for your time.
