### ISSUE TITLE
Expand not responding in custom query Datagrid

### ISSUE THREAD

**Issue by guilleironhack** [marmelab/react-admin#4706]
**What you were expecting:**
When using a `Datagrid` to display a custom query result (following the example in the documentation), I expect that I can use the `expand` feature.

**What happened instead:**
The expand icon is displayed, but nothing happens upon clicking it.

**Steps to reproduce:**
 - Create a `Datagrid` outside of a `List` or any other component that injects the data
 - Provide your own data (`ids` and `data`) to the component
 - Add a `expand` component to the `Datagrid`
 - Try to expand a row

**Related code:**
The simple example wasn't loading for me in codesandbox, so I had to reproduce it in the tutorial sandbox. Sorry for that.

See the users list:
https://codesandbox.io/s/jolly-dirac-7lo01?file=/src/users.js

**Environment**

* React-admin version: 3.4.2
* Last version that did not exhibit the issue (if applicable): 3.2.4
* React version: 16.13.1
* Browser: Chrome 80.0.3987.163

**Comment by djhi** [comment]
That's because the expand feature stores its state per resource in redux. Just add a `resource` prop on the `Datagrid` (it's usually injected by the `List` component) and it will work.

See https://codesandbox.io/s/eloquent-jennings-2n57h?file=/src/users.js

**Comment by fzaninotto** [comment]
which example in the documentation were you referring to?

**Comment by guilleironhack** [comment]
Thanks for the answer!

@fzaninotto The example I referred to is in the `DataGrid` documentation, the very last tip before the `SimpleList` component section.
