### ISSUE TITLE
initialValue is not used on child fields of SimpleFormIterator

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#4709]
**What you were expecting:**
I have a property that is an array of objects. When array element exists, but a property is missing on the object, Field's initial value should work

**What happened instead:**
Field is empty (initial value is not assigned)

**Steps to reproduce:**

- Go to https://codesandbox.io/s/adoring-morning-54qgk?file=/src/posts/PostEdit.js:3462-3480
- To to post edit screen and edit record with post ID=1 (miscelaneous tab); in the sandbox, it url is https://54qgk.csb.app/#/posts/1/2
- Notice how initialValue was not applied to ZZZ field. 

**Related code:**
```js
        <ArrayInput source="backlinks">
          <SimpleFormIterator>
            <DateInput source="date" />
            <TextInput source="url" />
            <TextInput source="zzz" initialValue="ZZZZZ" defaultValue="qqqqq" />
          </SimpleFormIterator>
        </ArrayInput>
```
![image](https://user-images.githubusercontent.com/48455289/79818072-83c99200-834c-11ea-83d6-f05a33e7f77a.png)

Notice, however that initialValue field is honored when creating a new record
![image](https://user-images.githubusercontent.com/48455289/79818117-a0fe6080-834c-11ea-9fff-ce927e725519.png)

**Other information:**
During troubleshooting, i noticed that FieldArray children are not honoring default values when placed into FormWithRedirect; however, I confirmed that the same code worked in native react (outside of react-admin; see attached testApp.txt file, which contains App component that can be rendered in react app) 
[testApp.txt](https://github.com/marmelab/react-admin/files/4507306/testApp.txt)

)
```js
import React from 'react';
import { FieldArray } from 'react-final-form-arrays';
import { Field } from 'react-final-form';
import { Edit, FormWithRedirect } from 'react-admin';
import { default as _ } from 'lodash';

const ReportEditForm = () => {
  return (
    <React.Fragment>
      <FieldArray name='a1'>
        {({ fields }) => {
          return fields.map((name) => (
            <div key={name}>
              <Field name={`${name}.a1`} component='input' placeholder='a1' initialValue='def.a1' />
            </div>
          ));
        }}
      </FieldArray>
    </React.Fragment>
  );
};

const ReportEdit = (props) => {
  return (
    <Edit {...props} undoable={false} title='Edit report'>
      <FormWithRedirect render={ReportEditForm} {...props} />
    </Edit>
  );
};

export default ReportEdit;
```

**Environment**

* React-admin version: 3.4.1
* Last version that did not exhibit the issue (if applicable):

**Comment by panfiva** [comment]
It appears the issue is caused by ```useInitializeFormWithRecord``` function called from ```FormView``` function at https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/FormWithRedirect.tsx


Suppose the initial data (api data) is 
```json
{"data": [{ "child_attr_1": "ar_1", "id":1 }]}
```
If form includes "data" as array reference, then useInitializeFormWithRecord will call form.change(key, record[key]) command on key="data"; this, in turn, will remove default values from "data".child_attr_1. 
```
<React.Fragment>
  <FieldArray name='data'>
    {({ fields }) => {
      return fields.map((name, index) => (
        <div key={name}>
          <Field name={`${name}.child_attr_1`} component='input' placeholder='child_attr_1' />
          <Field
            name={`${name}.child_attr_2`}
            component='input'
            placeholder='child_attr_2'
            initialValue='def.child_attr_2'
          />
        </div>
      ));
    }}
  </FieldArray>
</React.Fragment>
```



Note:  after I commented out line 25 and added console.log statement, the default value was honored as seen in the second image below.

![image](https://user-images.githubusercontent.com/48455289/79906047-c33fbf00-83dc-11ea-93d7-e3f9154a154d.png)



![image](https://user-images.githubusercontent.com/48455289/79905515-ffbeeb00-83db-11ea-9292-3f71132782bd.png)

**Comment by panfiva** [comment]
I do not know the intent behind ignoring default values in the form; my guess on fixing the issue: we need to read current values of the field and, if null, update them with default values on update; otherwise, keep the current value; We will also need to make sure that parent elements are processed before child elements; that means we need to sort registeredFields (line 13 in the screen print above ) so that parent elements appear before children elements.

**Comment by panfiva** [comment]
I have updated sample applications to only include one record that displays the issue 

### Steps to reproduce:

- Go to https://codesandbox.io/s/adoring-morning-54qgk?file=/src/posts/PostEdit.js:3462-3480
- To to post edit screen and edit record with post ID=1 (miscelaneous tab); in the sandbox, it url is https://54qgk.csb.app/#/posts/1/2
- Notice how initialValue was not applied to ZZZ field.

**Comment by fzaninotto** [comment]
Bug confirmed, fix incoming. Thanks for the report.
