### ISSUE TITLE
Filters require to use SearchInput as first Input to render properly

### ISSUE THREAD

**Issue by frisi** [marmelab/react-admin#4710]
**What you were expecting:**
Adding Inputs to `<Filter>` as suggested in the documentation (https://marmelab.com/react-admin/List.html#filtering-the-list) should suffice to get a nice layout

**What happened instead:**

The online demo uses `SearchInput` as the fist input. If we remove the SearchInput (in the screenshot simply removed from the DOM), add some Filters and reduce page width the layout is broken (as other inputs do not have `margin-top:32px` they have no visual padding to the title-bar)

https://github.com/marmelab/react-admin/blob/52a4ca810eebb1eea25e900392432b14024f8097/packages/ra-ui-materialui/src/input/SearchInput.tsx#L13

Link to Demo: https://marmelab.com/react-admin-demo/#/commands?displayedFilters=%7B%22customer_id%22%3Atrue%2C%22returned%22%3Atrue%2C%22date_lte%22%3Atrue%7D&filter=%7B%22status%22%3A%22ordered%22%7D&order=DESC&page=1&perPage=25&sort=date

![grafik](https://user-images.githubusercontent.com/1120517/79875751-5df2ca80-83ea-11ea-895d-d56b720d8a72.png)

**Environment**

* React-admin version: 3.4.2
* Last version that did not exhibit the issue (if applicable): 3.3.
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting

**Comment by frisi** [comment]
sure thing ;-)
