### ISSUE TITLE
custom react-final-form in example does not support values as a parameter

### ISSUE THREAD

**Issue by NlVEK** [marmelab/react-admin#4712]
**What you were expecting:**
the example from react-final-form looks like: 
`render={({ handleSubmit, form, submitting, pristine, values }) => (<some field>...`
(copied from https://github.com/final-form/react-final-form/blob/master/examples/simple/index.js)
the example here is:
`render={formProps => (<myinput>...`

**`What happened instead:**
I can pass and render the defaultvalue from record inside <input>, but it is not listened by onChange function by final-form

**Comment by NlVEK** [comment]
My <input> is rendered with a function so i wonder if that causes the issue

**Comment by djhi** [comment]
Please follow the issue template

**Comment by NlVEK** [comment]
> Please follow the issue template

updated

**Comment by fzaninotto** [comment]
Your question concerns react-final-form rather than react-admin. We can't provide support for all the third-party libraries used in react-admin, so I suggest you ask that question on their repository.
