### ISSUE TITLE
initialValue in SelectInput component causes warning

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#4716]
**What you were expecting:**
initialValue passed to SelectInput should not cause warnings. The warnings are caused by the fact that function ```sanitizeRestProps``` at ```ra-ui-materialui\src\input\SelectInput.tsx```  is missing ```initialValue``` property in the list of sanitized properties

**What happened instead:**
![image](https://user-images.githubusercontent.com/48455289/80048148-f796a680-84d4-11ea-9b5b-61bd85b9ace9.png)

**Steps to reproduce:**
Create an expansion pannel and observe errors in console.log
```js
    <ExpansionPanel>
        <ExpansionPanelSummary>Summary</ExpansionPanelSummary>
        <ExpansionPanelDetails>
          <Box mr={{ xs: 0, md: '0.5em' }}>
            <SelectInput
              source={'template'}
              label='Page tempate'
              validate={required()}
              choices={[{id:'tableau', name:'Tableau'}, {id:'tableau2', name:'Tableau2'}]}
              initialValue='tableau'
            />
          </Box>
        </ExpansionPanelDetails>
      </ExpansionPanel>
```

**Related code:**
function sanitizeRestProps at ra-ui-materialui\src\input\SelectInput.tsx  should include initialValue in addition to defaultValue.

**Environment**

* React-admin version: 3.4.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting
