### ISSUE TITLE
Empty values of object in an array are not sanitized by `sanitizeEmptyValues`

### ISSUE THREAD

**Issue by armellarcier** [marmelab/react-admin#4726]
Here is my input :

`<TextInput source={"i18n[0].content"} />`

The record looks like

```
{
    id: 1,
    i18n: [{
        language_id: "fr",
        content: "Mon texte",
    }, {
        language_id: "en",
        content: "My text",
    }]
}
```

**What you were expecting:**

When the input has a value, it is sent to dataProvider.

When it is empty, the key is not sent at all.

I'd expect the sent record to be:

```
{
    id: 1,
    i18n: [{
        language_id: "fr",
        content: "",
    }, {
        language_id: "en",
        content: "",
    }]
}
```

or

```
{
    id: 1,
    i18n: [{
        language_id: "fr",
        content: null,
    }, {
        language_id: "en",
        content: null,
    }]
}
```

**What happened instead:**

The content of the actual sent record with an empty content field is:

```
{
    id: 1,
    i18n: [{
        language_id: "fr",
    }, {
        language_id: "en",
    }]
}
```

**Steps to reproduce:**
Just configure an input with array access

I'm creating a sandbox example

**Comment by fzaninotto** [comment]
We're delegating form handling to react-final-form. I suggest you ask your question on their repository.

**Comment by Benew** [comment]
Thanks @fzaninotto I did but the behavior of final-form differs from that of ra : final-form does not populate data props for empty values, while ra does, but only when the `source` prop has no `.` in it.
I guess you figured a workaround for https://github.com/final-form/react-final-form/issues/430 ?

**Comment by Benew** [comment]
So actually I think this should be addressed in `packages/ra-core/src/form/sanitizeEmptyValues.ts`

```

/**
 * Because final-form removes undefined and empty string values completely
 * (the key for the empty field is removed from the values), we have to check
 * whether this value was initially provided so that it is correctly sent to
 * the backend.
 * @see https://github.com/final-form/react-final-form/issues/130#issuecomment-493447888
 *
 * @param initialValues The initial values provided to the form
 * @param values The current form values
 */
const sanitizeEmptyValues = (initialValues: object, values: object) => {
```

The original comment at https://github.com/final-form/react-final-form/issues/130#issuecomment-493447888 states that
> Note: this doesn't work for nested properties

**Comment by Benew** [comment]
It has been addressed for objects, just not for arrays. See the current reducer :

```
if (values[key] instanceof Date || Array.isArray(values[key])) {
                acc[key] = values[key];
            } else if (
                typeof values[key] === 'object' &&
                typeof initialValues[key] === 'object' &&
                values[key] !== null
            ) {
                acc[key] = sanitizeEmptyValues(initialValues[key], values[key]);
            }
```

**Comment by Benew** [comment]
@fzaninotto can you reopen this? I can rename the issue to reflect what it really is.

**Comment by fzaninotto** [comment]
Right, reopening and marking this as a bug. A PR is welcome!
