### ISSUE TITLE
Sidebar "size" and "closedSize" prop are not being used.

### ISSUE THREAD

**Issue by klendi** [marmelab/react-admin#4728]
**What you were expecting:**
When I passed size prop to sidebar it didn't work, when I took a look at the code size and closedSize was not being used at all. Instead values from theme was being used.

What I did to make it work was inside theme I added sidebar prop with width inside.
`
export const lightTheme = {
    sidebar: {
        width: "15em"
    }}
`

https://github.com/marmelab/react-admin/blob/933c8de74e3e9eab1c7930ecb02ee8ed92f110f3/packages/ra-ui-materialui/src/layout/Sidebar.js#L52

**Environment**

* React-admin version: 3.0.0

**Comment by fzaninotto** [comment]
This is explained in the migration guide:

https://github.com/marmelab/react-admin/blob/master/UPGRADE.md#the-sidebar-width-must-be-set-through-the-theme

The props are kept in the code to avoid warnings in the console.
