### ISSUE TITLE
Ability to set <DateField/> <DateInput/>'s locales property globally 

### ISSUE THREAD

**Issue by janakact** [marmelab/react-admin#4732]
**Is your feature request related to a problem? Please describe.**
React admin allows you to set Date locales at the component when you use the DateField and DateInput.

```jsx
<DateField source="publication_date" locales="fr-FR" />
// renders the record { id: 1234, publication_date: new Date('2017-04-23') } as
<span>23/04/2017</span>
```
but most of the time we don't need to set it on the component, rather we need to configure it globally. Is there a way to set it globally?

**Describe the solution you'd like**
Using i18n provider's locale for Date format will be ideal. 

**Describe alternatives you've considered**
Also I tried overriding Date.toLocaleDateString() but didn't work as well.
I tried setting default locale of the i18n provider, but looks like it is only considered for translation and not for date formatting.

**Additional context**

**Comment by djhi** [comment]
Create your own component with your own defaults ?
https://marmelab.com/blog/2019/03/27/supplying-your-own-defaults-to-react-admin.html

**Comment by janakact** [comment]
@djhi Thank you very much.
