### ISSUE TITLE
ReferenceInput Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by MarkLyck** [marmelab/react-admin#4734]
ReferenceInput works great for all references that has a "name" column.

However with any references that doesn't have the default "name" it doesn't work and throws the above error.

**What you were expecting:**
To show references with the correct filter.

**What happened instead:**

```
Cannot read property 'match' of undefined
The above error occurred in the <Downshift> component:
    in Downshift (created by AutocompleteInput)
    in AutocompleteInput (created by EditView)
    in ReferenceInputView (created by ReferenceInput)
    in ReferenceInput (created by EditView)
```

**Steps to reproduce:**
Create a ReferenceInput with AutoComplete in an EditView
Set up a table with column name
set up a table with column ssid_name and no column "name"
Set up Resources from both tables in React Admin

table references with column "name" will work
table references with column "ssid_name" won't work

The network request and filter works just fine, and it returns 25 rows of the table it's supposed to reference. But something in React-Admin doesn't accept it and throws the above error.

The error only occours once the network request response comes in.

**Related code:**
```
    let referenceSource: string = 'id'; // use id by default
   
    if (referenceFieldNames.includes('name')) {
       // if a "name" column exists on the other table use it
      referenceSource = 'name';
    } else if (referenceFieldNames.includes('ssid_name')) {
      // if a "ssid_name" column exists on the other table use that
      referenceSource = 'ssid_name';
    }

    return (
      <ReferenceInput
        key={field.name}
        source={field.name}
        reference={field.referenceTable}
        filterToQuery={(searchText: string) => {
          if (!searchText) return {};
          const filter = {};
          filter[referenceSource] = searchText;
          return filter;
        }}
        allowEmpty
      >
        <AutocompleteInput optionsText={referenceSource} />
      </ReferenceInput>
    );
```

**Other information:**
If this is not a bug. Please add a more helpful error text than just "Cannot read property 'match' of undefined"

MY references work with most of my tables, just the ones that don't have name fails...

Here's a screenshot of the successful network request of the reference table that has "id" and "ssid_name" columns

<img width="1146" alt="Screen Shot 2020-04-28 at 3 58 07 PM" src="https://user-images.githubusercontent.com/6841110/80531783-26939900-8969-11ea-85dc-5e68399fa149.png">

The error occurs both when the record I'm editing has a value or it's empty.

* React-admin version: 3.4.1
* React version: 16.13.1
* Browser: Chrome

**Comment by fzaninotto** [comment]
I can't really determine if this is a bug without the complete code. Can you please for [the react-admin CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and tweak it to reproduce your bug?

Also, your snipper shows you're using `optionsText` instead of `optionText`, could it be the culprit?

**Comment by fzaninotto** [comment]
No news for about a month, closing.
