### ISSUE TITLE
Router issue with Form values

### ISSUE THREAD

**Issue by AstroNet-K2** [marmelab/react-admin#4737]
**What you were expecting:**
The tabbed form should retain the values entered while navigating across the tabs on Create and Edit screens.

**What happened instead:**
While navigating across the forms, the values keyed-in are not being retained and the form text boxes are becoming blank upon returning to the tab.

**Steps to reproduce:**

- Fill in the values in the first tab and navigate to the second tab and fill in the values there.
- Come back to the first tab and you will already notice that the entered values are gone.
- If you go to second tab now, values there are also already gone.

**Related code:**
https://codesandbox.io/s/stupefied-elgamal-q59us
(please goto `/posts` and go to the create flow to reproduce the behavior for the two tabs there)

**Other information:**
We must use the BrowserRouter at the main navigation to enable other routing purposes related to Okta and other routes. On local environments, overriding FormTabs with MemoryRouter seems retaining the values while navigating across the tabs but the Save functionality is not working (Save button wouldn't respond to the clicks), so trying other Routers from react-router seems not an option.

This behavior was earlier reported by me already (https://github.com/marmelab/react-admin/issues/4353) but by then, I was not sure what is the exact reason for this issue. Upon further investigation, I was able to understand that this issue for FormTabs is specifically happening when react-router routing is applied at the root pages. Like I explained earlier, I noticed a warning **You cannot change <Router history>** during navigating across the tabs.

**Environment**
Latest versions, pls refer to package.json from above example.

**Comment by fzaninotto** [comment]
The `<Admin>` component doesn't support being included in an existing `<Router>`, as in your example. Check [the "Including React-Admin In Another Application" doc chapter](https://marmelab.com/react-admin/CustomApp.html) for a guide about how not to use `<Admin>` in this case.

**Comment by AstroNet-K2** [comment]
Thanks @fzaninotto. So how to accommodate the Okta in that case bcz it needs router to be there.
Please check https://developer.okta.com/quickstart-fragments/react/default-example/ where we need to have this flow, code snippet from above example as below.

```
const App = () => { 
  return (
    <Router>
      <Security {...config}>
        <Route path='/' exact={true} component={Home}/>
        <Route path='/implicit/callback' component={LoginCallback}/>
      </Security>
    </Router>
  );
};
```

**Comment by fzaninotto** [comment]
For "how to" questions, please use StackOverflow - this issue trackers is only for react-admin bugs.

**Comment by panfiva** [comment]
@AstroNet-K2 , did you find a way to integrate react-admin with Okta? if yes, can you post a link here?

**Comment by AstroNet-K2** [comment]
> 
> 
> @AstroNet-K2 , did you find a way to integrate react-admin with Okta? if yes, can you post a link here?
We followed  https://developer.okta.com/quickstart-fragments/react/default-example/
