### ISSUE TITLE
React Admin Tutorial Documentation - dataProvider endpoint is incorrect

### ISSUE THREAD

**Issue by spitznasio** [marmelab/react-admin#4745]
**What you were expecting:**
The react admin tutorial demo results in an error when trying to GET users from jsonplaceholder api

**What happened instead:**
No data return

**Steps to reproduce:**
Follow the steps here
https://marmelab.com/react-admin/doc/3.0/Tutorial.html

**Related code:**
The REST call does not work because the dataProvider end point is using http and needs to use https

Incorrect
```
const dataProvider = jsonServerProvider('http://jsonplaceholder.typicode.com');
```
Correct with https
```
const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');
```
* React-admin version: 3.0

**Comment by fzaninotto** [comment]
You're reading an old version of the documentation. Check the latest one instead: https://marmelab.com/react-admin/Tutorial.html
