### ISSUE TITLE
React does not recognize the `permanentFilter` prop on a DOM element and Invalid value for prop `exporter` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.

### ISSUE THREAD

**Issue by dhavalk-simform** [marmelab/react-admin#4747]
**What you were expecting:**
Output is not affected because of this warning.
**What happened instead:**
Output is as expected

**Steps to reproduce:**
I've overridden list action as described [here](https://marmelab.com/react-admin/List.html#actions) to add custom create button.

```
const ListActions = props => {
  const {
    resource,
    showFilter,
    displayedFilters,
    filterValues,
    filters
  } = props;
  return (
    <TopToolbar className={props.className} {...sanitizeListRestProps(props)}>
      {filters &&
        cloneElement(filters, {
          resource,
          showFilter,
          displayedFilters,
          filterValues,
          context: "button"
        })}

      {/* <CreateButton basePath={props.basePath} /> */}

      <CreateFirebaseUser />

      <ExportButton
        disabled={props.total === 0}
        resource={props.resource}
        sort={props.currentSort}
        filter={{ ...props.filterValues, ...props.permanentFilter }}
        exporter={props.exporter}
        maxResults={props.maxResults}
      />
    </TopToolbar>
  );
};
```

**Other information:**
Functionality wise it's working as expected but in the console, I'm getting 2 warning.

first one is related `permanentFilter` and a warning message is :

`React does not recognize the permanentFilter prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase permanentfilter instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

The second one is related to `exporter` and a warning message is :

`Invalid value for prop exporter on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior`

**Environment**

* React-admin version: ^3.2.1
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.12.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
You've not properly copied the code snippet from the documentation. The bug is yours!
