### ISSUE TITLE
Attempted import error: 'useExpanded' is not exported from 'ra-core'

### ISSUE THREAD

**Issue by Godman-quake** [marmelab/react-admin#4752]
./node_modules/ra-ui-materialui/esm/list/DatagridRow.js
Attempted import error: 'useExpanded' is not exported from 'ra-core'.

error after exec `npm run start`, react-admin release is 3.4.3

**Comment by Godman-quake** [comment]
Use yarn instead of npm to update react-admin, and everything is ok.
Use npm to install react-admin@3.4.3, there is no useExpanded.js in the ra-core module, it's weird and I don't know why!

**Comment by kopax** [comment]
Have you tried to run `npm ls react-admin` , `npm ls ra-core` ? How have you solved your issue ? Please do not hesitate to leave your resolution for others...

**Comment by Godman-quake** [comment]
Ok, kopax.
This is my resolution:
$cd $PROJECT_ROOT
$rm -rf node_modules/*
$rm package-lock.json
$yarn
$yarn start

**Comment by CleverAtBen** [comment]
I just had a similar problem, npm ls ra-core showed that ra-core was still on v3.3, I fixed using....  npm install ra-core
