### ISSUE TITLE
Resources not loading since 3.4.1

### ISSUE THREAD

**Issue by shakhal** [marmelab/react-admin#4755]
**What you were expecting:**
Show resources and menu

**What happened instead:**
Since version 3.4.1 resources are not loading and strings are not populated
<img width="331" alt="Screen Shot 2020-05-03 at 11 11 49" src="https://user-images.githubusercontent.com/4223768/80909361-4ee81280-8d30-11ea-9577-9d57aab8ec27.png">

Goes back to normal when I install 3.4.0

**Environment**

* React-admin version: 3.4.1
* Last version that did not exhibit the issue (if applicable): 3.4.0
* React version: 16.12.0
* Browser: Chrome
* Stack trace (in case of a JS error): no errors visible

**Comment by djhi** [comment]
Can you please provide a codesandbox showing the issue ?

**Comment by fzaninotto** [comment]
Could it be that you updated `react-admin` but not the other `ra-` packages?

**Comment by shakhal** [comment]
@fzaninotto yes that was it! thanks!
