### ISSUE TITLE
Info about current user (checkAuth -> useAuthState)

### ISSUE THREAD

**Issue by andreivinaga** [marmelab/react-admin#4759]
**Is your feature request related to a problem? Please describe.**
It would be useful to get information about the current user when he is logged in, the only thing we are getting now is the data from useAuthState which is useful but it does not contain information about the user logged in

**Describe the solution you'd like**
When `checkAuth` is called we should update the state from `useAuthState` with the response from that function and the user can access it later on as he desires.

**Describe alternatives you've considered**
One option would be to call checkAuth myself but that would mean that is is called twice once by react admin and another time by myself.
Another option would be to use custom pages and implement the auth process by myself..

**Additional context**
I have searched for a solution to this problem and i have not been able to find anything suitable. I had a look at [https://marmelab.com/react-admin/AdvancedTutorials.html#add-a-user-profile-page](this) but it's not the same thing as having the current user available in the state of the app.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. 

There is currently no standard way to do that in react-admin. My suggestion is that you add another method to your `authProvider`, something like `getUser`, and use the `useAuthProvider` hook to call it from your code. It's also your responsibility to store the user details at login.

**Comment by l3v1k** [comment]
Why doesn't AuthContext, following its naming, does not store current identity inside of it? Relying on function "getUser" calling is not a react way, because we couldn't determine when user is updated, e.g. using useEffect. I think "your responsibility to store the user details" is making things complicated. There is only way to do this is write custom AuthContext and replace react-admin's context.
