### ISSUE TITLE
ReferenceInput and SelectInput not submitting correct data for Filter form 

### ISSUE THREAD

**Issue by killerwhiteshark** [marmelab/react-admin#4761]
**What you were expecting:**
Using ReferenceInput with SelectInput inside a Filter Form for the List View, I want to have every ringId for an option to select for my filter form for all available IDs in the database. Without using "getMany"

**What happened instead:**
I only get 25 default options, If I click an available option, I get an error message (see picture) and the form is only submitted with the database List ID ["123"]

**Steps to reproduce:**
```
<Form onSubmit={onSubmit} initialValues={filterValues} >
    {({ handleSubmit }) => (
       <form onSubmit={handleSubmit}>
          <ReferenceInput label="Ring Id" source="ringid" reference="candidates">
              <SelectInput optionText="ringid" />
          </ReferenceInput>
       </form>
     )}
</Form>
```

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**
<img width="408" alt="Screenshot 2020-05-04 12 42 26" src="https://user-images.githubusercontent.com/57851493/81014296-72cf5500-8e11-11ea-99b1-db69c8cbe184.png">
<img width="413" alt="Screenshot 2020-05-04 12 42 17" src="https://user-images.githubusercontent.com/57851493/81014342-88dd1580-8e11-11ea-899f-2fb7f869663f.png">

**Environment**

* React-admin version: Current Version
* React version: Current
* Browser: Google Chrome
* Stack trace (in case of a JS error):
` Failed to load resource: the server responded with a status of 404 ()
0.chunk.js:346453 
Error
    at new HttpError (0.chunk.js:264745)
    at 0.chunk.js:265156`

**Comment by fzaninotto** [comment]
I don't understand your problem, and I cannot reproduce any issue with ReferenceInput as a filter.

If you need more than options in the `<SelectInput>`, you need to set the `perPage` prop, as explained in [the `<ReferenceInput>` documentation](https://marmelab.com/react-admin/Inputs.html#referenceinput). 

Also, you're using a custom filter form instead of react-admin's `<Filter>` component. This may work but isn't supported.

Please add a link to a CodeSandbox based on the simple example reproducing the problem.

**Comment by killerwhiteshark** [comment]
I basically want a pull down filter for every available Ring ID from the database to filter the candidates that belong to to the Rings.

**Comment by djhi** [comment]
You should probably use an `AutocompleteInput` inside the `ReferenceInput`. `SelectInput` are not the best choice for so many items.

https://marmelab.com/react-admin/Inputs.html#autocompleteinput

**Comment by killerwhiteshark** [comment]
I understand thank you I will try that!
