### ISSUE TITLE
dataProvider: normalize data structure

### ISSUE THREAD

**Issue by gpietro** [marmelab/react-admin#4763]
I'm using feathers as backend and tried ra-data-feathers as dataProvider.
It works fine but when you have a complex document with nested objects is not easy to create a usable form for the entity.

I was wondering if there is the possibility or you would consider to wrap the dataProvider with a normalizer function like [normalizr](https://github.com/paularmstrong/normalizr).

The idea is the same as when we normally use with a reducer. You fetch the data, normalize it and on save you denormalize the reducer state and send it back to the server.

What do you think? There are other way to solve the problems? Since the backend works as services isn't the best for relational database so this would be a better solution in my opinion.

Thanks

**Comment by fzaninotto** [comment]
You can use normalizr in your dataProvider, but we won't use it inside react-admin. We don't encourage using complex documents with nested objects, as they are usually hard to interface width data. Besides, react-admin encourages a resource-based model, and optimizes dataProvider calls to avoid n+1 query problems.

**Comment by gpietro** [comment]
Thanks for the quick replay. I understand your point.
Can you give me an idea on how could I wrap the dataProvider with a normalizr?

**Comment by fzaninotto** [comment]
I suggest you ask this question on StackOverflow, this issue tracker is only for bugs and feature requests.
