### ISSUE TITLE
sometimes initial content is not visible in  RichTextInput  , issue is intermittent

### ISSUE THREAD

**Issue by AnoopChillayi** [marmelab/react-admin#4764]
**What you were expecting:**

**What happened instead:**

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
There is no chance we can reproduce the issue if you're not following the issue template. If you want us to look at this issue, please provide more details.
