### ISSUE TITLE
useGetOne hook not pointed to right URL

### ISSUE THREAD

**Issue by ackalhan** [marmelab/react-admin#4765]
**What you were expecting:**
 const { data, loading, error } = useGetOne('users', 10); **// should pointed to users/10?**

**What happened instead:**
pointed to **/10** not related to the resource

**Related code:**

```
import { useGetOne } from 'react-admin';

const UserProfile = () => {
    const userId = 10;
    const { data, loaded, error } = useGetOne('users', userId);

    if (!loaded) return "NOT LOADED...";
    if (error) return "ERROR";
    if (!data) return "NO DATA";

    return (
        <ul>
            <li>Name: {data.name}</li>
            <li>Email: {data.email}</li>
        </ul>
    )
}
```

**Other information:** This code works fine
```
const { data, loaded, error } = useGetList(
    'users',
    { page: 1, perPage: 10 },
    { field: 'id', order: 'DESC' },
    { name: 'hello' }
)
```

**Environment**

* React-admin version: 3.4.2

**Comment by fzaninotto** [comment]
I cannot reproduce the error you're mentioning. This is probably an error in the dataProvider you're using. Plase provide a CodeSandbox reproducing the problem including the dataProvider call.

**Comment by ackalhan** [comment]
Im using this with api-plat form it's a bug there as i see
closing this
