### ISSUE TITLE
ant design library

### ISSUE THREAD

**Issue by MarkLyck** [marmelab/react-admin#4768]
**Is your feature request related to a problem? Please describe.**

We're a small company using react-admin and love it!

However, I have to admit, we hate Material-UI and it's by far the biggest pain we have in our platform.

It would be so amazing if we could implement react-admin with ant design language: https://ant.design/

Ant design (in our humble opinion just works seamlessly and looks a lot better). They also surpassed Material UI in GitHub stars: https://github.com/ant-design/ant-design/

We'd be happy to either do all the work required to make an antd version of the ra-ui-material package.

But wanted to reach out first, to make sure that's something you'd be willing to merge if we went ahead and built that, I'd be happy to help maintain the antd portion after the fact as well if you're worried about any extra work to implement new features / fix bugs related to ui libraries.

@djhi really hope we'll hear back from you on this subject.

**Comment by fzaninotto** [comment]
Great idea!

I'm not sure you measure the work it is to maintain such a library (weeks of work for years), so even if you propose your help here, it's too big a risk for us to merge your work and be forced to maintain it in the future if you leave. Also, we can't commit on maintaining a huge amount of code we've not written.

But you can totally publish an independent ant design version - in fact, the react-admin architecture is designed just for that. So I suggest you publish the ant design package yourself, and open a PR here to link to it in the Ecosystem documentation.

**Comment by MarkLyck** [comment]
@fzaninotto that's a fair point.

Is there any way it would be doable without having to fork the react-admin repo? The reason we were hoping to get it merged in rather than just forking react-admin is so we don't have to merge all your future updates manually.

Does React-admin have the capability to easily switch from using ra-ui-material to another package with the same exports?

**Comment by djhi** [comment]
The `react-admin` package is made of two packages:
- `ra-core` which contains the core logic and components
- `ra-ui-materialui` which contains the Material UI components

You don't need to fork `react-admin` but to create a new package `ra-ui-antd`. However, it might be a good idea to use the `ra-ui-materialui` package as a starting point.

**Comment by MarkLyck** [comment]
@djhi Thanks for the package structure overview, and yeah that was the plan, just copy over ra-ui-material, keep the unit tests the same and replace each UI component with antd versions 1 folder at a time.

And thanks for creating this awesome tool. I believe it was your presentation I saw about RA at React-Europe in Paris a few years ago.

**Comment by djhi** [comment]
Np 🙂 Hopefully we have migrated all tests from enzyme to testing-library. If not, it would probably be a good idea to help us migrate the remaining tests first.

Besides, it might help a lot to copy the cypress tests as well but we have to make sure they don't rely on material-ui markup first.

I think you saw @fzaninotto presentation at react-europe 😉

**Comment by MarkLyck** [comment]
@djhi Sure, I'd be happy to contribute with some test updates as well :)

Just working on the basic setup now.

Since it's gonna be in a separate repo, I'm adding storybooks for everything as well, so I can develop all the components in there.

I'll make the stories, with Material first, get all the tests running, etc. then work on migrating everything.

<img width="1680" alt="Screen Shot 2020-05-06 at 2 50 50 PM" src="https://user-images.githubusercontent.com/6841110/81216550-130bb200-8fa9-11ea-9c74-00557bcdc792.png">

For each component, I'll check the test, if its Enzyme migrate it, and make a PR to react-admin with the updated test.

Luckily the specs don't seem specific to Material UI so they should for the most part "just work", haven't checked out the Cypress ones yet though.

**Comment by Unforgiven-wanda** [comment]
@MarkLyck Any progress on this? I'd love to see a version of React-admin on Antd as well.

**Comment by MarkLyck** [comment]
@Unforgiven-wanda

I've got the setup and storybooks done, but sadly haven't gotten the time to finish it yet as we hit some pretty hard deadlines from our customers. But it's still on the roadmap to get done, hopefully soon 🤞

Would love to make this public actually if anyone wants to contribute.

**Comment by jbek7** [comment]
It looks like Mark made his repo public at https://github.com/MarkLyck/ra-ui-antd in case anyone wants to contribute.

**Comment by MarkLyck** [comment]
> It looks like Mark made his repo public at https://github.com/MarkLyck/ra-ui-antd in case anyone wants to contribute.

We ended up abandoning react-admin altogether as it's just too difficult/problematic to maintain and work with,  even with the default library. So I'd recommend not using my start on this, as I won't be maintaining this, but feel free to clone it of course.

**Comment by fzaninotto** [comment]
@MarkLyck Would you mind adding a few details about the difficulties you had with react-admin? We're always looking for ways to improve, and your feedback would be great insight about the actual problems met by developers.
