### ISSUE TITLE
Cannot using ReferenceInput when using createAdminStore: argument fn is undefined or null

### ISSUE THREAD

**Issue by vctqs1** [marmelab/react-admin#4782]
**What you were expecting:**
I found a same issue, but I dont see a solution to fix this. https://github.com/marmelab/react-admin/issues/3534
Please help me with this. Thank u guys

**What happened instead:**
I got error `call: argument fn is undefined or null` when trying to using ReferenceInput 

**Steps to reproduce:**
```
             <ReferenceInput
                    validate={[required()]}
                    label={translate("resources.schools.edit.city")}
                    source="city_id"
                    allowEmpty
                    filterToQuery={(searchText) => ({name: searchText})}
                    reference="cities">
                    <AutocompleteInput  />
                </ReferenceInput>
```
**Related code:**
I using "react-admin": "^3.2.0",

```
import {applyMiddleware, combineReducers, compose, createStore} from "redux";
import {routerMiddleware, connectRouter} from "connected-react-router";
import createSagaMiddleware from "redux-saga";
import {all, fork} from "redux-saga/effects";
import {adminReducer, adminSaga, USER_LOGOUT} from "react-admin";

import authReducer, {authRequestMiddleware, initialState as authInitialState} from "./auth";

export default ({authProvider, dataProvider, history}) => {
    const reducer = combineReducers({
        admin: adminReducer,
        router: connectRouter(history),
        /* add your own reducers here */
        auth: authReducer,
    });
    const resettableAppReducer = (state, action) => {
        return reducer(action.type !== USER_LOGOUT ? state : undefined, action);
    };

    const saga = function* rootSaga() {
        yield all(
            [
                adminSaga(dataProvider, authProvider),
                // add your own sagas here
            ].map(fork)
        );
    };
    const sagaMiddleware = createSagaMiddleware();

    const composeEnhancers =
        (process.env.NODE_ENV === "development" &&
            typeof window !== "undefined" &&
            window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ &&
            window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
                trace: true,
                traceLimit: 25,
            })) ||
        compose;

    const store = createStore(
        resettableAppReducer,
        authInitialState,
        composeEnhancers(
            applyMiddleware(
                sagaMiddleware,
                routerMiddleware(history),
                // add your own middlewares here
                authRequestMiddleware()
            )
            // add your own enhancers here
        )
    );
    sagaMiddleware.run(saga);
    return store;
};

```

**Other information:**

**Environment**

* React-admin version: 3.2.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser:
* Stack trace (in case of a JS error):

**Comment by vctqs1** [comment]
I found this when a log error. I saw `undefined` in `relateTo`
![image](https://user-images.githubusercontent.com/30227910/81280124-42422200-9082-11ea-8118-2cebe460271e.png)

**Comment by vctqs1** [comment]
I solve this error, Just need upgrade react-admin and redux-saga

**Comment by arulraj711** [comment]
@vctqs1  , Can you post how you sovled this issue? I am too running out of the same issue.

**Comment by sebitoelcheater** [comment]
I'm still having this error

**Comment by Luwangel** [comment]
@sebitoelcheater Could you provide a code sandbox reproducing the issue?

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by akuimov** [comment]
Tell, please, is there a solution to this problem? I'm still having this error

**Comment by djhi** [comment]
@akuimov We need a way to reproduce the issue. Please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by akuimov** [comment]
> @akuimov We need a way to reproduce the issue. Please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

I can give you a link to my repository https://github.com/akuimov/nestjs-crud.git
