### ISSUE TITLE
lowercased delete names

### ISSUE THREAD

**Issue by burnes** [marmelab/react-admin#4783]
**What you were expecting:**
I wanted to customize the text of a delete message in German. Therefore I added a translation for my resource and the bulk_delete_title in `translations.ts`:

```
...
"resources": {
  "Company": {
    "name": "Firma"
  }
}
...
"message": {
  "bulk_delete_title":
          "Lösche %{name} |||| Lösche %{smart_count} %{name} Elemente",
}
...
```

I assumed the message would be `Lösche Firma` on the delete confirmation overlay.

**What happened instead:**

The displayed message was `Lösche firma` with lowercased `F`, which is wrong in German. Could not find a way to "hack" this without changing the react admin codebase.

**Reason:**

The translate options of the `<Confirm/>` object in `<DeleteWithConfirmButton/>` uses `inflection.humanize` to lowercase the resource. This may make sense for English language, but not for others.

**Proposal:**

Make this humanize optional or use a different translation message ID and do not humanize.

**Environment**

* React-admin version: 3.5.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: any
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for the report. I don't see how to fix it in a way that works in all locales though.

**Comment by burnes** [comment]
Yeah, was thinking the same when I saw the code. Maybe use an optional translation ID, e.g. `resources.${resource}.deleteName` without humanizing -  and if this is not given use the current implementation.

**Comment by fzaninotto** [comment]
There are many other instances of `humanize` in the code. This is a broader problem than just the `<DeleteWithConfirmButton>`, right?

**Comment by burnes** [comment]
In the delete buttons and in the empty component the same happens, in all other occurences of humanize it's uppercased or only the fallback (resource name) is humanized.
