### ISSUE TITLE
React-Admin doesn't show column data of related model in List component

### ISSUE THREAD

**Issue by mgpepe** [marmelab/react-admin#4796]
**What you were expecting:**
to see data from the related model

**What happened instead:**
column is empty

**Steps to reproduce:**
just go to list of the main model

**Related code:**

in the list of the main model `papers`:
```      
<ReferenceField source="imageId" reference="files">
        <TextField source="urlPath" />
</ReferenceField>
```

Here is what the main model `papers` is returning for this row:
```
brandId: "b3dc4246-3adf-4f4e-9f81-294f23d24977"
brandModelId: "2819360d-2e6e-48e4-88a3-823a03177a7c"
colorId: "98031f74-a83f-4389-b9d6-bab959ff8a0e"
gsm: 200
id: "058cc13d-1255-4d9b-9ccf-e087ddb3935d"
imageId: "1bc99717-f60c-485e-989a-5d1726501b8d"
originalSize: "A4"
paperMaterialId: "5afd0d7c-5ace-49e3-a538-894ce288fe71"
paperSurfaceId: null
price: 12
ref: "44202129"
storeId: "2f7567ad-fa62-4bda-851b-89b8c39a189e"
```

Here is what the related model `files` is returning:
```
id: "1bc99717-f60c-485e-989a-5d1726501b8d"
originalFileName: "palette1.2.png"
type: "undefined"
urlPath: "asdf/101d7c68-9bf4-4d55-bbb5-818f62c480a3-palette1.2.png"
```

but here is my screenshot with missing data:
[![enter image description here][1]][1]

Note that the Store related field works, which has the exact same code:
```
      <ReferenceField source="storeId" reference="stores">
        <TextField source="name" />
      </ReferenceField>
```

Also, here is my `getMany` dataProvider:
```
  getMany: (resource, params) => {
    const query = {
      filter: JSON.stringify({ id: params.ids }),
    };
    const url = `${API_URL_LOCAL}/${resource}?${stringify(query)}`;

    return request(url, 'get', {}, {}).then(({ data }) => ({
      data,
    }));
  },
```

Looks like a bug, smells like a bug, but is it?

  [1]: https://i.stack.imgur.com/cwGdl.png

**Environment**

* React-admin version: 3.5.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Chrome  81.0.4044.138
* Stack trace (in case of a JS error): No error

**Comment by djhi** [comment]
Can you please provide a codesandbox reproducing the issue ?

**Comment by fzaninotto** [comment]
Also, what do you see in the network tab of your browser dev tools? Do you see the call to `getMany('files')`? What's the response?

**Comment by mgpepe** [comment]
Found the issue. Had the wrong resource name in App.js. My molestake.

**Comment by mgpepe** [comment]
And actually, @fzaninotto yes - I had files response in the network, which is why i didn't bother checking the resource name - I assumed wrongly that if it is feching correct data from correct endpoint it is set up correctly.
