### ISSUE TITLE
ReferenceArrayInput with SelectInput in Filter is crashing

### ISSUE THREAD

**Issue by Eduardogbg** [marmelab/react-admin#4797]
**What you were expecting:**

To use a ReferenceArrayInput with SelectInput to filter a column in my list.

**What happened instead:**

It works as expected until I go elsewhere on the application. After I leave the list, if I try to go back the view will crash with "TypeError: ids.map is not a function in ReferenceArrayInput (created by MyFilter)"

**Steps to reproduce:**
- Make a List
- Make a Filter
- Make a ReferenceArrayInput with SelectInput
- Click on a link to elsewhere inside the application
- Go back to the original list

**Related code:**
```
<Filter {...props}>
  <ReferenceArrayInput
    label="Label"
    reference="somewhere"
    source="key"
    alwaysOn
  >
    <SelectInput source="name" />
  </ReferenceArrayInput>
</Filter>
```

**Environment**

* React-admin version: 3.1.1
* React version: 16.12.0
* Browser: Chromium 81

**Comment by fzaninotto** [comment]
Yep, that's normal. You should use a `SelectArrayInput`, not a `SelectInput`.

**Comment by Eduardogbg** [comment]
Sure, I know about SelectArrayInput, but in this case I wanted only one input. Do you know a quick workaround or will I have to create my own input? Thanks btw

**Comment by djhi** [comment]
Then why using a `ReferenceArrayInput` instead of a `ReferenceInput` ?

**Comment by Eduardogbg** [comment]
Because of a misconception I had. That's sorted out now. Sorry for bothering you!
