### ISSUE TITLE
Server Sent Event (EventSource)

### ISSUE THREAD

**Issue by L-Luciano** [marmelab/react-admin#4807]
**Is your feature request related to a problem? Please describe.**
I would like to notify or/and refresh the view when I received a SSE in my EventSource. 

**Describe the solution you'd like**
I would like to pass an eventSource to the List/Show/Edit component and it could manage the refresh data with notify/refresh/RefreshConfirm function.

The useListController could manage the server sent event.

**Describe alternatives you've considered**
Now, I manage the EventSource in my DataProvider but I can't notify or refresh because I'm out of the redux-context. If you have a solution.

Thanks

**Comment by L-Luciano** [comment]
Another solution : let custom values in useListController for example :

my dataprovider return : {data, total, eventSource} and I could get my EventSource in my CustomList to manage it.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

React-admin v2 had a package called [ra-realtime](https://github.com/marmelab/react-admin/tree/2.x/packages/ra-realtime), which used sagas to offer a feature comparable to what you describe. 

We're planning to release a paid version of ra-realtime, as part of the Enterprise Edition. 

So I'm closing this issue as this package won't be part of the open-source edition of react-admin.

**Comment by L-Luciano** [comment]
Ok thanks.

What is the planing for the Enterprise Edition ? 
Do you have a list of features for this edition ?

Regards

**Comment by fzaninotto** [comment]
please email to react-admin-ee at marmelab dot com for more details about the enterprise edition.
