### ISSUE TITLE
Add a way to translate the <TextField /> value

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#4809]
In RA v3,

I am sending from the servers within my entity a `slug`. The slug is a `key` that should be assigned to a translation client side.

This is a list of status:

```json
[
  {
    "description": "Refused",
    "slug": "refused"
  },
  {
    "description": "Accepted",
    "slug": "accepted"
  },
  {
    "description": "Abandoned",
    "slug": "abandoned"
  },
  {
    "description": "Wrong number",
    "slug": "wrong-number"
  },
  {
    "description": "To renew call back",
    "slug": "to-renew-call-back"
  },
  {
    "description": "To call back",
    "slug": "to-call-back"
  }
]
```

This is how I am able to translate within my `<CallMeBackCreate />` component:

```jsx
    <Create {...props}>
      <SimpleForm>
        <ReferenceInput
          source="status.id"
          reference="callmeback"
        >
          <SelectInput 
            optionText={(choice) => translate(`translation.${choice.slug}`)}
          />
        </ReferenceInput>
      </SimpleForm>
    </Create>
```

Instead of using the `description`, it uses the `slug` and translates client side, 

I want to achieve the same thing with `<Field />` components in my `<CallMeBackShow />` and `<CallMeBackList />` components:

```jsx
<TextField
  source="status.description"
  label={(choice) => translate(`translation.${choice.slug}`)}
/>
```

It seems that the `<TextField />` doesn't allow that : https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/field/TextField.tsx#L19

Is there another component for such case? Would this feature be welcome if not supported?

**Comment by djhi** [comment]
We usually create a custom component for this

**Comment by kopax** [comment]
I am thinking to do that to but I have not yet found a way to access the item in the list. Can you access the data of one item from within the `<List />`?

**Comment by djhi** [comment]
Follow the documentation https://marmelab.com/react-admin/Fields.html#writing-your-own-field-component

Your component will receive the current record as a prop

**Comment by kopax** [comment]
Thank you.
