### ISSUE TITLE
AllowEmpty feature no longer works in SelectArrayInput

### ISSUE THREAD

**Issue by fancyaction** [marmelab/react-admin#4811]
**What you were expecting:**
SelectArrayInput should display empty option with value/label passed via emptyText/Value props.

**What happened instead:**
Option does not render in menu select.

**Steps to reproduce:**
```
        <SelectArrayInput
          label="Role"
          source="role_id"
          choices={[
            {
              id: "headwriter",
              name: "Head Writer"
            },
            {
              id: "proofreader",
              name: "Proof reader"
            },
            {
              id: "cowriter",
              name: "Co-Writer"
            }
          ]}
          allowEmpty
          emptyValue={null}
          emptyText="Unassigned"
        />
```

**Related code:**
https://codesandbox.io/s/allowempty-bug-qj29i?file=/src/posts/PostCreate.js:3265-3749

**Environment**

* React-admin version: RA 3.0.0, RA 3.5.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.9.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
> SelectArrayInput should display empty option with value/label passed via emptyText/Value props.

This isn't documented anywhere, and it isn't implemented either. Why would you expect that? You can enter an empty value in SelectArrayInput by deselecting all choices.

**Comment by fzaninotto** [comment]
No new for some time, closing.
