### ISSUE TITLE
Filter Component will not filter all sources

### ISSUE THREAD

**Issue by tannerPriest** [marmelab/react-admin#4815]
**What you were expecting:**

Inside the Filter Component from React-Admin, I have 8 text fields that I want to use as filters, the sources are correct.

**What happened instead:**

Only Ring ID, Candidate Name, and Notes work as expected. All others give me code 500

Only 3 out of the 8 filter work. The other 5 only give me a Error saying -->

```
Error from intermediary with HTTP status code 500

 Warning: Missing translation for key: "Error from intermediary with HTTP status code 500 " 
    in Notification (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Router.Consumer)
```

**Steps to reproduce:**

**Related code:**

You can see that the Data renders in the table and the sources are the same between the Filter and List Components

```

        <div style={{ marginTop: '15px' }}>
            <Filter {...props} >
                <TextInput label="Ring ID" source="ringid" alwaysOn resettable />
                <TextInput label="Candidate Name" source="candidatename" alwaysOn resettable />
                <TextInput label="Created by" source="createdby" alwaysOn resettable />
                <TextInput label="Updated By" source="updatedby" alwaysOn resettable />
                <TextInput label="Notes" source="notes" alwaysOn resettable />
                <TextInput label="Version Number" source="candidateversionnumber" alwaysOn resettable />
                <TextInput label="Created Date" source="createdat" alwaysOn resettable />
                <TextInput label="Form ID" source="candidatedata" alwaysOn resettable />
            </Filter>
        </div>


            <List
                {...props}
                hasCreate={false}
                exporter={false}
                filters={<CandidateFilter />}
                pagination={<CandidatePagination />}
                bulkActionButtons={<BulkActionButtons />}
                style={{ position: 'relative', marginTop: '5px' }}
            >
                <Datagrid>
                    {/* Ring ID, Cand. Name, Created By and Updated date */}
                    <TextField label="Ring ID" source="ringid" />
                    <TextField label="Candidate Name" source="candidatename" />
                    <TextField label="Created by" source="createdby" />
                    {mediumWidth ? (<TextField label="Updated By" source="updatedby" />) : ("")}
                    {mediumWidth ? (<DateGetter label="Date Created" source="createdat" />) : ("")}
                    <DateGetter label="Date Updated" source="updatedat" />
                    {largeWidth ? (<TextField label="Notes" source="notes" />) : ("")}
                    {largeWidth ? (<TextField label="Version Number" source="candidateversionnumber" />) : ("")}
                    <ShowButton label="Show"/>
                </Datagrid>
            </List>
```

**Other information:**
Working Correctly:

<img width="1680" alt="Screen Shot 2020-05-14 at 1 03 03 PM (2)" src="https://user-images.githubusercontent.com/57851493/81980820-27246480-95e4-11ea-99e4-5995c2cb9261.png">

<img width="1680" alt="Screen Shot 2020-05-14 at 1 02 06 PM (2)" src="https://user-images.githubusercontent.com/57851493/81980931-5dfa7a80-95e4-11ea-90b4-95484d719e52.png">

Rendering Error:

<img width="1680" alt="Screen Shot 2020-05-14 at 1 02 45 PM (2)" src="https://user-images.githubusercontent.com/57851493/81980917-55a23f80-95e4-11ea-995b-74239d82ce6e.png">

<img width="1680" alt="Screen Shot 2020-05-14 at 1 02 23 PM (2)" src="https://user-images.githubusercontent.com/57851493/81981029-871b0b00-95e4-11ea-8a96-410f5dd1eb64.png">

**Environment**

* React-admin version: 3.0.4
* React version: 16.12.0
* Browser: Google Chrome
* Stack trace (in case of a JS error):

```
Warning: Missing translation for key: "Error from intermediary with HTTP status code 500 " 
    in Notification (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Router.Consumer)
    in Router.Consumer (created by withRouter(WithStyles(Layout)))
    in withRouter(WithStyles(Layout)) (created by ConnectFunction)
    in ConnectFunction (created by LayoutWithTheme)
    in LayoutWithTheme (at MyLayout.js:5)
    in MyLayout (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (created by CoreAdminRouter)
    in CoreAdminRouter (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (created by AdminUI)
    in AdminUI (created by Admin)
    in Admin (at App.js:34)
    in App (at src/​index.js:8)
```

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application by forking this CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)

**Comment by fzaninotto** [comment]
HTTP code 500 are server-side errors. I don't see what react-admin has to do with it.

**Comment by killerwhiteshark** [comment]
The reason I believe it is a react admin bug is because I'm retrieving the data from my server in the data grid for the List component but when filtering only 3 of them work

**Comment by killerwhiteshark** [comment]
> Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application by forking this CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)

I will try to replicate thank you
