### ISSUE TITLE
No data from useGetList after refresh

### ISSUE THREAD

**Issue by wkrh** [marmelab/react-admin#4817]
**What you were expecting:**

useGetList gives data even after pressing refresh button at the header toolbar

**What happened instead:**

Data is empty after refresh

**Steps to reproduce:**

Reproduces at  the simple example `examples/simple/src/customRouetLayout.js`.

1. `make run-simple`
2. Go to http://localhost:8080/#/custom2
3. "Found 13 posts!" displayed.
4. Press Refresh icon
5. "Found posts!" displayed. (no posts listed.)

**Other information:**

Passing version value of `useVersion()` hook to options parameter of `useGetList` seems to be a workaround.
```js
--- a/examples/simple/src/customRouteLayout.js
+++ b/examples/simple/src/customRouteLayout.js
@@ -1,12 +1,15 @@
 import React from 'react';
-import { useGetList, useAuthenticated, Title } from 'react-admin';
+import { useGetList, useAuthenticated, Title, useVersion } from 'react-admin';
 
 const CustomRouteLayout = () => {
     useAuthenticated();
+    const version = useVersion();
     const { ids, data, total, loaded } = useGetList(
         'posts',
         { page: 1, perPage: 10 },
-        { field: 'published_at', order: 'DESC' }
+        { field: 'published_at', order: 'DESC' },
+        {},
+        { version }
     );
```

**Environment**

* React-admin version: current master branch 70e9b48
* Browser: Chrome

**Comment by fzaninotto** [comment]
Thanks, reproduced.

**Comment by fzaninotto** [comment]
It seems to be a race condition between:

- the Application cache, which skips the call to the data provider if there is a cached request
- the refresh action, which empties cached requests. 

It only appears when using the application cache. 

It's a pretty serious bug, and users shouldn't have to add the version dependency themselves.
