### ISSUE TITLE
ArrayInput with array of strings throws "Cannot set a numeric property on an object"

### ISSUE THREAD

**Issue by NikitaVlaznev** [marmelab/react-admin#4823]
I have started to get a

> Cannot set a numeric property on an object

 exception on my forms with ArrayInputs for fields that contains an array of strings.

Bug have appeared in version 3.5.2 after PR #4810.

This happens because this is not a correct way to detect an object values that are used as a subdictionary:

`if (value && Object.keys(value).length > 0)`

It failes on strings and may be with something else, because:

```
Object.keys("cats")
[ '0', '1', '2', '3' ]
```

**Comment by alanpoulain** [comment]
PR to fix this issue: https://github.com/marmelab/react-admin/pull/4819.

**Comment by fzaninotto** [comment]
Fixed by #4819

**Comment by cyberlake** [comment]
Getting the same issue with `<ReferenceArrayInput>` and `<AutocompleArrayInput>`
