### ISSUE TITLE
Documentation update for CustomApp.md

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#4832]
**What you were expecting:**
The example for using \<Routes\> in **Not Using the \<Admin\> Components** section should be

`<Route exact path="/posts/:id" render={(routeProps) => <PostEdit hasShow resource="posts" basePath={routeProps.match.url} id={decodeURIComponent((routeProps.match).params.id)} {...routeProps} />} />`

**What happened instead:**
Instead the hasShow attribute is put onto the \<Route\> so PostEdit may give out a warning because the routeProps does not include the hasShow attribute.
id is not decoded from URI, so everytime dataProvier will fetch an undefined id.

**Other information:**
We also need to update appropriate section in UPGRADE.md
Update useCheckMinimumRequiredProps('Edit', ['basePath', 'resource'], props) to check for 'id' in the useEditController.js file to give out a warning

**Environment**

* React-admin version: 3.5.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting :) Would you mind openning a pull request to fix it ?
