### ISSUE TITLE
Lost filters after edit resource

### ISSUE THREAD

**Issue by hugofialho** [marmelab/react-admin#4835]
**What you were expecting:**
Afeter edit resource redirect to list with filters.

**What happened instead:**
Redirect to list without filters.

**Steps to reproduce:**
Access demo(https://marmelab.com/react-admin-demo/#/).
Go to Catalog/Categories.
Click on Products inside any category.
Edit any poster.
You lost Category filter.

**Related code:**
It happens on demo(https://marmelab.com/react-admin-demo/#/categories)

**Comment by fzaninotto** [comment]
Thanks for the report, I reproduced the bug.

This only happens with the category link. Setting the Category filter manually in the Product list makes it persistent.

**Comment by fzaninotto** [comment]
The problem comes from `useListParams`: it doesn't dispatch a `changeListParams` on mount if the params from the state differ from the params from the location (which would imply a direct link to a filtered list).

**Comment by argestes** [comment]
I'm having somewhat related issue. I have this button inside a list which fetches a resource. After fetch succeds for a split second the updated resource is shown on the list but after that query changes and i'm redirected to first page of 'books'. Even if i remove `refresh` it's still the same issue. I need the grid to stay the same after this call.

```
export const FetchButton = ({record, ...rest}) => {
    const notify = useNotify();
    const refresh = useRefresh();
    const dataProvider = useDataProvider();
    const fetch = () => dataProvider
        .update('books', {
            id: record.id + "/fetch", data: {request_fetch: true}
        })
        .then(response => {
            refresh()
            notify(`Book fetched`, 'info', {}, false);
        }).catch(error => {
                notify(`Book fetch failed`, "warning");
            }
        );

    return record && !record["name"] ?
        <Button label="Fetch" onClick={fetch}/> :
        null;
}

export const BookList = (props) => (
    <List {...props}>
        <Datagrid>
            <TextField source="id"/>
            <TextField source="name"/>
            <TextField source="isbn"/>
            <FetchButton/>
            <EditButton/>
        </Datagrid>
    </List>
);```

**Comment by fzaninotto** [comment]
@argestes This is probably not the same problem. I suggest you ask for troubleshoot help in StackOverflow.
