### ISSUE TITLE
useListParams not exported from react-admin

### ISSUE THREAD

**Issue by cpv123** [marmelab/react-admin#4836]
## Bug report & general question

**What you were expecting:**

`import { useListParams } from 'react-admin` to give me the `useListParams` hook.

Question: _Should this be available to import? Is there a reason it is not?_

**What happened instead:**

App fails to compile with the follow error:
`Attempted import error: 'useListParams' is not exported from 'react-admin'.`

**Related code:**

The `useListParams` hook is not exported from https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/index.ts

**Environment**

* React-admin version: 3.5.1

**Comment by fzaninotto** [comment]
Thanks for your report. We can expose this hook. 

As it's a new feature, the change has to be pushed in the `next` branch, and will be released in a minor version. 

Would you like to work on a PR?

**Comment by cpv123** [comment]
I see I was beaten to it! Thanks @WiXSL for https://github.com/marmelab/react-admin/pull/4843

**Comment by fzaninotto** [comment]
Fixed by #4843
