### ISSUE TITLE
AutocompleteArrayInput breaks with records that has string id

### ISSUE THREAD

**Issue by cyberlake** [marmelab/react-admin#4838]
When using `ReferenceArrayInput` and `AutocompleteArrayInput` together, if the referenced records have string id, it returns `Cannot set a numeric property on an object` error. Here's [codesanbox](https://codesandbox.io/s/react-admin-bug-referencearrayinput-d62in?file=/src/posts.js) to reproduce the bug. 

I think it's related to #4823 and #4827

**Comment by fzaninotto** [comment]
Yep, that's a duplicate. Closing the issue.

**Comment by cyberlake** [comment]
👍
