### ISSUE TITLE
Notifications persist after being logged out

### ISSUE THREAD

**Issue by ilaif** [marmelab/react-admin#4845]
**What you were expecting:**
When `dataProvider` returns a 401/403 authentication error, react-admin logs out and redirects to the login page before the "logged_out" notification pops up. Then, when logging back in, this notification should not pop up.

**What happened instead:**
The "logged_out" notification pops up after a successful login, although it belongs to the **former** failed dataProvider request attempt, and the current attempt is successful. It seems like the notifications are "waiting" until the screen is switched back to the control of Admin and then fires up the notifications, instead of removing them when logging out.

**Steps to reproduce:**
It's a bit tricky to create this in code sandbox since it requires a stateful authentication.

**Related code:**
Standard setup

**Environment**

* React-admin version: ^3.5.0
* React version: 16.13.1
* Browser: Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by djhi** [comment]
Thanks for reporting.

**Comment by fzaninotto** [comment]
Are you using a custom Login page?

**Comment by ilaif** [comment]
Thanks for trying it yourself.

I do have a custom login page, and I did not include the `<Notification />` component, as it wasn't mentioned in the docs: https://marmelab.com/react-admin/doc/2.8/Authentication.html

I did add it now, and it works! the "stuck" notifications are arriving at my login page after logging out.

I have a followup question, is there a way to "clear" the notifications queue in the `authProvider.logout` method? This way I can make those notifications to disappear if I want them to.

Anyhow you solved most of my problem, and I recommend adding it to the docs.

Thanks!

**Comment by fzaninotto** [comment]
The `<Notification>` component is included in the custom Login examle... in the latest version of the documentaiton (https://marmelab.com/react-admin/Authentication.html).

To remove a notification from the Redux store, you can dispatch the `hideNotification()` action.
