### ISSUE TITLE
EmailField should use Mui Lunk

### ISSUE THREAD

**Issue by lelek16** [marmelab/react-admin#4863]
Hi, now EmailField is rendered by normal anchor (a) and it will be easier to style it when it will use MuiLink.

Exactly the same situation was here: https://github.com/marmelab/react-admin/issues/4397

If you are ok with that, i can do it. ;)

**Comment by djhi** [comment]
Already done in #4568 :)

**Comment by lelek16** [comment]
It's done for **UrlField**, i'm talking about **EmailField**.

https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/field/EmailField.tsx

**Comment by djhi** [comment]
Sorry, you're right. Please open a pull request then :)

**Comment by fzaninotto** [comment]
Fixed by #4866
