### ISSUE TITLE
FileInput without any children throws an exception

### ISSUE THREAD

**Issue by my-kel** [marmelab/react-admin#4876]
**What you were expecting:**
It should be possible to use `FileInput` without any `children`, because as stated [in the documentation](https://marmelab.com/react-admin/doc/3.5/Inputs.html#fileinput) the `children` prop is optional.

**What happened instead:**
An error is thrown (see the stack trace below).

**Steps to reproduce:**
Please note that I can't give you any code because I tried your CodeSandbox and it always crashes (sometimes with a "504 Gateway Timeout" error)...

To reproduce, simply use FileInput component without any child: `<FileInput ... />`.

**Solution:**
The bug is due to the fact that the React `Children.only(children)` function throws an error if the parameter isn't a single React element. Here is the React documentation: https://reactjs.org/docs/react-api.html#reactchildrenonly

The line throwing the exception for me is https://github.com/marmelab/react-admin/blob/v3.5.2/packages/ra-ui-materialui/src/input/FileInput.tsx#L163

The fix is pretty easy, just add a check that `children` is present before calling `Children.only(children)`.

**Environment**

* React-admin version: 3.5.2
* Last version that did not exhibit the issue (if applicable): 2.9.8
* React version: 16.12.0
* Browser: Google Chrome (it isn't browser dependant...)
* Stack trace:
```
react.development.js:1385 Uncaught Error: React.Children.only expected to receive a single React element child.
    at Object.onlyChild [as only] (react.development.js:1385)
    at FileInput (FileInput.js:112)
    at renderWithHooks (react-dom.development.js:16260)
    at mountIndeterminateComponent (react-dom.development.js:18794)
    at beginWork$1 (react-dom.development.js:20162)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25780)
    at performUnitOfWork (react-dom.development.js:24695)
    at workLoopSync (react-dom.development.js:24671)
    at performSyncWorkOnRoot (react-dom.development.js:24270)
    at react-dom.development.js:12199
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12194)
    at flushSyncCallbackQueue (react-dom.development.js:12182)
    at scheduleUpdateOnFiber (react-dom.development.js:23709)
    at dispatchAction (react-dom.development.js:17076)
    at hooks.js:11
    at CoreAdminRouter.js:83
    at step (CoreAdminRouter.js:43)
    at Object.next (CoreAdminRouter.js:24)
    at fulfilled (CoreAdminRouter.js:15)
```

**Comment by fzaninotto** [comment]
Bug confirmed, thanks for the report.

**Comment by my-kel** [comment]
@fzaninotto you're welcome. If I knew that the fix would not include any test, I would have did it ;-)

**Comment by fzaninotto** [comment]
Yes, sometimes I'm lazy. But if you feel like adding a test, please do open a PR!

**Comment by ElGoorf** [comment]
Hi, I'm having the same issue with v3.15.2 (can't update more recently because of using ra-form-layout which depends on this).

Using firefox.

```Uncaught (in promise) Error: React.Children.only expected to receive a single React element child.
    onlyChild2 React
    transformFile FileInput.js:64
    transformFiles FileInput.js:83
    onChange react-final-form.es.js:665
    useConstantCallback react-final-form.es.js:463
    handleChange useInput.js:60
    onDrop FileInput.js:94
    onDropCb index.js:620
    promise callback*useDropzone/onDropCb< index.js:594
    composeEventHandlers index.js:102
    composeEventHandlers index.js:100
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 15
    <anonymous> index.js:5
    <anonymous> index.js:113002
react.development.js:1139:12
    onlyChild2 React
    transformFile FileInput.js:64
    transformFiles FileInput.js:83
    onChange react-final-form.es.js:665
    useConstantCallback react-final-form.es.js:463
    handleChange useInput.js:60
    onDrop FileInput.js:94
    onDropCb index.js:620
    (Async: promise callback)
    onDropCb index.js:594
    composeEventHandlers index.js:102
    some self-hosted:163
    composeEventHandlers index.js:100
    React 14
    bind_applyFunctionN self-hosted:1373
    dispatchEvent self-hosted:1336
    unstable_runWithPriority scheduler.development.js:468
    React 4
    bind_applyFunctionN self-hosted:1373
    dispatchDiscreteEvent self-hosted:1336
    React 4
    forEach self-hosted:4336
    React 7
    <anonymous> index.js:5
    <anonymous> index.js:113002
```

Error points to https://github.com/marmelab/react-admin/blob/ccbcd5c3d82ef8e2b337b3d0864ee24035c14604/packages/ra-ui-materialui/src/input/FileInput.tsx#L89

What do you suggest?

**Comment by djhi** [comment]
How is `ra-form-layout` preventing you to upgrade?

**Comment by ElGoorf** [comment]
```
$ npm add --save @react-admin/ra-form-layout
npm WARN @react-admin/ra-form-layout@1.7.0 requires a peer of react-admin@^3.15.1 but none is installed. You must install peer dependencies yourself.
```
But regardless, I removed @react-admin/ra-form-layout from my project, installed react-admin 3.18.3, restarted and refreshed and still have the same issue with the same trace :(

**Comment by djhi** [comment]
Yes, note the `^` before the `3.15.1`. It means it's compatible with all versions `3`

**Comment by ElGoorf** [comment]
I'm running on the latest version of React Admin and still have the same issue with the FileInput throwing the children error on file drop/selection. I've resorted now to using `<Dropzone>` directly without issue.
