### ISSUE TITLE
Scope of refresh action

### ISSUE THREAD

**Issue by francoisruty** [marmelab/react-admin#4877]
**What you were expecting:**

When I use RA dataProvider (created with useDataProvider()) to delete a resource, and then use refresh() (created with useRefresh()), I expect the data to reload.

**What happened instead:**

The data reloads, but it tries to load the resource I just deleted, which yields a 404 or an empty response from the backend, which causes a redirect in RA. At first I thought it was a bug with RA redirect feature, it took me some time to understand that it was due to an error returned by the backend due to RA trying to load the resource I had just deleted

**Steps to reproduce:**

You can use an Edit component to edit a resource.
Inside that Edit component, use an ArrayField, or a ReferenceManyField, and inside it a Datagrid.
Inside the Datagrid, use an Edit component, to edit the related resource (that is listed in the datagrid). I set this inner Edit component id props from the props.record transmitted by the parent Datagrid
Long story short: You want to have an edit form for a resource, and inside it you want to be able to Edit related resources (for instance: you want a form to edit a doctor consultation, and inside that form you want mini-forms to be able to edit each related prescription name).
It can consist in editing multiple fields from the related resource, so I can't just follow the "comments approve button" example of RA documentation. It has to be a form, not just an action button.

In one of those "miniforms" (= Edit component inside another Edit), if you perform a delete on one of the related resources (ex: I delete a prescription related to the consultation), and then use refresh(), RA will try to load the resource I just deleted.

I suspect this is caused by the fact that the inner Edit components are responsible for fetching the resource they edit, and somehow when I delete the resource, its presence must stay "cached" somewhere which means the inner Edit components still tries to fetch it when I use refresh

I was able to work around that by using directly SimpleForm for the miniforms, without the wrapping Edit components.
This makes sense anyway since the parent Datagrid transmits the full record so I don't need an Edit to fetch it from the backend.

I'm not sure this is a bug per se, but I think somehow maybe the refresh action "has a too small scope" or something alike

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

Here is the workaround I was able to come up with:

```
          <ArrayField
              label="Roles"
              source="roles"
          >
              <Datagrid>
                <TextField source="name" label="Roles"/>
                <TextField source="label" name="Contact Field" />
                <EditRole {...props} process_id={process_id} />
              </Datagrid>
          </ArrayField>

const EditRole = props => {
  return (
    <EditGeneric {...props} res={"roles"}>
      <TextInput source="name" label="Name"/> 
    </EditGeneric>
  )
}


const EditGeneric = props => {
  const dataProvider = useDataProvider();
  const refresh = useRefresh();
  const notify = useNotify();


  const save = (record) => {
    record.id = props.record.id;
    record.process_id = props.process_id;
    dataProvider.update(props.res, {id: props.record.id, data: record})
    .then( response => {
      refresh();
    })
    .catch(error => {
        console.log(error.message);
        notify(error.message, 'warning');
    });
  }

  const del = () => {
    dataProvider.delete(props.res, {id: props.record.id})
    .then( response => {
      refresh();
    })
    .catch(error => {
        console.log(error.message);
        notify(error.message, 'warning');
    });
  }

  return (
    <div>
      {props.children !== undefined
      ?
      <SimpleForm
      initialValues={{...props.record}}
      redirect={false}
      resource={props.res}
      basePath="/"
      title=" "
      undoable={false}
      save={save}
      >
        {props.children}
      </SimpleForm>
      :
      <div/>
      }
      <Button onClick={del}>Effacer</Button>
    </div>
  )
}
```

**Other information:**

**Environment**

* React-admin version: 3.1.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.11.0
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for this issue. 

I understand you're using an Edit component inside another Edit component. This is not something that is documented or supported - do it at your own risks. 

We've implemented Editable Datagrids, but not but nesting `<Edit>` components - they are just not designed for that.

**Comment by francoisruty** [comment]
ok thanks for the feedback, I'll have a look at editable datagrids
