### ISSUE TITLE
useRefresh() do not update the edit view and shows old data, even after api response

### ISSUE THREAD

**Issue by manohar719** [marmelab/react-admin#4880]
const [open, setOpen] = React.useState(false);
const notify = useNotify();
const refresh = useRefresh();

const handleClickOpen = () => {
setOpen(true);
};

const handleClose = () => {
setOpen(false);
};

const [deleteOne, { loading }] = useDelete('document', record.id, record, {
action: CRUD_DELETE,
onSuccess: () => {
        notify('ra.notification.deleted', 'info', { smart_count: 1 });
        setOpen(false);
        refresh();
    },
    onFailure: error => {
        notify(
            typeof error === 'string'
                ? error
                : error.message || 'ra.notification.http_error',
            'warning'
        );
        setOpen(true);
    },
    undoable: false,
});

It does not load with updated values in edit

**Comment by fzaninotto** [comment]
Please use the issue template.

**Comment by fzaninotto** [comment]
No news for some time, closing.
