### ISSUE TITLE
TextInput Strips [] from source params

### ISSUE THREAD

**Issue by jordanvector** [marmelab/react-admin#4885]
I am trying to use something like this as a source field

`<TextInput label="Search Club" source="name[$like]" alwaysOn resettable />`

However it looks like react admin is doing some sort of sanitization and that parameter gets appended to the end of the string like:

run?$limit=10&$skip=0&$sort[clubId]=1&name.$like=asd 

rather than:

run?$limit=10&$skip=0&$sort[clubId]=1&name[$like]=asd 

Is there a way to prevent react admin from stripping the brackets in my source params?

**Comment by fzaninotto** [comment]
First, please follow the issue template and provide a link to a CodeSandbox showing the issue. 

Without a way to reproduce it, I believe the change is done by react-final-form. So I'd advise opening an issue in their repository. 

Finally, we've never designed or tested react-admin for field names with brackets in them. It's not a supported feature. 

So I'm closing that issue.
