### ISSUE TITLE
Invalid URL using 'jsonapiClient '

### ISSUE THREAD

**Issue by rubenghio** [marmelab/react-admin#4888]
I am using jsonapiClient and seems like URL is being created by react-admin is invalid

http://localhost:4500/employees?filter[id][]=239749&filter[id][]=239748&filter[id][]=235523

when, based on standar, I think should be something like this:

http://localhost:4500/employees?filter[id]239749,239748,235523

**Comment by fzaninotto** [comment]
Please use the issue template

**Comment by rubenghio** [comment]
**What you were expecting:**
The URL GET generated by jsonapiClient should be: http://localhost:4500/employees?filter[id]239749,239748,235523

**What happened instead:**
Seems like URL is being created by react-admin is invalid

http://localhost:4500/employees?filter[id][]=239749&filter[id][]=239748&filter[id][]=235523

**Steps to reproduce:**
Using jsonapiClient, 
* Create a component to list "Config Parameters" (for example)
* Create a component to list "Transactions" that contain a reference to a parameter record (for example). Make sure to have multiples transaction records.
When you see the URL is being created to GET PARAMETERS records, as you have more than one reference, the 'filter' params seems to be wrong.

**Related code:**


* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

-----------
const dataProvider = jsonapiClient('http://localhost:4500', fetchJson, settings);

const App = () => (
  <Admin dataProvider={dataProvider}>
    <Resource name="parameters" list={ParameterList} show={ParameterShow} create={ParameterCreate} edit={ParameterEdit} />
    <Resource name="invoices" list={InvoiceList} show={InvoiceShow} create={BonusPersonInvoiceCreate} />
    <Resource name="employees" list={EmployeeList} show={EmployeeShow} />
    <Resource name="bonperinv" list={BonusPersonInvoiceList} show={BonusPersonInvoiceShow} create={BonusPersonInvoiceCreate} />
    <Resource name="calculations" list={CalculationList} />
    <Resource name="calculations_bills" list={CalculationBillsList} />
    <Resource name="calculations_bonus" list={CalculationBonusList} />
    <Resource name="calculations_bonus_employee" list={CalculationBonusEmployeeList} />
  </Admin>
);
-----------
export const CalculationBonusEmployeeList = props => (
    <List {...props} title="Bonus Employee list">
        <Datagrid rowClick="show">
            <TextField source="id" label="ID" />
            <ReferenceField source="invoice_id" label="Invoice" reference="invoices">
                <TextField source="invoice_number" />
            </ReferenceField>
            <ReferenceField source="parameter_id" label="Bonus" reference="parameters">
                <TextField source="code" />
            </ReferenceField>
            <ReferenceField source="employee_id" label="Person" reference="employees">
                <TextField source="last_name" />
            </ReferenceField>
        </Datagrid>
    </List>
);
-----------

**Other information:**
<img width="1894" alt="Screen Shot 2020-06-02 at 18 17 02" src="https://user-images.githubusercontent.com/766960/83571121-8d264c80-a4fd-11ea-9363-d7be8fbf0737.png">

**Environment**

* React-admin version: 3.5.2
* Last version that did not exhibit the issue (if applicable):
* React version: 
* Browser: Google Chrome 83
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
The json api client isn't maintained by the core team. Please open an issue in the [henvo/ra-json-api](https://github.com/henvo/ra-jsonapi-client) repository instead.
