### ISSUE TITLE
Add disabled prop to AutocompleteInput

### ISSUE THREAD

**Issue by fancyaction** [marmelab/react-admin#4896]
**Is your feature request related to a problem? Please describe.**
Every form input has a disabled prop feature except AutocompleteInput. This is useful when you don't want an input to be editable on update, but still need api reference to render option text that may contain several fields `(e.g. choice => ${choice.description}: ${choice.price}}`

**Describe the solution you'd like**
Add `disabled` prop and pass into TextField component under Downshift.

**Additional context**
Making pull request with feature now.

**Comment by fzaninotto** [comment]
Fixed by #4915
