### ISSUE TITLE
Compatiblity problem with @material-ui/core 4.10

### ISSUE THREAD

**Issue by kowalski** [marmelab/react-admin#4898]
After upgrading to newest version of React Admin it fails to build.

ra-ui-materialui package seems to be using deprecated way of `userMediaQuery` (please see backtrace below).

Correct way to use it nowadays is:

```
import { useMediaQuery } from '@material-ui/core';
import { useTheme } from '@material-ui/core/styles';

...

  const theme = useTheme();
  const isSmall = useMediaQuery(theme.breakpoints.down('sm'));

```
I don't know why `useMediaQuery` changed syntax, it sucks!

**Environment**

* React-admin version: 3.6.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser:
* Stack trace (in case of a JS error):

```
TypeError: Cannot read property 'breakpoints' of null
(anonymous function)
node_modules/ra-ui-materialui/esm/layout/AppBar.js:94
  91 | var children = props.children, classesOverride = props.classes, className = props.className, _a = props.color, color = _a === void 0 ? 'secondary' : _a, logo = props.logo, logout = props.logout, open = props.open, title = props.title, userMenu = props.userMenu, rest = __rest(props, ["children", "classes", "className", "color", "logo", "logout", "open", "title", "userMenu"]);
  92 | var classes = useStyles(props);
  93 | var dispatch = useDispatch();
> 94 | var isXSmall = useMediaQuery(function (theme) { return theme.breakpoints.down('xs'); });
     | ^  95 | var translate = useTranslate();
  96 | return (React.createElement(HideOnScroll, null,
  97 |     React.createElement(MuiAppBar, __assign({ className: className, color: color }, rest),
```

Btw, you guys are doing great work! I'm huge fan of React-Admin:)

**Comment by fzaninotto** [comment]
The syntax didn't change in the material-ui docs and code. The problem is more likely on your side - did you provide an empty theme to react-admin?

**Comment by fzaninotto** [comment]
Also, the demo uses material-ui 4.10 and doesn't have any problem at build time and at runtime with the AppBar.

**Comment by kowalski** [comment]
My bad. It works well.
Apparently I had two installs of @material-ui/core in node_modules (one on top and other in react-admin/node_modules). So I was providing theme to the other one that react-admin was using, hence no theme.
Weird bug. 

Anyway, sorry to bother. Keep up good work :)

**Comment by kamleshwebtech** [comment]
Thanks to share your problem, it solved my another problem :)

```
import { useMediaQuery } from '@material-ui/core';
import { useTheme } from '@material-ui/core/styles';

...

  const theme = useTheme();
  const isSmall = useMediaQuery(theme.breakpoints.down('sm'));
```

Happy Sharing 👍

**Comment by hshahir-nisum-com** [comment]
thank you for sharing

**Comment by bucuri** [comment]
I also had the same problem after updating to react-admin 3.12.1. It uses @material-ui/core@^4.11.2". 

What I did is delete yarn.lock (or package.json.lock for npm) and then reinstall all packages.
