### ISSUE TITLE
Always redirecting to first page when make an edit or delete to an item in the list

### ISSUE THREAD

**Issue by gamemn02** [marmelab/react-admin#4902]
**What you were expecting:**

when you open another page in a list other than the first page then chose to edit or delete an item, it should stay in the current page to allow editing other items without changing the page again
**What happened instead:**

after the edit or delete is done, the list view is directed to the first page
**Steps to reproduce:**

create any sample list with many pages.
run the app.
open the second page in the list.
select an item and click the delete bulk action button.
**Related code:**

this not my sandbox but it can be used to reproduce the problem
https://codesandbox.io/s/nice-dawn-95btl
**Other information:**

i am not sure if this is a bug or a normal behavior. if it is not a bug consider closing the report
**Environment**

* React-admin version: 3.6.0, 3.5.5, 3.0.0-alpha.0
* React version: 16.13.1
* Browser: chrome 83.0.4103.97 (Official Build) (64-bit) and in codesandbox.io

**Comment by djhi** [comment]
Hi and thanks for the report. I can reproduce the issue on the simple example as well

**Comment by LaMarseillaise** [comment]
I have also encountered this issue, specifically with editing from the list page. While this is addressed, can you suggest any work-arounds?
