### ISSUE TITLE
When authenticating with OAuth a "Please login to continue" message is displayed

### ISSUE THREAD

**Issue by 09wattry** [marmelab/react-admin#4903]
We are actively developing a customer portal using React Admin. We have been very happy with the quality of the product and the wide feature set. I know this is not technically the place since there is another project, however, we are trying to get some momentum. There have been several challenges but we have managed to overcome them and as part of the community we have been encouraged to try to contribute to this project where we can. In saying that we are well established in the nodejs environment, however, we are new to ReactJs so please forgive me if I am overlooking something.

**What you were expecting:**
Using an object authProvider and an OAuth flow we expect that on login no error messages to be displayed.

**What happened instead:**
On successful login, we receive a "Please login to continue" message even though there is a token.

**Steps to reproduce:**
I have taken the time to update the [ra-example-oauth](https://github.com/marmelab/ra-example-oauth) project with a pure OAuth approach. I had to remove some of the stylings to simplify the process.

**Related code:**
[The  issue  to upgrade](https://github.com/marmelab/ra-example-oauth/issues/5)

[My branch](https://github.com/09wattry/ra-example-oauth/tree/wattry/app)

Using the branch provided and valid Google OAuth credentials this should be fairly straight forward to reproduce. Please let me know if there is anything I can do.

**Environment**

* React-admin version: 3.5.5
* React version: 16.13.1
* Browser: Chrome & Firefox
* Stack trace (in case of a JS error): There is no stack trace provided.

**Comment by fzaninotto** [comment]
Hi, and thanks for your input. 

We focus our open-source efforts on maintaining the react-admin core. The example you're referring to is not in the core and, indeed, not maintained. 

If you need assistance on OAuth, I suggest you contact Marmelab for professional services.

I'm closing this issue as it's also posted in the ra-example-oauth repository.

**Comment by 09wattry** [comment]
I have created a [pull request](https://github.com/marmelab/ra-example-oauth/pull/9/) after fixing the issue.
