### ISSUE TITLE
Default ordering should be as provided by API endpoint instead of id ascending

### ISSUE THREAD

**Issue by olivierdalang** [marmelab/react-admin#4906]
**What you were expecting:**

When not explicitly specified otherwise (by using `<List sort={{...}}>` or with user sorting), no sorting parameters should be set, so that the default API sorting is used.

**What happened instead:**

Instead, react-admin forces sorting on ascending id (it appends `&order=id.asc` to the queries).
This is harmless (and also useless) when using autoincrementing keys, but harmful when using UUIDs, as you get a random order. Also, it prevents from respecting the API default sorting, which usually follows some logic that may not be reproduce-able without multiple field sorting (see https://github.com/marmelab/react-admin/issues/2602)

**Steps to reproduce:**

Just display a List of a resource using UUIDs.

**Environment**

* React-admin version: 3.5.5

**Comment by fzaninotto** [comment]
I agree that there should be no sort by default, however this is a breaking change. So at best, this will be done in v4.

**Comment by fzaninotto** [comment]
After trying to address this issue in `next`, I noticed that it breaks every dataProvider that expects a default sort - basically every third-party dataProvider. That's really not something we want to push in v4. 

Besides, there is a workaround: in your dataProvider, if the sort order is the default, remove it. 

So I'm going to close this issue as "won't fix". I know it's not ideal, but the benefit / cost ratio isn't there for this feature.
