### ISSUE TITLE
Add ability to make the <SaveButton> not disabled by default

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#4913]
In `<Edit>` and `<Create>` forms, the `<SaveButton>` is rendered disabled until the user enters a change (i.e. as long as the form is still in `pristine` state).

In some cases (e.g. a form wizard), that's inconvenient. 

Currently, to bypass the disabled default, a developer needs to write their own `<SaveButton>`, create a custom Toolbar, and pass that to the Form. That's a lot of work to get what used to be the default behavior. 

we need to provide a simple way to disable the `pristine = disabled` feature.

**Comment by UltimateForm** [comment]
hello @fzaninotto do you guys intend to work on this any time soon? This is kinda of critical to a project I'm working on since I'm using wizards and dialogs inside the form.

**Comment by fzaninotto** [comment]
Fixed by #5002
