### ISSUE TITLE
Errors while running demo example independantly

### ISSUE THREAD

**Issue by rohinrohin** [marmelab/react-admin#4917]
**What you were expecting:**
Expected application to start without errors

**What happened instead:**
Lot of dependency issues

**Steps to reproduce:**
Clone the repo
cd examples/demo
npm install 
npm start

Is there a way to quickly start building from the demo application directly?

Thanks!

**Comment by fzaninotto** [comment]
Please follow the manual.

https://github.com/marmelab/react-admin#setup

**Comment by rohinrohin** [comment]
I am able to follow the manual and build within this repo. However my question is more regarding how do I eject the demo out of this repo. I would like to use the entire demo code in a different repo.

**Comment by fzaninotto** [comment]
For "how to" questions, as explained in the issue template, please use StackOverflow.
