### ISSUE TITLE
Does <Resource />  support inner routes ?

### ISSUE THREAD

**Issue by JasurN** [marmelab/react-admin#4921]
Thank you for a really good framework. 

I am using Django Rest dataProvider and it works fine. 

**What you were expecting:**

When I put ``` <Resource name='warehouse/rolls'
 options={{label: 'All Rolls'}} list={RollsList}/>```
at the buttom, it goes and fetches when I click on Rolls Consumption or   Rolls Income ```warehouse/rolls/consumption```,  ```warehouse/rolls/income```,
``` 
const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name='warehouse/rolls/consumption' options={{label: 'Rolls Consumption'}} list={RollsConsumptionList}/>
        <Resource name='warehouse/rolls/income' options={{label: 'Rolls Income'}} list={RollsIncomeList}/>
        <Resource name='warehouse/rolls' options={{label: 'All Rolls'}} list={RollsList}/>
        <Resource name='warehouse/papers/formats'/>
    </Admin>
);
```

**What happened instead:**
But when I put ```<Resource name='warehouse/rolls' options={{label: 'All Rolls'}} list={RollsList}/>``` at the beginning, it doesn't make request or nothing happens. 
```
const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name='warehouse/rolls/consumption' options={{label: 'Rolls Consumption'}} list={RollsConsumptionList}/>
        <Resource name='warehouse/rolls/income' options={{label: 'Rolls Income'}} list={RollsIncomeList}/>
        <Resource name='warehouse/rolls' options={{label: 'All Rolls'}} list={RollsList}/>
    </Admin>
);
```

**Environment**

* React-admin version: 3.5.2
* React version: 16.13.1
* Browser: Chrome Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by djhi** [comment]
This is due to React Router Switch component. You must place the more specific routes first.

**Comment by kopax** [comment]
For automatic ordering I personally use a `sort`:

```jsx
      <Admin {...props}>
        {(permissions) => this.getResourcesRoutes(permissions)
          .sort((a, b) => a.props.name.length < b.props.name.length ? 1 : -1) /* this fix https://github.com/marmelab/react-admin/issues/2910 temporary */}
      </Admin>
```

**Comment by JasurN** [comment]
- One solution that I did was to change `api/warehouse/rolls` to `api/warehouse/rolls/all` in my Django backend. It works as intended.
- If I put more specific first, then All rolls item is placed at the bottom. Which is not good for my case. 
![image](https://user-images.githubusercontent.com/23478773/84226662-db3de000-aafb-11ea-94da-3418a929be03.png)
