### ISSUE TITLE
Custom Menu permissions prop not updated (Non-static permissions)

### ISSUE THREAD

**Issue by atomicacorn** [marmelab/react-admin#4922]
**What you were expecting:**
Following the documentation for implementing [permissions in the app](https://marmelab.com/react-admin/Authorization.html) (more specifically the Restricting Access to a Menu section), I store the user's permissions in localStorage and use the permissions to hide resources from the menu. 

The permissions I get on initial load are correct, however if the localStorage changes this is not reflected in the Menu's permission prop (see Menu code below).

This problem also affects any resource components that I have added permissions to restrict certain views, such as list or edit, as these receive the props from Admin.

**What happened instead:**
The permissions are the same as when the app first loads/user logs in.

**Steps to reproduce:**
I was able to replicate my problem using the code sandbox posted in Related Code below (I limited the Tags resource to only show if you have admin permissions from the Admin component). I also added some logging out of permissions prop from an instance of the usePermissions hook from Menu to show it does not get the latest permissions.

If you log in as with user/password to get the user role, the menu displays the Users resource, and you do not see Tags (correct), but if you change the localStorage permissions to be admin, I can only get the Menu to retrieve the updated permissions on a hard refresh.

**Related code:**

Code Sandbox: https://codesandbox.io/s/damp-hooks-kjklt?file=/src/index.js 

Custom Menu layout:
```
import React from 'react';
import { useSelector } from 'react-redux';
import { useMediaQuery } from '@material-ui/core';
import {
  DashboardMenuItem,
  MenuItemLink,
  getResources,
  usePermissions,
  useTranslate,
} from 'react-admin';
import inflection from 'inflection';
import { ViewList as DefaultIcon } from '@material-ui/icons';
import { icon as TermsAndConditionsIcon } from 'resources/TermsAndConditions';
import { isSuperAdmin, isApprover } from 'utils/roles';

const translatedResourceName = (resource, translate) =>
  translate(`resources.${resource.name}.name`, {
    smart_count: 2,
    _:
      resource.options && resource.options.label
        ? translate(resource.options.label, {
            smart_count: 2,
            _: resource.options.label,
          })
        : inflection.humanize(inflection.pluralize(resource.name)),
  });

const Menu = ({ onMenuClick, logout }) => {
  const { permissions, loaded, error } = usePermissions();

  const isXSmall = useMediaQuery(theme => theme.breakpoints.down('xs'));
  const open = useSelector(state => state.admin.ui.sidebarOpen);
  const resources = useSelector(getResources);
  const translate = useTranslate();

  return (
    <div>
      <DashboardMenuItem onClick={onMenuClick} sidebarIsOpen={open} />
      {resources.map(resource =>
        resource.name === 'TermsAndConditions' ? (
          isSuperAdmin(permissions) && (
            <MenuItemLink
              key={resource.name}
              to={
                resource.name !== 'TermsAndConditions'
                  ? `/${resource.name}`
                  : '/terms-and-conditions'
              }
              primaryText={
                translatedResourceName(resource, translate) || resource.name
              }
              leftIcon={resource.icon ? <resource.icon /> : <DefaultIcon />}
              onClick={onMenuClick}
              sidebarIsOpen={open}
            />
          )
        ) : resource.name === 'Inspection' ? (
          isApprover(permissions) ? (
            <MenuItemLink
              key={resource.name}
              to={`/${resource.name}`}
              primaryText={
                translatedResourceName(resource, translate) || resource.name
              }
              leftIcon={resource.icon ? <resource.icon /> : <DefaultIcon />}
              onClick={onMenuClick}
              sidebarIsOpen={open}
            />
          ) : null
        ) : (
          <MenuItemLink
            key={resource.name}
            to={`/${resource.name}`}
            primaryText={
              translatedResourceName(resource, translate) || resource.name
            }
            leftIcon={resource.icon ? <resource.icon /> : <DefaultIcon />}
            onClick={onMenuClick}
            sidebarIsOpen={open}
          />
        )
      )}
      {isXSmall && logout}
    </div>
  );
};

export default Menu;
```

**Other information:**

**Environment**

* React-admin version: 3.5.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.0
* Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by atomicacorn** [comment]
Update:

I've mapped the localStorage response to props and that returns the latest permissions for me, but this is a workaround:

```
const mapStateToProps = state => ({
  formState: state,
  userPermissions: JSON.parse(localStorage.getItem('permissions')),
});

export default connect(
  mapStateToProps,
  {} // Avoid connect passing dispatch in props
)(Menu);
```

I would have still expected usePermissions hook to return the latest permissions by calling the getPermissions function in AuthProvider, unless (and highly likely) I've misunderstood/misused the hook? The hook works fine when called in a specific resource.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by atomicacorn** [comment]
@djhi Apologies, when I was writing this ticket originally I was at my wits end! What I was actually trying to say is I believe <Admin /> does not adopt changes to permissions prop, even though authProvider.getPermissions is being called.

I've used ra permissions model in other apps where the permissions were unlikely to change during a user's session, so inevitably a hard refresh or a logout/login would pick up a change in the user's permission.

What I've found in a more recent app that has a multiple role permissions model is that when the permissions change during a user's session is that the permissions prop that comes from `<Admin />`, never changes. This is the permissions prop passed down to all my resource components and layout components, which means that the permissions logic added to fields and the like never changes, unless the user refreshes the browser or logs back in.

This has led me to have to use the `usePermissions` hook in my resources pages (not custom pages) in order to ensure I get the updated permission prop. The Menu component was more tricky, as I had to hook in state changes, as per my [prev comment](https://github.com/marmelab/react-admin/issues/4922#issuecomment-641222893). Regardless it has made the permissions that has passed out of `<Admin />` in my app redundant.

Apologies is this is still considered a support ticket- I have read and implemented permissions as per docs and it has worked perfectly in the past when user permissions were unlikely (or it was not crucial) that they changed, hence why I feel the need to raise a bug ticket for discussion.

**Comment by djhi** [comment]
Hi @atomicacorn, thanks for the detailed answer. Would you mind trying to create a CodeSandbox based on our [simple example](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and update it to show the issue? It would help debugging it.

**Comment by atomicacorn** [comment]
@djhi I made a code sandbox originally, but that seems to have broken :/ After some fiddling I think I've made one that demonstrates what I mean: Here you go! https://codesandbox.io/s/condescending-moser-ieor3

Here I made use of already existing logins for user/password (set role to user) and admin/password (set role to admin). To demonstrate what I mean I pass the permissions prop from Admin to the Posts section, and if the user is not an Admin if they try to create the post they will see a (horribly unstyled- code sandbox kept breaking when I brought in styles :/) Access Denied page. Otherwise Admin users would see normal create post page.

To simulate the permissions changing, I've added three buttons to the filter section of the list page, clicking on each sets the role in local store. There is logging demonstrating the getPermissions function being called and returning the correct value from locale store.

My expectation would be that if getPermissions is called the permissions prop should reflect that in local store, so your components and rerender and display correct view.

**Comment by fzaninotto** [comment]
I've managed to change permissions in the simple example: log in with use/password, you see 3 resources. Log out, then log in with admin/password, you see 4 resources.

So yes, it requires logging in an out, but how would you get more permissions without going through a new authentication?

**Comment by atomicacorn** [comment]
@fzaninotto thanks for looking into this and for your and team mates replies. Apologies for the delay in reply, I'm on a reduced work week.

So in previous apps we have sent the permissions through on tokens (provided they weren't too big)- this meant what when a token was requested in checkAuth I would update the permissions stored.

In the most recent app, the user roles could potentially become quite long, as they had roles within companies which were a resource with CRUD actions. In this case we make an authenticated request after successful login to get permissions, then request permission role updates as a side effect when specific actions occur- e.g. a user created a company. This meant they now have an updated role that links them to that company and the UI should reflect that.

I respect what I'm asking may be outside the scope of core react-admin. I have managed to achieve the sort of behaviour I needed (as detailed in the [comment above](https://github.com/marmelab/react-admin/issues/4922#issuecomment-641222893)) by mapping state to props in my custom menu, and by calling usePermissions hook everywhere I need to- but this feels like a misuse, as I am no longer using the permissions prop passed in from Admin.

**Comment by fzaninotto** [comment]
I don't understand why you don't make the call for permissions inside the `authProvider.login()` method. Also, I don't understand the permission role update. For me permissions are read-only.

**Comment by djhi** [comment]
@atomicacorn If I understand correctly, you have dynamic permissions which should have effects on the menu when they change.

First, note that you don't have to store the permissions in localstorage. You could make a call to your API to get "fresh" permissions each time.

Then, even though it's not really clear in the documentation, both [`authProvider.getPermissions`](https://marmelab.com/react-admin/Authentication.html) and [`usePermissions`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/auth/usePermissions.ts#L45) accept an argument called `params`. In the case of the hook, it means it will call the `authProvider.getPermissions` again if `params` changes.

What you could do is create a custom `useDynamicPermissions` which would react to an external change (localstorage change event, custom redux action, etc.) to update a `params` stored in a React `useState`. This `params` would be used by `usePermissions` which would then update correctly.

**Comment by atomicacorn** [comment]
@fzaninotto @djhi thanks for your responses. Yes, @djhi you've hit the nail on the head- furthermore the permissions prop that is passed down to resources from Admin doesn't change after the first call to `authProvider.getPermissions`, so my resources permission logic wasn't reflecting on changes in localStorage.

Thanks for the hint! Will bear it in mind. We wanted to try and reduce the number of calls to the backend, but it's a good solution for when I definitely need to know the latest permissions.

Ah! I had totally missed the params arg in `usePermissions`. That's should do the trick on the Menu. Thank you! 👍
