### ISSUE TITLE
Ids for radio inputs when using react element for choices is set incorrectly

### ISSUE THREAD

**Issue by helenwilliamson** [marmelab/react-admin#4924]
**What you were expecting:**
When creating a `RadioButtonGroupInput` using a react element for the choices, I expect that the rendered inputs will have unique ids

**What happened instead:**
Instead the rendered inputs will end up with the same id

**Steps to reproduce:**
Create `RadioButtonGroupInput` as per https://marmelab.com/react-admin/Inputs.html#radiobuttongroupinput using a React element:

```
const choices = [
   { id: 123, first_name: 'Leo', last_name: 'Tolstoi' },
   { id: 456, first_name: 'Jane', last_name: 'Austen' },
];
const FullNameField = ({ record }) => <span>{record.first_name} {record.last_name}</span>;
<RadioButtonGroupInput source="gender" choices={choices} optionText={<FullNameField />}/>
```

Check ids for radio inputs in rendered html. They're all `gender_[object Object]`

**Proposed fix:**
Change https://github.com/marmelab/react-admin/blob/ae64892c72f25c908d20eae2b87b4983cf9df00a/packages/ra-ui-materialui/src/input/RadioButtonGroupInputItem.tsx#L29 to the following:

```
const nodeId = `${source}_${value}`;
```

**Comment by djhi** [comment]
Hi and thanks for the report. Would you mind openning a pull request with the proposed fix?
