### ISSUE TITLE
 get the roles previously linked to users

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#4925]
Hello, i have a problem i cannot solve, and i think im following the documentation to the letter.
I want to obtain the assigned roles when im editing the user, for example if exist a user "Daniel", which has "Administrator" and "Editor" roles. When im editing that user i would like to obtain those assigned roles.

my code is:
```
> export const UserEdit = props => (
>     <Edit title={<RoleTitle />} {...props}>
>         <SimpleForm validate={validateUserEdition}>
>             <TextInput source="name" />
>             <TextInput source="email" type="email" />
>             <TextInput source="password" type="password" />
>             <ReferenceInput label="Role" source="role" reference="role">
>                 <AutocompleteArrayInput source="id" {...props} />
>             </ReferenceInput>
>         </SimpleForm>
>     </Edit>
> );
```
Add the endpoint format where check my API:
`GET to /user/{user}/role`

someone help me with this please?

**Comment by kopax** [comment]
You need to wrap your edit:

```js
const UserShow = props => (
    <EditController {...props}>
        {controllerProps =>
            <EditView {...props} {...controllerProps}>
                <SimpleForm>
                    <TextInput source="username" />
                    <TextInput source="email" />
                    {controllerProps.record.role.includes(roles.ROLE_ADMINISTRATOR) && (
                    <ReferenceInput label="Role" source="role" reference="role">
                      <AutocompleteArrayInput source="id" {...props} />
                    </ReferenceInput>
                  )}
                </SimpleForm>
            </EditView>
        }
    </EditController>
);
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by DanielSanchez94** [comment]
Hello, I still cannot solve my problem, the resources that I have in my administrator are user and role, but I imagine that with those resources they are enough to have the relationship between the two.

Again, when I edit a user, I need to be able to view and edit the roles associated with it.

my code is the follow

export const UserEdit = props => (
<Edit title={<RoleTitle />} {...props}>
    <SimpleForm validate={validateUserEdition}>
        <TextInput source="name" />
        <TextInput source="email" type="email" />
        <TextInput source="password" type="password" />
        <ReferenceInput label="Role" source="role" reference="role">
            <AutocompleteArrayInput source="id" {...props} />
        </ReferenceInput>
    </SimpleForm>
</Edit>
);

in app.js

const App = ( ) => (
    <Admin dashboard={ Dashboard } dataProvider={ dataProvider } authProvider={ authProvider }>
        <Resource name="user" list={ UserList } create={ UserCreate } edit={ UserEdit } icon={ UserIcon }/>
        <Resource name="role" list={ RoleList } create={ RoleCreate } edit={ RoleEdit } icon={ ContactsIcon }/>
   </Admin>
);

Thank

**Comment by DanielSanchez94** [comment]
Hello, I still cannot solve my problem, the resources that I have in my administrator are user and role, but I imagine that with those resources they are enough to have the relationship between the two.

Again, when I edit a user, I need to be able to view and edit the roles associated with it.

my code is the follow

```
export const UserEdit = props => (
<Edit title={<RoleTitle />} {...props}>
    <SimpleForm validate={validateUserEdition}>
        <TextInput source="name" />
        <TextInput source="email" type="email" />
        <TextInput source="password" type="password" />
        <ReferenceInput label="Role" source="role" reference="role">
            <AutocompleteArrayInput source="id" {...props} />
        </ReferenceInput>
    </SimpleForm>
</Edit>
```
);

in app.js

```
const App = ( ) => (
    <Admin dashboard={ Dashboard } dataProvider={ dataProvider } authProvider={ authProvider }>
        <Resource name="user" list={ UserList } create={ UserCreate } edit={ UserEdit } icon={ UserIcon }/>
        <Resource name="role" list={ RoleList } create={ RoleCreate } edit={ RoleEdit } icon={ ContactsIcon }/>
   </Admin>
);
```

Thank
