### ISSUE TITLE
Allow multiple GraphQL queries to satisfy a react-admin 'verb'

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#4932]
**Is your feature request related to a problem? Please describe.**
Some GraphQL APIs do not support some of the verbs required by react-admin in a single query. For instance, they may not support GET_MANY([ids]) in which case GET_MANY needs to be supported via multiple GET_ONE(id) calls. The current `buildQuery` only allows for a single GraphQL query before the response is passed to `parseResponse`
Similarly for a mutation, an `updateMany` may require multiple `updateOne` calls on some APIs.

**Describe the solution you'd like**
Allow an optional `queries` key in the return from `buildQuery`, that, if present, would take precedence over `query` key, and that holds an array of GraphQL queries. Only when all queries are resolved, will the response be provided (as an array, each element being the response from each GraphQL operation) to `parseResponse` which then would be responsible for correct formatting expected by react-admin

**Describe alternatives you've considered**
None - described solution keeps compatibility with current solution

**Additional context**
(none)

**Comment by djhi** [comment]
The solution is to build your own GraphQL dataProvider. Use the existing ones as starting points.

**Comment by bayareacoder** [comment]
Sure but I propose to make some small changes to `ra-data-graphql` so it can support multiple GraphQL queries to fulfill a single react-admin verb.  Like this, by adding a `queries` key and variables that get iterated over. In file `index.js`:
```
// allow for a `queries` key that takes precedence
    const operation = getQueryOperation(query.queries || query.query);

    // GRAPHQL QUERY
    if (operation === "query") {
      if (!query.queries) {
        // single GraphQL query
        const apolloQuery = {
          ...query,
          fetchPolicy: "network-only",
          ...getOptions(otherOptions.query, aorFetchType, resource),
        };

        return client
          .query(apolloQuery)
          .then((response) => parseResponse(response));
      }
      else {
        // multiple GraphQL queries
        const prs = query.variables.map(variables => {
          const { queries, ...rest } = query;
          const apolloQuery = {
            ...rest,
            query: queries,
            variables,
            fetchPolicy: "network-only",
            ...getOptions(otherOptions.query, aorFetchType, resource),
          };
          return client.query(apolloQuery);
        })
        return Promise.all(prs).then(responses => parseResponse(responses));
      }
    }
```

Then a caller can use this as follows to satisfy GET_MANY Shops for a GraphQL API that only supports GET_ONE Shop, in a file `buildQuery` (this is what you customize for your API):
```
return {
            queries: gql`
              query get${resourceName}($shopId: ID!) {
                shop(id: $shopId) {
                  ${buildFieldList(
                    introspectionResults,
                    resourceName,
                    raFetchType
                  )}
                }
              }
            `,
         variables: shopIds.map((shopId) => ({ shopId })),
            parseResponse: (responses: any[]) => {
              const result = {
                data: responses.map((response) => response.data.shop),
                total: responses.length,
                resource: "Shop",
              };
              return result;
            },
          };
```
