### ISSUE TITLE
Edit view do not load on browser refresh

### ISSUE THREAD

**Issue by manohar719** [marmelab/react-admin#4935]
On browser refresh at Edit View, the data is has to be visible in ui,
instead it is showing blank screen.

https://codesandbox.io/s/confident-snowflake-u8f03?file=/src/posts.js

Steps to reproduce,
1. Open the codesandbox given above, browse to /booking
2. Click on booking menu
3. In first record, click on Edit and refresh the browser. It will load the data in ui
4. Same step for Second record, UI do not load data

**Other information:**
I am using UUID 

**Environment**

* React-admin version: 3.6.0

**Comment by djhi** [comment]
If you look at the network tab, you'll notice that your backend return an object as the payload of the first record but returns an array as the payload of the second.

**Comment by manohar719** [comment]
Thank you so much @djhi
