### ISSUE TITLE
useQuery does not reload on refresh()

### ISSUE THREAD

**Issue by jesseshieh** [marmelab/react-admin#4938]
**What you were expecting:**

When `refresh()` is called, `useQuery` should reload data. `useQueryWithStore` reloads data properly because it depends on the `version`, but `useQuery` does not. 

`useQueryWithStore` is described in the docs with "In practice, react-admin uses useQueryWithStore instead of useQuery everywhere, and you should probably do the same in your components. It really improves the User Experience, with only one little drawback: if the data changed on the backend side between two calls for the same query, the user may briefly see outdated data before the screen updates with the up-to-date data." Which suggests to me that both will reload data from the backend.

**What happened instead:**

`useQuery` does not reload data.

**Steps to reproduce:**

Write code that uses `useQuery` and shows the data. 
Change the data on the server.
Hit the loading indicator icon to refresh or call `refresh()` somewhere in code.
See data is not updated.

**Other information:**

useVersion in useQueryWithStore is here
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useQueryWithStore.ts#L124

But not used in useQuery here
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useQuery.ts#L69

**Environment**

* React-admin version: 3.6
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Historically, the responsibility of depending on the version for a side effect was on the controller, not on the query hook. We changed that in #4817 for `useQueryWithStore()`, but forgot to do the same for `useQuery()`.

Note that until it's fixed, you can still use the `key={version}` prop on a React component using `useQuery()` to force a remount and therefore a refetch when the version changes.

**Comment by jesseshieh** [comment]
Wow, that was so fast! Thank you!
