### ISSUE TITLE
ReferenceArrayField useReferenceArrayFieldController

### ISSUE THREAD

**Issue by L-Luciano** [marmelab/react-admin#4949]
**What you were expecting:**
I configure my ReferenceArrayField like this: 
```
<ReferenceArrayField
            source='areas'
            reference='areas'
            key='areas'
        >
            <SingleFieldList>
                <ChipField
                    source='title.fr'
                />
            </SingleFieldList>
        </ReferenceArrayField>
```

My dataprovider returns :
GET_LIST:

```{
@id: "/****/****"
@type: "User"
areas: ["/areas/9ccc74cf-b083-11ea-875a-0242ac130004"]
connectedAt: null
createdAt: "2020-06-17T10:16:45+00:00"
createdFrom: "form"
email: "***@****"
enabled: true
firstname: "****"
id: "/pathuser/a5ce0101-b083-11ea-875a-0242ac130004"
language: "fr"
originId: "a5ce0101-b083-11ea-875a-0242ac130004"
permissions: {read: true, write: true, delete: true}
role: {@id: "/pathrole/{id}", @type: "Role", name: "mon role"}
status: "waiting"
surname: "****"
}
```

GET_MANY: (for areas)

```
[{
@id: "/areas/9ccc74cf-b083-11ea-875a-0242ac130004"
@type: "Area"
allRelations: []
createdat: "2020-06-17T10:16:30+00:00"
deletable: true
enabled: false
id: "/areas/9ccc74cf-b083-11ea-875a-0242ac130004"
inseecodes: null
latitude: 47.21
longitude: -1.55
originId: "9ccc74cf-b083-11ea-875a-0242ac130004"
permissions: {read: true, write: true, delete: true, import: false, export: false}
radius: 10000
title: {fr: "Albi", en: null, es: null, ca: null, zh: null, …}
updatable: true
updatedat: "2020-06-17T10:16:30+00:00"
zipcodes: "81000"
}]
```

I expect my referenceArrayField display "Albi"

**What happened instead:**
display no value 

If I try to debug, I see the data returns by useReferenceArrayFieldController is always {}, loading stay at true and loaded at false.

```
data: {}
error: null
ids: ["/areas/9ccc74cf-b083-11ea-875a-0242ac130004"]
loaded: false
loading: true
referenceBasePath: "/areas"
```

**Environment**

* React-admin version: ^3.6.1
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error): No error

**Comment by L-Luciano** [comment]
I suppose the getMany hook does'nt work well but I don't know why.


call : useGetMany('areas', ['/areas/9ccc74cf-b083-11ea-875a-0242ac130004']
receive :
```
data: [undefined]
error: null
loaded: false
loading: true
```

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by L-Luciano** [comment]
Sorry, I can't reproduce in the CodeSandbox. 
We use a DataProvider with 2 entrypoints.
Everything looks good but the component doesn't render well.

**Comment by djhi** [comment]
Well, without a CodeSandbox we can't debug this issue
