### ISSUE TITLE
TypeScript declaration file

### ISSUE THREAD

**Issue by Rechdan** [marmelab/react-admin#4951]
I was having trouble with the TypeScript declarations, then I made a good solution:

```ts
declare module 'react-admin' {
	import * as ReactAdmin from 'react-admin/src';

	export = ReactAdmin;
}
```

Hope that helps people that are having trouble with it 😀

**Comment by djhi** [comment]
Thanks :) 
See https://github.com/marmelab/react-admin/issues/4505
