### ISSUE TITLE
Support for standard i18n source string file format

### ISSUE THREAD

**Issue by osarrat** [marmelab/react-admin#4953]
**Is your feature request related to a problem? Please describe.**
On Mobicoop Platform, we gather several components for our API, our web client, our mobile client and our admin based on react-admin. RA is apparently not using a standard monolingual or bilingual i18n source string format like .po, .yaml or .xliff files. And this make future translations of our admin more cumbersome.

**Describe the solution you'd like**
The ability to have source string in files format manageable by Weblate (or Pootle, etc.) : https://docs.weblate.org/en/latest/formats.html#supported-file-formats

**Describe alternatives you've considered**
No alternative solution available for this need.

**Comment by jdemangeon** [comment]
RA uses a plain old JS object as translation dictionnary (because of PolyglotJS that is used under the hood).

So, you're free to use the format you want and transform it to a JS object with a specific webpack loader.

@ThieryMichel have wrote a very good article about that in our tech blog (in french): https://marmelab.com/blog/2019/08/27/creer-son-propre-loader-webpack.html

**Comment by fzaninotto** [comment]
Hi Olivier,

The translation layer of react-admin is agnostic of the actual tool (and translation format) you're using for your messages. If you don't want to use the default i18nProvider based on Polyglot, you can always write your own and pass it to your `<Admin>` component, as long as it respects the same interface as the expected i18nProvider. Check the documentation here: https://marmelab.com/react-admin/Translation.html.

**Comment by osarrat** [comment]
I confirm that my need is now resolved with @jdemangeon comment: since it is easily possible to convert in RA the single multilingual i18n strings file into multiple monolingual i18n strings files, there is no issue. In monolingual format, those strings will be easily processed by Weblate or similar software.
