### ISSUE TITLE
Redirect from create to edit can have a wrong pristine due to optimistic rendering

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#4954]
**What you were expecting:**

Within a project, I have a **customer** `resources`, `<CustomerCreate />` and `<CustomerEdit />` form. 

Server side, within it's rest controller, I am :

- first saving the entities on `Stripe` (a payment system) using it's api
- then put the returned `customerStripeId` into my customer before saving the entity into my database. (The response of this controller is just the newly created id)

After creation, I have the default client redirect that brings me to the `<CustomerEdit />` form, I expect the `edit` form to have the `pristine` state with a `<Button disabled />`.

**What happened instead:**

On create redirect, I have the form in `pristine` state with the optimistic rendering, but then right after the entity fetch and the form update and lose it's `pristine` state when the `customerStripeId` is filled.

**Steps to reproduce:**

- Create a resource on a `<Create />` view that has the default redirect to edit
- Make the create controller add extra data to the entity while saving the create form.
- Notice the form values being updated and the pristine state being changed.

Pressing the application refresh button restore the `pristine=true`

**Environment**

* React-admin version: 3.6.1
* React version:  16.13.0
* Browser: Google Chrome

**Related issues**

- https://github.com/marmelab/react-admin/issues/4733
- https://github.com/marmelab/react-admin/pull/4904
- https://github.com/marmelab/react-admin/issues/4913#issuecomment-645370798

**Comment by fzaninotto** [comment]
Thanks for the report

**Comment by kopax** [comment]
Sorry about this (since I ask for the feature). Do you know why optimistic rendering can behave like this?

Either:

1. We update the form with the received values and all change made while fetching the record will be lost
2. We keep it like this.


Normally, in `react-final-form`, if you pass the updated entity into the prop `initialValues`, the whole form gets reinitialized and `pristine` would be false. I am not sure why this default behavior is not in place in react-admin v3.
