### ISSUE TITLE
ReferenceParentField?

### ISSUE THREAD

**Issue by calebfaruki** [marmelab/react-admin#4956]
**Is your feature request related to a problem? Please describe.**

`<ReferenceField />` works great for the "has one" relationship. But it's counter-intuitive to standard REST patterns when dealing with "belongs to" relationships.

**Describe the solution you'd like**

But when you're doing standard REST and you have a parent association, shouldn't you be able to do a `GET /:parent_id` request instead of a `GET /:child_id?where[parent_id]=parent_id`

**Describe alternatives you've considered**

In my own project, I duplicated the `<ReferenceField />` component, renamed it `<ReferenceParentField />` and simply changed the `useGetOne` hook instead of `useGetMany`. It works beautifully.

Alternatively, you could support a configuration option in `useReference` to support either a "has_one" or "belongs_to" option and conditionally use `useGetOne` or `useGetMany` based on that configuration.

**Comment by revskill10** [comment]
Thanks for the great idea, could you please post the gist here for us to see ?

**Comment by calebfaruki** [comment]
https://gist.github.com/calebfaruki/4bfafa237bc14768b3bd86dbe9c75af4

**Comment by fzaninotto** [comment]
I'm happy that you managed to write your own ReferenceField to replace the one from react-admin that didn't fit your need. Note that you can also change the request in the dataProvider. 

However, we don't want to add the possibility to change the request issued by a ReferenceField in the react-admin core, so I'm closing this issue.
