### ISSUE TITLE
Show doesn't render SimpleShowLayout after refresh

### ISSUE THREAD

**Issue by llizon** [marmelab/react-admin#4958]
**AC**
- Resource component has a List component with Datagrid
- Datagrid has `rowClick="show"` to render Show component on row click

**Expected behaviour:**
- Show component should be rendered after click on List row and also when go to show url directly

**What happened instead:**
- Show component is rendered after click on List row, but when user refresh the page or just go to show url directly, the component isn't rendered

**Steps to reproduce:**
- click on List row
- Show component should be rendered properly
- refresh the page
- Show component isn't rendered

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

**Other information:**
- no errors in console

**Environment**

* React-admin version: 3.6.0

**Comment by djhi** [comment]
I cannot reproduce this on the simple example which you linked in the issue without modifying it. I assume the problem is in your code. Please provide a fork of the codesandbox showing the issue.

**Comment by llizon** [comment]
I couldn't also reproduce on sandbox, after some debugging I found the problem - my data for record doesn't contain `id` property. I'm closing as this is not an issue
