### ISSUE TITLE
jsonplaceholder is down

### ISSUE THREAD

**Issue by NikitaVlaznev** [marmelab/react-admin#4960]
jsonplaceholder used in the tutorial is not working.
Here is a URL the tutorial is trying to fetch:

    curl -v https://jsonplaceholder.typicode.com/users?_end=10&_order=ASC&_sort=id&_start=0

It shows sometimes a "heroku application error" sometimes a "520 Origin Error".

**Comment by fzaninotto** [comment]
Then you should open an issue in the jsonplaceholder repository ;)

**Comment by NikitaVlaznev** [comment]
Definately, if my goal would be to make jsonplaceholder work.
But the goal is to have a react-admin with working tutorial.
This goals are not the same.
May be it would be better for react-admin to stop using them and switch to some offline server.
