### ISSUE TITLE
There should be a way to disable pagination

### ISSUE THREAD

**Issue by faizan-tariq** [marmelab/react-admin#4965]
There should be a way to disable pagination

Right now i don't think there is a way to disable pagination. It would be great to have this feature. 
Thanks.

**Comment by fzaninotto** [comment]
There is a way: pass `pagination={false}` to the `List` component.

**Comment by hvqzao** [comment]
Setting `pagination={false}` on `List` component hides pagination component, but dataProvider request still attempts to fetch range of data. From what I see in the code there is no way to do that unfortunately.

**Comment by ali-hellani** [comment]
You can modify this process in your custom data provider inside GET_LIST

taking for example this [https://github.com/marmelab/admin-on-rest/blob/49a616c93d1ee5ea0bfa3c5f7abea0bb29c8d01c/src/rest/simple.js](url)

modify the query like this:
```
if (perPage > 0) {
    query.range = JSON.stringify([
           (page - 1) * perPage,
           page * perPage - 1,
    ]);
}
```
