### ISSUE TITLE
Label on SearchInput partially hides searched text

### ISSUE THREAD

**Issue by alixdeschamps** [marmelab/react-admin#4973]
**What you were expecting:**
The label from SearchInput should not partially hides the search test
 
![Screenshot from 2020-06-23 16-18-00](https://user-images.githubusercontent.com/9588479/85415101-35638a00-b56d-11ea-9338-a5bdfb23704e.png)

**Steps to reproduce:**
Add a label prop to a SearchInput and enter some text in the search field

**Related code:**
Here is a fork from your sandbox, I just added the label prop to the SearchInput
https://codesandbox.io/s/admiring-butterfly-zj21v?file=/src/posts/PostList.js

**Environment**

* React-admin version: 3.6.1
* React version: 16.3.1
* Browser: Chrome and codeSandbox browser

**Comment by djhi** [comment]
Reproduced. Thanks for reporting. We should at least automatically add an `aria-label` on this input.

**Comment by fzaninotto** [comment]
We should just throw an exception if you set a label on the SearchInput. It's not designed to contain a floating label. If you want a floating label, use a TextInput.

**Comment by Raidro** [comment]
> 

but, if I need to use an input with ICON, especifically searchIcon, like seachInput has, how can I use with TextInput? because in documentation TextInput can't receive a iconProp!

**Comment by slax57** [comment]
@Raidro you might want to have a look at https://mui.com/material-ui/react-text-field/#input-adornments
