### ISSUE TITLE
Support of "NaN" in json data

### ISSUE THREAD

**Issue by yeus** [marmelab/react-admin#4980]
**What you were expecting:**

I have a restful API which sometimes creates json data with "NaNs" ("keywords") in it:

```
[{
  "keywords": NaN,
  "name": "Wixel Programmable USB Wireless Module (Fully Assembled)",
  "distance": 0.017472684383392334,
  "id": "661ec0b6-18c3-47fb-8cd8-ae09bfdd8e0e",
  "score": 8.51261725437658
}]
```

**What happened instead:**

Instead of just treating it as if it was empty, I get an error.

**Steps to reproduce:**

Provide a REST API with "NaNs" as values

**Related code:**

**Other information:**

**Environment**

* "react": "16.13.1",
* "react-admin": "3.4.2",
* Browser: Chrome 83.0.4103.61
* Stack trace (in case of a JS error):

```
TypeError: Cannot read property 'map' of undefined
    at idsReducer (1.chunk.js:235873)
    at cachedRequestsReducer (1.chunk.js:235844)
    at combination (1.chunk.js:310881)
    at 1.chunk.js:235756
    at Array.reduce (<anonymous>)
    at 1.chunk.js:235750
    at combination (1.chunk.js:310881)
    at combination (1.chunk.js:310881)
    at resettableAppReducer (1.chunk.js:227663)
    at dispatch (1.chunk.js:310634)
    at 1.chunk.js:189695
    at 1.chunk.js:183900
    at 1.chunk.js:229212
```

Hope you guys can help me with this, thank you for react-admin it is awesome!

**Comment by fzaninotto** [comment]
The simple rest dataProvider bundled with react-admin expect the JSON to be well-formed.

If that assumption doesn't fit your use case, you'll have to [write your own dataProvider](https://marmelab.com/react-admin/DataProviders.html#writing-your-own-data-provider).
