### ISSUE TITLE
Feature request - useListController, useListParams params not attached to redux store or query from location

### ISSUE THREAD

**Issue by gomcodoctor** [marmelab/react-admin#4982]
**Usage case:**

We are trying to show sub resource list in main resource list view

e.g.
1. We have list of users
2. We want to show all articles posted by a user as row expand on grid.

**Issue:** 
1. when we expand first user, it show its articles, but when we click second user, it keep showing articles of first user ( for few sec ) due to optimistic rendering 

``
 When the user changes the page/sort/filter, this controller runs the
    useGetList hook again. While the result of this new call is loading,
   the ids and total are empty. To avoid rendering an empty list at that
   moment, we override the ids and total with the latest loaded ones.
``

2. when we try to navigate to second page for articles, users page also navigate because of query from location.
3. Params from redux store are for Main list not for custom query.

**Proposed solution:**

1. Add new props in List component, named 

> 1. UseQueryFromLocation
> 2. UseParamFromStore 
> 3. UseOptimisticRendering

which can be set to false if we are using for subresource list
2.  remove defaultId if  UseOptimisticRendering is false

`const defaultIds = useSelector(
        (state: ReduxState): Identifier[] =>
            get(state.admin.resources, [resource, 'list', 'ids'], [])
    );
`

3. change if UseParamFromStore  is false

`const params = useSelector(
        (reduxState: ReduxState) =>
            reduxState.admin.resources[resource]
                ? reduxState.admin.resources[resource].list.params
                : defaultParams,
        shallowEqual
    );
`
to

` const [params, setParams] = useState(defaultParams);
`

and

`      dispatch(changeListParams(resource, newParams));
`

to

`   setParams(newParams);
`
4. remove if UseQueryFromLocation is false

`    const queryFromLocation = parseQueryFromLocation(location);
`

**Comment by fzaninotto** [comment]
Without the code you use, it's hard to tell if the problem comes from your usage of react-admin, or from react-admin itself. 

Please post a link to a CodeSandbox showing the problem, as requested in the issue template.

**Comment by gomcodoctor** [comment]
This is not issue.. This is feature request..

Currently useListParams use  Param from redux store and location, it's causing issue if we are using multiple list view on single page

**Comment by gomcodoctor** [comment]
This is one of use case where this new feature can be helpful

https://stackoverflow.com/questions/59883643/how-to-not-change-the-url-on-list-filtering-with-react-admin

**Comment by fzaninotto** [comment]
This is not something we'll implement, but it's feasible in user land. See the `useListController` code: it's only glue on top of several specialized hooks. You can assemble the hooks that best fit your case. 

Also, react-admin provides the `<ReferenceManyField>` for the use case you describe.
