### ISSUE TITLE
React admin throws error when a dashboard calls `useGetOne`

### ISSUE THREAD

**Issue by gavacho** [marmelab/react-admin#4985]
**What you were expecting:**

I expected the Dashboard component to be able to call `useGetOne`

**What happened instead:**

An exception is thrown:

```
Error: No <Resource> defined for "posts". useGetOne() relies on the
Redux store, so it cannot work if you don't include a <Resource>.
```

**Steps to reproduce:**

Load the application's root url so that react-admin will render the Dashboard component first.

**Related code:**

Here is a minimal patch to reproduce: https://github.com/marmelab/react-admin/commit/8bf35dda2d1331b872ab414b993ee5d2a69c12e6

**Environment**

* React-admin version: 3.6.2
* Last version that did not exhibit the issue (if applicable): 3.5.5 (at least)
* React version: 16.12.0
* Browser: Firefox
* Stack trace (in case of a JS error):
```
    in PostShow (created by Dashboard)
    in Dashboard (created by WithPermissions)
    in WithPermissions (created by Context.Consumer)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Context.Consumer)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Context.Consumer)
    in withRouter(WithStyles(Layout)) (created by ConnectFunction)
    in ConnectFunction (created by LayoutWithTheme)
    in ThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme
    in Unknown (created by Context.Consumer)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Context.Consumer)
    in Route (created by CoreAdminUI)
    in Switch (created by CoreAdminUI)
    in CoreAdminUI (created by AdminUI)
    in AdminUI (created by Admin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by CoreAdminContext)
    in TranslationProvider (created by CoreAdminContext)
    in Provider (created by CoreAdminContext)
    in CoreAdminContext (created by AdminContext)
    in AdminContext (created by Admin)
    in Admin
```

**Comment by fzaninotto** [comment]
Confirmed and reproduced, thanks for the report.

It's a race condition: going to the dashboard after loading another page doesn't show the error.

**Comment by fzaninotto** [comment]
So the `Dashboard` renders right away, before the effect in `<Resource intent="registration">` has dispatched the resource registration. It's the same for `<Resource intent="routes">`, but in this case we already have a security mechanism in place:

https://github.com/marmelab/react-admin/blob/2fb3fc9f46eec09bd46ab71209ae47c7e8faf6ec/packages/ra-core/src/core/Resource.tsx#L48-L59

We just miss the same security for the dashboard.

**Comment by fzaninotto** [comment]
I've reverted #4988 as it's the wrong fix, so I'm reopening this issue.
