### ISSUE TITLE
Layout width too large

### ISSUE THREAD

**Issue by ybarbaria** [marmelab/react-admin#4986]
**What you were expecting:**
I except the layout will take the available width and not extand the body width.
The scrollbar should be inside the List and not into the body. 
I would like to know if there is any solution to fix that. 

**What happened instead:**
When I use my react admin app on my laptop (1536x864 Screen Width: 1536 pixels Screen Height: 864 pixels) the datagrid doesn't fit the space available and the body display a scrollbar.

![layout-width](https://user-images.githubusercontent.com/5574663/85913896-f09d6300-b88c-11ea-8859-f31694aa78a6.png)

**Steps to reproduce:**
Create a react admin app and use a List and launch the website on a laptop.

My List component
```
export const ChallengeList = props => (
    <List {...props}>
        <Responsive
            medium={
                <Datagrid rowClick="edit">
                    <TextField source="title" />
                    <TextField source="instructions" />
                    <TextField source="link" />
                    <TextField source="reference" />
                    <NumberField source="level" />
                    <NumberField source="duration" />
                    <TextArrayField source="categories">
                        <SingleFieldList>
                            <ChipField source="id" />
                        </SingleFieldList>
                    </TextArrayField>
                </Datagrid>
            }
        />
    </List >
);

```

My app 

```
 const App = () => (
   <Admin dataProvider={dataProvider} authProvider={AuthProvider}>
     <Resource name="challenges" list={ChallengeList} edit={ChallengeEdit} create={ChallengeCreate} />
   </Admin>
 );
```

**Environment**

* React-admin version:  3.6.2
* React version: 16.13.1
* Browser: Chrome  83.0.4103.116

**Comment by fzaninotto** [comment]
We made the decision to avoid multiple horizontal scrollbars, therefore the body isn't fixed in width. You can use a custom Layout if your users have different needs.

**Comment by ybarbaria** [comment]
@fzaninotto such a weird decision usually grids should host the scrollbar but anyway I will found a solution on my own.

**Comment by AymanElarian** [comment]
@ybarbaria   can you share it please
