### ISSUE TITLE
User profile creation documentation is outdated

### ISSUE THREAD

**Issue by SergejNosko** [marmelab/react-admin#4999]
I found that this article https://marmelab.com/blog/2019/03/07/react-admin-advanced-recipes-user-profile.html was written using react-admin v2.6.1. But this code isn't working fully with the latest version. When the profile page is reloaded an error occurs with this message `No <Resource> defined for "profile". useGetOne() relies on the Redux store, so it cannot work if you don't include a <Resource>.`, but `Resource` is included. Is it possible to update the article or explain how to make it's code work with the latest version of react-admin? Thank you.

**Comment by djhi** [comment]
This error is actually the one described in #8985. Closing as duplicate.
