### ISSUE TITLE
New prop to ReferenceInput child component: count

### ISSUE THREAD

**Issue by situplastik** [marmelab/react-admin#5001]
ReferenceInput child component already have some interesting props such as `choices` `loading` or `pagination`.

https://marmelab.com/react-admin/Inputs.html#referenceinput

It would be great to have a `count` prop with the total of items of the query. React Admin already ask that info to the API, so I expect that is not a nightmare to included it.

I'm doing a pagination inside a `ReferenceInput` in order to show all the results and helps the final user to select the reference that they want. With the actual props (`pagination.perPage` and `pagination.page`) I cannot know when there are not loaded items.

The resource that I want to reference doesn't have `List` view so I cannot get the total items resources from redux structure.

Thanks for all the react-admin system, it works really well!

**Comment by djhi** [comment]
Hi, thanks for this feature request. We're planning to revisit the Reference components (fields and inputs). You can see the beginning of this work in #4952 with the introduction of the `ListContext`.

**Comment by situplastik** [comment]
Wou, good to know that on the next release (3.7.0) I will have the option to solve it. I suggest passing another prop to the component but if I can get all the list props with ListContext it will be perfect. Great job!

**Comment by WiXSL** [comment]
`ReferenceInput` has been refactored in #7185 to support more features, including the ones described here, so I'm closing his enhancement request.
