### ISSUE TITLE
Highlight current page on pagination

### ISSUE THREAD

**Issue by TCM5** [marmelab/react-admin#5003]
**Is your feature request related to a problem? Please describe.**
In the list pagination, the current page number is lacking on caption/focus when many pages are displayed. Sometimes, when too many numbers are dispalyed in pagination, it's hard to check the current page that the user it's in.

![imagem](https://user-images.githubusercontent.com/9709208/86457960-6174cd00-bd1c-11ea-8af3-c148af095c6a.png)

**Describe the solution you'd like**
Just like the core pagination style on Material-UI. They make the current page with a background color (like a badge component). This differenciates the current page from others, like this:

![imagem](https://user-images.githubusercontent.com/9709208/86457919-4dc96680-bd1c-11ea-91d6-9ae4bdeeb8e3.png)

**Describe alternatives you've considered**
An alternative is to implement my own list, overriding the default pagination component. But I think this should be RA native, because it will take theme in consideration.

**Comment by fzaninotto** [comment]
Nice! I didn't notice Material-ui had added this background color. It's a good idea.

**Comment by fzaninotto** [comment]
Note: the material-ui Pagination component appeared in version 4.9 of the library.

**Comment by jdemangeon** [comment]
This feature is always in the `@material-ui/lab` package. Should we wait for the `@material-ui/core` integration before include it @fzaninotto?

**Comment by fzaninotto** [comment]
Yes, and that means waiting for material-ui@5.0

**Comment by TCM5** [comment]
@fzaninotto MUI core v5 was released with a stable version. Will this upgrade be migrated to 4.0 milestone?

**Comment by palyvodaBoi** [comment]
@fzaninotto +1

**Comment by WiXSL** [comment]
This feature was added in #7120 and set to be released in v4.0.0-alpha.2
