### ISSUE TITLE
Bug with incorect name field 

### ISSUE THREAD

**Issue by romaaan-ur** [marmelab/react-admin#5007]
Hi, I runnied this project in weekends, but have many bugs with Command, Category entity. I'm migrationed from MySQL to PostgreSQL, saw code and edit name fields, where published = 1 reedit for true.
And project started in normally, without bugs and errors.

**Comment by Luwangel** [comment]
Hi,

I'm not sure to understand if you describe a bug, a need for documentation or just a remark. Could you tell us more or give us a CodeSandbox to highlight your issue?

As explained in the bug report template:
1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by fzaninotto** [comment]
No news for some time, closing.
