### ISSUE TITLE
New prop to CreateButton: defaultValues

### ISSUE THREAD

**Issue by TCM5** [marmelab/react-admin#5008]
**Is your feature request related to a problem? Please describe.**
Currently is possible to set `defaultValues ` to the `ListView`, but this values are defined during list creation, not to prior actions. As a use case, sometimes we want to create a new record but based on the current list filters (this is just an example). This seems like `CloneButton` behaviour, but no... Because in this case, this will be is just a way to define default values outside Create/Edit view

Using the RA demo as an example, on the Posters List View, and if we filter by category, then it could be possible that when the `CreateButton` is clicked it could "transport" the current category filter value to the CreateView default values. 

**Describe the solution you'd like**
To make this possible, the create button should have a prop called default values or options. If this prop is not given, the current behaviour should mantain. Somethin like this:

```
 <Button component={Link}
         to={defaultValues ? 
               { pathname: `${basePath}/create`, state: { record: defaultValues }} : `${basePath}/create` 
            }
         className={className}
         label={label}
         variant={variant}
         {...rest as any}
        >
         {icon}
 </Button>
```

**Comment by fzaninotto** [comment]
I don't understand what's wrong with the solution documented here: https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record. 

```jsx
const CreateRelatedCommentButton = ({ record }) => (
    <Button
        component={Link}
        to={{
            pathname: '/comments/create',
            state: { record: { post_id: record.id } },
        }}
    >
        Write a comment for that post
    </Button>
);
```

Could you please elaborate? 

Also, I think that what you ask will be possible in the next bugfix release thanks to #5014

**Comment by TCM5** [comment]
Sorry @fzaninotto, you're so right! I didn't notice the [#5014](https://github.com/marmelab/react-admin/pull/5014)... This is related to the problem that I was trying to describe. 

You can close this.

**Comment by rkfg** [comment]
For the future reference here's my more or less full solution to the exact same problem (prefilling the new item form according to the filter values), it's mostly copypasted from the [already mentioned docs](https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record):
```js
const ListActions = ({
  className,
  resource,
  filters,
  displayedFilters,
  filterValues,
  showFilter,
  permanentFilter,
  total,
  ...rest
}) => <TopToolbar className={className} {...sanitizeListRestProps(rest)}>
    {filters && cloneElement(filters, {
      resource,
      showFilter,
      displayedFilters,
      filterValues,
      context: 'button',
    })}
    <CreateButton to={{
      pathname: '/records/create',
      search: `?source=${JSON.stringify({ organization_id: filterValues.organization_id, department_id: filterValues.department_id })}`,
    }} />
  </TopToolbar>;
export const RecordList = (props) => <List actions={<ListActions />} {...props}>
// rest of list
```
