### ISSUE TITLE
<SelectArrayInput /> fail to get index value properly

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#5018]
**What you were expecting:**

I want to add a filter on my list for the status id.

`<SelectArrayInput />` should have the unique id key prop.

**What happened instead:**

It has duplicate id

**Related code:**

```jsx
    <ReferenceInput
      source="statusIn"
      reference="status"
      perPage={500}
      alwaysOn
      allowEmpty
    >
      <SelectArrayInput
        optionText="description"
      />
    </ReferenceInput>
```

**Other information:**

My status looks like this :

```jsx
{
  "_embedded" : {
    "promotionStatuses" : [ {
      "id" : 5,
      "description" : "Deleted",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/promotion-management/status/5"
        }
      }
    }, {
      "id" : 4,
      "description" : "Unpublished",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/promotion-management/status/4"
        }
      }
    }, {
      "id" : 3,
      "description" : "Published",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/promotion-management/status/3"
        }
      }
    }, {
      "id" : 2,
      "description" : "Created",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/promotion-management/status/2"
        }
      }
    }, {
      "id" : 1,
      "description" : "Draft",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/promotion-management/status/1"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/promotion-management/status?page=0&size=500&sort=id,desc"
    }
  },
  "page" : {
    "size" : 500,
    "totalElements" : 5,
    "totalPages" : 1,
    "number" : 0
  }
}
```

This before `dataProvider` convertion, what's important there is that I don't have duplicate status id and I have a description for all of them.

**Environment**

* React-admin version: 3.7.0
* React version: 3.10.1
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by Luwangel** [comment]
Hello,

Thank you for opening this issue.

The `<SelectArrayInput>` component returns a list of `<MenuItem>`. They all have a key corresponding to the `optionValue` provided to the `<SelectArrayInput>`. By default, the key corresponds to the `id` of the choice.

Your code should work and I need more context to reproduce the issue. So I invite you to create a code sandbox wrapping your scenario.

As explained in the bug report template:
1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by fzaninotto** [comment]
No news for too long, closing.
