### ISSUE TITLE
Rendering a Datagrid outside of a resource

### ISSUE THREAD

**Issue by oliverox** [marmelab/react-admin#5020]
react-admin version 3.7.0

Hi!
I used to be able to render a Datagrid not attached to a specific resource. I used to pass the Datagrid an array of items via the `data` prop and their respective ids via the `ids` prop. How to achieve this now in version 3.7.0?
Based on the following lines, it seems RA is now only reading the ListContext for data and ids. I am unable to find a way to pass my `data` and `ids` props to my Datagrid now. Thank you for your help.
https://github.com/marmelab/react-admin/blob/bc9ac4e3123baa79ec4ba2d579fee083414ec9c8/packages/ra-ui-materialui/src/list/Datagrid.tsx#L84-L96

**Comment by fzaninotto** [comment]
Hi,

You must now enclose your Datagrid inside a `ListContext.Provider`. See the jsdoc of that component for details.

**Comment by megantaylor** [comment]
i just ran into this issue when i tried to upgrade from 3.3.0. its no longer clear from docs how to do datagrids with custom data. what ended up working was:

```
<ListContext.Provider
// @ts-ignore (we will remove this at some point and pass in the rest of the data that is required)
      value={{
        data,
        currentSort,
        ids
      }}
    >
<DataGrid  /> // dont need to pass additional `data`, `ids` or `currentSort` props
    </ListContext.Provider>
```

based on the documentation we initially tried using `useListController` but that requires the data to be stored a certain way in redux and for my use case was not the right answer. hope this helps someone else.
