### ISSUE TITLE
SelectInput/SelectArrayInput/AutocompleteArrayInput don't update selections when choices update

### ISSUE THREAD

**Issue by bard** [marmelab/react-admin#5022]
**What you were expecting:**

Selected items in SelectInput, SelectArrayInput, and AutocompleteArrayInput, should stay consistent with the available choices. If choices change to no longer include one or more of the selected values, those should be automatically deselected, similarly to what appears with a plain HTML `<select/>` input when removing `<option/>` elements.

**What happened instead:**

When the underlying choices change, selected items remain the same, leading UI state and API requests that are inconsistent with the data model.

**Steps to reproduce:**

1. `git clone https://github.com/bard/repro-update-choices-in-select-array`
2. `yarn install && yarn start`
3. navigate to `http://localhost:3000/#/users/1` — only projects available for client "Acme, Inc." are selectable, and "Roadrunning" is selected
4. change client to "Sirius Cybernetics"
5. "Roadrunning" project stays selected, even if it belogs to "Acme, Inc."

**Related code:**

https://github.com/bard/repro-update-choices-in-select-array

**Environment**

* React-admin version: 3.7.0
* React version: 16.13.1
* Browser: Chromium

**Comment by rkfg** [comment]
[It's a design decision](https://github.com/marmelab/react-admin/issues/2431#issuecomment-446493639), was reported multiple times and will not be changed it seems. There's a solution in the comments as well but it's outdated, you don't need to use Redux directly now. Add the following handler to your first (main) `ReferenceInput`:
```js
onChange={() => {
    form.change('projects', null);
  }
```
Also add `const form = useForm();` before that and don't forget to `import { useForm } from 'react-final-form';`

**Comment by bard** [comment]
Thanks @rkfg. Pity, because pretty much everywhere in react-admin (as far as I've seen) it's impossible to produce data with invalid relationships.

**Comment by Luwangel** [comment]
@rkfg You're right. We use final form since the last major version. And as it's possible to use the `onChange` callback, we didn't do anything in `React-Admin`.

I'm closing this issue.

Have a good day,
Adrien
