### ISSUE TITLE
Independent row selection for TabbedShowLayout(Tabs) so that Bulk Actions are Tab specific 

### ISSUE THREAD

**Issue by AnanthChristy** [marmelab/react-admin#5030]
**Is your feature request related to a problem? Please describe.**
`<TabbedShowLayout/>`  carries the selection through all the tabs. This forces the Bulk Action button to be a common action that can be performed on all the Tabs. 

Selecting multiple items from different tabs makes it hard to perform different actions on them. I will need extra validation in the UI to display how many were selected from each list and also need backend validation for each item. 

![image](https://user-images.githubusercontent.com/12214160/87072229-48fb2b80-c1d0-11ea-8855-fe9947576d6e.png)

Creating a 'Submenu' with three list pages also did not help as the selection was based on the basePath which is the API route.

**Describe the solution you'd like**
We need to have a way in which each of these tabs have different bulk actions performed on them based on the filters.
Ex: 'Ordered' list can be marked as delivered. 'Delivered' can be marked as canceled, etc. 

We would like to have a way to switch between universal selection or independent selection in TabbedShowLayout. Maybe something like a 'rowClickVariant: universal | independent'. This way we maintain the Bulk Actions independent for the list for those who need it.

**Describe alternatives you've considered**
Created a SubMenu for the three lists pointing to three different API's so that the selection is not common across the lists.
![image](https://user-images.githubusercontent.com/12214160/87073374-266a1200-c1d2-11ea-9769-34e2156e2237.png)

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

The screenshot you joined, from the ecommerce demo, uses a custom component (TabbedDatagrid) that is not published in the react-admin package. It's just here for the sake of the demo, and is not meant to be reused. 

So we won't implement the feature you describe in react-admin. If you need guidance on how to implement it, I suggest you ask a question on stackOverflow using the react-admin tag.

**Comment by AnanthChristy** [comment]
Sorry about that. I realized that it was StyleTabbedDatagrid a little later and came here to correct it.

Thanks for the information.
