### ISSUE TITLE
Is there any facility to provide guesser components with GraphQL schema details?

### ISSUE THREAD

**Issue by rassie** [marmelab/react-admin#5034]
(not on StackOverflow since there's probably no clear answer and I consider it a kind of discussion topic, maybe enable discussions on the Github project?)

I'm currently struggling to put the pieces together to implement a combo of Flask and GraphQL (via Graphene-SQLAlchemy, which is strongly Relay-influenced) on the backend with `react-admin` on the frontend. Having somehow managed to implement what `ra-data-graphql-simple` expects of me, I couldn't help to notice that all the additional information from GraphQL's schema is ignored.

For example, I can restrict the API to only allow the `name` field to be updatable (which is reflected in the introspection query which `ra-data-graphql-simple` uses), however this is not at all reflected in `EditGuesser`, which proposes to make all fields from the model editable. Same is true for GraphQL typings which would make guesses so much more reliable, but GraphQL's data provider has no obvious way to provide `EditGuesser` with presumed types.

I can imagine other data providers would be able to provide extra information to different parts of `react-admin` to make the out-of-the-box experience more smooth. Is this a desirable aim for the project? What would be the best way to proceed, it that's the case?

**Comment by fzaninotto** [comment]
The people at API Platform have written a set of react-admin guessers based on the Hydra schema, which provides a lot of information (kind of like the GraphQL schema you're referring to). Theses guessers do indeed produce better results than the simple guessers provided by react-admin. Maybe you can use their code as inspiration?

[api-platform/admin](https://github.com/api-platform/admin)

As for adding more intelligence to the default react-admin guessers, I'm afraid we don't have any standard to base that upon.
