### ISSUE TITLE
ReferenceInput adds a buggy DOM property "pagination" to the inner SelectInput

### ISSUE THREAD

**Issue by rkfg** [marmelab/react-admin#5037]
It's not a serious bug but rather a weirdness, at least I haven't noticed any malfunctions. Found it while fixing another issue in my own code. You can see it in the demo app.

**What you were expecting:**

No redundant DOM properties that don't make sense.

**What happened instead:**

The `<div>` representing `SelectInput` has a DOM property `pagination` with value `"[object Object]"` which clearly means something not working as expected. Doesn't seem to happen with `AutocompleteInput`.

**Steps to reproduce:**

Open [this url](https://marmelab.com/react-admin-demo/#/products?displayedFilters=%7B%22category_id%22%3Atrue%7D&filter=%7B%7D&order=ASC&page=1&perPage=20&sort=reference), use `Inspect element` on the `Category` filter.
![2020-07-11_20-52-06](https://user-images.githubusercontent.com/184066/87230375-6b4f9d80-c3b8-11ea-8b6d-f518dd71b88a.jpg)
Note the `undefined` class as well, might be worth looking into.

**Comment by Luwangel** [comment]
Hi, thanks for submitting this issue.

I've opened a PR to sanitize this prop. You can take a look :wink:
