### ISSUE TITLE
sanitizeEmptyValues should not touch properties that do not belong to form fields

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#5043]
continuation of https://github.com/marmelab/react-admin/issues/4942#issuecomment-657501184

but i think its best to open a new issue, because the bug is related but not the same.

**What you were expecting:**

when saving a record, form fields that contain objects as values are not altered. object as values should be treated as opaque and should not be touched. These objects could be representations of a rich-text-field or content editor like [react-page](https://github.com/react-page/react-page)

**What happened instead:**

saving a record may alter object values of form fields because there is a recursive function `sanitizeEmptyValues` which tries to sanitize any object tree it finds. This might lead to unexpected `[key]: null` in your opaque object.

in particular, `sanitizeEmptyValues` only takes in the current record and the old record and does not check which properties in the tree belong to form fields.

A solution would be that `sanitizeEmptyValues` in `submit` would use the final form `api.getRegisteredFields` (api is second unused argument to submit) to check which properties are form fields and would only sanitize these fields and wont be called recursivly. see this code: https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/FormWithRedirect.tsx#L95

**Steps to reproduce:**

- create a custom form field that contains an object tree (with arrays)
- create a record
- update this record in a way that a nested property of this custom form field is changed
- sanitizeEmptyValues will then go recursilvy through your object value and might add [key]: null properties

**Environment**

* React-admin version: 3.7.1
* Last version that did not exhibit the issue (if applicable): 3.5.3 (actually it already exists there, but its not that severe because arrays are unaltered
* React version: 16.13.1
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Fixed by #5077

**Comment by macrozone** [comment]
@fzaninotto can still be reproduced in 3.9.4.
