### ISSUE TITLE
ListBase does not render "Add Filter" button

### ISSUE THREAD

**Issue by zivaricha** [marmelab/react-admin#5045]
**What you were expecting:**

When using the new customisable `ListBase` example shown in the documentation,
the "Add Filter" button suppose to be rendered on the top right corner of the list page.

**What happened instead:**

the 'Add Filter' button is missing.

**Steps to reproduce:**

Just copy the short code snippet displayed in the List documentation. (under ListBase)

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

I suspect the problem is inside ListView.tsx
https://github.com/marmelab/react-admin/blob/bc9ac4e3123baa79ec4ba2d579fee083414ec9c8/packages/ra-ui-materialui/src/list/ListView.tsx

`ListToolbar` uses `ListView` internally, which is suppose to render `defaultListActions` if no actions was sent to it via props.
But it doesnt. so using `ListToolbar` as follows (very similar to documentation), the "Add Filter" button will not be rendered.
```
const MyList = (props: any) => {
  const {
    title,
    filters,
    actions,
    bulkActionButtons,
    children,
    ...rest
  } = props;
  return (
    <ReactAdmin.ListBase {...props}>
      <h1>{title}</h1>
      <ReactAdmin.ListToolbar
        filters={filters}
      />
      <Card>
        <ReactAdmin.BulkActionsToolbar>
          {bulkActionButtons}
        </ReactAdmin.BulkActionsToolbar>
        {cloneElement(children, {
          hasBulkActions: bulkActionButtons !== false,
        })}
        <ReactAdmin.Pagination />
      </Card>
    </ReactAdmin.ListBase>
  );
};
```

But, if I explicitly send the `ListActions` component to `ListToolbar` component, it works and the "Add Filter" button is rendered and functional.
```
const MyList = (props: any) => {
  const {
    title,
    filters,
    actions,
    bulkActionButtons,
    children,
    ...rest
  } = props;
  return (
    <ReactAdmin.ListBase {...props}>
      <h1>{title}</h1>
      <ReactAdmin.ListToolbar
        filters={filters}
        actions={<ReactAdmin.ListActions/>}
      />
      <Card>
        <ReactAdmin.BulkActionsToolbar>
          {bulkActionButtons}
        </ReactAdmin.BulkActionsToolbar>
        {cloneElement(children, {
          hasBulkActions: bulkActionButtons !== false,
        })}
        <ReactAdmin.Pagination />
      </Card>
    </ReactAdmin.ListBase>
  );
};
```

**Other information:**

**Environment**

* React-admin version: 3.7.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.4
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Yes, that's actually the point of the `ListBase` component, it only provides the bare minimum without any UI. It's meant to allow you to build a fully custom List. You'll have to use the `useListContext` hook which is also explained in the documentation
