### ISSUE TITLE
TabbedForm: getActiveTab

### ISSUE THREAD

**Issue by TCM5** [marmelab/react-admin#5046]
**Is your feature request related to a problem? Please describe.**
Sometimes some custom logic is performed based on the current active FormTab. For example, show aside component only if a specific tab is focused.

**Describe the solution you'd like**
One of this:

- Have an utility method to retrieve the current active tab, the index of it
- Allow to add an onChangeTab callback

**Describe alternatives you've considered**
An alternative is to inspect the current location using `useLocation` hook and extract the tab key from the path

**Comment by Luwangel** [comment]
Hi,

Thanks for submitting this feature request. But it's already possible to get the active tab.

- The first solution is to parse the location as you said in the alternative you considered.
- The second one is to pass an `onChange` callback to the `<TabbedForm>`.

I simplified the `<PostEdit>` component from the Simple Example of React-Admin to show you how to do it:

```js
const PostEdit = (props) => (
    <Edit {...props}>
        <TabbedForm
            tabs={
                <TabbedFormTabs
                    onChange={(event, value) => {
                        console.log('onChange', event, value); // On Tab Change
                    }}
                />
            }
        >
            <FormTab label="post.form.summary">
                <TextInput disabled source="id" />
            </FormTab>
        </TabbedForm>
    </Edit>
);
```

Material-UI also provides a [`<TabContext>` component](https://material-ui.com/api/tab-context/). It comes from the lab and we don't implement experimental components in React-Admin. But you can do it on your side.

If you have any question, you can use the [React Admin Channel on StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

Regards,
Adrien
