### ISSUE TITLE
onSuccess used without redirect can't submit form twice

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#5047]
I am using the following `Edit`:

```
    <Edit
      title={<MyProfileTitle />}
      onSuccess={() => {
        notify('resources.users/profile.success', 'info');
        setReset(!reset);
      }}
      {...rest}
    >
```

After submitting once the form, I am not able to submit again the form despite values get change and button is shown in a non disabled state.

react-admin : 3.7.0

**Comment by kopax** [comment]
There's `const refresh = useRefresh();` for that.

**Comment by ede-vagyok** [comment]
It does't work for me with `refresh()` neither.

**Comment by djhi** [comment]
@ede-vagyok Please open a new issue and follow the template

**Comment by nik-lampe** [comment]
@ede-vagyok @djhi 

I came across this too. Opened a issues following the template at #5195
