### ISSUE TITLE
Cannot read property 'ui' of undefined

### ISSUE THREAD

**Issue by rk-rohit** [marmelab/react-admin#5057]
I am integrating the react-admin in react boilerplate (**https://github.com/react-boilerplate/react-boilerplate** ).When trying to access resource. then getting error of 

![image](https://user-images.githubusercontent.com/34423257/87634595-3ac28780-c75b-11ea-8d91-fd886901806d.png)
![image](https://user-images.githubusercontent.com/34423257/87634632-4c0b9400-c75b-11ea-89b6-2fd632a4a345.png)

**Comment by Luwangel** [comment]
Hi,

Thank you for opening this issue :pray:

It should be an issue with Redux. But I need to reproduce the problem you describe.

Could you provide a CodeSandbox?

As explained in the bug report template:
1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by rk-rohit** [comment]
Thanks Luwangel, I have got the solution.
I was not passing the admin Reducer that's why the error was coming.

**Comment by Rapido102** [comment]
what do you meam by passing the admin Reducer ?
