### ISSUE TITLE
Switching order problem in ReferenceManyField

### ISSUE THREAD

**Issue by timofeyp** [marmelab/react-admin#5059]
**What you were expecting:**
I want to use sorting inside `ReferenceManyField`, as it works on `List` components: by clicking at column name, and then component switches its list order DESC\ASK.

**What happened instead:**
Just first click works. And there is order indicate icon just near first clicked column. No this icon on next clicked columns.

![2020-07-16 18-56-42 2020-07-16 18_57_52](https://user-images.githubusercontent.com/37977572/87694500-f3f28300-c796-11ea-905e-882edb473198.gif)

**Steps to reproduce:**
Just click at column names in app with `ReferenceManyField` component.

**Related code:**
```
`import React from 'react';
import PropTypes from 'prop-types';
import {
  Show,
  TextField,
  TabbedShowLayout,
  Tab,
  DateField,
  NumberField,
  ReferenceManyField,
  Datagrid,
  Pagination,
} from 'react-admin';
import SessionActions from 'components/Actions/SessionActions';

const View = (props) => (
  <Show
    actions={<SessionActions id={props.id} />}
    title={`Пользователь #${props.id}`}
    {...props}
  >
    <TabbedShowLayout>
      <Tab label="Инфо">
        <TextField label="Имя" source="first_name" />
        <TextField label="Отчество" source="middle_name" />
        <TextField label="Фамилия" source="last_name" />
        <NumberField label="Телефон" source="phone" />
      </Tab>
      <Tab label="Карты" path="body"></Tab>
      <Tab label="Девайсы" path="devices">
        <ReferenceManyField
          target="user_id"
          reference="devices"
          addLabel={false}
          pagination={<Pagination />}
        >
          <Datagrid>
            <TextField source="id" />
            <DateField source="created_at" />
            <DateField source="updated_at" />
            <TextField source="vendor_id" />
            <TextField source="push_token" />
          </Datagrid>
        </ReferenceManyField>
      </Tab>
      <Tab label="Сессии" path="sessions">
        <ReferenceManyField
          target="user_id"
          reference="sessions"
          addLabel={false}
          pagination={<Pagination />}
        >
          <Datagrid>
            <TextField source="id" />
            <DateField source="created_at" />
            <DateField source="updated_at" />
            <DateField source="expired_at" />
            <TextField source="useragent" />
          </Datagrid>
        </ReferenceManyField>
      </Tab>
    </TabbedShowLayout>
  </Show>
);

View.propTypes = {
  id: PropTypes.string,
};

export default View;
`
```

**Other information:**

**Environment**

* React-admin version: "^3.7.1"
* Last version that did not exhibit the issue (if applicable):
* React version: "^16.13.1"
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by Luwangel** [comment]
Hi,

Thank you for opening this issue :pray:

I need to reproduce the problem you describe in order to fix it quickly.

As explained in the bug report template:
1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by timofeyp** [comment]
> Hi,
> 
> Thank you for opening this issue 🙏
> 
> I need to reproduce the problem you describe in order to fix it quickly.
> 
> As explained in the bug report template:
> 
> 1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
> 2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
> 3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.
> 
> Regards,
> Adrien

So, bug is already in your template. Look at gif.

![2020-07-27 19-48-50 2020-07-27 19_50_50](https://user-images.githubusercontent.com/37977572/88569112-a1d91980-d042-11ea-8f03-976b53ed855c.gif)
