### ISSUE TITLE
CodeSanbox not working

### ISSUE THREAD

**Issue by rudza** [marmelab/react-admin#5066]
**What you were expecting:**
Codesandbox to work, so I can issue a reproducable bug

**What happened instead:**
Invalid Host header

**Steps to reproduce:**
Go to: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by Luwangel** [comment]
Thanks for reporting this issue. I can reproduce it but I don't know yet how to fix it. I'll take a look as soon as possible.
