### ISSUE TITLE
Including in another App tutorial does not work at all. Many issues.

### ISSUE THREAD

**Issue by MacMcDell** [marmelab/react-admin#5069]
**What you were expecting:**
I was expecting to be able to either copy the provided source code provided to get the app to at least compile and run. 

**What happened instead:**
createAdminStore.js: 
1: Attempted import error: 'formMiddleware' is not exported from 'react-admin'.
resolution: 
import formMiddleware from 'ra-core/lib/form/formMiddleware';
--- doesn't resolve 'formMiddleware is missing from that lib!

remove reference to formMiddleware on line 14
2: Line 26:15:  'i18nReducer' is not defined  no-undef
resolution: 
remove reference as per another related issue: 
App.js
1:cannot resolve i18n
resolution: 
none at the moment. file not provided

[createAdminStore.txt](https://github.com/marmelab/react-admin/files/4954903/createAdminStore.txt)
[admin .txt](https://github.com/marmelab/react-admin/files/4954904/admin.txt)

* React-admin version: 3.7.1
* React version:16.13.1

**Comment by Luwangel** [comment]
Hi, and thanks for reporting this issue.

It seems that someone else already reported it. To make things easier for everyone, we prefer to centralize the discussions in only one thread.

So I'll close this issue and invite you to speak about your problem directly on the original issue.

https://github.com/marmelab/react-admin/issues/5026
