### ISSUE TITLE
New Proxy DataProvider implementation doesn't properly find custom functions

### ISSUE THREAD

**Issue by hirokib** [marmelab/react-admin#5070]
Steps to reproduce

Create an admin app and pass a custom data provider

```
   <Admin
      dataProvider={dataProvider}
    ><any resources...></Admin>
```

In custom data provider, add a custom function:'

```
interface ExtendedDataProvider extends DataProvider {
   testFunction: () => void;
}
const dataProvider: DataProvider = {
  testFunction: () => {
    console.log(`called testFunction`);
  },
```

Bind to an input

```
const TestFunctionButton = (props: any) => {
  const notify = useNotify();

  const [testFunc, { loading }] = useMutation(
    {
      type: 'testFunction',
      resource: 'someResource',
      payload: { ...userData },
    }
  );

  return (
    <Button label="Test" onClick={testFunc} disabled={loading}>
      <PostAdd />
    </Button>
  );
};
```

Results:

Uncaught Error: Unknown dataProvider function: testFunction
    at Proxy.<anonymous> (useDataProvider.js:144)

This is a regression from earlier data providers. Before we updated to 3.7.1, we were able to use custom functions with useMutation/useDataprovider without issue.

**Comment by hirokib** [comment]
I realized that I could fix the individual components by wrapping them in DataProviderContext.Provide with the custom dataprovider but this should've been initialized properly when it was passed to the Admin in the beginning. Somehow the context is not being maintained.

**Comment by djhi** [comment]
I just tried it on the simple example and it works fine. 

If you are able to illustrate the bug or feature request with an example, please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by hirokib** [comment]
Not sure but couldn't replicate the issue. Not sure why. Was updating various libraries all at once so can't be sure what it was. Thanks for the quick response and sorry.
