### ISSUE TITLE
Notifications are shown behind Confirm component

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5071]
https://codesandbox.io/s/elastic-joliot-w42qf

1.- Dashboard => Click on "Show Confirm".
2.- Click on "Confirm".

Possible Fix:
1.- Uncomment line number 18 at `App.js` : `//layout={MyLayout}";`
2.- Run it again.

**Notes**:
`MyLayout` component is a copy of react-admin's `Layout` component version 3.7.1 where I just move the line `createElement(notification)` outside the div containers.

**Comment by JulienMattiussi** [comment]
Agree with you. Opened a PR for this.
Thanks for noticed it, and reproduced it.

**Comment by fzaninotto** [comment]
Fixed by #5073
