### ISSUE TITLE
[SimpleForm, TabbedForm] warnWhenUnsavedChanges not working on a real api / data lost on cancel

### ISSUE THREAD

**Issue by glauff** [marmelab/react-admin#5081]
**What you were expecting:**
From the docs:
React-admin keeps track of the form state, so it can detect when the user leaves an Edit or Create page with unsaved changes. To avoid data loss, you can use this ability to ask the user to confirm before leaving a page with unsaved changes.
**What happened instead:**
When the user clicks "cancel" the Form State is resetted to the server values, so the user looses his data anyway.

**Steps to reproduce:**

1. Click on posts
2. Edit any post
 *  I've added a datagrid of users via a reference field to the Post Edit
3. Click on a row to edit a user
4. Change a value in the user form
5. Leave the form without saving by clicking "Back button" !important
6. You get informed of not saved values.
7. Click cancel.
8. BUG: Form is resetted to server values, and the user is loosing his changes.

I've set up a codesandbox based on the react admin tutorial operating on the real json server api to reproduce it.
 
**Related code:**
https://codesandbox.io/s/peaceful-monad-0q6r5

**Other information:**

I suppose it has something to do with the way useWarnWhenUnsavedChanges Hook is working.
The previous view gets loaded, effectively refetching the data of the referenced data.
 
**Environment**

* React-admin version: 3.7.1
* React version: 16.13.1
* Browser: Chrome

**Comment by djhi** [comment]
Reproduced. Thanks for the report

**Comment by djhi** [comment]
I'm not able to reproduce this issue on v3.8.1 anymore. Please ask to reopen if you can reproduce it. Also note that the warning when usaved is now an opt in feature (See https://marmelab.com/react-admin/CreateEdit.html#warning-about-unsaved-changes)

**Comment by SnirShnitzer** [comment]
The bug is still recurring in my code.
my code is in the latest version (3.8.1).
why is there a fetch call after the "Cancel" ?
is there a way to the detect the leave call before the url change?
and then open the confirm and on a "Cancel" click, simply do nothing..

**Comment by glauff** [comment]
Back from holiday. 
Unfortunately the bug is still there. 
I've forked another Codesandbox with react-admin explicitly set to 3.8.1:

https://codesandbox.io/s/sweet-sound-wwcbh

When I follow step 1 to 8, the bug occurs as before.
So it would be nice to reopen the issue, as it's not fixed atm.

**Comment by JoeJErnst** [comment]
I'm jumping in here to also request a re-open of this issue.  It's happening for me in version 3.12.1

**Comment by fzaninotto** [comment]
Bug confirmed, I'm reopening the issue.
