### ISSUE TITLE
BooleanInput label in index filters not changing color with theme change

### ISSUE THREAD

**Issue by xelnaga85** [marmelab/react-admin#5089]
**What you were expecting:**
When switching theme from light to dark label of BooleanInput in Filter component have to change color accordingly to the theme color (such happens to TextInput, SelectInput, etc).

**What happened instead:**
When switching theme from light to dark label of BooleanInput remains black (like with light theme).

**Steps to reproduce:**
Using the sandbox (see link below) i've created login with username demo/password demo, click on the top right button in appbar and go to configuration.
Switch theme from light to dark then access the post resource from left menu (second item from the top in the menu).
if you look at the filters default showed the second one is a BooleanInput with "test" label displayed as black.

The problems still remains when used automatic label from a "boolean" resource instead of a fixed label. I have two active project based on react admin that reproduce the same effect. (cannot share code) 

here the link to the sandbox https://codesandbox.io/s/hardcore-water-zgvvi

**Related code:**
```
const PostFilter = props => (
  <Filter {...props}>
    <TextInput label="Search" source="q" alwaysOn />
    <ReferenceInput label="User" source="userId" reference="users" allowEmpty>
      <SelectInput optionText="name" />
    </ReferenceInput>
    <BooleanInput label="test" source="test" alwaysOn /> 
     {/*The label color of BooleanInput should change when switching theme but does not.*/} 
  </Filter>
);
```

**Other information:**

**Environment**

* React-admin version: 3.7.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: firefox
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Reproduced. Thanks for reporting.
