### ISSUE TITLE
Check the render method of `SimpleFormIterator`.

### ISSUE THREAD

**Issue by erialex** [marmelab/react-admin#5090]
This error occurs in Arrayinput when associated with Autocomplete or ReferenceInput, in the simple example from this line (https://github.com/marmelab/react-admin/blob/f20546c52cd2fc2b33ee457e4eb4f4b5ab696bb7/examples/simple/src/posts/PostEdit.js#L71) that you provide, it is also visible in tabs when you have to populate the resource values
Environment
    React-admin version: 3.7.1
    React version: 16.13.1
    Browser: Chrome 84 and  Firefox 78.0.2
                  
![vokoscreen-2020-07-27_14-16-29](https://user-images.githubusercontent.com/22195890/88572683-f1edb700-d015-11ea-8da3-3daf70ca5d75.gif)

![image](https://user-images.githubusercontent.com/22195890/88572660-e8644f00-d015-11ea-94fd-63c449eb94b9.png)

**Comment by djhi** [comment]
Reproduced. Thanks for reporting.

**Comment by manishsundriyal** [comment]
Is anyone working on it?
If not then, can I?

**Comment by Luwangel** [comment]
> Is anyone working on it?
> If not then, can I?

@manishsundriyal We are not working on it. Please go ahead :)

**Comment by djhi** [comment]
I can't reproduce this issue anymore. Please ask to reopen if needed
