### ISSUE TITLE
Add GetAll hook

### ISSUE THREAD

**Issue by Niesyto** [marmelab/react-admin#5093]
I think it would be good to implement hook GetAll. Instead of getting one element like getOne or some of them, it would always return the entire resource. It would take no payload, since there's no need for them

**Comment by Luwangel** [comment]
Hello,

I think what you want is already implemented by the `getList` verb.

- `getOne` means getting one record (for example one `comment`)
- `getList` means getting a list of records (for example all `comments`)

You could read the documentation about the [data provider](https://marmelab.com/react-admin/DataProviders.html) and the [specialized hooks](https://marmelab.com/react-admin/Actions.html#specialized-hooks) to have more information.

I'm closing this issue at the moment. You can reopen it if it's necessary.

Have a good day,
Adrien

**Comment by Luwangel** [comment]
And if you have questions, you can contribute to the [React Admin Channel on StackOverflow](http://stackoverflow.com/questions/tagged/react-admin) 😊.

Regards,
Adrien

**Comment by Niesyto** [comment]
`getList `is not what I want. 
Let's say i have this array in store
```
comments: [
    {id:1, text:'a'},
    {id:2, text:'b'},
    {id:3, text:'c'},
]
```
For getList, i need to specify page, how many items per page, and sorting, like this:

```
    const { data, loading, error } = useGetList(
        'comments',
        { page: 1, perPage: 3},
        { field: 'id', order: 'DESC' }
    )

```
```
And it will return this (unless that's the fault of data provider):
{
    1:{id:1, text:'a'},
    2:{id:2, text:'b'},
    3:{id:3, text:'c'},
}
```
What I would like to have is a hook that would look like this:
```
  const { data, loading, error } = useGetList(
        'comments',
    )
```
Which would return the exact array from data provider

**Comment by Luwangel** [comment]
Pagination is the way React-Admin works. But you're free to not use it, or to implement your own verbs that you can call using the [useQuery hook](https://marmelab.com/react-admin/Actions.html#usequery-hook).
