### ISSUE TITLE
Remove deprecated sort prop in <DataGridHeaderCell>

### ISSUE THREAD

**Issue by Luwangel** [marmelab/react-admin#5096]
Follows issue https://github.com/marmelab/react-admin/issues/5059 and PR https://github.com/marmelab/react-admin/pull/5094

**Is your feature request related to a problem? Please describe.**

The renaming has already be done. But we need to remove deprecated props.

The original issue is motivated by the confusion introduced by two similar names (`sort` in `<Datagrid>` and `sort` in `<DatagridHeaderCell>`) containing different content. The first one contains an object `{ field: 'id', order: 'ASC' }` named sort and the second one `{ sort: 'id', order: 'ASC' }`.

**Describe the solution you'd like**

Remove `sort` in favor to `field` in the `<DatagridHeaderCell>`.

Files concerned:

- `packages/ra-ui-materialui/src/list/DatagridHeaderCell.js` (line 64)

**Comment by WiXSL** [comment]
Fixes #7065
