### ISSUE TITLE
[REQUEST] Make the redirect in useLogout callback optional

### ISSUE THREAD

**Issue by dejancg** [marmelab/react-admin#5099]
**Is your feature request related to a problem? Please describe.**
When using react-admin with an OpenID Connect based identity provider such as IdentityServer (https://github.com/IdentityServer/IdentityServer4) and using a library provided by the IdentityServer authors (https://github.com/IdentityModel/oidc-client-js), it's currently impossible to implement the logout flow without resorting to workarounds, because the callback returned by `useLogout` always redirects to, either login page by default, or another specified URL returned by `authProvider.logout()`. When logging out from an identity provider, `logoutRedirect` from `oidc-client-js` needs to be called, which redirects users to identity provider and logs out from there. Additionally, a logout could be initiated by identity provider itself (see Front-channel logout from the OIDC spec), by redirecting users to a page on our react-admin app, which to be implemented properly, creates the need for additional workarounds.

**Describe the solution you'd like**
A proposed solution is to modify `useLogout.ts` so `useLogout` doesn't always `push` to `history`. When an identity provider forwards users to a front-channel logout URL, the component which is configured to render at that URL should call ´useLogout´ to clear the redux state, but should be able to expect `useLogout` callback to not redirect to login or w/e. Also, in case of react-admin initiated logout, a call to ´useLogout´ callback should be able to allow any redirects initiated by `authProvider.logout` to complete, instead of pushing to the URL returned by `authProvider.logout`. 

**Describe alternatives you've considered**
The current workaround is to have two seperate methods for logout, one being `AuthProvider.logout` required by react-admin, and the other being `logoutFromIdentityProvider`. So when react-admin logs out, this gets executed:

```ts
logout = async (params: any) => {
    // ...
    // if logged in to identity provider, redirect to "/logout"
    const user = await this.userManager.getUser();
    if (user) {
      return "/logout";
    }

    // otherwise, by default, redirect to /login
    return;
  };
```

This is the LogOut component which renders at route "/logout":
```ts
const LogOut = (props: IProps) => {
  useEffect(() => {
    // calls signoutRedirect() from oidc-client
    props.authProvider.logoutFromIdentityProvider();
  }, [props.authProvider]);

  return <div>Logging out...</div>;
};
```

which effectively redirects to identity provider logout endoint and performs the real logout.

That is when a logout is initiated by react-admin, but when a logout is initiated by identity provider, I'd need to create a new route with a new component called FrontChannelLogout which only calls `useDispatch()` and then dispatches `dispatch(clearState());` to make sure react-admin is also logged out.

That's two additional unnecessary components which could've been avoided only if  `useLogout` callback didn't force a redirect.
This workaround also creates two routes which "log out" but not really, since they don't call `useLogout`. Both of them perform a partial logout, i.e. when users navigate to "/logout", they logout from identity provider without clearing the state, and when they navigate to "/front-channel-logout", they clear the state but without logging out from identity provider.

**Comment by djhi** [comment]
Thanks for the detailed request :+1: I'll mark this as an enhancement and wait for other team members inputs as I don't have much experience with OpenID
