### ISSUE TITLE
Allow third party quill modules in `ra-input-rich-text` 

### ISSUE THREAD

**Issue by thought2** [marmelab/react-admin#5101]
https://github.com/marmelab/react-admin/blob/990a4639f39f252e209648d3490e71af1a65fb1d/packages/ra-input-rich-text/src/index.tsx#L91

To me it looks, like there's no way to configure the `RichTextInput` component with additional quill modules, such as e.g. 'quill-mentions'.

Do I miss something here o should I make a PR that adds an additional prop `modules` to the component?

**Comment by djhi** [comment]
You can use the `option` prop. It's an object we spread in the Quill constructor. We should document it though.

**Comment by thought2** [comment]
Ah true, I saw it but forgot that it overrides the modules, which is what I want.

**Comment by fzaninotto** [comment]
Fixed by #5145
