### ISSUE TITLE
NumberInput accepts input it can not gracefully handle

### ISSUE THREAD

**Issue by MicroJackson** [marmelab/react-admin#5102]
**What you were expecting:**
NumberInput not accepting things that it should not accept, or handle it gracefully.

**What happened instead:**
It keeps the values entered in the input box, but the help text goes over it thinking it is empty.
Either make it empty, or accept the input. Do not display help text over input.

**Steps to reproduce:**
Goto: https://marmelab.com/react-admin-demo/#/products/112/details
Enter: 8+8 or 9e or something similar in the Stock NumberInput.
Results in:
![image](https://user-images.githubusercontent.com/39806531/89036955-fb409180-d33d-11ea-9741-c37f834fe913.png)

**Environment**
    "react": "^16.13.1",
    "react-admin": "^3.7.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting. Reproduced

**Comment by fzaninotto** [comment]
The bug comes from the underlying react-final-form library. Please open an issue in their bug tracker.

**Comment by MicroJackson** [comment]
I can not do that because I do not understand why this is a react-final-form library problem in the first place. The examples (https://final-form.org/docs/react-final-form/examples) do not show the behaviour that is shown in react-admin, so I have no clue where to start. You are right that it is a general problem, because the TextInput also does it. 
![image](https://user-images.githubusercontent.com/39806531/91190628-13fd5680-e6f4-11ea-802c-ca20323a9469.png)
Also, I do not see any issues on their tracker about this, but it is a really annoying problem, so that's a weird combination if it really is a react-final-form problem. If anyone with more knowledge about this could make an issue at react-final-form that would be great.
