### ISSUE TITLE
Cant access the full selected data on ReferenceInput  

### ISSUE THREAD

**Issue by Abenezer** [marmelab/react-admin#5105]
i have simple Reference Input 
`<ReferenceInput onChange={(ev)=>console.log(ev)}   source="record" reference="Record">
            <SelectInput    />
        </ReferenceInput>`

Reference input makes the "get many" request to get details of selected item when an item is selected. but only the id is available for onChange event. making another third request to get the full data after  onChange is redundant and inefficient.  if we can't get the full selected  data what is the use of the second request, am i missing something  ?

**Comment by djhi** [comment]
Please follow the issue template

**Comment by Abenezer** [comment]
Sorry, here is a feature request if its' not implemented already 

**Is your feature request related to a problem? Please describe.**
I usually have reference inputs with select input where i want to use the selected result (eg to modify some other field). but right now we can only get the id of selected element even after it request the complete object though "GET MANY" request.  

**Describe the solution you'd like**
onChange function should have the full object of the data as a second parameter maybe 
`<ReferenceInput onChange={(ev,data)=>console.log(ev,data)} source="record" reference="Record"> <SelectInput /> </ReferenceInput`

**Describe alternatives you've considered**
the alternative is to run the (get one) request again on onChange method to get the full data
this is redundant

**Comment by fzaninotto** [comment]
The complete reference records are available in the Redux store ; you can get the record from the id using a Redux selector in the onChange method if you want. 

As this is achievable in userland, there is no need for any change in the react-admin code, so I'm closing this issue.

**Comment by JayVansjalia** [comment]
> The complete reference records are available in the Redux store ; you can get the record from the id using a Redux selector in the onChange method if you want.
> 
> As this is achievable in userland, there is no need for any change in the react-admin code, so I'm closing this issue.

Can you please give a small example for <ReferenceInput> with <SelectInput>.
Thanks

**Comment by cydergoth** [comment]
This worked for me: 

```
export const FieldCreate = (props: any) => (
  <Create {...props}>
    <SimpleForm>
        <ReferenceInput label="Field Definition" source="definition_id" reference="catalog/field-def">
           <SelectInput optionText="name" optionValue="id" />
      </ReferenceInput>
      <FormDataConsumer>
        {
          ({ formData, ...rest }) => {
            if (formData.definition_id === undefined) {
              return (<><span>Select a field definition</span></>)
            }
            else {
              return (<Query type="getOne" resource="catalog/field-def" payload={{ id: formData.definition_id }}>
                {({ data, loading, error }) => {
                  if (loading) { return <Loading />; }
                  if (error) { return <p>ERROR {error}</p>; }
                  if (data.field_type != "datetime") {
                    return (< TextInput source="field_value" {...rest} />)
                  } else {
                    return (< DateInput source="field_value_datetime" format={dateFormatter} parse={dateParser} {...rest} />)
                  }
                }}
              </Query>);
            }
          }
        }
      </FormDataConsumer>
    </SimpleForm>
  </Create>
);
```

**Comment by shurshilov** [comment]
I think in most cases this answer will do. It’s only interesting, but if we want to do something not with a specific field, but with the entire record
 ```
     <ReferenceInput label="Field Definition" source="definition_id" reference="catalog/field-def">
           <SelectInput optionText="name" optionValue="id" />
      </ReferenceInput>
```
