### ISSUE TITLE
Exporter from list seems doesn't work 

### ISSUE THREAD

**Issue by JasurN** [marmelab/react-admin#5108]
**What you were expecting:**

In the demo you can press export in sales -> orders, it should give you a prompt to download .CSV file.   
 
**What happened instead:**
 
It loads data to the client but nothing happens.  Same issue in my current project. Exporter doesn't work
 

**Steps to reproduce:**

1. Go to https://marmelab.com/react-admin-demo/#/commands
2. Press Export

**Other information:**

**Environment**

* React-admin version: 3.7.0
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.13.1
* Browser: Google Chrome 83.0.4103.116
* Stack trace (in case of a JS error): No Error

**Comment by Luwangel** [comment]
Hello,

Thanks for reporting this issue. I don't know exactly what is wrong but we'll take a look.

You can also open a PR if you want to fix the issue.

Regards,
Adrien

**Comment by JasurN** [comment]
In the latest version 3.7.2, there is no problem with export. 
![image](https://user-images.githubusercontent.com/23478773/89557610-7fa67f00-d82c-11ea-8032-513ca77a0026.png)

**Comment by Luwangel** [comment]
I think your issue has been fixed in v3.7.1 by the following PR: https://github.com/marmelab/react-admin/pull/5032.

I'm deploying the demo with the new version.

**Comment by Luwangel** [comment]
@JasurN Published. The export bug is now fixed :partying_face:.

https://marmelab.com/react-admin-demo

Have a good day,
Adrien
