### ISSUE TITLE
redirectTo not working with QueryParams

### ISSUE THREAD

**Issue by talivodworks** [marmelab/react-admin#5114]
I was trying to pass information to login component through queryParams when checkAuth fails.

**Expectations:**
I was expecting the app to redirect to login page successfully with data in queryParams.

**What happened instead:**
It shows 404 error page.

**Steps to reproduce:**
In your _authProvider_ **reject** the promise with this object pass as argument `{ redirectTo: '/login?code=test' }`.

**Related code:**
Here is what I did in my authProvider's `checkAuth` function
```js
const REDIRECT_PARAMS = { redirectTo: '/login?code=test' };

module.exports = {
	logout: () => {
		localStorage.removeItem('token');
		return Promise.resolve();
	},
	checkAuth: async () => {
		const token = localStorage.getItem('token');
		if (!token) {
			return Promise.reject(REDIRECT_PARAMS);
		} else {
			return Promise.resolve();
		}
	},
};
```
I followed the example provided [here in the docs](https://marmelab.com/react-admin/Authentication.html).

**Other information:**

When I dig into the source code my guess is that because react-admin is passing the `redirectTo` as pathname https://github.com/marmelab/react-admin/blob/792422b33f5d8f1bd3404d717196da44bf3277d7/packages/ra-core/src/sideEffect/auth.ts#L88 and it expects the path without queryParams, and expect search params as a different key as mentioned here in the react-router [history docs](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/history.md#push) that is why it is causing the issue. I am not sure.

**Environment**

* React-admin version: 3.6.0
* React version: 16.13.1
* Browser: Google Chrome

Any help would be great. 
Thank you.

**Comment by fzaninotto** [comment]
Reproduces, thanks for the issue

**Comment by talivodworks** [comment]
@fzaninotto That really help. Thank you so much... 👍
