### ISSUE TITLE
How can I get the timing before submitting? 

### ISSUE THREAD

**Issue by shkyung** [marmelab/react-admin#5127]
both onSubmit and handleSubmit don't work for \<SimpleForm>

in 2.8version there is a way to get that timing 
https://marmelab.com/react-admin/doc/2.8/Actions.html#altering-the-form-values-before-submitting

but in the latest version I don't know how to get the moment before submitting.

and also I wanna know how I can  add "submit" event listener to \<SimpleForm>

thanks :)

**Comment by djhi** [comment]
Please follow the issue template

**Comment by timotgl** [comment]
@shkyung Sounds like you're looking for https://marmelab.com/react-admin/CreateEdit.html#transform

**Comment by shkyung** [comment]
> @shkyung Sounds like you're looking for https://marmelab.com/react-admin/CreateEdit.html#transform

yeah that's what Im looking for thanks a lot 👍
