### ISSUE TITLE
Documentation error - DataProvider example  getOne is missing return statement.

### ISSUE THREAD

**Issue by GlenMasters** [marmelab/react-admin#5138]
In the documentation on the page: https://marmelab.com/react-admin/DataProviders.html

The example for a dataprovider has this implementation for getOne.
```
    getOne: (resource, params) =>
        httpClient(`${apiUrl}/${resource}/${params.id}`).then(({ json }) => ({
            data: json,
        })),
```

It is missing the return statement.  It should read:
```
    getOne: (resource, params) =>
        return httpClient(`${apiUrl}/${resource}/${params.id}`).then(({ json }) => ({
            data: json,
        })),
```

**Comment by Luwangel** [comment]
Hi,

The documentation is correct and the `return` keyword is implicit thanks to the (arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

Regards,
Adrien
