### ISSUE TITLE
[documentation] Tree Structure for Menu

### ISSUE THREAD

**Issue by harshit-budhraja** [marmelab/react-admin#5149]
**Is your feature request related to a problem? Please describe.**
Sometime back, I had a use-case where I had to implement a menu structure similar to that in the react-admin demo app i.e. tree-view for resources.

**Describe the solution you'd like**
As a solution for this, taking inspiration from the demo, I implemented a package which could be used to quickly implement the tree structure in the ra menu. Would it be a good idea to add it in the react-admin documentation (`Ecosystem`)?

**Additional context**
Here're the ref to the package:
NPM - https://www.npmjs.com/package/@bb-tech/ra-treemenu
Github - https://github.com/BigBasket/ra-treemenu

**Comment by djhi** [comment]
Nice :) Can you open a pull request to add it to the documentation?

**Comment by harshit-budhraja** [comment]
Sure, @djhi should I open it to the `next` branch or just add it directly to `master`?

**Comment by djhi** [comment]
Please open it on `master`. Thanks!
