### ISSUE TITLE
SortButton translate reference

### ISSUE THREAD

**Issue by marcostoduto** [marmelab/react-admin#5154]
**What you were expecting:**
The SortButton should have labels based on the resource, instead the code of SortButton uses the "products" resources, code should be fixed, otherwise cannot be used.

**Related code:**
Line 74 ```field: translate(`resources.products.fields.${currentSort.field}`)```
Line 117 ```{translate(`resources.products.fields.${field}`)}```

**Environment**

* React-admin version: 3.8.1
* Last version that did not exhibit the issue (if applicable): /
* React version: 
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting!
