### ISSUE TITLE
Set initial active FormTab component

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5161]
Currently, there is no practical way of choosing a particular `<FormTab/>` component  (within a `<TabbedForm/>` component) as the active one.

**Describe the solution you'd like**
Maybe a `<TabbedForm/>` prop `initialSelectedIndex`

**Comment by Luwangel** [comment]
I think it's possible using the URL. If you need to open a specific `<Tab>`, you can change its link. For example, the link `/artists/{id}/1` will target the second tab.

We can still add a prop. But maybe it's overkill and it leads to more maintenance.

**Comment by WiXSL** [comment]
Sorry, I've forgotten about this one.
I tried redirecting and I end up in a situation where the tab became active but not the view associated with it somehow.
That lead me to believe there wasn't an easy way to initiate a particular tab.

Since  I can't reproduce the bug, this could be closed.

**Comment by djhi** [comment]
Besides, if you don't like the numeric tab, you can give each tab a path
