### ISSUE TITLE
Documentation: The documentation link is not clickable on small screens

### ISSUE THREAD

**Issue by Luwangel** [marmelab/react-admin#5166]
**What you were expecting:**

I can click on the link "Documentation" on screens which are not small enough to trigger the mobile view.

**What happened instead:**

The link is not reachable (hidden by the lego logo).

![Sélection_005](https://user-images.githubusercontent.com/5584839/90532201-3ed92f00-e177-11ea-9ffb-4f6fa2182fa5.png)

**Comment by fzaninotto** [comment]
Fixed by #5167
