### ISSUE TITLE
react admin list not show all column or scroll for large column number

### ISSUE THREAD

**Issue by AymanElarian** [marmelab/react-admin#5169]
**What you were expecting:**
I have  large amount of columns >15 columns I expect scroll bar  to scroll right or left 

**What happened instead:**
many of them hidden , and no scroll bar 

**Steps to reproduce:**
add a list with large columns amount  you will not see many of them 

**Environment**

* React-admin version:3.8.1
* Last version that did not exhibit the issue (if applicable):
* React version:16^
* Browser:chrome , safari

**Comment by djhi** [comment]
Please follow the issue template

**Comment by AymanElarian** [comment]
Done

**Comment by djhi** [comment]
Can you please provide a codesandbox with an admin preconfigured to show the issue? It would help us a lot. Thanks

**Comment by fzaninotto** [comment]
Can't reproduce on the simple example CodeSandbox - the scrollbar is there all right.

![image](https://user-images.githubusercontent.com/99944/91016659-63a52a80-e5ed-11ea-8eaa-12c58a8a2cee.png)

https://codesandbox.io/s/eager-murdock-yft2m?file=/src/posts/PostList.js
