### ISSUE TITLE
FormdataConsumer empty value fields not inside formdata object

### ISSUE THREAD

**Issue by rkoleci** [marmelab/react-admin#5173]
Filling in a form, if I leave a field empty, "", that field (key, val) is deleted from **FormdataConsumer** data object. So I loose the empty fields basically as if they're not part of this module.

I need to be able to retrieve the empty fields as well.

"react-admin": "^3.5.0",
"react": "^16.13.1",
Chrome: v83

1. Field initially has value: **'new order no'**
![Field Initial](https://user-images.githubusercontent.com/18247975/91175804-a21c1180-e6e1-11ea-851e-88add05a6420.PNG)

2. Then I empty the field value: 
![Field Empty](https://user-images.githubusercontent.com/18247975/91175848-afd19700-e6e1-11ea-936b-02a9174f995b.PNG)

3. But it still sends the old value in the params: '**number_new_order**: new order no'
![Network params](https://user-images.githubusercontent.com/18247975/91175942-d8599100-e6e1-11ea-83bf-e0fb3f42aae6.jpg)

4. **FormDataConsumer** does not contain the field anymore when field value is empty String ""
![FormData](https://user-images.githubusercontent.com/18247975/91176722-fb387500-e6e2-11ea-8101-c06f5c685e69.jpg)

**Comment by djhi** [comment]
Please follow the issue template

**Comment by rkoleci** [comment]
> Please follow the issue template

I updated the issue. 
Any help appreciated!

**Comment by joebordes** [comment]
ping ??

**Comment by djhi** [comment]
Thanks for reporting this. In order to fix an issue we have to reproduce it, please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by joebordes** [comment]
so nice :-(

**Comment by joebordes** [comment]
thanks

**Comment by fzaninotto** [comment]
@joebordes we asked the author to provide a way to report the issue a month ago. He never came back to us. So we closed the issue. What gets you confused? 

If you have the same bug, please provide a way to reproduce it, and we'll reopen the issue.

**Comment by joebordes** [comment]
your little effort to try to reproduce it, or the lack of any feedback if you have

but you're free to manage it as you please
