### ISSUE TITLE
Ability to force re-render of <AdminUI> component from authProvider, so we can change resources and menus after user permissions change

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#5177]
**Is your feature request related to a problem? Please describe.**
I am using dynamically-defined resources as discussed at https://marmelab.com/react-admin/Admin.html#declaring-resources-at-runtime. I am using data provider to dynamically build resources, routes, and also menu (from `Layout` component) based on information returned using dataProvider custom functions.

In order to return data, a user must authenticate so appropriate data is returned based on user's permissions. If a user is not authenticated, an empty array is returned.

Unfortunately, `AdminUI` component is computed before a user is authenticated, so after users login, they have no resources to access and their menu is empty. They need to manually refresh browser to re-initialize resources and menu.

See **Additional context** section for sample code

**Describe the solution you'd like**
I would like to be able to control when `AdminUI` from authProvider.login function (after a user is authenticated) and authProvider.checkAuth (after we renew user token and also check if user permissions changed).

I think the easiest way to do so is as follows:
- I dispatch a custom event from authProvider.login and authProvider.checkAuth functions
- I subscribe to redux store inside `AdminUI` component and re-define resources, routes and menu.

To make it work, i would like `dispatch` function to be sent as a property to authProvider calls, so i can use to to dispatch events.

**Describe alternatives you've considered**
An alternative is to save `dispatch` function as a global variable or to access store directly from inside authProvider functions; however i am trying to avoid this to make transition to server-side rendering easier.

**Additional context**

Sample app flow

```js
const App = () => {
  return (
    <AdminContext
      dataProvider={dataProvider}
      authProvider={authProvider}
    >
      <AdminUI/>
    </AdminContext>
  )
}

function AdminUI() {
  const [resources, setResources] = React.useState([])
  const [routes, setRoutes] = React.useState([])
  const dataProvider = useDataProvider();

  React.useEffect(() => {
   dataProvider.getResources().then(r => setResources(r)); // custom function that queries resources; returns [] if not authenticated
   dataProvider.getRoutes().then(r => setRoutes(r)); custom function that queries routes; returns [] if not authenticated
  }, [])

  return (
    <AdminUI
      layout={Layout} // in this component, we also query API to get menus that should be available to users
      customRoutes={routes}
    >
      {resources}
    </AdminUI>
  )
}
```

**Comment by djhi** [comment]
If I understand correctly, you need to register resources specifically for each user. The current way to do it is to follow the [Restricting Access to Resources or Views](https://marmelab.com/react-admin/Authorization.html#restricting-access-to-resources-or-views) documentation.

Basically you write `<Resource>` components for every resource but only enable what you want.

**Comment by panfiva** [comment]
I think that meets our requirements
