### ISSUE TITLE
Allow to silently ignore errors when loading references

### ISSUE THREAD

**Issue by srosset81** [marmelab/react-admin#5190]
**Is your feature request related to a problem? Please describe.**
We are using react-admin for semantic data (see https://semapps.org) and, as instances (will) work in federation, it can occur that a link to a resource on another instance fails.
Currently, if a resource fails to be loaded by the `ReferenceArrayField` component, it displays an error (in the bottom notifications) and **no other linked ressources are displayed**. Thus it appears to to be very "buggy" for the user.
The code responsible for this behaviour is here:
https://github.com/marmelab/react-admin/blob/39f698c612c08281ef6312cd26ce2cc913d8de4d/packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts#L65-L73

**Describe the solution you'd like**
It would be great if we could pass an option like `ignoreErrors` to the `ReferenceArrayField` component. The references which cannot be loaded would just be silently ignored, and the references which could be loaded will be displayed normally.

**Describe alternatives you've considered**
We could copy the `ReferenceArrayField` component and make our own component but I think this is an option which could interest other react-admin users.

**Additional context**
I'm available to do a PR if this option interests the react-admin team.

**Comment by djhi** [comment]
This looks like a feature very specific to your own use case. The solution is indeed to make your own component. I'll leave the issue open so that another core team member can confirm. Ping @fzaninotto

**Comment by fzaninotto** [comment]
What do you mean by "no other linked ressources are displayed"? Would you mind appending a screenshot / screencast of the problem?

ReferenceArrayField makes one call to the dataProvider, a `getMany`. The component has no way to know which resource in the requested list is missing. From react-admin, it's an error in the `dataProvider` logic, so it seems logic to show it that way.

So I tend to agree with @djhi, this is a corner case and should not be covered by react-admin.

**Comment by srosset81** [comment]
> What do you mean by "no other linked ressources are displayed"? Would you mind appending a screenshot / screencast of the problem?

Sure ! Here it is :
https://drive.google.com/file/d/1JphuUhJPdgC-0nxGfIt7HdttRRFQaP0O/view

> ReferenceArrayField makes one call to the dataProvider, a `getMany`. The component has no way to know which resource in the requested list is missing. From react-admin, it's an error in the `dataProvider` logic, so it seems logic to show it that way.

Oh, I understand, thanks ! We use a custom data provider. By adding a try/catch inside `getMany`, we can ensure it returns only the ressources that have successfully loaded. So this solves my problem for now, even if it is not perfect.
