### ISSUE TITLE
Token localStorage null after login

### ISSUE THREAD

**Issue by emulienfou** [marmelab/react-admin#5191]
**What you were expecting:**

After login, using the sign in form, I was expecting the dataProvider is able to read the token from the localStorage.

**What happened instead:**

After login, each calls made using the dataProvider will not send the JWT token, because it seems the value return null instead of the token value stored in the localStorage.

**Steps to reproduce:**

1. Follow the steps to add authentication from React-Admin documentation page: https://marmelab.com/react-admin/Authentication.html
2. Follow the steps to add authentication from API Platform documentation page: https://api-platform.com/docs/admin/authentication-support/

**Other information:**

Related to issues:
* https://stackoverflow.com/questions/59963309/apiplatform-react-admin-token-in-localstorage-null-on-redirect-have-to-refre
* https://stackoverflow.com/questions/60701075/react-admin-localstorage-token-null

**Environment**

* React-admin version: 2.9, 3.8
* Last version that did not exhibit the issue (if applicable): ?
* React version: 16.9
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Please don't cross post troubleshooting issues here and on stackOverflow.

**Comment by emulienfou** [comment]
Hi @fzaninotto I opened this has an issue because there is more than 1 tread on stackOverflow and this seems to be a real issue on react-admin and not a simple "how-to" question.

Can I update this task with example code and you can reopen this issue?

**Comment by fzaninotto** [comment]
We've been using the localStorage as explained in the doc in many, many projects without problem. I strongly suspect the problem is on your side, or in the API Platform admin side - but not in react-admin core.

If you're able to reproduce the issue in a CodeSandbox while doing exactly what's in the documentation (which is NOT what you did in your example, see https://stackoverflow.com/a/63613707/1333479), then I'll reopen the issue.

**Comment by emulienfou** [comment]
Works perfectly when following the documentation, my bad
