### ISSUE TITLE
onSuccess Prop on Edit Component not working as intended

### ISSUE THREAD

**Issue by nik-lampe** [marmelab/react-admin#5195]
**What you were expecting:**

I followed the documentation at https://marmelab.com/react-admin/CreateEdit.html#changing-the-success-or-failure-notification-message to change the success notification In my production use case I want to reload some data after saving, but even just showing the notification does not work as intended.

The Edit Component should still work as intended, when adding a onSuccess function as prop. The form should save, and *then* the function should be called on success.

**What happened instead:**

On submitting the Form for the Edit Component  the function onSuccess get's called immediately, no saving is done before. And after the function was executed submitting the form again won't work.

**Steps to reproduce:**
https://cy6t3.sse.codesandbox.io/#/posts/13

Edit something, then click save

**Related code:**

https://codesandbox.io/s/heuristic-oskar-cy6t3?file=/src/posts/PostEdit.js

Just changed the onSuccess prop.

```
 const notify = useNotify();
  const refresh = useRefresh();

  const onSuccess = () => {
    notify("Post saved successfully"); // default message is 'ra.notification.updated'
    //refresh();
  };
  return (
    <Edit
      title={<PostTitle />}
      actions={<EditActions />}
      {...props}
      onSuccess={onSuccess}
    >
```

**Other information:**

Related to #5047 
Also tried to use useRefresh, but doesn't change anything.

**Environment**

* React-admin version:
3.8.2

**Comment by fzaninotto** [comment]
Success side effects are run immediately if the Edit view is `undoable` (which is the default). If you want to wait for the dataProvider success response, disable optimistic rendering by adding `undoable=false` to the Edit component.

This explanation is missing from the documentation, so if it solves your problem it means we should address it via a doc enhancement.

**Comment by ede-vagyok** [comment]
As you tagged me in the other issue, I checked it again and tried several things.

**Long Story Short**
It turned out that if  `undoable={false}` prop is added to the `<Edit />` solves the problem.

**Little Longer Story**
When the Edit form is undoable, the the changes will be dispatched with some delay, but the onSuccess is called with the redirection. There's no data could be passed to onSuccess yet (I don't know why).
You could check it when you pass args to onSuccess

```js
// the 'data' should contain the modified record...
const onSuccess = ({data}) => {
  console.log(data) // ... but gives an empty object because undoable=true
  refresh()
}
...
<Edit {...props} onSuccess={onSuccess} />
```

But if you set `undoable={false}`...
```js
const onSuccess = ({data}) => {
  console.log(data) // ...gives you the modified record.
  refresh()
}
...
<Edit {...props} onSuccess={onSuccess} undoable={false} />
```

That's all I could find. I hope it helps a bit.

**Comment by fzaninotto** [comment]
So indeed, it's a documentation issue. Marking it as such.

**Comment by jdemangeon** [comment]
Documentation informations added in https://github.com/marmelab/react-admin/pull/5260

**Comment by sushantmzjn** [comment]
thanks
