### ISSUE TITLE
Uniformize props used by choices inputs

### ISSUE THREAD

**Issue by djhi** [marmelab/react-admin#5199]
Some inputs accept a `disableValue` prop, some not.

Besides, this prop is not documented

**Comment by WiXSL** [comment]
`disableValue` prop has been documented for `SelectInput` and `SelectArrayInput` here 80e8f33c97bd091c99880042c5e36773de4db4ad and here 6ed5b45de81a4ec0609ccad0cd434d0a2244a98e respectively
