### ISSUE TITLE
Possible issues with ReferenceInput

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#5211]
I have the following component call:
```js
<ReferenceInput
    label='Report Tab'
    source={`${buttonSource}.callbacks.onSubmit.reportTabId`}
    reference='reportTabs'
    filterToQuery={(searchText) => ({ searchName: searchText, template: 'ReportTabTableau' })}
    perPage={5}
  >
    <AutocompleteInput
      optionText={(choice) => {
        return choice ? `${choice.reportName}: ${choice.tabName}` : undefined
      }}
      fullWidth
    />
  </ReferenceInput>
```

While everything works fine, except I see "undefined@tabs[...]" in redux tools

![image](https://user-images.githubusercontent.com/48455289/91732165-7bd8f480-eb6d-11ea-9ffb-7c5449f83fae.png)

Is that behavior normal, or there is a bug somewhere? If there is a bug, i can put together a reproducible code.

**Comment by djhi** [comment]
This looks weird indeed. Please provide the codesandbox as you suggested. Thanks!

**Comment by fzaninotto** [comment]
No news for a month, closing.
