### ISSUE TITLE
"Module not found" while following React-Admin Tutorial

### ISSUE THREAD

**Issue by koval** [marmelab/react-admin#5216]
**What you were expecting:**
Following tutorial does not result in an error.

**What happened instead:**
"Making Contact With The API Using a Data Provider" step of tutorial results in an application with `Module not found` error.

**Steps to reproduce:**

1. yarn create react-app test-admin
2. cd test-admin/
3. yarn add react-admin ra-data-json-server prop-types
4. yarn start
5. Modify App.js to contain:

```
import * as React from "react";
import { Admin } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');
const App = () => <Admin dataProvider={dataProvider} />;

export default App;
```

6. Following appears in shell and in browser:

```
Failed to compile.

./src/App.js
Module not found: Your application tried to access ra-data-json-server, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

**Environment**

Latest versions of Node.js, Yarn and React-admin (3.8.3).

**Comment by fzaninotto** [comment]
which version of `yarn` are you using?

**Comment by koval** [comment]
```
$ yarn --version
2.2.2
```

**Comment by fzaninotto** [comment]
I see no reason why this would fil. It has always worked. 

If anyone with a similar configuration want to try and reproduce, that'd help.

**Comment by koval** [comment]
Switching to `yarn 1.22.5` solved the problem.

**Comment by koval** [comment]
It may be worth mentioning in the tutorial that Yarn 1.x is only supported. Because if someone googles "Yarn", he will very likely end up looking at https://yarnpkg.com/getting-started/install page which instructs how to install Yarn 2.

And according to Yarn installation docs, you first install Yarn 1.x globally and then Yarn 2 in your project. So it's natural that Node docker images are bundled with globally installed Yarn 1.x.
