### ISSUE TITLE
Form initialValues prop as function is not working

### ISSUE THREAD

**Issue by ahshum** [marmelab/react-admin#5221]
**What you were expecting:**

As per [docs](https://marmelab.com/react-admin/CreateEdit.html#global-default-value), the value of the form `initialValues` prop is an object, or a function returning an object

**What happened instead:**

Passing function to initialValues prop does not run while passing to defaultValue works.

**Related code:**

```jsx
<SimpleForm initialValues={(values) => {
  console.log(values)
  return values
}} />
```

**Environment**

* React-admin version: 6.8.3
* React version: 16.13.1

**Comment by djhi** [comment]
Indeed. Thanks for reporting
