### ISSUE TITLE
state.admin.loader is always greater than 0

### ISSUE THREAD

**Issue by ajay-dev-j** [marmelab/react-admin#5232]
**Note**: I don't have the right to create a StackOverflow question. Kindly check out this here.

**What you were expecting:**
Once the app is loaded, the state.admin.loader should be 0.

**What happened instead:**
The state.admin.loader is always 6 in my case

**Steps to reproduce:**

- Create the app as [custom](https://marmelab.com/react-admin/CustomApp.html)

- The `<LoaderIndicator />` is always loading in the custom MyAppBar.

**Environment**

* React-admin version: 3.7.1
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.9.0
* Browser: chrome
* Stack trace (in case of a JS error): N/A

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by ajay-dev-j** [comment]
I will close this. This is my bad the redux-persist persists the admin reducer which causes the problem.
