### ISSUE TITLE
ra-input-rich-text font text italic.

### ISSUE THREAD

**Issue by VanTy207** [marmelab/react-admin#5233]
Hi,
I have an italic font problem and I don't like it, but I don't know how to leave it out of the way.

![Annotation 2020-09-07 132419](https://user-images.githubusercontent.com/35839235/92355057-b282b200-f10d-11ea-9c4b-34e17732a620.gif)

Thank you.

**Environment**

* React-admin version: 3.7.1
* React version: 16.13.1
* Browser: chrome

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by VanTy207** [comment]
Thank you,
I have fixed the above error.
