### ISSUE TITLE
Make SimpleList compatible with rowStyle property.

### ISSUE THREAD

**Issue by ValentinnDimitroff** [marmelab/react-admin#5253]
**Is your feature request related to a problem? Please describe.**
Using the `rowStyle `property on the `Datagrid `component is great. But when you switch to the responsive `SimpleList `component you suddenly loose the ability to style each row based on the `record `values. 

The way SimpleList is written right now allows absolutely no way to plug in record-based conditional styling.

**Describe the solution you'd like**
Adding the prop `rowStyle `to the `SimpleList `component which could be applied to the iterating `ListItem` to allow full styling through nested selectors.

**Describe alternatives you've considered**

Here is a PR #5252

**Comment by jdemangeon** [comment]
Hello @ValentinnDimitroff  and thanks for you PR!

Can you rebase your PR on the `next` branch since it's a new feature please ?
Moreover some tests are not passing, can you fix them ?

**Comment by ValentinnDimitroff** [comment]
Hey @jdemangeon - sure, I saw the tests but didn't have the time at the moment. I will fix them and rebase to the `next ` branch :)

**Comment by WiXSL** [comment]
This issue can be closed
