### ISSUE TITLE
Documentation: The DataProvider action "createMany" isn't documented anywhere

### ISSUE THREAD

**Issue by benwinding** [marmelab/react-admin#5256]
**Context**
I'm trying to fix an issue in this library https://github.com/benwinding/react-admin-import-csv/issues/21 and was encouraged to use the `createMany` method on the DataProvider.

**Problem**
The `createMany` doesn't seem to be documented anywhere:
- It doesn't seem to be in official documentation `@3.8.4`
- It's not in the typescript declarations in `ra-core@3.8.4`
- [This comment](https://github.com/benwinding/react-admin-import-csv/issues/21#issue-684577626) mentions it, as well as [this StackOverflow answer](https://stackoverflow.com/a/61702060/2419584)

![image](https://user-images.githubusercontent.com/11782590/93167034-e63d8780-f75e-11ea-8e34-74c2fb94c131.png)

![image](https://user-images.githubusercontent.com/11782590/93167332-94493180-f75f-11ea-9d66-776370420535.png)

Is this a new action? Or is it optional?

**Environment**

* React-admin version: 3.8.4
* Last version that did not exhibit the issue (if applicable): -
* React version: 16.8.6
* Browser: Chrome
* Stack trace (in case of a JS error): -

**Comment by djhi** [comment]
Indeed, it does not exist in the default dataproviders. The exact suggestion was:
> May I suggest you call a **new** verb on the dataProvider (something like createMany)

You can add your own verbs to the dataproviders. See https://marmelab.com/react-admin/Actions.html#usemutation-hook

**Comment by benwinding** [comment]
Okay, I just saw it mentioned in a few places, and thought it might be an undocumented feature. 

Is there any way to check if a DataProvider action exists?

It seems to be fairly difficult as it's wrapped in a `ProxyObject` when accessing with `useDataProvider`. 

https://github.com/marmelab/react-admin/blob/d1aef1d52c4cef157d9c17305192f591fd6ff53a/packages/ra-core/src/dataProvider/useDataProvider.ts#L149-L153

The only way I've found is to call the method and parse the error to check for `Unknown dataProvider function`... but this seems dirty

**Comment by fzaninotto** [comment]
Indeed, there is no way to check the existence of a dataProvider method because of Proxy objects. We're adding TypeScript types to encourage doing that type of check at compile time, but that implies that you use these type sin your code, too.

**Comment by benwinding** [comment]
> We're adding TypeScript types to encourage doing that type of check at compile time, but that implies that you use these type sin your code, too.

Yes, my library [react-admin-import-csv](https://github.com/benwinding/react-admin-import-csv) is written in Typescript so I'm using types where I can. 

I want to call a custom DataProvider verb `createMany` _if it exists_ otherwise fallback to the singular `create` method. Is there a clean way to do this?

**Comment by fzaninotto** [comment]
Yep: call createMany in a try/catch, and fallback to create in the catch block.
