### ISSUE TITLE
List blinks (not being cached?) while sorting or reloading

### ISSUE THREAD

**Issue by IAmVisco** [marmelab/react-admin#5262]
While migrating from v2 to v3 I noticed that List filters are now blinking while sorting or reloading which wasn't a thing before. I checked with the demo site and it works just fine there. I tested in simple lists but can't seem to track down the issue. I had legacy custom dataProvider from v2 and tried rewriting few methods to new v3 dataProvider to see if it fixes the issue but it did not. 
Here's GIF representing what I have.
![image](https://i.imgur.com/cN5M3rC.gif)
And GIF from the demo site for comparison.
![image](https://i.imgur.com/bDnuDXI.gif)

**Related code:**

```js
// data provider
getList: (resource, params) => {
    const { page, perPage } = params.pagination;
    const { field, order } = params.sort;
    const query = {
      ...params.filter,
      sort: field,
      order,
      offset: (page - 1) * perPage,
      limit: perPage,
    };

    const url = `${apiUrl}/${resource}?${stringify(query)}`;
    return httpClient(url).then(({ json }) => {
        return { data: json.resource, total: json.total };
      },
    );
  },
// list
<List
  title="Managers"
  filters={<ManagersFilter />}
  exporter={false}
  bulkActionButtons={false}
  sort={{ field: 'id', order: 'DESC' }}
  {...props}
>
  <Datagrid rowClick="edit">
    <TextField label="ID" source="id" />
    <TextField label="Profile name" source="username" sortable={false} />
    <TextField label="Name" source="name" sortable={false} />
    <TextField label="Surname" source="surname" sortable={false} />
    <TextField label="Email" source="email" sortable={false} />
    <EditButton />
    <DeleteButton undoable={false} />
  </Datagrid>
</List>
```

**Environment**

* React-admin version: 3.8.4
* Last version that did not exhibit the issue (if applicable): 2.9.8
* React version: 16.13.1
* Browser: Chrome 85, Edge 85

**Comment by djhi** [comment]
Thanks for reporting this. I cannot reproduce it on the demo or the simple example. Please provide a sample application which show the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)

**Comment by IAmVisco** [comment]
I understand that it's hard to track down but just like in the demo, I can't seem to reproduce it in the sandbox. Oh well. I had a faint hope that someone else encountered this before. I will try commenting out stuff and play around more, will report if I find anything. Thanks for the reply.

**Comment by IAmVisco** [comment]
There was a custom wrapper with permission checks around `<Resource />` which was returning `null` at times. I rewrote it to properly check permissions and now it's working fine. It was my app issue after all, not the library. Sorry for taking your time.
