### ISSUE TITLE
AppBar doesn't use resource's label

### ISSUE THREAD

**Issue by farooqaaa** [marmelab/react-admin#5266]
**What you were expecting:**
Show the resource label on the AppBar

**What happened instead:**
It's showing the default label instead.

**Steps to reproduce:**

1. Add a label to a resource. Say the resource is `<Resource name="users" options={{ label: 'New Label' }}/>`.
2. The title that appears on the appbar is still Users and not New Label

**Environment**

* React-admin version: 3.8.4
* Browser: Chrome

**Comment by djhi** [comment]
The `label` option won't change the page title. It's a shortcut to set the menu label for this resource.
See https://marmelab.com/react-admin/Resource.html#options

To change the page title, use the `title` prop on the `List`, `Edit`, `Create` or `Show` components.

**Comment by farooqaaa** [comment]
Thanks!
