### ISSUE TITLE
LoadingIndicator does not get class overrides

### ISSUE THREAD

**Issue by danejorgensen** [marmelab/react-admin#5268]
**What you were expecting:**
Can apply custom theme to LoadingIndicator component

**What happened instead:**
LoadingIndicator is default color.   Does not pass styles to RefreshIconButton

It does pass the styles to the CircularProgress component while isLoading is true.

**Steps to reproduce:**
```
import { LoadingIndicator } from 'react-admin';

theme => ({
  indicator: {
    color: '#F00'
  }
})

<LoadingIndicator className={classes.indicator} />
```

**Environment**

* React-admin version: 3.8.4
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting. Indeed only the `CircularProgress` is passed a `className`.

**Comment by Luwangel** [comment]
This feature will be part of the next release. You'll have to overide the classes passed to the `LoadingIndicator` using the key `loadedIcon`.

**Comment by matboud** [comment]
just wrapp it inside a div and pass the styles you want to that div, or inside the LoadingIndicator.d.ts file add this line "const style: PropTypes.Requireable<object>; " in the namespace prototype and you u ll be fine to go
