### ISSUE TITLE
Provide ability to hook into actual data returned by a reference field

### ISSUE THREAD

**Issue by wattry** [marmelab/react-admin#5269]
**Is your feature request related to a problem? Please describe.**
When using a referenceInput we'd like to be able to hook into the data provided to set information else where in the page. We have tried using useQueryWithStore however, a second request is made which is wasteful.

**Describe the solution you'd like**
We'd like to be able to hook into the redux store easily or have access to the data received from a reference input or field.

**Comment by djhi** [comment]
If I understand correctly, you'd like that we provide some ready to use redux selectors ?

**Comment by wattry** [comment]
That would be great, or have some docs on how to access the redux state based on what RA is doing under the hood.

**Comment by djhi** [comment]
> I believe we can use the useSelector hook to get data from the store.

Yes

> I'm not sure if this project would be open to adding a little context to react redux useSelector?

Not sure about what you mean by that. Can you elaborate?

**Comment by fzaninotto** [comment]
If you imply adding a description of the redux store and explaining how to get data from there, yes, that would be a great addition to the documentation!

**Comment by wattry** [comment]
@fzaninotto summed it up. Thanks! I don't mind doing the PR myself when I have sometime if you guys accept external contributions?

**Comment by wattry** [comment]
Hey there, @djhi I have a cycle to reflect on this. There is a brief example on how to use the redux store [on the custom menu docs](https://marmelab.com/react-admin/Admin.html#menu). I was thinking the appropriate location for the docs on the redux store should be either it's own new menu item or inside querying the api? Any thoughts?

**Comment by fzaninotto** [comment]
I thin ka new menu item is the best location

**Comment by WiXSL** [comment]
In version 4 of react-admin in `next` branch, Redux has been removed and the use of hooks related to global state has been documented there.

So I'm closing this enhancement request.
