### ISSUE TITLE
Change list params of a resource, another ones change too

### ISSUE THREAD

**Issue by tunglt1810** [marmelab/react-admin#5280]
Hi guys. Sometime my app have an issue when i dispatch changeListParams action to change params of a resource, after that all another resources change too. This is redux log

![Screenshot from 2020-09-21 09-25-44](https://user-images.githubusercontent.com/19906349/93731287-921b2300-fbf6-11ea-976a-cd0f1d520af6.png)
![Screenshot from 2020-09-21 09-26-00](https://user-images.githubusercontent.com/19906349/93731292-96dfd700-fbf6-11ea-8ab1-0b86091ac393.png)

**Environment**

* React-admin version: 3.6.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Chrome 85
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
no news for some time, closing.
