### ISSUE TITLE
Inputs throw error when passing react-final-form props

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5288]
Some of react-final-form [`FieldProps`](https://final-form.org/docs/react-final-form/types/FieldProps) props are not sanitized in react-admin inputs.
For example:
```jsx
<BooleanInput
     allowEmpty
     label="Can edit?"
     source="canEdit"
     beforeSubmit={() => false} // <-- Throws error
/>
```
* React-admin version: 3.8.5
* React version: 16.13.1
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting
