### ISSUE TITLE
Getting error after upgrading from 3.4 to 3.8.4 

### ISSUE THREAD

**Issue by manohar719** [marmelab/react-admin#5292]
**What happened instead:**
Getting error when upgrade to 3.8.4
./node_modules/ra-ui-materialui/esm/field/ArrayField.js
Attempted import error: 'ListContextProvider' is not exported from 'ra-core'.

**Steps to reproduce:**
upgrade from 3.4 to 3.8.4 react-admin

**Other information:**

**Environment**

* React-admin version: 3.8.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: chrome

**Comment by toti1212** [comment]
I had the same errors too.
In order to solve it I did:
- npm update ra-core --depth 2 (you can see it if you run npm audit)
- update typescript

**Comment by manohar719** [comment]
> I had the same errors too.
> In order to solve it I did:
> 
> * `npm update ra-core --depth 2` (you can see it if you run `npm audit`)
> * update `typescript`

Thank you so much, it resolved the issue.

**Comment by manohar719** [comment]
@toti1212 

Translate is not working, can you help me

<img width="1440" alt="Screenshot 2020-09-24 at 10 54 32 AM" src="https://user-images.githubusercontent.com/8014963/94104392-8cbb1400-fe54-11ea-8413-21d6e12b5f5c.png">

**Comment by toti1212** [comment]
Sorry for my late reply @manohar719 . I had those same errors but couldn't find a solution. I tried upgrading from 3.0x to 3.8.5 but after manually upgrading some libraries, typing errors etc, I stayed there, in translation.

I finally postponed the update because I invested a lot of hours but didn't find a clear solution or guide to solve it.

**Comment by QuentinPetel** [comment]
@manohar719  Adding manually `ra-core` to package.json dependencies solved the issue for me, after upgrading react-admin from 3.8.0 to 3.8.5.

**Comment by toti1212** [comment]
Good to know, thanks @QuentinPetel . I will try it and update this issue if it works fine
