### ISSUE TITLE
'useListContext' is not exported from 'react-admin'

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#5293]
I have the latest version of react-admin (3.8.5) and I want to build a custom Filter.

When I copy exactly the example from the documentation, I get this error:

> Attempted import error: 'useListContext' is not exported from 'react-admin'.

I need urgent help, thank you very much!

**Comment by djhi** [comment]
Import it from `ra-core`. We're working on re-exporting everyting from `react-admin`
