### ISSUE TITLE
Show and Edit pages render incorrect data if you go from the List page which was rendered with 'optimistic rendering' and still loading.

### ISSUE THREAD

**Issue by MikeyKubarych** [marmelab/react-admin#5295]
**Steps to reproduce:**

1. Go to Show page
2.  On the Show page make a click on the 'List' button which returns you on the List page which immediately renders a list of records with help of 'optimistic rendering' and in the while sends an HTTP request to get data from the back-end.
3. Click on 'Show' button before the list view has completed loading
4. The Show view starts with data got by getOne() and then a few seconds later when getList() finishes loading it re-render the page with the record from the List page

**Environment**

* React-admin version: 3.8.5
* React version: 16.13.1
* Browser: All

**Comment by djhi** [comment]
Do you mean you have different shape for a resource depending on whether it has been fetched for a list or a edit/show view? If yes, it is a current limitation of react-admin. Resources **must** always have the same shape.

**Comment by fzaninotto** [comment]
No news for some time, closing.
