### ISSUE TITLE
'useGetIdentity' is not exported from 'ra-core'

### ISSUE THREAD

**Issue by datakurre** [marmelab/react-admin#5296]
TypeScript issues breaking code with 3.9.0-beta.1 were requested: https://github.com/marmelab/react-admin/issues/4505#issuecomment-697666524

After upgrading from 3.8.x to 3.9.0-beta.1 and removing local types/react-admin stub, I got

```
./node_modules/ra-ui-materialui/esm/layout/UserMenu.js
Attempted import error: 'useGetIdentity' is not exported from 'ra-core'.
```

**Comment by djhi** [comment]
Can you please check which version of `ra-core` has been installed because `useGetIdentity` is definitely exported: https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/auth/index.ts#L25

**Comment by datakurre** [comment]
@djhi Thanks. That was it (ra-core 3.8.5). I was too excited only upgrade react-admin and another pin kept that at the old version. :see_no_evil:
