### ISSUE TITLE
Unclickable ChipField is still clickable

### ISSUE THREAD

**Issue by Xeizzeth** [marmelab/react-admin#5297]
**What you were expecting:**
Clicking on the ChipField won't do anything.

**What happened instead:**
It is not highlighted anymore, yet it is still clickable and able to send rest request. 

**Steps to reproduce:**
Create ArrayField with SingleFieldList with the ChipField inside with the prop "clickable" assigned to false.

**Related code:**
json_entry:
```
[
  {
    "id": 1,
    "username": "Bret",
    "some_array_with_some_data": [
      { "name": "one" },
      { "name": "two"},
      { "name": "three"}
    ]
  }
]
```

The RA component(s):
```
export const UserList = props => (
  <List {...props}>
    <Datagrid rowClick="edit">
      <TextField source="id" />
      <ArrayField source="some_array_with_some_data">
        <SingleFieldList>
          <ChipField source="name" size="small" clickable={false} />
        </SingleFieldList>
      </ArrayField>
    </Datagrid>
  </List>
);
```

**Environment**

* React-admin version: 3.8.6
* React version: 16.13.1
* Browser: Chrome

**Comment by MGxpwr** [comment]
According to the docs of react admin https://marmelab.com/react-admin/List.html#the-singlefieldlist-component
If you add linkType={false} prop to your SingleFieldList, it will remove the click listeners on the chipfields.

**Comment by fzaninotto** [comment]
indeed, the `clickable` prop must be set in the `SingleFieldList` component, not in the `ChipField` component.
