### ISSUE TITLE
TextInput using FormDataConsumer 

### ISSUE THREAD

**Issue by sivaavkd** [marmelab/react-admin#5301]
**What you were expecting:**
I used the FormDataConsumer example mentioned in the documentation: https://marmelab.com/react-admin/Inputs.html#hiding-inputs-based-on-other-inputs
I have made the TextInput as multiline resettable fullWidth.  I expected the textbox to span the full width of the screen.

**What happened instead:**

Textbox didn't take fullWidth prop into consideration.
Note: If I remove {...rest} from TextInput, fullWidth is working.

**Steps to reproduce:**

Create a TextInput with fullWidth using FormDataConsumer 

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.7.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by wattry** [comment]
@sivaavkd  what is likely happening is the fullWidth property is being overridden by the ...rest property being spread. You need to spread the rest property and then provide the property you want to modify.

```
  <TextInput fullWidth {...rest> />

  <TextInput {...rest} fullWidth />
```

In the [common property docs](https://marmelab.com/react-admin/Inputs.html) you'll see that full width is set to false by default.
