### ISSUE TITLE
Add Phone number field

### ISSUE THREAD

**Issue by nicodmf** [marmelab/react-admin#5303]
**Is your feature request related to a problem? Please describe.**
For admin used by phone agents, or for admin on cellphone it is possible to use admin to directly call a person by phone. For the moment no field permit directly to 

**Describe the solution you'd like**
Dispose a phoneField in react admin library

**Describe alternatives you've considered**
Permit to format a record value with a function provided by a field property

Possible implementation : https://gist.github.com/nicodmf/f3fb75c56f370db8e7d554668a2f9e4b

I can make a a PR if you agree.

**Comment by djhi** [comment]
We probably won't include this in the core as we would have to maintain it. However, feel free to create a package for it and include it in our ecosystem documentation!

**Comment by nicodmf** [comment]
@djhi Just for a field which include no logic ?
