### ISSUE TITLE
Allow customization of "Element deleted" notification when using <DeleteButton>

### ISSUE THREAD

**Issue by gavacho** [marmelab/react-admin#5309]
**Is your feature request related to a problem? Please describe.**
When the user clicks a `<DeleteButton>` in an Edit toolbar, react-admin displays "Element deleted". I would like to customize that message for different resources (e.g. "Post deleted" and "Comment deleted").

**Describe the solution you'd like**
I would like `DeleteButton` to behave like `SaveButton` and accept `onSuccess` and `onFailure` properties.

**Describe alternatives you've considered**
The "Element deleted" message can be customized using internationalization but I think that's a global change and wouldn't let me customize the message by resource.

**Comment by fzaninotto** [comment]
Nice idea. We could also pass the `resource` in the translate parameters, letting users do the customization. Both are valid enhancements.

**Comment by wattry** [comment]
> Nice idea. We could also pass the `resource` in the translate parameters, letting users do the customization. Both are valid enhancements.  

We discussed this but someone mentioned passing the resource might not always grammatical sense. We tried the translation but realized that we could not pass the messageArgs through.

**Comment by fzaninotto** [comment]
Fixed by #5310
