### ISSUE TITLE
Support FilterListItem `selected` for nested filters

### ISSUE THREAD

**Issue by bharatkashyap** [marmelab/react-admin#5314]
**Is your feature request related to a problem? Please describe.**
The filterValues I am using for our project has objects as keys. For instance, `{ school: { location: .. } `. As a result, the isSelected function inside the FilterListItem which uses simple equality ( == ) with the `value` prop of the FilterListItem fails.

**Describe the solution you'd like**
Add a check to see if values[key] is an object, and then add an object equality check.

**Describe alternatives you've considered**

**Additional context**

**Comment by fzaninotto** [comment]
Hi, and thanks for your request.

This is not something we'll support in react-admin. The use case is rare IMHO, and you can overcome the problem by serializing the value in your dataProvider.
