### ISSUE TITLE
TypeScript error - when start the demo 

### ISSUE THREAD

**Issue by Selvi-winvest** [marmelab/react-admin#5316]
Am trying to run the demo in example.. but below error am getting

SyntaxError: F:\react-admin\examples\demo\src\products\GridList.tsx: Identifier 'width' has already been declared (51:4)

  49 |
  50 | const LoadingGridList: FC<GridProps & { nbItems?: number }> = ({
> 51 |     width ,
     |     ^
  52 |     nbItems = 20,
  53 | }) => {
  54 |     const classes = useStyles();
Compiling...
Compiling...
Files successfully emitted, waiting for typecheck results...
Files successfully emitted, waiting for typecheck results...
Failed to compile.

TypeScript error in F:/react-admin/examples/demo/src/products/GridList.tsx(58,35):
Argument of type 'string | number | undefined' is not assignable to parameter of type '"xs" | "sm" | "md" | "lg" | "xl"'.
  Type 'undefined' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl"'.  TS2345

    56 |         <MuiGridList
    57 |             cellHeight={180}
  > 58 |             cols={getColsForWidth(width)}
       |                                   ^

**Comment by djhi** [comment]
I don't have any errors when running the demo from the `master` branch. Can you pull the latest changes and retry?

**Comment by yograf** [comment]
Same here.

**Comment by fzaninotto** [comment]
What is the version of `react-admin`, `ra-ui-material-ui`, and `@material-ui/core` that you're using?

**Comment by CaoDuyThanh** [comment]
hi @Selvi-winvest, I got the similar problem, try to use @types/react version 16.9.0, I found that the later version had additional field `width` in interface TableHTMLAttributes<T> in module `@types/react/index.d.ts` and it conflicts with WithWidth. Hope this help.

**Comment by fzaninotto** [comment]
I'm not sure I understand: the bug occurs with a version of react types more recent than 16.9.0? Because I'm using `"@types/react-dom@^16.9.4"` and I don't see the problem.

**Comment by dream811** [comment]
![image](https://user-images.githubusercontent.com/45660446/95556744-5a113e00-0a46-11eb-9ca4-9f0b5b918817.png)
I met same error.

**Comment by fzaninotto** [comment]
I still can't reproduce the error. Here is what I did:

```sh
git checkout git@github.com:marmelab/react-admin.git
cd react-admin
make install
make build
make run-demo
```

I'm using Node v12.16.1

Please give a way to reproduce the issue or we'll have to close it.

**Comment by yograf** [comment]
OK, it's working fine now. thx @fzaninotto.

**Comment by Amitkad** [comment]
I've also faced the issue, when trying the following:
git checkout git@github.com:marmelab/react-admin.git
cd react-admin
cd examples
cd demo
npm start

is something wrong with the above ?

**Comment by fzaninotto** [comment]
@Amitkad Please follow the steps explained in my comment above instead:

```
git checkout git@github.com:marmelab/react-admin.git
cd react-admin
make install
make build
make run-demo
```
