### ISSUE TITLE
Cannot build with snowpack/rollup/pikapack

### ISSUE THREAD

**Issue by MarkLyck** [marmelab/react-admin#5321]
When trying to build an application with react-admin, I get thousands of warnings about The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten

for example: 
```
[snowpack] /Users/mark/ypm/xxxx/cloud-one2/node_modules/ra-core/esm/reducer/admin/resource/list/selectedIds.js:1:30 The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
```

This happens for thousands of modules in all of these react-admin packages:

- ra-core
- ra-ui-materialui
- @react-admin
- ra-input-rich-text
- ra-i18n-polyglot

I also saw this error in about 10 modules in `react-mapbox-gl`, but the 10 modules isn't what's completely crashing my computer, it's the 1000s of warnings from react-admin modules.

This happens when attempting to build react-admin with `snowpack`, `rollup` or `pikapack` which are not so obscure they should be ignored imho.

Please fix these 🙏

**What you were expecting:**
Build to work

**What happened instead:**
JavaScript heap out of memory error

**Steps to reproduce:**
- setup a fresh snowpack build. (build works fine)
- Add a simple react-admin Component (build fails)

* React-admin version: "^3.8.5",
* React version:"^16.13.1",

**Comment by fzaninotto** [comment]
thanks for your report. 

The core team uses react-admin with webpack on all our projects. Until we have to use another bundler, we'll spend no time on this issue.

But the beauty of open-source is that you can fork the project, tweak the babel transpilation options (I believe they are the source of the problem) and fix the bug yourself. And if you feel like sharing your fix with the rest of the react-admin community, please open a PR in this repository.

**Comment by fzaninotto** [comment]
This is an incompatibility between the TypeScript compiler (tsc) and rollup. See https://github.com/rollup/rollup/issues/794 for details. The solution is to change your rollup configuration to silence these warnings (see https://stackoverflow.com/a/43556986/1333479 for details).

So I'm closing this issue as it's outside of the realm of react-admin.
