### ISSUE TITLE
<DateInput> - Calendar popup not working on Safari

### ISSUE THREAD

**Issue by timofeyp** [marmelab/react-admin#5324]
As was described in previous issue #2296, date input not works in Safari. Issue was closed by common Matherial UI problem at those moment. But in last Matherial UI version it works: [demo](https://material-ui.com/ru/components/pickers/). So, could you update Matherial-ui DateInput in future react-admin releases?

> **What you were expecting:**
> _DateInput_ not working as expected. There are couple of issues in different browsers.
> 
> * Calendar pop-up should appear/displayed on Safari
> * When I use keyboard and try to deleted _yyyy_ in _dd/mm/yyyy_, it should only deleted _year_.
> 
> **What happened instead:**
> 
> * There is no Calendar pop-up on Safari
> * When I use keyboard and try to deleted _yyyy_ in _dd/mm/yyyy_, it reset's entire date input on Chrome and Firefox.
> 
> **Related code:**
> 
> ```
> <DateInput label="Birth Date" source="birth_date" />
> ```
> 
> **Screenshot:**
> ![error](https://user-images.githubusercontent.com/762942/45272827-295c2480-b4cd-11e8-84df-6620bc2753c9.png)
> 
> **Environment**
> 
> * react-admin version: 2.3.0
> * Safari: 11.1.2
> * Chrome: 69.0

**Comment by fzaninotto** [comment]
The material-ui demo you're linking doesn't use the native date picker. They use a software date picker from another package, '@material-ui/pickers'.

React-admin doesn't use these software pickers in the core, but a third-party package for react-admin does: [https://github.com/vascofg/react-admin-date-inputs](vascofg/react-admin-date-inputs). I invite you to use it.
