### ISSUE TITLE
Add transform capabilities to Field Components

### ISSUE THREAD

**Issue by GimpMaster** [marmelab/react-admin#5331]
**Is your feature request related to a problem? Please describe.**
Right now there is the capability to transform the values when using an Input Component but I didn't see a way to do the same when using a Field Component. Obviously you would need to only implement the format prop since Field is a read-only used in lists typically

**Describe the solution you'd like**
https://marmelab.com/react-admin/Inputs.html#transforming-input-value-tofrom-record 

Shows how to use the format prop. It would be good to have this same prop on Field Components

**Describe alternatives you've considered**
I'm assuming I would need to make my own wrapped component for each Field that I want to manipulate data before showing.

**Additional context**

**Comment by fzaninotto** [comment]
You can use the [`<FunctionField>`](https://marmelab.com/react-admin/Fields.html#functionfield) component for that.

If that doesn't match your need, yes, you'll need to make your own wrapped component for each Field that tou want to manipulate data before showing. 

We don't want to replace React one-liners with react-admin features: that would make the framework harder to learn, use, and maintain. Keeping its API small is what made it so powerful!

**Comment by GimpMaster** [comment]
Thanks, I'll give that a try.
