### ISSUE TITLE
Tab component Type Definition is incorrect

### ISSUE THREAD

**Issue by martdavidson** [marmelab/react-admin#5334]
**What you were expecting:**
Should be able to use `<Tab label="summary">` as shown in the documentation.

**What happened instead:**
Looks like all the possible Tab props are required:

```
TS2740: Type '{ children: Element[]; label: string; }' is missing the following properties from type '{ [x: string]: any; basePath: any; children: any; contentClassName: any; context: any; className: any; icon: any; label: any; record: any; resource: any; value: any; }': basePath, contentClassName, context, className, and 4 more.
```

Also, it would be nice if that list of props was available as an exported TabProp interface.

**Steps to reproduce:**
Try creating the TabbedShowLayout example from the docs, should be enough to show the issue.

* React-admin version: 3.9.0-beta.3
* React version: 16.13.1

**Comment by fzaninotto** [comment]
Thanks for the report. We haven't converted Tab to TypeScript yet, so TypeScript falls back to inference from PropTypes, which is wrong in that case.
