### ISSUE TITLE
Error component type definition conflicts with propTypes

### ISSUE THREAD

**Issue by martdavidson** [marmelab/react-admin#5336]
**What you were expecting:**
To be able to use `<Error error={'Oh no'} />` (or even just `<Error />`, as that was what we had in our codebase previously)

**What happened instead:**
`ErrorProps` allows `error: any`, but the `propTypes` has `error: PropTypes.Validator<object>;`, so I have to do `<Error error={{}} />` to compile.

* React-admin version: 3.9.0-beta.3
* React version: 10.13.1

**Comment by fzaninotto** [comment]
Reproduced, thanks for the report.
