### ISSUE TITLE
Router is missing compilation error 

### ISSUE THREAD

**Issue by asok-mirror** [marmelab/react-admin#5348]
**What you were expecting:**
There should not be a compile error 

**What happened instead:**
./node_modules/ra-core/esm/core/RoutesWithLayout.js
Attempted import error: 'Redirect' is not exported from 'react-router-dom'.

./node_modules/ra-core/esm/core/RoutesWithLayout.js
Attempted import error: 'Redirect' is not exported from 'react-router-dom'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-material-dashboard@1.0.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-material-dashboard@1.0.0 build script.

**Steps to reproduce:**
1) Added the Posts Page as per the documentation. 
2)Run npm start 
**Related code:**
Using version v6 of react-router.
is it related to this ?
https://github.com/ReactTraining/react-router/issues/7185

my router versions:
"react-router": "^6.0.0-beta.0",
 "react-router-dom": "^6.0.0-beta.0",

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.9.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
React-admin isn't compatible with react-router-dom 6.0. We'll see about that when it's released. 

In the meantime, you may want to report the issue to the react-router team - this is not a documented breakage of their major release, and [their doc doesn't show that from is required on the Redirect component](https://reactrouter.com/web/api/Redirect), so it's a bug on their side.
