### ISSUE TITLE
Refresh page with querystrings breaks one of my reducers causing infinite loop

### ISSUE THREAD

**Issue by otaviobps** [marmelab/react-admin#5350]
I'm using React Admin and it's working fine, however there's a strange behavior whenever I try to refresh a page with querystrings, like `orders?displayedFilters={"name"%3Atrue}&filter={}&order=DESC&page=1&perPage=100&sort=createdAt`

I have a reducer that runs on every page render to check if the user info is present in my redux store:

```
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { getUserInfo } from '../actions/userActions';
import { LoaderLottie } from '../components/Loader';

function useCheckUserInfo() {
    const dispatch = useDispatch();
    const userState = useSelector((state) => state.user);

    useEffect(() => {
        // check if global state has user info
        if (userState.data === null) {
            dispatch(getUserInfo());
        }
        //eslint-disable-next-line
    }, []);

    if (userState.loading) {
        return <LoaderLottie />;
    }
}

export default useCheckUserInfo;
```

This is on top of the React Admin component, so in every page change this hook is called. If the user info is already in my state, it doesn't dispatch any action.

If I'm in React Admin, which for me is under `/admin/`, my hook works fine, even if I refresh the page. The problem is when the URL has querystrings: `http://localhost:3000/admin/orders?displayedFilters=%7B%22name%22%3Atrue%7D&filter=%7B%7D&order=DESC&page=1&perPage=100&sort=createdAt`. If I try to refresh the page, an infinite loop happens in my reducer:

> Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.
```
   5 | try {
   6 |     dispatch({ type: types.START_GET_USER_INFO });
   7 |     const response = await api.get('/private/info/userinfo');
>  8 |     dispatch({ type: types.FINISH_GET_USER_INFO, value: response.data });
     | ^   9 | } catch (e) {
  10 |     dispatch({ type: types.ERROR_GET_USER_INFO });
  11 | }
```

The `dispatch(getUserInfo())` calls the api fetching the user info:

```
import { types } from '../reducers/types';
import api from '../services/api';

export const getUserInfo = () => async (dispatch) => {
    try {
        dispatch({ type: types.START_GET_USER_INFO });
        const response = await api.get('/private/info/userinfo');
        dispatch({ type: types.FINISH_GET_USER_INFO, value: response.data });
    } catch (e) {
        dispatch({ type: types.ERROR_GET_USER_INFO });
    }
};
```

I'm using `Redux Thunk` but I also installed `Redux Saga` for React Admin.

It's strange because everything works fine, except when I refresh a page with querystrings, and only within the `React Admin` element tree.

I have other pages that also uses querystrings, like `http://localhost:3000/sendmoney?from=EUR&to=ARS&amount=50`, and I can refresh it a ton of times and I won't enter in an infinite loop.

It's strange because my action finish correctly and then throw an error:

![image](https://user-images.githubusercontent.com/28715087/95121991-3b4d3780-0726-11eb-8f0c-d75fe6827e1c.png)

I'm 100% sure this error is inside React-Admin, because my application is using this hook in production for months with no errors, and then when I decided to install React-Admin I'm seeing this behavior only inside the `Admin` tree.

Is it possible to disable the querystrings?

**Comment by djhi** [comment]
No, the querystring is used in many places and it's not not possible to disable it. However, we use react-admin in production for multiple projects which all requires user authentication checks without any issues.

It's hard to help you without a way to reproduce your issue so please follow the issue template

**Comment by fzaninotto** [comment]
No news for some time, closing.
