### ISSUE TITLE
Allow MenuItemLink to have a customizable and optional tooltip

### ISSUE THREAD

**Issue by gstn-caruso** [marmelab/react-admin#5359]
**Problem description**
I added a few MenuItemLinks in my Customized Appbar but then I wanted to customized the tooltips (I don't want them or I want to change the content), it turns that the configuration for that component was hardcoded to display the same than the primary title and to be displayed on the right side.

**The solution I'd like**
I would like to be able to pass the props to the MenuItemLink with the tooltip options, and if I don't pass any, I don't want the tooltip to be rendered.

**Alternatives I've considered**
I've considered using another component apart from the MenuItemLink, but this component is configured out of the box to keep track of the current route.

Here is a [PR](https://github.com/marmelab/react-admin/pull/5360)

**Comment by fzaninotto** [comment]
Fixed by #5714
