### ISSUE TITLE
AutocompleteInput send wrong query

### ISSUE THREAD

**Issue by Selen34** [marmelab/react-admin#5362]
there is resourse `data-systems` with table

id | key | name |
--- | --- | --- |
1 | a_key | a_name

and resource `units` with table

id | key | dataSystemId | 
--- | --- | --- |
3 | a_unit_key | 1

in react-admin (resource edit `units`) I use:

```
<ReferenceInput reference={'data-systems'} source={'dataSystemId'}>
     <AutocompleteInput optionText={"key"} optionValue={"id"}/>
</ReferenceInput>
```

And I expect that react-admin send query like `GET localhost/data-systems?filter={key: <VALUE_FROM_INPUT>}`

 BUT! really query is `filter={q: <VALUE_FROM_INPUT>}` 

Is there a way to send right fieldname?

**Comment by fzaninotto** [comment]
> Is there a way to send right fieldname?

Yep: [read the docs](https://marmelab.com/react-admin/Inputs.html#referenceinput)!
