### ISSUE TITLE
Upgrade from 3.5.3 to 3.9.3 causing router reducer error

### ISSUE THREAD

**Issue by jeremyrajan** [marmelab/react-admin#5397]
**What happened instead:**
I upgraded from 3.5.3 to 3.9.3 and I am getting the following error:
![image](https://user-images.githubusercontent.com/2890683/95883014-f623a800-0dac-11eb-816a-64813bd666ab.png)

**What you were expecting:**
When I downgrade, it's working fine.
**Steps to reproduce:**
1. Install 3.9.3

**Other information:**
Not sure, from which version it's starting to break. I don't see any migration docs as well, so assume that's not an issue?
**Other Deps**
![image](https://user-images.githubusercontent.com/2890683/95883356-68948800-0dad-11eb-9b8a-9a9bd0a1bcf9.png)

* React-admin version: 3.9.3
* Last version that did not exhibit the issue (if applicable): 3.5.3
* React version: 16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error):
```
react-dom.development.js:327 Uncaught Could not find router reducer in state tree, it must be mounted under "router"
rethrowCaughtError @ react-dom.development.js:327
runEventsInBatch @ react-dom.development.js:3313
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
```

**Comment by djhi** [comment]
Thanks for reporting this. We have several applications migrated to 3.9.3 without any issue. Without more informations it's difficult to help you. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or a github repository.

**Comment by yezhiming** [comment]
facing the same issue, downgrade history package to 4.10.1 resolve the problem for me.

**Comment by iamdb** [comment]
I'm also seeing this issue. I wish I could provide more informationt, but I don't really have any. It's essentially a new setup with Create React App and React Admin. If I simply add a custom history to the Admin component to remove the hash I get that error. The history package defaulted to v5, though, and downgrading like @yezhiming mentioned worked fine, so maybe there's a version compatibility issue somewhere.

**Comment by jeremyrajan** [comment]
Yes, downgrading to 4.10 solved the issues. Thanks a lot 😄! @djhi I think its probably the `history` dependency causing the issues.
