### ISSUE TITLE
Custom Menu component doesn't receive onMenuClick

### ISSUE THREAD

**Issue by Ponjimon** [marmelab/react-admin#5398]
The documentation states that a custom menu component should receive a `onMenuClick` prop, but it only receives `logout` and `hasDashboard`.

https://marmelab.com/react-admin/Theming.html#using-a-custom-menu

Either the documentation is wrong, or it needs to be added here: https://github.com/marmelab/react-admin/blob/792422b33f5d8f1bd3404d717196da44bf3277d7/packages/ra-ui-materialui/src/layout/Layout.js#L130-L135

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by Ponjimon** [comment]
It's litereally in the code sample of this repository, I don't understand why it needs a sample application.

**Comment by fzaninotto** [comment]
It's [the Sidebar component](https://github.com/marmelab/react-admin/blob/b6ee2fbc57e8f2958b4923119a6231921e9430f6/packages/ra-ui-materialui/src/layout/Sidebar.tsx) that injects the `onMenuClick` prop to Menu, to allow menu items to close the sidebar on click. But in only injects `onMenuClick` on lower sreen sizes. On larger screen sizes, Sidebar doesn't inject it.

The default menu has a defaultProp for `onMenuClick` (`() => null,`) to work even when the prop isn't injected. This default prop isn't documented or practical, so I think Sidebar should inject an empty `onMenuClick` on desktop.

Marking it as a bug.
