### ISSUE TITLE
default AuthContext value fails TypeScript compilation

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#5406]
I believe issue #5372 is not yet fixed since only `id` was set to a string.
There is still a problem with the `fullName` property of `defaultIdentity` which is set to null in AuthContext.txt, giving error:
`type 'null' is not assignable to type 'string | undefined'.`

```
const defaultIdentity: UserIdentity = {
id: '',
fullName: null
 };
```
However UserIdentity type has:
```
fullName?: string;
```
so it can either be a string or undefined, but not null.

If you can't repro this it's probably because you have 'strict' set to false in tsconfig, which disables strict null checks (so null is  valid for a string type)

Using TS 3.9.4

**Comment by fzaninotto** [comment]
Building ra-core with `"strick": true` fails with 175 errors. I think there must be another reason why you're having this error and we don't.

**Comment by bayareacoder** [comment]
> Building ra-core with `"strick": true` fails with 175 errors. I think there must be another reason why you're having this error and we don't.

This was the first error that popped up.  Did a search based on error string and saw the earlier issue that I referenced. Doesn’t mean there are no other errors. Yes it builds fine with “strict:false”.
