### ISSUE TITLE
AppBarProps is not exported

### ISSUE THREAD

**Issue by ordovicia** [marmelab/react-admin#5409]
**What you were expecting:**

`AppBarProps` would be exported from `ra-ui-materialui` here:
https://github.com/marmelab/react-admin/blob/9bf186b0522b9c82bf126c21d772dc6ef367ce68/packages/ra-ui-materialui/src/layout/index.ts#L1

**What happened instead:**

`AppBarProps` is not exported.
So I can't assign a proper type to my app bar implementation like this:

```typescript
import { AppBarProps } from 'ra-ui-materialui'; // error

const MyAppBar: React.FC<AppBarProps> = (props) => {
 ...
};
```

**Other information:**

**Environment**

* React-admin version: 3.9.3

**Comment by fzaninotto** [comment]
Thanks for the report, bug confirmed.
