### ISSUE TITLE
"Out of the box" sorting feature currently not working with MERN stack application

### ISSUE THREAD

**Issue by manedurphy** [marmelab/react-admin#5413]
**What you were expecting:**

When walking through the tutorial and gathering data online fake API, the sorting abilities work just find. I can order in ascending and descending order as expected.

**What happened instead:**

For my current MERN stack application, I have linked react-admin to my Mongo database, and it is currently able to gather information as expected. However, the sorting feature no longer works. Regardless if I change the sort query parameters, the order does not change. Everything is currently listed in the same order as it is in my database. 

**Steps to reproduce:**

**Related code:**

This is how I am currently getting my list of interest. I have played around with "sort", "sortBy", and "sortByOrder" with no success

```jsx
export const TutorList = (props) => (
  <List {...props} /*filters={<TutorFilter />}*/>
    <Datagrid rowClick="edit">
      <TextField source="name" />
      <TextField source="id" />
      <EmailField source="email" />
      <DateField source="date" />
      <TextField source="role" />
    </Datagrid>
  </List>
);
```

I can provide more information if it is necessary. The information in my database holds sensitive information so I am hesitating to show a demonstration of this behavior, although I am willing to clear it out and start over if need be in order to fix this issue.

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
Sorting works in the core. The problem probably lies in your dataProvider. If you are using one of the core dataProviders (simple-rest, json-server, graphql-simple), then this may be a bug in our code, otherwise it's a bug in your code or in a third party data provider code.

**Comment by fzaninotto** [comment]
This issue has gone silent. Without any way to reproduce the issue, we have to close it. Feel free to comment with new info if you want it reopened.
