### ISSUE TITLE
useListController() properties selectedIds, onSelect, onUnselectItems, onToggleItem are ignored

### ISSUE THREAD

**Issue by izziaraffaele** [marmelab/react-admin#5415]
**What you were expecting:**
```javascript
<ListBase basePath="/user" resource="user" selectedIds={[1,2]} onToggleItem={handleToggleItem}>
  <Datagrid>
     //....
  </Datagrid>
</ListBase>
```
Rendering this component I expect to see a table of users where the user 1 and 2 are preselected. By selecting/unselecting a single user in the table I expect the handleToggleItem callback to be called with the record toggled

**What happened instead:**
Records in the table are not preselected and the callback is never called

**Other information:**
The problems seem to be inside useListController() which doesn't take into consideration its props.

**Environment**

* React-admin version: ^3.9.2

**Comment by fzaninotto** [comment]
This is not supported. Where in the doc did you see that?

Also, I suspect that your use case is not standatrd if you need to preselect items and to override the selection system, so I suggest you don't use `ListBase`, but fetch the data and create the `ListContext` manually instead.

**Comment by izziaraffaele** [comment]
@fzaninotto thanks for the suggestion. In fact, it is not mentioned in the docs, I was just looking at the ListControllerProps and I thought those options were meant to be used for that use case.

**Comment by fzaninotto** [comment]
thanks for your feedback. This is neither supported or documented, so I'm closing this issue.
