### ISSUE TITLE
DO SOMETHING ABOUT THE CORS!!!

### ISSUE THREAD

**Issue by joaoh821C** [marmelab/react-admin#5416]
I HAVE BEEN TRYING FRO AN ENTIRE DAY TO GET THIS TO WORK WITH A GOLANG BACKEND THAT WORKS EVERYWHERE EXCEPT WITH REACT-ADMIN

IT IS RIDICULOUS THAT IT WOULD TAKE ME 2 HOURS TO WRITE AN ENTIRE API AND AFTER 8 HOURS I STILL CANNOT GET THIS FREACKING THING TO WORK BECAUSE OF YOUR STUPID CORS RETRICTIONS.

I ALREADY HAVE EVERYTHING WORKING ON THE GO SIDE, WITH ALL THE HEADERS BUT REACT-ADMIN STILL DOES NOT ACCEPT IT.

CRAPPY FRAMEWORK THIS IS!!

**Comment by fzaninotto** [comment]
Your contribution is exactly the reason why being an open source project maintainer sucks. 

Let me summarize:

-you have tons of feature for free
-you didn't read the documentation 
-you didn't follow the issue template

And you dare yelling at us? That, my friend, gets you banned from this repository. 

We work on react-admin for fun and pleasure, not to get yelled at. 

So long.
