### ISSUE TITLE
Frightening error messages about vmlinuz, initrd.img

### ISSUE THREAD

**Issue by vibl** [marmelab/react-admin#5417]
After just installing react-admin on a freshly created Razzle app, I get frightening messages:

```
(node:3346932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz'
(node:3346932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:3346932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz.old'
(node:3346932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:3346932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/initrd.img'
(node:3346932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:3346932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/initrd.img.old'
(node:3346932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:3346932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz'
(node:3346932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:3346932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz.old'
(node:3346932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

If a script is trying to reach my Linux bootloader, something seriously dangerous is occurring here...

In some cases, the error logs also showed this ENOENT error for $HOME/.steampath

The only other similar report I could find with Google is there: https://stackoverflow.com/questions/63165044/vue-cli-outputting-very-concerning-error-security-question

I did a full-text search ("vmlinuz", "initrd") with VScode, ripgrep  and grep. Nothing found.

I deleted my $HOME/.nvm, $HOME/.npm $HOME/node_modules and $HOME/.yarn before redoing the steps below but the same happened.

**Steps to reproduce:**
```
npx create-razzle-app myapp
cd myapp
npm start
```
No error message here. Razzle is working fine.
```
# Ctrl+c (to kill the Razzle server)
npm i react-admin
npm start
```
Here, I get the normal Razzle stdout and then the error messages pasted above.

**Environment**
react-admin 3.9.4
Ubuntu 20.04

**Comment by vibl** [comment]
Same with `create-react-app`:

```
npx create-react-app myapp
cd myapp
npm start
```
No error message here.
```
# Ctrl+c (to kill the Razzle server)
npm i react-admin
# Replace src/App.js with the first example shown in https://marmelab.com/react-admin/Tutorial.html
npm start
```
Console output:
```
Compiling...
/home/vianney/dev/js/perso/quantself/lifetrack/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

[Error: ENOENT: no such file or directory, stat '/initrd.img'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/initrd.img'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lifetrack@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lifetrack@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by vibl** [comment]
I can't manage to get traces of theses errors.

I tried ```NODE_OPTIONS="--trace-warnings" npm start```

And I tried adding replacing the `unhandledRejection` listener in `node_modules/react-scripts/scripts/start.js` to:
```
process.on('unhandledRejection', (err, p) => {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', err, 'stack:', err.stack);
});
```

**Comment by fzaninotto** [comment]
The error message doesn't link to react-admin. This is likely an error in your node setup, nothing specific to react-admin. 

Please provide a way to reproduce the problem, or we'll have to close it.

**Comment by vibl** [comment]
The messages only appear when I install react-admin, both with Razzle and create-react-app. What's more, I found out since yesterday that the messages disappeared when I install the package `ra-data-json-server` or when I use https://github.com/BowlingX/ra-postgraphile. I'd say that it does link them to react-admin, even though they don't mention it. The malicious script might have found a way to avoid being logged in the traces.

Would you say it's impossible that one of the dependencies (direct or indirect) of react-admin has been compromised and a malicious script is executed with it? It could explain the errors, and those described there: https://stackoverflow.com/questions/63165044/vue-cli-outputting-very-concerning-error-security-question

I'm surprised that you're not considering that possibility seriously.

I don't think it's related to my Node.js setup because it happens the same whether I use `nvm`'s node (after deleting all my config and reinstalling from scratch), or if I use `apt`'s node, freshly installed as well. Furthermore, I don't have any `node_modules` in the parent directories of the app.

Did you try the steps I laid out?

If you don't see the errors, it doesn't mean that the script is not executed. For example, the files that this script stats happen to be missing on my machinne at the location it's looking at, but there wouldn't be error if it had found them.

**Comment by djhi** [comment]
Just tried the exact same steps you laid out and could not reproduce the issue so something is wrong with your setup

**Comment by fzaninotto** [comment]
I suggest you search for the string 'initrd.img' in your packages.json to find the culprit package, and report an issue on their repository.

**Comment by vibl** [comment]
So that confirms you didn't read what I wrote. 

It's in the fourth sentence of my first message.

**Comment by fzaninotto** [comment]
You're right, this was in your post. Then I don't see how we can progress on this issue, since we can't reproduce it.

**Comment by vibl** [comment]
There clearly is a malicious script in the JS ecosystem. It is either in one of react-admin's dependencies or in a dependency common to Razzle and create-react-app. I'd say the former is the most probable because the error messages only show up when I install react-admin.

Wherever this script is, it's trying to access the Linux kernel, so it's a big security risk.

According to the SO issue (stackoverflow.com/questions/63165044/vue-cli-outputting-very-concerning-error-security-question), we are at least four people to have detected it thanks to this error messages, but this script probably runs on many more machines undetected (for example, if it finds the files it's looking for, or if `unhandledRejection` error are not listened to, or not traced).

Who can we alert so that this problem is investigated? Is there a security team at NPM that can take charge of this, or at least help us?

**Comment by fzaninotto** [comment]
You can alert the npm team if you have isolated the package that is misbehaving. But it seems you don't have any way to isolate it, and we have no way of reproducing the problem...

**Comment by vibl** [comment]
I sent an email to security@npmjs.com

Pasted below:

---
Probable malicious package trying to access initrd and vmlinuz

Hi,

There probably is a malicious package in the dependency tree of https://www.npmjs.com/package/react-admin, that  is trying to access initrd, vmlinuz and $HOME/.steampath

All the details are in this Github issue thread:
https://github.com/marmelab/react-admin/issues/5417

I can paste them in an email if your prefer.

The node console only shows these error messages after I install react-admin, either with Razzle or create-react-app. However, the react-admin team could not reproduce them.

Three other people reported the same messages (although not related to react-admin):

https://stackoverflow.com/questions/63165044/vue-cli-outputting-very-concerning-error-security-question

Feel free to ask any question.

Regards,

Vianney Stroebel

**Comment by vibl** [comment]
I've just had the error messages without react-admin, so it's not related. You can close this issue.

**Comment by vibl** [comment]
For reference: see updated report at https://stackoverflow.com/questions/64483296/react-apps-build-output-concerning-build-errors-about-initrd-img-and-vmlinuz

**Comment by vibl** [comment]
There seems to be a simple answer: these messages could just come from Node searching for `node_modules` in the project parent directories all the way to the filesystem root. (See https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders). It might also try to follow symlinks in case they point to a `node_modules` directory, and emit an error each time it encounters a broken symlink in the process.

That's plausible and reassuring. No malicious script involved.

I removed initrd.img, /initrd.img.old, /vmlinuz and /vmlinuz.old, which were indeed broken symlinks. So I shouldn't get these errors anymore.

**Comment by yuichiu416** [comment]
I had this initrd.img error recently, it ended up being me writing the import incorrectly.
In my project, I did `import $ from 'jQuery';` instead of `import $ from 'jquery';`
Not sure if this is the same issue as yours but hope this helps.

**Comment by janspoerer** [comment]
Same error source for me as for @yuichiu416. I did `import {Helmet} from 'react-helmet';` instead of `import { Helmet } from 'react-helmet';` and then received this error about a missing `initrd.img`.

**Comment by DShcherbak** [comment]
> I had this initrd.img error recently, it ended up being me writing the import incorrectly.
> In my project, I did `import $ from 'jQuery';` instead of `import $ from 'jquery';`
> Not sure if this is the same issue as yours but hope this helps.

Something quite similar for me: I was having this problem and fixed it simply by changing
`import styles from "Editor.module.css"`
to 
`import styles from "./Editor.module.css"`
Hope it helps somebody

**Comment by shubham-rajodiya** [comment]
Solved:
I was also facing the same issue few days before.
This is because if any of the code is importing any library ( package ) and if that library ( package ) is not installed it will throw this error.
In my case, I have used **exceljs** in one of my component. And without installing **exceljs** I was trying to start the project.
After intsalling the **exceljs**  package its working fine.

**Comment by franquil** [comment]
I met a similar error message, after removing all deps and reinstalling them again, it says there's 'node-sass' dependency issue. Then I rebuild the dep, the error was gone.

**Comment by rogoit** [comment]
My problem was a not installed "call" lib from VSC auto completion. So the error message has nothing to do with it. Spooky issue ;)
