### ISSUE TITLE
allow TS strict mode compilation

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#5418]
Currently TS compilation fails when overall strict mode, or individual components of it (especially `strictNullChecks`, but possibly also `strictFunctionTypes` and `strictBindCallApply`) are enabled in tsconfig.json.
This puts a restriction on code consuming `react-admin` to also have looser type checking, which can make bugs go unnoticed in consuming app at compile time. 
For instance `x.<prop or method>` now is not flagged by TS compiler if x can be null, so optional chaining is not enforced,  since `strictNullChecks=false` allows any type to be null.
In a future update, it would be good to pass with `strict:true` (which sets all 3 sub-rules), or at least with `strictNullChecks:true` which is the most common check.

**Comment by djhi** [comment]
Thanks for reporting. Yes, we have an example app in strict mode to work on this and indeed, there is still a lot to do.

**Comment by fzaninotto** [comment]
I'm -1 for spending time on this. We've already stalled the react-admin development for months just to provide TypeScript support. I like writing code for people, not to please compilers. Also, given the number of users of this library, if there is a bug in react-admin, and it's not reported yet, I bet it's not super critical. So I doubt the cost/benefit ratio of TS strict mode can ever be positive.

**Comment by fzaninotto** [comment]
No feedback on this, so I'm closing the issue. The core team will not spend time on this in the near future. If you wish to help making react-admin capable of passing strict TS checks, feel free to open a PR with your changes.
