### ISSUE TITLE
form.dirty is being reset in FormTab but is working correctly in ArrayInput in FormTab

### ISSUE THREAD

**Issue by CarlosSia** [marmelab/react-admin#5424]
**What you were expecting:**
when calling form.change in a custom component within a FormTab, the form will become dirty and let the user able to save the data

**What happened instead:**
after calling the form.change, the form.dirty actually updated and become true but when React rerender form.dirty has change to false, however if the custom component is put in a ArrayInput within a FormTab, it is working correctly.

**Steps to reproduce:**
I have create the custom component and implement it inside 3 tabs in PostEdit.js.
firstTab have custom component without wrapped in anything and wrapped in ArrayInput, while secondTab only have custom component without wrapped in anything and thirdTab only have custom component wrapped in ArrayInput.

Step:
For custom component wrapped in ArrayInput
1. Click first post.
2. Click the add button.
3. Save the form.
4. Click first post.
5. Click the Upload File button, a dialog will pop out.
6. Select File to be upload.
7. Click Save button of dialog.
8. The title of the file will come out in an input, can try to save the form.
9. Click first post and click remove button of the title of file.
10. Save the form.

For custom component not wrapped in ArrayInput, repeat step 4 - 10, and step 8 and 10 is not able to be done because the save button is disabled

**Related code:**

https://codesandbox.io/s/amazing-meitner-iply7?file=/src/posts/PostEdit.js

**Comment by CarlosSia** [comment]
any update on this issue?

**Comment by djhi** [comment]
Thanks for reporting it and adding a codesandbox. I had a quick look yesterday but will have to dig deeper

**Comment by CarlosSia** [comment]
Sorry to say but i have rewrite the component in new file which is same as the one have problem and suddenly it is working, thanks for checking and i will close this issue
