### ISSUE TITLE
Resource dependency not found.

### ISSUE THREAD

**Issue by BatcaveBC** [marmelab/react-admin#5425]
I have been working with the dependency on a React Project for about a week and worked very smoothly, when I updated today to version 3.9.4 I had a problem with the Resource import on my App.js file. I'm working on IntelliJ and the dependency already showed like it is not there.
<img width="577" alt="Screen Shot 2020-10-19 at 9 39 14 PM" src="https://user-images.githubusercontent.com/43043946/96537499-a4b76500-1253-11eb-9bc5-0ba83da3845c.png">

When you run the application, the following happens:
<img width="1111" alt="Screen Shot 2020-10-19 at 9 41 10 PM" src="https://user-images.githubusercontent.com/43043946/96537588-ddefd500-1253-11eb-8d68-8b929e05a9c8.png">

To reproduce it just follow the first steps of the tutorial on the main site and be sure in your package.json file to use the 3.9.4 version for react-admin. I already tested, debugged, removed, and added dependencies to my project but never got to solve it while using that version. Once I removed the node_modules (*just to be sure) and downgraded the library, I finally made it work on my app again, back to joy and developing normally.

**Comment by djhi** [comment]
Please double check your `react-admin`, `ra-core` and other related packages versions in either your `yarn.lock` or `package-lock.json` file. Make sure there aren't multiple versions of the packages in it.

**Comment by BatcaveBC** [comment]
Indeed by deleting the package-lock.json, node_modules and running `npm install` in the terminal again, I got the new version and it works normally now. I did confirm I had multiple versions on my old package-lock.json and I will keep it in mind next time.
