### ISSUE TITLE
Sidebar option in theming doesn't work

### ISSUE THREAD

**Issue by mariaefi29** [marmelab/react-admin#5426]
**What you were expecting:**
As docs are saying in order to customise the sidebar and keep it responsive, you have to pass the settings in a theme prop in Admin:

```
import { createMuiTheme } from '@material-ui/core/styles';

const theme = createMuiTheme({
    sidebar: {
        width: 300, // The default value is 240
        closedWidth: 70, // The default value is 55
    },
});

const App = () => (
    <Admin theme={theme} dataProvider={simpleRestProvider('http://path.to.my.api')}>
        // ...
    </Admin>
);
```

**What happened instead:**
Unfortunately, it didn't work, because createMuiTheme doesn't support `sidebar` option.

I have found the same question in [StackOverflow](https://stackoverflow.com/questions/62190823/simple-solution-for-sizing-sidebar-of-a-react-admin-app) and there was a solution not to wrap it around createMuiTheme:

```
const theme = {
  sidebar: {
    width: 220, 
    closedWidth: 55, 
  },
} 
```

However, it doesn't work either. I got the following error:

 `Type '{ sidebar: { width: number; closedWidth: number; }; }' has no properties in common with type 'ThemeOptions'.`

**Steps to reproduce:**

Modify App.tsx with the code from docs or the code in Related Code and you will see a compile error. I use Typescript. Apparently it doesn't work with TS.
**Related code:**
App.tsx:

```
import * as React from 'react'
import { Admin, Resource} from 'react-admin';
import dataProvider from './dataProvider';
import { cacheDataProviderProxy } from 'react-admin';
import { FeedList } from './components/feeds'
import Layout from './components/layout';
import { CollectionsBookmark } from '@material-ui/icons';

const customDataProvider = cacheDataProviderProxy(dataProvider('http://localhost:8080/api/v1'));

const theme = {
  sidebar: {
    width: 220,
    closedWidth: 55,
  },
}

const App = () => (
    <Admin
        theme={theme}
        dataProvider={customDataProvider}
        loginPage={false}
        title="Title"
        layout={Layout}>
        <Resource name="feeds" list={FeedList} icon={CollectionsBookmark}/>
    </Admin>
);

export default App;
```

**Environment**

* React-admin version: ^3.9.4
* React version: ^16.13.1
* Browser: Google Chrome
* Stack trace (in case of a JS error):
```
TypeScript error in /Users/Mariaefi/Documents/react/admin-is/src/App.tsx(21,9):
Type '{ sidebar: { width: number; closedWidth: number; }; }' has no properties in common with type 'ThemeOptions'.  TS2559

    19 | const App = () => (
    20 |     <Admin
  > 21 |         theme={theme}
       |         ^
    22 |         dataProvider={customDataProvider}
    23 |         loginPage={false}
```

**Comment by djhi** [comment]
This is a documentation issue. Indeed, in order to override a component styles, you'll have to use the `overrides` key of the MUI theme:

```jsx
const theme = {
  overrides: {
    RaSidebar: {
      width: 220,
      closedWidth: 55,
    },
  },
}
```

See this article which explains this in details: https://marmelab.com/blog/2020/09/11/react-admin-tutorials-build-your-own-theme.html

**Comment by mariaefi29** [comment]
Thank you for a good blog post! I will check it out!

However, with this new proposed style and have the following TS error:

```
Type '{ overrides: { RaSidebar: { width: number; closedWidth: number; }; }; }' is not assignable to type 'ThemeOptions'.
  Types of property 'overrides' are incompatible.
    Type '{ RaSidebar: { width: number; closedWidth: number; }; }' has no properties in common with type 'Overrides'.
```

**Comment by djhi** [comment]
That's because we don't export a custom theme type yet. For the time being, you can try this not ideal workaround:

```js
import { ThemeOptions as MuiThemeOptions } from "@material-ui/core";

export interface ThemeOptions extends MuiThemeOptions {
  overrides?: {
    [key: string]: any;
  };
}

const theme: ThemeOptions = {
  overrides: {
    RaSidebar: {
      size: 300
    }
  }
};
```

**Comment by mariaefi29** [comment]
Thank you! I have tried that, but unfortunately, it didn't work. The app compiled, but the sidebar had the same default size/width and for some reason all my colors have changes. I had blue-ish design, but now everything red. 

Something weird is going on, it seems like it overrides other properties and themes as well :( 

![image](https://user-images.githubusercontent.com/25860669/96562550-91df7780-12c9-11eb-8f36-6ca9123d94fe.png)

**Comment by djhi** [comment]
Can you set up a codesandbox showing the issue?

**Comment by mariaefi29** [comment]
Is this ok? https://codesandbox.io/s/cranky-sanderson-2l2tm?fontsize=14&hidenavigation=1&theme=dark

As you can see, the size doesn't change a bit (even if you put width/size, doesn't matter), however, the colors changed. 

You can remove the theme and see how it was before. But most importantly, I can't make the Sidebar responsive with a custom width easily.

**Comment by djhi** [comment]
Yes, thanks a lot. And sorry about the bad tips...

## About the theme

If you want to keep the default theme but override/extend some parts, this will make sure you don't loose our defaults such as the colors:

```jsx
import { defaultTheme } from "react-admin";

export interface CustomThemeOptions extends MuiThemeOptions {
  overrides?: {
    [key: string]: any;
  };
}

const theme: CustomThemeOptions = {
  ...defaultTheme,
  overrides: {
    ...defaultTheme.overrides,
    RaSidebar: {
      ...
    }
  }
};
```

The readon we don't merge the custom theme with our default one ourselves is that you may provide us with a complete theme returned by `createMuiTheme`. Not sure it's a good reason though. @fzaninotto ?

## About the Sidebar width

The documentation is even more misleading than I thought. The `<SideBar>` component simply accept two props for sizes:
- `size: number`: the size when open
- `closedSize: number`: The size when closed

**Comment by mariaefi29** [comment]
Thanks a lot! I'll keep that in mind!

I saw those parameters (size, closedSize), but that do not work :( 

https://codesandbox.io/s/cranky-sanderson-2l2tm?fontsize=14&hidenavigation=1&theme=dark

I even tried to have my own SideBar and put the size parameter as a prop, nothing( still 240px width

**Comment by djhi** [comment]
So after more digging, it seems the documentation is right but we haven't provided types for our theme... :tired_face: In the mean time, you can do:

```js
import { ThemeOptions } from '@material-ui/core/styles';

export interface CustomThemeOptions extends ThemeOptions {
  sidebar?: {
    width?: number;
    closedWidth?: number;
  };
}

const theme: CustomThemeOptions = {
    sidebar: {
        width: 300, // The default value is 240
        closedWidth: 70, // The default value is 55
    },
};

const App = () => (
    <Admin theme={theme} dataProvider={simpleRestProvider('http://path.to.my.api')}>
        // ...
    </Admin>
);
```

**Comment by mariaefi29** [comment]
@djhi Thank you so much! 

It works! I added `..defaultTheme` though as well, because without that it changes colors again.

I'll stay tuned for provided types then! Thanks again for your help!

**Comment by mariaefi29** [comment]
Dear @djhi,

will you export the types, please? So it will work as it says in the docs? I thought it could be done with this issue, but the issue was closed :) I would appreciate your help! Thank you!

**Comment by djhi** [comment]
We usually close TS issues but now that we actually ship types officially, we should probably track them correctly

**Comment by mariaefi29** [comment]
Thank you very much!
