### ISSUE TITLE
Attempted import error: 'ListContextProvider' is not exported from 'react-admin'.

### ISSUE THREAD

**Issue by Murali-mahadeva-BS** [marmelab/react-admin#5430]
I am trying to use ListContextProvider with useQuery hook. i just copy pasted the code from react admin documentation. But i got this error.

My import patter: 

```
import { useQuery, Datagrid, TextField, Pagination, Loading, ListContextProvider } from 'react-admin'
```

Usage:

```
 <ListContextProvider
            value={{
                resource: 'posts',
                basePath: 'posts',
                data: keyBy(data, 'id'),
                ids: data.map(({ id }) => id),
                currentSort: { field: 'id', order: 'ASC' },
                selectedIds: [],
            }}
        >
            <Datagrid rowClick="edit">
                <TextField source="id" />
                <TextField source="title" />
            </Datagrid>
```

within ListContextProvider my parameter are different, I didnt get why it is giving error in import

**Comment by fzaninotto** [comment]
Perhaps you're using an old version of react-admin that doesn't expose this component. Can you paste your react-admin version dependency, as requested in the issue template?

**Comment by fzaninotto** [comment]
This issue has gone silent. Without any way to reproduce the issue, we have to close it. Feel free to comment with new info if you want it ropened.
