### ISSUE TITLE
Release v3.9.5  broke layout prop

### ISSUE THREAD

**Issue by mariaefi29** [marmelab/react-admin#5443]
**What you were expecting:**
On v3.9.4  I used layout prop and passed in it my custom layout component.

**What happened instead:**
After upgrading to v3.9.5 I started getting the following error and the app stoped working:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Steps to reproduce:**
I was able to identify the problem and it turned out to be with a custom layout component.

**Related code:**
https://codesandbox.io/s/cranky-sanderson-2l2tm?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.tsx

If you comment out the layout component, everything works. If you add it again, the app break with the error that I specified above.

**Environment**

* React-admin version: v3.9.5
* Last version that did not exhibit the issue (if applicable): v3.9.4
* React version: 17.0.1
* Browser: Google Chrom
* Stack trace (in case of a JS error):
![image](https://user-images.githubusercontent.com/25860669/97287393-97066e80-1855-11eb-8feb-202c19785a2d.png)

**Comment by Luwangel** [comment]
Hi, thanks for reporting this issue. It's probably related to my PR https://github.com/marmelab/react-admin/pull/5421. I let you know as soon as I understand what is wrong.

**Comment by Luwangel** [comment]
Hi again,

You issue is not related to my changes because they haven't been released yet.

But I found your issue:

> Warning: Failed prop type: Invalid prop `userMenu` of type `function` supplied to `AppBar`, expected a single ReactElement.

You need to pass a ReactElement to the `userMenu` prop.

``` jsx
const MyAppBar = props => <AppBar {...props} userMenu={<MyUserMenu />} />;
```

Regards,
Adrien

**Comment by mariaefi29** [comment]
@Luwangel  Oh, thank you so much!!!

**Comment by mariaefi29** [comment]
Could you please tell me why in AppBar for example you don't need to pass as a react element?

this works:
`return <Layout {...props} appBar={CustomAppBar} />;`

**Comment by Luwangel** [comment]
It's because we use internally `createElement` for the `appBar`, and `cloneElement` for the `userMenu`. But it's difficult to change it at the moment because it'll introduce a breaking change. We need to think about it for the v4.
