### ISSUE TITLE
Delete error does not refresh list view

### ISSUE THREAD

**Issue by fergonco** [marmelab/react-admin#5445]
**What you were expecting:**

When the user deletes a resource from a list view, the optimistic rendering shows the list without the deleted resource. If the resource deletion fails (returning a 500 status code, for example), the list view should be refreshed, as stated in the documentation [https://marmelab.com/react-admin/Actions.html#optimistic-rendering-and-undo](): "If the fetch fails, react-admin shows an error notification, and forces a refresh, too." This refresh should make the item reappear, as the deletion failed.

**What happened instead:**

The list view is not refreshed. Only after the user hits the refresh button manually the entry reappears.

**Steps to reproduce:**

1. Navigate to a list of resources.
2. Select one.
3. Delete it (and manage to get a 500 status response from the server, not deleting the resource)
4. Wait for the commit delay.
5. The delete request is made, it fails, an error notification is shown but the list is not refreshed and the resource is missing.

**Related code:**
The "delete-error-missing-refresh" branch in this project [https://github.com/fergonco/ra-vs-fergonco/tree/delete-error-missing-refresh]() shows the issue. The missing part would be a server returning 500 status code when an user is deleted.

* React-admin version: 3.8.5
* Last version that did not exhibit the issue (if applicable): -
* React version: 16.13.1
* Browser: Firefox, chrome

**Comment by fzaninotto** [comment]
Confirmed and reproduced, thanks for the report.
