### ISSUE TITLE
Need to go to a resource section to retrieve data from this resource with useGetMany

### ISSUE THREAD

**Issue by fbigand** [marmelab/react-admin#5454]
**What you were expecting:**

I wanted to use the useGetMany hook to retrieve data. If I wanted to be more specific, I have a A resource (I will call it posts), and a B resource (I will call it comments), and I use foreign keys from a list of comments in useGetMany to get all the related posts.

**What happened instead:**

I get a proper list of posts, but only if I have previously visited the posts page, otherwise the hook get me back a list of undefined.

**Steps to reproduce:**

Use the useGetMany hook from a component in the comments section (eg: CommentsList), check that the retrieved data in a list of undefined, go to the posts section, and go back to the comments section, and see the that the provided data is now correct.
Unfortunaltely, I was not able to reproduce the issue on CodeSandbox.

**Related code:**

SomeComponent.js
```javascript
import * as React from 'react'
import { useGetList, useGetMany } from 'react-admin'

// This function works fine, you can skip the code
const GetCommentList = () => {
  const { data } = useGestList(
    'comments',
    { page: 1, perPage: 20000 },
    { field: 'id', order: 'ASC' },
    {}
  )
  var list = []
  for (const [key, value] of Object.entries(data)) {
    list.push(value)
  }
  return list
}

// The function I have problem with
const GetRelatedPosts = (comments) => {
  var postIds = []
  comments.forEach(comment => {
    const postForeignKey = comment.post_id
    if (!postIds.includes(postForeignKey)) {
      postIds.push(postForeignKey)
    }
  })
  const { data } = useGetMany(
    'posts',
    postIds // I already test the array [1,2,3,4,5], and had the same result
  )
  console.log(data) // Only for the purpose of debugging
}

const SomeComponent = () => {
  const comments = GetCommentsList()
  GetRelatedPosts(comments)
  return <p></p>
}

export default SomeComponent
```

CommentList.js
```javascript
import * as React from 'react'
import { Datagrid, List, TextField } from 'react-admin'
import SomeComponent from './SomeComponent'

const CommentList = props => {
  <List {...props} sort={{ field: 'id', order: 'DESC' }}>
    <>
      <SomeComponent />
      <Datagrid>
        <TextField source='comments' label='id' />
      </Datagrid>
    </>
  </List>
}
```

**Other information**
Here is some screen to show to result from the code below.
I first start from the comment list view and the console shows me undefined data
![image](https://user-images.githubusercontent.com/45237836/97591775-40896380-1a00-11eb-88ba-13107ba120e7.png)
Then I go to the posts list view, and go back to the comment list, and the console displays me the correct values from my api (I did not expand on the image, but the data is right).
![unnamed](https://user-images.githubusercontent.com/45237836/97591800-454e1780-1a00-11eb-814b-62eb826392dd.png)

**Environment**

* React-admin version: 3.7.1
* React version: 16.13.1
* Browser: Firefox 82.0 (64-bits)

I thank you in advance for any response and help.

**Comment by fzaninotto** [comment]
I cannot reproduce the problem in the simple example. So either the problem comes from your dataProvider, or there is something else in your code than what you've described here.

In any case, we'll need a Codesandbox reproducing the issue to investigate further.

**Comment by MicroJackson** [comment]
Seems like the same problem described in https://github.com/marmelab/react-admin/issues/5054 with a codesandbox https://github.com/marmelab/react-admin/issues/5054#issuecomment-694164979. UseGetMany and UseGetManyReference (used by ReferenceManyField) seem to have the same problem, that it will give undefined back if you did not go to the specific Resource first.

**Comment by fbigand** [comment]
After having the exact same problem when using the ReferenceField component (which worked before we changed our dataprovider) I am definitively convinced that the problem comes from the getMany function of our custom dataProvider.
