### ISSUE TITLE
withDataProvider without onSucess/onFailure keys break

### ISSUE THREAD

**Issue by blamze** [marmelab/react-admin#5477]
**What you were expecting:**
Using **withDataProvider** only 2 arguments should be required, and third one - optional. After 3.9.5 version it breaks.

**What happened instead:**
If you do not give third argument with keys: ' onSuccess' and 'onFailure' JS breaks, does not fetch. Throws error
```
`
TypeError: Cannot convert undefined or null to object
node_modules/ra-core/esm/dataProvider/useDataProviderWithDeclarativeSideEffects.js:60
  57 | var onFailure;
  58 | var finalOptions = options;
  59 | var finalAllArguments = allArguments;
--> 60 | if (Object.keys(options).some(function (key) {
     | ^  61 |     return ['onSuccess', 'onFailure'].includes(key);
  62 | })) {
  63 |     var sideEffect = getSideEffects(resource, options);`
```

**Steps to reproduce:**
Does not work/fetch with this snippet, even thought it used to work.
```
export const LanguageSelect = withDataProvider(({ dataProvider }) => {  
... 
   ` useEffect(() => {
        dataProvider
            .getList('languages', {
                pagination: { page: 1, perPage: 100 },
                sort: { field: 'id', order: 'ASC' },
                filter: {},
            })
            .then(({ data }) => {
                setLanguages(data);
                setLoading(false);
            })
    }, [dataProvider]);
```

**Works now with this snippet**
`
```
export const LanguageSelect = withDataProvider(({ dataProvider }) => {
 ...
    useEffect(() => {
        dataProvider
            .getList(
                'languages',
                {
                    pagination: { page: 1, perPage: 100 },
                    sort: { field: 'id', order: 'ASC' },
                    filter: {},
                },
+                { onSuccess: {}, onFailure: {} },
            )
            .then(({ data }) => {
                setLanguages(data);
                setLoading(false);
            })
    }, [dataProvider]);
`
```

**Other information:**
@djhi
I believe this PR https://github.com/marmelab/react-admin/pull/5395
with code change on file useDataProviderWithDeclarativeSideEffects.ts broke it.

Even thought those changes should make useDataProvider and withDataProvider syntax the same, but now it's different, and withDataProvider is not usable without onSuccess and onFailure keys in third argument.

Also I strongly doubt that example about withDataProvider will work
https://marmelab.com/react-admin/Actions.html#legacy-components-query-mutation-and-withdataprovider

Edit:
I believe this
`
if (
                        Object.keys(options).some(key =>
                            ['onSuccess', 'onFailure'].includes(key)
                        )
                    )
`
in useDataProviderWithDeclarativeSideEffects.ts
 breaks if options = undefined or options = null
`returns Uncaught TypeError: Cannot convert undefined or null to object`

Maybe fix would be to check if options exist before Object.keys
```
if (options && Object.keys(options).some(key =>['onSuccess', 'onFailure'].includes(key)))
```

**Environment**

* React-admin version: from 3.9.5
* Last version that did not exhibit the issue (if applicable): Should be 3.9.4
* React version: 16/17
* Browser: chrome

Thank you

**Comment by fzaninotto** [comment]
hi, and thanks for your report. 

I tried to reproduce the problem you describe with `useDataProvider`, but I didn't manage to. I've forked the simple example CodeSandbox here: https://codesandbox.io/s/great-wilson-595eq?file=/src/customRouteLayout.js (uses react-admin 3.9.6).

```jsx
// in /src/customRouteLayout.js
import * as React from "react";
import { useEffect } from "react";
import { useDataProvider, useAuthenticated, Title } from "react-admin";

const CustomRouteLayout = () => {
  useAuthenticated();
  const dataProvider = useDataProvider();
  useEffect(() => {
    dataProvider
      .getList("posts", {
        pagination: { page: 1, perPage: 100 },
        sort: { field: "id", order: "ASC" },
        filter: {}
      })
      .then(({ data }) => {
        console.log(data);
      });
  }, [dataProvider]);

  return (
    <div>
      <Title title="Example Admin" />
      <h1>Posts</h1>
    </div>
  );
};

export default CustomRouteLayout;
```

Then I browse to https://595eq.sse.codesandbox.io/#/custom2 and get no error.

Can you fork this CodeSandbox and tweak it to reproduce your error? Something seems to be missing in your report.

**Comment by blamze** [comment]
@fzaninotto
The problem is with 'withDataProvider' not 'useDataProvider'

I forked and updated your example
https://codesandbox.io/s/thirsty-babbage-5ing6?file=/src/customRouteLayout.js
https://5ing6.sse.codesandbox.io/#/custom2

snippet
```
import * as React from "react";
import { useEffect } from "react";
import { withDataProvider, useAuthenticated, Title } from "react-admin";

const CustomRouteLayout = ({ dataProvider }) => {
  useAuthenticated();
  useEffect(() => {
    dataProvider
      .getList("posts", {
        pagination: { page: 1, perPage: 100 },
        sort: { field: "id", order: "ASC" },
        filter: {}
      })
      .then(({ data }) => {
        console.log(data);
      });
  }, [dataProvider]);

  return (
    <div>
      <Title title="Example Admin" />
      <h1>Posts</h1>
    </div>
  );
};

export default withDataProvider(CustomRouteLayout);
```

The bug is that signature of 'withDataProvided -> dataProvider' and 'useDataProvider -> dataProvider' are different after 3.9.5, and for 'withDataProvided -> dataProvider ' to work you need to add 3rd argument with {onSucess:{}, onFailure:{}} or it won't work.

**Comment by fzaninotto** [comment]
Thanks, I can now reproduce the problem. Investigating.
