### ISSUE TITLE
Custom Admin with custom dataprovider

### ISSUE THREAD

**Issue by Xeizzeth** [marmelab/react-admin#5478]
Desperately looking for assistance.  
Created this issue, as requested here in issue questions: https://stackoverflow.com/questions/64660478/custom-admin-component-with-custom-dataprovider  
Really looking into any help that could help me advance forward.  
  
Custom dataprovider I use is fetched from the tutorials with little modifications. It supports all the interface dataprovider should provide.

**Comment by fzaninotto** [comment]
If you're desperate for assistance, consider the following two options:

1. Offer a bounty on StackOverflow to motivate more people from the community to help you
2. Subscribe to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), which includes professional support. You'll get an answer within a day.

But as this issue tracker is only about bug and not "how to" or "help me" questions, I have to close your issue.

**Comment by Xeizzeth** [comment]
@fzaninotto I would subscribe if 125€ weren't a big deal. Pity I live not in so-called first world countries so yes - 125€ is too much yet.
