### ISSUE TITLE
Missing doc: recap of when the different methods of the AuthProvider are called

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#5490]
Hello,

I think the Authentication/Authorization pages could be made a little better if it included a flow diagram or a table like the one in https://marmelab.com/react-admin/DataProviders.html#request-format. The important bit in this table is the `Usage` column. Understand when each method is called and what for in a summarized table (or flow diagram like I said) would go a long way making it easier to integrate with esoteric API (in my case a JS lib that uses iframes, so I'm not using at all the react-admin login page but a custom one).

As I haven't explored the full AuthProvider and am not an expert, I'm not sure I can contribute it, but I'd be very happy to review it.

Thanks in advance!

**Comment by fzaninotto** [comment]
Fixed by #5493
