### ISSUE TITLE
Doc not clear about authProvider return values

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#5491]
Hello,

In https://marmelab.com/react-admin/Authentication.html#the-authprovider, you give the spec of the AuthProvider, specifying that each method should return `Promise.resolve()`. At first, second and third read, for me and my workmate it meant "the methods should return a Promise". After trying to return `Promise.reject("something")` many times and reading a bit of the source (for example [`useLogout`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/auth/useLogout.ts#L51) and [`checkAuth`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/auth/useCheckAuth.ts#L57)), it's clear that the `logout` method *must* use `Promise.resolve` and doesn't support `Promise.reject`. But `checkAuth` does support `Promise.reject`.

It would be nice to clarify what exactly is supposed to be returned from these functions.

**Comment by fzaninotto** [comment]
You're right, we can do better!

**Comment by DjebbZ** [comment]
1. You're super fast!
2. I've read the whole diff, and the Request/Response/Error format tables are spot on. Exactly the kind of info I was seeking.

Thanks a lot!
