### ISSUE TITLE
Ability to provide PopperProps to MUI Tooltip in MenuItemLink, DashboardMenuItem and buttons in AppBar

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#5497]
**Is your feature request related to a problem? Please describe.**
I have crated a "show" component that displays PowerBi reports inside a flex container so that the report is automatically resized on browser resize and on menu open/close. I noticed that when I hover over any button in menu, or in AppBar, a tooltip is rendered and PowerBi report flickers (resizes to a smaller size, and then resized back to a correct size). I noticed that this behavior is caused by a div added to "body" element.

![image](https://user-images.githubusercontent.com/48455289/98410111-ac3f8200-2039-11eb-82d9-2d097481a7b0.png)

I was able to fix the issue by adding adding a hidden div to index HTML file, and using it as a target for Toolbar Popper. For example, to fix the issue, I copied your MenuItemLink component to manually add a PopperProps that references tooltip target container.

**index.html:**
```html
<div
  id="tooltipsDiv"
  style="display: block; position: fixed; pointer-events: none; top: 0; left: 0; height: 100%; width: 100%; z-index: 10000;"
></div>
```

**copy of MenuItemLink:**
```js
return (
  <Tooltip
    title={primaryText}
    placement='right'
    PopperProps={{ container: document.getElementById('tooltipsDiv') }} // I added this line
  >
    {renderMenuItem()}
  </Tooltip>
)
```

**Describe the solution you'd like**
1. Modify all MenuItemLink, DashboardMenuItem, AppBar, Tooltip, UserMenu and other component that have Tooltip component to accept PopperProps attribute and forward it to Tooltip component; This will allow us to control tooltips within customized menus and appbars
2. Add a parameter PopperProps to Layout component so that all default appbars, sidebars and menus receive this property

Alternatively, React admin can just create div similar to my example above inside document body and always use this div for tooltip display.

**Describe alternatives you've considered**
Copy/paste code from React-admin and adding PopperProps to each tooltip component

**Comment by panfiva** [comment]
Note that the solution I described above is updating the highlighted DIV when tooltips are shown:

![image](https://user-images.githubusercontent.com/48455289/98411768-46082e80-203c-11eb-80c0-b8b4dd638cc0.png)

**Comment by fzaninotto** [comment]
I don't understand the problem. How can the tooltips create a reflow? They are in position `fixed`.

In my opinion, this is an incompatibility between your CSS and material-ui, so it's either a material-ui problem, or a problem on your side.

**Comment by panfiva** [comment]
I am not sure where this reflow issue happens; Instead of PowerBi report, I tried including an empty container with a border, and I did not see any reflow issues. Also, PowerBi's report exterior border does not change; only inside of PowerBi report changes and then goes back to normal. I suspect that something in PowerBi is trying to reflow for one reason or another.

That being said, the only solutions that I found to work was adding a different container for tooltips (as described above). or using "block" instead of flex containers with fixed size of DIV.

**Comment by fzaninotto** [comment]
I understand your problem. But since it can be fixed in user land (e.g. using material-ui's CSS overrides system) and it's specific to some black magic done by Power BI, we won't be changing anything in react-admin. I don't think the bug is in react-admin ; it's in Power BI.

**Comment by panfiva** [comment]
Well, the only way for me to fix this issue is to fork React-Admin project (or, at the minimum, all components that have tooltips). This is not a very good solution, since it will be a significant effort on our part to maintain a modified copy of components, considering our project is a pure JavaScript project. I was hopping that by allowing us to pass pop-up configurations, we can avoid this.

**Comment by panfiva** [comment]
Using "block" container is not a viable solution for us, since we need an ability to automatically determine chart size to fill available width and height
