### ISSUE TITLE
Run-time error when calling custom data provider method that requires no call arguments, when data provider is retrieved from useDataProvider hook

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#5505]
Imagine a custom method `getPrimaryShopDefaultNavigationTreeId()` is defined on a dataprovider.
then below code will cause a run-time error:
```
const dataProvider = useDataProvider();
const resp = await dataProvider.getPrimaryShopDefaultNavigationTreeId();
```

The error occurs in file getDataProviderCallArguments:
```
var isDataProviderOptions = function (value) {
    var options = value;
    return Object.keys(options).some(function (key) { return OptionsProperties.includes(key); });
};
```
as `options` is undefined.

Workaround is of course to call with a dummy argument (eg `getPrimaryShopDefaultNavigationTreeId({})`) but there should really be no restriction on arguments of custom dp methods.

**Comment by djhi** [comment]
Thanks for the report!

**Comment by fzaninotto** [comment]
I'm marking this as a bug as I believe it used to work and the fix is easy.
