### ISSUE TITLE
DateField incorrectly shows hour as 0 for AM/PM format

### ISSUE THREAD

**Issue by sreenath-n** [marmelab/react-admin#5507]
**What you were expecting:**
DateField should show values between 1 and 12 for hour part when hour12 is true.

**What happened instead:**
DateField shows 0:52 pm for hour part when it should be 12:52 pm

![image](https://user-images.githubusercontent.com/69649218/98659635-5422bb80-236a-11eb-99f2-f66187232a1e.png)

**Steps to reproduce:**
Pass a field containing timestamp (milliseconds since epoch) as the source

**Related code:**

```
<DateField showTime options={{ weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true }} />
```

**Other information:**

**Environment**

* React-admin version: 3.9.5
* React version: 16.14.0
* Browser: Google Chrome 85.0.4183.83 (64-bit) (Ubuntu 20.04)

**Comment by fzaninotto** [comment]
That's… your browser's fault. React-admin relies on [the `Intl` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) for date formatting, and this objects uses your browser preferences.

If there is a bug in [`Date.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString), which uses Intl under the hood, then there is nothing we can do about it in react-admin. I suggest you open an issue in the Chrome bug tracker.
