### ISSUE TITLE
Can dynamic resources depend on user input ?

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#5509]
First, I'm not sure if this is a bug report, a limitation of React Admin that could be a feature request or a "How to". Sorry for the noise in advance.

**What you were expecting:**
Display a custom UI component (the `dashboard`) at start to gather user input so that I can fetch resources afterwards. Resources are dynamic and based on user input. I'm following the doc at https://marmelab.com/react-admin/Admin.html#unplugging-the-admin-using-admincontext-and-adminui

**What happened instead:**
I see the `ready` component "Welcome to React Admin...".

**Steps to reproduce:**
See the code below.

``` javascript
const AsyncServices: React.FC = (props) => {
    // custom hook that fetches some state and a list of services (= resources) from an API
    const [selectedGame, selectedEnv, services] = useVerifiedServices();

    return (
        <AdminUI
            customRoutes={[
                <Route path="/games" exact component={GamesSelector} key="games" />,
                <Route path="/:game/environments" exact component={EnvironmentsSelector} key="games-environments" />,
                <Route path="/error" exact component={ErrorPage} key="error" />,
            ]}
            dashboard={Dashboard} // we expect this to display when loading the route `/`, it does the necessary user input necessary to fetch the resources from the API
            title="TEST"
            loginPage={LoginPage}
        >
            {services : services
                .map(service =>
                    <Resource
                        key={service.serviceID}
                        name={`${selectedGame?.gameID}/${selectedEnv?.envID}/${service.serviceID}`}
                        options={{ label: service.name }}
                        list={ListGuesser} />)
            }
        </AdminUI>
    );
};
```

**Other information:**
As the code stands above, since Dashboard is not displayed, no user input is gathered, hence the `services` variable remains `null` and per the code in [`CoreAdminRouter`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRouter.tsx#L112) if the children of `AdminUI` are neither a function nor an array with some elements in it React Admin fallbacks to the `ready` component`.

We haven't found a way to display a custom component, unless we do some hacky stuff like this :

``` javascript
{services ? services
            .map(service =>
                    <Resource
                        key={service.serviceID}
                        name={`${selectedGame?.gameID}/${selectedEnv?.envID}/${service.serviceID}`}
                        options={{ label: service.name }}
                        list={ListGuesser} />)

            : <Resource name="/dummy" /> // force the display of a fake Resource as a workaround, in this case it seems that our `Dashboard` component is displayed. 
}
```

Basically we need these from React Admin :
- React Admin should work without resources, since the call to our API may return no result
- React Admin should let us display something while the dynamic list of resources is not built yet
- React Admin should let us gather user input before retrieving the list of resources.

If it's possible, then this issue is a How to and I'm sorry for polluting the issue queue, but I'd still love some guidance. It seems like a "corner/advanced" to have resources gated behind user input.
If it could be possible with little changes to React Admin, we may consider contributing if we have some guidance from you.
If this is not possible with React Admin, then it's not the right tool for job, but no drama here :)

**Environment**

"react": "^17.0.1",
"react-admin": "latest"

**Comment by fzaninotto** [comment]
I think you're looking for the `<Admin ready>` prop.

https://marmelab.com/react-admin/Admin.html#ready

**Comment by DjebbZ** [comment]
Indeed, it's been added yesterday and we missed it. `npm update` and we're good to go!

Thanks and sorry again for the noise.
