### ISSUE TITLE
ReferenceInput doesn't inject filter prop to child

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5513]
```js
   // In packages/ra-ui-materialui/src/input/ReferenceInput.spec.tsx 

    it('should pass filter prop to child', () => {
        let gblFilter = {};
        const Component = props => {
            gblFilter = props.filter;
            return <div data-testid="test">Hello</div>;
        };

        render(
            <ReferenceInputView
                {...defaultProps}
                filter={{test: true}}
            >
                <Component/>
            </ReferenceInputView>
        );

        expect(gblFilter).toEqual({test: true});
    });
```

**Environment**
* React-admin version: 3.10.0

**Comment by fzaninotto** [comment]
`ReferenceInput` creates a `ListContext`, and puts the `filter` there. You can grab it by calling `const { filter } = useListContext()`.

Is it breaking a documented feature?

**Comment by WiXSL** [comment]
Thanks, you are right!

`...Is it breaking a documented feature?`

Yes, it breaks the documentation here https://marmelab.com/react-admin/Inputs.html#referenceinput
When saying "`You can tweak how this component fetches the possible values using the perPage, sort, and filter props.`" plus the below examples where `filter` prop is being used.

```jsx
// you can filter the query used to populate the possible values. Use the
// `filter` prop for that.
<ReferenceInput
     source="post_id"
     reference="posts"
     filter={{ is_published: true }}>
    <SelectInput optionText="title" />
</ReferenceInput>

**Comment by fzaninotto** [comment]
Well, passing a `filter` prop to `<ReferenceInput>` does work, right? But it's not passed down to `<SelectInput>`, which is normal.

Your issue mentions `<ReferenceInputView>`, which is an internal API so I don't think we broke anything.

**Comment by WiXSL** [comment]
I've use `ReferenceInputView` in the test by copying from another one of your tests. And I assume you did this because is simpler for the tested features, either way you might be right about this.

**Comment by kuuneko** [comment]
I think this is related, in the latest update the `sort` field no longer works on `ReferenceInput`, I had to downgrade to keep that functionality.

**Comment by fzaninotto** [comment]
Closing as we only changed an internal API - the public API remains unchanged.
