### ISSUE TITLE
 ReferenceError: setImmediate is not defined 

### ISSUE THREAD

**Issue by rodbs** [marmelab/react-admin#5516]
**What you were expecting:**
To get it working without errors

**What happened instead:**
It kind of works but I'm getting this error:

`ReferenceError: setImmediate is not defined`
 

**Steps to reproduce:**
 
I'm running react-admin under nextJs 10.0.1. With the previous version of react-admin (3.9.5) I didn't experience any problems

**Related code:**
 
```
const DynamicReactAdmin = dynamic(
  () => import("@/components/reactadmin/ReactAdmin"),
  {
    loading: () => <p>Loading ...</p>,
    ssr: false,
  }
)
```

**Other information:**

**Environment**

* React-admin version: 3.10.0
* Last version that did not exhibit the issue (if applicable): 3.9.5
* React version: 17.0.0 
* Browser: Chrome
* Stack trace (in case of a JS error):
 
```
next-server\lib\loadable.js (270:42) @ <unknown>

  268 |       ...partial,
  269 |     }
> 270 |     this._callbacks.forEach((callback) => callback())
      |                                          ^
  271 |   }
  272 | 
  273 |   _clearTimeouts() {
```

**Comment by aiji42** [comment]
I get the same error in my environment.
## Environment
- React-admin version: 3.10.0
- Last version that did not exhibit the issue (if applicable): 3.9.6
- React version: 16.13.1
- Next.js version: 9.5.5
- Browser: Chrome

**Comment by fzaninotto** [comment]
Thanks for the report!
