### ISSUE TITLE
Data Provider getList get array of Objects, but List Component doesn't show it

### ISSUE THREAD

**Issue by YuripzEdata** [marmelab/react-admin#5518]
**What you were expecting:**
as described  by documentation, the simplest React App was prepared:
*App.tsx*
```
    return (
        <Admin dataProvider={dataProvider} dashboard={Dashboard} title={'Dashboard'}>
            <Resource  name="MessageDirections" list={MessageDirections}>
            </Resource>
        </Admin>
  );
```
*MessageDirections.tsx*
```
export const  MessageDirections = (props: any) => {
    return (
            <List aside={<Aside />} { ...props } title={"Datagrid"} perPage={5} >
                <Datagrid>
                    <NumberField source="id" />
                    <DateField source="Last_Update_Dt" />
                    <TextField source="Msgdirection_Cod" />
                    <TextField source="Msgdirection_Desc" />
                    <NumberField source="Num_Thread" />
                </Datagrid>
            </List>
        );
};
```
Component *<Aside/>* was used for additional checking data response from  Data Provider ( via console.log ) :
```
const Aside = () => {
    const { data, ids } = useListContext();
    console.log( "useListContext()=data: ", data);
    console.log( "useListContext()=ids: ", ids.length);
. . .
};
```
**What happened instead:**

![изображение](https://user-images.githubusercontent.com/74334172/98886231-af58c900-24a4-11eb-987d-5377bc441ffd.png)

**Steps to reproduce:**

**Related code:**
* A link to a GitHub repo with the minimal codebase to reproduce the issue
https://github.com/YuripzEdata/react-admin-case-5518

```
dataProvider.getList('MessageDirections',
        { pagination: { page: 1, perPage: 5 },
                  sort: { field: 'Msgdirection_Cod', order: 'ASC' },
                  filter: { msgdirection_cod: 'ONLINE' }
            }
        )
        .then(  response => {
                    console.log("response.data isArray=", Array.isArray(response.data) );
                    console.log(response.data);
                     console.log("response");
                    validateResponseFormat(response, 'getList');
                if ( Array.isArray(response.data) )
                    console.log( 'data.length=', response.data.length);
                }
             );
```
Data Provider getList return *Json* : Array of 5 oblects, browser console show its.
```
response.data isArray= true 
(5) […]
​
0: Object { Long_Retry_Count: 0, Num_Helpers_Thread: 0, Wsdl_Name: "http://center.tgrad:80/DatumNode/DatumNode.svc/basic", … }
​1: Object { Long_Retry_Count: 5, Num_Helpers_Thread: 0, Wsdl_Name: "http://10.36.130.74:5201/WsBridge", … }
​2: Object { Num_Helpers_Thread: 0, Wsdl_Name: "http://center.tgrad:80/DatumNode/DatumNode.svc/basic", Type_Connect: 3, … }
​3: Object { Long_Retry_Count: 5, Num_Helpers_Thread: 0, Wsdl_Name: "http://center.tgrad:80/DatumNode/DatumNode.svc/basic", … }
​4: Object { Num_Helpers_Thread: 0, Wsdl_Name: "http://10.28.88.241:80/CMS_B2B/additional/wservice.nsf/WsHermesAPI/", Type_Connect: 3, … }

length: 5
​
<prototype>: Array []
:96
response :97
data.length= 5 :99
```

**Other information:**

**Environment**

* React-admin version: 3.10
* React version: 17.0.1 ( DISABLE_NEW_JSX_TRANSFORM=true )
* Type Script : 4.0.3
* Browser: Firefox 82.0.2
* Stack trace (in case of a JS error): no  JS error

**Comment by YuripzEdata** [comment]
Also,
when jsonServerProvider is used, 
`const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');` - all work fine,  as disigned.
 Problems was happening with custom , myDataProvider 
`const dataProvider = myDataProvider("http://localhost:8008/HermesService/InternalRestApi/apiSQLRequest");`

The same code via *jsonServerProvider* return the same result as *myDataProvider*
```
    dataProvider.getList('users',
        { pagination: { page: 1, perPage: 5 },
                  sort: { field: 'username', order: 'ASC' },
                  filter: { msgdirection_cod: 'ONLINE' }
            }
        )
        .then(  response => {
                    console.log("response.data isArray=", Array.isArray(response.data) );
                    console.log(response.data);
                     console.log("response");
                    validateResponseFormat(response, 'getList');
                if ( Array.isArray(response.data) )
                    console.log( 'data.length=', response.data.length);
                }
             );
```
```
response.data isArray= true 
(5) […]
0: Object { id: 2, name: "Ervin Howell", username: "Antonette", … }
1: Object { id: 1, name: "Leanne Graham", username: "Bret", … }​
2: Object { id: 9, name: "Glenna Reichert", username: "Delphine", … }
3: Object { id: 7, name: "Kurtis Weissnat", username: "Elwyn.Skiles", … }
4: Object { id: 5, name: "Chelsey Dietrich", username: "Kamren", … }
​
length: 5
```

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
