### ISSUE TITLE
Using <Create> for a different resource inside <Show>

### ISSUE THREAD

**Issue by timotgl** [marmelab/react-admin#5521]
We recently upgraded our project from react-admin 3.8 to 3.10.0 and noticed that using the `<Create>` component for other resources than the current one doesn't seem to work anymore.

In our case, we're on a route like `resource_a/<someid>/show` rendered by a <Show> component. Then somewhere deeper in the component tree we have a form that is supposed to create a resource `resource_b` by using the `<Create>` component:

```
<Show>
  ...lots of nested components here showing details of the resource_a...
    <Create basePath={'/resource_b'} resource="resource_b">
      <SimpleForm>...</SimpleForm>
    </Create>
</Show>
```

This results in the dataProvider trying to create a `resource_a` (through GraphQL), which of course doesn't work because the form inputs belong to a `resource_b` record we'd like to create.

I'm aware that passing `basePath` and `resource` props to the `<Create>` component like that might not be the officially supported way of doing things - however this has worked fine in many places in our codebase up until now.

If what we're doing here is just entirely wrong, what is the recommended way to show a form to create a different resource? Was passing `basePath` and `resource` props manually just never really supported but only recently stopped working?

**Comment by fzaninotto** [comment]
Hi Tim, and thanks for your report.

Using Create as anything other than a page controller was never an expected (or supported) feature, which explains that we didn't even test it while refactoring the create logic in 3.10. Sorry that it breaks your app.

The good news is: you can restore the previous behavior by wrapping your Create component inside a `ResourceContextProvider`:

```diff
<Show>
  ...lots of nested components here showing details of the resource_a...
+ <ResourceContextProvider value="resource_b">
-   <Create basePath={'/resource_b'} resource="resource_b">
+   <Create basePath={'/resource_b'}>
      <SimpleForm>...</SimpleForm>
    </Create>
+ </ResourceContextProvider>
</Show>
```
