### ISSUE TITLE
Typescript compliation error (has no exported member: ts2305)

### ISSUE THREAD

**Issue by vikeri** [marmelab/react-admin#5529]
**What you were expecting:**
TypeScript compliation without errors

**What happened instead:**
Complier error: 
```
Module '"../../../node_modules/react-admin/lib"' has no exported member 'List'.ts(2305)
```

**Steps to reproduce:**
1. Have existing TypeScript project
2. Upgrade from react-admin 3.7 -> 3.10
3. `rm -rf node_modules`
4. `yarn`
4. Compile project: `yarn start`

**Related code:**
```ts
import { List, Datagrid, TextField } from 'react-admin'
````

**Other information:**

**Environment**

* React-admin version: 3.10.0
* Last version that did not exhibit the issue (if applicable): 3.7
* React version: 16.9 (Also tried 17.0 with same error) (using create-react-app)
* Browser: Brave
* Stack trace (in case of a JS error):
```
Module '"../../../node_modules/react-admin/lib"' has no exported member 'List'.ts(2305)
```

**Comment by djhi** [comment]
Please double check your yarn.lock and ensure all react-admin packages are up to date and without duplicates

**Comment by vikeri** [comment]
All of the `ra-` packages as well as `react-admin` itself points at `3.10.0`

**Comment by vikeri** [comment]
Hmm it seems that it does find some symbols. `useNotify` is found for example.

**Comment by vikeri** [comment]
Very strange, some symbols are found while others aren't. Seems to mostly be an issue with the components: 
<img width="189" alt="bild" src="https://user-images.githubusercontent.com/846688/99079456-48c8cd80-25c0-11eb-957a-8286f309d0bb.png">

**Comment by vikeri** [comment]
My bad, I had marked the `ra-ui-materialui` package as untyped...
