### ISSUE TITLE
Feature request: document the role of the `id` field in records better

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#5530]
**Is your feature request related to a problem? Please describe.**
While implementing a dataProvider with a fake `getOne` and a real `getList`, it took us a few hours to realize that our fake result from `getOne` was wrong. We expected our fake data to be displayed in the `show` page after clicking a row from the `list` page, instead we got a blank page. No useful results or messages appeared in the UI or in the console, apart from a cryptic `warning: You cannot change <Router history>` that looked completely unrelated since we never changed it and never re-render the app component (the one with `Admin` or in our case `AdminContext`) as mentionned in this [issue](https://github.com/marmelab/react-admin/issues/4998#issuecomment-653424456).

**Describe the solution you'd like**
It seems that the `id` field in the URL of the `show` page must match the record that comes from the `getOne` or weird things happen. This field seems super important. 
I'd like to see at least better docs about the role of the `id` field in the records. After looking quickly it seems this place is ideal https://marmelab.com/react-admin/DataProviders.html#response-format. Below the table is a sentence saying that each `Record` must have an `id` field.

**Describe alternatives you've considered**
I was about to open an issue about the React router problem...

**Additional context**
Using react-admin 3.10.0.

**Comment by fzaninotto** [comment]
Hi @DjebbZ, and thanks for your report.  That's a very strange use case - I'm not sure we want to address it in the documentation. 

Besides, I think documentation isn't the right solution to fix the problem. The documentation is already very large, and people will have a hard time looking for the sentence you've added. 

A better solution would be to check the fetched `data` in `useEditController` and `useShowController`, and throw a meaningful Error if the `id` isn't the expected one. 

Would you like to work on that change?

**Comment by DjebbZ** [comment]
I get it. I may give it a try in the next few days.

**Comment by WiXSL** [comment]
Fixed by #6898

**Comment by DjebbZ** [comment]
By now I'm comfortable with the role of the id field but hey cool to see the issue addressed!
