### ISSUE TITLE
Need an easy way to allow reordering items in SimpleFormIterator

### ISSUE THREAD

**Issue by audunhalland** [marmelab/react-admin#5537]
**Is your feature request related to a problem? Please describe.**
The SimpleFormIterator does not allow reordering of items, and there seems to be no supported way to easily make this kind of extension yourself, without pulling in a drag'n'drop-library and reimplement SimpleFormIterator. Instead I want an extension that allows me to add move up/down buttons (using react-final-form's _move_ API)

**Describe the solution you'd like**
I looked at SimpleFormIterator's `Remove`-button and started to think a little bit about how that button could be generalized into Actions (like those in e.g. Show). Let's imagine a new SimpleFormIterator property: `itemActions?: ReactElement`.

The element receives properties akin to this:
```
  source?: string;
  record?: Record;
  index?: number;
  onRemove?: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  disableRemove?: boolean;
  disableMoveUp?: boolean; // true when it's the first element
  disableMoveDown?: boolean; // true when it's the last element
  removeButton?: ReactElement; // Element received through SimpleFormIterator.removeButton
```
When `itemActions` is unspecified, it defaults to the react-admin-internal `DefaultItemActions`, which just draws the remove button, like before. No change.

You could now create your own ItemActions, replacing the remove Button, instead creating something like a drop-down menu with three different actions for remove, move up and move down.

```
<SimpleFormIterator itemActions={<MyItemActions />} />
```
itemActions will use React.cloneElement, the pattern used over large parts of react-admin.

**Describe alternatives you've considered**
The alternative is completely changing the SimpleFormIterator UI for all react-admin users.
I've read older bug reports and understand that react-admin won't depend upon drag'n'drop, and that's completely fine.
Using more action buttons is a much simpler alternative, but there are two problems:
1. I'm no designer and have little clue how to make this feature work intuitively for all react-admin users (I can, however, accept under-par UX in my own react-admin based app 😬 )
2. Adding completely new actions to react-admin requires extending the set of translation keys, which could be considered API-breakage

**Additional context**
There is no need for screenshots because this is just an API extension, no change in UI.

I've implemented this feature in a local react-admin branch. Just wanted to check what you guys think.

**Comment by fzaninotto** [comment]
Hi @audunhalland, and thanks for writing this request.

The core team doesn't have the need you describe, and therefore won't be working on implementing a reordering feature in SimpleFormIterator. Feel free to develop a third-party package for it, and if you feel like sharing it with other developers, please open a PR on the Inputs documentation when it's done!

**Comment by audunhalland** [comment]
If I made a PR that allows replacing the remove Button, as described, would it be impossible to accept it?

**Comment by fzaninotto** [comment]
Sorry, I didn't see this PR and it didn't mention the current issue. I can't find it on GitHub (see https://github.com/marmelab/react-admin/pulls?q=is%3Apr+author%3Aaudunhalland). Could you point me to your PR?
