### ISSUE TITLE
getSource's type of FormDataConsumerRenderParams interface

### ISSUE THREAD

**Issue by etienne-bondot** [marmelab/react-admin#5539]
Hi, 

This is not a "bug" but I was wondering why and how the `getSource` type of the `FormDataConsumerRenderParams` interface could be undefined ?

**What you were expecting:**
I'm expecting the `getSource` method not to be undefined and so properly typed so Typescript won't be mad about it.

**What happened instead:**
The `getSource` method could be undefined and Typescript is mad.

![image](https://user-images.githubusercontent.com/2827929/99259654-9d678500-281a-11eb-84a4-4014d83b3888.png)

**Related code:**
```
export interface FormDataConsumerRenderParams {
    formData: any;
    scopedFormData?: any;
    getSource?: (source: string) => string;
}
```

**Environment**

* React-admin version: 3.9.6
* Typescript version: 4.0.5

**Comment by djhi** [comment]
It can happen when not used inside an iterator component (not inside an `ArrayInput` for example). See https://github.com/marmelab/react-admin/blob/5cbe7a2029/packages/ra-core/src/form/FormDataConsumer.tsx#L90

Indeed, you don't need to call the `getSource` function when not inside an iterator component. Not sure how we can make TS happy about it without having two different `FormDataConsumer` components.

**Comment by etienne-bondot** [comment]
@djhi Why not just returning the source when not in an iterator ?

```
    if (typeof index !== 'undefined') {
        scopedFormData = get(formData, source);
        getSource = (scopedSource: string) => {
            getSourceHasBeenCalled = true;
            return `${source}.${scopedSource}`;
        };
        ret = children({ formData, scopedFormData, getSource, ...rest });
    } else {
       getSource = () => {
            getSourceHasBeenCalled = true;
            return `${source}`;
        };
        ret = children({ formData, getSource, ...rest });
    }
```

This seems more consistent and understandable in my opinion
