### ISSUE TITLE
The example of using function as admin child stuck in permanent loading state

### ISSUE THREAD

**Issue by Xeizzeth** [marmelab/react-admin#5545]
**What you were expecting:**
The example is being useful.  

**What happened instead:**
Stuck in permanent loading state.  

**Steps to reproduce:**
Use the code from the tutorial, then use your api, or whatever else api (jsonplaceholder also suffice) in dataprovider.

**Related code:**
```
import * as React from "react";
import { Admin, Resource, ListGuesser } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const knownResources = [
    <Resource name="users" list={ListGuesser} />,
    <Resource name="posts" list={ListGuesser} />,
    <Resource name="comments" list={ListGuesser} />,
];

const fetchResources = permissions =>
    fetch('http://localhost:8888//admin/fetch_resources', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(permissions),
    })
    .then(response => response.json())
    .then(json => knownResources.filter(resource => json.resources.includes(resource.props.name)));

const App = () => (
    <Admin dataProvider={
        jsonServerProvider('https://jsonplaceholder.typicode.com')
}>
        {fetchResources}
    </Admin>
);

export default App;
```

**Other information:**
The continuation of dataprovider bug of admin expecting "options" property from dataprovider.  

**Environment**

* React-admin version: 3.10.1
* Last version that did not exhibit the issue (if applicable): 3.10.1
* React version:16.14.0
* Browser:Firefox
* Stack trace (in case of a JS error):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://myapi/resources. (Reason: CORS request did not succeed). 2
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

**Comment by Xeizzeth** [comment]
Update:  
Still stuck but now it can't fetch options, for get nor post methods.  
How should I fetch it? For my API. And what API should return in order for fetched resources to work?

**Comment by fzaninotto** [comment]
Looking at the error you're pasting, it seems your server doesn't allow [CORS requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) on that route. This is a server problem, not a client problem. so I'm closing the issue. 

Feel free to reopen it if you can demonstrate that the problem comes from react-admin (e.g. by providing a link to a [CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) reproducing the problem).

**Comment by Xeizzeth** [comment]
Sorry. Forgot to said anything related to the errorstack. I solved it before I even added the second comment. But anyway - the problem is irrelevant now, since it's solved the different way.
