### ISSUE TITLE
The `variant` prop of React Admin's `TextInput` has no effect in FilterForm

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#5550]
**What you were expecting:**
Use an alternative look and feel for the `TextInput`, based on the doc of [Material-UI `TextField`](https://material-ui.com/components/text-fields/#textfield). Specifically using the `outlined` or the `standard` value of `variant` should produce the expected visual result.

**What happened instead:**
Whatever the value passed to the `variant` prop, the component always uses displays using the default `filled` variant.

**Steps to reproduce:**
Use `variant="outlined"` or `variant="standard"` on any `TextInput`.

**Related code:**
In https://codesandbox.io/s/laughing-smoke-2fics?file=/src/posts/PostList.js I added the `variant` props to the filters components.

``` jsx
<TextInput variant="outlined" {...} />
```

**Other information:**
Pause the debugger inside the devtools inside the `TextInput` source code. For whatever reason `props.variant` is always `undefined`!

**Environment**

* React-admin version: 3.10.0
* React version: 16.9.56
* Browser: Chromium 86.0.4240.198

**Comment by fzaninotto** [comment]
Confirmed and reproduced, thanks. 

The bug only happens in the FilterForm though.

**Comment by DjebbZ** [comment]
Thanks again for your reactivity!

Does it mean the fix will make it to the next release?

**Comment by fzaninotto** [comment]
Yep! Check [the milestones page](https://github.com/marmelab/react-admin/milestones) for a rough idea of the release date of the next milestone.
