### ISSUE TITLE
Extend ` ra-data-grapql` so it can support GQL APIs that do not have operations for plural verbs

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#5552]
Currently the package requires that each RA verb has a corresponding GQL operation, e.g.
[GET_ONE] -> `tag`
[GET_LIST] -> `allTags`

What if we have an API that does not support a multi-verb operation to implement `GET_LIST`, `GET_MANY`, `DELETE_MANY` etc. Then the only way to support is with multiple GQL queries or mutations. But this is not supported by this package currently.

We have extended it in a backward compatible way to support this: if specifying `queries` instead of `query` in your `buildQuery.ts` file for a given verb & resource, then our customized package will issue multiple GQL mutations or queries, and `parseResponse` will receive an array of each of the responses.

eg assume you have DELETE as follows in `buildQuery.ts` for a resource named `Tag` : 
```
const input: TRemoveTagInput = {
  id: params.id,
  shopId,
};
return {
  query: gql`
    mutation ($input: RemoveTagInput!) {
      data : removeTag(input: $input) {
        tag {
          ${resourceFieldList}
        }
     }
  }`,
  variables: {
    input,
  },
  parseResponse: (resp: any) => {
    const { tag } = deepCloneWithoutTypename(resp.data.data);
    return {
      data: deep_id2id(tag),
    };
  }
};
```

Then, if the API does not support a plural `removeTags`, we can instruct the package to use multiple singular calls as follows to implement `DELETE_MANY` 
(note the use of `queries` instead of `query`, and `variables` now is an array of the input required for each call:

```
const variables: Array<{ input: TRemoveTagInput }> = (params.ids as string[]).map((id: string) => ({ input: { id, shopId } }));
 return {
  queries: gql`
    mutation ($input: RemoveTagInput!) {
      data: removeTag(input: $input) {
        tag {
          _id
        }
     }
   }`,
   variables,
   parseResponse: (arrResp: any[]) => {
       const ids = arrResp.map(resp => resp.data.data.tag._id);
       return { data : ids };
   }
};
```

Of course you also need to specify in your `introspectionResults` options to use the singular operation for `DELETE_MANY`:
```
const introspection = {
      // ...
        [DELETE_MANY]: (type: { name: string }) => {
          // will use multiple DELETE operations
          if (type.name === 'Tag') {
            return `remove${type.name}`;
          }
      // ...
}
```

Note that this builds on:
https://github.com/marmelab/react-admin/issues/4933#issue-637353639 
which allows a resource to be included even when it is missing a verb by using a whitelist, which was meanwhile included. However the package as-is cannot be used if you cannot implement each RA verb by a single GQL call.

If you believe this is useful to include, we can send a PR.

**Comment by fzaninotto** [comment]
This enhancement request hasn't gained enough interest to get a PR from the community. As we canot keep all feature requests open, I'm closing it. 

If you feel like working on this feature, we'd love a PR!
