### ISSUE TITLE
Can't use custom routes if no resources are available

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5562]
CodeSandBox: https://codesandbox.io/s/elated-http-x1hxd?file=/src/index.js

1. Go to the Login page
2.  Uncomment line 33 of `index.js` file, and comment line 34
3. Click on `Redirect to Custom Route` button on Login page

Expected behavior:
- You get redirected to `/customroute` and `CustomRouteNoLayout` component is rendered

Actual behavior:
- You get the `LoadingPage` component

My use case is an admin with dynamically loaded resources.
When standing in login page and going to a custom route, no resources are loaded, since I'm not logged in.
But still should be able to go to a custom route like "forgot password" or "contact form"

**Comment by fzaninotto** [comment]
That's an interesting use case. We don't have it, but it'd be nice to have react-admin support that. @djhi marked it as an enhancement, feel free to submit a PR to implement it.

**Comment by WiXSL** [comment]
Ok, I see what I can do

**Comment by WiXSL** [comment]
This is now cover in `react-admin` v4  By using `<CustomRoute noLayout>` right?

**Comment by djhi** [comment]
It was already possible with custom routes in v3. I implemented such cases on several projects.
