### ISSUE TITLE
[Support] <SaveContextProvider> deprecated-message of React-Admin

### ISSUE THREAD

**Issue by tanpld** [marmelab/react-admin#5563]
I have this message in the Chrome console since I updated react-admin to version 3.10.0, I tried to dig into the document but can't find any information or example. Anyone encounter this, or luckily any members of react-admin seeing this, please help!
```
Edit or Create child components must be used inside a <SaveContextProvider>. Relying on props rather than context to get persistence related data and callbacks is deprecated and won't be supported in the next major version of react-admin.
```

**Comment by djhi** [comment]
Are you using custom Create or Edit components ?

**Comment by kaluohena** [comment]
I am using the custom Edit component and get the same warning.

**Comment by tanpld** [comment]
> Are you using custom Create or Edit components ?

Yes, custom one

**Comment by djhi** [comment]
Reproduced. Thanks
