### ISSUE TITLE
MenuItemLink route forming

### ISSUE THREAD

**Issue by Xeizzeth** [marmelab/react-admin#5564]
**What you were expecting:**
Link to the resource is staying the same when clicking on the resource multiple times.

**What happened instead:**
Link prepending the first part of itself, apart of ID.

**Steps to reproduce:**
I use custom menu with custom layout.  
And I use routing with the pattern [http://myserver/admin/some_resource/\<id\>](http://myserver/admin/some_resource/1)  
Where id is an int of id of an object in the database.
And I form the MenuItemLink this way:  
```
    const formElements = (props: GeneratedProps) => {
        // const lololo = fetchStationComponents()
    
        // console.log(lololo);
    
        const { data, total } = state.stations_info;
 
        let render_items = []
    
        for (var item of data) {
            render_items.push(<MenuItemLink
                key={`${item.id}`}
                to={`${item.route}`}
                primaryText={item.name}
                leftIcon={<DashboardIcon />}
                onClick={props.onMenuClick}
                sidebarIsOpen={props.open}
                dense={props.dense}
            />)
        }
    
        return (
                <div>
                    {render_items.map(item => item)}
                </div>
        )
    }
```
"to" is the route that looks like "some_resource/\<id\>" as you can guess.

But if you click on this item, that works with that route, in the menu multiple times, it will start prepending "some_resource" at the route, so it will begin to look something like this: http://localhost:3000/#/some_resource/some_resource/some_resource/some_resource/some_resource/some_resource/1  

**Related code:**
Above. If necessary I can provide any other snippets.  

**Other information:**
I'm almost sure it's a bug within the react-admin itself, since the problem lies, or could like only in lower levels, as I see it.  
I basically form an array of MenuItemLinks which I then push to render.  

**Environment**

* React-admin version: 3.10.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.14.0
* Browser: Mozilla Firefox
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by Xeizzeth** [comment]
https://codesandbox.io/s/jovial-elion-vkpwz

**Comment by fzaninotto** [comment]
The MenuItemLink delegates rendering of links to react-router's NavLink, so the problem doesn't come from react-admin.

You codesandbox is full of offending content and we won't look at it. 

I'm closing this issue and banning you from this repo, because I don't want to read anything from you ever again.
