### ISSUE TITLE
"Associated reference no longer appears to be available." in ReferencInput when selecting a value that has '/' in it

### ISSUE THREAD

**Issue by ash1f** [marmelab/react-admin#5571]
Im using` react-admin-firebase` to pull some data and basically a dashboard for CRUD

So whenever a value has a '/' in the ReferenceInput (see code below) it throws "Associated reference no longer appears to be available." 
See following code snippet

          
 
```
<ReferenceInput
   label="Interface"
   source="interface"
   reference="mounting"
>
   <SelectInput
      required
      variant="outlined"
      source="interface"
      optionText="name"
      optionValue="name"
  />
</ReferenceInput>
```

and my firebase data array looks like this;

```
{
name: "3/8 inch"
refId : "M0016"
},
{
name: "9 inch"
refId : "M0017"
}
```

 the second on works but the first one throws error due to the '/' in the name field

**Note:** Im using the name as the value, because it's necessary

* React-admin version: ^3.x
* Last version that did not exhibit the issue (if applicable): --
* React version:16.13.0
* Browser: All
* Stack trace (in case of a JS error): "Associated reference no longer appears to be available."

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
I guess this is a problem with the react-admin-firebase dataProvider, which is maintained by another organization. 

Unless you can prove that the bug exists with another dataProvider (like te one in the CodeSandbox), please open an issue in https://github.com/benwinding/react-admin-firebase instead.

**Comment by ash1f** [comment]
Yep. couldn't recreate this issue in the sandbox. Seems like a problem in the dataProvider of  `react-admin-firebase`. I'll close this for now. Thank you.
