### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by capJavert** [marmelab/react-admin#5572]
I was wondering does [application level cache](https://marmelab.com/react-admin/Caching.html#application-cache) gets invalidated on `create/update/delete` dataProvider calls?
 
For example If we use `cacheDataProviderProxy` mentioned in the link above does `validUntil` param automatically gets invalidated when for example `update` action occurs or we need to implement that separately?

Thanks!

**Comment by fzaninotto** [comment]
It's your responsibility to return a response to `dataProvider.update()` and `dataProvider.create()` which contains an updated `validUntil` data. React-admin will update the application cache accordingly.

As for the `dataProvider.delete()`, if the response is successful, react-admin removes the result from the cache automatically.
