### ISSUE TITLE
ReferenceField ignores emptyText prop

### ISSUE THREAD

**Issue by fvoordeckers** [marmelab/react-admin#5573]
**What you were expecting:**
Other fields like TextField allow an emptyText prop to pass a text value to render when the prop is empty or does not exist on the record. Would expect the same result for a ReferenceField when the source passed to the ReferenceField is empty on the record.

**What happened instead:**
The field rendered an empty value.

**Steps to reproduce:**

1. Add a ReferenceField to a show view or a list with an emptyText prop.
2. Add a record without the reference value

**Related code:**
```
<ReferenceField label="Parent" source="parentId" reference="categories" emptyText="-">
    <TextField source="name" />
 </ReferenceField>
```

**Other information:**

**Environment**

* React-admin version: 3.8.2

**Comment by fzaninotto** [comment]
`emptyText` was introduced in #4413 by a member of the community. It seems they forgot the ReferenceField...
