### ISSUE TITLE
Regression: Update notification doesn't show up anymore

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#5580]
**What you were expecting:**

After saving updates to an Edit form, a snackbar should show up with "Element updated"

**What happened instead:**

The snackbar doesn't show up

**Steps to reproduce:**

1. Go to Post List
2. Click on a Post
3. Update the title
4. Click on Save
5. Where is the notification? 

**Related code:**

Reproducible on the default CodeSandbox https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Other information:**

**Environment**

* React-admin version: master (3.10.2)
* Last version that did not exhibit the issue (if applicable): 3.9.6
* React version: 17.0
* Browser: Chrome

**Comment by djhi** [comment]
Probably related to https://github.com/mui-org/material-ui/issues/23215
