### ISSUE TITLE
Improve FilterListItem so it can work with APIs that have nested filter keys

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#5585]
Some API's may have nested keys, eg instead of 
```
filter: {
    last_seen_gte: ...
    last_seen_lte: ...
}
```
something like:
```
filter: {
     last_seen: {
       gte:...
       lte: ...
     }
}
```

Also you could have APIs that have nested arrays to allow filtering on a number of enum values, e.g.:
```
filter: {
   orderStatus: ['new', 'processing']
}
```
While the current FilterList does not allow multiple selections within a group, at least it could support this syntax for 1 selection:
```
filter: {
   orderStatus: ['new']
}
```

The current component does not work in any of these cases because of the way it determines the active selection in `FilterListItem`. I suggest the small change below, which is backward compatible, to allow operation with nested keys/arrays:
```
  // THIS DOESN'T WORK FOR NESTED KEYS
  // const isSelected = Object.keys(value).reduce(
  //   (acc, key) => acc && value[key] == filterValues[key], // eslint-disable-line eqeqeq
  //   true
  // );

  // REPLACED BY, based on: https://stackoverflow.com/questions/13142968/deep-comparison-of-objects-arrays
  const isSelected = Object.keys(value).reduce(
    (acc, key) => acc && JSON.stringify(value[key]) === JSON.stringify(filterValues[key]), // eslint-disable-line eqeqeq
    true
  );
```

**Comment by djhi** [comment]
This is the job of the `dataProvider`, responsible for translating react-admin objects to your API "dialect"
