### ISSUE TITLE
Update ra-tree-ui-materialui readme to point to Enterprise Edition ra-tree

### ISSUE THREAD

**Issue by zhicong** [marmelab/react-admin#5590]
**Is your feature request related to a problem? Please describe.**
I was trying to implement drag and drop reordering in a List, and a Google search directed me to the [ra-tree-ui-materialui package](https://www.npmjs.com/package/ra-tree-ui-materialui).

I spent several hours trying to implement it, before finally stumbling upon a Github issue thread that said it has been replaced by ra-tree in the Enterprise Edition, and no longer supported in React Admin v3.

**Describe the solution you'd like**
Seems like a missed opportunity to plug the Enterprise Edition, while also clearing up confusion around packages. Could the ra-tree-ui-materialui package be updated to say that it is no longer supported in v3, and to upgrade to Enterprise to use ra-tree instead?

**Comment by fzaninotto** [comment]
Hi, and sorry you lost some time on the old tree package...

Installing ra-tree-ui-materialui in a react-admin 3.x project should raise many warnings about missing peerDependencies, am I right? I think these should be enough to warn developers.

I'm reluctant to update (and republish) such an old package just to explain that it's not supported by future versions of react-admin, when the package.json already does it... And also, people still using react-admin 2.x don't need to see that warning. 

So I'm going to close this issue, hoping that it won't cost too much time to developers like you.

Thanks for the report anyway!
