### ISSUE TITLE
Multiple ListBase components on the same page using the same paging state, resulting in unwanted API calls

### ISSUE THREAD

**Issue by dejancg** [marmelab/react-admin#5596]
I have this iterator component which allows selecting IDs from a referenced resource table and using these in an `ArrayInput`:
```ts
import React, { useEffect, useCallback, useRef } from "react";
import { FieldArrayRenderProps } from "react-final-form-arrays";
import {
  Record,
  ListBase,
  Datagrid,
  Pagination,
  ResourceContextProvider,
  Identifier,
  useListContext,
} from "react-admin";
import { Card } from "@material-ui/core";
import { difference } from "lodash";
import { useForm } from "react-final-form";

interface Props extends Partial<FieldArrayRenderProps<any, HTMLElement>> {
  reference: string;
  children: React.ReactNode;
  record?: Record;
  source?: string;
}

interface SelectedItemsHandlerProps extends Partial<Props> {
  handleSelectedItems: (ids: Array<Identifier>) => void;
}

const SelectedItemsHandler = ({
  handleSelectedItems,
  record,
  source,
}: SelectedItemsHandlerProps) => {
  const form = useForm();
  const { selectedIds, onSelect } = useListContext();
  const effectCount = useRef<number>(0);
  useEffect(() => {
    handleSelectedItems(selectedIds);
  }, [selectedIds, handleSelectedItems]);

  useEffect(() => {
    // Effect to set the initial selected items based on the editing record
    if (!record) {
      return;
    }

    if (!source) {
      return;
    }

    effectCount.current++;
    if (effectCount.current > 1) {
      console.error(
        "This effect of ListInput.SelectedItemsHandler should only run once!"
      );
      return;
    }

    onSelect(record[source] ?? []);

    // onSelect will trigger handleSelectedItems and make the form dirty, when in reality it should be pristine. So call reset()
    form.reset();
  }, [record, source, onSelect, form]);
  return null;
};

export const ListIterator = ({
  fields,
  reference,
  record,
  source,
  children,
}: Props) => {
  const handleSelectedItems = useCallback(
    (ids: Array<Identifier>) => {
      if (!fields) {
        console.warn("fields was undefined in ListInput.handleSelectedItems");
        return;
      }

      const toAdd = difference<Identifier>(ids, fields.value);
      const toRemove = difference<Identifier>(fields.value, ids);

      const indicesToRemove = [];
      for (const item of toRemove) {
        const index = fields.value.indexOf(item);
        if (index === -1) {
          console.warn(
            `Tried to remove the item '${item}', but it was not found in fields.value`,
            { currentValues: fields.value }
          );
          continue;
        }

        indicesToRemove.push(index);
      }

      // Sort in descending order to remove items in one go and avoid multiple effects
      indicesToRemove.sort((a, b) => b - a);
      for (const index of indicesToRemove) {
        fields.remove(index);
      }

      for (const item of toAdd) {
        fields.push(item);
      }
    },
    [fields]
  );

  return (
    <ResourceContextProvider value={reference}>
      <ListBase resource={reference} basePath={`/${reference}`}>
        <SelectedItemsHandler
          handleSelectedItems={handleSelectedItems}
          fields={fields}
          record={record}
          source={source}
        />
        <Card>
          <Datagrid hasBulkActions>{children}</Datagrid>
          <Pagination />
        </Card>
      </ListBase>
    </ResourceContextProvider>
  );
};
```

It can be used in `ArrayInput`, for example like this (editing a form field called "selectedPeople" using a reference to "people" resource):
```ts
<ArrayInput source="selectedPeople" label="">
  <ListIterator reference="people">
    <TextField source="firstName" />
    <TextField source="lastName" />
  </ListIterator>
</ArrayInput>
```

But when I have a tabbed form with for example 2 tabs with `ListIterator` components, both lists seem to use the same paging state. Let's assume we reference two resources: *drivers* and *vehicles*. Let's say there are 11 drivers and 1 vehicle in the database. Going from page 1 to page 2 of *drivers* list causes 4 `get-filtered-list` calls:
1. The first call to */drivers/get-filtered-list* initiated by me when selecting another page in the *drivers* list;
2. The second call to */vehicles/get-filtered-list* initiated by the other list which seems to be using the same pager state of the *drivers* list;
3. Since this second call returned `totalCount: 1`, this seemed to have triggered the pager state to reset to page 1, causing the third call: to */drivers/get-filtered-list* with `skipCount: 0` (i.e., went back to the first page);
4. This in turn caused another call to */vehicles/get-filtered-list* with `skipCount: 0` (i.e., went back to the first page).

The said form would look something like this:
```ts
<TabbedForm {...props}>
    <FormTab {...props} label="Drivers">
        <ArrayInput source="selectedDrivers" label="">
            <ListIterator reference="drivers">
                <TextField source="fullName" />
            </ListIterator>
        </ArrayInput>
    </FormTab>
    <FormTab {...props} label="Vehicles">
        <ArrayInput source="selectedVehicles" label="">
            <ListIterator reference="vehicles">
                <TextField source="name" />
            </ListIterator>
        </ArrayInput>
    </FormTab>
</TabbedForm>
```

This behavior resulted in inability to change pages in such scenario.
Is this expected or am I missing something?
I hope I explained this good and the issue is clear to you. If not, please let me know if you need a repro sample.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

ListBase uses useListController, which takes the sort, filter, and pagination state from the URL. You're not supposed to use more than one ListBase per page. So what you do isn't supported. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
