### ISSUE TITLE
Uncaught Error: Cannot find module '@material-ui/icons/Label'

### ISSUE THREAD

**Issue by firepol** [marmelab/react-admin#5600]
https://marmelab.com/react-admin/Admin.html#menu

When I try to create a menu like in the example:

```
// in src/Menu.js
import * as React from 'react';
import { createElement } from 'react';
import { useSelector } from 'react-redux';
import { useMediaQuery } from '@material-ui/core';
import { MenuItemLink, getResources } from 'react-admin';
import { withRouter } from 'react-router-dom';
import LabelIcon from '@material-ui/icons/Label';
```

I get: `Uncaught Error: Cannot find module '@material-ui/icons/Label'`

![image](https://user-images.githubusercontent.com/1702718/100522674-02bc5e00-31ab-11eb-80e4-3bbda792a8cf.png)

Using react-admin 3.8.4.

Please fix the example, thank you.

**Comment by firepol** [comment]
Solved:
```yarn add @material-ui/icons```

But then I get more errors:
![image](https://user-images.githubusercontent.com/1702718/100522928-bd009500-31ac-11eb-9594-6c89330a0328.png)

would be nice to have a working example...

**Comment by fzaninotto** [comment]
Hi, and thanks for your issue.

We consider that the minimum knowledge to use react-admin includes the ability to detect missing packages and install them. Besides, the documentation shows snippet using the `@material-ui/icons` package in various chapters, and adding a note explaining that the package must be installed first would make it the documentation less fluid. So we won't change that.

As for the problem with `useMEdiaQuery`, I cannot reproduce it with a normal react-admin application. This shouldn't happen if you're using react-admin's `<Layout>` - so there must be something else in your code that triggers the bug. 

Finally, `useMediaQuery` is a material-ui hook, so I recommend that you open an issue in their repository.
