### ISSUE TITLE
Default dashboard should take the first Resource with a list, instead of the first Resource

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#5605]
**What you were expecting:**

When declaring `<Resources list={...}/>` in `<App/>`, I use permissions to define a `list` of components.
If for some reason the component sheet of the first `<Resource list={()=>false}/>` is not available, http: // localhost: 8080 / is expected to redirect to the second `<Resource list={ResourceList}/>` (if it has a list)

**What happened instead:**
Instead, it is redirected to the route of the inaccessible list.

**Steps to reproduce:**

**Related code:**
file error
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/RoutesWithLayout.tsx

need to replace
`const childrenAsArray = React.Children.toArray(children);`
==>
`const childrenAsArray = React.Children.toArray(children).filter(child => child.props.list);`

* React-admin version: 3.9.6

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. I think it would be nice to have this feature, but I don't think your patch is right - we need Resources to be registered even though they don't have a list.

Besides, you can achieve what you want by passing a specific dashboard component which redirects to the resource you want:

```jsx
const Dashboard = () => <Redirect to="/foos" />;
```

So I'm marking this as an enhancement: we will accept a patch to implement it, but if nobody contributes within a few months, we'll close the issue.

**Comment by wmwart** [comment]
I did not quite understand.
What does it mean to be registered?
If I have a `<Resource name="Foo" />`, for example, just for the ReferenceInput , why have the `/Foo` route?

**Comment by WiXSL** [comment]
Resources need to be registered in the Redux Store first before they can be used.
Since this can be solved in user-land (with the explanation of @fzaninotto) and had no traction by the community in more than a year, I'm closing this issue.

Feel free to re-open it if you are willing to implement this feature.
