### ISSUE TITLE
connect in update mutation

### ISSUE THREAD

**Issue by gtolarc** [marmelab/react-admin#5608]
It seems that nexus-plugin-prisma removes relation id from update mutation when building crud.

If this is intended, it would be nice if there was an option to use the shopId for query and shop.connect.id for mutation. Like this,
```javascript
<ReferenceInput label="Shop" source="shopId" sourceOut="shop.connect.id" reference="Shop">
    <SelectInput optionText="name" />
</ReferenceInput>
```

**Comment by gtolarc** [comment]
https://github.com/panter/ra-data-prisma/issues/46

**Comment by djhi** [comment]
Thanks for your question. That's the job of the dataProvider though.
