### ISSUE TITLE
Supporting getManyReference caching

### ISSUE THREAD

**Issue by capJavert** [marmelab/react-admin#5610]
**Is your feature request related to a problem? Please describe.**
Application cache docs page says:

> Tip: As of writing, the validUntil key is only taken into account for getOne, getMany, and getList.

What would take to implement and support getManyReference for cache? I am interested in implementing this but would like your insight and problems that you encountered and why you decided that it is not supported for now.

Thanks, would appreciate your insights.

**Describe the solution you'd like**
getManyReference calls are cached like other `get` based calls.

**Describe alternatives you've considered**
My first dummy approach would be to invalidate reference cache when base item (that is referenced) is updated. For example from ReferenceArrayInput.

**Comment by diegocgaona** [comment]
Would be nice if it could cache any get endpoint which you put the `validUntil ` .
I have some endpoints to get data to make charts, it could be really good have it in these.

**Comment by WiXSL** [comment]
`master` branch is feature-freeze.

The cache of `getManyReference` is handled by `react-query` via the use of `useGetManyReference` hook in `next` branch, thanks to the adoption of `react-query`.
The `validUntil` attribute has been removed, as explained in the upcoming upgrade guide.

So I'm closing this feature request.
