### ISSUE TITLE
SelectInput inside ReferenceInput causes material-ui warning "You have provided an out-of-range value"

### ISSUE THREAD

**Issue by bodo22** [marmelab/react-admin#5615]
**What you were expecting:**

No material-ui warnings to appear

**What happened instead:**

material-ui warnings appear

**Steps to reproduce:**

- I cloned the [simple demo sandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple), update the react-admin to the most current versin (3.10.3).
- in the file CommentEdit I replaced AutocompleteInput with SelectInput.
- I went to the edit view of comment number 2 and did a hard reload of that page

**Related code:**

codesandbox: https://codesandbox.io/s/smoosh-browser-q05kc?file=/src/comments/CommentEdit.js
direkt link to see the material-ui warnings: https://q05kc.sse.codesandbox.io/#/comments/2

**Other information:**

After digging way to much, i think this has to do with the fact that this [loading prop](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/useReferenceInputController.ts#L202) is being set to false too early, because [matchingReferences here](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/useReferenceInputController.ts#L154) is always an array.

Happy to help fix if you point me in the right direction :)

**Environment**

* React-admin version: 3.10.3
* React version: 17.0.0
* Browser: chrome 87

**Comment by Alex1844** [comment]
Also seeing this issue, not every time but often

**Comment by djhi** [comment]
Thanks for the detailed report

**Comment by fzaninotto** [comment]
I can't reproduce the bug anymore in 3.12. Can you please check if it's also fixed for you?

**Comment by bodo22** [comment]
Doesn't appear for me anymore with version 3.12.1, thanks!
