### ISSUE TITLE
provide a way to pass an option to useQueryWithStore so it doesn't actually make a request

### ISSUE THREAD

**Issue by megantaylor** [marmelab/react-admin#5619]
i need a way to bail out of useQueryWithStore without making a request

similar to the `enabled` option in react-query: https://react-query.tanstack.com/docs/guides/queries#dependent-queries

**Comment by djhi** [comment]
Hi and thanks for this feature request. Can you please describe what your usecase is exactly?

**Comment by megantaylor** [comment]
i have a drawer that opens and closes and uses useQueryWithStore to get additional data and i want to be able to control when the requests fire

**Comment by fzaninotto** [comment]
Hi @megantaylor

We won't implement that in useQueryWithStore - your need seems too specific, and doesn't fit wit hthe purpose of useQueryWithStore.

I recommend that you use either useDataProvider, or useMutation to trigger the query in certain conditions instead of on mount.

**Comment by rajadsms** [comment]
@fzaninotto 
As per the documentation useQueryWithStore maintain data in redux store for future use. But UseDataProvider or useMutation doesn't work this way right?It doesn't store data in redux store.
Let me know if you have any way to achieve this. My usecase is same as the question describe.

**Comment by djhi** [comment]
We added the `enabled` option in `useQueryWithStore` in [v.3.13.0](https://github.com/marmelab/react-admin/releases/tag/v3.13.0). It's not documented though. Please look at the PullRequest linked in the release notes in the mean time.
