### ISSUE TITLE
ReferenceInput loads its data before its containing view

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5622]
`RefereneInput` loads its items before its own container.
This is a problem for me, because my api sets up at the server what the `RefereneInput` is going to load.
I don't know if this is a bug or a limitation or how to change the order of the calls.

![screen-shot](https://user-images.githubusercontent.com/8268610/101045936-6b1a8f00-355f-11eb-927f-339295baa947.jpg)

https://codesandbox.io/s/heuristic-kepler-m2zkf?file=/src/index.js (Just in case)

**Comment by ozgurrgul** [comment]
For me, I got the opposite one (your expectation) after opening page directly `/posts/2`. 
![image](https://user-images.githubusercontent.com/20097288/101066307-82c13a00-3596-11eb-906e-eefb270da666.png)

**Comment by WiXSL** [comment]
Try clicking the "Refresh" button.

**Comment by ozgurrgul** [comment]
Nope, I don't think so.

**Comment by WiXSL** [comment]
I don't get it.
I've try it in many computers with the latest browsers and all do the same, first the `ReferenceInput` call then the `Edit` api call

**Comment by MicroJackson** [comment]
I have the effect you get when first loading the resource, but every refresh does it the other way around.
![image](https://user-images.githubusercontent.com/39806531/101508287-c1c90400-3977-11eb-88bb-55b77139c317.png)

You could change the order of the call with something like this:
```
import { useForm } from "react-final-form";

const DelayedReference = ({ record = {}, source, classes, ...props }) => {
  const form = useForm();
  let is_id_set = form.getFieldState("id");

  if (is_id_set) {
    return (
      <ReferenceInput label="User" source="user_id" reference="users">
        <AutocompleteInput />
      </ReferenceInput>
    );
  } else {
    return "Nothing yet.";
  }
};

const PostEdit = ({ permissions, ...props }) => (
  <Edit {...props}>
    <SimpleForm>
      <TextInput disabled source="id" />
      <DelayedReference />
    </SimpleForm>
  </Edit>
);
```
It waits for the id to be set to actually create your reference input forcing it to be later then the Edit.
Don't know if this is intented though from RA.

**Comment by WiXSL** [comment]
@MicroJackson, 
Thank you very much for the workaround.
Very simple idea, seems to work.
Even do I would love to hear from RA team regarding this behaviour.

**Comment by fzaninotto** [comment]
We haven't thought about doing these queries in a particular order. It's a result of the react rendering and effect process. 

I don't think it's a bug. And if it matters, as in your case, you can use @MicroJackson's trick.  

So 4Im closing this issue.

**Comment by WiXSL** [comment]
@MicroJackson,
I end up using `useVersion` hook for the task, just sharing:

```jsx
import * as React from "react";
import {useEffect, useRef} from "react";
import {ReferenceInput, useVersion} from "react-admin";

const DelayedReferenceInput = props => {
    const version = useVersion();
    const parentLoaded = useRef(false);

    useEffect(() => {
        parentLoaded.current = true;
    }, [version]);

    if (parentLoaded.current) {
      return (
        <ReferenceInput label="User" source="user_id" reference="users">
          <AutocompleteInput />
        </ReferenceInput>
      );
    } else {
      return "Nothing yet.";
    }
};

**Comment by MicroJackson** [comment]
@WiXSL 
Thanks for sharing!
Just curious, is there any benefit of writing it this way instead of the `useForm`?

**Comment by WiXSL** [comment]
Your example work for me only the first time, using `useVersion` allows me to re fetch after each refresh of the form's data.
React-admin's fetch hooks use it.

**Comment by MicroJackson** [comment]
Cool, thanks for the explanation. 
Learned something again.
