### ISSUE TITLE
displayedFilters documentation is inconsistent.

### ISSUE THREAD

**Issue by martdavidson** [marmelab/react-admin#5635]
On the List View page in the documentation it's mentioned:

`displayedFilters: Names of the filters displayed in the form, e.g. ['commentable','title']`

But then later on on the same page it's written:

`displayedFilters, // a dictionary of the displayed filters, e.g. { title: true, nationality: true }`, which is in fact correct as passing an array to setFilters' `displayedFilters` param results in a console error of:

```
Failed prop type: Invalid prop `displayedFilters` of type `array` supplied to `ListActions`, expected `object`.
```

**What you were expecting:**
Consistency in the documentation, and additionally - if it makes sense to - an update to the `displayedFilters` param on the `setFilters` type definition, and anywhere else it might exist. Currently it is defined as `any` but clearly somewhere in the code it knows it should be an object, hence the console error, and it would be ideal if the type definition reflected that.

**Environment**

* React-admin version: 3.10.3
* React version: 17.0.1

**Comment by djhi** [comment]
Good catch, thanks. Would you mind opening a PR to fix the documentation?

**Comment by etienne-bondot** [comment]
@djhi this issue can be closed as the documentation has been update :)
