### ISSUE TITLE
Updating React-Admin CreateContextProvider' Error

### ISSUE THREAD

**Issue by webdevNYC** [marmelab/react-admin#5639]
**What you were expecting:**
Hi there, After I updated the react-admin to version 3.10.4 I get the error:
./node_modules/ra-ui-materialui/esm/detail/Create.js
Attempted import error: 'CreateContextProvider' is not exported from 'ra-core'.

not sure how to fix it. 

Thanks,

**Comment by djhi** [comment]
This is weird as it is indeed exported. Please double your `yarn.lock` and `package-lock.json` file et ensure `ra-core` is at version `3.10.4` as well

**Comment by victorcoder** [comment]
Same issue for me, updated with `npm update react-admin` then running `npm install ra-core@3.10.4` solved the issue for me.

**Comment by fzaninotto** [comment]
Yet react-admin 3.10.4 has a dependency on ra-core `^3.10.4`. You can only have another version of ra-core if yo installed it by hand. So I don't think it's a react-admin problem.

**Comment by MicroJackson** [comment]
I always remove my node_modules folder and package-lock.json then `npm update` to install and update everything in my package.json again with the correct dependencies when I encounter issues like this. 99% of the time that fixes it for me, but it is a workaround.

**Comment by fzaninotto** [comment]
OK, so this seems like an npm-related problem. The dependency is correctly declared in react-admin, so I'm closing this issue.
