### ISSUE TITLE
ReferenceField doesn't call fetch

### ISSUE THREAD

**Issue by TalOrlan** [marmelab/react-admin#5640]
<ReferenceField label="User" source="owner_id" reference="users">
        <FunctionField
          render={(record) => `${record.first_name} ${record.last_name}`}
          label="Name"
        />
      </ReferenceField>
I ahve this code and nothing happend  it all empty and doesn't call anything

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
No news for some time, closing.
