### ISSUE TITLE
Issue with Editing posts

### ISSUE THREAD

**Issue by petrbui** [marmelab/react-admin#5647]
Hello, I need to ask about post Edit 

**What you were expecting:**
If i click on Edit button it will show me data from the post but I want to change for example title it will write the succes but the changes are not updated in firestorage.

Create and delete buttons work fine without problem

**What happened instead:**
nothing happend it just redirect me to the list 

and getting this error in console
<img width="723" alt="obrazek" src="https://user-images.githubusercontent.com/32798156/101638694-a967f080-3a2e-11eb-989c-c2a622fd0e4d.png">

**Steps to reproduce:**

```
export const PostEdit = (props) => {

  const redirect = useRedirect();
  const onSuccess = () => {
    console.log("succes")
    redirect("list", props.basePath);
  };
  const onFailure = (error) => {
    if (error.code === 123) {
     console.log("error",error)
    } else {
      console.log("ra.notification.http_error", "warning");
    }
    redirect("list", props.basePath);
  };
  return (
    <Edit
      title="Article Edit"
      {...props}
      onFailure={onFailure}
      onSuccess={onSuccess}
    >
      <SimpleForm>
        <TextInput disabled source="id" />
        <TextInput source="title" validate={required()} />
        <RichTextInput source="body" />
        <DateField source="lastupdate" />
        <ImageInput source="image" multiple label="gallery">
          <ImageField source="src" title="title" />
        </ImageInput>
        <AutocompleteArrayInput source="tags" choices={sections} />
      </SimpleForm>
    </Edit>
  );
};

```

**Environment**

<img width="349" alt="obrazek" src="https://user-images.githubusercontent.com/32798156/101639751-f3050b00-3a2f-11eb-86e3-9cc410830628.png">

**Comment by MicroJackson** [comment]
That's a warning not an error and does not seem to be the problem that causes you to not save your edit data. I have that same one on all my projects and my Edits work fine.

I am almost certain your backend is not saving the data correctly, this does not seem like a React Admin problem (The warning is not nice though). Might also be your dataProvider not giving correct data to your backend. My advice is to look there.

**Comment by petrbui** [comment]
Ok thanks i tought if create and delete work fine it will be someting with react admin

**Comment by petrbui** [comment]
I find the solution 
with `undoable={false}`
[here](https://stackoverflow.com/questions/63960736/react-admin-edit-component-does-not-call-update-function)
