### ISSUE TITLE
Resource in useListController

### ISSUE THREAD

**Issue by Al0ngsy** [marmelab/react-admin#5648]
https://github.com/marmelab/react-admin/blob/12a40fb73cb4c8cd60feeed515aac6dccd420b55/packages/ra-core/src/controller/useListController.ts#L121

Shouldn't this line be `const resource = res || useResourceContext(props);` with `const {resource: res, ...otherProps} = props` instead? Since on line 109 there is still a check for 'resource' as a required props in ListControllerProps.

https://github.com/marmelab/react-admin/blob/12a40fb73cb4c8cd60feeed515aac6dccd420b55/packages/ra-core/src/controller/useListController.ts#L109

My Problem: I tried to render resource Y inside a Modal when I am currently at resource X and this one breaks the ListView since it returns data from X instead of Y. It works fine on v3.8 but breaks after updated to v3.10.

**Comment by djhi** [comment]
Actually, the `resource` should be removed from the `useCheckMinimumRequiredProps`. Indeed the reason we pass the props the `useResourceContext` is to fallback to the resource prop until we release version 4. Would you mind opening a pr to fix it ? 

As for your usecase, you may pass the `resource` prop for now but will probably need to wrap your `List` with a `ResourceContextProvider` later
