### ISSUE TITLE
not rendering the Image in SHOW

### ISSUE THREAD

**Issue by petrbui** [marmelab/react-admin#5651]
Hello guys, i got some problem with  ` <ImageField source="image" title="title" />`

**What you were expecting:**
i want to render in SHOW images like here
<img width="1211" alt="obrazek" src="https://user-images.githubusercontent.com/32798156/101767925-379eae00-3ae5-11eb-8f05-1b333aefc303.png">

**What happened instead:**
but insted it will show me just title of images 
<img width="1214" alt="obrazek" src="https://user-images.githubusercontent.com/32798156/101767775-fa3a2080-3ae4-11eb-8d90-d439331cc089.png">

**Related code:**

```
export const PostShow = (props) => (
  <Show {...props}>
    <SimpleShowLayout>
      <TextField label="Article ID" source="id" />
      <TextField label="Title of article" source="title" />
      <TabbedShowLayout>
        <Tab label="body">
          <RichTextField source="body" addLabel={false} />
        </Tab>
        <Tab label="summary" path="summary">
          <TextField label="Id" source="id" />
          <TextField source="title" />
          <TextField source="teaser" />
        </Tab>

        <Tab label="Miscellaneous" path="miscellaneous">
          <TextField label="Created By" source="createdby" />
          <DateField label="Publication date" source="createdate" />
          <TextArrayField
            label="tags"
            source="tags"
            optionText="name"
            optionValue="id"
          >
            <SingleFieldList>
              <ChipField source="id" />
            </SingleFieldList>
          </TextArrayField>
          <BooleanField
            label="Allow comments?"
            source="commentable"
            defaultValue
          />
          <TextField label="views" source="views" />
        </Tab>
        <Tab label="comments" path="comments">
          <ReferenceManyField
            reference="comments"
            target="post_id"
            addLabel={false}
          >
            <Datagrid>
              <TextField source="body" />
              <DateField source="created_at" />
              <EditButton />
            </Datagrid>
          </ReferenceManyField>
        </Tab>
        <Tab label="gallery" path="gallery">
          <ImageField source="image" title="title" />
 
        </Tab>
      </TabbedShowLayout>
    </SimpleShowLayout>
  </Show>
);
```

**Environment**
![obrazek](https://user-images.githubusercontent.com/32798156/101768465-e4792b00-3ae5-11eb-9f3c-28316f790cc7.png)

**Comment by etienne-bondot** [comment]
This is because you add the `title` property I think

> title: The name of the property containing the image source if the value is an array of objects

Try to remove it.

**Comment by petrbui** [comment]
if i removed it its empty if i write src to the title it will give me src to the images
<img width="1212" alt="obrazek" src="https://user-images.githubusercontent.com/32798156/101774399-56557280-3aee-11eb-8310-fbe3394391e2.png">

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by petrbui** [comment]
as you can see [Here](https://codesandbox.io/s/issue-with-image-38rxk?file=/src/posts/posts.js) in Article ID 1 there is 2 images it i put one Imagefield with Title  and one without if there is the title it will show 2 titles but no images

**Comment by etienne-bondot** [comment]
I've update you example looking directly in the component. The doc is actually broken on the `ImageField` property and how to use them.

Working codesample: https://codesandbox.io/s/issue-with-image-forked-nbb1y?file=/src/data.js

**Comment by petrbui** [comment]
@etienne-bondot  thanks a lot now it work fine

**Comment by djhi** [comment]
@etienne-bondot Would you mind fixing the documentation?

**Comment by etienne-bondot** [comment]
I will try to make something this weekend if I found some time and motivation ;)

**Comment by etienne-bondot** [comment]
As discussed on #5654. I will try to find something more generic to generate a better documentation on components.
