### ISSUE TITLE
[doc] Add clear information on How to update content of ConfirmationDialog

### ISSUE THREAD

**Issue by etienne-bondot** [marmelab/react-admin#5654]
Hi RA team,

There are two properties of the `DeleteButton` and `BulkDeleteButton` which was missing (or I missed them) in documentation but useful to know 
- `confirmTitle={'My Title'}  // 'resources.<my_res>.delete.title'`
- and `confirmContent={'My Content'}`

I think that this could be great to be add them to the documentation.
I found them wandering on SO in [this post](https://stackoverflow.com/a/61013796/1985912) and the sample example looks good and might be used "as it".

```javascript
const MyActions = props => (
  <TopToolbar>
    <DeleteButton
      undoable={false}
      confirmTitle={'My Title'}  // 'resources.my_res.delete.title'
      confirmContent={'My Content'}
    />
  </TopToolbar>
)

const MyBulkActionButtons = props => (
  <>
    <BulkDeleteButton
      undoable={false}
      confirmTitle={'My Title'}
      confirmContent={'My Content'}
      {...props}
    />
  </>
)

<List actions={<MyActions />} bulkActionButtons={<MyBulkActionButtons />} />
<Edit actions={<MyActions />} />
```

Any thoughts ? 

Regards.

**Comment by etienne-bondot** [comment]
I perfectly understand that. 

How can I help on this ? 
Do you already have some ideas, plan or tools to generate this documentation ?

**Comment by fzaninotto** [comment]
Nope, at this stage everything is open. We've explored solutions like Docz, but they imply doubling the JSDoc with .mdx files, which is too much work. 

Ideally, we'd need a tool that parses all our source files, detects components and functions, and generates one static page for each based on the jsDoc and TypeScript types. I haven't looked, but I suspect this exists - that's what material-ui does. 

Would you like to take a look?

**Comment by etienne-bondot** [comment]
OK, I'm keeping this page open on my side. I will look around to see if I can find something / do something on it.
