### ISSUE TITLE
Allow passing a custom resource prop to Create / Edit

### ISSUE THREAD

**Issue by danjebs** [marmelab/react-admin#5662]
Hi guys, loving using React-Admin! The look on my clients' faces was priceless - "Will it actually be this fast? 🤯 "

I have a feature request for a now-deprecated feature to be re-enabled, although maybe you will have a compelling clarification of why it was removed. Apologies if this has been covered elsewhere, I couldn't find another discussion pertaining to this.

**Is your feature request related to a problem? Please describe.**
In prior versions of React Admin (I was using 3.7.0), I was able to make Create/Edit forms within complex objects, for simple objects within it. For example, in the image below, a Program could open a Drawer component which allowed for adding ProgramDates or FAQs related to theProgram. As a Program is a complex object with many relations within it, this prevented the user from having to switch contexts to fill out a very simple form.
![Screen Shot 2020-12-13 at 10 43 28 AM](https://user-images.githubusercontent.com/12756405/102001713-0ebe2900-3d30-11eb-9821-fbf9ac4a7d4b.png)

This was achieved by the following:
```javascript
const ProgramDateDetailCreate = ({ programId, onSuccess }) => (
  <Create
    {...{onSuccess}}
    basePath='/ProgramDateDetail'
    resource='ProgramDateDetail'
    undoable={false}
  >
    <SimpleForm defaultValue={{ programId }}>
      // inputs go here
    </SimpleForm>
  </Create>
)

export default ProgramDateDetailCreate
```

In newer versions of React-Admin, the `resource` that I pass is overwritten by the resource in the URL and therefore the submit sends to the "wrong" endpoint.

**Describe the solution you'd like**
The ability to override the `resource` prop in the CreateContext or EditContext. I understand there may be some issues that this causes - but I think having the option, with the caveat that some redirects etc won't work, is worthwhile. Perhaps the prop could be called `dangerouslySetResource` so that you can absolve responsibility for bugs arising from it 😅 

**Describe alternatives you've considered**
I attempted to use the useCreate and useEdit hooks, but they remove the convenience of SimpleForm and lead to a duplication of components.

**Additional context**
The frustrating part about this bug is that I didn't upgrade and it still affected the app - even with my dependencies locked at 3.7.0, it still broke the app when I re0built my Docker container (and re-ram `npm install`). And that's probably more of an issue with NPM, though. Luckily the app is still in QA, but a change like this that could break the an app and require a re-write of many pages makes me nervous.

**EDITS**
Grammar, adding name for override prop, adding edits

**Comment by danjebs** [comment]
Related (I think) to #5648

**Comment by koaladlt** [comment]
Hey @danjebs, where you able to find a workaround to this? I'm in the same situation.

**Comment by danjebs** [comment]
Unfortunately not - I ended up switching to having the forms on their own pages. I thought they allowed using drawers again but I didn't double back and re-change it since I had already converted them and it seems this isn't entirely approved of. But...I thought it would be doable since 3.11.2.
