### ISSUE TITLE
<DeleteButton /> typings don't allow confirm dialog props

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#5667]
**What you were expecting:**
It looks like the [DeleteWithConfirmButton](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx) can receive a number of Confirm Dialog specific props, and it sets the default value itself if it doesn't receive any from its parent.

When using the RA's default `<DeleteButton undoable={false} >` I expect that TypeScript accepts the props that DeleteWithConfirmButton also accepts.

[In this sandbox](https://codesandbox.io/s/sweet-browser-zoiwv?file=/src/posts/PostEdit.js) you can see that I'm passing through the props fine in vanilla javascript, it just seems that the `DeleteButton` props assume that we always want `undoable` set to `true`.

If you would like to have these types export I can look into whipping up an MR.

I would imagine that implementation to look something like this: 

```tsx
interface DeleteButtonBaseProps {
  title: string;
  resource: string;
  ...other props
}

interface DeleteButtonNoDialogProps extends DeleteButtonBaseProps {
  undoable: true;
  ...other props
}

interface DeleteButtonDialogProps extends DeleteButtonBaseProps {
  undoable: false;
  dialogTitle: string;
  ...other props
}

type DeleteButtonProps = DeleteButtonNoDialogProps | DeleteButtonDialogProps;

function DeleteButton(props: DeleteButtonProps) {
  if (props.undoable) {
    return <DeleteButtonNoDialog {...props} />;
  }

  return <DeleteButtonWithDialog {...props} />;
}

function DeleteButtonNoDialog(props: DeleteButtonNoDialogProps) {
  return null;
}

function DeleteButtonWithDialog(props: DeleteButtonDialogProps) {
  return null;
}

function Test() {
  <DeleteButton
    title="delete"
    resource="posts"
    undoable={true}
    dialogTitle="Delete Forever" // typescript error
  />;
  <DeleteButton
    title="delete"
    resource="posts"
    undoable={false}
    dialogTitle="Delete Forever"
  />;
}
```

But let me know if this doesn't work for you, or if you have another pattern in mind

**Environment**

* React-admin version: 3.11.0
* React version: 17.0.1

**Comment by fzaninotto** [comment]
If you know you want a `<DeleteWithConfirmButton>`, why do you use a `<DeleteButton>`? And since `DeleteWithConfirmButtonProps` is exported, it should fit your need.

**Comment by andrico1234** [comment]
Honestly, I hadn't considered that both the more specific components were exported by React Admin, that's a complete oversight on my part.

Your suggestion works as expected,

Thanks
