### ISSUE TITLE
Edit and Create component are not working with a common SimpleForm component

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#5670]
**What you were expecting:**

If order to avoid code duplication on admin creation and edition components that will have the same field, I created a common component containing `SimpleForm` and the fields.

I expect the create and edit element to work properly.

**What happened instead:**

1. On Edit, the form fields are not filled
2. On both, I have the following error on save: `TypeError: onSave.current is not a function`

However, both work great if I remove the common component logic for duplicated `SimpleForm` definition.

**Steps to reproduce:**

See related code.

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```typescript
import * as React from "react";
import { List, Datagrid, TextField, Filter, SearchInput, Create, SimpleForm, TextInput, PasswordInput, BooleanInput, BooleanField, Edit, EditButton } from 'react-admin';
import Icon from '@material-ui/icons/AccountCircle';

export const UserIcon = Icon;

const UserFilter = (props) => (
  <Filter {...props}>
    <SearchInput source="email" alwaysOn />
  </Filter>
);

export const UserList = (props) => (
  <List {...props} filters={<UserFilter />}>
    <Datagrid>
      <TextField
        source="lastName"
        label="Prénom"
      />
      <TextField
        source="firstName"
        label="Nom"
      />
      <TextField
        source="phoneNumber"
        label="Tél."
      />
      <TextField source="email" />
      <EditButton />
    </Datagrid>
  </List>
);

const UserForm = () => (
  <SimpleForm>
    <TextInput
      source="email"
    />
    <TextInput
      source="phoneNumber"
      label="Numéro de téléphone"
    />
    <PasswordInput
      source="password"
      label="Mot de passe"
    />
    <TextInput
      source="firstName"
      label="Prénom"
      required
    />
    <TextInput
      source="lastName"
      label="Nom de famile"
      required
    />
  </SimpleForm>
);

export const UserCreate = (props) => (
  <Create {...props}>
    <UserForm />
  </Create>
);

export const UserEdit = (props) => (
  <Edit {...props}>
    <UserForm />
  </Edit>
);

// eslint-disable-next-line import/no-anonymous-default-export
export default null;
```

**Other information:**

**Environment**

* React-admin version: `3.11.0`
* Last version that did not exhibit the issue (if applicable):
* React version: `17.0.1`
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi and thanks for your question. react-admin currently still clone elements and inject props. In your case, The `UserForm` component receive props which it should pass to its underlying `SimpleForm`.

```jsx
const UserForm = (props) => (
  <SimpleForm {...props}>
    <TextInput
      source="email"
    />
    <TextInput
      source="phoneNumber"
      label="Numéro de téléphone"
    />
    <PasswordInput
      source="password"
      label="Mot de passe"
    />
    <TextInput
      source="firstName"
      label="Prénom"
      required
    />
    <TextInput
      source="lastName"
      label="Nom de famile"
      required
    />
  </SimpleForm>
);
```
