### ISSUE TITLE
Сustom theme is not merged but replaced by default

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#5672]
**What you were expecting:**
Expected custom theme to merge with default theme

**What happened instead:**
Сustom theme replaced the default theme
Documentation:

> If you need more fine-tuning, you’ll need to write your own theme object, following Material UI themes documentation. Material UI merges custom theme objects with the default theme.

[https://marmelab.com/react-admin/Theming.html#writing-a-custom-theme](https://marmelab.com/react-admin/Theming.html#writing-a-custom-theme)

**Steps to reproduce:**
[https://codesandbox.io/s/confident-davinci-192ss](https://codesandbox.io/s/confident-davinci-192ss)

According to the documentation, and the latest changes with this theme configuration
1) the theme should change to dark
2) there should be no ripple effect on the buttons

however, as we can see the dark theme applied and the ripple effect returned

**Environment**

* React-admin version: 3.11.0
* Last version that did not exhibit the issue (if applicable): 3.9.6

**Comment by fzaninotto** [comment]
Well spotted, thanks!
