### ISSUE TITLE
react-admin main module should not use caret versions

### ISSUE THREAD

**Issue by digitalbreed** [marmelab/react-admin#5677]
**What you were expecting:**

When I pull in RA in package.json, I deliberately decide which version format I use - e.g. fixed version vs. caret version. If I use a fixed version and install dependencies, I would expect all RA modules to be installed in this specific version – I might be looking at exactly this code tag to compare, or at exactly this documentation snapshot, or there may be some critical issue that I want to avoid.

**What happened instead:**

The react-admin module uses caret versions, e.g. currently react-admin is at 3.11.0 and package.json contains `"ra-core": "^3.11.0",` as a dependency. If I use an earlier version, like "3.10.1", I still get ra-core etc. in the latest version. In fact, I get any latest release as long as its major version is 3.

This feels counter-intuitive and I think version resolution should be left to the user. If I decide to use "^3.10.1", I am happy to receive "3.11.0" for all RA dependencies. If I decide to use "3.10.1" I would expect this to be used for all RA dependencies.

NB: I am aware I could use yarn resolutions as a workaround, but this won't help npm users and I feel it should be dealt with inside of RA.

**Steps to reproduce:**

Run CRA and add "react-admin": "3.10.1" as a dependency, then run `yarn install` and inspect the `node_modules/ra-core/package.json` version, you'll find 3.11.0.

**Comment by fzaninotto** [comment]
Hi, and thanks for opening this discussion.

As we (do our best to) follow semver, the caret will bring new features and bug fixes, but no breaking changes. We believe it's what users want by default.

If you want to pin packages to a specific versions, yarn resolutions will work for you.
