### ISSUE TITLE
CustomList component passes wrong resource parameter

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#5678]
**What you were expecting:**
Expected creating a CustomList as in the documentation would work correctly [https://marmelab.com/react-admin/List.html#performance](https://marmelab.com/react-admin/List.html#performance)

> Tip: You can use the <Datagrid> component with custom queries, provided you pass the result to a <ListContextProvider>:

```

import keyBy from 'lodash/keyBy'
import { useQuery, Datagrid, TextField, Pagination, Loading, ListContextProvider } from 'react-admin'

const CustomList = () => {
    const [page, setPage] = useState(1);
    const perPage = 50;
    const { data, total, loading, error } = useQuery({
        type: 'GET_LIST',
        resource: 'posts',
        payload: {
            pagination: { page, perPage },
            sort: { field: 'id', order: 'ASC' },
            filter: {},
        }
    });

    if (loading) {
        return <Loading />
    }
    if (error) {
        return <p>ERROR: {error}</p>
    }
    return (
        <ListContextProvider
            value={{
                resource: 'posts',
                basePath: '/posts',
                data: keyBy(data, 'id'),
                ids: data.map(({ id }) => id),
                currentSort: { field: 'id', order: 'ASC' },
                selectedIds: [],
            }}
        >
            <Datagrid rowClick="edit">
                <TextField source="id" />
                <TextField source="title" />
            </Datagrid>
            <Pagination
                page={page}
                perPage={perPage}
                setPage={setPage}
                total={total}
            />
        </ListContextProvider>
    );
}

```

**What happened instead:**

Instead, in the component, everywhere in `<Datagrid>`, the `resource` parameter is correct, and `<DatagridRow>` it is replaced by `resource` from `useResourceContext(props)`

**Steps to reproduce:**
Open DatagridRow.tsx
```
...
    const resource = useResourceContext(props);
...
```

**Other information:**
I don't know how to properly wrap the example in a ResourceContext or do I need to edit the DatagridRow?

**Environment**

* React-admin version: 3.11.0
* Last version that did not exhibit the issue (if applicable): 3.9.6

**Comment by djhi** [comment]
Until the documentation is fixed, you can wrap your custom list inside a `ResourceContextProvider` which take the resource name as its `value` prop
