### ISSUE TITLE
jsonServerProvider (ra-data-json-server) misleading documentation

### ISSUE THREAD

**Issue by newfylox** [marmelab/react-admin#5680]
**Is your feature request related to a problem? Please describe.**
At first, when using `jsonServerProvider`, I thought the `getMany` documentation was doing multiple `GET` calls as mentioned
`getMany` | `GET http://my.api.url/posts/123`, `GET http://my.api.url/posts/456`, `GET http://my.api.url/posts/789`

In fact, it uses `query-string` and it produces one call like this
`GET http://my.api.url/posts?id=1&id=2&id=3`

**Describe the solution you'd like**
Two things are wrong in the documentation. First, it assumes it calls `GET` multiple times and it's a "_filter_" query (`?`), not a controller action query (`/`).
Right now I've cloned the repository and I added `{ arrayFormat: "bracket" }` as an option to `stringify` function to fit my API.

Is it possible to update the documentation? Thanks

**Comment by wangzuo** [comment]
I guess it should be `{ arrayFormat: "bracket" }`  by default.

**Comment by dannyxu2015** [comment]
> I guess it should be `{ arrayFormat: "bracket" }` by default.

No, it's not default
