### ISSUE TITLE
initialValues in TabbedForm within <Edit> not called

### ISSUE THREAD

**Issue by paulito415** [marmelab/react-admin#5682]
**What you were expecting:**
My use case is one where I need to do some data transformation upon calling the provider GET APIs before they get rendered in my `<Create>` / `<Edit>` views. From https://marmelab.com/react-admin/CreateEdit.html#default-values my understanding is that the `initialValues` attribute can be used under `<TabbedForm>` under both `<Create>` and `<Edit>`. Under my `<Create>` it correctly fires and my expectation is that under `<Edit>` it should also fire.

**What happened instead:**
When placed as an attribute in `<TabbedForm>` under `<Edit>` it does not fire the actual call to my function referenced by `initialValues`.

**Steps to reproduce:**

Add an `initialValues` attribute pointing to a function, for a `<TabbedForm>` under `<Edit>` and notice that entering into the Edit view that the function is not called.

**Related code:**

```
const postDefaultValue = () => ({ created_at: new Date(), weight: 915 });

export const HbEventEdit = props => (
    <Edit {...props} transform={updateUrl}>
        <TabbedForm initialValues={postDefaultValue}>
        ...
        </TabbedForm>
    </Edit>
);
```

**Other information:**

**Environment**

* React-admin version: 3.10.3
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.13.1
* Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by etienne-bondot** [comment]
Seems this is the same for me, related to https://github.com/marmelab/react-admin/issues/5582.

**Comment by paulito415** [comment]
Thanks @etienne-bondot for sharing your case! Can you elaborate a bit on what you mean by overriding the record "directly on edit"? Are you saying that is a way to circumvent the issue? Thanks!

**Comment by MicroJackson** [comment]
Seems to be a problem on your side, I made an example here:
https://codesandbox.io/s/keen-villani-n2m1b?file=/src/posts/PostEdit.js

Go to /#/posts/3/2. You will see that the initial value is 1000 as set in the function.

**Comment by etienne-bondot** [comment]
You can see in the link I provide that I could set my initialValues on edit overriding the record directly like

```
const initialValues: Values = {
    ...overrides,
};

return (
  <SimpleForm {...props} record={initialValues}>
    {props.children}
  </SimpleForm>
);
```

As I mutualise my edit and my create forms, I need to switch between `initialValues` or `record` according to my view (edit or create).

**Comment by djhi** [comment]
The `record` will always override the `initialValues`. As shown by @MicroJackson, `intialValues` works fine in an Edit when the record does not have a value for any of the field with an initial value. Transforming the data received from your API should be the responsability of your dataProvider.

**Comment by etienne-bondot** [comment]
So If I understand properly this means that we can't mixed `initialValues` with `record` ?

**Comment by djhi** [comment]
No, it means `initialValues` is only usefull with Edit when the record may not contain a value for a field

**Comment by etienne-bondot** [comment]
OK so we can use the `initialValue` but if the record's `source` exists it will override it. Is that right ?

**Comment by paulito415** [comment]
Thanks @djhi for your explanation. But I'm not sure in my use case the transformation should be the responsibility of my dataProvider. There are cases on a per-resource level where these transformations need to happen, as the `transform` attribute allows in `<Edit>` or `<Create>` but why doesn't the "reverse" of such an attribute exist?

**Comment by djhi** [comment]
per-resource level transformation can still occur in the dataProvider

**Comment by paulito415** [comment]
@djhi that's what I ended up doing but in my opinion I should not really have resource specific code in my dataProvider - my impression of its job is that it shouldn't be littered with if else / switch statements pointing to resource specific logic. But maybe that's only my opinion. I don't quite understand the lack of parity with the presence of the "transform" attribute on <Edit>.

**Comment by etienne-bondot** [comment]
I personally can't made a complexe switch base on the resource within my customDataProvider. I will keep the mapping within the form top level.
