### ISSUE TITLE
[3.11] SaveButton inside FormWithRedirect component throws error

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5691]
The custom form shown here:
https://marmelab.com/react-admin/CreateEdit.html#custom-form-component
No longer works with react-admin v3.11

I copy-paste the above sample as the Post form in the following sandbox:
https://codesandbox.io/s/charming-mahavira-kuphi?file=/src/posts/PostCreate.js

1. Create a new Post
2. You get the error `TypeError: Cannot read property 'save' of undefined`

**Environment**

* React-admin version: 3.11
* Last version that did not exhibit the issue (if applicable): 3.10.4
* React version: 17.0.1
* Browser: Google Chrome latest

**Comment by AnkitaGupta111** [comment]
@WiXSL  follow documentation properly,enclose `FormWithRedirect` Component within `Create` tags and replace `resource` and `source` props in Input fields with correct value

**Comment by WiXSL** [comment]
My example wasn't the best. But I have  code like that, that was working before verion 3.11.
I'll re-do the example. 
Basically I have a mui `Dialog` with a `FormWithRedirect` inside that is opened from a `List` bulkActionButtons's button.

**Comment by fzaninotto** [comment]
Using `FormWithRedirect` outside of `Create` or `Edit` isn't something we encourage. Use react-final-form's `<Form>` component for such cases.

**Comment by etienne-bondot** [comment]
Same here, three views on my side were broken after 3.11 update. Changing from the react-admin `SimpleForm` to the `Form` component from `react-final-form` and reimplementing handleSubmit fix it. But this is a dangerous breaking change introduced for many users here. They are some SO post talking about it.

**Comment by fzaninotto** [comment]
I'm sorry that you were bitten by this as well, but it's not a breaking change if the feature was never documented.

**Comment by alextaymx** [comment]
@fzaninotto  , the DEMO examples are not updated to this latest changes

**Comment by fzaninotto** [comment]
@alextaymx Not sure what you're talking about. Can you be more specific?

**Comment by WiXSL** [comment]
#5738 just has been merged, which solves the problem (At least the one I reported) at least  until the next mayor release. In which case is my responsibility to upgrade my code of course.

**Comment by alextaymx** [comment]
@fzaninotto , if i'm not mistaken,  in the demo repo, the Review Edit part [https://github.com/marmelab/react-admin/blob/master/examples/demo/src/reviews/ReviewEdit.tsx](url) is using SimpleForm without Edit component, this is where the error pops out.

**Comment by fzaninotto** [comment]
@alextaymx You're right. Since @WiXSL's patch, it only logs a warning, but it should be changed. I'll update the demo.
