### ISSUE TITLE
SaveButton component renders in a non responsive way on small screens

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5692]
Sandbox:

https://codesandbox.io/s/pensive-yonath-r9xgh?file=/src/posts/PostList.js&resolutionWidth=591&resolutionHeight=675

![screenshot](https://user-images.githubusercontent.com/8268610/102704691-7bb84e00-425d-11eb-9a2f-96944ba0ddae.png)

**Comment by fzaninotto** [comment]
That's by design. I don't agree that this is a bug. 

![127 0 0 1_8080_(iPhone 6_7_8)](https://user-images.githubusercontent.com/99944/102794137-330eab00-43ab-11eb-935c-549ed7a1a542.png)


If you want a IconButton for submitting the form, you can always build your own in user land.
