### ISSUE TITLE
Setting scrollable={true} in TabbedFormTabs component throws an error

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5695]
Using this example from the docs and getting an error:
https://marmelab.com/react-admin/CreateEdit.html#tabbedformtabs

Sandbox:
https://codesandbox.io/s/xenodochial-torvalds-fsbet?file=/src/posts/PostEdit.js

1.- Edit a Post

![screenshot](https://user-images.githubusercontent.com/8268610/102727797-d0fc6a00-4306-11eb-9ecf-7273312df945.png)

**Comment by fzaninotto** [comment]
Right, it seems `scrollable` was a material-ui v3 prop. The correct prop in v4 is `scrollButtons`, as explained [in the material-ui documentation](https://material-ui.com/components/tabs/#scrollable-tabs).

I'm marking this as a documentation issue ; PR welcome!

**Comment by WiXSL** [comment]
I try setting `tabs={<TabbedFormTabs variant="scrollable" scrollButtons="auto" />}` to `TabbedForm` component but it doesn't show a vertical scrollbar.

**Comment by fzaninotto** [comment]
#5713 seems to fix that problem but I don't understand why.

**Comment by fzaninotto** [comment]
Fixed by #5960
