### ISSUE TITLE
SimpleForm equivalent of FormTab contentClassName

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5696]
`FormTab` component allows to set `contentClassName` prop to style the content of the tab which is applied to a top level `span`.
`SimpleForm` doesn't have anything like that for its content.

**Comment by fzaninotto** [comment]
As seen in #5697, I don't think this is a good idea, but we can accept a PR that would allow to replace the root `component` used by `<SimpleForm>`

**Comment by fzaninotto** [comment]
Fixed by #5703
