### ISSUE TITLE
Static "filter" property of the List is readable vie useListContext(), and not added to filterValues either

### ISSUE THREAD

**Issue by vkost** [marmelab/react-admin#5699]
**What you were expecting:**
I have created a List with filter={} parameter, to add a static filter on top of the dynamic one that is fetched from the URL parameters. This works as expected and I get the filtered results. I also have the Export button to export the list results to CSV. I expected that the server request (made to fetch the contents to be exported) will contain the static filter I applied via the filter={} property. 

**What happened instead:**
The parameters set in filter={} property were ignored.

**Steps to reproduce:**
Create a List and add a static filter via filter={} property. Then add an export button using the default library. Do an export and see if the static filter was applied.

**Related code:**
I applied the filter as so: filter={{custCode: 'C04748'}}.  Works as expected in the fetched list contents, fails in Export button.

**Environment**
Mac OSX, docker containers

* React-admin version: 3.10.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Firefox 84
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
You should upgrade to 3.11.1 ;) 

#5675
