### ISSUE TITLE
Set entries limit to SimpleFormIterator

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#5708]
**Is your feature request related to a problem? Please describe.**
I have an API that allows users to update multiple records. We currently use an ArrayInput to handle this. We would like to adjust, on the client side, how many records a user is able to update in a single request.

Since the `SimpleFormIterator` already has the ability to remove the add button via the `disableAdd` prop, it makes sense to extend the behaviour of `disableAdd` to accommodate my request. 

It looks like you do something similar for `disableRemove` as it has a function signature of `boolean | DisableRemoveFunction | undefined`. Where `DisableRemoveFunction` is invoked onChange, and is passed through the record.

```tsx
<ArrayInput source="newUsers" label="Create users">
  <SimpleFormIterator
    disableAdd={(record) => {
      return record.newUsers.length <= 3;
    }}
  >
    <TextInput source="username" label="Username" />
  </SimpleFormIterator>
</ArrayInput>
```

**Describe alternatives you've considered**
I can't think of any other alternatives other than setting a hard limit via a prop, e.g. `<SimpleFormIterator limit={3}>` but I personally prefer the inversion of control given in the initial solution, though this is subjective.

**Additional context**
If this looks like something you think would work well for RA, i'd be happy to implement it myself. I've been enjoying using RA for the last month, and I'd like to give back

**Comment by fzaninotto** [comment]
I don't think it's a good idea to inject the `record` to a `disableAdd` funciton, because the `record` doesn't change until the user submits the form. From your use case, I understand that you want to set the `disableAdd` fleg based on the form `state`, which you can already do using a `FormSpy` (or a `FormDataConsumer`) in user land, without any modification to `SimpleFormIterator`.
