### ISSUE TITLE
Forms: save button label option

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#5716]
**Is your feature request related to a problem? Please describe.**

Sometimes I am asked to change the save button label with an another label that match better the context.

For example, I have a create only resource that will send a SMS. Having a "Send" button rather than a "Save" one if better,

However, I saw it seems impossible to change the default label with ease.

**Describe the solution you'd like**

A simple string option to change the label. Something like:

```typescript
<SimpleForm
  saveLabel="Send the SMS"
>
```

**Describe alternatives you've considered**

I start using the `toolbar` option to change the default label:

```typescript
import React, { FC } from 'react';
import {
  Create, SimpleForm, TextInput, CreateProps, ResourceProps, useRefresh, useNotify, Toolbar, SaveButton, ToolbarProps,
} from 'react-admin';
import { Sms as icon } from '@material-ui/icons';

const SmsCreateToolbar: FC = props => (
  <Toolbar {...props}>
      <SaveButton label="Envoyer" />
  </Toolbar>
);

const SmsCreate: FC<CreateProps> = (props) => {
  const notify = useNotify();
  const refresh = useRefresh();
  const handleSuccess: CreateProps['onSuccess'] = () => {
    notify('SMS envoyé.');
    refresh();
  };

  return (
    <Create
      title="Envoyer un SMS"
      onSuccess={handleSuccess}
      {...props}
    >
        <SimpleForm
          toolbar={<SmsCreateToolbar />}
        >
        <TextInput
          source="to"
          label="Numéro de téléphone"
          required
        />
        <TextInput
          source="message"
          multiline
          required
        />
      </SimpleForm>
    </Create>
  );
};

const resourceProps: ResourceProps = {
  name: 'sms',
  icon,
  list: SmsCreate,
  options: {
    label: 'SMS',
  },
};

export default resourceProps;
```

This is kinda working, however:

1. It's cumbersome. At the end, I just want to change a label.
2. This is not produce the same behavior. With my example, the button is directly clickable even if the form content is not changed. This is not the case with the default behavior.

**Additional context**

I made work on a PR, but I am quite new to react. If I can have some clues of where to start, I may take a look. :wink:

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

The design decisions we made for react-admin exclude "god-like" components that have plenty of options for customizing everything. Instead, we rely as much as possible on composition. You can compose the Edit component with a custom Toolbar, and use a composition of the default Toolbar with the SaveButton to achieve what you want. 

We won't add any prop higher in the chain, because that would make more code to maintain, more complex logic (what to do when both the SaveButton and the Form have a label?), and because we consider that the customization is simple enough.

**Comment by soullivaneuh** [comment]
> what to do when both the SaveButton and the Form have a label?

This is currently not the case but we may have two labels.

However I understand the decision, at least we have now a record if someone else want to propose the same thing. :+1: 

A bit out of scope, but may you have a explanation of why the save button behavior changed with my current implementation?
