### ISSUE TITLE
TabbedDatagrid component

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#5717]
**Is your feature request related to a problem? Please describe.**

The tabbed data-grid view viewable on the [demo](https://marmelab.com/react-admin-demo/#/commands) is very great and may be useful on many contexts.

**Describe the solution you'd like**

We already have ready to use tabbed layout for the show and the form, so why not for the list datagrid?

The goal would be to propose a simpler implementation without to work on the logic we can see on the [demo source code](https://github.com/marmelab/react-admin/blob/master/examples/demo/src/orders/OrderList.tsx) 

**Describe alternatives you've considered**

Creating my own component. If I made something great and easily re-usable, I may propose it as a Merge Request.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

We're trying to keep the core packages small (and manageable from a maintenance standpoint). That's the reason why we won't add this feature in the core. 

You're welcome to create and publish your own TabbedDatagird component on npm though.
