### ISSUE TITLE
pauseValidation is invalid

### ISSUE THREAD

**Issue by peacetrue** [marmelab/react-admin#5720]
**What you were expecting:**

The form will not be validated.  All validation rules will not be triggered.

**What happened instead:**

The form still be validated.

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/38878763/103076887-ad3c6b00-4609-11eb-8cf7-eb1c15581c39.png)

**Related code:**

https://codesandbox.io/s/j4g41?file=/src/posts/PostCreate.js

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

https://github.com/peacetrue/react-admin/blob/csb-j4g41/examples/simple/src/posts/PostCreate.js

```
<SaveButton
        label="post.action.save_and_edit"
        redirect="edit"
        submitOnEnter={true}
        handleSubmitWithRedirect={(event) => {
          formApi.pauseValidation();
          return props.handleSubmitWithRedirect(event);
        }}
      />
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
What you're trying to do isn't supported by `<SaveButton handleSubmitWithRedirect>`. I advise you to try something else - perhaps write your own `<SaveButton>`?

**Comment by gergo123** [comment]
I am trying to achieve the same thing. Have a save only and a save and submit button separately. But I just cant find a way to pause the validation. I've managed to hack around with global variables, but its really ugly.
I tought calling pauseValidation and calling handleSubmit after could work, but no luck. At first sight the field just does not notice the pauseValidation change and even if submit the form despite invalid being true, it still shows up as red and just doesn't submit the form.

My next step would be to set up a project and somehow debug react-admin itself, to see what is happening. Any ideas?
