### ISSUE TITLE
SelectInput shows error for allowEmpty if i8nProvider is used with option allowMissing

### ISSUE THREAD

**Issue by firdouserp** [marmelab/react-admin#5727]
**What you were expecting:**
select input should successfully renderd

**What happened instead:**
```
Error 
index.js:175 Uncaught TypeError: Polyglot.transformPhrase expects argument #1 to be string
    at transformPhrase (index.js:175)
    at Polyglot.push../node_modules/node-polyglot/index.js.Polyglot.t (index.js:367)
    at Object.translate (index.js:41)
    at useTranslate.js:25
    at useChoices.js:27
    at SelectInput.js:142
    at SelectInput.js:148
    at Array.map (<anonymous>)
    at SelectInput (SelectInput.js:147)
```

**Steps to reproduce:**
use i8nprovider with option allowMissing
```
const i18nProvider = polyglotI18nProvider((locale) => messages[locale], "en", {
  allowMissing: "true",
});
i.e.
<SelectInput allowEmpty choices={data} source="source" reference="reference" />;
```

**Comment by djhi** [comment]
Please follow the issue template

**Comment by Fernito69** [comment]
@firdouserp I had a similar problem. Is `data` in `choices` loaded in an asyncronous way? If so, that might be the problem. You can fix it by rendering the SelectInput conditionally once the data has been loaded.

**Comment by Davidvision** [comment]
Hi @firdouserp  !
I just ran into the exact same issue and found a workaround. If you're still looking for a solution or in case someone else does :

As stated in the Airbnb docs, you can add a 'onMissingKey' key to the polyglot options ([https://airbnb.io/polyglot.js/#options-overview](url)). Here is my code extract :

`const i18nProvider = polyglotI18nProvider(() => ENi18n, "en", {
  allowMissing: true,
  onMissingKey: (key, _, __) => key
});`

And now the error is now gone !

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by dorthwein** [comment]
Incase someone else runs into this as well, having `source` undefined causes this issue.

**Comment by isfopo** [comment]
Setting `translateChoice` on `SelectArrayInput` to `false` works too. It defaults to `true` and tries to find potentially non-existent keys, causing the problem.

**Comment by AndrewStarlike** [comment]
I'm using API Platform v2.6.8 which uses React Admin v3.19.7.

The only way for me to get rid of the error discussed was to use:

`
import polyglotI18nProvider from "ra-i18n-polyglot";
import englishMessages from "ra-language-english";

const i18nProvider = polyglotI18nProvider((locale) => englishMessages, "en", {
  allowMissing: true,
  onMissingKey: (key, _, __) => key,
});

      <HydraAdmin
        ...
        i18nProvider={i18nProvider}
`

**Comment by nga-27** [comment]
Even a year later, this fix by @AndrewStarlike solved my team's issue.  Thank you!
