### ISSUE TITLE
Bug in React Admin pagination

### ISSUE THREAD

**Issue by RamanRajpoot** [marmelab/react-admin#5742]
I was trying to display a big list on the console which was working fine but upon adding pagination to the list it does not work as expected.

At first, it just displays all the list items and then upon clicking on next it does limit the list items to the limit set for pagination. It should paginate the list upon first rendering also which it is not doing.

For eg.
let's say I have a list of 100 items returned from the data provider. I have set the pagination as 10 rows per page. Upon opening the page I am getting all the 100 records returned in the list view and it does show the pagination footer (1-10 of 100). Upon clicking on 2(second page) it displays a list of next 10 items only and worked fine upon going forward.
Now again, if we click on 1 (first page) it returns all 100 records again.

react-admin version - 3.11.1

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by rinaharry** [comment]
some error with apollo
