### ISSUE TITLE
I want to contribute a new translation: https://github.com/markovicmarco/ra-language-serbo and https://github.com/markovicmarco/ra-language-serbo-cyrillic

### ISSUE THREAD

**Issue by markovicmarco** [marmelab/react-admin#5743]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by djhi** [comment]
Hi and thanks for this question. Can you create a pull request to update the documentation page and add those two languages?

**Comment by markovicmarco** [comment]
Sure. How should I write usage for each of them?

**Comment by WiXSL** [comment]
@markovicmarco,
The usage is already explain in the docs: https://github.com/marmelab/react-admin/blob/master/docs/Translation.md
You just have to add a new  entry for your language there.

**Comment by markovicmarco** [comment]
@WiXSL I just want to avoid mistakes, because I am sure about latin and cyrillic standards of the same language. As you know in Serbia we use both.

**Comment by WiXSL** [comment]
Just make any explanations in the docs of your repository.

**Comment by markovicmarco** [comment]
I found this in Mozilla sr-Latn-RS Serbian (Latin) (Serbia) and sr-Cyrl-RS Serbian (Cyrillic) (Serbia)

**Comment by markovicmarco** [comment]
@WiXSL Never have been translated my own language before:) Sorry for that!

**Comment by WiXSL** [comment]
Look, I'm just trying to help you, I'm not even a part of react-admin's core team

**Comment by markovicmarco** [comment]
@WiXSL Sure. I appreciate that. I will check web for the right usage of Serbian cyrillic and latin standards, so I can update README file. Thank you for your help!
