### ISSUE TITLE
Clone button omit only id but not _id

### ISSUE THREAD

**Issue by jurnet** [marmelab/react-admin#5746]
Hello
The cloneButton only omit Id but , I use mongoose and the identifier is _id, it will be great to use omit _id
Any idea ?
Thanks

**Comment by jurnet** [comment]
The only solution i have found : 
````
    const CloneElement = ({ record }) => {
    return record ? (
        <CloneButton
            to={{
                pathname: '/templates/create',
                search: `?source=${JSON.stringify(omitId(record))}`,
            }}
        />
    ) : null;
    };
    const omitId = ({ _id, ...rest }) => rest;
    
    const TemplateList = (props) => {
      return (
        <List {...props}>
          <Datagrid rowClick='edit'>
            <TextField source='templateName' />
            <TextField source='subject' />
            <TextField source='htmlContent' />
            <TextField source='lang' />
            <CloneElement />
          </Datagrid>
        </List>
      );
    };
````

**Comment by djhi** [comment]
This should be the responsability of your dataProvider. However your solution should work as well

**Comment by jurnet** [comment]
> This should be the responsability of your dataProvider. However your solution should work as well

I don't think so, because the dataProvider transform _id to id but the component remove only id

**Comment by djhi** [comment]
Which probably means your dataProvider does not remove `_id`. It only adds `id` as a copy right?

**Comment by jurnet** [comment]
Yes, I think, I followed your DOCS for the dataProvider with Mongoose.
 I'm new on your project and my code is :
`data: {
                        ...params.data,
                        id: json._id
                    }`

Effectively, it does not remove _id as I can see, but I know how it works.

**Comment by jurnet** [comment]
Another problem is when i decide to clone a RichTextInput , the url look like this : 
`..../templates/create?source={%22templateName%22:%22verify-signup-alert-client%22,%22subject%22:%22Verifier%20votre%20adresse%20email%20${firstname}%20${lastname}%20pour%20valider%20votre%20compte%22,%22htmlContent%22:%22%3C!--%20HEADER%20--%3E\n%3Ctable%20style=\%22height:%20336px;\%22%20border=\%220\%22%20width=\%22100%\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%3E\n%3Ctbody%3E\n%3Ctr%20style=\%22height:%20122px;\%22%3E\n%3Ctd%20style=\%22height:%20122px;\%22%20align=\%22center\%22%20bgcolor=\%22#34495e\%22%3E%3C!--%20[if%20(gte%20mso%209)|(IE)]%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3Ctable%20align=\%22center\%22%20border=\%220\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%20width=\%22500\%22%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20align=\%22center\%22%20valign=\%22top\%22%20width=\%22500\%22%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C![endif]--%3E\n%3Ctable%20class=\%22wrapper\%22%20style=\%22max-width:%20500px;\%22%20border=\%220\%22%20width=\%22100%\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%3E\n%3Ctbody%3E\n%3Ctr%3E\n%3Ctd%20class=\%22logo\%22%20style=\%22padding:%2015px%200;\%22%20align=\%22center\%22%20valign=\%22top\%22%3E%3Cimg%20style=\%22display:%20block;%20font-family:%20Helvetica,%20Arial,%20sans-serif;%20color:%20#ffffff;%20font-size:%2016px;\%22%20src=\%22......static/media/logo-blanc.0f566063.png\%22%20alt=\%22Logo\%22%20width=\%22300\%22%20border=\%220\%22%20/%3E%3C/td%3E\n%3C/tr%3E\n%3C/tbody%3E\n%3C/table%3E\n%3C!--%20[if%20(gte%20mso%209)|(IE)]%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C/td%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C/table%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C![endif]--%3E%3C/td%3E\n%3C/tr%3E\n%3Ctr%20style=\%22height:%20194px;\%22%3E\n%3Ctd%20class=\%22section-padding\%22%20style=\%22padding:%2070px%2015px;%20height:%20194px;\%22%20align=\%22center\%22%20bgcolor=\%22#D8F1FF\%22%3E%3C!--%20[if%20(gte%20mso%209)|(IE)]%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3Ctable%20align=\%22center\%22%20border=\%220\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%20width=\%22500\%22%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20align=\%22center\%22%20valign=\%22top\%22%20width=\%22500\%22%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C![endif]--%3E\n%3Ctable%20class=\%22responsive-table\%22%20style=\%22max-width:%20500px;\%22%20border=\%220\%22%20width=\%22100%\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%3E\n%3Ctbody%3E\n%3Ctr%3E\n%3Ctd%3E%3C!--%20HERO%20IMAGE%20--%3E\n%3Ctable%20border=\%220\%22%20width=\%22100%\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%3E\n%3Ctbody%3E\n%3Ctr%3E\n%3Ctd%3E%3C!--%20COPY%20--%3E\n%3Ctable%20border=\%220\%22%20width=\%22100%\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%3E\n%3Ctbody%3E\n%3Ctr%3E\n%3Ctd%20class=\%22padding\%22%20style=\%22font-size:%2025px;%20font-family:%20Helvetica,%20Arial,%20sans-serif;%20color:%20#333333;%20padding-top:%2030px;\%22%20align=\%22center\%22%3EValider%20votre%20compte%3C/td%3E\n%3C/tr%3E\n%3Ctr%3E\n%3Ctd%20class=\%22padding\%22%20style=\%22padding:%2020px%200%200%200;%20font-size:%2016px;%20line-height:%2025px;%20font-family:%20Helvetica,%20Arial,%20sans-serif;%20color:%20#666666;\%22%20align=\%22center\%22%3EBonjour%20${firstname}%20${lastname},%20Merci%20de%20valider%20votre%20compte%20en%20cliquant%20ici%20:&nbsp;%3C/td%3E\n%3C/tr%3E\n%3C/tbody%3E\n%3C/table%3E\n%3C/td%3E\n%3C/tr%3E\n%3Ctr%3E\n%3Ctd%20align=\%22center\%22%3E%3C!--%20BULLETPROOF%20BUTTON%20--%3E\n%3Ctable%20style=\%22height:%2024px;\%22%20border=\%220\%22%20width=\%22100%\%22%20cellspacing=\%220\%22%20cellpadding=\%220\%22%3E\n%3Ctbody%3E\n%3Ctr%20style=\%22height:%2024px;\%22%3E\n%3Ctd%20class=\%22padding\%22%20style=\%22padding-top:%2025px;%20height:%2024px;\%22%20align=\%22center\%22%3E%3Ca%20href=\%22${tokenLink}\%22%3E${tokenLink}%3C/a%3E%3C/td%3E\n%3C/tr%3E\n%3C/tbody%3E\n%3C/table%3E\n%3C/td%3E\n%3C/tr%3E\n%3C/tbody%3E\n%3C/table%3E\n%3C/td%3E\n%3C/tr%3E\n%3C/tbody%3E\n%3C/table%3E\n%3C!--%20[if%20(gte%20mso%209)|(IE)]%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C/td%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C/table%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3C![endif]--%3E%3C/td%3E\n%3C/tr%3E\n%3Ctr%20style=\%22height:%2020px;\%22%3E\n%3Ctd%20style=\%22padding:%2020px%200px;%20height:%2020px;\%22%20align=\%22center\%22%20bgcolor=\%22#ffffff\%22%3E%3C!--%20[if%20(gte%20mso%209)|(IE)]%3E\n%20%20%20%20%20%20%20%20%20%20%20%20%3Ctable%20align=\%22center\%22%20border=\%22e%3E%22,%22lang%22:%22fr%22,%22updatedAt%22:%222021-01-07T08:53:07.522Z%22,%22id%22:%225ff6c6d018fa0495df4bcba5%22}`

The rich html content not works because of htmlContent,  any idea ?

**Comment by fzaninotto** [comment]
As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/). It's a good way to contribute to the sustainability of react-admin.
