### ISSUE TITLE
Unsave Data Confirmation appears even if the data has been changed

### ISSUE THREAD

**Issue by firdouserp** [marmelab/react-admin#5754]
**What you were expecting:**

No Unsave Data Warning should appear on after Submitting the form via Save

**What happened instead:**

Edit a Post on demo, goto miscelaneous and add a backlink via SimpleformIterator. Click save, A Confirmation warning of losing unsave data appears. It should not appear.
**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue
You can reproduce the error via this sandbox
https://codesandbox.io/s/smoosh-browser-q05kc?file=/src/comments/CommentEdit.js

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for the report. This issue is already tracked with #5267 though
