### ISSUE TITLE
AutocompleteInput doesn't work decorated with RefernceInput

### ISSUE THREAD

**Issue by anjeylink** [marmelab/react-admin#5757]
When using AutocompleteInput decorated with ReferenceInput it should load new possible values using user input as query filter after user starts typing. 

Instead when it trying to load new possible values "AutocompleteInput" disappear and appear again after request was finished with old value of input and old possible values. see video. 

I think this is related to https://github.com/marmelab/react-admin/pull/5731

CodeSandbox
https://codesandbox.io/s/strange-drake-gm82q?file=/src/comments/CommentEdit.js

* React-admin version: 3.11.2
* Last version that did not exhibit the issue: 3.11.1

https://user-images.githubusercontent.com/11900120/104159447-ff4a0280-53f7-11eb-81eb-7cf85802b4fb.mp4

Not possible to filter posts.

https://user-images.githubusercontent.com/11900120/104163386-04f71680-53ff-11eb-955b-c88c1356b908.mp4

**Comment by djhi** [comment]
Please follow the issue template

**Comment by anjeylink** [comment]
@djhi I added CodeSandbox link and another video

**Comment by andrico1234** [comment]
I'm also having the same issue, under the same circumstances. I'll be happy to provide a repro too if it's of any use

**Comment by djhi** [comment]
Thanks for the report. That's a nasty bug indeed

**Comment by etienne-bondot** [comment]
Get this too, from 3.11.2, not present in 3.11.1 if that can help.

**Comment by etienne-bondot** [comment]
I can confirm after testing it that it was introduced by #5731 as @anjeylink said. Reverting locally fix it.

**Comment by fzaninotto** [comment]
Fixed by #5763
