### ISSUE TITLE
Add disabled options in SelectArrayInput

### ISSUE THREAD

**Issue by paulo9mv** [marmelab/react-admin#5759]
**Describe the solution you'd like**
I want to pass a disabled options to some choices in SelectArrayInput, the same way I do with SelectInput

This is supported in material ui, since `MenuItem` has prop disabled but SelectArrayInput is not passing that prop down

**Describe the solution you'd like**

<SelectArrayInput source="status" choices={[
  { id: "DISABLED", name: "disabled", disabled: true},
  { id: "ENABLED", name:"enabled"}
]} />

**Additional context**
I believe it's a similar description and solution as done in this issue here: https://github.com/marmelab/react-admin/issues/2512
I'm able to work on this too.

**Comment by fzaninotto** [comment]
Right, it's useful and similar to #2512. Please open a PR against `next` with you implementation.

**Comment by WiXSL** [comment]
I think this one can be closed

**Comment by fzaninotto** [comment]
Fixed by #5940
