### ISSUE TITLE
useCreateController example in documentation seems to be broken.

### ISSUE THREAD

**Issue by nrobates** [marmelab/react-admin#5779]
Hello!

I am currently working to see if react-admin will fit my needs for a project and I have run into a snag. This could be a lack of knowledge on my part. In the documentation located at, https://marmelab.com/react-admin/CreateEdit.html#usecreatecontroller, the example provided does not work for me and throws the following error:
```
Property 'children' does not exist on type 'CreateProps<Record>'.  TS2339

    19 |             <div>
    20 |                 <h1>{defaultTitle}</h1>
  > 21 |                 {cloneElement(props.children, {
       |                                     ^
```
Is the code example wrong? Should it be doing something different than using `props.children`?

I appreciate the help and advice in advance.

Thank you.

Nick

**Comment by fzaninotto** [comment]
The example shows how to write your custom Create component, but doesn't detail the usage of SimpleForm, which expects input components as children (see https://marmelab.com/react-admin/CreateEdit.html#the-simpleform-component). So when the usage example shows:

```tsx
const PostCreate = props => (
    <MyCreate {...props}>
        <SimpleForm>
            ...
        </SimpleForm>
    </MyCreate>
)
```

You're supposed to replace the ellipsis by Input components. 

I've tested the snippet with Inputs in the form, and it works all right.

**Comment by nrobates** [comment]
Hi @fzaninotto!

Thank you for your response. I do have input components instead of the ellipsis; however, I am still getting the error described.

Upon further investigating on my end, the issue looks to be due to something else. To highlight, in my code, I have the following:

```
const UserCreateForm = (props: CreateProps<Record>) => {
...
```

I was using Typescript and was typecasting the props value to the `CreateProps<Record>` type based on what it is; instead of allowing it to be an `any` type. Changing it to the following fixed the issue entirely. 

```
const UserCreateForm = (props: any) => {
...
```
Your answer did in fact point me to switching that out to be typecasted to `any` instead. 

Again, thank you for your response and assistance. 

Nick
