### ISSUE TITLE
Provide a way to set the AppBar title with custom <Show> components.

### ISSUE THREAD

**Issue by nicohagen** [marmelab/react-admin#5786]
**Is your feature request related to a problem? Please describe.**
The react-admin `<Show>` component sets the AppBar title, consequently when not using it but something custom, the header title remains empty when accessing the `/show`route.

```
function ResourceShow(props) {
  const { record } = useShowController(props)

  return (
    {/* No AppBar title */}
    <CustomShow record={record} />
  )
}
```

**Describe the solution you'd like**
There are several solutions i guess. I'd prefer that `useShowController` just exposed some setter method for the header title.

```
function ResourceShow(props) {
  const { record, setTitle } = useShowController(props)
  setTitle('Hello world!')

  return (
    <CustomShow record={record} />
  )
}
```

**Describe alternatives you've considered**
Alternatively the react-admin `<Show>` could forward its own props to is component prop component. By that, the custom component could access the record via the `useShowController(props)` hook. 
```
const CustomShow = (props) => {
  const { record } = useShowController(props)

  return <div>{record?.data}</div>
}

function ResourceShow(props) {
  return (
  <Show {...props} component={CustomShow} title='Hello world!' actions={null}>
      {/* For some reason a Layout component is required for the Show component to work */}
      <SimpleShowLayout />
    </Show>
  )
}
```
To help myself currently i go for this...

```
const CustomShow = ({ record }) => {
  return <div>{record?.data}</div>
}

const RaShow = withStyles(theme => ({
  noActions: { marginTop: 0 },
}))(Show)

function ResourceShow(props) {
  const { record } = useShowController(props)

  return (
    <RaShow {...props} component='div' title='Hello world!' actions={null}>
      <CustomShow record={record} />
    </RaShow>
)
```
This is not that bad, but it requires me to nest my custom Show inside the react-admin one (instead of replacing it) and i have to override unwanted styles.

I hope all this makes sense to you and if there actually already is a better way to solve the issue then i'd be happy to hear about.

Cheers.

**Comment by dejancg** [comment]
Have you tried to use `Title` component?

```ts
import React from "react";
import { Title, useShowController } from "react-admin";
import { CustomShow } from "...";

interface Props {}

export const YourCustomComponent = (props: Props) => {
  const { record } = useShowController(props);
  return (
    <>
      <Title title="Your custom title" />
      <CustomShow record={record} />
    </>
  );
};

```

**Comment by nicohagen** [comment]
@dejancg No i haven't, did not know about. Works perfect, thanks a lot. Issue can be closed then.
