### ISSUE TITLE
Not Understanable Error 

### ISSUE THREAD

**Issue by ac2epsilon** [marmelab/react-admin#5788]
**What you were expecting:**

I expected ra-data-graphql example will work. 
https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql-simple#usage
And after I copy-pasted code into App.js... (compiling was fine)

**What happened instead:**

... in run time I got following with 2 sec delay after page appearence

Unhandled Rejection (Error): The dataProvider threw an error. It should return a rejected Promise instead.

**Steps to reproduce:**

Copy And Paste App.js from docs, change endpoint to http://ac2spotters.gq/apollo (playground opened, so welcome to play) and what? Even IF it is my own fail like "Not properly configured schema", I'd like to know this, not The dataProvider threw an error.

**Other information:**

**Environment**

* React-admin version: "react-admin": "^3.11.2", "ra-data-graphql-simple": "^3.10.2", "graphql": "^15.4.0"
* Last version that did not exhibit the issue (if applicable): n/a
* React version: "react": "^17.0.1"
* Browser: Версія 86.0.4240.193 (Розробка) (64-розрядна версія)
* Stack trace (in case of a JS error):
Unhandled Rejection (Error): The dataProvider threw an error. It should return a rejected Promise instead.
▼ 22 stack frames were expanded.
performQuery
node_modules/ra-core/esm/dataProvider/useDataProvider.js:512
doQuery
node_modules/ra-core/esm/dataProvider/useDataProvider.js:275
Proxy.
node_modules/ra-core/esm/dataProvider/useDataProvider.js:239
(anonymous function)
node_modules/ra-core/esm/dataProvider/useQueryWithStore.js:180
(anonymous function)
node_modules/ra-core/esm/dataProvider/useQueryWithStore.js:179
invokePassiveEffectCreate
node_modules/react-dom/cjs/react-dom.development.js:23487
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4056

**Comment by fzaninotto** [comment]
Which code snippet did you paste?

**Comment by ac2epsilon** [comment]
> Which code snippet did you paste?
https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql-simple#usage  - right here App.js

**Comment by ac2epsilon** [comment]
It compiled of course - I have got ./post.js , packages etc - all yarn-starts fine

**Comment by ac2epsilon** [comment]
React-admin version: "react-admin": "^3.11.2", "ra-data-graphql-simple": "^3.10.2", "graphql": "^15.4.0",
Last version that did not exhibit the issue (if applicable): n/a
React version: "react": "^17.0.1",
Browser: Версія 86.0.4240.193 (Розробка) (64-розрядна версія)
Stack trace (in case of a JS error):
×
Unhandled Rejection (Error): The dataProvider threw an error. It should return a rejected Promise instead.
▼ 22 stack frames were expanded.
performQuery
node_modules/ra-core/esm/dataProvider/useDataProvider.js:512
doQuery
node_modules/ra-core/esm/dataProvider/useDataProvider.js:275
Proxy.<anonymous>
node_modules/ra-core/esm/dataProvider/useDataProvider.js:239
(anonymous function)
node_modules/ra-core/esm/dataProvider/useQueryWithStore.js:180
(anonymous function)
node_modules/ra-core/esm/dataProvider/useQueryWithStore.js:179
invokePassiveEffectCreate
node_modules/react-dom/cjs/react-dom.development.js:23487
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4056
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js:23574
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:646
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11276
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js:23447
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:22269
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:646
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js:11309
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:21893
enqueueSetState
node_modules/react-dom/cjs/react-dom.development.js:12467
App.push../node_modules/react/cjs/react.development.js.Component.setState
node_modules/react/cjs/react.development.js:365
▲ 22 stack frames were expanded.
(anonymous function)
http://ac2spotters.gq:3000/static/js/main.chunk.js:65:34
  62 |     clientOptions: {
  63 |       uri: 'http://ac2spotters.gq/apollo'
  64 |     }
> 65 |   }).then(dataProvider => this.setState({
     |                                ^  66 |     dataProvider
  67 |   }));
  68 | }
View source

**Comment by ac2epsilon** [comment]
![Знімок екрану_2021-01-17_16-12-28](https://user-images.githubusercontent.com/9274064/104845606-fe750d00-58de-11eb-986c-e9a47dccadc4.png)

**Comment by ac2epsilon** [comment]
Live Demo http://ac2spotters.gq:3000/

**Comment by ac2epsilon** [comment]
I am not sure, if it ought to be considered as separate issue, BUT all the same applies to bare https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql (I mean NOT the bugs per se, but not obvious pathways to solving them). BTW straight C'n'P of https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql#customize-the-apollo-client gives **Failed to compile. ./src/App.js Attempted import error: 'createNetworkInterface' is not exported from 'react-apollo'.**

**Comment by ac2epsilon** [comment]
> You can also supply your own ApolloClient instance directly with:

`buildGraphQLProvider({` client: myClient });

Not really. This will not be thrown as a issue as these errors are here and there. I believe that both GraphQL providers are at least very outdated (createNetworkInterface?!) or, from the user's point of view, broke.

```
        const cache = new InMemoryCache();
        const myclient = new ApolloClient({ cache: cache, uri: 'http://ac2spotters.gq/apollo' });
        console.log(myclient); // looks fine !
// and next line.. nothing good happens - TypeError: buildQueryFactory is not a function
        buildGraphQLProvider({ client: myclient })
           .then(dataProvider => this.setState({ dataProvider }))
           .catch(err => console.log(err)); 
```

**Comment by fzaninotto** [comment]
I could reproduce the error "The dataProvider threw an error. It should return a rejected Promise instead.". Fix incoming.

**Comment by ac2epsilon** [comment]
Vivre La France! And then.. if you so kind today - can you look to other two bugs I mentioned above OR I can make new issues, if mixing topics breaks something.

**Comment by fzaninotto** [comment]
Let's keep this issue for the initial description. 

The providers are indeed outdated. Please look for existing issues about them before opening a new issue.
