### ISSUE TITLE
Create POST url documentation is inaccurate in ja-data-json-server package

### ISSUE THREAD

**Issue by tjsturos** [marmelab/react-admin#5792]
![image](https://user-images.githubusercontent.com/55340199/104905224-ba3f4680-598a-11eb-92b3-f26a2e8fcb57.png)

In the create route, it says `POST http://my.api.url/${resource}/${id}`  but it should `POST http://my.api.url/${resource}` as you wouldn't have the ID-- and the actual code backs this up:

![image](https://user-images.githubusercontent.com/55340199/104905497-1c984700-598b-11eb-969a-9bfa1c2173c9.png)

**Comment by djhi** [comment]
Good catch! Would you mind opening a pull request to fix it?

**Comment by tjsturos** [comment]
Sure can!
