### ISSUE TITLE
The save button on the creation page is inactive if all fields has initial value.

### ISSUE THREAD

**Issue by Dunkaj** [marmelab/react-admin#5796]
Hello.

I have two date inputs with initial value and validate.
The form is completely filled, but the save button is not active. 
Save button will become active only after changing any of the values.

`export const ReportCreate = (props) => (<Create {...props}>
    <SimpleForm>
        <DateInput source="fromDate" validate={[required()]}
                   initialValue={moment().subtract(6, "days").format("YYYY-MM-DD")}/>
        <DateInput source="toDate" validate={[required()]} initialValue={moment().format("YYYY-MM-DD")}/>
    </SimpleForm>
</Create>);`

![image](https://user-images.githubusercontent.com/23344940/104969852-4b95d380-59f2-11eb-971b-b8eba79b6fec.png)

react-admin v3.11.3

**Comment by fzaninotto** [comment]
Yep, that's a feature. And the doc explains how to turn it off if it doesn't suit you.

https://marmelab.com/react-admin/CreateEdit.html#toolbar
