### ISSUE TITLE
List displays the last last received result, not the result of the last query.

### ISSUE THREAD

**Issue by Dunkaj** [marmelab/react-admin#5797]
Hello.
The problem concerns the List page.
After the change in the filter fields, a new request is sent.
It turns out that if the last query was processed faster than the previous one, the data in the filter will not match the result found. Because the list displays the last last received result, not the result of the last query.

react-admin v3.11.3

**Comment by fzaninotto** [comment]
That's a known limitation of react-admin that we don't have a simple way to fix. Your users will have to live with that, sorry.
