### ISSUE TITLE
Document `linkToRecord`

### ISSUE THREAD

**Issue by jgabriele** [marmelab/react-admin#5801]
## Problem
I recently had to implement a custom `ReferenceField` in order to show multiple field of the reference.

![image](https://user-images.githubusercontent.com/395650/105164288-3f566700-5b15-11eb-970b-97197869a94a.png)

Every field has a link to a different url.

## Solution
I found no place in the doc to implement custom fields like this, so by having a look at the implementation I found out you were using [getResourceLinkPath](https://github.com/marmelab/react-admin/blob/f7d978debf3f101b88dc27973d76e295990a61c8/packages/ra-core/src/controller/field/getResourceLinkPath.ts#L47) which was using `linkToRecord`.

I ended up with something like this:

```javascript
const MyCustomReferenceField = ({ record: article }) => {
  const { loading, referenceRecord: seller } = useReference({
    reference: 'users',
    id: article.seller.id,
  })

  if (loading) {
    return <LinearProgress />
  }

  if (!seller) {
    return null
  }

  const linkToUser = linkToRecord('users', seller.id, 'show')

  return (
    <>
      <div>
        <Link to={linkToUser}>{seller.username}</Link>
      </div>
      <div>
        <Link to={`${linkToUser}/log`}>{seller.id}</Link>
      </div>
    </>
  )
}
```

Do you also think `linkToRecord` could be mentionned in the doc? (At least in the [Reference](https://marmelab.com/react-admin/Reference.html) page)

**Comment by djhi** [comment]
Yes, it would be a great addition! Would you mind opening a PR?

**Comment by jgabriele** [comment]
Sure, I'll do that this week or the next one 👍

**Comment by jgabriele** [comment]
@djhi Done – https://github.com/marmelab/react-admin/pull/5860
