### ISSUE TITLE
[Question] Why does ReferenceInput default sort by descending id?

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#5803]
This just seems weird. Is there a reason behind it?

**Comment by djhi** [comment]
That's the only field react-admin requires.

**Comment by davidhenley** [comment]
@djhi what I asked was why descending?

**Comment by davidhenley** [comment]
@djhi what I asked was why descending?

**Comment by fzaninotto** [comment]
Because that's what we need most of the time - the most recent first. If that doesn't suit you, you can always set your own sort prop.
