### ISSUE TITLE
ReferenceInput does not show loader while possible values and reference record are loading

### ISSUE THREAD

**Issue by anjeylink** [marmelab/react-admin#5805]
**What you were expecting:**
When using ReferenceInput expect to get LinearProgress instead of empty input (SelectInput or any other valid children) while data is loading. 
I manually set delay in dataProvider to 3 seconds, but loader wasn't shown. 

**What happened instead:**
ReferenceInput renders children like data was loaded, but in reality it's still loading. 

**Steps to reproduce:**
Add ReferenceInput in create/edit form. Simulate delay in data provider more than 1 sec.

```
<ReferenceInput reference="reference" source="source">
    <SelectInput optionText="name" />
</ReferenceInput>
```

**Possible solution**
I think problem is in "useReferenceInputController" when it generates "dataStatus.waiting", because finalData is always empty object and "matchingReferences" will be always empty array.

```
const dataStatus = getDataStatus({
    input,
    matchingReferences: Object.keys(finalData).map(id => finalData[id]),
    referenceRecord,
    translate,
});
```

**Other information:**
There was already issue opened
https://github.com/marmelab/react-admin/pull/5731
https://stackoverflow.com/questions/65488613/react-admin-referenceinput-doesnt-show-loading-linearprogress-while-loading?noredirect=1#comment115901905_65488613

CodeSandbox
https://codesandbox.io/s/admiring-monad-uludk?file=/src/dataProvider.js

**Environment**

* React-admin 3.11.3

https://user-images.githubusercontent.com/11900120/105323332-ac7c0200-5bd2-11eb-91bf-7f7c28fc9143.mp4

**Comment by djhi** [comment]
Yes, we had a fix which has been reverted in 3.11 because it introduced other issues. We fixed it in 3.12 by giving the loader display responsability to the ReferenceInput children. See https://github.com/marmelab/react-admin/pull/5767
