### ISSUE TITLE
Extended AutocompleteInput with function optionText prop clears itself right after input

### ISSUE THREAD

**Issue by IAmVisco** [marmelab/react-admin#5807]
**What you were expecting:**
During input, the text stays in the text field, allowing you to scroll through the list of options.

**What happened instead:**
A few hundred milliseconds after input is complete (I assume on network request?), the text input field is cleared, which causes another network request, making AutocompleteInput effectively useless.

**Steps to reproduce:**
1. Write a custom component that has AutocompleteInput wrapped into ReferenceInput (L33 `CustomAutocomplete` in the sandbox). If those two components are directly supplied to the `Filter`, the bug does not appear.
2. Write custom optionText formatter (L34 `formatComment` in the sandbox). It has to be a function - if a string passed as a prop, the bug does not appear.
3. Put custom AutocompleteInput inside `Filter` (L45 in the sandbox).
4. Try entering any value and waiting for a bit - entered text will disappear from the textbox.
Demo GIF:
![n3UAGUy4oR](https://user-images.githubusercontent.com/18630605/105341286-f6bfac00-5bef-11eb-8c1e-538a73467888.gif)

**Related code:**
Sandbox: https://codesandbox.io/s/priceless-worker-tds62?file=/src/posts/PostList.js

**Environment**

* React-admin version: 3.11.3 (was able to reproduce on 3.10.1 and 3.10.4 too)
* Last version that did not exhibit the issue (if applicable): Will update after more testing.
* React version: 17.0.1
* Browser: Chrome 87
* Stack trace (in case of a JS error): -

**Comment by djhi** [comment]
Thanks for the report!

**Comment by djhi** [comment]
While we try to fix this issue, can you try the following workaround ? Extract the optionText function outside the component.

```jsx
const formatComment = (comment) => comment.body;

const CustomAutocomplete = (otherProps) => {
  return (
    <ReferenceInput {...otherProps}>
      <AutocompleteInput optionText={formatComment} />
    </ReferenceInput>
  );
};
```

**Comment by IAmVisco** [comment]
That works both in the sandbox and locally. Though, locally I'm using some props that come to the component to influence formatting (like full name or not etc), so makes it a bit harder but I can think about more workarounds in the meantime. Thanks!

**Comment by jcarrancia-toothpic** [comment]
hey @IAmVisco I'm running into the same issue, did you find a workaround for the formatting? 
Thanks!

**Comment by IAmVisco** [comment]
@jcarrancia-toothpic Exactly like in the example djhi posted above - by moving formater function outside the component.

**Comment by berenddeboer** [comment]
Also ran into this, would be nice to have fixed, because as like @IAmVisco I also need access to props, and haven't found a workaround for that.

**Comment by WiXSL** [comment]
I can't reproduce this bug with the latest version of `react-admin`

**Comment by IAmVisco** [comment]
Seems to work fine in the sandbox, thanks guys!
