### ISSUE TITLE
CSS is distorted in develop and working fine in local enviornment

### ISSUE THREAD

**Issue by Anubhavv23** [marmelab/react-admin#5808]
I am using react-admin version - 2.9.9 and mui-datatables version - 3.7.4, table is looking fine in local environment but distorted
![Screenshot from 2021-01-21 19-21-04](https://user-images.githubusercontent.com/62381158/105359786-d9093b80-5c1d-11eb-81db-3dce5be08659.png)
 in develop server.

**Comment by djhi** [comment]
Have you seen https://marmelab.com/react-admin/FAQ.html#ui-in-production-build-is-empty-or-broke? Double check that you don't have multiple versions of material-ui packages

**Comment by fzaninotto** [comment]
Also, we don't support version 2 anymore. I suggest you test with react-admin version 3.

**Comment by Anubhavv23** [comment]
@djhi should I have to install @material-ui/core ?

**Comment by djhi** [comment]
If you installed react-admin, no. But if mui-datatables depends on another version than the one used in this old version of react-admin, you might have duplicates

**Comment by djhi** [comment]
Anyway, that's not a bug in react-admin and I invite you to post this kind of questions on StackOverflow
