### ISSUE TITLE
Add state indicators to Autocomplete inputs

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#5814]
**Is your feature request related to a problem? Please describe.**
I've added a short clip below demonstrating a problem I'm having.

I want to use the `ReferenceInput` along with the `AutocompleteInput` to pull in email addresses. For slow connections, there's no state indicator to help discern whether the query being fired is loading, or has loaded and has no records to display.

This is especially noticeable on slower connections.

https://user-images.githubusercontent.com/17087167/105701012-97201400-5f01-11eb-824c-359fbdf16ec6.mov

**Describe the solution you'd like**
For the _loading_ state:

A non-clickable option that says 'loading' or uses the small spinner displayed in the top right corner when a request is being made. 

For the _no results_ state:

A non-clickable option that says 'no results match your query' or equivalent.

I'm not too sure whether this is something that can be implemented realistically, because I know that RA uses downshift to render the Autocomplete component.

Saying that, it might be possible to implement by passing that current state to the `AutocompleteSuggestionList`.

I'll be happy to open a PR if this sounds like something that should be added

**Additional context**

**Comment by djhi** [comment]
Thanks for the feature request. It has already been adressed in https://github.com/marmelab/react-admin/pull/5767
