### ISSUE TITLE
Bug : useListContext // ListContextProvider

### ISSUE THREAD

**Issue by Angerel** [marmelab/react-admin#5816]
Good morning,
I apologize in advance for my English level as I am French (and if you're brave enough I'd like some corrections, to improve).
I was programming a customer list, with a custom query, and I chose to use ListContextProvider, from the lib 'react-admin', and the Datagrig component, from the same lib

**What you were expecting:**
I was expecting the ListContextProvider to pass the parameters from the value prop to the ListContext then to the Datagrid that will show the data.

**What happened instead:**
I instead got an error from Datagrid.js "cannot read property field of undefined", refering to currentSort being undefined, while I have set it in the value array of ListContextProvider

**Steps to reproduce:**
I'll paste the minimal code in order to let you see how to reproduce

**Related code:**

```
import { useState, useEffect } from 'react';
import {
    Loading,
    Datagrid,
    TextField,
    ListContextProvider,
    useListContext
 } from 'react-admin';
 import keyBy from 'lodash/keyBy';

export const CustomList = props => {

    const data = [
        {id:0,firstName:"James", lastName:"Lembrand"},
        {id:1,firstName:"Frederich", lastName:"Lanovski"},
        {id:2,firstName:"Uriel", lastName:"Obril"}
    ];

    return(
            <ListContextProvider value={{
                currentSort: { field: 'id', order: 'ASC' },
                page:1,
                perPage:10,
                selectedIds:[],
                data:keyBy(data, 'id'),
                ids: data.map(({id})=>id),
                total:3,
                basePath:"/client",
                resource:"client",
                defaultTitle:"Clients"
            }}>
                <Datagrid>
                    <TextField label="Prénom" source="firstName" />
                    <TextField label="Nom" source="lastName" />
                </Datagrid>
            </ListContextProvider>
    )
};
```

**Other information:**
I found how to fix this, by searching in the source code
I've seen that Datagrid uses "useListContext" from 'ra-core', and not from 'react-admin', so I've tried importing ListContextProvider from 'ra-core' and the page showed me the data I wanted.
Still, I'm not sure why the ListContext from react-admin and from ra-core are different, and I decided to report this to be enlighted and to inform you and your team

**Environment**

* React-admin version: 3.11.4
* Last version that did not exhibit the issue (if applicable): I didn't test this
* React version: 17.0.1
* Browser: Chrome
* Stack trace (in case of a JS error):
Uncaught TypeError: Cannot read property 'field' of undefined
    at Datagrid.js:79
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)
    at beginWork (react-dom.development.js:19098)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at scheduleUpdateOnFiber (react-dom.development.js:21881)
    at updateContainer (react-dom.development.js:25482)
    at react-dom.development.js:26021
    at unbatchedUpdates (react-dom.development.js:22431)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020)
    at Object.render (react-dom.development.js:26103)
    at Module.<anonymous> (index.js:7)
    at Module../src/index.js (index.js:9)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Object.1 (routes.js:12)
    at __webpack_require__ (bootstrap:856)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1

Thank you in advance for your kindness, and please excuse my syntax

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by Angerel** [comment]
I don't think this is a "How to" question, because it is a bug report, please reconsider my request

**Comment by fzaninotto** [comment]
You probably have mismatched dependencies on react-admin and ra-cor ein your package.json. I don't believe it's a react-admin bug, but a problem on your side. That's why @djhi closed your issue.

**Comment by Angerel** [comment]
Oh, my mistake, I'll try to update my package.json, thank you for the enlightment
