### ISSUE TITLE
Edit onSuccess prop doesn't work correctly

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#5819]
**What you were expecting:**
Expected to work as stated in the documentation

> The onSuccess function receives the response from the dataProvider call (dataProvider.create() or dataProvider.update()), which is the created/edited record (see the dataProvider documentation for details)

**What happened instead:**
Instead, onSuccess is called immediately after Save action , and the data parameter is empty

**Steps to reproduce:**
Copy the code from the documentation and apply

https://codesandbox.io/s/proud-water-10dbo?file=/src/posts/PostEdit.js
after adding code from documentation codeandbox hangs on save

* React-admin version:3.11.4

**Comment by djhi** [comment]
Thanks for the report.
