### ISSUE TITLE
Installing latest versions of graphql and ra-data-graphql-simple fails.

### ISSUE THREAD

**Issue by pj** [marmelab/react-admin#5824]
**What you were expecting:**
Installing the latest versions of graphql and ra-data-graphql-simple in an empty npm project would install correctly.

**What happened instead:**
The following error is thrown:

```
פֿ npm install --save graphql ra-data-graphql-simple           1 ~/temp/test_react_admin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: graphql@15.5.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^14.1.1" from ra-data-graphql-simple@3.11.4
npm ERR! node_modules/ra-data-graphql-simple
npm ERR!   ra-data-graphql-simple@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/pauljohnson/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pauljohnson/.npm/_logs/2021-01-28T00_46_16_159Z-debug.log
```

**Steps to reproduce:**
Create a directory:

mkdir test_react_admin
cd test_react_admin

Install graphql and ra-data-simple-graphql:

npm install --save graphql ra-data-graphql-simple

**Other information:**
installing react-admin and ra-data-graphql-simple also fails:

```
פֿ npm install --save react-admin ra-data-graphql-simple         ~/temp/test_react_admin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.9.0 || ^17.0.0" from ra-core@3.11.4
npm ERR!   node_modules/ra-core
npm ERR!     peer ra-core@"^3.9.0" from ra-data-graphql-simple@3.11.4
npm ERR!     node_modules/ra-data-graphql-simple
npm ERR!       ra-data-graphql-simple@"*" from the root project
npm ERR!   peer react@"^16.4.0" from connected-react-router@6.8.0
npm ERR!   node_modules/connected-react-router
npm ERR!     peer connected-react-router@"^6.5.2" from ra-core@3.11.4
npm ERR!     node_modules/ra-core
npm ERR!       peer ra-core@"^3.9.0" from ra-data-graphql-simple@3.11.4
npm ERR!       node_modules/ra-data-graphql-simple
npm ERR!         ra-data-graphql-simple@"*" from the root project
npm ERR!   2 more (react-redux, react-router)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-dom@17.0.1
npm ERR! node_modules/react-dom
```

**Environment**

* React-admin version: 3.11.4
* Last version that did not exhibit the issue (if applicable):
* React version: N/A
* Browser:
* Stack trace (in case of a JS error):

**Comment by pj** [comment]
Hmm, I was able to get this to install correctly using:

    npm install --save graphql@^14.1.1 ra-data-graphql-simple react@^16.9.0 react-dom@^16.9.0 react-admin

Not sure if this is really a bug then.

**Comment by djhi** [comment]
This is very weird but I fail to see what we can do about it

**Comment by oseisaac** [comment]
Experiencing the same issues

`$ npm upgrade
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: stack-wiser-project@0.1.0
npm ERR! Found: graphql@15.5.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^15.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2
npm ERR! node_modules/apollo-link-persisted-queries
npm ERR!   apollo-link-persisted-queries@"^0.2.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\oseis\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oseis\AppData\Local\npm-cache\_logs\2021-02-22T18_41_28_095Z-debug.log`
