### ISSUE TITLE
demo it's Can't work 

### ISSUE THREAD

**Issue by houtianxi** [marmelab/react-admin#5825]
i am clone \examples\demo to local  folder c:\react-admin-demo,
1: npm install
2: npm run start 
open :http://localhost:3000/
 but it's cant't work. 
![image](https://user-images.githubusercontent.com/3362680/106108975-f68d5680-6183-11eb-8941-07fc6c49c2fc.png)

**Comment by djhi** [comment]
This is a monorepo. I don't get how you just clone the demo. Please follow the readme instructions: https://github.com/marmelab/react-admin#examples
