### ISSUE TITLE
[Docs] Linking inputs - additional methods

### ISSUE THREAD

**Issue by vdimitroff** [marmelab/react-admin#5830]
**Is your feature request related to a problem? Please describe.**
About half an year later since using the react-final-forms inside react-admin I have found out that the forms library suports decorators and react-component event listeners.

The above methods save me a huuuge amount of time and bring down the whole complexity around inputs communication and dependancy.

- [final-form-calculate](https://github.com/final-form/final-form-calculate)
- [react-final-form-listeners](https://github.com/final-form/react-final-form-listeners)

**Describe the solution you'd like**
I suggest including a tiny hint sentence with links under the [Inputs/Linkining-two-inpits](https://marmelab.com/react-admin/Inputs.html#linking-two-inputs) part and maybe a short example.

I also understand that react-admins documentation purpose is not to document other libraries but as these two are so closly coupled and rff's documentaion is quite unhandy I think it will be useful for ra users.

If you fancy the suggestion I will gladly submit a PR.

**Comment by djhi** [comment]
Hi and thanks for the suggestion. As you mentionned, we do not intend to document the final-form library as we would have to maintain it and keep it up to date. The documentation already mention we use this library.
