### ISSUE TITLE
Consider using `unknown` instead of `any`

### ISSUE THREAD

**Issue by antoine-pous** [marmelab/react-admin#5834]
Hi!

I'm currently discovering React Admin and this is a really cool project, i'm really impressed :+1: 

I'm using typescript in a really strict way, and i noticed that your project use `any` type in many places instead of `unknown`. `any` is mostly a hack which disable the type checking, `unknown` remain typesafe which is what we expect in any cases.

Can you consider to refactor this part?

Have a nice day

**Comment by djhi** [comment]
Very good point, thanks! Would you mind helping us?

**Comment by fzaninotto** [comment]
From what I understand by reading https://stackoverflow.com/questions/51439843/unknown-vs-any/51439876#51439876, using `unknown` would require additional work by developers to set the type before using the value. I'm not sure we want that.

Could you give an concrete example of a type in the react-admin code that would benefit from `unknown`, and explain why with a concrete example?

**Comment by fzaninotto** [comment]
No news for some time, closing.
