### ISSUE TITLE
documentation: <Button> not documented

### ISSUE THREAD

**Issue by elsni** [marmelab/react-admin#5847]
**What you were expecting:**
Finding the react-admin component `<Button>` in the reference list and a linked documentation page

**What happened instead:**
`<Button>` is missing

**Steps to reproduce:**
Open reference of 3.12.0 documentation

**Comment by fzaninotto** [comment]
There are a lot of undocumented react-admin components. If we have one issue open for each of them, we won't be able to track other issues. So I'm closing this one. 

We know we need to improve with the API documentation. If you want to give a hand, you're welcome to submit a PR. 

In the meantime, please refer to the source code and the associated jsDoc and TypeScript types.
