### ISSUE TITLE
<Edit mutationMode="pessimistic"> produces "undoable" delete action in toolbar

### ISSUE THREAD

**Issue by despatates** [marmelab/react-admin#5854]
**What you were expecting:**
With `<Edit mutationMode="pessimistic" />`, clicking on the delete button should open a confirmation dialog like it does with `undoable={false}`.

**What happened instead:**
With `<Edit mutationMode="pessimistic" />`, clicking on the delete button deletes the resource like it does with `mutationMode="undoable"`.
A notification is shown with an "undo" action.

**Steps to reproduce:**
Create an edit form on a resource, and set pessimistic mutation mode.
In the toolbar at the bottom, click on the delete button.

https://user-images.githubusercontent.com/3403829/106747935-d4cd1d00-6624-11eb-9439-7930ba9a00ff.mp4

**Related code:**

```js
import * as React from 'react';
import { DeleteButton, Edit, SaveButton, SimpleForm, TextInput, Toolbar } from 'react-admin';

const UserEdit = props => (
  <Edit {...props} mutationMode="pessimistic">
    <SimpleForm redirect="show">
      <TextInput source="name" />
      <TextInput source="email" />
    </SimpleForm>
  </Edit>
);
```

The result is the same with a custom toolbar, following the [documentation example](https://marmelab.com/react-admin/doc/3.12/CreateEdit.html#mutationmode):

```js
import * as React from 'react';
import { DeleteButton, Edit, SaveButton, SimpleForm, TextInput, Toolbar } from 'react-admin';

const CustomToolbar = props => (
  <Toolbar {...props}>
    <SaveButton />
    <DeleteButton mutationMode="pessimistic" />
  </Toolbar>
);

const UserEdit = props => (
  <Edit {...props} mutationMode="pessimistic">
    <SimpleForm redirect="show" toolbar={<CustomToolbar />}>
      <TextInput source="name" />
      <TextInput source="email" />
    </SimpleForm>
  </Edit>
);
```

**Environment**

* React-admin version: 3.12.0
* React version: 16.14.0
* Browser: Chrome 88.0.4324.96

**Comment by djhi** [comment]
Thanks for the report. Indeed, the `DeleteButton` has its `undoable` prop set to `true` by default

**Comment by djhi** [comment]
Sorry I misread. So we actually don't propagate mutationMode accross all actions in a view. This would be a feature request. Howver there is also an issue with the `DeleteButton` which has `undoable` prop set to `true` by default. This prevent users to set another `mutationMode`. This is an issue. I'll fix this issue asap and add a feature request tag here

**Comment by nckenn** [comment]
@despatates not related to the issue, just want to ask are you using RA Enterprise Edition?

**Comment by despatates** [comment]
@nckenn No, I'm not. Why?

**Comment by djhi** [comment]
Closed automatically by Github but should be kept open for the feature request

**Comment by fzaninotto** [comment]
The description mentions a bug that you've fixed. What's the feature request?

**Comment by djhi** [comment]
The propagation of the `mutationMode` accross all actions in a view

**Comment by fzaninotto** [comment]
As seen on the phone with @djhi, we agree that the bug is now fixed, so I'm closing this issue.

**Comment by nckenn** [comment]
@despatates can you share your AppBar?

**Comment by despatates** [comment]
@nckenn My AppBar is very simple, it's a merge between react-admin and Material-UI components.

https://gist.github.com/despatates/3e92ea856ee2db4ddb870e3a0bfa9c3b
If you have any questions please comment on the gist.
