### ISSUE TITLE
Resource with icon, conflict with Redux (non-serializable value)

### ISSUE THREAD

**Issue by adrien-may** [marmelab/react-admin#5856]
**What you were expecting:**
I followed official documentation setting my own <Resource> with icons (from @material-ui/icons)
Using <Resource ... icon={MyIcon} ...>, no warning raises from redux.
 
**What happened instead:**
Using the app, I get several times messages in my console like the following:

```
A non-serializable value was detected in the state, in the path: `admin.resources.my_resource.props.icon.$$typeof`. Value: Symbol(react.memo)
Take a look at the reducer(s) handling this action type: RA/FETCH_START
```

(this react.memo is the Icon being stored)
(It happens in many actions, `FETCH_START` is just an example.)

**Steps to reproduce:**
I haven't tried to replicate this issue on an empty react-admin project yet. If you never saw that before, it may definitely comes from my setup, feel free to close this issue.

A while ago, using plain javascript, I was "cheating" storing icon as a "string" and retrieving icon in my custom menu by hand. That worked for a while. I'm switching to typescript and you Resource.icon types expects a ComponentType, not a string. Your solution with icon={MyIcon} seems much cleaner anyway. The number of warning in the web console makes me think we're doing something wrong ?

**Environment**

* React-admin version: 3.12 (but I already had this problem on earlier versions)
* React: 16

**Comment by adrien-may** [comment]
Hum sorry, I figured it out.

I'm using a custom store with redux-persist.

```javascript
const store = configureStore({
  reducer: persistedReducer,
  middleware: [
    ...getDefaultMiddleware({
      serializableCheck: false
    }),
    sagaMiddleware,
    routerMiddleware(history)
  ]
})
```

With this code, I get rid of all warnings, I guess a better options could be provided instead of "false":
I tried but with no luck. 

Unless you got further question, I guess you can close safely this issue. I still wonder if this is relevant to store the icon "as is" though. Anyway, I consider it fixed on my side.

**Comment by fzaninotto** [comment]
That means we're storing the icon in the Redux state, and that's bad anyway. I'm marking this as a bug.

**Comment by fzaninotto** [comment]
So we're storing every Resource props in Redux, including the icon, to be able to retrieve them when we need. For the icon, we need it in the `<Menu>` component, and developers may use it in other places (e.g. to render a button to a resource of another type). 

The only way we can avoid putting the icon in Redux is to introduce yet another React context to store what we currently store in Redux. But, as the Resources may be dynamic, this context can cause multiple app redraws...

As there is a workaround, this is considered low-priority, and we'll probably not work on it before the next major version.

**Comment by WiXSL** [comment]
This has been fixed for `next` branch.
I'm closing this issue.

**Comment by gi-t-ansari** [comment]
Upon refreshing the icons are gone. How to overcome that?

**Comment by fzaninotto** [comment]
@gi-t-ansari This is a closed issue, please open a new issue with a proper reproduction on the latest version if you think there is a bug.
