### ISSUE TITLE
French missing translation: ra.navigation.skip_nav

### ISSUE THREAD

**Issue by cpetit-sigma-fr** [marmelab/react-admin#5862]
Hello,

I get a message in the Firefox console about a missing translation "ra.navigation.skip_nav".

English version contains that key.

To avoid that message in console, I just added a line before using frenchMessages:
```js
__frenchMessages.ra.navigation.skip_nav = '??? Skip to content ???';__
const messages = {
    'fr': frenchMessages,
};
const i18nProvider = polyglotI18nProvider(() => frenchMessages, 'fr');
````

As I don't know the use context of this translation, I can't even suggest a french sentence to replace it.

Cheers!

$ yarn list ra-language-english ra-language-french
yarn list v1.22.5
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ ra-language-english@3.12.0
└─ ra-language-french@3.12.0

**Environment**

* React-admin version: 3.12.0
* Last version that did not exhibit the issue (if applicable): -
* React version: 17.0.1
* Browser: -
* Stack trace (in case of a JS error): -

**Comment by fzaninotto** [comment]
Already fixed by #5841
