### ISSUE TITLE
[Typescript] options are not typed

### ISSUE THREAD

**Issue by HendrikRoehm** [marmelab/react-admin#5868]
**What you were expecting:**
On using `useGetOne` and `useGetMany` the options argument should be typed.

**What happened instead:**
The options have any type.

**Related code:**
In [useGetMany](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useGetMany.ts), I would suggest:
```ts
{
    onSuccess: ({ data: (Record | undefined)[]}) => void,
    onFailure: (error: any) => void
}
```
Additionally, Query should use the same types instead of just callback.

In [useGetOne](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useGetOne.ts) options have any type as well.

**Comment by fzaninotto** [comment]
Fixed by #5849
