### ISSUE TITLE
DeleteButton resource is not passed down

### ISSUE THREAD

**Issue by ybrodsky** [marmelab/react-admin#5869]
**Is your feature request related to a problem? Please describe.**
I have a resource named `answers` and another named `questions`. Within a route belonging to `answers` I have a list of `questions` displayed in a table. I want to use the `DeleteButton` to be able to delete a question from here. The `DeleteButton` accepts an attribute `resource` but it's only used to display the confirmation message. 
When the time comes that RA does the actual delete request, it gets the resource from the context, in this case the wrong resource `answers`. You can see here https://github.com/marmelab/react-admin/blob/0deb2b5d59db5d8720b8f6a2ba8468331567e19a/packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx#L53 where the `resource` is no longer passed down.

**Describe the solution you'd like**
To be able to pass `resource` to the `DeleteButton` and that property be passed down up until here https://github.com/marmelab/react-admin/blob/0deb2b5d59db5d8720b8f6a2ba8468331567e19a/packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx#L83 so that you are able to manually overwrite the context resource.

**Describe alternatives you've considered**
I managed to resolve my problem using this:
```
<ResourceContextProvider value="questions">
  <DeleteButton resource="questions" />
</ResourceContextProvider>
```
but it took me 1 hour of digging through your code, when the instinctively solution is to simply use the `resource` attribute in the button and have it pass down.

**Comment by djhi** [comment]
Hi and thanks for the report. That's a bug indeed.
