### ISSUE TITLE
SSR usage throws: Hash history needs a DOM

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#5896]
I would argue that react-admin does not required to be server side rendered,
but the if you for example use it in nextjs it will probably get server side rendered by default. So developers need to be careful and dynamic load it with ssr:false. It would be good if react-admin would work in ssr without crashing, even if it just renders empty on the server

**What you were expecting:**

when used in SSR, react-admin throws:

`Error: Invariant failed: Hash history needs a DOM`

**What happened instead:**

the defaults with hash-router does not throw an error, instead it just renders empty on the server

**Steps to reproduce:**

- create an empty nextjs app
- add this page:

```
import React from 'react';

import {
  Admin,
  Create,
  Datagrid,
  Edit,
  EditButton,
  List,
  Resource,
  ShowButton,
  SimpleForm,
  TextField,
  TextInput,
} from 'react-admin';
import fakeDataProvider from 'ra-data-fakerest';

const dataProvider = fakeDataProvider({
  posts: [
    { id: 0, title: 'Hello, world!' },
    { id: 1, title: 'FooBar' },
  ],
});

const PostList = (props) => {
  return (
    <List {...props}>
      <Datagrid>
        <TextField source="id" />
        <TextField source="title" />
        <EditButton />
        <ShowButton />
      </Datagrid>
    </List>
  );
};

export const PostEdit = (props) => (
  <Edit title="Edit a Page" {...props}>
    <SimpleForm label="summary">
      <TextInput disabled source="id" />
      <TextInput source="title" />
    </SimpleForm>
  </Edit>
);

export const PostCreate = (props) => (
  <Create title="Edit a Page" {...props}>
    <SimpleForm label="summary">
      <TextInput source="title" />
    </SimpleForm>
  </Create>
);

const posts = {
  list: PostList,
  create: PostCreate,
  edit: PostEdit,
};

export default function ReactAdminExample() {
 
  return (
    <Admin dataProvider={dataProvider} title="Example Admin">
      <Resource name="posts" {...posts} />,
    </Admin>
  );
}

```

**Related code:**

see aboe

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.12.1
* Last version that did not exhibit the issue (if applicable): not sure, i think it worked at some point
* React version: 17.0.0
* Browser: chrome

**Comment by fzaninotto** [comment]
You can pass you own history to react-admin in this case: https://marmelab.com/react-admin/Admin.html#history

**Comment by macrozone** [comment]
@fzaninotto i would argue that you still want to use hash routes in many cases (e.g. when integrating react-admin in an existing app that already has routing). In particular in nextjs, which has its own routing, you still want to have hash-router. Is there a no-op history for server then?
