### ISSUE TITLE
selectedIds.includes is not a function when use FilterLiveSearch component

### ISSUE THREAD

**Issue by fabienlege** [marmelab/react-admin#5901]
**What you were expecting:**

A working component who do not crash my app

**What happened instead:**

App crash when you try to **enter text** in search field

**Steps to reproduce:**

please see this fiddle : https://codesandbox.io/s/adoring-dust-7hu5e?file=/src/posts.js

**Warning** : Because render zone in jsFiddle is too small (half screen), app is rendered in responsive mode and aside not appear at left of User list. Please extends preview panel width or open render in new tab to show aside containing FilterLiveSearch.

If you try to click in search field, APP crash with error `selectedIds.includes is not a function`.
Corresponding code is in posts.js file, line 26 to 32

**Related code:**

posts.js file, line 26 to 32 in my JsFiddle

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.12.1
* Last version that did not exhibit the issue (if applicable):
* React version: last
* Browser:Firefox
* Stack trace (in case of a JS error):
```
TypeError
selectedIds.includes is not a function
evaluate/DatagridBody</<
https://7hu5e.csb.app/node_modules/ra-ui-materialui/esm/list/datagrid/DatagridBody.js:56:29
evaluate/DatagridBody<
https://7hu5e.csb.app/node_modules/ra-ui-materialui/esm/list/datagrid/DatagridBody.js:40:17
renderWithHooks
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:10792:31
updateForwardRef
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12267:24
beginWork$1
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:13582:20
callCallback
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:149:18
invokeGuardedCallbackDev
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:173:20
invokeGuardedCallback
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:204:35
beginWork$$1
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17289:32
performUnitOfWork
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16584:16
workLoopSync
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16569:26
performSyncWorkOnRoot
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16282:15
flushSyncCallbackQueueImpl/<
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8023:28
unstable_runWithPriority
https://7hu5e.csb.app/node_modules/scheduler/cjs/scheduler.development.js:697:12
runWithPriority$2
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:7984:14
flushSyncCallbackQueueImpl
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8019:28
flushSyncCallbackQueue
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8010:7
discreteUpdates$1
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16391:11
discreteUpdates
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:839:16
dispatchDiscreteEvent
https://7hu5e.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3714:22
```

**Comment by djhi** [comment]
The component you pass to `aside` is currently cloned by the List which also inject it a lot of props. Don't pass them all to the `Card` component which does not know what to do with them.

You can import the `sanitizeListRestProps` from `react-admin` and use it like this:

```jsx
const CarFilter2 = (props) => (
  <Card {...(sanitizeListRestProps(props))}>
    <CardContent>
      <FilterLiveSearch source="username" />
    </CardContent>
  </Card>
);
```
