### ISSUE TITLE
Scroll to top with sticky list header was covered by top navigation bar

### ISSUE THREAD

**Issue by Cherkov** [marmelab/react-admin#5902]
**What you were expecting:**

When I'm in a List view try to scroll top and my list header are sticky I want to see that list header moves a little bit down and top bar menu not cover it.

**What happened instead:**

 on "React-Admin" demo you can see the same issue here: 
![image](https://user-images.githubusercontent.com/30770969/107762775-33398000-6d36-11eb-9403-034a1dbb34f4.png) - screenshot with sticky list header( with **Customer, Last seen, Orders, Spent** etc. fields) when scroll down

![image](https://user-images.githubusercontent.com/30770969/107763041-9c20f800-6d36-11eb-85bd-9bc4a8ad6eae.png) - screenshot with the same list and scroll to top.

**Steps to reproduce:**

1. Open [Demo react-admin]( https://marmelab.com/react-admin-demo/#/customers)
2. Scroll bottom (table head with column names must be visible)
3. Scroll top (table head with column names was covered by top navigation bar)

**Comment by fzaninotto** [comment]
Nice idea! Feel free to submit a PR for it. 

I'll close the issue though as the core team won't address it.
