### ISSUE TITLE
unhandled rejection error when returning rejected promise from custom data provider method

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#5907]
**What you were expecting:**
When returning `Promise.reject(new HttpError(<errMsg>, 200)` from a CUSTOM data provider method, react-admin should show the snackbar notification with the error message.

**What happened instead:**
react-admin throws an unhandled rejection and no error message

**Steps to reproduce:**
Write a custom data provider method, eg for GQL client along these lines:
```
    return this._client.mutate(apolloQuery).then((resp) => (<whatever you return on the happy path>))
    .catch(() => Promise.reject(new HttpError('cannot update ', 200)))
```
where the GQL client throws

**Related code:**
Solution is to add a catch handler to each invocation of your custom data provider method, eg.
```
      dataProvider
        .<custom_method>({<params>})
        .catch((e) => {
          notify(e.message, 'error', null, false, 6000);
        });
```
but this gets a little unwieldy if you need to add it everywhere.

Note: this issue does not show for STANDARD data provider methods since it seems you have an extra catch clause in `useQuery` and `useMutation` for those standard methods to avoid the unhandled rejection
```
            .catch(error => {
                setState({
                    error,
                    loading: false,
                    loaded: false,
                });
            });
```
and you also add a `onFailure` handler in the components that automatically call a standard data provider method.
However for custom methods, which seem to get processed inside `useDataProvider`, it seems a similar catch is missing, and it'd be nice to have a similar default notification added too unless overridden.

This was seen together with #5906 

**Environment**

* React-admin version: 3.12

**Comment by WiXSL** [comment]
@bayareacoder, could you try if this is fixed in react-admin v3.19.7 ?

**Comment by bayareacoder** [comment]
Hi, I received a notification so logging in here but at this time, a year later, I'm not using RA for a project so I can't test it currently. I also did the workaround noted in my earlier post in my previous RA code.

**Comment by fzaninotto** [comment]
Fine, so we're closing the issue.
