### ISSUE TITLE
Setting List.empty prop to false causes location.state passed in Link to not be set properly

### ISSUE THREAD

**Issue by CompleteScone** [marmelab/react-admin#5909]
**What you were expecting:**
When using the `to` prop in a `<Button />` component in a Datagrid to update the `location.state` passed to the target route, I would expect the target route (in my case a create page) to be prefilled with the values in `location.state.record`. As described in the [documentation](https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record).

**What happened instead:**
This was working exactly as expected until I also updated the `empty` prop on the `<List />` component and set it to `false`. Doing this caused my button to redirect to my create page, but not to prefill any values. If I removed the `empty` prop, or set it to a custom component the prefill worked as expected.

**Steps to reproduce:**
1. Create an app with two Resources.
2. For one Resource create a Create view with at least one Input field.
3. For the other resource create a List view with a Datagrid.
4. In the List view component, set the `empty` property to `false`.
5. Add a Button component as a child to the Datagrid with the necessary props as defined [here](https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record)
6. Navigate to the List view and click the button on one of the records. You should successfully go to the Create view, but no data will be filled out.

**Related code:**
``` js
//Create.jsx
import * as React from "react";
import { Create, Edit, SimpleForm, TextInput, DateInput, ReferenceManyField, Datagrid, TextField, DateField, EditButton } from 'react-admin';
import RichTextInput from 'ra-input-rich-text';

export const PostCreate = (props) => (
    <Create {...props}>
        <SimpleForm>
            <TextInput source="title" />
            <TextInput source="teaser" options={{ multiLine: true }} />
            <RichTextInput source="body" />
            <DateInput label="Publication date" source="published_at" defaultValue={new Date()} />
        </SimpleForm>
    </Create>
);

```
``` js
//List.jsx
import * as React from "react";
import { Datagrid } from 'react-admin';
import Button from '@material-ui/core/Button';
import { Link } from 'react-router-dom';

const CreateRelatedPostButton = ({ record }) => (
    <Button
        component={Link}
        to={{
            pathname: '/posts/create',
            state: { record: { title: record.title } },
        }}
    >
        Create Post with Same Title
    </Button>
);

export default PostList = props => (
    <List {...props} empty={false}>
        <Datagrid>
            ...
            <CreateRelatedPostButton />
        </Datagrid>
    </List>
)
```

**Environment**
* React-admin version: 3.11.1

**Comment by djhi** [comment]
Hi and thanks for the report. I'm unable to reproduce the issue though.

What I did notice is that clicking on the create button actually redirect to the edition of the record of the same row. You need to stop the propagation of the click event in your custom button.

```js

const CreateRelatedPostButton = ({ record }) => (
    <Button
        component={Link}
        onClick={event => event.stopPropagation()}
        to={{
            pathname: '/posts/create',
            state: { record: { title: record.title } },
        }}
    >
        Create Post with Same Title
    </Button>
);
```

Besides, note that you should probably use the `Button` from `react-admin` which accept a translatable `label` prop and an optional icon as its children. It implement a responsive design.

**Comment by CompleteScone** [comment]
Took a break from the project that was having this issue and I can no longer reproduce the problem, so may have been some transient config on my end.

As a note, the use of a raw MaterialUI `Button` was to match what is listed in the react-admin documentation. If the `react-admin` component is preferred in this use case, then the documentation may be out of date.
