### ISSUE TITLE
Select multiple records with Shift + click

### ISSUE THREAD

**Issue by m4theushw** [marmelab/react-admin#5910]
**Is your feature request related to a problem? Please describe.**
Users sometimes want to apply a bulk action in a subset of the records, but selecting each one may become a tedious task. It would be very useful if react-admin allowed to select a range of records by Shift + clicking, like in Gmail or Excel.

**Describe the solution you'd like**
When the user selects two records while pressing Shift, then all records between them will get selected too. See screenshot below.

**Describe alternatives you've considered**
Clone `<DatagridRow />` to pass the original event to [`onToggleItem`](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx#L89). Next, create a custom `<List />` to override `onToggleItem`.

**Additional context**
I already have part of this feature implemented "the right way". I just want to know if it's worth the investment to open a PR.

![Peek 2021-02-14 22-06](https://user-images.githubusercontent.com/42154031/107895133-f675b080-6f10-11eb-8a7e-af4ac79e88fb.gif)

**Comment by fzaninotto** [comment]
Oh, sure, that would be welcome! Looking forward to seeing your PR.

I'll close this issue though, as we don't want to clutter our tracker with all the enhancements that people wish. You have our greenlight to PR!
