### ISSUE TITLE
Empty choices with AutocompleteArrayInput in Edit mode

### ISSUE THREAD

**Issue by keery** [marmelab/react-admin#5935]
**What you were expecting:**
Hi ,
I am facing a problem with usage of AutocompleteArrayInput or SelectArrayInput, I would like to display a collection with this shape
``` json
{
  "styles" : [
    { "id": 1, "name": "first" },
    { "id": 2, "name": "second" }
  ]
}
```

``` jsx
<ReferenceArrayInput
    label="Styles"
    reference="filter-style"
    source="styles"
>
    <AutocompleteArrayInput  />
 </ReferenceArrayInput>
```
**What happened instead:**
Instead having my collection rendered, I got my two items empty 
![image](https://user-images.githubusercontent.com/10221598/108424813-f12ea380-7239-11eb-8308-6754f19a1d89.png)

**Other information:**
I tried different ways, example with ReferenceArrayInput wrapping my component, or using prop optionText, in function in order to analyze injected props but they are undefined, same if try to use a react component I got this log for props
![image](https://user-images.githubusercontent.com/10221598/108425123-52ef0d80-723a-11eb-8600-6a81c40f5648.png)

Hope this is a mistake from myself and not a bug.

Have a nice day

**Environment**

* React-admin version: 3.12.1
* React version: 17.0.1

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by keery** [comment]
Thank you the link you shared with the example app helped me a lot, my mistake was that I didn't get that my object didn't have the right shape from my api.

Before 
``` js
{
  "styles" : [
    { "id": 1, "name": "first" },
    { "id": 2, "name": "second" }
  ]
}
```

After
``` js
{
   styles: [1, 2],
}
```
