### ISSUE TITLE
Cannot find module: 'lodash.isequalwith'

### ISSUE THREAD

**Issue by guilbill** [marmelab/react-admin#5942]
**What you were expecting:**

When following the tutorial to [this point](https://marmelab.com/react-admin/Tutorial.html#making-contact-with-the-api-using-a-data-provider) I want the app to build and run properly when running `yarn start`, as described in the doc.

**What happened instead:**

The build failed with the message : 
```
./node_modules/connected-react-router/esm/ConnectedRouter.js
Module not found: Can't resolve 'lodash.isequalwith' in '/react-admin/node_modules/connected-react-router/esm'
```

**Steps to reproduce:**

Create new react app :
```
yarn create react-app test-admin
cd test-admin/
yarn add react-admin ra-data-json-server prop-types
```
Change App.js as follow:
```js
// in src/App.js
import * as React from "react";
import { Admin } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');
const App = () => <Admin dataProvider={dataProvider} />;

export default App;
```

**Related code:**

https://github.com/guilbill/tuto-react-admin

**Other information:**

It is related with a bug on connected-react-router : https://github.com/supasate/connected-react-router/issues/480

**Environment**

* React-admin version: 3.12.4
* React version: 17.0.1
* Browser: Brave Version 1.19.90 Chromium: 88.0.4324.146
* Stack trace (in case of a JS error): 
```Failed to compile.

./node_modules/connected-react-router/esm/ConnectedRouter.js
Module not found: Can't resolve 'lodash.isequalwith' in '/react-admin/node_modules/connected-react-router/esm'
```

**Comment by djhi** [comment]
So it's because we have a dependency on `connected-react-router` with a `^`.

**Comment by fzaninotto** [comment]
This is a critical bug. We'll wait a day to see if the `connected-react-router` team fix it on their side, and release a bugfix if they don't. 

In the meantime, please use `resolutions` in `packages.json` to force the version of connected-react-router used by react-admin.

```js
// in packages.json
{
   // ...
   "resolutions": {
      "connected-react-router': "6.6.1",
    }
}

```

**Comment by ltnscp9028** [comment]
@fzaninotto  I make connected-react-router PR. https://github.com/supasate/connected-react-router/pull/481
The relevant PR must be merged urgently.

**Comment by fzaninotto** [comment]
`connected-react-router@6.9.1` was just released (https://github.com/supasate/connected-react-router/releases/tag/v6.9.1). I tested that the bug no longer occurs.
