### ISSUE TITLE
List without bulkActionButtons and rowClick set to "toggleSelection" problem

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#5947]
CodeSandbox: https://codesandbox.io/s/elated-forest-ftsfr?file=/src/users/UserList.js:171-188

1- Got to the Users List
2- Click any row.

Result:
**The entire list moves up.**

**Comment by fzaninotto** [comment]
Thanks, I managed to reproduce the bug in your CodeSandbox. 

My question is: why would you want to do that? If you use datagrid selection without the datagrid bulkActions, then I wonder why you're using datagrid at all.

**Comment by WiXSL** [comment]
Fair enough.
I discover the bug because I have an internal tool that generates react-admin Lists, always generating them with prop `rowClick="toggleSelection"`.
Some Lists have bulkActions some don't.
I have to adjust that, but I thought It was worth the bug report.

**Comment by fzaninotto** [comment]
I don't think the bug can occur in real life. And if it does, it's for use cases we don't want to support. 

So I'm closing this issue, thanks for the report anyway.
