### ISSUE TITLE
useSafeSetState incompatible with @types/react@16.14 and later

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#5949]
**What you were expecting:**
react-admin should compile in Typescript when using @types/react@16.14 or @types/react@17

**What happened instead:**
Throws an error at compile time due to the return type from the returned destructor from `useSafeSetState` in file `ra_core/src/util/hooks.ts`

```
   const mountedRef = useRef(false);
  > 12 |     useEffect(() => {
       |               ^
    13 |         mountedRef.current = true;
    14 |         return () => (mountedRef.current = false);
    15 |     }, []);
```
Type 'boolean' is not assignable to type 'void | { [UNDEFINED_VOID_ONLY]: never; }'

**Root cause:**
Type definitions for EffectCallback changed to explicitly disallow to return anything else than void from the Destructor

From @types/react@16.9
```
  type EffectCallback = () => (void | (() => void | undefined));
```

To @types/react@16.14 (maybe already from earlier version but not tested)
```
type EffectCallback = () => (void | Destructor);
type Destructor = () => void | { [UNDEFINED_VOID_ONLY]: never };
declare const UNDEFINED_VOID_ONLY: unique symbol;
```

**Fix**
2 character fix: replace () by {}

**Environment**

* React-admin version: 3.12.5

**Comment by fzaninotto** [comment]
Thanks for the detailed description and root cause analysis. The fix is simple indeed.
