### ISSUE TITLE
Trigger warnWhenUnsavedChanges confirmation when leaving the app

### ISSUE THREAD

**Issue by tdnl** [marmelab/react-admin#5976]
**Is your feature request related to a problem? Please describe.**

Currently, the confirmation gets displayed once the form is unmounted (which happens when the user tries to navigate to a different pages inside the app). However, if he tries to visit a different website (or even close the page) the confirmation will not get displayed and the form's changes will be lost. 

**Describe the solution you'd like**

Trigger the confirmation prompt when the user leaves the website and not just when the component unmounts.
We might be able to achieve this by using the browser's `beforeunload` event: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Describe alternatives you've considered**

N/A

**Additional context**

The current logic is implemented in the `useWarnWhenUnsavedChanges` hook: 
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx

**Comment by andrico1234** [comment]
Curious as to whether anyone has had any luck implementing this in userland?

**Comment by fzaninotto** [comment]
I believe this is now the default in v4. Feel free to reopen if you can provide a reproduction proving otherwise.
