### ISSUE TITLE
App jumps to previous page if getList returns`data: []`

### ISSUE THREAD

**Issue by marcpalm** [marmelab/react-admin#5987]
**Is your feature request related to a problem? Please describe.**
I was debugging some issues with the pagination today. At some point, I realized that the `getList` function returned an empty array for the second page, and then the app auto navigated to the first page. This might seem like a pagination issue but it was actually my implementation error in the dataProvider.

**Describe the solution you'd like**
If the total length suggests that data should exist for the paginationPayload, I'd prefer an error to be thrown.

**Describe alternatives you've considered**
Show an empty list.

**Additional context**
I have found many bug reports about pagination. This might be one reason for it.

Sandbox Link
https://codesandbox.io/s/mystifying-platform-lvnw1?file=/src/App.js

**Comment by fzaninotto** [comment]
Hi, this is by design. If you want to show an error page instead, you should build your own List component by calling `useGetList` manually.
