### ISSUE TITLE
AutocompleteInput not showing selected values in Edit mode

### ISSUE THREAD

**Issue by manishk1683** [marmelab/react-admin#5993]
Hi ,
I have following setup for create and edit recipes. Each recipe can have multiple ingredients associated with it - 

```jsx
  export const recipeEdit = (props) => (
    <Edit {...props}>
      <SimpleForm>
        
        <TextInput label= "name" source="name" validate={required()} />
        <TextInput label= "cookTime" source="cookTime" />
        <TextInput label= "type" source="type" />
        <TextInput label= "link" source="link" />
        <TextInput label= "prepTime" source="prepTime" />
        <TextInput label= "serves" source="serves" />
        <TextInput label= "img" source="img" />
        <TextInput label= "notes" source="notes" />
        <TextInput label= "instructions" source="instructions" />
        <BooleanInput source="isBase" validate={required()} />
        <ArrayInput source="recipe_ingredients">
          <SimpleFormIterator>
          <ReferenceInput
              source="id"
              label="ingredient"
              reference="ingredient" 
              
            > 
              <AutocompleteInput optionText="english" />
            </ReferenceInput>

          </SimpleFormIterator>
        </ArrayInput>

      </SimpleForm>
    </Edit>
  )
```

This works well in create mode but in edit mode the autocomplete is not coming pre-filled with the saved values - 
![image](https://user-images.githubusercontent.com/66935427/109917508-7fdffd80-7cdb-11eb-89dd-e1f270140bef.png)

I am not sure if this is desired behaiviour.
Any help much appreciated.
Thanks,
Manish.

**Comment by djhi** [comment]
I can't reproduce this on the simple example where we have a similar setup. I modified our data to include default authors and they are displayed on edit.

Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by manishk1683** [comment]
Thanks Gildas for looking into.
However I realised that my mappings are many-many.
Sightly modifying mappings and using ReferenceArrayInput solved the problem.

Thanks,
Manish.

**Comment by manishk1683** [comment]
closing the same.
