### ISSUE TITLE
List property "filter" renders badly

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#5997]
Hello, I found a bug in the "filter" property of List, it turns out that I put an id of a user, so that it only shows me the products of that user, like the following code:
```
<List 
    {...props} 
    pagination={<ProductPagination />} 
    filter={{ sellerId: uid }}>
    <Datagrid rowClick="edit">
        <TextField label="Nombre" source="name" />
        <TextField label="Precio" source="price" />
        <TextField label="Descripción" source="description" />
    </Datagrid>
</List>
```
But, what happens is that it first renders me all the products and then it shows with the filter.
What I want is that this does not happen, first because it is a security problem and second because it is ugly to do a double rendering in the same List view.

Any solution?

**Comment by DanielSanchez94** [comment]
It is clear that what I want to achieve is to put a persistent filter on the list

**Comment by djhi** [comment]
Hey, thanks for the report!

I would say that the security problem is that your API allows users to query things they shouldn't ;)

However, this behavior seems strange indeed. Would you mind setting up a codesandbox to help us debug it?

**Comment by DanielSanchez94** [comment]
In my case the information is public, only that I show different products for each user.
 
Would you please pass me a react-admin base sandbox so I can configure it?

**Comment by WiXSL** [comment]
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by DanielSanchez94** [comment]
The link not working!

**Comment by WiXSL** [comment]
Did you Fork the repo like the site suggest  you?

![screen](https://user-images.githubusercontent.com/8268610/110019062-c4cd5980-7d06-11eb-925d-ebd74818eb60.png)

**Comment by DanielSanchez94** [comment]
I tested my code and found the error, it was mine, a thousand apologies for the inconvenience.
I just had to add a:
  ` if (loading) return <Loading />;`
Now it works perfectly, thank you very much and excuse me.
