### ISSUE TITLE
NullableBooleanInput defaultValue not working

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#6000]
**What you were expecting:**
Expected to be able to set a default value for the fields as stated in the documentation

**What happened instead:**
This does not work

**Steps to reproduce:**
1) Set the default as in the documentation
2) No reaction

**Related code:**
```
<NullableBooleanInput source="commentable" defaultValue={true} />
<NullableBooleanInput source="commentable" defaultValue={false} />
<NullableBooleanInput source="commentable" defaultValue={null} />
```

https://codesandbox.io/s/old-firefly-879dr?file=/src/posts/PostCreate.tsx:2648-2713

**Other information:**
In the codesandbox example, there was some kind of crutch passing the defaultValue for BooleanInput. does not look like in the documentation
https://marmelab.com/react-admin/CreateEdit.html#per-input-default-value

**Environment**

* React-admin version: 3.13.1

**Comment by djhi** [comment]
Reproduced. Thanks for the report!
