### ISSUE TITLE
alwaysEnableSaveButton prop completely disables the save button if it is defined and false

### ISSUE THREAD

**Issue by macklin-10x** [marmelab/react-admin#6008]
**What you were expecting:**

Passing `alwaysEnableSaveButton = false` to `Toolbar` defaults to the standard behavior of using the form's pristine state to enable or disable the save button.

**What happened instead:**

The save button is fully disabled, and my users are confused why none of the forms work anymore :)

**Steps to reproduce:**

Pass `alwaysEnableSaveButton = false` to `Toolbar`.

**Other information:**

If this is an intended feature, then improving the docs on the property would be sufficient.  Probably too late to change now, but if this is intended, then the property is somewhat confusingly named and just `enableSaveButton` might have been a more clear name.

Otherwise, adjusting the implementation in `Toolbar.tsx` such that `undefined` and `false` both default to the standard behavior would be preferable.  Thank you!

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback. 

The documentation only documents how to disable the auto-disabled save button. So you're trying to use an undocumented feature that is not implemented, so let's call it a feature request.

Could you explain your use case? Why would you want to force a behavior that is the default one?

**Comment by macklin-10x** [comment]
Sorry I was perhaps not so clear - it's not exactly a feature request, more like a request to remove a potential surprising pitfall.  Potential use cases would be if you were computing a dynamic value to pass to `alwaysEnableSaveButton` - it is surprising that passing `undefined` and `false` trigger different behavior, since it means I can't just pass the result of a boolean expression to `alwaysEnableSaveButton` but need to map the result back into the domain `(undefined, true)`.

**Comment by WiXSL** [comment]
This could be implemented simple by changing `Toolbar` component's line 80 like this:
```diff
const disabled = !valueOrDefault(
-   alwaysEnableSaveButton,
+   alwaysEnableSaveButton !== false ?? undefined, 
    !isValidating && !saving
);
```
To evaluate  `false` the same way as `undefined`
