### ISSUE TITLE
Allow BooleanField component to evaluate its values in a non strict way

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6022]
Currently, the `BooleanField` evaluates its value strictly as `boolean` in order to show something.
My  `BooleanField` value may be `0` or `1` instead of `true` or `false` and the component is not showing anything in that case.
I'would like to be able to tell the `BooleanField` to loosen up a little bit.

**Comment by fzaninotto** [comment]
Fixed by #6027
