### ISSUE TITLE
TabbedShowLayout not scrollable

### ISSUE THREAD

**Issue by JoshCorps** [marmelab/react-admin#6024]
**What you were expecting:**
When there are too many tabs to fit the current screen the tab bar should become scrollable and not continue off screen.

**What happened instead:**
The tab bar remains the same size with no scroll and tab options off screen.

**Steps to reproduce:**
I copied the react-admin tutorial code from [here](https://github.com/marmelab/react-admin/tree/master/examples/tutorial) and then added the code from the scrollable example [here](https://marmelab.com/react-admin/Show.html#the-tabbedshowlayout-component)

**Related code:**

I've pushed the code [here](https://github.com/jcorps1/react-admin-scrollable-tabs)

```
export const PostShow = props => (
    <Show {...props}>
        <TabbedShowLayout tabs={<TabbedShowLayoutTabs variant="scrollable" {...props} />} >
            <Tab label="Summary">
                <TextField source="title" />
                <TextField source="teaser" />
                <RichTextField source="body" />
                <DateField label="Publication date" source="created_at" />
            </Tab>
            <Tab label="Summary"></Tab>
            <Tab label="Summary"></Tab>
            <Tab label="Summary"></Tab>
            <Tab label="Summary"></Tab>
            <Tab label="Summary"></Tab>
            <Tab label="Summary"></Tab>
        </TabbedShowLayout>
    </Show>
);
```

**Other information:**
![image](https://user-images.githubusercontent.com/78795658/110553177-871a6780-8130-11eb-8b95-0afed20d227f.png)

I've tried material-ui tab components without react-admin and they work as expected

**Environment**

* React-admin version: 3.9.0 (also tried in 3.12.4)
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.0
* Browser: Chrome and Firefox
* Stack trace (in case of a JS error):

**Comment by fzan** [comment]
@jcorps1 I think you cannot scroll because the window is actually scrolling the content. 
Did you try to set a max width to the container? and adding scroll buttons?
Just dropped an example here:
https://codesandbox.io/s/naughty-bogdan-4q3mv?file=/src/index.css
Please note that the css tricky rule is "quick and dirty" to show what i mean :-)

**Comment by davidhenley** [comment]
@JoshCorps did you ever find a good solution for this?

**Comment by fzaninotto** [comment]
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.
