### ISSUE TITLE
Support TreeQL Data Provider

### ISSUE THREAD

**Issue by mevdschee** [marmelab/react-admin#6044]
Thank you for creating React Admin, it looks wonderful to me!

I've received [a request](https://github.com/mevdschee/php-crud-api/issues/768) to support React Admin for my REST API software and I think this is a nice match.

I've tried implementing a Data Provider for [PHP-CRUD-API](https://github.com/mevdschee/php-crud-api)'s protocol ([TreeQL](https://treeql.org)).

See: https://github.com/mevdschee/ra-data-treeql

Maybe somebody can help me finish the code, there are some TODO's in the code.

// TODO: filter is not well-formed
https://github.com/mevdschee/ra-data-treeql/blob/master/src/index.ts#L65

// TODO: update is not returning the record
https://github.com/mevdschee/ra-data-treeql/blob/master/src/index.ts#L82

// TODO: delete is not returning the id
https://github.com/mevdschee/ra-data-treeql/blob/master/src/index.ts#L107

I'm not very familiar with React-Admin, so any pointers in the right direction are welcome.

Kind regards,

Maurits van der Schee

**Comment by fzaninotto** [comment]
Hi Maurits, and thanks for your kind words!

The core team only works on a few dataProviders for platforms we know and use. We don't invest time in every other platforms, there are better people than us to do so. So I'm closing this issue as we won't spend time on it. 

I wish you the best for your data provider.

**Comment by mevdschee** [comment]
Hi @fzaninotto, Thank you for your fast reply. I understand your position. Good luck with the project! Kind regards, Maurits
