### ISSUE TITLE
type definition for Datagrid rowClick property doesn't match the docs.

### ISSUE THREAD

**Issue by jvert** [marmelab/react-admin#6050]
**What you were expecting:**
The documentation for Datagrid claims you can pass a function that returns a promise as the rowClick property:

> **Tip**: If you pass a function, it can also return a promise allowing you to check an external API before returning a path. For example:
> 
> ```js
> import fetchUserRights from './fetchUserRights';
> 
> const postRowClick = (id, basePath, record) => fetchUserRights().then(({ canEdit }) => canEdit ? 'edit' : 'show');
> ```
> 

But the type definition for RowClickFunction does not allow that
```js
type RowClickFunction = (
    id: Identifier,
    basePath: string,
    record: Record
) => string;
```

**What happened instead:**
Typescript error TS2322:
```
  Type '(id: Identifier, basePath: string, record: Record) => Promise<string>' is not assignable to type 'RowClickFunction'.
    Type 'Promise<string>' is not assignable to type 'string'.  TS2322
```

**Steps to reproduce:**
From a typescript .TSX file try to pass a function that returns a `Promise<string>` to `<Datagrid rowclick={onclick}/>`

**Environment**

* React-admin version: 3.13.14

**Comment by djhi** [comment]
Thanks for reporting this! Can you open a PR ?
