### ISSUE TITLE
FilterLiveSearch input cleared on navigation but filter remains

### ISSUE THREAD

**Issue by Dormanator** [marmelab/react-admin#6052]
**What you were expecting:**
When filtering a List with FilterLiveSearch  the correct filter results display in the List. If you click on a record in the List or navigate to another view and then come back to the List it should still be filtered. Further, all filter components (e.g., FilterListItem, FilterLiveSearch , etc.)  should indicate what filters are currently active.

**What happened instead:**
The FilterLiveSearch component no longer has any text input or indicates a search filter is active, but the List results are still filtered by the search. To clear the active filter you must reload the page or search for another term.

**Steps to reproduce:**
- Go to the Customers resource in the demo: https://marmelab.com/react-admin-demo/#/customers
- Type a partial name into the FilterLiveSearch input such as 'Ra'
- Take note of the filtered List results
- Navigate to another resource like 'Posters'
- Return to the Customers List and notice the FilterLiveSearch  is empty but the list results are still filtered
- Reload the page to clear the search filter and see the original Customer list

**Environment**
React-admin version: 3.12.1
React version: 17.0.1
Browser: Chrome

**Comment by fzaninotto** [comment]
Indeed, that's a bug. Thanks for reporting!
