### ISSUE TITLE
Not possible to hide a few filters

### ISSUE THREAD

**Issue by Darkiman** [marmelab/react-admin#6055]
**What you were expecting:**
3 filters are hidden

**What happened instead:**
hidden only first filter

**Steps to reproduce:**

**Related code:**

```
hideFilter('expiringCertificates');
hideFilter('caName');
hideFilter('date');
```

**Other information:**
It's better if we will have possibility to pass array of filters to hideFilter function

**Environment**

* React-admin version: 3.13.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.14.0
* Browser: Chrome
* Stack trace (in case of a JS error): No error in console

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
You can use the `setFilters` callback to set multiple filters at once. 

https://marmelab.com/react-admin/List.html#uselistcontext

**Comment by Darkiman** [comment]
https://codesandbox.io/s/red-bash-tdsw0?file=/src/posts/PostList.tsx
Select title and Commentable in filters.
Click on Hide filers or Update filters button. 
setFilters, hideFilter not working

**Comment by djhi** [comment]
In the codesandbox, you're trying to access the ListContext outside of the List component. This cannnot work as the List component is the one creating the context

**Comment by Darkiman** [comment]
I changed sandbox :
https://codesandbox.io/s/condescending-browser-vv59x
setFilters function working correctly.
but hideFilter is not correct.

1) Select title and commentable in filters.
2) Select row
3) click Hide filters button in bulk actions toolbar

commentable filter gone, but title still exists.

**Comment by fzaninotto** [comment]
Thanks for the report, bug confirmed.
