### ISSUE TITLE
OpenID doc example no longer works in 3.13.x

### ISSUE THREAD

**Issue by instantlinux** [marmelab/react-admin#6073]
**What you were expecting:**
Example for OpenID authentication created in https://github.com/marmelab/react-admin/pull/3795 and mentioned in this repo's [advanced tutorial](https://marmelab.com/react-admin/doc/3.13/AdvancedTutorials.html#openid-connect-authentication-with-react-admin) should work with current 3.13.x version.

_(Suggested extra feature for anyone who fixes this: make the form accept **either** local login **or** google / twitter / github auth. And add a documentation section spelling out how LoginPage customization can be achieved, in particular for the OpenID use-case.)_

**What happened instead:**
With 3.12 I get this error:
```
React does not recognize the `LoginForm` prop on a DOM element. If you intentionally want
 it to appear in the DOM as a custom attribute, spell it as lowercase `loginform` instead.
 If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Steps to reproduce:**
Follow the steps outlined in [openid advanced tutorial](https://github.com/marmelab/react-admin/blob/master/docs/AdvancedTutorials.md#openid-connect-authentication-with-react-admin) to launch the example but specify current react-admin in its `package.json`.

**Other information:**
The example lives in https://github.com/marmelab/ra-example-oauth. This request, or similar, was submitted over a year ago as https://github.com/marmelab/ra-example-oauth/issues/5 and PR https://github.com/marmelab/ra-example-oauth/pull/9 has yet to be reviewed / merged.

**Environment**

* React-admin version: 3.12.1
* Last version that did not exhibit the issue (if applicable): 2.9.9

**Comment by ducalai** [comment]
Same issue here. Based on that OpenID sample, I am trying to authenticate users with MSAL.js libs (msal-browser and msal-react), but without success. It would be very helpful to have a running sample on which we can build.

**Comment by fzaninotto** [comment]
There is already an issue open on the ra-example-oauth repo, no need to open another one here.

**Comment by instantlinux** [comment]
The fix noted in that issue was approved 5 months ago. Can you merge it?
