### ISSUE TITLE
Slow form inputs in V3 compared to V2 (useInput, composeValidators)

### ISSUE THREAD

**Issue by bucuri** [marmelab/react-admin#6075]
I have a form (SimpleForm) with around 50 inputs and also an ArrayInput with 15 inputs on each line.
With React Admin v3 the form is very slow. After some investigation it seems to be linked to field validation. The function `composeValidators` ( which is asynchronous) seems to be a lot slower than `composeSyncValidators` (which is synchronous).

**What you were expecting:**

I would expect too see the same level of speed as in React Admin V2, which didn't use field async validation. 

**What happened instead:**

As soon as we migrated RA V2 to V3, the form became very slow.

**Steps to reproduce:**

Add a SimpleForm with 50+ input controls on it (they should be controls using useInput() hook).
Editing any field will be slow, the form becomes unusable.

Using the sample code bellow we can visualize this behaviour by following the following steps:
1. On the admin view with the two menus `users` and 'posts'.
2. Click on either a user or post to see the Edit view.
3. The `users` Edit view contains a form using input controls from react-admin. By editing any field we can see it is **slow**.
4. The `posts` Edit view contains a form using **modified** input controls from react-admin. By editing any field we can see it is considerably **faster**.
   - these modified inputs are located in `ra-inputs` folder.

**Related code:**

https://codesandbox.io/s/ra-forms-slow-g8scw

```
    // useInput ... line 65-67

   // slow
    const sanitizedValidate = Array.isArray(validate)
        ? composeValidators(validate)
        : validate;
```

Changed code:
```
    // useInput ... line 65-67

   // slow
    const sanitizedValidate = Array.isArray(validate)
        ? composeSyncValidators(validate)
        : validate;
```

**Other information:**

The temporary solution we found is to copy every input from react-admin source code into our code and change them to use a custom version of the useInput hook.

Maybe in the future we could control this sync/async validation behavior through some parameter at field level.

**Environment**

* React-admin version: 3.13.5
* Last version that did not exhibit the issue (if applicable): 2
* React version: >=16.x.x.x
* Browser: All I think (tried in chrome  89.0.4389.90)

**Comment by Ashenbacken** [comment]
I tested it out with ArrayInput as well and it really is slow unless you add subscription={{}} to it:
https://codesandbox.io/s/ra-forms-slow-using-arrayinput-90e7f

**Comment by gearFifth** [comment]
/* eslint-disable react-hooks/rules-of-hooks */
import * as React from "react";
import {
  TextInput,
  NumberInput,
  required,
  DateInput,
  FormDataConsumer,
  ReferenceInput,
  AutocompleteInput,
  ImageInput,
  ImageField,
} from "react-admin";

import { Styles } from "@material-ui/core/styles/withStyles";
import { ApiModels } from "../types";
import { Theme } from "@material-ui/core";

export const styles: Styles<Theme, any> = {
  input: { display: "inline-block", marginRight: 32, width: 200 },
};

export const CarsForm = (props: any) => {
  const requiredValidate = [required()];
  const TestComponent: React.FC = () => {
    const inside = React.useRef(0);
    console.log("inside", ++inside.current);
    return <FormDataConsumer subscription={{submitting: true}} >
        {() => {
          const renders = React.useRef(0);
          console.log("third", ++renders.current);
          return (
            <>
              <TextInput validate={requiredValidate} fullWidth source="color" />
            </>
          );
        }}
      </FormDataConsumer>
  }
  const renders = React.useRef(0);
  console.log("he.l", ++renders.current);
  return (
    <>
      <FormDataConsumer subscription={{submitting: true}}>
        {({ formData }) => {
          const renders = React.useRef(0);
          console.log("second", ++renders.current);
          return (
            <>
              <TextInput fullWidth source="style" />
              {formData.style && <NumberInput min={0} fullWidth source="doors" />}
              <ReferenceInput
                perPage={10}
                source="purchased_from"
                reference={ApiModels.customers}
              >
                <AutocompleteInput optionText="firstName" />
              </ReferenceInput>
            </>
          );
        }}
      </FormDataConsumer>
      <TestComponent />
    </>
  );
};

**Comment by gearFifth** [comment]
It doesnt work for me either. even one validation field is making the form very slow. even adding the  subscription={{}} didn't work for me.

@Ashenbacken @bucuri 
```
/* eslint-disable react-hooks/rules-of-hooks */
import * as React from "react";
import {
  TextInput,
  NumberInput,
  required,
  DateInput,
  FormDataConsumer,
  ReferenceInput,
  AutocompleteInput,
  ImageInput,
  ImageField,
} from "react-admin";

import { Styles } from "@material-ui/core/styles/withStyles";
import { ApiModels } from "../types";
import { Theme } from "@material-ui/core";

export const styles: Styles<Theme, any> = {
  input: { display: "inline-block", marginRight: 32, width: 200 },
};

export const CarsForm = (props: any) => {
  const requiredValidate = [required()];
  const TestComponent: React.FC = () => {
    const inside = React.useRef(0);
    console.log("inside", ++inside.current);
    return <FormDataConsumer subscription={{submitting: true}} >
        {() => {
          const renders = React.useRef(0);
          console.log("third", ++renders.current);
          return (
            <>
              <TextInput validate={requiredValidate} fullWidth source="color" />
            </>
          );
        }}
      </FormDataConsumer>
  }
  const renders = React.useRef(0);
  console.log("he.l", ++renders.current);
  return (
    <>
      <FormDataConsumer subscription={{submitting: true}}>
        {({ formData }) => {
          const renders = React.useRef(0);
          console.log("second", ++renders.current);
          return (
            <>
              <TextInput fullWidth source="style" />
              {formData.style && <NumberInput min={0} fullWidth source="doors" />}
              <ReferenceInput
                perPage={10}
                source="purchased_from"
                reference={ApiModels.customers}
              >
                <AutocompleteInput optionText="firstName" />
              </ReferenceInput>
            </>
          );
        }}
      </FormDataConsumer>
      <TestComponent />
    </>
  );
};
```

**Comment by djhi** [comment]
Thanks for the report
