### ISSUE TITLE
Upgrade to react-redux v7.2.3

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6077]
Shouldn't `react-admin` be upgraded to [`react-redux`](https://github.com/reduxjs/react-redux/releases/tag/v7.2.3)  v7.2.3?

The new version fixes the `useSelector` hook by returning the existing reference if the newly returned selector result passes the equality check.
This affects `react-admin` `useListParams` hook and the `Menu` component.

**Comment by fzaninotto** [comment]
What bug in react-admin are you talking about?

also, react-admin has a dependency on `react-redux^7.1.0`, so npm should install the version you're referring to whenever a user types `npm upgrade`.
