### ISSUE TITLE
Show and Edit Actions inverted

### ISSUE THREAD

**Issue by Xabibax** [marmelab/react-admin#6078]
**What you were expecting:**
I was expecting the \<ShowActions\/\> and  \<EditActions\/\>component to display a Show button and a Edit button that redirect to the corresponding Show and Edit Views

**What happened instead:**
The \<ShowActions\/\> displayed an Edit button redirecting to the Edit view
The \<EditActions\/\> displayed a Show button redirecting to the Show view

**Steps to reproduce:**
In a List view, add a \<ShowActions\/\> or  \<EditActions\/\> as a Datagrid <Field> children

**Related code:**

This code :

```javascript
<List {...props}>
    <Datagrid >      
      <FunctionField
        label="Customer ID"
        render={(record) => `Foo`}
      />
      <FunctionField
        label="Customer Name"
        render={(record) => `Bar`}
      />
      <EditActions/>
    </Datagrid>
  </List>
```

Display this :

![react_admin_actions_issue](https://user-images.githubusercontent.com/22958799/112446912-fe671280-8d50-11eb-86f4-4410d6e51592.PNG)

**Other information:**

It seems that the [react-admin/packages/ra-ui-materialui/src/detail/ShowActions.tsx](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/ShowActions.tsx) and [react-admin/packages/ra-ui-materialui/src/detail/EditActions.tsx](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/EditActions.tsx) could be swapped as theirs behaviours are correct but theirs respective names are not.

**Environment**

* React-admin version: 3.13.4
* ~~Last version that did not exhibit the issue (if applicable):~~
* React version: 17.0.1
* Browser: Chrome (88.0.4324.150), Firefox (72.0.2), Edge (89.0.774.57)
* ~~Stack trace (in case of a JS error):~~

**Comment by fzaninotto** [comment]
If you want to display a Show button, use the `<ShowButton>` component. `<ShowActions>` is the actions component for the Show view (which contains, and it's logical, an `<EditButton>`).

**Comment by Xabibax** [comment]
My bad, thanks!
