### ISSUE TITLE
DefaultValue stopped working as a parameter for form inputs

### ISSUE THREAD

**Issue by Merkure** [marmelab/react-admin#6084]
Hello, after upgrading from version 3.12.1 to the latest version. DefaultValue stopped working as a parameter for form inputs. Examples:

1. `<SelectInput {...props} choices={choices} optionText="text" optionValue="id" defaultValue={1} />`
2. `useInput({ name: 'lng', defaultValue: initLngLat ? initLngLat[0] : '' })`

If I use the initialValues ​​parameter on the form everything works correctly. The problem is also observed in version 3.12.5

**Comment by fzaninotto** [comment]
I think that's because we upgraded `react-final-form` in 3.13.3 (cf https://github.com/marmelab/react-admin/commit/f4832fedbc1cf11304dfa99b56c4a5217779a99e), expecting it to follow semver, but it didn't... I think https://github.com/final-form/final-form/releases/tag/v4.18.6 contains a breaking change in our case.

Needs further investigation to see if we can fix it in react-admin.

**Comment by fzaninotto** [comment]
I can't reproduce the problem on the simple example (see https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple?file=/src/comments/CommentCreate.tsx, where the `created_at` field defaults to the current date thanks to `defaultValue)`.

There must be something else about your code. could you please include a link to a fork of the CodeSandbox above reproducing the issue?

**Comment by Merkure** [comment]
I researched the problem and found out that the problem occurs when the real dataProvider is used.  After resolving the request on the edit page, the component is rerender and the default value disappears ... Because sandbox uses a fake data provider, the problem is not reproduced there.

**Comment by fzaninotto** [comment]
the dataProvider isn't fetched in the Create page. Do you mean that the problem happens only in an Edit page?

there should not be any difference between a real and the fake dataProvider - both have a latency (artificial for the latter).

**Comment by Merkure** [comment]
yes, I checked, the problem appears only on the edit page after executing the request, initially defaultValue is set correctly, but after re-rendering it changes to an empty value ...

**Comment by fzaninotto** [comment]
So could you please join a link to a Codesandbox reproducing the problem?

**Comment by kolben** [comment]
I experience the same issue with `RadioButtonGroupInput`

https://codesandbox.io/s/cool-fire-vrbvr?file=/src/comments/CommentCreate.tsx
https://codesandbox.io/s/cool-fire-vrbvr?file=/src/comments/CommentEdit.tsx

**Comment by fzaninotto** [comment]
So it's the same problem as #6198. As this issue is less concise, we'll keep the other one, even though it's older. 

Thanks for the report.
