### ISSUE TITLE
Don't show warning message on checkAuth failure

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#6098]
I have been doing the upgrade from React-Admin v2 to v3 for a while now. I'm almost finished, but there's something that I would like fine-tune.

Using v2, when user comes to our website at domain.tld without a token, Promise is rejected and user is redirected to domain.tld/#/login. No error/warning messages are shown.

Using v3, if the same situation happens, Promise is also rejected and user is redirected to the login page, but there comes the `ra.auth.auth_check`_error warning message - and twice!

I understand the logic, it may be useful most of the cases to display the warning message. For example if non-logged user tries to access domain.tld/#/settings, the user should be redirected to the login page and notify, that "you must login first". But if user comes to the website first time ever, he gets redirected to the login page as supposed to, but in this case that warning message should not be displayed. In this case the user is most likely known that he/she must login before seeing any content, so there's no point to warn the user since he/she didn't do anything wrong.

I don't know how easily this could be solved. Maybe just removing the notify completely? How that can be done?

Maybe some exception would be the other solution, that if user tries to access the root, domain.tld/#/, then the warning message would not be shown. And with other routes it would be shown. How this could be done?

Can the functionality what happens after Promise.reject() be overwritten somehow?

**Comment by djhi** [comment]
Explained in the documentation: https://marmelab.com/react-admin/Authentication.html#catching-authentication-errors-on-the-api
