### ISSUE TITLE
peerDependencies of ra-ui-materialui needs updating

### ISSUE THREAD

**Issue by jvert** [marmelab/react-admin#6099]
The ra-ui-materialui package.json has ` "ra-core": "^3.14.1"` under devDependencies, but `"ra-core": "^3.9.0"` under peerDependencies. Since it depends on the new useResourceLabel hook in 3.14, I think peerDependencies also needs updating to ^3.14.

**Environment**

* React-admin version: 3.14.0
* Last version that did not exhibit the issue (if applicable): 3.13

**Comment by fzaninotto** [comment]
You're right, thanks for the heads up!
