### ISSUE TITLE
Navbar Overlapping Scrollbar on demo page

### ISSUE THREAD

**Issue by Dnouv** [marmelab/react-admin#6101]
**What you were expecting:**
On clicking the user icon, the user menu should have been opened.

**What happened instead:**

After clicking the user icon, the top appbar overlapped the navbar and scrollbar.

**Steps to reproduce:**

1. Visit react admin demo site.
2. Turn on the dark theme.
3. Click on the user icon.

**Other information:**

Here is a screenshot of the error; the overlapping can be seen at the top right corner.
<img width="960" alt="ra-err" src="https://user-images.githubusercontent.com/61188295/113101406-4f2baf00-921a-11eb-8cb9-dc490432fb22.png">

**Environment**

* Browser: Chrome

**Comment by djhi** [comment]
Indeed. Thanks or reporting

**Comment by Dnouv** [comment]
@djhi, @fzaninotto I think there is some misunderstanding here; my issue was related to the Appbar overlapping the navbar. The issue resolved here is the user icon's overlapping; the navbar issue is still not resolved. Please look into this issue once more. Thank you.

**Comment by fzaninotto** [comment]
@Dnouv Then I don't understand what your issue is. Could you elaborate?

**Comment by Dnouv** [comment]
Yeah, sure, I will try; when the user drop-down is opened, the app bar overlaps the navbar on the top right side, as indicated in the picture below.
Overlapping page screenshot:
![ra-err_LI](https://user-images.githubusercontent.com/61188295/113345458-1a217880-9350-11eb-9044-fd97d699dd17.jpg)

Without overlapping of navbar:
![image](https://user-images.githubusercontent.com/61188295/113345676-6a003f80-9350-11eb-96e4-aa7e229300ed.png)

Thank you!

**Comment by fzaninotto** [comment]
Thanks for the clarification. Indeed, we should use the `disabledScrollLock` modal attribute on the menu (cf https://material-ui.com/api/modal/#props). Reopening.

**Comment by Dnouv** [comment]
Thanks a lot, @fzaninotto.

**Comment by Dnouv** [comment]
@fzaninotto, the issue was resolved using `disableScrollbarLock,` but it caused another issue. Since the scrolling is not locked, the popover menu remains on the screen while scrolling down it could be seen in the screenshot below.

![image](https://user-images.githubusercontent.com/61188295/116358356-2ef00f80-a81b-11eb-922e-e5c6de1a61bd.png)

I have tried a solution for fixing this issue by varying the padding of the body using the `onEntering` function of Material-UI Popover API, as in the PR: [https://github.com/navidrome/navidrome/pull/948](url)

Please look into the issue once again. Thank you!

**Comment by Dnouv** [comment]
Thanks for looking into the issue. It seems we need to wait for it to fix on the Material-UI side.
