### ISSUE TITLE
Custom Query Documentation - Wrong example - SetSort & SetPerPage errors

### ISSUE THREAD

**Issue by newfylox** [marmelab/react-admin#6108]
Following this example [**Rendering `<Datagrid>` With A Custom Query**](https://marmelab.com/react-admin/List.html#rendering-datagrid-with-a-custom-query) will throw 2 errors if using `sorting` and `pagination` features.

* `setSort` must be present inside `<ListContextProvider value={{setSort: ...}} />`
* `setPerPage` must be present inside `<Pagination setPerPage={...} />`

It could be something like this:
```jsx
const [perPage, setPerPage] = React.useState(25); // update here instead of const perPage = 50;
const [sort, setSort] = React.useState({ field: "myfield", order: "DESC" });

...

<ListContextProvider
    value={{
      basePath: "/expenses",
      data: keyBy(data, "id"),
      ids: data.map(({ id }) => id),
      currentSort: sort,
      selectedIds: [],
      setSort: (field, order) => { // update here
        setSort({ field, order });
      },
    }}
  >

...

<Pagination page={page} perPage={perPage} setPage={setPage}
  setPerPage={setPerPage} // update here
  total={total} />
```

**Comment by djhi** [comment]
Thanks for reporting. Can you open a PR ?

**Comment by fzaninotto** [comment]
Sorry, I pushed the fix to master by mistake. Reopening.
