### ISSUE TITLE
Tutorial catalog need tree struct to locate the content i want to browse quickly

### ISSUE THREAD

**Issue by pep-pig** [marmelab/react-admin#6109]
Current tutorial is hard to find the exactly right content i want.  For example，I need to browse all the content in the `<List View>` to find the `<span>`function tutorial. It's really ineffective.
 
**Describe the solution you'd like**
I hope that tutorial catalog can be changed to  tree struct , So that we can locate the specified content much more quickly

**Comment by djhi** [comment]
Thanks for your input. You can can use the search feature though

**Comment by pep-pig** [comment]
It is just a example，actually i don't even known the exist of span features. When I want to realize a similar feature, I have to read all the tutorials to find the exactly right content.
