### ISSUE TITLE
Filter values, sort params etc are lost after successful logging-in in custom login page

### ISSUE THREAD

**Issue by makbol** [marmelab/react-admin#6117]
**What you were expecting:**
After successful login, the filter values are kept

**What happened instead:**
User is redirected to resource but without query string

**Steps to reproduce:**
1. Create custom login page
2. Use `useLogin()` hook
3. Add resource with filters
4. Send to user a link to resource with filters set e.g `domain.com/#/my-component?filter=%7B%22filterA%22%3A%22foo%22%2C%22filterB%22%3A%22bar%22%7D&order=ASC&page=1&perPage=10&sort=foo`
5. Unauthenticated user is redirected to login page
6. User successfully logged-in
7. User is redirected to `domain.com/#/my-component`

Expected:
User is redirected to `domain.com/#/my-component?filter=%7B%22filterA%22%3A%22foo%22%2C%22filterB%22%3A%22bar%22%7D&order=ASC&page=1&perPage=10&sort=foo`

Actual:
User was redirected to `domain.com/#/my-component`

**Environment**
* React-admin version: 3.14.1
* React version: 16.14.0
* Browser: Chrome Canary 91.0.4443.0

**Comment by hieusmiths** [comment]
I have same the issue. When edit I passed redirect into Edit component like as bellow:

<Edit redirect="/users?query=xxx" /> but after edit success location lost a query params

**Comment by makbol** [comment]
@hieusmiths Can you test my PR if it also fixes your issue?
