### ISSUE TITLE
<DashboardMenuItem /> doesn't allow styling the underlying <MenuItemLink />

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#6120]
**What you were expecting:**
Being able to customize the appearance of the `<MenuItemLink />` rendered by `<DashboardMenuItem />`, using Typescript.

**What happened instead:**
Nothing changes.

**Steps to reproduce:**
`<DashboardMenuItem classes={{ backgroundColor: "red" }} />`

**Related code:**
The `classes` props of the `MenuItemLink` component is unused.
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/MenuItemLink.tsx#L37

**Other information:**
Not sure how you want to fix this, so I'm letting you figure out the solution. It's because it's unclear to me what you mean by the `classes` props of the DashboardMenuItem component and how it's supposed to be used.

**Environment**

* React-admin version:
* 3.14.1

**Comment by djhi** [comment]
That's because `classes` accept a Material-UI classes object. Please read their documentation
