### ISSUE TITLE
how I can use ra-data-graphql-simple with typescript?

### ISSUE THREAD

**Issue by dmytropaduchak** [marmelab/react-admin#6124]
Invalid module name in augmentation. Module 'ra-data-graphql-simple' resolves to an untyped module at '../index.js', which cannot be augmented.
declare module 'ra-data-graphql-simple';

Could not find a declaration file for module 'ra-data-graphql-simple'. '.../index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ra-data-graphql-simple` if it exists or add a new declaration (.d.ts) file containing `declare module 'ra-data-graphql-simple';`

**Comment by djhi** [comment]
Indeed, we haven't migrated this package to TypeScript yet. We welcome any help on this matter ;)
