### ISSUE TITLE
rtl TextInput multiline  weird behavior

### ISSUE THREAD

**Issue by ahmadi-akbar** [marmelab/react-admin#6125]
## mycode result
https://user-images.githubusercontent.com/48069695/113502550-397ff780-9542-11eb-9b41-48209f65f77f.mp4

## CodeSandBox
![image](https://user-images.githubusercontent.com/48069695/113503505-9500b400-9547-11eb-9e00-b82952b0ecab.png)

codes
https://codesandbox.io/s/react-admin-text-input-rtl-cibzo

## steps to reproduce

1. got to https://cibzo.csb.app/#/user/create
2. type some long text to third field

**Comment by djhi** [comment]
Confirmed. Thanks!

**Comment by djhi** [comment]
Found the issue:  For some reason, passing a custom theme through `createMuiTheme` before providing it to the `Admin` component creates two themes and somehow all styles are doubled. As a workaround until we figure out how to fix it, just pass you theme object directly to the `Admin` component

**Comment by fzaninotto** [comment]
I suggest that when `<Admin>` receives a theme, it checks if it's a theme object or the result of `createMuiTheme` (not sure how), and only calls the latter if necessary.

**Comment by djhi** [comment]
The thing is, `createMuiTheme` is very simple: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/createMuiTheme.js. It just merges what it receives with some defaults

**Comment by djhi** [comment]
I can't reproduce the issue locally using the simple example and following the MaterialUI instructions for RTL

**Comment by ahmadi-akbar** [comment]
## solved
After hours working around theme, I found that it because of these snippet


In https://codesandbox.io/s/react-admin-text-input-rtl-cibzo?file=/src/Providers/theme.js
``` js
 overrides: {
    MuiInputBase: {
      root: {
        height: 40
      }
    }
  }
```

"hight: 40" make input's height be 40px even on multiline

**Comment by djhi** [comment]
I think there is a `multiline` class you can use as well, probably like this:

``` js
 overrides: {
    MuiInputBase: {
      root: {
        height: 40
      },
      multiline: {
          minHeight: 40
      }
    }
  }
```

**Comment by ahmadi-akbar** [comment]
@djhi tnx ✌✌😅
