### ISSUE TITLE
SelectInput with repeated choices crashes

### ISSUE THREAD

**Issue by ybrodsky** [marmelab/react-admin#6127]
**What you were expecting:**
That the SelectInput lets me have choices with items that have a repeated "value".

**What happened instead:**
Crashes because it's using the value as a `key` when mapping the `choices` array

**Steps to reproduce:**
Create an input like this:
```
  <SelectInput 
    source="something" 
    optionValue="val"
    optionText="label"
    choices={[
      { val: "one", label: "One" },
      { val: "one", label: "Another one" },
    ]}
  />
```

**Related code:**
https://github.com/marmelab/react-admin/blob/fdee4e8489fbda9f729e94c140f982bd3d595609/packages/ra-ui-materialui/src/input/SelectInput.tsx#L270

**Other information:**
Might be as easily fixed as to change that line to use the choice index instead.

**Comment by djhi** [comment]
This is indeed a requirement of the SelectInput. Choices must have unique values.

**Comment by ybrodsky** [comment]
Yes figured that part by the error in the console. However looking at the code there seems to be no reason for the values to be unique, other that you decided to use that property as key. 
Can't this be changed? It's not a real world case for values to be unique

**Comment by fzaninotto** [comment]
You can write your own SelectInput component if react-admin's on doesn't suit your need.
