### ISSUE TITLE
Add support for a createMany for dataProviders to allow the creation of multiple records 

### ISSUE THREAD

**Issue by wattry** [marmelab/react-admin#6131]
**Is your feature request related to a problem? Please describe.**
The dataProvider does not handle a createMany use case where you have a multiple records that you want to create in a single interaction. There is however a deleteMany and an updateMany which allow the response to be an array of items.

**Describe the solution you'd like**
We'd like a createMany handler in the dataProvider with a property on the create component that would allow us to handle this use case.

**Describe alternatives you've considered**
We considered building an entire create component and adding our own custom reducers. However, we feel it would not be a break away from the react admin style to allow for this functionality and it would possibly more effective to include it as a new feature.

**Comment by djhi** [comment]
Marking this as an enhancement while we discuss it. However, please note that you can extend the dataProvider supported actions as explained in the [documentation](https://marmelab.com/react-admin/DataProviders.html)

> A Data Provider can have more methods than the 9 methods listed above. For instance, you create a dataProvider with custom methods for calling non-REST API endpoints, manipulating tree structures, subscribing to real time updates, etc.

**Comment by wattry** [comment]
@djhi thanks for getting back to us, I appreciate your team taking the time to discuss the feasibility. 

We were able to create a solution that produces the required functionality using the documentation and the comment you provided. We'd like to stay as close as possible to the framework so as not lose the action dispatching, error handling and sanitization that is provided by ra-core, while still having the ability to use a <Create> component.

For anyone trying to solve the same problem, here is a snippet of stubbed out code that shows how we solved this

```
const dataProvider = {
  // ...
  createMany: async (resource, params) => {
    try {
      // Client side processing, perform on request at a time and the resolved promised are returned as an array.
      const data = await Promise.all(
        params.data.map((requestData) => {
          axios.post(`${baseUrl}/${resource}`, requestData)
        })
      );

      // Or server side processing, send all at once and let the server return results for all
      const { data } = axios.post(`${baseUrl}/${resource}`, params.data);

      return { data };
    } catch (error) {
      return Promise.reject(error);
    }
  },
}

// ------------------------------ //


function CustomCreate(props) {
  const dataProvider = useDataProvider();

  const onSuccess = () => {
    // ...
  }

  const onFailure = (error) => {
    // ...
  }

  const save = async (formData) => {
    try {
      const { data } = dataProvider.createMany('resource-name', { data: formData });

      onSuccess();
      return data;
    } catch (error) {
      onFailure(error);
    }
  }

  return (<Create>
    <SimpleForm save={save}>
      {/* ... */}
    </SimpleForm>
  </Create>);
}
```

Thanks again, and in advance.

**Comment by fzaninotto** [comment]
Your example is good, thanks for sharing it!

Adding more required methods to the `dataProvider` type makes it harder for contributors to create new implementations for custom backends. Besides, the framework currently doesn't use any functionality that would benefit from this action. So we won't add it to the core. 

But nothing prevents you to do so, as @djhi explained. We do it routinely in our projects and it works perfectly.

**Comment by shousper** [comment]
Sorry to jump into a closed issue, but my team has also just run into this challenge, which is a little more complicated with TypeScript. `createMany` is a great example that could be good to put into documentation alongside the current "Extending a Data Provider" example!

**Comment by shousper** [comment]
@wattry I haven't yet, no sorry. I imagine it'll involve augmenting the type returned by `useDataProvider` and authoring some custom hooks. Many thanks for your `createMany` example 🙏🏻
