### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop;

### ISSUE THREAD

**Issue by AndriiPetrashchukEmpeek** [marmelab/react-admin#6134]
I got the error "Warning: Each child in a list should have a unique "key" prop;" 
when I used the "SimpleList" component;

**Example**
     <SimpleList
          primaryText={record => record.email}
          secondaryText={record => record.roleId}
          tertiaryText={record => (record.isActive ? 'Active' : 'Inactive')}
          linkType="edit"
        />

**Environment**

* React-admin version: ^3.12.2
* React version: ^17.0.1
* Browser: Google Chrome

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
I confirm that I can't reproduce the problem with the simple example (where PostList renders a SimpleList on small screens). Could it be that some of the records in your list share the same id?

**Comment by fzaninotto** [comment]
I managed to reproduce the problem by slowing down the dataProvider. The problem lies in the `SimpleListLoading` component.

**Comment by aenonGit** [comment]
what if the items do not have ids? This is my case and I get the same error in console

**Comment by slax57** [comment]
@aenonGit As stated in the [docs](https://marmelab.com/react-admin/FAQ.html#can-i-have-custom-identifiersprimary-keys-for-my-resources):

> React-admin requires that each resource has an `id` field to identify it. If your API uses a different name for the primary key, you have to map that name to `id` in your [dataProvider](https://marmelab.com/react-admin/DataProviders.html).
