### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by AndriiPetrashchukEmpeek** [marmelab/react-admin#6135]
I got the error 

> Warning: validateDOMNesting(...): `<div>` cannot appear as a descendant of `<p>`.

when I used the "SimpleList" component;

I supposed i got this error because i passed prop "secondaryText"
which pass to the prop "secondary" of ListItemText there we have the condition:
secondary={ hasSecondaryText ? Placeholder  : undefined}
ListItemText it's node Element p
component Placeholder  return to us div node element

## Example

```
<SimpleList
primaryText={record => record.email}
secondaryText={record => record.roleId}
tertiaryText={record => (record.isActive ? 'Active' : 'Inactive')}
linkType="edit"
/>
```

## Environment

React-admin version: ^3.12.2
React version: ^17.0.1
Browser: Google Chrome

**Comment by djhi** [comment]
So make sure your Placeholder component does not return a `div`

**Comment by fzaninotto** [comment]
I could reproduce the bug in the simple example by making the dataProvider slower. The problem comes from our `<SimpleListLoading>` component.
