### ISSUE TITLE
ReferenceInput with SelectInput filtering not working

### ISSUE THREAD

**Issue by ig92** [marmelab/react-admin#6137]
Hi guys,

I've been trying to do a very basic thing this morning, filtering the values that can be selected in a SelectInput according to a simple boolean field. I have categories and subcategories. If a category is a subcategory it has a boolean field value isSubCategory set to true and of course I want the reference to the super category (name suffices). This is the code:
```
export const CategoryEdit = (props) => (
    <Edit {...props}>
        <SimpleForm>
            <TextInput source="name"/>
            <TextInput source="description"/>
            <BooleanInput source="isSubCategory"/>
            <FormDataConsumer>
                {
                    ({formData, ...rest}) => formData.isSubCategory &&
                        <ReferenceInput label="Category" source="mainCategory" reference="categories" filter={{isSubCategory: false}}>
                            <SelectInput optionText="name" validate={required()}/>
                        </ReferenceInput>
                }
            </FormDataConsumer>
        </SimpleForm>
    </Edit>
);
```
Of course I have the resource categories.

The problem is that the filtering is not working and thus I see the list of all the categories, both main categories and subcategories.

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by i1990jain** [comment]
faced the same issue please check your dataprovider maybe it is not sending the filter parameter in the request

**Comment by fzaninotto** [comment]
No news for some time, closing.
