### ISSUE TITLE
Specify data provider methods as generic (not just their arguments) for type safety

### ISSUE THREAD

**Issue by bayareacoder** [marmelab/react-admin#6143]
**Is your feature request related to a problem? Please describe.**
When manually calling data provider methods, or when they are called by react-admin behind the scenes, there is no type safety for input data, or returned data.

**Describe the solution you'd like**
1/ Provide the option to make all data provider methods type-safe by making them generic, so that at least when they are called manually it can be type-safe.
2/ Provide type-safety also when react-admin internally calls these methods. This would lead to a great DX where you could create a form for object create and it would err when a required property is forgotten, or a form for object update that would err if a property that cannot be updated is included.

**Describe alternatives you've considered**
We have coded 1/ ourselves in our data providers and how we call them manually, but it would probably be useful to enhance the docs with this (now that you have #5934)

eg. for `create` with `ResourceName` as a union of literal types which also ensures no non-existing resource names can be passed:
```
async create<T extends any = any, R extends RaRecord = RaRecord>(
    resource: ResourceName,
    params: CreateParams<T>,
  ): Promise<CreateResult<R>> {
// ...
}
```
and then call, for resource `Shop` as:
```
create<CreateShopData, Shop>('Shop', { data });
```

Then if you add overloaded declarations in your data provider for each of the narrowed resource types:
```
create(resource: 'Shop', params: CreateParams<CreateShopData>): Promise<CreateResult<Shop>>;
create(resource: 'Account', params: CreateParams<CreateAccountData>): Promise<CreateResult<Account>>;
// ...
async create<T extends any = any, R extends RaRecord = RaRecord>(
    resource: ResourceName,
    params: CreateParams<T>,
  ): Promise<CreateResult<R>> {
// ...
}
```
you can call without generics on the call site and get full type safety:
``` 
create('Shop', { data });
```

To avoid all the overloaded definitions, I tried first to do this with some kind of mapped/conditional type but that that wasn't successful so far.

**Additional context**
This builds further upon #5934 which introduced generics for the arguments to the data provider methods but not the methods themselves.

**Comment by fzaninotto** [comment]
I'm not sure to understand where you want to add these generics.

We already have them in `useDataProvider`:

```jsx
interface Product extends Record {
    name: string;
    sku: string;
}

const dataProvider = useDataProvider();
dataProvider.getOne<Product>('resources', 123)
   .then(({ data }) => {
        // TS sees data as Product
    })
```

We can't add these generics in `useQuery`, `useQueryWithStore`, or `useMutation` because they are dynamic in nature (the dataProvider method called is determined at runtime).

 `useGetList` and `useGetOne` are already generic:

```jsx
    const { ids, data, total, loaded } = useGetList<Product>(
        'posts',
        { page: 1, perPage: 10 },
        currentSort
    );
    // data is of type RecordMap<Product>
```

So the only places left to add them are the remaining the specialized hooks like `useUpdate`, `useCreate`, etc. Is that where you'd expect to specify the record type? Or somewhere else?

**Comment by bayareacoder** [comment]
it wasn't clear to me that there is some support already for generics. I didn't see it in the data provider doc at https://marmelab.com/react-admin/DataProviders.html#request-format and it's not obvious from the code or comments in `useDataProvider.ts`: 
```
/*
 * @example Action customization
 *
 * dataProvider.getOne('users', { id: 123 });
 * // will dispatch the following actions:
 * // - CUSTOM_FETCH
 * // - CUSTOM_FETCH_LOADING
 * // - FETCH_START
 * // - CUSTOM_FETCH_SUCCESS
 * // - FETCH_END
 *
 * dataProvider.getOne('users', { id: 123 }, { action: CRUD_GET_ONE });
 * // will dispatch the following actions:
 * // - CRUD_GET_ONE
 * // - CRUD_GET_ONE_LOADING
 * // - FETCH_START
 * // - CRUD_GET_ONE_SUCCESS
 * // - FETCH_END
 */
const useDataProvider = (): DataProviderProxy => {
```
So at least updating the docs to make it obvious where generics are supported would be good.

So yes also on the static create & update methods since not always do you specify all properties of the returned record in a create (server may add some that are returned in the response, eg a timestamp) so you'd most likely have a CreateParams<T> where T would be a subset of the RecordType, and then also allow to use a different type on UpdateParams<U> as U may be a subset of T as you may not be able to update all properties after creation.

In a real-world application with 20+ resources on a data provider and multiple data providers this really helps to make sure everything is correct by construction.

Understood that it cannot be done on the dynamic ones.

**Comment by fzaninotto** [comment]
I've updated the specialized dataProvider hooks in #6168.

As for moving the types from components to the dataProvider and through the form, I don't think it's possible due to the dynamic programming techniques we're using. 

Feel free to open a PR if you find a way to do so.

**Comment by bayareacoder** [comment]
Thanks but the typing is not as strict as what I requested. I see in the code it is now:
```
create = useCallback(
         (
             resource?: string | Partial<Mutation> | Event,
             data?: Partial<RecordType>,
             options?: MutationOptions
         )
```

So:
1. since the typing for `resource` allows non-literal types, it probably won't work with the overloaded function syntax in the data provider as there is no mutual exclusivity per resource type. 
2. typing `data` as `Partial<RecordType>` does not give any type safety to ensure you specify all required properties for a create, or protect against specifying non-updateable properties in `update`.  We have separate types for eg `UserRecord`, `CreateUserRecord`, `UpdateUserRecord` for this. This is also typical when you use a GraphQL backend where you will get separate types for inputs & payloads of all operations.

**Comment by fzaninotto** [comment]
I didn't understand that sentence:

> since the typing for resource allows non-literal types, it probably won't work with the overloaded function syntax in the data provider as there is no mutual exclusivity per resource.

Can you give examples of what you mean? 

As for the second point, please open a PR to implement what you want, we'll see if it makes sense to merge it in the core.

**Comment by bayareacoder** [comment]
Issue #1. I thought it was explained in my original post. We create overloaded data provider methods based on the resource. This works if the `resource` arg is defined as a literal union type: 
```
type Resource = `posts` | `users`
```
The TS compiler will now select the correct overloaded function based on the resource and since the declarations in the data provider specify the generic params for each resource, see my original post, you don't need to specify these when you call the methods.

Issue #2. I think the benefit of what I propose is clear, right and there is no downside since the 2nd generic argument (ie the `CreateParams<T>` generic type can be by default your current `Partial<RecordType>` so it is backward compatible. The change probably affects several locations so would probably be better done by you if it is deemed useful.

**Comment by fzaninotto** [comment]
I understand that you want to be much more type safe than what we currently target in react-admin. So please submit a PR if you feel you can contribute what you did to the core, but we won't work further on this subject for now.

**Comment by bayareacoder** [comment]
OK understood. 
FYI we actually take it 1 step further in our code by using an npm package called `runtypes`: https://github.com/pelotom/runtypes. In the data provider we type the expected runtypes and the package derives the static TS types automatically from that. During dev the package validates that the data from the API backend is consistent with the runtype/TS type. And with the above changes we link that type safety with the manual data provider calls.

**Comment by WinstonN** [comment]
I landed here today, because I wanted to run the demo application as described here https://github.com/marmelab/react-admin/tree/master/examples/demo

I followed all the steps, and on the last step `make run-demo` the site loads but with an error

```
Compiled with problems:X

ERROR

Plugin "react" was conflicted between "../../.eslintrc" and "BaseConfig » /home/win/Projects/private/smashem/react-admin/node_modules/react-scripts/node_modules/eslint-config-react-app/base.js".


ERROR in src/reviews/ReviewEditToolbar.tsx:19:35

TS2315: Type 'ToolbarProps' is not generic.
    17 | }));
    18 |
  > 19 | const ReviewEditToolbar = (props: ToolbarProps<Review>) => {
       |                                   ^^^^^^^^^^^^^^^^^^^^
    20 |     const {
    21 |         basePath,
    22 |         handleSubmitWithRedirect,
```

![image](https://user-images.githubusercontent.com/1143789/147797806-9e6854b9-c8be-4a54-8798-bacce04be798.png)

I can click away the error, but have not found a resolution yet

**Comment by WiXSL** [comment]
@WinstonN, 
Thaks for pointing this out.
This error was caused by a very recent change.
We'll try to fix it as soon as possible

**Comment by WiXSL** [comment]
#7045
