### ISSUE TITLE
UrlField does not allow fallbacks or explicit urls

### ISSUE THREAD

**Issue by dylanh724** [marmelab/react-admin#6148]
**What you were expecting:**

I expected to be able to explicitly put `'https://www.example.com'` under a UrlField `source` (for example, as a fallback or placeholder)

**What happened instead:**

Nothing - the result is empty

**Steps to reproduce:**

`<UrlField source='https://www.example.com />`

**Related code:**
^

**Other information:**

**Environment**

* React-admin version: Latest

**Comment by fzaninotto** [comment]
Wrong assumption :)

If you want to output a value (and not a field from the current record), you don't need ract-admin's `Field`, you need material-ui's `Link`.
