### ISSUE TITLE
Official Discord server (Revived)? Unofficial @ discord.me/react-admin

### ISSUE THREAD

**Issue by dylanh724** [marmelab/react-admin#6150]
This topic is revived due to misinformation from https://github.com/marmelab/react-admin/issues/4451

## Original
> Is your feature request related to a problem? Please describe.
The big issue is stackoverflow responses take a long time. If we have a channel to ask questions to people who are active in the community we may have a better chance of faster replies?
Describe the solution you'd like
Slack, DIscord or anything like that. You can have multiple channels like questions, types of apis it works with etc?
> 
> Describe alternatives you've considered
> Stackoverflow - not worth it

## Reply (with misinformation responses now added)

Thanks for your suggestion. We've considered it in the past, and I still don't think it's a good solution.

> A chat isn't searchable
* This is beyond-words untrue: **Discord** has an indexed search engine with more search filters than StackOverflow.

> If there are not enough community contributions on StackOverflow, why would there be more on a chat?
* Because chat at least has people hanging around - you're not lurking around stackoverflow niche topics, but the average dev will have Discord running. There's no one on StackOverflow (for this topic), when nearly all my Google searches result in landing on a GitHub issue where you respond "Use stackoverflow [where no one lurks at all]". There are numerous communities that use Discord significantly over stackoverflow (esp the more-niche ones). See the way Discord.js organizes here, as an example - https://discord.com/invite/bRCvFy9

> Unanswered questions on a chat feel even more frustrating than on a forum-like site like stackoverflow
* This is just untrue, as told blindly by someone that's clearly never used Discord (no offense): You'll eventually be @pinged, and users can CTRL+F later to quote/reference.

> There are no ways to encourage people to do support in a chat (stackOverflow gamification does that).
* This is just incorrect, as well: Again, see discord.js above. You can assign volunteer moderators as volunteer support via role systems. You essentially have community support instead of relying on the bloat of stackoverflow that buries your posts since no one uses it with react-admin. I expect 0 replies to my questions there. You also can set it up to be a "community" server and browsable.

> So we still won't open a chat support.
* You don't have to: The _community_ can support themselves, if there's a hub (that you have not attempted to provide; instead, you point people to put a tiny-message-in-a-bottle among an ocean of questions posted; you may as well express that you can cure global hunger "by simply asking the right questions"). 

### ^ That said, I went ahead and made an unofficial Discord react-admin community hub:
[https://discord.me/react-admin](https://discord.me/react-admin)

If Marm won't offer support (no worries, it's time-consuming and you're unpaid) and instantly closes tickets that doesn't even allow _community_ support (this part is odd), let's figure this out together! Because if you go to stackoverflow, everyone knows it's a waste of time for niche packages - expect your question to rot and go unanswered.

@ Marm, you're welcome to take over admin later should you wish to majority-participate, but this is the way.

**Comment by andrico1234** [comment]
I'd love a Discord channel, it would be easier for other people to help and get involved.

**Comment by fzaninotto** [comment]
Nice, thanks for taking the time to do that.
