### ISSUE TITLE
NumberInput `options` throws client errs

### ISSUE THREAD

**Issue by dylanh724** [marmelab/react-admin#6151]
`^3.13.5` in Chrome:

**What you were expecting:**
The page to load

**What happened instead:**
Client Error:
```js
Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
// Need callstack?
```

**Steps to reproduce:**

1. Add a `<NumberInput>`
2. Add the following options:
```js
const currencyOpts= 
{
  style: 'currency',
  currency: 'USD',
};

<NumberInput 
  source="fooSrc"
  locales="en-US"
  options={currencyOpts}
/>

// Remove `options=` and the error is gone.
```

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

**Comment by dylanh724** [comment]
## To add
More specifically, it's just `style` key name that's being detected as needing extra `{}`, which seems to be a false-positive err throw. If I just remove the `style: 'currency'` from `currencyOpts` const, the err goes away (although `currency` by itself is useless)

**Comment by fzaninotto** [comment]
`<NumberInput>` doesn't support the `options` prop (see [doc](https://marmelab.com/react-admin/Inputs.html#numberinput)). Besides, `NumberField` doesn't have the problem you describe.

So I think you got confused between fields and inputs, am I right?

**Comment by dylanh724** [comment]
Ah, I am confused by them - you are right... I must have looked at Field doc and assumed it worked for Input. My bad!

However, why wouldn't this also be supported for Input? It's a struggle when the user inputs a number and have it try to look like currency.

**Comment by djhi** [comment]
That would be an HowTo question. You can either ask it on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin) or on the new [discord](https://discord.gg/MR9QFxMc)

**Comment by fzaninotto** [comment]
Material-ui mentions custom formatter options in their documentation:

https://material-ui.com/components/text-fields/#integration-with-3rd-party-input-libraries

This isn't supported natively by react-admin, though. You'll have to write a custom Input component to support it.
