### ISSUE TITLE
Ability to pass additional context to data provider

### ISSUE THREAD

**Issue by abdusco** [marmelab/react-admin#6155]
**Is your feature request related to a problem? Please describe.**
When implementing a data provider I try to keep it as generic as possible, i.e. devoid of special cases. But some views (List/Show/Edit/Create) need some special handling (API needs a different shape of input, for example). Handling all these edge cases in the data provider is not very flexible and nor is it maintainable.

**Describe the solution you'd like**
I want to be able to pass some additional context to data provider from List/Show/Edit/Create components, also from `useDataProvider/useGetList/...` api hooks.

something like:
```tsx
const {data, loading} = useGetList('myresource', /*...*/, {
  async handleRequest(http, resource, payload) {
    const response = await http.get('/url', {params: {a: 1}});
    // ...
    return {data, total};
  }
})

// or from a view

const MyList = (props) => {
  return <List {...props} context={{
    async handleRequest(http, resource, payload) { ... }
  }}>
    // ...
  </List>
}
```

then I can add a check inside the data provider and run the hooks (as in functions passed inside the context, not react hooks):

```tsx
const http = axios.create(...);
const dataprovider: DataProvider = {
  async getList(resource, payload, context) {
    const {handleRequest} = context;
    if (typeof handleRequest === 'function') {
      return handleRequest(http, resource, context);
    }
    // default implementation
    // ... 
  },
  // ...
}
```

**Describe alternatives you've considered**
At the moment the only way I can send additional parameters to data provider is to shoehorn default `filter`s in List/dataprovider and check it inside `getList` method. But for other dataprovider methods there's not even that.

**Comment by fzaninotto** [comment]
Could you tell us more about your use case? Because it seems you're trying to use the generic `dataProvider.getList()` method to do something specific... In that case, we usually create custom methods in the `dataProvider`.

**Comment by abdusco** [comment]
Extending the data provider is always an option, and it works wonderfully. But that also means I cannot get native datagrid/list components to use these methods, which means I have to override a lot of things / write a lot of glue code for something that would have "just worked" (sorting, pagination, filters...) if it just used the standard data provider methods (getList, getOne etc.).  
I guess what I'm looking for is a way to get react-admin to call my own methods (if possible). Or a way to inject code which I could then call inside the data provider methods and let them override the default implementation/behavior.

**Comment by fzaninotto** [comment]
Then I guess you should use a custom resource name for these cases, and handle the logic in your dataProvider.

**Comment by abdusco** [comment]
That's actually a good idea. I hadn't thought of using a custom resource name. I think that's the most straightforward way to handle it.

Meanwhile, I've noticed that there's actually a third parameter passed to data provider methods. But it's not exposed to consumers downstream.

https://github.com/marmelab/react-admin/blob/98b30d3cef2b9fd5d556a1c995ff685a98c39403/packages/ra-core/src/dataProvider/useQueryWithStore.ts#L189

If I could tap into that, it might provide the feature I'm looking for. But only when calling the data provider methods myself. Not when using the standard List/Edit/Create/Show components.

**Comment by abdusco** [comment]
If I were to pass a value to as a property to List component, how would I go about passing this value all the way down to data provider?

--- 

I've found a workaround for it by giving these parameters as default filters, then reading it inside `getList` method.

```
return <List {...props} filter={{$mySpecialValue: 1}}>
    // ...
  </List>

// inside the getList method
async getList(resource, params) {
  const {$mySpecialValue} = params.filter;
  // ...
}
```

but it's an ugly hack.

**Comment by fzaninotto** [comment]
I don't think that using filters is an ugly hack. You actually want to filter the result, right?

Anyway, you actually have 2 ways to tell your dataProvider to do something special: filters and resource name. The dataProvider is the place where you should put this logic mapping react-admin queries to your API. 

Also, we don't want to add a channel to bypass the dataProvider for now, as the added complexity in the core would be huge. 

So I'm closing this issue as a "won't fix".

**Comment by george-mcintyre** [comment]
I found another way to solve this problem. 

```import {Resource} from "react-admin"

const ResourceWithProjection = ({projection, ...props}) => {
  // Save this projection for use later
  if (projection === undefined) {
    sessionStorage.removeItem(props.name + '.projection')
  } else {
    sessionStorage.setItem(props.name + '.projection', JSON.stringify(projection));
  }

  return (
    <Resource {...props}/>
  )
}

export default ResourceWithProjection
```

Then use it instead of `Resource` but add projection as an array of strings/objects
```
<ResourceWithProjection projection={["projectionField", { projectionSub: [ "subField" ] } ] } name="Assignment" options={{label: 'Assignments'}} list={AssignmentList} show={AssignmentShow} icon={AssignmentIcon}/>
 ```

Then in `buildQuery()` check to see if there are any projections for the resource you're  building the query for.  Note: `getProjectionString()` parses the array of strings/objects to produce a normal projection for use in the graphql query/mutation.

```
const buildQuery = (jsonIntrospectionResults) => (raFetchType, resourceName, params) => {
  let projection = sessionStorage.getItem(resourceName+".projection")
  if (projection !== undefined && projection !== null) {
    projection = JSON.parse(projection)
    projection = getProjectionString(projection)
  } else {
    projection = undefined /* your normal method for getting projection */
  }

...
```

**Comment by suamai** [comment]
An use case I'm having where something like this could be useful is for pagination based on pointers. 

I'm using Dynamodb as my database and need a few keys to perform some kinds of ordered paginations - as the usual route for pagination seems to be kinda locked on numbered pagination.

Trying to work around I've faced some issues: 
- There is no way to pass the information down to the dataProvider, trying to use a custom Pagination with `setPage` gets messy really quickly, since it's passed to the url and any complex data needs to be constantly manually stringfied/parsed. 
- Trying to use Redux with `customReducers` to store the relevant keys does not work, since RA does not expose its store and I cannot access it from the dataProvider
- Using the filter ( to do a pagination, so in this case would totally say it's a hack ) ends up in an infinite loop - each request will generate a new cursor, and so a new "filter", wich then triggers a new request...

I've seen a few issues on cursor-based pagination from a few years ago, but they all seem to have been abandoned. Having some way to give some custom context to the `dataProvider` could let us craft ways to solve almost all of those problems.

**Comment by abdusco** [comment]
> Trying to use Redux with customReducers to store the relevant keys does not work, since RA does not expose its store and I cannot access it from the dataProvider.

@suamai One workaround we've employed to use redux store inside the data provider (to get access to global UI state & to show upload progress for large files) is to unwrap the `<Admin/>` component, build the store yourself, then inject it to your data provider inside the custom admin component. Something like this (pseudo-code):


```text
import {Admin} from 'react-admin'
import {Provider} from 'react-redux'

const CustomAdmin = ({dataProvider}) => {
  const store = makeReduxStore();
  dataProvider.setStore(store);
  return <Provider store={store}>
    <Admin dataProvider={dataProvider} />
  </Provider>
}
```
