### ISSUE TITLE
Warning: Failed prop type: The prop `selectedIds` is marked as required in `BulkDeleteButton`, but its value is `undefined`.

### ISSUE THREAD

**Issue by vladyslavsokulskyiempeek** [marmelab/react-admin#6157]
I got the error "Failed prop type: The prop `selectedIds` is marked as required in `BulkDeleteButton`, but its value is `undefined`".

**Related code:**
https://codesandbox.io/s/xenodochial-kepler-1hqhj?file=/src/posts/PostList.tsx

**Example**
```
<List
  {...props}
  bulkActionButtons={<BulkDeleteButton />}
>
```

**Environment**

* React-admin version: 3.12.4
* React version: ^17.0.0
* Browser: Google Chrome

**Comment by fzaninotto** [comment]
Confirmed, thanks
