### ISSUE TITLE
Menu icon in NavBar alignment with side bar icons

### ISSUE THREAD

**Issue by JayKaku** [marmelab/react-admin#6159]
![image](https://user-images.githubusercontent.com/61429929/114522249-d4728300-9c60-11eb-9cd9-32dff6e503d7.png)

The Menu icon on the Navigation bar for the sidebar (top left corner) would look great if it were aligned in line with the icons below, let me your thoughts, I'll make the required changes

**Comment by fzaninotto** [comment]
Good catch! As we want to emphasize the content rather than the chrome, the change must be to reduce the left margin in the navbar rather than to increase the left margin in the menu.

Feel free to send us your PR!
