### ISSUE TITLE
Error running Demo individually

### ISSUE THREAD

**Issue by andreslon** [marmelab/react-admin#6166]
I'm getting an error only downloading the project, restoring packages and starting:

`npm install`
`npm start`

https://github.com/marmelab/react-admin/tree/next/examples/demo

![image](https://user-images.githubusercontent.com/2242679/114772705-bd509580-9d33-11eb-9cb7-2ae33e0584be.png)

**Comment by djhi** [comment]
That's most probably because you used npm and it installed different versions of material-ui.

**Comment by fzaninotto** [comment]
Did you follow the README about running the examples? https://github.com/marmelab/react-admin#examples

**Comment by vorotech** [comment]
hi @andreslon 
Got the same issue while trying to lunch a demo with the latest react-admin and its dependencies.

Try to change in the GridList.tsx:

```diff
- interface GridProps extends DatagridProps, WithWidth {}
+ interface GridProps extends Omit<DatagridProps, 'width'>, WithWidth {}
```

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by jamesholcomb** [comment]
Thanks @vorotech your solution worked for me.
