### ISSUE TITLE
Adding component=pre to TextField in list removes "Add Filter" and "Export" buttons

### ISSUE THREAD

**Issue by LeslieMurphy** [marmelab/react-admin#6171]
**What you were expecting:**

I tried to use component="pre" on a textfield so it would process newlines in the text to split out the lines.  I saw this technique in a SO article on react-admin.  My goal was to preserve newlines in a textfield within a list.

See https://stackoverflow.com/questions/55940218/preserving-line-breaks-with-react-admin-material-uis-textfields

Using a class instead works fine - I updated the SO article with comments about using component=pre in a TextField in the List

**What happened instead:**
The field splits using the newlines and looks good - but the buttons at the top for "Add Filter" and "Export" disappear!

**Steps to reproduce:**

`<TextField source="summaryMessage" component="pre" />`

vs

`<TextField source="summaryMessage"   />`

**Environment**

* React-admin version:
3.14.3

* Last version that did not exhibit the issue (if applicable):

* React version:
17.0.2

* Browser:
Edge or Firefox

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by LeslieMurphy** [comment]
My app was based on sample code from 3.9.2.  The new sample app has a lot more features!   I tried applying the component="pre" to the Posts and it worked as expected (wrapped the text, and it left the Add Filter and Create and Export visible in the top bar.

So - so far UNABLE TO RECREATE.

If I get more time I will try to isolate what is different about my application vs the sample.  Perhaps there is an underlying  node package dependency I did not update when I updated to 3.14.3 today.

**Comment by fzaninotto** [comment]
> The new sample app has a lot more features!

Yes, a lot happens in 6 months! We've been hard at work.

> so far UNABLE TO RECREATE

Right, so we'll close this issue. If you happen to recreate it, please add a reproduction case to this issue and we'll reopen it.

**Comment by christylaguardia** [comment]
I had this problem when passing an export button to `List` and while having `exporter={false}`
