### ISSUE TITLE
Undo link color on success notification

### ISSUE THREAD

**Issue by jeroenvdmeer** [marmelab/react-admin#6173]
**What you were expecting:**
Using the new "success" notification type, the notification is turned green. The undo link is still the primary color of the theme, which by default is blue. I would expect the link color to match the green notification color, such as [green 900 (#1b5e20)](https://material-ui.com/customization/color/).

**What happened instead:**
![image](https://user-images.githubusercontent.com/1658477/114979686-9d33ea00-9e8b-11eb-90ed-4b74a3b38b1d.png)

**Steps to reproduce:**
`notify("resources.employee.updated", "success", {}, true)`

**Environment**
* React-admin version: 3.14.3
* React version: 17.0.2
* Browser: Chrome Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by djhi** [comment]
Thanks for reporting this

**Comment by fzaninotto** [comment]
I've reverted #6189, so I'm reopening this issue.
