### ISSUE TITLE
Props to control HideOnScroll  behavior of AppBar

### ISSUE THREAD

**Issue by pkspyder007** [marmelab/react-admin#6174]
**Is your feature request related to a problem? Please describe.**
I have a fixed sidebar that is toggled by the App bar for expanding and collapsing. But after scrolling down there is no button to toggle the side menu until the user scrolls back up.

https://user-images.githubusercontent.com/331353/114960721-a2664a00-9e35-11eb-8e3b-76e9dce47d1e.mov

**Describe the solution you'd like**
Ability to control the hideOnScroll behaviour through a prop on AppBar component would be really helpful for enhancing user experience.

**Describe alternatives you've considered**
Adding a second toggle button behind the appbar in side menu, but that would be redundant.

**Comment by pkspyder007** [comment]
@djhi We are using React-admin a lot at [Navidrome](https://github.com/navidrome/navidrome). There are few suggestions I would like to give.
- Having the ability for fixed/sticky side menu 
- Changing Menu icon in AppBar on toggling

React-Admin provides the ability to provide a custom implementation for these use-cases but deviates us from the framework. Having the ability to change such properties based on props or some other method will help a lot.
I appreciate the work that you people have put in creating such an amazing technology 🙌

**Comment by fzaninotto** [comment]
Fixed by #6178
