### ISSUE TITLE
Pin the Bulk Actions Toolbar to the top.

### ISSUE THREAD

**Issue by YashJipkate** [marmelab/react-admin#6180]
**Is your feature request related to a problem? Please describe.**
If we have many records on one page in the list, and if we select multiple records by scrolling down, the Bulk Action Toolbar goes out of view. I have to scroll all the way up to perform the bulk actions. It gets only worse if we try to implement something like infinite scroll. 

**Describe the solution you'd like**
The toolbar should be fixed at the top, not scrollable. That would make the toolbar very handy.

**Additional context**
A screen recording here: 

https://user-images.githubusercontent.com/34203227/115080943-247f6d00-9f21-11eb-9df6-32dead079cf6.mp4

**Comment by sarangpm18** [comment]
I'd like to work on this issue, can I raise a PR?

**Comment by YashJipkate** [comment]
@sarangpm18 I was actually thinking of waiting for one of the maintainers to give their feedback on this feature request. Once they give this a go, you can send a patch.

**Comment by djhi** [comment]
That's a cool idea. Maybe we can even pin the table headers. @sarangpm18 Please do!

**Comment by sarangpm18** [comment]
> That's a cool idea. Maybe we can even pin the table headers. @sarangpm18 Please do!
> 
> PS: Please target the `next` branch

I am on it

**Comment by fzaninotto** [comment]
I'm closing this issue as you now know that a PR for this will be welcome.
