### ISSUE TITLE
useGetMany options.enabled not working

### ISSUE THREAD

**Issue by capJavert** [marmelab/react-admin#6184]
`options.enabled` does not seem to do anything inside `useGetMany` hook. Option exists in docs but it is not used anywhere, and if you put `false` it still execute the query.

```js
// this will still execute even though `false` is provided
const { data } = useGetMany('taxonomies', navIds, {
    enabled: false
})
```

**Other information:**

**Environment**

* React-admin version: 3.14.1
* Last version that did not exhibit the issue (if applicable): it does
* React version: 16.13.1
* Browser: Any

**Comment by djhi** [comment]
Thanks for reporting this
