### ISSUE TITLE
Redirection After Submission to external route

### ISSUE THREAD

**Issue by cebucul** [marmelab/react-admin#6194]
**Is your feature request related to a problem? Please describe.**
 
Hi,
Documenting here per discussion at: 
https://stackoverflow.com/questions/67047157/react-admin-redirect-button-with-parameters-from-form

RA doesn't redirect to external routes after form submission. (simple form)

**Describe the solution you'd like**
 
Please implement functionality to redirect also to external websites (routes) as the current solution described at:
https://marmelab.com/react-admin/CreateEdit.html#redirection-after-submission
only redirects to internal routes.

Thank you
**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fzaninotto** [comment]
This enhancement request hasn't gained enough interest to get a PR from the community. As we canot keep all feature requests open, I'm closing it. 

If you feel like working on this feature, we'd love a PR!
