### ISSUE TITLE
`initialValue` `defaultValue` props no longer work in edit views

### ISSUE THREAD

**Issue by jtomaszewski** [marmelab/react-admin#6198]
**What you were expecting:**

Just as it works in `Create`, inputs placed inside of a `SimpleForm` in `Edit` view, when they have a `initialValue` / `defaultValue` prop, I'd expect that value to be used (if the initial value for the given `source` is `null` or `undefined`).

Currently, that default value is shown, but only for first ~10-50ms of form being rendered - and then is set back to `undefined`.

**Steps to reproduce:**

Go to https://codesandbox.io/s/cranky-voice-psf4s . See that the default value is not respected in PostEdit view, but it is respected in PostCreate view.

**Environment**

* React-admin version: 3.14.3

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report.

**Comment by fzaninotto** [comment]
I managed to track this regression to version 3.13.3, so it was probably introduced by #6005
