### ISSUE TITLE
Allow passing children to ListAction component

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6212]
In order to add custom `actions` to the `List` component, one has to replace the entire default ´ListActions´ component with something else.

Couldn't it be possible to re-use `react-admin`'s `ListActions` component and pass children to it?

**Comment by fzaninotto** [comment]
As explained in #6218, I don't think this is a good idea. I agree that the current way of overriding the List actions isn't very user friendly, but the solution that you propose isn't a clear win and brings confusion.

**Comment by fzaninotto** [comment]
Fixe by #6218
