### ISSUE TITLE
React Admin, Achieve the Empty page feature, while having a "filterDefaultValues" tag in the <List>

### ISSUE THREAD

**Issue by SameetPati** [marmelab/react-admin#6213]
As per the documentation of "React Admin", in the filter tag we cannot give "alwaysOn" and "defalutValue" at the same element.

In my case, 
I need an element to be alwaysOn with default value in the filters, so I am passing the "filterDefaultValues" at the list level, by this the Empty page feature is getting over ridden.
**I need the Empty page to be loading up.** but not able to achieve this.

My filters -
        Filter {...props} SelectInput source="StatusFlag" label="Status" choices={StatusFlags} alwaysOn 

My List -
```jsx
        <List {...props} filters={<ListFilter />} filterDefaultValues={{ StatusFlag: '1' }}
            // empty={ <Empty/>}    // **nor the default empty page is working not the declared one, but i need it.**
        ></List>
 ```

**Comment by fzaninotto** [comment]
This enhancement request hasn't gained enough interest to get a PR from the community. As we canot keep all feature requests open, I'm closing it. 

If you feel like working on this feature, we'd love a PR!
