### ISSUE TITLE
[RFC] Additional syncWithLocation strategies

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#6216]
# Problem
When using the `TabbedForm` or `TabbedShowLayout` we can either set `syncWithLocation` to `true` or `false`.

Setting it to `false` means the browser's default back button takes the user previous page, but not the previous tab. Refreshing the page causes the page to reload to the first tab of the page.

With `syncWithLocation` set to `false` this poses a problem in the `Edit` view. 

In a page with 3 tabs, if I:
- go to the third tab
- make some changes
- press save
- have `TabbedForm` call the `onSuccess` callback with `refresh`.

Then the page will refresh and redirect the user back to the first tab. This is expected behaviour, but it feels very clunky and will leave users feeling confused.

Setting `syncWithLocation` to `false` makes sense though, because pressing the back button should take us back a whole page, not just a tab.

# Solution

Instead of a boolean value, we can treat the property similar to `mutationMode` and pass through the strategy we want to employ, which can be one of three things: `off`, `push`, `replace`.

`off` is equivalent to `syncWithLocation={false}`

`push` is equivalent to `syncWithLocation={true}`

`replace` would be in the middle, where clicking a tab would replace the current item in history stack. That way we sync tabs with location, while also getting the ability to go back a page.

Implementing this change would require something like the following

```tsx
export const Tab = ({ syncWithLocation = 'push', ...rest }) => {
    const propsForLink = {
        component: Link,
        to: { ...location, pathname: value },
        replace: syncWithLocation === 'replace',
    };

    const renderHeader = () => (
        <MuiTab
            {...(syncWithLocation ? propsForLink : {})} // to avoid TypeScript screams, see https://github.com/mui-org/material-ui/issues/9106#issuecomment-451270521
            {...rest}
        />
    );

    const renderContent = () => <blah>// component logic</blah>;

    return context === 'header' ? renderHeader() : renderContent();
};
```

I'm happy to implement this, i don't think it's too technically demanding, but I wanted thoughts to see if there are any reasons why we shouldn't go ahead with this approach

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion!

I'm not sure we want to address this use case in the code. SyncWithLocation was designed to allow more than one tabbed form/layout per page, not to have a back button return to the previous page. Also, it's achievable in userland (as `<Tab>` passes rest props to `<MuiTab>`). Finally, I'm not fond of the added complexity and the breaking change.

So I'm -1 about this.

**Comment by andrico1234** [comment]
Thanks for the response, this makes perfect sense and I hadn't considered the complexity this adds for multiple tabs in a page.
