### ISSUE TITLE
NumbeField does not work with ReferenceField

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#6229]
**What you were expecting:**

I expect the `NumberField` used inside `ReferenceField` to renders a euro price related format.

**What happened instead:**

The number is display as raw value, like a `TextField` would do.

**Steps to reproduce:**

Create a show template using a `ReferenceField` with a `NumberField`.

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```typescript
<ReferenceField
  source="transactionId"
  label="Transaction"
  reference="transactions"
  link="show"
  {...props}
>
  <NumberField
    source="amount"
    locales={['fr']}
    options={{
      style: 'currency',
      currency: 'EUR',
    }}
  />
</ReferenceField>
```

Note: My API also return a `transaction` object related to the `transactionId` property and if I bind a `NumberField` directly on `transaction.amount`, it does render the number as a price.

**Other information:**

**Environment**

* React-admin version: `3.14.5`
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Firefox Dev Edition 87.0b4 (64-bit)
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I can't reproduce it in the simple example, so the problem is likely on your side. . Please post a list to [a fork of the simple example codesandbox](https://codesandbox.io/s/beautiful-brook-l34cd?file=/src/comments/CommentList.tsx) that reproduces the issue.

**Comment by soullivaneuh** [comment]
I did create a fork: https://codesandbox.io/s/react-admin-reference-number-issue-ti8mv?file=/src/comments/CommentShow.tsx

But indeed, it seems to work here.

I keep investigating why it is not for my case. If you have any clue, I am hearing. :+1:

**Comment by soullivaneuh** [comment]
In which case the `NumberField` may not show the value with the wanted format? :thinking:

**Comment by soullivaneuh** [comment]
Ok I found the source of the problem. On the previous code sample I have `{...props}` added on the `ReferenceField`. Remove it and all is working.

I updated the sandbox accordingly.

As this line was not wanted and imported by a bad copy/paste, this solve my issue.

However, I don't know if you may want to improve the error handling for that case. I let you close the issue or not accordingly.

Thanks
