### ISSUE TITLE
useQueryWithStore should not show loading = true when enabled = false

### ISSUE THREAD

**Issue by OoDeLally** [marmelab/react-admin#6236]
```ts
const { data, isLoading } = useGetOne(myResource, myId, { enabled: false })
```

**What you were expecting:**
```ts
isLoading = false
```

**What happened instead:**
```ts
isLoading = true
```

**Steps to reproduce:**
Run this above code.

**Other information:**

It likely comes from `useQueryWithStore`, which sets `loading: true` regardless of whether `enabled` is true or false.

**Environment**

* React-admin version: 3.14.5
* Last version that did not exhibit the issue (if applicable): /
* React version: 17.0.2
* Browser: Chrome

**Comment by djhi** [comment]
Indeed, thanks for the report
