### ISSUE TITLE
Failed to compile demo

### ISSUE THREAD

**Issue by vaheeds** [marmelab/react-admin#6244]
The brand new copy of demo example has some errors:

```
Failed to compile
src\dashboard\Dashboard.tsx
  Line 168:37:  Parsing error: Unexpected token, expected "}"

  166 |   return isXSmall ? (
  167 |     <div>
> 168 |       <div style={styles.flexColumn as CSSProperties}>
      |                                     ^
  169 |         <Welcome />
  170 |         <MonthlyRevenue value={revenue} />
  171 |         <VerticalSpacer />

src\dashboard\OrderChart.tsx
  Line 35:15:  Parsing error: Unexpected token, expected ","

  33 |             acc[day] += curr.total;
  34 |             return acc;
> 35 |         }, {} as { [key: string]: number });
     |               ^
  36 |
  37 | const getRevenuePerDay = (orders: Order[]): TotalByDay[] => {
  38 |     const daysWithRevenue = aggregateOrdersByDay(orders);

src\dataProvider\rest.ts
  Line 14:53:  Parsing error: Unexpected token, expected "]"

  12 |                           () =>
  13 |                               resolve(
> 14 |                                   restProvider[name as string](resource, params)
     |                                                     ^
  15 |                               ),
  16 |                           500
  17 |                       )
```

**Comment by fzaninotto** [comment]
You're trying to parse a TypeScript file in Javascript. I don't know how you did it, but when opening the source code in the main repository, there is no such error.

**Comment by vaheeds** [comment]
I just copy the `demo` folder from the `react-admin/examples/` folder and 

`yarn install`  then `yarn start`, that's it. Is there something that I've missed?

**Comment by vaheeds** [comment]
> I just copy the `demo` folder from the `react-admin/examples/` folder and
> 
> `yarn install` then `yarn start`, that's it. Is there something that I've missed?

I want to create a new project base on the demo example.

**Comment by fzaninotto** [comment]
Start by following the README at https://github.com/marmelab/react-admin/tree/master/examples/crm

**Comment by jaballogian** [comment]
> The brand new copy of demo example has some errors:
> 
> ```
> Failed to compile
> src\dashboard\Dashboard.tsx
>   Line 168:37:  Parsing error: Unexpected token, expected "}"
> 
>   166 |   return isXSmall ? (
>   167 |     <div>
> > 168 |       <div style={styles.flexColumn as CSSProperties}>
>       |                                     ^
>   169 |         <Welcome />
>   170 |         <MonthlyRevenue value={revenue} />
>   171 |         <VerticalSpacer />
> 
> src\dashboard\OrderChart.tsx
>   Line 35:15:  Parsing error: Unexpected token, expected ","
> 
>   33 |             acc[day] += curr.total;
>   34 |             return acc;
> > 35 |         }, {} as { [key: string]: number });
>      |               ^
>   36 |
>   37 | const getRevenuePerDay = (orders: Order[]): TotalByDay[] => {
>   38 |     const daysWithRevenue = aggregateOrdersByDay(orders);
> 
> src\dataProvider\rest.ts
>   Line 14:53:  Parsing error: Unexpected token, expected "]"
> 
>   12 |                           () =>
>   13 |                               resolve(
> > 14 |                                   restProvider[name as string](resource, params)
>      |                                                     ^
>   15 |                               ),
>   16 |                           500
>   17 |                       )
> ```

Hello @vaheeds 

First, I also had these issues before.
Then, I tried to follow this instruction below.

> Start by following the README at https://github.com/marmelab/react-admin/tree/master/examples/crm

The issues on some Typescript files were already gone.
Here are my steps:
1. Clone the root project https://github.com/marmelab/react-admin.
2. Open the root project folder.
3. Install all packages using ```npm install``` command.
4. Go to the example folder you want to run (```crm```, ```data-generator```, ```demo```, etc).
5. Install all packages using ```npm install``` command (inside of the selected example folder).
6. Back to the root project folder.
7. Open ```package.json``` file and you will see all the commands below in the ```scripts``` section:

![image](https://user-images.githubusercontent.com/24468466/122864706-519c3180-d34f-11eb-8ded-acfcaf8eba83.png)

8. Just type one of the commands inside the ```scripts``` section. For example, I want to run the demo dashboard (inside example > demo folder) so I just need to type ```yarn run-demo```

But after doing those, now I get new errors in some Typescript files.

![image](https://user-images.githubusercontent.com/24468466/122864976-c53e3e80-d34f-11eb-904b-6522560a73cf.png)

So what is the solution to run successfully one of the dashboard examples @fzaninotto ?
Or is there something wrong with my steps?

I have already checked some issues about ```prettier``` in this repo but I don't understand much since I've never used ```prettier``` package and Typescript in building a ```react```` app.

**Comment by djhi** [comment]
That's most probably because you used npm instead of yarn and it may have ignored the `yarn.lock` file thus updating many dependencies

**Comment by jaballogian** [comment]
> That's most probably because you used npm instead of yarn and it may have ignored the `yarn.lock` file thus updating many dependencies

I have tried using ```yarn``` like these steps:
1. Clone the root project https://github.com/marmelab/react-admin.
2. Open the root project folder.
3. Install all packages using ```yarn install``` command.
4. Run ```yarn run-demo``` to run the demo dashboard but got this error

![marmela](https://user-images.githubusercontent.com/24468466/122895512-5faf7980-d372-11eb-8f67-8537a5dc778c.PNG)

I think I should try to install (Windows 10) and use the ```make``` command instead.

**Comment by jaballogian** [comment]
I have tried using the ```make``` command like these steps:

1. Clone the root project https://github.com/marmelab/react-admin.
2. Open the root project folder.
3. Run ```make install``` command then get this error

![marmelab](https://user-images.githubusercontent.com/24468466/122902946-20d0f200-d379-11eb-9748-395c314c1b2c.PNG)

My environment:
- Node version: 12.19.0
- Npm version: 6.14.8
- OS: Windows 10 Home build 19042
- GNU make 4.3

So what's the solution in this case now?

**Comment by fzaninotto** [comment]
I advise you to use a Linux OS (or WSL2 on Linux). We don't want to spend time on Windows support.

**Comment by jaballogian** [comment]
> I advise you to use a Linux OS (or WSL2 on Linux). We don't want to spend time on Windows support.

Thank you for the advice.

**Comment by deksden** [comment]
My way to solve problems with CRM demo (I m on macOS). 

First, make commands does not work, producing some errors with `make build` command.

Then i copied whole CRM demo into separate project, and make some tweaks:

1) package.json: upgraded react-admin version to v3.17.0
2) added dev dep: "@types/react-router-dom": "^5.1.8",

thats it. Demo now runs

**Comment by deksden** [comment]
UPD: as for 3.17.2 and my macos - there is no build issues for CRM demo on fresh install of react-admin!
