### ISSUE TITLE
Inconsistent and wrong order of CSS styles in <head>

### ISSUE THREAD

**Issue by sMteX** [marmelab/react-admin#6245]
**What you were expecting:**
Correct order of CSS imports in the HTML `<head>`. I would assume Material UI's styles, then React-Admin's styles, then our custom `makeStyles`.

Example would be overriding `<MenuItemLink />` style in `theme` as described [here](https://marmelab.com/react-admin/Buttons.html#menuitemlink), to change colors of the sidebar menu items.

**What happened instead:**
CSS styles are imported inconsistently in `<head>`. Sometimes it's MUI, then RA, then MUI again and `makeStyles`, but it can get even more mixed. The result is inconsistent styles, ignored custom styles, duplicate CSS classes overwriting previous CSS properties etc.

In the example, what happens for me is that the theme overrides _are_ inserted into `<head>` but are overwritten by `.MuiButtonBase-root` which is inserted later.

**Steps to reproduce:**
Unfortunately, I haven't been able to reproduce my issue on `codesandbox.io`.

**Related code:**

See StackOverflow link below.

**Other information:**

This bug started happening in my app when I upgraded from React-Admin `3.10.3` to `3.15` (and with it, `@material-ui/core` to `4.11.4`), it didn't happen before. I originally thought it's just a problem with the `theme` but it seems like if this was somehow expected change, there would be _some_ note in documentation, or a migration guide or something. It might also be some unexpected interaction with Next.js (which to be fair is outdated, 9.5.5), but I'm out of ideas on even identifying the root cause, let alone fixing it.

I described the issue more in details in this StackOverflow question: [https://stackoverflow.com/questions/67369087/react-admin-css-theme-overrides-are-placed-earlier-in-head-and-getting-overwri](https://stackoverflow.com/questions/67369087/react-admin-css-theme-overrides-are-placed-earlier-in-head-and-getting-overwri)

**Environment**

* React-admin version: `3.15`
* Last version that did not exhibit the issue (if applicable): `3.10.3`
* React version: `16.14.0`
* Browser: `Firefox 88.0`

**Comment by djhi** [comment]
We don't handle styles ourselves and only use material-ui solution. I suggest you open an issue on their repository. Besides, if you can't reproduce it, we can't fix it

**Comment by sMteX** [comment]
@djhi I expected as much, but thank you very much for pointing me in their direction. I had no idea where this is handled.

**Comment by sMteX** [comment]
Leaving this here in case anyone comes with similar issue - before trying anything else, try deleting `node_modules` folder and reinstall packages from scratch. For me, something went wrong during the process of updating the versions and all issues fixed themselves after reinstalling.
