### ISSUE TITLE
Support for Full Vertical Menu

### ISSUE THREAD

**Issue by dknight10** [marmelab/react-admin#6250]
**Is your feature request related to a problem? Please describe.**
react-admin currently only allows the layout to be an app bar that spans the entire top of the page, with the menu tucked under it.

**Describe the solution you'd like**
It would be nice to have a different layout option in which the side menu spans to the top of the page. This look seems to follow a more "modern" trend among admin-type apps (see examples below).

**Describe alternatives you've considered**
Manually overriding the Layout component in https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/Layout.tsx.

**Additional context**
<img width="792" alt="Screen Shot 2021-05-06 at 6 13 50 AM" src="https://user-images.githubusercontent.com/10201947/117283146-80a82380-ae33-11eb-9c85-667da1c9834a.png">

<img width="792" alt="Screen Shot 2021-05-06 at 6 14 53 AM" src="https://user-images.githubusercontent.com/10201947/117283219-9289c680-ae33-11eb-90ee-74c749008650.png">

**Comment by djhi** [comment]
We could support a variant for this but as it's doable in userland by overriding the layout, I'm not sure we will. Flagging as a possible enhancement. Feel free to open a PR to discuss the implementation

**Comment by fzaninotto** [comment]
We won't support it in core as it's achievable in user land. See e.g. in the CRM demo how we use a completely different navigation system. React-admin doesn't aim to provide all possible UIs out of the box, but to provide one, opinionated one, and to allow to change it easily.

Also, what you see as a "modern" trend isn't necessarily adapted to admins, where a top app bar is often necessary to host a page name, a user menu, a search engine, etc.

**Comment by dknight10** [comment]
Fair enough. In this case there would still be an app bar, would just be laid out differently. 

I'll take a look at the CRM demo. 

Thanks guys.
