### ISSUE TITLE
BooleanInput with default value false not working

### ISSUE THREAD

**Issue by burnes** [marmelab/react-admin#6269]
**What you were expecting:**
If I add a new BooleanInput Filter with default value `false` on a List, I'd expect the list to filter for falsy attributes when adding the filter.

**What happened instead:**
The list stays the same and still lists items with true and false values.

**Steps to reproduce:**
Add a BooleanInput with defaultValue `false`
```
    <BooleanInput
      source="commentable"
      defaultValue={false}
      label="(Not) commentable"
    />
```

Select the Input on `Add Filters'.

**Related code:**

CodeSandbox example:
https://codesandbox.io/s/magical-field-e32pv?file=/src/posts/PostList.tsx:959-1069

**Environment**

* React-admin version: 3.12.4
* React version: 17.0.0
* Browser: Chrome, all

**Comment by djhi** [comment]
It seems to work on the codesandbox. Did I miss something?

**Comment by burnes** [comment]
@djhi I expected that after adding the filter the list would not contain posts without comments 

![Screenshot 2021-05-12 at 09 46 37](https://user-images.githubusercontent.com/568455/117938334-34635480-b307-11eb-9539-4034ced2dac4.png)

**Comment by burnes** [comment]
@djhi After setting the filter I would expect the list to contain only items where commentable is false (X)

![Screenshot 2021-05-12 at 09 46 37](https://user-images.githubusercontent.com/568455/117938456-5bba2180-b307-11eb-8959-aa0d9348a1a9.png)

**Comment by djhi** [comment]
Nevermind, reproduced it this time

**Comment by djhi** [comment]
Thanks for the report
