### ISSUE TITLE
Global + Input Validation don't consolidate properly

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#6270]
**What you were expecting:**
When using both global + input level validation, there are scenarios where RA doesn't reconciliate the values properly. This can lead to the local errors being overridden by the global validation.

According to the [docs](https://marmelab.com/react-admin/CreateEdit.html#validation)

> Tip: You can use both Form validation and input validation.

I've provided an example with this branch: https://github.com/andrico1234/react-admin/tree/feature/validation-error

You'll need to run the local example, and navigate to: http://localhost:8080/#/posts/13

If you jump to PostEdit page, I have two groups of inputs. The `name` input is being validated on the global level, while the `tag` input is being validated on the input level.

It looks like in this scenario, the object being returned on the global value is overriding the value being set on the input level.

In the example, if you try and pass through an empty value to `tag` nothing happens. If you remove the global validation and do the same, the custom validation works as expected.

Code snippet:

```tsx
import * as React from 'react';
import {
    Edit,
    FormTab,
    TabbedForm,
    ArrayInput,
    SimpleFormIterator,
    TextInput,
} from 'react-admin'; // eslint-disable-line import/no-unresolved

function validate(values: any) {
    const { nestedData } = values;
    const errors = {
        nestedData: [],
    };

    if (nestedData?.length) {
        nestedData.forEach((data, i) => {
            if (!data) return;

            const error: Record<string, unknown> = {};

            const { name } = data;

            if (!name) {
                error.name = ['no val'];
            }

            errors.nestedData[i] = error;
        });
    }

    console.log('in global validator');

    return errors;
}

function customValidator(val: string) {
    console.log('in input validator');
    if (!val) return 'is required';
}

const PostEdit = ({ permissions, ...props }) => (
    <Edit {...props}>
        <TabbedForm validate={validate}>
            <FormTab label="post.form.miscellaneous">
                <ArrayInput source="nestedData" label="data">
                    <SimpleFormIterator>
                        <TextInput source="name" label="Name" />

                        <TextInput
                            source="tag"
                            label="tag"
                            validate={customValidator}
                        />
                    </SimpleFormIterator>
                </ArrayInput>
            </FormTab>
        </TabbedForm>
    </Edit>
);

export default PostEdit;
```

And in the `simple/src/data.tsx` file don't forget to add the following data to post 13:

```
nestedData: [
                {
                    id: '1',
                    tag: 5,
                    name: 'hey there',
                },
                {
                    id: '2',
                    tag: 3,
                    name: 'helloo',
                },
            ],
```

## Video

https://user-images.githubusercontent.com/17087167/117823824-cca8fd00-b265-11eb-99b0-e42b70b37bb0.mov

**Comment by djhi** [comment]
Reproduced. Thanks!

**Comment by soullivaneuh** [comment]
I got the same behavior and I would like to add: This happen also when using the `resolver` option.

This deactivate any `validate` prop of the inputs.

**Comment by soullivaneuh** [comment]
I did get a deeper look, the validation looks to be managed directly by `react-hook-form`: https://github.com/marmelab/react-admin/blob/dabd1f53f7d0ce2a66cb07476a341e972de579d2/packages/ra-core/src/form/useAugmentedForm.ts#L52-L81

If am I right, on that case we may not be able to resolve the situation. According to the [docs](https://react-hook-form.com/api/useform/#validationResolver):

> A resolver cannot be used with the built-in validators (e.g.: required, min, etc.)

I also find theses changes by @fzaninotto in https://github.com/marmelab/react-admin/commit/32b680b490924dfe6a6ac0d5cf11e786496ea546 moving the per input validation calls back to the global validation on `examples/demo/src/visitors/VisitorCreate.tsx`.

It should indeed works, however, it makes the code much more verbose, don't you think?

If nothing can be changed here, I think a documentation update on the upgrade guide and the form validation section would be welcomed.

**Comment by andrico1234** [comment]
> I got the same behavior and I would like to add: This happen also when using the `resolver` option.
> 
> This deactivate any `validate` prop of the inputs.

Just a heads up that the behaviour I initially described was for RA v3. We've upgraded our codebase to use v4 now, which uses a different form library under the hood.

I'll be happy to close this issue and re-open if I notice this behaviour in v4

**Comment by soullivaneuh** [comment]
@andrico1234 My report is for the v4 version of react-admin. Here is a fresh issue with a reproduction sample: https://github.com/marmelab/react-admin/issues/7697
