### ISSUE TITLE
Inconsistent naming for useCreateSuggestion hook

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#6279]
In the example [here](https://github.com/marmelab/react-admin/blob/adbd4e0d7b959b73fc9a9d4c27bb64e7928d70b9/examples/simple/src/posts/TagReferenceInput.tsx#L8) the hook used is named `useCreateSuggestionContext`, in the docs [here](https://github.com/marmelab/react-admin/blob/master/examples/simple/src/posts/TagReferenceInput.tsx#L8) it's named `useCreateSuggestion`.

**Comment by djhi** [comment]
Good catch! Can you submit a PR to fix it?
