### ISSUE TITLE
DateField does not show the time in the correct timezone

### ISSUE THREAD

**Issue by angelotragno** [marmelab/react-admin#6280]
**What you were expecting:**
DateField should show the time based on the user's timezone

**What happened instead:**
My API returns the time in UTC and the DateField shows it as-is in UTC, regardless of the timezone where the user is. Even when I try to overwrite the timezone DateField still returns it in UTC, see "Steps to reproduce".

**Steps to reproduce:**
I tried to force the timezone in two ways:

`<DateField source="checkout_time" label="Date" showTime options={{ timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }}/>` 

and         

`<DateField source="checkout_time" label="Date" showTime options={{ timeZone: 'America/New_York' }}/>`

 but none of the two seems to work. DateField still shows the time in UTC.

**Other information:**

**Environment**

* React-admin version: 3.15.0
* React version: 17.0.2
* Browser: Firefox

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
No news for a month, closing.
