### ISSUE TITLE
React Native version

### ISSUE THREAD

**Issue by scheiblr** [marmelab/react-admin#6289]
Hey guys,

I really love your project and would like to thank you for publishing it!

The main part, that I think is so genious about RA apart from the many widgets, is the data provider abstraction. Thus, I wonder if you guys planned to build a RA version with react native support. I saw, that there are undertakings for UI frameworks like [nativebase](https://nativebase.io/) in the native field, but unfortunately without dataprovider etc ;)

Kind regards,
Raphael

**Comment by fzaninotto** [comment]
Hi, and thanks for your kind words. 

No, we have no plans for react native support. The apps we build with react-admin are mostly to address needs users have on desktop. 

But if you want to reuse the core logic (in ra-core) in another package  targeting react-native, feel free to do it: it's all MIT.
