### ISSUE TITLE
Partial pagination support (related to api-platform/admin)

### ISSUE THREAD

**Issue by jvmanji** [marmelab/react-admin#6300]
**Is your feature request related to a problem? Please describe.**

Hi! In api-platform/admin there is a support for partial pagination, it's very useful when we want to display `List` from a very big table where `count(*)` may take few minutes to be calculated. The problem is it stopped working. I've reported the problem here: https://github.com/api-platform/admin/issues/379. Partial pagination has been implemented by keeping information about it in `total`, where:
 - `total = -1` – partial pagination is enabled, and we're on the last page;
 - `total = -2` – partial pagination is enabled, and there is next page after current page;
 - `total = -3` – partial pagination is enabled, and we don't know whether there is next page.

This solution stopped working when react-admin in version 3.7.2 started to validate if `query.page > totalPages`.

**Describe the solution you'd like**

The simplest solution would be to allow `total < 0` in https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/useListController.ts#L189, but that seems a bit ugly.

**Describe alternatives you've considered**

An alternative would be to add some `meta` information to pagination. It'd allow us to implement partial pagination, but also other things, e.g. if we'd like to add some kind of `approxTotal`, and approximate total results instead of performing direct `count(*)` – I'm sure we'd like to distinguish `total` from `approxTotal` in the user interface.

**Additional context**
For more info, please check: https://github.com/api-platform/admin/issues/379.

**Comment by fzaninotto** [comment]
Implementing cursor-based pagination via a negative total is a hack that we don't support. 

The right way to implement cursor-based pagination is, indeed, supporting metas in the response. #4834 was a good step towards that goal, but the added complexity to all queries didn't seem worth the merge.

**Comment by yelworc** [comment]
For what it's worth, I'm also using a simple custom pagination component (basically just prev page/next page buttons) for an API that does not provide totals, and my similarly hacky solution broke in 3.7.2 as well (by [this change](https://github.com/marmelab/react-admin/commit/0774a434bfc3ae0fc435b843221110d34ab16660), specifically).

@jvmanji not sure if that helps in your case, but I just changed my hack to set `total` to something like `Number.MAX_SAFE_INTEGER - x` – it's not pretty but it seems to work for now…

It would be great to have proper support for data sources without totals in react-admin – just a gut feeling, but I'd guess the strict requirement for total counts excludes a substantial number of use cases.

**Comment by fzaninotto** [comment]
Fixed by #7120
