### ISSUE TITLE
TabbedShowLayoutProps should have the tabs prop marked as optional

### ISSUE THREAD

**Issue by Reggionick** [marmelab/react-admin#6303]
**What you were expecting:**
The `tabs` prop of the TabbedShowLayout component should be optional

**What happened instead:**
The `tabs` prop of the TabbedShowLayout is missing the `?` sign so it's required

**Related code:**
```
// TabbedShowLayout.tsx:158
export interface TabbedShowLayoutProps {
    basePath?: string;
    className?: string;
    classes?: ClassesOverride<typeof useStyles>;
    children: ReactNode;
    record?: Record;
    resource?: string;
    syncWithLocation?: boolean;
    tabs: ReactElement;
    value?: any;
    version?: number;
}
```

**Environment**

* React-admin version: 3.15.1

**Comment by djhi** [comment]
Thanks for the report. Would you mind opening a PR to fix it?
