### ISSUE TITLE
useInput/onChange not working in initial useEffect.

### ISSUE THREAD

**Issue by hereblur** [marmelab/react-admin#6308]
I'm trying to implement custom input using `useInput`.
The initial value of input come from other context. I try to use 'onChange' to update value of the input but it's not update value as expected.

However It's working if I delay a bit  using `setTimeout()`. 

**What you were expecting:**
`onChange` inside `useEffect` should update value of input.

**What happened instead:**
`onChange` inside `useEffect` not update value of input.

**Steps to reproduce:**
Implemented as example code

**Related code:**
https://codesandbox.io/s/currying-bash-4o68c?file=/src/RandomInput.tsx , try create new Post.

```
const {
    input: { onChange, name, value },
    meta: { touched, error }
  } = useInput({ ...props, source });

  useEffect(() => {

    onChange(Math.random() * 99999);
    // This should update value of input when render.
 
    console.log("ONCHANGE CALLED [useEffect]");
  }, []);
```

**Other information:**

**Environment**

* React-admin version: 3.15.1
* Last version that did not exhibit the issue (if applicable): I think 3.7 was working before I updated.
* React version: Any
* Browser: Any
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
We've fixed an issue about defaultValue in Edit views (#6272) in 3.15.2. Can you test it and report if it fixes your issue?

**Comment by fzaninotto** [comment]
No news for some time, closing.
