### ISSUE TITLE
Improve documentation container's width

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6313]
Documentation central container is visually too narrow, specially for props tables.
By adding `max-width: fit-content` to `main > .container` class inside `docs/css/style-v11.css` you can improve this.

Before:
![before](https://user-images.githubusercontent.com/8268610/119896002-d0e74280-bf14-11eb-8555-2a9737ec93c9.png)

After:
![after](https://user-images.githubusercontent.com/8268610/119896006-d17fd900-bf14-11eb-8073-9f86f8495b62.png)

**Comment by fzaninotto** [comment]
I agree with the problem, not with the solution. I think we should simply reduce the margin of the markdown content on medium-size screens.

**Comment by fzaninotto** [comment]
This has been fixed some time ago.
