### ISSUE TITLE
Proposal: Add `useEffect` natively to Fields for an `onLoad`-type result

### ISSUE THREAD

**Issue by dylanh724** [marmelab/react-admin#6316]
**Is your feature request related to a problem? Please describe.**
Fields are read-only: It makes sense that we would sometimes want to load data from other data. For example, we have `subtotal` and `discount` -> for inputs, no problem, we have `onChange` . For fields? We need some sort of `onLoad` mechanism. `useEffect` seems to be the closest thing to this. 

Another example besides `subtotal+discount={total}` is for middleware. PayPal is common: Let's say when you're creating a new Invoice, you want to "get" the next invoice # async. As the form loads, I'd shoot the paypal lib a call and ask for info to prefill.

**Describe the solution you'd like**
Add `useEffect` to come default with core Field components. Have the option to use it async for middleware.

**Describe alternatives you've considered**
Without this (currently), fields aren't very versatile - it would be faster just to hack `format` to do something on its first trigger than to make a new custom component for every onLoad you want to handle.

**Additional context**
We need something similar to `onLoad` without having to tediously create new Components each time - we shouldn't have to. We get `onBlur` by default but not the `onLoad` equivalent (`useEffect`)? It just makes sense ~

**Comment by fzaninotto** [comment]
Thanks for your suggestion.

It seems like you need to [write your own field component](https://marmelab.com/react-admin/Fields.html#writing-your-own-field-component), which is documented. 

React-admin's philosophy is: we provide components for some use cases. If they don't work in your case, replace them by your own components. We even provide the lower-level bricks to do so.

We prefer that to adding more options and tests and documentation, and forcing people to learn a framework while in reality, it's just React™.
