### ISSUE TITLE
AutocompleteInput optionText component complexity

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#6317]
**Is your feature request related to a problem? Please describe.**

For the first time I tried to pass a custom component to the `AutocompleteInput::optionText` prop in order to a fancy gravatar to the user list (because I can).

I can, but the `inputText` and `matchSuggestion` option are now required, growing a bit more the diff and the complexity:

```diff
     <AutocompleteInput
       fullWidth={fullWidth}
-      optionText="name"
+      optionText={(choice: UserRecord) => {
+        if (!choice.id) {
+          return undefined;
+        }
+
+        return <UserIdentityField record={choice} />;
+      }}
+      inputText={(choice: UserRecord) => choice.name}
+      matchSuggestion={(_: string, choice: UserRecord) => Boolean(choice.name)}
     />
```

I assume when `optionText` type is a string, it is somehow used for the internal needed for `inputText` and `matchSuggestion`.

However, in addition to be required, the value are not text anymore but callbacks.

Because of that, I can not take benefit anymore of the internal logic that currently fits my needs.
The only thing I want to change here is the rendering.

**Describe the solution you'd like**

I see two possibilities:

1. Exposing a required common `fieldName` (or another) prop that will be used for the internal `inputText` and `matchSuggestion`.
Then, `optionText` will be used only for rendering and will not impact the other props.

2. Similar to option 1 but with `optionText` main option keeping. However, a new `optionRender` option can be created to accept custom rendering function. 

However, I don't have enough knowledge about your logic structure to be sure about the propositions.

**Describe alternatives you've considered**

I see none at the moment.

**Additional context**

**Comment by fzaninotto** [comment]
Thanks for your proposition. 

The `<AutocompleteInput>` is indeed complex, but we don't want to change it further. It is likely that we'll replace it by [material-ui's `<Autocomplete>` component](https://material-ui.com/components/autocomplete/#autocomplete) (which is recent) in the next major version. 

You can already build your own AutocompleteInput for react-admin based on mui's component, and that's what we recommend if the current API doesn't fit your need.
