### ISSUE TITLE
Documentation Request "Refresh Button"

### ISSUE THREAD

**Issue by tjgragg** [marmelab/react-admin#6324]
Hello, I was recently looking into how to hide the "Refresh Button" from the AppBar because it doesn't do anything on my app (but shows up on every page). Was looking into the documentation around UserMenu and MenuItemLink, and saw there was a section for the RefreshButton, but zero information on it. Would be nice to know if it's possible to hide it or override it's functionality somehow, thanks!

https://marmelab.com/react-admin/Buttons.html#refreshbutton

**Comment by fzaninotto** [comment]
Thanks for pointing it out. We know we need to document all components, so I'm closing this issue (or there will be one issue per component!). 

If you feel like giving a hand on this, any Pr is welcome.
