### ISSUE TITLE
Exception if sort params not defined 

### ISSUE THREAD

**Issue by cb1986ster** [marmelab/react-admin#6335]
https://github.com/marmelab/react-admin/blob/14de16c541631d800fea3e0e5977e21872f34fd0/packages/ra-data-fakerest/src/index.ts#L50

If data provider is called and sort parameter is not defined exception will be throw in fake rest server. If adding this element would be conditional ( field, order not undefined ) then should be file.

**Comment by fzaninotto** [comment]
Why is it a bug? Can you explain your use case? And please follow the issue template.

**Comment by fzaninotto** [comment]
No news for some time, closing.
