### ISSUE TITLE
When switching from the list page to editing, an error crashes

### ISSUE THREAD

**Issue by Merkure** [marmelab/react-admin#6336]
After updating the version to the latest from version 3.12.1. In the project, when switching from the list page to editing, an error crashes. It does not appear immediately, but after about a second or two. As I understand it, after some re-rendering. The problem is most likely related to useInput in the custom component. 
![image](https://user-images.githubusercontent.com/5706663/121220790-60d6a600-c89e-11eb-9582-7047c661217b.png)

**Comment by fzaninotto** [comment]
Please follow the issue template.

**Comment by fzaninotto** [comment]
No news for some time, closing.
