### ISSUE TITLE
Sidebar content order shifts

### ISSUE THREAD

**Issue by benracine** [marmelab/react-admin#6344]
**What you were expecting:**
I expect the sidebar contents to always be rendered in the same order. The expected order is the order that the `<Resource>` components are provided in the `<Admin>` component.

**What happened instead:**
The order jumps around as one navigates through the resources.

**Comment by benracine** [comment]
`<Admin>` component specification is as shown below... 

<img width="545" alt="Screen Shot 2021-06-09 at 11 41 51 AM" src="https://user-images.githubusercontent.com/798971/121403086-cdda5200-c917-11eb-94ca-83a3a3ea4452.png">

<img width="371" alt="Screen Shot 2021-06-09 at 11 41 57 AM" src="https://user-images.githubusercontent.com/798971/121403088-cf0b7f00-c917-11eb-84d6-4370d854d7c5.png">

**Comment by fzaninotto** [comment]
Your video isn't public. 

Besides, as we don't reproduce this on the simple example, there must be something with your code, so please provide a link to a modified CodeSandbox that shows the problem. 

That, and your react-admin version. 

(we wrote an issue template to avoid posting that kind of comment, so please use it)

**Comment by benracine** [comment]
Closing... subscribers just needed a label in the options attribute, e.g.

```
      <Resource
        name="subscribers"
        options={{label: 'Subscribers'}}
        {...subscribers}
      />

```
