### ISSUE TITLE
Many of inputs don't support label={false}

### ISSUE THREAD

**Issue by mahdijirofti** [marmelab/react-admin#6352]
**What you were expecting:**
NumberInput, AutoCompleteInput and all inputs support label={false} same as TextInput to hide label

**What happened instead:**
NumberInput and many input cause error when label prop is false

**Steps to reproduce:**
Try <AutocompleteArrayInput label={false} />

* React-admin version: 3.14.3

**Comment by djhi** [comment]
Thanks for reporting this. Many of them (NumberInput for example) actually support it but are missing the proper types and PropTypes. We'll gladly accept PRs to fix that, one input at a time.

**Comment by VikrantShirvankar** [comment]
Hi..
I would like to work on this issue. This will be my first open source contribution.

**Comment by VikrantShirvankar** [comment]
Hello..
Raised PR for Number input label issue.
[PR](https://github.com/marmelab/react-admin/pull/6361)
Please let me know if any changes needed.

**Comment by fzaninotto** [comment]
Fixed by #6381
