### ISSUE TITLE
Feature Request: Resizable table columns

### ISSUE THREAD

**Issue by Dnouv** [marmelab/react-admin#6353]
Greetings,
The feature request is related to the issue of irregular row height in the table. In the image attached, the first row occupies three lines while the second row is four lines.
<img width="500" height="300" src="https://user-images.githubusercontent.com/61188295/121779210-35aec800-cbb8-11eb-87b2-8a7e19115d2d.png">

If possible, it would be nice to have single line rows with resizable columns with slide(drag) to resize as we have in excel, google sheets tables.

Here is a short video of how the feature request might look like,

https://user-images.githubusercontent.com/61188295/121779404-15cbd400-cbb9-11eb-8f53-b2ed392ceff8.mov

It might be added as an optional property feature, which could be enabled by setting it to `true`

Thank you!

**Comment by fzaninotto** [comment]
Hi,

Thanks for your suggestion, it's be a great addition indeed, but a lot of work to develop and maintain. 

I suggest you replace our Datagrid by standalone (and commercial) datagrids supporting column reordering, like [Material-ui's Datagrid](https://material-ui.com/components/data-grid/).

If you feel like developing this resizable columns support yourself and contributing it to the react-admin codebase, feel free to open a PR!

**Comment by Dnouv** [comment]
Thanks for your reply; I will give it a try, and if the try succeeds will open a PR.
