### ISSUE TITLE
Filter by reference as null or not null

### ISSUE THREAD

**Issue by oklas** [marmelab/react-admin#6358]
It would be good to have boolean filter for case where two associated resources are defined and association allowed to be null. This will reflect required/not-null database field spec.

One obvious way is using boolean reference input: 

```js
    <Filter {...props}>
      <ReferenceInput
        source="owner_id"
        reference="Owner"
        filterToQuery={value => ({filter: {owner_id_is_null: !!value}})}
      >
        <BooleanInput source="owner_id"/>
      </ReferenceInput>
    </Filter>
```

But argument of `filterToQuery` is empty string for any state of `<BooleanInput/>` (or `<NullableBooleanInput/>`).

Are you consider this as a good suggestion (or this is bug to fix)? Is pr is acceptable?

**Comment by fzaninotto** [comment]
Why do you need a ReferenceInput? You can already do it with:

```jsx
const PostFilter = props => (
    <Filter {...props}>
        <NullableBooleanInput source="owner_id_is_null" />
    </Filter>
);
```

**Comment by oklas** [comment]
Just quick trial gives no result. `ReferenceInput` is needed to be able to prepare query, because filter field is not same as data field `owner_id`. Actually `source` property need to be nested, something like `filter.owner_id_is_null`.

**Comment by fzaninotto** [comment]
No news for some time, closing.
