### ISSUE TITLE
add property to configure `maxResults` on exporter without custom actions

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#6359]
**Is your feature request related to a problem? Please describe.**

exporter is limited to 1000 records by default. There is a property `maxResults`, but that can only be used directly on the `ExportButton`. The documentation mentions this and recommends to use custom actions (https://marmelab.com/react-admin/List.html#actions), but this is incredibly verbose and may potentially break in future versions.

**Describe the solution you'd like**

`<List />` should take a property `exporterMaxResults` that gets passed to the default actions

**Describe alternatives you've considered**

a context based api for defining defaults would also be useful and could be done without breaking react-admin

**Additional context**

none

**Comment by fzaninotto** [comment]
Thanks for your suggestion. 

This is actually a design decision (see https://marmelab.com/react-admin/Architecture.html#component-composition). We avoid giving too much control to top components (like `<List>`) and let users use composition to tweak features. 

The problem of the verbosity of the ListActions customization is already identified in #6212, feel free to participate in the discussion there.
