### ISSUE TITLE
importing ShowActionProps forbids compilation

### ISSUE THREAD

**Issue by Cornul11** [marmelab/react-admin#6360]
**What you were expecting:**

After importing `ShowActionProps` I was expecting the code to compile just like before. 
**What happened instead:**

Instead, I get an error that asks me to install a type package.
```/home/dan/app/node_modules/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
TypeScript error in /home/dan/app/node_modules/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx(6,24):
Could not find a declaration file for module 'inflection'. '/home/dan/app/node_modules/inflection/lib/inflection.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/inflection` if it exists or add a new declaration (.d.ts) file containing `declare module 'inflection';`  TS7016

    4 | import ActionDelete from '@material-ui/icons/Delete';
    5 | import { fade } from '@material-ui/core/styles/colorManipulator';
  > 6 | import inflection from 'inflection';
      |                        ^
    7 | import { makeStyles } from '@material-ui/core/styles';
    8 | import {
    9 |     useTranslate,

```
After installing the said package, I get a seemingly unrelated error:
```
/home/dan/app/node_modules/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx
TypeScript error in /home/dan/app/node_modules/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx(64,30):
Object is possibly 'undefined'.  TS2532

    62 |             refresh();
    63 |             notify('ra.notification.deleted', 'info', {
  > 64 |                 smart_count: selectedIds.length,
       |                              ^
    65 |             });
    66 |             unselectAll(resource);
    67 |         },

```

**Steps to reproduce:**

Import `ShowActionProps` -> first bug appears
Install `@types/inflection` -> second bug appears

**Other information:**

The problem appears even if I don't use said `ShowActionProps` anywhere in the code. Only importing it creates this issue.

**Environment**

* Typescript version: 4.3.2
* React-admin version: 3.15.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.6
* Browser: Chrome 91
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I've tried to reproduce your issue in a CodeSandbox, without success: https://codesandbox.io/s/young-tdd-zgzbn?file=/src/App.tsx:27-104

Can you please tweak the sandbox until it reproduces the problem?

**Comment by Cornul11** [comment]
> I've tried to reproduce your issue in a CodeSandbox, without success: https://codesandbox.io/s/young-tdd-zgzbn?file=/src/App.tsx:27-104
> 
> Can you please tweak the sandbox until it reproduces the problem?

This is very weird, but I cannot seem to be able to reproduce the problem, not even on my local machine. I will go ahead and close the issue.
