### ISSUE TITLE
CustomField issue :   Line 19:37:  'props' is not defined  no-undef

### ISSUE THREAD

**Issue by neps-in** [marmelab/react-admin#6363]
**What you were expecting:**

Custom Field Not working  Line 19:37:  'props' is not defined  no-undef
**What happened instead:**

I am using the exact same code as below https://marmelab.com/react-admin/Fields.html
```
import * as React from "react";
import { List, Datagrid, TextField, useRecordContext } from 'react-admin';

const FullNameField = () => {
    const record = useRecordContext(props);

    return <span>{record.firstName} {record.lastName}</span>;
}

FullNameField.defaultProps = { label: 'Name' };

export const UserList = (props) => (
    <List {...props}>
        <Datagrid>
            <FullNameField source="lastName" />
        </Datagrid>
    </List>
);
```
**Steps to reproduce:**

**Related code:**

```
import * as React from "react";
import { List, Datagrid, TextField, useRecordContext } from 'react-admin';

const FullNameField = () => {
    const record = useRecordContext(props);

    return <span>{record.firstName} {record.lastName}</span>;
}

FullNameField.defaultProps = { label: 'Name' };

export const UserList = (props) => (
    <List {...props}>
        <Datagrid>
            <FullNameField source="lastName" />
        </Datagrid>
    </List>
);
```

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: latest
* Browser: chrome
* Stack trace (in case of a JS error): Line 19:37:  'props' is not defined  no-undef

**Comment by neps-in** [comment]
In the example following the line *The component will be:*  pass the props like this
```
const FullNameField = (props) => {
    const record = useRecordContext(props);

    return <span>{record.firstName} {record.lastName}</span>;
}
```

Very obvious though, if you can add to the doc that would be great. 

Btw, fantastic library react-admin, Coooooooool

**Comment by djhi** [comment]
Thanks for reporting this and the kind words. Would you mind opening a PR?

**Comment by neps-in** [comment]
PR ?

**Comment by neps-in** [comment]
pull request ? on the doc ?

**Comment by djhi** [comment]
Yes :)
