### ISSUE TITLE
Add posibility to hide Toolbar's `DeleteButton` when editing a record

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6366]
I need to hide `DeleteButton` from toolbar when editing a record, without overriding the entire `Toolbar`.

Possible solution:
Add a prop `hideDelete` to the `Toolbar` component, defaults to `false`, used only if there are no children.

So we can do something like `<SimpleForm toolbar={<Toolbar hideDelete />} />`

**Comment by djhi** [comment]
Thanks for suggestion. However and as stated in the documentation new Architecture page, we really don't want to introduce new props for each new use case.
