### ISSUE TITLE
Undefined ra-input suffix with FormDataConsumer

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#6370]
**What you were expecting:**

When an input is display from a `FormDataConsumer`, I expect to see an input raw with the correct css classes.

**What happened instead:**

Got a `ra-input ra-input-undefined` row class. 

**Steps to reproduce:**

See the sandbox link.

**Related code:**

```typescript
<FormDataConsumer>
    {({ formData, ...rest }) =>
    formData.commentable && (
        <TextInput source="foo" label="Foo" {...rest} />
    )
    }
</FormDataConsumer>
```

Sandebox: https://codesandbox.io/s/react-admin-data-consumer-class-undefined-vm6eg?file=/src/posts/PostCreate.tsx:2682-2902

Note: The goal is to make the input appear only if the `commentable` option (previous input) is activated.

This sample should produce a `ra-input-foo` class, not `ra-input-undefined`

**Other information:**

**Environment**

* React-admin version: 3.16.2
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
`<SimpleForm>` uses the `source` prop of its children to set the classname. If you want the right classname with a `<FormDataConsumer>`, just set the `source` on it:

```jsx
<FormDataConsumer source="foo">
    {({ formData, ...rest }) =>
    formData.commentable && (
        <TextInput source="foo" label="Foo" {...rest} />
    )
    }
</FormDataConsumer>
```

https://codesandbox.io/s/react-admin-data-consumer-class-undefined-forked-r5tsc?file=/src/posts/PostCreate.tsx:2682-2722
