### ISSUE TITLE
Multiple inputs bad rendering with FormDataConsumer

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#6371]
**What you were expecting:**

The two inputs are on the same `ra-input` row:

![image](https://user-images.githubusercontent.com/1698357/122656333-d7ef2280-d159-11eb-9614-dc63021a26b9.png)

**What happened instead:**

Two distinct rows should be created:

![image](https://user-images.githubusercontent.com/1698357/122656340-e2a9b780-d159-11eb-91f3-49156bc92ea1.png)

**Steps to reproduce:**

See related code and sandbox.

**Related code:**

```typescript
<FormDataConsumer>
  {({ formData, ...rest }) =>
    formData.commentable && (
      <>
        <TextInput source="foo" {...rest} />
        <TextInput source="bar" {...rest} />
      </>
    )
  }
</FormDataConsumer>
```

Sandbox: https://codesandbox.io/s/react-admin-data-consumer-class-multiple-inputs-9qwtf?file=/src/posts/PostCreate.tsx:2682-2980

**Other information:**

**Environment**

* React-admin version: 3.16.2
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I think you inverted the what you expected / What happened instead sections in your report.

So what you currently get is that the two inputs are in the same row:

![image](https://user-images.githubusercontent.com/1698357/122656333-d7ef2280-d159-11eb-9614-dc63021a26b9.png)

I don't think this is a bug. `<SimpleForm>` creates one row per child. The `<FormDataConsumer>` is seen as one child. 

If you need a form layout more specific than what `<SimpleForm>` offers, you should replace it with your own component.

**Comment by yoitsro** [comment]
@soullivaneuh I was facing a similar problem. I took a look at how `<SimpleForm>` [performs its layout](https://github.com/marmelab/react-admin/blob/c6c43bc1a766d762fc0791514a31f7e365e66fd0/packages/ra-ui-materialui/src/form/SimpleFormView.tsx#L36) and came up with the following. Place your inputs as children of this component:

```
import { Children } from "react";
import { FormInput } from "react-admin";

export const StandardFormLayout = ({
  basePath,
  record,
  resource,
  variant,
  margin,
  children,
}) => (
  <div>
    {Children.map(
      children,
      (input) =>
        input && (
          <FormInput
            basePath={basePath}
            input={input}
            record={record}
            resource={resource}
            variant={input.props.variant || variant}
            margin={input.props.margin || margin}
          />
        )
    )}
  </div>
);
```
