### ISSUE TITLE
[Doc] Aside component for Show view is injected as element

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#6372]
**What you were expecting:**

I expect the document to match the behavior of code. However, the code snippet in https://github.com/marmelab/react-admin/blob/43c4fafc8bcedebc386c7d3dc3b63cfd56420a17/docs/Show.md#aside-component throws error.

The actual implementation here https://github.com/marmelab/react-admin/blob/a170daefddd4259debc086c753c5c68752f0e0ff/packages/ra-ui-materialui/src/detail/ShowView.tsx#L105 requires an element.

The `<Show aside={Aside} {...props}>` should be `<Show aside={<Aside />} {...props}>` to make it work.

**Other information:**

Fixing the doc should be simple. But what I want to bring up is, it is not very consistent with https://github.com/marmelab/react-admin/issues/3246 and https://github.com/marmelab/react-admin/pull/3262 introduced for 3.0

What should we do? Change the code now, change the document, or wait and introduce another breaking change in 4.0 https://github.com/marmelab/react-admin/issues/5933 ?

**Environment**

* React-admin version: 3.16
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: Edge 90
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for pointing this out! Indeed, the doc must be fixed. 

FYI, we have reverted the #3262 in #3312. We still expect users to inject elements.
