### ISSUE TITLE
Console error from bulkactions

### ISSUE THREAD

**Issue by davidMfolkins** [marmelab/react-admin#6377]
**What you were expecting:**
Using a documented feature to not cause console errors

**What happened instead:**
Using the documented feature like mutationMode causes console error. 
https://marmelab.com/react-admin/List.html#bulkactionbuttons

I'm importing this and using it in multiple components, error exists on every component that has it.

**Steps to reproduce:**
1. Create example bulkaction from documentation
2. import into list as documentation details.
3. It works fine, but console error reads:
```
Warning: Failed prop type: Invalid prop `hasBulkActions` of type `array` supplied to `PureDatagridRow`, expected `boolean`.
```

**Related code:**

```
import { Fragment } from 'react'
import { BulkDeleteButton } from 'react-admin';

const AssetBulkActionButtons = props => (
  <Fragment>
    <BulkDeleteButton {...props} />
  </Fragment>
);

export { AssetBulkActionButtons }
```
Imported and used:

```
const AlgorithmList = props => (
  <List title={<Title />} pagination={<PagePagination />} actions={<ListActions />} perPage={25} {...props} filters={<AlgorithmFilter />} bulkActionButtons={<AssetBulkActionButtons />} sort={{ field: "id", order: "DESC" }}>
    <Datagrid style={{ tableLayout: 'fixed', wordWrap: "break-word" }} rowClick="edit">
      <TextField source="id" />
      <TextField source="description" />
      <TextField source="logged" />
    </Datagrid>
  </List>
);
```
**Other information:**

**Environment**

* React-admin version: ^3.14.2
* Last version that did not exhibit the issue (if applicable):
* React version:^17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
I can't reproduce this issue on the simple example. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by davidMfolkins** [comment]
Hey, yeah i recreated it in codesandbox and I don't see any console errors there. Would you know off the top of your head, any reason I may be encountering it? I've been searching for a solution for a couple days now.

**Comment by fzaninotto** [comment]
Sorry, we've never met this error before.

**Comment by davidMfolkins** [comment]
Alright, ill look more into this. Closing for now! thanks for the tips
