### ISSUE TITLE
Export button is not exporting all the data points to the CSV file

### ISSUE THREAD

**Issue by ShaswatZest** [marmelab/react-admin#6384]
**What you were expecting:**
There are 1000s of rows of data in the backend where we are trying to export the csv.

**What happened instead:**
But only the first 1000 rows are getting exported in the csv file.

**Environment**

* React-admin version: 3.8.3
* React version:16.13.1
* Browser: Google Chrome

**Comment by fzaninotto** [comment]
This is by design, to avoid limitless requests to the backend. Read the manual to understand how to lift this limit. 

https://marmelab.com/react-admin/List.html#exporter

**Comment by ShaswatZest** [comment]
Yeah it says to create csv in the server side and then export it but I am required to do it in the frontend

**Comment by fzaninotto** [comment]
It also says that you can pass a `maxResults` prop to the `<ExportButton>`, and that should let you change the limit.
