### ISSUE TITLE
Can not use ra-data-graphql-simple with React function components

### ISSUE THREAD

**Issue by Panzki** [marmelab/react-admin#6386]
**What you were expecting:**
We want to use the `ra-data-graphql-simple` package with React function components and hooks. (The documentation only contains an example with class components [here](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql-simple#usage).)

**What happened instead:**
When building the data provider from the `ra-data-graphql-simple` package in a function component the React application crashes. The error is: 
```
Unhandled Rejection (Error): Unknown resource undefined. Make sure it has been declared on your server side schema. Known resources are Post
```

**Steps to reproduce:**
1. Clone the repository containing a minimal example: `git clone git@github.com:Panzki/ra-simple-graphql-bug-report.git`
2. Install dependencies: `yarn`
3. Start the GraphQL server: `npx json-graphql-server db.js --p 4000`
4. Start the React application (in another terminal): `yarn start`
5. Open: http://localhost:3000

**Related code:**
The code snippet below uses the useEffect hook in a function component instead of `componentDidMount`. Here is GitHub repository containing a minimal example:  https://github.com/Panzki/ra-simple-graphql-bug-report
```jsx
import buildGraphQLProvider from "ra-data-graphql-simple";
import React from "react";
import { Admin, ListGuesser, Resource } from "react-admin";

function App() {
  const [dataProvider, setDataProvider] = React.useState<any | null>(null);

  React.useEffect(() => {
    buildGraphQLProvider({
      clientOptions: { uri: "http://localhost:4000" },
    }).then((provider) => setDataProvider(provider));
  }, []);

  if (!dataProvider) {
    return <div>Loading</div>;
  }
  return (
    <Admin dataProvider={dataProvider}>
      <Resource name="Post" list={ListGuesser} />
    </Admin>
  );
}

export default App;
```

**Other information:**

**Environment**

* React-admin version: 3.16.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: FireFox 89.0.1 (64-bit)
* Stack trace (in case of a JS error):
![image](https://user-images.githubusercontent.com/12871965/123110010-001da080-d43c-11eb-81e1-926b32cd0911.png)

**Comment by djhi** [comment]
That's most probably because your resource is named `posts` in your `db.js` file instead of `Post` (the resource name in `Resource`

**Comment by Panzki** [comment]
Hi,
thanks for getting back. However I'm afraid the problem is not a simple naming issue. Even if I change the name in `db.js` to `post` (or vice versa) I still get the same error. Therefore I'd like to ask you to reopen the issue.

**Comment by djhi** [comment]
It should be `Post` ( note the uppercase `P`)

**Comment by Panzki** [comment]
Thanks for your patience. Sadly it still doesn't work with the uppercase `P`.

**Comment by miladnikad** [comment]
Hello friends
I have a similar problem. Is it possible to help?

MongoDb collection name: 
`users`

setDataProvider
```
const provider = await buildGraphQLProvider({
      clientOptions: {uri: 'http://localhost:4000/graphql'},
});
setDataProvider(() => provider);
```

Admin
```
<Admin dataProvider={dataProvider}>
    <Resource name="users" list={ListGuesser} />
</Admin>

```


query

```
allUsers(
  page: Int
  perPage: Int
  sortField: String
  sortOrder: String
  filter: UserFilter
): [User]
```

Resolver
```
allUsers: (parent, args, context) => allUsers(args, context)
```

allUsers
```
const allUsers = async () => {
  const users = await User.find({});
  return users;
};
```

Error: 
**Unknown resource users. Make sure it has been declared on your server side schema. Known resources are**

**Comment by djhi** [comment]
@Panzki Thanks for the reproduction. There is indeed something wrong but I haven't found what it is yet.

**Comment by winner106** [comment]
@miladnikad 

<Admin dataProvider={dataProvider}>
    <Resource name="User" list={ListGuesser} />
</Admin>

**Comment by kav** [comment]
This also confuses the ListGuesser for referenced fields as it wants the Resource name for the ReferenceField to be lower cased and plural. For example using the `json-graphql-server`
`db.js`:
```js
module.exports = {
    posts: [
        { id: 1, title: "Lorem Ipsum", views: 254, user_id: 123 },
        { id: 2, title: "Sic Dolor amet", views: 65, user_id: 456 },
    ],
    users: [
        { id: 123, name: "John Doe" },
        { id: 456, name: "Jane Doe" }
    ]
}
```
run with `json-graphql-server graphql/db.js --p 4000`
`App.js`
```js
// in App.js
import * as React from 'react';
import { Component } from 'react';
import buildGraphQLProvider from 'ra-data-graphql-simple';
import { Admin, Resource, ListGuesser } from 'react-admin';

// import { PostCreate, PostEdit, PostList } from './posts';

class App extends Component {
    constructor() {
        super();
        this.state = { dataProvider: null };
    }
    componentDidMount() {
        buildGraphQLProvider({ clientOptions: { uri: 'http://localhost:4000' }})
            .then(dataProvider => this.setState({ dataProvider }));
    }

    render() {
        const { dataProvider } = this.state;

        if (!dataProvider) {
            return <div>Loading</div>;
        }

        return (
            <Admin dataProvider={dataProvider}>
                <Resource name="Post" list={ListGuesser} />
                <Resource name="User" />
            </Admin>
        );
    }
}

export default App;
```

Triggers `Error: You must declare a <Resource name="users"> in order to use a <ReferenceField reference="users">`

Also saw the same behavior described above using functional components, no amount of renaming or case swapping resolved the issue.

**Comment by kav** [comment]
Amusingly if you add a list guesser to User then it complains about a missing Resource for "Posts" so casing expectations are reversed there but the plural is still expected

**Comment by OoDeLally** [comment]
The issue is here:
```ts
setDataProvider(provider);
```
If a function is passed to the `useState`'s dispatcher, it will be called with the current value of the state, e.g.
```ts
const [value, setValue] = useState()
setValue(val => val + 2)
```

It turns out `provider` *is* a function, so it triggers this unwanted effect.

The solution is to *absorb* that effect by wrapping it into a function:
```ts
setDataProvider(() => provider);
```

**Comment by fzaninotto** [comment]
Thanks @OoDeLally! Indeed, this seems to be a user land issue, not a problem with react-admin.

**Comment by Panzki** [comment]
@OoDeLally Thanks for pointing this out. If one looks closely this can be found in the [React docs](https://reactjs.org/docs/hooks-reference.html#functional-updates) as well. 🤦

@fzaninotto Should I submit a PR to extend the documentation of the `ra-data-graphql-simple` package to include an example of a function component?

**Comment by djhi** [comment]
@Panzki Yes please :heart:
