### ISSUE TITLE
Support UI Provider

### ISSUE THREAD

**Issue by HongjiangHuang** [marmelab/react-admin#6391]
**Is your feature request related to a problem? Please describe.**
I wish I could provide ra-ui-ant-design to enable react-admin to support building ant-design projects

**Comment by djhi** [comment]
It's already possible. The `react-admin` package is just a distribution which binds the `ra-ui-materialui` package to the feature provided by `ra-core`.

**Comment by HongjiangHuang** [comment]
But I see that it seems to be written dead here ra-ui-materialui https://github.com/marmelab/react-admin/blob/master/packages/react-admin/src/AdminUI.tsx#L4  ？

I can't seem to achieve this with code like the following?

```react
    <Admin
        dataProvider={jsonServerProvider(
            'https://jsonplaceholder.typicode.com'
        )}
        authProvider={authProvider}
        uiProvider={antDesignProvider}
        dashboard={Dashboard}
    >
    </Admin>
```

**Comment by djhi** [comment]
There is no `uiProvider`. `ra-ui-materialui` is just a library of components which leverages the hooks and components from `ra-core`. To build a `ra-ui-antdesign`, you would have to do the same.
