### ISSUE TITLE
Cannot use `TextField` inside of an iterator within a form

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#6393]
**What you were expecting:**
If I wanted to display some static data from a record from within an Edit page, I should expect to use a `TextField` as normal to output the data.

**What happened instead:**
Code like this:
```
const PostEdit = props => {
    return (
        <Edit title={<PostTitle />} {...props}>
            <TabbedForm>
                <FormTab label="post.form.summary">
                    <ArrayInput source="backlinks">
                        <SimpleFormIterator>
                            <TextField source="url" />
                            <TextInput source="url" />
                        </SimpleFormIterator>
                    </ArrayInput>
                </FormTab>
            </TabbedForm>
        </Edit>
    );
};
```

Displays the following:
![image](https://user-images.githubusercontent.com/17087167/123411635-8eaf3080-d5a8-11eb-8f45-0940583f022a.png)

**Steps to reproduce:**
You can find the [repro case here](https://github.com/andrico1234/react-admin/tree/repro/iterator-field-in-edit)
Run the simple-demo and access [post 12](http://localhost:8080/#/posts/12)

**Related code:**
It looks like a problem with the TextField component itself.

The value returned from `useRecordContext` is

```
{ url: "https://blog.johndoe.com/2012/08/12/foobar.html }
```

Where the source passed through is: `backlinks[1].url`.

* React-admin version: 3.16.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Yes, the `SimpleFormIterator` should provide a RecordContext. Thanks for reporting

**Comment by WiXSL** [comment]
#6932 should solve this bug since it introduces a `RecordContext` into the `FormWithRedirect` component

**Comment by WiXSL** [comment]
My bad, haven't read the entire report, sure, this is a problem to solve

**Comment by andrico1234** [comment]
You're right!
