### ISSUE TITLE
AutocompleteInput cause material error when I want customize input style

### ISSUE THREAD

**Issue by mohandes-jiri** [marmelab/react-admin#6394]
I have a custom AutocompleteInput like this:

```
<AutocompleteInput
	{...props}
	variant="filled"
	options={{
		InputProps: {
			classes: {
				marginDense: classes.inputRoot,
				input: classes.input,
				underline: classes.inputUnderline,
				error: classes.inputError,
				ocused: classes.inputFocused,
			},
		},
	}}
/>
```
These classes delivered to the material **Input** component, not **TextField** and work fine.

But in console raising error like this:

![Screenshot from 2021-06-25 15-17-31](https://user-images.githubusercontent.com/22638025/123414018-9d0d4480-d5c8-11eb-8069-5b36eae3746f.png)

![Screenshot from 2021-06-25 15-17-42](https://user-images.githubusercontent.com/22638025/123414032-a1d1f880-d5c8-11eb-9f23-0a95d506d13b.png)

When I investigating for reason in react admin project code I found this line
https://github.com/marmelab/react-admin/blob/c6c43bc1a766d762fc0791514a31f7e365e66fd0/packages/ra-ui-materialui/src/input/AutocompleteInput.tsx#L484

That return classes field in `inputProps` then in this line you pass this props to `TextField` component

https://github.com/marmelab/react-admin/blob/c6c43bc1a766d762fc0791514a31f7e365e66fd0/packages/ra-ui-materialui/src/input/AutocompleteInput.tsx#L545

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by mahdijirofti** [comment]
@djhi 
Hi,
I provide a sample at this link

[https://codesandbox.io/s/frosty-tdd-plo2r?file=/src/comments/CommentCreate.tsx](url)

Please check the console in creating the comment form.
Each render of this page causes the errors I mentioned above.

**Comment by mahdijirofti** [comment]
@djhi 
Hi again!
Is my sample code OK?

**Comment by fzaninotto** [comment]
Indeed, we're passing the InputProps to two different components. Thanks for the reproduction, I'm marking this as a bug.

**Comment by mahdijirofti** [comment]
@fzaninotto 
You're right.
I think by sanitizing the InputProps to eject classes filed this issue should be solved easily.

**Comment by mahdijirofti** [comment]
@fzaninotto 
I test 3.17.1 and still has errors.
I opened PR.
Thank you.

**Comment by mahdijirofti** [comment]
@djhi @fzaninotto 
Hi, again guys,
I understand this definitely doesn't have priority for you, but the huge development error message heavily suffer us in the team.
