### ISSUE TITLE
Make TranslatableInputs responsive

### ISSUE THREAD

**Issue by CyanoFresh** [marmelab/react-admin#6396]
**What you were expecting:**

TranslatableInputs tabs should not exeed 100vw and fold the tabs

**What happened instead:**

TranslatableInputs tabs take more width which makes all the page not responsive
![image](https://user-images.githubusercontent.com/4249082/123562685-f9cf5180-d7b8-11eb-94e7-d4f52a1d244f.png)

**Steps to reproduce:**

1. go to
https://codesandbox.io/s/vibrant-wave-yneb7?file=/src/posts/PostEdit.tsx:2837-3052&resolutionWidth=320&resolutionHeight=675
2. Shrink browser to see tabs is not responsive

**Related code:**

Title field in PostEdit.tsx
https://codesandbox.io/s/vibrant-wave-yneb7?file=/src/posts/PostEdit.tsx:2837-3052&resolutionWidth=320&resolutionHeight=675

**Other information:**

header component of TranslatableInputs is not responsive

**Environment**

* React-admin version: 3.16.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Chrome last
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for reporting this. This is a nice to have for us, so we'll accept PRs that implement this feature. As we don't have an immediate need for it, the core team won't implement it, though. If you absolutely need this feature, consider hiring a contractor (or the core team) to implement it.

Also, if the community doesn't provide a PR for it within a few months, we'll close this issue during one of our monthly issues cleaning session.

**Comment by CyanoFresh** [comment]
Thanks for reply. Do you have any suggestions how to fix this bug? I'd like to make a PR but haven't found any fix for this

**Comment by fzaninotto** [comment]
No, you'll have to dig in the material-ui options for the tabs.

**Comment by CyanoFresh** [comment]
OK, found the problem. Removing `min-width` from `.RaLayout-root`:
![image](https://user-images.githubusercontent.com/4249082/123665008-8ec95d80-d840-11eb-85ec-9a23f5d27c3b.png)
and `dispay: flex` from `.RaLayout-contentWithSidebar`
![image](https://user-images.githubusercontent.com/4249082/123665121-a6084b00-d840-11eb-99cb-2099da982326.png)
fixes the problem. Overrided them in MyLayout and now everything is responsive.

Would you accept a PR removing specified properties?

**Comment by djhi** [comment]
Hi, some contributors tried this approach but it introduced other issues so no we won't accept a PR modifying those.

**Comment by fzaninotto** [comment]
This enhancement request hasn't gained enough interest to get a PR from the community. As we canot keep all feature requests open, I'm closing it.

If you feel like working on this feature, we'd love a PR!
