### ISSUE TITLE
Data in Reference Field didn`t appear

### ISSUE THREAD

**Issue by MC169** [marmelab/react-admin#6397]
Hello, 

i have used ReferenceField and ReferenceManyField several times in my project and they worked fine, but in part of my project the ReferenceField does not work properly.

the call is there and correct, but the data was not displayed.

In order to display the data, I should come into Edit view and then back in List view to display the data.

**code:**

```
export const DepartmentList = (props) => {
        const translateHook = useTranslate()
        return (
            <List {...props} filters={<DepartmentFilter/>} actions={<ListActions/>}
                  bulkActionButtons={<AssetBulkActionButtons/>}>
                <Datagrid rowClick='expand'
                          expand={< StudyAreaShow translateHook={translateHook} id_department={props.id}/>}>
                    <TextField source="id"/>
                    <TextField source="name"/>
                    <ReferenceField label='pos.conduction' source="id_conduction"
                                    reference="persons" sortable={false}>
                        <ChipField className='fullnameChip' source="fullname"/>
                    </ReferenceField>
                    <ReferenceField label='resources.departments.fields.id_deputy' source="id_deputy"
                                    reference="persons" sortable={false}>
                        <ChipField className='fullnameChip' source="fullname"/>
                    </ReferenceField>
                    <EditButton/>
                </Datagrid>
            </List>
        )
    }
;
```
![2021-06-28 14-20-58](https://user-images.githubusercontent.com/60115987/123638122-1605d980-d81f-11eb-9ce3-ae657ba25e0c.gif)

**Environment**

* React-admin version: 3.16.2
* React version: 17.0.2
* Browser: Chrome, Firefox

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by tauqeer-trailfive** [comment]
I just git the same error is some fixed that. @MC169 @djhi . my reference fields in List Component which i user to clickable to go to that specfic referenced record.

**Comment by tauqeer-trailfive** [comment]
Above sandbox is showing or reproducing the same error I'm getting @djhi

**Comment by fzaninotto** [comment]
@tauqeer-trailfive PLease open a new issue and follow the issue template.
