### ISSUE TITLE
Phone number is parsed as date in listguesser

### ISSUE THREAD

**Issue by niekbruins** [marmelab/react-admin#6402]
**What you were expecting:**
Expected that a phone number, like 06 - 123 456 78, is not parsed as a date in the listguesser

**What happened instead:**
Phone number is parsed as a date and in the listguesser shown as InValid date

**Steps to reproduce:**
Ad a column with only phone numbers in the format xx - yyy yyy yy and it is parsed as an inValid date in the listguesser

**Related code:**
ra-core/src/inference/assertions.ts
```
export const isDateString = (value: any) =>
    !value || (typeof value === 'string' && isValid(parseDate(value)));
export const valuesAreDateString = (values: any[]) =>
    values.every(isDateString);
```
This can be fixed in the assertionss.ts by changed the above to:
```
export const isDateString = (value: any) =>
  !value || (typeof value === 'string' && isValid(parseISO(value)));
export const valuesAreDateString = (values: any[]) =>
  values.every(isDateString);
```
Downside, It is nessesary to update date-fns to version 2

**Other information:**

**Environment**

* React-admin version: 3.14.1
* Last version that did not exhibit the issue (if applicable): ?
* React version: 17.0.2
* Browser: chrome/firefox/opera, latests versions
* Stack trace (in case of a JS error): -

**Comment by fzaninotto** [comment]
thanks for the bug report. 

The fix you suggest is a breaking change, so we won't do it until version 4.0.

Besides, the ListGuesser is designed to be a first approach - there are many cases (like this one) when it falls short. Making it perfect isn't an objective.

I believe we can live with some phone numbers parsed as dates. 

So I'll close this one as a "won't fix".
