### ISSUE TITLE
alwaysOn is not allowed on <Button> in <Filter>

### ISSUE THREAD

**Issue by ad-si** [marmelab/react-admin#6409]
**What you were expecting:**

`<Button>` components in a `<Filter>` need the `alwaysOn` property to be displayed per default

**What happened instead:**

I'm getting an error `Property 'alwaysOn' does not exist on type …`

**Steps to reproduce:**

1. Create a list with a custom `filters={<CustomFilter />}`
2. The `CustomFilter` then needs to include a <Button alwaysOn>Test Button</Button>` component
3. Compile with TypeScript

**Other information:**

Other input components (e.g. Date, Select, …) might be affected as well.

**Environment**

* React-admin version: 3.16.4

**Comment by fzaninotto** [comment]
`<Filter>` only accepts Input component as children. If you want to use a Button, you'll have to wrap it with a span for instance.
