### ISSUE TITLE
How to run the Demo project independently from everything else

### ISSUE THREAD

**Issue by hichemfantar** [marmelab/react-admin#6411]
I tried running npm install inside the Demo project folder and I keep getting a bunch of typescript errors and unresolved packages like the classnames package.
However when i installed using the steps provided in the readme, everything worked.
However I don't understand why when I run npm install inside the Demo folder, not everything is installed.
It seems that when I do that, some packages that the Demo project needs are only installed when i run yarn install in the root react-admin folder.
Right now, It seems i need to install everything inside the root folder of react-admin and then run make commands to build the Demo project.
Isn't there a way to just include everything the demo needs in the package.json of the Demo folder and then simply install it from there.
Currently it seems too many unnecessary steps are required to run the Demo project.
One of the errors I get when installing from the Demo folder package.json
"Could not find a declaration file for module 'classnames'."

**Comment by fzaninotto** [comment]
No, there is no simpler way. The demo is intended to be used as a development tool.

If you want to write a project off of the demo and don't know how to do it, we recommend that you find a contractor with experience with react and react-admin.
