### ISSUE TITLE
Input label ignored inside TranslatableInputs

### ISSUE THREAD

**Issue by mjomble** [marmelab/react-admin#6414]
**What you were expecting:**
Custom label text (via the `label` prop) should appear on an input inside TranslatableInputs

**What happened instead:**
The default label text (derived from the name of the field) appeared instead, with seemingly no way to override it.

**Steps to reproduce:**
Open the edit view of any tag (or navigate to `/#/tags/1`).
Look at the label on the name field.

**Related code:**
https://codesandbox.io/s/eloquent-fermi-jjxte?file=/src/tags/TagEdit.tsx

**Other information:**
[This line](https://github.com/marmelab/react-admin/blob/45921e2d3b479648598535c90b2e970722da593d/packages/ra-ui-materialui/src/input/TranslatableInputsTabContent.tsx#L57) overwrites `child.props.label`

**Environment**

* React-admin version: 3.16.4
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Chrome 91
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Good catch! Thanks for reporting it. Can you make a PR to fix it too?

**Comment by mjomble** [comment]
I can try making a PR.
