### ISSUE TITLE
CSS API for SelectInput doesn't match TypeScript types

### ISSUE THREAD

**Issue by nathan-britten** [marmelab/react-admin#6423]
**What you were expecting:**
The CSS API should take a rule name of input as described here https://marmelab.com/react-admin/Inputs.html#selectinput

**What happened instead:**
However, when we use input we get the type error below:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/53157349/124947406-b5895000-e007-11eb-8151-2df209220b5a.png">

**Steps to reproduce:**
Add a SelectInput
Add a classes propswith an object with a propert name of input

**Related code:**
<img width="442" alt="image" src="https://user-images.githubusercontent.com/53157349/124947974-347e8880-e008-11eb-83a8-eaab2e50d44d.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/53157349/124947823-157ff680-e008-11eb-8007-5b5d421db146.png">

**Other information:**
I will be opening a PR for this issue. 

**Environment**

* React-admin version: 3.16.2
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Firefox 89.0.2
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for the report!

**Comment by fzaninotto** [comment]
I believe @djhi closed the issue by mistake

**Comment by fzaninotto** [comment]
Now the fix has been merged to master, it can be closed!
