### ISSUE TITLE
Allow custom Redux enhancers

### ISSUE THREAD

**Issue by melvinkcx** [marmelab/react-admin#6431]
**Is your feature request related to a problem? Please describe.**
I'm trying to add [Redux Integration of Sentry](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/redux/) to one of our react-admin projects. However, looking at the source code in `createAdminStore.ts`, it seems like there is no way to pass a custom Redux enhancer. 

**Describe the solution you'd like**
It would be much appreciated if we could pass an array of custom enhancers. Eg:
```
const store = createStore(
        resettableAppReducer,
        typeof initialState === 'function' ? initialState() : initialState,
        composeEnhancers(
            applyMiddleware(sagaMiddleware, routerMiddleware(history)),
            ...customEnhancers   // Added this line
        )
    );
```

**Describe alternatives you've considered**
Nothing else has come to my mind yet. Do share if you have a better solution to this :pray: 

**Additional context**
-

**Comment by djhi** [comment]
You can follow the instructions here: https://marmelab.com/react-admin/CustomApp.html

**Comment by melvinkcx** [comment]
thanks!
