### ISSUE TITLE
[Lab] no-code example cannot start in codesandbox

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#6432]
Hi, It was nice there are new packages to make a try. 🚀

However when I run the no-code example in codesandbox, it is always showing a white screen.
I am not sure if there are some config files not set up correctly

**What you were expecting:**

The demo should run successfully

**What happened instead:**

The demo cannot start

**Steps to reproduce:**

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/no-code

**Related code:**

**Environment**

* React-admin version: 3.17
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 17.0.2
* Browser: Edge 91
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for the report! Can you open a PR to fix it too?
