### ISSUE TITLE
AutocompleteInput does not support inputRef properly

### ISSUE THREAD

**Issue by shamim2883** [marmelab/react-admin#6434]
**What you were expecting:**
Passing inputRef should not change autocomplete suggestion container location

**What happened instead:**
When we pass `inputRef` to `AutocompleteInput` props, it does not set. If we set in `options` then it sets but suggestions are not shown bellow input field anymore, It shows in browser top left corner.

**Steps to reproduce:**
In a form add following code to pass `AutocompleteInput` props (add `const fieldRef2 = useRef(null);` first)
```
<ReferenceInput label="Test2" source="post_id" reference="posts">
          <AutocompleteInput
            options={{
              InputProps: {
                inputRef: fieldRef2
              }
            }}
            optionText="title"
          />
</ReferenceInput>
```
It will show suggestion box at very top left corner of the browser.

**Related code:**
https://codesandbox.io/s/mystifying-lamarr-f0hlt?file=/src/comments/CommentCreate.tsx

**Other information:**

**Environment**

* React-admin version: 3.17.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Indeed, we should merge the `inputRef` you provide with the `inputRef` we already have to avoid this. Thanks for the report!
