### ISSUE TITLE
Change <List> component prop to PropTypes.element 

### ISSUE THREAD

**Issue by datoslabs** [marmelab/react-admin#6439]
Hi,

I am trying to implement a collapsable `<Aside>` panel via action buttons in a `List` view; the view tracks the `<Aside>` panel's open/close state and updates the `<List>` main content's CSS to shrink/expand with transition effects.  Since the `<List>`  component prop expects a component type instead of an element, I am forced to use React Context to share the `<Aside>` panel's open/close state with the custom component.  I could define the custom component (functional) inside my view component; however, doing so will cause the custom component to re-render each time the view updates and thus unable to make the CSS transition effect work properly not to mention taking a performance hit. 

If the `<List>`  component prop accepts an element type, I would be able to reference `<Aside>` panel's open/close state without the use of React Context as follows:

```
const MyView = (props) => {
  const [showAside, setShowAside] = React.useState(false);
  ...
  return (
    <List
      {...props}
      component={<MyCustomComponent style={showAside ? narrowWidth : fullWidth} />}
      ...
    >
      ...
    </List>
  );
}
```
Alternatively, `List` can expose an additional `componentStyle` prop to be applied to the custom component during rendering.

**Comment by djhi** [comment]
This is the case. `List` accepts an element

**Comment by datoslabs** [comment]
According to `ListProps`, component property accepts `ElementType`, not `ReactElement`; therefore `component={<MyCustomComponent style={showAside ? narrowWidth : fullWidth} />}` will throw an error.

**Comment by djhi** [comment]
That's not what I see: https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/types.ts#L17

**Comment by datoslabs** [comment]
I am referring to the `component` property which would be: https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/types.ts#L21

**Comment by datoslabs** [comment]
@djhi, any thoughts?
