### ISSUE TITLE
SearchInput placeholder is hidden

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#6450]
**What you were expecting:**
Expected to see a text placeholder in SearchInput

**What happened instead:**
SearchInput placeholder is hidden

**Steps to reproduce:**
1) update to version 3.17.0

* codesandbox https://codesandbox.io/s/thirsty-wind-3k3q6

* React-admin version: 3.17.0
* Last version that did not exhibit the issue (if applicable): 3.16.6

**Comment by djhi** [comment]
It is hidden until focused which is the default behavior in Material-UI. You should be able to customize it yourself using the props and options.

**Comment by wmwart** [comment]
It sounds strange and this is the first time I've seen it. There is no such behavior on Material-UI [https://material-ui.com/ru/components/text-fields/](https://material-ui.com/ru/components/text-fields/) by default.

[https://codesandbox.io/s/material-demo-forked-3x88q?file=/demo.js](https://codesandbox.io/s/material-demo-forked-3x88q?file=/demo.js)

In the api description for placeholder: _The short hint displayed in the input before the user enters a value._

So your answer contradicts the description.

Could you please point out the relevant clause in the Material-UI documentation?
