### ISSUE TITLE
Fork of "simple" Codesandbox project immediately shows an error

### ISSUE THREAD

**Issue by yelworc** [marmelab/react-admin#6453]
This is kind of meta… I was gonna try to reproduce an actual RA problem on codesandbox, but after forking the [simple](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) project, it immediately spits out an error:

![2021-07-20 19 07 01 codesandbox io b2d339014a20](https://user-images.githubusercontent.com/454308/126366255-ebfda58d-1586-4662-ac96-91d64e82dc4c.png)

**What you were expecting:**

The demo project to work after forking it 😄

**What happened instead:**

See screenshot above. I tried it twice, same result. Here's the fork: https://codesandbox.io/s/divine-waterfall-ks9df
Maybe I'm being an idiot and missing something obvious?

**Comment by fzaninotto** [comment]
I can't replicate the problem on this CodeSandbox just forked from the simple example: https://codesandbox.io/s/eager-jepsen-0j89d

I believe it was a CodeSandbox glitch. Could you try again?

**Comment by yelworc** [comment]
Thanks for looking into it! I am still getting the error when forking the project in my everyday browser, but in an incognito window in Chromium it works fine. Apparently the problem is on my end (not really eager to dig into it any further though), and I have a working sandbox now → closing this. Sorry about the bogus report!
