### ISSUE TITLE
Admin component use defaultPath prop to redirect after user enter to panel

### ISSUE THREAD

**Issue by mahdijirofti** [marmelab/react-admin#6460]
**Is your feature request related to a problem? Please describe.**
Now Admin component uses the first resource name as the default path.
When I write the Admin children code for 2 or more access levels of users to manage the default path makes code dirty.
**Describe the solution you'd like**
Provide an optional prop for Admin component like "defaultPath".

```
defaultPath as string:

<Admin defaultPath="/user">...</Admin>

defaultPath as function:

<Admin 
  defaultPath={
    (permission) => permission.role === 'userLevel' ? '/user' : '/products'
  }
>
...
</Admin>

```

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

We won't implement that feature as you can already do it by providing a custom `dashboard` component which uses the `<Redirect>` component to redirect to the right resource list depending on your business logic. 

Cheers!
