### ISSUE TITLE
Using "outlined" variant break Input border

### ISSUE THREAD

**Issue by deluan** [marmelab/react-admin#6468]
**What you were expecting:**
Up until version 3.15, using the "outlined" variant in Input fields worked as expected.

**What happened instead:**
After upgrading to 3.17, if I click on an Input that has `variant='outlined'`, it cuts the border above the first character of the field.

**Steps to reproduce:**
Just click the field and you can see the border changing:

https://user-images.githubusercontent.com/331353/127083307-2a557c5f-3a59-46ee-9290-1873d4bcba8f.mov

**Related code:**
Just add the "outlined" variant, PostList.js:44
```jsx
const postFilter = [
  <SearchInput source="q" alwaysOn variant="outlined" />, 
  <TextInput source="title" defaultValue="Qui tempore rerum et voluptates" />,
  <QuickFilter
    label="resources.posts.fields.commentable"
    source="commentable"
    defaultValue
  />
];
```
Code Sandbox: https://codesandbox.io/s/gracious-frog-eknfj?file=/src/posts/PostList.tsx:1093-1362

**Environment**

* React-admin version: 3.17.0 (but was able to reproduce locally with 3.16.5)
* Last version that did not exhibit the issue (if applicable): 3.15 didn't have this bug
* React version: 17
* Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by djhi** [comment]
Thanks for reporting. It looks like we'll have to build an input using lower levels components from MUI for the SearchInput.

**Comment by Augani** [comment]
Hello @djhi , Can i take this?

**Comment by fzaninotto** [comment]
@Augani #6470 already proposes a solution for this issue

**Comment by Augani** [comment]
@fzaninotto ohok,seen

**Comment by fzaninotto** [comment]
This issue is a regression created by #6381. The right fix is to rollback the code that causes the problem. I'll handle it.

**Comment by richardgarnier** [comment]
I'm still seeing this issue on 4.4. Did it break again?

**Comment by niccmac** [comment]
This also happens in the Time Input

**Comment by fzaninotto** [comment]
Could you please open a new issue with a reproduction?
