### ISSUE TITLE
Make build error 

### ISSUE THREAD

**Issue by biel-jony** [marmelab/react-admin#6471]
When I run the make build & make run-demo, I got the following errors.

![image](https://user-images.githubusercontent.com/75117639/127319900-e3a684f4-5976-45bf-847a-81d0bf9feea3.png)

**Comment by fzaninotto** [comment]
I can't reproduce the error. You probably have a different version of typescript than the one we use in react-admin. Please use the `make install` command to use the package versions from yarn.lock.

**Comment by biel-jony** [comment]
Thanks , I  will try it. But it has been stuck at 2755 when i used `yarn install` command.  After I deleted yarn.lock file , It i worked normally. So should I wait a little longer after` make install`?
![image](https://user-images.githubusercontent.com/75117639/127417267-bd6a70cb-b50a-42cd-bba2-cd1be802f078.png)

**Comment by biel-jony** [comment]
Thank you, wait a long time and it worked. But I got a new error when used `make build`. 

![image](https://user-images.githubusercontent.com/75117639/127422617-53d66d81-1eb5-43dd-a0bc-9100993d3112.png)

System: Win10

**Comment by fzaninotto** [comment]
The react-admin Github repository isn't designed to support Windows. The individual npm packages can be used on Windows for your own projects, but if you want to *contribute* to react-admin, you'll need a Linux/BSD system (e.g. WSL2 on Windows).
