### ISSUE TITLE
Warning for unsaved changes within Edit form

### ISSUE THREAD

**Issue by nathan-britten** [marmelab/react-admin#6477]
**What you were expecting:**
I was expecting the EditForm to save. 

**What happened instead:**
Instead I was presented with the notification: Some of your changes weren't saved. Are you sure you want to ignore them?

**Steps to reproduce:**
I have modified the data to reflect the issuee I was having locally.

1. Navigate to posts
2. Select post with ID 12
3. Remove the second resource.posts.fields.date from either backlinks 1 or 2
4. Notification is displayed
5. Then remove another item and save, it times out

https://drive.google.com/file/d/1dmaYhIxFagOXIsYQafBWxJiJsrpm6ysF/view

**Related code:**

Code can be found here: https://github.com/nathan-britten/react-admin/tree/nested-ArrayInput-save-issue

I stripped down the PostEdit file and chaned the data.tsx file to match how I would be using it locally

**Other information:**

I think the issue is arising from nested Array Inputs but not entirely sure. 

I currently have nested ArrayInputs inside a tabbed form. 

**Environment**

* React-admin version: 3.17.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Firefox 90.0.2
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
As you just changed the simple example, please fork the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) instead of providing a repository. It's way simpler for us to use.

**Comment by nathan-britten** [comment]
Hi @djhi,

You can find the forker CodeSandbox here: https://codesandbox.io/s/focused-einstein-tw1c1?file=/src/posts/PostEdit.tsx

Please Open in a New Window using the button the right. As the issue doesn't show when you run it in the codesandbox window

![image](https://user-images.githubusercontent.com/53157349/127646810-d562f531-619f-4bc9-a50a-039003d211a6.png)

**Comment by nathan-britten** [comment]
Hey @djhi, were you able to access my codesandbox? Wasn't sure if the sharing permissions were correct.

**Comment by andrico1234** [comment]
I've done a little digging and saw that the issues we're having are related to this particular merge: Fix form default values [#6272](https://github.com/marmelab/react-admin/pull/6272/commits/3fb979036a543f5369c4491b666e4550e18be22a?file-filters%5B%5D=.ts)

(for context Nathan and I are both on the same team)

Specifically the changes made to the file: packages/ra-core/src/form/useInitializeFormWithRecord.ts.

I tried corroborate this by seeing if going back to 3.15.1 in the RA repo prevents the issue present in Nathan's codesandbox, but it didn't, which is leading me to believe that they're two different problems entirely.

I wasn't able to recreate the problem in the simple example, but making changes in our node_modules shows that this line of code:

```
        if (isEqual(form.getState().initialValues, initialValues)) {
            return;
        }
```

is what's breaking things. If i remove it, everything works as expected. I'm going to call the above condition the _naughty_cond_.

In our repo:

with naughty-cond present:
https://user-images.githubusercontent.com/17087167/128411612-87114c8d-1ef4-47ab-a1be-38c45dffc8f2.mov



with naughty-cond removed:
https://user-images.githubusercontent.com/17087167/128411247-57b2e4e6-7eed-43b0-ab8d-3dfc8e82e07d.mov




@djhi , i can't quite work out why breaking early in `useInitializeFormWithRecord` is causing this problem. Do you have any thoughts?

**Comment by andrico1234** [comment]
Cool! so the problem was the fact that in our `updateOne` mutation, we were returning early on a very certain condition. When we returned early, we weren't sending the full record, just a partial record. This caused RA to think our data was out of sync

It was on our side! and it's not an issue with RA

**Comment by andrico1234** [comment]
One thing we might want to consider is whether we want to display the alert if the end user is triggering a `refresh` in the `onSuccess` mutation? We've done this in the past to ensure that we have up-to-date data displayed in the view. It's possible that a mutation isn't able to provide a record that's fully, and that could potentially lead to this discrepency

what do you all think?

**Comment by djhi** [comment]
Thank you both for the details and the sandbox. 

> One thing we might want to consider is whether we want to display the alert if the end user is triggering a refresh in the mutation's onSuccess callback? 

I think this is a user-land concern but maybe we should document the fact that a full record is expected
