### ISSUE TITLE
ReferenceInput + AutocompleteInput

### ISSUE THREAD

**Issue by VSymonenko** [marmelab/react-admin#6478]
**What you were expecting:**

Use **_ReferenceInput_** includes **_Autocompletenput_**. [Documentation](https://marmelab.com/react-admin/Inputs.html#referenceinput)

**What happened instead:**

Has error when change value once or once again

**Steps to reproduce:**

1. Go to page https://ig2c4.sse.codesandbox.io/#/comments/create
2. Click on the input element
3. Choose the first value "Fusce massa lorem, pulvinar a posuere ut, accumsan ac nisi"
4. Click on any other element
5. See an error: "Associated reference no longer appears to be available"

**Related code:**

```
import * as React from "react";

import {
  Create,
  SimpleForm,
  ReferenceInput,
  AutocompleteInput
} from "react-admin";

const CommentCreate = (props) => {
  return (
    <Create {...props}>
      <SimpleForm redirect={false}>
        <ReferenceInput reference="posts" source="post_id">
          <AutocompleteInput
            resettable
            optionText="title"
            // can't change value many times whith optionValue when user use keyboard
            // has an error when the value set once again
            optionValue="originId"
          />
        </ReferenceInput>
      </SimpleForm>
    </Create>
  );
};

export default CommentCreate;
```
[codesandbox](https://codesandbox.io/s/react-admin-ig2c4?file=/src/comments/CommentCreate.tsx)

**Environment**

* React-admin version: 3.17.0
* React version: ^17.0.0
* Browser: Chrome Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by djhi** [comment]
Yes, although we support custom `optionValue` in all the selection inputs such as `AutocompleteInput`, it doesn't work within references which requires `id`. See https://github.com/marmelab/react-admin/issues/2022#issuecomment-406206759
