### ISSUE TITLE
3.17.1 compile error

### ISSUE THREAD

**Issue by mahdijirofti** [marmelab/react-admin#6483]
**What happened instead:**

./node_modules/ra-input-rich-text/esm/index.js
Attempted import error: 'InputHelperText' is not exported from 'ra-ui-materialui'.
 
**Environment**

* React-admin version: 3.17.1
* Last version that did not exhibit the issue (if applicable):3.17.0
* ra-input-rich-text version:3.17.0
* React version:17.0.2

**Comment by fzaninotto** [comment]
You probably need to upgrade `ra-ui-material-ui` to 3.17.1, too. If you did, could you check in your yarn.lock (or packages-lock.json) that you don't have 2 versions of ra-ui-material-ui?

And if you manage to make sure this is a react-admin bug, please provide a reproducible test case using CodeSandbox, as explained in the issue template.

**Comment by mahdijirofti** [comment]
Yes, you're right.
I have duplicate `ra-ui-maretialui` in `yarn.lock` for a reason that I don't know.
I remove any other versions except 3.17.1 by hand and then it works fine.

**Comment by fzaninotto** [comment]
Fine, so I'm closing this issue then.
