### ISSUE TITLE
Material-UI: The `fade` color utility was renamed to `alpha`

### ISSUE THREAD

**Issue by CyanoFresh** [marmelab/react-admin#6490]
**What happened instead:**

I get this deprecation message after upgrading material ui to 4.12.3 package:
![image](https://user-images.githubusercontent.com/4249082/128524255-6779723a-ed55-4e3a-813a-ad2fb6d37cf5.png)

**Related code:**

**Other information:**

**Environment**

* React-admin version: 3.17.1
* React version: 16

**Comment by fzaninotto** [comment]
Note that this warning only occurs in development. The warning tells that that this feature will be removed in MUI 5.0. Version 5.0 has many breaking changes and is only in beta, and we don't intend to support before react-admin 4.x. In other words, we don't intend to care about MUI 5.x in react-admin 3.x

If they put a deprecation warning for all breaking changes in 4.x, it'll be hell to fix on our side. 

As the peerDependency on material-ui is `"^4.11.2"`, fixing this warning this implies that we bump the minimal mui version in our next minor (3.18)

**Comment by fzaninotto** [comment]
I'll move the discussion to #6451, as there are more warnings than this one.
