### ISSUE TITLE
Fetch blob 

### ISSUE THREAD

**Issue by RP-manuelurbano** [marmelab/react-admin#6491]
**Is your feature request related to a problem? Please describe.**
The feature request isn't related to a problem. I want to add new method fetchUtils.fetchBlob(url, options)

**Describe the solution you'd like**
I only found a fetchUtils.fetchJson() method, and I want to return a BLOB from the response.

**Describe alternatives you've considered**
I can create a PR with the following code snippet in order to add the functionality needed:
```
export const fetchBlob = (url, options: Options = {}) => {
    const requestHeaders = createHeadersFromOptions(options);

    return fetch(url, { ...options, headers: requestHeaders })
        .then(response =>
            response.blob().then((blob) => ({
                status: response.status,
                statusText: response.statusText,
                headers: response.headers,
                body: blob,
            }))
        )
        .then(({ status, statusText, headers, body }) => {
            if (status < 200 || status >= 300) {
                return Promise.reject(
                    new HttpError(statusText, status)
                );
            }
            return Promise.resolve({ status, headers, body });
        });
};
```

**Additional context**
Having this new method, I can easily handle the file attachments returned from a request without any additional treatment of the response.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

I don't see any difficulty for users to do that in user land, of any interest in having react-admin provide an alternative API to the native fetch API for that. So we won't add that capability to react-admin. 

Feel free to publish your own package for it!
