### ISSUE TITLE
Use Quill 2.0 branch for RichTextInput

### ISSUE THREAD

**Issue by anyalir** [marmelab/react-admin#6494]
**Is your feature request related to a problem? Please describe.**
I need to add Tables to a Quill instance, but that is not supported in the 1.3.x releases. 

**Describe the solution you'd like**
Make ra-input-rich-text use the 2.0.0 branch of quill.

**Describe alternatives you've considered**
I could ofc just fork react-admin and build the re-input-rich-text locally, but I could imagine I'm not the only one looking for that feature. I'd be doing the work anyway, would a pull req implementing this be welcome? :)

Thanks for considering!

**Comment by fzaninotto** [comment]
Quill 2.0 hasn't been released as a stable package. The latest stable available package is 1.3.7 (see https://github.com/quilljs/quill/releases). So we won't work on a new version of ra-input-rich-text for Quill 2.0 in the near future. If we were to work on an update, we'd probably not choose Quill, which feels like abandonware:

![image](https://user-images.githubusercontent.com/99944/128889765-b5a8d0ed-6d10-4d77-bef1-dffb02748e00.png)

Feel free to create your own package for Quill 2.0.

**Comment by anyalir** [comment]
Understood, thanks for the heads up. My use case is to provide a way to add and edit tables in RichTextInput. Would you know if that has already been explored, whether there is some prior work that i could pick up to contribute to?

**Comment by fzaninotto** [comment]
`ra-markdown`, an Enterprise Edition module (https://marmelab.com/ra-enterprise/modules/ra-markdown), supports table insertion in the Rich text editor. I would definitely recommend it!

https://user-images.githubusercontent.com/99944/129065906-a1e5d4a7-94f3-430a-90c6-ea5114b04fe0.mp4

**Comment by anyalir** [comment]
That's literally perfect, thank you so much!
