### ISSUE TITLE
How can optimize bundle size for app

### ISSUE THREAD

**Issue by romaaan-ur** [marmelab/react-admin#6495]
Hi dear maintainers.
I use this framework and say it is amazing, but I have one question:
How can I optimized bundle for application, example now it is more 2 mb. I know about dynamic import (ex React.lazy, Loadable), use him and analyze bundle, yes he is contained smallest files, but don't worked application. 
I have searched in stackoverflow, but found this link:
https://stackoverflow.com/questions/50285368/code-splitting-a-react-admin-app-with-a-bundle-before-and-after-login

P.s. I am looking for the optimal solution for the user, because downloaded files of 2 MB are not good practice.

**Comment by fzaninotto** [comment]
Hi Romaan,

And thanks for the kind words. 

Optimizing bundle size is a question that goes well beyond react-admin, and depends on the bundler you use. We do nothing special in react-admin, it's up to you, the developer, to use and configure a bundler for tree shaking and lazy loading. 

So I'll close this issue as it's out of our scope. 

As a side note, the react-admin e-commerce demo (https://marmelab.com/react-admin-demo/#/), which simply uses Create React App with no special configuration, loads 600kB of JS. You should be able to load a react-admin app with way less than 2MB.
