### ISSUE TITLE
Docs: linkToRecord example code showing undefined variable

### ISSUE THREAD

**Issue by mddarmawan** [marmelab/react-admin#6497]
Hello, 

From the [linkToRecord documentation](https://marmelab.com/react-admin/Fields.html#linking-to-other-records) there is a line of code which returning `<Link>` with `{seller.username}` as it's value. Unfortunately, it's showing in the editor: 
![Screen Shot 2021-08-10 at 21 28 30](https://user-images.githubusercontent.com/22543134/128885194-cf8b1fc5-85f3-4582-8f97-3f884a70015e.png)
which I think the `seller` variable is not undefined yet.

I know it is just an example code that we need to change to match with our production code. But is it a good idea to make the variable more clear to the reader?

Thanks.

**Comment by fzaninotto** [comment]
You're right, I'm marking this as a documentation issue.
