### ISSUE TITLE
Attempted import error: 'mergeRefs' is not exported from 'ra-core'.

### ISSUE THREAD

**Issue by omattman** [marmelab/react-admin#6501]
When updating react-admin from v3.13.5 to latest version (v3.17.1) I receive the following error when starting up the server.

```shell
Failed to compile.

./node_modules/ra-ui-materialui/esm/input/AutocompleteInput.js
Attempted import error: 'mergeRefs' is not exported from 'ra-core'.
```

Even when downgrading, to the previously mentioned version again, the issue still persists. I have tried deleting `node_modules` folder and do a clean install but it still occurs.

**Comment by NastyaLo** [comment]
@omattman 
Hi!
I have the same problem, maybe you could describe how to solve it?

**Comment by omattman** [comment]
Hi @NastyaLo, 

I deleted the entire project, then pulled it again from remote repo. Before running `npm install` I made sure to install react-admin and ra-core @ latest. Afterwards I ran the normal npm install setup and managed to make it work. Just ensure that all project dependencies that are connected to react-admin are updated to the same version.

**Comment by NastyaLo** [comment]
@omattman Thank you!
Btw I had a little different source of the problem: project dependencies had same libs as deps of react-admin, but different versions, so we fixed it by writing strict versions inside package.json. I hope It will help someone :)
But the problem is really just in libs versions
