### ISSUE TITLE
Chip labels are undefined in Array Inputs where the source data is an array of objects

### ISSUE THREAD

**Issue by christylaguardia** [marmelab/react-admin#6506]
**What you were expecting:**

The chip labels should display.

**What happened instead:**

The chip labels are undefined and render blank/empty chips. Or if this is the intended data shape, please update the docs.

**Steps to reproduce:**

Create two array fields where one is an array of ids and another is an array of the objects (with `id` and `name` properties).

**Related code:**

Replicated in this forked [Codesandbox](https://codesandbox.io/s/react-admin-v3-advanced-recipes-quick-create-preview-forked-hgper?file=/src/comments/CommentEdit.js). See [https://hgper.csb.app/#/comments/1](https://hgper.csb.app/#/comments/1).

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.4.0
* Last version that did not exhibit the issue (if applicable):
* React version:  16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
thanks for the report. 

When working with a value that is an array of objects, `<AutocompleteArrayInput>` requires you to use `parse` and `format` to turn the value into an array of scalar values. 

So in your example:

```diff
<AutocompleteArrayInput
                    label="Category (array of objects)"
                    source="categories"
+                   parse={value =>
+                       value && value.map(v => ({ id: v }))
+                  }
+                   format={value => value && value.map(v => v.id)}
                   choices={choices}
                />
```

But I agree this is arcane and not documented, so I'm marking this as a documentation issue.
