### ISSUE TITLE
Wrong type for error prop in LayoutProps (typescript, ra-ui-materialui)

### ISSUE THREAD

**Issue by NastyaLo** [marmelab/react-admin#6507]
**What you were expecting:**
I expect LayoutProps['error'] error prop to have type `Error | undefined`
```
export interface LayoutProps extends CoreLayoutProps, Omit<HtmlHTMLAttributes<HTMLDivElement>, 'title'> {
    appBar?: ComponentType<AppBarProps>;
    classes?: any;
    className?: string;
    error?: ComponentType<{
        error?: Error;
        errorInfo?: React.ErrorInfo;
        title?: string | ReactElement<any>;
    }>;
    menu?: ComponentType<MenuProps>;
    notification?: ComponentType;
    sidebar?: ComponentType<{
        children: JSX.Element;
    }>;
    theme?: ThemeOptions;
}
```

**What happened instead:**
https://github.com/marmelab/react-admin/blob/8219644e002677f4b0d698505d3456c3ac3b42f7/packages/ra-ui-materialui/src/layout/Layout.tsx#L189
![image](https://user-images.githubusercontent.com/32715171/129160962-bc78a5a2-f0f7-4658-bd12-613431daf4a5.png)

**Related code:**
As we can see from render for error, error prop has type `Error | undefined | null`
https://github.com/marmelab/react-admin/blob/8219644e002677f4b0d698505d3456c3ac3b42f7/packages/ra-ui-materialui/src/layout/Layout.tsx#L99
![image](https://user-images.githubusercontent.com/32715171/129161651-9245abb1-1cd4-47c5-b405-39f672d64307.png)

**Environment**

* React-admin version: 3.17.1
* React version: 17.0.2

**Comment by fzaninotto** [comment]
Reproduced, thanks for the report
