### ISSUE TITLE
Allow updating nested/joined resources in a single Edit form

### ISSUE THREAD

**Issue by larsblumberg** [marmelab/react-admin#6517]
**Is your feature request related to a problem? Please describe.**

We can set up Show and Edit forms which display/mutate a single resource, most often stored as a table row (depending on the underlying data provider). There are use cases where we want to offer users to modify nested resources (that is joined rows) within the same Edit form. While we can already use `ReferenceField` to display related/referenced/joined resources/fields, we cannot updates them along with the "root" resource.

Example use case: The settings/profile page could allow users to change their display name as well as their team name. Both the user and the team are however 2 different, but joined/related resources.

**Describe the solution you'd like**

I'd like to have Edit forms to allow for modifying related resources, too. Depending on the data provider, this would require one ore more http requests to the backend in order to update those resources. In the case of GraphQL providers, a single mutation allows for changing nested resources, too. At least Hasura does provide such mutations which could be leveraged by the react-admin (graphql) data provider.

**Describe alternatives you've considered**

We can provide two independent Edit forms on the same page via a custom route. However both forms each come with their own save buttons. It might not be obvious to the user that they need to press different buttons in order to have their changes saved.

To workaround that, we can always directly call the data provider (i.e. ApolloClient in case of GraphQL) by writing custom mutations with nested resource updates. This however defeats the purpose/design goals of react-admin, namely to encapsualte such functionality with an easy to use component API. react-admin does have a great API, however to my knowledge it doesn't support nested updates.

**Additional context**

This problem probably requires a complex solution since many existing features such as undo need to consider the undoing of nested resource updates, too. Developers will expect the undo functionality to work. Maybe in the first implementation version undo could be disabled for Edit forms with nested updates to facilitate an initial implementation. I guess there are more implications of nested updating.

**Comment by djhi** [comment]
Hi and thanks for the detailed feature request. This is not something we want to include in the core, at least for now. However, this is achievable in user land using the core hooks (such as `useUpdate`) and custom forms.

**Comment by larsblumberg** [comment]
Thanks for your feedback!
