### ISSUE TITLE
Inconsistent type for DeleteResult

### ISSUE THREAD

**Issue by mjomble** [marmelab/react-admin#6530]
**What you were expecting:**
I returned `{}` from my custom data provider's `delete` method and expected it to work because the `data` property is typed as optional:
https://github.com/marmelab/react-admin/blob/b007fb7176d2ca4a779acddccd5b0316987b1d03/packages/ra-core/src/types.ts#L208

**What happened instead:**
I got this error: "The response to 'delete' must be like { data: ... }, but the received response does not have a 'data' key. The dataProvider is probably wrong for 'delete'."

**Steps to reproduce:**
Use a custom dataProvider with the following delete method: `delete: () => ({})`, then try deleting a record.

**Related code:**
https://codesandbox.io/s/morning-thunder-ofouy?file=/src/dataProvider.tsx

**Other information:**
This line requires the `data` property to be present for all responses:
https://github.com/marmelab/react-admin/blob/b007fb7176d2ca4a779acddccd5b0316987b1d03/packages/ra-core/src/dataProvider/validateResponseFormat.ts#L17
It should probably have an exception for delete operations.

I can submit a PR that adds this exception, but maybe there are other pieces of code that also require this property to always be present. A comment from someone more familiar with the codebase would be helpful.

**Environment**

* React-admin version: 3.17.1
* Last version that did not exhibit the issue (if applicable): -
* React version: 17.0.2
* Browser: Chrome 92 on Windows 10
* Stack trace (in case of a JS error): -

**Comment by mjomble** [comment]
Ah, a bit of testing shows that this would also fail:

https://github.com/marmelab/react-admin/blob/b007fb7176d2ca4a779acddccd5b0316987b1d03/packages/ra-core/src/reducer/admin/resource/list/selectedIds.ts#L51

Now I wonder if perhaps the typedef should be changed instead.

**Comment by djhi** [comment]
Hi and thanks for the report. Yes, the typedef should be changed. We require the `data` property as stated in https://marmelab.com/react-admin/DataProviders.html#response-format

**Comment by mjomble** [comment]
I wonder if the entire record is required or just an object with the `id` field?
In some cases, it may be easier to return only the id from the backend without having to fetch the full deleted object.

**Comment by djhi** [comment]
It should suffice
