### ISSUE TITLE
ReferenceField for Polymorphic Associations

### ISSUE THREAD

**Issue by WesleyKapow** [marmelab/react-admin#6532]
**Is your feature request related to a problem? Please describe.**
The existing `ReferenceField` component is great when you have a simple reference field, e.g. `author_id` which maps to a `author.id`. However, it does not lend itself to polymorphic association where multiple other resources can be referenced from either a single field or multiple, e.g. `customer_type, customer_id` or `customer = :customer_type/:customer_id` (let's say where `customer_type` is either a `person` or a `business`).

**Describe the solution you'd like**
Having a component similar to `ReferenceField` that didn't take a `references` prop and instead took the following two props:
1. Pass in a function for `source` which takes a record and returns something that will then get passed in `params` in the `getMany` call. This way, when dealing with two columns you could do something like `source={(record) => [record.customer_type, record.customer_id]}` and have your `dataprovider` look for something like `params.references` to interpret these and look them up.
2. Similarly, we need a way to specify how `ReferenceField` matches a given record to the result of `getMany`. Currently it is hardcoded to `record[source] == reference.id`. Again if we could pass in a method here that'd open the door to polymorphic associations, something like: `match={matcher}`.
```js
function matcher(references, record) {
  // Two field polymorphic association.
  return references.find((ref) => ref.type == record.customer_type && ref.id == record.customer_id)

  // Single field polymorphic association, e.g. ":customer_type/:customer_id"
  let [type, id] = record.customer.split('/')
  return references.find((ref) => ref.type == type && ref.id == id)
}
```

**Additional context**
My particular use case is wrapping a REST API that I do not control that uses `/resource/id` references. Ideally I could wrap these fields in something like `ReferenceField` and have it pass all of the unique references to my dataprovider's `getMany` method AND hook into how matches are performed.

In trying to do this myself, I get a bit lost in the different contexts and use hooks that do the magic for `ReferenceField`. Any pointers here would be GREATLY APPRECIATED!!

Cheers on the awesome library!

**Comment by djhi** [comment]
Hi and thanks for the feature request. I don't see why this couldn't be achieved in user land with a custom `ReferenceField`.

**Comment by fzaninotto** [comment]
I agree with Gildas: this is something that is achievable in user land, and that we don't want to include in the core for now. If you develop a package for it, please open a PR in our ecosystem documentation so that we can link to it!
