### ISSUE TITLE
Redundant Authorization sections in the docs

### ISSUE THREAD

**Issue by hichemfantar** [marmelab/react-admin#6539]
**Is your feature request related to a problem? Please describe.**
Currently there are 2 separate docs for Authorization.
There's [Authorization.html](https://marmelab.com/react-admin/Authorization.html) and there's a different version that you can access from [Authentication.html#authorization](https://marmelab.com/react-admin/Authentication.html#authorization)

the Authorization.html came up in google search but there's no way to access it from inside the docs.

**Describe the solution you'd like**
- Remove Authorization.html page
OR
- Remove the authorization section (and its recipes) from the authentication page and add Authorization.html link to the side navigation bar.

**Comment by djhi** [comment]
Thanks for the report

**Comment by fzaninotto** [comment]
Fixed by 9fcff3f05186bb57e267ffea7aff452af6b4c2cc
