### ISSUE TITLE
BooleanField no longer displays label by default

### ISSUE THREAD

**Issue by flouc001** [marmelab/react-admin#6549]
**What you were expecting:**
When using the `BooleanField` the label should be displayed by default due to the `defaultProps` setting `addLabel` to `true`.

**What happened instead:**
`BooleanField` no longer displays the label without explicitly specifying the `addLabel` prop, this is breaking.

**Steps to reproduce:**
1. Add a `BooleanField` component to a view with the `label` prop set.
2. Observe the field being rendered without the label.
3. Add the `addLabel` prop.
4. Observe the label being rendered.

**Related code:**
https://codesandbox.io/s/eloquent-silence-1te8b

Observe the tick with no label on this page: https://1te8b.sse.codesandbox.io/#/posts/13/show/2

**Other information:**
I think it's down to the memo being moved directly to the default export in this commit: https://github.com/marmelab/react-admin/commit/b79787a65d82da82e3862e7e9c7fadaf82525061#diff-d7c4dd12e78cb28e0370dc53068aa45ec475f6fe54b5b40db238547e6278f5aaR119

It's no longer respecting the `defaultProps`.

**Environment**

* React-admin version: 3.17.3
* Last version that did not exhibit the issue (if applicable): 3.17.2
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error): N/A

**Comment by flouc001** [comment]
@WiXSL what's the motivation to moving away from FC typing? I'm guessing you moved the memo because Typescript was throwing an error.

**Comment by WiXSL** [comment]
> @WiXSL what's the motivation to moving away from FC typing? I'm guessing you moved the memo because Typescript was throwing an error.

Here: https://github.com/marmelab/react-admin/pull/6515#issuecomment-906702131

One solution could be to use default values for props inside the component instead of `BooleanField.defaultProps`

**Comment by flouc001** [comment]
@WiXSL thank you for the response - the motivation makes sense! I raised a PR with an idea for maybe moving the responsibility to the displaying components. Let me know what you think, just throwing some ideas out there.

**Comment by WiXSL** [comment]
We have to ping @fzaninotto and @djhi on how to solve this

**Comment by flouc001** [comment]
Agreed, that's why I was thinking of moving the logic to the component with the responsibility of displaying the component. That way it fixes all of the fields that may encounter this issue rather than just `BooleanInput`.

**Comment by eamahanna** [comment]
I also encountered this issue with the `DateField` and `ArrayField`.
