### ISSUE TITLE
Parameter 'props' implicitly has an 'any' type.  TS7006

### ISSUE THREAD

**Issue by JLeLo** [marmelab/react-admin#6554]
Hi,

I was running `make run-demo` and was starting to build the demo react-admin app.

![1](https://user-images.githubusercontent.com/17622439/132100209-27c43e65-424c-4a2e-8e62-3d0781191a9e.PNG)

There is a bug in `react-admin\examples\demo\src\categories\CategoryList.tsx`

![2](https://user-images.githubusercontent.com/17622439/132100278-d3bbf961-0284-4d11-b86f-fc1eb1313e6b.png)

**Comment by fzaninotto** [comment]
Thanks for the report!
