### ISSUE TITLE
Uncaught Error: Choice creation is only supported when optionText is a string

### ISSUE THREAD

**Issue by hieudn2012** [marmelab/react-admin#6560]
```<SelectInput optionText={(record) => record.fullName} optionValue="id" />```
React-admin: 3.18.0
<img width="952" alt="Screen Shot 2021-09-08 at 11 22 12 AM" src="https://user-images.githubusercontent.com/51831671/132446170-3573ab7c-9207-427d-a021-c1d7c11eca27.png">

**Comment by fzaninotto** [comment]
Thanks for reporting. It is indeed a bug, and we've already fixed it in #6558, to be released in 3.18.1.

**Comment by davidhenley** [comment]
Thank you @hieudn2012 this was driving me crazy

**Comment by davidhenley** [comment]
@fzaninotto @hieudn2012 That fixed it! Thank you!
