### ISSUE TITLE
Update Django Rest Framework Data Provider's Link to New Repo

### ISSUE THREAD

**Issue by FulcronZ** [marmelab/react-admin#6565]
**Is your feature request related to a problem? Please describe.**
The [Django Rest Framework data provider][drf_provider_2] listed in [data provider page][data_provider_page] can support 
only up to React Admin 2. And there is a new repo which can support React Admin 3. 

**Describe the solution you'd like**
In that [page][data_provider_page], update the DRF data provider's link for React Admin 3 to 
[bmihelac/ra-data-django-rest-framework][drf_provider_3]. 

**Describe alternatives you've considered**
I havn't found other DRF provider alternatives. 

**Additional context**
It has a working example out in its repository. I tried it out and it worked nicely. 

[data_provider_page]: https://marmelab.com/react-admin/DataProviders.html
[drf_provider_2]: https://github.com/synaptic-cl/ra-data-drf
[drf_provider_3]: https://github.com/bmihelac/ra-data-django-rest-framework

**Comment by fzaninotto** [comment]
Thanks for the report!

**Comment by FulcronZ** [comment]
Thanks for the update 😃
