### ISSUE TITLE
[ra-data-graphql-simple] Wrong inferred type non-null array arg

### ISSUE THREAD

**Issue by OoDeLally** [marmelab/react-admin#6581]
```graphql
createMultiChoiceQuestion(
  answers: [String!]!
  level: Int!
): MultiChoiceQuestion!
```

**What you were expecting:**
```graphql
mutation createMultiChoiceQuestion($answers: [String!]!, $level: Int!) {
  ....
}
```

**What happened instead:**
```graphql
mutation createMultiChoiceQuestion($answers: [String!], $level: Int!) {
  ....
}
```
leading to the following error:
```
Variable "$answers" of type "[String!]" used in position expecting type "[String!]!".
```

**Steps to reproduce:**
Run the above example with a non-null array as arg.

**Other information:**
I've investigated a bit, and I'm not sure if the error comes from `ra-data-graphql-simple` or from `graphql-ast-types-browser` that is used under-the-hood to build the query.

**Environment**

* React-admin version: 3.17.2
* ra-data-graphql-simple version: 3.13.2

**Comment by fzaninotto** [comment]
No news for some time, closing.
