### ISSUE TITLE
Type error MenuItemLink

### ISSUE THREAD

**Issue by mshd** [marmelab/react-admin#6582]
./layout/Menu.tsx:38:8
Type error: Type '{ to: string; primaryText: string; leftIcon: Element; dense: boolean; }' is missing the following properties from type 'Pick<any, "title" | "alignItems" | "color" | "translate" | "button" | "hidden" | "exact" | "strict" | "style" | "dense" | "disabled" | "replace" | "children" | "classes" | "slot" | ... 276 more ... | "ContainerProps">': title, alignItems, color, translate, and 284 more.

I haven't added or removed anyfields, they are identical with https://github.com/marmelab/react-admin/blob/1cb407b5085e52ed1cf0d4c1a69e9759b3143189/examples/demo/src/layout/Menu.tsx

**Comment by fzaninotto** [comment]
Please use the issue template, and a way to reproduce the problem

**Comment by ljardim** [comment]
Have the same issue. Managed to reproduce with a clean project by doing the following steps:

- Create new blank react app using typescript template: `npx create-react-app my-app --template typescript`
- `cd my-app/`
- `yarn add react-admin ra-data-json-server prop-types`
- replace the content of App.tsx with the following:

```TypeScript
import React from 'react';
import {Admin, MenuItemLink} from "react-admin";
import jsonServerProvider from 'ra-data-json-server';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');

const Dashboard = () => {
  return (
      <MenuItemLink primaryText="testing" />
  )
}

function App() {
  return (
    <Admin dataProvider={dataProvider} dashboard={Dashboard} />
  );
}

export default App;
```

**Comment by fzaninotto** [comment]
Thanks, I managed to reproduce the issue in https://codesandbox.io/s/dry-pond-for9c?file=/src/App.tsx, but not in the Simple example - no matter how I tweak the TypeScript config. Note that I also never met this error in any project.

Besides, I have absolutely no idea about what hTypeScript complains about. 

I'd love a helping hand if someone loves cryptic TypeScript messages.

**Comment by rsjunior** [comment]
Same problem here =(

**Comment by ljardim** [comment]
Seems to work by ignoring it using ts-ignore above MenuItemLink as a temporary workaround:

{/*@ts-ignore*/}

**Comment by TannicArturo98** [comment]
Same error only on my Vercel dev app. On VS Code doesn't appear.

**Comment by mvanderblom** [comment]
Have the same error.

**Comment by padmalcom** [comment]
Same problem here, the error does not really tell which properties are missing. I could reproduce with the demo.

**Comment by fzaninotto** [comment]
@padmalcom can you explain how exactly you reproduced it?

**Comment by padmalcom** [comment]
@fzaninotto It is difficult for me to reproduce the steps since I used the demo to learn an built it up step by step. When I customized the menu by copying the code, the exact error from @mshd appears. As stated by @ljardim, adding `@ts-ignore` surpresses the issue (which does not really seem to be one, since everything works as expected).
```
    return (
        // @ts-ignore
        <MenuItemLink
            ref={ref}
            to="/configuration"
            primaryText={translate('pos.configuration')}
            leftIcon={<SettingsIcon />}
            onClick={props.onClick}
            sidebarIsOpen
        />
    );
```
I wish I could give you more information but I come from the java world and I'm not yet too familiar with debugging in JS.

**Comment by nrikiji** [comment]
Same error for me.

https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/MenuItemLink.tsx#L56-L72
I tried the following code based on this.

```
import * as React from "react"
import BookIcon from "@material-ui/icons/Book"
import { Menu as Menu2, MenuItemLink } from "react-admin"

export const Menu = (props: any) => {
  return (
    <Menu2 {...props}>
      {/@ts-ignore/}
      <MenuItemLink to="/posts" primaryText="Posts" leftIcon={<BookIcon />} />
    </Menu2>
  )
}
```

```
"react": "^17.0.2"
"react-admin": "^3.19.0",
"typescript": "^4.1.2",
```

**Comment by maxcorbeau** [comment]
same issue when I re-use `Menu` and `SubMenu` from the poster demo https://github.com/marmelab/react-admin/blob/master/examples/demo/src/layout/Menu.tsx. I'm also inserting `{/* @ts-ignore */}` above `<MenuItemLink>` elements to suppress the error.

**Comment by felicandalc** [comment]
Have you tried adding to devDependencies:
- @types/react-router
- @types/react-router-dom

**Comment by WiXSL** [comment]
@mshd, have you tried @felicandalc solution?

**Comment by soullivaneuh** [comment]
I confirm @felicandalc solution.

@fzaninotto Maybe react-admin should require them as dependencies?

**Comment by felicandalc** [comment]
> I confirm @felicandalc solution.
> 
> @fzaninotto Maybe react-admin should require them as dependencies?

Yes, I think so too, would you like me to open a PR?

**Comment by rafaelgslima** [comment]
I already have this types added and I still with the same error

**Comment by mshd** [comment]
Closing this as it seems to be resolved.

**Comment by MaxAlex666** [comment]
After updating to: react-admin: "4.16.16" and "typescript": "5.4.5" I got
similar error, such an error had never occurred in the project before.

**Comment by ilia-os** [comment]
@MaxAlex666 you probably also updated @types/react.
Issue was introduced in @types/react v18.2.66 and is still present in the current v18.3.2
https://github.com/marmelab/react-admin/issues/9737
