### ISSUE TITLE
Allowing custom link in SimpleList

### ISSUE THREAD

**Issue by jdemangeon** [marmelab/react-admin#6592]
Hi!

On the application I currently working on, I would like to redirect my user to `/#/reports/X/details` instead of `/#/reports/X` or `/#/reports/X/show` when I click on one of the SimpleList line.

However, whereas the SimpleList allows to provide a custom function in `linkType`, and as it's name suggests, it only allow the user to return a "link type" (show or edit) as returning value.

**Describe the solution you'd like**

It would be cool to be able to provide any link we want. (or any action we want, just like the `rowClick` function from RA.Datagrid.

Note: Unfortunately, the `linkToRecord` function is called without the type arg here (https://github.com/marmelab/react-admin/blob/c0cf7d626e44c29f9a1e1a2eab7b640aa6027c97/packages/ra-ui-materialui/src/list/SimpleList.tsx#L285). We concat the "/show" at the end.

Thanks by advance

**Comment by djhi** [comment]
Fixed by #6594

**Comment by sebastianbuechler** [comment]
@djhi as @jdemangeon  mentioned the `rowClick` of `RA.Datagrid` it came to my mind to use `expand` here on the `SimpleList` as well. Is it possible to integrate this too with the corresponding `expand` prop?
