### ISSUE TITLE
Option to remove default Title component

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#6593]
We'd like to be able to remove the default title in the app. The way the current title's value is displayed is by changing the text of the element with id `react-admin-title` on every page change. 

This means we could do something like this when customising our layout, to place our own title wherever we like.

```
export default (props) => (
  <Layout {...props} appBar={MyAppBar}>
    <h1 id="react-admin-title">React Admin</h1>
    {props.children}
  </Layout>
);
```

This should work great if not for one problem, the default title element already has an id of `react-admin-title`. There should be a way to disable this without needing to completely reimplement the `appBar` component. 

We can pass through custom `userMenu` to the `appBar` so why not a title as well? It means we could do something like this

`const CustomAppBar = (props) => <AppBar {...props} title={null} />;`

and let us easily implement a custom title elsewhere.

This can give us something like this:

![image](https://user-images.githubusercontent.com/17087167/133759734-aeff90b8-e746-4b12-9d19-4f044112016b.png)

Which might work better for a number of dashboards.

**Comment by fzaninotto** [comment]
Thanks for your suggestion. 

You can already replace the AppBar title by passing a child to it. To remove the title, pass an empty child:

```jsx
const CustomAppBar = (props) => <AppBar {...props}><span style={{ flex: 1 }} /></AppBar>;
```

I don't see the point to introduce an option to replace a one liner.

**Comment by andrico1234** [comment]
Ahh 🤦🏽 , you're completely right I missed it in the [docs](https://marmelab.com/react-admin/Theming.html#customizing-the-appbar-content)
