### ISSUE TITLE
[ra-test] No way to use custom dataProvider as shown in the examples

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#6597]
In the [ra-test](https://github.com/marmelab/react-admin/tree/master/packages/ra-test#testing-permissions) README, the last examples declare a custom dataProvider but then never use them. And `<TestContext />` don't provide a way to pass a custom dataProvider (I've read the code).

Is this an unimplemented possibility ? A bug in the documentation ? Something missing ?

**Comment by djhi** [comment]
This is indeed a documentation issue. `TestContext` does not even wrap anything with a DataProvider context. You have to do it yourself. Until we fix the documentation and/or provide more tools around this, you can refer to some our tests. For instance: https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/useListController.spec.tsx#L59

**Comment by DjebbZ** [comment]
Thanks for the pointer !

It kinda works because we now move the `loaded`/`loading` booleans correctly, but the `total` received inside our list is still `undefined`. I need to wrap my head around what's happening in `useGetMainList`.

**Comment by WiXSL** [comment]
Fixed by #6600
