### ISSUE TITLE
BulkDeleteButton doesn't do `refresh()` on failure

### ISSUE THREAD

**Issue by MWojtasik** [marmelab/react-admin#6598]
**What you were expecting:**
After deleting any items in `<List />` by bulk actions, when those items are unsuccessfully deleted on backend they should be restored on List view.

**What happened instead:**

Unsuccessfully deleted items are gone, and user needs to refresh whole page to see that those items are still in List.

**Steps to reproduce:**
try to delete some post from BulkActions - after error deleted elements aren't restored
https://codesandbox.io/s/react-admin-issue-bulkdeletebutton-2qezd?file=/src/dataProvider.js

**Related code:**
https://codesandbox.io/s/react-admin-issue-bulkdeletebutton-2qezd?file=/src/dataProvider.js

**Other information:**
IMO there is missing `refresh()` in `onFailure` function in `BulkDeleteButton`

**Environment**

* React-admin version: ^3.9.0
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.9.0
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Reproduced. Thanks for the report
