### ISSUE TITLE
[docs] Record Buttons are missing documentation details

### ISSUE THREAD

**Issue by ValentinnDimitroff** [marmelab/react-admin#6602]
**Is your feature request related to a problem? Please describe.**
My suggestion is related to the documentaion of the `Record Buttons` page.

**Describe the solution you'd like**
I would like to support you in filling up the docs with the supported properties and behaviour 

**Additional context**
It seemed strange that there are titles already but no body. Couldn't find an issue if it is WIP and if it is not - I'll be happy to take it.

**Comment by fzaninotto** [comment]
Please submit a PR if you feel like it!

I'm closing this issue as we know the documentation is lacking on some parts.
