### ISSUE TITLE
Missing styles for RichTextField content

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#6607]
**What you were expecting:**
When using the `align right`, `align center`, `justify` and the indents buttons in the `<RichTextInput />` component, the content in the resulting `RichTextField` would have these styles applied.

**What happened instead:**
When using theses buttons, the resulting content is still aligned to the left. Note that the content does have the proper css classes of `ql-align-right`, `ql-align-center`, `ql-align-justify` and `ql-indent-<X>` where `<X>` is the number of indents applied to the content.  

**Steps to reproduce:**
- Add some paragraphs in a `<RichTextInput />`
- Style them with the aforementionned buttons
- See the results in a `<RichTextField />`

**Related code:**
Sorry, no repro code, it's a quick bug report. But ! Here's the CSS code we manually inserted to adjust the presentation, it may prove useful to fix the problem (it's SASS code but pretty straightforward):

``` sass
.ql-align-center {
    text-align: center;
}

.ql-align-right {
    text-align: right;
}

.ql-align-justify {
    text-align: justify;
}

@for $indent from 1 to 8 {
    .ql-indent-#{$indent} {
        padding-left: #{$indent}em;
    }
}
```

**Environment**

* React-admin version: "^3.17.3"
* React version: "^17.0.1"
* Browser: All

Hope this helps !

(mentioning @dorian-ubisoft for the record)

**Comment by djhi** [comment]
Not really a bug as we don't include those actions by default, so it is indeed your job to update the styles if you need them. By the way, have you noticed we released [ra-richtext-tiptap](https://github.com/marmelab/ra-richtext-tiptap)? This will probably become the new richtext in v4
