### ISSUE TITLE
TextField and TextInput components don't show label out of SimpleForm context

### ISSUE THREAD

**Issue by Luke1982** [marmelab/react-admin#6610]
**What you were expecting:**
I expected the field to render with a label

**What happened instead:**
It rendered without a label

**Steps to reproduce:**
Follow the instructions as described in the [documentation](https://marmelab.com/react-admin/CreateEdit.html#custom-form-component) to render fields outside of the stock `<SimpleForm>` component and try to render a field.

**Related code:**
https://github.com/Luke1982/workshop-portal-v2/blob/master/src/components/WorkassignmentEdit.js

**Environment**

* React-admin version: 3.18.2
* React version: 17.0.2
* Browser: Firefox

**Comment by WiXSL** [comment]
I believe in order to work for `TextField` components inside a custom layout, you have to add a `Labeled` component.
`TextField` components don't resolve the labels themself and the `addLabel` trick work only if your fields are inside on of `react-admin` layouts

```jsx
<Labeled label="My Label">
    <TextField source="...">
</Labeled>
```

**Comment by djhi** [comment]
> But I personally think Field components should be allowed to resolve the label, so they can be more easily used in custom layouts

Yes this is most probably something that will change in v4

**Comment by Luke1982** [comment]
> This is explained in the [docs](https://marmelab.com/react-admin/Fields.html#adding-a-label-to-custom-field-components)

I missed that one even though I thought I had read the docs carefully, thanks for the heads up!

**Comment by stumpykilo** [comment]
In react-admin `4.1.1` I am not seeing labels render with `<TextField label"test" source"test" />`  inside a `<SimpleForm />`.

**Comment by fzaninotto** [comment]
@stumpykilo then please open a new issue, following the issue template, and including a reproduction.
