### ISSUE TITLE
Type error with TranslatableInputs caused by TranslatableProps 

### ISSUE THREAD

**Issue by nicolas-lescop** [marmelab/react-admin#6624]
**What you were expecting:**
Use TranslatableInputs container without the need of adding useless source on typescript stack.

**What happened instead:**
![image](https://user-images.githubusercontent.com/1667009/135124194-b40078fb-cbfb-434e-8142-6a79b60ae369.png)

**Steps to reproduce:**
```
<TranslatableInputs locales={['en', 'fr']}>
    <TextInput source="description" />
</TranslatableInputs>
```
Property 'source' is missing in type '{ children: Element[]; locales: string[]; }' but required in type 'TranslatableProps'.

**Related code:**
https://codesandbox.io/s/gallant-bush-jfuwx?file=/src/posts/PostCreate.tsx

**Other information:**
You need to fork the codesandbox to see typescript errors 

**Environment**

* React-admin version: 3.18.2
* Last version that did not exhibit the issue (if applicable): 3.17.2
* React version: 17.0.1
* Browser: 
* Stack trace (in case of a JS error):
* "ra-i18n-polyglot": "^3.18.2",
*  "ra-language-english": "^3.18.2",
*  "ra-language-french": "^3.18.2",

**Comment by djhi** [comment]
Indeed, thanks for the report!
