### ISSUE TITLE
Custom menu doesn't collapse

### ISSUE THREAD

**Issue by mvanderblom** [marmelab/react-admin#6630]
I'm trying to add a custom menu following the documentation here: https://marmelab.com/react-admin/Theming.html#using-a-custom-menu. The menu gets displayed ok but when it is collapsed, the text stays visible behind the main content

Open menu: 
![image](https://user-images.githubusercontent.com/3511418/135281281-5345fbd6-b426-4f86-a7b8-883ce84c8dab.png)

Closed menu with text visible behind main content:
![image](https://user-images.githubusercontent.com/3511418/135281362-ae4b489f-1f4f-43ce-9b4b-2892d9b17a95.png)

Codesandbox example:
https://codesandbox.io/s/youthful-fog-h607k?file=/src/App.js

I would expect the collapsing of the menu to be handled by the MenuItemLink component as described here: https://marmelab.com/react-admin/Buttons.html#menuitemlink

I'm not sure what causes the current beahviour

**Comment by djhi** [comment]
Indeedm thanks for the report. It seems that #6534 introduced this breaking change

**Comment by WiXSL** [comment]
Duplicate of #6591?

**Comment by djhi** [comment]
No, that's not the same issue

**Comment by mvanderblom** [comment]
Thanks for the quick reply and fix!

**Comment by felipejh** [comment]
@mrclayman 

I will try to exemplify:

1- `CustomMuiTheme.tsx`
```js
const theme: RaThemeOptions = {
   overrides: {
      RaSidebar: {
         fixed: {
           position: 'inherit'
         }
       }
   }
}

export { theme } 
```

2- `CustomLayout.tsx`
```js
import { theme } ...

<Layout theme={theme}/>

```

3- `App.tsx`
```js
<Admin 
   layout={CustomLayout}
/>
```
