### ISSUE TITLE
react admin demo not working 

### ISSUE THREAD

**Issue by skandarChahbouni** [marmelab/react-admin#6652]
After i have downloaded react-admin zip folder from github, i have oppened the demo subfolder in vscode and i excuted "npm install" command. then after it i excuted "yarn start" but i recieved all this errors. any one have an idea ? thank you in advance.

src\dashboard\Dashboard.tsx
  Line 167:43:  Parsing error: Unexpected token, expected "}"

  165 |     return isXSmall ? (
  166 |         <div>
> 167 |             <div style={styles.flexColumn as CSSProperties}>
      |                                           ^
  168 |                 <Welcome />
  169 |                 <MonthlyRevenue value={revenue} />
  170 |                 <VerticalSpacer />

src\dashboard\OrderChart.tsx
  Line 34:15:  Parsing error: Unexpected token, expected ","

  32 |             acc[day] += curr.total;
  33 |             return acc;
> 34 |         }, {} as { [key: string]: number });
     |               ^
  35 |
  36 | const getRevenuePerDay = (orders: Order[]): TotalByDay[] => {
  37 |     const daysWithRevenue = aggregateOrdersByDay(orders);

src\dataProvider\rest.ts
  Line 14:53:  Parsing error: Unexpected token, expected "]"

  12 |                           () =>
  13 |                               resolve(
> 14 |                                   restProvider[name as string](resource, params)
     |                                                     ^
  15 |                               ),
  16 |                           500
  17 |                       )

src\layout\themes.ts
  Line 9:22:  Parsing error: Unexpected token, expected ","

   7 |             main: '#FBBA72',
   8 |         },
>  9 |         type: 'dark' as 'dark', // Switching the dark mode on is a single property value change.
     |                      ^
  10 |     },
  11 |     sidebar: {
  12 |         width: 200,

src\orders\Basket.tsx
  Line 42:27:  Parsing error: Unexpected token, expected ","

  40 |                         state.admin.resources.products.data[
  41 |                             productId
> 42 |                         ] as Product
     |                           ^
  43 |                 )
  44 |                 .filter(r => typeof r !== 'undefined')
  45 |                 .reduce((prev, next) => {

src\orders\NbItemsField.tsx
  Line 8:19:  Parsing error: Unexpected token

   6 |
   7 | const NbItemsField = ({ record }: FieldProps<Order>) => (
>  8 |     <FunctionField<Order> record={record} render={render} />
     |                   ^
   9 | );
  10 |
  11 | NbItemsField.defaultProps = {

src\orders\OrderList.tsx
  Line 97:55:  Parsing error: Unexpected token

   95 |         theme.breakpoints.down('xs')
   96 |     );
>  97 |     const [ordered, setOrdered] = useState<Identifier[]>([] as Identifier[]);
      |                                                       ^
   98 |     const [delivered, setDelivered] = useState<Identifier[]>(
   99 |         [] as Identifier[]
  100 |     );

src\reviews\ReviewList.tsx
  Line 88:62:  Parsing error: Unexpected token, expected ","

  86 |                                             isMatch
  87 |                                                 ? parseInt(
> 88 |                                                       (match as any).params.id,
     |                                                              ^
  89 |                                                       10
  90 |                                                   )
  91 |                                                 : undefined

src\reviews\ReviewListMobile.tsx
  Line 41:19:  Parsing error: Unexpected token, expected ","

  39 |     return loaded || Number(total) > 0 ? (
  40 |         <List className={classes.root}>
> 41 |             {(ids as Exclude<typeof ids, undefined>).map(id => {
     |                   ^
  42 |                 const item = (data as Exclude<typeof data, undefined>)[id];
  43 |                 if (!item) return null;
  44 |

src\visitors\Aside.tsx
  Line 228:56:  Parsing error: Unexpected token, expected "}"

  226 |                             {event.type === 'order' ? (
  227 |                                 <Order
> 228 |                                     record={event.data as OrderRecord}
      |                                                        ^
  229 |                                     key={`event_${event.data.id}`}
  230 |                                     basePath={basePath}
  231 |                                 />

src\visitors\VisitorCreate.tsx
  Line 41:22:  Parsing error: Missing semicolon.

  39 |     confirm_password,
  40 | }: AnyObject) => {
> 41 |     const errors = {} as any;
     |                      ^
  42 |
  43 |     if (password && confirm_password && password !== confirm_password) {
  44 |         errors.confirm_password = [

**Comment by djhi** [comment]
Hi, this is a monorepo and there are instructions about this in the root README
