### ISSUE TITLE
A delayed "GetList" overwrites response from a subsequent "GetOne"

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#6658]
I tried recreating this in the simple codesandbox, but I had trouble triggering a `getOne` whenever I moved from the list page into a single record. If anyone knows why, then I can provide a reproduction.

Problem:

I have a resource, like Posts, that fetches X records, but I only fetch the necessary data. Maybe just the title, ID, and author.

When I click through to a particular record, I fetch more data, like the article's contents, tags, etc.

Here's the sequence of events I follow to create this bug:

1. Go to Posts list
2. Go to post record 
3. Go back to post list (which fires a getList, but displays the existing data in the mean time)
4. Go to post record again

If the second request to `getList` takes a while, the request isn't cancelled when I access the post record. This means that if my post's `getOne` request returns earlier than the `getList` request, then the results from the `getList` request will overwrite the results from the `getOne`. Meaning I lose the additional data, like contents, tags, etc. 

**What you were expecting:**
React Admin should consider the sequence of network requests, and not overwrite the data returned from a later request OR the results from the `getList` shouldn't overwrite data returned from in the `getOne` that wasn't present in the `getList`

**Environment**

* React-admin version: 3.18.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by crousser** [comment]
I am using Datagrid to display the list. I display the detailed information of the record via expand-render (in my solution, the detailed information is the result of aggregation and / or extraction from related database collections). Displaying detailed information in a separate form (without displaying the parent Datagrid) is inconvenient for the user. At the same time, I, like the user @andrico1234 , do not quite understand - why the getList request goes later than the getOne request?
It seems to me that replacing the sequence of sent requests (i.e., first there should be getList and only then getOne for all expanded) when updating / rendering (Datagrid, etc.) - would solve the problem

**Comment by andrico1234** [comment]
Thanks @fzaninotto for the heads-up

@crousser , this should better illustrate the point I was trying to make. We don't fire the `getList` later than the `getOne`, but it may return after if the `getList` is particularly slow

![getlist drawio](https://user-images.githubusercontent.com/17087167/137091610-b4404f6c-fb1a-4f3b-bae8-75e62ce7ae0c.png)

**Comment by andrico1234** [comment]
For anyone interested in my solution I did the following:

```typescript
const ENDPOINT = 'fake-endpoint'; 

async function listShifts(params: GetListParams) {
  const source = axios.CancelToken.source();

  const shouldCancel = (clientConfig: AxiosRequestConfig): boolean => {
    const getOneRegordRegex = new RegExp("/records/[0-9]+?");
    const url = clientConfig.url ?? "";
    return getOneRecordRegex.test(url);
  };

  const disconnectInterceptor = interceptNetworkRequests(async clientConfig => {
    if (shouldCancel(clientConfig)) {
      disconnectInterceptor();
      source.cancel();
    }

    return clientConfig;
  });

  // we do a little rejigging inside of this network request helper and replace the error message for an aborted request with `ABORT` which we use a little later
  const { data, total } = await list(ENDPOINT, {
    params: queryParams,
    cancelToken: source.token,
  });

  disconnectInterceptor();

  return { data, total };
}
```

This worked a treat, except that RA displays a notification because it recognises an aborted request as a network error. I had to create a custom notification with the following logic to ensure that we don't display this notification:

```typescript
export const Notification: ComponentType<Props> = props => {
  const notification = useSelector(getNotification);
  const dispatch = useDispatch();

  const message = notification?.message ?? null;

  // This is related to aborting network requests
  // If we abort a request, then we don't want to show an error message
  useEffect(() => {
    if (message === null) return;

    if (message === "ABORT") {
      dispatch(hideNotification());
    }
  }, [message, dispatch]);

  return <RANotification {...props} autoHideDuration={10000} />;
};
```

I hope this help anyone who runs into a similar issue. Also, please let me know if there's an issue with my logic 😅
