### ISSUE TITLE
Consider the possibility to set emptyText to ArrayField or to it's children component

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#6661]
**Is your feature request related to a problem? Please describe.**

This request is a follow up of #6179.

Using the `empty` field of the `Datagrid` component is a solution. however, this field require only a react component.

This may be useful for some cases, but it is completely overkill if you just want to show a "It is empty" text just like other simple fields.

We may also use `empty={<span>It is empty</span>}`, however, we loose all the react-admin design of the Fields (`Typography` with specific config).

**Describe the solution you'd like**

Having a way to just put a `emptyText` props on a `ArrayField`, making the configuration much simpler:

```typescript
<ArrayField
  source="userDiscountCodes"
  label="Codes promos associés"
  emptyText="Aucun"
>
  <Datagrid empty={<TextField emptyText="Aucun." />}>
  </Datagrid>
</ArrayField>
```

Or, if the `ArrayField` usage is a problem, maybe on the `Datagrid` component itself (and any of the usable children):

```typescript
<ArrayField
  source="userDiscountCodes"
  label="Codes promos associés"
>
  <Datagrid emptyText="Aucun.">
  </Datagrid>
</ArrayField>
```

**Describe alternatives you've considered**

The only solution I found to get the exact same render with a minimal "code copy/paste" impact is this:

```typescript
<ArrayField
  source="userDiscountCodes"
  label="Codes promos associés"
>
  <Datagrid empty={<TextField emptyText="Aucun." />}>
  </Datagrid>
</ArrayField>
```

**Additional context**

A side note about the last change: the `emptyText` was reported as not used for the ArrayField. However, this option is still present on the TS definition. Is it a wanted behavior?

**Comment by fzaninotto** [comment]
This feature request hasn't received any attention from the community. As it's not on the roadmap of the core team, we're closing the GitHub issue.
