### ISSUE TITLE
DeleteButton not rendering properly in custom toolbar

### ISSUE THREAD

**Issue by aromeoes** [marmelab/react-admin#6675]
**What you were expecting:**
I was expecting to be able to configure a custom toolbar and use DeleteButton, CloneButton, and SaveButton from react-admin components

**What happened instead:**
CloneButton, and SaveButton work as expected

**Related code:**
```jsx
import * as React from 'react'
import { TextInput, SimpleForm, Edit, DateInput, NumberInput, Toolbar, SaveButton, CloneButton, DeleteButton } from "react-admin";

const CustomToolbar = props => (
    <div style={{marginBottom:16, marginLeft:16, marginRight:16}}>
        <SaveButton/>
        <CloneButton/>
        <DeleteButton/>
        
    </div>
)

export const SocioEdit = props => (
    <Edit title=" "  mutationMode="optimistic" {...props}>
        <SimpleForm toolbar={<CustomToolbar />}>
            <TextInput disabled source="status" />
            <TextInput disabled source="fecha_vigencia" />
            <TextInput source="nombre" />
            <TextInput source="apellido" />
            <TextInput source="documento" />
            <TextInput source="celular" />
            <TextInput source="nacimiento" />
            <TextInput source="email" />
            <TextInput disabled source="discount_string" />
            <TextInput disabled source="last_subscription_date" label="Alta" />
            <TextInput disabled source="sportaccess_id" />
        </SimpleForm>
    </Edit>
);
```

It doesn't print the DeleteButton within the toolbar as expected

**Comment by djhi** [comment]
Yes, you have to wrap them inside a `Toolbar` component as explained in the documentation. This component ensure they receive the props they expect. This is something that will be easier to customize in v4 as we're going to leverage contexts a lot more. Until then, you either have to use the `Toolbar` component or check the buttons source code to see what prop they expect.
