### ISSUE TITLE
all[Entities] queryrequest for the list doesnt incude the properties of nested types.

### ISSUE THREAD

**Issue by yaswanthpflegia** [marmelab/react-admin#6691]
**What you were expecting:**
I have recently started using react-admin in our application with backend that supports Graphql.
   <TextField source='geoLocation.formattedAddress' label='Address' />
expected to get the data from the geolocation Type.

type GeoLocation {
  description: String
  formattedAddress: String
  id: ID!
  location: GeoJSONPoint!
  name: String
}

type Employer{
geoLocation:GeoLocation
}

allEmployers: [Employer!]!

**What happened instead:**
but the query in the network tab (checkd in browser) doesn't incude "formattedAddress" at all.All i can see is only Id
![image](https://user-images.githubusercontent.com/84310897/137505166-04f34ddf-1d84-4285-ada4-bd8e07f6c0a8.png)

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:3.18.3
* Last version that did not exhibit the issue (if applicable):
* React version:"^17.0.2",
* Browser:chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Can you try upgrading to 3.19.0 ? We fixed many gql issues in addition to upgrading to the latest apollo

**Comment by wand2016** [comment]
still happens in 4.0.2

**Comment by wand2016** [comment]
@yaswanthpflegia 

If you define any CRUD Operation for `GeoLocation` type (e.g. `GeoLocation(id: ID!)`, `allGeoLocations()`, `deleteGeoLocation(id: ID!)`, etc.), the `GeoLocation` type is treated as `linkedResource`: 

https://github.com/marmelab/react-admin/blob/14b2544534501234eae764f3ac63a7cae907245f/packages/ra-data-graphql/src/introspection.ts#L123-L129

https://github.com/marmelab/react-admin/blob/14b2544534501234eae764f3ac63a7cae907245f/packages/ra-data-graphql/src/index.ts#L60-L68

And queries for `linkedResource` s include only `id` field.

https://github.com/marmelab/react-admin/blob/14b2544534501234eae764f3ac63a7cae907245f/packages/ra-data-graphql-simple/src/buildGqlQuery.ts#L120-L135

If you want to include the other fields, there are some options:

- Delete all CRUD operations for `GeoLocation` type, then the type is treated as `linkedType`.
- Exclude `Geolocation` type in introspection option:

```ts
  buildGraphQLProvider({
    introspection: {
      exclude: ['GeoLocation'],
    }
  });
```

https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql-simple#customize-the-introspection

have a nice day.

**Comment by yaswanthpflegia** [comment]
@wand2016 Thanks for your reply,but this doesnt work if any of the relations are already a resources

**Comment by slax57** [comment]
This is actually the expected behaviour.
`ra-data-graphql-simple` only brings back the `id` by default, because it is sufficient to handle relations (with ReferenceField for example), and otherwise bringing back all fields might cause cyclic relationship problems.
If you want to bring back other fields, you need to list them explicitly in a custom query.
