### ISSUE TITLE
[4.0.0-alpha.1] Demo: Checkboxes are not align correctly in Reviews view

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6698]
![103612](https://user-images.githubusercontent.com/8268610/137742809-2dabe7e6-6815-429e-b116-0b452af031ca.png)

**Comment by WiXSL** [comment]
> I think that this issue is already been resolved. Here's a screen shot of the master branch.
>
No, this is from `next` branch which is version 4, master is version 3, and doesn't have that problem

**Comment by oguhpereira** [comment]
I didn't find any listings with this problem. 

I'm on the next branch, and some listings have a problem. Is there already a fix for this?

![image](https://user-images.githubusercontent.com/24482087/142398607-e603af6a-8613-4e58-850f-49bba87e4675.png)

i can help with this issue when it is resolved.

**Comment by fzaninotto** [comment]
@oguhpereira Can you please open a new issue with a repro for this "something went wrong" bug?
