### ISSUE TITLE
[4.0.0-alpha.1] Notify component appears at the bottom left of the canvas

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6699]
![test](https://user-images.githubusercontent.com/8268610/137744176-3c371a9b-ee03-4d56-9874-8c2406c70ee8.png)

**Comment by oguhpereira** [comment]
Well, the material-ui has a property to configure which position the snackbar should be displayed.

Now it would be interesting to understand whether you need to keep this fixed or dynamic.

![image](https://user-images.githubusercontent.com/24482087/142301400-79d7dc08-9465-4f8e-b0e1-0aee72780ca2.png)

**Comment by WiXSL** [comment]
Fixed by #6878
