### ISSUE TITLE
Attempted import error: 'createTheme' is not exported from '@material-ui/core/styles'.

### ISSUE THREAD

**Issue by hieudn2012** [marmelab/react-admin#6705]
<img width="657" alt="Screen Shot 2021-10-19 at 5 19 46 PM" src="https://user-images.githubusercontent.com/51831671/137891313-da5bc11e-c3cd-4682-b57c-bb4fd533016e.png">

**Comment by luoenzhen** [comment]
Same issue here.

**Comment by kimchirice** [comment]
I change the the import to below then the compile was successful.
````javascript
import { createTheme } from "@mui/material/styles";
````

**Comment by ENGR-MANSOOR** [comment]
Same issue while dockerizing the app

**Comment by janlin002** [comment]
Same issue here.

**Comment by fzaninotto** [comment]
If you have this bug, please open a new issue following the issue template - this allows us to reproduce the bug. Without reproduction, your comments are useless. 

Locking this issue to avoid noise.
