### ISSUE TITLE
initialValue overwrites non-null & non-undefined values

### ISSUE THREAD

**Issue by hvqzao** [marmelab/react-admin#6708]
**What you were expecting:**

According to React Admin docs, `initialValue` is a `Value to be set when the property is null or undefined` (reference: https://marmelab.com/react-admin/Inputs.html)

**What happened instead:**

After upgrade RA from 3.17.2 to 3.19.0:
if initialValue is used on Inputs (confirmed with `AutocompleteInput`) which are rendered on both Edit and Create forms behavior is now changed: if we are editing entry and input value is not null nor undefined, current value is still overwritten by initialValue.

To temporarily address the issue I had to replace
`initialValue={default}`
with
`initialValue={create ? default : undefined}`

At least for me impact was serious, causing a lot of data to be overwritten for every "touched" data entry.

**Steps to reproduce:**

**Related code:**

```
<Edit {...props}>
  <SimpleForm>
     <AutocompleteInput source="field" initialValue={"overwrite"}>
  </SimpleForm>
</Edit>
```

**Other information:**

**Environment**

* React-admin version: 3.19.0
* Last version that did not exhibit the issue (if applicable): 3.17.2
* React version: 17.0.2
* Browser: Chrome (latest)
* Stack trace (in case of a JS error): N/A

**Comment by WiXSL** [comment]
@djhi, could this be closed?

**Comment by djhi** [comment]
Yes it should be
