### ISSUE TITLE
fetchJson Error status undefined instead of 401

### ISSUE THREAD

**Issue by AbdelrahmanKhaledAmer** [marmelab/react-admin#6710]
**Problem**
I have a custom dataProvider that I'm calling using the `useDataProvider()` hook (called in the dashboard). When making requests with a false/expired token, it calls the `checkError` function, but the response status is always `undefined` instead of 401.

**What you were expecting:**
Error status should be a HTTP status code (number).

**What happened instead:**
Error status is `undefined`.

**Steps to reproduce:**
Here's how my project currently looks like. I don't know if all these steps are necessary, but will add them just in case.
1. Make a react-admin app
2. modify checkError to print error status code
3. Use two or more dataProviders (using a composite Data Provider)
4. Make a dashboard page
5. Access the custom dataProvider via `useDataProvider()` hook and use one (or more) of it's functions while having a false token

**Related code:**
Adding a code snippet for the custom dataProvider in case there's something I'm missing there.
**`customDataProvider.js`**
```js
import { fetchUtils } from "ra-core";

const customDataProvider = (apiUrl, httpClient = fetchUtils.fetchJson) => ({
  /*...*/
  getOne: (resource, params) => {
    const url = `api/url/endpoint?${params}`;
    return httpClient(url).then(({ json }) => {
      return { data: json };
    });
  },
  /*...*/
});

export default customDataProvider;
```

**Other information:**
None

**Environment**

* React-admin version: **3.16.0**
* Last version that did not exhibit the issue (if applicable): **N/A**
* React version: **17.0.2**
* Browser: Microsoft Edge
* Stack trace (in case of a JS error): **N/A**

**Comment by AbdelrahmanKhaledAmer** [comment]
It's been over a week, and I'm afraid the issue might get stale and ignored, so I'm adding a comment to make sure this issue stays relevant.

Also can we please remove the `needs more info` label considering I provided a minimal recreation of the bug?

**Comment by djhi** [comment]
Regarding the codesandbox, it works fine if you change the url from `http://httpstat.us/` to `https://httpstat.us/` (note the `https`). You had an error about [mixed content](https://www.howtogeek.com/443032/what-is-mixed-content-and-why-is-chrome-blocking-it/). This has nothing to do with react-admin.

**Comment by AbdelrahmanKhaledAmer** [comment]
That doesn't make sense. I use another data provider with `http` (not `https`) for a resource component, and it works fine. It detects the error status and logs out. It only fails to detect the error status when I use it on the dashboard with `useDataProvider()` hook.

We use `https` for everything on production, but locally we test with only `http`, so as far as I can tell there's no mixed content issue.

**Comment by djhi** [comment]
That's what happen on the codesandbox at least and you can verify it by yourself in the network tab

**Comment by AbdelrahmanKhaledAmer** [comment]
Yes, I can verify that it happens on the codesandbox, but I'm unsure if that's the issue.

Like I said, locally in our project everything is `http` and it works fine for a resource component, but fails on the dashboard. These attached screenshots should show that there seems to be a problem

Screenshot 1: dashboard uses the `useDataProvider()` hook to make an api call to retrieve some analytics data. The response is 401, but nothing happens (stays in the dashboard because error status is not detected). You can see the network tab here. I blacked out anything that can be considered sensitive information, but left all the necessary data to show that it uses `http` and the response is 401.
![Screenshot 2021-11-03 at 14 57 13](https://user-images.githubusercontent.com/25390378/140075387-0f31f812-12c6-4e81-9ef1-89fb8ef951f5.png)

Screenshot 2: upon clicking on the users tab in the dashboard, I am taken to a `ListView` component that uses a regular dataProvider to retrieve a list of users. Again I blacked out sensitive data, but as you can see the request is still using `http` and the response is still 401, but this time I was logged out (as intended).
![Screenshot 2021-11-03 at 14 57 58](https://user-images.githubusercontent.com/25390378/140076071-940d4716-a883-43b9-9748-4f35ab7c1497.png)

So, it doesn't seem to be a mixed content issue in this case.

**Comment by djhi** [comment]
Then I need a way to reproduce the issue.
