### ISSUE TITLE
ra-data-graphql-simple - typescript template + buildQuery question

### ISSUE THREAD

**Issue by stefanburt** [marmelab/react-admin#6712]
Hello React Admin,

I'm building a new project using RA and ra-data-graphql-simple and our codebase is built using typescript. I was wondering if the recently updated ra-data-graphql-simple supports TS?

I'm following https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql-simple#usage but this is the non TS implementation I was wondering if there is documentation to support the recent update.

Many thanks for any assistance

Stefan

We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(https://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.

**Comment by djhi** [comment]
Hi and thanks for reporting this. The `buildQuery` function should indeed be optional in `ra-data-graphql-simple`. Can you make a PR?
