### ISSUE TITLE
Reference input Autocomplete within ArrayInput and FormDataConsumer isn't working since 3.19.0

### ISSUE THREAD

**Issue by groomain** [marmelab/react-admin#6715]
**What you were expecting:**
Hi !
Since 3.19.0 version my autocomplete isn't working anymore.
I should be able to search in an autocomplete input within a reference input and a form data consumer.

**What happened instead:**
The dropdown open but I can't type in the input.

**Steps to reproduce:**
Create an autocomplete input with a form data consumer.

**Related code:**
```
import {
  ReferenceInput,
  AutocompleteInput,
  useTranslate,
  ArrayInput,
  SimpleFormIterator,
  FormDataConsumer,
} from "react-admin";
import Box from "@material-ui/core/Box";
import Accordion from "@material-ui/core/Accordion";
import AccordionSummary from "@material-ui/core/AccordionSummary";
import AccordionDetails from "@material-ui/core/AccordionDetails";
import Typography from "@material-ui/core/Typography";
import ExpandMoreIcon from "@material-ui/icons/ExpandMore";

const Form = () => {
  const t = useTranslate();

  return (
    <ArrayInput
      source="allowedServiceProviders"
      label={t("company")}
    >
      <SimpleFormIterator>
        <FormDataConsumer>
          {({ getSource, scopedFormData }) => {
            return (
              <Accordion>
                <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                  <Typography>title</Typography>
                </AccordionSummary>
                <AccordionDetails>
                  <Box>
                    <ReferenceInput
                      label={t("select")}
                      source={getSource("serviceProvider.id")}
                      reference="ServiceProvider"
                      record={scopedFormData}
                    >
                      <AutocompleteInput
                        optionText={(serviceProvider) =>
                          `${serviceProvider?.averageDailyRate} €`
                        }
                      />
                    </ReferenceInput>
                  </Box>
                </AccordionDetails>
              </Accordion>
            );
          }}
        </FormDataConsumer>
      </SimpleFormIterator>
    </ArrayInput>
  );
};
```

**Other information:**
There is no bug in the console I only lose the focus when I try to type in it. Everything work when I use it without the FormDataConsumer.

**Environment**

* React-admin version: 3.19.0
* Last version that did not exhibit the issue (if applicable): 3.18.0
* React version: 17.0.0
* Browser: Chrome 94
* Stack trace (in case of a JS error): ---
<img width="773" alt="Capture d’écran 2021-10-21 à 08 06 01" src="https://user-images.githubusercontent.com/3601848/138229829-0f19a081-8b7c-439c-bcb7-c58cba253e24.png">

**Comment by instantlinux** [comment]
I see this stacktrace when using my custom render function:
```
react_devtools_backend.js:2528 TypeError: Cannot read properties of null (reading 'name')
    at Zt (event.js:336)
    at AutocompleteInput.js:173
    at Object.useMemo (react-dom.production.min.js:172)
    at t.useMemo (react.production.min.js:23)
    at I (AutocompleteInput.js:163)
    at sa (react-dom.production.min.js:157)
    at Zs (react-dom.production.min.js:267)
    at Tu (react-dom.production.min.js:250)
    at ku (react-dom.production.min.js:250)
    at Pu (react-dom.production.min.js:250)
```
This was working prior to `3.19.0`.

**Comment by djhi** [comment]
Hi, I'm unable to reproduce this issue. Can you please provide a codesandbox?

**Comment by dulguuned** [comment]
<img width="784" alt="Screen Shot 2021-12-10 at 18 29 57" src="https://user-images.githubusercontent.com/10085623/145559768-aabd15cc-6e87-4e38-a0ff-c7a1d218675e.png">

can't type in AutocompleteInput. What should i do?

**Comment by andrico1234** [comment]
Hi @djhi ,

I've come across this issue too,

here's a recreation of the problem. Clicking the AutocompleteInput is very glitchy. I also managed to recreate  this in a different way by using the `useFormData` hook. It looks clicking the input causes it to rerender multiple times, which can cause the choices list to hide as soon as it's rendered.

**Comment by andrico1234** [comment]
I did some digging, and it looks like the first bad commit is: `166ddf4e09d0fb04f4d499e2a16655a3de0922e4`.

After doing some tweaking, removing the `inputEl.current.blur();` on line 327 prevents the problem from happening

**Comment by nicgirault** [comment]
@djhi  Not sure if this is related but here is a fork of the bug report code sandbox with no change: https://codesandbox.io/s/restless-leaf-bh5mv?file=/src/posts/TagReferenceInput.tsx. You can see that when creating a new tag, the choice list does not close and is not closable.

https://user-images.githubusercontent.com/551837/146556564-355ef50e-e38c-4272-8e39-c7ff12b973a8.mov

**Comment by fzaninotto** [comment]
Thanks for the repro, it is indeed a serious regression. We're working on a fix.
