### ISSUE TITLE
Breadcrumbs using ra-navigation

### ISSUE THREAD

**Issue by mohamad-elbohsaly** [marmelab/react-admin#6716]
Dear concerned,

Upon installing ra-navigation through npm install --save @react-admin/ra-navigation, I get the following error
<img width="790" alt="Screen Shot 2021-10-21 at 12 55 13 PM" src="https://user-images.githubusercontent.com/18421260/138255191-c144f359-0422-42fc-9f11-02125c224cc4.png">
:

**Comment by djhi** [comment]
`ra-navigation` is an enterprise package? Do you have a subscription?
