### ISSUE TITLE
SimpleFormIterator ReOrder function not properly working with RichTextInput

### ISSUE THREAD

**Issue by michelnyx** [marmelab/react-admin#6722]
**What you were expecting:**
ReOrder of SimpleFormIterator properly working with RichTextInput.

**What happened instead:**
ReOrder on new items with RichTextInput on SimpleFormIterator moves only title.

**Steps to reproduce:**
Open a row from react-admin grid engine, add items to SimpleFormIterator with RichTextInput and move up / down, then only the "Key" with TextInput moves correctly (RichTextInput remains static).

It will work if the row already was saved.

**Related NOT WORKING code:**

```
        <ArrayInput source="src">
            <SimpleFormIterator>
                <TextInput source={"key"} />
                <RichTextInput source={"value"} toolbar={toolbarOptions} />
            </SimpleFormIterator>
        </ArrayInput>
```

**Related WORKING code:**

```
        <ArrayInput source="src">
            <SimpleFormIterator>
                <TextInput source={"key"} />
                <TextInput source={"value"} />
            </SimpleFormIterator>
        </ArrayInput>
```

**Environment**

* React-admin version: 3.19.0
* Last version that did not exhibit the issue (if applicable): No
* React version: 17
* Browser: Latest Chrome 
* Stack trace (in case of a JS error): No

**Comment by WiXSL** [comment]
Reproduced. Thanks

**Comment by WiXSL** [comment]
Update:
Believe it or not, it has to be with the `CSSTransition` component we use. If I remove it, the reorder works correctly.
