### ISSUE TITLE
Prefil create form does not work if the create form has once rendered without prefilled values

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#6738]
Following this example: https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record (with the link)
There is a list that has a custom button that opens a create view from another resource.

Now when the user clicks on this custom button, the CreateForm is correctly filled. 
But if the same CreateForm has once rendered without any value, this no longer works. 

This situation also happens when the the user presses browser back button after submiting a create form. This will render an empty form

**What you were expecting:**

CreateForm is always prefilled when setting the state

**What happened instead:**

When a CreateForm has been rendered with an empty state, it can no longer be filled

**Steps to reproduce:**

See description above. 

**Related code:**

i tried to setup the code sandbox, but it does not work 

```
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'proxy-polyfill/proxy.min.js' in '/sandbox/src'
 @ ./src/polyfills.ts 5:0-38
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8080 (webpack)/hot/dev-server.js ./src/polyfills.ts
```

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.19.0
* Last version that did not exhibit the issue (if applicable): unknown
* React version: 17.0.2
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by macrozone** [comment]
there is something wrong with the history and location.

Compare the values for history.location and location (screen shot taken from react-dev-tools):

a) When it works correctly:

<img width="426" alt="Bildschirmfoto 2021-10-31 um 14 40 29" src="https://user-images.githubusercontent.com/1972353/139586513-379a9735-ea6a-4a44-ab8f-55c2edd85de0.png">

as you can see, both history.location and location have the same state (the passed one)


b) when it no longer works:

<img width="438" alt="Bildschirmfoto 2021-10-31 um 14 41 17" src="https://user-images.githubusercontent.com/1972353/139586532-6ec554d3-a746-46c9-83cf-365040237599.png">


here `location.state` is undefined, but `history.location.state` is correct.

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by boorad** [comment]
@macrozone Did you ever solve this?  I'm seeing it currently.

**Comment by fzaninotto** [comment]
No news for some time, closing.
