### ISSUE TITLE
Error in dependency package "ra-ui-materialui" used by react-admin

### ISSUE THREAD

**Issue by rohan-techahead** [marmelab/react-admin#6741]
Hi Team,
I am currently facing a issue which appears to be appearing from one of the dependent package used by react-admin which is "ra-ui-materialui".

It says **"./node_modules/ra-ui-materialui/esm/layout/DeviceTestWrapper.js Attempted import error: 'createTheme' is not exported from '@material-ui/core/styles' ".**
I am using "react-admin": "^3.17.0".

Following are the some of the package version which I m using.
   
` "@material-ui/core": "4.11.4",`
   ` "@types/react": "^16.14.11",`
   ` "react-admin": "^3.17.0".`
    `"react": "^16.13.1",`
    `"typescript": "~3.8",`

Step to reproduce the error
`npx create-react-app test`
`npm i react-admin`
`npm i @material-ui@4.11.4`

Now in app.js simple add 
`import  {Admin} from "react-admin"`

Done, Code is broken

![Capture1](https://user-images.githubusercontent.com/80825511/139805162-da413071-1a0c-41d1-904d-f414c68af9de.PNG)
![pic1](https://user-images.githubusercontent.com/80825511/139805165-15890f9c-4752-4794-8dc7-0edab99e5fd0.PNG)

I had raised the issue before #6728 it is closed without resolved.
I upgraded to "react-admin": "^3.19.0", still getting the same error.

**Comment by djhi** [comment]
Please don't reopen issue. As explained in the previous one, I'm unable to reproduce it by following those steps.
