### ISSUE TITLE
return Promise.reject() in chechAuth don't make route direct to /login page

### ISSUE THREAD

**Issue by raunyuyuan** [marmelab/react-admin#6744]
why do you write the below code in the ra-core/esm/auth/useAuthState.ts ?

`useEffect(() => {
        checkAuth(params, false)
            .then(() =>
                setState({ loading: false, loaded: true, authenticated: true })
            )
            .catch(() =>
                setState({ loading: false, loaded: true, authenticated: false })
            );
    }, [checkAuth, params, setState]);`

when the second param of checkAuth is valued by a false, it never redirects to the login page when authorization faile.

I am using last version of your farmwark

**Comment by djhi** [comment]
This is explained in the [documentation](https://marmelab.com/react-admin/Authentication.html#useauthstate-hook). That's the difference between `useAuthState` and `useAuthenticated`.

**Comment by raunyuyuan** [comment]
@djhi 

yeah, but my code looks like below, it comes without hooks:
```
<Admin title="markManagement" dataProvider={dataProvider} authProvider={AuthProvider}>
      <Resource name="list" options={{ label: 'Posts' }} ></Resource>
    </Admin>
```

And in your document [checking-credentials-during-navigation](https://marmelab.com/react-admin/Authentication.html#checking-credentials-during-navigation), it say:

> Fortunately, each time the user navigates to a list, edit, create or show page, react-admin calls the authProvider.checkAuth() method. If this method returns a rejected Promise, react-admin calls authProvider.logout() and redirects the user to the login page. So it’s the ideal place to make sure the credentials are still valid.


It looks like means when I route to list and` checkAuth` method return `Promise.reject()', it will logout and redirect to the login page. But the above behavior doesn't really happen.

**Comment by raunyuyuan** [comment]
Have I misunderstood anything?
@djhi

**Comment by fzaninotto** [comment]
If you have identified a bug, please follow the issue template and provide a reproducible test case.
