### ISSUE TITLE
Unable to copy the error message in clipboard

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#6749]
**What you were expecting:**

I expect the error message to be copyable in the clipboard.

![image](https://user-images.githubusercontent.com/551837/140480134-5697c857-b012-4517-b943-4d19c76b5da9.png)

**What happened instead:**

When I start selecting the error message, it toggles the accordion.

**Related code:**

https://codesandbox.io/s/confident-sanderson-o4igs?file=/src/posts/PostList.tsx

**Environment**

* React-admin version: 3.19.0
* React version: 17.0.0
* Browser: Chrome 95

**Comment by djhi** [comment]
That's the way the Accordion works in mui. We should probably display the error message as a simple Typography and set the `AccordionSummary` title to something like `Error stack`
