### ISSUE TITLE
Progress Indicator/Refresh button spins constantly on checkError reject with logoutUser: false

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#6750]
Once rejected with the refresh button spins until page refresh.

![Screen Shot 2021-11-05 at 10 31 28 AM](https://user-images.githubusercontent.com/15056748/140536485-a6f05f54-fbcf-4ae2-960b-6875126d83a2.png)

```js
checkError: (error: any) => {
    const status = error.status;
    if (status === 401 || status === 403) {
      if (status === 401)
      {
        localStorage.removeItem('auth');
        localStorage.removeItem('permissions');
        return Promise.reject();
      }

      return Promise.reject({ redirectTo: '/', logoutUser: false });
    }
    return Promise.resolve();
  }
```

**Comment by djhi** [comment]
Please follow the issue template

**Comment by davidhenley** [comment]
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/sideEffect/auth.ts

handleCheck or handleFetchError is not resetting admin loading state to false.

**Comment by fzaninotto** [comment]
Reproduced: https://codesandbox.io/s/funny-clarke-4ve7h?file=/src/dataProvider.tsx

I'm marking this as a bug.
