### ISSUE TITLE
`List` permanent filter doesn't change if initial filter is set and new filters have same keys

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6752]
https://codesandbox.io/s/reverent-euclid-09q8d?file=/src/posts/PostList.tsx

1. Go to Posts `List` and click on `Filter By Id = 2` button. ( It will filter the List showing record of id = 2)
2. Uncomment PostList.tsx line 37 to set an initial filter and save. (Reload the entire sandbox for the changes to take effect)
3. Now the `List` will load with one record ( id = 1 )
4. Click on `Filter By Id = 2` button.

Expected: It should load record with id = 2

Result: Nothing happens

Possible fix:
I believe this is because the  filter is incorrectly merged inside `useListController` hook:

https://github.com/marmelab/react-admin/blob/ac9913393b28298acf3864cd73c70fd6f3acd985/packages/ra-core/src/controller/useListController.ts#L167

And returned here:

https://github.com/marmelab/react-admin/blob/ac9913393b28298acf3864cd73c70fd6f3acd985/packages/ra-core/src/controller/useListController.ts#L225

**Comment by djhi** [comment]
It's by design, permanent filters cannot be overriden. See https://marmelab.com/react-admin/List.html#filter-permanent-filter
