### ISSUE TITLE
noLayout mounts the component twice

### ISSUE THREAD

**Issue by anniestudent** [marmelab/react-admin#6756]
I have a component Map in a noLayout custom route. The console.log I put into the did mount useEffect hook printed out twice. If I remove the noLayout prop, the Map component only mount once.

**What you were expecting:**
The component mounts once.

**What happened instead:**
The component mounted twice. According to the console.log I put in the did mount useEffect hook, it first mounted, and then unmounted, and then mounted again.

**Related code:**
```
// customeRoutes.js
import * as React from "react";
import { Route } from 'react-router-dom';
import Map from './Map';


export default [
  <Route exact path="/map" component={Map} noLayout />,
];

// MyLayout.js

import { Layout } from 'react-admin';
import MyMenu from './MyMenu';
import * as React from 'react';

const MyLayout = (props) => <Layout {...props} menu={MyMenu} />;

export default MyLayout;

// App.js

import * as React from "react";
import { Admin, Resource } from 'react-admin';

import dataProvider from './dataProvider';
import MyLayout from './MyLayout';
import customRoutes from './customRoutes'
import authProvider from './authProvider';
import { createTheme } from '@material-ui/core/styles';
import MyLoginPage from './MyLoginPage'

// https://github.com/marmelab/react-admin/issues/3903#issuecomment-586652345
import polyglotI18nProvider from "ra-i18n-polyglot";
import englishMessages from "ra-language-english";

const messages = {
  en: englishMessages
};

const i18nProvider = polyglotI18nProvider(locale => messages[locale], "en", {
  allowMissing: true
});

const theme = createTheme({ ... });

export default function App() {
  return (
    <Admin
      theme={theme}
      loginPage={MyLoginPage}
      customRoutes={customRoutes}
      layout={MyLayout}
      dataProvider={dataProvider}
      authProvider={authProvider}
      i18nProvider={i18nProvider}>
      {
        permissions => [
           ...
        ]
      }
    </Admin>
  )
}

// Map.js

import React, { useEffect } from 'react'

const Map = (props) => {
  useEffect(() => {
    console.log('did mount')
    return () => console.log('unmount')
  }, [])

  return (
    <div>
    </div>
  )
}

export default Map
```

**Environment**

* React-admin version: 3.7.2
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.14.0
* Browser: Chrome
* Stack trace (in case of a JS error): N/A

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by yitzgold** [comment]
I am running into the same issue on v3.19.11, and it doesn't help to use the `RouteWithoutLayout` wrapper.

**Comment by slax57** [comment]
@yitzgold Same answer: we need a reproduction to be able to work on the issue.
You can build one by forking the simple example in v3: https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple
