### ISSUE TITLE
TypeError: cyclic object value when using TextField from aside component

### ISSUE THREAD

**Issue by shreyas-jadhav** [marmelab/react-admin#6757]
**What you were expecting:**
Material UIs `TextField`, `Input`, `<input` elements should work from the aside component passed to a `List`.
i was using just to update a local `useState`  value

**What happened instead:**
Input element renders correctly, but when it is focused a error is thrown not sure why.
It says `TypeError: cyclic object value`

**Steps to reproduce:**
Use material UIs `<TextField />` / `<Input />` or `<input />` inside the `aside` component which is passed to ListView of any resource.

**Related code:**
```ts
<TextField
    type="number"
    defaultValue={distance}
    onChange={(e) => setDistance(Number(e.target.value))}
    helperText="Meters"                    
/>
```

**Other information:**
```
TypeError: cyclic object value

./node_modules/ra-ui-materialui/esm/list/datagrid/Datagrid.js/Datagrid<@http://localhost:1234/static/js/vendors~main.chunk.js:337991:84
div
Paper@http://localhost:1234/static/js/vendors~main.chunk.js:21351:17
WithStyles@http://localhost:1234/static/js/vendors~main.chunk.js:194113:25
Card@http://localhost:1234/static/js/vendors~main.chunk.js:5480:17
WithStyles@http://localhost:1234/static/js/vendors~main.chunk.js:194113:25
div
div
ListView@http://localhost:1234/static/js/vendors~main.chunk.js:337069:17
ListContextProvider@http://localhost:1234/static/js/vendors~main.chunk.js:289040:15
List@http://localhost:1234/static/js/vendors~main.chunk.js:336609:79
SpeakerList
WithPermissions@http://localhost:1234/static/js/vendors~main.chunk.js:287377:20
```

**Environment**

"react-admin": "^3.18.3",
* React version: 17.0.2
* Browser: firefox

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
No news for some time, closing.
