### ISSUE TITLE
Can't call notify function without `type` argument 

### ISSUE THREAD

**Issue by nidebo** [marmelab/react-admin#6767]
**What you were expecting:**
Be able to not pass optional argument `type` to `useNotify` returned function

**What happened instead:**
Code breaks because destructuring `undefined` throws an error.

**Steps to reproduce:**
```
const notify = useNotify();
notify();
```

**Environment**

* React-admin version: 3.19.0 and I think will happen on 3.19.1 too.

**Comment by WiXSL** [comment]
Yes, It's been fixed in #6713.

**Comment by nidebo** [comment]
opened #6768
