### ISSUE TITLE
useNotify hook deprecation warning does not match documention

### ISSUE THREAD

**Issue by wattry** [marmelab/react-admin#6769]
The notify callback was signature updated and a deprecation warning was added. However, the documentation does not warn developers and has several examples with the old method.

Located [here ](https://marmelab.com/react-admin/Actions.html#usenotify)
 
The documentation states:  

```
// notify a warning
notify(`This is a warning`, 'warning');
// pass translation arguments
notify('item.created', 'info', { resource: 'post' });
// send an undoable notification
notify('Element updated', 'info', undefined, true);
Tip: The callback also allows a signature with only 2 arguments, the message to display and an object with the rest of the arguments

// notify an undoable success message, with translation arguments
notify('Element deleted', {
    type: 'success',
    undoable: true,
    messageArgs: { resource: 'post' }
});
```

Resulting in all of our notification calls logging: 

```This way of calling useNotify callback is deprecated. Please use the new syntax passing notify("[Your message]", { ... restOfArguments })```

Should the documentation possibly be updated to include the deprecation warning for the first examples and add all of the properties that restOfArguments has i.e.?

```
   // info, success, warning, error
   type: string
    // The duration in milliseconds the notification is shown
    autoHideDuration?: number;
    // Arguments used to translate the message
    messageArgs?: any;
    // If true, the notification shows the message in multiple lines
    multiLine?: boolean;
    // If true, the notification shows an Undo button
    undoable?: boolean;
```

**Environment**

* React-admin version: 3.19.0

**Comment by djhi** [comment]
Fixed by #6760
