### ISSUE TITLE
Url changes but page does not load new content until manual browser reload

### ISSUE THREAD

**Issue by jashwant** [marmelab/react-admin#6770]
**What you were expecting:**

When clicking on a record or a sidebar menu item, it should redirect to relevant page every-time.

**What happened instead:**

When I click on dashboard, sometimes it becomes unresponsive and does nothing but change the url of the page.
Sidebar menu to open different resources does not work. Clicking on a record row, does not open up the record's edit page. 

**Steps to reproduce:**

<strike>It happens randomly. I couldn't find a direct way to reproduce it. But it happens often after I use the dashboard couple of times.</strike>
**Edit**
Issue occurs when I click on browser's back button to go back to previous page.

**Related code:**

I think issue is occurring because I am using the history like below instead of default hash route. I would prefer to use it like this instead of hash.

```javascript
import { createBrowserHistory } from "history";
<Admin
 
      history={createBrowserHistory({
        basename: "admin",
      })}
  
    >
...
</Admin>
````

**Environment**

* React-admin version: "react-admin": "^3.19.0",
* React version: ^17.0.2"
* Browser: Chrome 95.0.4638.69 and firefox 94.0.1 (64-bit)
* Stack trace (in case of a JS error): There's no javascript error in console.

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by jashwant** [comment]
@djhi 

Here's the link: (I created a separate file dashboard.tsx for react admin and installed react-router-dom for history)
https://codesandbox.io/s/blissful-hopper-q7fbo?file=/src/index.tsx. 

I now realised that it is probably caused by 2 browser histories I am using.
When I click on back/forward button, it pops /dashboard history out. And react-admin doesn't work anymore as it reacts to /dashboard history.

I have read [adding react-admin in existing app](https://marmelab.com/react-admin/CustomApp.html), but I am not sure how it will work in my situation. I am not even using redux in my app.

**Comment by jashwant** [comment]
Found the solution.

I was creating history inside Dashboard component.

````javascript
const App = () => {
  return (
    <>
      <Switch>
        <Route path="/dashboard" component={Dashboard} />
      </Switch>
    </>
  );
};

const Dashboard = () => {
  return (
    <Admin
      ...
      history={createBrowserHistory({
        basename: "dashboard"
      })}
    >
      {(permissions) => (
           <Resource name="posts" {...posts} />
      )}
    </Admin>
  );
};
````
 
When I was hitting back/forward button, App was re-rendering the Dashboard component and thus re-initialising and clearing the history of Admin. So, I moved `createBrowserHistory` outside of Dashboard component.

````javascript
const history = createBrowserHistory({
  basename: "dashboard"
})};

const Dashboard = () => {
  return (
    <Admin
      ...
      history={history}
    >
      {(permissions) => (
           <Resource name="posts" {...posts} />
      )}
    </Admin>
  );
};
````

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###

**Comment by GrantRynders** [comment]
###marmelabTimeLog###
