### ISSUE TITLE
App menu item link primaryText not hiding on sidebar close

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#6773]
![menuOverride](https://user-images.githubusercontent.com/43347643/141351458-2f6dce63-dea5-4577-a2e4-cf76317d917b.png)

**What you were expecting:**
Menu item labels /  primaryText hides when sidebar menu is closed

**What happened instead:**
As seen in attached picture, the label persist on sidebar close, and overrun the FilterMenu and action buttons.

**Steps to reproduce:**
Tried to replicate in codeSandbox, but the app is failing to compile. In my case, merely updating from 3.17 to 3.19 was enough to create the issue. I am using a MenuItemLink / SubMenu scheme very similar to the source code for the main demo application.

**Environment**
* React-admin version: 3.19.0
* Last version that did not exhibit the issue (if applicable): 3.17
* React version: 16.12.0
* Browser: Chrome

**Comment by ZachSelindh** [comment]
As an addendum: if I manually style the element "RaSidebar-fixed" in Chrome dev tools, toggling "position: fixed" on and off hides the menu item primaryText as I would expect while "off."

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple). A fork should work fine now

**Comment by ZachSelindh** [comment]
Thank you for your attention to this issue! My fork displaying the problem is found here:

https://codesandbox.io/s/nice-glade-jq2bc?file=/src/Layout/MainMenu/index.tsx

As you can see, when providing a custom menu to the Layout component, collapsing the menu does not hide the MenuItem text.

**Comment by ZachSelindh** [comment]
This appears to have been fixed with 3.19.1, thanks for the update!
