### ISSUE TITLE
[GraphQL] What is the content of "buildFieldList" mentioned in README.md?

### ISSUE THREAD

**Issue by chiu0602** [marmelab/react-admin#6775]
In file `react-admin/packages/ra-data-graphql/README.md`, file `buildFieldList` is mentioned with no content suggested, please help.

**Comment by djhi** [comment]
You can refer to the `ra-data-graphql-simple` for an implementation example. Basically, `ra-data-graphql` just run the introspection query and act as a layer between your queries and Apollo.

In this example, the `buildFieldList` is called with the resource name and the introspection result. It should return the list of fields for the resource by analysing the introspection query.
