### ISSUE TITLE
ReferenceArrayInputs are stuck in loading state prior to receiving choice options if using enableGetChoices

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#6776]
![referenceArrayInputs](https://user-images.githubusercontent.com/43347643/141503699-41fa87cb-c1e6-4aef-ae18-b4e353dfbec0.png)
**What you were expecting:**
New prop enableGetChoices, when supplied to a ReferenceArrayInput, will prevent that component from attempting to load choices until the supplied conditions are met, and will be in a static, inactive state until user input is supplied.

**What happened instead:**
When using new prop enableGetChoices to prevent ReferenceArrayInputs (with an AutoCompleteArrayInput serving as the child/input component) from receiving choices prior to user input, the ReferenceArrayInput will start up with a MUI loading CircularProgress, seeming to indicate it is waiting for choices from the dataProvider. 

**Steps to reproduce:**
Update to 3.19, use an AutoCompleteArrayInput as a child / input component for a ReferenceArrayInput.

**Related code:**

```
<ReferenceArrayInput
        label={label}
        source={source}
        reference="projects"
        sort={{ field: 'name', order: 'ASC' }}
        filter={{ ...filter, fieldSelectOnFilterLine }}
        filterToQuery={searchText => ({ name: `%${searchText}%` })}
        enableGetChoices={({ name }) => 'undefined' !== typeof name && 2 < name.trim().length}
        emptyText="Clear Selection"
        {...rest}
    >
        <AutocompleteArrayInput
            shouldRenderSuggestions={val => 'undefined' !== typeof val && 2 < val.trim().length}
            optionText={projectsOptionRenderer}
        />
    </ReferenceArrayInput>
```

**Environment**

* React-admin version: 3.19
* Last version that did not exhibit the issue (if applicable): 3.17
* React version: 16.2
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by ZachSelindh** [comment]
Thanks for your attention to this issue! Here's my forked sandbox:

https://codesandbox.io/s/proud-fire-dtt0j?file=/src/posts/PostList.tsx

As you can see, when you initially load in to the Posts List view with my new custom filter, the filter appears to be "loading" until the conditions stipulated by the enableGetChoices prop are met, despite (or perhaps BECAUSE of) not receiving initial options.

**Comment by WiXSL** [comment]
Reproduced. Thanks
