### ISSUE TITLE
The AppBar component color property doesn't work properly for mobile

### ISSUE THREAD

**Issue by Gorett** [marmelab/react-admin#6876]
**What you were expecting:**
The color property should work for both mobile and desktop resolutions equally.

**What happened instead:**
I'm not sure why this style is used for the mobile resolution. Desktop one doesn't have such issue.
```
.MuiToolbar-root.MuiToolbar-regular {
    background: #fafafa;
}
```
**Steps to reproduce:**
Use dev tools to set any mobile resolution.

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
<AppBar className={classes.header} {...props} color="primary">
```

**Other information:**
I faced with this issue at the first time after migration to the 3-rd version.

**Environment**

* React-admin version: 3.19.1
* Last version that did not exhibit the issue (if applicable): 2.*.*
* React version: 17.0.2
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
No news for some time, closing.
