### ISSUE TITLE
useMutation drops declaration-time options

### ISSUE THREAD

**Issue by robertjustjones** [marmelab/react-admin#6882]
**What you were expecting:**

For this code
```javascript
const [ mutate ] = useMutation( undefined, { returnPromise: true } );

const post = await mutate( { type: 'create', resource: 'posts', data } );
console.log( post.data )
```
I expected `post` to be set.

**What happened instead:**
`post` was not set after the `await` because the returnPromise got dropped at callTime.

**Steps to reproduce:**

**Related code:**

I believe this [this line in useMutation](https://github.com/marmelab/react-admin/blob/5f46fd6b6e4c4460f82308f542eb04c684916a05/packages/ra-core/src/dataProvider/useMutation.ts#L300) should be like [this line](https://github.com/marmelab/react-admin/blob/5f46fd6b6e4c4460f82308f542eb04c684916a05/packages/ra-core/src/dataProvider/useMutation.ts#L310)

**Other information:**

**Environment**

├─ @react-admin/ra-audit-log@2.5.1
├─ @react-admin/ra-editable-datagrid@2.1.1
├─ @react-admin/ra-enterprise@5.1.1
│  ├─ @react-admin/ra-form-layout@1.7.0
│  └─ @react-admin/ra-preferences@1.4.2
├─ @react-admin/ra-form-layout@1.8.0
├─ @react-admin/ra-markdown@1.3.1
├─ @react-admin/ra-navigation@3.0.1
├─ @react-admin/ra-preferences@1.4.3
├─ @react-admin/ra-rbac@1.0.1
├─ @react-admin/ra-realtime@1.4.3
├─ @react-admin/ra-relationships@2.1.10
├─ @react-admin/ra-search@2.2.1
├─ @react-admin/ra-tour@1.2.0
├─ @react-admin/ra-tree@1.6.8
└─ react-admin@3.19.1

**Comment by djhi** [comment]
Thanks for reporting!

**Comment by robertjustjones** [comment]
Excellent, thanks!
