### ISSUE TITLE
Unsaved changes prompt comes up when saving in SimpleForm

### ISSUE THREAD

**Issue by benthepoet** [marmelab/react-admin#6887]
**What you were expecting:**
The unsaved changes prompt shouldn't appear when trying to save a record using `SimpleForm`.

**What happened instead:**
When saving a record using the `SimpleForm` the unsaved changes prompt appears.

**Steps to reproduce:**

* Run the **simple** project in the **examples**.
* Edit the body of a comment.
* Save the comment.
* Unsaved changes prompt appears.

**Environment**

* React-admin version: 3.19.1
* Last version that did not exhibit the issue (if applicable): 3.19.0
* Browser: Brave 1.32.106

**Comment by WiXSL** [comment]
Reproduced. Thanks

**Comment by WiXSL** [comment]
@djhi, 
If you await more than 100 ms here, the test fails:
`await new Promise(resolve => setTimeout(resolve, 101));`
https://github.com/marmelab/react-admin/blob/fdee20110f68440149198622312ddb5f21c8d1f6/packages/ra-core/src/form/useWarnWhenUnsavedChanges.spec.tsx#L123
