### ISSUE TITLE
ReferenceArrayInput bug

### ISSUE THREAD

**Issue by aysenurakman** [marmelab/react-admin#6896]
Hello, 

the code:
![image](https://user-images.githubusercontent.com/32497073/142881502-39191d45-64d4-417c-817d-2c27d75ed20f.png)

output:
![image](https://user-images.githubusercontent.com/32497073/142881601-7a8ea07d-afc2-44a7-a8a8-6a8cd8855e36.png)

output2 (when i click inside):
![image](https://user-images.githubusercontent.com/32497073/142881732-0d54349c-4fd4-43e0-8799-f10725d74bde.png)

ReferenceArrayInput has everything but cannot show selections from API inside input. 

--When there is 1 option it works:
![image](https://user-images.githubusercontent.com/32497073/142883475-3687d83f-804d-47c6-8102-409e4f83077f.png)

-!- I opened it in edit mode, keyItemIds has the ids of the selected items. Selected items appear in the combobox. When we click on the already selected one, this record would be deleted in the past. Now it adds again. The record is multiplexed. (bug2)

please help

**Comment by fzaninotto** [comment]
Hi, I don't understand this issue. Could you please explain what you're trying to do, what you expect, what you have instead? This means you should follow the issue template.

**Comment by ahmettetik** [comment]
Hi Zaninotto,

We using to SelectArrayInput in the referancearrayinput. But, my frends as sing,the selectarrayinput have been selected data, selectarrayinput text empty.
After,  selectarrayinput text fulled
Help me.

**Comment by doubleniki** [comment]
I have the same issue. Or I suppose so :) It was unclear from the initial bug description.

Here is an example of my code (custom component):
```typescript
export const DealershipSelect: React.FC<InputProps> = ({ source, ...props }) => {
  console.log('form state', useFormState().values);
  return (
    <ReferenceArrayInput label="Dealerships" source={source} reference="dealerships" {...props}>
      <SelectArrayInput
        variant="outlined"
        translateChoice={false}
        optionText="dealerName"
        optionValue="id"
      />
    </ReferenceArrayInput>
  );
};
```

When I use this input inside Create view it works fine, but when I put the input inside a form in the Edit view the select doesn't show default/initial values that come from our BE.

But I can choose an option from the dropdown and it will appear. And if I do so I see that the input has data from BE and also the chosen one(s). But the data structure of selected options inside the array is different. The data from my BE is a list of objects, but newly selected options are integers. 

P.s. If I use to check initial values of an edit form like this `const { values } = useFormState()` it shows that data was passed to the input properly.

Hope it will help to investigate the problem.

**Comment by ahmettetik** [comment]
Hi,

There isn't Unfortunately,
I as viewing screen view and source code down.
The selectarrat selected items, but selecttext empty.
Thank you. Help me.
![Untitled](https://user-images.githubusercontent.com/12066748/143543979-a7eb0474-ca2a-4d3c-b43d-c7845c6e6821.png)

![Screenshot_1](https://user-images.githubusercontent.com/12066748/143543987-0a64c26f-36f5-4d64-a3fd-bfa8708e897d.png)

**Comment by aysenurakman** [comment]
Hello again,
I solved my problem.

@doubleniki   i think your problem is same.

newly selected options are right sight and old, default/initial values that come from response are left sight.
![image](https://user-images.githubusercontent.com/32497073/149975056-3e85503c-4f0d-43fe-88d3-f06fc3a42bd7.png)

right sight is true. because all of items should be integer. in response, my item was List<string> but it should be list<int>

**Comment by aysenurakman** [comment]
Hello again,
I solved my problem.

@doubleniki   i think your problem is same.

newly selected options(options ids) are right side and old ( default/initial ) values that come from response are left side.
![image](https://user-images.githubusercontent.com/32497073/149975056-3e85503c-4f0d-43fe-88d3-f06fc3a42bd7.png)

right side is true. because all items must be integer. in response, my item was List< string >  but it was supposed to be
list< int >

![image](https://user-images.githubusercontent.com/32497073/149975732-0ef59423-4302-4f8b-9505-729ca4f57f16.png)
