### ISSUE TITLE
'SidebarToggleButton' is not exported

### ISSUE THREAD

**Issue by despatates** [marmelab/react-admin#6910]
Hi guys,

**What you were expecting:**

Since react-admin v3.19.0, you mention in the [documentation](https://marmelab.com/react-admin/Theming.html#replacing-the-appbar):
> To make it easier to customize, we export some of the components and hooks used by the `<AppBar>`:
>
> - `<LoadingIndicator>`: A `CircularProgress` bound to the dataProvider activity.
> - `<SidebarToggleButton>`: An `IconButton` used to toggle the `<Sidebar>`.
> - `useToggleSidebar`: A hook that returns the sidebar open state and a function to toggle it. Used internally by `<SidebarToggleButton>`.

**What happened instead:**

When I want to use it to make a custom `AppBar`, I have a compilation error:

```js
import { SidebarToggleButton } from 'react-admin';
```

```
Attempted import error: 'SidebarToggleButton' is not exported from 'react-admin'.
```

**Environment**

* React-admin version: 3.19.2
* Browser: Chrome 96.0.4664.45

**Comment by WiXSL** [comment]
You are correct.
I'm marking this as a bug
