### ISSUE TITLE
Can't use Typescript private properties from 3d party library

### ISSUE THREAD

**Issue by lecoqlibre** [marmelab/react-admin#6927]
Hi, following the _Setting Up_ section from [tutorial](https://marmelab.com/react-admin/Tutorial.html), and adding `yarn add openid-client` will throw an exception about private properties being not supported :

`Support for the experimental syntax 'classPrivateProperties' isn't currently enabled`

Following the compiler advises with`yarn add @babel/plugin-proposal-class-properties` didn't solve this.

The pb seems to come from Create-React-App but it would be nice to get it fixed to be able to make an OIDC Auth Provider.

Thanks for your help.

### Complete steps to reproduce

```
npx create-react-app my-app
cd my-app
yarn add openid-client @babel/plugin-proposal-class-properties
```
Add the following code to test the lib in `src/App.js`:
```
import { Issuer } from 'openid-client';
const googleIssuer = Issuer.discover('https://accounts.google.com');
console.log('Discovered issuer %s %O', googleIssuer.issuer, googleIssuer.metadata);
```
Run the app with `yarn start`

**Comment by fzaninotto** [comment]
If I underdtand correctly, you have this problem whether you install react-admin or not? If it's the case, this is not a react-admin bug, you should open an issue with CRA or openid-client.

**Comment by WiXSL** [comment]
I agree, this doesn't seem a react-admin problem.
So I'm closing this issue.
