### ISSUE TITLE
TabbedForm, onChange does not work

### ISSUE THREAD

**Issue by DamSor** [marmelab/react-admin#6944]
**What you were expecting:**
Hi! I would like to get active tab from TabbedForm. Related bug: https://github.com/marmelab/react-admin/issues/5046

**Related code:**
I tried code from https://github.com/marmelab/react-admin/issues/5046:
```
const PostEdit = (props) => (
    <Edit {...props}>
        <TabbedForm
            tabs={
                <TabbedFormTabs
                    onChange={(event, value) => {
                        console.log('onChange', event, value); // On Tab Change
                    }}
                />
            }
        >
            <FormTab label="post.form.summary">
                <TextInput disabled source="id" />
            </FormTab>
        </TabbedForm>
    </Edit>
);
```
but it does not work. onChange event is not called.

**Environment**

* React-admin version: 3.19.2
* React version: 17.0.2

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. 

This isn't a bug, as you're using an undocumented feature. 

`<TabbedForm>` uses material-ui's `<Tabs>` component, which doesn't support the `onChange`prop. 

To do what you want, you'll have to write your own tabs component to replace `<TabbedFormTabs>` using the `tabs` prop to do what you ask.

I agree that it'd be nice to support an `onChange` prop at the `<TabbedForm>` level. Feel free to open a PR against the `next` branch to add it.
