### ISSUE TITLE
Ability to use data provider hooks without registering a resource

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#6973]
**Is your feature request related to a problem? Please describe.**
We have many REST API endpoints that do not have dedicated web pages in UI. For example, each `product` Show page also displays a list that shows volume discounts for each product. Today, in order to call useGetList hook with `volume_discounts` REST API endpoint, we first need register volume_discounts as resource, making development more complex

**Describe the solution you'd like**
It would be nice if we did not have to pre-register REST API endpoints as resources to be able to use `use` hooks in data provider. Perhaps version 4.0 can address this?

**Describe alternatives you've considered**
The only option that we found is to register each endpoint as a resources, making the list of resources large and not very manageable

**Additional context**
none

**Comment by fzaninotto** [comment]
Agreed, and we're actually implementing it in v4 (see 'Remove Ressource Initialization' in #5933). We won't implement it in v3, though.

I'm closing this issue as it's already in our goals.
