### ISSUE TITLE
Cannot use a SimpleList as a child of an ArrayField

### ISSUE THREAD

**Issue by Luwangel** [marmelab/react-admin#6974]
**What you were expecting:**

I want to use a `<SimpleList>` inside an `<ArrayField>`, but it's not working.

``` 
const UserShow = ({ permissions, ...props }) => (
  <Show {...props}>
        <TextField source="id" />
        <TextField source="name" />
        <ArrayField source="skills">
          <SimpleList primaryText={(record) => record.name} />
        </ArrayField>
        <ArrayField source="skills">
          <SingleFieldList>
            <ChipField source="name" />
          </SingleFieldList>
        </ArrayField>
  </Show>
);
```

**What happened instead:**

The `<SimpleList>` is rendered empty. It's not the case with the `<SingleFieldList>`.

![Sélection_004](https://user-images.githubusercontent.com/5584839/145606539-9c26788b-8a3a-4b49-896e-1bae1e1ef430.png)

**Steps to reproduce:**

I've written an example on CodeSandbox: https://codesandbox.io/s/sweet-mendeleev-jq98y?file=/src/users/UserShow.tsx.

**Related code:**

The `<ArrayField>` computes a total of `null`. But the `<SimpleList>` is not rendered if the total is not > 0.

https://github.com/marmelab/react-admin/blob/bd409a5942d8a20b04493b922be23f548734eac9/packages/ra-ui-materialui/src/field/ArrayField.tsx#L168

https://github.com/marmelab/react-admin/blob/77be726cca9c3512fdc4ddee65b32acb0988d16f/packages/ra-ui-materialui/src/list/SimpleList.tsx#L123

**Environment**

* React-admin version: 3.19.3
* Last version that did not exhibit the issue (if applicable): ?
* React version: /
* Browser: /
* Stack trace (in case of a JS error): /

**Comment by WiXSL** [comment]
Fixed by #6975
