### ISSUE TITLE
useShowController returns data for a previous record on first show component re-render

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#6977]
Issue https://github.com/marmelab/react-admin/issues/5492 could not be easily fixed in react-admin 3.x ( see https://github.com/marmelab/react-admin/issues/5492#issuecomment-723791621 for detailed explanation)

Since react-admin is moving to a different data query framework, is it possible to address this issue as a part of 4.0 migration?

**Comment by fzaninotto** [comment]
I think it's already solved in `next`. Would you like to try?

**Comment by fzaninotto** [comment]
No news for some time, closing.
