### ISSUE TITLE
Response data is undefined while web call return 200

### ISSUE THREAD

**Issue by willwei2021** [marmelab/react-admin#6980]
**What you were expecting:**
use useQuery to query the filter option and then render the list

**What happened instead:**
useQuery called the api end point, and returned 200  with data,
![Screen Shot 2021-12-10 at 5 25 41 PM](https://user-images.githubusercontent.com/88670368/145653464-de806091-4109-43e3-95f5-b3d036549575.png)
But in console I am seeing error:
![Screen Shot 2021-12-10 at 5 13 38 PM](https://user-images.githubusercontent.com/88670368/145652659-45e77f9e-7d16-4b88-9e56-fda18420e542.png)
And I looked into the code:
![Screen Shot 2021-12-10 at 5 15 54 PM](https://user-images.githubusercontent.com/88670368/145652879-d47a5e17-7e8b-4835-94d6-f7c2561da1cd.png)
under `ra-core` -> `performPessimisticQuery.js` -> line 40, the response is `data: { undefined }`
![Screen Shot 2021-12-10 at 5 16 22 PM](https://user-images.githubusercontent.com/88670368/145652897-b8796b00-898b-4688-88cd-bf8f0311bf04.png)

**Related code:**

```
export const ListApprovedOrgs = (props: any) => {
  const query = useQuery({
    type: 'getOne',
    resource: 'internalRiskProfileOptions',
    payload: { id: '' }
  });

  if (query?.loading) {
    return <CircularProgress />;
  }

  return (
    <>
      <List
        {...props}
        sort={{ field: 'createdAt', order: 'DESC' }}
        exporter={false}
        filters={<ApprovedFilters />}
        bulkActionButtons={false}
        title="APPROVED Organizations"
      >
        <Datagrid>
          <TextField
            source="organizationId"
            sortable={false}
            label="Organization Id"
          />
          <TextField source="name" sortable={false} label="Organization Name" />
          <TextField source="status" sortable={false} label="Status" />
          <DateField
            source="createdAt"
            sortable={true}
            options={{ year: 'numeric', month: 'long', day: 'numeric' }}
            label="Recent Approved At"
          />
        </Datagrid>
      </List>
    </>
  );
};

const ApprovedFilters = ({ onDocValidatedChange, ...props }: any) => {
  return (
    <Filter {...props}>
      <TextInput label="Organization Name" source="name" alwaysOn />
    </Filter>
  );
};

```

**Environment**

* React-admin version: 3.18.2
* React version: 16.14.0
* Browser: chrome

**Comment by WiXSL** [comment]
I don't understand your use case.
You are asking for an empty `id` to start with and not using the data for anything.

**Comment by fzaninotto** [comment]
Right, this looks more like a call for help on react-admin usage than a bug report. I suggest you post your question on StackOverflow, as explained in the issue template.  If it turns out to be an actual bug (but I doubt it, we're using useQuery all the time without problem), please post a comment here with a reproducible test case on a legitimate use case.
