### ISSUE TITLE
Mutation interface typing access

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#6984]
**Is your feature request related to a problem? Please describe.**

In order to create a custom component using a `Mutation` state as a prop, I would like to import it directly from `react-admin`.

**Describe the solution you'd like**

```
import { Mutation } from 'react-admin
```

By the `Mutation` import, I mean this interface: https://github.com/marmelab/react-admin/blob/bd409a5942d8a20b04493b922be23f548734eac9/packages/ra-core/src/dataProvider/useMutation.ts#L215

**Describe alternatives you've considered**

I did try this kind of import:

```typescript
import {
  Mutation,
} from 'ra-core/src/dataProvider/useMutation';
```

But it throws the following error:

```
/admin/node_modules/ra-core/src/actions/dataActions/crudGetAll.ts
TypeScript error in /home/sullivan/p/gitlab.com/kidways/admin/node_modules/ra-core/src/actions/dataActions/crudGetAll.ts(19,13):
Type 'CallbackSideEffect | undefined' is not assignable to type 'CallbackSideEffect'.
  Type 'undefined' is not assignable to type 'CallbackSideEffect'.  TS2322

    17 |         fetch: GET_LIST,
    18 |         onSuccess: {
  > 19 |             callback,
       |             ^
    20 |         },
    21 |         onFailure: {
    22 |             notification: {
```

I created a copy/paste of the typing referencing this issue waiting a final solution.

**Additional context**

A `Mutation` already exist on the global namespace, but according to what I found on the documentation, it's a reference to a legacy component and does not fit my needs.

**Comment by WiXSL** [comment]
Yes, we should rename the exported `Mutation` interface for something that doesn't conflict with the `Mutation` component

**Comment by fzaninotto** [comment]
I think that's a breaking change. People who already imported `Mutation` via an alias will see their code break. So we recommend that you do this. 

```jsx
import { Mutation as RaMutation } frpom 'react-admin';
```

in the next major version, I believe this interface will disappear completely.

**Comment by WiXSL** [comment]
> I think that's a breaking change. People who already imported `Mutation` via an alias will see their code break. So we recommend that you do this.
> 
> ```js
> import { Mutation as RaMutation } frpom 'react-admin';
> ```
> 
> in the next major version, I believe this interface will disappear completely.

The problem is that `import { Mutation } from 'react-admin'` only reference to the `Mutation` component. 
You can't import the `Mutation` interface.
By renaming the Mutation interface, now you can import it,

**Comment by soullivaneuh** [comment]
@fzaninotto I understand your concern about the conflict, however this subject is still active as no fix was merged so far.

May you please re-open it? Thanks!

Then my proposition: As the needed `Mutation` interface is not yet exposed, why not rename it to something more accurate?

Something like: `MutationState` or `MutationDescription`?

**Comment by soullivaneuh** [comment]
@fzaninotto The subject is still actual as no fix was merged, could you please re-open it?

About your conflict concern: The current `Mutation` interface is not exposed to the public API. So I don't think exposing it with a new name like `MutationQuery` will be breaking anything.

By the way, as I described on the issue body, importing the interface with the direct path already brake the typescript project build.
