### ISSUE TITLE
Enable data to pass in list 

### ISSUE THREAD

**Issue by cloud2torial** [marmelab/react-admin#6986]
For static data we use **useList**

For fetching a data we use **useListController**

But i want to pass static data and api calls should happen only doing pagination or sorting

so please option something like this 

> sortingMode="server"

**Comment by fzaninotto** [comment]
Hi, and thanks for your request. This is not a need that we have oursleves, or that we consider common enough to have to be implemented in the core. So we won't work on it.

You'll have to implement it yourself in a custom hook. Check the useList and useListController source to get inspiration.

If you need help on this, please consider buying [Professional Services](https://marmelab.com/ra-enterprise/) to support the core team.
