### ISSUE TITLE
Support for nested forms

### ISSUE THREAD

**Issue by frisi** [marmelab/react-admin#6990]
I've implemented a small form that allows the user to create a facebook-page-post for that links to the the current article.

For Usability reasons, the form is not only shown on the ShowView of the article but also within the "Social Media" section of the (Tabbed) EditForm (see screenshow below)

Rendering the Edit form results in a react warning:

```
Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.
...
```

### possible solution

If react-admin would render the forms using the "form" attribute rather than nesting them 
(not sure about the impact on the form library (final-form, and it's predecessor for v4) used under the hood)

nested -> bad
```
<form action="/edit">
  <input type="text" name="title"/>
  <form action="/facebook-post">
    <input type="text" name="message" />
  </form>
</form>
```

using the form attribute

```
<form id="editForm" action="/edit" method="post"></form>
<form id="facebookForm" action="/facebook-post" method="post"></form>

<input type="text" name="message" form="facebookForm" />
<input type="text" name="title" form="editForm" />
```

see this related question on SO: https://stackoverflow.com/a/21900324/810427

### form definition

``` jsx
      <TabbedForm>
      
        <FormTab label="cms.tab.content">
          ...
        </FormTab>
        
        <FormTab label="cms.tab.channels" path="channels">
        
            <Block title="Social Media">
                <TextInput source="ogTitle" fullWidth />
                <TextInput source="ogDescription" fullWidth multiline />
            </Block>

            <Block title="Facebook Beitrag" xs={12}>
                <FacebookPostForm articleId={articleId} />  ${/*  renders a SimpleForm */}
            </Block>

        </FormTab>
```

### screen 
this screen (sorry for the german) might help in giving some context

![image](https://user-images.githubusercontent.com/1120517/145822606-65427a16-e4c8-40e9-ae92-476c79e3a8ca.png)

**Comment by fzaninotto** [comment]
Thanks for your request. 

What you ask isn't really possible due to HTML constraints (not React or anything). If you want to reuse a group of inputs between two forms, you can already do it without reusing the entire form. And if you want to create a custom form layout, you cant do that, too. Finally, we're already offering forms-in-forms (kinda) via ArrayInput.

We're currently thinking about migrating away from react-final-form (see #6730) but I don't think this will change the issue.  

All in all, there are many cons and not many pros for adding this feature to the core (I think it's a rare need), so I'm -1 on adding it.

If you build a custom Form component allowing that, feel free to package it and publish it as a third-party package.

**Comment by frisi** [comment]
thanks for your feedback @fzaninotto 
i can understand your reasons to not considering this core functionality.

however i want to point out that - if i understood the [use of  the `form` attribute on `input`](https://www.w3schools.com/html/html_form_attributes_form.asp) correctly - this is no html constraint.

in plain html this would work w/o the nesting warning, however finalform (and therefore the react admin components) require inputs to be child elements of their form. 

the following form
```
<SimpleForm1>
  <TextInput source="title">
  <SimpleForm2>
    <TextInputSubForm source="message" />
  <SimpleForm2/>
</SimpleForm1>
```

could be rendered like this

```
<form id="SimpleForm1" />
<form id="SimpleForm2" />

<div class="layout-for-SimpleForm1>
  <input name="title" form="SimpleForm1" /> 
  <div class="layout-for-SimpleForm2">
    <input name="message" form="SimpleForm2" />
  </div>
</div>
```

this would allow to **display** the forms and their input nested, w/o requiring to actually nest the forms.


another option would be to only render SimpleForm2 outside SimpleForm1 - just to give you an idea.

```
<form id="SimpleForm2" />

<form id="SimpleForm1">
  <input name="title" form="SimpleForm1" /> 
  <div class="layout-for-SimpleForm2">
    <input name="message" form="SimpleForm2" />
  </div>
</form>
```

**Comment by fzaninotto** [comment]
Thanks for pointing a possible solution. Once again, I'm -1 for adding that to the core. But you can develop your own Form component to replace our `<SimpleForm>`, and even publish-it as a third-party package if you want!
