### ISSUE TITLE
optionText function not supported on AutocompleteArrayInput with create new item

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#7010]
**What you were expecting:**

When specifying this code:

```typescript
<AutocompleteArrayInput
        optionText={item => `${item.category}:${item.value}`}
        create={<CreateTagDialog />}
 />
```

I expect to see a "Create" item at the end of the list of choice

**What happened instead:**

There is an empty item. I have to write the following code to make it work:

```typescript
<AutocompleteArrayInput
        optionText={item => {
          if (item.id === '@@ra-create') {
            return item.name
          }
          return `${item.category}:${item.value}`
        }}
        create={<CreateTagDialog />}
 />
```

**Related code:**

https://codesandbox.io/s/empty-framework-p8v3q?file=/src/posts/TagReferenceInput.tsx

**Environment**

* React-admin version: 3.19.4

**Comment by fzaninotto** [comment]
Reproduced, thanks for the report.
