### ISSUE TITLE
httpOnly Cookies not being sent by requests

### ISSUE THREAD

**Issue by alphonso06** [marmelab/react-admin#7019]
**What you were expecting:**
Request should contain the cookies.

**What happened instead:**
Request does not contain the cookies, which contain the JWT.

**Related code:**
I login via an endpoint which sends HTTPOnly Cookies for use with authentication. This works on Postman, and on the browser itself (as in without the dashboard's requests).

I read both issue [#1015](https://github.com/marmelab/react-admin/issues/1015) and  [#403](https://github.com/marmelab/react-admin/issues/403), which basically states the `credentials` from `fetch()` need to be set to `include`.

Here is my authProvider's login function:
```js
login: async ({ username, password }) => {
        try {
            const form = JSON.stringify({ email: username, password })
            const payload = {
                method: 'POST',
                body: form,
                headers: new Headers({ 'Content-Type': 'application/json' })
            }

            const request = new Request(`${serviceUrl}${apiVersion}/auth/login`, payload)
            
            const response = await fetch(request, { credentials: 'include' })

            if (response.status < 200 || response.status >= 300) {
                throw new Error(response.statusText)
            }

            const auth = await response.json()
            return localStorage.setItem("user", auth.data)
        } catch (error) {
            console.error(error)
            throw new Error("Network error :(")
        }
    },
```

This does make the browser accept the cookies, but I still receive `401` because when I checked the request headers, the cookies weren't sent.

![image](https://user-images.githubusercontent.com/43776043/147036913-797ae81f-269c-40bd-b990-5a03a85b640b.png)

But when we check the browser's cookies:

![image](https://user-images.githubusercontent.com/43776043/147037006-900fc8b4-bb9b-4d1c-8fd7-263f02c31925.png)

Though as stated above, using Postman, or just directly sending a GET request using the browser, it works just fine.

![image](https://user-images.githubusercontent.com/43776043/147037377-30fd8dd3-c7f5-422a-8eb9-d2d4ffba2e5b.png)

**Postman**
![image](https://user-images.githubusercontent.com/43776043/147037516-1203e450-4d54-4237-8441-cc7567c04824.png)

![image](https://user-images.githubusercontent.com/43776043/147037575-04322ef9-aadb-4a0b-aa39-86757d9c39dd.png)

Perhaps I need to set it somehow using `httpClient`? Though being `httpOnly` JS(client) won't have access to it.

**Environment**

* React-admin version: 3.19.2
* React version: 17.0.2
* Browser: _any_

**Comment by fzaninotto** [comment]
Are you using the `simpleRestProvider`? If so, did you also add the ` { credentials: 'include' }` option to the `httpClient calls?

**Comment by alphonso06** [comment]
> Are you using the `simpleRestProvider`? If so, did you also add the ` { credentials: 'include' }` option to the `httpClient calls?

I'm using the `simpleRestProvider` yes. I just added `options.credentials = 'include'` to also send cookies in the request. This was not made clear to me with the issues I linked.

For anyone else having this issue, here's what your `dataProvider` should look like if you want to send `httpOnly` cookies with your requests:
```js
function fetchJson(url, options = {}) {
  if (!options.headers) {
    options.headers = new Headers({ Accept: 'application/json' })
  }

  options.credentials = 'include'

  return fetchUtils.fetchJson(url, options)
}

const dataProvider = simpleRestProvider(
  process.env.REACT_APP_SERVICE_URL + process.env.REACT_APP_API_VERSION, 
  fetchJson
)
```
