### ISSUE TITLE
Bug in ArrayInput still not fully solved

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#7027]
**What you were expecting:**
We still have the issue reported in the fake PR https://github.com/marmelab/react-admin/pull/6908, that was supposed to be fixed in RA 3.19.3. The temporary workaround of pinning to a specific version of `final-form` works, but removing this specific version of 
 `final-form` and moving to RA version 3.19.3 did not solve the problem of disappearing values inside `<ArrayInput>`s.

**What happened instead:**
To be able to upgrade to 3.19.4 (since it was released since then), we also had to change all `initialValue` props to `defaultValue` (at the field level). The combination of RA 3.19.4 + `defaultValue` props + removing the specific version of `final-form` is what worked for us to be able to upgrade RA.

**Steps to reproduce:**
Sadly, we didn't manage to create a reproduction case, the one in the PR mentioned above is the closest thing to our production code we could come up with. There must be something we missed, but we can't see what.

**Related code:**
We did a bit of digging inside RA code and from our understanding, the fix of RA 3.19.3 (https://github.com/marmelab/react-admin/pull/6932) deals with `initialValue`, but `defaultValue` is handled in another code path, which seems to be why using `defaultValue` works for us and not `initialValue`. I hope this hint can give you enough information to try to track the problem, which seems to be tricky.

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue
Link to the original fork in the PR mentioned at beginning. 

**Environment**

* React-admin version: 3.19.3, 3.19.4
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 17
* Browser: All

**Comment by WiXSL** [comment]
@DjebbZ, 
I've tried to set up different scenarios to reproduce the problem but without success.
Could you please make another try at producing a simple, reproducible case to work with?

**Comment by DjebbZ** [comment]
I'll give it a try soon. I would love to get the final word on this problem.

**Comment by DjebbZ** [comment]
We tried hard today, with no luck. The best we could come up with is this, which works perfectly but is even closer to our actual code than our precedent example.

https://codesandbox.io/s/beautiful-mestorf-26h9p?file=/src/posts/PostCreateEditForm.tsx.

In our code, striping down a similar form to keep only the `reward` ArrayInput (cf. CodeSandbox) works with `defaultValue` but doesn't with `initialValue`. Hopefully this information can help you find the problem.

**Comment by DjebbZ** [comment]
Ok, final answer here. The problem came from our side :) We create custom views and forgot to pass the `record` to the forms under certain circumstances. It was also the occasion for us to "double-validate" [the fix](https://github.com/marmelab/react-admin/pull/6932/files#diff-a7d3a173bb3c937b4ae2cfa9fafe622bfa7ce804081a9d5fa2654ec5ee5d292bR78) introduced in React-admin 3.19.3 that was supposed to correct the problem, and indeed it fixes it.

So far so good ! And no more problem with `<ArrayInput>`s.

**Comment by WiXSL** [comment]
I'm glad you could solve the problem! 💪 
Thanks for the feedback.
Please, open another issue at any tine if you find any related problems.
