### ISSUE TITLE
Save with redirect=false is broken 

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#7029]
The PostCreate form has a "save and add" button. When tested manually, it fails to empty the form after submission. The e2e tests don't detect this regression because they navigate to the creation form via the URL rather than via the menu.

Test via this URL: https://react-admin-marmelab.vercel.app/#/posts/create

The bug occurs both on `master` and `next`

![image](https://user-images.githubusercontent.com/99944/147268517-458b6432-6714-45aa-bff9-2692b9aa934a.png)

**Comment by andrico1234** [comment]
Am I right in thinking that this is the same behaviour exhibited [here](https://github.com/marmelab/react-admin/issues/7004)?

**Comment by fzaninotto** [comment]
No, the problem is different: here it's about triggering a reset of the form values after successful submission.
