### ISSUE TITLE
Filters don't get cleared when loading a resource list from the Menu

### ISSUE THREAD

**Issue by JonatanSalas** [marmelab/react-admin#7034]
**What you were expecting:**

I'm working on a button that redirects to a resource List with some default filters. When testing it out, it redirects well and it filters the information, but, if I move to another resource from the menu, and then from the menu go back again to the resource that has the filters, I would expect it to be cleared, but instead they keep persisted.  

**This button mimics the logic from the react-admin demo.** 

**What happened instead:**

I would expect the filters to be removed from context if the route is the path of the resource and it doesn't has url search params.

**Steps to reproduce:**

This issue is also in the demo, [check it out](https://drive.google.com/file/d/1hJHIPXAoy8j0LBZFHtVuO6B56ZY-szRF/view?usp=sharing).

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: 16
* Browser: Google Chrome

**Comment by fzaninotto** [comment]
This is by design. If you want the menu to reset filters, you have to use a custom menu, as documented there:

https://marmelab.com/react-admin/List.html#linking-to-a-pre-filtered-list
