### ISSUE TITLE
[4.0.0-alpha.1] Delete two records in a row throws exception

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#7036]
In `simple` project of the next branch:

1- Select and delete one post
2- Immediately delete another post (before notify with undo message disappears)

Result: 
You get several errors

![2021-12-27 090247](https://user-images.githubusercontent.com/8268610/147470039-0209fba9-8197-4481-b4ea-47bd3063580e.png)

**Comment by fzaninotto** [comment]
Fixed by #7046
