### ISSUE TITLE
Proper implementation for `getIdentity()`?

### ISSUE THREAD

**Issue by alphonso06** [marmelab/react-admin#7042]
## Context
I found this [one question from StackOverflow](https://stackoverflow.com/questions/64840037/react-admin-user-identity-is-not-updating-the-user-name-in-the-appbar-instantly) that was abandoned, but somewhat relevant to me. However, instead of having to manually update the page with refresh, on my end it simply doesn't apply the data.

## User Identity
According to the [documentation](https://marmelab.com/react-admin/Authentication.html#user-identity), the way to display the name and avatar of the logged-in user was to implement `getIdentity()`.

Here's mine:
```js
getIdentity: () => {
        try {
            const decoded = window.atob(localStorage.getItem("user"))

            if (decoded) {
                const { Name, ProfilePictureUrl } = decoded
                return Promise.resolve({
                    fullName: Name,
                    avatar: ProfilePictureUrl
                })
            }
        } catch (error) {
            Promise.reject(error)
        }
    }
```
The web app I'm writing sends back a base64-encoded string that contains fields for the `fullName` and `avatar` respectively.

Using `console.log()` with `atob()` reveals the data accordingly.
![image](https://user-images.githubusercontent.com/43776043/147656901-8ab12309-190f-4df6-afe4-6738cfe46cdb.png)

Somehow the avatar and name are both still empty. Refreshing the page doesn't really do anything.
![image](https://user-images.githubusercontent.com/43776043/147657035-0bf34cdc-afc4-4a3b-aaf8-160c25a5ccd7.png)

I'm sure I'm missing something with the implementation. 🤔

**Comment by WiXSL** [comment]
Can you provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
Also, you can find a proper implementation in the simple example:

https://github.com/marmelab/react-admin/blob/bc8570dd5c43f04308f8ffa59f31fa60fb140ebb/examples/simple/src/authProvider.tsx#L62-L67

**Comment by WiXSL** [comment]
This seems more a how to question than a bug report. 
I'm closing this issue, but if It's not the case, please feel free to re-open it, providing a way to reproduce the issue you are having trouble with.

**Comment by LeslieMurphy** [comment]
The question @alphonso06 asked was how to use the result of a API request to provide data for getIdentity (to show the logged in user name and avatar).  This is what worked for me in my AuthProvider.  I don't have an avatar so I pass the user initials (only the first letter appears on the page)

```
getIdentity: async () => {
       const userinfo = await UserService.getUserInfo();
       const {id: id, userName: fullName, firstLastInitials: avatar} = userinfo;
       console.log(`getIdentity UserService user name is ${fullName}'`);
       return Promise.resolve({ id, fullName, avatar });
   }

```
and

```
const getUserInfo = async () => {
    const apiUri = HostApiServer();  // GET SERVER URI
    const mainResponse = await fetch(`${apiUri}/loggedInUser`, {
        method: 'GET'
        });
    const resp = await mainResponse.json();
    console.log(`UserService - GOT user info from ${apiUri}`);
    console.log(JSON.stringify(resp));
    return resp;
    };

const UserService = {

   doLogin,
   doLogout,
   isLoggedIn,
   getToken,
   getUserInfo
 };
```
