### ISSUE TITLE
DateTimeInput clear button sends filter value to null

### ISSUE THREAD

**Issue by campings-szanetti** [marmelab/react-admin#7068]
**What you were expecting:**
When clicking on "Clear" button the filter should not be sent to the data provider.

**What happened instead:**
When clicking on "Clear" button the filter is sent to the data provider with the null value.

**Steps to reproduce:**
https://codesandbox.io/s/datetimeinput-datetime-filters-nq648?file=/src/resources/posts/list.tsx

- Select a date with the DateTimeInput component
- Click on the "Clear" button
- Notice that the filter is sent with the null value

DateInput component works well.
- Select a date with the DateInput component
- Click on the "Clear button"
- Notice that the filter is completly cleared

**Environment**

* React-admin version: 3.19.0 in my application and 3.19.6 in the CodeSandbox
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 17.0.2
* Browser: at least Chrome and Firefox
* Stack trace (in case of a JS error): N/A

**Comment by WiXSL** [comment]
Reproduced. Thanks

**Comment by dimaTalkspace** [comment]
Any update on this? Was it fixed in any version?
Thanks.

**Comment by WiXSL** [comment]
This is no longer reproducible in react-admin version 4.5.2 at least

**Comment by fzaninotto** [comment]
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.
