### ISSUE TITLE
Formatted DateField value not working as described

### ISSUE THREAD

**Issue by evergreen-trading-systems** [marmelab/react-admin#7089]
**What you were expecting:**
Formatted DateField value

**What happened instead:**
Cannot use record prop to format value

**Steps to reproduce:**
```js
const DateFieldForTimestamp = props => {
    const recordWithTimestampAsInteger = {
        [props.source]: parseInt(props.record[props.source], 10)
    };
    return <DataField {...props} record={recordWithTimestampAsInteger} />
}
```
https://stackoverflow.com/questions/54916324/can-i-use-datefield-with-timestamp-value-in-react-admin

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: latest
* Browser: chrome

**Comment by fzaninotto** [comment]
This is not a bug in react-admin but a discussion on StackOverflow. Please continue the discussion there.
