### ISSUE TITLE
UI not responsive when using both ConcurrentMode and StrictMode in React 18

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7091]
Hi, we are preparing to adopt the next React major release, which is in RC stage now.
In the new React version https://github.com/reactwg/react-18/discussions/5, they have changed the root API to `createRoot` (ConcurrentMode), while deprecating the `ReactDOM.render` (LegacyMode) 

During testing, we have found out all the button stopped working after we did a version upgrade to 18, and changed the root API to `createRoot`, and used StrictMode in render.

**What you were expecting:**

We expect the button continue to work after upgrade.

**What happened instead:**

The UI can render some part of the page, but freezes after rendering.

Browser console does not print any error

**Steps to reproduce:**

I have added a codesandbox example to illustrate the problem

https://codesandbox.io/s/interesting-cookies-bkxvx?file=/src/index.tsx

**Related code:**

Update react versions in package.json to any of the rc version of react 18
Change the render method in /src/index.tsx to

```
const container = document.getElementById("root");

const root = ReactDOM.createRoot(container);

root.render(
  <React.StrictMode>
    <Admin ...rest of admin />
  </React.StrictMode>
)
```

If we remove the <React.StrictMode> then there is no error. This is our temporary solution

**Other information:**

**Environment**

* React-admin version: 3.19.6
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 18.0.0-rc.0
* Browser: Edge 96
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report. 

This is likely due to [Strict effects in strick mode](https://github.com/reactwg/react-18/discussions/18), i.e. we are not properly cleaning up an effect on unmount.

**Comment by fzaninotto** [comment]
Maybe due to a limitation in react-router, see https://github.com/remix-run/react-router/issues/7870

**Comment by smeng9** [comment]
Seems react-router v5 won't fix compatibility problem. Closing this.

We are switching to react-admin v4 anyway, which uses react-router v6. 
For legacy application to support react 18 need to disable strict mode.
