### ISSUE TITLE
[4.0.0-alpha.2] Notification component CSS classes not being applied

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#7094]
Notifications always show with type `info`

* Given a code like this:

```js
    const notify = useNotify();

    useEffect(() => {
        notify('ra.boolean.true', { type: 'warning', undoable: true });
    }, [notify]);
```
* You get the following result:

![bug](https://user-images.githubusercontent.com/8268610/149674146-bf374373-9ef0-4863-907a-57e27c82d6cc.png)

- SOLUTION: 
 Redefining the CSS classes at the mui's Snackbar level instead of the undo button fixes it.

![after](https://user-images.githubusercontent.com/8268610/149674178-f78dddf8-26ea-4126-97cc-69100154ddab.png)

**Comment by fzaninotto** [comment]
Fixed by #7095
