### ISSUE TITLE
Allow filters that apply to the same source

### ISSUE THREAD

**Issue by zbarbuto** [marmelab/react-admin#7103]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to add multiple filters on the same source. This [appears to be](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/filter/FilterButton.tsx#L97) because the `source` is used as the `key` in the filter dropDown so duplicate filters for the same `source` result in duplicate keys and React throws an error.

A reason this might be useful is if you want to have a few different input types to filter on a single property.
For a contrived example, let's say you have a table of polymorphic data ("Comments") where each item has a `modelId` that would refer to a specific instance of a `model` (let's say a Product or a Customer). 

You might want to allow searching for a particular customer or product by name:

```jsx
// Let's say this entity is "comments" where you can comment on a user or product
const filterFields = [
   // Search for comments to a particular user by finding their username
  <ReferenceInput label="For User" source="modelId" reference="users"> // <- source is modelId
    <AutocompleteInput optionText="userName" />
  </ReferenceInput>,
   // Search for comments on a particular product by finding the product name
  <ReferenceInput label="For Product" source="modelId" reference="products"> // <- same source
    <AutocompleteInput optionText="name" /> 
  </ReferenceInput>,
]
```

**Describe the solution you'd like**
The quickest and easiest solution I can think of (that should not have any breaking changes) is to add a new optional property on the input fields which is something like `filterKey` (or whatever name makes most sense) which allows the key on filter to be customised.

Example modified code:

```jsx
  <ReferenceInput label="For User" source="modelId" reference="users"
         filterKey="userModelId"> // <- filterKey added
    <AutocompleteInput optionText="userName" />
  </ReferenceInput>,
  <ReferenceInput label="For Product" source="modelId" reference="products"
        filterKey="productModelId"> // <- different filterKey
    <AutocompleteInput optionText="name" /> 
  </ReferenceInput>,
```

This would then be used by the `FilterButton` (falling back to source as a default):

```jsx
<FilterButtonMenuItem
  key={filterElement.props.filterKey ?? filterElement.props.source}
// ...
```

**Describe alternatives you've considered**
At the moment my **super-hacky** workaround is to add some extra nonce to each "source" and then strip it out in the data provider layer:

```jsx
// DataProvider layer strips out any (.*) from the filter key
  <ReferenceInput label="For User" source="(user)modelId" reference="users">
    <AutocompleteInput optionText="userName" />
  </ReferenceInput>,
  <ReferenceInput label="For Product" source="(product)modelId" reference="products">
    <AutocompleteInput optionText="name" /> 
  </ReferenceInput>,
```

**Additional context**

The error produced when using the example above as-is:

![image](https://user-images.githubusercontent.com/9100419/149885517-5c9d9e34-eccc-48eb-8feb-108570b2a16c.png)

I'm more than happy to make a PR for this feature if we're happy with the solution and new property name.

**Comment by fzaninotto** [comment]
Thanks for your suggestion!

This is something we'll address in 4.0 with the following change:

> Change dataProvider.getList signature to accept operators in filters (filters?: Array<{ field, operator, value}>) (to be done in a BC way by passing both filter and filters to the dataProvider to avoid breaking existing data providers)

As it is already identified and scheduled, I'll close this issue as ducplicate.
