### ISSUE TITLE
bulkActionButtons={false} doesn't hide checkboxes (4.0.0-alpha.1)

### ISSUE THREAD

**Issue by olegcherr** [marmelab/react-admin#7106]
Checkboxes are always visible, even with `bulkActionButtons={false}`

![image](https://user-images.githubusercontent.com/3730074/150080166-de145b66-738b-4ef5-805c-84478c2f15e3.png)

`<List {...props} bulkActionButtons={false}>`
React-Admin 4.0.0-alpha.1

**Comment by fzaninotto** [comment]
`bulkActionButtons` moved from `<List>`to `<Datagrid>`. But since this BC break didn't appear in the upgrade guide, I'm marking this as a documentation bug.

**Comment by fzaninotto** [comment]
Fixed by #7114
