### ISSUE TITLE
Lazy load Show data within tab layouts

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7107]
There may be some cases where a GetOne request pulls in data from several different sources. The beauty of the dataProvider is that we can pretty much handle our data fetching however we want.

For a Show page that has several tabs, some tabs might display data that are infrequently used. In the scenario that a resource's GetOne data might call several endpoints, we could split up the tabs to match this network request separation. It's possible that we could offload the data fetching based on UI

lazy loading parts of the resources could result in:

- Improve user experience
- Reduced network traffic
- Lower carbon footprint

One way to manage lazy loading is by giving the option of fetching additional GetOne data based on the currently selected tab.

I'm not too sure about a valid API for this, but a simple one could involve passing through the URL param that indicates the currently selected tab to the dataProvider.

I could have a think about how this might affect caching, but I feel this would be a very valuable feature to consider adding

**Comment by fzaninotto** [comment]
Hi, and thanks for the suggestion.

This is currently not possible in react-admin v3, as each resource is supposed to have the same shape in List and Show views, and be loaded all at once. My advide would be to implement minimal data fetching for your resource, and expose additional dataProvider methods to fetch the rest of the fields. 

In v4, we've introduced [referenceOneField](#7060), and we're working on allowing to pass additional params to the dataProvider query (that's already oin the 4.0 roadmap).

So I'm closing this issue as the feature is already traced elsewhere.

**Comment by andrico1234** [comment]
Thanks for the response!

I've gone ahead with your suggestion to use additional dataProvider methods, and that services us perfectly fine.

I am looking forward to using the `referenceOneField`, since we're currently using `referenceManyField` sometimes to do what the new field should likely be doing.
