### ISSUE TITLE
Property 'children' is optional in type 'ShowControllerProps' but required in type 'ShowProps'

### ISSUE THREAD

**Issue by olegcherr** [marmelab/react-admin#7109]
**React-Admin v4.0.0-alpha.1**

I'm trying to use `ShowGuesser`, but got this TypeScript error:
`Property 'children' is optional in type 'ShowControllerProps<Record> & { children?: ReactNode; }' but required in type 'ShowProps<Record>'.`

The code is quite simple:
`<Resource name="posts" show={ShowGuesser} />`

![image](https://user-images.githubusercontent.com/3730074/150191943-249549ca-4149-4954-a940-73c20ad1b3e9.png)

Related, I guess: https://github.com/marmelab/react-admin/issues/7110

UPD:
https://codesandbox.io/s/demo--ra-showguesser-type-bug-vj7x5?file=/src/App.tsx

**Comment by olegcherr** [comment]
I reproduced it on codepen:
https://codesandbox.io/s/demo--ra-showguesser-type-bug-vj7x5?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/3730074/150509265-53b9036f-f435-4da9-8dad-15247878cfc5.png)

**Comment by WiXSL** [comment]
Thanks for the report.

**Comment by fzaninotto** [comment]
Fixed by #7121
