### ISSUE TITLE
Safari: DateInput and DateTimeInput show current date (today) when value is null... should be empty input. Tried with allowEmpty but didn't work. Issue is in safari, in chrome it is working fine.

### ISSUE THREAD

**Issue by neerajmind1** [marmelab/react-admin#7113]
* React-admin version:3.17.2
* React version: 17.0.2
* Browser: Safari 15.2

**Comment by WiXSL** [comment]
Please describe the issue in the boy instead of the title and follow the issue template.
Thanks

**Comment by WiXSL** [comment]
No news for some time, closing.

**Comment by GeorgEduard** [comment]
I have the same issue. 

Empty date fields in Safari are pre-filled with the current date. 
On Chrome they're empty, as they should be. 

 "react": "^17.0.0",
"react-admin": "^4.16.18"
Safari: 17.4.1

In [this example](https://stackblitz.com/edit/github-uoa13a?file=src%2Fposts%2FPostCreate.tsx) if you create a new post, `published_at` has no `defaultValue`. In Chrome, the field is empty, in Safari is prefilled.

**Comment by slax57** [comment]
Thanks for providing a Stackblitz.

This seems to be an issue in the underlying MUI component: https://github.com/mui/material-ui/issues/31305

As a workaround, you can pass the following `sx` prop to `DateInput` to make it behave like a regular [`<input type="date">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) in Safari (i.e. gray out the current date value when it is a placeholder value and not the actual value):

```tsx
        <DateInput
          source="published_at"
          sx={{
            '& .MuiInputBase-input': {
              backgroundColor: 'white',
            },
          }}
        />
```

I'm keeping this issue closed as this is not a react-admin issue but a material-ui one.
