### ISSUE TITLE
Validation Message issue: Validation message reflected twice on the user's end

### ISSUE THREAD

**Issue by AnubhavMukhija7** [marmelab/react-admin#7129]
**What you were expecting:**

Validation message should only be reflected once on the screen.

**What happened instead:**

When Array input is used, in certain cases error message is reflected twice on user end.

**Steps to reproduce:**

1. Select array input
2. Select a value in array input
3. Click add
4. Repeat 1,2
5. Remove 2nd element
6. Remove 1st element

**Related code:**

```
export const CustomDivisionsListInput = ({ role }) => {
  return (
    <ArrayInput
      source="list"
      label="Divisions"
      validate={[
        required(),
        minLength(1, "Enter atleast one division"),
        maxLength(5, "Enter atmost 5 divisions"),
        validateDivisionDocumentCreation,
      ]}
    >
      <SimpleFormIterator>
        <FormDataConsumer>
          {({
            formData,
            scopedFormData, 
            getSource,
            ...rest
          }) => {
            return (
              <React.Fragment>
                 <ReferenceInput
                   validate={[required()]}
                   source={source}
                   reference="divisions"
                   label="divisions"
                   sort={{ field: "name", order: "ASC" }}
               >
                  <AutocompleteInput optionText="name" />
              </ReferenceInput>
            </React.Fragment>
            );
          }}
        </FormDataConsumer>
      </SimpleFormIterator>
    </ArrayInput>
  );
};
```

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**
![Screenshot from 2022-01-24 16-23-42](https://user-images.githubusercontent.com/77374757/150770571-7baf95e0-a257-44c4-b254-19a2e3c3b64e.png)
![Screenshot from 2022-01-24 16-24-18](https://user-images.githubusercontent.com/77374757/150770694-ef4d84a3-e506-44b2-9900-ec9979f1da5a.png)
![Screenshot from 2022-01-24 16-24-15](https://user-images.githubusercontent.com/77374757/150770699-7eece1f9-cbc7-4288-8942-d6b5f6e21158.png)

After removing 2 then 1
![Screenshot from 2022-01-24 16-16-26](https://user-images.githubusercontent.com/77374757/150769995-5c5c0780-e9c2-4f2c-be5d-0565177ba979.png)

Required,Required Error is reflected twice. 

* React-admin version: 3.18.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
No news for some time, closing.
