### ISSUE TITLE
Can not run the tutorial

### ISSUE THREAD

**Issue by gpaulissen** [marmelab/react-admin#7137]
**What you were expecting:**

The command `make run-tutorial` should start the application just like `make run-simple`. I did run `make install` before (make run-simple is okay).

**What happened instead:**

Compiled with problems:X

ERROR in ./src/App.js 9:0-59

Module not found: Error: Can't resolve 'react-admin' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

ERROR in ./src/App.js 10:0-53

Module not found: Error: Can't resolve 'ra-data-json-server' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

ERROR in ./src/posts.js 9:0-212

Module not found: Error: Can't resolve 'react-admin' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

ERROR in ./src/users.js 11:0-80

Module not found: Error: Can't resolve 'react-admin' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

ERROR in ./src/App.js 9:0-59

Module not found: Error: Can't resolve 'react-admin' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

ERROR in ./src/App.js 10:0-53

Module not found: Error: Can't resolve 'ra-data-json-server' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

ERROR in ./src/posts.js 9:0-212

Module not found: Error: Can't resolve 'react-admin' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

ERROR in ./src/users.js 11:0-80

Module not found: Error: Can't resolve 'react-admin' in '/Users/gpaulissen/dev/react-admin/examples/tutorial/src'

**Steps to reproduce:**

As descibed above. Just git clone, make install and make run-tutorial.

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.9.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.0
* Browser: Google Chrome 97.0.4692.71
* Stack trace (in case of a JS error): see above

**Comment by WiXSL** [comment]
Did you run `make build` after `make install` but before `make run-tutorial` ?

**Comment by WiXSL** [comment]
No news for some time, closing
