### ISSUE TITLE
ReferenceManyField label is not displayed anymore when used on a custom field component

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#7140]
In order to avoid code duplicate, I created a custom field that use `ReferenceManyField`.

However, when I replace my `ReferenceManyField` implementation by my new custom component, the label is not displayed anymore.

**What you were expecting:**

Having the exact same behavior, meaning having the label being shown, as it's just a code export without any change.

**What happened instead:**
The label is not shown anymore.

**Steps to reproduce:**

1. Configure a `ReferenceManyField` on a show view with a label (proof test)
2. Create a custom field component using `ReferenceManyField` with the exact same configuration as the previous implementation
3. Replace the original implementation by the new custom component.

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

Repository: https://github.com/pocivaneuh/react-admin/tree/custom-reference-many-field-label

Relevant files:

- The custom component: https://github.com/pocivaneuh/react-admin/blob/621665f9cc8b67c4483e66da0136c0b4979893a5/examples/simple/src/posts/PostCommentsField.tsx
- The implement: https://github.com/pocivaneuh/react-admin/blob/621665f9cc8b67c4483e66da0136c0b4979893a5/examples/simple/src/posts/PostShow.tsx#L99

**Other information:**

**Environment**

* React-admin version: 3.19.7
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
This is not a bug.
The solution to your use case is documented: https://marmelab.com/react-admin/Fields.html#adding-a-label-to-custom-field-components

**Comment by soullivaneuh** [comment]
Thanks! I indeed missed that documentation part, sorry for that.
