### ISSUE TITLE
Datagrid inside ReferenceManyField has many issues

### ISSUE THREAD

**Issue by wayheyha** [marmelab/react-admin#7150]
**What you were expecting:**
Expectation: The Datagrid-Component works the same, inside List-View-Component and inside ReferenceManyField.
I guess this is a known issue but React-Admin does not provide nested Ressources out of the box, and now this is not working. I waisted several hours working arround the missing ressource nesting feature and now this. I also bought the premium licence. This feels so unfinished.

**What happened instead:**

1. Checkbox does not open Delete-Dialog above Table
2. Pagination is missing
3. Every Child that is no Source-Field does not create tableHead

**Steps to reproduce:**
```
<Edit>
    <SimpleForm>
        <ReferenceManyField
            reference="lorem"
            target="id"
            label="Lorem ipsum"
        >
            <Datagrid rowClick="edit" optimized>
                <TextField source="id"/>
                <TextField source="lorem_ipsum" label="Lable"/>
                <TextField source="dolor_sit_amet" label="Lable 2"/>
                <DeleteButton/>
            </Datagrid>
        </ReferenceManyField>
    </SimpleForm>
</Edit>
```

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.19.7
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
1. Could you provide a code-sandbox with an example of this behavior?
2. You have to provide the pagination component for the `ReferenceManyFIeld` as explain [in the docs](https://marmelab.com/react-admin/Fields.html#referencemanyfield)
3. The `Datagrid` produces its header items base on its children `source` and `label` props. But you can make your own header component for your own custom Datagrid as describe [in the docs](https://marmelab.com/react-admin/List.html#header-element)

**Comment by fzaninotto** [comment]
Thanks for your report. 

As for the 1., we've designed the ReferenceManyField for read scenarios. If you want to use the datagrid to take actions on a list of records, that's outside of the initial scope, and you'll have to build your own component for that. So I don't consider it a bug. That would be a nice feature to add to the Datagrid in ReferenceManyFields, but the `master` branch is feature-freeze. 

Note that the architecture of lists and datagrids will change in the next version, and the scenario you're describing is already supported in the `next`version.

Points 2 and 3 are documented and are not bugs.

So I'm closing this issue.
