### ISSUE TITLE
useEditController doesn't return mutationMode

### ISSUE THREAD

**Issue by lauri865** [marmelab/react-admin#7176]
**What you were expecting:**
useEditController doesn't return mutationMode, causing problems in child forms (SaveButton, DeleteButton)

**What happened instead:**
Mutation mode is not returned back by useEditController

**Steps to reproduce:**
```
const {mutationMode} = useEditController({...props, mutationMode: "pessimistic"});
console.log(mutationMode) -> "undefined"
```

**Related code:**
Tbd

**Comment by fzaninotto** [comment]
Why is this a bug? What "problems" does it cause in child forms? Please be more explicit and follow the issue template.

**Comment by WiXSL** [comment]
No news for some time, closing.
