### ISSUE TITLE
[4.0.0-alpha.2] Unexpected behavior since allowEmpty as been removed, empty value always present

### ISSUE THREAD

**Issue by emulienfou** [marmelab/react-admin#7179]
**What you were expecting:**

Empty MenuItem should not be present since `allowEmpty: false`

**What happened instead:**

An empty MenuItem is present and cannot be removed.
I followed the upgrade guide here: https://github.com/marmelab/react-admin/blob/next/UPGRADE.md#allowempty-has-been-removed-from-selectinput-autocompleteinput-and-autocompletearrayinput
However, according to the upgrade guide I should NOT have this empty value unless I add: `validate={[required()]}` to the component.

**Steps to reproduce:**

```tsx
<SelectInput source="type" choices={ [
        { id: 'Full Time', name: 'Full Time' },
        { id: 'Past Time', name: 'Past Time' }
      ] }/>
```

Here is the current render using the code bellow:
![image](https://user-images.githubusercontent.com/84061/152274572-2504c785-4508-4a58-8b01-1301dd5959d6.png)

**Environment**

* React-admin version: 4.0.0-alpha.2
* React version: 17.0.2
* Browser: Chrome 97

**Comment by djhi** [comment]
The documentation is not clear enough then. There will always be an empty item, with or without `required`. The `required` validation only ensure users cannot keep it empty if you need it

**Comment by emulienfou** [comment]
@djhi Haha indeed it's called `validate` so it's related to validation, my bad!

However when the `allowEmpty` props has been removed from the code, there is still the propTypes definition in the next line who needs to be removed FYI: https://github.com/marmelab/react-admin/blob/21e5a9ba6908bf2d9a97ad8a4b1dcd7886a5f350/packages/ra-ui-materialui/src/input/SelectInput.tsx#L299

**Comment by djhi** [comment]
Good catch! Thx!
