### ISSUE TITLE
Tab component complains about react node sent as label

### ISSUE THREAD

**Issue by otaviosoares** [marmelab/react-admin#7192]
This is more of an annoyance instead of a bug, as nothing breaks but it keeps logging a bunch of warnings.

When using the `Tab` component I need to pass a ReactNode as label, but react-admin's TabProps expects strings only.

I don't know if there's a specific reason for that, since material ui accepts ReactNode and it works normally.

**Steps to reproduce:**
```
<Tab label={<div>Test</div>}>
  Test
</Tab/>
```

**Environment**

* React-admin version: 3.19.2
* React version: 17.0.2
* Browser: any
* Stack trace (in case of a JS error):
`Warning: Failed prop type: Invalid prop label of type object supplied to Tab, expected string.`

**Comment by geobde** [comment]
Hello @otaviosoares i think the reason is that inside Tab component is used the ```useTranslate``` hook that takes as first  argument a key of type string.

**Comment by WiXSL** [comment]
As @geobde noted,
In the current implementation, the label is being used as the `key` prop for the Tab components; that is why it has to be a string.

**Comment by dejancg** [comment]
@WiXSL I haven't looked into it, but maybe it can be solved similar to how @djhi resolved this one: https://github.com/marmelab/react-admin/issues/5436 ?

**Comment by WiXSL** [comment]
The problem is the usage of the `key` prop that is not the same as in that PR.
But I'll try to push this one anyway for the `next` branch, since `master` is feature-frezze until version 4 is published.
