### ISSUE TITLE
checkAuth not redirecting to login page after Promise.reject()

### ISSUE THREAD

**Issue by Wrufesh** [marmelab/react-admin#7195]
**What you were expecting:**
In authProvider.js > checkAuth, I am returning Promise.reject(). Still it is not redirected to login page.

**What happened instead:**
Nothing happened

**Steps to reproduce:**
https://codesandbox.io/s/wonderful-monad-kek0c

**Comment by WiXSL** [comment]
In order to work, `<Admin>` requires at least one child `<Resource>`.
This is stated in the documentation.
I'm closing this issue

**Comment by Wrufesh** [comment]
Thank you 😊

**Comment by Xachman** [comment]
https://codesandbox.io/s/elated-bell-n8881t

I put this together to create a more complete example where you want to use custom pages.
@WiXSL

**Comment by WiXSL** [comment]
It needs to redirect to somewhere before the authProvider calls happen.
Your resource don't have a list or a name `<Resource name="posts" list={()=> null} />`.
Please read the docs.
