### ISSUE TITLE
Implement Redux toolkit

### ISSUE THREAD

**Issue by Lenny4** [marmelab/react-admin#7197]
I'm struggling to implements redux with react admin, despite the [documentation](https://marmelab.com/react-admin/CustomApp.html#using-an-existing-redux-provider).

I can copy paste the documentation and I have no errors but what is the next step ?:
```
const reducer = combineReducers({
        admin: adminReducer,
        router: connectRouter(history),
        // add your own reducers here
    });
```
We don't have a clear example on how to implement a custom reducer in the documentation.

When I'm looking at the [react-admin/examples/demo/](https://github.com/marmelab/react-admin/tree/master/examples/demo) there is a complete other way to implement redux.
```js
<Admin
      // ...
      customReducers={{ theme: themeReducer }}
      // ...
    >
```
Furthermore on the official [documentation](https://redux-toolkit.js.org/introduction/getting-started) it says:

> The [Redux](https://redux.js.org/) Toolkit package is intended to be the standard way to write Redux logic.

Wouldn't be easier to have an example with react admin implementing redux toolkit ?

Thank you

**Comment by WiXSL** [comment]
I believe the documentation section you are looking for is this one : [customReducers](https://marmelab.com/react-admin/Admin.html#customreducers). You have an example there.

The documentation you are talking about is more complex, for cases where you wwant to  embed the admin in another application, or customize the admin redux store deeply.

You even have a tip there that tells you about the other section:

`Tip: Before going for the Custom App route, explore all the options of [the <Admin> component](https://marmelab.com/react-admin/Admin.html). They allow you to add custom routes, custom reducers, custom sagas, and customize the layout.`
