### ISSUE TITLE
ReferenceManyField pagination defect

### ISSUE THREAD

**Issue by MaxKameniev** [marmelab/react-admin#7204]
**What you were expecting:**
Pagination query of ReferenceManyField is similar to List

**What happened instead:**
No results found

**Steps to reproduce:**
A bug was founded using pagination in ReferenceManyField data grid related to the page statement and the count of rows selected from perPage drop down.
To reproduce the bug we should have a total number of records more then minimal displayed records per page. Then select the last page from the pagination toolbar and increase count of records per page. "No results found" message will be displayed.
For example, we have 26 records in data grid and 25 of them are displaying on the first page, navigate to second page and increase a count of records up to 50. The query will be created with parameters: "page: 2, perPage: 50" as a result, there are no records to show due to this request.

**Related code:**
```
    <ReferenceManyField
      reference={listResource}
      target={target}
      filter={{ some filter }}
      sort={{ field: "isEnabled", order: "DESC" }}
      pagination={<Pagination rowsPerPageOptions={[25, 50, 100]} />}
      {...props}
    >
      <Datagrid
        expand={<Component />}
        isRowExpandable={boolean}
      >
     Some fields....
      </Datagrid>
    </ReferenceManyField>
```

**Environment**

* "react-admin": "3.17.3"
* "react": "17.0.1"
* Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by WiXSL** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by MaxKameniev** [comment]
Thanks for the quick answer.  Sorry, but I'm not sure if this is possible under my NDA. Could be any other solutions for this?

**Comment by CampingPanda** [comment]
@MaxKameniev just an FYI, you could have shown it in their simple sandbox like this:
```
<FormTab label="post.form.comments">
    <ReferenceManyField
        reference="comments"
        target="post_id"
        addLabel={false}
        fullWidth
        perPage={1}
        pagination={<Pagination rowsPerPageOptions={[1, 2, 3]} />}
    >
        <Datagrid>
            <DateField source="created_at" />
            <TextField source="author.name" />
            <TextField source="body" />
            <EditButton />
        </Datagrid>
    </ReferenceManyField>
</FormTab>
```
Just change the PostEdit.tsx ReferenceManyField to that and you can test it out with their data.
No need to break your NDA. Maybe it helps next time.
