### ISSUE TITLE
provide DevTools(like Redux DevTools)?

### ISSUE THREAD

**Issue by whg517** [marmelab/react-admin#7271]
react-admin version: 4.0.0-beta.1.0

**Is your feature request related to a problem? Please describe.**

Prior to 4.0, due to Redux, I could use the Redus Devtools browser plug-in to easily view my data. But now remove Redus. I tried using react-Query Devtools, but there were some problems with configuration and it didn't work

**Describe the solution you'd like**

Can we integrate react-query Devtools or other Devtools by default to assist debugging? I don't know much about the front end (which is why I chose React-Admin), and I don't know if there are any better tools out there.

**Describe alternatives you've considered**

Integrate [react-query DevTools](https://react-query.tanstack.com/devtools) ? Or others (I don't known)?

**Additional context**

Nothing.

**Comment by fzaninotto** [comment]
Thanks for your report. 

> I tried using react-Query Devtools, but there were some problems with configuration and it didn't work

It does work seamlessly in the simple example, and is documented here: https://marmelab.com/react-admin/doc/4.0/DataProviders.html#enabling-query-logs

We've used the react-query debugger extensively and it's a good replacement the ReduxDevTools for data fetching. 

As for what moved from Redux to the Store, your browser already has a debugger for localStorage.

So I don't see the need for additional dev tools. 

So please be more specific on the problems installing the react-query dev tools, or about the things you want to debug.

**Comment by whg517** [comment]
Thanks, i follow the latest doc, and everything is ok .
