### ISSUE TITLE
[v4 beta] The "save" text is not translated but shown as a key: `ra.action.save` 

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#7281]
**What you were expecting:**

The SAVE button to show the word `Save`

**What happened instead:**

The SAVE button shows the word `ra.action.save`

**Steps to reproduce:**

Just start a CREATE action for any resource and look at the "Save" button's text:

![image](https://user-images.githubusercontent.com/7850073/154867417-183cba1d-f5f3-41ce-a7cd-c8f05801f30e.png)

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

**Other information:**

**Environment**

React-admin version: "react-admin": "^4.0.0-beta.1"
Last version that did not exhibit the issue (if applicable):
React version: "react": "^17.0.2"
Browser:
Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
We're working on providing a Codesandbox for v4 ;)

**Comment by afilp** [comment]
You are all great, thank you!!

**Comment by fzaninotto** [comment]
Can you try with https://codesandbox.io/s/stupefied-goldstine-oqehsp ?

**Comment by afilp** [comment]
Thank you, are the login credentials "demo/demo"?

**Comment by afilp** [comment]
Also, are the `examples` (mainly the `demo` one) in the `next` branch fully working with `beta.1`? Because what I did, I copied the `examples/demo` folder and changed the resources/menus/dataProvider/screens/etc. to create my app. It all started from the demo I mean (taking the diffs, every day).

**Comment by fzaninotto** [comment]
Yes, the demos work fine in the `next` branch, with minor glitches.

**Comment by afilp** [comment]
I found the problem, I created all my migration based on the demo and I most likely took the `Create` logic from a `Create` component from there, that used to have `props` (while it should not) and/or the import of `SimpleForm` was done directly for `ra-ui-materialui'.

With my new commit, the problem is solved, FYI, these are the changes:

![image](https://user-images.githubusercontent.com/7850073/155695025-0eaa7d57-6f1f-46f3-bd71-3b8c56abf99b.png)

FYI: There is still a component in your DEMO (`next` branch) that uses the old logic (but `SimpleForm` is correctly imported from `react-admin`):

![image](https://user-images.githubusercontent.com/7850073/155695257-48695903-730d-482a-81c5-2e687e0420c0.png)

**Comment by afilp** [comment]
Also, maybe this is also a result of cloning the demo from its alpha status? It always fails on the 2nd navigation after login:

![image](https://user-images.githubusercontent.com/7850073/155765942-d627d780-90b8-4eac-926a-20097b4b3f03.png)

**Comment by WiXSL** [comment]
Fixed by #7325

**Comment by afilp** [comment]
@WiXSL Thank you! Will you upload the demos for v4 too, so that we can play with them online?

**Comment by WiXSL** [comment]
It is updated in `next` branch.
What do you mean?

**Comment by afilp** [comment]
Yes, I meant if they are online, so that we see the behavior without having to build the demos (unfortunately I am on Windows and the `make` commands cannot be applied).

![image](https://user-images.githubusercontent.com/7850073/156255499-1175dad3-bbe5-4ba0-9b03-45ab3673124f.png)

**Comment by WiXSL** [comment]
You can use yarn. I'm on Windows and I use that

**Comment by afilp** [comment]
Thanks, may I suggest you write something in UPGRADE.md about the missing `normalize` prop? 
I used that prop and now I am not sure how to achieve the same result, thanks a lot.

**Comment by WiXSL** [comment]
I don't think I follow you. There isn't any `normalize` prop in react-admin

**Comment by afilp** [comment]
For example, this was working in previous RA version (due to a different `form` package being used):

```
export const upper = v => v && v.toUpperCase();

...

<TextInput multiline label={window.labels.comments} source="comments" allowEmpty normalize={upper} />
```

**Comment by djhi** [comment]
You can use `format` for this purpose

**Comment by afilp** [comment]
@djhi thanks but I think that `format` only changes the appearance of the value, not the value itself (`normalize` does this). I have requested this feature from the `react-hook-form` team, unless I am wrong with what I said above and `format` works (I think not).

**Comment by djhi** [comment]
That's why you also have `parse` ;-)
