### ISSUE TITLE
[v4 β1] useConfigureAdminRouterFromChildren does not allow API Platform Admin ResourceGuesser component

### ISSUE THREAD

**Issue by alanpoulain** [marmelab/react-admin#7284]
CoreAdminRoutes component is using the [useConfigureAdminRouterFromChildren](https://github.com/marmelab/react-admin/blob/next/packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx) hook.
This hook filters the passed children by their types:
https://github.com/marmelab/react-admin/blob/next/packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx#L241-L243

Since API Platform Admin is using its [own special Resource component](https://github.com/api-platform/admin/blob/main/src/ResourceGuesser.tsx), it seems impossible to make API Platform Admin compatible with React-admin v4.

Would it be possible to provide an alternative way to filter the children? Maybe by their props? I think it will also improve the compatibility of this piece of code (comparing an element type is known to create some issues with some loader/transpiler/compiler).

**Comment by fzaninotto** [comment]
Agreed, this is a regression - I'm marking it as a bug. 

We need to detect child type based on a custom property, like material-ui does with `muiName` (cf: https://github.com/mui/material-ui/blob/master/packages/mui-utils/src/isMuiElement.ts).

A PR is welcome.
