### ISSUE TITLE
Change sidebar width doesn't work as expected

### ISSUE THREAD

**Issue by FernandoVelcic** [marmelab/react-admin#7285]
**What you were expecting:**
Change the width of the sidebar

**What happened instead:**
It works but, the titles got cutted.

**Related code:**
```
const theme = {
    ...defaultTheme,
    sidebar: {
        width: 280,
        closedWidth: 55,
    }
};
```

With this change there are more space between sidebar and content but, all the resource titles are cutted because there is another css property with fixed width at 200px

![image](https://user-images.githubusercontent.com/7217340/155012116-48b2c01e-981d-4635-969b-586909108936.png)

**Other information:**
In the picture you have more detail:
![image](https://user-images.githubusercontent.com/7217340/155012321-27491715-3b9f-455b-ab6c-7d351c0e41cc.png)

**Environment**

* React-admin version: 3.19.10
* React version: 17.0.2
* Browser: Google Chrome Version 98.0.4758.102

**Comment by fzaninotto** [comment]
Can you please follow the issue template? That would allow us to know which version of react-admin you're using, and to reproduce the problem.

**Comment by FernandoVelcic** [comment]
> Can you please follow the issue template? That would allow us to know which version of react-admin you're using, and to reproduce the problem.

Thanks for reply, I added the required information according to the issue template.
