### ISSUE TITLE
NPM error: Upstream dependency conflict

### ISSUE THREAD

**Issue by ibnlisha** [marmelab/react-admin#7287]
I am trying to npm install reactadmin which installed sucessfully. However ra-data-simple-rest doesnt and report an upstream dependency error probably cuz Ihave react-router-dom 6.2.1, whereas ra-core requires an older version. Upon force instal I get another error related to react-router-dom saying that Routes imported as Routes was not found.
**What you were expecting:**
To install ra-data-simple-rest without the need to downgrade to react-router-dom 5.3.1.

**What happened instead:**
Failed installation

**Steps to reproduce:**
npm i react-router-dom
npm i ra-data-simple-rest

```
PS C:\Users\ibn\portfolio\Enuh> npm i ra-data-simple-rest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: portfolio-enuh@0.1.0
npm ERR! Found: react-router-dom@6.2.1
npm ERR! node_modules/react-router-dom
npm ERR!   react-router-dom@"^6.2.1" from the root project        
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-router-dom@"^5.1.0" from ra-core@3.19.10      
npm ERR! node_modules/ra-core
npm ERR!   peer ra-core@"^3.17.2" from ra-data-simple-rest@3.19.10
npm ERR!   node_modules/ra-data-simple-rest
```

**Comment by WiXSL** [comment]
Please, follow the issue template!

**Comment by ibnlisha** [comment]
> Please, follow the issue template!

@WiXSL Thanks for your reply. I hope the issue is clearer now

**Comment by fzaninotto** [comment]
The npm error message explains the problem.

React-admin v3 relies on react-router v5, which is incompatible with react-router v6. If you want to use react-router v6, you'll have to use react-admin v4 (currently in beta). 

I'm closing this issue as it is not something we're going to fix in the 3.x branch (because react-router v5 and v6 and fundamentally different).
