### ISSUE TITLE
[v4 ß1 doc] Suggestion for documentation website navigation

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7293]
**Is your feature request related to a problem? Please describe.**
The navigation for v4 always reset the menu back to top after clicking a link, this makes us always have to scroll to the bottom to navigate to a different page/example

See video

https://user-images.githubusercontent.com/38666763/155390799-3459a722-cc3a-4357-9689-b44c7cd883f3.mp4

**Describe the solution you'd like**
The v3 documentation website is more friendly as there are additional navigation menus on the right side of the page

**Describe alternatives you've considered**
I would prefer the v3 documentation as it is section based and has anchor on the page. Or we need to make the v4 navigation menu not go back to top after clicking a link

**Additional context**

**Comment by fzaninotto** [comment]
It's now fixed, thanks to good old JavaScript™! https://marmelab.com/react-admin/doc/4.0/Readme.html

**Comment by smeng9** [comment]
The navigation menu on the right side of the page seems still not correct.
________________________________

**Comment by fzaninotto** [comment]
Right, reopening the issue.

**Comment by fzaninotto** [comment]
Should be fixed by now.
