### ISSUE TITLE
Why is authProvider.logout called when accessing a page when there is no user?

### ISSUE THREAD

**Issue by jeremydrichardson** [marmelab/react-admin#7294]
**What you were expecting:**
When a user goes to any page they are not logged in, they should get a "not authorized" page or redirect them to the login page.

**What happened instead:**
When a user goes to any page when they are not logged in, it calls the authProvider.logout() function. We have this set to return "/loggedout" (the route to redirect to after logout). 

The problem is that because logout is called before the authProvider.checkError function, we never have a chance to first check if there is any user logged in a redirect to the login page.

I guess I'm also not sure why authProvider.logout is called when there is no logged in user. What is the rationale behind this?

**Steps to reproduce:**

1. Add `return "/loggedout"` to authProvider logout function.
2. Add a custom route for /loggedout with a basic component.
2. Goto app and make sure no one is logged in
3. Navigate to the main url of the app (localhost:3000 or whatever)
4. Takes you to /loggedout even though you were never logged in

**Related code:**
```javascript
// authProvider.js
function authProvider(Auth) {
  return {
    checkError: (error) => {
      console.log("authProvider error", error);
      return Promise.resolve();
    },
    checkAuth: () => {
      return Auth.currentSession();
    },
    logout: async () => {
      console.log("logging out");
      await Auth.signOut();
      return "/loggedout";
    },
    getIdentity: () => {
      return Auth.currentAuthenticatedUser();
    },
  };
}
```

```javascript
// App.js
function App() {
  return (
    <Admin
      authProvider={authProvider(Auth)}
      dataProvider={dataProvider}
    >
      <CustomRoutes noLayout>
        <Route path="/loggedout" element={<LoggedOutPage />} />
      </CustomRoutes>
      <Resource name="tasks" list={ListGuesser} />
    </Admin>
  );
}
```

* React-admin version: 4.0.0-beta.1.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: 
* Stack trace (in case of a JS error):

**Comment by jeremydrichardson** [comment]
Ok, figure it out. Not a react-admin bug.

## Source of issue
The heart of the issue was in the Amplify.Auth.signout() function that I was using for signing out a user in Cognito that was federated with Google Workspaces.

## Issue
The issue was that in order to complete the logout flow it actually redirect the browser. It was this redirect that I couldn't figure out where it came from.

I enabled the Amplify logger (`Amplify.Logger.LOG_LEVEL = "DEBUG"`) which finally showed where and when that was happening.

## Fix
I needed to change the `Auth.oauth.redirectSignOut` url to match where I wanted it (in this case `localhost:3000/loggedout`). Then in my AWS Console > Cognito hosted UI config I needed to add `localhost:3000/loggedout' as an option for the signOut url. Otherwise the sign out redirection will give an error because it's not an authorized url. Then the logout worked correctly instead of a logout/login loop.

### Tip
You'll need to replace the default router of react-admin since Cognito redirect urls don't support hashes in them.


Hope that helps someone else who it dealing with AWS Amplify for authentication.

**Comment by djhi** [comment]
Thanks for sharing the solution!
