### ISSUE TITLE
Fix color for BulkUpdateButton

### ISSUE THREAD

**Issue by friday** [marmelab/react-admin#7296]
It uses the theme's `error` color, because it was accidentally copied from BulkDeleteButton

To fix this you need to remove this, or change the `error` color to `primary` (maybe the latter, so user can override it?): https://github.com/marmelab/react-admin/blob/10ad4741374ef1aa7cf5a2b4d65503b1e32dea3e/packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx#L20-L35

https://github.com/marmelab/react-admin/blob/10ad4741374ef1aa7cf5a2b4d65503b1e32dea3e/packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx#L38

https://github.com/marmelab/react-admin/blob/10ad4741374ef1aa7cf5a2b4d65503b1e32dea3e/packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx#L105

**Comment by djhi** [comment]
Thanks for the report. Would you mind opening a pull request to fix this?

**Comment by friday** [comment]
> Thanks for the report. Would you mind opening a pull request to fix this?

I don't have enough time to figure out how your dev setup with monorepo etc works.
