### ISSUE TITLE
ReferenceInput not passing label to child AutocompleteInput

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7305]
**What you were expecting:**
According to the documentation [here](https://marmelab.com/react-admin/doc/4.0/ReferenceField.html) we should apply the label to the ReferenceInput

It seems that this no longer seems to work, the text for the label instead comes from the value of `source`.

This works fine if I move the label to within the `AutocompleteInput`. 

This isn't a problem and in fact, this seems like logical behaviour. I wanted to flag it since I couldn't find any reference to this in the upgrade guide and TypeScript didn't flag it in the console either

This can be replicated in the RA demo repo:

## With label on the ReferenceInput
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/17087167/155703202-146dfe2f-f345-45cc-9fb7-25a05e6cb8b8.png">

## With label on the AutocompleteInput
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/17087167/155703377-d41b4f17-3a81-40d3-81df-8bd39b3ec508.png">

As i mentioned earlier, this new behaviour seems more intuitive.

* React-admin version: 4.0.0-beta.1.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
This has already been addressed in #7273 #7297 for the next beta, so, I'm closing this issue.

> Also, amazing job on the upgrade! We're currently upgrading our pretty big RA codebase :)

Thank you!
