### ISSUE TITLE
ReferenceArrayInput and FormDataConsumer fullWidth props not defined with Typescript

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#7312]
**What you were expecting:**

The `fullWidth` prop being set to `ReferenceArrayInput` and `FormDataConsumer`.

**What happened instead:**

The `fullWidth` prop not being defined, we have nothing on autocomplete and typechecking.

**Other information:**

I firstly only put `fullWidth` on the `CheckboxGroupInput`:

```typescript
<FormDataConsumer>
  {({
    formData, // The whole form data
    scopedFormData, // The data for this item of the ArrayInput
    getSource, // A function to get the valid source inside an ArrayInput
    ...rest
  }: FormDataConsumerRenderParams) => (getSource && formData && formData.customerId ? (
    <ReferenceArrayInput
      source={getSource('childrenIds')}
      label="Enfants"
      reference="children"
      filterToQuery={(filter: string) => ({
        $search: filter,
        userId: formData.customerId,
      })}
      {...rest}
    >
      <CheckboxGroupInput
        fullWidth
        label="Enfants"
        optionText={(record: ChildRecord): string => `${record.firstName} ${record.lastName}`}
      />
    </ReferenceArrayInput>
  ) : null)}
</FormDataConsumer>
```

But it does not change a thing.

I was thinking this is a similar issue to https://github.com/marmelab/react-admin/issues/4093.

However, I tried to add the `fullWidth` property to the parent `ReferenceArrayInput` and `FormDataConsumer` components, and it works!

This kind of missing Typescript definition can leads to hours of debug and misunderstanding (experienced). 

I see two options that have to be review by your expertise:

1. Improve the typing definition to have the `fullWidth` prop available and/or a [concrete case documentation](https://marmelab.com/react-admin/CreateEdit.html#fullwidth).
2. Change the `FormDataConsumer` and `ReferenceArrayInput` component to **not** override the full width children component, making the configuration simpler.

**Environment**

* React-admin version: 3.19.10
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by soullivaneuh** [comment]
Final diff that fix the original problem:

```diff
diff --git a/src/resources/rides/components/RideForm.tsx b/src/resources/rides/components/RideForm.tsx
index 295c04e..87e959d 100644
--- a/src/resources/rides/components/RideForm.tsx
+++ b/src/resources/rides/components/RideForm.tsx
@@ -126,7 +126,8 @@ export const RideForm: FC<Omit<TabbedFormProps, 'children'>> = (props) => (
             source="place.location.lng"
             label="Position (longitude)"
           />
-          <FormDataConsumer>
+          {/* @see https://github.com/marmelab/react-admin/issues/7312 */}
+          <FormDataConsumer fullWidth>
             {({
               formData, // The whole form data
               scopedFormData, // The data for this item of the ArrayInput
@@ -134,6 +135,7 @@ export const RideForm: FC<Omit<TabbedFormProps, 'children'>> = (props) => (
               ...rest
             }: FormDataConsumerRenderParams) => (getSource && formData && formData.customerId ? (
               <ReferenceArrayInput
+                fullWidth
                 source={getSource('childrenIds')}
                 label="Enfants"
                 reference="children"
@@ -144,6 +146,7 @@ export const RideForm: FC<Omit<TabbedFormProps, 'children'>> = (props) => (
                 {...rest}
               >
                 <CheckboxGroupInput
+                  fullWidth
                   label="Enfants"
                   optionText={(record: ChildRecord): string => `${record.firstName} ${record.lastName}`}
                 />
```

**Comment by WiXSL** [comment]
`<CheckboxGroupInput>` `fullWith` default value is already `true`.
In general, your issue is difficult to follow because you are talking about different problems.
Please, follow the issue template providing a code sandbox to reproduce the problem

**Comment by Seojun-Park** [comment]
Hello, @WiXSL
I'm currently working same project with @soullivaneuh 

Here is the reproduced code sandbox(https://codesandbox.io/s/gallant-heyrovsky-yzc3bo?file=/src/posts/PostCreate.tsx)
You can find in `PostCreate` screen.

We expected this way of row style : 
<img width="1178" alt="스크린샷 2022-03-03 11 03 28" src="https://user-images.githubusercontent.com/47709344/156543081-b801a643-6a4a-4f09-9ef6-f6485298f2a9.png">

As @soullivaneuh mentioned above, it works when the `fullWidth` prop is provided to both, parent `<ReferenceArrayInput />` and child component.

However, when the `fullWidth` prop is provided  only to  child component and not 
 to parent component(`<ReferenceArrayInput />`) , the `fullWidth` prop seems doesn't work properly.
 
In a short term, unless we provide `fullWidth` prop to `<ReferenceArrayInput />,  the result would be the same whether provide `fullWidth` prop to child or not.

<img width="1151" alt="스크린샷 2022-03-03 11 03 52" src="https://user-images.githubusercontent.com/47709344/156543428-a28ecfe3-76c3-42c8-9e5b-712fcbd2998b.png">

Could you please check it?
