### ISSUE TITLE
[4.0.0-beta.1.0] ReferenceInput -> SelectInput field, label not translated

### ISSUE THREAD

**Issue by kcsoft** [marmelab/react-admin#7314]
**What you were expecting:**
Label displays translated

**What happened instead:**
Label is always displayed in english

**Steps to reproduce:**
Using the provided [codesandbox](https://codesandbox.io/s/stupefied-goldstine-oqehsp)
Edit the posts, tab "Extra"
https://oqehsp.sse.codesandbox.io/#/posts/13/2

![2022-02-28_09-20 SelectInput](https://user-images.githubusercontent.com/176441/155941608-852f31bc-1d90-411b-a0bb-f8ac2a71c7ac.png)

**Comment by WiXSL** [comment]
Thanks for the report.

**Comment by djhi** [comment]
Fixed in #7318
