### ISSUE TITLE
RaLabeled classname not applied properly

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7317]
**What you were expecting:**
We're migrating over to RA 4, and we've noticed difficulties with applying style overrides to labelled components. 

In the theme object we're applying the following overrides:

```
RaLabeled: {
      styleOverrides: {
        label: {
          fontSize: "1.4em",
          color: PrimaryColors.Black,
          border: "1px solid red",
          opacity: 0.87,
          fontWeight: 500,
        },
      },
    },
```

But these styles aren't being applied in the app because the classname being generated by RA is the following:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/17087167/155981825-05a11392-d9f8-4f58-b0c9-3d31a7c80cee.png">

This might be a red herring, but it seems that our styles may not be applied properly because the Labeled component's root cass class is `css-8l66u2-MuiStack-root-RaLabeled-root`. And it seems we can no longer target it via the theme object. 

Do you have a codesandbox that uses RA v4 beta? If so i can create a repro case easily without having to pull from the repo

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.0.0-beta.1.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
Yes, we have:
https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple

**Comment by andrico1234** [comment]
The codesandbox fails when starting for me. Is it working for you?

**Comment by WiXSL** [comment]
Sorry, wrong code-sandbox.

Is this one: https://codesandbox.io/s/stupefied-goldstine-oqehsp

**Comment by andrico1234** [comment]
https://codesandbox.io/s/misty-star-yq5g5t?file=/src/index.tsx

If you go to one of the comment show pages in the demo, you can see that the label isn't having the custom styles applied.

You can see that the other styles are applied correctly, i.e.  the save button and menu bar

**Comment by WiXSL** [comment]
> If you go to one of the comment show pages in the demo, you can see that the label isn't having the custom styles applied.

Where exactly do I have to go?

**Comment by djhi** [comment]
That's because most of the default inputs don't use the `Labeled` component but leverage the defaults of MUI instead.

I forked the codesandbox to show how to customize MUI labels and added a `Labeled` so that you can check it works.

https://codesandbox.io/s/modern-wave-q63dwi?file=/src/comments/CommentEdit.tsx

**Comment by andrico1234** [comment]
Thanks a lot!
