### ISSUE TITLE
RichTextInput automatically adding `target="_blank"` on text change

### ISSUE THREAD

**Issue by chloelangston** [marmelab/react-admin#7324]
**What you were expecting:**
I expect that when I remove `target="_blank"` from the HTML in the rich text input, and then change the text in the "Rich text" tab, `target="_blank"` will not be automatically added back to the HTML.

**What happened instead:**
When I remove `target="_blank"` from the HTML in the rich text input, and then change the text in the "Rich text" tab, `target="_blank"` is automatically added back to the HTML. This causes a lot of confusion.

**Steps to reproduce:**
* Remove `target="_blank"` from the HTML in the rich text input
* Change the text in the "Rich text" tab
* Look back at the "HTML" tab to see that `target="_blank"` is automatically added back in

<img width="778" alt="Screen Shot 2022-02-28 at 4 23 58 PM" src="https://user-images.githubusercontent.com/12164376/156061496-ff9137f2-71f1-4659-895e-c2d68ea88ef4.png">
<img width="360" alt="Screen Shot 2022-02-28 at 4 24 07 PM" src="https://user-images.githubusercontent.com/12164376/156061504-b965ddc6-1d7e-445a-903a-61f0c2ac1ec8.png">

**Environment**

* React-admin version: 3.19.7
* Last version that did not exhibit the issue (if applicable):
* React version: 16.14.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
This is a QuillJS issue, not a react-admin one. FYI, we replaced Quill with [TipTap](https://tiptap.dev/) in v4

**Comment by chloelangston** [comment]
Thank you, @djhi ! That's great, so I will expect this issue to be resolved. Is there a date when v4 will be released?
