### ISSUE TITLE
Can't resolve 'final-form-arrays'

### ISSUE THREAD

**Issue by chrisdavies71** [marmelab/react-admin#7338]
Hey team,

I get an error when installing the V4 beta. Any thoughts or help would be appreciated.

Chris

**What you were expecting:**
Following the tutorial for V4 I installed the packages:

```
npm install react-admin@next ra-data-json-server prop-types
npm run start
```

Expected package to install and spin up React App.

**What happened instead:**
Got the following error:
```
ERROR in ./node_modules/ra-core/esm/form/FormWithRedirect.js 29:0-46

Module not found: Error: Can't resolve 'final-form-arrays' in '/Users/chrisdavies/Sites/tests/admin-test/test-admin/node_modules/ra-core/esm/form'
```

**Steps to reproduce:**
See above

**Other Information:**
Also get the error on a clean install of the package.

**Environment**
* React-admin version: 4.0.0-beta.1.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Safari 15.2
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
That's because you installed an old version of `ra-data-json-server` that has a reference to an old `ra-core`.

Update `ra-data-json-server` to the latest beta as well and it should solve your issue.
