### ISSUE TITLE
Formatting of NumberInput and TextInput breaking after X chars pressed

### ISSUE THREAD

**Issue by achyutjhunjhunwala** [marmelab/react-admin#7358]
**What you were expecting:**
In my case, user needs to enter revenue, based on which i will filter the results. Since revenue can be a huge number, i am trying to format the number using String.toLocaleString() so that it looks good and parse the value back to number when submitted to API

For this i have created 2 functions

```
const numberParser = (value) => (value ? parseInt(value, 10) : 0);
const numberFormatter = (value) => {
  return value?.toLocaleString();
};

```

and in my filters, i have defined a filter like this

```
<TextInput
  label="Min Revenue"
  source="revenue_min"
  key="revenue_min"
  format={numberFormatter}
  parse={numberParser} 
/>

Even tried to swap TextInput with NumberInput
```

**What happened instead:**
Now with this implementation, the moment the user starts typing in, if i am using NumberInput, after 3 char, when 4th number is pressed, it resets the input field. For Text Input, 4 numbers are formatted, with 5th number it resets

**Steps to reproduce:**

To login, just use any username password

https://codesandbox.io/s/condescending-moore-jri1ug?file=/src/posts.js:1424-1588

I have prepared a code sandbox where if you go to the Post Page and try to add he Min Revenue Filter and start tying in the value, you will see the issue after the 5th char is inputed.

**Related code:**
https://codesandbox.io/s/condescending-moore-jri1ug?file=/src/posts.js:1424-1588

**Environment**

* React-admin version: ^3.9.0
* Last version that did not exhibit the issue (if applicable): Not Sure
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error): No Error

**Comment by CampingPanda** [comment]
This is not a problem of React Admin, this is a general JavaScript issue.
Please read: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
If it encounters a "." it removes everything that comes after, so you constantly start over when you got above a thousand.
Also the "parse" functions are always in an English locale, while toLocaleString goes to your own computers locale unless you specify a locale.
```
const PostFilter = (props) => {
  const numberParser = (value) => parseFloat(value.replace(".", "").replace(",", "."));

  const numberFormatter = (value) => {
    if (value == null || value === "") {
      return value;
    }
    return value?.toLocaleString();
  };
```
This code at least gives you some functionality that can go to 7 digits, don't really know what the use case is for you so you can build it further on your own for your specifications. Locales are the bane of my programming existence...

**Comment by achyutjhunjhunwala** [comment]
@CampingPanda Thank you for your reply.
But this does not solves the complete problem where a user can enter lets say 1 billion as an input and it gets properly formatted.
Also i did try this code from Post Filter while reading the docs, this also has a problem like if you start typing, 12345, it gets formatted to 12,345 and the moment you enter 6, the number gets changed to 12,346 and this last number swap happens all the way until we hit the 7th number where it resets everything.

But thank you for pointing to the ParseInt issue, now I know in which direction i should be looking. 

I will try to find a solution for this and report back if i find something. In case some one else reaches here and have already solved this challenge, it would be great

**Comment by achyutjhunjhunwala** [comment]
@WiXSL Can you please specify exactly what more i should add

**Comment by WiXSL** [comment]
> @WiXSL Can you please specify exactly what more i should add

I just put that label because of your input:

`I will try to find a solution for this and report back if i find something. In case some one else reaches here and have already solved this challenge, it would be great`

**Comment by achyutjhunjhunwala** [comment]
Sorry for the confusion but no. @CampingPanda helped in finding the exact root cause of the problem. But the solution is still unclear. So I am hoping to find one or in case someone else has already solved it, expecting them to help.

The label needs more info is misleading in this case as it means that I must provide more steps or details on to how to re-produce the ticket

**Comment by CampingPanda** [comment]
Just to be reiterate, I do not understand your use case. I expect all other programmers here to also not understand it. There is no one size fits all solution for these kinds of problems. 
You would need to specify what you want or you will not get answers, that's why I just gave a direction.
```
const number = 123456.789;
console.log(new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(number));
// expected output: "123.456,79 €"
```
I have no idea if this fits your use case. This can be fed to your TextInput and you need to cleanse it to make it a number again in your parse function so it can be formatted when the user keeps typing. If you want to support 'minor' units, like the 79 cents in different languages you will probably have a problem. If you don't then its probably a solution, depending on if you want 1 or more locales.
So do you want to support cents? 
Which languages do you want to support? 
What do you want to happen when someone copy pastes weird stuff into your TextInput?
What if someone with a German locale puts in English locale input?
And a lot more edge cases.

If you just want thousand separator dots you can just insert them hard coded into the string.
So without more information you will need to fix the issue yourself.

**Comment by achyutjhunjhunwala** [comment]
@CampingPanda Thank you for the comment. My bad i was not very clear in my question above.

For my use case i only need to support 1 use case which is 'en_US' locale.
To explain the problem better, I have a Input field where User is going to Enter Revenue and based on that, i fire a query to return results based on that revenue. So use cases are
1. User enters - 7000000 
2. Now as the user is typing this, i want the text to get formatted as he starts typing so that he doesn't has to count that how many Zeroes he has already entered to make that 7 into 7 million.

User Enters 7 => they see 7
User types 70 => they sees 70
User types 700 => they sees 700
User types 7000 => they sees 7,000
User types 70000 => they sees 70,000
User types 700000 => they sees 700,000
User types 7000000 => they sees 7,000,000

I have no use case to support cents, basically only Integers, and not Floats.
Only English US language.
Copy Pasting weird stuff, such validations at the moment i don't want to handle but if i am able to solve the above problem, i will definitely try to solve that.

May be i am not understanding the exact way `parse`and `format`functions are working.
I initially thought `format` function only takes care of the text displayed on the UI and `parse` takes care of the data which will be sent to the backend. May be I am wrong in understanding this. 

When the User starts entering any number in that Input field, i get the Input in the format function, which i format and return immediately. But then after 4 chars, when the use enters the 5th char, what i get in the format function is not a number now but a string which has a comma in it, so basically i need to remove that comma, make it back into Int, and then again convert it into a comma separated value. I hope i am going in the right direction here.

But what confuses me is, this all is done by the `format`function. `parse` job is to reverse format that comma separated string into a number and send to the API. But if i remove the parse function, then the format part also stops working

**Comment by CampingPanda** [comment]
Not a problem just wanted to be clear.
You are right about the parse and format, I made an error writing `parse` should have been a `format`: https://marmelab.com/react-admin/Inputs.html#transforming-input-value-tofrom-record
This formatter should do what you want.
```
  const numberFormatter = (value) => {
    console.log("1  " + value + "  " + typeof value);       // Standard input from the textbox
    if (value == null || value.length === 0) return value;  // No crash when empty textbox
    value = value.replaceAll(".", "").replaceAll(",", "");  // Remove garbage so we can make a number
    console.log("2  " + value + "  " + typeof value);
    value = parseInt(value, 10);                            // toLocaleString needs a Number
    console.log("3  " + value + "  " + typeof value);
    if (isNaN(value)) return 0;                             // Cant make a number then 0
    return value?.toLocaleString("en-US");                  // Cast number to US locale
  };
```
You can try it here: https://codesandbox.io/s/sad-tree-jv9tof?file=/src/posts.js
This doesn't have a parser yet, you can make your own with this info, if you actually need it. 
I am unsure what you mean with your last sentence, because my sandbox shows that you can `format` fine without a `parse` function. You could just send `7,000,000` back to your back end and let it handle the logic there. But that's up to you.

**Comment by achyutjhunjhunwala** [comment]
@CampingPanda You are a rockstar mate. Thank you so much for this help. This is exactly what i need.
There is one caveat to this which i found when using the `parse` function now.

I am writing a logic in parse function which would convert this generated string by `format` function to Integer again before it sends to the backend.

But the `parse` function is overwriting whatever `format` does also in the UI. This mean the moment `parse` function executes, it converts the string to Integer and `format` functions fails because it always expect the `value` to be string. (.replaceAll only works with string and fails when it gets a number)

So I modified the code a bit like below to handle number input in `format` function

```
  const numberFormatter = (value: any) => {
    console.log('1  ' + value + '  ' + typeof value) // Standard input from the textbox
    if (value == null || value.length === 0) return value // No crash when empty textbox
    
    // ------------------CHANGED CODE -----------------------------
    
    if (typeof value === 'number') {
      value = value.toLocaleString() // Here i check if value is number (as parse function is converting it), and convert it to string so that it doesn't fails in the next step
    }
    
    // ------------------CHANGED CODE -----------------------------
    
    value = value.replaceAll('.', '').replaceAll(',', '') // Remove garbage so we can make a number
    console.log('2  ' + value + '  ' + typeof value)
    value = parseInt(value, 10) // toLocaleString needs a Number
    console.log('3  ' + value + '  ' + typeof value)
    if (isNaN(value)) return 0 // Cant make a number then 0
    return value?.toLocaleString('en-US') // Cast number to US locale
  }

  const numberParser = (value: any) => {
    return parseInt(value.replaceAll('.', '').replaceAll(',', ''), 10)
  }
```

With this change, now i don't need any change on the backend

Once again @CampingPanda many thanks for your help here. Really really appreciate

**Comment by WiXSL** [comment]
Since this issue has been clarified not to be a react-admin bug, I'm closing it.
