### ISSUE TITLE
Dependency Cycle between ra-core and ra-i18n-polyglot

### ISSUE THREAD

**Issue by antdking** [marmelab/react-admin#7361]
**What you were expecting:**

No dependency cycle

**What happened instead:**

```sh
$ yarn lerna run build
lerna notice cli v4.0.0
lerna info Executing command in 16 packages: "npm run build"
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE ra-core -> ra-i18n-polyglot -> ra-core
```

**Steps to reproduce:**

run `yarn build`

**Related code:**

N/A

**Other information:**

`ra-core` has tests that depend on `ra-i18n-polyglot`. This means that `ra-i18n-polyglot` needs to be included in the `ra-core` `devDependencies`.

---

While this is functioning for Lerna (with a warning), it fails for `yarn workspaces foreach`.

Suggest finding another way to test interpolation support.

**Environment**

* React-admin version: next
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Fixed by #7362
