### ISSUE TITLE
Can't disable SaveButton when the form is invalid with custom toolbar

### ISSUE THREAD

**Issue by FernandoVelcic** [marmelab/react-admin#7372]
**What you were expecting:**
I have a custom toolbar and I want to disable save button when the form is invalid. Without creating a custom toolbar the default behaviur works well but I can't hide delete button.

**What happened instead:**
The custom toolbar doesn't receive the validating prop updated from the form.

**Steps to reproduce:**
Just create a simple edit/create form with a custom toolbar and test it with valid or invalid data, you will see that Save button doesn't work as expected.

**Related code:**
```
const CustomToolbar = toolbarProps => {
    return (
        <Toolbar {...toolbarProps} >
            <SaveButton disabled={!toolbarProps.pristine && !toolbarProps.validating} invalid={toolbarProps.invalid} />
        </Toolbar>
    )
};
```

**Environment**

* React-admin version: 3.9.10
* React version: 17.0.2
* Browser: chrome

**Comment by WiXSL** [comment]
Your code is wrong.
You should use `props.pristine` instead of `!props.pristine`

https://marmelab.com/react-admin/CreateEdit.html#:~:text=%3CSaveButton%20disabled%3D%7Bprops.pristine%7D%20/%3E

**Comment by FernandoVelcic** [comment]
Thanks for reply @WiXSL but even with your code doesn't work as expected, pristine is updating as expected but validating prop no, I checked it with a console.log

**Comment by WiXSL** [comment]
I used your code in react-admin's simple project, and it works.
If you can reproduce what you say, please provide a code-sandbox of the simple project with the code to reproduce the issue.

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
