### ISSUE TITLE
Customtoolbar (and other form elements) not receiving Form State as expected

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7373]
**What you were expecting:**
Similar behavior for the useForm hook from react-hook-form to how useForm/useFormState were used by react-final-form. And for the form to be correctly passed to the custom toolbar and form elements.

**What happened instead:**
Calling useForm and logging formState in the CustomToolbar (and other custom formcomponents within a Tabbed or SimpleForm) returns an empty object, preventing parity for custom forms written with react-final-form.

**Steps to reproduce:**
Call useForm inside any SimpleForm, log results.

**Related code:**
https://codesandbox.io/s/affectionate-wave-0iun4h

**Environment**

* React-admin version: 4.0.0-beta.2
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 18
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
You are using  code-sandbox with version 3 of react-admin.

Version 4 code-sandbox is here: https://codesandbox.io/s/stupefied-goldstine-oqehsp

**Comment by ZachSelindh** [comment]
@WiXSL I apologize! Here is a codesandbox showing the issue with the correct dependencies: 

https://codesandbox.io/s/loving-waterfall-1efg5r

Go to the Post create page and click the "Console Log Formstate" button, you'll see the formState and errors are both empty objects.

**Comment by ZachSelindh** [comment]
@fzaninotto Thanks for looking at this. What I'm experiencing locally is that calling 'useWatch' and 'useFormState' inside a SimpleForm or Form component throws the error "cannot read 'control' of null", which according to react-hook-form's docs/issues is an indication that the Form is not properly wrapped in FormContext.

HOWEVER, I have another project using React-Admin which will correctly call the react-hok-form methods, which leads me to believe the problem is with something in this particular project.

Will update for posterity if I can find the root of this issue and why it affects only this particular project.

**Comment by ZachSelindh** [comment]
Commenting in case it helps future users: I solved my issue of useFormContext returning "null" by pruning my app's dependencies. We were using a library that relied on an old version of React, which required me to use the "--legacy-peer-deps" flag with npm install. After removing/replacing that dependency, and starting with a fresh install of node_modules, the form context is returning as expected, and the other react-hook-form methods like useWatch are behaving as expected!
