### ISSUE TITLE
filterDefaultValues not working as expected in 4.0 beta

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7376]
**What you were expecting:**
Parity with v3 in behavior of List prop filterDefaultValues.

**What happened instead:**
Values for filterDefaultValues seem to be ignored.

**Steps to reproduce:**
Add filterDefaultValues to a given List.

**Related code:**
https://codesandbox.io/s/agitated-ptolemy-gizhtx

I have added filterDefaultValues to comments and posts List views in this sandbox, and am logging the params.filters at the dataProvider getList method. The filters, as displayed, do not reflect the filterDefaultValues, and the params do not either.

**Environment**

* React-admin version: 4.0.0-beta.2
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 18
* Browser: Chrome

**Comment by WiXSL** [comment]
Thanks for the report.
I couldn't exactly reproduce it in your sandbox but I could locally

**Comment by fzaninotto** [comment]
I'm not sure the problem still exists in the latest beta. I can't reproduce it, or I don't understand it. Could you please test with the latest beta and explain exactly what you're doing to get the error (if you get one)?

**Comment by ZachSelindh** [comment]
@fzaninotto I think you might be right, it hasn't happened to me locally on beta-3. Seems difficult/inconsistent to reproduce based on above comments. My codesandbox is not compiling properly at the moment but if I experience this issue again, I can let you guys know.

**Comment by djhi** [comment]
Can you try with this one? https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple. It target the `next` branch though but at least it compiles now

**Comment by ZachSelindh** [comment]
@djhi Confirmed using a fork of the sandbox you sent me, the filterDefaultValues prop is working!

https://codesandbox.io/s/exciting-grass-9scvr9?file=/src/posts/PostList.tsx

I believe this issue can be safely closed.

**Comment by fzaninotto** [comment]
Thanks for your feedback!
