### ISSUE TITLE
Forking new 4.0 beta 2 sandbox frequently fails to compile

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7380]
**What you were expecting:**
Stable behavior for new 4.0.0-beta.2 sandbox (located at https://codesandbox.io/s/stupefied-goldstine-oqehsp)

**What happened instead:**
Webpack attempts to compile, and fails with an error message in the console that refers to the SimpleForm component

**Steps to reproduce:**
Fork above sandbox (this error is somewhat intermittent; I have been able to compile forks correctly, but the failure rate is about 75%)

**Related code:**
As an example sandbox:
https://codesandbox.io/s/friendly-hermann-dl2qzk
![failedFork](https://user-images.githubusercontent.com/43347643/157925475-970a215b-6295-4959-877f-2fa6bde905cc.png)

**Environment**
* React-admin version: 4.0.0.beta-2
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 18
* Browser: Chrome, Codesandbox
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for the report but I don't see what we can do about it.
