### ISSUE TITLE
Use locale from browser/user agent as `react-admin` default locale

### ISSUE THREAD

**Issue by strarsis** [marmelab/react-admin#7383]
**Is your feature request related to a problem? Please describe.**
It would be nice if a `react-admin` app can detect the locale that is used by the browser/user agent and automatically set it as the default locale.

**Describe the solution you'd like**
`react-admin` detects the locale that is used by the browser/user agent and sets it as the current locale. The user can still switch the locale later (when the UI allows it).

**Describe alternatives you've considered**
Setting the default locale. But this also doesn't seem to be as easy as I thought.

**Comment by djhi** [comment]
You mean this? https://marmelab.com/react-admin/Translation.html#using-the-browser-locale

**Comment by strarsis** [comment]
Yes, thanks!

**Comment by WiXSL** [comment]
Closing
