### ISSUE TITLE
Allow for passing FormHelperTextProps and InputLabelProps to SelectArrayInput 

### ISSUE THREAD

**Issue by mccasey** [marmelab/react-admin#7386]
Currently the [SelectArrayInput](https://github.com/marmelab/react-admin/blob/dfcd326eafb59bbd4fa777a4e8a003a928c36ce2/packages/ra-ui-materialui/src/input/SelectArrayInput.tsx#L221L281) component does not allow for passing **label props** and **helper text props**. Any props passed that aren't removed after sanitization are only applied to the `<FormControl />` component. This seems like very odd behavior as other react-admin inputs accept those props and are passed down to the underlying Material UI components. The same should apply to SelectArrayInput, ArrayInput, BooleanInput and NullableBooleanInput, etc. 

**Solution**
* Allow for **label props** to be passed to the <InputLabel /> component. Example: [SelectArrayInput](https://github.com/marmelab/react-admin/blob/dfcd326eafb59bbd4fa777a4e8a003a928c36ce2/packages/ra-ui-materialui/src/input/SelectArrayInput.tsx#L228L239).
```JS
<InputLabel
    ref={inputLabel}
    id={`${label}-outlined-label`}
    error={touched && !!(error || submitError)}
    {...InputLabelProps}
>
    <FieldTitle
        label={label}
        source={source}
        resource={resource}
        isRequired={isRequired}
    />
</InputLabel>
```

* Allow for form **helper text props** to be passed to the `<FormHelperText />` component. Example: [SelectArrayInput](https://github.com/marmelab/react-admin/blob/dfcd326eafb59bbd4fa777a4e8a003a928c36ce2/packages/ra-ui-materialui/src/input/SelectArrayInput.tsx#L273L279).
```JS
<FormHelperText error={touched && !!(error || submitError)} {...FormHelperTextProps}>
    <InputHelperText
        touched={touched}
        error={error || submitError}
        helperText={helperText}
    />
</FormHelperText>
```

**Comment by lissitz** [comment]
I'm facing the same issue with the equivalent SelectProps prop for the Select component. The included autoWidth prop looks odd in many cases, and there is no way to change it other than replicating the component.

**Comment by mccasey** [comment]
@lissitz Yes it seems there was a pr opened for this but it has since been closed. The expectation should be that we can manipulate the underlying MUI components react-admin uses for rendering inputs. I need to be able to manipulate the input label component via props to display a special label at time in the form. Having to recreate every react-admin input by copying the source code just to allow for the passing of InputLabelProps isn't great.

**Comment by mccasey** [comment]
> I'm facing the same issue with the equivalent SelectProps prop for the Select component. The included autoWidth prop looks odd in many cases, and there is no way to change it other than replicating the component.

You can also override the label related components (FormControlLabel, InputLabel) 'component' prop with a custom label component via theme overrides. This way you won't have to replicate all the react-admin input components.
