### ISSUE TITLE
Problem with ra-test when upgrade to react-router v6

### ISSUE THREAD

**Issue by nphdiem** [marmelab/react-admin#7400]
I am upgrading my app from react-router v5 to v6. When I run unit tests, I receive error message:

`Error: Uncaught [TypeError: Cannot read property 'pathname' of undefined]`

I take a look into the <TestContext> component definition and see the code shows error:

Code:
`<Provider store={this.storeWithDefault}>
<Router history={this.history}>{this.renderChildren()}</Router>
</Provider>`

Error:
`Property 'history' does not exist on type 'IntrinsicAttributes & RouterProps'`

As I know, the property history is removed in react-router v6.

Environment:

- react: 17.0.2
- react-router-dom: 6.2.2
- ra-test: 3.19.10
- react-admin: 3.19.10

**Comment by nphdiem** [comment]
My problem was solved by version 4.0.0-alpha.1 which migrate to react-router v6.
Thanks.

**Comment by djhi** [comment]
We released several beta since. Latest is `4.0.0-beta.3`
