### ISSUE TITLE
Have multiple lists for same resource on the same page

### ISSUE THREAD

**Issue by arnaudvergnet** [marmelab/react-admin#7401]
**Is your feature request related to a problem? Please describe.**
We can display several lists on the same page by using the [`disablesyncwithlocation`](https://marmelab.com/react-admin/doc/4.0/List.html#disablesyncwithlocation) `List` prop. But if those lists use the same resource, their selection state is synced (while filters, pagination and data is not). Select items (for bulk actions) in one list, and the same selection gets applied to the other.

**Describe the solution you'd like**
It would be nice to be able to make selection local with the help of a prop similar to `disablesyncwithlocation`. Ideally selection would have its own context like pagination and filters.

**Describe alternatives you've considered**
My current workaround is to not show the lists at the same time and hide one behind a dialog. When the dialog opens or closes, I call the `useUnselectAll` hook to reset selection.

**Additional context**
I tried to do this in both v3 and v4 and got the same problem.

From what I could see in the code this selection state is set in `useListController` using the `useRecordSelection` hook. In [v3 selection is synced globally](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/useRecordSelection.ts#L29) using the redux store, and in [v4 it is also synced globally](https://github.com/marmelab/react-admin/blob/0d507ce8ed3fc57f26f60e013fb33c268bfb2228/packages/ra-core/src/controller/list/useRecordSelection.ts#L25), but using the new `useStore` hook.

**Example**

Here I am editing a museum. I want to display the list of people associated to the current museum and allow the user to add some from the list of all available people (Like `ReferenceArrayInput` but with the power of the `ListBase` component). So I have 2 lists in the same page with the resource `Person`, so  `useRecordSelection` returns the same selection.

https://user-images.githubusercontent.com/80701113/158987824-c3505e2c-37cd-4c27-94fb-07c63cae83d9.mp4

**Comment by djhi** [comment]
A solution might be to allow users to provide their own store key in v4.

**Comment by fzaninotto** [comment]
If row selection isn't tied to a resource, then when a user deletes a record, it may remain selected without any ability to unselect it. 

We've chosen to store one selection per resource for that reason. We won't support the use case you describe. 

If your need doesn't match this design, then don't use our List component, and build your own based on react-admin hooks.

**Comment by arnaudvergnet** [comment]
> A solution might be to allow users to provide their own store key in v4.

I managed to create the behavior I wanted by reimplementing the `useListController` hook. This was simple because I only needed to add a new parameter for a custom store key passed to the `useRecordSelection`. But this is going to be difficult to maintain for me as I will have to copy-paste `useListController` implementation on each update. Then I created my own `ListBase` component to use this new controller with this new prop.

> If row selection isn't tied to a resource, then when a user deletes a record, it may remain selected without any ability to unselect it.

To solve this I use the `useUnselect` and `useUnselectAll` hooks with the new store key to unselect rows when the user deletes them.

Letting users provide their own store key would be a nice addition. **If you do not want to add this feature, it should at least be documented that the selection state will always be globally synced with the resource.** The current [`disablesyncwithlocation`](https://marmelab.com/react-admin/doc/4.0/List.html#disablesyncwithlocation) documentation is misleading:

> When you use a `<List>` component anywhere else than as `<Resource list>`, you may want to disable this synchronization to keep the parameters in a local state, independent for each `<List>` instance. This allows to have multiple lists on a single page. The drawback is that a hit on the “back” button doesn’t restore the previous list parameters. To do so, pass the disableSyncWithLocation prop.

Here we might understand that enabling this prop will make our List state completely local, which is only true if you ignore the selection.

**Comment by fzaninotto** [comment]
> To solve this I use the useUnselect and useUnselectAll hooks with the new store key to unselect rows when the user deletes them.

This means you've made changes in several components - not only the list, but also the DeleteButton and BulkDeleteButton. this isn't a solution we can make generic, so this will stay in userland. 

>  it should at least be documented that the selection state will always be globally synced with the resource. 

You're right. Would you like to open a PR for that?

**Comment by christiaanwesterbeek** [comment]
A completely different approach to this problem is to create an alias of the `Person` resource in your api. Create an endpoint called `MuseumPerson` (that underlyingly interacts with the same Person entity in your database/backend). If you're working with postgrest for example you could create a view that does `create view api.MuseumPerson as select * from api.Person`). This way there is no need to do anything special in RA (whether it is version 3 or 4). It's the way I've been doing it since RA 2.

**Comment by djhi** [comment]
You can do that at the data provider level as well if you can't change the API
