### ISSUE TITLE
BUG: ReferenceInput cannot reference same path on Edit

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#7403]
Version: `"react-admin": "^3.19.10"`

I have a `Product` that has a `parentId` of the same type `Product` so I create a reference input on my product like so:

```jsx
<ReferenceInput reference="products" source="parentId">
    <AutocompleteInput />
</ReferenceInput>
```

This works fine in Create, but in Edit the **entire form goes blank with no errors in console.**

**WORKS:**
```jsx
<Create {...props}>
<SimpleForm>
    ...
    <ReferenceInput reference="products" source="parentId">
      <AutocompleteInput />
    </ReferenceInput>
</SimpleForm>
</Create>
```

**DOES NOT WORK:**
```jsx
<Edit {...props}>
<SimpleForm>
    ...
    <ReferenceInput reference="products" source="parentId">
      <AutocompleteInput />
    </ReferenceInput>
</SimpleForm>
</Edit>
```

**Comment by WiXSL** [comment]
Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
No news for tome time, closing.
