### ISSUE TITLE
Allow disabling of optimistic rendering to support permanent filters

### ISSUE THREAD

**Issue by sarahtrefethen** [marmelab/react-admin#7409]
Hi, I love react-admin! It is so powerful and easy to use. 

However, I have a problem. Our site uses a tab layout to display lists of one resource with different permanent filters. In this case, optimistic rendering is not desirable, because it causes the data from a previous tab to appear briefly while a new tab loads. 

I see that this issue was discussed two years ago [here](https://github.com/marmelab/react-admin/issues/4486), but as far as I can tell the solution was never implemented. 

We also use paging and user-controlled filters on these tabbed sublists, so if it were somehow possible to disable optimistic rendering just for the first load of the tab component that would be ideal. Maybe useListController could take a boolean that could be warped in a useEffect in the calling component to create the behavior I want?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question.

What you describe is very hard to do in react-adùin v3, and trivial in react-admin v4. For instance, here is how to make the OrderList of [the ecommerce demo](https://marmelab.com/react-admin-demo/#/) behave how you describe:

```diff
const OrderList = () => (
    <List
        filterDefaultValues={{ status: 'ordered' }}
        sort={{ field: 'date', order: 'DESC' }}
        perPage={25}
        filters={orderFilters}
+       queryOptions={{
+           keepPreviousData: false,
+       }}
    >
        <TabbedDatagrid />
    </List>
);
```

So we won't do anything special about it, as it's possible in userland in v4 and v3 is feature freeze.
