### ISSUE TITLE
textAlign not working with FunctionField when used in function component

### ISSUE THREAD

**Issue by nkappler** [marmelab/react-admin#7410]
I am writing a custom number field to avoid redundant code and because I want to have some custom formatting.
I expected to be able to use textAlign in the function component to write shorter code, but it has no effect.

```javascript
/* Take this sample field */
const Test = (props: any) => <FunctionField render={() => "Test"} textAlign="right"  {...props}  />

/* I expected to be able to write this, but the Fields are still left aligned */
export const MyList = (props: ListProps) => (
    <List {...props}>
        <Datagrid >
            <Test source="name" />
            <Test source="name" />
            <Test source="name" />
        </Datagrid>
    </List>
);

/* Instead I have to repeat the textAlign property on each Field */
export const MyList = (props: ListProps) => (
    <List {...props}>
        <Datagrid>
            <Test source="name"  textAlign="right"  />
            <Test source="name"  textAlign="right"  />
            <Test source="name"  textAlign="right" />
        </Datagrid>
    </List>
);
```

I expected this to work, because I cannot set a default text alignment currently. `<NumberField />` for example is right aligned per default and it is not possible to write a custom number field which is also right aligned per default.

**Comment by nkappler** [comment]
```json
"react-admin": "^3.19.0",
"react-dom": "^17.0.2",
"typescript": "^4.4.4",
```

**Comment by nkappler** [comment]
Ok I found a solution, so I'll post it in case somebody needs it.

I still find it quite confusing, so I'll leave the issue open until it get's the attention of a maintainer.
Feel free to close it, but maybe you consider to change this behaviour or document it somewhere.

The solution is to do it the same way `<NumberField>` is implemented:

```javascript
import { FC, memo } from "react";

// the call to memo is not strictly needed I guess
const Test: FC<any> = memo((props) => <FunctionField render={() => "Test"} {...props} />);
Test.defaultProps = {
    textAlign: "right"
};
```

**Comment by fzaninotto** [comment]
Thanks for your feedback.

This is documented, but a bit hidden: https://marmelab.com/react-admin/Fields.html#styling-fields

The react-admin v4 documentation makes it more obvious: https://marmelab.com/react-admin/doc/4.0/Fields.html#textalign
