### ISSUE TITLE
[Examples/IDE] Autocompleted paths to project files relative to project root, not `src/`

### ISSUE THREAD

**Issue by strarsis** [marmelab/react-admin#7425]
**What you were expecting:**
VSCode IDE JS/TS refactoring `Add import from [...]` should use a path relative to the `src/` folder, not the project root,
when the file to be imported is at least one directory below `src/` (as being in `src/components/`).

**What happened instead:**
VSCode IDE JS/TS refactoring `Add import from [...]` uses a path relative to the project root, 
build (`vite`) fails:
````
Failed to resolve import "src/[...]" from "src/categories/[...].tsx". Does the file exist?
````
Also those paths stick out as import paths relative to the project root are not used elsewhere in the project.

**Steps to reproduce:**
- Open a `react-admin` example app in VSCode.
- Ensure the project builds / builds+watches.
- Use a component that is inside the project, e.g. a custom component (`<MyComponent />`,
without importing it yet.
- VSCode IDE proposes a JS/TS refactoring that adds the import, select it.
- The new import is added, but the build fails.
The import path starts with `src/` as the path is relative to the project folder, not `src/`.
When `src/` is removed from that import path, the import works correctly and the build succeeds.

**Related code:**
`src/components/MyComponent.tsx`:
```tsx
import { Label } from "@material-ui/icons";
import React from "react";

export default function (props) {
    return <Label>Test</Label>;
}
````
In order to reproduce this issue the component to be imported must be inside a directory below `src/`, not directly in `src/`.

`src/index.tsx` (or any other file in `src/`):
```tsx
//    <Admin ...>
         <MyComponent />
//    </Admin>
````
The `import` of `<MyComponent />` is intentionally omitted in order to trigger and use the IDE refactor.

**Other information:**

**Environment**

* React-admin version: `3.19.10`
* Last version that did not exhibit the issue (if applicable): (not known, this is probably example project-specific)
* React version: `17.0.2`
* Browser: Latest Chrome on Windows 10
* Stack trace (in case of a JS error):
````
Failed to resolve import "src/components/MyComponent" from "src/index.tsx". Does the file exist?
````

**Comment by WiXSL** [comment]
You are describing a possible bug in your IDE.
This has nothing to do with react-admin.
How could a change in react-admin would help you?

**Comment by fzaninotto** [comment]
For my part, I never had any issue with the auto-import feature os VSCode. Whenever I add e.g. `SaveButton`to a component, VSCode adds the correct import:

```jsx
import { SaveButton } from 'react-admin';
```

**Comment by strarsis** [comment]
@WiXSL: Yes, probably a bug with the IDE, but it could be caused by a specific configuration in the `react-admin` example projects.

@fzaninotto: Imports from external modules (`npm`/`node_modules`) work fine. The issue occurs when local modules are imported (using relative paths).

**Comment by fzaninotto** [comment]
I don't see how react-admin can impact the way your IDE imports local files... This looks like a configuration problem on your side.

**Comment by strarsis** [comment]
@fzaninotto: `webpack.config.js` in the sample app:
```js
module.exports = {
    entry: {
        polyfills: './src/polyfills.ts',
        index: './src/index.tsx',
    },
````
The `entry.index` is `./src/index.tsx` - the IDE however assumes `/` being the project root and uses paths that are relative to it.
Maybe this is the reason? TypeScript uses `entry.index` while the IDE doesn't use that field and assumes `/` as the default?

**Comment by fzaninotto** [comment]
I'm sorry, we can't troubleshoot your problems with your IDE here. This tracker is for react-admin bugs only. Please ask your question on StackOverflow.
