### ISSUE TITLE
FilterLiveSearch doesn't allow outlined variant

### ISSUE THREAD

**Issue by Oktay28** [marmelab/react-admin#7429]
**What you were expecting:**
To not render the label in FilterLiveSearch component when the label prop has falsy value. Freedom to pass regular TextInput props down to the TextInput while using TypeScript.

**What happened instead:**
Label is always rendered and hides the placeholder when not focused. TypeScript prop types on FilterLiveSearch does not allow me to pass regular TextInput props like placeholder, variant, etc ...

**Steps to reproduce:**
\<FilterLiveSearch variant="outlined"  placeholder="Search"  source="name" />
without label prop
with label = null
label = undefined
label = ""

**Comment by fzaninotto** [comment]
Please follow the issue template.

**Comment by fzaninotto** [comment]
My interpretation:

`<FilterLiveSearch>` cannot be represented with an 'outlined" variant for 2 reasons:

1. TypeScript doesn't accept the `variant` prop
2. Even when bypassinfg TypeScript, an empty label shows over the outline (see below). 

<img width="668" alt="image" src="https://user-images.githubusercontent.com/99944/161416894-d842696e-899d-47a7-8de2-0e62314278d9.png">

Problem 1 occurs on v3 and v4, problem 2 only occurs on v4.

**Comment by fzaninotto** [comment]
Fixed by #7478
