### ISSUE TITLE
[v4] Text Filter Gets Refilled After User Empties It

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#7432]
**What you were expecting:**

When a user empties a text filters, it stays empty

**What happened instead:**

The textinput compes back to pre-reset value on blur

**Steps to reproduce:**

1. Open [the v4 CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple)
2. Type a filter in the seach box (e.g. "tempore"
3. Click on the first element in the list
4. Once in the detail view, **click on the back button**
5. In the list view, empty the text filter with the small cross
6. The previous value ('tempure") comes back

https://user-images.githubusercontent.com/99944/160161603-6eac26d9-56bc-4885-8886-834995e86693.mov

**Environment**

* React-admin version: v4.0.0-beta-3 / `next` branch
* Last version that did not exhibit the issue (if applicable): v3
* React version: 17
* Browser: Chrome

**Comment by arnaudvergnet** [comment]
I also encountered this issue and from what I could find, this seems to happen only when you change page with text in the filter. If you clear the filter, change page and come back, the bug does not occur anymore.

**Comment by fzaninotto** [comment]
Fixed by #7442
