### ISSUE TITLE
Dataprovider calls re-made by clicking back and forth from application

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7433]
**What you were expecting:**
Dataprovider calls to not be made when clicking back into the window.

**What happened instead:**
When leaving the application window, and then clicking back in, the dataProvider calls relevant to the current view are re-made, resulting in unnecessary data transfer.

**Steps to reproduce:**
Open the application, click away (such as into the devtool console), then click inside the application window.

**Related code:**
https://codesandbox.io/s/nifty-feynman-bm8ue2?file=/src/posts/PostList.tsx

**Other information:**
![dataProviderCallRepeat](https://user-images.githubusercontent.com/43347643/160168345-af64931c-820c-4d01-9cfc-fd35bd6f2209.gif)

**Environment**

* React-admin version: 4.0.0-beta.3
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 17.0.2
* Browser: Chrome

* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
That's a react-query feature, that you can disable by passing an option to the QueryClient. 

```jsx
 const queryClient = new QueryClient({
   defaultOptions: {
     queries: {
       refetchOnWindowFocus: false,
     },
   },
 })

const App = () => (
   <Admin queryClient={queryClient}>
      ...
   </Admin>
);
```


See https://react-query.tanstack.com/guides/window-focus-refetching

**Comment by ZachSelindh** [comment]
@fzaninotto Thank you for your attention to this issue! I have configured my queryClient as you suggested, and list view calls are not made repeatedly as shown in my issue. However, blurring and refocusing on form windows still makes redundant calls to all the form's enabled ReferenceInput calls.
