### ISSUE TITLE
Ability to override default redirects inside Show, Create, Edit and Delete components (RA 4.0) 

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#7436]
**Is your feature request related to a problem? Please describe.**
I've create a custom tabbed component that is supposed to render different resources inside MUI tabs
```js
<Tabbed route="search">
  <Tab name="home">
    {SearchHomePage}
  </Tab>
  <Tab name="products">
    <Resource name="products" list={ProductList} show={ProductShow} />
  </Tab>
  <Tab name="parts">
    <Resource name="parts" list={PartsList} show={PartsShow} />
  </Tab>
</Tabbed>
```

`Tabbed` component automatically registers the following routes:
- /search/home/*
- /search/products/* (all  `<Resource>`  are registered as child routes)
- /search/parts/* (all  `<Resource>`  are registered as child routes)

The issue is that react-admin's `Show`, `Create`, `Edit` and `Delete` controllers use `useRedirect`, `useCreatePath` and `useBasePath` to redirect  to `/<resourceName>` instead of `/search/<resourceName>` once actions are completed or failed

I would like to be able to force `Show`, `Create`, `Edit` and `Delete` components to use a different base path for default actions

**Describe the solution you'd like**
- update `useRedirect`, `useCreatePath` and `useBasePath` to access options `{ basename: string}` and use this parameter instead of context value; also forward this parameter to `useCreatePath` call inside `useRedirect`
- update `Show`, `Create`, `Edit` and `Delete` controller to add  { basename:string } option, and forward this parameter to  `useRedirect`, `useCreatePath` and `useBasePath`  functions inside `useShowController`, `useEditController`, `useCreateController`, `useDeleteWithUndoController`, and `useDeleteWithConfirmController`

This solution will not impact current functionality, and will provide me with ability to easily influence where users are redirected to when actions are successful or failed.

**Describe alternatives you've considered**
Alternative is to replicate `Show`, `Create`, `Edit` and `Delete` components and supporting controllers in my project, and make changes directly to them; this option, however, is error-prone and is not maintainable.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

We won't implement that feature. Keeping the url and the resource name the same allows us to keep the API not too complex, and we don't want to change that balance. 

You'll have to create your own versions of Edit and Create to accomodate your need.

Note that `basename` will be removed altogether in 4.0.

**Comment by panfiva** [comment]
@fzaninotto , can we export `BasenameContextProvider` so that I can use it to override basename within individual components; that will allow me to implement the changes I need.

Thanks

**Comment by panfiva** [comment]
@fzaninotto , I just tested the following code using `react-admin/examples/simple` and it appears `posts` resource works properly using both `/posts` and `/custom/posts` URL; should we add this to documentation to let people know they can publish resources outside of a standard URL by overriding `<BasenameContextProvider>`?

```js
  <Admin
      authProvider={authProvider}
      dataProvider={dataProvider}
      i18nProvider={i18nProvider}
      title="Example Admin"
      layout={Layout}
  >
      <CustomRoutes noLayout>
          <Route
              path="/custom/posts/*"
              element={
                  <BasenameContextProvider basename={'/custom'}>
                      <Resource name="posts" {...posts} />
                  </BasenameContextProvider>
              }
          ></Route>
      </CustomRoutes>
      <Resource name="posts" {...posts} />
  </Admin>
```

**Comment by fzaninotto** [comment]
We'll export BasenameContextProvider (see #7439), but we won't document what you described because we don't want to support it.
