### ISSUE TITLE
4.0.0-beta.3 UseMany call not sent to data provider in list view

### ISSUE THREAD

**Issue by arnaudvergnet** [marmelab/react-admin#7438]
**What you were expecting:**
useMany requests should always be sent to the data provider.

**What happened instead:**
useMany request appears in react-query but is not received by the data provider.

**Steps to reproduce:**
- Open the [v4 codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple
)
- Create a new post without tags
- Create a new post with a tag
- Enter a search query to show only those posts in the list
- Open the react query log and the console
- See how the data provider did not log the call to retrieve the tag,. It only received the call with the empty array.

**Related code:**

Could reproduce the issue on the v4 sandbox.

https://user-images.githubusercontent.com/80701113/160426713-f835479d-2a4c-4d96-8c23-068c1e62e9d7.mp4

**Environment**

* React-admin version: 4.0.0-beta.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.0
* Browser: Firefox

**Comment by fzaninotto** [comment]
Reproduced, thanks!

**Comment by fzaninotto** [comment]
Fixed by #7477
