### ISSUE TITLE
Error: graphql operation failed Error: Unable to find any GraphQL type definitions for the following pointers: - graphql

### ISSUE THREAD

**Issue by almelm** [marmelab/react-admin#7447]
I am trying to run the below graphql script however, each time I excute the gql`` , it throws this error Error: graphql operation failed Error: Unable to find any GraphQL type definitions for the following pointers: - graphql. 

`import React from 'react';
import { useQuery, gql } from '@apollo/client';

const PLANETS = gql`{
    planets {
      cuisine
      id
      name
  }
}`

export default function Planets() {
    const { loading, error, data } = useQuery(PLANETS);

    if (loading) return <p>Loading...</p>
    if (error) return <p>Error :(</p>

    return data.PLANETS.map(({ id, name, cuisine}) => (
        <div key={id}>
            <p>
                {name} | {cuisine}
            </p>
        </div>
    ));
}`

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
No news for some time, closing.
