### ISSUE TITLE
Infinite rerender on no-code example on CodeSandbox

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7453]
**What you were expecting:**

The codesandbox should not keep rerendering the view

**What happened instead:**

the view gets rerendered infinitely

**Steps to reproduce:**

Create a sandbox using https://github.com/marmelab/react-admin/tree/next/examples/no-code

**Related code:**

```
https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/no-code?file=/vite.config.ts
```

**Other information:**

**Environment**

* React-admin version: 4.0.0-rc.0
* Last version that did not exhibit the issue (if applicable): 3.19
* React version:
* Browser: Edge 99
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hello!
Thank you for submitting this issue.
This looks like a codesandbox only issue, since I have no problem running the no-code example locally.
We'll look into that and keep you updated!
Cheers

**Comment by smeng9** [comment]
Hi @slax57 Checkout this repo's config, it is no longer having infinite loop, can you also verify if the local one works fine for you?
https://codesandbox.io/s/wandering-wind-zcpkf3?file=/vite.config.ts

**Comment by smeng9** [comment]
Seems now the codesandbox no longer rerenders infinitely,

but, it still has an error without any console log....

![Screenshot from 2022-11-02 15-06-32](https://user-images.githubusercontent.com/38666763/199592648-d963050d-b9e3-4e13-8d9a-d30d8442780e.png)

Tested against https://codesandbox.io/s/github/marmelab/react-admin/tree/vite-consistent/examples/no-code after vite version bump in #8345

**Comment by fzaninotto** [comment]
I managed to launch your last codesandbox without problem:

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/99944/199675497-33ac81eb-8b01-4fe1-8506-490279a890a4.png">

Is your issue coming from CodeSandbox?

**Comment by smeng9** [comment]
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/no-code seems throws bad gateway for now because vite cannot be found. 

![Screenshot from 2022-11-03 12-50-25](https://user-images.githubusercontent.com/38666763/199797476-adb0c9a4-d611-4e37-9932-5be060a02be3.png)

Huh, I have to fork and change the starting script in https://codesandbox.io/s/pedantic-ully-d1so8d?file=/package.json:64-83 from `"dev": "vite",` to `"dev": "yarn vite",` in order to get it work.
The infinite rerender loop is indeed resolved.
