### ISSUE TITLE
Loader keeps spinning after applying filter

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#7458]
**What you were expecting:**

The loader icon on the appbar should stop spinning after the dataProvider answers

**What happened instead:**

The loader icon keeps spinning. it's probably related to #7438

**Steps to reproduce:**

0. launch the simple example (https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple) *in desktop mode* (because this seems related to the tags column being rendered)
1. Go to the posts list
2. type "lorem" in the search box
3. The loader never stops spinning

**Environment**

* React-admin version: 4.0.0-rc.0
* Last version that did not exhibit the issue (if applicable): 3
* React version: 17
* Browser: Chrome

**Comment by arnaudvergnet** [comment]
Yes this is exactly https://github.com/marmelab/react-admin/issues/7438 but with a simpler way to reproduce the issue. If you open the react-query inspector you can see the `["tags","getMany",{"ids":[]}]` request staying in fetching state.

**Comment by fzaninotto** [comment]
Fixed by #7477
