### ISSUE TITLE
4.0.0-rc.0 Datagrid rowClick function called on mount

### ISSUE THREAD

**Issue by arnaudvergnet** [marmelab/react-admin#7463]
**What you were expecting:**
The rowClick function passed as prop to Datagrid is called only when the user presses a row.

**What happened instead:**
The rowClick function passed as prop to Datagrid is called on mount for each rendered row and when the user presses a row.

**Steps to reproduce:**
1. Open the [v4 codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple?file=/src/posts/PostList.tsx)
2. Open the /src/posts/PostList.tsx file
3. In the `rowClick` function, add the following : `console.log('rowClick');console.log(record);`
4. Refresh the sandbox and open the console
5. See all the records in the datagrid being printed in the console.

**Environment**

* React-admin version: 4.0.0-rc.0
* Last version that did not exhibit the issue (if applicable): 4.0.0-beta.3
* React version: 17.0.1
* Browser: Firefox
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi!
Thank you for reporting this issue.
I can reproduce this behavior on my side as well.
I'll have a look at the code and see what causes this.

**Comment by WiXSL** [comment]
I've trace it to this PR #7411

**Comment by fzaninotto** [comment]
Fixed by #7465
