### ISSUE TITLE
can i use a react-admin project inside another app with react-admin store .But no sidebar and appbar?

### ISSUE THREAD

**Issue by Bijayini** [marmelab/react-admin#7473]
Don't want to use in another app without Admin component as it has list, crate and edit functionality. In case of Route, data fetch call is not happening

**Comment by WiXSL** [comment]
Yes.
Simply provide your own layout component: https://marmelab.com/react-admin/Admin.html#layout

**Comment by Bijayini** [comment]
@WiXSL  I don't want the sidebar and header at all.
