### ISSUE TITLE
Multiple @mui errors after updating to 4.0.0-rc.0

### ISSUE THREAD

**Issue by ricardochimenes** [marmelab/react-admin#7474]
**What you were expecting:
Update version from 3.0 beta to 4.0.0-rc.0**

**What happened instead:
The application is returning a lot of errors regarding react-admin mui components. At first, using 4.0.0 beta3 it all worked fine. This week I updated the version and tried out the new release and from the start, the errors popped out. Here follows the code from one of the pages with error, LoggedOutPage.js

**

**Steps to reproduce: Changed the version on package.json, deleted node-modules folder, installed node modules again and run**

**Related code:**

```
import { Link, Layout } from "react-admin";
import Card from "@mui/material/Card";
import CardHeader from "@mui/material/CardHeader";
import Avatar from "@mui/material/Avatar";
import LockOpenTwoToneIcon from "@mui/icons-material/LockOpenTwoTone";

export default function LoggedOutPage() {
  console.log("logged out page");

  return (
    <Layout appBar={() => <></>} menu={() => <></>}>
      <Card variant="elevation">
        <CardHeader
          title="Logged Out"
          subheader="This will show your logged in status."
          avatar={
            <Avatar sx={{ bgcolor: "red" }}>
              <LockOpenTwoToneIcon color="success" />
            </Avatar>
          }
        />

        <p>You have been successfully logged out.</p>
        <p>
          <Link to="/login">Log in again?</Link>
        </p>
      </Card>
    </Layout>
  );
}
```

**Other information:**

**Environment**

* React-admin version: 4.0.0-rc.0
* Last version that did not exhibit the issue (if applicable):4.0.0-beta.3
* React version: 18.0.0
* Browser: Chrome
* Stack trace (in case of a JS error):
ERROR in ./src/theme/LoggedOutPage.js 6:0-50
Module not found: Error: Can't resolve '@mui/material/CardHeader' in '/Volumes/extra/DEV/trace-mvp/trace-frontend/src/theme'
 @ ./src/App.js 13:0-50 37:40-53
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./src/theme/LoggedOutPage.js 7:0-42
Module not found: Error: Can't resolve '@mui/material/Avatar' in '/Volumes/extra/DEV/trace-mvp/trace-frontend/src/theme'
 @ ./src/App.js 13:0-50 37:40-53
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./src/theme/LoggedOutPage.js 8:0-70
Module not found: Error: Can't resolve '@mui/icons-material/LockOpenTwoTone' in '/Volumes/extra/DEV/trace-mvp/trace-frontend/src/theme'
 @ ./src/App.js 13:0-50 37:40-53
 @ ./src/index.js 7:0-24 11:33-36

**Comment by fzaninotto** [comment]
The errors appear in a component of yours, not in a react-admin component. Besides, the error messages seem pretty clear: you have missing dependencies. 

I'll close this PR as it doesn't look like a react-admin problem. Please provide more details if you can show that this is indeed a react-admin problem.
