### ISSUE TITLE
Sortable ImageInput

### ISSUE THREAD

**Issue by beinoriusju** [marmelab/react-admin#7476]
This is a feature request for ImageInput component.

**Is your feature request related to a problem? Please describe.**
I want my client to be able to sort product images. Some images are more important to customers and should be shown first, but they are dependent on upload order.

**Describe the solution you'd like**
ImageInput with multiple={true} could have a drag function to sort child images like in this library https://clauderic.github.io/react-sortable-hoc/#/basic-configuration/horizontal Changing sort order and saving a document should keep a new order.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
![Screenshot from 2022-04-02 14-23-22](https://user-images.githubusercontent.com/24639014/161381221-557cb0f1-ea52-42a6-9dee-0c2d0898eed1.png)

**Comment by fzaninotto** [comment]
Great idea! Feel free to submit a pull request to implement it. 

As we won't implement it ourselves unless we need it, I'll close this PR. If you need assistance building it, consider sponsoring the project for it.
