### ISSUE TITLE
Input level validation doesn't fire until after submit

### ISSUE THREAD

**Issue by nathan-britten** [marmelab/react-admin#7490]
**What you were expecting:**
Input level validation to fire on input change

**What happened instead:**
Input level validation is only firing after the form has been submitted

**Steps to reproduce:**

1. Navigate to  https://codesandbox.io/s/withered-fast-ogtbkt?file=/src/posts/PostCreate.tsx
2. Create new post
3. Enter a string that is more than 3 characters long in title
4. No validation occurs
5. Click save
6. Validation then fires
7. Shorten length of string in title, then lengthen again
8. Observe validation disappearing and appearing as we would expect

**Related code:**

Sandbox: https://codesandbox.io/s/withered-fast-ogtbkt?file=/src/posts/PostCreate.tsx

**Other information:**

Currently inputs require on the change but they are now only firing on submit. 

**Environment**

* React-admin version: 4.0.0-rc.0
* Last version that did not exhibit the issue (if applicable): 3.19.5
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi!
Thank you for reporting this.

Actually this is a consequence of the replacement of `react-final-form` by `react-hook-form` in v4, see https://marmelab.com/react-admin/doc/4.0/Upgrade.html#forms for more info.

Indeed, with react-hook-form, the default mode for validation is `'onSubmit` (see https://react-hook-form.com/api/useform/).

If you really wish to have the validation trigger before submission, you can try using a different validation mode like so:
```tsx
<SimpleForm defaultValues={defaultValues} mode="onBlur">
  [...]
</SimpleForm>
```

Closing this as this does not seem like an issue to me.

**Comment by ZachSelindh** [comment]
This is probably due to the "mode" for the form being set to "onSubmit", which the docs seem to imply is the default.

https://react-hook-form.com/api/useform

I fixed it on my forms by adding mode="onBlur" to my SimpleForm and TabbedForm components, though you may want "onChange" or even "all"

**Comment by WiXSL** [comment]
> Thanks guys, appreciate the response. Would it be worth adding this to the RA documentation to make it clearer?

I'm doing that right now!

**Comment by WiXSL** [comment]
Done!
