### ISSUE TITLE
ra-data-graphql v4 unpublished

### ISSUE THREAD

**Issue by arjunyel** [marmelab/react-admin#7493]
**What you were expecting:**

Hi friends, I am working on maintaining ra-data-hasura which relies on ra-data-graphql, I was working to make sure ra-data-hasura works with react admin v4 but it looks like ra-data-graphql v4 was unpublished from NPM? Thank you for your help!

**What happened instead:**

ra-data-graphql v4 unpublished

**Related code:**

https://github.com/marmelab/react-admin/commit/2ccf578890528105f70c50a3d6c3a5a9e28281c8

**Environment**

* React-admin version: 4
* Last version that did not exhibit the issue (if applicable): 3
* React version: 18

**Comment by fzaninotto** [comment]
Yep, we won't publish ra-data-graphql at the same time as the other 4.0 packages. I'm not satisfied with the developer experience, and I think we should change some major aspects of it. But I also don't want to delay the 4.0 release because of that. 

That's why we didn't release rc1 for this package, and won't release a 4.0 before it's ready.

**Comment by fzaninotto** [comment]
> Any chance you release v4 of ra-data-graphql with react admin v4 and then release an update later? That way our users can stay in sync with all the big changes and can upgrade to v4 with everyone else. Thank you!

That would forbid a breaking change, so we won't do that. 

As for feedback about ra-data-graphql, feel free to comment here!

**Comment by arjunyel** [comment]
@cpv123 feel free to leave any feedback you have here, thanks again for your work on ra-data-hasura!

**Comment by tkahng** [comment]
Just to be clear does this mean that those who use ra-data-graphql-simple should not migrate to ra4 since the lasted dataprovider wont work with ra4?

**Comment by hjr3** [comment]
I think this should be mentioned in the upgrade guide.

**Comment by fzaninotto** [comment]
This is fixed by #7607, released in 4.0.2
