### ISSUE TITLE
React 18 strict mode breaks URL query params

### ISSUE THREAD

**Issue by arjunyel** [marmelab/react-admin#7494]
**What you were expecting:**

That react admin works normally with React 18 strict mode

**What happened instead:**

When I click on a column header to sort the url doesn't update with query params, so nothing happens.

**Steps to reproduce:**

In the code sandbox try to sort a column, see it doesn't work. In index.js, comment out the React 18 section and uncomment the React 17 mode section, sorting should work now. 

**Related code:**

https://codesandbox.io/s/sweet-fast-1pkgk5?file=/src/index.js

React 18 mode (broken):

```
import App from "./App";
import * as React from "react";
import { StrictMode } from "react";
import * as ReactDOMClient from "react-dom/client";

const rootElement = document.getElementById("root");
const root = ReactDOMClient.createRoot(rootElement);

root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
```

React 17 mode (working):

```
import App from "./App";
import * as React from "react";
import { render } from "react-dom";
const container = document.getElementById("root");
render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  container
);
```

**Environment**

* React-admin version: 4
* React version: 18
* Browser: Latest Chrome and Safari

**Comment by slax57** [comment]
Hi!
Thank you for submitting this.
Indeed it seems that using React 18 introduces some problems, I also see many errors in the devtools console.
We'll look into that and keep you updated.

**Comment by slax57** [comment]
Small update:
- errors in devtools console were due to the use of `ListGuesser`, which hasen't been updated yet
- app behaves normally with React 18 **without** strict mode. So it probably has something to do with this: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

**Comment by fzaninotto** [comment]
The culprit is https://github.com/marmelab/react-admin/blob/c001779ea47a1d8d5cf1f5da07dfd6e17708b9b8/packages/ra-core/src/controller/useListParams.ts#L172

As Strict mode unmounts and remounts a component, the safety added in #7443 deactivates the setParams.

I still have to figure out a fix.

**Comment by WiXSL** [comment]
Can this one be closed?
