### ISSUE TITLE
Formcontext returns 'null' inside SOME SimpleForm components.

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7501]
**What you were expecting:**
React-hook-form methods such as useWatch, useFormContext, etc. to work correctly inside a SimpleForm component.

**What happened instead:**
React-hook-form methods inside SOME SimpleForms fail with the error "cannot read properties of null (reading 'control')". In this case, particularly when used in my codebase to wrap inputs on a modal form on a list view's bulk actions. Elsewhere, such Create and Edit forms, the react-hook-form methods return the expected values.

**Steps to reproduce:**
I'll provide screenshots below, but perhaps the most frustrating aspect of this bug is that I have been unable to replicate it in a CodeSandbox. Since the problem is likely something to do with my local, I hope this issue can potentially help other RA users who may run into that same problem.

**Related code:**
The below code is a VERY stripped down component which is breaking when used as a Bulk action on a list view in my codebase.
```
import React from 'react';
import { SimpleForm, TextInput } from 'react-admin';
import { useWatch } from 'react-hook-form';

const TestForm = () => (
    <SimpleForm>
        <TestInputs />
    </SimpleForm>
);

const TestInputs = () => {
    const test = useWatch({ name: 'test' });
    return <TextInput source="test" />;
};

export default TestForm;
```

**Other information:**
As mentioned above, I really believe that the issue is on my side (especially since I can't recreate it on CodeSandbox), but my code follows the patterns that previously worked when RA was using react-final-form, and I'm hoping this issue can be used to point me in the right direction for debugging the problem, and hopefully help others who have have run into the same issue or will in the future.

Screenshot for the stack trace below.
![stacktraceSimpleFormError](https://user-images.githubusercontent.com/43347643/162214759-61417294-2cd4-43d1-b53e-f8af36ca6e7b.png)

**Environment**

* React-admin version: 4.0.0.rc-1
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by ZachSelindh** [comment]
@slax57 Thank you for taking a look at this. Given the strangeness and inconsistency of this issue, do you have any tips on how to debug it? I'm using react-hook-form 7.28.1.

I previously had this same issue with ALL forms, but refactoring my application to avoid installing legacy-peer-deps (I was willing to try anything) allowed me to at least use react-hook-form methods inside Create and Edit forms at the appropriate resource view, but not elsewhere.

**Comment by slax57** [comment]
I would need to reproduce myself and dive deeper in the stacktrace to figure out what's missing. So for now I don't have any clues, sorry 🙁 .
@WiXSL would you happen to have any ideas about this one?

**Comment by WiXSL** [comment]
@ZachSelindh,
Could you provide us a repo with a simple project with the exact same setup you have (in terms of dependencies and config) and that is given you problems?

**Comment by ZachSelindh** [comment]
@WiXSL I'll try to put one together!

**Comment by ZachSelindh** [comment]
@WiXSL @slax57 I have added you guys as collaborators on this Repo: https://github.com/ZachSelindh/react-admin-form-testing

In order to recreate my issue, simply navigate to "Part Request Lines", select/toggle a record, and click the bulk action button "Request Approval."

The app will break at that point looking for FormContext, though the element that breaks is wrapped in a SimpleForm.

Thank you so much fir your attention to this issue!

**Comment by WiXSL** [comment]
I can confirm, that this has nothing to do with react-admin.

I can take a simplified version of your (not working) code, and include it in a new project created with CRA with exactly the same dependencies/devDependecies and there, it works without problems.

The problem is most likely in the configuration of your project's webpack or babel.

**Comment by ZachSelindh** [comment]
@WiXSL Thank you so much for looking into this! That is a huge help and a critical clue to my next debugging steps. I'll document my fix here when I discover what was going wrong.

**Comment by ryanostrom** [comment]
@ZachSelindh did you ever find a resolution? I've just experienced this issue with a vite buildpack system. Babel versions and configuration are identical between the sandbox project and my vite project, the only difference is vite vs. webpack building. I experience the issue when trying to declare a TextInput filter.

```
const Filters = [
  <TextInput source="q" label="Search" defaultValue="" alwaysOn />
]

export default () => (
  <List filters={Filters} >
  ...
)
```

**Comment by ryanostrom** [comment]
Ah nvm this is on me. Using yarn workspaces and thought I had a clean yarn install but I didn't.

**Comment by ZachSelindh** [comment]
@ryanostrom I have resolved this issue, thanks for reminding me to post it here.

Initially, I was unable to see formContext in any situation, which I resolved by refactoring our codebase to avoid installing legacy peer deps via npm. React-hook-form hooks started working in most forms after this.

Shortly afterwards, useFormContext and useWatch started failing inside many nested components in forms, particularly custom form inputs. After posting the above issue, and the RA team confirming that the issue was on my side, I scrutinized our webpack and babel config. I started with babel. We were using a .babelrc file, which I changed to a babel.config.json and pruned down to absolute bare essentials.

Confoundingly, it worked. Especially strange since our webpack config only uses a babel-loader rule for our own source code. 

I'll be the first to admit that I'm relatively inexperienced (in all regards, but especially) in webpack and babel configuration, so if anyone wants to chime in with suggestions of what could have been the problem, I welcome the chance to learn and possibly help others.

Glad to hear you found the issue! Posting my above fix for posterity.

**Comment by toniweser** [comment]
I was working on a project, where we were using Material UI and included React Admin at a later point. 

As React Admin is providing also Material UI dependencies, we did forget to remove the previously used Material UI dependencies. Probably this was causing the error. 

After removing the Material UI dependencies, everything was working fine.
