### ISSUE TITLE
useForm().setValues(...) doesn't cause input's value to update

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7502]
**What you were expecting:**
If I wanted to programmatically set the value of an input using `form.setValue()`, I would expect the input to receive the value and update it's state accordingly. 

This is no longer working, and the input's value is no longer updating.

You can view this behaviour [here](https://codesandbox.io/s/black-currying-21zpdb?file=/src/posts/PostCreate.tsx)

There's a setTimeout that runs after 3 seconds. The log inside of it runs, but the text doesn't update.

**What happened instead:**

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by ZachSelindh** [comment]
Try destructuring setValue from react-hook-form's useFormContext method instead of useForm! UseForm is used to instantiate the initial form, while useFormContext is where you can pull the useForm methods from in order to use them inside the FormContext.

**Comment by slax57** [comment]
@ZachSelindh +1

Also, you should use the `useFormContext` hook _inside_ a `Form` component.
In you example you used the hook outside your `<SimpleForm>`.
Here is a working example: https://codesandbox.io/s/recursing-robinson-mo563f?file=/src/posts/PostCreate.tsx:493-505

Closing issue

**Comment by Danjavia** [comment]
link is broken @slax57 :(
