### ISSUE TITLE
render prop on <Form> seems missing

### ISSUE THREAD

**Issue by gartner** [marmelab/react-admin#7504]
When working on upgrading from V3 to V4, I came across this in the upgrade guide:

[](https://marmelab.com/react-admin/doc/4.0/Upgrade.html#formwithredirect-render-function-arguments-have-changed)

- this explains that the arguments to the render() function has changed.
However, it seems like the render() function is completely removed from the <Form> component. And that it instead uses child components.

Indeed, the form displays nothing when using the render() function, but works as expected when placing the contents as childs of <Form>

This is on the v4.0.0-rc.1

**Comment by andrico1234** [comment]
We noticed this behaviour as well, it looks like the new `Form` instead removes the need for renderProps, and the children should be rendered as regular React children. I think this may just need a documentation update?

It's a much neater pattern without the render props and required `form` element!

**Comment by slax57** [comment]
Hi!
Thank you for submitting this.
Indeed the doc needs to be updated on this point.
I'll do a PR right away to fix this.
Cheers

**Comment by fzaninotto** [comment]
Fixed by #7505
