### ISSUE TITLE
useUpdate notification

### ISSUE THREAD

**Issue by tiberiu1995** [marmelab/react-admin#7516]
**What you were expecting:**
I want to show a notification after the success/failure of update action. 

**What happened instead:**
After the response came from the api, the onSuccess/onFailure functions weren't executed.

**Steps to reproduce:**

**Related code:**

I took the sample from [https://marmelab.com/react-admin/Actions.html#](https://marmelab.com/react-admin/Actions.html#)
and edited according to my needs.

```
update("orders", record.id, record, {
      onSuccess: () => {
        redirect("/orders");
        notify("Order approved", { undoable: true });
      },
      onFailure: (error) =>
        notify(`Error: ${error.message}`, { type: "warning" }),
    });
```

**Environment**

* React-admin version: 3.19.10
* React version: 17.0.2
* Browser: Google Chrome

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
Let me add that such success side effects do work in our examples, and in our unit tests. The problem likely lies on your side.

**Comment by fzaninotto** [comment]
No news for some time, closing.
