### ISSUE TITLE
ArrayInput delete array when unmounted

### ISSUE THREAD

**Issue by ivandivito** [marmelab/react-admin#7517]
**What you were expecting:**
When I unmount a ArrayInput from a form i expect the form array value remains the same.

**What happened instead:**
When I unmount a ArrayInput from a form the component set the array value to undefined. This doesn't happen with other inputs like TextInput. 

**Steps to reproduce:**
Create a Form with a conditional redered ArrayInput and load some data in it. Then change the condition so the ArrayInput unmount. If you see the form value after that the array value is set to undefined.

**Other information:**
The ArrayInput implementation have this code.
```
    // We need to register the array itself as a field to enable validation at its level
    useEffect(() => {
        register(source);

        return () => {
            unregister(source);
        };
    }, [register, unregister, source]);
```
react-hook-form delete the form value when someone call unregister without keepValue option set to true.

**Environment**

* React-admin version: 4.0.0-rc.1
* React version: 17.0.2

**Comment by fzaninotto** [comment]
Fixed by #7525
