### ISSUE TITLE
CustomRoutes registered before Resources are being overridden by Resource routes

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7534]
# Problem

I want to extend some of the routes for a given resource. 

e.g. 

- list `/posts`
- edit `/posts/:postId`
- show `/posts/:postId/show`
- custom action/view `posts/:postId/customAction`

This seems to cause the `edit` view to display, even though the CustomRoute is registered first. 

You can view this behaviour in this [repro case](https://codesandbox.io/s/kind-babycat-tlgunl?file=/src/customRouteNoLayout.tsx)

Steps to reproduce:
1. Navigate to the following url: /#/posts/13/customLayout

You'll see that it renders the UI for `/#/posts/13`

I would expect that it would be caught by the custom route first, as the custom routes are defined before we defined the resources. 

It looks like `exact` isn't a valid property for `Route` either now

**Environment**

* React-admin version: 4.0.0.rc-1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi!
Thank you for submitting this.

I can't reproduce your problem with the codesandbox you provided.
- The route `posts/:postId/customAction` is never declared in your code (unless I missed it?)
- The route `posts/:postId/newAction` however, does work when I access it (although I needed to clean your customRouteWithNoLayout component because it contained errors)

Can you double check?

**Comment by andrico1234** [comment]
After digging into the problem a little more, it's due to a custom implementation of a TabbedForm that we have. In our custom routes we had somethng like this:

`/users/:userId/posts/:postId`, which renders a tab form. Because the tabs are synced with the URL, it looks like the router passes this route unless we explicitly define a view parameter like:

`/users/:userId/posts/:postId/:view`

I'll close this bug as it's due to a custom implementation on our side!
