### ISSUE TITLE
ReferenceArrayField is not passing data to child DataGrid or EditableDataGrid

### ISSUE THREAD

**Issue by gautiermarechal** [marmelab/react-admin#7543]
**What you were expecting:**
To have data fetched from ReferenceArrayField passed to the child EditableDataGrid

I am trying to display a datagrid of media of a product from a list of media ids. Using ReferenceArrayField component, the getMany() function of the media data provider is called. The fetching is working fine.

**What happened instead:**
The data fetched is not passed by the ReferenceArrayField component to its child EditableDataGrid.
I really don't get what is happening here, might be a bug.

**Steps to reproduce:**
The resource `mediaResource` is created, the ids `mediasIds` are passed to the `ReferenceArrayField`, the data is fetched. All the fetching works perfectly fine, but the `ReferenceArrayField` is not passing the fetched data to its child.

The component: 
```
function MediasList(): JSX.Element {
    return (
        <ReferenceArrayField fullWidth label="Médias" reference="mediaResource" source="mediasIds">
            <EditableDatagrid
                undoable
                createForm={<MediasForm children={undefined} />}
                editForm={<MediasForm children={undefined} />}
                rowClick="edit"
                hasCreate
            >
                <UrlField source="finalUrl" label="Miniature" target="_blank" />
                <TextField source="id" />
            </EditableDatagrid>
        </ReferenceArrayField>
    );
}
```

The edit page where the component is implemented:
```
<Edit {...props}>
            <SimpleForm>
                // Some irrelevant code here
                <MediasList />
            </SimpleForm>
        </Edit>
```

**Related code:**
The ReferenceArrayField doc: 
https://marmelab.com/react-admin/ReferenceArrayField.html

The EditableDataGrid doc:
https://marmelab.com/ra-enterprise/modules/ra-editable-datagrid

**Environment**

React-admin version: 3.19.7
React version: 17.0.2
React Admin EditableDataGrid version: 2.2.0
Browser: Chrome

**Comment by djhi** [comment]
Please follow the issue template

**Comment by WiXSL** [comment]
This is a `ra-enterprise` related question and has been addressed in the corresponding support channel, so I'm closing this issue

**Comment by slax57** [comment]
@gautiermarechal Any chance this is link to https://github.com/marmelab/react-admin/issues/7544 ?

**Comment by slax57** [comment]
Customer has confirmed the problem has been figured out.
(internal tracker issues 563 and 565)
Closing issue.
