### ISSUE TITLE
Form submission buttons with type button should show validation errors on pristine fields

### ISSUE THREAD

**Issue by slax57** [marmelab/react-admin#7555]
**What you were expecting:**
Clicking on a save button with `type="button"`, like "Save and Add", should show validation errors, even on pristine fields

**What happened instead:**
The notification "The form is not valid. Please check for errors" is displayed, but the validation errors are not shown below the fields.

**Steps to reproduce:**
Go to https://codesandbox.io/s/relaxed-cerf-88qx9i?file=/src/posts/PostCreate.tsx , change something in the form and then click "Save and Add".

**Environment**

* React-admin version: 4.0.0
* Last version that did not exhibit the issue (if applicable): 3.9.10 (probably)
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by afilp** [comment]
Thank you for fixing this.

You mentioned that if we use `yup`, then the "asterisks" cannot be shown unless we keep the `validate={required()}` on each field (while this code is not used for validation at all) 

![image](https://user-images.githubusercontent.com/7850073/163723302-5cf5ca88-3c5d-4076-83b5-8aaa364e5f1a.png)

This seems a little strange, as it creates a "false sense" of validation (if we forget to add the requirement in `yup`). Could we maybe have a different prop for showing an "asterisk" if we use `yup` (or any other resolver) and not need to have duplicate code for "required" validation? (i.e. both in `yup` for the actual validation and in the field itself just for the asterisk to be shown).

**Comment by slax57** [comment]
Hi @afilp 
Just noticed you can actually use the `isRequired` prop on your inputs, which seems to me to be exactly what we are looking for here (although it is not documented).

```tsx
<TextInput source="title" isRequired />
```

Does that fit your needs?
