### ISSUE TITLE
Docs reference Record type which does not exist

### ISSUE THREAD

**Issue by hjr3** [marmelab/react-admin#7560]
**What you were expecting:**

See this example: https://marmelab.com/react-admin/doc/4.0/Upgrade.html#list-views

```ts
import { useGetList, Record } from 'react-admin';
```

I expected the `Record` type to exist. Note: It did exist in v3. I could do `import { Record } from 'ra-core';`.

**What happened instead:**

```ts
import { useGetList, Record } from 'react-admin';
```

generates this error: `'"react-admin"' has no exported member named 'Record'`

I am pretty sure the type should be `RaRecord`, according to the code here: https://github.com/marmelab/react-admin/blob/953716c693c78695180e1c3c1ff38e7062c89264/packages/ra-core/src/types.ts#L12-L15

**Environment**

* React-admin version: v4
* Last version that did not exhibit the issue (if applicable): v3
* React version: NA
* Browser: NA
* Stack trace (in case of a JS error): `'"react-admin"' has no exported member named 'Record'`

**Comment by WiXSL** [comment]
You must use `RaRecord` instead of `Record`. This is also explained in the upgrade guide https://marmelab.com/react-admin/doc/4.0/Upgrade.html#record-was-renamed-to-rarecord
