### ISSUE TITLE
[Doc] 4.x doc search does not display section title correctly

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7565]
![Screenshot from 2022-04-17 14-33-30](https://user-images.githubusercontent.com/38666763/163729605-ac756522-f94f-4a77-ba30-92e2f258cda7.png)

**What you were expecting:**
I expect the section titles with `<` and `>` are not escaped

**What happened instead:**

Some of the section titles are escaped

**Other information:**

Additionally searching on 3.x docs will return results from 4.x and redirect to 4.x.

**Environment**

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi!
Thanks for submitting this.
We'll need to look into that shortly, thanks.
Regarding the version used by the search issue, this was already a problem before the release of the v4, the search always redirects to the latest version of the component's doc. I'm not sure we can change this, but we'll have a look.

**Comment by fzaninotto** [comment]
I've submitted the problem to the Algolia support a week ago, I haven't received any answer so far.

**Comment by fzaninotto** [comment]
After two hours of die and retry, I've finally managed to kill the boss - without any cheat code from the Algolia team. The search should work better now.
