### ISSUE TITLE
FileInput no longer passes source to `name` attribute, and instead `id` attribute

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7572]
FileInput no longer receives a `name` attribute. Instead it gets passed an `id` attribute instead.

The main problem for us is that it causes our E2E tests to fail (though this is something we will happily update), it also means that there are elements with duplicate IDs (HTML validation issue). e.g.:

![image](https://user-images.githubusercontent.com/17087167/164264549-4ffd0432-e4c7-491f-b8a2-13237c00c199.png)

This is a problem that exists in the CodeSandbox without any changes needed. 

Just jump into the `Create Post` page. Open the element inspector and move to the `input type="file"` element, and observe the problem

**Environment**

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Reproduced, thanks!
