### ISSUE TITLE
Missing typescript properties on DashboardMenuItem 

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#7575]
**What you were expecting:**
`DashboardMenuItem` passes all properties it receives to `MenuItemLink`; however types are different.

I am trying to pass `tooltipProps?: TooltipProps` to `DashboardMenuItem`, however typescript complaints that tooltipProps is invalid. This property, however, is allowed from `MenuItemLink`

**What happened instead:**
Typescript does not allow passing tooltipProps to `DashboardMenuItem`, however allows passing them to `MenuItemLink`

**Steps to reproduce:**
Uncomment @ts-ignore to see errors
```js
const DashboardMenuItem = (props: DashboardMenuItemProps) => {
	//@ts-ignore
	const tooltipProps = props.tooltipProps || ({} as TooltipProps)
	tooltipProps.PopperProps = { container: document.getElementById('tooltipsDiv') }
	//@ts-ignore
	return <DashboardMenuItemOrig {...props} tooltipProps={tooltipProps} />
}

```

**Related code:**
```js
export const DashboardMenuItem = (props: DashboardMenuItemProps) => {...}
```

**Environment**

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Thanks for submitting this!

**Comment by panfiva** [comment]
Also noticed that there are some attributes that are not used
```js
export interface DashboardMenuItemProps {
    locale?: string; // not used anywhere in the code
    onClick?: () => void;
    dense?: boolean;
    /**
     * @deprecated
     */
    sidebarIsOpen?: boolean;
}
