### ISSUE TITLE
Problem with linking two resources.

### ISSUE THREAD

**Issue by niksamoil** [marmelab/react-admin#7576]
Hi, I faced this issue when I tried to migrate the old version to the current.
I didn't find any information in the documentation, on how it works now.

**What you were expecting:**
In the previous version, we could add for example "option" for "good", or "address" for "supplier" being in the good or supplier component.

Let's say we have suppliers and addresses resources(1). In supplier(Show), we have a tab with addresses(3), and here in the tab we also have the "Add Address" button(2).

[Screenshot](https://prnt.sc/twxs3HiZg-06)

Clicking the "Add Address" button we were redirected to the Address(Create) resource. 

[Screenshot](https://prnt.sc/KRA85QX_tiV-)

Here in the Create Address resource, we could create an address assigned to the related supplier. The payload sent to the backend automatically included supplierId, and after clicking the "Save" button we were redirected back to the Supplier Addresses tab in the supplier show component.

Notice that when we added an address from the supplier,  in the Address create form we didn't have Input for a supplier, but we had it when we created the address directly from the Address resource.

**What happened instead:**
Now we only send payload without supplierId, and are not redirected back to the Supplier Addresses tab, as it was earlier.

**Environment**

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable): 2.9
* React version: 17.0.2
* Browser: Chrome

**Comment by slax57** [comment]
Hi!
Thank you for submitting this.
I agree, the doc is really poor on this topic. I'll mark it as a documentation bug.
In the meantime, you can find an example on how you can do this in the CRM demo: https://github.com/marmelab/react-admin/blob/master/examples/crm/src/companies/CompanyShow.tsx#L205

**Comment by niksamoil** [comment]
@slax57 thanks for your feedback, it works now, but only with one resource...

With something like this, it does still not work: 
```
<Button
      className={classes.button}
      variant="outlined"
      color="primary"
      size="small"
      component={Link}
      state={{ record: { goodId: record.id, supplierId: record.supplierId } }}
      to="/optionGroup/create"
      label={translate('ra.action.add_option_group')}
      title={translate('ra.action.add_option_group')}
/>
```

**Comment by djhi** [comment]
Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
No news for some time, closing. 

Besides, the ability to create a record related to another one is documented in https://marmelab.com/react-admin/Create.html#prefilling-the-form
