### ISSUE TITLE
v4.0.1 ImageInput dont support options for tsx

### ISSUE THREAD

**Issue by jnre** [marmelab/react-admin#7578]
**What you were expecting:**

imageinput has options prop for dropzone

**What happened instead:**

option prop of wrong type  

**Steps to reproduce:**

code in tsx component, import imageInput and put option as prop

**Related code:**

![image](https://user-images.githubusercontent.com/20430100/164424523-343a0bee-5f7f-4494-8060-39828cc25608.png)

**Other information:**

**Environment**

* React-admin version: v4.0.1
* Last version that did not exhibit the issue (if applicable):
* React version: v17.0.2
* Browser: edge
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi!
Thank you for submitting this.
Actually, the props are meant to be passed directly to the `ImageInput` component, not via an `options` prop, like this: `<ImageInput source="image" noDragEventsBubbling={false} />`
But the docs do not make this clear at all.
I'm marking this as a documentation issue.

**Comment by fzaninotto** [comment]
Actually, I see it more like a regression than a documentation issue.
