### ISSUE TITLE
Default buttons in custom toolbar for RichTextInput not re-rendering

### ISSUE THREAD

**Issue by witheroux** [marmelab/react-admin#7582]
When customizing the toolbar to provide a custom set of the default buttons, it would seem that a change in the state of the editor does not cause the button to re-render. It becomes impossible to add/modify a link through the Toolbar for example.

|Package|Version|
|------|-------|
|react-admin|4.0.1|
|react|17.0.2|

I've made an example forking the sandbox example : 
https://codesandbox.io/s/keen-brook-vkws1r?file=/package.json

The example is using the `PostEdit.tsx` `RichTextInput` for the body and uses the following reproduction scenario :
```jsx
<RichTextInput
    source="body"
    label=""
    validate={required()}
    fullWidth
    toolbar={<RichTextInputToolbar />}
/>
```

This example should result in the same thing as the default `<RichTextInput />` without a toolbar prop, but somehow, it's not the case. You can see in the screenshot below that despite having selected some text, the link button is not enabled.

![image](https://user-images.githubusercontent.com/7202656/164507489-5b4580a4-2eba-4d3e-95da-d6b1f0d9e326.png)

**Comment by djhi** [comment]
Reproduced, thanks for reporting it

**Comment by witheroux** [comment]
Great! Saw your PR. Just wanted to say that I specifically highlighted the fact that the link button doesn't work, but most of the default buttons are impacted by this. The ToggleButton's selected properties for most of the buttons (Format, List, Quote, etc.), doesn't update as the active element isn't updated.

**Comment by djhi** [comment]
Thanks for the details, I'll take a look
