### ISSUE TITLE
Fix right sidebar scrolling on documentation pages

### ISSUE THREAD

**Issue by bobah2000** [marmelab/react-admin#7589]
**What you were expecting:**
Vertical scrolling in right sidebar when there are many list items and the height of the viewport is not enough to place all of them.

**What happened instead:**
There are no scrolling and it is not possible to click on last list items

**Steps to reproduce:**
1. Visit react admin documentation page [https://marmelab.com/react-admin/Tutorial.html](https://marmelab.com/react-admin/Tutorial.html) 
2. Decrease the height of browser or open this page on display with low resolution

**Environment**

* React-admin version: 4.0.1 
* Browser: Google Chrome

![ra1](https://user-images.githubusercontent.com/51819476/165065728-4aa4effc-50aa-489f-9dbf-34d0ddac8be2.png)
![ra2](https://user-images.githubusercontent.com/51819476/165065746-5506221c-d8fc-48f9-b628-5d64c399f3cf.png)
![ra3](https://user-images.githubusercontent.com/51819476/165065777-d83d798d-ffb5-4607-aad1-320000aad260.png)

**Comment by djhi** [comment]
Thanks for reporting this!

**Comment by fzaninotto** [comment]
I've reduced the font size for the table of contents. In my experience, it renders correctly even on small screens (tested with a height of 750px). 

Perhaps we should simply hide the ToC for screens with smaller height. 

Making it low priority though.
