### ISSUE TITLE
dataProvider error. Check the console for details. 

### ISSUE THREAD

**Issue by neps-in** [marmelab/react-admin#7597]
dataProvider error. Check the console for details. 
The response to 'getList' must be like { data : [...] }, but the received data is not an array. The dataProvider is probably wrong for 'getList'

trying a minimalist code that is breaking.

```
import drfProvider from 'ra-data-django-rest-framework';

const dataProvider = drfProvider('http://127.0.0.1:8000/api');
const App = () => (
<Admin  dataProvider={dataProvider} >     
        <Resource name="users/list" options={{ label: 'Users' }} list={UserList} />
</Admin>
);
```

**What you were expecting:**
To get the response rendered.

**What happened instead:**
dataProvider error. Check the console for details. 
The response to 'getList' must be like { data : [...] }, but the received data is not an array. The dataProvider is probably wrong for 'getList'

## response without data key inserted.

```
[
    {
        "fullname": "QR Fl",
        "username": "qr"
    },
    {
        "fullname": "OP Fn",
        "username": "opfn"
    },
]
```

Hence made my DRF backend to spit out as JSON response with

## Response with data key inserted.
```
{
    "data": [
        {
            "fullname": "QR Fl",
            "username": "qr",
            "email": "qr@qr.com"
        },
        {
            "fullname": "OP Fn",
            "username": "opfn",
            "email": "op@op.com"
        }
    ]
}
```

But still the problem persists.

### Package.json
```
{
  "name": "djrauth-ra-clientv2",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@mui/styles": "^5.6.2",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.1.1",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^0.26.1",
    "ra-data-django-rest-framework": "^0.2.1",
    "ra-data-fakerest": "^4.0.1",
    "ra-data-simple-rest": "^4.0.1",
    "react": "^18.0.0",
    "react-admin": "^4.0.1",
    "react-dom": "^18.0.0",
    "react-query-devtools": "^2.6.3",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

Saw this post too https://stackoverflow.com/questions/57297317/the-response-to-get-list-must-be-like-data-but-the-received-data
it was not helpful though.

Whats causing the issue. Give some light on debugging this issue.

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
also, this looks related to 'ra-data-django-rest-framework', which we don't maintain. Please open an issue in their repository instead.

**Comment by neps-in** [comment]
No this is not the issue from 'ra-data-django-rest-framework' because the same code was working for react admin v 3.19. Now when I moved to 4.0.1 this error is coming. Hence Its the flaw in react admin. 

@djhi This is a very very basic app,  Hence creating a sandbox is overkill.  Also one thing you guys can do is you can document about what each API  expects as a response for react admin to work. and headers any does the API expects along with the response. May be this Resource getlist may be a starting point, and you can go over one by one.

**Comment by fzaninotto** [comment]
React-admin is API agnostic and requires no headers as it doesn't speak HTTP. This is the responsibility of your data provider. The request and response formats for the data provider are documented here: https://marmelab.com/react-admin/DataProviderWriting.html

If you can't provide a repro, we can't fix the bug. You might think this is overkill, but it allows you to prove that the problem is actually on the react-admin side - and not on your side.

**Comment by priyatamnayakwsp** [comment]
am getting the same issue, am using 'ra-data-simple-rest'


validateResponseFormat.js:15 The response to 'getList' must be like { data : [...] }, but the received data is not an array. The dataProvider is probably wrong for 'getList'

**Comment by slax57** [comment]
@priyatamnayakwsp at its core, `ra-data-simple-rest` basically simply returns whatever the REST API responds. 
We are using `ra-data-simple-rest` with `fakerest` in our [Demo](https://marmelab.com/react-admin-demo/) without any issues, so the problem is probably not with `ra-data-simple-rest`.
Please double check your API.
If you are still convinced there is a bug in one of the react-admin packages, then please open a new issue.
