### ISSUE TITLE
QuickFilter in List view is replaced by "Save query" in listFilter array when toggled

### ISSUE THREAD

**Issue by joobacca** [marmelab/react-admin#7600]
**What you were expecting:**
When using QuickFilters (as described as [here](https://marmelab.com/react-admin/FilteringTutorial.html#quick-filters)), the toggling via the "Add Filter" button should work. The toggled QuickFilter option should disappear from the "Add Filter" dropdown.

**What happened instead:**
After I have enabled the quick filter, the dropdown of the "Add Filter" button shows a new entry instead of the activated QuickFilter, which shows the "Save current query" function even though it is not explicitely enabled anywhere.

**Steps to reproduce:**
The bug is reproducible in the [default RA CodeSandbox of v4](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)

**Related code:**

```es6
const postFilter = [
    <SearchInput source="q" alwaysOn />,
    <TextInput source="title" defaultValue="Qui tempore rerum et voluptates" />,
    <QuickFilter
        label="resources.posts.fields.commentable"
        source="commentable"
        defaultValue
    />,
];
```

**Other information:**
![QuickFilter bug](https://i.imgur.com/vx2MfAP.gif "QuickFilter bug")

**Environment**

* React-admin version: 4.0.1
* React version: 17.0.2
* Browser: Chrome Version 100.0.4896.60

**Comment by slax57** [comment]
Reproduced, thanks!

**Comment by fzaninotto** [comment]
I don't understand that this is a bug. 

The filter button isn't a toggle button: it only shows the non-active filters. To disable a filter, you have a cross button on its left. 

The "save query" menu entry enables as soon as you have an active filter. 

So everything looks normal to me the way it is. 

Could you explain again why you think this is a bug?

**Comment by fzaninotto** [comment]
I think the current documentation is correct:

- the save query option is enabled by default *as long as there is something to save*, i.e. not until the user adds at least one filter
- the GIF for the quickfilter shows adding the quickfilter with the menu and removing it with the cross. Each time the user opens the filter menu, there is no active filter, so there is no "Save query"

There is no way to disable the save current query option.

**Comment by joobacca** [comment]
@fzaninotto The gif is showing how the user adds a second filter (and how there is no "Save current query"-option), could you take a look at it again? It might need an update if there really is no way to disable the save current query option and if it was added with the version update (v3 -> v4).

Thank you!

**Comment by fzaninotto** [comment]
again, I don't understand what's wrong with the GIF. I don't see the user adding a second filter. Please explain again the suer scenario.

**Comment by joobacca** [comment]
@fzaninotto The filter "Tagged Code" is added, then "Low views", after the user hovers over the active chips in the List.

**Comment by fzaninotto** [comment]
Ah, right: The GIF from the documentation that you pointed does indeed need to be updated. 

https://marmelab.com/react-admin/FilteringTutorial.html#quick-filters

![gif](https://marmelab.com/react-admin/img/quick_filters.gif)

**Comment by adrianszablowski** [comment]
I have the option to disable `<Quick Filters>` completely?
