### ISSUE TITLE
[Doc] Outdated page appeared in latest doc

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7615]
**What you were expecting:**

I expect accessing an outdated page on latest documentation should show 404 not found, or at least show the page is outdated.

**What happened instead:**

Outdated page is accessible in latest doc, which is very very confusing.
I have previously saved a page as bookmark, and the content in the page is no longer reflecting latest practice used in v4

**Steps to reproduce:**

Go to https://marmelab.com/react-admin/CreateEdit.html (Assume you are accessing from a bookmark)
Also this one https://marmelab.com/react-admin/doc/4.0/CreateEdit.html
On the left corner it will show `latest(4.0.2)` however this documentation is for v3

**Related code:**

```
https://marmelab.com/react-admin/doc/4.0/CreateEdit.html
```

**Other information:**

**Environment**

* React-admin version: 4.0.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting this

**Comment by fzaninotto** [comment]
It's now fixed, thanks again!
