### ISSUE TITLE
Pipe as filter operator breaks TextInput

### ISSUE THREAD

**Issue by mediafreakch** [marmelab/react-admin#7618]
**What you were expecting:**  

Using a pipe operator (`|`) as part of the value for `source` in a `<TextInput />` filter is possible in 4.0.2 like it is in 3.x. 

**What happened instead:**  

`<TextInput />` doesn't allow to enter any characters anymore

**Related code:**

```
import { Datagrid, TextField, List, TextInput } from 'react-admin'

const filters = [
  <TextInput label="Lookup name" source="name|contains" alwaysOn />,
]

const DataloggersList = () => {
  return (
    <List filters={filters}>
      <Datagrid>
        <TextField source="id" />
        <TextField source="name" />
      </Datagrid>
    </List>
  )
}

export default DataloggersList
```

**Additional information**

- Relevant part of documentation: https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators
- As a workaround, one can use `_` or `/`, both work.

**Environment**

* React-admin version: 4.0.2
* Last version that did not exhibit the issue (if applicable): 3.17.3
* React version: 18.1.0
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting this.

This seems to be a limitation of `react-hook-form` as shown in this [codesandbox](https://codesandbox.io/s/react-hook-form-js-forked-ehnheg?file=/src/App.js). There's nothing we can do about it so you might want to open an issue in their repository.
