### ISSUE TITLE
Form level validation doesn't affect multiple inputs

### ISSUE THREAD

**Issue by nathan-britten** [marmelab/react-admin#7620]
**What you were expecting:**

I have form level validation that looks at the two different inputs. The mode is set to onChange. 

When text is removed from both inputs, an error message should display underneath both inputs as they have both been touched. 

When I enter a value into either input the error messages on both should disappear. 

**What happened instead:**

When a value is entered into an input the error message only disappears from that input, rather than both error messages disappearing. 

**Steps to reproduce:**
1. Go to https://codesandbox.io/s/beautiful-bhabha-h670m6?file=/src/posts/PostEdit.tsx
2. Navigate to a post and edit. 
3. Remove the title and teaser
4. See both error messages
5. Add text to one input.
6. See that only one error message disappears

**Related code:**
https://codesandbox.io/s/beautiful-bhabha-h670m6?file=/src/posts/PostEdit.tsx

**Other information:**

**Environment**

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Reproduced, thanks

**Comment by fzaninotto** [comment]
This is a react-hook-form bug, I can reproduce it without react-admin: https://codesandbox.io/s/serene-gates-e17zfj

Please open an issue in the react-hook-form repository instead.
