### ISSUE TITLE
Custom key for SingleFieldList component

### ISSUE THREAD

**Issue by joobacca** [marmelab/react-admin#7621]
**Is your feature request related to a problem? Please describe.**
The `SingleFieldList` component automatically sets the `id` prop of the iterating list objects as the needed [React key prop](https://reactjs.org/docs/lists-and-keys.html#keys). While this is enough in most cases, sometimes the objects may not have an `id` prop. This leads to an error thrown by React, which probably most React developers have seen at some point: `Warning: Each child in a list should have a unique "key" prop.`

For example, I have an array of translated name objects for each of my resource, let's say, `post`:

```es6
const postData = {
    ...someDatas,
   name: [
    { translation: 'Foo', iso: 'en-US' },
    { translation: 'Bar', iso: 'de-DE' },
  ],
};
```

**Describe the solution you'd like**
The `SingleFieldList` component could accept a string (or a function for even more customizable key props) as `customKey` prop to set. To achieve this, two changes would be necessary (as far as I can tell):

- Extension of the `SingleFieldListProps` with a `customKey` prop, typed with `string`. As for the function to work, it would probably need to make usage of the `RecordType` and look like `(record: RecordType) => string;` maybe, but I'm unsure what this would look like in particular.
- Destructuring and making usage of the new `customKey` prop, which will get null-checked and used before the `record.id` value.

**Comment by djhi** [comment]
Duplicate of #7614?

**Comment by joobacca** [comment]
@djhi Yes, I don't think it's necessary to be able to customize the key if the solution provided to #7614 works with multiple `SingleFieldList` components.
