### ISSUE TITLE
useRegisterResource is not exported

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#7623]
**What you were expecting:**
useRegisterResource should be exported in react-admin

**What happened instead:**
useRegisterResource is no longer exported in 4.0.2

Recevied error when importing useRegisterResource 
```
TS2305: Module '"react-admin"' has no exported member 'useRegisterResource'.
``` 

**Environment**

* React-admin version: 4.0.2
* Last version that did not exhibit the issue (if applicable): 4.0.1
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Why did you use this hook? As far as I know, it was not documented anywhere - to put it otherwise, a private API.

**Comment by panfiva** [comment]
Here is a component that we created that we use in custom routes, so that RA features work properly.

```js
/**
 * This component will register resource in resource ResourceDefinitionContext in React-Admin
 * If a resource is not registered in ResourceDefinitionContext, some generic functions in List, Create, Edit and Show will not work properly
 * For example, Create button will be missing on List component
 *
 * @example
 * <ResourceWithReg name='users' list={UserList} />
 */
export function ResourceWithReg(props: ResourceProps) {
	const def: ResourceDefinitions = useResourceDefinitions()

	const { name, create, edit, list, show, icon } = props

	const hasList = !!list
	const hasCreate = !!create
	const hasEdit = !!edit
	const hasShow = !!show

	const registerResource = useRegisterResource()

	const isRegistered = !!def[props.name]

	useEffect(() => {
		if (!isRegistered) {
			console.debug(`Registering "${name}" resource`)
			registerResource({ name, hasList, hasCreate, hasEdit, hasShow, icon })
		}
	}, [registerResource, isRegistered, name, hasList, hasCreate, hasEdit, hasShow, icon])

	if (isRegistered) return <Resource {...props} />
	else return null
}

export default ResourceWithReg
```

**Comment by panfiva** [comment]
An example of a page that we render under /ad_accounts/9513/show/ad_accounts_log/27075/show

Change Log table is a List from `ad_accounts_log` resource that is related to AD account `ad_accounts` id=9513;

Additional details are a record `ad_accounts_log` = 27075

To make all features work properly, before we render `ad_accounts_log` , we modify basePath from "" to "/ad_accounts/9513/show/"; after that, all React-Admin components work well, as long as resource is registered

![image](https://user-images.githubusercontent.com/48455289/166500651-08ff2a90-b212-441c-b628-bd9207953de6.png)

**Comment by panfiva** [comment]
An alternative solution is to update React-Admin's `<Resource/> component to check if resource is registered, and register the resource before returning child components.

**Comment by smeng9** [comment]
@panfiva Here is the linked pull request, and the use case is mentioned there, https://github.com/marmelab/react-admin/pull/7455

You can still use the `const { register: registerResource } = useResourceDefinitionContext();` to register.

I also noticed the method is no longer exported when upgrading to 4.0.2. If we still want to support this use case we can add an example in documentation.

**Comment by fzaninotto** [comment]
So the `useRegisterResource` hook was refactored in https://github.com/marmelab/react-admin/pull/7539, and became `useResourceDefinitionContext`. The syntax has changed, but it is still exported. You will need to update your code to make it work with 4.0.2 and further releases. 

We still consider this hook internal API though, so we won't document it or support its usage outside of react-admin modules. The official way of adding resource at runtime is documented at https://marmelab.com/react-admin/Admin.html#declaring-resources-at-runtime.
