### ISSUE TITLE
Typescript identifies no record prop on Edit component

### ISSUE THREAD

**Issue by wongathon** [marmelab/react-admin#7624]
Typescript error passing record prop to Edit component, prop does not exist and component not reading record override

<img width="526" alt="image" src="https://user-images.githubusercontent.com/8127658/166500561-59ac9466-5a17-44ae-b46b-037aaa3ffce8.png">

Attempting to render only if transformedRecord exists - still retrieves from resource getOne and not using supplied transformedRecord

<img width="353" alt="image" src="https://user-images.githubusercontent.com/8127658/166500738-bb7d5e60-0905-43e3-9168-4ac61a8a00c9.png">

TS error ignore-override -- still does not use supplied transformedRecord
<img width="354" alt="image" src="https://user-images.githubusercontent.com/8127658/166500926-ced08653-8e6b-4869-92d6-548badfcbd47.png">

As seen in docs, it should be there: https://marmelab.com/react-admin/Edit.html#record

**Comment by fzaninotto** [comment]
Thanks for the report. I think the documentation is erroneous - `<Edit>` does not and should not accept a custom `record`.
