### ISSUE TITLE
Ambiguous <FilterList/> selection in demo

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7626]
**What you were expecting:**

I want to apply just one filter at a time.

**What happened instead:**

Applying one filter gets the other one selected.

**Steps to reproduce:**

Goto: https://marmelab.com/react-admin-demo/#/customers?filter=%7B%22last_seen_gte%22%3A%222022-05-01T05%3A00%3A00.000Z%22%7D&order=DESC&page=1&perPage=25&sort=last_seen

Click `This Week` in the filter, you will see `This Month` is also selected.

This seems only happen when the first day is Sunday.

![Screenshot from 2022-05-03 18-12-45](https://user-images.githubusercontent.com/38666763/166588411-408b2bd5-7b78-4584-84bb-9001b1976da3.png)

**Related code:**

Need to use `lte` to differentiate week from month
```
https://github.com/marmelab/react-admin/blob/master/examples/demo/src/visitors/VisitorListAside.tsx#L50
```

**Other information:**

**Environment**

* React-admin version: 4.0.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Is it really a bug? If the month starts on a Sunday, and I'm on the first week, "this week" and "this month" are indeed the same filter. 

Anyway, this concerns the e-commerce demo, so I'm marking it as a documentation issue.
