### ISSUE TITLE
Can no longer override SimpleFormIterator styles

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7629]
**What you were expecting:**
In RA v3 we were able to override the SimpleFormIterator styles from within our Theme component, but it seems that with the upgrade to v4, this is something we can no longer do

You can see from the  [repro case](https://codesandbox.io/s/zealous-lalande-nvnlyx?file=/src/index.tsx) that we're applying styles to both the RaEdit component RaSimpleFormIterator. The styles are being applied to the Edit form, but none are being applied to the SimpleFormIterator.

I've also tried a number of different selectors and they don't work.

I'll be happy to open a PR to resolve this. I imagine that it was a small oversight, and would be a straight forward fix

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Thanks for submitting this! 🙂 
I'll just wait for another member of the team to validate your PR and we will be good to go!
