### ISSUE TITLE
SingleFieldList hasn't empty props

### ISSUE THREAD

**Issue by atcg01** [marmelab/react-admin#7634]
When using ReferenceArrayField, the emptyText props isn't available. Instead the doc say that we should use the child empty props. The Datagrid component has an empty props but the SingleFieldList hasn't

**Comment by djhi** [comment]
Thanks for reporting this.

**Comment by simonneaves** [comment]
Hi, just checking if there is any update on this. We're still on RA3, is this fixed in RA4 perhaps?

**Comment by atcg01** [comment]
Hi, yes it is fixed in 4.2.7

**Comment by slax57** [comment]
Closed via https://github.com/marmelab/react-admin/pull/9439
