### ISSUE TITLE
`disableRemove` doesn't pass down record object

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7644]
It seems that the following code will always log out an empty object in the console.

```
<ArrayInput source="resourcePools" label="CP Resource Pools" level={2}>
        <SimpleFormIterator
          disableRemove={record => {
            console.log(record);
            return true
          }}
        >
            ...
        </SimpleFormIterator>
</ArrayInput>
```

**What you were expecting:**
To be given the record of the current ArrayInput iterable

**Steps to reproduce:**
If you go to the [repro case](https://codesandbox.io/s/upbeat-thunder-3j4pdk?file=/src/posts/PostEdit.tsx)

- Navigate to the PostEdit page
- Add a new post_id
- Click save
- Click back into the record

You'll observe that the input is populated, but no data is being passed through to the `disableRemove` function

**Related code:**

* Preferably, a CodeSandbox forked from 
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Reproduced, thanks!

**Comment by andrico1234** [comment]
I'll be happy to take a pass at this!
