### ISSUE TITLE
custom resource functional component are not inserted under admin

### ISSUE THREAD

**Issue by benoit38** [marmelab/react-admin#7648]
```
import * as React from "react";
import { Admin, Resource, ListGuesser } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');

const MyResource=(props)=>(<Resource {...props} />)

const App = () => <Admin dataProvider={dataProvider}>
<MyResource name="users" list={ListGuesser}/>
</Admin>;

export default App;
```

* React-admin version: 4
 
"Error" message:
Your application is properly configured.
Now you can add a `<Resource>` as child of `<Admin>`.

**Comment by djhi** [comment]
Yes, custom Resource components are not supported. Would you mind explaining your use case?

**Comment by benoit38** [comment]
Thanks for your answer. My goal was to have each Resource component in its own file for code organization and import them from the Admin component.

**Comment by djhi** [comment]
You can follow the pattern we use in all our projects:

export all components for a resource from their [index](https://github.com/marmelab/react-admin/blob/master/examples/simple/src/comments/index.tsx) file, import them as a [single object](https://github.com/marmelab/react-admin/blob/master/examples/simple/src/index.tsx#L8) in the admin and [spread](https://github.com/marmelab/react-admin/blob/master/examples/simple/src/index.tsx#L34) this object on the `Resource`.
