### ISSUE TITLE
<SaveButton /> documentation

### ISSUE THREAD

**Issue by Cimanel** [marmelab/react-admin#7649]
**What you were expecting:**

When I want to see whats are the SaveButton props, I want them to be explain at the [SaveButton documentation.]( 
https://marmelab.com/react-admin/Buttons.html#savebutton)

**What happened instead:**

 There is nothing on the [SaveButton documentation.]( 
https://marmelab.com/react-admin/Buttons.html#savebutton)

**Other information:**

I have to go to the [toolbar simple form documentation](https://marmelab.com/react-admin/SimpleForm.html#:~:text=to%20the%20prop-,alwaysEnable,-%3A) to see the ```alwaysEnable``` prop of the SaveButton

* React-admin version:4.0.2

**Comment by fzaninotto** [comment]
I don't understand the problem: `<SaveButton alwaysEnabled>` is properly documented in https://marmelab.com/react-admin/SaveButton.html#alwaysenable
