### ISSUE TITLE
When using FormDataConsumer, changes to defaultValue are reflected in the TextInput

### ISSUE THREAD

**Issue by hjr3** [marmelab/react-admin#7657]
**What you were expecting:**

When using `FormDataConsumer`, changes to `defaultValue` are reflected in the `TextInput`

**What happened instead:**

Only the initial default value is shown in `TextInput`

**Steps to reproduce:**

See CodeSandbox

**Related code:**

See https://codesandbox.io/s/stupefied-kate-0h06qr?file=/src/posts/PostCreate.tsx

```tsx
        <FormDataConsumer>
          {({ formData, ...rest }) => {
            const title = formData.title ?? "";

            // in v3, the updated title would show in the below text input
            return (
              <TextInput
                source="foo"
                defaultValue={title}
                validate={required()}
                {...rest}
              />
            );
          }}
        </FormDataConsumer>
```

**Other information:**

**Environment**

* React-admin version: v4
* Last version that did not exhibit the issue (if applicable): v3
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi!
Indeed, this is not supported (at least not this way) by react-hook-form.
You can probably use this answer to come up with a workaround: https://stackoverflow.com/a/66268317/3975522
