### ISSUE TITLE
`simple` example: `unable to resolve dependency tree` (`npm`)

### ISSUE THREAD

**Issue by strarsis** [marmelab/react-admin#7659]
**What you were expecting:**
`npm` should install all dependencies for the [`simple`](https://github.com/marmelab/react-admin/tree/master/examples/simple) example project.

**What happened instead:**
`npm` error occurs: `unable to resolve dependency tree` (see npm log at the end)

**Steps to reproduce:**
1. Clone this `react-admin` repository.
2. `cwd` into `examples/simple` directory of the `simple` example project.
3. (Optional step) Use `nvm use 16.15.0` to use a LTS `node` version.
4. Invoke `npm install` to install the dependencies.
Note that a `npm` error occurs: `unable to resolve dependency tree` (see npm log at the end)

**Environment**

* React-admin version: `4.0.3`
* Last version that did not exhibit the issue (if applicable): (not applicable)
* React version: `17.0.0`
* Browser: (not applicable)
* Stack trace (in case of a JS error):
````
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: simple@4.0.3
npm ERR! Found: webpack@5.70.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"~5.70.0" from simple@4.0.3
npm ERR!   examples/simple
npm ERR!     simple@4.0.3
npm ERR!     node_modules/simple
npm ERR!       workspace examples/simple from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from ignore-not-found-export-plugin@1.0.1
npm ERR! node_modules/ignore-not-found-export-plugin
npm ERR!   dev ignore-not-found-export-plugin@"^1.0.1" from simple@4.0.3
npm ERR!   examples/simple
npm ERR!     simple@4.0.3
npm ERR!     node_modules/simple
npm ERR!       workspace examples/simple from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
````

**Comment by slax57** [comment]
Hi!
Internally we mostly use yarn as package manager, but npm should work fine too.
However, I just tried `npm install` inside the simple exemple, and it worked without any error. 🤷 
I have attached the package-lock.json file it has juste generate. 
Node v16.15.0
Npm 8.5.5
[package-lock.json.txt](https://github.com/marmelab/react-admin/files/8650650/package-lock.json.txt)

**Comment by strarsis** [comment]
@slax57: Re-running `npm install` (after purging the `node_modules/` directory before that) fixed the issue.
It is great that it works now, but it still shouldn't have happened on the first run...

**Comment by slax57** [comment]
I agree. But it's hard for me to work on it without being able to reproduce.
Anyway, I'm glad it's fixed.
Thanks for the feedback.

**Comment by MuhammadsolihGofurov** [comment]
i have problem that is relaeted it
please who can help me ?

**Comment by dsight** [comment]
While resolving: admin@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.3
npm ERR! node_modules/flux
npm ERR!   flux@"^4.0.3" from the root project

How can i resolve this?

**Comment by djhi** [comment]
@dsight please open a new issue and follow the issue template

**Comment by KeyOnTech** [comment]
> While resolving: admin@0.1.0 npm ERR! Found: react@18.2.0 npm ERR! node_modules/react npm ERR! react@"^18.2.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.3 npm ERR! node_modules/flux npm ERR! flux@"^4.0.3" from the root project
> 
> How can i resolve this?

@dsight I'm working on a project completely different than this project and getting the exact same issue..???
but when you check the react web site it shows that is the latest version...

I only found your posting by Google'ing the issue your post here came up so your not alone on having issues npm installing react

anyone wanting to recreate - delete your package.lock file and you node modules folder it will not pull react 18.2.0 for some reason today..???

**Comment by dsight** [comment]
> > While resolving: admin@0.1.0 npm ERR! Found: react@18.2.0 npm ERR! node_modules/react npm ERR! react@"^18.2.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.3 npm ERR! node_modules/flux npm ERR! flux@"^4.0.3" from the root project
> > How can i resolve this?
> 
> @dsight I'm working on a project completely different than this project and getting the exact same issue..??? but when you check the react web site it shows that is the latest version...
> 
> I only found your posting by Google'ing the issue your post here came up so your not alone on having issues npm installing react
> 
> anyone wanting to recreate - delete your package.lock file and you node modules folder it will not pull react 18.2.0 for some reason today..???

thank you. it frustrating.. I have been trying to resolve this issue for over 48hrs

**Comment by dsight** [comment]
> 

i have it fixed.. if you have shards-react as a dependency, that is probably the cause, replace "shards-react" with "darizabalo/shards-react#master" that should fix it
