### ISSUE TITLE
is it possible to disable localStorage DataGrid settings for some tables?

### ISSUE THREAD

**Issue by ogroppo** [marmelab/react-admin#7670]
**Scenario**
Nesting DataGrid into the expand of a DataGrid row. I.e. Creating subcategories for product categories.

**Problem**
If a row is repeated, all rows will collapse/expand but also all tables will sort because it's all the same resource.
e.g. `RaStore.category.datagrid.expanded`
In the extreme case of a circular reference the browser crashes.

**Possible solutions**
- Assign stored settings to a (table) id instead of resource name (ideal, but I guess hard)
- disable storage for some view/resources?

**Comment by slax57** [comment]
Hi.
Indeed, this is not something that we currently support.

You can try to work on implementing it yourself, or you may consider requesting some [Professional Services](https://marmelab.com/ra-enterprise/) to have our team help you in the process.
