### ISSUE TITLE
Lack of documentation about addField

### ISSUE THREAD

**Issue by niksamoil** [marmelab/react-admin#7676]
**What you were expecting:**
Hi, in your major update to version 4.0 you've removed HOCs like addField, and I didn't find any information about replacing it according to the new version.

Example code:
```
import { addField } from 'ra-core';

const FileUploader = () => {};

const StyledFileUploader = withStyles(styles)(FileUploader);

export const S3FileInput = addField(StyledFileUploader);
```

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable): 2.9
* React version: 17.0.2
* Browser: Chrome

**Comment by djhi** [comment]
`addField` used to wrap custom inputs inside `react-final-form` `Field` component. As we changed the form library to `react-hook-form`, the way to create custom inputs has changed to. You can find the instructions [here](https://marmelab.com/react-admin/Inputs.html#writing-your-own-input-component). Make sure you read the whole section until you reach the `useInput` hook.
