### ISSUE TITLE
combineDataProviders function is not exported from `react-admin`

### ISSUE THREAD

**Issue by bleafman** [marmelab/react-admin#7680]
**What you were expecting:**

Hey `react-admin` team! I was looking at the docs for Data Providers and it says that there should be a `combineDataProviders` method exported from `react-admin`. ([link to section](https://github.com/marmelab/react-admin/blob/master/docs/DataProviders.md#combining-data-providers). 

However when I try to import the method, it appears that it does not exist. (Searching the code, it also doesn't show up). 

**What happened instead:**

No `combineDataProviders` method is exported from the `react-admin` package.

I can write my own but it'd be preferable to use an official one if it exists :)

**Steps to reproduce:**

Create a new project (or an existing project that is on `4.0.3`) and add this line to your code.

```typescript
import { combineDataProviders } from 'react-admin';
```

You should see a `Module '"react-admin"' has no exported member 'combineDataProviders'.` error.

**Related code:**

* Preferably, a CodeSandbox forked from 
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.0.3
* Last version that did not exhibit the issue (if applicable): N/A
* React version: ^17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
I cannot reproduce the problem on the `master` branch (see the [working example on CodeSandbox](https://codesandbox.io/s/muddy-monad-m9jkgq?file=/src/index.tsx)).

There must be a problem in the version of the packages you use.
