### ISSUE TITLE
`ReferenceArrayInput` with `AutocompleteArrayInput` throws error if the array is empty

### ISSUE THREAD

**Issue by ogroppo** [marmelab/react-admin#7685]
**What you were expecting:**
I expect the autocomplete to be empty for no references returned i.e. {data: [], total: 0}

**What happened instead:**
The page throws error
`TypeError: Cannot read properties of undefined (reading 'length')`

**As soon as I create a `Tag`, the form is happy**

**Steps to reproduce:**
Create a form that relies on a many-to-many rels, i.e. a classic Posts-Tags

```
export const PostCreate = (props: CreateProps) => (
  <Create title="New post" {...props}>
    <SimpleForm>
      <TextInput source="text" />
      <ReferenceArrayInput label="Tags" reference="tag" source="tags">
        <AutocompleteArrayInput />
      </ReferenceArrayInput>
    </SimpleForm>
  </Create>
);
 ```
 
<img width="880" alt="Screenshot 2022-05-11 at 16 37 46" src="https://user-images.githubusercontent.com/4820803/167891740-0d0d0878-c550-410f-b6a0-1bbe3b863858.png">

**Comment by slax57** [comment]
Reproduced, thanks!
