### ISSUE TITLE
The FilterButton is present with all filters children having the alwaysOn option being set

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#7689]
**What you were expecting:**

When I have all my filter being show by default:

```typescript
const UserFilter: FC<Omit<FilterProps, 'children'>> = (props) => (
  <Filter {...props}>
    <SearchInput source="$search" alwaysOn />
    <BooleanInput source="isDriver" label="Chauffeur" alwaysOn />
  </Filter>
);
```

The additional filter button should not appears.

**What happened instead:**

The button appears with an obvious empty filter list, making it useless.

**Steps to reproduce:**

Checkout the following PR and start the application.

**Related code:**

https://github.com/soullivaneuh/react-admin-sandbox/pull/2

**Other information:**

**Environment**

* React-admin version: 4.0.3
* Last version that did not exhibit the issue (if applicable): 3.19.7
* React version: 18.1.0

**Comment by fzaninotto** [comment]
Reproduced, thanks!
