### ISSUE TITLE
validation of  ArrayInput and its children is conflict.

### ISSUE THREAD

**Issue by bingluen** [marmelab/react-admin#7692]
**What you were expecting:**

ArrayInput validation can work with its children validation. And ArrayInput validation should be triggered at the same time as its children.

**What happened instead:**

1. The validation result of ArrayInput is overwritten by its children's validation after children's validation triggered. 
2. ArrayInput's validation be triggered at its children changed.  

**Steps to reproduce:**

1. Set `mode=onSubmit` on form component. (optional, make observation easy)
2. trigger `ArrayInput` validation ([ArrayInput.tsx#126](https://github.com/marmelab/react-admin/blob/v4.0.3/packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.tsx#L126))
3. print `form.formState.errors`, you can see a error message of `ArrayInput` be include with key equal to `source` value of `ArrayInput`.
4. trigger children's validation.
5. print  `form.formState.errors` again, the property of `form.formState.errors` which with key equal to `source` of `ArrayInput` is overwritten by an array of error bag object of `ArrayInput`'s children.

**Related code:**
```jsx=
<ArrayInput
    source="peoples" validate={value => value.length > 2 ? undefined : 'Must give least 2 peoples'}>
    <TextInput source="firstName" validate={required('This field is required')} />
    <TextInput source="lastName" validate={required('This field is required')} />
</ArrayInput>
```
The error bag of form (`form.formState.errors`):
```typescript=
// If exist error on its children.
{
    errors: {
        peoples: [
            { firstName: 'This field is required', lastName: 'This field is required' },
            { firstName: 'This field is required', lastName: 'This field is required' },
        ]
    }
}
```
```typescript=
// If did not exists errors on its children
{
    errors: {
        peoples: []
    }
}
```

**Environment**

* React-admin version: 4.0.3
* React version:  17.0.2
* Browser: Microsoft Edge 100 / Firefox 100

**Comment by slax57** [comment]
Reproduced, thanks!
