### ISSUE TITLE
[4.0 Migration] Unable to await updateMany()

### ISSUE THREAD

**Issue by mediafreakch** [marmelab/react-admin#7695]
**What you were expecting:**

In v3.19.x I used to be able to `await updateMany()` using the `returnPromise: true` mutationOption.  

**What happened instead:**

Does not work in v4.x. However it's still available with `useUpdate()`.

If this change is intended could you outline in the migration docs how to mitigate this breaking change?

**Steps to reproduce:**
-

**Related code:**

- [useUpdate](https://github.com/marmelab/react-admin/blob/v4.0.4/packages/ra-core/src/dataProvider/useUpdate.ts#L292) (working in v4)
- [useUpdateMany](https://github.com/marmelab/react-admin/blob/v4.0.4/packages/ra-core/src/dataProvider/useUpdateMany.ts#L290) (not working in v4)

```
const [updateMany, { data }] = useUpdateMany()

const onSubmit = async () => {
  await updateMany('posts', {
    ids: [1, 2],
    data: { ... }
  }, { 
    mutationMode: 'pessimistic',
    returnPromise: true
  })
}
```

**Comment by fzaninotto** [comment]
Thanks for the report. You're right, the `returnPromise` option isn't implemented in `updateMany`. I'm marking it as a bug.
