### ISSUE TITLE
[4.0 Migration] ShowController/ShowView combo no longer working

### ISSUE THREAD

**Issue by mediafreakch** [marmelab/react-admin#7696]
**What you were expecting:**

The `<ShowController /><ShowView />` combo can still be used, as it could be in v3.19.x

**What happened instead:**

Nothing is displayed in v4.0.4

**Steps to reproduce:**

Look at the `CommentShow.tsx` file in the sandbox provided

**Related code:**

https://codesandbox.io/s/compassionate-firefly-vwjtu5?file=/src/comments/CommentShow.tsx

**Other information:**

Looks like the `useShowContext` hook is now the preferred way to go. This should be documented in the migration guide.  
Probably other CRUD views are affected as well. I haven't tested.

**Environment**

* React-admin version: 4.0.4
* Last version that did not exhibit the issue (if applicable): 3.19.x
* React version: v17.x

**Comment by fzaninotto** [comment]
As explained in [the 4.0 migration guide](https://marmelab.com/react-admin/Upgrade.html#no-more-prop-injection-in-page-components), the page components don't accept prop injection anymore. Instead, you must use the controller props to create a context.

```diff
const CommentShow = () => (
  <ShowController>
    {(controllerProps) => (
+.    <ShowContextProvider value={controllerProps}>
-       <ShowView {...controllerProps}>
+       <ShowView>
          <TabbedShowLayout>
            <Tab label="Test">
              <TextField source="id" />
              <ReferenceField source="post_id" reference="posts">
                <TextField source="title" />
              </ReferenceField>
              <TextField source="author.name" />
              <DateField source="created_at" />
              <TextField source="body" />
            </Tab>
          </TabbedShowLayout>
        </ShowView>
+.    </ShowContextProvider>
      )}
  </ShowController>
);
```

We hesitated to document this change for `<ShowController>` in the upgrade guide, but as the component was (almost) not documented (apart in Fields.md), we decided not to. 

Note that if you used `<Sho<Controller>` just to access the `record`, there is a new component to do that: [`<WithRecord>`](https://marmelab.com/react-admin/doc/4.0/ShowTutorial.html#accessing-the-record).

**Comment by mediafreakch** [comment]
Oh yeah I see the mistake. Was a not so obvious one because Typescript didn't complain. Thanks for elaborating.
