### ISSUE TITLE
Typescript: FunctionField without record like data typing limitation

### ISSUE THREAD

**Issue by Seojun-Park** [marmelab/react-admin#7702]
**What you were expecting:**

I tried to give a type definition to a `FunctionField`. As you can see on sandbox below, I gave `backlinks` property as a type which belong to `PostRecord` to `FunctionField`. However, type error occurs.

I assume this type error occurs because `backlinks` type is a type property of the `PostRecord` not a record itself.

It would be nice if a `FunctionField` would be able to accept another kind of object type than a record. 

**What happened instead:**

> Type error with a message `Type 'foo' does not satisfy the constraint 'Record'`

**Related code:**

https://codesandbox.io/s/crazy-dan-2x2prk?file=/src/posts/PostShow.tsx (line#58)

```
  <FunctionField<
           Required<PostRecord>['backlinks'][number]
  >
           source="info"
           render={r =>`${r.info.email}`}
  />
  ```
  Related types
  ```
  type BackLinkProps = Array<{
    date?: string;
    url?: string;
    info?: {
        email?: string;
        nationality?: string;
    };
}>;
  
  export interface PostRecord extends Record {
    id: number;
    title: string;
    teaser?: string;
    body?: string;
    view?: number;
    average_note?: number;
    commentable?: boolean;
    pictures?: Array<ImageProps>;
    published_at?: Date;
    tags?: Array<number>;
    category?: string;
    subcategory: string;
    backlinks?: Array<BackLinkProps>;
    notifications: Array<number>;
}
```

**Other information:**

**Environment**

* React-admin version: 3.19.7
* React version: 17.0.2
* Browser: Chrome 101

**Comment by slax57** [comment]
Hi!
Indeed in the case of an ArrayField, the record does not necessary have to have an id.
So we could enlarge the type to be any object (`any` being the default type btw).
Meanwhile, as a workaround, you can simply change to:
```diff
  <FunctionField<
-          Required<PostRecord>['backlinks'][number]
+          Required<PostRecord>['backlinks'][number] & RaRecord
  >
           source="info"
           render={r =>`${r.info.email}`}
  />
```

**Comment by Seojun-Park** [comment]
Thank you! @slax57

I will consider to be with workaround while awaiting this issue is fixed  :)

**Comment by fzaninotto** [comment]
The problem goes beyond `FunctionField`: All fields used as child of `ArrayField` should work on a non-record. But only the `FunctionField` is generic for now. 

I'm not sure how we should fix that.
