### ISSUE TITLE
Codesandbox not working for tutorial example

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7705]
![Capture2](https://user-images.githubusercontent.com/38666763/168947222-4e50819e-49ff-44db-8395-98e26d644670.PNG)

```
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/tutorial
```

**Other information:**

**Environment**

* React-admin version: ^4.0.0
* Last version that did not exhibit the issue (if applicable):
* React version: ^17.0.0
* Browser:
* Stack trace (in case of a JS error): Cannot read properties of undefined (reading 'generate')

**Comment by slax57** [comment]
Reproduced, thanks!
