### ISSUE TITLE
Cannot change color using `sx` on loading page

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7706]
**What you were expecting:**

I expect the text color on loading page can be changed

**What happened instead:**

The text color seems cannot be changed

**Steps to reproduce:**
Fork  https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple on codesandbox
Delete all resource and routes
Add a ready prop with following component

```
        <Loading
          loadingPrimary="loading1"
          sx={{
            color: "red",
            [`& .RaLoading-message`]: {
              color: "red"
            }
          }}
        />
```

**Related code:**

```
https://codesandbox.io/s/delicate-water-py8q0r?file=/src/index.tsx:956-996
```

**Other information:**

**Environment**

* React-admin version: 4.0.4
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.0
* Browser: Edge 101
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Alright then. I think it shouldn't be too hard to fix anyway. I'll see to fix it along with https://github.com/marmelab/react-admin/issues/7712
