### ISSUE TITLE
Form input are not cleaned up anymore since v4

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#7717]
I created a special resource to send SMS that does contains only a create component. This one is configured on the `list` property so I have it as a main page.

**What you were expecting:**

When I submit the form, I expect the form fields to be cleaned up as on v3.

**What happened instead:**

The form data is process but the value are still present on the inputs.

**Steps to reproduce:**

1. `make run-simple`
2. Go to http://localhost:8080/#/comments
3. Fill the form with valid data
4. Submit

**Related code:**

https://github.com/pocivaneuh/react-admin/pull/3

**Other information:**

The easiest way would be to trigger the same behavior as before.

As an another option that can lead to a global feature, we should expose a bit the returned value of [`useForm`](https://react-hook-form.com/api/useform) in order to access to some controls like the [`reset`](https://react-hook-form.com/api/useform/reset) function.

**Environment**

* React-admin version: v4.1
* Last version that did not exhibit the issue (if applicable): v3
* React version: v17

**Comment by fzaninotto** [comment]
Also, can you please use a codesandbox to provide a repro?

**Comment by soullivaneuh** [comment]
This solution should indeed totally fit my needs. However, it does not looks to do anything.

Here is my implementation: https://github.com/pocivaneuh/react-admin/pull/3/commits/6e21b0666ae3be92571cdda750c085fa3fbaa0c3

Maybe I missed something?

**Comment by soullivaneuh** [comment]
@fzaninotto I found why it was not working, the `button` type is required to get the `mutationOptions` working.

I specified that on the documentation: https://github.com/marmelab/react-admin/pull/7724

Note: We may throw an error instead of logging a warning when `mutationOptions` are provided with a `submit` type button.
