### ISSUE TITLE
Numeric `id` parameter is casted to string only for the `getOne` dataProvider method

### ISSUE THREAD

**Issue by ogroppo** [marmelab/react-admin#7728]
**What you were expecting:**
The id parameter should be the same type for all methods.
For instance
<img width="171" alt="Screenshot 2022-05-20 at 18 20 53" src="https://user-images.githubusercontent.com/4820803/169581065-e0285e2f-9889-49c9-bb3c-ad45285d1e8d.png">
<img width="167" alt="Screenshot 2022-05-20 at 18 21 00" src="https://user-images.githubusercontent.com/4820803/169581066-b96581aa-9acb-428a-8517-6daf49087215.png">

**What happened instead:**
id is string
<img width="153" alt="Screenshot 2022-05-20 at 18 21 23" src="https://user-images.githubusercontent.com/4820803/169581035-e9682d03-df42-4114-a0bd-fa57f4f55da4.png">

**Steps to reproduce:**
Use a "Show" view for a record that has numeric id (postgres, mysql...) and inspect the request

**Comment by fzaninotto** [comment]
I'm not sure I understand your problem. Do you mean that you expect the data provider to receive a numeric ID when rendering the show view ? 

In that case, it's not possible : the Show view takes its id parameter from the URL (like `posts/123/show`). It has no way to decide whether it's a string or a number. Therefore, the dataProvider receives a request with a string id.

It is your responsibility to turn this string into a number in your dataProvider if your backend expects a number.

**Comment by ogroppo** [comment]
Ah ok, I see. Closing & thanks for clarification!
