### ISSUE TITLE
Default select input value can't be undefined

### ISSUE THREAD

**Issue by kriskw1999** [marmelab/react-admin#7736]
The `SelectInput` doesn't allow in any way to send undefined if no element is selected and it sends instead empty string. I saw all the properties linked in the site but there seems that is no way to send undefined if empty.
If I pass to `emptyValue` undefined or null it work in the same way like when I don't pass it.
This is very annoying because of lots of validations in my aplication backend side. 

```
<SelectInput emptyValue={undefined} choices={someChoices}/>
```

**Environment**

* React-admin version: 4.0
* Last version that did not exhibit the issue (if applicable): 3.0
* React version: 17.0
* Browser: any
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
This is expected as we use the `useController` hook from `react-hook-form` and it does not accept `undefined` as its default value. This means it will apply our default `defaultValue` when it receives undefined.

As a workaround, you can use the `transform` prop of either the `Create` or `Edit` component to set the value for this input property to `undefined` when it's an empty string
