### ISSUE TITLE
Default translation gets always triggered

### ISSUE THREAD

**Issue by JenniferKiesel** [marmelab/react-admin#7746]
**What you were expecting:**

The translation is applied without executing the default translation code.

**What happened instead:**

The default translation code is executed even though a translation is available.

**Steps to reproduce:**

Click on **Posts** in the left menu, change the language and watch the console.

**Related code:**

https://codesandbox.io/s/silly-darkness-njuz78?file=/src/posts/PostList.tsx

**Other information:**

https://marmelab.com/react-admin/Translation.html#using-specific-polyglot-features

**Environment**

* React-admin version: latest, 4.1.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: all
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
This behavior is due to the way React works. The JSX is executed at every render. If you want to only have it executed once, use a React.memo.

I'm closing this as this is not a react-admin problem.
