### ISSUE TITLE
Theme settings are shared between subdomains

### ISSUE THREAD

**Issue by thibault-barrat** [marmelab/react-admin#7752]
**What you were expecting:**
If you have have two react-admin apps installed on the same domain, each app should have its own theme settings.

**What happened instead:**
The theme settings are stored in local storage for the domain inside the key RaStore.theme and so the settings are shared between subdomains.

**Comment by fzaninotto** [comment]
Indeed, developers should be able to specify a custom store key (instead of "RaStore") by passing a custom store.
