### ISSUE TITLE
How to write custom form using react-hook-form in react-admin?

### ISSUE THREAD

**Issue by ApolloRisky** [marmelab/react-admin#7756]
Hey guys, I'm building a custom form by installing react-hook-form package while using react-admin. The issue is after installing react-hook-form, other react-admin's built-in inputs got crashed and throw below error. 

This should be a libraries conflict issue. How to fix that?

![Screenshot 2022-05-25 at 14 16 07](https://user-images.githubusercontent.com/18187332/170220721-1f3e3211-3a4c-49f2-9cd2-8f0de4f40741.png)

**Comment by djhi** [comment]
You need to wrap the form **content** with the `FormContext` from react-hook-form. See https://react-hook-form.com/api/useformcontext

**Comment by ApolloRisky** [comment]
hey @djhi , the SearchInput usage in the screenshot is used by React-Admin <List /> component, I don't know and don't want to break that. I just wanted to build the custom form in different component but installing react-hook-form caused that error.

**Comment by ApolloRisky** [comment]
Here is the usage of SearchInput that installing react-hook-form along with react-admin sucks

![Screenshot 2022-05-25 at 14 16 07](https://user-images.githubusercontent.com/18187332/170222096-d264bafb-b87b-4ac5-b345-6e83bfc14c6e.png)

**Comment by djhi** [comment]
Then please follow the issue template and provide a codesandbox showing the issue

**Comment by ApolloRisky** [comment]
I figured out the way to use react-hook-form hooks, components without installing that package along with react-admin.
It's just needed to import things from 'react-hook-form' like
```tsx
import { ... } from 'react-hook-form';
```

I think we should put that important tip into the current documentation.
