### ISSUE TITLE
AutocompleteInput inside ReferenceInput shows "No options" once a value is assigned

### ISSUE THREAD

**Issue by lvernaillen** [marmelab/react-admin#7761]
**What you were expecting:**
When clicking on an AutocompleteInput inside a ReferenceInput I always expect to see list of suggestions regardless if that AutocompleteInput already has a value assigned/selected.

**What happened instead:**
When the AutocompleteInput has no value assigned/selected yet, it correctly show the list of suggestions.
As soon as the AutocompleteInput has a value assigned/selected, it shows empty list with "No options".

![AutocompleteInput-inside-ReferenceInput](https://user-images.githubusercontent.com/4180374/170678982-04d2d05e-330b-4e27-9697-f067ba7c56f6.png)

**Steps to reproduce:**
- make sure to login as _admin_
- go to the edit page of a post
- click on the Add button at bottom of the form to add an author
- click on the User autocomplete input
- notice all the available options are shown
- select Breanna Gibson
- click on the User autocomplete input again
- notice it shows "No options" instead of the complete list

**Related code:**
It is reproducable in your `simple` application. See CodeSandbox https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4)

**Other information:**
It does work as expected when the AutocompleteInput is not inside a ReferenceInput.
It seems that the input now immediately uses the already set input to query for autocompletion. Where before you saw the complete suggestion list and it only queried for autocompletion when you started to modify the value that was set.

**Environment**

* React-admin version: 4.1.0
* Last version that did not exhibit the issue (if applicable): 3.19.7 (maybe later version of v3 as well)
* React version: 17
* Browser: Chrome version 101.0.4951.67

**Comment by djhi** [comment]
Thanks for reporting. This is indeed a bug

**Comment by davidhenley** [comment]
Hey @djhi just wondered if there is any update on this:

The AutocompleteInput is calling the dataProvider getList an extra time with each mount and you have to clear the input which causes ANOTHER call to dataProvider getList. 

Just a lot of extra load on the server. Especially when many AutocompleteInput exists on one page.

![Screen Shot 2022-06-23 at 2 28 49 PM](https://user-images.githubusercontent.com/15056748/175382077-cdabec6b-cf6e-4070-b6a8-1e7b402b7f96.png)

![Screen Shot 2022-06-23 at 2 29 10 PM](https://user-images.githubusercontent.com/15056748/175382094-78d88602-9065-470b-b3d7-14ef248bfb42.png)

You can see the extra calls here:
![Screen Shot 2022-06-23 at 2 31 32 PM](https://user-images.githubusercontent.com/15056748/175382187-f87d17a6-d8d7-4600-a157-ea76195a564f.png)
