### ISSUE TITLE
Issues dealing with Error Response as per documentation

### ISSUE THREAD

**Issue by iskandersierra** [marmelab/react-admin#7762]
**What you were expecting:**
I expected `react-admin` to gracefully deal with an error response from `dataProvider` having status `404`

**What happened instead:**
A lot of errors are shown in the console, indicating that an error occurred.

**Steps to reproduce:**
1- Create a custom `dataProvider` using `@urql/core` and set it up for the `<Admin>` component.
2- On `getOne`, when the GraphQL response returns `{"data":{"result":null}}`, throw an `HttpError` (from `react-admin`) with `status` set to `404`
3- Navigate to any existing item on the list, and then change the url to a non-existent item id
4- Watch the network and console in browser's developer tools

**Related code:**

Partial implementation of `getOne` for the specific resource:

```typescript
  const response = await query.toPromise();   // query not relevant for this sample

  if (response.error) {
    throw response.error;      // CombinedError from URQL
  }

  if (!response.data?.result) {
    const error = new HttpError('No data returned', 404, response);   // from react-admin
    console.dir(error);
    throw error;
  }

  return {
    data: response.data.result!,
  };
```

Network POST is correct:

![image](https://user-images.githubusercontent.com/3475117/170681206-532ce4a3-1a41-4e12-8d84-c7998a008ae4.png)

and receives expected response:

```json
{"data":{"result":null}}
```

**Other information:**
- [Documentation on Error Format](https://marmelab.com/react-admin/doc/3.19/DataProviders.html#error-format) states that:
> When the API backend returns an error, the Data Provider should return a rejected Promise containing an Error object. This object should contain a status property with the HTTP response code (404, 500, etc.). React-admin inspects this error code, and uses it for authentication (in case of 401 or 403 errors). Besides, react-admin displays the error message on screen in a temporary notification.

and also:
> If you use another HTTP client, make sure you return a rejected Promise. You can use the HttpError class to throw an error with status in one line

**Environment**

* React-admin version: `^4.0.3`
* Last version that did not exhibit the issue (if applicable): `NA`
* React version: `^18.1.0`
* Browser: `Firefox 100.0.2`
* Stack trace (in case of a JS error): 
![image](https://user-images.githubusercontent.com/3475117/170681871-adc71bb9-afe4-49d6-83c7-ea10eab52211.png)
This stack trace is printed `99+` times in the console, in rapid successions, almost blocking the browser's UI. I can see the `HttpError` is thrown at `apiConventions.ts` file (where the snippet above is taken from), and it is called by a `Retryer`. I do not see in the `Retryer` any code dealing with `status` property from the error.

**Comment by djhi** [comment]
That's react-query default behavior to retry failed requests (See https://react-query.tanstack.com/guides/important-defaults). If you don't like this, you can provide your own query client as explained [here](https://marmelab.com/react-admin/Admin.html#queryclient).

However, I agree this is disturbing so I'll keep this issue open and mark it as a bug.

**Comment by fzaninotto** [comment]
React-query should retry only 3 times, so I doubt it's the culprit here.

Could you please try and reproduce the bug based on the simple example codesandbox? As it simulates the API client-side, it's easier to simulate error responses. 

If you don't manage to reproduce the bug with the codesandbox, it means the problem lies in your data provider.

**Comment by iskandersierra** [comment]
Ok @fzaninotto, I'll try to setup the simplest repro that produces the behaviour I'm showing.

**Comment by iskandersierra** [comment]
I have not abandoned this issue, just looking for some time to prepare the simplest repro.

**Comment by fzaninotto** [comment]
No news for some time, so I'll close this issue. I you can provide a repro, we'll reopen it.
