### ISSUE TITLE
Populating 'false' by default when we type 'on' in TextInput 

### ISSUE THREAD

**Issue by dittybijil** [marmelab/react-admin#7769]
Auto populates boolean false in 'textInput' when we start to type 'on'.  Please support to fix this issue.

Can see the issue if we type 'on' in first name field in the following link
https://marmelab.com/react-admin-demo/#/customers/create

**Comment by slax57** [comment]
Hi,
This has been fixed since 4.0.5 with https://github.com/marmelab/react-admin/pull/7682
If you still encounter this issue after upgrading, then please open an issue following the issue template.
