### ISSUE TITLE
react-admin TextInput multiline without fixed width or fullWidth causes Too many re-renders. The layout is unstable

### ISSUE THREAD

**Issue by rcfrias** [marmelab/react-admin#7780]
**What you were expecting:**
Follow and implement Tutorial instructions without any console errors in the DevTools console.

**What happened instead:**
Frontend renders fine, but console is flooded with errors: "Too many re-renders. The layout is unstable"

**Steps to reproduce:**
Follow the tutorial, I've isolated the problem. The bug happens only when this line is present:
<TextInput multiline source='body' />

**Related code:**
```
<TextInput multiline source='body' /> // <- multiple errors
// changing to: 
<TextInput fullWidth multiline source='body' /> // no errors
```
The exact console error is:
MUI: Too many re-renders. The layout is unstable.TextareaAutosize limits the number of renders to prevent an infinite loop.

**Comment by septentrion-730n** [comment]
Hello and thanks for your report.

I have not been able to reproduce this bug using the source code provided with the tutorial.
Here is a codesandbox using unmodified source from the repo: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/tutorial

Am I missing something?

**Comment by davidhenley** [comment]
Reproduced:

`Too many re-renders. The layout is unstable. TextareaAutosize limits the number of renders to prevent an infinite loop.`

**Comment by davidhenley** [comment]
https://github.com/mui/material-ui/issues/33081

It's an MUI problem

**Comment by davidhenley** [comment]
Here is the fix @slax57 https://github.com/mui/material-ui/pull/33253

**Comment by fzaninotto** [comment]
I understand this was an MUI bug that was fixed upstream, so we can close the issue. 

Feel free to comment if this is not the case.
