### ISSUE TITLE
Unable to load saved queries when alwaysOn filters are empty

### ISSUE THREAD

**Issue by mbryk** [marmelab/react-admin#7784]
**What you were expecting:**
I have an "alwaysOn" text filter.

When the filter is not empty, the "Add Filter" dropdown is displayed, allowing me to save the current filter as a query, or load a previously saved query.

<img width="1575" alt="Screen Shot 2022-06-03 at 10 44 38 AM" src="https://user-images.githubusercontent.com/1477066/171877411-81c9be8d-ee5b-4749-9752-0693e1352aec.png">

When the filter is empty however, the "Add Filter" dropdown is not displayed, meaning I can't load any previously saved queries.

<img width="1572" alt="Screen Shot 2022-06-03 at 10 45 33 AM" src="https://user-images.githubusercontent.com/1477066/171877501-fc3f1eb7-c189-4558-9dea-295efc230a1a.png">

Shouldn't the "Add Filter" dropdown always be displayed, if previously saved queries exist?

Lastly, it would be easiest if I could hide the new "Save current query" functionality from the Filter dropdown and avoid this altogether, but I can't see any information in the documentation on how to do that. It only says: "It’s enabled by default for the Filter Button/Form combo" without any information on how to disable it. Skimming through [the code here](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/filter/FilterButton.tsx#L139), it seems like it's not possible.

* React-admin version: 4.1

**Comment by fzaninotto** [comment]
Confirmed, thanks. 

There is indeed no API to disable saved queries in `<List filters>`. You'll have to [implement your own filter](https://marmelab.com/react-admin/FilteringTutorial.html#building-a-custom-filter) for that.
