### ISSUE TITLE
Filter query parameters are persisted when switching tabs

### ISSUE THREAD

**Issue by luiz-fv** [marmelab/react-admin#7796]
**What you were expecting:**

The filters to be cleared as the resource on the other tab might be different.

**What happened instead:**

The previous filters are applied to the current resource, resulting in errors on the data provider.

**Steps to reproduce:**

Create two different tabs inside a TabbedShowLayout and use two Lists pointing to two different resources.

**Environment**

* React-admin version: 4.1.2

**Comment by fzaninotto** [comment]
I fail to understand the scenario that reproduces the error, could you please join a link to a reproduction using the simple example codesandbox?

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by samanmohamadi** [comment]
I had the same problem.
usign [disableSyncWithLocation](https://marmelab.com/react-admin/List.html#disablesyncwithlocation) solved mine.
