### ISSUE TITLE
Outdated document for conditional-formatting 

### ISSUE THREAD

**Issue by AntonOfTheWoods** [marmelab/react-admin#7797]
**What you were expecting:**
The examples should work

**What happened instead:**
The props `record` is undefined.

**Steps to reproduce:**
Implement the following
https://marmelab.com/react-admin/Theming.html#conditional-formatting

**Related code:**
See outdated docs above.

See migration guide here: https://marmelab.com/react-admin/Upgrade.html#the-record-prop-is-no-longer-injected

* React-admin version: 4.1.2
* Last version that did not exhibit the issue (if applicable): pre-4
* React version: all
* Browser: all
* Stack trace (in case of a JS error): "Cannot read properties of undefined"

**Comment by fzaninotto** [comment]
Thanks for the heads up! I'm marking this as a documentation issue.
