### ISSUE TITLE
SEO optimizations, indexability

### ISSUE THREAD

**Issue by mshd** [marmelab/react-admin#7798]
**Is your feature request related to a problem? Please describe.**
This might seem like a strange question, but I'm working on a way to display a public dataset (let's say a library) on react-admin. Would it be possible for google to index the list and show pages? Has this ever been considered or is react-admin only meant to be used as an admin dashboard internally?

**Describe the solution you'd like**
I'm using nextJs as a Backend, but I think ra uses react-router.

**Comment by fzaninotto** [comment]
hi, and thanks for your question.

We haven't designed react-admin for that use case. You may find a way to do it, but we won't be able to help you.
