### ISSUE TITLE
useTheme returns undefined as value

### ISSUE THREAD

**Issue by bladx** [marmelab/react-admin#7805]
**What you were expecting:**
Getting the theme value with the react-admin hook: useTheme().

**What happened instead:**
useTheme() hook returns undefined as value.

**Steps to reproduce:**
Just go to the configuration page of the demo right after a login (cache initially cleared).
https://marmelab.com/react-admin-demo/#/configuration
I reproduce every time (not that evident as the primary and secondary colors are close).

**Related code:**
```
const [theme] = useTheme();
console.log(theme);
```
**Environment**

* React-admin version: ^4.1.0
* Last version that did not exhibit the issue (if applicable): I used ^3.14.1 before so I would say the bug was introduce with v4 (when the hook has been created actually)
* React version: ^18.1.0
* Browser: Firefox 100.0.2 (64-bit), macOS Monterey Version 12.2.1

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report.

**Comment by bladx** [comment]
Also, do you know how I can make the stored theme in local storage not to be cleaned at log out?
I found out how not to store the theme in local storage using: https://marmelab.com/react-admin/Store.html#transient-store
But I would like that the theme selected with ToggleThemeButton is not flushed at log out anymore.
