### ISSUE TITLE
TextField Label not rendered after migrating to V4 and MUI to V5

### ISSUE THREAD

**Issue by nicoladj77** [marmelab/react-admin#7807]
**What you were expecting:**
The [TextField component documentation](https://marmelab.com/react-admin/TextField.html) shows that a label property is still accepted, and I was expecting my coomponents to render with a label 

**What happened instead:**
Only the Value of the component renders. 
`<span class="MuiTypography-root MuiTypography-body2 css-e784if-MuiTypography-root">Casa Mia al lago</span>`

**Steps to reproduce:**
I'm using a simple Edit compoonent:

```
export function PropertyEdit() {
  return (
    <Edit>
      <SimpleForm>
        <TextField source="buildingName" label="Building name" />
      </SimpleForm>
    </Edit>
  );
}
```

**Environment**

* React-admin version: 4.1.2
* Last version that did not exhibit the issue (if applicable): 3.19
* React version: 17.0.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
This is a documented change in 4.0: https://marmelab.com/react-admin/Upgrade.html#the-addlabel-prop-has-been-removed-from-all-inputs-and-fields

You have to use the Labeled component when using a Field in a Form. https://marmelab.com/react-admin/SimpleForm.html#using-fields-as-children

But I agree that the Upgrade guide is a bit short on the matter, I'll label this as a documentation issue.
