### ISSUE TITLE
Can't override ImageField global style

### ISSUE THREAD

**Issue by peam1146** [marmelab/react-admin#7809]
**What you were expecting:**

The ImageField components provide a [key](https://marmelab.com/react-admin/ImageField.html#sx-css-api) for overriding style in global theme but it doesn't work

**What happened instead:**

not thing happened.

**Steps to reproduce:**

styling ImageField in global theme with "RaImageField" key

**Related code:**

```js
RaImageField: {
      styleOverrides: {
        root: {
          "&.RaImageField-image": {
            maxWidth: "150px",
          },
        },
      },
    },
```

**Environment**

* React-admin version: "^4.1.2"
* React version: "^17.0.2"
* Browser: Chrome

**Comment by septentrion-730n** [comment]
Thank for your report.
Here is a codesandbox to reproduce the bug: https://codesandbox.io/s/raimagestyle-wufz7o?file=/src/themes.ts
