### ISSUE TITLE
Datagrid with expand element expands ALL rows when used as a child of ArrayField

### ISSUE THREAD

**Issue by mikemcclaran** [marmelab/react-admin#7814]
**What you were expecting:**

When expanding a grid row, I expect only the row I clicked on to be expanded.

**What happened instead:**

All rows in the grid are expanded

**Steps to reproduce:**

Add a Datagrid with expand element as a child of ArrayField.

```
const BacklinkPanel = () => {
  const record = useRecordContext();
  return <div dangerouslySetInnerHTML={{ __html: record.url }} />;
};

<ArrayField source="backlinks">
  <Datagrid expand={<BacklinkPanel />}>
    <DateField source="date" />
    <UrlField source="url" />
  </Datagrid>
</ArrayField>
```
**Related code:**

[CodeSandbox of issue using master](https://codesandbox.io/s/gifted-babycat-ehp0ce?file=/src/posts/PostShow.tsx)

[CodeSandbox working properly using v3.x](https://codesandbox.io/s/adoring-stallman-8726bz?file=/src/posts/PostShow.tsx)

**Other information:**

[Demo working as expected in v3.x](https://media.giphy.com/media/9E3t2JZy738V97nq6n/giphy.gif)
[Demo of incorrect behavior in v4.x](https://media.giphy.com/media/GIdt8LqEFKc6y0ZoiV/giphy.gif)

**Environment**

* React-admin version: 4.1.3
* Last version that did not exhibit the issue (if applicable): 3.x
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by septentrion-730n** [comment]
Thanks for reporting this and for having provided a compete test set. We have been able to reproduce the bug, we just have to fix it now!
