### ISSUE TITLE
Cannot destructure property 'data' of '_ref17' as it is undefined.

### ISSUE THREAD

**Issue by zhang-quan-yi** [marmelab/react-admin#7815]
I am using a list page. When my list api return a 401 error, I am getting this error:
![image](https://user-images.githubusercontent.com/12481444/173189007-6c9289bd-09a3-4d18-a4e1-cae7d62a0d1c.png)

![image](https://user-images.githubusercontent.com/12481444/173178015-bcc69b7d-6607-4157-8cee-b5dc9393d1fc.png)
![image](https://user-images.githubusercontent.com/12481444/173178029-7618f1d0-8482-4214-934e-6068a1326d48.png)

**What you were expecting:**

Show the error message related to 401 error.

**What happened instead:**

Unexpected error occured:
Cannot destructure property 'data' of '_ref17' as it is undefined.

**Steps to reproduce:**

1. use `<List>` component
2. remove the token of list api.
3. call the list api again.
4. api return a 401 error.
5. Unexpected error occured: Cannot destructure property 'data' of '_ref17' as it is undefined.

**Related code:**

my authProvider is something like this:
```javascript
{
  checkError(error) {
    if (error.status === 401) {
      return Promise.reject();
    }
    return Promise.resolve();
  },
  logout(){
    return Promise.resolve();
  }
}

```
My index.tsx file:
```jsx
import ReactDOM from "react-dom/client";

const root = ReactDOM .createRoot(document.getElementById("root"));
root.render(<App />);
```

**Other information:**

**Environment**

* React-admin version:4.0.4
* React version: 18.1.0
* Stack trace (in case of a JS error):
![image](https://user-images.githubusercontent.com/12481444/173178389-1b925029-6c55-4178-b755-acbaf97c324a.png)

**Comment by zhang-quan-yi** [comment]
I think this code has something wrong [https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useDataProvider.ts#L112](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useDataProvider.ts#L112):
![image](https://user-images.githubusercontent.com/12481444/173178847-939d4f70-4a7d-4962-a8df-8836c854fe13.png)

Even though loggedOut is true, we should also need to throw the error. A normal return will cause the Promise go to next `then` function with `undefined` value:
[https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useGetList.ts#L80](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useGetList.ts#L80)
![image](https://user-images.githubusercontent.com/12481444/173178970-6f5be524-2f00-47d0-8aed-1fdc680cf684.png)

**Comment by slax57** [comment]
Hi,
Thank you for submitting this.
Indeed this seems like a bug to me.
I believe you manage to point out the right location, however, to me, the fix would rather be something like

```diff
- if (loggedOut) return;
+ if (loggedOut) return { data: {} };
```

I'll do a PR and request the team's pov.
