### ISSUE TITLE
Translation is partially not present on ReferenceInput when used as a filter

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#7817]
**What you were expecting:**
A filter using the `ReferenceInput` should be translated.

**What happened instead:**
A filter using the `ReferenceInput` is translated on the filter selector, but not on the input label.

**Steps to reproduce:**

1. Change the language of the dashboard to french
2. Go to the comment list
3. Click on "Filter"
4. Select the "Article" filter

**Related code:**

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

Note: No need to fork and modify the base sandbox, the bug is already present on it.

**Other information:**

<details>
<summary>Translated filter on choice list</summary>
![image](https://user-images.githubusercontent.com/1698357/173192409-20ebc639-c22d-47a0-9c1f-63628e06988f.png)
</details>

<details>
<summary>Not translated filter when set</summary>
![image](https://user-images.githubusercontent.com/1698357/173192434-fcad4b81-f3c7-4748-a57a-c4f5e3c38928.png)
</details>

**Environment**

* React-admin version: v4
* Last version that did not exhibit the issue (if applicable): v3
* React version: v17

**Comment by septentrion-730n** [comment]
Thanks for pointing this out. Bug confirmed!
