### ISSUE TITLE
SaveButton does not disable and show indeterminate progress while onSubmit function is executing 

### ISSUE THREAD

**Issue by mikemcclaran** [marmelab/react-admin#7821]
**What you were expecting:**

After clicking the save button I was expecting the button to show indeterminate progress and be disabled from subsequent clicks until the onSubmit function execution completes.

**What happened instead:**

Button remains active while onSubmit function is executing and no indeterminate progress is shown on the button

**Steps to reproduce:**

Simplest way to see the issue is to make a onSubmit function that takes a bit of time to execute.

**Related code:**

[CodeSandbox of issue using master](https://codesandbox.io/s/xenodochial-maxwell-6sl91j?file=/src/users/UserEdit.tsx)
[CodeSandbox working properly in v3.x](https://codesandbox.io/s/optimistic-williams-9b257c?file=/src/users/UserEdit.tsx)

```
const UserEditForm = ({ permissions, save, ...props }) => {
  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  const newSave = async (values) => {
    console.log("before sleep");
    await sleep(5000);
    console.log("after sleep");
  };

  return (
    <TabbedForm
      defaultValue={{ role: "user" }}
      toolbar={<UserEditToolbar />}
      {...props}
      save={newSave}
    >

...
```

**Other information:**

[Demo of working as expected in v3.x](https://media.giphy.com/media/GAatJVW6MADdk6AoXH/giphy.gif)
[Demo of incorrect behavior in v4.x](https://media.giphy.com/media/vhttDcL6YJuupS0xU9/giphy.gif)

**Environment**

* React-admin version: 4.1.3
* Last version that did not exhibit the issue (if applicable): v3.x
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by septentrion-730n** [comment]
Reproduced. Thanks for reporting this so precisely.
