### ISSUE TITLE
React-Admin examples not changing on save

### ISSUE THREAD

**Issue by leonaburime** [marmelab/react-admin#7826]
**What you were expecting:**

- I expect to be able to make minor changes in the "demo" folder or any folder and have them reflected

**What happened instead:**

- Nothing is able to fast refresh or reload. I have to restart the server to see changes

**Steps to reproduce:**

- Download react-admin and try running it. Simple as that

**Related code:**

* Preferably, a CodeSandbox forked from 
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
npm start
```
npm start runs ```react-scripts start```
Try running it and see **nothing** happen. Its maddening!

**Other information:**

**Environment**

* React-admin version: ^4.0.0
* Last version that did not exhibit the issue (if applicable):
* React version: ^17.0.0
* Browser: Chrome and Safari
* Stack trace (in case of a JS error):

**Comment by leonaburime** [comment]
The ```react-scripts``` package is the problem.
I had to install regress to ```"react-scripts": "^3.4.4"``` for this to work

**Comment by fzaninotto** [comment]
https://github.com/facebook/create-react-app/issues/12173
