### ISSUE TITLE
Please update the "Creating a Record Related to the Current One" to v4

### ISSUE THREAD

**Issue by shlfung** [marmelab/react-admin#7827]
**Is your feature request related to a problem? Please describe.**
The tutorial section is outdated for react-admin v4
https://marmelab.com/react-admin/AdvancedTutorials.html

**Describe the solution you'd like**
Please update the tutorial and example code to be v4 compatible

**Describe alternatives you've considered**
I have tried to follow the tutorial and example code, but it is not working under v4

**Additional context**

**Comment by septentrion-730n** [comment]
Thanks for pointing this out! We will debate the priority of this topic tomorrow.

**Comment by strarsis** [comment]
+1! The new v4 architecture surely makes things simpler but also different. How to create a new, related record inline, in a dialog? What hooks are used, how should the ID of referenced record be passed?

**Comment by danysz** [comment]
+1

**Comment by fzaninotto** [comment]
https://marmelab.com/blog/2023/10/12/react-admin-v4-advanced-recipes-creating-a-record-related-to-the-current-one.html

**Comment by strarsis** [comment]
Awesome!
