### ISSUE TITLE
Clear (reset) filter action

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#7831]
**Is your feature request related to a problem? Please describe.**

Since the new v4 major release of react-admin, it seems we have persisted filter enabled by default.

This is convenient for the navigation. However, sometimes we need to reset to the defaults and we may have a lot of filter to disabled one by one.

**Describe the solution you'd like**

A generic "Clear filter" action that resets the filter state from scratch.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by septentrion-730n** [comment]
Thanks for the suggestion, this will be discussed with the team.

**Comment by septentrion-730n** [comment]
Feature has been implemented and merged for the next minor version 4.3 due by August 26, 2022.
