### ISSUE TITLE
Cannot override RaReferenceField defaultProps for link

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#7834]
The following does not override the default link type props:

```js
import {defaultTheme} from "react-admin"

const Theme = {
  ...defaultTheme,
  components: {
    ...defaultTheme.components,
    RaReferenceField: {
      defaultProps: {
        link: "show"
      }
    }
  }
}
```

https://github.com/marmelab/react-admin/blob/a408de0db2c6db0281b3d39e27c1f2de3deed44e/packages/ra-ui-materialui/src/field/ReferenceField.tsx

**Comment by fzaninotto** [comment]
That's because we don't support overriding props via theming in react-admin. What you show is a material-ui feature for MUI components. This isn't documented anywhere for react-admin, and we won't implement it (as you can create your own derivatives by wrapping a react-admin component).
