### ISSUE TITLE
AutocompleteInput not sending `null`

### ISSUE THREAD

**Issue by garrettcam** [marmelab/react-admin#7857]
**What you were expecting:**
When AutocompleteInput is empty send `null` to API

**What happened instead:**
Empty string `""` is sent to API

**Steps to reproduce:**
Delete value or click 'Clear value' in the AutocompleteInput then click save

**Related code:**

```
<ReferenceInput source="clerk" reference="persons">
          <AutocompleteInput
            label="Clerk"
            optionText="fullname"
            emptyValue={null}
            defaultValue={null}
            filterToQuery={(searchText) => ({ fullname: searchText })}
          />
</ReferenceInput>
```

**Other information:**

**Environment**

* React-admin version: 4.1.4
* React version: 18.2.0
* Browser: Chrome 102

**Comment by septentrion-730n** [comment]
This behaviour is induced by `react-hook-form` library ([website](https://react-hook-form.com/)).

You can use `transform` properties on [`Edit`](https://marmelab.com/react-admin/Create.html#transform) and [`Create`](https://marmelab.com/react-admin/Edit.html#transform) to sanitize your inputs.

**Comment by septentrion-730n** [comment]
Please have a look at : https://github.com/marmelab/react-admin/issues/7793
