### ISSUE TITLE
Add data provider libraries for Postgrest to Marmelab-managed libraries

### ISSUE THREAD

**Issue by promitheus7** [marmelab/react-admin#7865]
**Is your feature request related to a problem? Please describe.**
The current problem is that the most popular library for Postgrest as a data provider is actively maintained by a handful of people who may not have the time to keep up with every update to `ra-core`. Link to the repo [here](https://github.com/raphiniert-com/ra-data-postgrest/issues/31). This issue arises due to the shared dependency on `ra-core` - while `yarn start` works fine, in more standardized environments that use `npm run build` to build the application, there is a build error due to a mismatch in the `ra-core` version present in the data provider library, and in react-admin. Having support for common API libraries such as Postgrest would greatly benefit react-admin's out-of-box stability and usability considering developers may be forced to use `npm` over `yarn`.

**Describe the solution you'd like**
I would like Marmelabs to provide support for the most common data provider integrations.

**Describe alternatives you've considered**
I've considered the alternative of doing it myself - however, given how quickly libraries move, and that `ra-core` is a library controlled by Marmelabs, doing it myself falls into the same potential situation of falling behind current dependency requirements for `react-admin` and running into build issues down the line for myself and whoever else may be using my fork.

**Additional context**
Please let me know if additional context is required.

**Comment by promitheus7** [comment]
I've built my own version with the same `ra-core` dependency [here](https://github.com/promitheus7/ra-data-postgrest). Testing in progress to ensure nothing has broken.

**Comment by septentrion-730n** [comment]
Nice work! I am updating the doc to list your project

**Comment by scheiblr** [comment]
@promitheus7, I would be very happy, if you could just push the changes upstream, instead of highjacking a still activerly maintained project. Then I would create a new major version. That's how OS works generally.

Kind regards
