### ISSUE TITLE
Prop types does not accept boolean for label props

### ISSUE THREAD

**Issue by thibault-barrat** [marmelab/react-admin#7868]
**What you were expecting:**
As described here https://marmelab.com/react-admin/Inputs.html#common-input-props, I want to hide the label on an `ImageInput` field by setting `label={false}`

**What happened instead:**
The label is hidden but I have this error in my browser : 
![image](https://user-images.githubusercontent.com/41492953/174772424-b156026c-32e2-417d-a2e7-8486d9a0e0ff.png)

**Steps to reproduce:**
Set the props `label={false}` on an `ImageInput` field

**Related code:**
See `PostEdit.tsx` in https://codesandbox.io/s/laughing-chaum-phq8f0

**Environment**

* React-admin version: 4.1.3

**Comment by slax57** [comment]
Reproduced, thanks!
