### ISSUE TITLE
adding a filter sometimes sets the wrong url 

### ISSUE THREAD

**Issue by megantaylor** [marmelab/react-admin#7874]
**What you were expecting:**
When I add a filter on a list, the url params should update with the filters and the path should not change

**What happened instead:**
Sometimes when I add a filter on a list, the path changes in addition to the url params. The path change seems to related to an older path.

**Steps to reproduce:**
We have implemented drawers that open from lists similar to those in https://marmelab.com/react-admin-demo/#/reviews/
We have reproduced the behavior in the demo as well.

1.  go to:  https://marmelab.com/react-admin-demo/#/reviews/
2. click on a review to open the drawer
3. close the drawer
4. add a filter
5. url now contains review id of previously viewed review (which is what opens the drawer) and drawer is open

the behavior is somewhat inconsistent so you may have to repeat steps 2-4 a few times

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable): 3.19

**Comment by septentrion-730n** [comment]
Reproduced, thanks for the report.
