### ISSUE TITLE
ImageInput clones its child

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#7877]
**What you were expecting:**

Using ImageInput with a custom preview component works:

```jsx
const PreviewField = () => <ImageField source="src" title="title" />;

<ImageInput source="pictures" label="Related pictures" accept="image/*">
    <PreviewField />
</ImageInput>
```

**What happened instead:**

The preview doesn't work. To make it work, one has to pass the props explicitly in the preview component:

```jsx
const PreviewField = (props) => <ImageField source="src" title="title" {...props} />;
```

This may be natural in 3.0, but in 4.0 this is unexpected. 

**Related code:**

The culprit is `<FileInput>`, which still clones its child instead of wrapping it in a `RecordContext`:

https://github.com/marmelab/react-admin/blob/8287a60e2ddecfbe56320ffc1358e893b9dc857c/packages/ra-ui-materialui/src/input/FileInput.tsx#L189-L205

**Environment**

* React-admin version: 4
* Last version that did not exhibit the issue (if applicable): 3
* React version:18
* Browser: Chrome

**Comment by thibault-barrat** [comment]
I experienced this problem and I can add that `<FileInput>` uses the `source` props of its children to create the file which is passed as a record to its children :  

https://github.com/marmelab/react-admin/blob/8287a60e2ddecfbe56320ffc1358e893b9dc857c/packages/ra-ui-materialui/src/input/FileInput.tsx#L55-L63

So, the custom preview component must have a `source` props to make it work.
