### ISSUE TITLE
React-Admin AutocompleteInput only uses first 1000 choices

### ISSUE THREAD

**Issue by Brebeck-Jan** [marmelab/react-admin#7880]
We use `AutocompleteInput` with an static array of more than 1000 choices for relatedPages:

       <ArrayInput source="pages">
        <SimpleFormIterator>
          <AutocompleteInput
            source={"id"}
            choices={relatedPages}
          />
        </SimpleFormIterator>
      </ArrayInput>

**Expected**:
We can select one item of all items in our static array.

**Actually**:
We can only select from the first 1000 items of our static array. This happens with the `SelectInput`, too.

It seems like an limitation of useChoicesContext and/or useList hooks.

**Environment**

React-admin version: 4.1.3
React version: 17.x

**Comment by septentrion-730n** [comment]
Thank for reporting! 

Could you provide a behaviour reproduction sandbox? 
- a CodeSandbox forked from [simple example V4](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or [v3](https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple)
- a link to a GitHub repo with the minimal codebase to reproduce the issue?

Many thanks for your help in this matter! 👍

**Comment by Brebeck-Jan** [comment]
I create an CodeSandbox with an simple example: [`CodeSandbox`](https://codesandbox.io/s/vibrant-christian-6pvxnq?file=/src/posts/PostEdit.tsx)

I did an AutocompleteInput on the title of PostEdit. If you click on it, you get Suggestions up to 999, but non further.
