### ISSUE TITLE
Problem with dependencies using yarn PnP mode when following tutorials

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7885]
**Is your feature request related to a problem? Please describe.**
When using the yarn 2 pnp mode for a fresh CRA app,
It throws following error when I finished the step of [Making Contact With The API Using a Data Provider](https://marmelab.com/react-admin/Tutorial.html#making-contact-with-the-api-using-a-data-provider)

`Compiled with problems:

ERROR in ./.yarn/__virtual__/ra-core-virtual-9ca0fb2ce4/0/cache/ra-core-npm-4.1.5-6d476eb117-886c343e31.zip/node_modules/ra-core/dist/esm/auth/useLogin.js 2:0-60

Module not found: Error: ra-core tried to access react-router-dom (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: react-router-dom
Required by: ra-core@virtual:3fa5b22b0fbfe8581ad50b14e0e51323d3a1c3805167aa458cc6b47f197e9ac94660c0fcfb23f2c9a4bb72a871b2e01d10436504396cbdfd2793e92b834e3876#npm:4.1.5 (via /home/motion/Developer/test-admin2/.yarn/__virtual__/ra-core-virtual-9ca0fb2ce4/0/cache/ra-core-npm-4.1.5-6d476eb117-886c343e31.zip/node_modules/ra-core/dist/esm/auth/)

Ancestor breaking the chain: ra-data-json-server@npm:4.1.5
Ancestor breaking the chain: ra-i18n-polyglot@npm:4.1.5
Ancestor breaking the chain: ra-language-english@npm:4.1.5

`

**Describe the solution you'd like**
I hope the PnP mode can be supported. The dependencies needs to be resolved correctly. 
It will be faster to install. This is simply a feature request, an enhancement.

**Describe alternatives you've considered**
For now I have to switch back the nodeLinker to node-modules

**Additional context**

**Comment by fzaninotto** [comment]
pnp is a burden and it should work in that setup:

- react-admin has ra-core and react-router-dom as dependencies
- ra-core has react-router-dom as peerDependencies

We can't add react-router-dom as a direct dependency to ra-core as it would create bugs when using it directly.

If you have a solution, I'm open to a PR solving this issue.

**Comment by smeng9** [comment]
Hi @fzaninotto 

I did a little bit more research of the error message
`
Ancestor breaking the chain: ra-language-english@npm:4.1.5`
and https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency

> one or more of its parents in the dependency tree doesn't provide it.

Based on my understanding ra-language-english dependes on ra-core, but ra-language-english does not list react-hook-form as a peer dependency, so it breaks the chain for ra-core. 

If we add react-hook-form to peerdependency to ra-language-english, ra-i18n-\*, ra-data-\*, it should resolve the error. Similarly we add peerdependencies to other packages.

https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency provides several ways to fix it. Including add it to package extension database https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts

**Comment by fzaninotto** [comment]
This doesn't make any sense. ra-language-english doesn't use forms at all. I'm strongly -1 to add a peer dependency just to please pnp, because to my mind, what you describe is a broken logic.

**Comment by smeng9** [comment]
I also feels pnp is too strict about peer depenencies. ra-language-english has nothing to do with the form.

There is also another field in package.json called [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) where you can make an optional peerDependency not used by ra-language-english and just let it passed down to ra-core.

Anyway, I will close this for now as nodeLinker: node_modules can still be used, although [yarn defaults to pnp](https://yarnpkg.com/configuration/yarnrc/#nodeLinker).
