### ISSUE TITLE
FormDataConsumer in TabbedForm causes stacked content

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/react-admin#7890]
I am trying to dynamically create form tabs based on an array. I've done this before (in both aor and ra 3) as a means to edit multiple locales and it worked fine.

However now it shows the tabs, but they all have the same keys making the content render stacked, and only the first tab can be visited..

**What you were expecting:**

Normal tab behaviour.

**What happened instead:**

Stacked content (duplicating all three tabs into the first one's content).

**Steps to reproduce/related code:**

I've made a sandbox. It's under the admin user (logout, admin:password) and then users > create. I've used `defaultValues` as a means to illustrate the issue.

https://codesandbox.io/s/priceless-dirac-35969f?file=/src/users/UserCreate.tsx

The relevant lines are on 67:

```tsx
        <FormDataConsumer>
          {({ formData, ...rest }) => {
            return formData.exampleKey.map((example, index) => (
              <FormTab label={example.name} key={index} {...rest}>
                <TextInput source={`exampleKey.${index}.name`} />
              </FormTab>
            ));
          }}
        </FormDataConsumer>
```

exampleKey is being defined on line 54 and set as default on line 64.

**Other information:**

I think the issue is that the TabbedForm (or some other ascendent) is using the child count to create paths. In this case it's counting a single child: the FormDataConsumer. Perhaps the children should instead register themselves with the parent? I tried setting an explicit path, but no dice.

**Environment**

See sandbox. Forked from master.

**Comment by septentrion-730n** [comment]
Reproduced! Thanks for the report.

**Comment by thibault-barrat** [comment]
Thanks for reporting this.

Unfortunately, as stated in the documentation `TabbedForm`  only accepts `FormTab` as children ([https://marmelab.com/react-admin/TabbedForm.html#usage](https://marmelab.com/react-admin/TabbedForm.html#usage)).

For your specific use case, if you don’t need to use a `FormDataConsumer` to dynamically create your tabs you can directly map your array to create the `FormTab` :

```tsx
{defaultValues.exampleKey.map((item, index) => (
    <FormTab label={item.name} path={item.name} key={index}>
        <TextInput source={`exampleKey.${index}.name`} />
    </FormTab>
))}
```

If your use case is more specific, I invite you to use the support included in our React-admin Enterprise Edition.

**Comment by RWOverdijk** [comment]
@thibault-barrat I mean, they're docs. Someone wrote them so they can be changed. 😄 

So let's change the way it works then. I'll work on a fix and submit a PR. Please reopen so I have something to reference.

**Comment by RWOverdijk** [comment]
@thibault-barrat Bump.

Also, the docs here: https://marmelab.com/react-admin/TabbedForm.html#dynamic-tab-label literally use a non-FormTab component.

I believe this issue shouldn't be closed.
