### ISSUE TITLE
Variant props is not applied on RichTextInput

### ISSUE THREAD

**Issue by thibault-barrat** [marmelab/react-admin#7892]
**What you were expecting:**
I want to be able to use `variant` on `RichTextInput` in order to have a coherent style with other inputs.

**What happened instead:**
Use of `variant` props on `RichTextInput` doesn't change the style of the input.

**Steps to reproduce:**
Try to add `variant="standard"` on a `RichTextInput`

**Related code:**
See `PostEdit.tsx` in https://codesandbox.io/s/angry-https-x03e37

**Environment**

* React-admin version: 4

**Comment by septentrion-730n** [comment]
React Admin uses [tiptap](https://tiptap.dev/) for the RichTextInput, consequently it does not support Material UI `variant` property. 
We should port MUI theme configuration for the three variants over the tiptap/.ProseMirror context. 
We do not intend to implement this in a close milestone but would be pleased to review any related pull request. 👍

**Comment by fzaninotto** [comment]
There is no traction from the react-admin community on this feature request, so I'll close it. But feel free to open a PR is you have an implementation!
