### ISSUE TITLE
FormDataConsumer typescript bug

### ISSUE THREAD

**Issue by hamidfzm** [marmelab/react-admin#7896]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `ra-core@4.2.0` for the project I'm working on.

There is a typescript build issue.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ra-core/src/form/FormDataConsumer.tsx b/node_modules/ra-core/src/form/FormDataConsumer.tsx
index bbb4a82..e23f130 100644
--- a/node_modules/ra-core/src/form/FormDataConsumer.tsx
+++ b/node_modules/ra-core/src/form/FormDataConsumer.tsx
@@ -45,6 +45,7 @@ import warning from '../util/warning';
 const FormDataConsumer = (props: ConnectedProps) => {
     const formData = useWatch();
 
+    // @ts-ignore
     return <FormDataConsumerView formData={formData} {...props} />;
 };
 
@@ -57,6 +58,7 @@ export const FormDataConsumerView = (props: Props) => {
 
     // If we have an index, we are in an iterator like component (such as the SimpleFormIterator)
     if (typeof index !== 'undefined') {
+        // @ts-ignore
         scopedFormData = get(formData, source);
         getSource = (scopedSource: string) => {
             getSourceHasBeenCalled = true;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by septentrion-730n** [comment]
Hi thanks for the sharing!
As this Typescript nitpicking is not required internally, I do not tend to integrate into the package. I will discuss it with the team but close the issue for now.

**Comment by septentrion-730n** [comment]
Hi thanks for the sharing and the kudos!
As this Typescript nitpicking is not required internally, I do not tend to integrate into the package. I will discuss it with the team but close the issue for now.
