### ISSUE TITLE
<MenuItemLink> style override documentation not working

### ISSUE THREAD

**Issue by diegocgaona** [marmelab/react-admin#7898]
**What you were expecting:**
The styles applied on the menu

**What happened instead:**
Nothing changes

**Steps to reproduce:**
Tried the documentation example: (from https://marmelab.com/react-admin/Theming.html#using-a-custom-menu)

```
export const theme = {
    palette: {
        // ...
    },
    overrides: {
        RaMenuItemLink: {
            active: {
                borderLeft: '3px solid #4f3cc9',
            },
            root: {
                borderLeft: '3px solid #fff', // invisible menu when not active, to avoid scrolling the text when selecting the menu
            },
        },
    },
};
```

**Related code:**
Tried the following code and it works in parts, but I couldn't change the "active" RaMenuItemLink styles.
The icon color changes and the root styles too, but I couldn't make as the example.
Anyway, the documentation is not right at this item.
```

import { defaultTheme } from 'react-admin';

const theme = {
    ...defaultTheme,
    components: {
        ...defaultTheme.components,
        RaMenuItemLink: {
            styleOverrides: {
                root: {
                    borderLeft: '2px solid #919191', // invisible menu when not active, to avoid scrolling the text when selecting the menu
                    "& .RaMenuItemLink-active": {
                        borderLeft: '10px solid #EFC44F',
                        marginRight: '4px',
                        backgroundColor: 'rgba(239, 196, 79, 0.15)',
                    },
                    "& .RaMenuItemLink-icon": {
                        color: '#EFC44F',
                    },
                },
            },
        },
    },
};
```

**Other information:**
I think the documentation is not updated, need a update to the example work.
My code do that partially only (no active item style change)

**Environment**

* React-admin version: 4.2.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18.0.0
* Browser: Tested in Chrome and Firefox
* Stack trace (in case of a JS error):

**Comment by septentrion-730n** [comment]
Thanks for reporting! - this is a documentation issue.
Apply style using: 
```
"&.RaMenuItemLink-active": {
    borderLeft: '10px solid #EFC44F',
    marginRight: '4px',
    backgroundColor: 'rgba(239, 196, 79, 0.15)',
},
```
Note the removed space in `&.RaMenuItemLink-active`

**Comment by septentrion-730n** [comment]
Thanks for reporting. This is a documentation issue.

You can apply an active state with: `'&.RaMenuItemLink-active': {...}` , please note the removed space.
