### ISSUE TITLE
AutocompleteInput create text is undefined when using a function as option text

### ISSUE THREAD

**Issue by Guy-Adler** [marmelab/react-admin#7902]
**What you were expecting:**

When passing the `create` property to `AutocompleteInput`, the default text for the creation option should be `ra.action.create_item`.
![image](https://user-images.githubusercontent.com/44903310/175990045-7dd19aa9-4fcd-43cb-a425-0dedac9b114c.png)

**What happened instead:**

The text was `undefined`.
![image](https://user-images.githubusercontent.com/44903310/175989994-8ea9be37-155e-4df7-89d9-3672bc68ad97.png)

**Steps to reproduce:**

1. Create an AutocompleteInput where the `optionText` prop is a function.
2. Start typing a text which isn't an option.

**Related code:**

Code sandbox: https://codesandbox.io/s/fervent-breeze-muqxj4?file=/src/posts/TagReferenceInput.tsx

The change was made on lines 48:
```ts
optionText={(choice) => choice.name[locale]}
```

**Other information:**

This is probably caused by line 84 of  https://github.com/marmelab/react-admin/blob/58f9841d1fd7dbb3132376b6c50a2b0dd3ca4b8b/packages/ra-ui-materialui/src/input/useSupportCreateSuggestion.tsx#L69-L77
when passing optionText as a function, the string is always saved under `name`, which makes it impossible to use a combination of fields as the option text.

**Environment**

* React-admin version: 4.2.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: Google Chrome 102.0.5005.115 
* Stack trace (in case of a JS error):

**Comment by Guy-Adler** [comment]
As a workaround, one can use
```ts
const buildOption = (choice: any) => {
  if (choice.name !== undefined) {
    return choice.name;
  }
  return whatever you want;
};
```
however, this is very confusing

**Comment by septentrion-730n** [comment]
Bug reproduced, thanks for your report  👍
