### ISSUE TITLE
Two GetList `requests` triggering on Filter Change in Aside

### ISSUE THREAD

**Issue by imrans110** [marmelab/react-admin#7913]
**What you were expecting:**
When on a List page of a resource. I have filters in the aside which when changed are triggering the getList DataProvider twice.

**What happened instead:**
`GetList` should not be called more than once. Earlier I thought its something from from my end but then I looked at the React-admin demo and it seems to be doing the same thing. Triggering the getList twice for a resource. 

**Steps to reproduce:**

Go to the link below : 
 - https://marmelab.com/react-admin-demo/#/products
 - Try using the filters on the left side. 
 - Check the console for GetList FakeRest api 
 - You will see that it's getting called twice on any single action change in the filter

* Preferably, a CodeSandbox forked from 
 - https://marmelab.com/react-admin-demo/#/products?filter=%7B%7D&order=ASC&page=1&perPage=24&sort=reference

**Environment**

* React-admin version: 4.1.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.1.0
* Browser: Chrome
* Stack trace (in case of a JS error): NONE

**Comment by septentrion-730n** [comment]
This a [feature](https://react-query.tanstack.com/guides/window-focus-refetching#_top) from `react-query` which refresh stale data when focusing the window again. You can disable by passing an option to the `QueryClient`.

```
 const queryClient = new QueryClient({
   defaultOptions: {
     queries: {
       refetchOnWindowFocus: false,
     },
   },
 })

const App = () => (
   <Admin queryClient={queryClient}>
      ...
   </Admin>
);
```
