### ISSUE TITLE
TabbedForm with inputs above tabs

### ISSUE THREAD

**Issue by megantaylor** [marmelab/react-admin#7916]
**Is your feature request related to a problem? Please describe.**
i have form designs where we'd like to have a few inputs followed by tabs for form sections. 

for example:

name input
some other input
tab 1     tab 2     tab 3

I can implement this on my own with a SimpleForm and my own tabs component, but i miss the feature of TabbedForm that updates the path with the name of the active tab.

**Describe the solution you'd like**
Let me add inputs directly as children of TabbedForm, which will appear above the tabs, regardless of which tab is active.

**Comment by fzaninotto** [comment]
Hi, thanks for the suggestion. This isn't something we consider common enough to be supported out of the box by react-admin. Besides, as you said it, you can implement it in userland. And if you need to update the path, you probably need to use react-router.
