### ISSUE TITLE
selectinput validation not working with onblur mode

### ISSUE THREAD

**Issue by megantaylor** [marmelab/react-admin#7920]
**What you were expecting:**

When choosing the empty value on a SelectInput with validate={required()} in a form with mode="onBlur", the error state on the input should appear on blur.

**What happened instead:**

i have a SelectInput in a form with mode="onBlur" on the form and validate={required()} on the SelectInput. When I change to the empty value, nothing happens.

**Steps to reproduce:**

https://codesandbox.io/s/small-dew-omw0di?file=/src/posts/PostEdit.tsx

In the Categories select input, select the empty value 

**Related code:**

https://codesandbox.io/s/small-dew-omw0di?file=/src/posts/PostEdit.tsx

**Environment**

* React-admin version: latest

**Comment by septentrion-730n** [comment]
Hi Megan,

I am not able to reproduce this behaviour, the required check happens on the blur event, at least with my config. 
Are you experiencing something different from the screencast  below?

https://user-images.githubusercontent.com/102964006/177116484-60fece67-c648-4fb5-9f43-a2a05cba15a9.mov

**Comment by megantaylor** [comment]
ah, it does look like its working in my codesandbox fork now, no idea why it wasnt working last week.
