### ISSUE TITLE
TranslatableInputs included into TabbedForm cause MUI error

### ISSUE THREAD

**Issue by vzhyhunou** [marmelab/react-admin#7922]
It looks like TranslatableInputs cause this issue if included into parent TabbedForm:

`"react-admin": "4.2.0"`

![Screenshot from 2022-07-02 18-57-56](https://user-images.githubusercontent.com/6532982/177007743-0c005826-8215-4850-aec2-56a82394d9bc.png)

If you select BODY tab then you can see error message in console:

![Screenshot from 2022-07-02 18-58-40](https://user-images.githubusercontent.com/6532982/177007749-c191512e-77b1-4e30-9e7f-fe1574da3627.png)

```
const PostEdit = () => (
    <Edit>
        <TabbedForm>
            <FormTab label="Summary">
                <TextField source="id" />
                <TextInput fullWidth source="title" />
                <TranslatableInputs locales={['en', 'fr']}>
                    <TextInput fullWidth source="teaser" />
                </TranslatableInputs>
            </FormTab>
            <FormTab label="Body" path="body">
                <TextInput multiline fullWidth source="body" />
            </FormTab>
        </TabbedForm>
    </Edit>
);
```
[CodeSandbox](https://codesandbox.io/s/e5qq8q)

**Comment by fzaninotto** [comment]
This seems to be a material-ui bug. I've opened an issue in their tracker: https://github.com/mui/material-ui/issues/33606

**Comment by fzaninotto** [comment]
We won't keep this issue open as it's a MUI issue. It'll be solved when they solve it, and as MUI is a Peer dependency you can upgrade your MUI version when it's done.
