### ISSUE TITLE
Record prop missing in EditBase/useEditController

### ISSUE THREAD

**Issue by jhrncar** [marmelab/react-admin#7923]
In docs, we see **_record_** prop available inside EditBase and useEditController:
![image](https://user-images.githubusercontent.com/71822106/177205124-ecc016c0-326f-4226-a87d-a294c7471a8d.png)
https://marmelab.com/react-admin/doc/4.0/EditBase.html

However, when we take a look at the type and props accepted, we see no mention of _**record**_ prop:
![image](https://user-images.githubusercontent.com/71822106/177205272-92194710-9241-40a9-aef8-7859aa4875b4.png)

Disclosure: this is my first issue submit, sorry for the lack of relevant info, feel free to give advice in responses.

* React-admin version: 4.2.0 (tested also in 4.0.4)
* Last version that did not exhibit the issue (if applicable): haven't tested
* Browser: Chrome

**Comment by fzaninotto** [comment]
You're right, the doc is misleading, it's not possible to pass a custom record to Edit, EditBase, or useEditController. they only accepts a custom id, that they'll use instead of the id from the URL path when passed. 

Marking this a s a documentation bug.

**Comment by jhrncar** [comment]
Thanks! But wouldn't it be better to enable this funcionality? Is there any workaround to passing record to Edit so taht it wouldn't query the API?

**Comment by fzaninotto** [comment]
If you already have a record, you don't need 50% of the work done by the Edit controller - so in my opinion, it's not the Edit controller's job to handle this case.

I understand that you just need an update callback to hook into a form. You can do that by hand using [`useUpdate`](https://marmelab.com/react-admin/useUpdate.html).

So I'm -1 to support this functionality.

**Comment by jhrncar** [comment]
Fair enough, totally forgot about useUpdate. Thanks!
