### ISSUE TITLE
Cannot delete leading character in AutocompleteInput

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7935]
**What you were expecting:**
Proper text input handling for AutocompleteInput.

**What happened instead:**
The leading character cannot be deleted, you must shift in front of the leading character to make changes.

**Steps to reproduce:**
Insert text into AutocompleteInput and attempt to remove it all with the delete key.

**Related code:**
https://codesandbox.io/s/frosty-moon-97b3ol

Open the Post create form and attempt to add/delete text in the Authors input

**Environment**

* React-admin version: 4.2.2
* Last version that did not exhibit the issue (if applicable): 4.2.1
* React version: 17
* Browser: Chrome

**Comment by cduran-seeri** [comment]
I have the same issue in many filters +1

**Comment by ronfogel** [comment]
Not a big issue as you can select all and override the text and it works + move the cursor before the character and add text but it's super annoying!
