### ISSUE TITLE
ArrayInput add/copy item underneath

### ISSUE THREAD

**Issue by Jayfrown** [marmelab/react-admin#7936]
**Is your feature request related to a problem? Please describe.**
We have some entities that hold arrays with a large number of items (100+). The specific order of the array is of importance. The array's value is largely automatically generated, but sometimes someone wants to manually add items to the array.

If someone wants to add an item at position 20, they have to add it at the bottom of the list and click the "re-order up" button a bunch of times to get it in the right position.

It would be great if we could either add a new item underneath any existing item, or copy an item underneath itself so you can then edit the values.

**Describe the solution you'd like**
A button at every item in an ArrayInput to add or copy above/beneath

**Describe alternatives you've considered**
Alternatively the ArrayInput order number could be editable so you can input the order number yourself, but if 20 and 21 exist, you add a new one at the bottom and enter "21" as order number, it would be duplicate.

**Additional context**
I'm be happy to provide additional context if someone needs it, just ask if something isn't clear.

**Comment by septentrion-730n** [comment]
Thanks for your suggestion, this feature could be pretty useful. This topic will be discussed with the team.
