### ISSUE TITLE
Don't clear filter text on `AutocompleteArrayInput` after selection has been made

### ISSUE THREAD

**Issue by yoitsro** [marmelab/react-admin#7939]
**Is your feature request related to a problem? Please describe.**
When selecting options from the `AutocompleteArrayInput` component, as with a `SelectArrayInput`, I may want to select multiple options at once without the selection options disappearing and without the filter text being cleared after a selection is made.

A `SelectArrayInput` is not a feasible solution in this case because the selection options are being populated via a `ReferenceArrayInput`.

**Describe the solution you'd like**
It should be possible for this behaviour to be enabled when required via setting a prop such as `clearsFilterUponSelection={false}`.

**Describe alternatives you've considered**
I've looked through the source code and this functionality doesn't look immediately possible using any of the existing props. An alternative would be to create a brand new component, but it would largely have the same functionality as the existing component.

**Additional context**
None.

**Comment by septentrion-730n** [comment]
IMHO `AutocompleteArrayInput` is suited for for the most common cases, adding more options to it would complicate an already quite bloated component. I tend to think that such a behaviour should be extended in userland. Will be discussed with the core team though!

**Comment by fzaninotto** [comment]
I agree, this isn't something we'll implement in the core package. You can write your own `AutocompleteArrayInput` to replace react-admin's component for your use case.
