### ISSUE TITLE
Documentation correction on Permissions Page

### ISSUE THREAD

**Issue by dcheli** [marmelab/react-admin#7946]
**What you were expecting:**
This is not a bug, but what I think is an error in the documentation on the 
[https://marmelab.com/react-admin/doc/4.0/Permissions.html](https://marmelab.com/react-admin/doc/4.0/Permissions.html) page, 
under the section **Restricting Access to Resources or Views**

I believe that the documented syntax
`{permissions => (
<>
<Resource ....
</> )}`

should be:

`{permissions => [
<>
<Resource ....
</> ]}`

I apologize if this is the wrong category to report this, I was not sure the best way to. 

**What happened instead:**

**Steps to reproduce:**

* A link to a GitHub repo with the minimal codebase to reproduce the issue

**Environment**

* React-admin version: 4
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
In fact, both syntaxes are correct:

```jsx
// either
{permissions => ( <> <Resource .... </> )}
// or
{permissions => [<Resource .... </>]}
```

Why do you think the doc is wrong?

**Comment by dcheli** [comment]
Using the {permissions => ( <> <Resource .... /></> ) notation in the documentation produces this error:

error: TS2322: Type '(permissions: any) => Element' is not assignable to type 'AdminChildren'.
  Type '(permissions: any) => Element' is not assignable to type 'RenderResourcesFunction'.
    Type 'Element' is not assignable to type 'ResourceElement[] | Promise<ResourceElement[]>'.

When I use the {permissions => [ <> <Resource .... </> ]}  notation, I don't get that error and my program works.

Dave

**Comment by fzaninotto** [comment]
You're right, I managed to reproduce the issue at https://codesandbox.io/s/determined-firefly-d9fnhr

It's weird that the simple example in the react-admin repository doesn't show the TypeScript error. 

Anyway, I'm marking this as a TypeScript bug. Thanks for the report.
