### ISSUE TITLE
Error with Pagination props

### ISSUE THREAD

**Issue by rafaelgslima** [marmelab/react-admin#7955]
**What you were expecting:**

I need to create a custom list component using hooks to deal with requests. So, I don't want to use the `<List>` component.
I saw in the documentation that it is possible to use `<Datagrid> With A Custom Query`. [The doc can be read here](https://marmelab.com/react-admin/doc/3.19/List.html#rendering-datagrid-with-a-custom-query)
As you can see in the doc, we can use the `<Pagination>` component after `<Datagrid>` passing these props:
![image](https://user-images.githubusercontent.com/3819008/178002482-28a4a5eb-6118-4acb-829c-dda3cf1d6fd2.png)

So, I have been expecting to use that without error.

**What happened instead:**

However, when I use these props in `<Pagination>` with Typescript, I have an error, because `<Pagination>` just receives these props:
![image](https://user-images.githubusercontent.com/3819008/178002914-08baff99-1416-4d1d-93ce-4237b7008bc4.png)

The error is:
![image](https://user-images.githubusercontent.com/3819008/178004280-97b694d6-5560-40bc-9543-9d402f2e6448.png)

**Steps to reproduce:**

**You can see the error here:** https://codesandbox.io/s/heuristic-ganguly-jhsu68?file=/src/posts/PostList.tsx

![image](https://user-images.githubusercontent.com/3819008/178004445-fbb50229-e1c5-4e76-83c3-f3883fb3d1d0.png)

**Related code:**

* React-admin version: 3.19.10
* React version: 17.0.2
* Browser: All

**Comment by tassioFront** [comment]
Same happing with me.

**Comment by fzaninotto** [comment]
Reproduced on 4.x, thanks!

**Comment by schirrel** [comment]
@fzaninotto i am having this problem at version 3.19, could you fix for that version also?

**Comment by fzaninotto** [comment]
@schirrel not in the near future, but you're welcome to take inspiration from #7956 and submit a PR against the 3.x branch!

**Comment by schirrel** [comment]
sure @fzaninotto, i gonna work on it
