### ISSUE TITLE
How to create two related component in one form (user and its address)

### ISSUE THREAD

**Issue by aurepito** [marmelab/react-admin#7964]
Hi!

I'm trying to make a react-admin component for create User and its Address in one form. (one-to-one relation)

Here the schema:
- **User** (Name, AddressId)
- **Address** (Street, City, Country)

Through different ways, I tried with ReferenceField/ReferenceInput but the best answer I found is with a `select` and create/show buttons. ([Link to tutorial](https://marmelab.com/blog/2018/08/27/react-admin-tutorials-custom-forms-related-records.html))

I just want to make a CreateForm component which contains 4 text inputs like this :
- user name
- address street
- address city
- address country

Is it possible through the react-admin components ?

**Comment by RWOverdijk** [comment]
> Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.
> 
> For support question ("How To", usage advice, or troubleshooting your own code), you have three options:
> 
> * **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
> * **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
> * **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
> 
> If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.
> 
> So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

The discord link says that the invite is invalid. I found this issue by googling for a discord link, I think that's a great idea.

Got any of those invites that works?
