### ISSUE TITLE
Inputs inside ReferenceInput's child's create component receive improper props

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7965]
**What you were expecting:**
Inputs inside a "create" form component passed to a SelectInput or an AutocompleteInput inside a ReferenceInput to behave the same as those form elements in and standalone use-case

**What happened instead:**
Inputs receive odd props; choices, labels, etc. seem to be inherited from the ReferenceInput parent component instead of the props passed to the form inputs themselves.

**Steps to reproduce:**
Pass a number of form inputs to a "create" component and observe their labels/choices.

**Related code:**
https://codesandbox.io/s/compassionate-herschel-5re5vg?file=/src/posts/PostCreate.tsx 
Navigate to the Post create form and attempt to create a user at the "Author" input. Observe that the "type" SelectInput has inherited incorrect choices and label.

**Environment**

* React-admin version: 4.2.2
* Last version that did not exhibit the issue (if applicable): 
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by sidescraper** [comment]
for me the createItemLabel is not displayed. is empty

```
<ReferenceArrayInput source="visitors" variant="outlined" reference="eventVisitor"
  perPage={1000} sort={{ field: 'disp_name', order: 'ASC' }}>
      <AutocompleteArrayInput optionText="disp_name" create={<CreateGast />} createItemLabel="Erstellen" />
</ReferenceArrayInput>
```

**Comment by djhi** [comment]
Reproduced. Thanks!
