### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by ENGR-MANSOOR** [marmelab/react-admin#7966]
I have created a simple admin application dashboard with ra-data-JSON server and using my own API, whenever I update the record of any user, it gives always "Cannot read properties of undefined (reading 'id')" although data is updated in the database. I have tried a lot and I think its a bug from the framework side

**Comment by djhi** [comment]
Please follow the issue template

**Comment by ENGR-MANSOOR** [comment]
///////update Record In edit View ////////////
    update:  (resource, params) =>
          httpClient( `${apiUrl}/${resource}/${params.id}`, {
              method: 'PUT',
              body: JSON.stringify(params.data),
          }).then(({ json }) => ({ data: json })),
  
      // simple-rest doesn't handle provide an updateMany route, so we fallback to calling update n times instead/////
      updateMany: (resource, params) =>
          Promise.all(
              params.ids.map(id =>
                  httpClient(`${apiUrl}/${resource}/${id}`, {
                      method: 'PUT',
                      body: JSON.stringify(params.data),
                  })
              )
          ).then(responses => ({ data: responses.map(({ json }) => json.id) })),
  
    ///////update Record In edit View end ////////////

**Comment by fzaninotto** [comment]
Invalid issue: you didn't follow the issue template, you didn't provide a reproduction. We cannot consider it.
