### ISSUE TITLE
Allow a custom filtering function for useList

### ISSUE THREAD

**Issue by Guy-Adler** [marmelab/react-admin#7970]
**Is your feature request related to a problem? Please describe.**
Currently, when using `useList`, one can only use eq/in filters.
The code for it is here:  https://github.com/marmelab/react-admin/blob/5feeda4bb9dec99f31a174448ff4df5f8aaa8318/packages/ra-core/src/controller/list/useList.ts#L159-L175

**Describe the solution you'd like**
useList should accept a function to use as the callback to the `.every` call. This way, we will be able to use more complex, custom features such as gte/lte, like the example [here](https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators).

**Describe alternatives you've considered**
The only alternative I'm able to see is cloning the file and changing those specific lines, but that seems like a bad idea.

**Additional context**

**Comment by oguhpereira** [comment]
I tried to assemble a pr that maybe meets this demand

**Comment by fzaninotto** [comment]
Fixed by #8116
