### ISSUE TITLE
input 'source' prop doesn't support numeric keys  in path (version 3 only)

### ISSUE THREAD

**Issue by danield770** [marmelab/react-admin#7971]
Assuming data with an object which contains numeric keys, something like:

```
data: {
    tables: { '1': 'available', '2': 'reserved', '3': 'in use' }
}
```

**What you were expecting:**
In create/edit views I should be able to pass a path to the source prop of the input containing the number `source="data.tables.1"`

```
<SelectInput
      source="data.tables.1"     <======
      label="Table 1"
      choices={[
      { id: 'in use', name: 'in use' },
      { id: 'reserved', name: 'reserved' },
      { id: 'available', name: 'available' }
      ]}
/>
```
`
**What happened instead:**
I get the error: 

"Cannot set a numeric property on an object"

**Steps to reproduce:**
Click Edit in the demo.

**Related code: (codesandbox)**
https://17jwen.csb.app/#/tables 

**Environment**
* React-admin (and ra-data-fakerest) version 3 (Versions 2.* and 4.* seem to work as expected)
* React version 17
* Browser: Chrome

**Comment by fzaninotto** [comment]
This is a react-final-form bug that needs to be fixed upstream. I invite you to open an issue at https://github.com/final-form/react-final-form instead.
