### ISSUE TITLE
ra-preferences deprecated, but no upgrade path for SelectColumnsButton?

### ISSUE THREAD

**Issue by braco** [marmelab/react-admin#7973]
It seems like ra-preferences has been deprecated.

What happened to `SelectColumnsButton` and `useSelectedColumns`? The docs don't mention any upgrade path.

Thanks

**Comment by djhi** [comment]
We plan to add them back in react-admin, hopefully in the next minor version

**Comment by braco** [comment]
thanks @djhim, do you guys keep a roadmap anywhere that maps these kind of issues? I'll need to back out of the upgrade I started on

**Comment by braco** [comment]
@djhi was this abandoned?

**Comment by slax57** [comment]
@braco no it is not.
We have made a (big) first step into adding this kind of feature back in react-admin (although in a different way) with this PR: https://github.com/marmelab/react-admin/pull/8145
Adding back selectable columns into Datagrid will probably one of the very next thing we will build on top of this.
You can also try to add it on your side and submit it as a PR if this is a critical feature for you app.

**Comment by fzaninotto** [comment]
See #8274 for the ongoing implementation

**Comment by fzaninotto** [comment]
Fixed in #8274
