### ISSUE TITLE
<SelectInput /> inside <ReferenceInput /> not showing a <LinearProgress /> when loading

### ISSUE THREAD

**Issue by newfylox** [marmelab/react-admin#7975]
**What you were expecting:**
See a `<LinearProgress />` when `<ReferenceInput />` if fetching options.

**What happened instead:**
It only show the label without the `<input />` at first glance and then the `<input />` appears, making the form changing size if the fields are vertically aligned.

**Steps to reproduce:**
* visit that demo https://marmelab.com/react-admin-crm/#/companies/create
* look at the **Account manager** field when refreshing the page
* it happens on my forms too

**Related code:**
probably related around this as if `isLoading` is true before options are (I suppose) https://github.com/marmelab/react-admin/blob/5feeda4bb9dec99f31a174448ff4df5f8aaa8318/packages/ra-ui-materialui/src/input/SelectInput.tsx#L236-L248

**Environment**

* React-admin version: 4.2.2

**Comment by fzaninotto** [comment]
Reproduced, thanks for the report.
