### ISSUE TITLE
NumberInput never be touched

### ISSUE THREAD

**Issue by bingluen** [marmelab/react-admin#7980]
**What you were expecting:**
fieldState.isTouched of NumberInput should be set touched if field has received a focus and blur event.

**What happened instead:**
fieldState.isTouched always keep `false`, event touch it.

**Steps to reproduce:**

just touch NumberInput field and observe its state

**Related code:**

https://codesandbox.io/embed/cranky-yonath-zh60ob?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fposts.js&theme=dark&view=editor

**Other information:**

**Environment**

* React-admin version: 4.x
* React version: 17
* Browser: Edge 102.0.1245.33

**Comment by septentrion-730n** [comment]
Reproduced, thanks for submitting this issue.
