### ISSUE TITLE
Backgroundcolor of resettable selectinput in focus does not cover complete input

### ISSUE THREAD

**Issue by lvernaillen** [marmelab/react-admin#7985]
**What you were expecting:**
When a resettable SelectInput gets focus, a darker grey background is applied which covers the complete input.

**What happened instead:**
Only part of the input gets the darker grey background leaving the right part (padding) of the input next to the dropdown glyph in light grey color.

**Steps to reproduce:**
- Open the simple blog demo
- Go to the Posts list view
- Select a post to go to the post edit view
- Select the Miscellaneous tab
- Notice Category selectinput has light grey background
- Select a different value for the Category selectinput
- Notice only part of the focussed Category selectinput has dark grey background

![input-background-focus](https://user-images.githubusercontent.com/4180374/179574382-45eedfdd-fdca-4a51-96d1-14bff6cb601a.png)

**Related code:**
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Other information:**
SelectInput without the resettable prop does not show this behavior.

**Environment**

* React-admin version: tested on 4.1.0 and master
* Last version that did not exhibit the issue (if applicable): ?
* React version: 17
* Browser: Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by fzaninotto** [comment]
Reproduced, thanks!
