### ISSUE TITLE
Multiple resources highlighted in sidebar if one resource is substring of another

### ISSUE THREAD

**Issue by HemalPatil** [marmelab/react-admin#7988]
**What you were expecting:**
Clicking on a resource in the side menu should highlight only that resoure's icon in the side menu list

**Steps to reproduce and What happened instead:**
Clicking on resource `name=sub1-dummy` highlights both `Sub1` and `Sub1-dummy` in the sidebar menu

**Related code:**

Codesandbox - https://codesandbox.io/s/floral-flower-pgyv8i?file=/src/dataProvider.tsx (forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4))

```
<Resource name="sub1" list={ListGuesser} />
<Resource name="sub1-dummy" list={ListGuesser} />
```

**Environment**

* React-admin version: 4.2.2
* Last version that did not exhibit the issue (if applicable): 3.15.2
* React version: 18.2.0
* Browser: Chrome Version 103.0.5060.114 (Ubuntu) (Official Build) (64-bit)

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. This is indeed a problem in your case. 

But this is the way react-router's `<NavLink>` works, and we've reproduced the same in our own `<MenuItemLink>` component. The reason for that is that we want to match a route with a query string. Changing that would be a breaking change and have unwanted side effects. 

If this is not the behavior you need, you'll have to override the default menu with one of your own , as described in [the Theming documentation](https://marmelab.com/react-admin/Theming.html#using-a-custom-menu).
