### ISSUE TITLE
Partial Pagination Not Working for `ReferenceManyField`

### ISSUE THREAD

**Issue by MichaelSandor** [marmelab/react-admin#8014]
**What you were expecting:**

When the `getManyReference` method of the `dataProvider` returns `pageInfo` instead of `total`, [partial pagination](https://github.com/marmelab/react-admin/pull/7120) should be in effect for the pagination component passed to the `ReferenceManyField` component.

**What happened instead:**

When the `getManyReference` method of the `dataProvider` returns `pageInfo` instead of `total`, the pagination component passed to the `ReferenceManyField` component does not render at all.

**Steps to reproduce:**

1. Pass a `Pagination` component to the `ReferenceManyField`:
https://marmelab.com/react-admin/ReferenceManyField.html#pagination
2. Have the `getManyReference` method of the `dataProvider` return `pageInfo` instead of `total`.

**Other information:**

This could be the culprit [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/field/ReferenceManyField.tsx#L92) as the `pagination` prop is not rendered unless `total` is defined.

**Environment**

* React-admin version: 4.0.1
* React version: 18.0.0
* Browser: Chrome 103.0.5060.134

**Comment by septentrion-730n** [comment]
Thanks for reporting! 

Could you provide a behaviour reproduction sandbox? 
- a CodeSandbox forked from [simple example V4](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or [v3](https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple)
- a link to a GitHub repo with the minimal codebase to reproduce the issue?

Many thanks for your help in this matter! 👍

**Comment by MichaelSandor** [comment]
> Thanks for this helpful and almost perfect reporting!
> 
> Could you provide a behaviour reproduction sandbox?
> 
> * a CodeSandbox forked from [simple example V4](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or [v3](https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple)
> * a link to a GitHub repo with the minimal codebase to reproduce the issue?
> 
> Many thanks for your help in this matter! 👍

Thank you @septentrion-730n! I will do this soon.

**Comment by MichaelSandor** [comment]
Hi @septentrion-730n, here is the reproduction sandbox:

https://codesandbox.io/s/sad-murdock-lgb5ck

The changes I made are as follows:
1. Set every comment's `post_id` to 13.
2. Pass a `Pagination` component to the `ReferenceManyField` in `PostShow` (line 90).
3. Set `perPage` of the same `ReferenceManyField` to 5 (line 91).
4. "Override" the default `getManyReference` of the `dataProvider` to use partial pagination (lines 11-22).

Notice how the pagination does not render at the following path: `posts/13/show/3`.

However, when commenting out the fourth change, pagination works because the default implementation of `getManyReference` returns a `total` value.

**Comment by MichaelSandor** [comment]
### With Partial Pagination (Nothing Rendered)
![Screen Shot 2022-07-28 at 3 32 11 PM](https://user-images.githubusercontent.com/29845136/181648190-1a60ce72-33c4-41e7-8c98-d6c1a998f695.png)

### With Regular Pagination (Rendered)
![Screen Shot 2022-07-28 at 3 33 25 PM](https://user-images.githubusercontent.com/29845136/181648344-8b0b2b45-ab0e-48c6-bf1a-877364ee0817.png)

**Comment by WiXSL** [comment]
Reproduced, thanks!

**Comment by MichaelSandor** [comment]
For those who encounter this issue in the future, a workaround is to return `total` as `null` as part of the `getManyReference` method of the `dataProvider`.

As an example:

```
getManyReference: (resource, params) => {

   ...

   return httpClient.get(path).then(res => ({
      data: ...
      pageInfo: {
         ...
      },
      total: null,
   }))

   ...

```

For those who use TypeScript, you can use the `@ts-expect-error` or `@ts-ignore` directives to suppress the type error that will arise as `total` is expected to be `number` or `undefined`.
