### ISSUE TITLE
meta is undefined in params of delete method of dataProvider when using DeleteButton

### ISSUE THREAD

**Issue by carlos-duran** [marmelab/react-admin#8016]
**What you were expecting:**

Receiving `meta` in data provider when using DeleteButton with `mutationOptions` prop.

**What happened instead:**

`meta` is undefined in the `delete` method of `dataProvider`.

**Steps to reproduce:**

1. Open [my fork of code sandbox](https://codesandbox.io/s/young-pond-nioyun?file=/src/users/UserEdit.tsx:613-683), logout and login with "user" and "password"
2. Navigate to Users, pick one and enter to Edit page
3. Click on the Delete button
4. Check the console

**Related code:**

https://codesandbox.io/s/young-pond-nioyun?file=/src/users/UserEdit.tsx:613-683

```js
// UserEdit.tsx line 34
<DeleteWithConfirmButton mutationOptions={{ meta: { foo: "bar" } }} />
```

```js
// dataProvider.tsx line 47
delete: (resource, params) => {
    // HERE
    console.log("No meta :(", { params });
    return dataProvider.delete(resource, params);
  }
```

**Other information:**

![image](https://user-images.githubusercontent.com/15650777/181243900-ce16226f-bd68-4df3-ba62-e6cd0bde2130.png)
![image](https://user-images.githubusercontent.com/15650777/181244018-7049c5af-dd21-4add-8bde-148df5c06003.png)

Suggestion to possible fix:
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx#L98
```js
// ra-core/src/controller/button/useDeleteWithConfirmController.tsx line 98
// ra-core/src/controller/button/useDeleteWithUndoController.tsx line 66

// from
{ id: record.id, previousData: record }
// to
{ id: record.id, previousData: record, meta: mutationOptions.meta }
```
![image](https://user-images.githubusercontent.com/15650777/181247808-da7b03fb-b0fd-4ab8-8c45-3bdf4149da7c.png)

**Environment**

* React-admin version: 4.2.4
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: Chrome 100+
* Stack trace (in case of a JS error):

**Comment by septentrion-730n** [comment]
Bug reproduced - thank you for your report and the fix, it allowed a wider check of meta support.
