### ISSUE TITLE
Emptying URL search params doesn't reset List filters to default values 

### ISSUE THREAD

**Issue by wattroll** [marmelab/react-admin#8025]
**What you were expecting:**

At List pages when URL's search query is emptied (e.g. with a back button), List should be reset to default filter values. 

**What happened instead:**

List stays with the filters that were there.

**Steps to reproduce:**

1. Open Posters Galore.
2. Open "Orders"
3. Switch to e.g. "Cancelled" tab
4. Press the back button
=> The tab won't switch back

https://user-images.githubusercontent.com/79251424/182068543-dcdea2dc-ef49-4c2d-b420-f02a0e1fe138.mp4

**Environment**
Posters galore demo, as well as local app.
* React-admin version: 4.2.5 (latest)
* React version: 18
* Browser: firefox, chrome

**Comment by fzaninotto** [comment]
This is a feature. React-admin remembers the last filters entered by the user on each list page. 

If you want the menu to reset filters, check https://marmelab.com/react-admin/Menu.html#resetting-filters-on-menu-click

**Comment by wattroll** [comment]
Right. The feature makes sense to me now. Thanks for the link, nice that it is well documented.

I appreciate the feature, however, I perceive the following flow as "back button not working":

0. Navigate to "/commands" (via menu, or direct link)
1. Starts at "Ordered" tab with URL `/commands`
2. Clicks to "Delivered" tab => `/commands?filter={status:delivered}`
3. Clicks to "Cancelled" tab => `/commands?filter={status:cancelled` 
4. Clicks back button: `/commands?filter={status:delivered}` => Returns to "Delivered"
5. Clicks back button: `/commands` => **Stays at "Delivered"**

I think many would expect that step 5 would take them back to where they started from.

For a quickfix in my app I added a hack along the lines of:

```typescript
const { filterValues, setFilters, displayedFilters } = useListContext();
useEffect(() => {
  if (window.location.search === "") {
    setFilters(filterValues, displayedFilters, false);
  }
}, [window.location.search]);
```

Which makes it so that whenever the user lands with an empty query (be it from the menu click, or direct link) the URL is adjusted to represent the default filters.

Perhaps that (but implemented properly) could be the default behaviour?

**Comment by afilp** [comment]
@fzaninotto If this is not to be implemented as an option, could the "hack" of @wattroll be added in the DOC section here for everybody else to have the code to apply it themselves? (it is quite useful, this is why)
https://marmelab.com/react-admin/Menu.html#resetting-filters-on-menu-click

Thanks!

**Comment by fzaninotto** [comment]
Yes, a PR to add this to the doc is welcome.
