### ISSUE TITLE
List embed inside List

### ISSUE THREAD

**Issue by ENGR-MANSOOR** [marmelab/react-admin#8034]
I would like to request you to add the feature of embedding a list view inside a list via the edit and show button.

Let's say I have a list with the unique id of the employee and further this specific employee has data on various IDs in it like its yearly based salary details or any other activity which updates on change of the year. can't repeat list prop twice in the same resource and there is not another way round. 

Only customized list prop can be written via routes, if you already know about this or any plan, please update

**Comment by fzaninotto** [comment]
Sorry, I fail to understand your use case. Could you show some screenshots / mockups of the UI you imagine?

**Comment by ENGR-MANSOOR** [comment]
![list1](https://user-images.githubusercontent.com/51232085/182817321-fef415cd-df39-4d43-9a8c-88acd5a5dd4b.png)

As you can see in list 1 image, have employees list and each employee has further various details on yearly based with multiple unique IDs.
After clicking on edit in list 1, it should take to list 2 images with list view where all yearly based report of the employee can get in list view

![list 2](https://user-images.githubusercontent.com/51232085/182817591-888df4cd-660a-4ec8-a997-e02f4fceb7d5.png)

**Comment by fzaninotto** [comment]
I think you're looking for [ArrayField](https://marmelab.com/react-admin/ArrayField.html), [ReferenceArrayField](https://marmelab.com/react-admin/ReferenceArrayField.html), or [ReferenceManyField](https://marmelab.com/react-admin/ReferenceManyField.html).

**Comment by ENGR-MANSOOR** [comment]
I have an array of employees and at one point I want to maintain and update a record of employees (e.g) increment in salary on a yearly basis or change of some other parameters which are further in other tables on different unique IDs so the main employees table has one more table inside with the child IDs. It is supposed to be Datagrid inside Main-List. it is hardly possible with the above-mentioned hooks but it is not a suitable and sustainable solution. I would suggest creating a hook list or something like that which would simply let the Datagrid call inside a list or let resources use more than one hook of the list.

**Comment by fzaninotto** [comment]
I read your reply three times but I couldn't understand your use case. Could you please rephrase using smaller sentences, examples, and the same vocabulary as we use in react-admin?

**Comment by ENGR-MANSOOR** [comment]
![flowdiagram drawio](https://user-images.githubusercontent.com/51232085/183602809-631ce40a-5997-451d-bbca-dd96f4df6fe7.png)


In Attached pic its clear as i have  table inside a table so to work with this scenerio i need two list or list inside list than further can edit, show or create etc. 

fields methods like [ArrayField](https://marmelab.com/react-admin/ArrayField.html), [ReferenceArrayField](https://marmelab.com/react-admin/ReferenceArrayField.html), or [ReferenceManyField](https://marmelab.com/react-admin/ReferenceManyField.html). what you purposed is not easy to integrate into this situation as it needs a complicated way of id provision and so on. it supposed to get id_main for main list and id_secondary for the secondary list from an array.

Fields error gives error on repetition of main_id because one main_id has many secondary_ids.

I hope its clear now

**Comment by fzaninotto** [comment]
So react-admin doesn't provide components for this use case, and we won't do for the foreseeable future. 

You'll have to develop them using low-level react-admin hooks, or pure React.
