### ISSUE TITLE
FilterButton + SavedQueriesList + FilterForm - filter is stuck and cannot be unselected

### ISSUE THREAD

**Issue by GreoN5** [marmelab/react-admin#8041]
The problem is when I have hidden filters inside the filter button. 

Steps to replicate:
1. I click on one of filters inside the dropdown menu of the FilterButton.
2. Filter appears as usual and I save it with the SavedQueriesList.
3. I try to unselect - works fine.
4. Then again I select the saved query from the SavedQueriesList
5. From then if I try to unselect the query from the SavedQueriesList it gets stuck and does not work.

Sandbox: https://codesandbox.io/s/late-forest-dg505c?file=/src/posts/PostFilters.tsx

I know that with I can save the queries with the last menu item of the dropdown of the FilterButton, but I decided to make it this way, because in my opinion is more user-friendly and just added the additional component SavedQueriesList next to it.

**Comment by fzaninotto** [comment]
You're mixing components from the Button/Form combo, and `SavedQueriesList`, which is designed to work in the `FilterList`. This is not supported. You have to use either one of the two, or build your own filter components.
