### ISSUE TITLE
Automatic translation (i18n) support for emptyText

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#8044]
**Is your feature request related to a problem? Please describe.**

The `emptyText` prop value of field components is not automatically translated as it is done for the `label` prop.

**Describe the solution you'd like**

Having the possibility to have the `emptyText` prop value being translated when available for example:

```typescript
<Tab
  // The label prop is being automatically translated.
  label="resources.rides.tabs.path"
  path="path"
>
  <DateField
    source="startedAt"
    showTime
    // Expected to be translated too.
    emptyText="resources.rides.emptyText.notStarted"
  />
</Tab>
```

**Describe alternatives you've considered**

I am using `useTranslate` hooks with the result store in a variable like so: `const t = useTranslate();`

Then I translate the key manually:

```typescript
  <DateField
    source="startedAt"
    showTime
    emptyText={t('resources.rides.emptyText.notStarted')}
  />

```

**Additional context**

N/A

**Comment by septentrion-730n** [comment]
That's a nice idea. We would gladly welcome a PR on this topic! The PR should include the code, unit tests, and the documentation.

**Comment by oguhpereira** [comment]
@fzaninotto @septentrion-730n the adjustment here must be for all fields or just for the date. I can raise this setting!

**Comment by fzaninotto** [comment]
Please do it for all fields.

**Comment by oguhpereira** [comment]
Should this issue be closed now?
cc @fzaninotto @septentrion-730n

**Comment by fzaninotto** [comment]
Indeed, thanks!
