### ISSUE TITLE
disable refetch of list during tab change: React-query refetchOnWindowFocus

### ISSUE THREAD

**Issue by martin-fv** [marmelab/react-admin#8046]
When I switch between tabs the content will reload, however this often leads to results having a different order.
I know this can be fixed by the following code, but I was thinking this might make sense to add the defaults, or at least have an easier way to configure it.

```
import { QueryClient } from 'react-query';
const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            refetchOnWindowFocus: false,
        },
    },
});
```

**Comment by septentrion-730n** [comment]
Hi,

Thanks for your feedback. 
Changing the default  would introduce a breaking change in the behaviour...
As for configuration, IMHO, the tweak is trivial but I will discuss this matter with the team and welcome any feedback about it.

**Comment by fzaninotto** [comment]
I agree that we shouldn't change the default, that the configuration is easy enough (and [documented](https://marmelab.com/react-admin/Admin.html#queryclient)), so I'm also -1 for this.

**Comment by martin-fv** [comment]
Ok fine. Thanks for the reply!
