### ISSUE TITLE
Validation error notification doesn't show for Edit page

### ISSUE THREAD

**Issue by sudhanshuVice** [marmelab/react-admin#8049]
**What you were expecting:**
Error notification to be rendered on Edit page just like it did on Create page.

**What happened instead:**
When a user tries to submit the form on Edit page without filling all the required fields, validation errors are shown below the fields but no notification is shown. 
Loom: https://www.loom.com/share/acb982880674400caaa2f16038bbe184
can be properly seen in the loom.

**Steps to reproduce:**
You can reproduce the error by following the steps shown in the loom in demo example: https://iuxnw.sse.codesandbox.io/#/posts/13

**Related code:**

* Preferably, a CodeSandbox forked from 
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Good catch! I'm marking this as a bug, thanks for the report.

**Comment by fzaninotto** [comment]
The problem lies in the `useIsFormInvalid` hook, called by the `useAugmentedForm` hook.
