### ISSUE TITLE
MUI New version theme conflict - Types of property 'MuiAlert' are incompatible.

### ISSUE THREAD

**Issue by martin-fv** [marmelab/react-admin#8050]
After upgrading to @mui/material version 5.9.3.
I'm getting a type-error on my custom theme. Apparently the sx property of MuiAlert is incompatible.

Would it be possible to upgrade react-admin to the latest MUI version?

![Screenshot from 2022-08-09 10-18-42](https://user-images.githubusercontent.com/105156564/183549603-b60c38e8-b46a-4ce3-b2f8-aae4a7ebaaab.png)

**Comment by fzaninotto** [comment]
I think that means that MUI has published a breaking change in a bugfix version, which is a breach of the semver convention... You should report the problem to them.

**Comment by martin-fv** [comment]
Ok, not a high priority now. Fixed by downgrading to `"@mui/material": "5.8.4",`
