### ISSUE TITLE
Integrating the Admin to other UI

### ISSUE THREAD

**Issue by Harshil-Jani** [marmelab/react-admin#8053]
Is there an easier way to just integrate the Main Content of the React Admin to some other UI which in my case would be Chakra-UI. We already have the routes to entities. But, Getting access on the Chakra UI Sidebar for the `<Resource>` Component is not much clear to me. 

![image](https://user-images.githubusercontent.com/79367883/183634497-813822d3-ba6c-44a1-9daa-07fdab9ab59c.png)

As can be seen here in the ScreenShot I want the main content to be added into Admin Route. Is there a direct way of doing it or it demands tweaking the React-Admin codebase a lot ?

**Comment by fzaninotto** [comment]
Hi and thanks for reaching out. 

We haven't built react-admin for that use case, and therefore we don't know how to do what you ask. If you want to achieve that, tweak/fork the react-admin codebase, or use another tool, but you're on your own! 

It's not in our objectives to support this use case either, so I'll close the issue.
