### ISSUE TITLE
type-aware fields

### ISSUE THREAD

**Issue by hiaselhans** [marmelab/react-admin#8064]
**Is your feature request related to a problem? Please describe.**

Creating List/Edit/Update Views is a clean and simple task.
However, i am missing type-safe fields. So that when the schemas/interfaces - defined in an openapi-generator - change, the typescript compiler will throw an error

**Describe the solution you'd like**

React-hook-form has a nice and simple interface.
Either using register:

``` typescript
import React from "react";
import ReactDOM from "react-dom";
import { useForm, SubmitHandler } from "react-hook-form";

enum GenderEnum {
  female = "female",
  male = "male",
  other = "other"
}

interface IFormInput {
  firstName: String;
  gender: GenderEnum;
}

export default function App() {
  const { register, handleSubmit } = useForm<IFormInput>();
  const onSubmit: SubmitHandler<IFormInput> = data => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>First Name</label>
      <input {...register("firstName")} />
      <label>Gender Selection</label>
      <select {...register("gender")} >
        <option value="female">female</option>
        <option value="male">male</option>
        <option value="other">other</option>
      </select>
      <input type="submit" />
    </form>
  );
}
```

https://react-hook-form.com/get-started#Registerfields

or controllers:
https://react-hook-form.com/get-started#IntegratingControlledInputs

Whenever the key is not existent in the generic argument (the "model"), or the data-types don't match, the compiler / Ide will warn me about it.

The drawback is that some kind of a context prop would be required, similar to  `control={control}` or `register(...)`

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

This is not something we want to explore, as the path we've taken for forms (a form element accepts children of various types, taking a source prop) is very dynamic and doesn't allow compile-time type checking.

If you want a form with a schema, check out [`<JsonSchemaForm>`](https://marmelab.com/react-admin/JsonSchemaForm.html), a component alternative to `<SimpleForm>` that uses a static definition of form fields as input. 

If that's not enough, you'll have to build your own Form component with react-hook-form. If then you have something generic and with a great developer experience, feel free to open a PR to have it added to react-admin!

**Comment by hiaselhans** [comment]
Hi @fzaninotto .

I am quite surprised this conversation is just over like that.
So - obviously - I am not going to clean this up or make a ready PR, because i don't expect it to be merged given your response.

But If you investe just a few minutes to look at how that is solved in react-hooks-form, you will see that it's basically just generics and type parameters.
No need to strip down on flexibility.

Here is my minimal approach to get type-safety on fields:

``` typescript
class Model<M> {
    constructor() {};

    register<Key extends keyof M>(source: Key) {
        return {
            source: source
        }
    }
};

const MyComponent = (props) => {
  const m = new Model<MyModel>();
  
  return <Show>
     <IntegerField {...m.register("id")}/>
  </Show>
}
```

![image](https://user-images.githubusercontent.com/5046381/184309740-66f88195-b506-42b6-95e6-4886294b5792.png)

I think the benefits are obvious:
 - Type-safe fields
 - IDE autocomplete

with the drawback of one extra line.
The register function could be an attribute of useShowContext<Model>() for example.
