### ISSUE TITLE
ArrayInput does not allow child with empty source.

### ISSUE THREAD

**Issue by martdavidson** [marmelab/react-admin#8069]
Looks like https://github.com/marmelab/react-admin/issues/3249 is back in v4.2.7:

```
<ArrayInput
  label={'Label'}
  source={'source}
>
  <SimpleFormIterator>
    <TextInput
      source={''}
      label={'subLabel'}
    />
  </SimpleFormIterator>
</ArrayInput>
```

Results in `[object Object]` being displayed in the text field. The form _does_ submit an array of strings correctly though for the ArrayInput field, but the user has to first clear the `[object Object]` text from the field.

It also happens with:

```
    {/*@ts-ignore*/}
    <TextInput
      label={'subLabel'}
    />
```

The `source` props is required by typescript, but leaving it out entirely results in the same behaviour.

**Comment by septentrion-730n** [comment]
Hi thanks for reporting. I am investigating and will come back to you when possible.
