### ISSUE TITLE
validateResponseFormat triggers error when calling a dataProvider custom method

### ISSUE THREAD

**Issue by jvert** [marmelab/react-admin#8083]
If you implement a data provider with a custom method, then call that method as documented [here](https://marmelab.com/react-admin/Actions.html#calling-custom-methods) then `validateResponseFormat()` throws an error if the returned object doesn't contain a 'data' key

`The response to 'action' must be like { data: ... }, but the received response does not have a 'data' key. The dataProvider is probably wrong for 'action'.`

I think if it's a custom method, there should not be any validation of the returned object (how could react-admin know?) 

Otherwise, maybe the type of `DataProvider` should be typed better than `[key: string]: any`

**Comment by septentrion-730n** [comment]
Thanks for your pertinent report.

IMHO, `validateResponseFormat()` should be perfectly un-opinionated about custom methods and we should harmonize the documentation and types accordingly. 

Feedback would be very gladly welcome!

**Comment by fzaninotto** [comment]
I agree, `validateResponseFormat` should only be called on the dataProvider methods documented there:

https://marmelab.com/react-admin/DataProviderWriting.html#request-format

I'm marking this as an enhancement. Feel free to open a PR to implement it.

**Comment by oguhpereira** [comment]
I can try to help with this update
