### ISSUE TITLE
3.19 Docs are leading to all dead links

### ISSUE THREAD

**Issue by the133448** [marmelab/react-admin#8086]
I have a major project still on V3 of react-admin, unfortunately we do not have capacity to go in and upgrade to v4 at the moment.

Trying to use the latest v3 docs (3.19) is showing broken links for almost every page
https://marmelab.com/react-admin/doc/3.19/TextInput.html
https://marmelab.com/react-admin/doc/3.19/ReferenceArrayField.html
https://marmelab.com/react-admin/doc/3.19/TranslationTranslating.html

Is this intentional, or an issue? I am not sure.

**Comment by fzaninotto** [comment]
The structure of the docs have changed between 3.x and 4.x. In 3.x, the doc had less pages, each page documenting several components. So for instance the TextInput is documented under https://marmelab.com/react-admin/doc/3.19/Inputs.html#textinput.

If you want to browse the docs for 3.x, go to the first chapter of the documentation (https://marmelab.com/react-admin/Tutorial.html), then in the left side bar, switch to version 3.19. Then, use the links on the sidebar to browse the 3.19 documentation. You can also bookmark the starting point for 3.19 to find it more easily later:

https://marmelab.com/react-admin/doc/3.19/Tutorial.html

The search feature only searches in the latest version. This was previously discussed in https://github.com/marmelab/react-admin/issues/7663 ; we're looking for a way to let users search in the scope a specific version, but that's low priority as there are workarounds.
