### ISSUE TITLE
Edit component title not working as expected when aside property is present

### ISSUE THREAD

**Issue by jbek7** [marmelab/react-admin#8092]
**What you were expecting:**

`<Edit title={<PostTitle />} aside={<CustomAside />}>...</Edit>` should only show title from `<PostTitle>` as described in here: [Edit#title](https://marmelab.com/react-admin/Edit.html#title)

**What happened instead:**
Instead it's generating a title from the `Resources` that are used in my custom aside component. 
![image](https://user-images.githubusercontent.com/2989603/185987091-baaa73b4-56ff-4159-84af-73f9c4b1d45d.png)

**Steps to reproduce:**
Create an Edit view with an aside property and the aside component should use `<SimpleShowLayout>` and it should use some other resources in it.

```
insert short code snippets here
```

**Other information:**

**Environment**
Mac OSX

* React-admin version: 3.19.11
* Last version that did not exhibit the issue (if applicable): the same issue
* React version:  18.0.8
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by jbek7** [comment]
As a workaround I had to label my resources as an empty string - that works only for the ones that don't have a list option.

**Comment by fzaninotto** [comment]
The title prop is working correctly in tests and existing apps. Please include a reproduction based on the simple example codesandbox to show the bug you describe.

**Comment by fzaninotto** [comment]
No news for some time, closing.
