### ISSUE TITLE
[DOCS] Using react-admin without Admin component

### ISSUE THREAD

**Issue by Abdullah0991** [marmelab/react-admin#8093]
Hi, I was searching how to use react-admin in another app, i.e without using the default layout, and precisely how to remove the AppBar. Sadly, I didn't find the how-to in the updated documentation, but google showed me a result that looks like an outdated page in the docs:
https://marmelab.com/react-admin/CustomApp.html

The link above exists in the docs but is not listed under any category and I can't find it be the search!

**Comment by fzaninotto** [comment]
This page has been split in 4.0:

- https://marmelab.com/react-admin/Routing.html
- https://marmelab.com/react-admin/Layout.html
- https://marmelab.com/react-admin/Theming.html#replacing-the-appbar
