### ISSUE TITLE
What kind of response data react-admin expects from ra-data-simple-rest?

### ISSUE THREAD

**Issue by hs-dev-web** [marmelab/react-admin#8098]
you already show kind of data react-admin expect from getList() but what about the other methods (create, update, delete)? is it an array of objects too just like getList()?

**Comment by djhi** [comment]
Please follow the issue template

**Comment by WiXSL** [comment]
You can find the information in the docs: https://marmelab.com/react-admin/DataProviderWriting.html#response-format

**Comment by fzaninotto** [comment]
An here: https://github.com/marmelab/react-admin/tree/master/packages/ra-data-simple-rest#example-calls
