### ISSUE TITLE
Is react-admin production ready?

### ISSUE THREAD

**Issue by olebedev** [marmelab/react-admin#81]
Actually, I want to use this in my React project. It is pretty useful embed it to the main application. But last changes were 3 months ago. How it's compare to ng-admin which develop on regular basis? Is it up to date?

Thanks for this awesome projects guys!

**Comment by fzaninotto** [comment]
Nope, we don't have any production site using it yet, and it needs some love. Would you like to give us a hand?

**Comment by olebedev** [comment]
I can help with certain things. What status of the project right now? What roadmap is?

**Comment by fzaninotto** [comment]
I'd say it's covering about 70% of the ng-admin features. The objective is clear: feature parity.

Unfortunately, marmelab won't be able to spend time on it for at least another couple months. However, if you're willing to give us a hand, we can share our Trello board with you and discuss the priorities.

**Comment by olebedev** [comment]
It seems good to me. Let's discuss it via email, my email address is oolebedev@gmail.com

**Comment by auvipy** [comment]
I want to use it as REST frontend for my django rest api developement server, possible? Will be happy to help add more features and fixing bug for it and it not atleast I can report bug :D

**Comment by maciekpaprocki** [comment]
I can also help if I will be provided with explanation what is needed. I don't have experience with ng-admin but I am more then happy to learn what needed.

**Comment by fzaninotto** [comment]
@auvipy @maciekpaprocki Dig in the code first, and if you feel ready to give a hand, send me your emails so that I can add you to our Trello board.

**Comment by mikedizon** [comment]
hey how are things coming along with this. i noticed there haven't been any major commits in 9 months. are there plans for further development?

**Comment by fzaninotto** [comment]
Not in the short term. It's a major investment that we don't want to do now.

**Comment by mikedizon** [comment]
@fzaninotto could you add me to the trello?

**Comment by fzaninotto** [comment]
@mikedizon done

**Comment by fzaninotto** [comment]
This project is discontinued. We've published a complete rewrite and committed to support it. Check out [marmelab/admin-on-rest](https://github.com/marmelab/admin-on-rest).
