### ISSUE TITLE
specific user data details

### ISSUE THREAD

**Issue by ENGR-MANSOOR** [marmelab/react-admin#8100]
let's say there is an organization where specifically assigned admins but multiple normal users, admin have full control over all possible actions, like edit delete show, and so on. 

Users only once log in directly redirect to their own data(such as their working hour details, and personal details) instead of getting a list of employees at first and then to its data which does not make sense. user details can be get from any like login name or email which we provide usually on the login step.

I do not feel there is any such feature that can help to accomplish this task.

**Comment by djhi** [comment]
Please follow the issue template

**Comment by WiXSL** [comment]
No news for some time, plus it really looks like a how to question. closing
