### ISSUE TITLE
Label prop added to filter button

### ISSUE THREAD

**Issue by rochelle-norman** [marmelab/react-admin#8119]
**Is your feature request related to a problem? Please describe.**
I had to create a custom filter button just to change the label of the filter button from `ADD FILTER` to `FILTER` as there is no label prop for this button.

```
const CustomFilterButton = () => {
  const { showFilter } = useListContext();
  return (
    <Button
      size="small"
      color="primary"
      onClick={() => showFilter("store")}
      startIcon={<ContentFilter />}
    >
      Filter
    </Button>
  );
}
```

**Describe the solution you'd like**
I would like a label prop added to the filter button as the label `ADD FILTER` may not be relevant for all use cases of this button

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by WiXSL** [comment]
If you are referring to the `FilterButton` component used in the List component, its label is the translation key `ra.action.add_filter`.
You can change it for your project by customizing your i18n setup.
You can read more about it here: https://marmelab.com/react-admin/Translation.html
