### ISSUE TITLE
AutocompleteInput issue when the id of a value is 0

### ISSUE THREAD

**Issue by fchasles** [marmelab/react-admin#8129]
**What you were expecting:**

I would like to be able to create an element with an id 0.

**What happened instead:**

I can't create an element with an id 0.
If I choose a choice where the id of the value is 0, the value/id is an empty string and when I choose it again, the other choices disappear.

**Related code:**

https://codesandbox.io/s/autocomplete-id-issue-rhcfzs

**Other information:**

![CPT2209011224-865x348](https://user-images.githubusercontent.com/42614188/187893469-d4639c7a-4929-4b71-a5e0-d555256527e8.gif)

**Environment**

* React-admin version: 4.3.0
* React version: 17.0.1
* Browser: Chrome/Firefox

**Comment by WiXSL** [comment]
Reproduced.
Thanks!
We are going to look into it.
