### ISSUE TITLE
SelectArrayInput choices are sorted in desc order

### ISSUE THREAD

**Issue by alexei-bykovski** [marmelab/react-admin#8134]
After upgrade to 4.3.0 version choices in SelectArrayInput are sorted in desc order.

**Example:**
```
<SelectArrayInput label="Statuses" source="statuses" choices={[
  { id: 'created', name: 'Created' },
  { id: 'sent', name: 'Sent' },
  { id: 'inbox', name: 'Inbox' },
  { id: 'spam', name: 'Spam' },
  { id: 'error', name: 'Error' },
]} alwaysOn/>
```

**Expected choices order:**
As they were passed to SelectArrayInput: Created, Sent, Inbox, Spam, Error

**Actual choices order:**
<img width="199" alt="SelectArrayInput" src="https://user-images.githubusercontent.com/11819387/188128482-a72067d6-a14d-49db-a801-a57b6716acaf.png">

**CodeSandbox:**
https://codesandbox.io/s/stoic-lake-l6ppm3?file=/src/posts/PostList.tsx

**Environment**
* React-admin version: 4.3.0
* Last version that did not exhibit the issue (if applicable): 4.2.7
* React version: 18.2.0

**Comment by fzaninotto** [comment]
Indeed, that's a serious regression. Thanks for the report!
