### ISSUE TITLE
DateTimeInput with type='time' is broken with default settings

### ISSUE THREAD

**Issue by Neffes1987** [marmelab/react-admin#8155]
Issue component: **DateTimeInput**
React-admin package version: **4.3.0**

**What you were expecting:**
When user set only time by DateTimeInput, component should return string in format like HH:MM 

https://user-images.githubusercontent.com/20636819/189308089-46ff4f15-4bf9-4576-a8d9-50a720bdd517.mov

**What happened instead:**
DateTimeInput return invalidDate value because of default parser and formatter, which is not checking type='time' flag

https://user-images.githubusercontent.com/20636819/189308217-81a22325-2d7c-4968-a5ad-1d109e247d79.mov

**Steps to reproduce:**
1. Setup **DateTimeInput** with type="time" 
2. Try to type any value

**Workaround:**
As a temporary solution i added custom **parse** and **format**  properties as a function like (value) => value

``
function formatTime(value: string) {
    return value;
  }

<DateTimeInput {...options} **parse={formatTime}** **format={formatTime}** type="time" />
``

**Environment**

* React-admin version: **4.3.0**
* React version: 18.2.0
* Browser: Chrome

**Comment by slax57** [comment]
4.3.0 introduced a new component to deal with time only: [TimeInput](https://marmelab.com/react-admin/TimeInput.html)
You should probably use this one instead.

**Comment by Neffes1987** [comment]
@slax57 Thanks a lot! Sorry for bothering you =)

**Comment by slax57** [comment]
No problem!
This component was added very recently so I can understand you missed it.
