### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase') in non chrome browsers

### ISSUE THREAD

**Issue by brave-merida** [marmelab/react-admin#8173]
**What you were expecting:**
Dashboard page should be rendered.

**What happened instead:**
Dashboard page is not rendering except for Chrome browser.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at HTMLDocument.eval (eval at <anonymous> (eval at ExRmtSvrCd (eval at <anonymous> (translate.js:211:45))), <anonymous>:1:31073)
```

**Steps to reproduce:**
Try react-admin app in Microsoft Edge or Safari browser

**Environment**

* React-admin version: 4.3.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Edge
* Stack trace (in case of a JS error):
Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at HTMLDocument.eval (eval at <anonymous> (eval at ExRmtSvrCd (eval at <anonymous> (translate.js:211:45))), <anonymous>:1:31073)

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. 

I can open https://marmelab.com/react-admin-demo/ in Safari without problem.

The problem probably lies in your own Dashboard code. 

If you're convinced this is a react-admin issue, please provide a CodeSandbox allowing to reproduced the problem (you can fork https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).
