### ISSUE TITLE
Array input issue when removing and reinserting element

### ISSUE THREAD

**Issue by kriskw1999** [marmelab/react-admin#8178]
# Bug
The bug happens when I have inside a `SimpleFormIterator` a `React.FC` or a `FormDataConsumer`.
In those cases if I have defaults they are not applied and if there is a record the informations shown does not respect the form state.

# To reproduce
To reproduce the bug use this [CODESANDBOX](https://codesandbox.io/s/heuristic-diffie-gzwqfp?file=/src/comments/CommentEdit.tsx)
Enter into the edit of the only comment present here delete this from the form. Then reinsert it. 
The form seems filled because you can see the numbers but if you press submit the validation error appears informing you that the form is not filled.

Result of bug:
![image](https://user-images.githubusercontent.com/71312948/191016246-4a08e915-d73d-469d-b2f6-e6d53e7481b8.png)

# Problem found
The screen below is the `SimpleFormIterator` `addField` function, in this function if I have a form data consumer or any other React.FC that have not source nor the default value on the SimpleFormIterator level the default returned is `{undefined: ""}`
This causes that react admin renders the array value from the record thinking that the form is filling with the record, showing a wrong value from record and not from the form state. 
![image](https://user-images.githubusercontent.com/71312948/191015232-aa7d6c0f-327f-43aa-9505-bbb14447b19e.png)

# Drity workaround to partially solve this issue

```tsx
type Props<T> = SimpleFormIteratorProps & {
  defaultValue?: { [TKey in keyof T]: T[TKey] }
}

/**
 * This component is used because react admin cannot handle default values for React.FC children of
 * the standard SimpleFormIterator. For those elements the native one takes the default from the record but it
 * does not update the record with like result having the field filled but with an empty form.
 *
 * @param SimpleFormIteratorProps all the props of the SimpleFormIterator
 * @param defaultValue this one is used when a new element is added
 * @return the standard SimpleFormIterator with the ability to add a default value to each element of the array
 */
const KSimpleFormIterator = <T extends any>({
  children,
  source,
  defaultValue,
  ...rest
}: Props<T>) => {
  // this source is automatically passed by the array input
  if (!source) throw new Error('KSimpleFormIterator: source is required')

  // we are going to perform a watch on the the array input values
  const arrayValue = useWatch({ name: source }) as Array<any>

  // we memorize the array input values
  const [value, setValue] = useState(arrayValue)

  // this hook is used to manipulate the ReactAdmin array input form state
  const { append, remove } = useArrayInput({ ...rest })

  console.log('aaa', {
    children: Children.toArray(children),
  })

  // if an element was added
  if (value.length < arrayValue.length) {
    // remove the last added element with wrong default value
    remove(arrayValue.length - 1)
    // set the default value with the correct one appending it like last element of the array
    append(defaultValue)
    // updates the cached value inside the component
    setValue(arrayValue)
  } else if (value.length > arrayValue.length) {
    // updates the cached value inside the component
    setValue(arrayValue)
  }

  return (
    <SimpleFormIterator {...rest} source={source}>
      {children}
    </SimpleFormIterator>
  )
}

export default KSimpleFormIterator

```

**Comment by WiXSL** [comment]
Thank you for reporting this.
Your codesandbox doesn't seem to be functional. Can you fix it?

**Comment by lsimone** [comment]
Same happens to me!

@WiXSL codesandbox gives error but if you take its url ( https://gzwqfp.sse.codesandbox.io/#/comments ) you can reproduce it

**Comment by kriskw1999** [comment]
@WiXSL try to enter in the link above that is the one of the deployed version where you can reproduce it.

**Comment by WiXSL** [comment]
Thanks, seems like a bug.
I have to investigate, further.

**Comment by WiXSL** [comment]
@kriskw1999, I couldn't reproduce the same behavior locally.
Could you fix your code sandbox, so I can have your exact project, and see the code?

**Comment by WiXSL** [comment]
I can reproduce it on stackblitz.com and codesandbox but not locally

**Comment by lsimone** [comment]
> UPDATE: I can reproduce it on stackblitz and codesandbox but not locally. I'll keep investigating

@WiXSL I could reproduce it locally through these steps:

1. (codesandbox) File > export to ZIP
2. extract and `(p)npm install`
3. `(p)npm dev`

If I can help to reproduce, please write me!

![image](https://user-images.githubusercontent.com/3266650/191679577-a8a789c9-693b-4e7e-9436-a80ea573103f.png)
