### ISSUE TITLE
Unmounting inputs doesn't reset/clear them.

### ISSUE THREAD

**Issue by whoiskonstantin** [marmelab/react-admin#8179]
**What you were expecting:**

Expect field inputs to be unmounted and the input value to be reset/clear with this code:
```
<FormDataConsumer>
    {({ formData, ...rest }) => formData.hasEmail &&
        <TextInput source="email" {...rest} />
    }
</FormDataConsumer>
```

**What happened instead:**
Form values are persisted and submitted with the form.

**Steps to reproduce:**
You can copy paste the form from the [official documentation](https://marmelab.com/react-admin/Inputs.html#hiding-inputs-based-on-other-inputs) and test it.

React admin v4.3.1

**Comment by KonkretneKosteczki** [comment]
I suggest watching for changes to the field you want and resetting the field manually.

```
    import {useFormContext} from "react-hook-form";
    ...

    const {watch, resetField} = useFormContext();
    const inputValue = watch("hasEmail");

    useEffect(() => {
        if (inputValue) resetField("email");
    }, [inputValue]);
```

**Comment by whoiskonstantin** [comment]
@KonkretneKosteczki Thank you! Worked with `unregister` in my case, but `reset` works too. Closing.

**Comment by WiXSL** [comment]
This behavior is the responsibility of `react-hook-form`.
You can solve it by setting `shouldUnregister` to `true` in your Form.

```jsx
<SimpleForm shouldUnregister>
    <FormDataConsumer>
        {({ formData, ...rest }) => formData.hasEmail &&
            <TextInput source="email" {...rest} />
        }
    </FormDataConsumer>
</SimpleForm>
```
