### ISSUE TITLE
Donate Button

### ISSUE THREAD

**Issue by martin-fv** [marmelab/react-admin#8185]
Please consider adding a Sponsor button on GitHub so we can donate some money for this awesome tool!

**Comment by fzaninotto** [comment]
Thanks for the suggestion!

If you want to give us money and help fund the react-admin development, please consider subscribing to [react-admin Enterprise Edition](https://marmelab.com/ra-enterprise/), developed by the same team. You will also get access to support by the core team, and Enterprise modules for role-based authentication, site-wide search, event, log, etc.
