### ISSUE TITLE
FormTab not turning red after ArrayInput global validation error

### ISSUE THREAD

**Issue by LabisAnargyrou** [marmelab/react-admin#8190]
**What you were expecting:**
Upon returning an errors object from global validation with a key equal to ArrayInput's source the FormTab should turn red.
This is true when the value of the key is an array of (children) errors.

**What happened instead:**
Only the label of ArrayInput turned red.
![image](https://user-images.githubusercontent.com/45109485/191924928-df15bb52-cca0-48f5-a538-d17954791f41.png)

**Related code:**
[codesandbox](https://codesandbox.io/s/formtab-arrayinput-global-validation-bug-6145yz)
Example made with source code from  [global validation docs](https://marmelab.com/react-admin/Validation.html#global-validation).

**Other information:**

https://user-images.githubusercontent.com/45109485/191922782-c001f473-3674-4037-b456-9e1935c31d71.mp4

**Environment**

* React-admin version: 4.3.3
* React version: 18.2.0
* Browser: Brave 1.43.93 Chromium: 105.0.5195.127

**Comment by WiXSL** [comment]
Reproduced!
Thanks for the report

**Comment by viniciusbsneto** [comment]
With #8190 fix we must wrap `ArrayInput` inside `FormGroupsProvider` if we want to use it without `SimpleForm` or `Form`, right? I had to do this for an `ArrayInput` I was using with `FormProvider` from React Hook Form.

**Comment by fzaninotto** [comment]
@viniciusbsneto no, this should not be necessary. If ArrayInput validation doesn't work anymore with SimpleForm, please open an issue with a reproduction.

**Comment by viniciusbsneto** [comment]
> @viniciusbsneto no, this should not be necessary. If ArrayInput validation doesn't work anymore with SimpleForm, please open an issue with a reproduction.

@fzaninotto It does work with either SimpleForm or Form. It actually stopped working with FormProvider only. I mean, outside SimpleForm or Form. And it makes sense since now they're the ones providing the FormGroupsProvider which now ArrayInput is dependent on.
