### ISSUE TITLE
Tab icon spacing inconsistent when importing icon indirectly

### ISSUE THREAD

**Issue by olliebennett** [marmelab/react-admin#8193]
**What you were expecting:**

Setting the `icon` attribute on a `<Tab>` should appear the same whether the icon is provided as a direct import from `@mui/icons-material` as it does when provided as an export from an intermediate component.

This affects the `<FormTab>` component in the same way.

**What happened instead:**

The icon provided directly from `@mui/icons-material` appears with correct whitespace but the indirectly passed icon appears with less space.

The rendering differs because the SVG in the correctly styled tab ("Summary" tab) icon has the class `MuiTab-iconWrapper` but the incorrect ("Body" tab) icon does not have this class.

**Steps to reproduce:**

Configure two tabs with icons where one is a direct mui tab import and the other is indirectly imported.

View the tabs and notice that they are spaced differently.

**Related code:**

https://codesandbox.io/s/busy-matan-rm3di2?file=/src/posts/PostShow.tsx:453-487

Correctly styled tab:

```ts
// PostShow.tsx

import InfoIcon from "@mui/icons-material/Info"; // direct import

<Tab label="post.form.summary" icon={<InfoIcon />}> // "Summary" tab
```

Incorrectly styled tab:

```ts
// PostTab.tsx
import * as React from "react";

import InfoIcon from "@mui/icons-material/Info";

export default () => {
  return <InfoIcon />;
};
```

```ts
// PostShow.tsx
import PostIcon from "./PostIcon"; // indirect import

<Tab label="post.form.body" icon={<PostIcon />}> // "Body" tab
```

**Other information:**

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1068525/192151899-ccad643d-b107-48ce-8d87-c5c93a0761f4.png">

^ notice the spacing difference between the "Summary" and "Body" tab icons.

**Environment**

* React-admin version: `"react-admin": "^4.3.4",`
* Last version that did not exhibit the issue (if applicable):
* React version: `"react": "^17.0.0"` - latest via CodeSandbox
* Browser: Firefox v104 AND Chrome v105
* Stack trace (in case of a JS error): N/A

**Comment by arimet** [comment]
Thanks for reporting this !
I can reproduce it. However, this behavior comes directly from MUI as you can see here: https://codesandbox.io/s/modest-glade-csz457?file=/demo.tsx
. I suggest you to open an issue on their side, and see their response.
