### ISSUE TITLE
A completed demo

### ISSUE THREAD

**Issue by haison8x** [marmelab/react-admin#8195]
Hello Sir!

I copied your demo and added the backend api (asp.net core and mysql) to create a completed demo: https://github.com/haison8x/reactadminnet

Did my demo violate your license? Is it possible for me to get a reference link from your demo site?

Thanks,
Jacob

**Comment by fzaninotto** [comment]
Hi Jacob,

Nice work! Your repository is using the MIT licence, but you're not attributing the `frontend` part, so it's technically a licence breach. 

I see you're using ra-data-simple-rest, so there isn't much here to learn for react-admin users. But don't hesitate to share it with the .Net community!
