### ISSUE TITLE
Persist the `Store` even after user logging out 

### ISSUE THREAD

**Issue by yousseftarekkh** [marmelab/react-admin#8197]
**Is your feature request related to a problem? Please describe.**
I faced a problem related to the Saved Queries feature, as all the saved queries get cleared once the user is logged out and unfortunately, we're pushing many updates to our admin panel and thus triggering session to expire and log out users when an update is deployed.

**Describe the solution you'd like**
It would be very convenient to have this "clearing the store" conditional, or maybe a persistence setting can be configured further to persist some of the keys.

**Describe alternatives you've considered**
I would introduce a `mode` for the store module, and offer different persistence settings such as `browser`, `user` and `session` to offer full flexibility to the user.

**Comment by fzaninotto** [comment]
Clearing the localStorage on logout is a security requirement, and we won't remove this feature.

If you want to have preferences persist between logins, you should save them sent to the server on update, and you should initialize the store with values from the server on login. This can be achieved by creating a custom [store](https://marmelab.com/react-admin/Admin.html#store).
