### ISSUE TITLE
Broken link in documentation https://marmelab.com/react-admin/Authorization.html returns 404

### ISSUE THREAD

**Issue by neps-in** [marmelab/react-admin#8207]
Broken link in documentation https://marmelab.com/react-admin/Authorization.html returns 404

Appreciate a fix.

**Comment by WiXSL** [comment]
We don't have an `Autorization.html` in the docs
Where did you find that URL?
And what was that you were looking for?

**Comment by neps-in** [comment]
In this question https://stackoverflow.com/questions/73858812/show-or-hide-resource-based-on-permission-in-react-admin-not-working?noredirect=1#comment130435997_73858812

I referred to other questions, you can find it as the second link in my question.  

This question has that link
https://stackoverflow.com/questions/66132803/react-admin-permissions-with-resource as a part of the answer.

Also if you have put the authorization.html page, these SO questions would not have come at all.

**Comment by WiXSL** [comment]
Ok.
This is what you are looking for: https://marmelab.com/react-admin/Permissions.html
I'll update the link in StackOverflow
