### ISSUE TITLE
Admin resources with permissions only work if there is a single child

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#8210]
**What you were expecting:**

The [permissions doc](https://marmelab.com/react-admin/Permissions.html#restricting-access-to-resources-or-views) says that to have Resources based on permissions, one has to pass a function as the admin child:

```jsx
<Admin
    dataProvider={dataProvider}
    authProvider={authProvider}
>
    {permissions => (
        <>
            {/* Restrict access to the edit view to admin only */}
            <Resource
                name="customers"
                list={VisitorList}
                edit={permissions === 'admin' ? VisitorEdit : null}
                icon={VisitorIcon}
            />
            {/* Only include the categories resource for admin users */}
            {permissions === 'admin'
                ? <Resource name="categories" list={CategoryList} edit={CategoryEdit} icon={CategoryIcon} />
                : null}
        </>
    )}
</Admin>
```

**What happened instead:**

This only works if `<Admin>` only has one child. The following doesn't work:

```jsx
<Admin
    dataProvider={dataProvider}
    authProvider={authProvider}
>
    <Resource name="posts" list={PostList} />
    {permissions => (
        <>
            {/* Restrict access to the edit view to admin only */}
            <Resource
                name="customers"
                list={VisitorList}
                edit={permissions === 'admin' ? VisitorEdit : null}
                icon={VisitorIcon}
            />
            {/* Only include the categories resource for admin users */}
            {permissions === 'admin'
                ? <Resource name="categories" list={CategoryList} edit={CategoryEdit} icon={CategoryIcon} />
                : null}
        </>
    )}
</Admin>
```

**Possible fixes:**

- throw an error when Admin has a function child and other children, or
- support multiple children with permissions

**Environment**

* React-admin version: 4.3
* Last version that did not exhibit the issue (if applicable): -
* React version: 17
* Browser: All

**Comment by newfylox** [comment]
I've updated from 4.2.4 to 4.2.8 and I just had this issue today. Hope it can helps

**Comment by newfylox** [comment]
I refactor my code to only use `<Admin>` instead of splitting it into `<AdminUI>` and permissions update correctly after sign in. Not sure if my previous example was wrong or not, so we probably should ignore it.

**Comment by djhi** [comment]
I don't get this error. Our simple example actually does that.
See https://github.com/marmelab/react-admin/blob/master/examples/simple/src/index.tsx#L36
 
You can only have one function child, but you can have a function child and `Resource` or `CustomRoute` components at the same level

**Comment by fzaninotto** [comment]
You're right, this old issue must have been fixed a while ago.
