### ISSUE TITLE
Allow CreateButton's label be changed with Empty component

### ISSUE THREAD

**Issue by stesie** [marmelab/react-admin#8213]
**Is your feature request related to a problem? Please describe.**

Given a `<List>` on a resource with a create route, rendering empty, I'd want to customize empty text, invite text + create button's label. Both the empty and invite text can be influenced with `resource.xxx.empty` and `resource.xxx.invite` translations.

However the `<CreateButton />` in `Empty` is hard-coded to not set the `label` prop, hence I cannot change the label (without implementing my own Empty component).

**Describe the solution you'd like**

Have a translation like `resources.xxx.create` that's used by `CreateButton` unless `label` prop is explicitly specified (falling back to `ra.action.create`).

This would also change the Label of the button as part of default `<ListActions/>` (as rendered if the list wouldn't be empty).

**Describe alternatives you've considered**

Add a `createButtonProps` prop to `EmptyProps` and pass all those to `<CreateButton variant="contained" {...createButtonProps />`

**Additional context**

**Comment by WiXSL** [comment]
Thanks for your feedback!
You are right, we should do something about it

**Comment by fzaninotto** [comment]
I don't think we should do something about it, as it's already possible ;)

You can already pass a custom component as the `empty` prop. Component injection is the way react-admin provides full capacity to customize the app. We won't move customization "up" the component tree by adding props, as it dilutes the responsibility of each component.

https://marmelab.com/react-admin/Architecture.html#component-composition

If you find yourself doing it over and over, create your own List variant with a custom Empty component.
