### ISSUE TITLE
Provide store context in the dataprovider

### ISSUE THREAD

**Issue by btoro** [marmelab/react-admin#8220]
**Is your feature request related to a problem? Please describe.**
Currently, the dataprovider does not have access to the react admin store. This prevents making use of a user-set variable in the react admin store when making API calls.

A great example is the language switcher, which stores data in the store. It would be practical to be able to send the user's language with each API call, without having to do it per API call using mutationOptions.

**Describe the solution you'd like**
1. Move the StoreContextProvider above the DataProviderContext in CoreAdminContext:

https://github.com/marmelab/react-admin/blob/dbd036f8122c1376b65bbc7e5cf6497641bde4de/packages/ra-core/src/core/CoreAdminContext.tsx#L82-L83

2. Provide access to the store as an optional argument to dataprovider functions.

**Additional context**
[I brought up the issue here first
](https://stackoverflow.com/questions/73833840/how-can-i-access-the-react-admin-store-in-the-dataprovider-react-admin-4-x/73839240?noredirect=1#comment130436134_73839240)

**Comment by WiXSL** [comment]
Thanks for the feedback.
I'm setting this as an enhancement request

**Comment by WiXSL** [comment]
Actually, as pointed out here https://github.com/marmelab/react-admin/issues/8226#issuecomment-1265365988
You have a solution for your use case.
So no need for a change in react-admin
