### ISSUE TITLE
RichTextInput not getting data from SaveContextProvider

### ISSUE THREAD

**Issue by RayMiles94** [marmelab/react-admin#8249]
**What you were expecting:**
RichTextInput not getting data from SaveContextProvider

**What happened instead:**
TextInput get data from  SaveContextProvider with no problem but RichTextInput show nothing to edit and the data is exist.

**Steps to reproduce:**
use RichTextInput inside SaveContextProvider

```
import { RichTextInput } from "ra-input-rich-text";
import React, { useEffect, useState } from "react";
import {
  useDataProvider,
  useNotify,
  SaveContextProvider,
  Toolbar,
  SaveButton,
  TabbedForm,
  FormTab,
  TextField,
  TextInput,
  RichTextField,
} from "react-admin";

export const Conditions = ({ staticContext, ...props }: any) => {
  const dataProvider = useDataProvider();

  const notify = useNotify();

  const [saving, setSaving] = useState();

  useEffect(() => {
    dataProvider.getConditions("condition").then(({ data }: any) => {
      setSaving(data);
    });
  }, []);

  const save = (data: any) => {
    dataProvider.saveConditions(data);
    notify("lucky.save");
  };

  const UserEditToolbar = (props: any) => (
    <Toolbar {...props}>
      <SaveButton />
    </Toolbar>
  );

  return (
    <SaveContextProvider value={{ save }}>
      <TabbedForm record={saving} toolbar={<UserEditToolbar />} >
        <FormTab label="Condition général de vente ">
          <RichTextInput source="cgv" label={false}  />
        </FormTab>
        <FormTab label="Responsable">
          <TextInput source="cgu" label={false}  />
        </FormTab>
        <FormTab label="Cookie">
          <TextInput source="cookie" label={false}  />
        </FormTab>
        <FormTab label="Condition général d’utilisation">
          <TextInput source="il" label={false} />
        </FormTab>
      </TabbedForm>
    </SaveContextProvider>
  );
};

```

**Environment**

* React-admin version:^4.0.0
* Last version that did not exhibit the issue (if applicable):
* React version:"^17.0.0
* Browser: Latest Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I don't know what you're trying to do. You don't need a SaveContext to use a TabbedForm - just pass an onSubmit prop. Besides, your title doesn't make sense: RichTextContent doesn't have any interaction wit the SaveContextProvider - the data is passed through the TabbedForm. 

Anyway, you're using undocumented features to do things that are not supported, so we won't dig further on this issue.
