### ISSUE TITLE
RichTextInput does not update when record field updates

### ISSUE THREAD

**Issue by lsimone** [marmelab/react-admin#8252]
We are migrating the old quill `richTextInput` to have a more "standard" react-admin component but it does not behave as for other RA components.

**What you were expecting:**

When its record field updates, it should change the shown input box content

**What happened instead:**

Nothing happens (`TextInput` updates instead => see codesandbox example)

**Steps to reproduce:**

- Bind a RichTextInput to a field in a form
- Update record's value (I used a `TextInput` to do it but it can be done in any way)

**Related code:**

In [codesandbox PostEdit](https://codesandbox.io/s/dreamy-banzai-x609ts?file=/src/posts/PostEdit.tsx) module I just added 2 new `TextInput` with the same source and I triggered a record update by changing the value of the first one:

#### expected

I would expect to see the value of the second `TextInput` and of the `RichTextInput` updated

#### actual

Just the second `TextInput` updates

```
          {/* this RichTextInput does not update when 'body' record value updates! */}
          <RichTextInput
            source="body"
            label=""
            validate={required()}
            fullWidth
          />
          {/* INSTEAD, this TextInput DOES update when 'body' record value updates! */}
          <TextInput source="body" label="body 1" fullWidth />
          <TextInput source="body" label="body 2" fullWidth />

```

**Other information:**

**Environment**

* React-admin version: ^4.4.1
* React version: ^17.0.0
* Browser: Chrome

**Comment by slax57** [comment]
Reproduced, thanks!
