### ISSUE TITLE
tree shaking

### ISSUE THREAD

**Issue by priyang12** [marmelab/react-admin#8254]
**What you were expecting:**
I have a CRA app and when I import one module from react-admin it looks like importing all things.

**What happened instead:**
 this size of the import remains almost the same regardless of imports. it's should remove not used module.

**Steps to reproduce:**

**Related code:**

<img width="652" alt="Screenshot 2022-10-11 at 6 11 39 PM" src="https://user-images.githubusercontent.com/72823974/195093443-a4df1c41-4630-4200-93b4-cc6fe687b550.png">

<img width="652" alt="Screenshot 2022-10-11 at 6 11 00 PM" src="https://user-images.githubusercontent.com/72823974/195093274-3f9b46e1-3861-4a7a-99bd-92005521654e.png">

**Other information:**

**Environment**

* React-admin version: 4.3.4
* Last version that did not exhibit the issue (if applicable): 
* React version: 18.2.0

**Comment by fzaninotto** [comment]
I cannot reproduce the problem with webpack. Do you only notice the problem through your VSCode extension? If not, can you please provide a reproduction?

**Comment by priyang12** [comment]
it's hard to create a reproduction since the issue is with the build. i don't how to share it but i have tried with vite setup and the same thing happened.

<img width="652" alt="Screenshot 2022-10-12 at 1 37 11 AM" src="https://user-images.githubusercontent.com/72823974/195188244-304b465a-7bcf-4d2b-b06a-4ae753ba7ed8.png">

code for the above build

```js
import { Admin } from "react-admin";
import jsonServerProvider from "ra-data-json-server";

const dataProvider = jsonServerProvider("https://jsonplaceholder.typicode.com");

const App = () => <Admin dataProvider={dataProvider} />;

export default App;
```

is it normal that the size is that big or something is wrong? 
the [repo](https://github.com/priyang12/react-admin)

**Comment by fzaninotto** [comment]
A reproduction for that bug would be 2 repos: one with minimal use of react-admin, and the other using more components. If the two bundles have the same size, there is a problem with tree shaking. 

In my experience, with CRA and webpack, I didn't see any issue.

**Comment by priyang12** [comment]
@fzaninotto thanks for the suggestion I add more components and the bundle size is increasing so tree shaking seems to be working but the bundle size the too big is there any way to reduce it???

**Comment by fzaninotto** [comment]
No. We're targeting long-lived B2B apps, for which 200kB of JS is acceptable. If this is too much for you, you'll have to choose other frameworks to build your app.
