### ISSUE TITLE
Disable Authentication for new `CustomRoute` component.

### ISSUE THREAD

**Issue by farshadmb** [marmelab/react-admin#8255]
**Is your feature request related to a problem? Please describe.**

There is an authentication problem when trying to define some unauthorized pages like reset password or forgot password with `<CustomRoutes> routes children </CustomRoutes>`.  The react-admin must provide a clean way to disable authentication for custom paths like mine. 

Version 4 dropped the custom routes props in the flavor of custom routes.

I try to use `useAuthenticated({ bypass: true, })` at my reset password component to bypass it. 
However, this method didn't even work out. 

I've also noticed this ability has existed on version 3. I think the feature was missed in refactoring. 
Please check the issue again. 
#6342

react-version: `latest` 
react-admin: `4.3.4` 
react-router: `6.1.0`

**Describe the solution you'd like**
It would be nice if we have a feature like it was provided in the `<List>` component props. 
I read the full [doc](https://marmelab.com/react-admin/Authentication.html). I noticed a clean way to bypass authorization by using `disableAuthorization` props.  

I think if we defined `disableAuthorization` in `CustomRoutes` to bypass authorization. it would pay off.

**Describe alternatives you've considered**
Also, we could provide another way by using `useAuthenticated({ enabled: false })`. I read the code and found there is a way to use it if you make it public to developers. 
https://github.com/marmelab/react-admin/blob/af81ccf0ecd3475f1ec69ff2b1fe14c5aa84d15c/packages/ra-core/src/controller/list/useListController.ts#L47

**Additional context**
```TypeScript
 <BrowserRouter basename={basename}>
      <Admin
        title={name}
        requireAuth
        loginPage={LoginPage}
        authProvider={appAuthenticationProvider}
        theme={appTheme}>
        <CustomRoutes noLayout disableAuthorization>
            <Route path="/forgotPassword" element={<>ForgotPassword</>} />
            <Route path="/resetPassword" element={<>ResetPassword</>} />
        </CustomRoutes>
```

**Comment by slax57** [comment]
Hi,

Having a CustomRoute with no authentication required is already supported.

We have a working example in the _simple demo_.
Have a look at this stackblitz: https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=src%2Findex.tsx
You can logout, and then browse to `/#/custom1`.
You will see that you are able to see the custom route content, even when logged out.

Hope this helped.

**Comment by farshadmb** [comment]
@slax57 Thanks for the hint but I think the mentioned approach would be error prunes. when you have to ensure every customized component follows authorization as well as anonymous pages or components. for instance, I want to create a custom informative page with material UI or something like this. 

There is two way to authorize the user: 
  1. The way you suggested to me which need to make sure each customized component uses `useAuthentication` hook or uses `Authorized` react component. which leads to errors that developers must care about it when the project grows. 
  2. The other way is to use `requireAuth` flag for the whole module or application. in fact, you have no control over custom routes that do not require authorization such as reset password, forgot password, etc. 
  
Would please check the project out to see the issue.
https://stackblitz.com/edit/ra-auth-issue?file=README.md,src%2Findex.tsx,src%2FApp2.tsx

It is good we have an option that makes the whole project requires auth however, for some special cases, we also need to bypass where the user access anonymous paths.

**Comment by farshadmb** [comment]
I just added the code below and every things went right.
```JavaScript
const Layout: FC<AppLayoutProps> = (props) => {
  useAuthenticated()
  return <RaLayout {...props} appBar={AppBar} menu={Menu} />
}
``` 
Thanks so much.
