### ISSUE TITLE
ArrayInput issues with nested properties

### ISSUE THREAD

**Issue by marhali** [marmelab/react-admin#8256]
**What you were expecting:**

I want to use the <kbd>ArrayInput</kbd> with a nested property structure like this:
```json
{
    "numbers": [
        {
            "nested": {
                "number": "10"
            }
        }
    ]
}

```

**What happened instead:**

The data gets displayed properly but if I remove an item from the array and want to add a new item, the old data gets displayed.
This does not happen if I do not use a nested property for the <kbd>source</kbd> parameter.
Another problem is the save button which will not display the correct state (enabled, disabled) on nested properties.

**Steps to reproduce:**

**Related code:**

See this example with a nested property structure:
https://stackblitz.com/edit/github-rmhseu?file=src/data.tsx

```tsx
<Edit>
    <SimpleForm>
      <ArrayInput source="numbers" defaultValue={[{ nested: { number: 1 } }]}>
        <SimpleFormIterator>
          <NumberInput source="nested.number" defaultValue={1} />
        </SimpleFormIterator>
      </ArrayInput>
    </SimpleForm>
  </Edit>
```

**Other information:**

**Environment**

* React-admin version: 4.4.1
* React version: 17
* Browser: chrome

**Comment by slax57** [comment]
Reproduced, thanks!

Might be the implementation of https://github.com/marmelab/react-admin/pull/8204 that only clears objects at depth=1
