### ISSUE TITLE
Null default value becomes blank string

### ISSUE THREAD

**Issue by damir-manapov** [marmelab/react-admin#8264]
**What you were expecting:**
I am expecting to get null value from form state when null default value is set.

**What happened instead:**
Blank string from form state returns.

**Steps to reproduce:**
1. Set default field value fo null
2. Get field value

**Related code:**
Set default value:
```
<SimpleForm
  defaultValues={{
    field: null,
  }}
>
```

Use it:
```
<FormDataConsumer>
  {({formData}) => (
    <div>
      field: {JSON.stringify(formData.field)}
    </div>
  )}
</FormDataConsumer>
```

**Result is:**
```
field: ""
```

**Environment**

* React-admin version: 4.4.1
* Last version that did not exhibit the issue (if applicable): 4.3.0
* React version: 18.2.0
* Browser: Chrome 106.0.5249.119

**Comment by shreyas-jadhav** [comment]
same issue!

**Comment by WiXSL** [comment]
Yes. It's a work in progress #8262
