### ISSUE TITLE
Module not found. Can't resolve 'react-admin'

### ISSUE THREAD

**Issue by hansolGib** [marmelab/react-admin#8265]
I'm trying to practice react with react-admin. I logged in ssh root@{ip address} in my terminal and git clone the react-admin in the remote server. Make install was successful even though had some warnings. Then, I tried make run-crm, and even went into the example/crm folder and run npm start to check whether it's working. However, it says

[Module not found: Error: Can't resolve 'react-admin' in '/root/react-admin/examples/crm/src'
ERROR in ./src/App.tsx 5:0-73
Module not found: Error: Can't resolve 'react-admin' in '/root/react-admin/examples/crm/src'

ERROR in ./src/Header.tsx 8:0-65
Module not found: Error: Can't resolve 'react-admin' in '/root/react-admin/examples/crm/src'
.
.
.
.]
, and picking up all values using 'react-admin'.

so i install react admin again using the command 'npm install react-admin'

and when i run make run-crm, i got an error 
[Internal Error: react-admin-lerna@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at AF.getCandidates (/root/react-admin/.yarn/releases/yarn-3.1.1.cjs:437:4421)
    at pd.getCandidates (/root/react-admin/.yarn/releases/yarn-3.1.1.cjs:432:5275)
    at /root/react-admin/.yarn/releases/yarn-3.1.1.cjs:441:7674
    at du (/root/react-admin/.yarn/releases/yarn-3.1.1.cjs:382:4003)
    at R (/root/react-admin/.yarn/releases/yarn-3.1.1.cjs:441:7654)
make: *** [Makefile:43: run-crm] Error 1]

so i did use 'yarn install' command. 
but, still having the error that [Module not found: Error: Can't resolve 'react-admin'] when i run make run-crm command

node version =v16.17.1
npm version = 8.15.0
yarn version = 3.1.1

**Comment by fzaninotto** [comment]
You have to run `make build` first, cf https://github.com/marmelab/react-admin#examples
