### ISSUE TITLE
Clear filter action doesn't appear when filter has `alwaysOn` props

### ISSUE THREAD

**Issue by Seojun-Park** [marmelab/react-admin#8277]
**Description:**

When any filter elements that has `alwaysOn` as true in filters prop on `<List />` component, `Remove Filter` action menu doesn't appears on `Add Filter` Button.

I assume, user should be able to remove filter by clicking reset(`x` mark on the right side of input) button and by clicking `Remove Filter` menu on `Add Filter` Button.

**What you were expecting:**

`Remove Filter` menu is appeared, even the filter input has `alwaysOn` prop.
So that, a user can remove all filter by clicking the menu.

**What happened instead:**

`Remove Filter` menu doesn't appear on the menu.

code sandbox link : https://codesandbox.io/s/broken-silence-8k4x5u?file=/src/posts/PostList.tsx

**Steps to reproduce:**

1. Choose any id on `<AutocompleteInput />` that is produced or add any value on `<SearchInput />` that is provided
2. Click `Add Filter Button`

**Environment**

* React-admin version: "^4.2.0"
* Last version that did not exhibit the issue (if applicable):
* React version: "^17.0.2",
* Browser: Chrome

**Comment by WiXSL** [comment]
Reproduced. Thanks!
