### ISSUE TITLE
Using a ReferenceField in a Form does not display the field name

### ISSUE THREAD

**Issue by clement-escolano** [marmelab/react-admin#8279]
**What you were expecting:**
When using a `ReferenceField` inside a `SimpleForm` inside an `Edit`, I expect the same behaviour as in the `Show` layout.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/11637509/196752912-9dd6f4a5-ac48-46b9-ae21-8245812017f2.png">

**What happened instead:**
There is no field name and there are other styling issues.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/11637509/196753002-0a243de3-d003-4c15-beec-eb70a97b78bd.png">

**Steps to reproduce:**
In a `SimpleForm` component inside an `Edit`, use a `ReferenceField` with a `TextField` to display a value (with no possibility to edit).

**Related code:**

Code here: https://codesandbox.io/s/sad-brahmagupta-rsyv8z?file=/src/comments/CommentEdit.tsx

In the `SimpleForm` (line 135) of the file `src/comments/CommentEdit.tsx`, there is this field:

```tsx
              <ReferenceField source="post_id" reference="posts">
                <TextField source="title" />
              </ReferenceField>
```

**Other information:**
It used to work in the v3.

**Environment**

* React-admin version: 4.4.3
* Last version that did not exhibit the issue (if applicable): 3.19.11
* React version: 17
* Browser: Firefox
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
This is not a bug. In react-admin v4, if you want to use Fields as children of SimpleForm, you must wrap them with a Labeled.

https://marmelab.com/react-admin/SimpleForm.html#using-fields-as-children

I agree that this should probably be mentioned in the upgrade guide, though.

**Comment by clement-escolano** [comment]
It works thank you :-)
Do you want me to open a pull request to add it in the upgrade guide?

**Comment by fzaninotto** [comment]
That would be great!

**Comment by clement-escolano** [comment]
Done :-)
