### ISSUE TITLE
SimpleForm component throws an error "Cannot read properties of null (reading 'control')"

### ISSUE THREAD

**Issue by mirronovko** [marmelab/react-admin#8289]
hi. i am using react-admin. the problem occurred in <SimpleForm>. it worked yesterday, but it stopped working today. code did not change. 

```
import React from "react";
import { Admin, Resource } from "react-admin";
import RegionCreate from "../regions/RegionCreate";

const App = () => (
  <Admin>
    <Resource name="regions" create={RegionCreate} />
  </Admin>
);

export default App;
```

```
import React from "react";
import { Create, SimpleForm, TextInput } from 'react-admin'

const RegionCreate = () => {
  return <Create>
    <SimpleForm>
      <TextInput
        name='name'
        source='name'
      />
    </SimpleForm>
  </Create>
}

export default RegionCreate
```
![example-5](https://user-images.githubusercontent.com/43735832/197255293-af53a2d1-9dd9-44fe-8cb7-05a595b4687a.png)

and here it works. What is going on?

```
import React from "react";
import { Create, SimpleForm, TextInput } from 'react-admin'

const RegionCreate = () => {
  return <Create>
    <div>
      test
    </div>
  </Create>
}

export default RegionCreate
```

![example-6](https://user-images.githubusercontent.com/43735832/197255546-c7e21be7-356f-4307-9726-cfbefeeb7320.png)

**Comment by slax57** [comment]
Please follow the issue template

**Comment by mirronovko** [comment]
@slax57 
`node v18.11.0`
`yarn 1.22.19`

package.json:
![sc12](https://user-images.githubusercontent.com/43735832/197576273-8f9a548e-079a-4f9e-9aeb-52abca31d4f2.png)
![sc13](https://user-images.githubusercontent.com/43735832/197576276-51fb93c7-3c65-4c5d-9ef8-f03a8c426f29.png)
![sc11](https://user-images.githubusercontent.com/43735832/197576277-5cbd896b-f88e-4721-9637-8ff497fcbde0.png)
![sc1](https://user-images.githubusercontent.com/43735832/197576279-14cd4b51-e599-48e5-88b2-a4223d2729fb.png)

```
...
"dependencies": {
    "history": "^5.3.0",
    "ra-data-json-server": "^4.4.3",
    "ra-data-simple-rest": "^4.4.3",
    "react": "^18.2.0",
    "react-admin": "^4.4.3",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.38.0",
    "react-scripts": "5.0.1",
    "slugify": "^1.6.5",
    "web-vitals": "^2.1.0"
  },
...
```

**Comment by WiXSL** [comment]
Thanks for reporting this!
Following the issue template implies giving us a way to reproduce the issue.

You can make 
A fork of our simple project in CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) 
Or a fork of our simple project in StackBlitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple)
Or A link to a GitHub repo 
With the minimal codebase to reproduce the issue

**Comment by mirronovko** [comment]
@WiXSL I'm sorry, https://codesandbox.io/s/nice-banach-q5wg71?file=/src/regions/RegionCreate.js. but for some reason there is another error

**Comment by slax57** [comment]
We'll keep this under "needs more info" for now, to give you some time to figure this out. When you manage to reproduce and are convinced this is a react-admin bug, please notify us again so we can have a look.

**Comment by fzaninotto** [comment]
No news for some time, closing.
