### ISSUE TITLE
SaveButton with alwaysEnable doesn't turn disabled when submiting the form

### ISSUE THREAD

**Issue by ramosht** [marmelab/react-admin#8292]
**What you were expecting:**
A custom `SaveButton` with `alwaysEnable` to be enabled before any edit but to be disabled when I submit the form, to prevent multiple submits on multiple clicks.

**What happened instead:**
When I submit a form that has a `SaveButton` with `alwaysEnable`, I'm able to click multiple times, submiting the form multiple times as well (generating duplicated records on my database when creating a new record, for example).

**Steps to reproduce:**
Create a `SimpleForm` with a custom `Toolbar` that have only a `SaveButton`, and then pass `alwaysEnable` to this `SaveButton`

**Related code:**

- [https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4)](https://codesandbox.io/s/thirsty-euclid-0kietg?file=/src/posts/PostCreate.tsx)

A simple snippet where it's still possible to reproduce it:
```
const CustomToolbar = () => (
  <Toolbar>
    <SaveButton alwaysEnable />
  </Toolbar>
);
```

**Environment**

* React-admin version: 4.4.4
* React version: 18.2.0
* Browser: Chrome

**Comment by slax57** [comment]
Hi,
Thank you for submitting this issue.
IMHO it makes some sense to have the `alwaysEnable` prop make the `SaveButton` always enabled, regardless of the submitting state.
Besides, if you need more fine-grained customization, it's quite easy to override the `SaveButton` with a custom button that will fit your needs.
Hence, I'll close this issue as we don't plan to fix this.
