### ISSUE TITLE
AutocompleteInput does not return to the initial state when clear the input 

### ISSUE THREAD

**Issue by arimet** [marmelab/react-admin#8297]
**What you were expecting:**
Recover the initial state when clearing an AutocompleteInput

**What happened instead:**
When you click outside the autocomplete input, the search is removed from the field. However the results are still filtered by this field. And it is impossible to remove this filter

**Steps to reproduce:**
- https://marmelab.com/react-admin-demo/
- Go to Sales > Orders
- Add filter -> Customers
- Type `Tromp`, click outside the field. Return on the field. 

https://user-images.githubusercontent.com/18294269/197570797-b21443dd-08fc-4405-98ea-a43438c5ee42.mp4

**Environment**

* React-admin version: 4.4.4
* React version: 18
* Browser: Brave

**Comment by slax57** [comment]
Reproduced, thanks
