### ISSUE TITLE
Allow to apply sorting and filtering on ReferenceOneField

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#8304]
The doc currently says:

> This field fetches a one-to-one relationship, e.g. the details of a book, when using a foreign key on the distant resource.

But actually it could be used to display only one record of many references (eg the latest reference of a record). To choose the right record to display, filtering & sorting might be useful. For example, to get the latest reference, I would like to sort DESC on a createdAt field. But I can't because the ASC order is hard coded [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/field/useReferenceOneFieldController.tsx#L49-L50).

Would you accept a PR on this feature?

**Comment by WiXSL** [comment]
Of course, PRs are always welcome

**Comment by fzaninotto** [comment]
Fixed by #8306
