### ISSUE TITLE
React Admin Vite not showing full width content

### ISSUE THREAD

**Issue by ganjarsetia** [marmelab/react-admin#8326]
Hi, please check this, is this bug?

**What you were expecting:**
Show full width like React Admin Tutorial

![image](https://user-images.githubusercontent.com/3258090/198511578-97c137ba-8c4f-4ac2-9c8a-0d44f38c8999.png)

**What happened instead:**
React Admin using Vite not showing full width content
![image](https://user-images.githubusercontent.com/3258090/198511156-ddfed9fb-85c7-4226-9591-5162074bb26c.png)

**Steps to reproduce:**
I tried follow [Vite tutorial](https://marmelab.com/react-admin/Vite.html) then [Get Started - Tutorial](https://marmelab.com/react-admin/Tutorial.html)
And the result is https://stackblitz.com/edit/vitejs-vite-g35d9t?file=src/App.jsx

**Environment**

* React-admin version: 4.4.4
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: `Brave [Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)](https://brave.com/latest/)`
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
You have left-over content in the `index.css` file that is conflicting with react-admin styles. You should remove it.

We currently have our **simple** demo (https://github.com/marmelab/react-admin/tree/master/examples/simple) and the **e-commerce** demo (https://github.com/marmelab/react-admin/tree/master/examples/demo) running with vite without any issues. So compatibility with vite should not be a problem :wink:

**Comment by ganjarsetia** [comment]
> You have left-over content in the `index.css` file that is conflicting with react-admin styles. You should remove it.
> 
> We currently have our **simple** demo (https://github.com/marmelab/react-admin/tree/master/examples/simple) and the **e-commerce** demo (https://github.com/marmelab/react-admin/tree/master/examples/demo) running with vite without any issues. So compatibility with vite should not be a problem wink

Ah I see, I didnt know should remove it. Thank you!

**Comment by fzaninotto** [comment]
Just a quick question: If you were following the Vite tutorial, where did the index.css come from?

**Comment by ganjarsetia** [comment]
> Just a quick question: If you were following the Vite tutorial, where did the index.css come from?

From this

![image](https://user-images.githubusercontent.com/3258090/198560703-829f2f09-5c7d-4749-a6fb-0b7775393bbd.png)

`yarn create vite my-admin --template react`

I think it would be better to tell the user to remove the index.css in Vite Tutorial

**Comment by slax57** [comment]
You are correct! I'll reopen this issue and mark it as documentation issue.

**Comment by fzaninotto** [comment]
But it seems to me that the tutorial is correct:

![image](https://user-images.githubusercontent.com/99944/198596045-0f30a3e6-6baf-40da-be35-fe53667cc81b.png)

It says replace the index, this should remove the import of the css file, right?

**Comment by ganjarsetia** [comment]
@fzaninotto Nope React Vite has different architecture, the tutorial doesn't say to modify the `main.jsx` which `index.css` is imported. See it here https://stackblitz.com/edit/vitejs-vite-g35d9t?file=src/main.jsx

**Comment by WiXSL** [comment]
Fixed by #8333
