### ISSUE TITLE
warnWhenUnsavedChanges not working when navigating to show from edit

### ISSUE THREAD

**Issue by mathieulordon-nimaling** [marmelab/react-admin#8338]
**What you were expecting:**

In the simple example https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple, when I navigate to a comment, edit the author name for example, and click the show button, I expect to have an alert saying my changes weren't saved.

**What happened instead:**

No alert is displayed and my changes are lost.
When I click on an other resource in the menu, the alert is displayed.

**Comment by WiXSL** [comment]
Thanks.
I believe is the same problem as described with the `CreateButton` below the `ShowButton` you are reporting in that code example.
It should get fixed like this:

```jsx
{/* FIXME: added with resource prop because react-router HashHistory cannot block navigation induced by address bar changes */}
<ShowButton resource="posts" record={record} />
{/* FIXME: added with resource prop because react-router HashHistory cannot block navigation induced by address bar changes */}
<CreateButton resource="posts" label="Create post" />
```

**Comment by mathieulordon-nimaling** [comment]
https://codesandbox.io/s/wizardly-rain-7p6pxp?file=/src/comments/CommentEdit.tsx:2650-2665

That's not really a fix even for `CreateButton`.

`CreateButton` should redirect to the creation of a comment.
`ShowButton` should redirect to the show page of the comment.

But…
`CreateButton` redirects to the creation of a **post**.
And with the same change, `ShowButton` redirects to the post with the id equals to the id of the comment (comment 1 => post 1, comment 2 => post 2, etc.) Not even the post the comment is linked to.

**Comment by WiXSL** [comment]
`...CreateButton should redirect to the creation of a comment....` for what I see, this was done on-propose to make cypress tests pass because of the FIXME comment.

`ShowButton should redirect to the show page of the comment.`, you are right, my mistake. your original concern is the main issue here, I will look into it.
