### ISSUE TITLE
Previous value showing when a field has been edited to null

### ISSUE THREAD

**Issue by cwagner22** [marmelab/react-admin#8341]
When `mutationMode='pessimistic'`:

1. I edit a record, set a field (tried with TextInput, NumberInput, SelectInput) that had a value to empty.
2. Save, redirected to the list.
3. Click on the Edit button to edit the same record, the old value is still shown instead of empty. (even though the server returns null for that value)

**Environment**

* React-admin version: 4.4.4

**Comment by slax57** [comment]
Can you please follow the issue template and provide a reproduction case? Thanks

**Comment by slax57** [comment]
No news for some time, closing.
