### ISSUE TITLE
IconButton size on AppBar is not very consistent

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#8347]
**What you were expecting:**

I expect all the IconButton on AppBar to have consistent size. (or a feature to allow better override of default size)

**What happened instead:**

Some of IconButtons are large and some are medium, also the spacing, they are not very consistent.

**Steps to reproduce:**

**Related code:**

Medium by default https://github.com/marmelab/react-admin/blob/a408de0db2c6db0281b3d39e27c1f2de3deed44e/packages/ra-ui-materialui/src/button/ToggleThemeButton.tsx#L39

Medium by default https://github.com/marmelab/react-admin/blob/64a9091c49a2a36a8974f1c261727edc64eeb39e/packages/ra-ui-materialui/src/preferences/InspectorButton.tsx#L40

large https://github.com/marmelab/react-admin/blob/a408de0db2c6db0281b3d39e27c1f2de3deed44e/packages/ra-ui-materialui/src/button/RefreshIconButton.tsx#L32

large https://github.com/marmelab/react-admin/blob/a408de0db2c6db0281b3d39e27c1f2de3deed44e/packages/ra-ui-materialui/src/layout/UserMenu.tsx#L107

large https://github.com/marmelab/react-admin/blob/479bc4af86d8a6fa31022ab57a7fe72428c82e36/packages/ra-ui-materialui/src/layout/SidebarToggleButton.tsx#L32

**Other information:**

**Environment**

* React-admin version: 4.5.0
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 18.2.0
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
You're totally right! Would you like to open a PR to fix this, and put them all in medium size?

**Comment by fzaninotto** [comment]
#8350 was reverted, so I'm reopening this one.
