### ISSUE TITLE
Column selection button should be made invisible on small screens

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#8360]
**What you were expecting:**

The button should disappear, or have the same style as other buttons

**What happened instead:**

![Screenshot from 2022-11-05 15-16-46](https://user-images.githubusercontent.com/38666763/200139302-a78cf2c2-d78a-4010-a85c-3d7c1a7ed30e.png)

**Steps to reproduce:**

Go to https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

Make screen smaller

**Related code:**

**Other information:**

**Environment**

* React-admin version: 4.5.0
* Last version that did not exhibit the issue (if applicable): 4.4.5
* React version: 18.2.0
* Browser:
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
Reproduced!
Thanks
