### ISSUE TITLE
RichTextInput moves cursor to end of input with each change

### ISSUE THREAD

**Issue by bchoate-jpg** [marmelab/react-admin#8361]
**What you were expecting:**
Normal text edit behavior.

**What happened instead:**
As I'm typing in the rich input field, the cursor moves to the end of the field.

**Steps to reproduce:**
I've reproduced the issue at this [repl.it instance.](https://RichTextInput-450.bradchoate.repl.co)

A fork of that project running with React Admin 4.4.4 is at this [repl.it instance](https://RichTextInput-444.bradchoate.repl.co), and shows the bug does not present.

**Related code:**
See above.

**Other information:**
Regression appears to have occurred with the 4.5.0 release. Switching back to 4.4.4 alleviates this issue, but I think the other issue the changes for 4.5.0 sought to address (content isn't in sync with the record state) are also present.

**Environment**

* React-admin version: 4.5.0
* Last version that did not exhibit the issue (if applicable): 4.4.4
* React version: 18.2.0
* Browser: Chrome latest
* Stack trace (in case of a JS error): n/a

**Comment by WiXSL** [comment]
Reproduced!
Thanks

**Comment by bchoate-jpg** [comment]
Thanks for the quick fix... although, I'm concerned the code here is invoking `editor.commands.setContent` unnecessarily for the case where the change is coming _from_ the editor itself. If I type "x" into the editor, and the change causes the field value to update and the effect code to trigger, isn't `editor.commands.setContent` unneeded, since the editor has that content already?

And then in the case where the field value is truly changed, but externally (a record context change)... I'd think that would need to reset the cursor position to the top of the document, since the location may not be valid for the new content.

**Comment by WiXSL** [comment]
This is the way we use to update the value coming from react-hook-form to the TipTap editor component.
If you know a more efficient way to do it, please, let us know.
