### ISSUE TITLE
Custom ErrorComponent in Layout locked

### ISSUE THREAD

**Issue by kdzone** [marmelab/react-admin#8370]
**What you were expecting:**
In version 4.4.1. when a data query error occurs in list, it was displayed in the ErrorComponent at the Layout level. 
In my Error component.

**What happened instead:**
Now in 4.5.0 the error is caught in the ListView.
src\list\ListView.tsx
```
      {error ? (
                <Error error={error} resetErrorBoundary={null} />
            ) : (
```
I can't catch the error display (only write my ListView).

**Steps to reproduce:**
Raise error on fetch data in any list,

**Comment by fzaninotto** [comment]
I'm confused. If a server error occurred in the List, in 4.4, the list was empty, with just an error notification. Example:

https://stackblitz.com/edit/github-csopnk?file=src%2FdataProvider.tsx

<img width="689" alt="image" src="https://user-images.githubusercontent.com/99944/200483880-5d73845e-3d1d-4400-8d8a-bbfebcecfeb8.png">

Server errors in the List view were not displayed in the Error component prior to 4.5.

Can you elaborate on the regression you're having?

**Comment by kdzone** [comment]
I am very sorry that I misled you.
In version 4.4.1, a blank list screen was displayed when an error occurred
and notification with an error. 
I have written my own error handling mechanism,
which stopped working after migrating to 4.5.0.

I really want to be able to replace the error component in the lists. 
Maybe you will make an additional property ErrorComponent.
