### ISSUE TITLE
change rowsPerPageOptions for <Pagination/> component globally on all <List/>

### ISSUE THREAD

**Issue by rgsk** [marmelab/react-admin#8373]
do we have a global of way of configuring rowsPerPageOptions for all the lists across the application. 

We can use below, but can there be an option to configure below globally for all List
```typescript
<List
      pagination={<Pagination rowsPerPageOptions={[5, 10, 25, 50]} />}
    ></List>
```

**Comment by rgsk** [comment]
anything better than below
```typescript
const CustomPagination = <Pagination rowsPerPageOptions={[5, 10, 25, 50]} />
<List
      pagination={<CustomPagination/>}
></List>
```

**Comment by fzaninotto** [comment]
No, we don't. React-admin encourages building your own variations of the core components instead of providing god-like components that configure their children. 

https://marmelab.com/react-admin/Architecture.html#component-composition
