### ISSUE TITLE
MuiCssBaseline component styleOverrides in custom theme is not working

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#8375]
**What you were expecting:**
To be able to change the body background image using MuiCssBaseline component styleOverrides.

**What happened instead:**
body tag is not styled at all by the theme

**Steps to reproduce:**

Go to:
https://stackblitz.com/edit/github-br7omu?file=src%2Findex.tsx,src%2FmyTheme.ts,src%2Fposts%2FPostList.tsx

You should see a fat blue dashed border at the body of the document, but there isn't. In contrast, RaDatagrid overrides are working.

```ts
import { defaultTheme } from 'react-admin';
import indigo from '@mui/material/colors/indigo';
import pink from '@mui/material/colors/pink';
import red from '@mui/material/colors/red';

export const myTheme = {
  ...defaultTheme,
  palette: {
    primary: indigo,
    secondary: pink,
    error: red,
    contrastThreshold: 3,
    tonalOffset: 0.2,
  },
  components: {
    ...defaultTheme.components,
    RaDatagrid: {
      styleOverrides: {
        root: {
          backgroundColor: 'green',
        },
      },
    },
    MuiCssBaseline: {
      styleOverrides: {
        body: {
          border: '20px dashed blue',
        },
      },
    },
  },
};

```

**Other information:**

- How to change global styles in MUI 5 in general: https://stackoverflow.com/a/71469625/1385429
- https://github.com/marmelab/react-admin/pull/8216

**Environment**

* React-admin version: 4.5
* Last version that did not exhibit the issue (if applicable): n/a
* React version: 18
* Browser: Chrome

**Comment by WiXSL** [comment]
In the case of the `Datagrid`, you get the green background, you probably are seeing it in a small screen which is showing a `SimpleList` instead and the style is not getting applied

**Comment by christiaanwesterbeek** [comment]
Thank you. I'll update the title, because the issue then seems narrowed down to only affect the MuiCssBaseline component...

**Comment by WiXSL** [comment]
`react-admin` uses `ScopedCssBaseline` instead of `MuiCssBaseline`, you have to change it, that's the problem here.

**Comment by christiaanwesterbeek** [comment]
Thanks man! I was trying al sorts of combinations except that one.

**Comment by christiaanwesterbeek** [comment]
I must be overlooking something, because I just tried `ScopedCssBaseline` instead of `MuiCssBaseline`, and still no border around the body.

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/465989/200888209-33eefd39-d9fb-4592-a4ae-b076c0d49b6b.png">

**Comment by WiXSL** [comment]
![screenshot](https://user-images.githubusercontent.com/8268610/200889596-c9b82160-f247-4890-959b-81f54afb4bb6.jpg)
It's show in wider screens.
I don't know if this is right

**Comment by christiaanwesterbeek** [comment]
Yes, I know I've seen that working. But I mean, that there is no border around the body.

<img width="1694" alt="image" src="https://user-images.githubusercontent.com/465989/200889964-59d0f8cf-767a-41fd-8b7c-b5e0a0227068.png">

There should be some kind of border around the body because of the ScopedCssBaseline body override.

Look, when you enter it manually at the body element, this is what you should get.

<img width="1694" alt="image" src="https://user-images.githubusercontent.com/465989/200890632-cbe09063-d02f-43b2-acd9-82950227f37d.png">

**Comment by christiaanwesterbeek** [comment]
I found the solution!

```
MuiScopedCssBaseline: {
  styleOverrides: {
    root: {
      border: '20px dashed salmon',
    },
  },
},
```

Source: https://stackoverflow.com/a/69586769/1385429

**Comment by WiXSL** [comment]
You are right!
Sorry I missed that
