### ISSUE TITLE
Ra-data-json-server filter bug

### ISSUE THREAD

**Issue by shurshilov** [marmelab/react-admin#8377]
4.4. 4.5
in line of getList or getManyReference
https://github.com/marmelab/react-admin/blob/master/packages/ra-data-json-server/src/index.ts#L41
use ...fetchUtils.flattenObject(params.filter)
and it unpack filter to query params that not equal to DOCS
https://marmelab.com/react-admin/FilteringTutorial.html#filter-query-parameter
because not filter json send send many unpack query params.
should be lke this
_filter: JSON.stringify(filter),

**Comment by fzaninotto** [comment]
I'm sorry, what is the bug? What do you expect, what do you get instead? And how can we reproduce the bug? 

Please follow the issue template.

**Comment by shurshilov** [comment]
I have described everything. The documentation says that the filtering peer, the filter object is added to the search string, which contains all the search fields and their values.
Here is an example https://myadmin.dev/#/posts?displayedFilters=%7B%22commentable%22%3Atrue%7D&filter=%7B%22commentable%22%3Atrue%2C%22q%22%3A%22lorem%20%22% 7D&order=DESC&page=1&perPage=10&sort=published_at
.It is here that the link I gave refers.
And in fact now, there is no filter object in the query string; instead, all fields are unpacked and added as query params and it turns out like this
https://myadmin.dev/#/posts?commentable=true&q=lorem&order=DESC&page=1&perPage=10&sort=published_at
The difference is obvious, most likely the library is still not very popular and this behavior has not been discovered or most of them are written by their own providers

**Comment by fzaninotto** [comment]
> The documentation says that (...) the filter object is added to the search string, which contains all the search fields and their values.

Which documentation are you referring to? The ra-data-json-server documentation at https://github.com/marmelab/react-admin/tree/master/packages/ra-data-json-server doesn't say anything about having a filter object.

**Comment by shurshilov** [comment]
1. https://marmelab.com/react-admin/DataProviders.html
GET http://my.api.url/posts?sort=["title","ASC"]&range=[0, 24]&filter={"title":"bar"}
2. https://marmelab.com/react-admin/useInfiniteGetList.html
{
    pagination: { page, perPage },
    sort: { field, order },
    filter: { ... },
    meta: { ...}
}
3.https://marmelab.com/react-admin/DataProviderWriting.html
const { data } = await dataProvider.getList('posts', {
    pagination: { page: 1, perPage: 5 },
    sort: { field: 'title', order: 'ASC' },
    filter: { author_id: 12 },
})
4.https://marmelab.com/react-admin/FilteringTutorial.html#filter-query-parameter
React-admin uses the filter query parameter from the URL to determine the filters to apply to the list. To change the filters, react-admin simply changes this filter query parameter, and the <List> components fetches dataProvider.getList() again with the new filters.

**Comment by shurshilov** [comment]
filter ALWAYS obkect but in your lib its not object:)

**Comment by fzaninotto** [comment]
@shurshilov You're mixing up the syntax of the dataProvider Input and the syntax of the underlying REST API. 

The dataProvider expects a filter object. As for the API, we're making no assumption and instead, providing a set of adapters. 

If the existing adapters don't suit your need, write your own dataProvider. 

As far as I understand, there is no bug in react-admin, so I'll close this issue.

**Comment by shurshilov** [comment]
> @shurshilov You're mixing up the syntax of the dataProvider Input and the syntax of the underlying REST API.
> 
> The dataProvider expects a filter object. As for the API, we're making no assumption and instead, providing a set of adapters.
> 
> If the existing adapters don't suit your need, write your own dataProvider.
> 
> As far as I understand, there is no bug in react-admin, so I'll close this issue.

I don't understand what input parameters you are talking about. It's about output parameters. When json-data-provider sends a request, it unpacks the entire filter. Now show me the code on the backend that can handle this))) Why is this module needed, do you need to rewrite all the functions with a filter? What task does it perform?
