### ISSUE TITLE
useReferenceFieldController Not found in code or documentation

### ISSUE THREAD

**Issue by Slntswrd** [marmelab/react-admin#8379]
Hi I am not sure if this is a bug or Support Question or something else.

In the documentation page: "Upgrading to v4", in the section: "Miscellaneous"
in the paragrapher: "Removed Deprecated Elements" I read: "Removed `<ReferenceFieldController>` (use useReferenceFieldController instead)".

**But i can't find anywhere in the documentation the usage for useReferenceFieldController. I have also tried to search it in the code via github search but i can't find it anywhere.**

This also happen for other elements in the "Removed Deprecated Elements" paraghapher.
Are those feature a work in progress? 

Thanks a lot!

**Comment by fzaninotto** [comment]
Yes, those are a work in progress. You've probably seen that we've added a massive amount of documentation already when compared to v3, helping developers with lower-level APIs. This will take time to cover all the public API.

In the meantime, read the source, Luke!

**Comment by Slntswrd** [comment]
Hi fzaninotto,
Really thanks for your reply!

But as written before:
> I have also tried to search it in the code via github search but i can't find it anywhere.

Maybe i can't use correctly the github search, but when I search for "useReferenceFieldController" and select "from this repository" i can find this mentioned only in the markdown of documentation. 
I will get you a screenshot.

![Schermata del 2022-11-10 12-35-22](https://user-images.githubusercontent.com/7038145/201080790-43a3537f-9678-47e8-b6d2-16ebef403f55.png)

 can you please tell me where are those functions in the code?

Thanks again
