### ISSUE TITLE
Fixed by #3735

### ISSUE THREAD

**Issue by clonez** [marmelab/react-admin#8390]
Fixed by #3735

_Originally posted by @fzaninotto in https://github.com/marmelab/react-admin/issues/3733#issuecomment-535048858_
      

Is this issue merged to the latest react-admin package? Don't see the red text on the CheckboxGroupInput validation.

**Comment by fzaninotto** [comment]
please follow the issue template

**Comment by fzaninotto** [comment]
I see that's a double post from #3735. Please don't do that - we have largely enough notifications.
