### ISSUE TITLE
React 14.3 compat

### ISSUE THREAD

**Issue by auvipy** [marmelab/react-admin#84]

**Comment by vencax** [comment]
I have tried to debug failing tests with 14.x react but still was not sucessful. 
https://github.com/blueskydigital/react-admin/tree/testfix
The libs used in react-admin are quite old and when upgraded new issues arises.
The showstoper is unability do debug the jest test with node-inspector for me now.
Maybe somebody is further and can help?
nice day, Vasek

**Comment by fzaninotto** [comment]
ping @jeromemacias

**Comment by auvipy** [comment]
I would suggest to use redux and react for upgrading the admin. I would be also be able to help

**Comment by vencax** [comment]
React is used (just from name :) I think I saw somewhere that flux is used for flow control. In any case IMHO now is necessary to remove obsolete libs switch to new ones (react 14) and still have the test passing.

**Comment by auvipy** [comment]
react + redux as flux + redux-react for later :) probably the test deps need to be updated too and tests rewrite in some case?

**Comment by vencax** [comment]
yes, there are some obsolete libs and their usage makes the testing harder. I started [here](https://github.com/blueskydigital/react-admin/tree/testfix) but was not able to fix the tests. I have insuficient knowledge of JEST and was not able to set up debugger.
Concerning usage of flux: IMHO it would be better to use it already in [admin-config](https://github.com/marmelab/admin-config) letting react-admin solve only the presentation part with flux-react.

**Comment by vencax** [comment]
I upgraded all libraries to current (react 15). I made all unit tests passing as requested in https://github.com/marmelab/react-admin/pull/85#issuecomment-180062074). Now I will verify the E2E tests. Then I will remove obsolete stuff.
https://github.com/blueskydigital/react-admin/tree/example_tunning

**Comment by thomasmodeneis** [comment]
@vencax great work you've done there, any plans for this to merged up to master ?
Cheers.

**Comment by fzaninotto** [comment]
This project is discontinued. We've published a complete rewrite and committed to support it. Check out [marmelab/admin-on-rest](https://github.com/marmelab/admin-on-rest).
