### ISSUE TITLE
DatagridConfigurable doesn't work with both filters and actions

### ISSUE THREAD

**Issue by adamjq** [marmelab/react-admin#8406]
I've tried to use the `DatagridConfigurable` component from the docs https://marmelab.com/react-admin/Datagrid.html under `Showing / Hiding Columns` but it's removing the filters I've already configured. The docs suggest that both filters and actions should be compatible. I'm using the `ra-data-graphql-simple` library to provide data.

**What you were expecting:**
DatagridConfigurable to display both the `SelectColumnsButton` and `Add Filter` sections.

**What happened instead:**
Adding `SelectColumnsButton` and `DatagridConfigurable` added an option to select columns but removed the `Add Filter` section.

The search bar defined in the filters still displays and works.

**Related code:**
```tsx
import React from 'react';
import { List, DatagridConfigurable, TextField, TextInput, NumberInput, TopToolbar, SelectColumnsButton } from 'react-admin';

const userFilters = [
    <TextInput label="Search by Email" source="q" alwaysOn />,
    <NumberInput label="id" source="id"/>,
];

const UserListActions = () => (
    <TopToolbar>
        <SelectColumnsButton />
    </TopToolbar>
);

export const UserList = (props: any) => {
    return (
        <List {...props} actions={<UserListActions />} filters={userFilters}>
            <DatagridConfigurable bulkActionButtons={false}>
                <TextField source="id" sortable={false}/>
                <TextField source="email" />
            </DatagridConfigurable>
        </List>
    );
};
```

**Library versions**
```
  "ra-data-graphql-simple": "^4.4.3"
  "react": "^18.2.0"
  "react-admin": "^4.5.1"
  "react-dom": "^18.2.0"
  "react-scripts": "5.0.1"
```

**Comment by WiXSL** [comment]
Maybe we should improve the example in the docs. (https://marmelab.com/react-admin/Datagrid.html#showing--hiding-columns)

If you are passing the `actions`, you are responsible for adding every action button.

```diff
const UserListActions = () => (
    <TopToolbar>
        <SelectColumnsButton />
+      <FilterButton />
+      <CreateButton />
+      <ExportButton />
    </TopToolbar>
);
```

**Comment by adamjq** [comment]
Great thanks @WiXSL - I tried that and it worked perfectly. I agree the documentation could be updated for that particular section
