### ISSUE TITLE
Weird 8px `<body>` margin when following new vite tutorial

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#8407]
**What you were expecting:**

I expect there are no extra margin when following the tutorial

**What happened instead:**

There are some margins after completing steps of https://marmelab.com/react-admin/Tutorial.html#mapping-api-endpoints-with-resources

**Steps to reproduce:**

Create new vite project and follow tutorial till https://marmelab.com/react-admin/Tutorial.html#mapping-api-endpoints-with-resources

![margin](https://user-images.githubusercontent.com/38666763/202835181-baef83b2-3e18-4e14-8359-badfbfe09d8b.PNG)

**Related code:**

https://github.com/vitejs/vite/blob/main/packages/create-vite/template-react-ts/src/index.css#L28

**Other information:**

https://github.com/marmelab/react-admin/blob/202274ef30b5538650798b1348df4b0ac028ea7e/docs/Tutorial.md?plain=1#L83

We shall preserve part of this index.css file

**Environment**

* React-admin version: 4.5.1
* Last version that did not exhibit the issue (if applicable): 4.5.0
* React version: 18.2.0
* Browser: Edge 107
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
I think you are right.
The simple project has a style set of  `body { margin: 0 }` in its index.html file
