### ISSUE TITLE
State don't update after login by google unless i reload app in react native

### ISSUE THREAD

**Issue by iamemiliano** [marmelab/react-admin#8408]
Hello, i hope you are doing well.

I have a few problem when i try to log in with Google in react native. I have a global state for user :

const initialState = {
    userId: null,
    token: null,
    email: "",
    firstName: "",
    lastName: "",
    nom: "",
    dateOfBirth: null,
    roles: [],
    photoUrl: "",
    phoneNumber: "",
    favorites: [],
};

With Login, it work well and my global state is update. The logic :

export const login = (email, password) => {
    return async (dispatch) => {
        const response = await auth.signInWithEmailAndPassword(email, password).then().catch((error) => {
            Alert.alert("L'email ou le mot de passe est invalide");
            throw new Error()
        } );

        if (response && response.user.uid === null) {
            throw new Error("Something went wrong!");
        }

        const user = await db.collection("Users").doc(response.user.uid).get();

        const expirationTime = (await response.user.getIdTokenResult())
            .expirationTime;

        const newDate = new Date(expirationTime).getTime();

        const token = (await response.user.getIdTokenResult()).token;

        await dispatch(authenticate(response.user.uid, token, newDate));
        await dispatch(
            addUserInfos(
                user.get("email"),
                user.get("username"),
                user.get("firstName"),
                user.get("lastName"),
                user.get("dateOfBirth")?.toDate(),
                user.get("roles"),
                user.get("photoUrl"),
                user.get("phoneNumber"),
                user.get("favorites"),
            )
        );

        const expirationDate = new Date(new Date().getTime() + newDate);

        saveDataToStorage(token, response.user.uid, expirationDate);
    };
};
But when i want to connect with Google. The app connect me but my global state only contain value userId and token. I need the reload the app for set my global state. However the 2 functions use the same logic.

export const addUserOnFirestore = (id, email, firstName, lastName, photoUrl, response, navigation) => {
    return async (dispatch) => {
        let isNeedOnboarding = false;
        const user = await db
            .collection('Users')
            .doc(id)
            .get();

        // Create user in firestore in it not exist
        if (!user.exists) {
            isNeedOnboarding = true;
            console.log('onboard : ', isNeedOnboarding);
            await db.collection('Users').doc(id).set({
                email: email,
                username: '',
                firstName: firstName ? firstName : '',
                lastName: lastName ? lastName : '',
                dateOfBirth: null,
                roles: [],
                photoUrl: photoUrl ? photoUrl : '',
                phoneNumber: '',
                favorites: [],
            }).then(res => {
                console.log("Effectué")
            })
                .catch(error => {
                    console.log("firestore error:", error);
                });
        } else {
            console.log('Document data:', user.data());
        }

        const expirationTime = (await response.user.getIdTokenResult())
            .expirationTime;

        const newDate = new Date(expirationTime).getTime() * 1000;

        const token = (await response.user.getIdTokenResult()).token;

        await dispatch(authenticate(token, id, newDate));

        if (isNeedOnboarding) {
            await dispatch(addUserInfos(email, '', firstName, lastName, '', '', photoUrl, '', []));
            navigation.navigate("Onboarding");
        } else {
            await dispatch(
                addUserInfos(
                    user.get("email"),
                    user.get("username"),
                    user.get("firstName"),
                    user.get("lastName"),
                    user.get("dateOfBirth")?.toDate(),
                    user.get("roles"),
                    user.get("photoUrl"),
                    user.get("phoneNumber"),
                    user.get("favorites"),
                )
            );
        }
        const expirationDate = new Date(new Date().getTime() + newDate);

        saveDataToStorage(token, id, expirationDate);

        if (isNeedOnboarding) {
            navigation.navigate("Onboarding");
        }
    };
};
The dispatch function addUserInfo :

const addUserInfos = (
    email,
    username,
    firstName,
    lastName,
    dateOfBirth,
    roles,
    photoUrl,
    phoneNumber,
    favorites,
) => {
    return (dispatch) => {
        dispatch({
            type: ADD_USER_INFO,
            payload: {
                email: email,
                username: username,
                firstName: firstName,
                lastName: lastName,
                dateOfBirth: dateOfBirth,
                roles: roles,
                photoUrl: photoUrl,
                phoneNumber: phoneNumber,
                favorites: favorites,
            },
        });
    };
};

And the authenticate :

export const authenticate = (userId, token, expiryTime) => {
    return (dispatch) => {
        dispatch(setLogoutTimer(expiryTime));
        dispatch({ type: AUTHENTICATE, payload: { userId, token } });
    };
};

Do you have any idea why it works in the simple login but not when I want to connect with google? Then why it is only when I reload the application that my global state is updated ?

Thanks in advance.

**Comment by slax57** [comment]
Hi, and thanks for your question.
As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for **bugs and feature requests only**.

It seems to me that what you are asking for here is rather help to identify the origin of your issue.

For such questions, you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
