### ISSUE TITLE
AutocompleteInput does not fetch the selected record by ID if `parse` and `format` attributes are present

### ISSUE THREAD

**Issue by magicxor** [marmelab/react-admin#8423]
**What you were expecting:**
When I open an edit page with AutocompleteInput on it (inside ReferenceInput), it should display the selected item regardless of its position on the list.

```tsx
  <Edit>
      <SimpleForm>
          <ReferenceInput label="Country" source="country" parse={valueToIdObject} format={valueToId} reference="country" sort={{ field: 'name', order: 'ASC' }} required fullWidth>
              <AutocompleteInput optionText="name" filterToQuery={createSearchFilter} parse={valueToIdObject} format={valueToId} fullWidth />
          </ReferenceInput>
      </SimpleForm>
  </Edit>
```

**What happened instead:**
The selected item is displayed only if it can be found on the first page of the list.

The bug **does not** reproduce if I rewrite this code without `format` and `parse` attributes:

```tsx
  <Edit>
      <SimpleForm>
          <ReferenceInput source="country.id" reference="country" sort={{ field: 'name', order: 'ASC' }} required fullWidth>
              <AutocompleteInput label="Country" optionText="name" filterToQuery={createSearchFilter} fullWidth />
          </ReferenceInput>
      </SimpleForm>
  </Edit>
```

**Steps to reproduce:**
1) Launch [CodeSandbox](https://codesandbox.io/p/github/magicxor/react-admin-repro-AutocompleteInput-pagination-bug/draft/awesome-diffie?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clasfqz2900017pbi5tew4rrm%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clasfsek700942a69hfpod7pr%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fuser%252F112%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clasfsb9l00732a69m9z8mil7%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%257D) or the code from this [repo](https://github.com/magicxor/react-admin-repro-AutocompleteInput-pagination-bug).
2) Edit user -> 112 - country is loaded correctly because it starts with A and it's on the first page of the data list
3) Edit user -> 113 - country is not loaded because it starts with T

**Environment**

* React-admin version: ^4.5.1
* Last version that did not exhibit the issue (if applicable):
* React version: ^18.2.0
* Browser: Chrome 107.0.5304.107 (Official Build) (64-bit) and Firefox 107.0 (64-bit)
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. 

As explained in the doc, [`<ReferenceInput>` doesn't support the `parse` prop](https://marmelab.com/react-admin/ReferenceInput.html#format). You're supposed to put the `parse` prop on the component child. 

As you're not using the component as documented, this is not considered a bug. I'm closing the issue, but feel free to comment if you think otherwise.

**Comment by magicxor** [comment]
@fzaninotto Hi, I have removed parse and format attributes from ReferenceInput, but the bug still persists.

```tsx
      <Edit>
          <SimpleForm>
              <ReferenceInput label="Country" source="country" reference="country" sort={{ field: 'name', order: 'ASC' }} required fullWidth>
                  <AutocompleteInput optionText="name" filterToQuery={createSearchFilter} parse={valueToIdObject} format={valueToId} fullWidth />
              </ReferenceInput>
          </SimpleForm>
      </Edit>
```

Please see the updated [CodeSandbox](https://codesandbox.io/p/github/magicxor/react-admin-repro-AutocompleteInput-pagination-bug/master?file=%2Fsrc%2FUserEdit.tsx&selection=%5B%7B%22endColumn%22%3A14%2C%22endLineNumber%22%3A52%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A46%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clatldea5000i7pg4aogebgyb%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clatleych01i52a6alcdieai4%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clatleuk101fc2a6a19usykwc%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) or the [repo](https://github.com/magicxor/react-admin-repro-AutocompleteInput-pagination-bug).

**Comment by magicxor** [comment]
@fzaninotto @WiXSL I’m sorry to bother you, but I was wondering if you could take a look at the updated code. Maybe this issue worth reopening?

**Comment by slax57** [comment]
@magicxor I think you are using `<ReferenceInput>` the wrong way.
The `source` prop of `<ReferenceInput>` needs to point to an id, you cannot point to a complex object.
In your case I'm not sure you need `format` nor `parse`, rather you should only need to use `source="country.id"` in `<ReferenceInput>`.
