### ISSUE TITLE
Boolean filter is not active by default

### ISSUE THREAD

**Issue by magicxor** [marmelab/react-admin#8430]
**What you were expecting:**
When I add a boolean filter, it immediately applies to the list. (Because it's BooleanInput, not NullableBooleanInput - it should have only two states)

**What happened instead:**
When I add a boolean filter, it has the same visual appearance as 'false' filter, but in fact it's just "not active".

![firefox_WalnDWmbQB](https://user-images.githubusercontent.com/8275793/203718001-a70db26b-e8d5-41df-85c2-427bfe3fbadf.gif)

**Steps to reproduce:**
1) Launch this [CodeSandbox](https://codesandbox.io/p/github/magicxor/react-admin-repro-boolean-filter-bug/draft/wonderful-sea?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clauq4vkc00047phphlxu62c8%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522clauq4y2o000r2a69p0qxk4lo%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clauq6bay007m2a69rpk2rxx1%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fcountry%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clauq68b9005l2a69azojfupk%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) or the code from this [repo](https://github.com/magicxor/react-admin-repro-boolean-filter-bug).

2) Open menu -> Countries

3) Add filter -> Is supported

**Related code:**
[CodeSandbox](https://codesandbox.io/p/github/magicxor/react-admin-repro-boolean-filter-bug/draft/wonderful-sea?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clauq4vkc00047phphlxu62c8%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522clauq4y2o000r2a69p0qxk4lo%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clauq6bay007m2a69rpk2rxx1%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fcountry%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clauq68b9005l2a69azojfupk%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) or [repo](https://github.com/magicxor/react-admin-repro-boolean-filter-bug)

```tsx
const gridFilters = [
  <BooleanInput label="Is supported" source="isSupported" />,
];
```

**Environment**

* React-admin version: ^4.5.1
* Last version that did not exhibit the issue (if applicable):
* React version: ^18.2.0
* Browser: Chrome 107.0.5304.107 (Official Build) (64-bit) and Firefox 107.0 (64-bit)
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
I disagree on how it should work, but you can fix it by passing a default value:

```jsx
const gridFilters = [
  <BooleanInput label="Is supported" source="isSupported" defaultValue />,
];
```
