### ISSUE TITLE
DataGridConfigurable & SelectColumnsButton preferenceKey broken

### ISSUE THREAD

**Issue by wcoppens** [marmelab/react-admin#8431]
**What you were expecting:**
When using the `<DataGridConfigurable>` component and apply a property `preferenceKey` with any value. You expect that a `<SelectColumnsButton>` component with the same property and value to show the columns of that datagrid.

**What happened instead:**
Instead we see an empty list of selectable columns.

**Related code:**
Following sandbox illustrates the problem on the Posts list page:
https://codesandbox.io/s/cocky-hooks-078gbb?file=/src/posts/PostList.tsx:2183-2196

**Environment**

* React-admin version: latest 
* React version: 18
* Browser: chrome

**Comment by WiXSL** [comment]
Reproduced!
Thanks for the report
