### ISSUE TITLE
React admin ReferenceInput filter exclude ids?

### ISSUE THREAD

**Issue by amit-sw-ac** [marmelab/react-admin#8434]
While using ReferenceInput we can use a filter like this. 

```
<ReferenceInput source="company_id" reference="companies"  filter={{ ids: [1, 2, 3}} >
    <AutocompleteInput label="Employer" />
</ReferenceInput>
```

This will return companies with id 1, 2 or 3 in the AutoComplete Input

However, my requirement is to filter to exclude some ids. Not sure how can I use not query here?

**Comment by WiXSL** [comment]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(https://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`) or the react-admin Discord Server(https://discord.gg/GeZF9sqh3N). Thanks! 😁.
