### ISSUE TITLE
TypeScript props say children compulsory for ReferenceArrayInput

### ISSUE THREAD

**Issue by IanMayo** [marmelab/react-admin#8438]
**What you were expecting:**

The `children` prop for `ReferenceArrayInput` should be `optional`.

![image](https://user-images.githubusercontent.com/1108513/204096669-c5a3db3d-f55e-42c5-97f7-16e305388f63.png)

**What happened instead:**

The `children` prop for `ReferenceArrayInput` is compulsory:

![image](https://user-images.githubusercontent.com/1108513/204096679-b2e2575f-c475-4f26-9fbc-0d7323292408.png)

**Environment**

* React-admin version: 4.5.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Confirmed, thanks!
