### ISSUE TITLE
`<NumberInput>` `format` function gets applied twice

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#8441]
**What you were expecting:**
I expect the format function only gets applied once

degree -> radian should * Math.PI / 180

**What happened instead:**

Format function gets applied twice

degree -> radian * (Math.PI / 180)^2

**Steps to reproduce:**
Go to https://stackblitz.com/edit/github-m7rhmv-uyfxyw?file=src%2Fcomments%2FCommentCreate.tsx
Go to Comments -> Create new comments
Change the dropdown selection to radian

Expected value for 10.2222 degree is 0.1784 radian, but got 0.0031 radian

**Related code:**

```
https://stackblitz.com/edit/github-m7rhmv-uyfxyw?file=src%2Fcomments%2FCommentCreate.tsx
```

**Other information:**

Related: https://github.com/marmelab/react-admin/pull/8422

**Environment**

* React-admin version: 4.5.3
* Last version that did not exhibit the issue (if applicable): N/A(4.5.3 did not fix correctly)
* React version: 18.2.0
* Browser: Firefox 106
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Indeed, thanks for the report!
