### ISSUE TITLE
NumberInput misinterprets zero-values (0 or 0.0) as type of string instead of number

### ISSUE THREAD

**Issue by poe42** [marmelab/react-admin#8451]
**What you were expecting:**
Number inputs with values equal to ```0``` or ```0.0``` should be regarded/handled as number types.

**What happened instead:**
Whenever you enter a zero value into a NumberInput (no matter if via arrow buttons or by key input) they are interpreted as of type of string.

**Steps to reproduce:**

1. Select _Posts_ from the Menu of the provided [trimmed simple example](https://codesandbox.io/s/optimistic-goldwasser-s6wnu6?file=/src/posts/PostEdit.tsx)
2. Click one of the posts to go to its edit page (which was trimmed down to a single NumberInput)
3. Enter a zero value (```0``` or ```0.0```) into the NumberInput ("Average note")
4. Check the console info output for the actual type of the parsed/formatted NumberInput value

**Environment**

* React-admin version: 4.5.0 (see forked codesandbox of master/example/simple)
* React version: 17.0.2
* Browser: Brave 1.45.133 Chromium: 107.0.5304.141 (64-Bit)

**Comment by slax57** [comment]
Reproduced, thanks!
