### ISSUE TITLE
rowClick show does not work when datagrid is nested in different resource show page

### ISSUE THREAD

**Issue by crtl** [marmelab/react-admin#8471]
**What you were expecting:**
Datagrid should read the list context and navigate to resource.

**What happened instead:**
Datagrid seems to read wrong resource value.

**Steps to reproduce:**
```typescript
const MyList = () => {
  const list = useListController({resource: "comments"});
  return <ListContextProvider value={list}>
    <Datagrid rowClick="show" />
  </ListContextProvider>
}
```
When `MyList` is used in tab of any detail page of another resource the rowClick does not work as expected.

**Related code:**
Ive created an example in `PostShow` in the following sandbox:
https://codesandbox.io/s/sweet-volhard-965czy?file=/src/posts/PostShow.tsx:839-843

Heres a link to the demo:
https://965czy.sse.codesandbox.io/#/posts/1/show/4

**Other information:**

**Environment**

* React-admin version: 4.6.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi,
I'm not sure that providing the resource in `useListController` is enough. You should probably try to wrap your List inside a `<ResourceContextProvider value="comments">`.

Have a look at what we do [here](https://github.com/marmelab/react-admin/blob/master/examples/simple/src/tags/TagEdit.tsx#L29) for instance (it's not exactly the same but it is somewhat similar to what you are trying to do).

I'm closing this issue for now since I don't think there is a bug. Feel free to reopen otherwise.

**Comment by crtl** [comment]
I have already thought about this.
I was following the [documentation/guide for `List`](https://marmelab.com/react-admin/ListTutorial.html#uselistcontext-accesses-the-list-context).
From the documentation it is not clear that `ResourceContextProvider` is required maybe this should be added for clarity.

Also:
Why is the `resource` in list related components read from `ResourceContext` instead of `ListContext` if `ListContext` provides `resource` as well?
Wouldn it make more sense to read the `resource` from `ListContext` when in list related components?
`ListBase` provides both Resource and ListContext at the moment anyways.
When a `ListContext` is wrapped with `ResourceContext` than it can red the `ResourceContext.resource` if none is passed but it should not require the `ResourceContext`.

**Comment by slax57** [comment]
@crtl 

> Why is the resource in list related components read from ResourceContext instead of ListContext if ListContext provides resource as well?
> Wouldn it make more sense to read the resource from ListContext when in list related components?

The only place to store the resource in a shared way is the `ResourceContext`. The `useListController` allows to override the resource for the scope of the hook only. This is supported by many RA components as well, to allow for more flexibility, but the reference place to store the resource is within the `ResourceContext`.

> From the documentation and examples it is not clear that ResourceContextProvider is required maybe this should be added for clarity.

The pointed documentation does not really cover your use case, it only describes how to access the values stored in the list context.
Your use case is more advanced and I don't think it's documented yet.
If you think it should be, you can open a feature request to discuss it, or better yet, provide a PR to share the knowledge once you have figured it out.
