### ISSUE TITLE
Query "removing" properties with null values and, when submitting a mutation, setting the previous value only to null fields

### ISSUE THREAD

**Issue by ramosht** [marmelab/react-admin#8472]
**What you were expecting:**

1. You have an edit form with at least one field filled;
2. You set this field to an empty value and submit the form;
3. On the server side, this property is processed and returned as a `null` (for being empty);
4. On the client side (again), a query is ran to get the recently updated data;
5. This query brings the recently updated value which is `null` now, and I can set `null` to the edited field (like normally happens when one set a non-null value);

**What happened instead:**

5. This query isn't returning any properties which value is `null`, even though the API is returning all other properties correctly (it's like there's some kind of sanitizing function, removing all properties that has `null` value).
6. Also, in cases where I just edited the field setting an empty value, it's also restoring the value to the previous one (it's like, in the abscense of a value, it restores to the last non-null value).
7. If I refresh the page, then it sets the value correctly.

**Steps to reproduce:**

- Have an edit form and an API that sets empty values (null or empty strings) to `null` and returns it in the query ran on "getOne" (which is run right after you successfully submit the form);
- Set the value of an input to an empty value;
- Submit it;

**Other information:**

- Our Edit form has property `queryOptions` to make some changes to the data before it's passed to the rest of the form, but the `data` that's being received by `queryOptions` is already without properties with `null` values (it's not even possible to control which properties I want to pass/remove);
- I tried to emulate it in the CodeSandbox, but it's also related to the API returning `null` values;
- I believe it's something related to 2 things mainly: the query removing properties with null values from the data and the form setting the previous value to these empty values (only to the empty values);

The payload I just sent, setting "priority" to ""
![image](https://user-images.githubusercontent.com/18227099/205651625-a531de59-50ba-4c4b-ab30-1e755709f401.png)

The returned value, which is corrected and persisted in the DB:
![image](https://user-images.githubusercontent.com/18227099/205651529-18c2e7e6-7274-4a30-97fd-ddd660baf925.png)

Having a `queryOptions` property on my Edit component, I got the returned value from the query, which already get this "sanitized" data (without the null values). This is the data I'm getting:
![image](https://user-images.githubusercontent.com/18227099/205651296-6a2bc187-ac69-42b4-adb1-f7be5502b580.png)

A clip I made showing the occurence:

https://user-images.githubusercontent.com/18227099/205849488-812624d5-4779-4511-9cb9-ccc0a4cd8a3d.mov

**Environment**

- React-admin version: 4.3.2
- React version: 18.2.0
- Browser: Chrome

**Comment by ramosht** [comment]
Hi,

Thanks for the reply. Right, I will take another look over it and try to create a minimalistic project to replicate it.

**Comment by fzaninotto** [comment]
No news for some time, closing
