### ISSUE TITLE
RaStore.[resource].listParams storage brings buggy experience

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#8483]
**Report:**

1. Sometime I refer to a list page with filters in the URL that are not implemented as filter inputs (for example with an array of record ids to show a very specific list of records). In this case, users have no way to remove the filter, even when they remove the parameters in the URL. This can create heart attack to developers thinking the database has been somehow emptied (true story, I was enable to work for at least 1 hour after this emotional rollercoaster)
2. When I am developing, the shape & list of filters is changing. I get unexpected bugs because the saved value shape is not consistent with the currently implemented filter. I loose time trying to understand what happen. For example at first my filter looked like: `<QuickFilter source='type' defaultValue={{$nin: ['a', 'b', 'c']}} />`. Then it became `<SelectArrayInput source='type' />`. The latest threw a cryptical error due to the fact the received value was not an array.

**Expected behavior:**

1. Removing filter in URL removes filters in storage
2. Disable storage when NODE_ENV !== 'production' (I would understand this is not acceptable for iso-production) so an alternative would be to somehow check filter shape consistency and clear storage in case of inconsistency.

**Environment**

* React-admin version: 4.6

**Comment by fzaninotto** [comment]
The filter state stored in the URL and store is for filters that users can act upon. 

If you need to implement a filter on the list that users can't override, use the `<List filter>` prop.

So I don't see what you report as a bug. But I'm waiting for other opinions on the matter.

**Comment by nicgirault** [comment]
Thanks for your reply. What if this filter is not hard codable? I want to be able to create a link on the list page with specific record ids but users never filter by record id otherwise so adding a filter for this field is not necessary.

**Comment by fzaninotto** [comment]
That's a "how to" question, I advise you to ask it on stackOverflow or on the Discord server - this issue tracker is only for bugs. 

If you need urgent help, please consider the Professional Services, part of [react-admin Enterprise Edition](https://marmelab.com/ra-enterprise/).

**Comment by nicgirault** [comment]
I am not in urgent need for a fix and I understand it's not a high priority bug but I really think there is a bug here: if it is not allowed to filter in the URL with a filter that is not displayable, then react-admin should prevent doing so. Right now when you do so, it puts the app in a buggy state. I have fixed this bug in my app but with a lot of tricks that I would not expect to have to write.

**Comment by fzaninotto** [comment]
React-admin does its best to support the features it documents. As for not breaking when using unsupported features, we don't consider it a bug.
