### ISSUE TITLE
react-hook-form hooks do not work with Electron + Webpack

### ISSUE THREAD

**Issue by qwyt** [marmelab/react-admin#8484]
**What you were expecting/What happened instead:**

[useWatch](https://react-hook-form.com/api/usewatch) (and other hooks like useFormContext etc.) fails with:

`Cannot read properties of null (reading 'control')
Cannot read properties of null (reading 'control')
 `

when used in an app created with [Electron Forge](https://www.electronforge.io/templates/typescript-+-webpack-template).

It looks similar to https://github.com/marmelab/react-admin/issues/7501 which seems to caused by having multiple versions of 'react-hook-form'. However there is only a single version in my project's in `node_modules` so I assume it's something else, possibly related to my Webpack config and/or Electron Forge.

**Related code:**

```
const UseWatchComponent = (props: any) => {
    const title = useWatch({name: "title"});
    return <React.Fragment>
        {title}
        <TextInput source="title"/>
    </React.Fragment>
}
export const PostCreate = () => {
    return <Create>
        <SimpleForm>
            <UseWatchComponent/>
        </SimpleForm>
    </Create>
}

```

**Steps to reproduce:**

I've made a sample project according to:
- https://www.electronforge.io/templates/typescript-+-webpack-template
- https://marmelab.com/react-admin/Tutorial.html
- https://marmelab.com/react-admin/Inputs.html

https://github.com/qwyt/repro-project-ra-hooks-issue

Steps:

-  `yarn install`
-  `yarn start`
-  click the button in the bottom right
-  observe the error (`"Cannot read properties of null (reading 'control')"`)

**Other information:**
There are multiple other issues with describing this problem:
- https://github.com/marmelab/react-admin/issues/7501 
- https://github.com/marmelab/react-admin/issues/8464 
- https://github.com/marmelab/react-admin/issues/8289 
- https://github.com/marmelab/react-admin/issues/7749 (not sure) 

None of them seem to have a solution (besides removing additional versions of 'react-hook-form' from the project which is not applicable in this case).

**Environment**

* React-admin version: 4.6.0
* Last version that did not exhibit the issue (if applicable): 
* React version: 18.2
* Browser: Electron 22.0.0/Chromium 108.0.5359.62
* Stack trace (in case of a JS error):

**Comment by qwyt** [comment]
@fzaninotto Hi, thank you for your reply. I filled this out as a bug report and not a support question. 

Obviously it's lacking in detail at this point since I haven't yet figured out what exactly in my config is actually causing this. However since multiple other people have run into a similar/identical issue under different circumstances wouldn't this imply that this might be a bug or at least something that might be worth looking into? (if so I'm willing to try to investigate this further)

**Comment by fzaninotto** [comment]
All the other issues are closed. We don't reproduce this problem in our tests and in existing apps. 

If you want us to reopen it, please fork the simple example Codesandbox and tweak it until you manage to produce the bug. Until then, I'll consider it a configuration problem on your side.
