### ISSUE TITLE
SelectArrayInput label is crossed by topBorder of the input

### ISSUE THREAD

**Issue by JasonStrazisar** [marmelab/react-admin#8498]
**What you were expecting:**
I want the SelectArrayInput design to be the same as the SelectInput: 
![SelectInput](https://user-images.githubusercontent.com/59898438/207277758-fb139ad6-d0f8-4d7d-bed8-21f4a1a43af8.png)

**What happened instead:**
The top border of the SelectArrayInput cross the InputLabel: 
![SelectArrayInput](https://user-images.githubusercontent.com/59898438/207277939-25e4f2c0-56e3-4123-b7a1-e66d6e164fd6.png)

**Related code:**
```
  <RaReferenceArrayInput
      {...props}
      required
      source="customers"
      reference="customers"
      filter={{ ignoreCustomerFilter: true }}
      perPage={2000}
    >
      <RaSelectArrayInput optionText="name" fullWidth />
    </RaReferenceArrayInput>
```

Or simply

```
 <RaSelectArrayInput source="source" choice={[...choices]}/>
```

**Other information:**

* React-admin version: 4.6.1
* Last version that did not exhibit the issue (if applicable): 3.19
* React version: 17.0.2
* Browser: Chrome and Firefox

**Comment by slax57** [comment]
Thanks for submitting this.
This issue is currently being addressed by https://github.com/marmelab/react-admin/pull/8465

**Comment by slax57** [comment]
Fixed by https://github.com/marmelab/react-admin/pull/8705
