### ISSUE TITLE
SimpleForm + ImageUpload/FileUpload in CreateView won't submit

### ISSUE THREAD

**Issue by JonasDoe** [marmelab/react-admin#8501]
**What you were expecting:**
I've this structure:
 ```typescript
<CreateView {...controllerProps} save={_=>console.log("uploading")}>
  <SimpleForm>
    <ImageInput
      source="upload"
      minSize={1}
      >
      <ImageField source="src" />
    </ImageInput>
  </SimpleForm>
</CreateView>
```
When I click on `Save`, nothing happens/gets logged. If I set up `SimpleForm` with `<SimpleForm onSubmit={_=>console.log('submitting')}>`, then `"submitting"` is logged here.

**What happened instead:**
Nothing gets logged. I can continue to click the Save button with no effect.

**Steps to reproduce:**
I figure it's straight-forward. The props look like this
![image](https://user-images.githubusercontent.com/10669876/207297438-ed608b29-c031-4309-9f5d-a29102197416.png)

**Environment**

* React-admin version: `4.4.1` and `4.6.1`
* Last version that did not exhibit the issue (if applicable): I came from RA v3, don't know when it happend in between
* React version: `17.0.2`
* Browser: Firefox `107.0.1`

**Comment by fzaninotto** [comment]
`<CreateView>` is an internal component. We won't support any usage other than the one we need. Use it at your own risk. 

So unless you can provide a reproduction with public (and documented) components, I'll close this as "won't fix".
