### ISSUE TITLE
 Problems displaying content in editors when first loading an Edit component

### ISSUE THREAD

**Issue by a-skrynnikov** [marmelab/react-admin#8503]
Good afternoon!
I have the following problem - in version 4.0.1 of the application, when you first enter the Edit component in any editors (including RichTextInput), the component is not displayed, when the page is reloaded, the content appears.
I will be grateful for the answer!

**Comment by fzaninotto** [comment]
Please follow the [issue template](https://github.com/marmelab/react-admin/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).

**Comment by fzaninotto** [comment]
No news for some time, closing.
