### ISSUE TITLE
Not following MUI's theme value name on Notification

### ISSUE THREAD

**Issue by Seojun-Park** [marmelab/react-admin#8510]
### Summary

`<Notification />` uses `MUI`'s `<SnackBar />` component and overrides style according to type of notification(`success, error, warning, undo...etc`).

`StyledSnackbar` uses MUI's `error` palette on both case, `error(error.dark)` and `warning(error.light)`.

- react-admin
https://github.com/marmelab/react-admin/blob/be726d6ec2b8c87ff6b0c515d822b513073a21c0/packages/ra-ui-materialui/src/layout/Notification.tsx#L136-L156

But, there is warning palette on MUI`'s default palette. (please refer the below screenshot, or [link](https://mui.com/material-ui/customization/palette/#default-values))

- MUI
![image](https://user-images.githubusercontent.com/47709344/208071895-4c123e2f-146a-4175-aa48-11fa487c9589.png)

Is there any reason that not using `warning` value from `MUI`'s default palette?

**Comment by slax57** [comment]
Thanks for submitting this.
I don't think it's intended, so indeed it might be better to change the warning notification to use the 'warning' palette color.

Would you like to submit a PR to change this?

**Comment by Seojun-Park** [comment]
@slax57 Of course

I will make PR :)
