### ISSUE TITLE
Hardcoded size value for SelectArrayInput

### ISSUE THREAD

**Issue by amilosmanli** [marmelab/react-admin#8515]
**What you were expecting:**
`SelectArrayInput` to honor defaultProps set for MuiSelect component

**What happened instead:**
`SelectArrayInput` has a hardcoded size prop that is not possible to override

**Steps to reproduce:**
add following to the `components` sections of the theme
```
MuiSelect: {
      defaultProps: {
        variant: 'outlined',
        size: 'medium',
      },
    },
```

**Related code:**
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/SelectArrayInput.tsx#L295

**Other information:**

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: 
* Browser:
* Stack trace (in case of a JS error):

**Comment by septentrion-730n** [comment]
Thanks for your feedback.
We would gladly welcome a PR from the community for this bugfix!
