### ISSUE TITLE
CustomMenu not being rendered

### ISSUE THREAD

**Issue by the133448** [marmelab/react-admin#8516]
**What you were expecting:**
Using the Custom Menu, only the resources that I define are listed under the Menu

**What happened instead:**
The custom menu is not being rendered.

**Steps to reproduce:**

CodeSandbox link
https://codesandbox.io/s/ecstatic-shape-bt2qwu?file=/src/Layout.tsx
Menu is created as
```
const CustomMenu = () => {
  return (
    <Menu>
      <Menu.ResourceItem name="posts" />
      <Menu.Item to="/custom-route" primaryText="Miscellaneous" />
    </Menu>
  );
};
```
And passed to the Layout
```
    <Layout appBar={MyAppBar} menu={CustomMenu}  {...props}  />
```

**Other information:**

Implemented as followed here: https://marmelab.com/react-admin/Menu.html

**Environment**

* React-admin version: 4.6.2
* Last version that did not exhibit the issue (if applicable): Not sure
* React version: 17
* Browser: Google Chrome | 108.0.5359.124 (Official Build) (64-bit) (cohort: 108_Ramp_up_124)

**Comment by septentrion-730n** [comment]
Hi,

You are overwriting your props by default settings. Try the following : 
```tsx
<Layout {...props} appBar={MyAppBar} menu={CustomMenu} />
```
Have a good day.
