### ISSUE TITLE
Ability to add a placeholder for SelectInput

### ISSUE THREAD

**Issue by lauri865** [marmelab/react-admin#8529]
Would like to be able to add a placeholder (or display emptyText) for the SelectInput component.

Currently it just displays an empty field, and I can't find a way around that via props (please correct me if there's a way, I scanned through the source code, but couldn't).

The default MUI Select component allows to displayEmpty and override the renderValue prop to display a placeholder.

**Comment by slax57** [comment]
I don't believe MUI supports a placeholder on single Select.
See:
- https://github.com/mui/material-ui/issues/11069
- https://github.com/mui/material-ui/pull/8875

[It is supported with **multiple** Select](https://mui.com/material-ui/react-select/#placeholder) however, i.e. the equivalent of `SelectArrayInput`, but still requires passing custom props such as `displayEmpty` and `renderValue` like you said.

In any case, this is not a feature currently supported by React-Admin, so you will need to build your own component to support it, or you can provide a PR to implement its support.
