### ISSUE TITLE
AutocompleteArrayInput along ReferenceArrayInput clears input search string on each request after at least one selected option

### ISSUE THREAD

**Issue by ise540** [marmelab/react-admin#8535]
I followed guide at https://marmelab.com/react-admin/AutocompleteArrayInput.html#using-in-a-referencearrayinput

Related code:      
```
<ReferenceArrayInput perPage={200} reference="methods" source="methods">
        <AutocompleteArrayInput
          filterToQuery={(searchText: string) => ({ name: searchText })}
          optionText="name"
        />
</ReferenceArrayInput>
```

**Steps to reproduce:** 
1. Select at least one value in AutocompleteArrayInput
2. Start typing for next value

**What you were expecting:** entered text remains after search request

**What happened instead:** after each new search request text disappears, immediately sending request with empty string, making it impossible to search for next values

<img width="137" alt="image" src="https://user-images.githubusercontent.com/92224458/209668881-eba641b2-b2db-472a-a118-8aabace7e127.png">

**Environment:** 

- react-admin: 4.6.1 (same issue on 4.6.2)
- react: 17.0.2

**Comment by amilosmanli** [comment]
@ise540 did you find a solution to this? I'm having the same problem and see you closed the issue

**Comment by serranomorante** [comment]
Same exact issue here 😪

**Comment by ise540** [comment]
@amilosmanli @serranomorante I found solution in this issue, using clearOnBlur={false} on AutocompleteArrayInput
https://github.com/marmelab/react-admin/issues/8181

**Comment by fzaninotto** [comment]
If you think there is a bug, please open a new issue and provide a reproduction.

**Comment by amilosmanli** [comment]
Yeap, `clearOnBlur={false}` fixed issues on my side too
