### ISSUE TITLE
dependent useLists on a single page

### ISSUE THREAD

**Issue by AntonOfTheWoods** [marmelab/react-admin#8536]
**What you were expecting:**
Lists created via `useList` (and their actions/bulk actions) should be independent.

**What happened instead:**
Bulk actions and selections are shared for all lists on a given page, including for any list items that have an identical id.

**Steps to reproduce:**
Go to the codesandbox, click on any of the list items from the uselist, see that you get reactions on both lists rather than just the list that was interacted with.

**Related code:**

https://codesandbox.io/s/kind-panka-mzlf4j?file=/src/comments/CommentShow.tsx
https://mzlf4j.sse.codesandbox.io/#/comments/1/show

**Environment**

* React-admin version: 4.6.2
* React version: 17
* Browser: Chrome

**Comment by djhi** [comment]
Indeed, that's a bug. `useList` should accept a `storeKey` to allow customizing the `useRecordSelection` storeKey (derive from it maybe). Thanks for the report!

**Comment by slax57** [comment]
@djhi I disagree. According to [the docs](https://marmelab.com/react-admin/List.html#storekey) this is a design choice:

> **Note:** Please note that selection state will remain linked to a resource-based key as described [here](https://marmelab.com/react-admin/List.html#disablesyncwithlocation).

And in the linked section:

> Please note that the selection state is not synced in the URL but in a global store using the resource as key. Thus, all lists in the page using the same resource will share the same selection state. This is a design choice because if row selection is not tied to a resource, then when a user deletes a record it may remain selected without any ability to unselect it. If you want the selection state to be local, you will have to implement your own useListController hook and pass a custom key to the useRecordSelection hook. You will then need to implement your own DeleteButton and BulkDeleteButton to manually unselect rows when deleting records.

**Comment by AntonOfTheWoods** [comment]
@slax57 and @fzaninotto , I'm confused. The docs mention "Thus, all lists in the page using the same *resource* will share the same selection state.". I definitely understand that, and obviously re-read that specific part of the docs several times before submitting a bug report. What I don't understand is how that relates to `useList`, which *doesn't* have a `resource`. If, for example, I put `grapes` in my first list and `apples` in my second, they are still joined, whether or not I have anything called `grapes` or `apples` that is known to `react-admin`. If I have two lists using `useListController` that use different `resources` (i.e, things that are known to react-admin), it works fine.

Or does everything that is created using `useList` automatically belong to the "null resource" somehow? If so, I personally think it would be good to document that (and can submit a docs PR if you think it justified).

And thanks for all the awesome work on `react-admin`!

**Comment by fzaninotto** [comment]
Hi Anton,

`useList` does accept a `resource` prop, see https://github.com/marmelab/react-admin/blob/9884b6843563f00a9e5fad00f1e41e8f32f6995c/packages/ra-core/src/controller/list/useList.ts#L266-L277

By default, `useList` reads the resource from the `ResourceContext`, but you can override it by passing a `resource` prop. This value is only used to forge the selection storage key, so you can basically use it to have separate selections on the same page. But, as said above, use it at your own risk, as a BulkDelete won't be able to unselect the rows, resulting in a "phantom" selection.
