### ISSUE TITLE
queryClient.invalidateQueries doesn't work when used with useQuery

### ISSUE THREAD

**Issue by osseonews** [marmelab/react-admin#8544]
**What you were expecting:**
React query has the following functionality: queryClient.invalidateQueries to invalidate and refetch queries. When using useQuery in React-Admin for a custom querying of the backend, per the docs here: https://marmelab.com/react-admin/Actions.html#usequery-and-usemutation - we expect that we can also import useQueryClient and then be able to invalidate the query by doing something like this: 
```
const queryClient = useQueryClient()
queryClient.invalidateQueries('todos')
```

**What happened instead:**
queryClient.invalidateQueries doesn't do anything in React-Admin if used with a custom query per the docs. The query is not invalidated. 

**Steps to reproduce:**
Use the example of useQuery from the docs, change some data, and then try to invalidate it per the invalidateQueries docs.

**Related code:**
1. I have noticed that React-admin has a useRefresh hook for the dataprovider, but this invalidates all queries. The idea is that we don't want to invalidate all queries, only the ones placed in the invalidatequeries function. 

2. To use invalidateQueries in the manner above, do we need to actually attached queryClient to the Admin provider, per the docs here: https://marmelab.com/react-admin/Caching.html#application-cache - if so, this is also not so useful as we are not trying to create a global value here. Just invalidate certain queries.

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. 

React-admin does an extensive use of the invalidateQueries feature, e.g. in https://github.com/marmelab/react-admin/blob/29f658d43ec4324d7decc20764733afc5137819d/packages/ra-core/src/dataProvider/useDelete.ts#L251-L254

So in our end, it works fine. The trick is often to use the right query key. 

If you found a particular way to trigger a bug, please build a reproduction based on the simple example codesandbox so that we can investigate.

**Comment by osseonews** [comment]
Right yeah, it works for the regular core dataprovider method hooks functionality, e.g. useGetOne, useDelete. however, if you query the API using useQuery, https://marmelab.com/react-admin/Actions.html#usequery-and-usemutation, it doesn't work for some reason. We have verified the key many times.

**Comment by fzaninotto** [comment]
Then please attach a reproduction.

**Comment by osseonews** [comment]
yeah, sorry, unfortunately, I am not familiar with codesandbox. The reproduction is to just use your example from the docs for usequery and usemutation, and then try to invalidate it using :  const queryClient = useQueryClient() and queryClient.invalidateQueries('THEKEY'). It won't work. My guess is that maybe the Admin provider is passing some other useQueryClient which conflicts, in some way, with the ability to call this directly in the code. But, i don't really know, of course. Haven't looked this deeply yet. Just know it doesn't work despite repeated attempts to use inside React-Admin (and we can use React Query separately and get it to work). 

Sorry, if I can't be more helpful with reporting this. I'll try to look at the code and post some basic code here.

**Comment by osseonews** [comment]
BTW, I got this to work, by calling the invalidateQueries in the OnSuccess of a useMutation. That pattern seems to work fine in React-Admin when using a custom dataprovider method.
