### ISSUE TITLE
Extended AutocompleteInput with useChoicesContext and optionText clears itself and flickers

### ISSUE THREAD

**Issue by harastaivan** [marmelab/react-admin#8545]
**What you were expecting:**

Input should behave like normal `AutocompleteInput`. Same as without using `useChoicesContext`, options don't flicker, input doesn't clear itself after network call.

**What happened instead:**
After network call is made to `ReferenceInput`'s `reference`, the input clears, the dropdown show previous options and then flickers the filtered options.

**Steps to reproduce:**
Go to any `PostEdit`, first input is `Test users`, type in something, then the flickering and input text clear happen.

**Related code:**
https://stackblitz.com/edit/github-jnpt6d?file=src%2Fposts%2FUserReferenceInput.tsx,src%2Fposts%2FPostEdit.tsx,src%2Fposts%2FUserAutocompleteInput.tsx

Go to any `src/posts/PostEdit.tsx`, first input is

```jsx
<ArrayInput source="test_users" fullWidth>
  <SimpleFormIterator inline>
    <UserReferenceInput />
  </SimpleFormIterator>
</ArrayInput>
```

inside `UserReferenceInput` there is `UserAutocompleteInput` which reproduces the issue.

The bug is reproducible when `UserAutocompleteInput` uses both:
- `useChoicesContext` to somehow read the choices
- `optionText`, `inputText` and `matchSuggestion` functionality.

I tried passing all the props or forwarding the ref which didn't help.

**Environment:**

- React-admin version: 4.6.2
- React version: 17.0.2
- Browser: Chrome 108

**Comment by djhi** [comment]
Can you share a bit more about what you're trying to achieve? I fail to understand why you would call `useChoicesContext` without using any of the values it returns

**Comment by fzaninotto** [comment]
No news for some time, closing.
