### ISSUE TITLE
DateTimeInput doesn't accept full ISO strings

### ISSUE THREAD

**Issue by dalen** [marmelab/react-admin#8548]
**What you were expecting:**

The documentation for DateTimeInput says that it wants strings in the ISO 8601 format, therefore I expected Date.prototype.toISOString()` to work with it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

**What happened instead:**

When using `.toISOString()` output (in google chrome) I get this error message in the console:

```
The specified value "2021-04-09T10:00:00.000Z" does not conform to the required format.  The format is "yyyy-MM-ddThh:mm" followed by optional ":ss" or ":ss.SSS".
```

**Steps to reproduce:**

**Related code:**

The API field is a Unix timestamp, so I tried using this:

```js
      <DateTimeInput
        source="start"
        format={(v) => new Date(v * 1000).toISOString()}
        parse={(v) => Math.floor(new Date(v).getTime() / 1000)}
      />
```

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.6.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Google Chrome 108.0.5359.125
* Stack trace (in case of a JS error):

**Comment by dalen** [comment]
This works as a workaround of course:

```js
      <DateTimeInput
        source="start"
        format={(v) => new Date(v * 1000).toISOString().slice(0, -1)}
        parse={(v) => Math.floor(new Date(v).getTime() / 1000)}
      />
```

But still a bug worth fixing IMHO

**Comment by slax57** [comment]
Thanks for submitting this issue.

Internally, `DateTimeInput` simply renders an `<input type="datetime-local">`, which is where the error comes from (you can test it live [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)).

But you are right about the fact that the doc is wrong about the expected format. PR incoming.
