### ISSUE TITLE
enableGetChoices={({ q }) => q.length >= 2} error: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by diegocgaona** [marmelab/react-admin#8554]
**What you were expecting:**
Get the choices after type 2 or more characters

**What happened instead:**
An error which cannot get my page rendered:

**Steps to reproduce:**
Tried like the docs said. I tried to isolate in the form only the `ReferenceArrayInput `(the error occur too with `ReferenceInput`) and the error still the same.

**Related code:**
```
                    <ReferenceArrayInput source="type_ids" label="Tipos do trabalho" reference="job_type"
                        filterToQuery={searchText => ({ name: searchText })}
                        enableGetChoices={({ q }) => q.length >= 2}
                        perPage={100} >
                        <AutocompleteArrayInput optionText="name" />
                    </ReferenceArrayInput>
```

* Preferably, a CodeSandbox forked from 
[  - https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple (v4)](https://codesandbox.io/s/late-silence-lh4uk9?file=/src/posts/TagReferenceInput.tsx)
My only change to the repo is in line 49:` enableGetChoices={({ q }) => q.length >= 2}`

When I changed, the error appears:
![image](https://user-images.githubusercontent.com/9142126/210883095-c3eecee1-7232-4d53-9c01-2a331db3bb43.png)

```
`enableGetChoices={({ q }) => q.length >= 2}`
```

**Other information:**
I was upgrading from V3 to V4. It is the only error occurring now.

**Environment**

* React-admin version: 4.6.3 (I tried 4.6.0, 4.6.1, 4.6.2 with the same result)
* Last version that did not exhibit the issue (if applicable): Last version of V3
* React version: 18.0.0
* Browser: Chrome (last version)
* Stack trace (in case of a JS error):
```
JobsCreate.js:89 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at enableGetChoices (JobsCreate.js:89:1)
    at useReferenceArrayInputController (useReferenceArrayInputController.ts:87:1)
    at ReferenceArrayInput (ReferenceArrayInput.tsx:88:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at updateFunctionComponent (react-dom.development.js:20313:1)
    at beginWork (react-dom.development.js:22356:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at beginWork$1 (react-dom.development.js:27243:1)
```
![image](https://user-images.githubusercontent.com/9142126/210847464-45be2983-8f29-4eb0-87cc-856e8cea243e.png)

**Comment by slax57** [comment]
Thanks for submitting this issue.
You are correct, the code sample should be `enableGetChoices={({ q }) => q?.length >= 2}` (in TS).
Also, the tag input is broken in PostEdit.
I'll fix that along with the docs.

**Comment by diegocgaona** [comment]
@slax57 Thanks, I tried your change `enableGetChoices={({ q }) => q?.length >= 2}` (but, I'm using .js) and I do not have the error anymore.
But, it is not working as expected.
When click in the text field, it shows "no options". After I use 2 or more characters, it shows the options, but all of it, even if I write anything.
I record a video to show this behavior: [Video link](https://www.awesomescreenshot.com/video/13788338?key=eaf3f7243e914efc8320298437769d67)

This is a video of the expected behavior (from my React-Admin V3): [video link](https://www.awesomescreenshot.com/video/13788483?key=1b6e86d2f6f5bb4ff3a6f43144c2cf58)

This is the snippet code I'm using:
                   ```
 <ReferenceArrayInput source="type_ids" label="Tipos do trabalho" reference="job_type"
                        filterToQuery={searchText => ({ name: searchText })}
                        enableGetChoices={({ q }) => q?.length >= 2}
                        perPage={100} >
                        <AutocompleteArrayInput optionText="name" />
                    </ReferenceArrayInput>
                    <ReferenceInput label="Nome do cliente" source="client_id" reference="clients"
                        filterToQuery={searchText => ({ name: searchText })}
                        enableGetChoices={({ q }) => q?.length >= 2}
                        filter={{ status: true }}
                    >
                        <AutocompleteInput optionText="name" />
                    </ReferenceInput>
```

**Comment by slax57** [comment]
@diegocgaona 
When working on the fix I tested my solution successfully in the simple demo of react-admin.
If you think you have found another issue, could you please provide a reproduction case based on this simple demo (either on [codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or [stackblitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple))?
Thanks

**Comment by diegocgaona** [comment]
@slax57 
Now in the comment create (the second box, after Post) is to select related posts (I modified line 28 and after).
The behavior before using `enableGetChoices={({ q }) => q?.length >= 2}` is OK, but when I put it, after click in the box, appears "No options" (where would show all the options).

Some other strange behaviors:

- if I input "acc" it shows titles without "acc".
- After the first input, it I deselect and select it again, it show all the options. (and if I try to put "acc" again, it does not filter)
- If I put something that does not exist (like: "accs"), if correctly shows "no options"
- If I put "Fusce" (the title of the first post option) it works correctly and filter showing only the correct post. (it seems to work fine only with the first post)


Video showing the behavior:
https://www.awesomescreenshot.com/video/13790676?key=0590395c186b8fb2ff268dce58a4927c

The sandbox:
https://codesandbox.io/s/late-silence-lh4uk9?file=/src/comments/CommentCreate.tsx

Thanks!!

**Comment by slax57** [comment]
@diegocgaona 

- _but when I put it, after click in the box, appears "No options" (where would show all the options)_ => That's the purpose of this prop, unless I don't get what you're saying
- _if I input "acc" it shows titles without "acc"_ => That's because you customized the `filterToQuery` at the wrong place. This prop should be on the `AutocompleteInput`. See [Customizing The Filter Query](https://marmelab.com/react-admin/ReferenceInput.html#customizing-the-filter-query).
- _After the first input, it I deselect and select it again, it show all the options_ => I don't reproduce
- _If I put "Fusce" (the title of the first post option) it works correctly and filter showing only the correct post. (it seems to work fine only with the first post)_ => That's linked to the issue with `filterToQuery`

Please note that if you customize the `filterToQuery` to filter on `title` instead of `q`, you will have to update the `enableGetChoices` prop as well:

```diff
- enableGetChoices={({ q }) => q?.length >= 2}
+ enableGetChoices={({ title }) => title?.length >= 2}
```

**Comment by slax57** [comment]
@diegocgaona No problem. I'm glad I could help :slightly_smiling_face:
