### ISSUE TITLE
Module '"react-admin"' has no exported member 'ReferenceManyCount'

### ISSUE THREAD

**Issue by idesignpixels** [marmelab/react-admin#8560]
![Screenshot 2023-01-09 at 11 50 52](https://user-images.githubusercontent.com/12501597/211302350-f86c3774-5126-4156-8b81-bfc353f03aa9.png)

**What you were expecting:**
ReferenceManyCount to be an available import from `react-admin` package

**What happened instead:**
`Module '"react-admin"' has no exported member 'ReferenceManyCount'`

**Steps to reproduce:**
install react admin `4.6.1` and try to import `ReferenceManyCount` component.

**Environment**

* React-admin version: 4.6.1
* React version: 18.2.0
* Browser: chrome 107.0.5304.110

**Comment by idesignpixels** [comment]
Seems to be fixed in 4.7.0, will close so other might reference if they have the same issue.

**Comment by fzaninotto** [comment]
It's not "fixed" in 4.7, this component was introduced in 4.7. 

https://github.com/marmelab/react-admin/releases/tag/v4.7.0

Please make sure you always browse the version of the documentation corresponding to your installed version.
