### ISSUE TITLE
Remove all filters action is removing my default filters

### ISSUE THREAD

**Issue by oguhpereira** [marmelab/react-admin#8564]
**Is your feature request related to a problem? Please describe.**
I am not able to use the filterbutton well in some areas that already contain a default filter and that this filter should always be used.

Exemple:
- Category listing for a given post always filters by default the post id. By removing all filters I also remove this filter.

**Describe the solution you'd like**
I see 2 possibilities here, one would be for it not to remove defaultFilters, another would be for the control with filterbutton not to display this remove all filters

**Describe alternatives you've considered**
As a faster action if it makes sense maybe give the filter button the possibility to hide remove all the filter as it was done with disable savequery

**Additional context**
I can help with the implementation if you want

**Comment by septentrion-730n** [comment]
Hi Gustavo,

Could you provide a behaviour reproduction sandbox such as a CodeSandbox forked from [simple example V4](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) ? Thanks for your feedback!

**Comment by oguhpereira** [comment]
I was able to reproduce here and it looks like the behavior has been resolved.

Now just using the defaultFilter that is being removed, if you use the filters it is not removing it.
