### ISSUE TITLE
Using Form outside of Admin Context: TypeError: Cannot read properties of null (reading 'navigator')

### ISSUE THREAD

**Issue by osseonews** [marmelab/react-admin#8566]
We are trying to use React-Admin form components outside the admin context, as the components are simply amazing and we want to use them throughout our Nextjs app, not just in the react-admin portion. However, when we try to run the Form components outside of the admin context, we get the error: TypeError: Cannot read properties of null (reading 'navigator'). Our code is basically as per below. Any ideas? Seems to be some issue with useWarnWhenUnsavedChanges? I couldn't find any other place in the core code where navigator is used.

```
import { Layout } from '@components/common'
import { Container } from '@components/ui'
import {
  TextInput,  
  required,
  email,
  Form
} from 'react-admin'
import { Grid } from '@mui/material'


export default function Orders() {
  const validateEmail = [required(), email()]
  const initialAddressFormValues: any = {
    email: '',
    first_name: '',
    last_name: '',
    company: '',
  }
  const postSave = async (data: any) => {
    console.log('data', data)
    
  }
  
  return (
    <Container className="pt-4">
     
      <div className="flex-1 p-24 flex flex-col justify-center items-center ">
       
        <Form
      record={initialAddressFormValues}
      defaultValues={initialAddressFormValues}
      onSubmit={postSave}
      sanitizeEmptyValues //this makes all blank form entries into null values, see https://marmelab.com/react-admin/Form.html#sanitizeemptyvalues
    >
      <Grid container spacing={2}>
      <Grid item xs={12}>
        <TextInput
          resettable
          variant="outlined"
          source="email"
          helperText="Please make sure you type your email in correctly. If you do not, you will not get any order emails."
          validate={validateEmail}
          fullWidth
        />
      </Grid>
      <Grid item xs={12} sm={6}>
        <TextInput
          resettable
          variant="outlined"
          source="first_name"
          fullWidth
        />
      </Grid>
      <Grid item xs={12} sm={6}>
        <TextInput resettable variant="outlined" source="last_name" fullWidth />
      </Grid>
      <Grid item xs={12}>
        <TextInput resettable variant="outlined" source="company" fullWidth />
      </Grid>
      </Grid>
    </Form>
      </div>
    </Container>
  )
}

Orders.Layout = Layout

```

**Comment by djhi** [comment]
Hi and thanks for the kind words.

Our components are meant to be used inside React-Admin context. In this particular case, it needs a context provided by react-router. We do not plan to make those components usable outside react-admin but feel free to copy them and adapt their code.

**Comment by osseonews** [comment]
I think you are missing a big business opportunity to not allow the components to be used outside of React-Admin. You can charge $25/Month for a version that allows this and you would probably get a ton of sign ups. Creating forms in React remains a terrible experience, but you guys solved that. Unfortunately, often there is no need for a full fledged React-Admin app, and you just need the Low Code react-admin form components.  B/c having to just reinvent the wheel by creating your own Hook Form components is just a waste of time. Incidentally, I also think you would make alot more $ by lowering the price of the enterprise, by say limiting the number of enterprise components at certain levels. So say for $50/Month you get your choice of 3 enterprise components, $100 gets you more etc.  Thanks for considering.

**Comment by fzaninotto** [comment]
Hi Shlomo,

Thanks for your kind words and your suggestion. You seem very good at business. If you can find 10 customers willing to pay $25 per month for the ability to use our Form component outside of react-admin, we'll develop it. Deal?

As for lowering the price of the Enterprise Edition, that would simply mean getting much more customers to get the same revenue. We're not so good at marketing, so we prefer to stay with the current pricing, which is enough to have a sustainable open-source project.

As a side note, we're not looking to make a lot more $. Being paid correctly to do what we love without the pressure of constant growth is a luxury, and we're glad to enjoy it.
