### ISSUE TITLE
Custom redirect is not taken into account on delete action in EditView

### ISSUE THREAD

**Issue by adrien-may** [marmelab/react-admin#8570]
**What you were expecting:**
When using : 

```typescript
<Edit
      {...props}
      resource="myResource"
      redirect={'/customRedirection/because/I/can'}
    >
```

The action bar at the bottom displays a "save" button and a delete button.
The save button redirects to "/customRedirection/because/I/can". I'm expecting the redirection to be the same on the delete button.

**What happened instead:**
Instead I'm redirected to the list page

**Environment**

* React-admin version: 4.6.3

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by adrien-may** [comment]
https://codesandbox.io/s/quizzical-chatterjee-70zllr?file=/src/tags/TagEdit.tsx

On the "tags" edit form, I changed the `redirect` prop from "list" to "users/1". This works correctly for edition. It redirects nicely to "/users/1" (page not found but whatever, that's not my point).

On the edit page, if I try to delete the item, I'm expecting to be redirected to `"/users/1"` as well. I'm redirected as if I let `"list"` in the `redirect` prop.

Is that more clear now ?

**Comment by djhi** [comment]
Indeed but that's not a bug. It's designed that way. To customize the delete side effects, you must provide your own [`actions`](https://marmelab.com/react-admin/Edit.html#actions) and `DeleteButton` on which you can provide the `redirect` prop as well
