### ISSUE TITLE
Using square brackets in the source description of list filters prevents their hiding/removal

### ISSUE THREAD

**Issue by poe42** [marmelab/react-admin#8572]
We are using DateTimeInputs for aggregating our custom date range filters. Therefore we use Api-Platform's [Date Filter](https://api-platform.com/docs/core/filters/#date-filter), like `before` and `after`, as in:
```
<DateTimeInput source="issuingDate[after]" resettable />
<DateTimeInput source="issuingDate[before]" resettable />
```

The filtering works like a charm (and no additional tweaking of the dataProvider is needed) but the removing/hiding of those filters fails. In this regard, the usage of _square brackets_ leads to some unexpected behaviors. 

**What you were expecting:**
After adding a filter, that uses _square brackets_ in its source description, and successfully filtering a list, this filter should be removed again, when clicking the filter's _hide_ button.

**What happened instead:**

a) Precondition: The filter is dirty (inputs were already made) -> When clicking on the filter's hide button, the according filter does **not** get removed -> Unexpected!
b) Precondition: The filter is dirty (inputs were already made) -> When clicking on the filter's **reset** button on the right, the according filter gets removed -> Unexpected!
c) Precondition: The filter was initiated but no user inputs were made -> When clicking on the filter's hide button, the according filter gets removed -> OK

**Steps to reproduce:**
At Example Simple (v4) go to [PostList](https://codesandbox.io/s/thirsty-newton-mv4n8n?file=/src/posts/PostList.tsx) and add the filter "Published before". Try removing the filter:
a) click _hide_ after setting a date
b) click _reset_ after setting a date
c) click _hide_ right after filter init

**Environment**
* React-admin version: v4
* Browser: firefox, chrome

**Comment by yanchesky** [comment]
It's very likely that I've found the source of the problem. The function `hideFilter` does not properly clear the filter value. That's why when the input is empty hiding works fine. 
I will make a PR soon to solve that issue if nobody minds 😊

**Comment by djhi** [comment]
Thanks for the report. We would gladly accept a pull request!

**Comment by fzaninotto** [comment]
There is something I don't understand. In your codesandbox, the filter that is sent to the API is not 

`{ 'published_at[before]': value }`,

it's

`{ published_at: { before: value } }`

and it is not what your API expects, right?

So you must be some kind of transformation in your API provider to turn the filter to the square bracket syntax. And if this is the case, why can't you use the dot notation in your filter, i.e. `published_at.before`?

**Comment by fzaninotto** [comment]
This "bug" doesn't seem to appear in real use cases, so we won't "fix" it. Thanks for the report anyway.
