### ISSUE TITLE
Problem with ra-cognito

### ISSUE THREAD

**Issue by eduardondev** [marmelab/react-admin#8573]
Hello guys.

I'm trying to install the ra-cognito package for app authentication with AWS Cognito. However, I'm getting a bunch of package dependency errors that I can't resolve.

Below are the errors I'm facing.

warning " > @material-ui/core@4.12.4" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @material-ui/core@4.12.4" has incorrect peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@material-ui/core > @material-ui/styles@4.11.5" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "@material-ui/core > @material-ui/styles@4.11.5" has incorrect peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@material-ui/core > @material-ui/system@4.12.2" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "@material-ui/core > @material-ui/system@4.12.2" has incorrect peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@material-ui/core > @material-ui/utils@4.11.3" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "@material-ui/core > @material-ui/utils@4.11.3" has incorrect peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning " > aws-amplify-react-native@7.0.2" has unmet peer dependency "@react-native-picker/picker@>=1.2".
warning " > aws-amplify-react-native@7.0.2" has unmet peer dependency "graphql@15.8.0".
warning " > ra-cognito@1.0.4" has incorrect peer dependency "@material-ui/core@^1.4.0".
warning " > ra-cognito@1.0.4" has unmet peer dependency "@material-ui/icons@^3.0.1".
warning " > ra-cognito@1.0.4" has unmet peer dependency "amazon-cognito-identity-js@^3.0.3".
warning " > ra-cognito@1.0.4" has incorrect peer dependency "aws-amplify@^1.1.10".
warning " > ra-cognito@1.0.4" has unmet peer dependency "classnames@2.2.6".
warning " > ra-cognito@1.0.4" has unmet peer dependency "ra-core@^2.5.2".
warning " > ra-cognito@1.0.4" has unmet peer dependency "ra-ui-materialui@^2.5.1".
warning " > ra-cognito@1.0.4" has incorrect peer dependency "ramda@^0.25.0".
warning " > ra-cognito@1.0.4" has incorrect peer dependency "react@^16.5.0".
warning " > ra-cognito@1.0.4" has incorrect peer dependency "react-admin@^2.5.1".
warning " > ra-cognito@1.0.4" has incorrect peer dependency "react-dom@^16.5.0".
warning " > ra-cognito@1.0.4" has incorrect peer dependency "react-redux@5.0.7".
warning " > ra-cognito@1.0.4" has unmet peer dependency "recompose@0.26.0".
warning " > ra-cognito@1.0.4" has unmet peer dependency "redux-form@7.4.2".
warning "ra-data-json-server > ra-core@4.7.0" has unmet peer dependency "history@^5.1.0".
warning "ra-data-json-server > ra-core@4.7.0" has unmet peer dependency "react-hook-form@^7.40.0".
warning "ra-data-json-server > ra-core@4.7.0" has unmet peer dependency "react-router@^6.1.0".
warning "ra-data-json-server > ra-core@4.7.0" has unmet peer dependency "react-router-dom@^6.1.0".
warning "react-admin > @emotion/react > @emotion/babel-plugin@11.10.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "react-admin > @emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > react-form@4.0.1" has incorrect peer dependency "react@^16.8.3".
warning "react-native > metro-react-native-babel-transformer@0.73.5" has unmet peer dependency "@babel/core@*".
warning "react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-react-native-babel-transformer@0.73.7" has unmet peer dependency "@babel/ core@*".

** PACKAGE.JSON
"dependencies": {
    "@material-ui/core": "^4.12.4",
    "aws-amplify": "^5.0.9",
    "aws-amplify-react-native": "^7.0.2",
    "aws-sdk": "^2.1294.0",
    "prop-types": "^15.8.1",
    "ra-cognito": "^1.0.4",
    "ra-data-json-server": "^4.7.0",
    "ramda": "^0.28.0",
    "react": "^18.2.0",
    "react-admin": "^4.7.0",
    "react-dom": "^18.2.0",
    "react-form": "^4.0.1",
    "react-native": "^0.71.0",
    "react-native-web": "^0.18.10",
    "react-redux": "^8.0.5",
    "redux": "^4.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "@vitejs/plugin-react": "^3.0.0",
    "typescript": "^4.9.3",
    "vite": "^4.0.0"
  }

Can someone help me?

**Comment by djhi** [comment]
`ra-cognito` is a very old package we don't maintain. However, we recently released [`ra-auth-cognito`](https://github.com/marmelab/ra-auth-cognito).
