### ISSUE TITLE
PasswordInput hide/show Button not working

### ISSUE THREAD

**Issue by denisesenguel** [marmelab/react-admin#8575]
**What you were expecting:**
Seeing the typed password when clicking the show password icon

**What happened instead:**
Nothing, password still hidden

**Other information:**
It looks like the react-admin TextInput field does not read the `type` prop correctly (or doesn't change it when state is updated). I could fix it easily by copy-pasting the PasswordInput component code making my own custom component and moving the conditional input `type` definition to `InputProps`.

**Environment**
* React-admin version: 4.6.0
* Browser: Checked in recent Chrome and Safari versions and appeared in both

**Comment by Andrey-Bazhanov** [comment]
@denisesenguel  I had same problem. In my case it was fixed by removing `type="password"` attribute from `PasswordInput` usage
