### ISSUE TITLE
CSS class for cell (column-<column source>) has periods in it

### ISSUE THREAD

**Issue by jimjoes** [marmelab/react-admin#8578]
**What you were expecting:**
The generated class name for cells in the Datagrid used for customising specific columns shouldn't have periods in it.

**What happened instead:**
A column with source `balance.base.amount` generated a class name of `column-balance.base.amount`. afaik CSS doesn't support dots in class names, so I can't target the class.

**Steps to reproduce:**
create a datagrid with a dot notated source.
check the generated CSS class.

**Environment**
* React-admin version: 4.6
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: Chrome latest

**Comment by djhi** [comment]
Good catch! Thanks for the report

**Comment by fzaninotto** [comment]
You can target a class name with a dot by escaping the dot in your CSS:

```css
column-balance\.base\.amount {
   color: red;
}
```

See https://stackoverflow.com/questions/3447329/styling-elements-with-a-dot-in-the-class-name

The fix you suggest would be a breaking change for the developers who already use this technique, so I'm not sure we should address it.

**Comment by jimjoes** [comment]
I'll just use a css selector.

thanks!
