### ISSUE TITLE
TabbedForm tabs inside of a Fragment cause all tabs to render at once

### ISSUE THREAD

**Issue by mwmatthew10** [marmelab/react-admin#8587]
**What you were expecting:**
I should be able to pass a Fragment containing TabbedForm.Tab's and it render successfully.

**What happened instead:**
All tabs are rendered at once and shown at once. and the content of the tabs shows as the tabs label
Expected result:
![image](https://user-images.githubusercontent.com/89316325/212952510-fa277604-c74c-4c5e-bdf8-5b7a5f388225.png)
Actual Result:
![image](https://user-images.githubusercontent.com/89316325/212954189-916efd06-3e2f-4b54-926e-c3db37f27489.png)

**Steps to reproduce:**
Put the tabs in a Fragment, or have them returned by a different Element in a Fragment.

**Related code:**
Working code:
```ts
const VisitorCreate = () => (
    <Create>
        <TabbedForm>
            <TabbedForm.Tab label="hello world">
                <h1>My first tab</h1>
            </TabbedForm.Tab>
            <TabbedForm.Tab label="hello world 2">
                <h1>My second tab</h1>
            </TabbedForm.Tab>
        </TabbedForm>
    </Create>
);
```
Broken code:
```ts
const VisitorCreate = () => (
    <Create>
        <TabbedForm>
            <>
                <TabbedForm.Tab value="hello world" label="hello world">
                    <h1>My first tab</h1>
                </TabbedForm.Tab>
                <TabbedForm.Tab value="hello world 2" label="hello world 2">
                    <h1>My second tab</h1>
                </TabbedForm.Tab>
            </>
        </TabbedForm>
    </Create>
);
```

**Other information:**
I have tried using both my own codebase and the demo codebase, and it happens in both.

**Environment**

* React-admin version: 4.7.0 (latest)
* Last version that did not exhibit the issue (if applicable): Not sure, doing a big upgrade from V2 to V4
* React version: ^17.0.0 and 17.0.2
* Browser: Brave (Chromium) and Safari
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
Sorry, react-admin doesn't support this. You probably need to build a custom form layout [using the `<Form>` component](https://marmelab.com/react-admin/Form.html) rather than using `<TabbedForm>`.
