### ISSUE TITLE
react admin 407

### ISSUE THREAD

**Issue by usamatiz** [marmelab/react-admin#8589]
They give an error when we call a new table in the app.tsx which imports React Router and ReactRouterDom. After adding these packages the cms menu doesn't work on the first load when we refresh it the second time it loads. I have also attached a video

https://user-images.githubusercontent.com/121954578/213161838-45c82eaf-42ee-4bc9-8092-f0b89801203a.mp4

**Comment by fzaninotto** [comment]
Please follow the issue template.

**Comment by usamatiz** [comment]
> Please follow the issue template.
Could you please let me know where to found the issue template?

**Comment by fzaninotto** [comment]
When you opened this issue on GitHub, the textarea wasn't empty - that was the issue template. You can find it here: https://github.com/marmelab/react-admin/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by usamatiz** [comment]
> When you opened this issue on GitHub, the textarea wasn't empty - that was the issue template. You can find it here: https://github.com/marmelab/react-admin/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

could you please tell me which template issue explicitly

**Comment by fzaninotto** [comment]
No news for some time, closing.
