### ISSUE TITLE
failed to load config from C:\Users\92311\Videos\demo\vite.config.ts on run demo dev command

### ISSUE THREAD

**Issue by tauqeer-trailfive** [marmelab/react-admin#8591]
So after I cloned the repo that is [https://github.com/marmelab/react-admin/tree/master/examples/demo] and install dev dependencies with node `16.0.0` or latest version that is `18.13.0` and then I run the command `npm run dev` i got the above error in vite.config.ts. I changes the node version down to 14 from latest still the same error

`

```
C:\Users\92311\Videos\demo>npm run dev
> demo@4.0.0 dev
> vite
```
**Error**

```
failed to load config from C:\Users\92311\Videos\demo\vite.config.ts
error when starting dev server:
Error: ENOENT: no such file or directory, scandir 'C:\Users\92311\packages'
    at Object.readdirSync (node:fs:1072:3)
    at Object.<anonymous> (C:\Users\92311\Videos\demo\vite.config.ts:37:34)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object._require.extensions.<computed> [as .js] (file:///C:/Users/92311/Videos/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63154:24)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at loadConfigFromBundledFile (file:///C:/Users/92311/Videos/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63162:21)
    at loadConfigFromFile (file:///C:/Users/92311/Videos/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63020:34)
```
`

**Comment by djhi** [comment]
Please follow the issue template

**Comment by tauqeer-trailfive** [comment]
So after I cloned the repo that is [https://github.com/marmelab/react-admin/tree/master/examples/demo] and install dev dependencies with node `16.0.0` or latest version that is `18.13.0` and then I run the command `npm run dev` i got the above error in vite.config.ts. I changes the node version down to 14 from latest still the same error

**Comment by fzaninotto** [comment]
You must use the commands documented here: https://github.com/marmelab/react-admin#examples

**Comment by tauqeer-trailfive** [comment]
@fzaninotto i still getting this error. please help

**Comment by fzaninotto** [comment]
As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

Please ask your question in one of the support channels above.
