### ISSUE TITLE
Getting data for Graphs

### ISSUE THREAD

**Issue by tauqeer-trailfive** [marmelab/react-admin#8597]
is there any way to get data for graphs like we getting data for a list or update from a provider?
by default, we show them with a static array
![image](https://user-images.githubusercontent.com/108520807/214799055-e32fe745-fb7a-403f-9ae1-f280972dbd37.png).

**Comment by djhi** [comment]
Please follow the issue template

**Comment by tauqeer-trailfive** [comment]
Is there any way to get data to form the data provider for graphs?
i have to use `useQuery` hook from apollo client.

**Comment by reterXDark** [comment]
🙂
