### ISSUE TITLE
Tutorial Posts and authProvider

### ISSUE THREAD

**Issue by erikvanderwerf** [marmelab/react-admin#8606]
I think I found two minor bugs with the 4.7.2 Tutorial Page.

1. In the [Handling Relationships](https://marmelab.com/react-admin/Tutorial.html#handling-relationships) section, the "diff" references the existing `users` line, not the new `posts` line as expected.

2. In the [Adding a Login Page](https://marmelab.com/react-admin/Tutorial.html#adding-a-login-page) section, I think that the first code line should include the type of the `const authProvider`. IntelliJ WebStorm (and `npm start`) is flagging the pasted code as not declaring any types for TypeScript.

```diff
< export const authProvider = [
> import {AuthProvider} from "react-admin";
>
> export const authProvider: AuthProvider = {
```

**Steps to reproduce:**
1. ![image](https://user-images.githubusercontent.com/4553730/215416961-a3f04435-14fd-4e75-9a5a-a6de4bf54145.png)
2. ![image](https://user-images.githubusercontent.com/4553730/215417037-c98356d1-2e6f-4ae2-b7b7-877b7313446d.png)

**Environment**
Browsing the 4.7.2 Tutorial on Chrome, using the 4.7.2 code in latest IntelliJ WebStorm EAP 231.4840.391.

* React-admin version: 4.7.2
* React version: 18.2.0
* Browser: Chrome

React and TypeScript are not my strong subjects (yet!), sorry if I missed anything.

**Comment by erikvanderwerf** [comment]
apologies for dumping multiple issues into the same ticket! I can split them up if desired.

I think there's a similar problem on the [Connecting to A Real API](https://marmelab.com/react-admin/Tutorial.html#connecting-to-a-real-api) section as well, TS wants to know what the `dataProvider` object *is*.
![image](https://user-images.githubusercontent.com/4553730/215419840-75ca5322-bc7f-4fb0-97ec-48b3b9e0a0ea.png)

TypeScript is also being exceptionally picky about the possibility of null-header.

**Comment by djhi** [comment]
Thanks for the report. Mind openning pull requests to fix those?

**Comment by erikvanderwerf** [comment]
Yes I can! I did not see the `Tutorial.md` on my first search, otherwise I would have skipped this step 😀
