### ISSUE TITLE
Possibility to add label to rowsPerPageOptions prop of TablePagination component

### ISSUE THREAD

**Issue by murattishkul** [marmelab/react-admin#8609]
**Is your feature request related to a problem? Please describe.**
I need to have customizable label in rowsPerPageOptions prop of TablePagination component like in mui

**Describe the solution you'd like**
I want to change prop type of rowsPerPageOptions prop from number[] to { label: string; value: number; } | number[] like it is in mui

**Describe alternatives you've considered**
-

**Additional context**
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/38204149/215457722-1fb7c48b-d5e2-49e3-971e-333a12823ae0.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/38204149/215457769-402cf25d-ea58-4562-9708-db4fe0c39848.png">

**Comment by slax57** [comment]
This seems to be a TS issue only.
It should already be supported if you add a `// @ts-ignore` comment. Can you confirm?
Would you like to open a PR to update the TS type?

**Comment by murattishkul** [comment]
hi @slax57 , it is working with @ts-ignore indeed, however I would not like to use it 
sure, would like to make a pr

**Comment by 7twik** [comment]
I would like to work on this issue, pls assign me this issue

**Comment by fzaninotto** [comment]
We don't have a formal assignment process. Just open a PR referencing that issue, and we'll do the review ;)
