### ISSUE TITLE
Create test for SavedQuery actions is less accurate because it doesn't have good entry point

### ISSUE THREAD

**Issue by oguhpereira** [marmelab/react-admin#8613]
**Is your feature request related to a problem? Please describe.**
Today I see difficulties in being able to create tests for the save query. There are few entry points, which makes testing difficult and less accurate.

**Describe the solution you'd like**
I think you can add more input points in the filter button, dialog, input and subimit and cancel buttons so that it is easier to create test for this flow

**Describe alternatives you've considered**
You can start with just the few entry points you need to avoid adding something that isn't really used that much.

**Additional context**
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/filter/AddSavedQueryDialog.tsx
![image](https://user-images.githubusercontent.com/24482087/215756756-3b23d95d-0e53-4745-90c3-41fc5166d035.png)

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback. 

I'm not sure I understand what you mean about "entry points". Are you referring to CSS classes used to target elements in the DOM in your tests? In that case, we discourage the use of CSS classes for e2e tests, and instead we rely on text that users actually see (cf https://kentcdodds.com/blog/testing-implementation-details).

**Comment by oguhpereira** [comment]
The idea would be to use data-testid or arial-label.

**Comment by slax57** [comment]
@oguhpereira  Can you maybe give an example of what you would like to test that requires accessing specific parts of the dialog and cannot be done by querying the visible elements on the screen only?
