### ISSUE TITLE
Enable EndAdornment for SelectInput

### ISSUE THREAD

**Issue by haminem** [marmelab/react-admin#8615]
**Is your feature request related to a problem? Please describe.**
I tried to set EndAdornment on SelectInput, but it seems impossible because I can't pass clearAlwaysVisible in SelectInputProps.

**Describe the solution you'd like**
In SelectInputProps, I would like to change Omit from TextFieldProps to ResettableTextFieldProps and be able to pass clearAlwaysVisible.

**Additional context**
![image](https://user-images.githubusercontent.com/64143893/215992731-763d9e95-a7c2-40bc-a469-ce0c14910e5c.png)
↑Add line 137
![image](https://user-images.githubusercontent.com/64143893/215993051-1530a2e0-0113-4476-8f86-541845b3a3a8.png)
↑Change line 433

**Comment by slax57** [comment]
Feel free to open a pull request to suggest this change :slightly_smiling_face:

**Comment by fzaninotto** [comment]
This enhancement request didn't receive any significant contribution, and the core team won't implement it in the near future, so I'll close it. feel free to contribute a PR if you need this feature.
