### ISSUE TITLE
RaCreateButton overrides have no effect 

### ISSUE THREAD

**Issue by IAmVisco** [marmelab/react-admin#8623]
**What you were expecting:**

[The docs state](https://marmelab.com/react-admin/Buttons.html#sx-css-api) that you can should be able to override default <CreateButton> styles with `RaCreateButton` key, but doing so in the `theme` has no effect on the actual create button.

**What happened instead:**

Nothing happens to the desktop button, seems like styles apply correctly to the floating button.

**Related code:**

https://codesandbox.io/s/busy-fast-jmec82?file=/src/index.tsx

**Environment**

* React-admin version: 4.7.4
* Last version that did not exhibit the issue (if applicable):
* React version: 18.0.2
* Browser: Chrome 109
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Thanks for reporting this issue.
Indeed the styles are only applied to the FAB and not the Desktop mode button.
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/CreateButton.tsx#L45

A workaround would be to pass your own class name with the `className` prop (which is forwarded to both components).

Would you like to open a PR to attempt to fix this?

**Comment by IAmVisco** [comment]
@slax57 Sure, I can tinker with it.

**Comment by IAmVisco** [comment]
What about other buttons? Edit or Delete buttons have no ways to override them globally at all (which I would like to do in my app).

**Comment by davidhenley** [comment]
This seems to have made all of my CreateButtons and EditButtons disappear from the List actions.

**Comment by djhi** [comment]
Can you elaborate?

**Comment by IAmVisco** [comment]
> This seems to have made all of my CreateButtons and EditButtons disappear from the List actions.

I just tested and the default buttons appear just fine on my Datagrid 
![image](https://user-images.githubusercontent.com/18630605/220161695-c5ed0e52-61cf-44ff-a9ed-945d353921cb.png)

**Comment by davidhenley** [comment]
I figured it out. The latest commit to the CreateButton and EditButton
changed the way the theme worked with style overrides.

I had:

RaCreateButton: {
      styleOverrides: {
        root: {
          display: 'none'
        }
      }
    },

in my theme which only became noticed after the last commit on RA.

**Comment by davidhenley** [comment]
I figured it out. This commit to the CreateButton and EditButton changed the way the theme worked with style overrides.

I had:

RaCreateButton: {
      styleOverrides: {
        root: {
          display: 'none'
        }
      }
    },

in my theme which only became noticed after the last commit on RA.

Fixed on my side. Sorry about that.
