### ISSUE TITLE
List perPage property works incorrect

### ISSUE THREAD

**Issue by EmperorPeter3** [marmelab/react-admin#8629]
First of all, I need to implement the same pagination controls on mobile layout as on desktop (but problem exist on desktop too)

**What you were expecting:**
When I set **perPage** property for `<List perPage={2} />` or `<ListBase perPage={2} />` or as field of value of `<ListContextProvider value={{ ...contextProps, perPage: 2 }} />` I want to see that there is only two rows will be rendered.

**What happened instead:**
I tried to use example of custom layout from
[ra-core/src/controller/list/ListBase.tsx](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/list/ListBase.tsx)

And also I tried to use **useListController** hook to provide non-default **perPage** property to **ListContextProvider**
[marmelab.com/react-admin/useListController](https://marmelab.com/react-admin/useListController.html)

In both ways nothing happened. Data source **getList** request still receive default perPage value (25) 

**Steps to reproduce 1:**
1. Use an example from this component
[ra-core/src/controller/list/ListBase.tsx](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/list/ListBase.tsx)
2. Replace SimpleList with Datagrid with TextField
3. Change perPage property of ListBase to specified number

**Steps to reproduce 2:**
1. Use an example from docs
[marmelab.com/react-admin/useListController](https://marmelab.com/react-admin/useListController.html)
2. Change provided value field perPage to specified number
3. Wrap Datagrid with TextField with this Provider

**forked CodeSandbox**
https://codesandbox.io/s/sleepy-shadow-l1tlb3?file=/src/posts/PostList.tsx

```
export const List = (props: ListProps) => {
  return (
    <RAList {...props} perPage={6}>
      <Datagrid>
        <TextField source="name" />
      </Datagrid>
    </RAList>
  )
}

export const List = (props: ListProps) => {
  const listContext = useListController()
  return (
    <ListContextProvider value={{ ...listContext, perPage: 6 }}>
      {props.children}
    </ListContextProvider>
  )
}
```

**Environment**

* React-admin version: ^4.6.2
* React version: ^18.2.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
In your foked CodeSandbox (https://codesandbox.io/s/sleepy-shadow-l1tlb3?file=/src/posts/PostList.tsx), you specify a `perPage={2}` and I see 2 results per page. 

![image](https://user-images.githubusercontent.com/99944/217323849-37118f73-c1c5-420e-a9d3-7f9583196737.png)


What's the problem?

**Comment by EmperorPeter3** [comment]
@fzaninotto seems that I forgot to refresh browser on codesandbox.

I have the same code and it's simple

```
<List perPage={2}>
   <Datagrid>
      <TextField source="name" />
   </Datagrid>
</List>
```

But my dataprovider getList receives pagination with value `{ page: 1, perPage: 5 }`

I don't have any other mappings or changes, what I've done wrong?

**Comment by EmperorPeter3** [comment]
The problem is inside the [useListParams](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/list/useListParams.ts)

line 83: received `perPage`: 2
line 91: `params.perPage` from `useStore(storeKey, defaultParams)`: 5
line 110: `query.perPage`: 5 (cause of `params.perPage` value)

`defaultParams` are empty object, from where it takes value `5` ?
