### ISSUE TITLE
useList filter option not working with nested objects

### ISSUE THREAD

**Issue by phelipegustavo** [marmelab/react-admin#8632]
**What you were expecting:**
When I use the `useList` hook with a nested filter option, e.g. `{ "author.name": "Fred" }`
1. the `data` should be filtered correctly

**What happened instead:**
1. the `data` is returning an empty array

**Steps to reproduce:**
1. Open code sandbox
1. Type "fred" in Author name input and Submit
1. The list will be empty

**Related code:**

Codesandbox: https://codesandbox.io/p/sandbox/peaceful-colden-p8qw7n

```tsx
const posts = [{ id: 1, title: "post 1", author: { name: "fred" } }]
const list = useList({
    data: posts,
    filter: { author: { name: "fred" } },
});
// list.data should be equal to posts
```

**Other information:**
The hook `useList` uses `Object.entries` to get the `filterName` and it doesn't work as expected with nested objects.
A possible solution would be to implement a method to flatten the keys into a string path. 
e.g `{ author: { name: "fred" } }`  ->  `{ "author.name": "fred" }`

https://codesandbox.io/p/sandbox/peaceful-colden-p8qw7n?file=%2Fsrc%2Fuse-list.ts

**Environment**

* React-admin version: 4.7.4
* Last version that did not exhibit the issue (if applicable):
* React version: 18.0.15
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Wait, we already support filtering by path thanks to `lodash.get`, so you're right, all it takes is a flattening of the filter object before filtering.

Would you like to work on a PR fixing this?
