### ISSUE TITLE
Save tool bar hiding content on mobile

### ISSUE THREAD

**Issue by idesignpixels** [marmelab/react-admin#8639]
Looks like a resurface of this issue https://github.com/marmelab/react-admin/issues/1274

**What you were expecting:**
all content to be visible on mobile

**What happened instead:**
Toolbar containing save button overlays content obstructing the user 

**Steps to reproduce:**
Visit [this page](https://marmelab.com/react-admin-demo/#/commands/581) on the demo and switch between mobile and desktop breakpoints, the total field gets hidden.

**Related code:**
See demo link here https://marmelab.com/react-admin-demo/#/commands/581

**Other information:**
Looks like a resurface of this issue https://github.com/marmelab/react-admin/issues/1274

**Environment**

* React-admin version: Latest
* Browser: chrome

**Comment by slax57** [comment]
Reproduced, thanks!
