### ISSUE TITLE
AutocompleteArrayInput doesn't work in 4.7.5 like it did before upgrading

### ISSUE THREAD

**Issue by jpschw** [marmelab/react-admin#8641]
AutocompleteArrayInput doesn't seem to behave the same as it did before upgrading from v3. It doesn't consider the source property anymore and displays the "id" field instead of "name" even though I have defined it:

```
<ReferenceArrayInput
            source="regions_ids"
            reference="regions">
   <AutocompleteArrayInput source="name" />
</ReferenceArrayInput>
```

![image](https://user-images.githubusercontent.com/1824966/218228359-6095eda3-132e-436b-b063-6dcf248da153.png)

Whereas if I use a SelectArrayInput I get what is expected:

```
<ReferenceArrayInput
            source="regions_ids"
            reference="regions">
   <SelectArrayInput source="name" />
</ReferenceArrayInput>

```
![image](https://user-images.githubusercontent.com/1824966/218228408-942f5a8c-3c10-4337-9302-fa2b661af7a8.png)

**Comment by slax57** [comment]
As stated in the docs, the prop allowing to choose the field of the record to display in the suggestion item is now `optionText`.
- [Doc for AutocompleteArrayInput](https://marmelab.com/react-admin/AutocompleteArrayInput.html#props)
- [Doc for SelectArrayInput](https://marmelab.com/react-admin/SelectArrayInput.html#props)

The fact that the `source` prop still works with SelectArrayInput in v4 is probably pure luck, but this way of doing things is deprecated and you should use `optionText` from now on.
