### ISSUE TITLE
Make ReferenceManyField compatible with filters

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#8642]
**Is your feature request related to a problem? Please describe.**

Today there is not guidance and support for filters within a ReferenceManyField. I am having difficulties trying to integrate react-admin filter system within a ReferenceManyField component.

**Describe the solution you'd like**

Digging into the source code of the `List` component, it looks like the react-admin way to setup filters in ReferenceManyField would be to write something like:

```jsx
<ReferenceManyField
  reference="comments"
  target="postId"
  pagination={<Pagination />}
>
  <ListToolbar
    filters={commentFilters}
    actions={
      <TopToolbar>
        <FilterButton />
      </TopToolbar>
    }
  />
  <Datagrid bulkActionButtons={false}>
  ...
  </Datagrid>
</ReferenceManyField>
```

But this generates infinite loop when writing within a filter input (probably due to the fact that reference many field context is not exactly similar to the list context, especially in terms of URL sync settings).

Note 1: Today, ReferenceManyField pagination state is not storable in the URL and this feature request might be related to this subject: could a solution be to be able to specify a "urlKey" props to the ReferenceManyField component so that all the state of this field can be stored in URL without conflicting with possible other components?

Note 2: I am not quite sure to understand why react-admin needs to implement a `useReferenceManyFieldController`: why ReferenceManyField component can't directly use a `useListController` hook instead?

**Comment by slax57** [comment]
Hi @nicgirault , and thank you for your suggestion.

I'm not sure I caught exactly what you are asking for. Would you like us to document how to add a FilterForm inside a `ReferenceManyField`, or would you like to add support for a `filters` prop to it (just like with `List`)?

Also, I'm not sure what you expect with the URL: do you expect the URL to be updated when you change the filters or not?

**Comment by nicgirault** [comment]
Thanks for your answer. 

Both would be good solutions for me. Being able to have a `filters` prop would probably be simpler to use, but might require more work.

I would expect the URL to be updated when I change filter and pagination but I guess this should be configurable.

**Comment by slax57** [comment]
Thank you for your answer.
I was mainly asking to better understand what kind change you had in mind, to clarify the enhancement request, and indeed estimate its complexity.

However, in any case, our policy regarding new features is that we only develop them if we require them for one of our projects, or if there is a high demand for this feature from the community.

Of course, you also have the ability to open a PR yourself if you are willing to give it a try. We would gladly welcome it.

Thus, I'm leaving this feature request open to see how things go, but we won't work on it for now.
