### ISSUE TITLE
Id and name fields can't be overridden and are easily duplicated

### ISSUE THREAD

**Issue by idesignpixels** [marmelab/react-admin#8643]
![react-admin-bug](https://user-images.githubusercontent.com/12501597/218415403-61dd18e6-0dba-4005-bf9f-9041a073eb01.gif)

**What you were expecting:**
When there are 2 inputs from the same source that they can be uniquely identified to avoid form bugs like sharing values and state

**What happened instead:**
Both filters are added when one should be, both fields update to the value of the other.
The source is used as an `id` and `name` on both fields and they don't seem to be overridden when the props are added.

**Steps to reproduce:**
Pass multiple filters with the same source, the following example if a filter on a calendar where you can filter by admins attending, clients attending or both.
Whether I put the `id` and `name` field on the `ReferenceInput` or the `AutocompleteInput` the issue still happens.

**Related code:**
```tsx
const calendarFilters = [
  <ReferenceInput
    key="admin"
    name="admin"
    label="Admin"
    source="meeting_invites#user_id"
    reference="users"
    filter={{ 'user_role#name': 'admin' }}>
    <AutocompleteInput label="Admin" />
  </ReferenceInput>,
  <ReferenceInput
    key="client"
    name="client"
    id="client"
    label="Client"
    source="meeting_invites#user_id"
    reference="users"
    filter={{ 'user_role#name': 'client' }}>
    <AutocompleteInput label="Client" />
  </ReferenceInput>,
];
```

**Environment**

* React-admin version: 4.7.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: chrome 109.0.5414.119

**Comment by slax57** [comment]
Thanks for submitting this issue.

I don't understand how you expect to be able to choose both a 'client' and an 'admin' since they both share the same filter field `"meeting_invites#user_id"`.

In any case, it is not supported to have multiple filter inputs targeting the same source field. You will need to [build your own filter form](https://marmelab.com/react-admin/FilteringTutorial.html#building-a-custom-filter) if you need this feature.

**Comment by idesignpixels** [comment]
Hi @slax57 the filter is different:
`filter={{ 'user_role#name': 'admin' }}` && `filter={{ 'user_role#name': 'client' }}`
I have seen something similar to separate 2 different view with the same source called `storeKey` I know this is slightly different but perhaps a similar concept could be added to have distinct references?
I think this is a common use case in the above example where you may want to list users by a role.

**Comment by slax57** [comment]
Again, I don't see how this would work without some custom code to tell the filter form which input it's supposed to update when you set the filter value in the URL for instance.
Using the input's `source` as key makes perfect sense for the simple use-cases covered by the default `FilterForm`.
If you need a more complex filter form, you need to build your own form.
