### ISSUE TITLE
NumberInput incorrectly passes the shouldUnregister prop to some div element down the component tree

### ISSUE THREAD

**Issue by ScienceOfficer** [marmelab/react-admin#8651]
**What you were expecting:**
When using NumberInput with the shouldUnregister prop, no errors/warnings happen.

**What happened instead:**
When using NumberInput with the shouldUnregister prop, a warning is shown in the console:

Warning: React does not recognize the `shouldUnregister` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `shouldunregister` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
div
...

**Steps to reproduce:**
Use a NumberInput and pass the shouldUnregister prop to it.

**Related code:**

<NumberInput source="some.source" shouldUnregister />
Environment

React-admin version: 4.7.3
React version: 18.2.0

Browser: Firefox/Chrome

_Remark:_ It should be basically the same problem as in this issue here: https://github.com/marmelab/react-admin/issues/8412
But SelectInput is using another sanitizing function for the rest props, so solving 8412 didn't solve this issue too.

**Comment by fzaninotto** [comment]
Thanks, the bug is confirmed.
