### ISSUE TITLE
Changing tabs to a CustomRoutes changes the menubar css

### ISSUE THREAD

**Issue by sunny-VFT** [marmelab/react-admin#8663]
```
const MenuBar = () => (
    <Menu>
        <Menu.ResourceItem name="products" />
        <Menu.Item to="/import-products" primaryText="Import" leftIcon={<LabelIcon />}/>
    </Menu>
);

export const MyLayout = props => <Layout {...props} menu={MenuBar} />;
```

```
const AdminIndex = () => {
    return(
    <Admin layout={MyLayout} dataProvider={delayedDataProvider} authProvider={firebaseAuthProvider}>
        <Resource name="products" list={ProductList} edit={ProductEdit} create={ProductCreate} />
        <CustomRoutes>
            <Route path="/import-products" element={<ImportProducts />} />
        </CustomRoutes>
    </Admin>)
}
```

Anytime I go from Products to Import, it changes the css and messes it up. If I refresh it then it gets fixed. What could I be doing wrong?

<img width="299" alt="image" src="https://user-images.githubusercontent.com/108150557/219538121-dc1b3417-7db4-41b7-bc11-5e0e0328734a.png">

**Comment by fzaninotto** [comment]
Could you please follow the issue template? This includes:

- version of react-admin you're using
- - link to a reproducible example.

And other details that are necessary for us to investigate on a possible bug.

**Comment by fzaninotto** [comment]
No news for some time, closing.
