### ISSUE TITLE
False behavior of Notification Snack bar in react-admin

### ISSUE THREAD

**Issue by tauqeer-trailfive** [marmelab/react-admin#8665]
React admin delete update notification or snack bar is showing before getting response from the respective query form data-provider

**What it should be like**

when I hit the delete button the below toast notification should wait for the response from the `graphql ` query defined in dataProvider and show the error in toast or snackbar below

**What is happening instead**

when I hit the delete button the below toast notification does not wait for the response from the graphql query defined in dataProvider and shows the Elemnent is Deleted in toast or snackbar below after that if the query got an error it shows them after Elemnent is Deleted toast this is wrong behavior.

https://user-images.githubusercontent.com/108520807/220036986-bb827a1c-9f6b-4150-83c2-aa01848ab0b1.mp4

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
This is a feature: It's called [optimistic mutations](https://marmelab.com/react-admin/Features.html#optimistic-updates-and-undo). You can tweak this behavior using the `mutationMode` prop

https://marmelab.com/react-admin/Edit.html#mutationmode

**Comment by reterXDark** [comment]
@fzaninotto thanks gotta.
