### ISSUE TITLE
Changing the theme using ToggleThemeButton does not persist function overrides 

### ISSUE THREAD

**Issue by IAmVisco** [marmelab/react-admin#8670]
**What you were expecting:**

Toggling theme would persist all overrides.

**What happened instead:**

Overrides defined with a function get lost after theme toggle

**Steps to reproduce:**

After loading the app with clean localStorage, the theme loads correctly, but after clicking the `ToggleThemeButton`, the value gets saved to the `localStorage` and the function overrides get lost:

![image](https://user-images.githubusercontent.com/18630605/220167072-d3769f45-2e7b-4060-a36e-9d8004f80d7c.png)
![image](https://user-images.githubusercontent.com/18630605/220167095-10310080-63ab-4038-a899-a4bbae73f144.png)

This happens to both Mui and RA components, with the only exception being RA components not having typings, but that's probably a separate issue and not as critical: 

![image](https://user-images.githubusercontent.com/18630605/220167735-c3e4cf79-b99e-4ba3-a99a-6970a04dfa64.png)

**Other information:**

I understand you can't serialize functions reliably, so maybe store only the theme mode in the store? Just thoughts.

**Environment**

* React-admin version: 4.8.0
* Last version that did not exhibit the issue (if applicable): Not sure
* React version: 18
* Browser: Chrome 109

**Comment by fzaninotto** [comment]
Thanks for your feedback. Indeed, the theme being serialized in the store, functions get lost in the process. 

Can you elaborate on 

> maybe store only the theme mode in the store

?

**Comment by IAmVisco** [comment]
> Thanks for your feedback. Indeed, the theme being serialized in the store, functions get lost in the process.
> 
> Can you elaborate on
> 
> > maybe store only the theme mode in the store
> 
> ?

I meant `theme.palette.mode` I assume if the theme got updated between user logins, they won't get the newest version since it will be pulled from the localStorage. By storing only the `mode`, the user will always get the newest version if that happens (albeit with longer loading times).

**Comment by fzaninotto** [comment]
Got you. That's probably the best thing to do , although it's a bit tricky to make it backwards compatible. 

Marking this as a bug.

**Comment by IAmVisco** [comment]
> although it's a bit tricky to make it backwards compatible.
`palette.mode` *is* saved currently, but the migration piece of code will be lingering in the codebase for some time if you decide to implement it (can be dropped on major ver bump). Otherwise this can be ignored considering this is purely UI-feel breaking, not business-logic breaking 🤔

**Comment by slax57** [comment]
Closed via https://github.com/marmelab/react-admin/pull/8874
