### ISSUE TITLE
DataGridConfigurable column ordering feature does not work in Firefox

### ISSUE THREAD

**Issue by Rudo2204** [marmelab/react-admin#8672]
**What you were expecting:**

Column ordering (drag and drop the columns to reoreder them) works as illustrated in the [`DataGridConfigurable` docs](https://marmelab.com/react-admin/Datagrid.html#configurable)

**What happened instead:**

- In Chrome, the feature works as intended
- In Firefox, column ordering does not work

**Steps to reproduce:**

- Run the `OrderList` example in Firefox.
- Click on `Column` button
- Drag and drop the columns to reorder them (it doesn't work)

**Related code:**

I also tried one example ( https://wikidata-table.vercel.app/#/international-airports) provided in #8488 and it also doesn't work

**Other information:**

- Chrome:

[chrome.webm](https://user-images.githubusercontent.com/26686688/220283843-87292b05-377b-4541-a618-a5938da20e71.webm)

- Firefox:

[firefox.webm](https://user-images.githubusercontent.com/26686688/220283877-34febe24-8e6e-4b27-a9e3-5460bc36b5f9.webm)

**Environment**

* React-admin version: 4.8.1
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome 110.0.5481.100, Firefox 110.0
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Reproduced, thanks for the report!

Btw this can be reproduced with the [simple example](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple) too.
