### ISSUE TITLE
When calling useInput::field::onChange, 'target' key doesn't work.

### ISSUE THREAD

**Issue by sweetyraven** [marmelab/react-admin#8675]
**What you were expecting:**
Even in the presence of the 'target' key, it should change properly.

**What happened instead:**
When calling useInput::field::onChange(), if the 'target' key is included in the value to be changed, the value is not changed properly.

**Steps to reproduce:**
1. Create an edit page.
2. Create a custom input component using useInput.
3. Among the return values ​​of useInput, call field.onChange({ target: 'test' }).
4. If you check the field.value of useInput, you can see that it has not been changed properly (Changed result should be {target: 'test'}).

**Other information:**

**Environment**

* React-admin version: 4.6.1
* Last version that did not exhibit the issue (if applicable):
* React version:18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi,
Could you explain where you have read that this is supposed to work?
Besides, as asked in the contribution guidelines of this repo, you need to provide a reproduction based on the [simple example demo](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple) for your issue report to be complete. Can you provide one?
Thanks

**Comment by sweetyraven** [comment]
Hi, I'm sorry I'm not familiar with English.

I made example. 
https://githublbpgb3-1nkz--8080.local-credentialless.webcontainer.io

The reprodution step is following:
1. open example link.
2. click on any row(Post) to open edit page.
3. You can see 'result', 'key' and 'value' fields.
4. put 'test' in the 'key' field and '123' in the 'value' field.
5. You can see that correct value are set in the 'result' field.
6. put 'target' in the 'key' field and '456' in the 'value' field.
7. You will see unwanted values ​​appearing in the result field.

Here's the input component I've implemented:
```
import { Stack, TextField } from '@mui/material';
import SelectInput from '@mui/material/Select/SelectInput';
import React, { useState, useEffect } from 'react';
import { InputProps, useInput } from 'react-admin';

const TestObjectInput = (props: InputProps) => {
  const { field } = useInput(props);
  const [key, setKey] = useState('');
  const [value, setValue] = useState('');

  useEffect(() => {
    field.onChange({ [key]: value });
  }, [key, value]);

  return (
    <Stack spacing={2}>
      <TextField label="result" value={JSON.stringify(field.value)} disabled />
      <TextField
        value={key}
        label="key"
        onChange={(e) => setKey(e.target.value)}
      />
      <TextField
        value={value}
        label="value"
        onChange={(e) => setValue(e.target.value)}
      />
    </Stack>
  );
};

export default TestObjectInput;
 ```

thanks

**Comment by slax57** [comment]
Thanks,
The provided stackblitz was most useful for me to understand your issue.

However, I'm not sure I can qualify this as a bug so far, because I'm not entirely sure that what you are trying to do is actually a use-case we support.

Can you tell me more about what you are trying to do? Why do you need to change the value of a text field to a complex object containing a `target` field?

Also, can you try to use [react-hook-form's setValue](https://react-hook-form.com/api/useform/setvalue) instead to set the value of the field? This would be the way I would have recommended to do it anyways, and it may not suffer from this issue.

**Comment by sweetyraven** [comment]
We are trying to set deep link information in admin. In that case, the information must be stored in the form of json, and the key and value must be freely settable. 

I solved the problem as follows.
```
const newSettingValue = { target: "Test" };
field.onChange({target: {value: {target: {value: newSettingValue}}}});
```

  * The reason why '{target: value: {' is used twice is that the code inside useInput calls onChange of useController once again.

I've done it the above way and it's working fine. Thanks for your reply.
