### ISSUE TITLE
Customise the create list item in AutocompleteInput Component 

### ISSUE THREAD

**Issue by patrickcollings** [marmelab/react-admin#8679]
**Is your feature request related to a problem? Please describe.**
The create item in the autocomplete list has the same style as the the other options. This makes it indistinguishable from a list item and not very obvious. It is also only displayed when a user begins to type.

**Describe the solution you'd like**
- A prop that allows us to override the style of the create option not just the label. 
- A prop that allows us to show the create option at all times.

If this is not possible can we have an option to set the create component inline rather than below the AutocompleteInput? In that scenario we would be able to use the CreateInDialogButton inside the dropdown which would be really nice.

**Describe alternatives you've considered**
I've tried using custom options from the MUI base component and then overriding the style of the options but it is applied to all of them.

**Additional context**
This is the design we are attempting to create:
![image](https://user-images.githubusercontent.com/30416464/220982090-ff1a1f46-2cdd-4707-9c51-9658836d97e8.png)

**Comment by slax57** [comment]
Hi,
Thank you for this detailed report.
I'll keep this issue open, in order to see if there is traction for it from the community.
If ever you would like to implement this feature yourself, feel free to open a PR!
Thanks

**Comment by fzaninotto** [comment]
This proposal hasn't received any attention from the community for quite some time, and we won't implement it in the near future. So I'm closing the issue. Feel free to contribute a PR implementing this feature, we'll look at closely.
