### ISSUE TITLE
RA Button with underlying Link component throws MUI warnings to console

### ISSUE THREAD

**Issue by IAmVisco** [marmelab/react-admin#8683]
**What you were expecting:**

No warnings in console.

**What happened instead:**

Mentioned briefly in #8671 
`<Button component={Link} ...>` throws MUI ref warnings to console.

**Related code:**

https://stackblitz.com/edit/github-g7vofu?file=src%2Fposts%2FPostEdit.tsx

**Environment**

* React-admin version: 4.8.1
* Last version that did not exhibit the issue (if applicable): Not sure
* React version: 18 (locally), 17 (in StackBlitz)
* Browser: Chrome 109
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
This is weird. The `Link` component is wrapped in a `forwardRef` (see https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L406). As far as I can tell, it has always been.

Besides. the warning seems to be triggered by the `FormTab` component and not the buttons. However, it simply passes the same `Link` component as the buttons just like the MUI documentation recommends (https://mui.com/material-ui/guides/routing/#tabs).

Finally I can't reproduce this on our simple example but your stackblitz uses a more recent mui release.

**Comment by IAmVisco** [comment]
I forked the repo provided in the issue template, not sure how it can be newer. Also, locally the same warning is popping within `SimpleForm` as well, maybe there is a connection.

**Comment by juranosaurustechs** [comment]
Using Link from react-router-dom worked for me: `import { Link } from "react-router-dom";`

**Comment by djhi** [comment]
Didn't noticed the import. Indeed, you should use react-router `Link`
