### ISSUE TITLE
`loginPage={false}` ends up calling `logout` and `checkAuth` in an infinite loop after logout

### ISSUE THREAD

**Issue by slax57** [marmelab/react-admin#8685]
**What you were expecting:**
Being able to pass `loginPage={false}` to `<Admin>` without breaking the App.

**What happened instead:**
After I logout, I get redirected to `/login`, which ends up in an infinite loop calling `logout` and `checkAuth` because the route no longer exists.

**Steps to reproduce:**
1. Go to https://stackblitz.com/edit/github-hwp9xd?file=src/index.tsx
2. Open the user menu in the AppBar and click on the 'Logout' button
3. Notice that in the DevTools console, `called logout!` and `called checkAuth!` appear in loop

**Related code:**
https://stackblitz.com/edit/github-hwp9xd?file=src/index.tsx

**Environment**

* React-admin version: 4.8.1
* Last version that did not exhibit the issue (if applicable): unknown
* React version: 18
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
I think this is expected. If you disabled the login page we have no other option than to redirect on the home page and that will call the `checkAuth` function indeed. It's your responsability to redirect to a custom unprotected route or an external service (auth0, etc).

I believe this is a documentation issue
