### ISSUE TITLE
Mistake in the docs about Vite

### ISSUE THREAD

**Issue by Mikilll94** [marmelab/react-admin#8688]
**What you were expecting:**

<img width="798" alt="Screenshot 2023-03-02 at 10 27 45" src="https://user-images.githubusercontent.com/17653648/222387715-d75cf119-d25e-4ed4-a9c9-40565ef24441.png">

There is no such a tool called `vite.js`. It is called `Vite` -> https://vitejs.dev/

**What happened instead:**

There is a mistake in the docs.

**Comment by djhi** [comment]
Can you make a PR to fix it? The documentation is the main repo. Thanks!
