### ISSUE TITLE
ReferenceManyCount documentation says calls DataProvider to retrieve no data. PerPage should be 0

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#8697]
> Under the hood, `<Count>` and `<ReferenceManyCount>` call `dataProvider.getList()` with the `pagination` parameter set to retrieve no data - only the total number of records

https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/Count.tsx
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/field/ReferenceManyCount.tsx

Both of these should have a perPage of 0, not 1.

**Comment by slax57** [comment]
I don't know about this one, some dataProviders may not like having `perPage=0`. Besides I really don't think it's such a big deal.
Do you see a scenario where this could be harmful?

**Comment by davidhenley** [comment]
Not really, it just feels dirty to query for one item when you are looking for a count.

Works fine, I just didn't take into account APIs not liking `perPage=0`
