### ISSUE TITLE
ERROR in multi app Module not found: Error: Cannot resolve module 'react-hot' 

### ISSUE THREAD

**Issue by yarhtut** [marmelab/react-admin#87]
Can not run the demo app

**Comment by cpursley** [comment]
I can confirm running into the same issue when running the Server package:

```
ERROR in multi app
Module not found: Error: Cannot resolve module 'react-hot' in /Users/path/react-admin/examples/blog
 @ multi app
```

 Also when running the Browswer package I'm getting this (even after npm instaling it):

```
make: ./node_modules/webpack-dev-server/bin/webpack-dev-server.js: No such file or directory
make: *** [run-blog] Error 1
```

**Comment by ajarbol** [comment]
+1 adding `"react-hot-loader": "^1.3.0"` to `devDependencies` fixes the original issue, I'm however seeing 
```
ERROR in ./config-webpack.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./build/react-admin-standalone.min
```

**Comment by veganson** [comment]
+1

**Comment by fzaninotto** [comment]
This project is discontinued. We've published a complete rewrite and committed to support it. Check out [marmelab/admin-on-rest](https://github.com/marmelab/admin-on-rest).
