### ISSUE TITLE
Don't render EditButton when there is no edit view

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#8706]
When adding `<EditButton />`, the button will display even if clicking the button will do nothing.

If using permissions to remove the edit view, then the user needs to write additional code to also remove the edit button. It seems like there should be enough information for the edit button component to do this automatically and reduce the amount of code needed for a developer to make this work correctly.

**Comment by fzaninotto** [comment]
Nope, it's the job of the component that includes the EditButton to do that. 

Tip: If you need fine-grained permissions, check out how ra-rbac changes the datagrid `rowClick` to lead either to the edit or show view depending on permissions: https://marmelab.com/ra-enterprise/modules/ra-rbac#datagrid

**Comment by Dreamsorcerer** [comment]
I already wrote code to replace the button. But, seems odd that a button would render when it already knows that it can't do anything (or, if it does render, it should be as a disabled button).

**Comment by fzaninotto** [comment]
Understood - let's agree to disagree. In the case of the EditButton, it's the parent's responsibility to do that check.
