### ISSUE TITLE
ra-supabase integration is completely unusable

### ISSUE THREAD

**Issue by Mikilll94** [marmelab/react-admin#8709]
**What you were expecting:**
Could you fix this bug in `ra-supabase` https://github.com/marmelab/ra-supabase/issues/16 ? It seems like it is treated as low priority.

Currently `ra-supabase` is completely unusable because sign up and reset password flow are not working. Unfortunately there is no working solution right now.

**Environment**

* React-admin version: 4.8.2
* React version: 18.2.0

**Comment by djhi** [comment]
Wrong repository. We released ra-supabase 2.0.0 and an PR is waiting for review regarding this issue
