### ISSUE TITLE
Path guide in source of inputs and fields

### ISSUE THREAD

**Issue by Gabriel-Malenowitch** [marmelab/react-admin#8710]
**Is your feature request related to a problem? Please describe.**
 > I am frustrated because i use react admin every day and i need to "guess" the field and inputs source : (. Sometimes i make some mistake in object path and i need to construct a hot fix PR : ( Do you thing my below suggestion could be util for react admin users?

 
**Describe the solution you'd like**
My suggestions:

Input:
![image](https://user-images.githubusercontent.com/56513919/223137564-ba9e8d5e-f6be-46b6-9b69-58d4c0058ceb.png)
![image](https://user-images.githubusercontent.com/56513919/223136400-d0704fdc-7a65-4b3a-9f50-c0da81d4ad0c.png)

Fields:
![image](https://user-images.githubusercontent.com/56513919/223145233-28d16827-aae5-4766-b966-a3659475ce33.png)

**Describe alternatives you've considered**

It can be talked : )

**Comment by djhi** [comment]
We are workint on it: https://github.com/marmelab/react-admin/pull/8690

**Comment by Gabriel-Malenowitch** [comment]
Thanks @djhi !
