### ISSUE TITLE
data-fakerest: Configurable id key

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#8714]
**Is your feature request related to a problem? Please describe.**

The current fake data provider of `getMany` implementation assumes the identity key is `id`: https://github.com/marmelab/react-admin/blob/3d7e3842504e993d6defee601c3156f9a2167c10/packages/ra-data-fakerest/src/index.ts#L68

However, this is not representative to my real API database, which has an `_id` property.

**Describe the solution you'd like**

Make the id key configurable.

**Describe alternatives you've considered**
Adds a `id` value. However, this may leads to misunderstanding mistake during development process.

**Additional context**

**Comment by djhi** [comment]
You can extend the dataProvider returned by `ra-data-fakerest` and override its behavior for the resources that needs it with [withLifecycleCallbacks](https://marmelab.com/react-admin/withLifecycleCallbacks.html#lifecyclecallbacks).

For instance:

```js
export const dataProvider = withLifecycleCallbacks(myFakeRestDataProvider, [
    {
        resource: 'my-resource',
        beforeGetMany: async (params) => {
            return { ...params, filter: { myProperty: params.filter.id } };
        },
    },
]);
```
