### ISSUE TITLE
ReferenceManyToManyInput not working within ReferenceManyInput

### ISSUE THREAD

**Issue by crc-sstubbs** [marmelab/react-admin#8718]
**What you were expecting:**
When nesting a `ReferenceManyToManyInput` within a `ReferenceManyInput`. I expected values to be populated on load. I also expected save to work within a `Create` or `Edit` `SimpleForm`. I've also noticed that `ReferenceManyToManyInput` does not seem to respect the source prop.  

**What happened instead:**
The request sends a query using the parent object id rather than the id of the `ReferenceManyInput` resource on load. I believe it's linking to the incorrect resource.

**Related code:**
```
<ReferenceManyInput reference="permission" target="permission_id">
  <SimpleFormIterator inline>

    <ReferenceManyToManyInput
      label="Roles"
      reference="role"
      through="permission_role"
      using="permission_id,role_id"
    >
      <SelectArrayInput label="Roles" optionText="name" />
    </ReferenceManyToManyInput>

    <ReferenceManyToManyInput
      label="Policies"
      reference="policy"
      through="permission_policy"
      using="permission_id,policy_id"
    >
      <SelectArrayInput label="Policies" optionText="name" />
    </ReferenceManyToManyInput>          

  </SimpleFormIterator>
</ReferenceManyInput>
```
**Environment**

* React-admin version: 4.8.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):
* ra-relationships: 4.1.5

**Comment by slax57** [comment]
Hi Stephen,

Please note that the Github Issue tracker should only be used to track issues affecting the Community components of React Admin.
For Enterprise components (such as `ReferenceManyToManyInput),` you can open a support request by writing to our Enterprise Support Desk (which you already did from what I can see).

Hence, I'll close this issue and invite you to contact us via the Enterprise Support Desk instead.
