### ISSUE TITLE
TextInputs with sources that contain '|' don't accept text

### ISSUE THREAD

**Issue by zbarbuto** [marmelab/react-admin#8721]
**Problem Description:**
The API I'm using has pipe (`|`) as a query delimiter, for example `firstName|startsWith`. Following the [filter operators section](https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators) of the docs I put this into the `source` property of a `TextInput`. However, when I do this, the text input completely stops working (typing keys does nothing) 

If I use any other delimiter (like `__` or `$`) the text field works, it just seems to be `|` or `||` that causes this issue.

This applies to both `TextInput` and `SearchInput`.

I have reproduced it in a fork of the example using the PostList:
https://codesandbox.io/s/stupefied-brattain-rcnymf?file=/src/posts/PostList.tsx

You can see the "Works" searches (using a `__` or `$$` delimiter) accepts searches while the `|` and `||` ones do not.

**Other Solutions / Workarounds:**

I could work around this at the data provider layer (re-mapping some other delimiter like `__` back to `|` before making the request) but it just seemed curious to me that the text fields just completely break with no errors or anything.

**Edit**

After some testing I found another fix is to add a `name` to the field that has a `|` in it, which fixes the issue:

```html
<TextInput label="Broken" source="a|eq" alwaysOn />
<TextInput label="Does Work" source="b|eq" name="Foo" alwaysOn />
```

**Comment by zbarbuto** [comment]
I did some digging and I think this relates to how the fields get named.
I have added another field that **does** work by giving it a "name" property:

```html
<TextInput label="Broken" source="a|eq" alwaysOn />
<TextInput label="Does Work" source="b|eq" name="Foo" alwaysOn />
```

So perhaps because the [source](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/useInput.ts#L40) gets [used as the name](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/useInput.ts#L67-L68) the issue actually lies in `react-form-hooks` / `useController`?

In any case adding `name`s to the inputs seems like a much better workaround than different delimiters like I suggested.

**Comment by djhi** [comment]
Yes we use the `source` as the `name` by default but allow you to override it when you need for those cases. We could add pass the `source` through a sanitizer function though. Feel free to open a PR

**Comment by zbarbuto** [comment]
I tried sanitizing by replacing the pipe with an underscore but this was too breaking of a change as the filters would came through differently (you get `filter: {name_ilike: 'Foo'}` instead of `filter: {'name|ilike': 'Foo'}`) - meaning it was no different to using a source with underscores instead of pipes.

**Comment by slax57** [comment]
Okay, thanks for giving it a try anyway!
Can you confirm I can consider this issue solved then, since you will probably work around this by tweaking the dataProvider in the end?

**Comment by zbarbuto** [comment]
Yeah, happy to close this as "Won't fix" - not sure if you think it's worth mentioning this little quirk anywhere in the docs?

**Comment by slax57** [comment]
Thanks for your reply.
I'd say that since this use-case is pretty specific, this issue is probably enough.
