### ISSUE TITLE
Make server-side validation supportable in the standard save function

### ISSUE THREAD

**Issue by ns-vpanfilov** [marmelab/react-admin#8722]
**Is your feature request related to a problem? Please describe.**
Currently, server-side validation is only supportable using a custom save function (https://marmelab.com/react-admin/Validation.html#schema-validation).

While that approach works, it has the following limitations:
- Some configurations that (e.g. `transform` property for `Create`) are ignored
- Building server-side component is more complex that for Create (due to the fact we need to be inside record context), and it is not documented

**Describe the solution you'd like**
Allow for a configurable parameter that can be passed to `Create` and `Update` components that will translate an error and return it to the form as validation results:
```js
const ServerSideValidation = async (e:Error): Promise< undefined | Record<string, {message: string, messageArgs?: any} >> = {

return undefined // no server-side validation errors to be reported

// OR

return {
   user_name: {
      message: 'messages.validation.invalid_chars',
      messageArgs: {'only numbers are allowed}
   }
} // error message to be displayed for 'user_name' field

```

**Describe alternatives you've considered**

**Additional context**

**Comment by djhi** [comment]
Can you check whether https://github.com/marmelab/react-admin/pull/7938 solves your issue? It's planned for `4.9.0`

**Comment by ns-vpanfilov** [comment]
it does. thanks
