### ISSUE TITLE
Filters are not cleared to the initial state when using browser back navigation

### ISSUE THREAD

**Issue by yanchesky** [marmelab/react-admin#8737]
**What you were expecting:**
I expect an applied filter to reset on navigating back using the browser back button when initially no filter was set.

**What happened instead:**
Applied filter persists 

**Steps to reproduce:**
Open [sandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) with a sample application. Set any filter and use the sandbox browser navigation back. The filter will stay unchanged

**Other information:**
During a cursory investigation of the code, I noticed that the logic 👇 inside `useListParams.ts` sets params (filters, sort, pagination....) only when there are query parameters in the URL. 

```
useEffect(() => {
    if (Object.keys(queryFromLocation).length > 0) {
        setParams(query);
    }
}, [location.search]);
```

I believe that this is intentional, but wouldn't it be better to reset the params in store to initial settings in case of lack query parameters in the URL - (`location.search == ""`)

**Environment**

* React-admin version: latest
* React version: latest
* Browser: chrome, safari

**Comment by yanchesky** [comment]
`disableSyncWithLocation` won't solve my issue because I'd like to have filters kept in URL query params. 
**Not** having `disableSyncWithLocation` makes me think that it should be synced with the location though. 

The first solution that comes into my mind is to append params kept in the store to the `/post` on the mount in case `location.search == ""`. 
If there are no params in the store then explicitly set URL query params to empty values eg. `/post?displayedFilters=%7B%7D&filter=%7B%7D`

**Comment by fzaninotto** [comment]
As explained by @slax57, we had to make tradeoffs and your use case falls in between. We can't support it natively without harming other use cases, which we consider more important. 

So we won't be able to fix this issue, and I encourage you to use some of the solutions you imagined in your app. As you guessed, you can update the sidebar menu to lead to an unfiltered list by setting the filter parameter to `{}`, following this piece of documentation:

https://marmelab.com/react-admin/FilteringTutorial.html#linking-to-a-pre-filtered-list

Thanks for the issue anyway!
