### ISSUE TITLE
useRecordContext inside <Create> always returns "undefined"

### ISSUE THREAD

**Issue by IAmVisco** [marmelab/react-admin#8742]
**What you were expecting:**
[As per the docs](https://marmelab.com/react-admin/useRecordContext.html#availability), useRecordContext should return the record when used inside a `<Create>` component. Instead, it's always `undefined` no matter if the from is filled out or not.

**Related code:**
https://stackblitz.com/edit/github-ktseeg?file=src%2Fposts%2FPostCreate.tsx

Go to post create and check console:
![image](https://user-images.githubusercontent.com/18630605/225987358-55203dad-9f20-418e-bd63-5b5711ff931c.png)

**Environment**
* React-admin version: 4.8.4
* Last version that did not exhibit the issue (if applicable):
* React version: 17 in StackBlitz, 18 locally.
* Browser: Chrome 111

**Comment by fzaninotto** [comment]
`useRecordContext` returns the record used to initialize the form. If you want to react to changes in the form values, you have to use react-hook-form's `useWatch`.

The `useRecordContext` doc is probably not explicit enough about that, so we should fix it.

**Comment by IAmVisco** [comment]
I assumed something of that sort was the case. Thanks for the response! 👍

**Comment by mhoussein99999** [comment]
> `useRecordContext` returns the record used to initialize the form. If you want to react to changes in the form values, you have to use react-hook-form's `useWatch`.
> 
> The `useRecordContext` doc is probably not explicit enough about that, so we should fix it.

I couldn't import the `useWatch` hook.
