### ISSUE TITLE
`ReferenceManyCount` renders a corrupted link

### ISSUE THREAD

**Issue by oleg-semyonov** [marmelab/react-admin#8750]
**What you were expecting:**
When used with `link` prop, `ReferenceManyCount` should render a clickable link that leads to the filtered resource page

**What happened instead:**
The link is rendered as `span` tag with `to` attribute set to `[object Object]`.

**Steps to reproduce:**
It is actually reproducible on the [simple example](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) straight out of the box. Just click "inspect" on any "Nb comment" field in Posts grid.

**Other information:**
This is easily fixable by removing a single line: https://github.com/marmelab/react-admin/blob/1a1b80adb3fd402dd8fd2af23692eadb4696eaa0/packages/ra-ui-materialui/src/field/ReferenceManyCount.tsx#L82

I've filed a PR with the proposed change: #8752 

I don't think using `span` was intended, probably just flowed over from `Typography` component props below.

**Environment**

* React-admin version: 4.6.2
* React version: 18.2.0
* Browser: Chrome

**Comment by slax57** [comment]
Reproduced, thanks!

**Comment by slax57** [comment]
Sorry @oleg-semyonov  I did not see you had already opened a PR for this issue.
Mine has the advantage of allowing to remove the `// @ts-ignore` for good so I'd recommend keeping this one over yours.
Still grateful for the report and the PR though! :pray:

**Comment by oleg-semyonov** [comment]
Wow, thanks for such a quick response!

I checked your PR, and indeed that's a much more permanent solution. I closed my PR in favor of yours.

**Comment by slax57** [comment]
@oleg-semyonov  plot twist: https://github.com/marmelab/react-admin/pull/8754#discussion_r1144501853 actually gives arguments in favor of your PR :grin: 
Would you like to reopen it? (seems like I can't do it myself)
Sorry for the time loss :sweat_smile:

**Comment by slax57** [comment]
It looks good to me, thanks!
