### ISSUE TITLE
Make the remove Icon of the FileInputPreview configurable

### ISSUE THREAD

**Issue by PennyJeans** [marmelab/react-admin#8755]
**Is your feature request related to a problem? Please describe.**

I am using the [ImageInput.tsx](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/ImageInput.tsx) component. This component includes the FileInputPreview.tsx (via the FileInput.tsx component) component, which imports a deletion icon for deleting single images/files from mui/icons (RemoveCircle) with no option to overwrite it.

**Describe the solution you'd like**

The FileInput.tsx, which is used in the ImageInput.tsx, should have an optional prop "removeIcon". This prop should be passed down as an optional prop to the FileInputPreview.tsx. If this prop is set by the consumer with an icon, this icon should be used by the FileInputPreview.tsx and, if it is not set, FileInputPreview.tsx should use RemoveCircle as a default icon.

**Describe alternatives you've considered**

I do not know of an alternative for making this icon configurable for consumers of ImageInput.tsx.

I also added a small PR with a suggestion of how the changes could roughly look.

**Comment by fzaninotto** [comment]
Can you explain why you need to configure the icon? What's wrong with the current icon?

**Comment by slax57** [comment]
Fixed by https://github.com/marmelab/react-admin/pull/8756
