### ISSUE TITLE
Optional run-time typechecking for data provider with zod

### ISSUE THREAD

**Issue by sebastianbuechler** [marmelab/react-admin#8757]
**Is your feature request related to a problem? Please describe.**
Currently, a data provider does not properly assert types on runtime but assumes that everything is correct according to the typescript models we specify. This is nice for development but can introduce bugs in runtime since the input is wrong in the first place. Example: If we get a JSON response from the API where a number is a string but we assume it to be a proper number, our implementation upstream could fail, as our code tries to do something that's not possible.

**Describe the solution you'd like**
I came across this [article ](https://tkdodo.eu/blog/type-safe-react-query) that talks about this issue, including solutions with react-query. The main concept is to use zod for defining a response schema and then parse it before it leaves the fetch function. 

**Additional context**
Is that something that was already considered? Or does marmelab see some alternatives for proper type-checking at runtime?

**Comment by djhi** [comment]
This could live in a dedicated package leveraging the lifecycle callbacks: https://marmelab.com/react-admin/withLifecycleCallbacks.html

**Comment by sebastianbuechler** [comment]
> This could live in a dedicated package leveraging the lifecycle callbacks: https://marmelab.com/react-admin/withLifecycleCallbacks.html

That's an interesting approach. But that would mean that for each resource the callbacks will be needed separately, right?

Unfortunately, I'm not experienced with zod as we did not see where to use it easily in the react-admin setup. However, we had to extend the default data provider for fetching non-record objects. So we built a customDataProvider that takes care of handling the types correctly. 

Could it make sense to approach this by building another dataProvider interface that accepts zod objects instead of types and then uses this automatically for parsing after the response has arrived? But this would impact the core of the dataProvider massively, as the interface would need to be extended.

**Comment by djhi** [comment]
We could also a decorator function accepting an object mapping resources to their schema and leveraging Proxy. Definitely something that can be in a dedicated extension package

**Comment by sebastianbuechler** [comment]
So it's clear to have both zod objects and typescript types for the response models, right? If yes, such a mapping would need to exist anyway somewhere, which would make both approaches you presented be useful.

**Comment by fzaninotto** [comment]
This is something we're interested in, but we won't work in it in the near future. If you'd like to contribute a PR implementing it, we'll be very happy to look at it.
