### ISSUE TITLE
Add the ability to disable title configuration (while still make the rest of the page configurable)

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#8776]
**Is your feature request related to a problem? Please describe.**
The documentation of AppBar says https://marmelab.com/react-admin/AppBar.html#configurable

> By default, users can override the page title [in configurable mode](https://marmelab.com/react-admin/Features.html#configurable-ui).

But did not suggest a way to turn it off while keeping the rest of the page configurable.

**Describe the solution you'd like**

I would like the `<Title />` component to accept a boolean prop called nonconfigurable, so user can optionally disable it

**Describe alternatives you've considered**

The alternative is developer has to manually change list, show, create and import additional react functions to render PageTitle into a portal.

**Comment by slax57** [comment]
I agree, we should allow to disable this feature while still allowing other parts of the app to be configurable.
Would you like to open a PR?

**Comment by ujjwalpandey922** [comment]
Hi,
Can I work on this?

**Comment by slax57** [comment]
@ujjwalpandey922 Of course! :slightly_smiling_face: 
Just remember to read the [Contribution Guidelines](https://github.com/marmelab/react-admin#contributing) first, and to target your PR against the `next` branch as it's a new feature.
Thanks!

**Comment by Aditay2002** [comment]
@smeng9 is this issue still open ? i will like to contribute towards it

**Comment by slax57** [comment]
@Aditay2002 yes the issue is still open, you can go ahead :slightly_smiling_face: 
Thanks

**Comment by adguernier** [comment]
Hi @Mex7180, it appears no one is working on this issue yet. So yes, you can give a try!
Don't forget to read our [Contribution Guidelines](https://github.com/marmelab/react-admin#contributing) first, and to target your PR against the `next` branch.
Thanks for your contribution :pray:

**Comment by markyao6275** [comment]
I have a pull request: https://github.com/marmelab/react-admin/pull/9836 that attempts to tackle this issue. Would appreciate a review, thanks!

**Comment by slax57** [comment]
Implemented in https://github.com/marmelab/react-admin/pull/9836
