### ISSUE TITLE
react-query dev tool break List view in mobile view

### ISSUE THREAD

**Issue by Seojun-Park** [marmelab/react-admin#8784]
**What you were expecting:**

List view should fit mobile screen without empty space

**What happened instead:**

https://user-images.githubusercontent.com/47709344/228841652-21a5b1a3-1f59-415c-9429-2f62ca88a727.mov

A large empty space is displayed beneath the list.

**Steps to reproduce:**

1. Go to Post list view
2. Go to browser's inspection page
3.  the inspection page, click on the "Toggle device toolbar" icon to switch to the mobile view.
4. Change the browser dimension size to mobile by selecting a mobile device
5. Verify that the page layout and content

**Related code:**

- Reproduce : https://codesandbox.io/s/compassionate-microservice-ekduri?file=/src/posts/PostList.tsx&resolutionWidth=436&resolutionHeight=682

### Notice: I was unable to reproduce this issue on CodeSandbox, so I have also included a link to a forked repository where the issue has been reproduced. Please test it using this branch.
- branch link : https://github.com/Seojun-Park/react-admin/tree/react-dev-tool-on-list
- file path: https://github.com/Seojun-Park/react-admin/blob/c0233fc800bdfbece696e6bf7599da193b633b74/examples/simple/src/posts/PostList.tsx#L123-L166

**Other information:**

**Environment**

* React-admin version: "4.9.0
* Last version that did not exhibit the issue (if applicable):
* React version: "17.0.2"
* Browser: "Chrome",  "Firefox"
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Thank you for this detailed report.
Currently I'm not sure if this is an issue with react-admin (e.g. the way we integrate the dev tool inside the `<Layout>`) or with the dev tool itself.
Since this is really minor though, we probably won't have time to work on this any time soon.
If you are willing to, feel free to push the investigation further, to check if there is something we can change on our side or not.

**Comment by Seojun-Park** [comment]
@slax57 

Okay, I will investigate more and bring you with more information later :)

**Comment by Seojun-Park** [comment]
On my project, I use the <List /> component with MUI's <Tabs />. This rendering issue is caused by the <Tabs /> component. I'm closing this issue as it is not related.

**Comment by slax57** [comment]
Thanks for taking the time to have a deeper look at this :slightly_smiling_face:
