### ISSUE TITLE
ArrayInput element parse might not work as intended

### ISSUE THREAD

**Issue by aximov** [marmelab/react-admin#8785]
**What you were expecting:**
I expected that the `parse` functionality of the element inside the `SimpleFormIterator` and `ArrayInput` would handle empty values, converting them to `null` as intended according to the [December 2022 update for better support for empty values](https://marmelab.com/blog/2022/12/08/react-admin-december-2022-update.html#better-support-for-empty-values-in-inputs).

**What happened instead:**
It seems that the `parse` functionality is not working correctly, resulting in empty values being sent as `""` instead of `null`.

**Steps to reproduce:**
1. Visit the [blog sample](https://iuxnw.sse.codesandbox.io/#/posts/create).
2. Add a new backlink without filling in any information.
3. Click "Save and Edit".
4. Observe the console, noting that the saved values for `date` and `url` are `""` rather than `null`. 

The same issue occurs in my production code, where empty strings are sent to API.

**Related code:**

You can find the related code in the [React-Admin repository](https://github.com/marmelab/react-admin/blob/d5ada6858b71cfc8b14ad4f2184a6d0a82f5ec26/examples/simple/src/posts/PostCreate.tsx#L146). 

**Other information:**
Please investigate this issue and confirm whether the current behavior of the `parse` functionality inside `ArrayInput` is by design or if it needs to be fixed to handle empty values correctly.

**Environment**

* React-admin version: 4.9.0 and 4.4.2
* Last version that did not exhibit the issue (if applicable): 4.0.1
* React version: 17.0.2
* Browser: Chrome 111.0.5563.110 (Official Build) (arm64)
* Stack trace (in case of a JS error): N/A

Thanks to @uzimith for their contribution in discovering this issue.

**Comment by slax57** [comment]
Fixed by https://github.com/marmelab/react-admin/pull/8792
