### ISSUE TITLE
Properties 'minLength' and 'maxLength' don't exist on TextInput props

### ISSUE THREAD

**Issue by carlos-duran** [marmelab/react-admin#8789]
**What you were expecting:**

Be able to use native minLength or maxLength on TextInput

**What happened instead:**

Type error: maxLength doesn't exist on that type.

**Steps to reproduce:**

Put minLength or maxLength attribute in a TextInput

**Related code:**

```jsx
<TextInput
    autoFocus
    source="title"
    validate={required('Required field')}
    maxLength={10} // type error
    minLength={8} // type error
/>
```

**Other information:**

![image](https://user-images.githubusercontent.com/15650777/229188385-78eb471d-37dc-4eff-9f3f-514a12d398bd.png)

**Environment**

* React-admin version: 4.9.0
* React version: 18
* Browser: Chrome

**Comment by bgryks18** [comment]
its type isn't written but
you can use  like this without type definition for now 

                      <TextInput
                          autoFocus
                          source="title"
                          validate={required('Required field')}
                          resettable
                          InputProps={{
                              componentsProps: {
                                  input: {
                                      maxLength: 3,
                                  },
                              },
                          }}
                      />
   
   InputProps is a type defined in the Mui's TextField.

**Comment by bgryks18** [comment]
its type isn't written but
you can still use it like this without type definition

                      <TextInput
                          autoFocus
                          source="title"
                          validate={required('Required field')}
                          resettable
                          InputProps={{
                              componentsProps: {
                                  input: {
                                      maxLength: 3,
                                  },
                              },
                          }}
                      />
   InputProps is a type defined in the Mui's TextField.

**Comment by bgryks18** [comment]
<TextInput
                      autoFocus
                      source="title"
                      validate={required('Required field')}
                      resettable
                      InputProps={{
                          componentsProps: {
                              input: {
                                  maxLength: 3,
                              },
                          },
                      }}
                  />
InputProps is a type defined in the Mui's TextField.

**Comment by fzaninotto** [comment]
As explained by @bgryks18, this is doable in user land via `InputProps`.
