### ISSUE TITLE
BulkUpdateButton: Missing documentation

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#8790]
BulkUpdateButton is listed at: https://marmelab.com/react-admin/Reference.html#components
With a link to: https://marmelab.com/react-admin/Buttons.html#bulkupdatebutton

But, it is not even mentioned on that page. There appears to be no reference documentation for the component.

**Comment by fzaninotto** [comment]
You can find basic documentation at https://marmelab.com/react-admin/Datagrid.html#bulkactionbuttons. But you're right, we can do better.

**Comment by fzaninotto** [comment]
> I was wondering if it's possible to do anything more dynamic without custom coding a component. e.g. To copy a value from another field (something vaguely like data = {foo: record.bar} for each selected record).

Not in react-admin. If your backend supports an update based on a formula, then you should definitely use it (through a custom component), but most CRUD backends don't, and that's why the `useUpdateMany` only accepts a modification object with literal values.

**Comment by fzaninotto** [comment]
Fixed by #9077
