### ISSUE TITLE
Make the filter inputs full width by default on low screen resolution (mobile)

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#8795]
It make more sense to me to have all the input taking a full width when we are on mobile view.

So instead of this being the default:

<details><summary>Before</summary>

![Screen Shot 2023-04-03 at 21 00 22](https://user-images.githubusercontent.com/1698357/229603372-9b806499-3c64-4d82-9b7c-8457beac4840.png)

</details> 

I suggest to have this:

<details><summary>After</summary>

![Screen Shot 2023-04-03 at 21 04 26](https://user-images.githubusercontent.com/1698357/229603474-edc80283-2f60-4d71-bce6-5be5f5b47620.png)

</details> 

This is what I am willing to on my project. I may work on that but I would like to be sure about the idea first.

Thanks!

**Comment by fzaninotto** [comment]
On Mobile, I agree with you - but on Mobile only.

**Comment by soullivaneuh** [comment]
Of course, we are on the same phase here!

By the way, for the demo, I just added `fullWidth` on the configured filter of the `OrderList` and `InvoiceList` but it did not work. I had to hack with the debugger to achieve my demo screenshot.

However, the same method on my project which has the latest release works like a charm.

Is there any difference I should take care of?

**Comment by soullivaneuh** [comment]
I also have an another wondering: Where should we apply this rule? Directly on the inputs scope, impacting both the filters and the form displays, or only gather to the filters?

The first option looks seducing to me.

**Comment by fzaninotto** [comment]
Fixed by #9169
