### ISSUE TITLE
setTheme() does not affect login page, new theme is reset after logging out

### ISSUE THREAD

**Issue by PawelSuwinski** [marmelab/react-admin#8805]
**What you were expecting:**
Theme changed programmatically stays after logout.

**What happened instead:**
Theme changed programmatically is reset after logging out. Login page still has an initial theme and after logging in again this initial theme is used as it was before. Is it intentional behavior or a bug?
 
In my app admin user can customise selected theme colours (do some branding) saving it on the server  what is loaded on init. So any newly loaded app will have a new theme but not the one where change was made and admin user  log himself out right after that, not without forcing page to reload (CRTL+R or `router.reload()`). Of course I am aware that any other already loaded app before theme change was made will have old theme, but the case is to not misleading admin user  whether this change was persisted properly or not. 

**Steps to reproduce:**
https://codesandbox.io/p/sandbox/dreamy-colden-8zrcow

1. Go to page and login (user:password) - after 2sec theme is switched to dark mode.
2. Logout  - login page  has old theme
3. Login  again - app use old theme (first 2sec :)

 **Environment**
* React-admin version: 4.8.0/ 4.9.1

**Comment by djhi** [comment]
Indeed, we reset the store on logout. If you want to keep some of the store values, you must provide your own store. The key for the theme is `RaStore.theme`
