### ISSUE TITLE
ReferenceInput shortcut for recordRepresentation

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#8807]
ReferenceInput produces a dropdown (via AutocompleteInput) which displays the available options using the recordRepresentation field. However, when typing, the default query uses `{q: "searchText"}`. It seems like an obvious choice to have the query use the recordRepresentation when filtering, e.g. if it references authors with `recordRepresentation="name"`, then the query could be set to `{name: "searchText"}`.

Currently, I don't see a trivial/obvious way to do this. Maybe it could be possible to add a simple option to set it to this automatically, or to pass the recordRepresentation value to the custom filter function?

**Describe alternatives you've considered**
An application-specific solution that looks up the reference value in the source data to find what the repr value was set to, then uses a closure for the custom filter function.

This unfortunately requires me to special-case the ReferenceInput to make this work correctly. All other components are created from the same code using a JSON schema.

**Comment by djhi** [comment]
You can provide the children yourself in that case.

**Comment by Dreamsorcerer** [comment]
I have, it's just a bit awkward and cumbersome compared to everything else.

I'm not familiar with the architecture, so maybe it's too difficult to do. But, it seems like there should be an obvious way to get the recordRepresentation at this point (given that it uses it for displaying). And as a user, surely you want to filter based on the displayed value 99% of the time.

Currently, I make it work by looking up the recordRepresentation in the source data that is used to generate the components, I don't see any way to get them automatically an an application-agnostic way (e.g. What about just making a custom reusable component which always does `{[reference.recordRepresentation]: searchText}`?)

**Comment by Dreamsorcerer** [comment]
> The issue is that `recordRepresentation` isn't always a string. See https://marmelab.com/react-admin/Resource.html#recordrepresentation

Yep, I just realised that. Making it only useful when it is a string.

> You can however build your own wrapper around the `ReferenceInput` that accept an additional prop that you'll pass to the `AutocompleteInput`.

I'll just stick to my application-specific approach. But, I've converted my awkward code into a new component, which makes things more elegant:
```
const ReferenceInput = (props) => {
    const ref = props["reference"];
    const repr = STATE["resources"][ref]["repr"];
    return (
        <_ReferenceInput {...props}>
            <AutocompleteInput filterToQuery={s => ({[repr]: s})} />
        </_ReferenceInput>
    );
};
```
