### ISSUE TITLE
addRefreshAuthToAuthProvider fails with Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by OoDeLally** [marmelab/react-admin#8808]
**What you were expecting:**
Should run fine as long as I respect `AuthProvider`'s typing

**What happened instead:**

```
Cannot read properties of undefined (reading 'apply')
```

**Steps to reproduce:**

* Create a `AuthProvider` without a `getIdentity` (according to the typing, `getIdentity` is optional)
* `addRefreshAuthToAuthProvider` fails at `return provider[name.toString()](...args);` when `provider` does not have `getIdentity` and `name` is `getIdentity`.

**Comment by djhi** [comment]
Please follow the issue template

**Comment by djhi** [comment]
Nevermind, I see the problem.
