### ISSUE TITLE
TabbedForm's FormTab cannot open first tab if any of tab includes filters

### ISSUE THREAD

**Issue by lexthedev** [marmelab/react-admin#8812]
**What you were expecting:**

One of Form tabs has a list with filters inside. For example tab with a list is 3rd.
- filter content;
- URL modifies and now ends with URL arguments of filters;
- click on 2nd tab -> 2nd tab opens;
- click on 1st tab -> 1st tab opens .

**What happened instead:**
- …
- click on 1st tab -> current tab is still open (the link to the 1st tab is equal to the link to the current tab).

**Steps to reproduce:**
- Create form with tabs;
- Add a list to any tab;
- Add filters to the list;
- Modify filters while browsing app;
- Click on 1st tab.

**Related code:**

```
        <Edit mutationMode="pessimistic">
            <TabbedForm toolbar={<ToolBar />}>
                <FormTab label="TabLabel">
                    {Content}
                </FormTab>
                <FormTab label="TabLabel2">
                    {Content2}
                </FormTab>
                <FormTab label="TabLabel3">
                    <ReferenceManyField label="ReferenceManyFieldLabel" reference="reference" target="target">
                        <ListBase filter={{ target: targetId }} sort={{ field: 'Timestamp', order: 'DESC' }}>
                            <ListToolbarAuditFilters Collection="collection" fieldsList={fieldsList} />
                            <Datagrid empty={<span>{"noData"}</span>} expand={<Expand/>} width="100%">
                                <DateField source='Timestamp' showTime />
                                <TextField source="textSource" fullWidth />
                                <FunctionField label="FunctionFieldLabel" render={(record: any) => record.data + "SomeText" />
                                <AuditEditFields label="AuditEditFieldsLabel" />
                                <ShowButton />
                            </Datagrid>
                            <Pagination />
                        </ListBase >
                    </ReferenceManyField >
                </FormTab>
            </TabbedForm>
        </Edit>
```

**Other information:**

**Environment**

* React-admin version = 4.9.1:
* React version = 18.2.0:
* Browser = Chrome:

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
Try adding the `disableSyncWithLocation` prop to `ListBase`.

https://marmelab.com/react-admin/List.html#disablesyncwithlocation

**Comment by lexthedev** [comment]
> `disableSyncWithLocation`

Thanks to you, works fine). But cannot feel myself free, thinking this is still a bug

**Comment by fzaninotto** [comment]
I disagree this is a bug. This is documented behavior, and you could bypass it easily. 

Thanks for bringing that to our attention though.
