### ISSUE TITLE
Wrap bulkActionButtons

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#8820]
It would be nice to wrap bulkActionButtons when there are a lot of buttons included, similarly to the behaviour of filter inputs.

Currently, this just disappears off the side of the page:

![image](https://user-images.githubusercontent.com/2203121/230774489-3bfe0ad9-4dc7-4ff5-9446-63dba9009ef6.png)

(It could also be nice to have a simple BulkUpdateButton alternative which allows to select from a list of choices (or number range), which would significantly reduce the number of buttons in this example).

**Comment by djhi** [comment]
Can't you build a dropdown button using MUI primives?

**Comment by fzaninotto** [comment]
I agree with @djhi, this is achievable in user land, so react-admin won't handle this (rather rare) case.

**Comment by Dreamsorcerer** [comment]
Why is this a rare case? Surely this is the most common type of bulk update.

The resource has a number field, as a user I want to set several records to the same value at once. Many admin/CMS systems have such an interface builtin.

e.g. From a WordPress backend, where I can change categories, author etc. for all selected posts:
![image](https://user-images.githubusercontent.com/2203121/231143153-c3045e1d-6054-4b88-8ae7-2508d64eab26.png)


Also, don't those comments only apply to the button suggestion? The main request was to wrap the button area.
Even if I build some custom dropdown buttons (which doesn't sound easy to do in a general manner), I would still have atleast 10 buttons there and it would run off the screen if it's not a rather wide screen.

**Comment by fzaninotto** [comment]
I think the Wordpress UX you're showing is bad. The bulk edition form is constrained by the table, and is hard to read. Why not have one "Bulk update" button that opens a dialog where you put all the options?

Anyway, this isn't something we want to implement in react-admin, and react-admin doesn't prevent you from doing it in user land.

**Comment by Dreamsorcerer** [comment]
Didn't say it was a great UX, just showing that it is a very common case to have bulk editing. I'm surprised that's not something you think belongs in react-admin. Maybe I'll have a go sometime, but I'm really trying to just use as much of react-admin's feature set as possible, without needing to learn too much react, MUI etc. (documentation is generally enough that I've not needed to).

It would still be nice to have the button wrap on the occasion there are too many though (on a mobile screen when it converts buttons to a small icon, it still only appears to fit 1 or 2 extra buttons after export/delete before running off the screen...).
