### ISSUE TITLE
An reacthook to toggle the sidebar

### ISSUE THREAD

**Issue by tadstr** [marmelab/react-admin#8836]
**Is your feature request related to a problem? Please describe.**
I want to customize the sidebar and need some logic to change the category text when toggling the sidebar.

**Describe the solution you'd like**
Create react hook to keep track of the sidebar state or some how select the default hamburger of the side bar to use my own state

**Comment by tadstr** [comment]
Tks, it works perfect

**Comment by denzuko** [comment]
This is perfect. Working to add Hotkey.js support and looks like the following is just what I needed:

https://github.com/marmelab/react-admin/blob/efaf26bb80301f4b63a923da1d30502ffc03d00e/docs/Layout.md?plain=1#L285-L291

```
import { useSidebarState } from 'react-admin';
...
const [open, setOpen] = useSidebarState();
const toggleSidebar = () => setOpen(!open);
```
