### ISSUE TITLE
List remains filtered when removing an active filter

### ISSUE THREAD

**Issue by nicgirault** [marmelab/react-admin#8840]
I apologize for rewrite an issue based on [the previous one](https://github.com/marmelab/react-admin/issues/8483) I wrote but as this subject is a regular feedback from my users, I would like to re-explain why I think there is a behavior that should be considered as a bug.

**What you were expecting:**

Let's assume there is a filter on a column "name" `source="name"`. Users are using it. With recent versions of react-admin (since filter state is saved in local storage), the last value of the filter is stored in local storage.

Then the developer (me) is deploying a new version of the app with an enhancement: the name filter is replaced by a search filter `source="q"`. There is no more "name" filter.

As there is no more "name" filter, I would expect the value in the store to be ignored (or removed).

**What happened instead:**

But the query to the API still contain the "name" filter which generate an inconsistency between what the user see (no filter applied) and what is queried to the API (filter on "name").

**Steps to reproduce:**

- add a filter on a list
- put a value in the input
- remove the filter
- the list remains filtered

**Environment**

* React-admin version: 4.9.2

**Comment by slax57** [comment]
I think I understand your point.

However, to me this is still something that needs to be dealt with in user-land.
Indeed, how could RA know that the "name" filter is no longer relevant in your app? You may have additional filters that are not in the filter form and yet could be perfectly valid.

Besides, RA already helps in two ways with this:
- When clicking 'Remove all filters' in the Filter Button, it removes all filters including those not in the filter form
- You can use the [Store invalidation](https://marmelab.com/react-admin/Store.html#store-invalidation) feature if you want to clean user settings after publishing a new version of the app that is not backwards compatible

Or you can, of course, add custom code to detect this case and remove the old filter automatically, leveraging the [`useListContext`](https://marmelab.com/react-admin/useListContext.html) hook to access the `filterValues` value and the `setFilters` callback.

So I'll close this issue for the reasons explained above.
In any case, thanks for raising this question as the answer might still be useful to others! :slightly_smiling_face:

**Comment by nicgirault** [comment]
Thanks for your detailed answer. Store invalidation is a very good point that I did not consider (being able to invalidate a subpart of the store would be appreciable in order not to loose all preferences).

The "Remove all filters" is too hidden so that users are autonomous on fixing this issue.

It seems to me that RA could know what are the "relevant" filters because they are defined in the codebase so filters can register somewhere and with the store keys, RA can compare previously registered filters and currently registered filters.
