### ISSUE TITLE
Disable 'to' property for menuitem

### ISSUE THREAD

**Issue by mphilip9** [marmelab/react-admin#8848]
Is there a way to disable the to property on a menuitem? I basically just want it to act like a simple dropdown menu and not redirect on click.

I have a react admin menu with a submenu, and I want the submenu to expand/collapse on click when you click the title OR the chevron. Right now, if you click the primary text, it triggers the navlink and navigates you to the dashboard (to=''). The dropdown works only if you click the chevron icon. I added a linkDisabled prop to the menuitem that acts as the wrapper for the submenu, but it doesn't work.

I tried another approach where I used mui listItems inside the multilevel menu, but the problem there is that when you click it closes the menu. If there were a way to stop the menu from closing onclick this approach would work best as it triggers the dropdown when you click the chevron or the title.

Here is the component that creates the submenu. The commented out code is what I originally did for the submenu:

    const SubMenuItemMapper = (subGroup, groupName) => {
      const [open, setOpen] = useState(false);
    
      const handleClick = () => {
        setOpen((prev) => !prev);
      };
      let subGroupTools = [];
      let curIcon = <PillarIcon />
      if (subGroup.length > 0) {
        subGroupTools = subGroup.map(MenuItemMapper(groupName));
        curIcon = createElement(subGroup[0].icon);
      }
      return (
        <MultiLevelMenu id="appSubMenu">
           <ListItem button onClick={handleClick}>
            <ListItemIcon>{curIcon}</ListItemIcon>
            <ListItemText primary={subGroup[0].options.subGroup + ` (${subGroupTools.length})`} />
            {open ? <ExpandLess /> : <ExpandMore />}
          </ListItem>
          <Collapse in={open} timeout="auto" unmountOnExit>
            <List component="div" disablePadding>
              {subGroupTools}
            </List>
          </Collapse>
          {/* <MenuItem
            name={subGroup[0].options.subGroup}
            label={subGroup[0].options.subGroup + ` (${subGroupTools.length})`}
            icon={curIcon}
            to={''}
            linkDisabled
          > 
          {subGroupTools}
          </MenuItem> */}
        </MultiLevelMenu>
    )};

And here is the component that renders the submenu:

    const SuperCategory = ({resources, groupName, groupDisplayName, menuItemCategoryClassName, harmoneeTools, arbitraryTools, icon, ...props}) => {
      const classes = useMenuStyles();
      const menuObject = MenuObjectFunc(resources, groupName)
      const subGroup = menuObject.subGroup
      const groupArray = menuObject.groupArray
      let groupTools = []
      let subGroupTools = []
      let curIcon = <SettingsIcon />;
      // TODO: Eventually, we will want the harmonee folder to show up for everyone even if they cant access the admin tool
      // if (groupName !== 'harmonee' && group_array.length === 0) return null;
      if (groupArray.length === 0) return null;
    
      if (Object.keys(subGroup).length > 0) {
        subGroupTools = Object.keys(subGroup).map(subMenu => SubMenuItemMapper(subGroup[subMenu]));
      }
      if (groupArray.length > 0) {
        groupTools = groupArray.map(MenuItemMapper(groupName));
        curIcon = createElement(groupArray[0].icon);
      } else {
        curIcon = <SI2 />;
      }
    
      if(icon) {
        curIcon = icon;
      }
    
      // Grab the first? icon from the resources in the group
      // const curIcon = (groupArray && groupArray.length) > 0 ? createElement(groupArray[0].icon) : <SettingsIcon />;
      // TODO: Default to a different icon maybe?
      return (
        <MenuItemCategory
          key={props.key}
          className={menuItemCategoryClassName}
          name={groupName}
          label={groupDisplayName} // TODO: Harmonee to upperCase
          icon={curIcon}
        >
          <CardContent className={classes.menuCategoryCard}>
            <Typography variant='h5' gutterBottom>{groupDisplayName}</Typography>
            <Menu
            >
              {harmoneeTools ? 
                harmoneeTools.map(tool => (
                  <MenuItem
                    name={tool._id}
                    to={`/dtx/harmonee/tools/${tool._id}/show`}
                    label={tool.title}
                    icon={<SI2 />} // TODO: Custom icons per tool?
                  />
                ))
               : null}
              {groupTools}
              {subGroupTools}
              {arbitraryTools}
            </Menu>
          </CardContent>
        </MenuItemCategory>
      );
    };

Relevant imports:

    import {
      MenuItemLink,
      getResources,
      usePermissions,
      Responsive,
      useQueryWithStore,
    } from 'react-admin';
    import {
      Menu,
      MenuItem,
      MenuItemCategory,
      MultiLevelMenu,
    } from '@react-admin/ra-navigation';
    import { makeStyles } from '@material-ui/core';
    import Typography from '@material-ui/core/Typography';
    import CardContent from '@material-ui/core/CardContent';
    import List from '@material-ui/core/List';
    import ListItem from '@material-ui/core/ListItem';
    import ListItemText from '@material-ui/core/ListItemText';
    import Collapse from '@material-ui/core/Collapse';
    import ListItemIcon from '@material-ui/core/ListItemIcon';
    // Icons
    import ExpandLess from '@material-ui/icons/ExpandLess';
    import ExpandMore from '@material-ui/icons/ExpandMore';

**Comment by slax57** [comment]
Hi,

Your question seems to target the `MultiLevelMenu`component, which is part of the Enterprise Edition of React Admin.

We offer no support for these components on Github, as there is a [dedicated Support Desk](https://marmelab.com/ra-enterprise#support) for Enterprise customers.

Hence I'll close this issue and invite you to ask your question to the [Support Desk](https://marmelab.com/ra-enterprise#support).
