### ISSUE TITLE
Custom AppBar has content aligned all to the left if it has any children 

### ISSUE THREAD

**Issue by zenflow** [marmelab/react-admin#8852]
**What you were expecting:**
I was expecting that after upgrading from 4.8.1 to 4.9.3 there would be no changes in behavior.

**What happened instead:**
The contents of my custom AppBar are now aligned all to the left, including non-custom content like the user dropdown menu.
![image](https://user-images.githubusercontent.com/3198597/233869849-9aafc5e7-e258-4f0e-8727-a680b40261ed.png)
This is only an issue if my custom AppBar has children; otherwise it behaves as normal.

**Steps to reproduce:**

1. Start with a react-admin project
2. Make sure it's using latest react-admin version (4.9.3)
3. Use a custom AppBar like the following:
```
export function MyAppBar(props: AppBarProps) {
  return <AppBar {...props}>Hi</AppBar>;
}
```
4. Observe app bar looking like my screenshot above

**Environment**

* React-admin version: 4.9.3
* Last version that did not exhibit the issue (if applicable): 4.8.1
* React version: 18.2.0
* Browser: Chrome

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by zenflow** [comment]
Thanks @djhi for taking a look and giving a thoughtful response.

I dug a little deeper to find what went wrong.

First off, sorry, as it looks like I made my example code a little too minimal, and it's not helpful at all so please forget it. Sorry again!

Breaking change was introduced in this PR: https://github.com/marmelab/react-admin/pull/8765

My custom AppBar ([here](https://github.com/zenflow/my-stuff-app/blob/ddff70886c30d345271cb69ea497f214116a0674/admin/MyAppBar.tsx#L7-L31)) is implemented according to the previous version of the docs, before TitlePortal was introduced:
https://github.com/marmelab/react-admin/commit/1c33cb6b1fd2d2c8ae103983162250c3ec5f661d#diff-9b95cf09c25d2354b5a5ae297343eac1594148fa8e77c864044f5669bf289eccL31-L40).

That previously documented way no longer works since there are no longer any styles (i.e. `flex: 1`) associated with the `AppBarClasses.title` class:
https://github.com/marmelab/react-admin/commit/1c33cb6b1fd2d2c8ae103983162250c3ec5f661d#diff-a81ad0901aeb0ca1ae0d7907215277afd74ce5e7c9691d1c7c67d1ca7d9952ccR174

Now, even when I integrate the breaking change (by using the new TitlePortal component as documentation instructs), I can't set custom styles on it like before since TitlePortal doesn't take a `sx` or `style` prop.

I can work deal with these issues, but I wonder if the breaking part of those changes could/should be reversed, to maintain backward compatibility, for others going through the upgrade.

Thanks so much and keep up the great work!

**Comment by fzaninotto** [comment]
To make it less breaking change, what if we:

- don't set a className to `TitlePortal` by default

https://github.com/marmelab/react-admin/blob/6b8386e1d33f5d4ae179c1816e40f7302f572009/packages/ra-ui-materialui/src/layout/AppBar.tsx#L76

- re-add the default style content of `AppBarClasses.title`

https://github.com/marmelab/react-admin/blob/6b8386e1d33f5d4ae179c1816e40f7302f572009/packages/ra-ui-materialui/src/layout/AppBar.tsx#L167

Would that work better?

**Comment by zenflow** [comment]
> Would that work better?

I think so, The "re-add the default style content of AppBarClasses.title" point alone would undo the breaking-ness completely I believe, and users would have the option to switch to using TitlePortal if they want to remove the code they duplicated into their project.
