### ISSUE TITLE
Locale language translate issue on <TitlePortal />

### ISSUE THREAD

**Issue by tsudhayakumar1996** [marmelab/react-admin#8860]
**What you were expecting:**

**What happened instead:**

**Steps to reproduce:**

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
You didn't use the issue template, so we can't consider this issue. 

Besides, it's probably fixed in 4.9.4 (see https://github.com/marmelab/react-admin/pull/8846)
