### ISSUE TITLE
ImageInput Improvements: Clear button.

### ISSUE THREAD

**Issue by kav** [marmelab/react-admin#8864]
**Is your feature request related to a problem? Please describe.**
We have a nullable image property in our application. Once an image is set in ImageInput it can't be cleared
 
**Describe the solution you'd like**
I'd love if the imageinput natively supported a standard for clearing the image value.

**Describe alternatives you've considered**
For now we've implemented a wrapper (that also adds support for server provided image urls)
```javascript
import Button from "@mui/material/Button"
import { ImageField, ImageInput, useInput } from "react-admin"
import { useWatch } from "react-hook-form"

const ClearImageInput = ({ source, label }) => {
  const { id, field, fieldState } = useInput({ source })
  return (
    <label htmlFor={id}>
      {label}
      <Button variant="text" onClick={() => field.onChange(null)}>
        Clear {label || source}
      </Button>
      {fieldState.error && <span>{fieldState.error.message}</span>}
    </label>
  )
}

export const ImageInputWithClear = ({ source, label }) => {
  const value = useWatch({ name: source })
  return value ? (
    <>
      <ImageField source={source} />
      <ClearImageInput source={source} />
    </>
  ) : (
    <ImageInput source={source} accept="image/*">
      <ImageField source="src" title="title" />
    </ImageInput>
  )
}
```
**Additional context**

**Comment by slax57** [comment]
>  Once an image is set in ImageInput it can't be cleared

To me it actually **can** be cleared. You just need to click on the remove button (which appears on hover).

![2023-04-28_09-52](https://user-images.githubusercontent.com/14542336/235088964-d24d8f78-f74f-49c2-8273-723b3a4e995e.png)


Am I missing something? :thinking:

**Comment by kav** [comment]
Oh man, how'd I miss that one... Thanks @slax57
