### ISSUE TITLE
disabled `AutocompleteInput` is still editable

### ISSUE THREAD

**Issue by zikowang** [marmelab/react-admin#8866]
**What you were expecting:**
A disabled `AutocompleteInput` should not be enableable when the user is keep on clicking it.

**What happened instead:**
If you keep on clicking the empty space right to the input label the options are shown and selectable.

**Steps to reproduce:**

https://stackblitz.com/edit/github-rj9f7h?file=src%2Fposts%2FPostEdit.tsx

- Go to Posts
- edit a post
- keep on clicking the user input

**Environment**

* React-admin version: 4.9.3
* React version: 18.2.0
* Browser: Chrome Version 107.0.5304.110 (Offizieller Build) (arm64)

**Comment by slax57** [comment]
Reproduced, thanks!

**Comment by slax57** [comment]
Trying to reproduce locally and in our storybook, it seems I can only reproduce the bug when I upgrade to the latest MUI version. Might be an MUI issue then... I'll need to investigate further...
