### ISSUE TITLE
parse prop doesn't work on default value of AutocompleteArrayInput

### ISSUE THREAD

**Issue by dalen** [marmelab/react-admin#8869]
**What you were expecting:**

When adding a `parse` prop to an AutocompleteArrayInput it uses it to change the input value before submitting the form. This should also happen when the AutocompleteArrayInput has its default value of an empty array.

**What happened instead:**

The parse function is never called when the AutocompleteArrayInput has not changed value, and the form is sent with an empty array as value instead.

**Steps to reproduce:**

```
<AutocompleteArrayInput source="attribute" choices={[{ id: 'test', name: 'Test' }]} parse={(val) => val.length} />
```

With default value in a create view this should submit `0` as the attribute value, but it submits `[]` instead.

**Other information:**

**Environment**

* React-admin version: 4.10.1
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
I believe it's the same for all inputs, not only `AutocompleteArrayInput`.
This is the way react-hook-form works.
`defaultValue` should be an already parsed value.

In your case I suggest you use the [`transform` prop](https://marmelab.com/react-admin/Create.html#transform) instead.
