### ISSUE TITLE
Filters + filter not working as expected

### ISSUE THREAD

**Issue by palagonKevo** [marmelab/react-admin#8876]
I'm using a <List> object that is using filters for dynamic filters and filter some permanent filters. The permanent filter is filtering the resource ids for example:
```
filter={{
    "id": [
        1,
        3,
        4,
        6,
        8,
        9,
        10,
        1620,
        1622,
        1623,
        1624,
        1625,
        1626,
        1627,
        1628,
        1630,
        1631,
        1632,
        1633,
        1634,
        1636,
        1638,
        1639,
        1640,
        1641,
        1642,
        1643,
        1645,
        1646,
        1647,
        1648,
        1649,
        1650,
        1651,
        1652,
        1653,
        1654,
        1655,
        1656,
        1657,
        1658,
        1659,
        1660,
        1661,
        1662,
        1663,
        1664,
        1665,
        1666,
        1667,
        1668,
        1669,
        1670,
        1671,
        1673,
        1675,
        1676,
        1678,
        1679,
        1680,
        1681,
        1682,
        1683,
        1684,
        1685,
        -1
    ]
}}
```
And at the same time I would like to be able to filter over those ids with the filters prop using a NumberInput like:
`<NumberInput label='ID' source='id' alwaysOn/>`

**What you were expecting:**

The expected behavior is that List applies and "and" operator to the two types of the filters allowing to filter the already given objects filtered with the permanent filter.

**What happened instead:**
Instead, the values are sent via the context of the list that can be seen by using the useListContext hook, but filter value overrides the filterValues value, ignoring it completely.

**Steps to reproduce:**
Build a <List> of a resource that contains a numeric id and use the prop filter with an array of existing ids (`filter={{id: [1,2,3]}}`), and add a filters prop as well on the same <List> component. In that filters you should add a <Filter> component with a <NumberInput> that has id as the source.

**Related code:**
```
const ListFilters = () => (
   <Filter>
       <NumberInput label='ID' source='id' alwaysOn/>
   </Filter>
)
...
<List
     filter={{id:[1,2,3,4]}}
     filters={<ListFilters>}
>
...
</List>
```

**Environment**

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
```

* React-admin version: ^4.9.2
* React version: ^18.2.0
* Browser: Any

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by slax57** [comment]
Thanks for the sample app.

I don't understand what you are trying to achieve. What is the purpose of the permanent filters? Are they default values ? Or values that you would want to merge with the values selected in the `NumberInput`?

If they are default values, you should use [`filterDefaultValues`](https://marmelab.com/react-admin/List.html#filterdefaultvalues) instead.

If they are to be merged, you should use only `filters` and change your `NumberInput` to something like this:

```tsx
<NumberInput source="id" alwaysOn parse={value => ([parseInt(value), 1, 2, 3, 4, 5, 6, 7, 8])} format={value => String(value[0] ?? '')} />
```

In any case, I don't think there is a bug with react-admin, hence I'll close this issue.
