### ISSUE TITLE
DatagridConfigurable should display label if it's a custom component

### ISSUE THREAD

**Issue by arimet** [marmelab/react-admin#8878]
**What you were expecting:**
When we use a DatagridConfigurable that contains a field with a custom label, this label should be displayed in the header of the Datagrid. 

**What happened instead:**
React-admin display an error: 
```
Converting circular structure to JSON --> starting at object with constructor 'Object' | property '_context' -> object with constructor 'Object' --- property 'Provider' closes the circle
```

**Related code:**
https://stackblitz.com/edit/github-gdk8e3?file=src%2Fposts%2FPostList.tsx

```
 <DatagridConfigurable
      bulkActionButtons={<PostListBulkActions />}
      rowClick={rowClick}
      expand={PostPanel}
      omit={['average_note']}
    >
      <TextField source="id" label={<Typography>Toto</Typography>} />
 </DatagridConfigurable
```

**Environment**

* React-admin version: ^4.10.1
* React version: ^17.0.0
* Browser: Brave
* Stack trace (in case of a JS error):
```
Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_context' -> object with constructor 'Object'
    --- property 'Provider' closes the circle


    at DatagridConfigurable
```

**Comment by djhi** [comment]
Duplicate of #8843?

**Comment by arimet** [comment]
Indeed it is a duplicate
