### ISSUE TITLE
Add an `<InfiniteReferenceManyField>` component

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#8879]
With the new InfiniteList, it would be nice if you could use the same functionality with the `ReferanceManyField`

**Comment by slax57** [comment]
Can you provide more info? Or else we'll have to close this issue :roll_eyes: :sweat_smile:

**Comment by davidhenley** [comment]
I thought it was self explanatory. It was marked as a feature request. With the new InfiniteList, it would be nice if you could use the same functionality with the ReferanceManyInputs.

**Comment by fzaninotto** [comment]
I'm interested in hearing about your use case. What type of related entity would you like to display in an infinite list?

**Comment by fzaninotto** [comment]
Got it, thanks. That's a valid use case. 

We'll gladly accept a PR implementing this. As we don't need it for our own projects, we'll close the issue within a few months if there is no external contribution.

**Comment by fzaninotto** [comment]
There was no contribution from the community about this feature, so I'll close the issue. If anybody wants to work on the feature, we'd gladly accept a PR.

**Comment by kslbdev** [comment]
I needed this feature so I created a couple of wrapper files to enable this support. I apologize for not having time to make the PR at the moment, but will share these files here if anyone want to use them or help carry out a PR with this change [patch files](https://github.com/kslbdev/kslbdev-share/tree/master/react-admin-patch)
