### ISSUE TITLE
ReferenceField not using custom data provider

### ISSUE THREAD

**Issue by JoppeDC** [marmelab/react-admin#8883]
**What you were expecting:**
My dataprovider adds auth headers to all api calls. I'm using Supabase, so we add supabase auth headers.
I'm expecting all components to use this data provider.

Since it appears that this should work, and i cant find any information on this, it is possible that something funky is happening on my side. 

It does that in the following way: 

```
const fetchHydra = async (url, options = {}) => {
  const { data } = await supabase.auth.getSession();
  if (!options.headers) options.headers = new Headers({});

  if (data.session) {
    options.user = {
      authenticated: true,
      token: `Bearer ${data.session.access_token}`,
    };
  }

  return baseFetchHydra(url, {
    ...options,
  });
};

const dataProvider = (setRedirectToLogin) =>
  baseHydraDataProvider({
    entrypoint: process.env.REACT_APP_API_ENTRYPOINT,
    httpClient: fetchHydra,
  });
```

This works as expected for all show/list/edit/create pages.

**What happened instead:**
But when using `ReferenceField` in either show or create/edit pages, these custom headers are not passed to the calls.
After doing some debuggin with console.logs, it appears that this component does not even call the custom dataprovider, but the built in data provider. Therefore, all these components cause request errors because the API returns 401. The data does appear, so it seems to be doing multiple API calls. One with the custom data provider, and one without.

**Environment**

* React-admin version: react-admin@4.10.1
* React version: react@18.2.0 | MIT | deps: 1 | versions: 1311
* Browser: NA

**Comment by slax57** [comment]
Internally `ReferenceField` gets the `dataProvider` using the `useDataProvider` hook, just like any other component in RA.

Hence I don't think the problem comes from RA but rather from the dataProvider you are using.

Where does your `baseHydraDataProvider` come from?
Did you try using [ra-supabase](https://github.com/marmelab/ra-supabase)?

**Comment by fzaninotto** [comment]
This is a problem with the hydra provider, which isn't maintained by the react-admin core team. Please open an issue in their registry.
