### ISSUE TITLE
data-generator-retail v4.10.2 incorrectly built

### ISSUE THREAD

**Issue by eliahuama** [marmelab/react-admin#8890]
Looks like the package versioned v4.10.2 was incorrectly published to registry, because it laks dist/esm folder.
Its easily fixed by building from source in react-admin/examples/data-generator, yet the expected behaviour'd better be to pull correct package.
So please, republish this version to registry with all dist in there.

**Comment by djhi** [comment]
Thanks for reporting!

**Comment by fzaninotto** [comment]
This will have to wait until next Friday, when we release the next bug fix release (4.10.3). 

In the meantime, you can use the previous version of the library. 

Out of curiosity, what do you use it for?

**Comment by fzaninotto** [comment]
Fixed in v4.10.3 https://www.npmjs.com/package/data-generator-retail

**Comment by NisargPatel310** [comment]
Hello, I have cloned the repo and trying to run the demo and it's given me this error:
[plugin:vite:import-analysis] Failed to resolve entry for package "data-generator-retail". The package may have incorrect main/module/exports specified in its package.json.
I have researched about it, but I can not find any proper solution.
Any help would be appreciated.
