### ISSUE TITLE
<ReferenceField> and <ReferenceInput> problem in referencing multiple field in same table

### ISSUE THREAD

**Issue by Slntswrd** [marmelab/react-admin#8897]
Hi to all,

I have a problem after the migration from RA 3 to 4 on `<ReferenceInput>` and `<ReferenceField>`.
I have a situation like this with my resource tables:

```
 ┌─────────┐         ┌────────────────┐
 │locations│         │movements       │
 ├─────────┤         ├────────────────┤
 │id       ├────┐    │id              │
 │Name     │    ├────┤locationStart_fk│
 │etc      │    └────┤locationEnd_fk  │
 └─────────┘         └────────────────┘

```
But when I use:
```
// In movimentsList (the list used for render the movements table)

<ReferenceField 
    label = "Location Start"
    link = {false}
    source = "locationStart_fk"
    reference = "location" 
  >
    <TextField source="name" />
  </ReferenceField>

  <ReferenceField 
    label = "Location End"
    source = "locationEnd_fk"
    link = {false}
    reference = "location" 
  >
    <TextField source="name" />
  </ReferenceField>
```
I only get the value for the first one. I have tried to switch position of the fields and only the firts is rendered. Before version 4 this code was working fine as intended.

The same problem is also in `<ReferenceInput>` for same values in edit mode.

There is something that i have missed during migration process? Or this is some sort of bug?

Best regards

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).
