### ISSUE TITLE
Datagrid isRowSelectable not hiding checkbox

### ISSUE THREAD

**Issue by EdwinCL** [marmelab/react-admin#8900]
**What you were expecting:**

According to the documentation, when Datagrid isRowSelectable prop set to false, it will hide the selection checkbox.

**What happened instead:**

The selection checkbox is disabled instead

**Steps to reproduce:**

From the tutorial app, add `isRowSelectable={() => false}` to the datagrid

**Related code:**

**Other information:**

**Environment**

* React-admin version: 4.10.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Firefox
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
This behavior was changed in #8650.
But you are right, the documentation needs to be updated
