### ISSUE TITLE
Basename gets duplicated upon redirect with new version of "react-router-dom"

### ISSUE THREAD

**Issue by FroYo425** [marmelab/react-admin#8904]
With v6.11.1 of "react-router-dom" the URL basename is added double. If you configured "my-basename" as basename in the router you are redirected to URLs like "example.com/my-basename/my-basename/rest-of-path". Maybe the problem is [here](https://github.com/marmelab/react-admin/blob/a408de0db2c6db0281b3d39e27c1f2de3deed44e/packages/ra-core/src/routing/resolveRedirectTo.ts) in the resolveRedirectTo function as the basename is now added by react-router since the latest updates.

**What you were expecting:**
single basename

**What happened instead:**
duplicate basename

**Environment**

* React-admin version: 4.10.2
* React version: 18.2.0

**Comment by slax57** [comment]
Thanks for reporting this. Can you please provide a sample application showing the issue by forking the following [Stackblitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple)?

**Comment by fzaninotto** [comment]
If that's confirmed, that's a major breaking change by the react-router team.

**Comment by FroYo425** [comment]
Problem solved with v6.11.2 of "react-router-dom"
