### ISSUE TITLE
mutationMode for ReferenceManyField

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#8913]
**What you were expecting:**
When using Datagrid in ReferenceManyField (and related fields), mutationMode should work (tried setting on Datagrid, ReferenceManyField and Show components).

There should be somewhere to set the mutationMode for a Datagrid in a ReferenceManyField on a Show page.
Or, even better, just some way to set it globally across the application.

**What happened instead:**
Doesn't work, no documentation to suggest it even should work currently (documentation only shows mutationMode set on Edit and BulkUpdateButton).

**Steps to reproduce:**
Use a Datagrid in a ReferenceManyField on a Show page.

**Related code:**
Something like:
```
<Show>
  <SimpleShowLayout>
    <ReferenceManyField ...>
      <Datagrid ...>
        ...
      </Datagrid>
    </ReferenceManyField>
  </SimpleShowLayout>
</Show>
```

**Comment by Dreamsorcerer** [comment]
Not sure how that makes a difference, but updated it.

**Comment by fzaninotto** [comment]
> mutationMode should work

> Doesn't work

This is not a bug description. We need to understand what you're actually trying to do, and the result you have instead.

**Comment by Dreamsorcerer** [comment]
I'm trying to set mutationMode on a datagrid in a show view.

There is no component shown in the documentation that appears to accept `mutationMode`. I'm not sure what more information I can give you. The documentation does not include this use case at all, so what do you want me to try?

**Comment by Dreamsorcerer** [comment]
Maybe the missing detail, if it wasn't obvious, as that a datagrid supports bulk actions (like delete). So, it's these actions that are not using `mutationMode`.

**Comment by fzaninotto** [comment]
Did you try passing a custom `<BulkDeleteButton mutationMode="pessimistic" />` as the `<Datagrid bulkActionButtons>` prop?

https://marmelab.com/react-admin/Buttons.html#bulkdeletebutton

**Comment by Dreamsorcerer** [comment]
OK, that works, just seems non-obvious when it's not needed in the list view. Maybe a note in Datagrid or the ReferenceManyField example, so people searching for mutationMode will find it.
