### ISSUE TITLE
The "id" field for the RaRecord type at Create makes no sense

### ISSUE THREAD

**Issue by PavelTankovich** [marmelab/react-admin#8921]
**What you were expecting:**
I do not expect an error because my request in the body does not require an id

**What happened instead:**
I'm getting a "TS2344: Type 'MyTypeDto' does not satisfy the constraint 'RaRecord'.   Property 'id' is missing in type 'MyTypeDto' but required in type 'RaRecord'" error

**Steps to reproduce:**
Add a type without an "id" field and pass in the generic type for the Create component

**Related code:**
```
import { Create } from 'react-admin';

type MyTypeDto = {
  name: string;
  someKey: string;
};

export default function CreateDetails() {
  return (
    <Create<MyTypeDto> title="Add Details" resource="send-to">
      ...
    </Create>
  );
}
```

**Environment**

* React-admin version: 4.9.0
* React version: 18.2.0
* Stack trace (in case of a JS error): TS types.d.ts(9, 5): 'id' is declared here.

**Comment by PavelTankovich** [comment]
@djhi The same problem applies to Edit and Show, could you extend the changes to these components as well, please

**Comment by fzaninotto** [comment]
No, un Edit and Show, react-admin needs a Record with an id.
