### ISSUE TITLE
The response to 'getList' must be like { data : [...] }

### ISSUE THREAD

**Issue by priyatamnayakwsp** [marmelab/react-admin#8926]
Am getting the below error

**data provider:  ra-data-simple-rest**
data api output:
[
    {
        "publishStart": "2023-05-26",
        "published": "d",
        "created": "2023-05-19",
        "modifiedbyId": "w",
        "description": "dd",
        "id": "36",
        "createdbyId": "w",
        "modified": "2023-05-19",
        "publishEnd": "2023-06-02",
        "type": "w",
        "title": "dd"
    },
    {
        "publishStart": "17-05-2023",
        "published": "patch_test",
        "created": "17-05-2023",
        "modifiedbyId": "test",
        "description": "test",
        "id": "2",
        "createdbyId": "test",
        "modified": "17-05-2023",
        "publishEnd": "17-05-2023",
        "title": "test",
        "type": "test"
    },
    {
        "published": "4",
        "modifiedbyId": "3",
        "description": "4",
        "id": "1",
        "createdbyId": "1",
        "type": "3",
        "title": "4"
    },
    {
        "publishStart": "2023-06-03",
        "published": "w",
        "created": "2023-05-04",
        "modifiedbyId": "d",
        "description": "d",
        "id": "34",
        "createdbyId": "w",
        "modified": "2023-05-11",
        "publishEnd": "2023-05-27",
        "type": "d",
        "title": "d"
    },
    {
        "publishStart": "17-05-2023",
        "published": "patch_test",
        "created": "17-05-2023",
        "modifiedbyId": "test",
        "description": "test",
        "id": "3",
        "createdbyId": "test",
        "modified": "17-05-2023",
        "publishEnd": "17-05-2023",
        "title": "test",
        "type": "test"
    },
    {
        "publishStart": "2023-05-26",
        "published": "d",
        "created": "2023-05-19",
        "modifiedbyId": "w",
        "description": "dd",
        "id": "39",
        "createdbyId": "w",
        "modified": "2023-05-19",
        "publishEnd": "2023-06-02",
        "type": "w",
        "title": "dd"
    }
]

**Error:**
**### react_devtools_backend_compact.js:2367 The response to 'getList' must be like { data : [...] }, but the received data is not an array. The dataProvider is probably wrong for 'getList'
overrideMethod @ react_devtools_backend_compact.js:2367**
validateResponseFormat @ validateResponseFormat.js:15
(anonymous) @ performPessimisticQuery.js:42
Promise.then (async)
performPessimisticQuery @ performPessimisticQuery.js:36
doQuery @ doQuery.js:59
(anonymous) @ useDataProvider.js:188
(anonymous) @ useQueryWithStore.js:196
(anonymous) @ useQueryWithStore.js:195
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react_devtools_backend_compact.js:2367 Error: ra.notification.data_provider_error
    at validateResponseFormat (validateResponseFormat.js:16:1)
    at performPessimisticQuery.js:42:1

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
