### ISSUE TITLE
conditionally visible column disappears from DatagridConfigurable and column visibility switcher is bugged

### ISSUE THREAD

**Issue by dkocich** [marmelab/react-admin#8927]
**What you were expecting:**

the column is shown, visibility switched should work changing the visibility of a correct column. Typescript error might appear that the `DatagridConfigurable` does not expect null as children. This is hard to spot that we miss one column there in the app with 80 lists.

**What happened instead:**

I used the condition to show one column only in dev mode, and it happened that on PROD the first column was missing from the list
```
          <DatagridConfigurable bulkActionButtons={false}>
            {isLocalhost() && (
              <TextField
                emptyText={NUL}
                label="id"
                sortable={isVehiclePropSortable("id")}
                source="id"
              />
            )}
```
and the column switcher was not switching the visibility of the correct columns, it switched some other columns

![Screenshot 2023-05-19 at 12 39 01](https://github.com/marmelab/react-admin/assets/6165660/558b62e9-1022-445b-90d6-95a069c8ce24)

Probably the solution is to use `{isLocalhost() ? ... : <Fragment/>` instead - then the first column of a table is visible again and the visibility switcher works. (but switcher shows "hidden" column as "unlabelled column" which does nothing)

...

**Steps to reproduce:**

**Related code:**
https://stackblitz.com/edit/github-tpakk4?file=src%2Fposts%2FPostList.tsx,src%2Findex.tsx,src%2Fposts%2Findex.tsx
- in `PostList.tsx` you can see the first column as conditionally hidden, it does not appear on the page - then switching the visibility of any column hides a different one

**Other information:**

**Environment**

* React-admin version:
*     "react-admin": "4.8.4",
* Last version that did not exhibit the issue (if applicable): not sure
* React version:
*     "react": "18.2.0",
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Please provide a way to reproduce the error

**Comment by dkocich** [comment]
@fzaninotto 
https://stackblitz.com/edit/github-tpakk4?file=src%2Fposts%2FPostList.tsx,src%2Findex.tsx,src%2Fposts%2Findex.tsx
- in `PostList.tsx` you can see the first column as conditionally hidden, it does not appear on the page - then switching the visibility of any column hides a different one
![Screenshot 2023-05-19 at 15 36 12](https://github.com/marmelab/react-admin/assets/6165660/4abc70c5-2acd-4fbc-9658-30ddf6d2c7e6)

**Comment by fzaninotto** [comment]
Reproduced, thanks.
