### ISSUE TITLE
linking-two-inputs：The value in the second input is not reset.

### ISSUE THREAD

**Issue by nptry** [marmelab/react-admin#8943]
[linking-two-inputs](https://marmelab.com/react-admin/Inputs.html#linking-two-inputs)

1. Select a country. 
2. Select a city. 
3. Clear the selection in the countries input. 
4. The value in the cities input remains unchanged. 

I need a solution to clear the value in the cities input when the selection in the countries input is cleared (for use in List Filters), but I have searched for a long time and have not found a solution. 
Can anyone help?

**Comment by djhi** [comment]
Please follow the issue template

**Comment by windsome** [comment]
@nptry  how to deal with this problem?
