### ISSUE TITLE
Command Palette for React Admin

### ISSUE THREAD

**Issue by MarkSFrancis** [marmelab/react-admin#8948]
React admin is heavily designed with power users in mind. The problem is that it can require multiple clicks to get to common pages (like creating a resource requires you to first navigate to the resource, then click "Create")

Command palettes are a proven tool to help enable power users with these types of issues. 

I think a command palette for commands like "Create {resource}" then automatically navigating to the "create" component for that resource would be a great addition to `react-admin`. Similarly for "Search {resource}", delete operations, edit operations, and more.

If it's helpful, I've used [react-cmdk](https://github.com/albingroen/react-cmdk) as a command palette for similar projects

**Comment by djhi** [comment]
This could be done in a dedicated package outside the core monorepo. We probably won't invest time on this but feel free to create and publish this package. We'll gladly include it in the documentation
