### ISSUE TITLE
Loading/Rendering of edit-pages stalls for large embedded arrays of objects (using <ArrayInput> and <SimpleFormIterator>)

### ISSUE THREAD

**Issue by poe42** [marmelab/react-admin#8949]
**What you were expecting:**

When using a <SimpleFormIterator> inside an <ArrayInput> component for editing embedded arrays of objects, I expect it to be sufficiently performant for common quantities of entries (25+ entries, 5+ attributes).

**What happened instead:**

When I want to edit an object with an embedded array of objects (of size _n_), each with a given number of attributes (of size _m_), the apps' responsiveness (while loading/rendering the edit page) significantly decreases with increasing _n_ or _m_.
E.g. we have one use case where we have approx 180 entries with two simple attributes (<TextInput> + <NumberInput>) which takes almost one minute for the edit page to load.

**Steps to reproduce:**

Go to the provided minimal [simple example (v4)](https://stackblitz.com/edit/github-rwg7tb?file=src%2Fposts%2FPostEdit.tsx,src%2Fdata.tsx) and click the first post ("Fusce massa lorem ...") which will redirect to its edit page, allowing to edit the _backlinks_ property only (the provided dummy data consists of 30 entries with 6 attributes each). You will notice a significant delay before the page shows up, which will increase noticeably the more entries there are.

**Other information:**
The effect seems to be sensitive to the input components used (e.g. it is heavy for <Text||NumberInputs>, but not significant for single <BooleanInput> attributes). According to my profiler there seems to be an issue with the _CSS parsing_.

**Environment**
* React-admin version: 4.10.6
* React version: 18.2.0
* Browser: firefox + chrome-based

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback. 

Having profiled your example, I see nothing unusual:

![image](https://github.com/marmelab/react-admin/assets/99944/7fe9520c-f21d-462f-984a-820f105d78d3)

I see ArrayInput renders twice, and I'm not sure why. This means we could potentially divide the render time by two, but the render time will still increase as you add more inputs. 

material-ui inputs are slow, and as there are many of them, React struggles to render them. Using material-ui or react-admin inputs, this will always be slow. Try using native inputs to see the baseline performance for your use case.

**Comment by djhi** [comment]
I can't reproduce this issue on the latest release (4.11.3). I tried with a CPU throttle x6. Feel free to reopen if needed
