### ISSUE TITLE
Ability to style emptyText on fields

### ISSUE THREAD

**Issue by elstgav** [marmelab/react-admin#8951]
# Problem

We would like to visually distinguish fields with `emptyText`, as it makes it easier to scan data. For example, here we use an `emptyText` of `"NULL"`, and mute the color:

<img width="858" alt="Google Chrome - AIQ Console  development  - 2023-05-26 at 10 38 05 AM" src="https://github.com/marmelab/react-admin/assets/674092/2412066d-54f9-4da6-81c2-423c850710e9">

The problem is standard fields don’t expose any info on whether they’re displaying `emptyText`, so we have no way to style them, and `emptyText` can only be set to a `string`, which offers no flexibility.

# Proposed solution

[Invert control](https://kentcdodds.com/blog/inversion-of-control) by allowing a React component for `emptyText`, e.g.

```tsx
<TextField source="foo" emptyText={<code>Null</code>}/>
```
> Note that this previously worked; before https://github.com/marmelab/react-admin/pull/8924 added `emptyText` translation

It would also be helpful to add a consistent class when `emptyText` is shown, e.g. `.RaField-isEmptyText`.

# Workarounds

Currently we have to make our own custom duplicates of standard Field components, that add styling if the value is `null`. This replicates existing component logic in react-admin and is fairly brittle as react-admin changes.

**Comment by fzaninotto** [comment]
The change in #8924 can be made backwards compatible by testing that the `emptyText` is a string before translating it. I think that's the right fix. 

We could also add a class name to the enclosing `Typography` in case of empty value - that would ease styling. 

In any case, your PR is welcome!

**Comment by andrey-programmist** [comment]
@fzaninotto how about the case when create button or other component should be shown if referenced record is null/undefined ?

**Comment by fzaninotto** [comment]
This feature request hasn't received enough traction from the community, so we're closing it. 

If you feel like working on this feature, we'll gladly accept a PR.
