### ISSUE TITLE
React-admin routing issue: Component not found after pushing to GitHub and pulling on another machine

### ISSUE THREAD

**Issue by RoniJackVituli** [marmelab/react-admin#8968]
I am experiencing a routing issue with React-Admin when using a custom component within the `<Resource>` tag. Here's the problem:

I have successfully installed and configured React-Admin in my project following the documentation provided at React-Admin Tutorial (https://marmelab.com/react-admin/Tutorial.html). Locally, everything works as expected, including routing to the /dashboard/admin route. However, when I push the project to GitHub and my friend pulls it, the routing to the dashboard component fails on their local environment and in production.

Here's the relevant code snippet from my App.tsx file, which serves as the parent component:
```
import React from "react";
import { useSelector } from "react-redux";
import { BrowserRouter as Router, Route, Navigate, Routes } from "react-router-dom";
import { RootState } from "./types";
import Auth from "./components/Auth";
import ToastContainer from "./components/ToastContainer";
import AdminWeb from "./components/AdminWeb";
import UserPage from "./components/UserPage";

const App = () => {
  const { isAuthenticated } = useSelector((state: RootState) => state.token);
  const admin = useSelector((state: RootState) => state.admin.admin);

  return (
    <Router>
      {authWindow.open && <Auth type={authWindow.type} />}
      <ToastContainer />
      <Routes>
        {isAuthenticated && (
          <>
            {admin && <Route path="/dashboard/admin" element={<AdminWeb />} />}
            <Route path="/account" element={<UserPage />} />
            <Route path="/account/:id" element={<UserPage />} />
          </>
        )}

        <Route path="*" element={<Navigate to="/home" />} />
      </Routes>
    </Router>
  );
};

export default App;
```

In the above code, the AdminWeb component is responsible for rendering the dashboard. Here's the simplified code for that component:

```
import React from "react";
import { Admin, Resource } from "react-admin";
import dataProvider from "./dataProvider";
import UserList from "./UsersList/UsersList";
import ContainerPage from "../../Layout/ContainerPage/ContainerPage";
import "./check.css";

const AdminWeb = () => {
  return (
    <ContainerPage>
      <Admin dataProvider={dataProvider}>
        <Resource name="users/all" list={UserList} />
      </Admin>
    </ContainerPage>
  );
};

export default AdminWeb;
```

Strangely, if I remove the following line from the AdminWeb component, the routing works as expected:

`<Resource name="users/all" list={UserList} />
`

However, as soon as I add it back, the routing fails and redirects to the home page.

I'm unable to understand why this issue occurs only when the code is pulled onto a different machine or deployed in production. I suspect there might be an issue with the data provider or the resource configuration.

Any help or suggestions to resolve this routing issue would be greatly appreciated.

Thank you!

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
