### ISSUE TITLE
Responsive issue in Simple example

### ISSUE THREAD

**Issue by Nitix** [marmelab/react-admin#8973]
**What you were expecting:**
A beautiful example with responsive behavior

**What happened instead:**
![image](https://github.com/marmelab/react-admin/assets/5849835/4a23d3db-8e9b-4dda-bc3d-34ca97612871)

**Steps to reproduce:**
Launch the example, and go to [tag list(https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=src%2Fcomments%2FCommentCreate.tsx)

**Related code:**
https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=src%2Fcomments%2FCommentCreate.ts

**Environment**

* React-admin version: 4.11.1
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Firefox 113.0.1
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Good catch! I'm on it.
