### ISSUE TITLE
support navigate options in rowClick

### ISSUE THREAD

**Issue by lumpov** [marmelab/react-admin#8987]
**Is your feature request related to a problem? Please describe.**

Using function `(id, resource, record) => 'url'` in `rowClick` prop of `Datagrid` I cannot navigate the state.

**Describe the solution you'd like**

Solution is change this line https://github.com/marmelab/react-admin/blob/6a8b1c9d9d485cc042c90a71c32d208d06d1789d/packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx#LL128C28-L128C28 to:

``` typescript
navigate(type.to ? type.to : type, type.options ? type.options : undefined);
```

and function `(id, resource, record) =>` may return the object (for example):

``` json
{
"to": "path/to/",
"options": {
  "state": { "parent": "parent" }
}
```

to full support of `navigate` in https://reactrouter.com/en/main/hooks/use-navigate

**Additional context**

Sorry, that is small changes for PR.

**Comment by fzaninotto** [comment]
I agree, this is achievable in user land, no need for a change in react-admin.
