### ISSUE TITLE
Docs page on website re: next.js has bad link to gettingstarted.md page

### ISSUE THREAD

**Issue by weisisheng** [marmelab/react-admin#9003]
**What you were expecting:**

Access getting started page from next.js setup page.

**What happened instead:**

#404 

**Steps to reproduce:**

Click on hyperlink ''https://marmelab.com/react-admin/GettingStarted.md" at bottom of page

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report!
