### ISSUE TITLE
Disconnect in next.js example re: /src, no-src setup.

### ISSUE THREAD

**Issue by weisisheng** [marmelab/react-admin#9004]
**What you were expecting:**

Easy to set-up next.js example with pages directory

**What happened instead:**

Initial setup instructions install without /src directory.

But 'pages' example uses /src/admin/-->"// in src/admin/App.jsx" throughout.

**Steps to reproduce:**

install with setup instructions.
try to set up toy/example admin pages for dashboard
can't access 

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
You're right, this is misleading.
