### ISSUE TITLE
Chipfields that are part of a Reference array have black text, while Chipfields that are singular inherit from primary palette

### ISSUE THREAD

**Issue by dnk8n** [marmelab/react-admin#9008]
**What you were expecting:**
I expected Chipfields to look the same regardless of whether they are part of a Reference array or single Reference, perhaps there could be a prop that allows the developer to define whether they want link highlighting or not

**What happened instead:**
Single Chipfield text take on the color of what is defined in theme as primary palette, while Chipfields as part of a reference array take on black text.

What I mean by a single Chipfield:
```
        <ReferenceField
          label="Employee"
          source="user.id"
          reference="employees"
          sortBy="user->name"
          link="show"
        >
          <ChipField
            source="username"
            size="small"
            clickable
            sx={{
              '&.RaChipField-chip': {
                color: theme.palette?.chipFieldText?.main ?? 'rgba(0, 0, 0, 0.87)',
              },
            }}
          />
        </ReferenceField>
```

What I mean by a Chipfield as part of an array:

```
        <ReferenceArrayField label="Members" source="member_ids" reference="employees">
          <SingleFieldList linkType="show">
            <ChipField source="username" size="small" clickable />
          </SingleFieldList>
        </ReferenceArrayField>
```

Note: I have included my workaround to ensure that they are the same. Maybe there is something simpler? 'theme' is constructed by `const [theme, setTheme] = useTheme();`

And theme is created like this:
```
declare module '@mui/material/styles' {
  interface PaletteOptions {
    chipFieldText?: {
      main: string;
    };
  }
}

const chipFieldTextColor = 'rgba(0, 0, 0, 0.87)';
const theme = {
  ...defaultTheme,
  palette: {
    primary: {
      main: import.meta.env.VITE_PALETTE_PRIMARY || '#330808',
    },
    secondary: {
      main: import.meta.env.VITE_PALETTE_SECONDARY || '#A32122',
    },
    chipFieldText: {
      main: chipFieldTextColor,
    },
  },
  components: {
    ...defaultTheme.components,
    RaChipField: {
      styleOverrides: {
        root: {
          '&.RaChipField-chip': {
            color: chipFieldTextColor,
          },
        },
      },
    },
  },
};
```
I had initially hoped to be able to remove the individual sx props from each singular theme by this workaround, but it seems that the component theme definition over here also only applies to array chipfields (maybe this is the root of the problem?)

**Environment**

* React-admin version: 4.9.0
* Last version that did not exhibit the issue (if applicable): NA
* React version: 18.2.0
* Browser: All
* Stack trace (in case of a JS error): NA

**Comment by dnk8n** [comment]
As someone pretty fresh to React in general, and kind of learning as much as I need to get react-admin working, I would say the most important thing is a document change. So if this can be solved in userland, add some docs that explain that things might not work as expected but here is how to make it work like you intend it.

As for a solution. I personally hate automatically highlighted/coloured (hyperlinked/underlined) so as long as by default there is no weird blue text, then I think it is good. I prefer the original as you have displayed. I think it should look more like the original even for singlular chipfields.

I didn't think to change things at the SingleFieldList. From a usability point of view, I can't think of a reason why anyone would want Chipfields to look different whether they are in an array or singular. I prefer the way it defaults in array (as you have screenshott as original).

In both cases, if the user wants colored text they can implement it, following a little example provided by React-admin in the documentation.

What are your thoughts? Please let me know where you agree/disagree. That way I can be as helpful in producing quality feedback.

**Comment by dnk8n** [comment]
Yeah, but in my opinion if clickable is set to true, the chip field becomes
more of a button and definitely in that case the text should default to the
usual color for text. As a user I would prefer to have control over (to be
consistent with everything else in the app) whether hyperlinks are coloured
or not.

Even if traditionally, links have been coloured I still think it is a lame
default in the modern age, more appropriate to word processing than web
applications. Explicit is better than implicit. Do I want a chip field, do
I want it clickable, do I want it's text highlighted? These are all
different questions that should be explicitly answered.

**Comment by djhi** [comment]
> If it's a link, it should look like it. In this rationale I'd even consider it to be a fix, not a change.

I agree

**Comment by dnk8n** [comment]
How is a chip field I link? I pretty much use it so that it looks more
beautiful than a text link. It makes sense to underline and colour a text
link by default, but does it make sense to underline and colour a chip
field (which itself could be of a clashing colour). The fact that when
clickable={true}, the chipfield reacts with changing colour is a much more
rich representation of a hyperlink, it doesn't also need what was designed
for bare text.

**Comment by fzaninotto** [comment]
So after reading your feedbacks, I think we should default to link color in children of SingleFieldList as well - provided there is a link to, which should not be the case for `<ArrayFields>`. I'll open a PR to clarify that.
