### ISSUE TITLE
RadioButtonGroupInput changes value of another RadioButtonGroupInput on the same page when clicking on labels

### ISSUE THREAD

**Issue by sebashwa** [marmelab/react-admin#9013]
When using `RadioButtonGroupInput` component twice on a page inside `EditBase` -> `SimpleForm` the behaviour is weird when clicking on the label of the radio button of the latter `RadioButtonGroupInput`. Clicking on the radio button itself works fine. The problem seems only to occur when clicking on the label.

**What you were expecting:**
I was expecting that only the value of the `RadioButtonGroupInput` I'm editing is changing.

**What happened instead:**
The value of the `RadioButtonGroupInput` in the other form is changing.

**Steps to reproduce:**
Put `EditBase` -> `SimpleForm` -> `RadioButtonGroupInput` twice on a page and change the value of the latter one by clicking on a label.

**Related code:**
See this example: https://stackblitz.com/edit/github-c9pyza?file=src%2Fposts%2FPostEdit.tsx

**Environment**

* React-admin version: ^4.11.2
* React version: ^17.0.0

Thanks for your work on this project!

**Comment by fzaninotto** [comment]
In your StackBlitz, both inputs have the same `source`. This leads to the same id for the options label. IMO that's a normal behavior. If you use different sources, the problem disappears.

I don't see any valid use case for having two RadioButtonGroupInputs with the same source in the page. Can you explain why you're doing it?

**Comment by sebashwa** [comment]
Thanks for your reply. 

I'd like to use multiple edit forms of the same resource (for different records) on the same page. In addition to `source` and `choice` id, do you think it could be feasible to also use the record `id` (and maybe also `resource`) that are passed to `EditBase` to generate the `id` of the resulting `input` and the corresponding `for` of the resulting `label`?

**Comment by fzaninotto** [comment]
Thanks for your answer. 

All inputs accept an `id` prop to manually link the label to the input, however there is a bug in `RadioButtonGroupInput` as this `id` is ignored in radio buttons. I'm marking this as a bug.
