### ISSUE TITLE
Content-Range header is missing in the HTTP Response - jsonplaceholder

### ISSUE THREAD

**Issue by eboss-dev** [marmelab/react-admin#9023]
Hello I'm trying to get used to react-admin using the tutorial. Unfortunately I couldn't proceed further due to a missing header as stateted above.

**What you were expecting:**
Expected list of user inside the table component. 

**What happened instead:**
The data is fetched correctly but since the header is not set up the client couldn't process the users and throw an error

**Steps to reproduce:**
Stricly follow the tutorial located in https://marmelab.com/react-admin/Tutorial.html

![img 2023-06-17 100149](https://github.com/marmelab/react-admin/assets/55625101/58b857b3-cadf-4690-b1e6-ddb170fcb1b8)
![img 2023-06-17 095143](https://github.com/marmelab/react-admin/assets/55625101/a067d995-8ddc-4a19-92ea-2003884f1903)

**Environment**

* React-admin version: 4.11.3
* React version: 18.2.0
* Browser: Firefox 114.0.1

**Comment by fzaninotto** [comment]
I can't reproduce the problem you're describing. Did you, by any chance, choose "Simple Rest" instead of "JSON Server" in the first question asked by `create-react-admin`?

**Comment by eboss-dev** [comment]
Yes you were right, thanks
