### ISSUE TITLE
DeleteButton styling 

### ISSUE THREAD

**Issue by guilbill** [marmelab/react-admin#9050]
**What you were expecting:**
When using `<DeleteButton/>` I'd expect it to use the palette defined in my custom theme, especially `color` and `contrastText`.

```
  <DeleteButton
    variant="contained"
    color="primary"
    label="Delete"
  />
```
I'd expect to have : 
![image](https://github.com/marmelab/react-admin/assets/560852/ab417025-9fac-4dad-aa16-a25f00188a1b)

**What happened instead:**

With the upper code I end up with this :

![image](https://github.com/marmelab/react-admin/assets/560852/21e9b26b-e3a3-42fa-a0c2-f3e412664536)

**Steps to reproduce:**

With the following theme :
```ts
export const theme = {
  ...defaultTheme,
  palette: {
    primary: {
      light: colors.orange[100],
      main: colors.orange[500],
      contrastText: colors.anthracite[50],
    },
    error: {
      main: colors.orange[500],
    },
  },
};
```

Add the DeleteButton like in the upper code.

**Related code:**

https://stackblitz.com/edit/github-uos7fp?file=src%2Fcomments%2FCommentEdit.tsx
https://stackblitz.com/edit/github-uos7fp?file=src%2Ftheme.ts

**Other information:**

**Environment**

* React-admin version: 4.11.4
* React version: 18.2.0
* Browser: [Version 1.52.126 Chromium: 114.0.5735.133 (Build officiel) (64 bits)](https://brave.com/latest/)

**Other information:**

I have a workaround :
```tsx
<DeleteButton
  variant="contained"
  color="primary"
  sx={{ color: colors.anthracite[50], '&:hover': { color: colors.orange[500] } }} />
```

**Comment by adguernier** [comment]
Reproduced by going to the edit view of a comment.
Thanks for your report.
