### ISSUE TITLE
a resource does not list while i have no errors or request issue

### ISSUE THREAD

**Issue by Ali00Naghiloo** [marmelab/react-admin#9051]
**What you were expecting:**
my request is 200 status and my components are fine and i expected to list

**What happened instead:**
did not list it

**Steps to reproduce:**
the name for that resource was like this :
name="category/recommended"

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.10.1
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by Ali00Naghiloo** [comment]
> Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).

sorry but i have some issues with this link
is there any other ways for showing you sample?

**Comment by slax57** [comment]
@Ali00Naghiloo you can try https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple if it works better

**Comment by fzaninotto** [comment]
No news for some time, closing.
