### ISSUE TITLE
Issue with Inputs within FormDataConsumer when removing and reinserting an element

### ISSUE THREAD

**Issue by marit970** [marmelab/react-admin#9089]
**What you were expecting:**
The form fields are empty when deleting an existing list item and trying to create a new one.  

**What happened instead:**
When removing a list item and creating a new one, the form stores the previous values.

**Steps to reproduce:**
Use [this sandbox](https://stackblitz.com/edit/github-hwaghj?file=src%2Fdata.tsx,src%2Findex.tsx,src%2Fcomments%2FCommentList.tsx,src%2Fcomments%2FCommentCreate.tsx,src%2Fcomments%2FCommentEdit.tsx,src%2Fcomments%2FCommentShow.tsx) to reproduce the bug. Open the ContentEdit Page. Remove the existing list item and then try to insert a new one. 
![Bildschirmfoto von 2023-07-10 16-07-26](https://github.com/marmelab/react-admin/assets/43189340/326d8601-884d-46d0-9d86-926846e55132)

**Comment by slax57** [comment]
Interesting, it looks like this bug only happens if you wrap the inputs inside a `FormDataConsumer` though...
I'm marking this as bug so we dedicate some time to investigate.
Thanks for the report.

**Comment by marit970** [comment]
@slax57 Great, thank you!
