### ISSUE TITLE
TabbedShowLayoutTabs Does Not Support Custom onChange Handler

### ISSUE THREAD

**Issue by maxschridde1494** [marmelab/react-admin#9098]
**What you were expecting:**

A custom `onChange` handler should be passable to `TabbedShowLayoutTabs` (as mentioned in these [docs](https://marmelab.com/react-admin/TabbedShowLayout.html#custom-tab-component)).

**What happened instead:**
The `TabbedShowLayout.handleTabChange` function always overrides the `TabbedShowLayoutTabs.onChange` prop. ([see code here](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/TabbedShowLayout.tsx#L113)).

**Other information:**
Our app uses Tabbed Show components. We nest List components within some of these tabs occasionally. The issue we were running into is that tab navigation does not clear query string parameters (i.e. list filters, etc.), so we experienced list filter param bleeding. The solve that we came up with is to override the `Tabs.onChange` method to navigate to the tab path sans query params. We still want the tables to syncWithLocation so that we can support deep linking. 

**Environment**

* React-admin version: 4.11.3
* React version: 18.2.0

**Comment by slax57** [comment]
Thanks for this report.
Indeed we could call the provided `onChange` handler in `handleTabChange`. But this would be a new feature, I don't consider it to be a bug.
Feel free to open a PR (against the `next` branch) if you'd like to implement this change.

Regarding your specific use-case however, I wonder if you can simply leverage the [`storeKey`](https://marmelab.com/react-admin/List.html#storekey) prop to prevent the filter parameters 'bleeding' between the lists.

**Comment by maxschridde1494** [comment]
Thanks for the quick response @slax57 :) I would be happy to open a PR.

Regarding our use case, we are leveraging the `storeKey` prop. However, the List component merges url params with the stored params, so when tab 1 updates filters, the url params (as well as the namespace store value) are updated, and that's what bleeds over to tab2 when you switch. The store value does not experience this bleeding as it is namespaced.

**Comment by slax57** [comment]
@maxschridde1494 Thanks for the additional info, and for offering to work on a PR :slightly_smiling_face: 

Just to be extra-safe, I'd also like to mention the [`disableSyncWithLocation`](https://marmelab.com/react-admin/List.html#disablesyncwithlocation) prop. It is not exactly equivalent as it will completely disable persisting the list parameters, but if you are ok with that it can help having two lists for the same resource on the same page, without having the issues with url params.

**Comment by fzaninotto** [comment]
This feature request has received no support from the community, and is not on the core team roadmap. I'm closing the issue, but feel free to open a PR if you have implemented the feature.
