### ISSUE TITLE
Add ability to disable sync with location in List without disabling saving params in the Store

### ISSUE THREAD

**Issue by slax57** [marmelab/react-admin#9100]
Currently, in a List, we can:
- :heavy_check_mark: enable sync with location and :heavy_check_mark: enable storing the list params, with the default props
- ❌ disable sync with location and ❌ disable storing the list params, with `disableSyncWithLocation`
- :heavy_check_mark: enable sync with location and ❌ disable storing the list params, with `storeKey={false}`

But we can't ❌ disable sync with location and and :heavy_check_mark: enable storing the list params.

This is what https://github.com/marmelab/react-admin/pull/8530 is suggesting.

I think RA should offer that ability, either via https://github.com/marmelab/react-admin/pull/8530 or another PR if this one does not reach completion.

**Comment by btbenedi** [comment]
+1 I opened that original PR and real work has gotten in the way of me finishing that PR

**Comment by fzaninotto** [comment]
Fixed by #10187
