### ISSUE TITLE
`NumberField` label does not stay on the top when provided non-numeric input

### ISSUE THREAD

**Issue by VGalata** [marmelab/react-admin#9103]
**What you were expecting:**
When providing a non-numeric input to a `NumberField` component and clicking outside of it, the input field label should stay on the top.

**What happened instead:**
The label went to the input field overlapping with the provided input.

See the attached screenshots:

![Screenshot from 2023-07-17 14-09-15](https://github.com/marmelab/react-admin/assets/5700085/7e18df0a-7e89-4b8e-a7b3-3119ca5dbe20)
![Screenshot from 2023-07-17 14-09-21](https://github.com/marmelab/react-admin/assets/5700085/11f34f2d-5ad1-47c1-b599-843c9a807936)

**Steps to reproduce:**
Clone the repo linked below and run

```bash
npm run build
npm run start
```

Click on one of the elements, try to change the input in the first field (`NumberField` input) and click outside of the field.

**Related code:**
Link to the repo with an example: [link](https://github.com/kasbergerc/React-admin-numberInput-bug-replication).

**Other information:**
See the linked code.

**Environment**

```
"react": "18.2.0"
"react-admin": "4.12.1"
```

**Comment by slax57** [comment]
I agree, but actually, apart from using special chars like `'e'` (and yet, only if I left the number incomplete), I have not been able to reproduce this issue easily. 

Hence my question about the use-case. To qualify the issue, I need to know if this can happen during normal usage of the component or if this only happens in case of misuse.

**Comment by VGalata** [comment]
I would not consider this a misuse. The component - as it is - allows non-numerical input. As a user, I would either expect a validation error or not being able to put strings into the field, but not broken styling.

**Comment by slax57** [comment]
Don't worry too much about the "misuse" term, maybe I picked the wrong word here (I'm not a native english speaker :sweat_smile: )

What I mean is that I never came across this case until now, and even knowing what to look for, it took me a couple of tries to actually reproduce the issue.

Besides, typing strings like `'SAdadsadsa'` (like in your screenshot) is not possible in my browser (Chrome) unless I temper with the DevTools.

So I'm still unsure it is an issue that can affect a significant number of users.

That being said, I'm still wondering if other browsers may behave differently.
Were you able to actually type in `'SAdadsadsa'` without changing the code or the DOM?

**Comment by VGalata** [comment]
Ah, I see. I am not a native speaker either. :D

Thanks for the clarification! Now, I understand what you mean. I did not need to do anything with the browser to be able to put in a string. And I just typed in some random characters. I will try it tomorrow in different browsers to see if there is a difference.

**Comment by VGalata** [comment]
I get the broken styling in Firefox (`115.0.2 (64-bit)`, on Ubuntu).
![Screenshot from 2023-07-21 16-30-38](https://github.com/marmelab/react-admin/assets/5700085/b7272100-1e87-4b93-9510-28ffcaa35668)

But typing in a string does **not** in Chromium (`114.0.5735.198 (Official Build) snap (64-bit)`).

So, there is definitely a difference in the used browser. :/

**Comment by adguernier** [comment]
Indeed, I have just tested on Firefox and I have the same behavior as you describe.
Issue qualified as bug.

Thanks for the report.

**Comment by fzaninotto** [comment]
This is a material-ui bug: in https://mui.com/material-ui/react-text-field/#inputs, you see that the Number input example has a special `InputLabelProps` property:

```
        <TextField
          id="outlined-number"
          label="Number"
          type="number"
          InputLabelProps={{
            shrink: true,
          }}
        />
```

Without it, MUI shows the same bug as you describe. 

So we won't fix this bug in react-admin. I suggest that you:

1. Use the `InputLabelProps` in your code if having letters in a NumberInput in Firefox is a common use case for you
2. Open an issue in the material-ui repo.
