### ISSUE TITLE
DeleteWithConfirmButton for ConfirmTitle accept only string

### ISSUE THREAD

**Issue by yurassic** [marmelab/react-admin#9105]
**Is your feature request related to a problem? Please describe.**
We need to add data-attribute for title and use existing field as title value (we want to show full name value in the title), but it only accepts string.

**Describe the solution you'd like**
Add ability to accept react components as well. So it's also brings ability to customize title.

**Describe alternatives you've considered**
-

**Additional context**
<img width="396" alt="Screenshot 2023-07-18 at 15 44 52" src="https://github.com/marmelab/react-admin/assets/10263616/e4a37f6f-1f44-4ed5-a5c8-38ce7c78fdad">

**Comment by djhi** [comment]
Sounds reasonable. Can you open a PR for this ? Make sure to target the `next` branch and to add a story :)

**Comment by yurassic** [comment]
@djhi Hey, I prepared PR but I couldn't push it, can you provide access for me?
Or provide instructions on how to do it.

**Comment by slax57** [comment]
Fixed via https://github.com/marmelab/react-admin/pull/9115
