### ISSUE TITLE
On edit form, useUnique fetches currently edited record and prevents saving

### ISSUE THREAD

**Issue by bjab** [marmelab/react-admin#9111]
**What you were expecting:**
**What happened instead:**
We have edit form, where one of fields has unique validator - in our case resource should have unique name.
We change one of other resource fields and try to save, but name field is marked as invalid as already existing, although it did not change.
I see, that query returns currently edited record and that's why it fails.

**Other information:**
I see two ways of solving this (in our case):
1. do not run validation if field did not change
2. somehow pass filter like `id <> currentRecord.id`, but I don't have idea, how to do it as json object
3. when checking server response, if it contains only one record and id matches current, then pass validation

**Environment**

* React-admin version: 4.12.1
* React version: 18.2.0
* Browser: chrome

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by bjab** [comment]
> Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).

Hi
https://stackblitz.com/edit/github-awixt5?file=src%2Ftags%2FTagEdit.tsx
I made tag names unique

Steps to reproduce:
- go to tags
- edit one of tags 
- add FR entry
- go to EN tab
- click save
- validation will fail, even that EN name was not changed

**Comment by djhi** [comment]
Ah I see now. Good catch, thanks!
