### ISSUE TITLE
Type mismatch for `confirmContent` on <DeleteWithConfirmButton>

### ISSUE THREAD

**Issue by elstgav** [marmelab/react-admin#9113]
**What you were expecting:**

The TypeScript definition for `DeleteWithConfirmButtonProps` allows `confirmContent` to be any `ReactNode`:

https://github.com/marmelab/react-admin/blob/b59f529c6d7876f82b8e5ca69fc95ec46d6ca023/packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx#L97-L102

Based on this, we should expect to be able to do something like this:

```tsx
<DeleteWithConfirmButton resource="foo" confirmContent={<strong>test</strong>} />
```

**What happened instead:**

We get a prop types error, as prop types is set to only allow string:

https://github.com/marmelab/react-admin/blob/b59f529c6d7876f82b8e5ca69fc95ec46d6ca023/packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx#L118-L121

**Steps to reproduce:**

```tsx
<DeleteWithConfirmButton resource="foo" confirmContent={<strong>test</strong>} />
```

**Comment by slax57** [comment]
Confirmed, thanks!

And thanks @yurassic for the fix :slightly_smiling_face:

**Comment by slax57** [comment]
Fixed via https://github.com/marmelab/react-admin/pull/9115
