### ISSUE TITLE
List filters automatically sync across browser tabs/windows

### ISSUE THREAD

**Issue by mediafreakch** [marmelab/react-admin#9120]
**What you were expecting:**

When having a list open in two separate browser windows, list content and list filters should **not** automatically sync across windows

**What happened instead:**

Filters and list content automatically sync across windows (without page refresh or window focus)

**Steps to reproduce:**

1. Go to https://marmelab.com/react-admin-demo/
2. Click on "Orders" in the navigation on the left
3. Duplicate currently open browsertab, extract it to a new window and arrange the new window next to the first one
4. In the **second** window, enter a search term to filter the list

**Other information:**

I am aware that when re-focussing a tab or window, `react-query` will refetch the current list by default. But the bug I encounter happens even if I disable that behaviour in the `QueryClient`'s settings. 

If this is a feature, I would appreciate this being documented and a setting to disable it.

https://github.com/marmelab/react-admin/assets/777093/d5b513d2-3331-4893-a3c6-5f60740cc0f4

**Environment**

* React-admin version: 4.12.2
* Browser: Chrome / Firefox

**Comment by mediafreakch** [comment]
So I've found the corresponding [lines in code here](https://github.com/marmelab/react-admin/blob/b37e2997615882282373492556de138171ac90ba/packages/ra-core/src/store/localStorageStore.ts#L59). From what I can see, there is no way to disable this auto-sync behaviour.

Using `disableSyncWithLocation` on the `<List />` component is not what I want, I do want filters to persist across page-loads or navigation. Just not in real-time.

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback. 

This is a feature. You can disable it for the entire app by using a `memoryStore` (see https://marmelab.com/react-admin/Admin.html#store), but not on a per-resource basis. If this doesn't fit your need, you can build your own List component using react-admin hooks as described here: https://marmelab.com/react-admin/ListTutorial.html#from-pure-react-to-react-admin
