### ISSUE TITLE
`SelectInput` does not support fetching remote choices with `isLoading`

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#9138]
**What you were expecting:**

I am following the example in the documentation. https://marmelab.com/react-admin/SelectInput.html#isloading
I expect the SelectInput will not crash when data is not available yet and isLoading is set to true.

**What happened instead:**

The form crashed during loading even when I have provided the choices prop to SelectInput.
The error message is a bit confusing.

**Steps to reproduce:**

1. Copy the example code in https://marmelab.com/react-admin/SelectInput.html#isloading, paste in examples/simple/src/comments/CommentsCreate.tsx 
2. Modify the useGetList to become useQuery with a promise to return data
3. Add the UserCountry component to the form

**Related code:**

* A link to a GitHub repo with the minimal codebase to reproduce the issue
https://stackblitz.com/edit/github-pkekbw?file=src%2Fcomments%2FCommentCreate.tsx

**Other information:**

**Environment**

* React-admin version: 4.12.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Safari 16.5.1
* Stack trace (in case of a JS error):

**Comment by smeng9** [comment]
Also, this issue happens only during the first time you visit this form, because react-query caches the result for subsequent render of the form.

So if after page throws error and you click the go back button and retry the create button, the form can render without a problem.

If you cannot reproduce it because of the dirty state caused by react-query, try use private browsing mode.

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report. 

The problem seems to come from a `useEffect` in `useList` making the data temporarily incoherent.
