### ISSUE TITLE
`NumberField` formatting does not work with string data

### ISSUE THREAD

**Issue by ksocha** [marmelab/react-admin#9143]
**Is your feature request related to a problem? Please describe.**
Some data serialisers (like Rails one which I'm using) serialise decimals using strings, to prevent precision loss.
However, `NumberField` does not fully work when provided with string instead of number, which it expects.
e.g.:
```js
<NumberField
  source="amount"
  locales="de"
  options={{ style: 'currency', currency: 'EUR' }}
/>
```
in case of `amount` = `"900.25"` renders plain `900.25`, without currency sign.

**Describe the solution you'd like**
Currently, the implementation is as follows:
```js
{hasNumberFormat && typeof value === 'number'
  ? value.toLocaleString(locales, options)
  : value}
```

`typeof value === 'number'` portion could be changed with some kind of parse-check to see if provided value is a string-representation of a number.

**Describe alternatives you've considered**
Using `FunctionField` instead of `NumberField`, but that's basically duplicating already existing functionality.

**Comment by fzaninotto** [comment]
This is already doable in user land using the `FunctionField` to do the conversion but not duplicate the current functionality:

```jsx
<FunctionField name="amount" render={record => <NumberField record={{ ...record, amount: toFloat(record.amount, 0) }} source="amount" locales="de" options={{ style: 'currency', currency: 'EUR' }}/>} />
```

It is also doable by doing the conversion in the dataProvider, and in the `<Edit transform>` prop. I doubt adding a fourth way to do it will help usability. 

That being said, we may add the above example in the documentation, so I'm marking it as a documentation issue.

**Comment by fzaninotto** [comment]
All things considered, I agree that doing the conversion should be the default. Changing the label to enhancement.
