### ISSUE TITLE
Return type of ResourceCallbacks.beforeSave should be Promise<Partial<T>>

### ISSUE THREAD

**Issue by awesome-manuel** [marmelab/react-admin#9152]
The return type of `ResourceCallbacks.beforeSave` should be the same as the type of the parameter `data`. The function cannot create a `RaRecord` from a `Partial<RaRecord>`.

https://github.com/marmelab/react-admin/blob/de8fbaa3285714aab914e0e76cc369c09a817d3c/packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts#L577C73-L577C74

**Comment by fzaninotto** [comment]
Why? A Create, for instance, doesn't require the `id`, but the response contains one.

**Comment by awesome-manuel** [comment]
Yes, but the return of `beforeSave` is the input to `create`, not the output.

**Comment by fzaninotto** [comment]
It is also the input of `update`, which is a partial of the record type. 

Since we don't seem to agree, I suggest you add an example showing a TS compilation error that you think is wrong.

**Comment by awesome-manuel** [comment]
```typescript
import { RaRecord, ResourceCallbacks } from 'react-admin';

const process = async (data: Partial<RaRecord>): Promise<RaRecord> => {
  data.myAttribute = data.myAttribute.split('.')[1];
  return data;
};

export const locationLifecycleCallbacks: ResourceCallbacks<RaRecord> = {
  resource: 'MyResource',
  beforeSave: process,
};
```

results in

```
Type 'Partial<RaRecord<Identifier>>' is not assignable to type 'RaRecord<Identifier>'.
  Types of property 'id' are incompatible.
    Type 'Identifier | undefined' is not assignable to type 'Identifier'.
      Type 'undefined' is not assignable to type 'Identifier'.ts(2322)
```

**Comment by fzaninotto** [comment]
Thanks, now I understand better. The return type must be a partial, too. 

I'm marking this as a bug, feel free to open a PR fixing it.
