### ISSUE TITLE
Add support for dynamic helperText based on form value

### ISSUE THREAD

**Issue by dalen** [marmelab/react-admin#9153]
**Is your feature request related to a problem? Please describe.**

In many cases I would like to add some extra explanation about the meaning of certain options in for example a SelectInput. But currently you can only add a static helperText for the input as a whole. And explaining every option in that becomes too much text.

**Describe the solution you'd like**

I would like to set helperText to a function that takes current input value and returns the helperText value.

**Comment by fzaninotto** [comment]
This is doable in user land, you don't need a react-admin change for that. So I'm closing this issue as won't implement it in the core.

**Comment by dalen** [comment]
It is probably possible with wrapping the input in a component, using `useWatch` etc. But a lot of extra work for a simple thing IMHO.
