### ISSUE TITLE
When using two forms on the same page RadioButtonGroupInput labels will change the status of the wrong RadioButtonGroup

### ISSUE THREAD

**Issue by alexrecarey** [marmelab/react-admin#9158]
**What you were expecting:**
When I add 2 or more forms to the same page, each one with a RadioButtonGroupInput, clicking on the radio button will correctly change the state of the RadioButtonGroup. However, clicking on the label will change the state of the first RadioButtonGroupInput element of the page.

**What happened instead:**
I was expecting clicking on the label to work the same as clicking on the radio button

**Steps to reproduce:**
[Here is a short video demonstrating the bug.](https://youtu.be/gyXKiRNNgew)

Add two forms to the same page for editing the same resource, each one editing instance of the resource. Check the following: 

1. The radio buttons for the first and second record work perfectly.
2. Clicking on the labels works only for the first record, when clicking
   the labels of the second record, the *first records* radio button will 
   change instead of the first one.

**Related code:**
I created a minimal project to demonstrate the issue:

https://github.com/patientgrid/react-admin-bug-multiform

Thank you!

**Comment by adguernier** [comment]
Hi @alexrecarey 

Thanks for the report. 

Does adding an id props resolve this issue ?

```ts
<RadioButtonGroupInput
  id="radio1"
  name="radio1"
  source="selected"
  choices={[
    { id: "1", name: "One" },
    { id: "2", name: "Two" },
    { id: "3", name: "Three" },
  ]}
/>
```

**Comment by fzaninotto** [comment]
@alexrecarey in your example, the two radio groups have the same `source`. So you're exposing two controls for the same piece of data, and you expect that they are not in sync. This is not a supported use case, and you'll have to build your own form control for that.

**Comment by alexrecarey** [comment]
@adguernier yes, I tried setting different `key`s, `id`s and `name`s as props, without effect.

@fzaninotto perhaps my example was too minimal. In my app, I need to provide an interface to answer a large number of variable `questions` for each `report`. Clicking into each `question` to answer it would take a lot of time when each question has only one reply. So yes, the `source` for every form is the same (`question`), but the `id` of each form is different. I don't think it's a particularly strange thing to do, and `TextInput`, `SelectInput` etc work perfectly. Only the `RadioButtonGroupInput` has issues with this configuration.
