### ISSUE TITLE
ReferenceInput API call doesn't have bearer token on initial load

### ISSUE THREAD

**Issue by nalopez** [marmelab/react-admin#9164]
**What you were expecting:**
We have a react admin app and we are using ReferenceInput on some fields of a create/edit form. As observed, every select of an autocomplete field wrapped with `ReferenceInput` triggers an API call to the `reference` endpoint, in our case, it's `/users`.

When the create/edit form loads for the first time in the browser and the logged in user selects an entry in autocomplete field, we don't expect any error on the `/users` API call.

**What happened instead:**
 When the create/edit form loads for the first time in the browser and the logged in user selects an entry in autocomplete field, we get an 401 response from `/users`. Checking on the API request, we see that it's Bearer token value is null.
![image](https://github.com/marmelab/react-admin/assets/6589993/069b7568-2568-4178-95b6-e976d7cf4209)

Also, the field shows an `ra.input.references.single_missing` error
<img width="220" alt="image" src="https://github.com/marmelab/react-admin/assets/6589993/49f289d7-d184-468b-98ea-7767cf6d372c">

On succeeding page loads, the error is no longer replicable. Any idea how to investigate and address this issue?

**Steps to reproduce:**

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.19.11
* React version: 16.14.0
* Browser: Google Chrome/Mozilla

**Comment by fzaninotto** [comment]
No news for some time, closing.
