### ISSUE TITLE
Improve generic type in useResourceContext

### ISSUE THREAD

**Issue by oguhpereira** [marmelab/react-admin#9173]
**Is your feature request related to a problem? Please describe.**
Today I see no advantage in passing a generic to the resource context, as it makes no difference. It is always returning me a string, I think it is interesting that there is the possibility of passing a generic that can return me an enum for example.

**Describe the solution you'd like**
```jsx
const resource = useResourceContext<'my-resource-name'>()
````

or

```jsx
const resource = useResourceContext<{resource: 'my-resource-name'}>()
```
**Additional context**

I think a change in generic ja will help us with that.

https://github.com/marmelab/react-admin/blob/e9b7582ef6e8efa98d31f535c4ade303aca94f86/packages/ra-core/src/core/useResourceContext.ts#L36

**Comment by fzaninotto** [comment]
Sorry, I fail to understand what pain point you have and what solution you suggest. Would you mind describing a bit more the benefits you'd get, using a real example?

**Comment by oguhpereira** [comment]
@fzaninotto off curse!

Well my suggestion is that instead of terms like type just string, provide the developer with a possible generic so that he knows exactly what the name of the resource is. I believe that this will help in the typescript part because it will know in development time which resource it is modifying, this will also avoid the use of `as` in the code.

**Comment by fzaninotto** [comment]
If you know the resource name at compile time, why would you need to call `useResource`?

**Comment by oguhpereira** [comment]
I could have a component that is used in 2 resources and separate the resource that it does in these conditions

```jsx
// Some component
...
const resource = useResourceContext<'users' | 'posts'>()

if (resource === 'users')
// do something
```

What I would like to say would be interesting how we manage to pass the generic type of a `useRecordContext` to also be able to do the same with the `useResourceContext`

```jsx
// Some component
...
const resource = useResourceContext<'users' | 'posts'>()

const data = resource.substring(0, resource.length - 1)
// now i know that date has the following value 'user' | 'post'
```

**Comment by oguhpereira** [comment]
@fzaninotto I could have a component that is used in 2 resources or more and separate what it does if it is certain resource

```jsx
// Some component
...
const resource = useResourceContext<'users' | 'posts'>()

if (resource === 'users')
// do something
```

What I would like to say would be interesting how we manage to pass the generic type of a `useRecordContext` to also be able to do the same with the `useResourceContext`

```jsx
// Some component
...
const resource = useResourceContext<'users' | 'posts'>()

const data = resource.substring(0, resource.length - 1)
// now i know that date has the following value 'user' | 'post'
```

**Comment by fzaninotto** [comment]
I find this use case a bit convoluted, and rare. We tend to use generics to let you specify a type, not a value. I know it is possible, but IMO this is bike shedding. 

Besides, you can achieve the same with

```tsx
const resource = useResourceContext() as 'users' | 'posts';
```

So personally, I'm -1 for this feature. Let's wait for more feedback from the community before making a decision on this one.

**Comment by oguhpereira** [comment]
I don't think so, if we're going to think about the typed text first, I think that's a good suggestion. I've already used "as" but I see it as a utility since the tool doesn't provide a way to control type.

I'm waiting community decision, if you need help to implement it, let me know :)
