### ISSUE TITLE
`onSettled` options seems is not fired when `<DeleteButton>` has pessimistic mode

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#9178]
**What you were expecting:**

I expect the onSettled function to be called after the record is removed when I click the delete button

**What happened instead:**

This function seems does not get called

**Steps to reproduce:**

Add a `DeleteButton` with `onSettled` to the `PostList.tsx`, and then click the button.

**Related code:**

```
https://stackblitz.com/edit/github-6p7pvf?file=src%2Fposts%2FPostList.tsx
```

**Other information:**

**Environment**

* React-admin version: 4.12.4
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Safari
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Reproduced, thanks for the report.

**Comment by djhi** [comment]
It appears the `useDelete` updates the react-query cache entries for `getList` and `getOne` to remove the deleted element. The list is updated and the line containing the deleted record is removed before `onSettled` is called

**Comment by smeng9** [comment]
No longer reproducible in 5.2.2. 
Marking as fixed.
Closing.
