### ISSUE TITLE
[Doc] Update <NumberInput> docs to match new behavior

### ISSUE THREAD

**Issue by itspladd** [marmelab/react-admin#9184]
**Is your feature request related to a problem? Please describe.**
The `<NumberInput>` documentation still references the component's old behavior, in which it only updates on blur. The component was changed in PR #8033; more specifically, the component now functions well in a filter form, since it updates the filtered value on change instead of on blur.

**Describe the solution you'd like**
Update the `<NumberInput>` docs to reflect the new behavior and remove or update the "Usage In Filter Form" section.

**Describe alternatives you've considered**
N/A, I think

**Additional context**
I'm not sure if there are still caveats or special considerations for using `<NumberInput>` in a filter form; otherwise, I'd just submit a PR to update the docs directly. However, I can anecdotally say that I've used it to filter lists by Postgres ID  with no customization or obvious problems.

**Comment by fzaninotto** [comment]
Good catch, thanks for pointing that out!
