### ISSUE TITLE
Two filters are not applied to List when `disableSyncWithLocation` is true

### ISSUE THREAD

**Issue by mikhail-fedosenko** [marmelab/react-admin#9190]
**What you were expecting:**
I have `BooleanInput` filter and `QuickFilter` in my `filters` for List:
```js
[
  <BooleanInput
    label="Has Code tag"
    source={'hasCodeTag'}
    alwaysOn
    sx={{ mb: 1 }}
  />,
  <QuickFilter
    label="resources.posts.fields.commentable"
    source="commentable"
    defaultValue
  />,
];
```
The List has `disableSyncWithLocation` enabled.
When I apply "Commentable" filter first, then apply "Has Code tag" filter, the data provider `getList` method should receive both filter values: `{ commentable: true, hasCodeTag: true }`.

**What happened instead:**
Data provider `getList` method receives only one filter value: `{ hasCodeTag: true }`.

**Steps to reproduce:**
1. Go to Posts list page.
2. Click on "Filters", select "Commentable" filter.
3. Click on "Has Code Tag" filter.
4. Observe the console log.

**Related code:**
https://stackblitz.com/edit/github-4uscjv?file=src%2Fposts%2FPostList.tsx

PostList.tsx
```jsx
const postFilter = [
  <BooleanInput
    label="Has Code tag"
    source={'hasCodeTag'}
    alwaysOn
    sx={{ mb: 1 }}
  />,
  <QuickFilter
    label="resources.posts.fields.commentable"
    source="commentable"
    defaultValue
  />,
];
```

```jsx
  <List
     ...
    disableSyncWithLocation
  >
```

dataProvider.tsx
```js
    beforeGetList: async (params, dataProvider) => {
      console.log('Filter is', params.filter);
      const { hasCodeTag, restFilters } = params.filter;
      params.filter = restFilters;
      return params;
    },
```

**Environment**

* React-admin version: 4.13.0
* React version: 17.0.2
* Browser: Chrome 114.0.5735.198

**Comment by djhi** [comment]
Reproduced, thanks

**Comment by djhi** [comment]
Actually no, if I follow your steps, I can't reproduce. I get:
```
{hasCodeTag: true, commentable: true}
```

**Comment by mikhail-fedosenko** [comment]
The order you apply filters is important - first apply a filter in Filters context menu ("Commentable"), then - "Has Code Tag".

If you apply "Commentable", then "Has Code Tag", then remove and re-apply "Commentable" the filtler value passed to the data provider will be correct.

**Comment by adguernier** [comment]
Actually I can reproduce by following the steps order.
 
select "Commentable" filter logs
```
Filter is { commentable: true }
```
and then click on "Has Code Tag" filter logs
```
Filter is { hasCodeTag: true }
```

Doing this by reversing the steps order will produce the right behavior
```
Filter is { hasCodeTag: true, commentable: true }
```

**Comment by djhi** [comment]
Indeed, must have done the reverse
