### ISSUE TITLE
I need a queryOptions prop to be added to useReferenceInputController and ReferenceInput for request that fetches current value.

### ISSUE THREAD

**Issue by ethembynkr** [marmelab/react-admin#9192]
**Is your feature request related to a problem? Please describe.**
In useReferenceInputController, I can pass options to query that fetches possible values, but not to the query that fetches current value. 

**Describe the solution you'd like**
I need a queryOptions prop to be added to **useReferenceInputController** and **ReferenceInput** for request that fetches current value.

**Additional context**
![image](https://github.com/marmelab/react-admin/assets/20007016/50c3b2a7-2836-476e-b240-99775f33a124)

**Comment by fzaninotto** [comment]
We know that the `queryOptions` is only passed to one of the two queries. But we've wondered if passing the same options to the two queries would be a good idea. For once, the types aren't the same, so TypeScript complains. But mostly, I don't see any use case for this - we're already passing `meta` to the two queries. 

Could you explain why you need this?

**Comment by ethembynkr** [comment]
We want to pass staleTime to both queries.

**Comment by fzaninotto** [comment]
Good enough reason! I'll mark this as a bug then.
