### ISSUE TITLE
UpdateButton Confirm Dialogue Close Cannot Be Triggered with a Custom onSuccess Mutation Option (no redirect)

### ISSUE THREAD

**Issue by maxschridde1494** [marmelab/react-admin#9194]
**What you were expecting:**
I expect that I would be able to close the update button confirm dialogue even with a custom onSuccess mutation option.

**What happened instead:**
onSuccess method is run (i.e. custom notification, page refresh, etc.) but the confirm dialogue remains open without a page redirect.

**Steps to reproduce:**
Pass a custom onSuccess mutation option to a confirmable UpdateButton that does not trigger a redirect. 

**Related code:**
```
<UpdateButton
          label='Send Password Reset'
          mutationMode="pessimistic"
          confirmTitle="Password Reset"
          confirmContent="Are you sure you want to send a password reset email?"
          data={{ ... }}
          mutationOptions={{
            onSuccess: () => {
              notify('Password reset email sent.', { type: 'success' })
              refresh()
            }
          }} 
        />
```

**Other information:**
Another idea, although somewhat unrelated, would be providing the ability to override the onSuccess / onError notification messages without having to pass custom mutation options. That would be a workaround for my case, but doesn't solve the underlying issue. 

**Environment**

* React-admin version: 4.13.0
* React version: 18.2.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report.

**Comment by maxschridde1494** [comment]
Thanks for the quick response and fix! Do you know when we can expect a new release that will include the fix?

**Comment by fzaninotto** [comment]
Reopened as #9196 will be reverted (it was a wrong fix)

**Comment by fzaninotto** [comment]
You're right! It's not a breaking change. 

The rest of your comment is valid: onSuccess now works, but onSettled doesn't. I think the cases where uses may want to pass a custom onSettled are rare, so we can decide not to support it. 

So the original problem IS, indeed, fixed.

**Comment by slax57** [comment]
Agreed. Thanks for your reply, and sorry for the noise :sweat:
