### ISSUE TITLE
BulkActionButtons mobile styling issue

### ISSUE THREAD

**Issue by zhiguow** [marmelab/react-admin#9195]
After the Datagrid passed in the bulkActionButtons, when selecting on the mobile phone, there was a problem with the TopToolbar above the Datagrid: the actionButton was set with a white background color to cover the theme color of the TopToolbar.

**What you were expecting:**

![e](https://github.com/marmelab/react-admin/assets/113873345/cb9771bc-72da-4913-99f9-e9358a64bd1e)

**What happened instead:**

![i](https://github.com/marmelab/react-admin/assets/113873345/f8c1d555-516c-44ae-89d5-68ecdb83669e)

**Steps to reproduce:**

On the mobile side, visit https://marmelab.com/react-admin-demo/#/invoices, click to select a record.

https://github.com/marmelab/react-admin/assets/113873345/ef96da8b-878d-486a-8388-52feb6fd1a54

**Related code:**

```
<Datagrid bulkActionButtons={<PostBulkActionButtons />} >
       .
       .
       .
  </Datagrid>
```

**Temporary solution:**

```
<Datagrid
      sx={{
          '& .RaBulkActionsToolbar-topToolbar': { backgroundColor: 'rgba(0, 0, 0, 0)' },
      }}
      bulkActionButtons={<PostBulkActionButtons />}
  >
       .
       .
       .
  </Datagrid>
```

**Other information:**

![1](https://github.com/marmelab/react-admin/assets/113873345/50971f2f-3a43-4736-bfeb-be716ff395a8)

**Environment**

* React-admin version: 4.6.1
* React version: 18.2.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Reproduced, thanks!
