### ISSUE TITLE
NumberInput and BooleanInput "setFocus" don't work

### ISSUE THREAD

**Issue by XStepien** [marmelab/react-admin#9202]
What you were expecting:   
When calling "react-hook-form" setFocus on NumberInput or BooleanInput, the input should be focused   

What happened instead:   
Calling setFocus don't work on these fields, nothing happen   

The "ref" from "react-hook-form" input (useInput) are passed to wrong MUI input component props:   
```
return (
        <StyledTextField
            id={id}
            size="small"
            {...field} // where field from useInput hook contain the ref (field.ref)
```

instead it should be passed to "inputRef" props
```
return (
        <StyledTextField
            id={id}
            size="small"
            {...field} // field should be desctructured before to remove the "ref" part
            ...
            inputRef={fieldRef}
```

**Environment**

* React-admin version: latest   
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by adguernier** [comment]
Hi @XStepien and thanks for this report.

Can you please provide a link to a reproducible example as described in issue template ?

**Related code:**
_If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:_

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

And also the **Steps to reproduce:**
_Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application._

Thanks

**Comment by XStepien** [comment]
Hello @adguernier,

https://stackblitz.com/edit/github-72atmx?file=src%2Fposts%2FPostEditFocusTest.tsx

While creating the sample app, found that CheckboxInput and ImageInput also have this bug

**Comment by adguernier** [comment]
Reproduce thanks.

Feel free to open a PR if you want to contribute :smiley:
