### ISSUE TITLE
Date input component not displaying correctly when view in mobile device

### ISSUE THREAD

**Issue by yong2579** [marmelab/react-admin#9215]
**What you were expecting:**
DateInput / DateTimeInput component are rendered correctly when view in mobile device

![image](https://github.com/marmelab/react-admin/assets/16757815/2029ce43-9913-483e-a042-de99db93851c)

**What happened instead:**
DateInput / DateTimeInput component is cut off 

![image](https://github.com/marmelab/react-admin/assets/16757815/91462338-bbe6-42d1-a867-60d8d5c51eaa)

**Steps to reproduce:**
To reproduce, simply navigate to https://marmelab.com/react-admin-demo/#/commands using a mobile device (e.g. iphone), then select the filter button and select the filter "Passed Since".

**Miscellaneous**
I realise if you view it from chrome on a desktop and emulate an iphone device using developer tools, you can see the expected behavior

Additionally if you select a date and rotate the iphone to landscape and rotate it back to portrait, the expected behavior is also achieved

For reference I have also seek for help in stackflow via https://stackoverflow.com/questions/76960417/react-admin-date-input-component-not-displaying-correctly-when-view-in-mobile-de

Note that so far this only happen on mobile device, tested windows surface and is ok. 

Also tested using a mac machine running xcode to emulate iphone and the date input component is also cut off.

**Environment**

* React-admin version: The version as per [react-admin demo](https://marmelab.com/react-admin-demo)
* Last version that did not exhibit the issue (if applicable): Unknown, new to react-admin and evaluating for new project
* React version: The version as per [react-admin demo](https://marmelab.com/react-admin-demo)
* Browser: safari 16.6 on iphone, chrome 116.0.5845.118 on iphone, edge and chrome on huawei p20
* Stack trace (in case of a JS error): Nil

**Comment by slax57** [comment]
Thanks for opening this issue.

According to my investigations, this comes from the fact that Safari on mobile does not have a placeholder text for `<input type="date">` on mobile.

See: https://developer.mozilla.org/fr/docs/Web/HTML/Element/input/date

In Chrome (desktop): 

![image](https://github.com/marmelab/react-admin/assets/14542336/8d8ccec2-158b-4410-8a3a-91158544600b)

In Safari mobile: 

![image](https://github.com/marmelab/react-admin/assets/14542336/45b97e14-196a-4504-86ba-9c577fa07f32)

This, combined with the fact that the input does not seem to have a `minWidth`, seems to cause the issue.

Can you try using the `sx` prop to set a `minWidth` to see if it solves the issue?

**Comment by yong2579** [comment]
Thanks for the reply!

I set the following on the date time input component and while the input does appear in full width (kind of hacky since it is not fluid anymore), the placeholder is dd-mm-yyyy --:-- -- is not available which I does understand is once again due to the browser on mobile issue

`<DateTimeInput sx={{ minWidth: "14rem" }} source="occurAt" isRequired />`

![image](https://github.com/marmelab/react-admin/assets/16757815/2b28cf17-1f4b-4e4a-bb38-5dc77d741315)

Is there any workaround to this issue? 

Additionally while testing i realised on mobile device, the reset button (which is actually clear when view on non-mobile device) is not able clear the value, it somehow remember the old value. However the clear does work on a non-mobile device.

![image](https://github.com/marmelab/react-admin/assets/16757815/699e883d-6898-43c2-a1ef-46f9b7b93611)

**Comment by slax57** [comment]
Okay so setting a `minWidth` seems to work. we'll could try to add it by default on the component to avoid this issue.

Regarding the missing placeholder, it seems this can be worked around with some CSS: https://github.com/flatpickr/flatpickr/issues/1103#issuecomment-485125291

Since this is a browser-dependent behaviour, I don't think we should try to fix (or workaround) it in RA.

**Comment by fzaninotto** [comment]
I think part of the problems reported here should be reported to the material-ui repository. 

Otherwise, I'm +1 for solving what can be solved on the react-admin side with a `minWidth`.

**Comment by yong2579** [comment]
I totally understand you guys, tested at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date using samsung, iphone, huawei device and we can conclude the behavior differ by settings in operating system (not device, not browser). Guess this cannot by fixed at the root by anyone other than the operating system vendor themselves. Sincerely appreciate you guys comments! Personally I believe react-admin will be an asset to our organisation and trying to convince my management that the organisation should use this framework. Great work guys!
