### ISSUE TITLE
make start command mentioned in the contribution guide isn't present in the available commands.

### ISSUE THREAD

**Issue by azizChebbi** [marmelab/react-admin#9226]
**What you were expecting:**

(make start) should work

**What happened instead:**

command not found
<img width="940" alt="Screenshot 2023-08-28 at 4 52 24 PM" src="https://github.com/marmelab/react-admin/assets/60013060/40216d90-5dbd-411c-9003-1e6685b8d60f">

<img width="458" alt="Screenshot 2023-08-28 at 4 55 04 PM" src="https://github.com/marmelab/react-admin/assets/60013060/3db6ab7e-510b-4417-bbdd-75e7ad1e0616">

**Steps to reproduce:**

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
You're right, it should be `make run` instead.

Would you like to open a PR to fix it?

**Comment by azizChebbi** [comment]
yes of course
