### ISSUE TITLE
Cannot build because of a type error on legacyAuthProvider of react-admin

### ISSUE THREAD

**Issue by comur** [marmelab/react-admin#9241]
Hi,

**What you were expecting:**
Build without any type error

**What happened instead:**
I have this errors when I try to build even if I comment authProvider prop of Admin:

```
TS2345: Argument of type 'any[]' is not assignable to parameter of type '[type: AuthActionType, params?: any]'.
  Target requires 1 element(s) but source may have fewer.
    18 |  */
    19 | export default (legacyAuthProvider: LegacyAuthProvider): AuthProvider => {
  > 20 |     const authProvider = (...args) => legacyAuthProvider.apply(null, args);
       |                                                                      ^^^^
    21 |     authProvider.login = params => legacyAuthProvider(AUTH_LOGIN, params);
    22 |     authProvider.logout = params => legacyAuthProvider(AUTH_LOGOUT, params);
    23 |     authProvider.checkAuth = params => legacyAuthProvider(AUTH_CHECK, params);
```

**Steps to reproduce:**

I can't really explain how to reproduce but I updated all package version of the project and that doesn't help. One of the packages that I can't update is typescript (I'm still on version 4) as react-scripts doesn't accept version 5 

**Related code:**
I actually have an Auth provider but I commented it out to check if it's related and it's not.

```
<Admin
                theme={SATheme}
                dataProvider={IS_FAKE ? fakeDataProvider : dataProvider}
                dashboard={PublicDashboard as DashboardComponent}
                // authProvider={authProvider as AuthProvider}
                loginPage={Login}
                layout={RALayout as LayoutComponent}
                // requireAuth
            >
...
</Admin>
```

**Environment**

* React-admin version: 4.13.3
* React version: 18.2.0
* Browser: Chrome on Mac

Thanks for any help !

**Comment by slax57** [comment]
Hi,

Not sure I understand the context of your issue. What are you trying to build? React-admin? Or your own project?

If it is the latter, why don't you configure your bundler to use the transpiled version of react-admin instead?

If you really think there is an issue in our code, we would need a way to reproduce the error so that we can work on it. Can you share a minimal project reproducing the build error?

**Comment by fzaninotto** [comment]
No news for some time, closing.
