### ISSUE TITLE
Changing page from Pagination inside WithListContext resets back to 1

### ISSUE THREAD

**Issue by botjaeger** [marmelab/react-admin#9254]
**What you were expecting:**

In Pagination component, when page is click, it data should change.

**What happened instead:**

Pagination works, sends a new request for page 2 but then it resets back to 1

**Steps to reproduce:**

`<ListBase>
    <WithListContext
        render={() => (
            <Pagination ...>
        )}>
</ListBase>`

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.13.3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. 

The Pagination component does work as expected in unit tests and demos, e.g. in the simple example:

https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple 

We can't investigate your problem unless you provide an executable example that reproduces it, e.g. based on the above CodeSandbox.

**Comment by botjaeger** [comment]
Adding this prop solve the issue `disableSyncWithLocation`
