### ISSUE TITLE
`useInput` returns referentially unstable field

### ISSUE THREAD

**Issue by macrozone** [marmelab/react-admin#9256]
**What you were expecting:**

`useInput` should return  a referentially stable `field` 

**What happened instead:**

`useInput().field` is different whenever it's value change

**Steps to reproduce:**

```
const MyCustomInput = ({ source }) => {
  const { field } = useInput({ source });

  React.useEffect(() => {
    field.onChange('hello world');
  }, [field]);
  return (
    <TextInput
      autoFocus
      source={source}
      validate={required('Required field')}
    />
  );
};


```

- if you do that, you are no longer able to change the text, since it will always return a new reference and therefore retrigger the effect.
- ommiting `field` from the deps-array would not only trigger any linter, but also makes the field not containing the default value "hello world"

**Related code:**

https://stackblitz.com/edit/github-43bviq-xachqv?file=src%2Fposts%2FPostCreate.tsx

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.13.3
* Last version that did not exhibit the issue (if applicable):
* React version: 18.1.0
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Reproduced, thanks!

**Comment by slax57** [comment]
Thank you for your answer.

> If there is another way to reliable set the value of a field programmatically, please let me know or point me to the documentation.

Yes there is.

If you need to change the field's value, you can use RHF's [setValue](https://react-hook-form.com/docs/useform/setvalue).
If you need to change the field's default value, you can use RHF's [resetField](https://react-hook-form.com/docs/useform/resetfield).

Hence, I'm gonna close this issue, unless you come across another use case that requires a `useEffect` with a dependency on `field`.
