### ISSUE TITLE
Setting 'disabled' to false in input components crashes the app

### ISSUE THREAD

**Issue by marit970** [marmelab/react-admin#9261]
This issue appears when updating the react-hook-form package (^7.46.0)

**What you were expecting:**
The input field is not disabled when setting the 'disabled'-property to false 

**What happened instead:**
It works correctly when setting the 'disabled'-property to 'true' or 'undefined', but it crashes the app when using 'false'

**Related code:**

* A link to a GitHub repo with the minimal codebase to reproduce the issue
https://github.com/marit970/react-disabled-bug

**Environment**

* React-admin version: 4.13.3
* React-hook-form version: 7.46.1 
* Last version that did not exhibit the issue (if applicable): 7.45.4 (react-hook-form)
* React version: ^18.2.0
* Browser: Mozilla Firefox
* Stack trace (in case of a JS error):
![Bildschirmfoto von 2023-09-08 11-16-55](https://github.com/marmelab/react-admin/assets/43189340/4f807363-5bc3-47ec-843a-aa9bb84fcf3f)

**Comment by fzaninotto** [comment]
This seems like a react-hook-form regression. Can you try and install https://github.com/react-hook-form/react-hook-form/releases/tag/v7.46.1, which fixes a similar regression?

**Comment by marit970** [comment]
@fzaninotto I've tried it out. This issue appears starting from the v7.46.0 (in 7.46.0 and 7.46.1 as well).

**Comment by fzaninotto** [comment]
Then it's a react-hook-form regression. Could you open an issue in their repository?

**Comment by marit970** [comment]
@fzaninotto sure, thank you!

**Comment by marit970** [comment]
@fzaninotto here is my issue by react-hook-form: https://github.com/react-hook-form/react-hook-form/issues/10907. I have not defined any resource in my example repo, but nothing changes when I add one. Also, I have not found anything in the documentation. Maybe you have an idea of what is wrong/missing here?

**Comment by qpointsystems** [comment]
Boy this killed me today, lol.  Finally tried checking here and violà, someone has logged it, thank god. 
Never thought it'd be in RA or hook form. 
Phew.

**Comment by slax57** [comment]
I have tried to reproduce the issue inside our [simple example project](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple), after upgrading to RHF v7.46.1, but didn't get the error.

@marit970 I see that your reproduction code is somewhat incomplete, for instance it does not provide any `ResourceContext`.
Could you try to reproduce the issue inside a complete Admin, like the [simple example project](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)?

**Comment by marit970** [comment]
@slax57 Hi, I have added a ResourceContext to my example project. Unfortunately, it did not solve the issue. We have tried to reproduce it in the condesandbox. With react v.17 it indeed does not appear, but with react v.18 it is broken: https://codesandbox.io/p/sandbox/elated-meitner-vvtqtt?file=%2Fsrc%2Findex.tsx%3A27%2C23 . The input field is not rendered but you can see the same errors in the console.

**Comment by slax57** [comment]
Hum right I forgot to upgrade to React 18 also. I'll try again then, thanks!

**Comment by slax57** [comment]
I was able to test (and reproduce) by myself and unfortunately, this still does not solve the issue.

Hence I have come up with a workaround for now: https://github.com/marmelab/react-admin/pull/9313

Hopefully this will be fixed by RHF themselves some time soon.

**Comment by marit970** [comment]
@slax57 Thank you for providing a workaround! :)
