### ISSUE TITLE
RichTextInput onBlur validation doesn't trigger

### ISSUE THREAD

**Issue by botjaeger** [marmelab/react-admin#9265]
**What you were expecting:**

It should trigger a validation error when touched

**What happened instead:**

It does nothing

**Steps to reproduce:**

```
<SimpleForm mode='all' reValidateMode='onChange'>
    ...
    <CustomRichTextInput />
</SimpleForm >
```

```
function CustomRichTextInput({ ...props }) {
    return (
        <RichTextInput
            fullWidth
            toolbar={(
                <RichTextInputToolbar size='small'>
                    <FormatButtons size='small' />
                    <ListButtons size='small' />
                </RichTextInputToolbar>
            )}
            validate={required()}
            {...props}
        />
    );
}
```

**Other information:**

**Environment**

* React-admin version: 3.14.3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Reproduced, thanks

**Comment by DxVxDOD** [comment]
Hi could I work on this ?

**Comment by fzaninotto** [comment]
@DxVxDOD There is already someone working on this (see the PR mentioned above your message).

**Comment by DxVxDOD** [comment]
Oh yeah... skipped my eye :)
