### ISSUE TITLE
Will i get this benefit even if I use graphql ?

### ISSUE THREAD

**Issue by DVGY** [marmelab/react-admin#9307]
Found it on refine vs react admin blog 
![image](https://github.com/marmelab/react-admin/assets/46158826/65447416-beb7-4676-94e6-58d3fda6fe52)

Is there any catch/caveat (performance and etc) if I use graphql instead of REST API ? I have a Hasura backend and looking for Admin framework to build the UI as Fast as Possible 

Thanks

**Comment by DVGY** [comment]
I asked this question in discord server. closing this now

**Comment by slax57** [comment]
As stated in [the contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use GitHub issues for bugs and feature requests only.

The [Discord server](https://discord.gg/B4G7AEQ3jm) is indeed one of the places to go for such questions, hence I'll close this issue and invite you to continue discussion on this channel instead.

FTR: [Message link](https://discord.com/channels/830711057643208724/830711057643208727/1155408963957964860)
