### ISSUE TITLE
Error when building app according to Remix v2 Integration Guide

### ISSUE THREAD

**Issue by ikenox** [marmelab/react-admin#9308]
Hi, I tried to build my app with Remix v2 according to [Remix Integration](https://marmelab.com/react-admin/Remix.html#setting-up-remix) guide step by step, and I encounted an error.

**What you were expecting:**

By following the Remix Integration guide, the app is successfully built with Remix v2.

**What happened instead:**

When I run `npm run dev`, I got an error `TypeError: jsonServerProvider is not a function`  and the app fails to start.

**Steps to reproduce:**

I created a minimum reproducible code.
https://github.com/ikenox/remix-v2-react-admin

```
$ git clone https://github.com/ikenox/remix-v2-react-admin.git
$ cd remix-v2-react-admin
$ npm install
$ npm run dev

> dev
> remix dev --manual


 💿  remix dev

 info  building...
 info  built (4.8s)
TypeError: jsonServerProvider is not a function
    at file:///Users/naoto.ikeno/tmp/remix-react-admin-2/build/index.js?t=1695627200457.7253:205:20
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Environment**

* React-admin version: 4.14.3
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by adguernier** [comment]
Hello @ikenox ,

I can reproduce, thanks for the report.

**Comment by djhi** [comment]
Hi @ikenox,

Until we release #9310, you have two workarounds:

## Workaround 1

Replace your dataProvider initialization code with:

```tsx
const dataProvider =
  jsonServerProvider.default != null
    // Make it work in Node
    ? jsonServerProvider.default("https://jsonplaceholder.typicode.com")
    // Make it work in browser
    : jsonServerProvider("https://jsonplaceholder.typicode.com");
```

## Workaround 2

Create a `dataProvider.client.ts` file and put your dataProvider initialisation code in it:

```tsx
import jsonServerProvider from "ra-data-json-server";

export const dataProvider = jsonServerProvider("https://jsonplaceholder.typicode.com");
```

Update your `App` code to import it.

**Comment by ikenox** [comment]
@djhi Thanks for speedy fix! I'll start my project with the workaround.
