### ISSUE TITLE
Changing any parameters of the ListGuesser empties the page 

### ISSUE THREAD

**Issue by djhi** [marmelab/react-admin#9318]
With the `ListGuesser`, when changing the sorting or the pagination parameters using the UI, we see a empty page (only the layout remains) for a time.

https://stackblitz.com/edit/github-qad8w5?file=src%2Fposts%2Findex.tsx

**Comment by dinaco** [comment]
Hey @djhi could you assign this issue to me? I'd like to work on it

**Comment by djhi** [comment]
Hi! We don't assign issues. Just open a PR :)
