### ISSUE TITLE
Make Confirm's confirmColor passable from DeleteButton

### ISSUE THREAD

**Issue by IAmVisco** [marmelab/react-admin#9322]
**Is your feature request related to a problem? Please describe.**
One of our team members expressed a concern that confirm to delete dialog's buttons are both primary color. They asked me if I could make the confirm one red, so I did a dive and apparently `Confirm` component supports `confirmColor` prop, but there's no way to pass it from `DeleteButton` component.

**Comment by slax57** [comment]
Thank you for your suggestion.
Indeed it looks like `DeleteWithConfirmButton` could support the `confirmColor` prop along with the other `Confirm` props, without too much trouble.
Would you like to open a PR to add support for this prop?

**Comment by IAmVisco** [comment]
Absolutely. I will see when I have time, hopefully this week.

**Comment by IAmVisco** [comment]
Not sure why merging the PR didn't close this automatically, but should be resolved in 4.15.0.

**Comment by slax57** [comment]
That's because the PR targeted `next`, and GH only closes the issues automatically when a PR gets merged to the repo's default branch.
But you were right to close the Issue, I would have done it eventually.
Thanks again!
