### ISSUE TITLE
Need the ability to delete ValidationErrorSpecialFormatPrefix "@@react-admin@@"

### ISSUE THREAD

**Issue by KislyakovDS** [marmelab/react-admin#9323]
Hi, I am using ra-core package for my project and I have component that using useInput(). My component gets error message from custom validation and now the error message looks like: @@react-admin@@"My error message". Could you make some option to delete this prefix?

**Environment**

* React-admin version: 4.14.4
* Last version that did not exhibit the issue (if applicable): 4.9.3
* React version: 18.2.0
* Browser: Chrome

**Comment by djhi** [comment]
Can't you use the `ValidationError` component from `ra-core` to display the message? It will handle the error format. See https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/ValidationError.tsx

**Comment by ZachSelindh** [comment]
I ran into the same issue you did and opened a PR to update the docs. Check out the i18n section of the Writing Your Own Input Component section:

https://marmelab.com/react-admin/Inputs.html#writing-your-own-input-component

**Comment by djhi** [comment]
Then we'll see when the need arise. Closing this issue now. Thanks!
