### ISSUE TITLE
DateTimeInput or DateInput reinitialise when typing a date starting with '0' - only on Firefox

### ISSUE THREAD

**Issue by guilbill** [marmelab/react-admin#9330]
Note: Only noticed on firefox.

**What you were expecting:**

I have a DateTimeInput field with a date `10/01/1985 10:20`:
![image](https://github.com/marmelab/react-admin/assets/560852/2414a8c9-826f-4f55-be8e-a87f08ed6283)

I select the field and type "01". The date is now `01/01/1985 10:20`

**What happened instead:**

The field is reinitialized as soon as I type the '0' 
![image](https://github.com/marmelab/react-admin/assets/560852/c1ec3731-0218-4078-87b0-ec105a58d730)

**Steps to reproduce:**

Go to https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-input-datetimeinput--basic
Type a valid date.
Now focus the beginning of the field, and type '0' (as if you want to type '01' for exemple) 

**Related code:**

The basic stackblitz is enough to reproduce. 
https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple
On firefox : Edit a Post > Miscellanous > Edit a date input by starting by a '0'

```
<DateTimeInput source='foo'/>
```

**Other information:**

I first though of a behaviour of the html input on firefox. But trying it directly : 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local 
I did not reproduce the same behaviour.

**Environment**

* React-admin version: "4.13.2"
* React version: "18.2.0"
* Browser:  Firefox 118.0.1 (64 bits)

**Comment by slax57** [comment]
Reproduced, thanks!
