### ISSUE TITLE
Documentation issues with yarn link

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#9331]
Hi @djhi, I am still trying to troubleshoot the vitest issue in https://github.com/marmelab/react-admin/pull/9309 by changing exports field in package.json 

However I found part of the tutorial in https://github.com/marmelab/react-admin#testing-your-changes-in-your-app is outdated since this commit. https://github.com/marmelab/react-admin/commit/8fe89469d1ad44056215e66ff2cd84aa72b2c595

**What you were expecting:**

Yarn link should not produce any problem regardless of yarn version

**What happened instead:**

Unable to link to a local copy with error:
Unknown Syntax Error: Not enough positional arguments.

**Steps to reproduce:**

Follow the steps in Testing Your Changes in Your App

**Other information:**

We should split this part of tutorial.
If client app is using yarn classic, they should follow https://classic.yarnpkg.com/lang/en/docs/cli/link/ to use

> $ YARN_IGNORE_PATH=1 yarn link

If client app is using yarn berry, they only need to link to the workspace

`yarn link /code/path/to/react-admin/packages`

**Environment**

* React-admin version: 4.14.4
* Last version that did not exhibit the issue (if applicable): 4.0.0-alpha.1 before https://github.com/marmelab/react-admin/commit/8fe89469d1ad44056215e66ff2cd84aa72b2c595 is merged
* React version: 18.2.0
* Browser: Safari 16.5.1
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Good catch! Do you mind opening a PR?

**Comment by djhi** [comment]
Fixed by #9341
