### ISSUE TITLE
Add hacktoberfest topic

### ISSUE THREAD

**Issue by richecr** [marmelab/react-admin#9347]
As we are in October, the [Hacktoberfest 2023](https://hacktoberfest.com/) event is taking place, it could be a good way to attract contributions from developers.

**Comment by fzaninotto** [comment]
We've done that several times in the past, and it didn't bring any significant benefit to the project. Lots of low-quality PRs brought low benefit at a significant triage and review cost. 

Marmelab has more than 500 contributors. We welcome third-party contributions every month of the year - not just in October. 

We'll pass hacktoberfest this year.
