### ISSUE TITLE
Allow to disable notification that is shown on invalid form submits

### ISSUE THREAD

**Issue by tim-hoffmann** [marmelab/react-admin#9350]
**Is your feature request related to a problem? Please describe.**
When a form is invalid a notification is shown on the bottom of the screen. I want to be able to disable the notification.

**Describe the solution you'd like**
There could be a prop or similar to disable the notification.

**Describe alternatives you've considered**
I checked the code and couldn't find an option to disable the notification. Only if I create a custom Form component, which wouldn't make much sense, since it would be basically copy paste.

**Additional context**
![image](https://github.com/marmelab/react-admin/assets/2560969/43b2765c-c607-4548-b66e-a476cf3b1c77)

**Comment by djhi** [comment]
That sounds reasonable. Can you open a PR?

**Comment by tim-hoffmann** [comment]
Ok, will create a PR.

**Comment by djhi** [comment]
Thanks, as this will be a new feature, please target the `next` branch :pray:

**Comment by fzaninotto** [comment]
Fixed by #9353
