### ISSUE TITLE
BulkDeleteButtonProps's resource not honored

### ISSUE THREAD

**Issue by jbek7** [marmelab/react-admin#9355]
**What you were expecting:**
When I set [resource to `<BulkDeleteButton>`'s
](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/BulkDeleteButton.tsx#L55) - it supposed to use that resource for deleteMany request.

**What happened instead:**
However the resource is undefined during the deleteMany request.

**Steps to reproduce:**
Try using `<BulkDeleteButton resource="different-delete-resource">` - in my case I've a resource that lists custom view from database and another resource that represents the view's primary table. 

**Related code:**
I've tried wrapping the bulk delete button inside a resource provider context too:
```
<ResourceContextProvider value="different-delete-resource">
        <BulkDeleteButton mutationMode={"confirm"} />
    </ResourceContextProvider>
``` 
but still the [resource](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx#L43) is undefined at BulkDeleteWithConfirmButton#L43.

**Environment**

* React-admin version: 4.14.3
* Last version that did not exhibit the issue (if applicable): N/A
* React version:  17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Please provide a StackBlitz reproducing the issue, e.g. based on https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple

**Comment by fzaninotto** [comment]
No news for some time, closing.
