### ISSUE TITLE
disableAuthentication prop on (Infinite)List is ignored when used on a Dashboard

### ISSUE THREAD

**Issue by milutinovici** [marmelab/react-admin#9363]
**What you were expecting:**
I want to have a root page, that's a List, to not require authentication. 

**What happened instead:**
Page redirects to login.

* React-admin version: 4.15.0
* React version: 18.2.0

**Comment by slax57** [comment]
Please follow the issue template (including a repro)

**Comment by milutinovici** [comment]
Here you go

https://stackblitz.com/edit/github-nmv8yb

**Comment by slax57** [comment]
I see you have put `disableAuthentication` only on the mobile version of the List, but not on the desktop version. Is it intended?

**Comment by milutinovici** [comment]
Yeah sorry. Didn't see. I edited the template
