### ISSUE TITLE
Incorrect handling of lists and non-nullability in arguments by ra-data-graphql-simple 

### ISSUE THREAD

**Issue by dricholm** [marmelab/react-admin#9370]
**What you were expecting:**

I have a GraphQL endpoint, which expects a non-nullable list with non-nullable items. Using `ra-data-graphql-simple` it should build the query matching the introspection result, for the above example both list and item should be non-nullable: `[ID!]!`.

**What happened instead:**

`ra-data-graphql-simple` creates the argument as `[ID!]`, meaning only the items are non-nullable, while the list is nullable. This will throw an error as the expected types are different.

**Steps to reproduce:**

- Have a GraphQL endpoint where an argument should be of type list with both list and items non-nullable.
- Let `ra-data-graphql-simple` generate the query automatically.
- Confirm generated query is not according to the introspection result and API throws an error due to incorrect types.

**Related code:**

Since it requires a GraphQL endpoint couldn't create a reproducible sandbox. I will open a PR with updated unit tests. Running the unit tests against `master` would fail in `buildGqlQuery.test.ts`:

```ts
it('returns the arg type for NON_NULL LIST with nullable item type', () => {
    expect(
        print(
            getArgType({
                name: 'arg',
                type: {
                    kind: TypeKind.NON_NULL,
                    ofType: {
                        kind: TypeKind.LIST,
                        ofType: {
                            kind: TypeKind.SCALAR,
                            name: 'ID',
                        },
                    },
                },
            })
        )
    ).toEqual('[ID]!');
});
```

**Other information:**

[Article about nullability and lists on Apollo blog](https://www.apollographql.com/blog/graphql/basics/using-nullability-in-graphql/#nullability-and-lists). As stated lists can be nested and non-nullable can apply to both list and items independently.

**Environment**

* React-admin version: 4.15.0
* Last version that did not exhibit the issue (if applicable): -
* React version: 18
* Browser: Chrome
* Stack trace (in case of a JS error): -

**Comment by slax57** [comment]
Confirmed, thanks for the report!
