### ISSUE TITLE
CustomRoutes not displaying in sidebar

### ISSUE THREAD

**Issue by wallacer** [marmelab/react-admin#9383]
[Here is my codesandbox](https://codesandbox.io/p/sandbox/condescending-booth-tqhch4) where I created a SimpleCard component which just renders `<h1>Hello World!</h1>` inside a `Card`.  I've not passed `noLayout` - and my component includes a `Title` component, so based on the docs.

**What you were expecting:**
I expect my custom route for my simple card component to appear in the sidebar, with the title I've used - "Hello".

**What happened instead:**
Nothing changes in the sidebar, no matter whether the CustomRoute is used or not.

**Steps to reproduce:**
Use a `CustomRoutes` component, with or without a `Title` component in it, and without passing `noLayout`.

**Related code:**
https://codesandbox.io/p/sandbox/condescending-booth-tqhch4

**Environment**

* React-admin version:  4.15.1
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by wallacer** [comment]
Weird!  Github bug or something, I wrote a detailed description.  I'll edit and add it back.

**Comment by slax57** [comment]
Hi @wallacer 

Custom Routes don't appear automatically in the menu, as we wouldn't know what label to use, or what to do with nested routes.

You need to use a [custom Menu](https://marmelab.com/react-admin/Menu.html) to show them.

**Comment by fzaninotto** [comment]
Also from the doc: https://marmelab.com/react-admin/CustomRoutes.html#linking-to-custom-routes

**Comment by wallacer** [comment]
Got it, sorry about that.  I was thinking the `Title` component [handled that](https://marmelab.com/react-admin/CustomRoutes.html#custom-page-title)   But I think I just mis-read app bar as side bar.

FWIW the other slightly confusing piece of documentation was [noLayout](https://marmelab.com/react-admin/CustomRoutes.html#nolayout).  "By default, custom routes render within the application layout (with the menu and the app bar)".

I had already landed on creating a custom `Menu`, but really appreciate the clarification here :)

**Comment by fzaninotto** [comment]
You've got a point: the CustomRoutes doc could be improved. I made a PR for that: #9404.
