### ISSUE TITLE
FilterLiveSearch input with "Enter" keyboard causes wrong url

### ISSUE THREAD

**Issue by lamtranb** [marmelab/react-admin#9387]
**What you were expecting:**
FilterLiveSearch input with "Enter" keyboard should have correct url  [https://marmelab.com/react-admin-demo/#/customers?q=test](https://marmelab.com/react-admin-demo/#/customers?q=test)

**What happened instead:**
FilterLiveSearch input with "Enter" keyboard cause wrong url

**Steps to reproduce:**
1. Go to [https://marmelab.com/react-admin-demo/#/customers](https://marmelab.com/react-admin-demo/#/customers)
2. Type any thing inside "Search input"
3. Press "Enter"
4. Observe the url: [https://marmelab.com/react-admin-demo/?q=test#/customers?filter=%7B%22q%22%3A%22test%22%7D&order=DESC&page=1&perPage=25&sort=last_seen](https://marmelab.com/react-admin-demo/?q=test#/customers?filter=%7B%22q%22%3A%22test%22%7D&order=DESC&page=1&perPage=25&sort=last_seen)

**Related code:**
 [https://marmelab.com/react-admin-demo/#/customers](https://marmelab.com/react-admin-demo/#/customers)

**Environment**

* React-admin version: 4.12.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome Version 118.0.5993.89 (Official Build) (64-bit)
* Stack trace (in case of a JS error): N/A

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report
