### ISSUE TITLE
useInfiniteGetList returns total as undefined, when real value equal to 0

### ISSUE THREAD

**Issue by KislyakovDS** [marmelab/react-admin#9388]
I have my own dataProvider for getList and I return object like `{ data: [], total: 0 };`

**What you were expecting:**
I am expecting the total value in useListContext is equal to 0.

**What happened instead:**
When total in dataProvider is equal to 0, I receive in useListContext total value as undefined.

There is such code in useInfiniteGetList:
```
return (result.data
	? {
		  ...result,
		  data: result.data,
		  total: result.data?.pages[0]?.total || undefined,
	  }
	: result) as UseInfiniteQueryResult<
	GetInfiniteListResult<RecordType>,
	Error
> & {
	total?: number;
};
```

**Environment**

* React-admin version: 4.15.1
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
You're right, the `|| undefined` should be replaced by `?? undefined`. Would you mind opening a PR, including a unit test that shows that the bug is solved?

**Comment by parthrc** [comment]
hey @fzaninotto can I wok on this?
