### ISSUE TITLE
Pagination doesn't use prop perPage properly

### ISSUE THREAD

**Issue by jswrnr** [marmelab/react-admin#9401]
**What you were expecting:**

I passed the perPage prop with the value 250 to a Pagination component for my List.
I expected this to be used as a default value of how many elements to show per page.

**What happened instead:**

250 is shown at the bottom as the selected value for elements per page, but the backend call is still done for 10 elements (the default)

![image](https://github.com/marmelab/react-admin/assets/64600096/eea8a90f-7b96-4e47-aa1c-59e5b89f8ba4)

**Steps to reproduce:**

I passed this 

const PostPagination = () => (
    <Pagination rowsPerPageOptions={[5, 10, 25, 50, 100, 250]} perPage={250} />
  );

to my List component as in:

<List pagination={<PostPagination />} >

**Comment by fzaninotto** [comment]
There is no `perPage` option in the `<Pagination>`component:

https://marmelab.com/react-admin/Pagination.html

If you want to preset the number of elements per page, use the `<List perPage>` prop.
