### ISSUE TITLE
ChipField is broken inside TabbedShowLayout.Tab

### ISSUE THREAD

**Issue by andkom** [marmelab/react-admin#9405]
**What you were expecting:**

ChipField looks normal inside TabbedShowLayout.Tab.

**What happened instead:**

ChipField design is broken. ChipField is stretched to 100% of width.

<img width="738" alt="Screenshot 2023-10-27 at 10 27 41" src="https://github.com/marmelab/react-admin/assets/150830/f95a6cc4-54f1-4d3c-81c0-7e43f5a7fc0e">

**Steps to reproduce:**

1. Put ChipField inside TabbedShowLayout.Tab 

**Related code:**

```
export const UserShow = () => (
  <Show>
    <SimpleShowLayout>
      <ChipField source="status" />
    </SimpleShowLayout>

    <TabbedShowLayout>
      <TabbedShowLayout.Tab label="Main">
        <ChipField source="status" />
      </TabbedShowLayout.Tab>
    </TabbedShowLayout>
  </Show>
);

```

**Environment**

* React-admin version: 4.15.1
* React version: 18.2.0
* Browser: Chrome 118.0.5993.70

**Comment by fzaninotto** [comment]
Reproduced, thanks!

**Comment by slax57** [comment]
@gitstart  sure you can open a PR. Thanks :slightly_smiling_face:
