### ISSUE TITLE
CustomRoutes with /* or * as path does not get rendered on root page

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#9411]
**What you were expecting:**

I expect passing a custom route with a match all case would always work, even for the root page

**What happened instead:**

Visiting the root page gives a blank layout

**Steps to reproduce:**

Go to the following stackblitz project https://stackblitz.com/edit/github-dk2hz7?file=src%2Findex.tsx and visit root page

**Related code:**

```
https://stackblitz.com/edit/github-dk2hz7?file=src%2Findex.tsx
```

**Other information:**

If a custom route with `/*` or `*` is present, both the `/` and `*` routes https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRoutes.tsx#L91 here no longer need to be rendered.
Then it's up to the user to implement all the nested routes by them selves using all the react-admin's context.

**Environment**

* React-admin version: 4.15.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Safari
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
If you need a custom route that matches all paths, the admin routes will never get rendered. Can you explain what is your use case?

**Comment by smeng9** [comment]
Hi @fzaninotto, our use case here is we have a large enterprise application. It takes a long time to start dev environment and build so we are migrating towards module federation that have separate builds, and each small build can be updated individually.

In the dev environment we develop a module under `<CustomRoutes>`. The module consist a route with /* to match all sub paths and all the business logic under this route and can still use the react-admin context. In the production this route will be published as remote module, and mounted under a different path like /app1, /app2, ... There will be many other routes and resources in the production environment.

```
<Route path="/app1/*>
  <Routes>
    // The module federation route with path /* goes here
    ...
  </Routes>
</Route>
```

The module matches the /* path for the development and we don't need the / route rendered in the development. In production we will use the / route from a different application.

**Comment by fzaninotto** [comment]
Thanks for your feedback. I consider this an uncommon use case and react-admin won't support it. You'll have to use CustomRoutes instead of Resources to build your custom route configuration.
