### ISSUE TITLE
The "Add Filter" menu appears in the corner of the screen after close

### ISSUE THREAD

**Issue by archik408** [marmelab/react-admin#9412]
What you were expecting:
The "Add Filter" menu should close (the status is open in false) after clicking on "Remove all filters" and button  "Add Filter" should disappear.

What happened instead:
The "Add Filter" button disappears, since there are no filters, but as soon as you enter a new filter, the "Add Filter" menu immediately appears in the corner of the screen.

Steps to reproduce:

1. Open demo https://marmelab.com/react-admin-helpdesk/#/tickets
2. Choose "Customer" filter
3. Click on "Add filter"
4. Click on "Remove all filters"
5. Choose again "Customer" filter
6. The "Add filter" menu appears in the corner of the screen.

https://github.com/marmelab/react-admin/assets/10139861/cf072491-597d-4fa7-9065-27d843a3e14d

<img width="1413" alt="Screenshot 2023-10-31 at 10 21 07" src="https://github.com/marmelab/react-admin/assets/10139861/65e35281-5cbb-48e9-b07a-2cd425ed7f51">

**Environment**

* React-admin version: 4.12.3
* React version: 18.2.0
* Browser: Chrome Version 118.0.5993.88 (Official Build) (x86_64)

**Comment by archik408** [comment]
I think just need add one more line of code in https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/filter/FilterButton.tsx
instead of
```
{hasFilterValues && (
                    <MenuItem onClick={() => setFilters({}, {}, false)}>
                        {translate('ra.action.remove_all_filters', {
                            _: 'Remove all filters',
                        })}
                    </MenuItem>
                )}
```
need
```
{hasFilterValues && (
                    <MenuItem onClick={() => {
                        setFilters({}, {}, false);
                        setOpen(false);
                     }}>
                        {translate('ra.action.remove_all_filters', {
                            _: 'Remove all filters',
                        })}
                    </MenuItem>
                )}
```

**Comment by erwanMarmelab** [comment]
reproduced, thanks!
