### ISSUE TITLE
Expose the queryKey in the useGetList hook and in the rest of the get hooks

### ISSUE THREAD

**Issue by danielfsmith91** [marmelab/react-admin#9416]
The way the get hooks are now, there is no way to target just one to do a refresh. On the other hand, to refresh a list in case of making any update, you must use useRefresh, which updates all the queries of the app, when there are some that do not need to be updated. And this means that more requests are made and the one that should be updated at that moment is delayed. It would be very good and necessary to expose the query key with which the request is made internally to be able to update only the request that is needed.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. I'm not sure I understand what you're asking with "expose the queryKey". 

The query key is already documented, see e.g. [the useGetList documentation](https://marmelab.com/react-admin/useGetList.html#syntax):

<img width="771" alt="image" src="https://github.com/marmelab/react-admin/assets/99944/5853c0b5-8200-4200-85cb-f98c4e43838a">

It is also easy to find in the source code of the `useGetList` hook:

https://github.com/marmelab/react-admin/blob/f71d3927c12ef736adab9da4b10ff4c8e2ae6111/packages/ra-core/src/dataProvider/useGetList.ts#L74

What more do you want?

**Comment by danielfsmith91** [comment]
> Hi, and thanks for your question. I'm not sure I understand what you're asking with "expose the queryKey".
> 
> The query key is already documented, see e.g. [the useGetList documentation](https://marmelab.com/react-admin/useGetList.html#syntax):
> <img alt="image" width="771" src="https://user-images.githubusercontent.com/99944/279886174-5853c0b5-8200-4200-85cb-f98c4e43838a.png">
> 
> It is also easy to find in the source code of the `useGetList` hook:
> 
> https://github.com/marmelab/react-admin/blob/f71d3927c12ef736adab9da4b10ff4c8e2ae6111/packages/ra-core/src/dataProvider/useGetList.ts#L74
> 
> What more do you want?

Real example:
I have two lists in the same view. I change a piece of information from the 1st. To do the update, I have to use useRefresh. The useRefresh invalidates all the queries, therefore, the 2 lists will be updated unnecessarily. The only way to update only one list is to have the queryKey so you can invalidate only that query and it is updated.

In the useGetList code, the queryKey is generated inside. Therefore, I have no way to obtain that queryKey from outside, to be able to do the above.

![Screenshot at 2023-11-02 09-25-55](https://github.com/marmelab/react-admin/assets/53831261/5f20da31-c73d-47f0-ac4c-7493e701cb6c)

On the other hand, if they expose the queryKey, only the desired request could be obtained and updated

![Screenshot at 2023-11-02 09-44-04](https://github.com/marmelab/react-admin/assets/53831261/1e0538b1-9614-41c3-94d0-8c425e7e5709)

![Screenshot at 2023-11-02 09-44-46](https://github.com/marmelab/react-admin/assets/53831261/8f654668-a6d3-4f5b-974e-dee27608f07d)

![Screenshot at 2023-11-02 09-47-55](https://github.com/marmelab/react-admin/assets/53831261/572cd04f-ad8c-4487-a35b-716e9f8370c0)

**Comment by fzaninotto** [comment]
All data provider hooks already return a `refresh` callback:

```jsx
const { data, total, isLoading, refetch } = useGetList(...);
```

Doesn't it solve your problem?

**Comment by danielfsmith91** [comment]
> All data provider hooks already return a `refresh` callback:
> 
> ```js
> const { data, total, isLoading, refetch } = useGetList(...);
> ```
> 
> Doesn't it solve your problem?

yes :) Thanks
