### ISSUE TITLE
Expose onClick on LoadingIndicator

### ISSUE THREAD

**Issue by david-bezero** [marmelab/react-admin#9418]
**Is your feature request related to a problem? Please describe.**
The suggested way to trigger cache invalidation when the user presses the built-in "refresh" icon in the `AppBar` is to replace the button, as there is no way to know that a request came from the refresh button from the data-provider layer. The default component in the `AppBar` is the `LoadingIndicator`, which provides the nice behaviour of showing a loading state, but otherwise just wraps `RefreshIconButton`.

`RefreshIconButton` has an `onClick` property, which can be used to trigger cache invalidation. But this property is not exposed when using `LoadingIndicator`.

**Describe the solution you'd like**
Add `onClick` to `LoadingIndicator` and forward this property to `RefreshIconButton`.

The usage would be:

```jsx
function doMyCacheInvalidation() {
  // store some global state which can be picked up by the data-provider to force a cache invalidation
}

const MyAppBar = () => {
  const toolbar = (
    <>
      <LoadingIndicator onClick={doMyCacheInvalidation} />
    </>
  );
  return <AppBar toolbar={toolbar} />;
};
```

**Describe alternatives you've considered**
Automatically passing the "refresh" information to the data provider as a `meta` property when the button is clicked would also work, but it seems that has been suggested before and rejected.

Another option is to forego the `LoadingIndicator` and use `RefreshIconButton` directly, but this loses the built-in loading state. It can be added back in manually, but then a lot of code needs to be copied over from react-admin into the client app to get consistent styling.

**Comment by fzaninotto** [comment]
I fail to understand your use case. Can you please rephrase your pain point? What data are you trying to refresh?

**Comment by david-bezero** [comment]
I basically have the same use-case as this person: https://github.com/marmelab/react-admin/issues/3617

I'm implementing the approach you suggested here: https://github.com/marmelab/react-admin/issues/3617#issuecomment-525812935

> In react-admin, the path between the click on Refresh and the actual queries in the data provider takes many, many steps, and passing parameters through these steps isn't possible. So I suggest you solve this in userland, by implementing your own RefreshButton that stores a boolean in sessionStorage to force refresh, and the dataProvider can read this boolean before making requests.

So the (working) code I have right now looks like this:

```tsx
import { FC } from 'react';
import { AppBar, RefreshIconButton, useLoading } from 'react-admin';
import CircularProgress from '@mui/material/CircularProgress';
import { useTheme } from '@mui/material/styles';

const PatchedLoadingIndicator: FC<{ onClick?: () => void }> = ({ onClick }) => {
  // TODO: replace this with LoadingIndicator once this is resolved:
  // https://github.com/marmelab/react-admin/issues/9418
  const loading = useLoading();
  const theme = useTheme();
  return loading ? (
    <CircularProgress
      className="app-loader"
      style={{
        marginLeft: theme.spacing(1.5),
        marginRight: theme.spacing(1.5),
      }}
      color="inherit"
      size={theme.spacing(2)}
      thickness={6}
    />
  ) : (
    <RefreshIconButton onClick={onClick} />
  );
};

export const MyAppBar = () => {
  const toolbar = (
    <>
      <PatchedLoadingIndicator onClick={invalidateCache} />
    </>
  );
  return <AppBar toolbar={toolbar} />;
};

function invalidateCache() {
  window.dispatchEvent(new CustomEvent('invalidate-cache'));
}
```

(the event is picked up inside my custom data provider and used to invalidate a cache)

But notice that I had to effectively re-implement `LoadingIndicator`, including some relatively nasty stuff to get the styling correct. It would be much nicer if I could use the native `LoadingIndicator` in the same way.

**Comment by david-bezero** [comment]
it may also be worth noting (mostly for future people seeing this who want to follow the same approach) that the `onClick` callback is invoked _after_ starting the data refresh, so to make this work I also added `await Promise.resolve()` to `withLifecycleCallbacks`'s `beforeGetMany` method (or equivalently the start of the data provider's `getList` method) so that the event is observed and acted on before the actual request begins (it only needs a single microtask's delay).

I guess it would also be _nice_ if the `onClick` callback were invoked _before_ calling the data refresh, to avoid this requirement, but that change could potentially break existing code.

**Comment by fzaninotto** [comment]
Ah, now I understand better, thanks.

We prefer to keep the API of our components as limited as possible (cf [Minimal API Surface](https://marmelab.com/react-admin/Architecture.html#minimal-api-surface)), and your use case is, in my opinion, not common enough to justify adding a new prop. 

As you can (and did) already achieve what you want in user land, we won't move forward with this proposal. 

Thanks anyway for the suggestion!

**Comment by david-bezero** [comment]
I guess I'm mostly concerned that by having to copy over the implementation from React-Admin, I won't be getting any future updates you make to that component (also my implementation is slightly diverged since some styles were more awkward to copy over).

The change I'm requesting is very minimal, and I'd be happy to make a PR for it if it's something you would consider?

**Comment by david-bezero** [comment]
I have created #9420 which implements the requested change.
