### ISSUE TITLE
Add a client-side sorting feature to the <List/> element

### ISSUE THREAD

**Issue by kindaway** [marmelab/react-admin#9421]
The point of this feature: if I have a lot of fields, I need to implement sorting on the backend for every field, which is really cumbersome.
Instead, it'd be convenient to enable sorting on the records we already have on the page, in pure js with simple sort(). This can be done easily in pure React+JS, but this would require to rewrite the whole SPA without react-admin :(

The solution is to add an ability to override the sorting feature of the List component. 

Any thoughts on this? Or is it just me? 😄

**Comment by fzaninotto** [comment]
It's already implemented: check [the `useList` hook](https://marmelab.com/react-admin/useList.html).
