### ISSUE TITLE
Validation Message for Reference Input is not Showing

### ISSUE THREAD

**Issue by tauqeer-trailfive** [marmelab/react-admin#9427]
**What you were expecting:**
Validation Message Should appear underneath Reference field

**What happened instead:**
Validation Message is Appearing.

**Steps to reproduce:**
Here it is i provided code sandbox and you can visit Create Comment Page to Reproduce this issue in below code.
 - https://codesandbox.io/p/sandbox/silly-moore-sq7vhv

```
<ReferenceInput
     source="posts"
     reference="posts"
     validate={required("This is required Field")}
     perPage={10}
  >
     <AutocompleteInput
       fullWidth
        key="Post"
        source="id"
        isRequired
        optionText={(choice) => `${choice.title}  /  (${choice.id})`}
        optionValue="id"
        noOptionsText="Post does'nt exist."
        label="Select Post"
        />
      </ReferenceInput>
```

**Other information:**

**Environment**

* React-admin 4.12.0:
* Last version that did not exhibit the issue (if applicable):
* React version ^17.0.0:
* Browser: Chrome

**Comment by tauqeer-trailfive** [comment]
@djhi This error is same issue not #3849

**Comment by adguernier** [comment]
Hello @tauqeer-trailfive ,

I'm afraid I don't understand the problem and don't see any bugs with the sandbox you provided.

If your issue concerns the required validation that does not work, well, you have to provide the `validate={required("This is required Field")}` prop in the `<AutocompleteInput>`.

If not, might you be more explicit and provide a reproducible sandbox without the need of copy/paste code. Thanks

**Comment by tauqeer-trailfive** [comment]
@adguernier its working now thanks.
