### ISSUE TITLE
Feature Request :  Date Range Picker Input

### ISSUE THREAD

**Issue by tauqeer-trailfive** [marmelab/react-admin#9429]
**Is your feature request related to a problem? Please describe.**
Yes, I have Form in which I have to give start and end date of a event and I want if I chose a date in `endDate` then that **date**, **past** dates from selected date should be disabled in other (`startDate`) input field and **future** dates should enabled.

**Describe the solution you'd like**
As far as I think the solutions is to add some date Range pickers from [**Date Range Picker**](https://mui.com/x/react-date-pickers/date-range-picker/) as currently react-admin does only contain simple date-Picker.

**Describe alternatives you've considered**
As a alternative approach i do some array manipulations to take a date from first date picker in my example case. but it sometime crashed during testing its not a valid way to do this thing.

**Additional context**
screenshot about the feature request here.

![image](https://github.com/marmelab/react-admin/assets/108520807/f4b7ee63-6575-4ef2-bee8-25fb2bc0a5c1)

**Comment by fzaninotto** [comment]
Thanks for your suggestion. This is already handled by a third-party package, https://www.npmjs.com/package/react-admin-mui-dateinputs, and we don't intend to integrate it in the core.

**Comment by fzaninotto** [comment]
My bad, the linked repo doesn't contain a daterange input. I'm marking this as a feature request, and we will gladly accept a PR implementing it. If this PR doesn't receive community traction, we'll close it within a couple months.

**Comment by fzaninotto** [comment]
No news for some time, closing.
