### ISSUE TITLE
Feature Request: Enhancing `<CheckForApplicationUpdate>` for module federation apps

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#9432]
**Is your feature request related to a problem? Please describe.**

1. Our application uses the module federation design but the `<CheckForApplicationUpdate>` can only check for a single url. It cannot check multiple urls for each module

2. Additionally the fetch function in getHashForUrl https://github.com/marmelab/react-admin/blob/f030350259ab8a5eb006b82a2a800568c6ee9230/packages/ra-core/src/util/useCheckForApplicationUpdate.ts#L61 does not support passing additional options like cache control, so even after the interval has passed, it may check for a stale copy of data from cache which breaks the purpose of CheckForApplicationUpdate. This may be a bug.

3. We would also like an additional callback function handleApplicationUpdate passed into the `<CheckForApplicationUpdate>` so we can customize the button click behavior https://github.com/marmelab/react-admin/blob/f030350259ab8a5eb006b82a2a800568c6ee9230/packages/ra-ui-materialui/src/layout/ApplicationUpdatedNotification.tsx#L17 like making backup of localstorage, give user warning about potential data loss, etc.

**Describe the solution you'd like**

Enhance the `<CheckForApplicationUpdate>` interface to make url support an array of strings, add the fetch options object, and add the callback.

**Describe alternatives you've considered**

Stack a bunch of CheckForApplicationUpdate in the layout, each checking for a single url. However that would not solve problem 2 and 3.
Hope these enhancement can benefit other people so they don't have to reimplement the react hooks.

**Additional context**

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback. 

Regarding your points:

1. The `CheckForApplicationUpdate` component won't support module federation. You will have to build your own component for that. 
2. We're open to a PR adding the support for an `options` prop passed as second argument to `fetch`
3. It's already possible: the parameter is called `onNewVersionAvailable`. We do need to document it, though, so I'm marking this as a documentation issue.
