### ISSUE TITLE
Remix & Supabase Example possible correction

### ISSUE THREAD

**Issue by ShaneC112** [marmelab/react-admin#9445]
I was following the remix example and experienced the following.

When requesting a list of less than 10 items the fetchUtils was giving a net::ERR_CONTENT_DECODING_FAILED 200 (OK) response.
When requesting a list of 11 items or more then fetchUtils was working perfectly !

I cloned the marmelab/ra-supabase example and adding a Remix app to the project it works perfectly with the example.

There appears to be a difference between a local supabase setup and using the hosted online version.

It appears the hosted Supabase adds Content-Encoding of "br" when the list is less than 10. This causes the resolution of the response.text promise within the fetchUtil to fail.

Changing the headers in the admin.api.$.tsx to specify Accept-Encoding: '' appears to resolve the issue and supabase returns the content not encoded (compressed) and the fetchUtil works.

    headers: {
      prefer: request.headers.get("prefer") ?? "",
      accept: request.headers.get("accept") ?? "application/json",
      'Accept-Encoding': '',
      apiKey: `${process.env.SUPABASE_SERVICE_ROLE}`,
      Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE}`,
    },

If there is a better alternative or fix which is usually used and the above is incorrect I'd appreciate knowing.

**Comment by erwanMarmelab** [comment]
reproduced, thanks
