### ISSUE TITLE
useShowContext returns record from list endpoint

### ISSUE THREAD

**Issue by sebashwa** [marmelab/react-admin#9451]
I'm using a REST-API and I'm returning a minimal record from the list endpoint (e.g. `/posts`) and a full version record from the detail endpoint (e.g. `/posts/2`). I'm also using `useShowContext` for the show page.

**What you were expecting:**
I was expecting `useShowContext` to always return the record fetched via `getOne`, as stated in the documentation:

```JS
const {
  [...]
  record, // record fetched via dataProvider.getOne() based on the id from the location
  [...]
} = useShowContext();
```

**What happened instead:**
The record from the list endpoint (probably cached via react query) is returned from `useShowContext`.

**Steps to reproduce:**
Return different records from your REST-API for list / detail endpoints (see edited `getList` for posts in the example `dataProvider` below). Navigate from your list page (posts) to the show page.

**Related code:**
[See this example](https://stackblitz.com/edit/github-msupcd?file=src%2FdataProvider.tsx,src%2Fposts%2FPostShow.tsx)

**Environment**

* React-admin version: 4.15.4
* Last version that did not exhibit the issue (if applicable): -
* React version: 18.2.0
* Browser: all

**Comment by erwanMarmelab** [comment]
Hi @sebashwa ,

The bug you are reporting is a feature. As you can read in [optimistic rendering](https://marmelab.com/react-admin/Caching.html#optimistic-rendering) and [features](https://marmelab.com/react-admin/Features.html#fast) documentations, we make an "optimistic rendering".

Cheers,

Erwan

**Comment by sebashwa** [comment]
Hi @erwanMarmelab,

thanks for your fast answer! Sorry I didn't find the Caching docs, it explains the behaviour very well. I think it would be good to link this page from some other places in the documentation (especially where it states that the response from `.getOne` is returned for `record`). I'd like to open a PR for this, if you think that's useful?

**Comment by fzaninotto** [comment]
Great idea, please open a PR!
