### ISSUE TITLE
useFormContext return null because of dependency of react-hook-form

### ISSUE THREAD

**Issue by flynncodeit** [marmelab/react-admin#9461]
My project dependency react-hook-form@^4.47.0 but react-admin@4.16.0 dependency eact-hook-form@^4.43.0 

So useFormContext is not working!

**What you were expecting:**

useFormContext return the appropriate form context

**What happened instead:**

useFormContext return null

**Other information:**

**Environment**

* React-admin version: 4.16.0
* Last version that did not exhibit the issue (if applicable): 
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
This isn't a react-admin bug, it's the state of the React ecosystem... Having two versions of the same package will break apps, as the context written by one version can't be read by the other version. 

It's your job to deduplicate dependencies, either by using the same version as react-admin, or by using the `resolutions` field in your `packages.json`.
