### ISSUE TITLE
Support Material UI Data Grid

### ISSUE THREAD

**Issue by oliviertassinari** [marmelab/react-admin#9467]
**Is your feature request related to a problem? Please describe.**

Add support for https://mui.com/x/react-data-grid/.

**Describe the solution you'd like**

Similar to https://marmelab.com/react-admin/DatagridAG.html

**Describe alternatives you've considered**

/

**Additional context**

Motivation

- I would expect Material UI Data Grid to provide a better integration with the rest of the react admin application than AG Grid. e.g. sharing the same theme.
- Could simplify the implementation of https://marmelab.com/ra-enterprise/modules/ra-editable-datagrid, cell and row edit is licensed MIT under the  Material UI Data Grid.
- Engineering team already having an MUI X license for some of the components won't need another license for a data grid

But overall, we will see, I'm curious to see if this get upvotes.

**Comment by fzaninotto** [comment]
Thanks for your suggestion. MUI X Data Grid is indeed a great component, and we hesitated between it and Datagrid AG for the Enterprise Edition's advanced Datagrid component. 

A react-admin binding to MUI X Data Grid would be nice indeed. However the core team has no plans for implementing it in the open-source edition. You're welcome to publish a third-party package doing so. 

We may consider it in the Enterprise Edition, but we need more insight from the market on DatagridAG before going further. If you need us to write it for one of your projects, please consider sponsoring the development.

**Comment by oliviertassinari** [comment]
@fzaninotto Fair enough. It depends on the metrics you are looking at. On the social proofs:

- MUI X has about 1/3 of the sales of AG Grid: you can compare the sales from the two comparable packages with equivalent pricing: https://npm-stat.com/charts.html?package=%40mui%2Fx-data-grid-premium&package=ag-grid-enterprise&from=2020-03-10&to=2024-03-10. 
- MUI X has more paid customers: https://npm-stat.com/charts.html?package=%40mui%2Fx-data-grid-pro&package=ag-grid-enterprise&from=2020-03-10&to=2024-03-10.
- MUI X has more users: https://npm-stat.com/charts.html?package=%40mui%2Fx-data-grid&package=ag-grid-community&from=2020-03-10&to=2024-03-10

I think where AG Grid shines is:

- Fortune 500 penetration, 90% is not something we match, we grew x3 compared to last year at the same time, but still not at this level.

<img width="263" alt="SCR-20240311-uqar" src="https://github.com/marmelab/react-admin/assets/3165635/a4bd5944-0f82-4b8f-b2be-bd1f24e89661">

https://ag-grid.com/license-pricing/

- More advanced features. We are just going to release Pivoting this year, and it will take more time to build a chart integration (not sure we will actually).
- A larger team. They seem to have 6 people working on the data grid across frameworks, while we have 3 and only now trying to hire to 5.

---

One thing that would be super helpful for @joserodolfofreitas @cherniavskii: What dimensions did you or your team consider between the two libraries? Or asked differently, what untimely made you lean on one side?

> You're welcome to publish a third-party package doing so.

Ok, we will consider this. I hope a member of the community will 😄
