### ISSUE TITLE
But why? The store is emptied when the user logs out.

### ISSUE THREAD

**Issue by dmitrisi4** [marmelab/react-admin#9484]
https://marmelab.com/react-admin/Store.html
The store is emptied when the user logs out.

But why not give the opportunity to set a parameter so as not to do this?

**Comment by fzaninotto** [comment]
If you want the user preferences to persist over logouts, and shared across sessions, you have to pass a custom `<Admin store>` implementation. 

https://marmelab.com/react-admin/Admin.html#store
