### ISSUE TITLE
Bulk actions toolbar covers filter toolbar

### ISSUE THREAD

**Issue by Babbiorsetto** [marmelab/react-admin#9495]
**What you were expecting:**

The bulk actions toolbar doesn't cover the filters toolbar or there's the option for it not to.

![image](https://github.com/marmelab/react-admin/assets/36596647/3cea2869-f3f7-4b9d-85a2-a20bfa1c1c1c)

It may very well be that this assumption is wrong, but I believe there's a use case for changing filters after starting a selection with a different set of filters.

**What happened instead:**

The bulk actions toolbar covers the filters toolbar, making it impractical to change filters after starting a selection of multiple items.
![image](https://github.com/marmelab/react-admin/assets/36596647/b1bc88a3-a4db-4a60-8e01-d63cf90f88ab)

**Steps to reproduce:**

Reproducible on https://marmelab.com/react-admin-helpdesk/ on the tickets tab
1. Select one item
2. Bulk actions toolbar pops up and blocks filters toolbar
3. Cannot access filters anymore

**Other information:**

In case this is intended behavior and doesn't get changed, a possible workaround is moving the content card and datagrid pagination controls slightly lower so the bulk actions bar doesn't cover the filters.

**Environment**

* React-admin version: "^4.7.0" according to https://github.com/marmelab/react-admin-helpdesk/blob/main/package.json
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser: Firefox and Chrome tested
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi Alessandro, and thanks for your message. 

Your initial assumption is wrong with react-admin: we don't support changing filters after the selection has started, for the reason that adding a filter could remove all the selected records from the view. Your use case is not and will not be supported. 

If you need a different layout for the bulk actions button, try tweaking the various components (the datagrid, the bulk actoins toolbar) with the `sx` Prop. You can also build your own Datagrid layout, using the individual components that react-admin  provides (DatagridBody, DatagirdRow, etc).
