### ISSUE TITLE
Reference Input UI render bug 

### ISSUE THREAD

**Issue by DanTaylorUSW** [marmelab/react-admin#9497]
**What you were expecting:**
Using `ReferenceField` inside an `ArrayInput` I expect to see the option text output on the page to edit the information using an `AutocompleteInput`.

**What happened instead:**
I am getting a render issue where some of the array objects render the option text and some do not. It means you do not know what item you are editing as no option text is being displayed. 

**Steps to reproduce:**
```

<ArrayInput source="moduleInfos" label={false}>
            <SimpleFormIterator disableReordering>
                <FormDataConsumer>
                    {({ getSource, formData }) => {
                        let moduleIds = formData && formData.moduleInfos
                        ? formData.moduleInfos.map((module) => module.moduleId)
                        : null;
                        let filter = moduleIds ? { ids_neq: moduleIds.filter(id => id !== "") } : undefined;
                        return <>
                        <Box display="flex" width={1}>
                            <Box flex={4}>
                                <ReferenceInput reference="Module" source={getSource("moduleId")} label='myroot.module' filter={filter}> 
                                    <AutocompleteInput optionText={ModuleTitleRenderer} fullWidth />
                                </ReferenceInput>
                            </Box>                            
                        </Box>
                        </>
                    }
                    }
                </FormDataConsumer>
            </SimpleFormIterator>
        </ArrayInput>

```
What is produced byt the code above:

![image](https://github.com/marmelab/react-admin/assets/83651298/be607381-e2e3-48ad-9f37-f419fb1872be)

**Environment**

* React-admin version: 4.10.1
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome (Version 119.0.6045.200 | Official Build | 64-bit)
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Can you please provide a reproduction sandbox (either [codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or [stackblitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple))?

**Comment by fzaninotto** [comment]
No news for some time, closing.
