### ISSUE TITLE
Datagrid rowClick not scrolling to top of the page

### ISSUE THREAD

**Issue by DavidVergnaultMoank** [marmelab/react-admin#9508]
**What you were expecting:**
When using the Datagrid prop "rowClick" with either "edit" or "show", I expect to be redirected to the top of the edit or show page.

**What happened instead:**
On a list with 50+ items, when I scroll down to one of the bottom row, and then click on it, I end up in the edit/show page but at the same scrolling state as I was in the List view, instead of being at the top of the page.
The bug is not happening when using an "EditButton" or "ShowButton"

**Related code:**
In the src/list/datagrid/DatagridRow.tsx, line 117 
`navigate(createPath({ resource, id, type }));`

The following code solved the issue (I took inspiration from the EditButton code)
`navigate(createPath({ resource, id, type }), { state: { _scrollToTop: true }});`

**Environment**

* React-admin version: 4.9.1
* React version: 18.2.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Reproduced on the simple example Stackblitz. I'm marking this as a bug. 

You suggested fix is right, would you mind opening a PR to bring it to master? That way the fix has your name on it ;)

**Comment by DavidVergnaultMoank** [comment]
It doesn't seem I can push a new branch in this repo. Do I need any permission?

**Comment by fzaninotto** [comment]
You need to fork the repo and create a branch on your fork. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests
