### ISSUE TITLE
how to upgrade to react latest version (18). if we do upgrade it work fine ?

### ISSUE THREAD

**Issue by krishanat** [marmelab/react-admin#9512]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(https://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`) or the react-admin Discord Server(https://discord.gg/GeZF9sqh3N). Thanks! 😁.

**Comment by djhi** [comment]
Please follow the issue template
