### ISSUE TITLE
Allow a function for source

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#9515]
**Is your feature request related to a problem?**
I have a resource that has a relationship to another resource with composite primary keys:

```
A          | B
            id: pk
x: pk  <--- child_x: fk
y: pk  <--- child_y: fk
```

I want one of the ReferenceField components to link to A. But, source requires the name of one of B's attributes.
The ID for A is in the format of `{x}:{y}`.

**Describe the solution you'd like**
Allow a function for the source attribute on Reference[*]Field.
Then I can do `source=(b) => '${b.child_x}:${b.child_y}'`.

**Comment by slax57** [comment]
Hi, and thank you for your suggestion.

I assume that by `Resource[*]Field` you mean `Reference[*]Field`?

In any case, I'm not in favor of supporting this feature in the core, for two reasons:
- this targets very specific use-cases
- this is already doable in userland: you can grab the current record by using react-hook-form's [useWatch](https://react-hook-form.com/docs/usewatch), and use that to compute the (string) value of the `source` prop.

Hence I'm -1 for this.
@fzaninotto @djhi do you agree?

**Comment by Dreamsorcerer** [comment]
> this is already doable in userland: you can grab the current record by using react-hook-form's [useWatch](https://react-hook-form.com/docs/usewatch), and use that to compute the (string) value of the `source` prop.

Not sure exactly how that works. At a glance, it looks like I'd need to create a custom component that wraps ReferenceField to make it work. At that point, I can presumably just change source in the code anyway, so I'm not entirely clear what useWatch does. Making a custom component seems a bit awkward for this use case, but I can give it a go.

**Comment by fzaninotto** [comment]
I agree with @slax57. We've had several requests for supporting relationships with composite primary keys, and we've always replied that it's out of our scope. Either you add a primary key to your hash table, and you can use react-admin relationship hooks and components, or you do your requests by hand.

**Comment by Dreamsorcerer** [comment]
> At a glance, it looks like I'd need to create a custom component that wraps ReferenceField to make it work.

Can't seem to make this work. I tried:
```
const _ReferenceField = (props) => {
    const {source, ...innerProps} = props;
    if (source instanceof Function) {
        return (
            <WithRecord {...innerProps} render={
                (record) => <ReferenceField {...innerProps} source={source(record)} />
            } />
        );
    } else {
        return <ReferenceField {...props} />;
    }
};
```

But, ReferenceField just ends up rendering blank and ReferenceManyField just errors with 'Error: target and id are required' (and I've been able to verify that the source function is being called and returning the correct value). Also tried useWatch(), but that seems to always error. Seems like it should be a lot simpler to be able to create a dynamic source attribute than this...

**Comment by fzaninotto** [comment]
Please use other channels like Discord for support questions, this tracker is only for bugs and feature requests.
