### ISSUE TITLE
usePreferences behavior is unexpected when used outside of Configurable

### ISSUE THREAD

**Issue by KilianB** [marmelab/react-admin#9526]
**What you were expecting:**

I would have expected the hook `usePreferences` to save a value inside the RaStore.preferences path.

If `usePreferences` is not to be used outside of a Configurable (which in my opinion it should be based on the name), at least a a warning should be printed to the console if the `PreferenceKeyContext` is not provided or empty.

**What happened instead:**

The key value forwarded to the `setItem` function in the store is empty, resulting in a value being set for `RaStore.` no matter what the actual key is.

![image](https://github.com/marmelab/react-admin/assets/9025925/67f50d6d-98cc-4008-8a0e-baaa9e0e2ce0)

**Steps to reproduce:**

- Use the  following code snipped outside of a Configurable component

````tsx
   //Does not work but should be identical to the hook below
   const [showExpertView, setShowExpertView] = usePreferences(
    "expertView",
    false,
  );
  
 //Works
  const [showExpertView, setShowExpertView] = useStore(
    "preferences.expertView",
    false,
  );
````

**Comment by fzaninotto** [comment]
you're right, if `usePreferences` is used outside of the right context, we should throw an error inviting to use `useStore` instead.

Would you like to open a PR about it?
