### ISSUE TITLE
Support Dark Mode for React Admin doc website

### ISSUE THREAD

**Issue by wattry** [marmelab/react-admin#9535]
**Is your feature request related to a problem? Please describe.**
Hi there, small request. I spend a lot of time using the docs, they are really easy to follow and provide great examples. They are just absolutely blinding. If it's possible and light weight could you please consider adding a dark mode?

**Comment by slax57** [comment]
Hi,
Thanks for the feedback and the kind words.
It's something we have in our roadmap already!
Although I can't give you any ETA for now...
Labeling as enhancement request.
