### ISSUE TITLE
Send refresh metadata to ReactQuery/DataProvider when clicking refresh icon on top right

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#9550]
Is there any way to set a flag on the dataProvider methods that says that the user manually clicked the refresh button?

This would be useful for sending a cache flag when calling the API to send back uncached data.

Am I overthinking this? This just popped in my head.

**Comment by fzaninotto** [comment]
You should customize the `<LoadingIndicator onClick>` instead, see https://github.com/marmelab/react-admin/pull/9420
