### ISSUE TITLE
Reseting filter values for child properties does not work

### ISSUE THREAD

**Issue by zbposs** [marmelab/react-admin#9551]
**What you were expecting:**
When reseting filter field on source object nested property value in filter input field is empty

**What happened instead:**
Filter input field still has value (this value is just in input field it is not aplied on list results).
If filter contained value "blue" and value is changed (it now contains "yellow"), calling setFilters({}, {}) will reset to "blue" rather then "".

**Steps to reproduce:**
1) There is filter on source child property that is "alwaysOn" and some value is entered.
2) Through menu go to some other page and return back to original page.
3) Click reset filter (remove all fitlers) button that calls setFilter().
4) Filter field should reset and have no value

**Related code:**
```
import { List, Button, useListContext, TopToolbar, TextInput, TextField, Datagrid } from "react-admin";

const { setFilters } = useListContext();

<List
  filters={[
    <TextInput source="name" alwaysOn />,
    <TextInput source="banana.color" alwaysOn />,
  ]}
  actions={
    <TopToolbar>
      <Button onClick={() => setFilters({}, {})} {...props}>
      </Button>
    </TopToolbar>
  }
>
  <Datagrid>
    <TextField<FruitBasket> source="name" />
    <TextField<FruitBasket> source="banana.color" />
  </Datagrid>
</List>
```
**Other information:**
In code above useListContext should be called from list context...
Everything works fine if removing filter for direct source property (first filter in code example), issues is when filtering on object properties from source object (second filter in code example). 

**Environment**

* React-admin version: 4.15.4
* React version: 18.2.0

**Comment by fzaninotto** [comment]
Thanks for your report. Could you please provide a reproduction based on the simple example Stackblitz? 

https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=README.md

**Comment by zbposs** [comment]
Here, I tried to reproduce it but it works! Changes are in CommentList.tsx and package.json (downgraded react-admin to "4.15.4")
https://stackblitz.com/edit/github-owx3cs?file=src%2Fcomments%2FCommentList.tsx

Steps:
1) write something in new "Author name" filter.
2) Got to some other page like "Posts"
3) Come back to "Comments" page
4) Click remove button
5) It works, value is removed from filter (it does not work on my side, I need to recheck why).

**Comment by zbposs** [comment]
After upgrading react-admin from  "4.15.4" to "4.16.4" and ra-ui-materialui (probably not relevant) everything works on my side also.
