### ISSUE TITLE
parse/format wrong TS typing

### ISSUE THREAD

**Issue by saalihou** [marmelab/react-admin#9560]
**What you were expecting:**
parse/format should be typed properly.
`parse` should take the `ValueType` as an argument and return `any` (or preferrably something strongly typed), since we are taking the type emitted by the input (`ValueType`) and turning it into a field in the record (which we don't know the type of)
`format` on the other hand takes an unknown value from the record and turns it into a known type (`ValueType`) for the input

**What happened instead:**
`parse` is typed as `any => ValueType`, and `format` is typed as `ValueType => any`

**Steps to reproduce:**
1. Create a custom strongly typed input with `InputProps<YourType>`
2. Use it in a form where the `source` fields has a different type than the input
3. Try to use `parse` and `format` to convert the `source` field into `YourType`
4. Typescript complains and does not properly auto complete

**Related code:**
I can illustrate if necessary but since this is a typing issue and not an actual bug, I think it is unnecessary

**Environment**

* React-admin version: 4.15.3
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Any
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I don't agree, or I don't understand your point. 

`parse` turns the value from the input to the record. The `ValueType` is the type of the record value. So the type for `parse` should be `any => `ValueType`, which is what we have in the code. 

So for me there is a misunderstanding on your side.

**Comment by saalihou** [comment]
Then there is a misunderstanding on my side. I thought ValueType is the type emitted by the input.

In that case, when declaring an input, I am saying that it can only be used with a given type from the record (i.e. ValueType) which seems limiting. If that's the case, why would I need parsing and formatting since the input already knows the type of the value it takes and the type of the value it emits (since it controls it) ?

My use case is I have a CoordsInput whose value type is {lat,lng} but I need to use it with a [lng,lat] type field. What's the recommended approach ? (I don't want to make a different input for every possible representation of coordinates in my apps)

**Comment by fzaninotto** [comment]
As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
