### ISSUE TITLE
Using validate on ReferenceInput

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#9568]
**What you were expecting:**
Setting `validate=required()` on ReferenceInput to make the label appear as required.

**What happened instead:**
I needed to set validate on AutocompleteInput instead.

Maybe it would be good to mention validate in the ReferenceInput documentation to avoid this confusion? Unless there's a code fix to ensure that validate gets passed through?

Code I used looks something like:
```
<ReferenceInput {...props}>
    <AutocompleteInput label={props["label"]} />
</ReferenceInput>
```

**Comment by fzaninotto** [comment]
You're right, we should catch the `validate` prop in `<ReferenceInput>` and throw an error explaining that it should be set on the child instead. Would you mind opening a PR for that?

**Comment by d640k** [comment]
This isn't caught by TypeScript as `ReferenceInputProps` extends `InputProps` which includes `validate`. Not sure what the implications are, but should that prop be omitted?
