### ISSUE TITLE
Possibility to pass additional data in the server response for getList

### ISSUE THREAD

**Issue by AntoineCrb** [marmelab/react-admin#9569]
An API might want to send additional data since all the data isn't send when using pagination

The `useListContext()` hook, as documented [here](https://marmelab.com/react-admin/useListContext.html), provides only `data` and `total`, not additional values sent back by `getList()`

The solutions that could be implemented to allow this mechanism are not practical at all (feel free to explain it here if you were to find one)

I also found this [stackoverflow question](https://stackoverflow.com/questions/75715770/add-extra-data-to-getlist-in-dataprovider) that raises the same issue

--------------------------------------------------------------------------------------

Here is an example using chips to show a summary of all the data (not working since the feature doesn't exist) :
![Screenshot 2024-01-07 223943](https://github.com/marmelab/react-admin/assets/32823523/d5155f0e-bf20-409d-ab54-03cc20b35450)

**Comment by fzaninotto** [comment]
Implemented in #10179
