### ISSUE TITLE
ra-ui-material Warning: Missing translation for key: "ra.configurable.customize"

### ISSUE THREAD

**Issue by roman89ua** [marmelab/react-admin#9571]
Hello. I am facing the issue with ra-ui-material which is a part of react-admin.
Our project was using react admin version 4.2.4. After update to 4.16.4 as this version propose beter form state traking we received this issue as described on screenshots.
I can fix this by adding key "ra.configurable.customize" to our project distionaries. But not sure if it's good idea to do that in this way.
 
Is that possible that someone can target me to that compnent that require some prop to be passed to avoid this warning or maybe I need to open issue to this repositiry and hopefully it will be fixed by react-admin developers? Probably if they have added this key  as default value to openButtonLabel then it should be the part of ra-ui-material library.

![2024-01-08 17_42_52-](https://github.com/marmelab/react-admin/assets/54412595/679b1ff0-fa6f-4eea-a2df-9ddafcc510ab)
![2024-01-08 17_44_32-web-admin – C__projects_adopt-pets-of-ukraine_web-admin_node_modules_ra-ui-mater](https://github.com/marmelab/react-admin/assets/54412595/b4f0a6e1-3cf3-408a-a34a-75ac83d893c4)

**Comment by fzaninotto** [comment]
You have the right fix: as the translation is missing, you have to add it to your dictionaries. It's properly handled by the two translations we provide (fr and en). If you a third-party translation, maybe they need to add the translation for that key.
