### ISSUE TITLE
Selecting a choice from AutocompleteArrayInput within ReferenceArrayInput replaces existing choices

### ISSUE THREAD

**Issue by Nepherte** [marmelab/react-admin#9579]
**What you were expecting:**
When using an AutocompleteArrayInput within ReferenceArrayInput, selecting one of the autocomplete options adds the item to the already selected ones.

**What happened instead:**
When using an AutocompleteArrayInput within ReferenceArrayInput, selecting one of the autocomplete options replaces the already selected ones.

**Test dataset:**
datasources
```js
[
  {
    id: 0,
    title: "title0"
  },
  {
    id: 1,
    title: "title1"
  }
]
```
publications
```js
[
  {
    id: 0,
    datasourceIds: []
  },
  {
    id: 1,
    datasourceIds: []
  }
]
```

**Related code:**
```jsx
<ReferenceArrayInput source={"datasourceIds"} reference="datasources">
  <AutocompleteArrayInput optionText={"title"} filterToQuery={searchText => {title: searchText}} clearOnBlur={false}/>
</RefererenceArrayInput>
```

**Steps to reproduce:**

1. Click inside the input element and select `title0`.
2. Click inside the input element and type `title`. 
3. Select datasource `title1`.
=> title1 replaces title0 instead of having both title0 and title1.

**Environment:**

* React-admin version: 4.16.5
* React version: 18.2.0
* Browser: Firefox 121.0.1

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).
