### ISSUE TITLE
docs tutorial - cosmetic issue - URLField link does not point to the right URL

### ISSUE THREAD

**Issue by siraj-samsudeen** [marmelab/react-admin#9592]
This is my day 2 with react-admin - really appreciate the clear yet comprehensive and friendly tutorial and how readable the code is, compared to barebones React and Refine. In the spirit of the improving something already excellent, here is a cosmetic issue to fix:

We have a bunch of URLs displayed in the Users list - the first one points to `http://localhost:5173/demarco.info` - I believe this is happening because it is interpreted as a relative URL. I tried to add the prefix `http://` in the custom MyUrlField component and it fixed the problem. If you accept this as an issue, I can send a PR with that modification.

**Comment by fzaninotto** [comment]
Hi,

> really appreciate the clear yet comprehensive and friendly tutorial and how readable the code is,

Thanks! We really appreciate the feedback.

You're right, the custom MyUrlField needs a `http` in front of the `src`. We'll gladly accept a fix on the Getting Started tutorial and in the examples/tutorial/src/MyUrlField file.

**Comment by siraj-samsudeen** [comment]
Sorry Francois. I could not send the PR in time, and thanks for taking it up and closing it promptly. Really appreciate the diligence.
