### ISSUE TITLE
FileInput - failed prop type of `removeIcon`

### ISSUE THREAD

**Issue by PawelSuwinski** [marmelab/react-admin#9595]
Using custom removeIcon in FileInput triggers such warning on the console: 

> Warning: Failed prop type: Invalid prop `removeIcon` of type `object` supplied to `FileInputPreview`, expected a single ReactElement.

ex. 

```
import CloseIcon from "@mui/icons-material/Close";
(...)
     <FileInput removeIcon={CloseIcon} />

```

**Steps to reproduce:**

https://stackblitz.com/edit/github-qjhrzz?file=src%2Fposts%2FPostCreate.tsx

1. Use project preview and open Console at Developers Tools
2. Add a file (PDF-Template)

It looks like a wrong prop type: 
https://github.com/marmelab/react-admin/blob/c606084311e74ad52f1cd90a2893e8d927fa2e1e/packages/ra-ui-materialui/src/input/FileInputPreview.tsx#L53

Shouldn't be?

```
FileInputPreview.propTypes = {
   (...)
    removeIcon: PropTypes.elementType,
}
```

**Comment by djhi** [comment]
Indeed, thanks for the report!
