### ISSUE TITLE
`ra-i18n-i18next` does not produce a `dist` folder when installing

### ISSUE THREAD

**Issue by PedroPerpetua** [marmelab/react-admin#9601]
**What you were expecting:**

Installing `ra-i18n-i18next` would install the package and have it ready to be used.

**What happened instead:**

`ra-i18n-i18next` is installed; however, the package does not build automatically, leaving only the source files, and nothing that can actually be imported.

**Steps to reproduce:**

1. Initialize a new project (`npm init` or `yarn init`)
2. Install `ra-i18n-i18next`
3. Check the folder produced in `node_modules`

**Related code:**

See the following sandbox - package was installed, but imports fail. As you can see by the `TestComponent`, it's not just a typescript issue; the project cannot run the packaged correctly.

https://stackblitz.com/edit/github-ijmaub?file=src%2Findex.tsx

**Comment by fzaninotto** [comment]
Confirmed, thanks for the report. 

The problem comes from a missing `build-ra-i18n-i18next` command there:

https://github.com/marmelab/react-admin/blob/71aaf601466e974d8e79c5dd4369811a4fdd8e58/Makefile#L123
