### ISSUE TITLE
Add rowDblClick prop to Datagrid

### ISSUE THREAD

**Issue by Youpiiiii** [marmelab/react-admin#9609]
Hello,

I would find it interesting to add rowDblClick to Datagrid.

Example:
`<Datagrid rowClick="show" rowDblClick="edit">`

What do you think?

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

You can already implement this feature by overriding the [`<Datagrid body>`](https://marmelab.com/react-admin/Datagrid.html#body) and the `<DatagridBody row>` props. We won't add another prop to the main `<Datagrid>` as we believe it's not a common enough need. 

Feel free to publish an alternative datagrid with this feature as a third-party package!
