### ISSUE TITLE
TextInput or BooleanInput default value not dynamic.

### ISSUE THREAD

**Issue by david-hov** [marmelab/react-admin#9618]
**What you were expecting:**
if component inside **SimpleForm** updated change children defaultValues

**What happened instead:**
Keeps the first defaultValue

**Related code:**
```
<SimpleForm>
      <FormDataConsumer>
          {({ formData }) => formData.value === 'AAA' ?
           <AAA /> : <BBB />
          }
      </FormDataConsumer>
</SimpleForm>

/// AAA
<BooleanInput defaultValue={true} source='sameSource' label='AAA' />

/// BBB
<BooleanInput defaultValue={false} source='sameSource' label='BBB' />
```

https://codesandbox.io/p/devbox/fast-sun-33rf9w?file=%2Fsrc%2Ftags%2FTagCreate.tsx%3A25%2C20

**Environment**

* React-admin version: 4.0.0
* React version: 18

**Comment by fzaninotto** [comment]
The default value is set on mount. That's a limitation of react-hook-form. If you need this feature, I suggest you open an issue on their repository. Otherwise, use a `useWatch` to update the current value (not the default) based on other values.
