### ISSUE TITLE
[RFC] package ra-data-json-server adaption of consistent getMany

### ISSUE THREAD

**Issue by rmargelidon** [marmelab/react-admin#9662]
**Is your feature request related to a problem? Please describe.**
I'm a bit frustrated when using jsonServerProvider, getMany are turned into http://website.local/api/resources?id=1&id=2 , common framework as Symfony are only receiving one param associated with one key. Here only the last given id in the request will be handled. 

**Describe the solution you'd like**
I want to transform request to have http://website.local/api/resources?id[]=1&id[]=2 which is better handled. 

Is-it relevant ?

**Comment by fzaninotto** [comment]
Hi, and thanks fro your suggestion. 

ra-data-json-server is designed to communicate with a [JSONServer](https://github.com/typicode/json-server) API. Being compatible with other APIs isn't a target. 

For your API, I suggest you fork the data provider and update it for your API, following this documentation:

https://marmelab.com/react-admin/DataProviderWriting.html
