### ISSUE TITLE
Security Risk, Default install allows request access to all files.

### ISSUE THREAD

**Issue by guy-radford-sunswap** [marmelab/react-admin#9665]
**What you were expecting:**
I was not expecting to be able to request README.md via HTTP with the default installation. I am away that I am running as `dev`, but I am still supprised and have not had this with other React projects.

**What happened instead:**
<img width="340" alt="image" src="https://github.com/marmelab/react-admin/assets/111859989/46c49c26-18d5-4ef0-a33d-de5775900400">

**Steps to reproduce:**
1. `npm init react-admin test-admin1`
2. `cd test-admin`
3. `npm run dev`
4.  visit: http://localhost:5173/README.md
5. Visit: http://localhost:5173/src/App.tsx

<img width="948" alt="image" src="https://github.com/marmelab/react-admin/assets/111859989/03623757-06e3-4878-891c-830d3e81623c">

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: "4.16.10"
* Last version that did not exhibit the issue (if applicable):
* React version: "18.2.0"
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by adguernier** [comment]
`create-react-admin` generates a react-admin app scaffolding using [Vite](https://vitejs.dev/).
Creating a basic React project with Vite will lead to the same result in dev mode.
This behavior does not apply in production mode however.
So this issue is not react-admin related but rather to Vite or server configuration. 
Thanks anyway but I'm closing this issue.
