### ISSUE TITLE
`CoreAdminUI` wraps everything in a `<div>`

### ISSUE THREAD

**Issue by MurkyMeow** [marmelab/react-admin#9680]
When using `<CoreAdminUI/>` everything gets wrapped in a `<div>` that can't be given any attributes or styles to: https://github.com/marmelab/react-admin/blob/a9c302325302a579b0d8ac49bf8cf6f3699f3027/packages/ra-core/src/core/CoreAdminRoutes.tsx#L80

and in my case that makes it difficult to implement scroll via `overflow: auto` inside a form because every parent has to be given a `height: 100%` style

It would be great to remove that `<div>` altogether or make it possible to pass a `className` to it

**Comment by adguernier** [comment]
Thanks for this reports.

Indeed this `div` is useless. 

However some people could have styled his element in another way. We will therefore not fix this problem until the next major release to avoid breaking changes.

Feel free to open a PR targeting the `next` branch if you want to contribute :+1:

**Comment by fzaninotto** [comment]
It is already fixed in `next` - there is no such div.
