### ISSUE TITLE
CheckboxGroupInput : disabling some of the checkboxes Feature

### ISSUE THREAD

**Issue by utku656** [marmelab/react-admin#9685]
In our project , we are using react-admin . CheckboxGroupInput is also another component that we used mostly but we have problem about disabled prop. Disabled prop type is boolean so it is disabling whole checkboxes. I want to disable only some of them. 

You can make disabled prop boolean array  or we can set disabled inside choices object for each checkbox.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by utku656** [comment]
It was not support question. I was asking that disabled prop type is boolean so if i pass true to this prop . It is disabling whole checkbox group but i want to disable just some of them . Is not it new feature ? CheckboxGroupInput does not support this feature . This is why i opened this as feature .

**Comment by fzaninotto** [comment]
Right, sorry for closing it as a "how to" question. 

This feature isn't supported by react-admin and we don't intend to work on it in the near future. I invite you to write your own implementation, and if you agree to contribute it to the core, open a PR here!
