### ISSUE TITLE
Multiple expandable datagrids: expanding a row triggers all datagrids to expand

### ISSUE THREAD

**Issue by roxeteer** [marmelab/react-admin#9688]
**What you were expecting:**
When I click to expand a row in a datagrid, only that row should expand.

**What happened instead:**
If I have multiple expandable datagrids on the same page, the same row in all of them expand (i.e. if I click the first row, the first row of all datagrids expand).

**Steps to reproduce:**
1. Create a view with multiple expandable datagrids.
2. Expand a row.
3. See that more than one row expands.
4. Collapse a row.
5. See that all the previous rows collapse, too.

**Related code:**
```jsx
<SimpleShowLayout>
  <ArrayField<Product> source="descriptionSource">
    <Datagrid bulkActionButtons={false} expand={<DescriptionPanel />} expandSingle>
      <TextField<ProductAttribute> source="language" />
      <TextField<ProductAttribute> source="value" />
    </Datagrid>
  </ArrayField>

  <ArrayField<Product> source="descriptionHtmlSource">
    <Datagrid bulkActionButtons={false} expand={<DescriptionPanel />} expandSingle>
      <TextField<ProductAttribute> source="language" />
      <TextField<ProductAttribute> source="value" />
    </Datagrid>
  </ArrayField>
</SimpleShowLayout>
```

The issue arises because all the datagrids use the parent resource name as the `localStorage` key. In this case expanding the first row of either of the datagrids stores `["row0"]` with the key `RaStore.Product.datagrid.expanded`.

**Other information:**
Since expand uses `<Datagrid>`'s `resource` prop value in creating the `localStorage` key, setting the prop to a unique string makes the `localStorage` key unique as well. However, I'm not entirely sure what else `resource` prop is used for here and if it creates side-effects. Like this:

```jsx
<Datagrid bulkActionButtons={false} expand={<DescriptionPanel />} expandSingle resource="descriptionSource">

// ...

<Datagrid bulkActionButtons={false} expand={<DescriptionPanel />} expandSingle resource="descriptionHtmlSource">
```

**Environment**

* React-admin version: 4.16.11
* React version: 18.2.0

**Comment by slax57** [comment]
Thank you for opening this issue.

Indeed, currently the expand controller uses a Store key built only with the resource: `` `${resource}.datagrid.expanded` ``.

There is currently no way to override that store key (except passing a different resource).

We could introduce the ability to customize this store key (using e.g. the [storeKey](https://marmelab.com/react-admin/List.html#storekey) prop from the ListContext), but this would be a new feature.

Would you like to open a PR (against the `next` branch) to implement it?

**Comment by roxeteer** [comment]
> Would you like to open a PR (against the `next` branch) to implement it?

I will take a look.

**Comment by davidhenley** [comment]
@roxeteer I'm digging through the ListContext source code right now, and am trying the same. It should be as simple as adding a prob and passing it down unless I'm missing something.

**Comment by roxeteer** [comment]
@davidhenley I think the more React Admin-like approach would be to create yet another context for it. `ListContext` is quite huge already and it's probably not needed to be exposed. `preferenceKey` is passed around in similar manner, using its own context provider.

**Comment by davidhenley** [comment]
I don't understand this logic, it would be the exact same as it is now, just pass it to ListContext under ArrayField. What am I missing?

**Comment by roxeteer** [comment]
Maybe I was thinking it too complicated. It's been a while already so can't remember how it was exactly.

**Comment by davidhenley** [comment]
Yeah since ArrayField only creates a ListContext around the children, you should just be able to pass the store key down to the ListContext to do the exact same thing you would with storeKey on List. This is super simple imo.

**Comment by fzaninotto** [comment]
This proposal didn't receive enough contributions from the community so we'll close the issue. 

We'll accept any PR that implements this change.
