### ISSUE TITLE
AutocompleteInput in ReferenceArrayInput with dynamic choices shows empty field on selection

### ISSUE THREAD

**Issue by bendenoz** [marmelab/react-admin#9691]
**What you were expecting:**

The UI of the AutocompleteInput within the ReferenceArrayInput should update to reflect the chosen item, regardless of whether it existed in the initial choices list or was entered by the user.

**What happened instead:**

When selecting an entry that is not in the default choices list, the component returns the correct value, but the UI shows an empty input field. This only occurs when the choices list comes from a dynamic list that requires a search parameter. There are no issues with AutocompleteArrayInput.

**Steps to reproduce:**

Create a ReferenceArrayInput using AutocompleteInput.
Configure the choices list to be dynamic and require a search parameter.
Select an existing entry from the options list (this works correctly).
Enter a value not present in the initial choices and select it.
Observe that the UI shows an empty field despite the correct value being stored.
Related code:

**Other information:**

React-admin version: 4.16.0
React version: 18.2.0
Browser: 121.0.6167.189

**Possible Cause:**

The issue has been traced to a potential incompatibility between AutocompleteInput's handling of selected values and the useReferenceArrayInput hook. Specifically, AutocompleteInput returns a string value (unlike AutoCompleteArrayInput), while useReferenceArrayInput expects an array.

**Proposed Solution:**

Our current workaround is the following diff. It addresses the issue by ensuring that both string and array values are correctly handled:

```diff
diff --git a/packages/ra-core/src/controller/input/useReferenceArrayInputController.ts b/packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
index c33cfa9ef..68c1bb3a6 100644
--- a/packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
+++ b/packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
@@ -63,7 +63,7 @@ export const useReferenceArrayInputController = <
   } = useGetManyAggregate<RecordType>(
     reference,
     {
-      ids: value || EmptyArray,
+      ids: value && Array.isArray(value) ? value : [value] || EmptyArray,
       meta,
     },
     {
```

**Comment by slax57** [comment]
Thank you for this report and for the investigation work.

Can you please provide a reproduction sandbox (forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple or https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple ) so that we can investigate the issue ?

Also, can you please confirm you are using an `AutocompleteArrayInput` as child of `ReferenceArrayInput` and not a simple `AutocompleteInput`?

I'm wondering because of this sentence in your report:

> Specifically, AutocompleteInput returns a string value (unlike AutoCompleteArrayInput), while useReferenceArrayInput expects an array.

**Comment by bendenoz** [comment]
Thanks @slax57. No I am using `AutocompleteInput` for a single entry, not the Array variant. It's used in a filters component. It works fine except when the choices are not present in the list. 
I will try to make a simple repro sandobx

**Comment by bendenoz** [comment]
Here is the sandbox 

https://codesandbox.io/p/devbox/funny-firefly-p64lgt?file=%2Fsrc%2FdataProvider.tsx%3A42%2C43

I cannot repro 100% (could be a cache problem) but it is still possible to demonstrate the issue. In our cases, the input is empty even before reloading.

1/ Working example: Add Tags filter. Click the input wait for the list to populate, select "Sport" . Only Sport posts are shown. Reload the page (the whole sandbox), the Sport filter is still working

2/ Broken example: Add Tags filter, Click the input, type "mu", wait for the list to populate, select "Music". Only Music posts are shown. Reload the page (the whole sandbox). The Music filter is still working but the Tags input is empty

Actual:

![image](https://github.com/marmelab/react-admin/assets/3428395/10954034-fd88-4b48-9966-3e2bf9de3ffd)

Expected:

![image](https://github.com/marmelab/react-admin/assets/3428395/80f749b1-a35d-4566-a20c-0d5fed7751d0)

**Comment by slax57** [comment]
Thanks for the sandbox.

If you are using `ReferenceArrayInput` the child should be an `AutocompleteArrayInput`. If you are expecting a single entry, you should be using a `ReferenceInput` with an `AutocompleteInput` child.

Am I missing something?

**Comment by bendenoz** [comment]
That's interesting... I guess I was confused by the fact it was almost working out of the box with `ReferenceArrayInput ` too. They almost provide the same context...
Anyway it works fine with `ReferenceInput`, thanks !
