### ISSUE TITLE
Property "resource" in SortButtonProps not involved

### ISSUE THREAD

**Issue by kdzone** [marmelab/react-admin#9692]
**What you were expecting:**
Property "resource" in SortButton will begin to be used for localization by 18n.

**What happened instead:**
Property "resource" not involved. Used resource name returned from useListSortContext(). 
I'm expecting the resource property passed in to be used to get the sort field label.

```
<SortButton resource="resourceName" />
```

* React-admin version: 4.16.11

**Comment by kdzone** [comment]
It’s also strange that the column labels in the DataGrid use the resource name from getResourceContext(), and labels in the SortButton getListContext()

**Comment by slax57** [comment]
Thanks for the bug report. We'll open a PR to fix this issue.

> It’s also strange that the column labels in the DataGrid use the resource name from getResourceContext(), and labels in the SortButton getListContext()

It should be the same in most cases, because the ListContext is built using the resource from the parent ResourceContext.
