### ISSUE TITLE
Change title property type in core display components <Edit>, <Show>, <View> 

### ISSUE THREAD

**Issue by antoinefricker** [marmelab/react-admin#9695]
#### Is your feature request related to a problem?
In the `<Edit>`, `<Create>` and `<Show>` components, the title property is typed as `title?: string | ReactElement;`
In our project, we would like to customize title content using the `<Title>` component within the aforementioned components children. It is now uncomfortable to implement as RA stacks default title and the userland defined title.  

#### Describe the solution you'd like
I would find it very _react-admin styled_ to allow a `false` value for the `title` property of the core display components.
It would require to update those, adding a render condition to the `<Title>` component - [here for example](https://github.com/marmelab/react-admin/blob/466f49756ff368bb987b115d3e30d7762ee8d85b/packages/ra-ui-materialui/src/detail/EditView.tsx#L47)

> By the way, using an empty string does not do the job as there is a [falsy evaluation](https://github.com/marmelab/react-admin/blob/466f49756ff368bb987b115d3e30d7762ee8d85b/packages/ra-ui-materialui/src/layout/PageTitle.tsx#L18C14-L18C20) of the string in `<PageTitle>`.

#### Describe alternatives you've considered
None

#### Additional context
No relevant

**Comment by fzaninotto** [comment]
Thanks for your suggestion. 

Supporting a falsy value for `<Edit title>` props does add a bit of flexibility, and we'd welcome a PR for that. 
`<Edit>` doesn't do much more than rendering the title, actions, and a `Card` around the page content. If you don't use the Title feature of `<Edit>`, I suggest you use `<EditBase>` instead.
