### ISSUE TITLE
Standalone version of the Store for a dual-store strategy

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#9701]
I use useStore for several global settings. I have a collision of interests for storing them in localStorageStore vs the memoryStore.

1. Some settings need to be persistent, because they are user settings that they want to have when revisiting the app. So, these I want to store in localStorage.

2. Other settings must not be persistent, because the app may be opened in multiple tabs as some users do (we have about 10k users). When they open a sidebar (covers 100% of the screen) in one tab, the sidebar is also opened in all other tabs. This is unwanted because in the other tabs they may be at an entirely different area of the app. So, these settings I want to store in memoryStore, so that the sidebar is only opened in that one tab.
 
But since I can use only a single store with react-admin, I was thinking of using the memoryStore for most settings (that must not be persistent) and pass that store to the Admin's store prop. And it would be nice if I could use another standalone store, based on localStorage, for the settings that need to be persistent.

Would you consider making the store available for standalone usage?

This dual-store strategy would allow me to tailor the storage mechanism to the nature of the data being stored.

The alternative for me would be to start using React Context for the settings that must not be persistent.

**Comment by djhi** [comment]
That's already the case. You can create a new store and export it from a file then import this file anywhere needed and use it directly:

```ts
export const myStore = localStore();

// somewhere else
import { myStore } from './myStore';
```

The store interface is here: https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/store/types.ts

**Comment by christiaanwesterbeek** [comment]
Thanks. But I suppose I cannot use useStore with this store right?

**Comment by djhi** [comment]
You could wrap the parts of the UI that need it in another `StoreContextProvider` and pass it the store: https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/store/StoreContextProvider.tsx
