### ISSUE TITLE
Documented theme level defaultProps overrides do not work for react admin components

### ISSUE THREAD

**Issue by wattry** [marmelab/react-admin#9706]
**What you were expecting:**
We use medium size buttons for our custom filter components and the FilterButton component which uses an RA Button which defaults the size to small. This means we cannot use the MUI defaultProps to override it at a theme level and it does not take a size prop. The RA upgrading to v4 docs state that you can override the defaultProps on RA components, however, this does not seem to be work as I tried the example provided RaTextInput and this [issue](https://github.com/marmelab/react-admin/issues/7834) states that it won't be implemented.

You can find the reference to where it is [documented here](https://marmelab.com/react-admin/Upgrade.html#formcontext-formcontextprovider-and-useformcontext-have-been-removed), I'm not sure if the position has changed or the RA Button does not allow for it. Since upgrading to RA4 we've tried to avoid creating too many wrapped copies unless necessary, since it made the upgrade considerably more work.

![Screen Shot 2024-03-08 at 3 44 20 PM](https://github.com/marmelab/react-admin/assets/22616082/87bee5e5-7d2e-44f4-bc85-589d907ea5ff)

** Related Code **

[Button.ts:39](https://github.com/marmelab/react-admin/blob/aa2863f3d113745e0f3a6177541e633f270ea296/packages/ra-ui-materialui/src/button/Button.tsx#L39)

**Environment**

* React-admin version: 4.16.1
* React version: 17.0.2

**Comment by fzaninotto** [comment]
The migration documentation you're referring to (https://marmelab.com/react-admin/Upgrade.html#simpleform-and-tabbedform-no-longer-accept-margin-and-variant) explains that you can apply custom props on the `MuiTextField`. This works. Can you confirm it? 

We probably need to remove the mention of overriding `RaTextInput` default props as it's not working. Marking this as a documentation issue.
