### ISSUE TITLE
AutocompleteInput don't keep focus with mouse

### ISSUE THREAD

**Issue by Nitix** [marmelab/react-admin#9715]
**What you were expecting:**
Focus stays in the autocomplete input when selecting an option with mouse

**What happened instead:**
Component loses the focus and the focus goes to the first element of the page breaking tab navigation

**Steps to reproduce:**

Go to a form, click on an input with options like SelectInput or AutocompleteInput, select an option, then press tab to try to go to next input. But it fails to do so. 

**Related code:**
No code modification form code sandox https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=README.md

**Other information:**

[Screencast from 2024-03-12 17-09-50.webm](https://github.com/marmelab/react-admin/assets/5849835/6eb6f763-5a08-4caf-a833-cf37d7fc5da2)

**Environment**

* React-admin version: 4.16.12
* Last version that did not exhibit the issue (if applicable):
* React version: 18
* Browser: Firefox 123
* Stack trace (in case of a JS error):

**Comment by erwanMarmelab** [comment]
reproduced, thanks :+1:

**Comment by fzaninotto** [comment]
I can reproduce on AutocompleteInput but not on SelectInput

**Comment by Nitix** [comment]
My bad, only AutocompleteInput has the bug.

**Comment by fzaninotto** [comment]
This is the culprit:

https://github.com/marmelab/react-admin/blob/717d292192f5d44dc5f10a05f2699f354ad06bae/packages/ra-ui-materialui/src/input/AutocompleteInput.tsx#L558

Now why did we add this?
