### ISSUE TITLE
Add ability to customize query string format for lists

### ISSUE THREAD

**Issue by milutinovici** [marmelab/react-admin#9727]
**Is your feature request related to a problem? Please describe.**
Currently, query string format is hard coded in useListParams.ts

**Describe the solution you'd like**
Ability to pass toQuery/parseQuery functions to List component, which would pass it further down.

**Describe alternatives you've considered**
Not really sure about this.

**Additional context**
Not needed, I think?

**Comment by fzaninotto** [comment]
Why would you need a custom query string?

**Comment by milutinovici** [comment]
I don't want JSON in my URLs

**Comment by adguernier** [comment]
> I don't want JSON in my URLs

Which JSON are you talking about? :thinking:

**Comment by milutinovici** [comment]
Oh, I have already patched the library for my needs using patch-package. But since URL is a user facing thing, I feel this should be part of the library
