### ISSUE TITLE
AutoComplete choice listing issue when using useChoicesContext

### ISSUE THREAD

**Issue by UdhayRevyrie** [marmelab/react-admin#9734]
**What you were expecting:**
Inside the reference input I am using useChoiceContext() hook, I would like to add one custom choice with {id:123, name: 'SelectAll'} the allChoices to the choices prop of AutoCompleteInput 

**What happened instead:**
error thrown as Cannot read properties of undefined (reading 'substring')

**Steps to reproduce:**
1) select {allChoices} from the useChoiceContext(), 
2) try to spread and add one more choice item to that,
3) give it to the choices prop of AutoCompleteInput

**Related code:**
<ReferenceInput
         source={'environment_id'}
         reference="assets-list"
         filter={{
              is_active: true,
              type: 3,
              updated_at: 'DESC',
         }}
         perPage={10}
>
         <AutoCompleteCustom />
</ReferenceInput>

const AutoCompleteCustom = () => {
  const {allChoices} = useChoicesContext()
  const choices = [...allChoices, {id: '1234',name: 'Select All', title: 'Select All'}]
  return (
    <AutocompleteInput
      validate={required()}
      fullWidth
      optionText={'name'}
      choices={choices}
      label={'360 Shell'}
    />
  )
}

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.4.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
This is not the advised way to add a new choice, see https://marmelab.com/react-admin/AutocompleteInput.html#creating-new-choices
