### ISSUE TITLE
useEditContext returns null for both values

### ISSUE THREAD

**Issue by ttante** [marmelab/react-admin#9744]
**What you were expecting:**
Expecting [the documented behavior](https://marmelab.com/react-admin/useEditContext.html) but instead the values of 'record' and 'isLoading' both return null

**What happened instead:**
No data - even though the data is being successfully fetched & returned as in the correct Promise format

**Steps to reproduce:**
Call useEditContext() in an edit page, observe no data is returned

**Environment**

* React-admin version: 4.16.0
* Last version that did not exhibit the issue (if applicable):
* React version: ^18
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I can't reproduce the issue you describe. Please provide a reproduction based on the simple example. I suggest you also look at the `error` contained in the ListContext. 

Note that there is a TypeScript issue about the controller Context, that we have already identified, and fixing (cf #9743).

**Comment by ttante** [comment]
@fzaninotto I believe I may have been using it incorrectly. I didn't notice the example with the "aside" component. I think I was looking for useEditController. In all honestly it can be quite confusing to figure out the correct methods to use when customizing pages with react-admin.

I see now that it's at the very bottom of the very long [Edit component docs page](https://marmelab.com/react-admin/Edit.html) - honestly I feel this should maybe be the 2nd or 3rd example on the page, certainly not the very last. Customizing views has proven to be a much larger learning curve to react-admin than should be necessary, perhaps I'll make an issue to have the docs display custom solutions more prominently.

**Comment by fzaninotto** [comment]
If you have suggestions to improve the docs, they're open-source, so you're one PR away from becoming a contributor ;)

**Comment by ttante** [comment]
Unfortunately I need to prioritize my efforts based on their returns, however, from recent heavy use I know of a lot of places where the docs could be improved. If you like I could provide a discounted contract rate to update your docs in a manner that would save react-admin users time & difficulty based on my experience using it every day the last 4 months.

**Comment by fzaninotto** [comment]
No thanks, this is an open-source project: we don't pay contributors because we don't get a revenue from their work.
