### ISSUE TITLE
Codemods are not included in ra-core v5

### ISSUE THREAD

**Issue by slax57** [marmelab/react-admin#9746]
**What you were expecting:**
To be able to run the command

```
npx jscodeshift ./src/ \
    --extensions=ts,tsx \
    --parser=tsx \
    --transform=./node_modules/ra-core/codemods/replace-Admin-history.ts
```

As described in the [upgrade guide](https://github.com/marmelab/react-admin/blob/next/docs/Upgrade.md#codemod-1).

**What happened instead:**
Got an error `ERROR Transform file /home/slax57/workspaces/my-admin5/node_modules/ra-core/codemods/replace-Admin-history.ts does not exist`

**Steps to reproduce:**
- Create a new RA project using RA v5 (`npm install react-admin@next`)
- Run the following command:

```
npx jscodeshift ./src/ \
    --extensions=ts,tsx \
    --parser=tsx \
    --transform=./node_modules/ra-core/codemods/replace-Admin-history.ts
```

**Environment**

* React-admin version: 5.0.0-alpha.1

**Comment by fzaninotto** [comment]
This is fixed in the beta.0
