### ISSUE TITLE
Duplicate entries in documentation search

### ISSUE THREAD

**Issue by Nitix** [marmelab/react-admin#9749]
**What you were expecting:**

Have a list of search result in the [documentation](https://marmelab.com/react-admin/documentation.html)

**What happened instead:**
Duplicate entries filling the search.

![image](https://github.com/marmelab/react-admin/assets/5849835/1f046915-3a3a-44ee-9076-67f74c035c8d)

Duplicate entries are two different links to the same documentation. The difference in the link is the extension. One link has the `.html` extension the other does not have extensions.

**Steps to reproduce:**
Search something on the documentation

**Environment**

* React-admin version: 4.16.13
* Last version that did not exhibit the issue (if applicable):
* React version: N/A
* Browser: Firefox 124

**Comment by fzaninotto** [comment]
Thanks for the report. There was a misconfiguration in the Algolia crawler. it should be fixed by now. Can you confirm it's working on your side?

**Comment by Nitix** [comment]
Yes it's fixed thanks.
