### ISSUE TITLE
When we use useRedirect hook to go back to a List Component, the pagination is reseted to page 1

### ISSUE THREAD

**Issue by Jer1605** [marmelab/react-admin#9777]
**What you were expecting:**
I expected that after viewing an order in the `ShowOrder` component and then using the back button (`handleBackToList` function) to return to the `ListOrders` component, the list should retain the same pagination state (same page number) as before viewing the order.

**What happened instead:**
When I return to the `ListOrders` component after viewing an order, the pagination resets to page 1 regardless of the previous page I was on.

**Steps to reproduce:**
1. Navigate to the `ListOrders` component.
2. Navigate to any page other than the first (e.g., page 5).
3. Click on any order to view its details in the `ShowOrder` component.
4. Use the back button implemented in `handleBackToList` function to return to the `ListOrders` component.
5. Observe that the list resets to page 1 instead of staying on the page previously visited (e.g., page 5).

**Related code:**
```javascript
import { useRedirect } from 'react-admin';

const ShowOrder = () => {
  const redirect = useRedirect();

  const handleBackToList = () => {
    redirect('list', 'orders');
  };

  // Remainder of component...
};

export default ShowOrder;
```

**Other information:**
It seems that adter the redirection to the list is processed, the component is rerendered two times (has I have two requests in the dataProvider getList method). The first time with the right value, the second time with the "page: 1" value.

![image](https://github.com/marmelab/react-admin/assets/22455472/20f0d299-c848-4e51-8e07-0985574c1850)

Maybe there's an issue with the strictmode or something ?

**Comment by khalifaelbanan** [comment]
@Jer1605 I'm currently onto the same issue, did you manage to resolve it ? thanks.
