### ISSUE TITLE
Bug in Translation in post edit page showing (post "some text here")

### ISSUE THREAD

**Issue by prajjwaljaiswal** [marmelab/react-admin#9784]
**What you were expecting:**

After Post "Text here"

![image](https://github.com/marmelab/react-admin/assets/47036042/e2375d1b-906f-4e99-acc0-d33e5268ad87)

**What happened instead:**

I think this is correct like this

After post Text here

**Steps to reproduce:**

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```
Please check in translation title code

https://stackblitz.com/edit/github-rwg7tb-ujwed4?file=src%2Fposts%2FPostEdit.tsx,src%2Fi18n%2Fen.ts,src%2Fposts%2FPostList.tsx

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
No news for some time, closing.
