### ISSUE TITLE
Dark mode become default upgrading react-admin package

### ISSUE THREAD

**Issue by botjaeger** [marmelab/react-admin#9785]
I'm using api-platform/admin and react-admin, upgrading both package, results to ignore my currently set theme, then it defaults to dark mode.

some features are also not working, like useGetIdentity doesn't return anything event tho I'm an authenticated user

from 
react-admin@4.16.10
to
react-admin@4.16.15

**Comment by fzaninotto** [comment]
Please follow the issue template.

**Comment by fzaninotto** [comment]
No news for some time, closing.
