### ISSUE TITLE
Following the "Save and add another" documentation leads to different submit behaviors when submitting on click or on pressing the "return" key

### ISSUE THREAD

**Issue by jstoeffler** [marmelab/react-admin#9803]
**What you were expecting:**

When implementing the "[Save and add another](https://marmelab.com/react-admin/Create.html#save-and-add-another)" feature, I would expect that submitting the form with the "return" key on my keyboard would have the same effect than if i click on the "Save" button.

**What happened instead:**

- When I click on the "Save" button, the expected behavior happens (the form is reset, my custom Notification is displayed)
- When I press the "return" key, the form is not reset, and the default notification is displayed

**Steps to reproduce:**

clone this sample app: https://github.com/jstoeffler/ra-save-and-add-another-bug

- npm install
- npm run dev
- go to http://localhost:5173/#/posts/create
- fill title
- click "Save and add another"
- => Form gets reset and "Awesome !" success notification is displayed ("Save button" behavior)
- fill title
- press return key
- => Form doesn't get reset, and "Element created" info notification is displayed. (default behavior)

**Related code:**

* A link to a GitHub repo with the minimal codebase to reproduce the issue

Sample App: https://github.com/jstoeffler/ra-save-and-add-another-bug
It's the basic template created using `npm init react-admin` and just a "CreatePost" "create" action that looks like:

```
import { Create, SimpleForm, TextInput, required, SaveButton, Toolbar, useNotify } from "react-admin";
import { useFormContext } from "react-hook-form";

const BatchCreateToolbar = () => {
  const notify = useNotify();
  const { reset } = useFormContext();

  return (
    <Toolbar>
      <SaveButton
        type="button"
        label="Save and Add Another"
        variant="text"
        mutationOptions={{
          onSuccess: () => {
            reset();
            window.scrollTo(0, 0);
            notify("Awesome !", {
              type: "success",
              messageArgs: { smart_count: 1 },
            });
          },
        }}
      />
    </Toolbar>
  );
};


export const CreatePost = () => {
  return (
    <Create redirect={false}>
      <SimpleForm toolbar={<BatchCreateToolbar/>} >
        <TextInput source="title" />
        {/* When adding this, submit with return key doesnt work */}
        {/*<TextInput source="content" />*/}
      </SimpleForm>
    </Create>
  );
};
```

**Other information:**

I tried using FormContext but it's not created, it's already been discussed in https://github.com/marmelab/react-admin/issues/7717

Also interestingly, it seems submitting with the return key only works when there's one field, is this expected? It would be nice to be able to submit forms with the keyboard, with return or command-return.

**Environment**

* React-admin version: 4.12.0
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 8.2.0
* Browser: Chrome latest
* Stack trace (in case of a JS error): N/A

**Comment by djhi** [comment]
Hi, if you don't need multiple buttons, I suggest you put your `mutationOptions` on the `<Create>` element directly. Indeed, passing `mutationOptions` on the button will disable the submission on enter. This is because in this case, it will call the `save` function directly by using the `SaveContext`.
