### ISSUE TITLE
<ListContextProvider> <Datagrid>  causes Datagrid to lose scroll Y position

### ISSUE THREAD

**Issue by rjjan** [marmelab/react-admin#9835]
Hi all,
I probably found the root cause but don't know how to solve this.  Appreciate suggestions from you.

I fetch data myself from cloud blob to Datagrid.  Doing something like the example described here.
https://marmelab.com/react-admin/Datagrid.html#standalone-usage

const listContext = useList({ data: blobData, isLoading: isLoading });
<ListContextProvider value={listContext}>
       <Datagrid> 
            ...
       </Datagrid>
</ListContextProvider>

Issue:
when I click the Datagrid row, navigate to Show page, then back. The Datagrid's scroll Y position will be reset to 0.  However, I expected the Datagrid to "remember" the scroll Y position. 

Cause:
It's because listContext = useList({ data: blobData, isLoading: isLoading });
it will transit from zero data to blobData, so the Datagrid will start from zero data to whole blobData.

Help:
The blobData is fetched inside useEffect(...,[user_id]) 
I use useEffect() because I must depend on user_id available.

To avoid the "Datagrid transition" I plan to completely load the blobData, then call
    listContext = useList({ data: blobData, isLoading: isLoading });

However, useList is a hook and cannot be inside useEffect.

Any suggestion is much appreciated!

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
