### ISSUE TITLE
Customising the message that appears after the delete operation in DeleteWithConfirmButton

### ISSUE THREAD

**Issue by ethembynkr** [marmelab/react-admin#9837]
**Is your feature request related to a problem? Please describe.**
I want to customise the notification message that appears to the DeleteWithConfirmButton component after the delete operation is successful. (Only for some pages.) I can give the message using notify in the onSuccess method of the MutationOptions prop, but this time confirm is not turned off.

**Describe the solution you'd like**
Is it possible to add a new prop to customise the notify message that appears after the delete operation is successful in the DeleteWithConfirmButton component?

```
{ onSuccessMessage =  'ra.notification.deleted' } = props;

onSuccess: () => {
  setOpen(false);
  notify(onSuccessMessage, {
    type: 'info',
    messageArgs: { smart_count: 1 },
    undoable: mutationMode === 'undoable',
  });
  unselect([record.id]);
  redirect(redirectTo, resource);
}
```

Or you can get props named handleSuccess, handleError and call them in the default onSuccess and onError methods in useDeleteWithConfirmController.

```
{ handleSuccess, handleError } = props;

onSuccess: () => {
  ...
 if (typeof handleSuccess === 'function') {
  handleSuccess();
 }
},
onError: () => {
  ...
 if (typeof handleError === 'function') {
  handleError();
 }
}

```

**Describe alternatives you've considered**
I can rewrite DeleteWithConfirmButton and useDeleteWithConfirmController components but it will be very costly for me.

**Additional context**
![image](https://github.com/marmelab/react-admin/assets/20007016/ad23ccbb-302f-401f-8d2d-486cb95c7026)

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. 

You can already override the success side effects with the `mutationOptions.onSuccess` prop, as in the screenshot you pasted in the "Additional context" section. This is also the way to customize the notification text in the Edit view (see https://marmelab.com/react-admin/Create.html#changing-the-notification-message). If this option doesn't work, please elaborate on the reproduction. 

We won't offer an additional prop to do something you can already do with `mutationOptions`.

**Comment by ethembynkr** [comment]
Hi, thank for feedback.

I can customise the notification text with mutationOptions in DeleteWithConfirmButton component, but in this case the confirm dialog does not close. 

I made a demo that shows this case. Please select a record on the post page and delete it. You will see that the Confirm dialogue does not close.

[You can access the demo here](https://codesandbox.io/p/devbox/frosty-platform-s7gh42?file=%2Fsrc%2Fposts%2FPostList.tsx%3A119%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw12s8hi00073b6ib0gxfyy8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw12s8hi00023b6i0rftp5u8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw12s8hi00043b6isw1hjp5a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw12s8hi00063b6ir6p8gndo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw12s8hi00023b6i0rftp5u8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw12s8hh00013b6iwow8ugzh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clw13bb7g00023b6iq6hovq66%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A119%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A119%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fposts%252FPostList.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw12s8hi00023b6i0rftp5u8%2522%252C%2522activeTabId%2522%253A%2522clw13bb7g00023b6iq6hovq66%2522%257D%252C%2522clw12s8hi00063b6ir6p8gndo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw12s8hi00053b6ifb27q0jv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%252F%2523%252Fposts%2522%257D%255D%252C%2522id%2522%253A%2522clw12s8hi00063b6ir6p8gndo%2522%252C%2522activeTabId%2522%253A%2522clw12s8hi00053b6ifb27q0jv%2522%257D%252C%2522clw12s8hi00043b6isw1hjp5a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw12s8hi00033b6iba3n9v6o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clw12s8hi00043b6isw1hjp5a%2522%252C%2522activeTabId%2522%253A%2522clw12s8hi00033b6iba3n9v6o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)

<img width="514" alt="image" src="https://github.com/marmelab/react-admin/assets/20007016/66d6b14a-ab6d-4465-8e86-e66c3dc3f647">

**Comment by fzaninotto** [comment]
Understood, thanks for the reproduction. 

You're right: there is no easy way to do what you ask without rewriting significant parts of the controller. So we need to expose an option to let users override the message (something like `successNotification`) in `useDeleteWithConfirmController` and the associated buttons. 

I'm marking this as an enhancement. We'll welcome a PR implementing this feature.

**Comment by ethembynkr** [comment]
@fzaninotto I opened a PR for this feature. Can you review it?

https://github.com/marmelab/react-admin/pull/9868

**Comment by slax57** [comment]
Implemented in https://github.com/marmelab/react-admin/pull/9868
