### ISSUE TITLE
How do 2 menu of one resource with different filter list

### ISSUE THREAD

**Issue by shurshilov** [marmelab/react-admin#9859]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(https://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`) or the react-admin Discord Server(https://discord.gg/GeZF9sqh3N). Thanks! 😁.
How do 2 menu of one resource with different filter list
![image](https://github.com/marmelab/react-admin/assets/11828278/2b9a0c31-f02b-40f1-96e1-9c20e33b9c9d)
![image](https://github.com/marmelab/react-admin/assets/11828278/46a50bd6-d4ef-4907-813a-2bd08818daec)
red chains always empty...

**Comment by fzaninotto** [comment]
Invalid issue - please follow the issue template.

**Comment by shurshilov** [comment]
I am not have dicsord
I am not have stackoverflow
very good support...
