### ISSUE TITLE
[v5 β1] cjs version of react-admin is broken as it imports an esm package

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#9869]
**What you were expecting:**

I expect my project to build without errors after upgrading from v5 alpha to v5 beta

**What happened instead:**

There is an error when importing ra-core package in cjs mode

**Steps to reproduce:**

Goto https://www.npmjs.com/package/ra-core/v/5.0.0-beta.1?activeTab=code
And then go to the file /ra-core/dist/cjs/dataProvider/fetch.js

You will find `var query_string_1 = __importDefault(require("query-string"));` of an esm package

**Related code:**

This regression is introduced from https://github.com/marmelab/react-admin/pull/9812 This package is pure esm now

**Other information:**

We can revert this change or find an alternative package to do query string parsing

**Environment**

* React-admin version: 5.0.0-beta.1
* Last version that did not exhibit the issue (if applicable): 5.0.0-beta.0
* React version: 18.3
* Browser: Safari
* Stack trace (in case of a JS error):
Error: require() of ES Module /Users/home/.yarn/berry/cache/query-string-npm-9.0.0-3f8486c724-10c0.zip/node_modules/query-string/index.js from /Users/home/Developer/frontend-base/.yarn/__virtual__/ra-core-virtual-8c88f77e9d/3/.yarn/berry/cache/ra-core-npm-5.0.0-beta.1-6689ec2614-10c0.zip/node_modules/ra-core/dist/cjs/dataProvider/fetch.js not supported.
Instead change the require of index.js in /Users/home/Developer/frontend-base/.yarn/__virtual__/ra-core-virtual-8c88f77e9d/3/.yarn/berry/cache/ra-core-npm-5.0.0-beta.1-6689ec2614-10c0.zip/node_modules/ra-core/dist/cjs/dataProvider/fetch.js to a dynamic import() which is available in all CommonJS modules.

**Comment by djhi** [comment]
Hi, thanks for the report. What bundler do you use?

**Comment by smeng9** [comment]
Hi @djhi I use vite and vitest, the issue happens in vitest

**Comment by fzaninotto** [comment]
Fixed by #9871
