### ISSUE TITLE
V5 beta: duplicated queries on mount

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#9896]
**What you were expecting:**
`useGetOne` and `useGetList` only trigger one call to the API. 

**What happened instead:**
They call the API twice

**Steps to reproduce:**
1. Launch the simple example
2. Go to a comment edit page
3. The `getOne` and `getList` calls are doubled. 

Note that the duplication disappears when I remove StrictMode. However, the example is using React 18, so this isn't caused by [changes in strict mode in React 19](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#strict-mode-improvements). When using react-admin v4 with React 18, the bug doesn't appear, so this a regression introduced by v5.

<img width="995" alt="image" src="https://github.com/marmelab/react-admin/assets/99944/2922a0f9-c714-4184-8f4f-c5d35152725f">

**Related code:**

https://stackblitz.com/github/marmelab/react-admin/tree/next/examples/simple

**Environment**

* React-admin version: 5.0.0-beta.3
* Last version that did not exhibit the issue (if applicable): 4.16
* React version: 18
* Browser: Chrome

**Comment by djhi** [comment]
It looks like this is the expected behavior when combining react 18 strict mode **and** query cancellation. See https://github.com/TanStack/query/issues/3633#issuecomment-1133581032

**Comment by fzaninotto** [comment]
I can confirm that by removing the `signal` in `useGetOne`, the `getOne` request is no longer duplicated. But this is very surprising: the demo uses `ra-data-fakerest`, which doesn't implement the abortSignal. 

All in all, it means that all apps, whatever their data provider, will see duplicated queries in strict mode by default. The developer experience is worse in general, for an end user benefit that only occurs in a minority of cases. 

We need to disable the abortsignal by default, and find a way to make it an opt-in feature.
