### ISSUE TITLE
Removing an item from an ArrayInput with primitive values and validation removes more than one input

### ISSUE THREAD

**Issue by k4v1cs** [marmelab/react-admin#9905]
**What you were expecting:**
Removing an item should only remove that one item

**What happened instead:**
When empty inputs are present removing an item removes other items as well

**Steps to reproduce:**
Have an ArrayInput with string values. The array and values are validated as required.
Sandbox: https://codesandbox.io/p/devbox/arrayinput-remove-item-issue-sx4zky?file=%2Fsrc%2FApp.tsx%3A25%2C26&workspaceId=03aee9bf-4bf8-480d-97ef-9f80cfaf967b

Steps 1:

1. Open edit view
2. Add a new item, leave it empty
3. Try to save the form, validation errors will appear
4. Click on the remove button of the first item

Expected result:
5. Only the first item should be removed
Actual result:
5. The first and the last, invalid and empty item was removed, the validation error from the whole array still remained

https://github.com/marmelab/react-admin/assets/4885562/624fb9fb-4b24-4d56-a7ac-3fabbefb9676

Steps 2:
1. Open edit view
2. Add a new item, leave it empty
3. Remove the value of the second item
4. Click on the remove button of the first item

Expected result:
5. Only the first item should be removed

Actual result:
5. One empty input the third item remained, the other empty input and fourth item was also removed 

https://github.com/marmelab/react-admin/assets/4885562/1b0e9877-124d-4c36-a805-1b0078b0a9ca

**Related code:**

```
<SimpleForm>
      <ArrayInput source="names" validate={required()}>
        <SimpleFormIterator>
          <TextInput source="" validate={required()} />
        </SimpleFormIterator>
      </ArrayInput>
</SimpleForm>
```

**Environment**

* React-admin version: 4.16.9
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
I haven't tried reproduction yet, but keep in mind that using ArrayInput for scalar values is an edge case in which we won't spend much time. We recommend using AutocompleteArrayInput or SelectArrayInput instead.

**Comment by slax57** [comment]
reproduced, thanks
