### ISSUE TITLE
Incorrectly parse of id with basename name same as resource name

### ISSUE THREAD

**Issue by Netail** [marmelab/react-admin#9906]
**What you were expecting:**
When a basename has been set in the `<Admin>` component and one of the resources has the same name as the basename, it should correctly parse the id for fetching getOne.

`/sponsored-recipes/sponsored-recipes/1` should fetch with the following: { resource: "sponsored-recipes", id: "1" }

**What happened instead:**
Instead it uses the resource name as id for fetching getOne.

`/sponsored-recipes/sponsored-recipes/1` will try to fetch with the following: { resource: "sponsored-recipes", id: "sponsored-recipes" }

**Steps to reproduce:**
1. Set a basepath with the same name as resource
2. Open a detail page or even on list page already
3. Check console 

**Related code:**
Haven't got time for a example yet, can add later if needed

**Environment**

* React-admin version: 4.16.18
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Yes, please add a reproducible example.

**Comment by fzaninotto** [comment]
No news for some time, closing.
