### ISSUE TITLE
V5 beta: List pages are not showing data and display an error notification

### ISSUE THREAD

**Issue by armandosg** [marmelab/react-admin#9909]
**What you were expecting:**

List pages load correctly without errors

**What happened instead:**

List pages are not showing data and display an error notification

**Steps to reproduce:**

1. Run `npm run dev`
2. Open the app the in the browser
3. The error should show after page is loaded
<img width="1440" alt="image" src="https://github.com/marmelab/react-admin/assets/13240476/7027d5d7-f750-47b5-9709-7955e58bf2b2">

**Related code:**

I followed the nextjs tutorial and modified the AdminApp component to use more than one data provider.

Here is the full code: [https://github.com/armandosg/react-admin-v5](https://github.com/armandosg/react-admin-v5)

**Other information:**

It looks like the data provider is receiving an undefined `params` object only when using the `combineDataProviders` function. If you remove the `combineDataProviders` function and use only one data provider the error is not showing and pages load correctly.

**Environment**

* React-admin version: 5.0.0-beta.3
* Last version that did not exhibit the issue (if applicable): 4.16.18
* React version: 18
* Browser: Chrome
* Stack trace (in case of a JS error):

<img width="571" alt="image" src="https://github.com/marmelab/react-admin/assets/13240476/65222945-cb93-4d0e-8a9e-29e03ded0b5f">

**Comment by fzaninotto** [comment]
Fixed by #9910
