### ISSUE TITLE
Add custom label prop to SelectColumnsButton

### ISSUE THREAD

**Issue by Revarh** [marmelab/react-admin#9914]
**Is your feature request related to a problem? Please describe.**
Not a problem but in my design case I'd rather hide the label of SelectColumnsButton

**Describe the solution you'd like**
Add a label prop to customize it

**Describe alternatives you've considered**
None.

**Additional context**
Thank you :)

**Comment by fzaninotto** [comment]
You can already customize it via the `ra.action.select_columns` translation message if you use i18N. If that's not enough, feel free to open a PR against the `next` branch to add support for a `label` prop. 

I'm marking this as an enhancement request. We'll close in a few weeks it if it doesn't get traction from the community.

**Comment by Revarh** [comment]
Hi !
Thank you, I did not thing of that. It is working great :)

**Comment by fzaninotto** [comment]
No PR proposed for this feature, so I'm closing the issue. Feel free to open a PR implementing it if you need it.
