### ISSUE TITLE
Le chargement du module a été bloqué en raison d'un type MIME interdit ("text/html")

### ISSUE THREAD

**Issue by AntoineRionde** [marmelab/react-admin#9927]
**What you were expecting:**
Je souhaiterai accéder à ma route /notification/history.

**What happened instead:**
Quand je suis en mode intégration/prod au niveau Docker, j'ai un message d'erreur ; 
Le chargement du module a été bloqué en raison d'un type MIME interdit ("text/html")
Pourtant mes pages qui sont sous la route /admin/* fonctionnent normalement.

Voici ce qui est affiché dans ma console : 
![Annotation 2024-06-17 172125](https://github.com/marmelab/react-admin/assets/92793361/b82b0df1-2da4-47ea-949f-988fba5d29f7)

**Steps to reproduce:**
J'ai trois routes principaux : une qui se nomme /notification/history, une autre /notification/:id et la dernière qui regroupe toutes les routes d'administration regroupées sous /admin/*
Quand je veux accéder à une route autre que /admin/*, j'ai l'erreur cité plus haut.

**Related code:**
![Annotation 2024-06-18 102733](https://github.com/marmelab/react-admin/assets/92793361/e805e017-fd3d-44e3-8cdb-34ca2dff734e)

![Annotation 2024-06-18 103046](https://github.com/marmelab/react-admin/assets/92793361/c65e67df-7780-4fac-b781-d665bd823c96)

**Other information:**
Voici le visuel de "chargement" à l'infini que me provoque cette erreur : 
![image](https://github.com/marmelab/react-admin/assets/92793361/523a4881-a940-4296-a54d-55a4a77a4dae)

**Environment**

* React-admin version: 4.16.18
* React version: 18.3.1
* Browser: Firefox / Chrome / Edge
* Stack trace (in case of a JS error): Le chargement du module à l’adresse « http://site+port/notification/assets/index-bd100f28.js » a été bloqué en raison d’un type MIME interdit (« text/html »).

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by slax57** [comment]
Possible lead: you're missing a [basename](https://marmelab.com/react-admin/Admin.html#basename)
