### ISSUE TITLE
Disabled TextInput in SimpleForm returns undefined

### ISSUE THREAD

**Issue by Netail** [marmelab/react-admin#9929]
**What you were expecting:**
Disabled TextInput value is passes initial value back

**What happened instead:**
Disabled TextInput value is passed back as undefined

**Steps to reproduce:**
Have a SimpleForm with a TextInput which has a disabled field for the edit page, which gets preloaded with an initial value, when saving it returns undefined

```ts
export const Edit = (): JSX.Element => {
  const { id } = useParams();
  return (
    <Edit id={id}>
      <SimpleForm warnWhenUnsavedChanges>
        <TextInput
          label="Ingredient Name"
          source="name"
          disabled
        />
      </SimpleForm>
    </Edit>
  )
}
```

**Environment**

* React-admin version: 4.16.19
* React version: 18.2.0
* Browser: Chrome
* @mui/material: 5.15.19

**Comment by Netail** [comment]
Not sure if this is default behaviour, to set disabled inputs to undefined, but something you want to use them as a display

**Comment by fzaninotto** [comment]
From https://marmelab.com/react-admin/Inputs.html#disabled:

![image](https://github.com/marmelab/react-admin/assets/99944/240de303-5173-4fad-9580-0ffa9956c9da)

**Comment by Netail** [comment]
Oh readOnly, sorry missed that completely
