### ISSUE TITLE
loosing  custom piece of state in query parameters for list view URL when setFilter is called

### ISSUE THREAD

**Issue by Nilegfx** [marmelab/react-admin#9932]
**What you were expecting:**
keeping extra/custom query params in the list view URL. [briefly discussed](https://discord.com/channels/830711057643208724/1022443113391853578/threads/1250066264915836929) in our discord community channel. 
as an example, `/posts?`extrakey=extra-value` should remain in the url after setting filters either by the direct UI components or through setFilter from `useListParams` hook. 

**What happened instead:**
when setting a filter the `extrakey` query param is dropped. this is due to a [design decision](https://github.com/marmelab/react-admin/blob/a655d60551c293eb8c74a58f59d99d6efaafecef/packages/ra-core/src/controller/list/useListParams.ts#L304) which can be changed without any impact on any other functionality of the library.

**Steps to reproduce:**
create any dummy list (e.g) 

**Related code:**
https://stackblitz.com/edit/vitest-dev-vitest-rag3eb?file=src%2Fmain.jsx

```
insert short code snippets here
```

**Other information:**
I am creating this issue to be able to create relevant PR (which should be simple, short and straight forward by removing the lines where it picks react-admin-related params only and open it for all params

```diff
- import pickBy from 'lodash/pickBy';


- export const validQueryParams = [
-     'page',
-     'perPage',
-     'sort',
-     'order',
-     'filter',
-     'displayedFilters',
-  ];

export const parseQueryFromLocation = ({ search }): Partial<ListParams> => {
-    const query = pickBy(
-        parse(search),
-        (v, k) => validQueryParams.indexOf(k) !== -1
-    );

+    const query = parse(search);

    parseObject(query, 'filter');
    parseObject(query, 'displayedFilters');
    return query;
};
```
 
@slax57 the above proposed code change I already tested in my local fork of react-admin, it works pretty fine without the need to change any tests (all tests and build are passes). I'll open PR right after this issue and link it here. any further recommendation?

**Environment**

* React-admin version: 4
* React version: 18
* Browser: all
* Stack trace (in case of a JS error): none

**Comment by slax57** [comment]
Both @fzaninotto and I approved, so you can go ahead! :+1: 
Thanks! :slightly_smiling_face:

**Comment by slax57** [comment]
Implemented in https://github.com/marmelab/react-admin/pull/9933
