### ISSUE TITLE
Query options not forwarded to getMany in ReferenceArrayInput

### ISSUE THREAD

**Issue by bendenoz** [marmelab/react-admin#9953]
**What you were expecting:**

When passing custom query options to `<ReferenceArrayInput ... />`, I expected them to be passed to all the react-query queries involved.
Specifically, we are trying to optimize some queries using custom staleTime combined with meta, to keep the server load minimal

**What happened instead:**

Instead, staleTime is only used in the getList query, but not in the getMany(Aggregate) query. 
Therefore the cache is not used and the query is set to the backend everytime

Note the meta prop is correctly included in the query key though.

**Steps to reproduce:**

It's easier to analyse with the ReactQueryDevtools installed

setup a ResourceEdit component with ReferenceArrayInput and custom queryOptions

```typescript
                    <ReferenceArrayInput
                      source="source"
                      reference="resource"
                      queryOptions={{
                        meta: { cache: true },
                        staleTime: 60000,
                      }}
                    />
```

Navigate once to the component, the getMany query is fetched once

Go back to dashboard / list

Return the the same ResourceEdit within 60 seconds, the getMany query should not be sent to the server

**Related code:**

See this patch which addresses the issue

```diff
--- a/packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
+++ b/packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
@@ -68,6 +68,7 @@ export const useReferenceArrayInputController = <
         },
         {
             enabled: value != null && value.length > 0,
+            ...otherQueryOptions,
         }
     );
 
```

**Other information:**

Note that that there is no issue with `<ReferenceArrayField />` , the useReferenceArrayFieldController code does pass otherQueryOptions to getManyAggregate

**Environment**

* React-admin version: 4.16
* Last version that did not exhibit the issue (if applicable): N/A
* React version: ^18.2.0
* Browser: Chrome latest

**Comment by bendenoz** [comment]
Thanks! PR in #9954

**Comment by slax57** [comment]
Fixed by https://github.com/marmelab/react-admin/pull/9954
