### ISSUE TITLE
SimpleShowLayout does not pass resource to Labeled Component, translation fails

### ISSUE THREAD

**Issue by glauff** [marmelab/react-admin#9965]
**What you were expecting:**
When nesting Field Components into a SimpleShowLayout the Label should be correctly translated.
**What happened instead:**
After migration to react-admin v5 the Fields in a SimpleShow Layout have not the correct translation
**Steps to reproduce:**
Just nest Fields into a SimpleShowLayout with a translation of fields to a resource in place
**Related code:**

SimpleShowLayout is not passing resource to Labeled
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/SimpleShowLayout.tsx
Labeled ist only using the passed resource prop and not also the ResourceContext
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/Labeled.tsx

**Environment**

* React-admin version: 5.0.2
* Last version that did not exhibit the issue (if applicable): 4.x.x
* React version: 18
* Browser: Chrome

**Comment by fzaninotto** [comment]
I'm not sure what you mean by "nesting fields". Can you please add a reproduction based on the simple example StackBlitz? 

https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=README.md

**Comment by glauff** [comment]
Sure, here you go
https://stackblitz.com/edit/github-wuzwwv

I'v modified the posts list to display the PostShow View on rowClick

PostShowView now contains just a SimpleShowLayout with a TextField with a source prop set to "notifications"

The translation for "notifications" in "en" is "Notifications recipients", but only "Notifications" is shown because resource context is missing

Hope this clarifies my issue.

**Comment by fzaninotto** [comment]
Thanks for the repro. I can confirm the bug. 

According to my initial analysis, it doesn't come from a Resource Context problem, but from a logic problem in `useTranslateLabel` or `getFieldTranslationArgs`.
