### ISSUE TITLE
Remix integration does not work

### ISSUE THREAD

**Issue by keita-makino** [marmelab/react-admin#9974]
**What you were expecting:**
Instructions for remix integration will work.

**What happened instead:**
Getting an error:
```cmd
__vite_ssr_import_2__.default is not a function
```

**Steps to reproduce:**
If following the tutorial,

1. The `remix.config.js` file does not exist while the tutorial tells you to edit it, so I created it.
2. After creating `routes/admin.$.tsx` and `styles/admin.css` and copy-pasting the contents, running the dev server by `npm run dev` and navigating to the root webpage will display the error.

**Related code:**
The code is here: https://github.com/keita-makino/react-admin-issue-remix

**Other information:**

**Environment**

* React-admin version: 5.0.3
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 18.2.0
* Browser: Brave 1.67.123
* Stack trace (in case of a JS error):
```
at eval (C:/Users/apricot/src/react-admin-issue/my-remix-app/app/routes/admin.$.tsx:15:51)
at async instantiateModule (file:///C:/Users/apricot/src/react-admin-issue/my-remix-app/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53451:5
```

**Comment by fzaninotto** [comment]
Reproduced, thanks for the report. This is due to Remix switching to Vite.js, we must adapt our documentation. In the meantime, choose the [Classic Remix Compiler](https://remix.run/docs/en/main/guides/vite#classic-remix-compiler-vs-remix-vite).
