### ISSUE TITLE
Autocomplete Input uses readOnlyProp as disabled

### ISSUE THREAD

**Issue by igor-adzz** [marmelab/react-admin#9981]
**What you were expecting:**
I'm expecting to use AutocompleteInput with readOnly prop and close this input for edit.

**What happened instead:**
Instead of this AutocompleteInput uses disabled

**Related code:**
![image](https://github.com/marmelab/react-admin/assets/127742125/51c56a5e-17fa-4a57-893d-8141dc771de6)

* React-admin version: 5.0.3

**Comment by slax57** [comment]
Thank you for your report.

This code was introduced as a way to solve an issue in the way `react-hook-form` deals with `disabled` inputs.
See https://github.com/marmelab/react-admin/pull/9656 for more info.

If my recollection is good, MUI's `Autocomplete` does not have a `readOnly` prop. Hence, we had to hook it to the `disabled` prop.

Can you elaborate on why this is causing an issue for you?
Thanks.

**Comment by slax57** [comment]
Alternatively, you can also try passing props directly to the underlying `TextField`.

For example:

```tsx
                <AutocompleteInput
                    optionText="name"
                    fullWidth
                    TextFieldProps={{ InputProps: { disabled: true } }}
                />
```

**Comment by fzaninotto** [comment]
No news for some time, closing.
