### ISSUE TITLE
Exporting CSV from DatagridConfigurable with modified Columns

### ISSUE THREAD

**Issue by aeberhart** [marmelab/react-admin#9986]
**Is your feature request related to a problem? Please describe.**

Consider the following DatagridConfigurable

```
export const PostList = () => (
  <List>
    <DatagridConfigurable>
      <TextField source="id" />
      <TextField source="title" />
      <TextField source="content" />
    </DatagridConfigurable>
  </List >
)
```

The export takes sorting and filtering into account which is great. However, if I use "configurable" and change the column projection order or omit columns, the CSV export does not change and the original columns (id, title, content) is exported.

**Describe the solution you'd like**
Configuring columns should affect the export in the same way as filtering and sorting does. Specifically, if I omit column id and change the projection order to "content, title", the CSV export should have only columns "content, title".

**Describe alternatives you've considered**
Considered a custom export function

**Additional context**
![image](https://github.com/marmelab/react-admin/assets/61732435/285dbf88-2770-4217-97c4-5c0f0a003f27)

**Comment by fzaninotto** [comment]
Thanks for your report. 

The default export function turns the raw JSON from the API into a CSV file, without any consideration for the datagrid columns. If you need the CSV to use a different format, you have to pass your own `exporter` function, as explained in the documentation. 

https://marmelab.com/react-admin/List.html#exporter 

Modifying the default exporter to take the DatagridConfigurable preferences into account is not in the scope of react-admin, so I'm closing this issue.
