### ISSUE TITLE
Standalone Datagrid fails "DatagridRow can only be used within a ResourceContext or be passed a resource prop" after v4 to v5 upgrade

### ISSUE THREAD

**Issue by andrewlorenz** [marmelab/react-admin#9990]
I am attempting an upgrade to v5.0.3, on an application that is fully functional at v4.16.
I have found that a use of a "standalone Datagrid" no longer works, and rather fails with message "DatagridRow can only be used within a ResourceContext or be passed a resource prop".
Referring to the documentation, I can see that there has been no change to the documentation between v4 and v5 apart from passing boolean isPending at v4 and isLoading at v5, so I have modified this.
```
      <Datagrid
        data={attendanceData?.users || []}
        total={attendanceData?.users?.length || 0}
        isLoading={busy}
        sort={{ field: 'usr_name', order: 'ASC' }}
        bulkActionButtons={false}
      >
```
I have consulted the upgrade notes for v5 and none of the bullets applies to this use of Datagrid.
This is where the error gets thrown in react-admin:
```
var DatagridRow = import_react51.default.forwardRef(function(props, ref) {
 ...
  var context = useDatagridContext();
  var translate = useTranslate();
  var record = useRecordContext(props);
  if (!record) {
    throw new Error("DatagridRow can only be used within a RecordContext or be passed a record prop");
  }
  var resource = useResourceContext(props);
  if (!resource) {
    throw new Error("DatagridRow can only be used within a ResourceContext or be passed a resource prop");
  }
```

**Comment by fzaninotto** [comment]
Hi Andrew,

You're right, we're missing an update in the documentation and in the upgrade guide. In your case, you must provide a resource parop, as explained by the error message:

```diff
      <Datagrid
        data={attendanceData?.users || []}
        total={attendanceData?.users?.length || 0}
        isLoading={busy}
        sort={{ field: 'usr_name', order: 'ASC' }}
        bulkActionButtons={false}
+       resource="attendance"
      >
```

I'm marking this as a documentation issue. Feel free to open a PR to fix it.

**Comment by andrewlorenz** [comment]
Thanks, that was an awesomely fast response!  I have added a resource prop and yes it works fine.

But - this is Datagrid in "standalone" usage, and all necessary data is provided by the data/total props?  So I'm left wondering why a resource prop would be necessary.  As a test, I passed it a few different resource strings, and in all cases the datagrid rendered the data (as passed to it via the data prop) absolutely fine, even including when I tried this crazy literal:
```
        resource="a resource that doesnt even exist!"
```
So this doesn't feel like a mere documentation fix - Datagrid appears to be insisting on a prop that it doesn't actually need or use when its being driven by the data prop ?

**Comment by fzaninotto** [comment]
The resource name is necessary to craft the keys for the column names. For instance, if you have a datagrid for the resource "products" that contains a field with source "price", the name of the corresponding column will be "resources.products.fields.price". This lets you translate the column names in the i18nProvider. 

This isn't a new thing: the resource was always necessary. In 4.0, without setting the resource, the column name would be "resources.undefined.fields.price". This may not have been a problem for you if you don't use i18n, as react-admin "humanizes" the column name to "Price" in this case. It was nonetheless a bug.
